### ISSUE TITLE
Support multiple Vulkan logical devices in one program

### ISSUE THREAD

**Issue by snowfoxer** [baldurk/renderdoc#1002]
## Description

my two gpus are GeForce GTX 1060 and Intel(R) HD Graphics 530.
When creating logical driver for the intel gpu, the segfault occured.

## Repro steps

When I use gdb  to try to get the error, It doesn't display;
But when I want to check the pipeline by renderdoc, It occured.

## Environment

* RenderDoc build: v1.0, commit 5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c
* Operating System: Windows 10
* API:Vulkan

.

**Comment by baldurk** [comment]
Can you clarify, are you using windows or linux? gdb and segfault implies linux, but you listed Windows 10.

Either way, can you give more details about what exactly you're doing - are you creating a logical device for *both* physical GPUs? That's currently not supported in RenderDoc. If you're skipping the nvidia GPU and only creating one for the Intel GPU that should work - when exactly does the crash happen? Can you get a callstack?

**Comment by snowfoxer** [comment]
I use tdm-gcc + gdb in windows10,  when I call vkCreateDevice for the intel gpu after having created the nvidia gpu logical device, the error  occured. 
And I test to only to run the same pass for the intel gpu, everything is ok.

**Comment by snowfoxer** [comment]
Also I have a question. As you say :
> creating a logical device for both physical GPUs? That's currently not supported in RenderDoc.

Do you means that we can creating a logical device for both two physical device?
But the function 
> VKAPI_ATTR VkResult VKAPI_CALL vkCreateDevice(
        VkPhysicalDevice                            physicalDevice,
        const VkDeviceCreateInfo*                   pCreateInfo,
        const VkAllocationCallbacks*                pAllocator,
        VkDevice*                                   pDevice
);

can only accept one physical device.

**Comment by baldurk** [comment]
I mean that it's legal in vulkan to create two logical devices for separate physical devices, but that is not something that RenderDoc supports currently - so crashes are definitely expected.

**Comment by snowfoxer** [comment]
Thanks. I will skip the second gpu logical driver create when test in renderdoc.
