### ISSUE TITLE
Official RenderDoc Linux builds don't include 32-bit version of librenderdoc.so

### ISSUE THREAD

**Issue by jozefkucia** [baldurk/renderdoc#1003]
It would be nice if the 32-bit version of librenderdoc.so could be included. Ideally, renderdoc would set LD_LIBRARY_PATH to paths of 32-bit and 64-bit librenderdoc.so.

**Comment by doitsujin** [comment]
Agreed, this would be useful for DXVK development as well.

**Comment by baldurk** [comment]
I don't officially support 32-bit architectures on linux, and I don't currently have any plans to change that.

The code may work since there's 32-bit support on windows, but it's not supported or maintained and it won't be included in any builds.
