### ISSUE TITLE
GLES applications that use GLX trigger incorrect warning

### ISSUE THREAD

**Issue by dos1** [baldurk/renderdoc#1009]
## Description

This is a very minor, almost cosmetic issue: when launching an application that requests OpenGL ES profile using GLX (as opposed to EGL), RenderDoc shows the incorrect warning on top of the application window.

```
OpenGL. F12, PrtScrn to capture. Frame: 1777, 16.66 ms (16.35 .. 17.11) (60 FPS)
0 Captures saved.
WARNING: Non-core context in use. Compatibility profile not supported.
```

After playing with it a bit it seems like all the functionality of RenderDoc that should work with GLES works just fine, it's just the incorrect warning.

## Environment

* RenderDoc build: v1.0
* Operating System: Arch Linux
* API: OpenGL ES with GLX

**Comment by baldurk** [comment]
Can you explain what you mean by using GLX as opposed to EGL? My understanding was that EGL was used to initialise OpenGL ES, and GLX was used for proper OpenGL. The message you're seeing happens when a context is created as proper OpenGL but without the core profile flag.

**Comment by dos1** [comment]
You can initialise OpenGL ES profile using GLX by setting the GLX_CONTEXT_ES_PROFILE_BIT_EXT flag instead of GLX_CONTEXT_CORE_PROFILE_BIT_ARB. Application reports that it got a proper ES 3.1 profile, while RenderDoc thinks it's OpenGL and checks for core profile flag, which doesn't make any sense in such case, as obviously ES profile won't have core profile flag set :)

Also, AFAIK you can use EGL to initialize OpenGL profile too. I haven't tested such case though.

**Comment by baldurk** [comment]
Ouch, what a mess :disappointed:. I guess we need to check for this flag then and go down the GLES path.

**Comment by baldurk** [comment]
I've refactored the GL hooking and this back-door GLES profile bit should now be supported and captured/replayed as GLES.
