### ISSUE TITLE
Oculus Mobile (VRAPI) continuous support in renderdoc

### ISSUE THREAD

**Issue by tuxerr** [baldurk/renderdoc#1011]
## Description
Currently, Oculus Mobile (GearVR and Go) frame captures on Android uses the gl_hooks_vrapi.cpp file to hook the vrapi_submitframe function in order to know when an app finishes its frame, a requirement to be able to do frame captures. This is quite buggy since 1.0, as it hooks into libvrapi.so instead of libvrapiimpl.so, and therefore calls the stub and not the implementation of vrapi_submitframe after the function has been hooked. This also works very differently depending on if you're on a GearVR or an Oculus Go, due to the differences of the compositor being an app in Gear vs a system component in Go. 

In SI1.15, the very latest runtime update (not available for Go yet, but soon), the compositor directly submits a GL marker, and renderdoc supports it as of https://github.com/baldurk/renderdoc/commit/83ba2e95e736a3f4f150c6fa16b92c4ad01845cd. In order to make all of this more stable, the best way going forward would be to deprecate the VRAPI hooking and solely maintain the GL path, including the end-of-frame markers. 

Is there anybody out there that is using renderdoc for oculus mobile, for which renderdoc is currently working, but who can't upgrade to the latest runtime update for Oculus?

Thanks :)

**Comment by trs-jimmy-lee** [comment]
This is fine for us. Our fork of renderdoc is working with oculus mobile, and I'll try the new changes out once I am done with what I am working on.

**Comment by baldurk** [comment]
To be concrete, let's say if no-one responds within 3 weeks (by 6th July) we'll assume everyone who is capturing VRAPI apps is on the latest runtime.

**Comment by baldurk** [comment]
I removed the hooks and closed this ahead of time because I didn't fully appreciate that some cases with the newer versions of oculus's libraries are actually broken while these hooks are in place.

If you do have issues with the removal of the vrapi hooking, please still comment here so we can evaluate what solution is appropriate.
