### ISSUE TITLE
vkEnumeratePhysicalDeviceGroups Crash

### ISSUE THREAD

**Issue by AaronHaganAMD** [baldurk/renderdoc#1012]
https://github.com/baldurk/renderdoc/blob/d79514f926e3efbae2933001efcda119ee7eb205/renderdoc/driver/vulkan/wrappers/vk_get_funcs.cpp#L525

Should this be vkEnumeratePhysicalDevices(instance, &numPhys, NULL);.. I have to remove the Unwrap to avoid a crash in WrappedVulkan::vkEnumeratePhysicalDevices.

Thanks !

**Comment by baldurk** [comment]
Yes that's exactly the right fix, it shouldn't be unwrapped unless it was going onward to the actual implementation rather than our wrapper.

**Comment by baldurk** [comment]
Fixed as described. Thanks!
