### ISSUE TITLE
Can't connect to an Android based Nvidia Shield Tv Console

### ISSUE THREAD

**Issue by brandon-unity3d** [baldurk/renderdoc#1018]
## Description
I am trying to attach to a Unity project I made running on the NVidia Shield TV console.
When I try to attach, I get the following error connection message.

"Something went wrong connection to the debugger on the Android device.
This can happen if the package is not marked as debuggable, or if another android tool such as android studio or other tool is interfering with the debug connection"

However, I can attach to my program using GAPID with no issue.  RenderDoc appears to fail to connect to JDWP, however, GAPID is able to connect to JDWP without issue.

## Diagnostic Log Output

"RDOC 045300: [13:51:49]             core.cpp( 298) - Log     - RenderDoc v1.0 64-bit Release (5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c) loaded in replay application
RDOC 052160: [13:51:49]             core.cpp( 298) - Log     - RenderDoc v1.0 64-bit Release (5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c) loaded in replay application
QTRD 045300: [13:51:49]       qrenderdoc.cpp(  87) - Log     - QRenderDoc initialising.
RDOC 030888: [13:51:49]             core.cpp( 298) - Log     - RenderDoc v1.0 64-bit Release (5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c) loaded in replay application
RDOC 045300: [13:51:51]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 forward tcp:39970 localabstract:renderdoc_39920'
RDOC 045300: [13:51:52]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 forward tcp:38970 localabstract:renderdoc_38920'
RDOC 045300: [13:51:52]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell getprop ro.product.manufacturer'
RDOC 045300: [13:51:52]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell getprop ro.product.model'
RDOC 045300: [13:51:52]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell setprop debug.vulkan.layers :'
RDOC 045300: [13:51:56]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell setprop debug.vulkan.layers :'
RDOC 045300: [13:51:59]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 forward tcp:39970 localabstract:renderdoc_39920'
RDOC 045300: [13:51:59]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 forward tcp:38970 localabstract:renderdoc_38920'
RDOC 045300: [13:52:00]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell pm list packages -3'
RDOC 045300: [13:52:06]    android_patch.cpp( 497) - Log     - Checking that APK is debuggable
RDOC 045300: [13:52:06]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell dumpsys package com.Unity.SRP20181'
RDOC 045300: [13:52:06]    android_patch.cpp( 460) - Log     - Checking for root access on 0321317163358
RDOC 045300: [13:52:06]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 root'
RDOC 045300: [13:52:06]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell whoami'
RDOC 045300: [13:52:06]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell test -e /system/xbin/su && echo found'
RDOC 045300: [13:52:07]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 forward tcp:39970 localabstract:renderdoc_39920'
RDOC 045300: [13:52:07]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 forward tcp:38970 localabstract:renderdoc_38920'
RDOC 045300: [13:52:09]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell cmd package resolve-activity -c android.intent.category.LAUNCHER com.Unity.SRP20181'
RDOC 045300: [13:52:09]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 forward --remove tcp:39021'
RDOC 045300: [13:52:09]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell am force-stop com.Unity.SRP20181'
RDOC 045300: [13:52:10]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell setprop debug.vulkan.layers VK_LAYER_RENDERDOC_Capture'
RDOC 045300: [13:52:10]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell mkdir -p /sdcard/Android/data/com.Unity.SRP20181'
RDOC 045300: [13:52:10]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell setprop debug.rdoc.RENDERDOC_CAPTUREOPTS ababaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabipdn'
RDOC 045300: [13:52:10]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell pm path com.Unity.SRP20181'
RDOC 045300: [13:52:10]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell ls /data/app/com.Unity.SRP20181-2//lib/*/libVkLayer_GLES_RenderDoc.so'
RDOC 045300: [13:52:11]          android.cpp( 173) - Log     - No library found in /data/app/com.Unity.SRP20181-2//lib/*/libVkLayer_GLES_RenderDoc.so for com.Unity.SRP20181 - assuming injection is required.
RDOC 045300: [13:52:11]          android.cpp( 185) - Log     - Setting up to launch the application as a debugger to inject.
RDOC 045300: [13:52:11]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell am start -S -D com.Unity.SRP20181/com.unity3d.player.UnityPlayerActivity'
RDOC 045300: [13:52:11]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell ps -A | grep com.Unity.SRP20181'
RDOC 045300: [13:52:12]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell ps -A | grep com.Unity.SRP20181'
RDOC 045300: [13:52:12]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell ps -A | grep com.Unity.SRP20181'
RDOC 045300: [13:52:12]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell ps -A | grep com.Unity.SRP20181'
RDOC 045300: [13:52:13]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 shell ps -A | grep com.Unity.SRP20181'
RDOC 045300: [13:52:13]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 forward tcp:39970 localabstract:renderdoc_39920'
RDOC 045300: [13:52:13]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 forward tcp:38970 localabstract:renderdoc_38920'
RDOC 045300: [13:52:14]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 forward tcp:39970 localabstract:renderdoc_39920'
RDOC 045300: [13:52:14]             jdwp.cpp( 399) - Error   - Couldn't make JDWP connection
RDOC 045300: [13:52:14]          android.cpp( 217) - Error   - Failed to inject using JDWP
RDOC 045300: [13:52:14]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 forward tcp:38970 localabstract:renderdoc_38920'
RDOC 045300: [13:52:22]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 forward tcp:39970 localabstract:renderdoc_39920'
RDOC 045300: [13:52:22]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\brandon\android-sdk_auto\platform-tools\adb.exe '-s 0321317163358 forward tcp:38970 localabstract:renderdoc_38920'"

## Repro steps

1. Deploy the remote server to the NVidia shield tv console.
2. From the Launch Application tab, choose the executable path on the android device
3. Press the Launch button

## Environment

RenderDoc build: e.g. v1.0 based 2018-06-20 nightly build
( https://github.com/baldurk/renderdoc/commit/5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c)
Operating System: Windows 10
API: OpenGLES
Device: Nvidia Shield Tv Console (Standard Edition) Version 7.0
Android Build: NRD90M.2427173_1038.2788
Shield Android TV SW Version: 6.3(24.32.406.472)

**Comment by baldurk** [comment]
This seems like the same bug that's come up a few times, where `ps` on some versions of android doesn't work if you pass it on `-A` (which is delightful since on other versions of android we *must* pass `-A`).

Under environment you've said "e.g. v1.0 based 2018-06-20 nightly build (5ef2d0b)" which is a weird mix of things, it's not an example because it's edited from the template, but 5ef2d0b is the commit of v1.0 - as in your pasted log - not the commit of the 2018-06-20 nightly build.

This has been fixed since v1.0, can you specifically try a recent nightly build and see if that works for you?

**Comment by brandon-unity3d** [comment]
Thanks for the quick reply.  The issue is resolved in version 1.1 https://github.com/baldurk/renderdoc/commit/67037ed4a125f618fbc759ed8935060f0b3503e4
