### ISSUE TITLE
Crash when trying to save texture as HDR with MSAA

### ISSUE THREAD

**Issue by saadjaved14** [baldurk/renderdoc#1023]
## Description
I was trying to save a texture to file, specifically to HDR format and the app crashed. After further inspection I noticed the crash only occurs when saving textures marked as Texture 2D MS XX. I am still able to save them as PNG or JPG. 

## Environment

* RenderDoc build: Tested on v1.0 (stable) and v1.1 (built: 0795e739)
* Operating System: Windows 10
* API: D3D12
* GPU: GTX 1060

**Comment by baldurk** [comment]
I implemented the MSAA <-> Array copies needed to support saving, so you should now be able to save to DDS, HDR, etc.
