### ISSUE TITLE
D3D sample_info returns 0 in debugger for non-MSAA textures

### ISSUE THREAD

**Issue by C-Core** [baldurk/renderdoc#1025]
## Description

When you use GetRenderTargetSampleCount() in HLSL to query the sample count of the bound rendertarget it actually returns 1 if a non-MSAA texture is bound. This function results in the sample_info instruction and RenderDoc returns 0 in the debugger for non-MSAA textures.

Furthermore EvaluateAttributeAtSample(input.xxx, 0) should return the unmodified input value if a non-MSAA texture is bound. The instruction is eval_sample_index.

## Repro steps

E.g. a common pattern in shader code to use these two functions would be:

uint msaaSamples = GetRenderTargetSampleCount();

for (uint i = 0; i < msaaSamples; ++i)
{
    float2 texCoords = EvaluateAttributeAtSample(psIn.texCoords, i));

    float alphaValue = diffuseTex.Sample(LinearSampler, texCoords);
    
    coverageMask = (coverageMask << 1) | (alphaValue >= alphaClipThreshold);
}

if (coverageMask == 0)
{
    discard;
}

This code gives you super sampled antialiasing for alpha tested geometry when using MSAA and it also works with non-MSAA targets, so no preprocessor defines etc. needed.

## Environment

* RenderDoc build: e.g. v0.92
* Operating System: e.g. Windows 10
* API: D3D11

**Comment by baldurk** [comment]
The `sample_info` fix is straightforward, I just didn't have the right behaviour on this edge case. The `eval_sample_index` is harder to emulate though, since by the time I'm debugging and interpreting instructions I've already gotten fixed per-pixel attributes.

Are you able to share a runnable sample (either a frame capture or a program) that has this in action? that would make it simpler to repro and fix the behaviour.

**Comment by C-Core** [comment]
Unfortunately I can't share a sample or capture right now. I can see if I can hack something together later/tomorrow.

**Comment by C-Core** [comment]
Hi again,
I've created a small repro case in the DX11 Tutorial 07. You can find a capture and the modified source here:
https://www.dropbox.com/sh/hzytia1mt39ppgf/AADdcA_TlXv8EKpAIZ2xq2aoa?dl=0

**SampleInfoRepro:**
In the texture preview you can see alpha testing works as expected. When you try to debug any of the white pixels the debugger goes into the discard case, because sample_info returned 0 and therefore the loop is not executed.

**EvalSampleIndexRepro:**
This is basically the same as above but I clamped the sample_info value to 1 so that the loop is executed.
When you step through a white pixel here you can see that eval_sample_index returns 0,0 although it should return the unmodified value of v1.xy.

Hope this helps! Let me know if you have any questions.

Cheers,
Clemens

**Comment by baldurk** [comment]
Thanks for the sample, that made it *much* easier to implement the functions.

The attribute evaluation is a little tricky - it's difficult to do on-demand so instead I conservatively cache all the sample evaluations that might be needed. For fixed samples this is fine, and even for loops like this I just cache every sample and most of that time that's what you'll need. The one case to be aware of is if using `EvaluateAttributeSnapped` with a dynamic offset - there are 256 possible offsets and they all get cached, so it can be quite slow.

Of course in the non-MSAA case you originally mentioned it just returns the attribute directly, no problem.

btw, side-note I saw the .rdc files you included were captured on a v0.x build. I'd suggest updating to v1.0, and you'll definitely need to update to get this fix :smile: .

**Comment by C-Core** [comment]
Thanks a lot for the fast fix. Re-tested it with my application and it works fine now :)
