### ISSUE TITLE
Crash when loading a .rdc file

### ISSUE THREAD

**Issue by DuncanKeller** [baldurk/renderdoc#1035]
## Description

Renderdoc is crashing when trying to load a recording of my simple application. There's a few warnings in the logs, but no obvious errors. My most recent change was moving a lot of code into an abstraction layer, so it's hard to say exactly what I did that caused it to stop working.

I'm using version 1.0 of renderdoc, with a D3D11 application on Windows 10. Here's the full log.

RDOC 000784: [23:54:31]             core.cpp( 298) - Log     - RenderDoc v1.0 64-bit Release (5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c) loaded in replay application
RDOC 011812: [23:54:31]             core.cpp( 298) - Log     - RenderDoc v1.0 64-bit Release (5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c) loaded in replay application
QTRD 000784: [23:54:31]       qrenderdoc.cpp(  87) - Log     - QRenderDoc initialising.
RDOC 007564: [23:54:31]             core.cpp( 298) - Log     - RenderDoc v1.0 64-bit Release (5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c) loaded in replay application
QTRD 000784: [23:57:15]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange () 0
QTRD 000784: [23:57:15]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange () 0
QTRD 000784: [23:57:16]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///C:/projects/Hunkadunk/Hunkadunk/build/x64/Debug/Hunkadunk.exe")) 1
RDOC 000784: [23:57:18]    win32_process.cpp( 477) - Log     - Running process C:\projects\Hunkadunk\Hunkadunk\build\x64\Debug\Hunkadunk.exe
RDOC 000784: [23:57:18]    win32_process.cpp( 538) - Log     - Injecting renderdoc into process 14920
RDOC 014920: [23:57:18]             core.cpp( 298) - Log     - RenderDoc v1.0 64-bit Release (5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c) capturing application
RDOC 014920: [23:57:20]   win32_libentry.cpp(  65) - Log     - Loading into C:\projects\Hunkadunk\Hunkadunk\build\x64\Debug\Hunkadunk.exe
RDOC 014920: [23:57:20]      dxgi_common.cpp(1365) - Warning - Querying IDXGIAdapter for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 014920: [23:57:20]      dxgi_common.cpp(1360) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 000784: [23:57:20]   target_control.cpp( 512) - Log     - Got remote handshake: Hunkadunk [14920]
RDOC 000784: [23:57:21]   target_control.cpp( 720) - Log     - Used API: D3D11 (Not presenting & supported)
RDOC 000784: [23:57:21]   target_control.cpp( 720) - Log     - Used API: D3D11 (Presenting & supported)
RDOC 014920: [23:57:24]     d3d11_device.cpp(1402) - Log     - Starting capture, frame 394
RDOC 014920: [23:57:25]     d3d11_device.cpp(1438) - Log     - Finished capture, Frame 395
RDOC 014920: [23:57:25]  d3d11_initstate.cpp( 698) - Warning - Not serialising texture 2D initial state. ID 44
RDOC 014920: [23:57:25]  d3d11_initstate.cpp( 702) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 014920: [23:57:25]          rdcfile.cpp(1084) - Log     - Finishing write to section 1 (renderdoc/internal/framecapture). Compressed from 533803776 bytes to 3192719
RDOC 014920: [23:57:25]             core.cpp(1090) - Log     - Written to disk: C:/Users/Logfella/AppData/Local/Temp/RenderDoc/Hunkadunk_2018.07.07_06.57.18_frame394.rdc
RDOC 014920: [23:57:25]          rdcfile.cpp( 239) - Log     - Opening RDCFile C:/Users/Logfella/AppData/Local/Temp/RenderDoc/Hunkadunk_2018.07.07_06.57.18_frame394.rdc
RDOC 000784: [23:57:25]   target_control.cpp( 673) - Log     - Got a new capture: 0 (time 1530946645) 33068 byte thumbnail
RDOC 000784: [23:57:26]    win32_network.cpp( 222) - Warning - recv: WSAECONNRESET: An existing connection was forcibly closed by the remote host.
RDOC 000784: [23:57:26]          rdcfile.cpp( 239) - Log     - Opening RDCFile C:\Users\Logfella\AppData\Local\Temp\RenderDoc\Hunkadunk_2018.07.07_06.57.18_frame394.rdc
RDOC 000784: [23:57:26]          rdcfile.cpp( 239) - Log     - Opening RDCFile C:\Users\Logfella\AppData\Local\Temp\RenderDoc\Hunkadunk_2018.07.07_06.57.18_frame394.rdc
RDOC 000784: [23:57:26]      d3d11_hooks.cpp( 275) - Log     - Created wrapped D3D11 device.
RDOC 000784: [23:57:26]     d3d11_replay.cpp(3588) - Log     - Created device.
RDOC 000784: [23:57:29] replay_controller.cpp(1574) - Log     - Created replay driver.
RDOC 000784: [23:57:31]     d3d11_device.cpp( 993) - Log     - Timer chunk initialisation - 2869.864 ms

**Comment by baldurk** [comment]
Can you share the capture file, or get a callstack of where the crash is? From the log there's not much I can tell about what's going wrong.

You could also try a recent nightly build, as there have been quite a few fixes since v1.0.

**Comment by DuncanKeller** [comment]
Sure thing, here's a link to the recording 
https://1drv.ms/u/s!An32u6FnaiDvyzSRwQP6sU2aNmRB

I'm not sure where to find the callstack. Is the another log location?

Thanks for the help, I'll download a newer build tonight and give it a whirl.

**Comment by baldurk** [comment]
Any crash that happens should open the bug reporter like this, I thought maybe you had the minidump you could open to get a callstack and hadn't reported it, or something like that.

![image](https://user-images.githubusercontent.com/661798/42414547-0e82fd30-822f-11e8-9742-73fe72c4f8cb.png)

In any case looking at the capture I believe this was a bug in v1.0 that has [since been fixed](https://github.com/baldurk/renderdoc/commit/9f07b073dc8f751a7882185fcc076ac77da2fab7). Hopefully you can confirm that with a nightly build when you have a chance.

**Comment by DuncanKeller** [comment]
Hm, yeah, I don't think it produced a minidump. It closed out without showing a screen like that. In any case, the nightly build did indeed fix it. Thanks very much for the help, sorry it ended up being a waste of time.
