### ISSUE TITLE
Crash on texture view after render doc activation in unity.

### ISSUE THREAD

**Issue by giordi91** [baldurk/renderdoc#1036]
## Description

Good afternoon, I am having a weird issue with render doc when used with unity.
I understand is a bit of a long shot but I thought I would try anyway.
The issue I am facing is I have a c++ plugin in unity, where I grab a texture pointer from unity and generate some custom mipmaps on such texture. Everything works great I can run the code (unity play mode) as many times as I want, then I enable render doc, enter play-mode again, and code fails on :
```c++
device->CreateShaderResourceView(texture, &srvDesc, &pTextureSRV);
```
the above is my code, where "texture" is the native pointer to a dx11 texture (created by unity). 
The weird thing is that it only happens if I enable render doc after I press play  N times (usually 2). If I start to render doc first and then play, no issue whatsoever. 

I wonder if render doc might be doing anything that might affect such texture in any way?
Again, apologies for the long shot, I thought I would pick your brain, maybe you had a hunch on top of your head. I am asking because I do nothing with that pointer, just get it and call CreateShaderResourceView. 

I have run the sample with the debug layer enabled, no issues were reported. 

## Repro steps
Not provided, but if interested I can provide the unity project.

## Environment
Unity 2018.2.b11 (tested with many version down to official 2017 release, same crash)
Windows 10
Nvidia gtx 1080
Using RenderDoc 1.0 from build https://github.com/baldurk/renderdoc/commit/5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c

**Comment by baldurk** [comment]
To really investigate this I'd need a way to reproduce this locally, meaning the unity project and plugin. Otherwise it's very hard to be sure of what's going wrong.

Just as a guess, do you cache or locally store any of the D3D interface pointers? When RenderDoc is loaded Unity re-initialises D3D and all the previous interfaces will be invalid, after that they'll be hooked interfaces. So e.g. if you're storing the `device` or `texture` pointer locally from before loading RenderDoc, it will not work afterwards.

**Comment by giordi91** [comment]
Apologies for the delay, long day at work. Yes I do hold on those pointers that might very well be the issue, I will verify ASAP and get back to you.

**Comment by giordi91** [comment]
I was just able to verify this, although unity does not give you a callback when it re-initialises D3D, but the actual abstract interface they give you does still work. What I ended up doing was cleaning up those pointer when the game is stopped and re-freshing them when play is hit, that seems to fix. I will let the unity guys know and maybe write a small blog post about it so doesn't get lost. Thank you for your help, most of all because it was not a render doc bug.

**Comment by baldurk** [comment]
Yeh this is unfortunately a limitation of how the hooking works. You'd have the same problem without renderdoc if the current graphics API changed from D3D to GL, then back to D3D, as it would be recreated each time. When renderdoc loads it 'changes' back to the same API, so everything is recreated.

Looking briefly at [the documentation here](https://docs.unity3d.com/Manual/NativePluginInterface.html), under "Access to the Graphics Device" the `OnGraphicsDeviceEvent` seems to provide information about when a GfxDevice is created (`kUnityGfxDeviceEventInitialize`) and destroyed (`kUnityGfxDeviceEventShutdown`), does that not fire in this situation?

**Comment by giordi91** [comment]
I did have a debug print in there that prints on unity console, none showed up. I will investigate more closely to make sure that maybe that print did not work but the function is called. Thanks again.

M.

**Comment by giordi91** [comment]
Had time to properly sit and the function gets properly called and works as advertised, thanks a lot.
