### ISSUE TITLE
Crash on Capture in IDXGIFactory2::CreateSwapChainForHwnd

### ISSUE THREAD

**Issue by JordanLogan** [baldurk/renderdoc#104]
I get a crash when running my program inside RenderDoc and the program works fine outside of RenderDoc. I attached a debugger to my program when it crashed and was getting a Access violation reading location 0x00000000 inside the DirectX function IDXGIFactory2::CreateSwapChainForHwnd.

I have tried RenderDoc 0.21 and 0.22 Bata.

**Comment by missmah** [comment]
This looks like it was fixed; but, somehow, I'm seeing a very similar crash with RenderDoc 0.26 x64 on Windows 10 TH2: (10.0.10586.0 (th2_release.151029-1700) C:\Windows\System32\dxgi.dll

Out of curiosity, have you tested on systems with multiple GPUs from multiple vendors?

**Comment by baldurk** [comment]
I haven't tested that personally, no, although I don't know how often that happens in the wild. Do you have any more details about the crash you're seeing that you can share?
