### ISSUE TITLE
 location=-1 exist

### ISSUE THREAD

**Issue by z00318884** [baldurk/renderdoc#1042]
## Description

I found a problem in xml file location is -1.
<chunk id="3" name="Initial Contents" .....>
<int name="Location" typename="int32_t" width="4">-1</int>
this is a bug？
note：test app was gfxbench 4.0.1 high-level Tests Car Chase

I also want to know  renderdoc will have a function that support to  translate rdc file to txt file？

**Comment by z00318884** [comment]
not only in initial contents（chunk id="3"）
<chunk id="1766" name="glUniform4fv" length="44" threadID="528124749040" timestamp="38728098" duration="0">
			<ResourceId name="Program" typename="GLResource" width="8" string="ResourceId::750">750</ResourceId>
			<int name="location" typename="int32_t" width="4">-1</int>

**Comment by z00318884** [comment]
not only in initial contents（chunk id="3"）

<chunk id="1766" name="glUniform4fv" ...>
<ResourceId name="Program" typename="GLResource" width="8" string="ResourceId::750">
<int name="location" typename="int32_t" width="4">-1</int>

**Comment by z00318884** [comment]
not only in initial contents（chunk id="3"）
<chunk id="1766" name="glUniform4fv" ...>
<int name="location" ...>-1<...>

**Comment by baldurk** [comment]
The XML is just a representation of the RDC file, unless there's a problem with the replay I don't consider any contents a bug. E.g. if -1 is listed for the location parameter of a `glUniform4fv` call then that's what the application passed to the function.

I don't have any plans to provide other plain-text exporters, but it's relatively straightforward to write your own either in C++ or python using the access to the structured data.
