### ISSUE TITLE
RenderDoc with QVulkanInstance and Vulkan 1.1

### ISSUE THREAD

**Issue by AndreasReiten** [baldurk/renderdoc#1043]
## Description
Qt quite recently introduced a basic set of QVulkan classes. One of these is QVulkanInstance. Before creation of the actual instance one may specify a Vulkan API version. Setting this to 1.1 prevented RenderDoc from hooking into the API (Renderdoc displays "API: none"). Specify instead API version 1.0 and RenderDoc works normally. The relevant Qt source code looks fine, so I think the bug might be with RenderDoc. 

## Repro steps
I can reproduce the bug by taking any of the official QVulkan samples and calling setApiVersion(QVersionNumber(1,1)) on the instance before creation. 

Unaltered source: http://doc.qt.io/qt-5/qtgui-hellovulkanwindow-example.html

## Environment

* RenderDoc build: 1.0
* Operating System: Windows 7, Arch Linux
* API: Vulkan 
* Misc: Desktop, GTX1070, latest drivers, latest layers and Vulkan headers

**Comment by baldurk** [comment]
RenderDoc 1.0 does not support Vulkan 1.1, so the vulkan loader forcibly disables/removes the layer.

Can you test again with the latest nightly build or compile from source? Then Vulkan 1.1 should be supported as normal as well.

**Comment by AndreasReiten** [comment]
For some reason I thought 1.1 support was in the stable build. Using the latest nightly build appears to solve all issues as well as permitting SPIR-V 1.3 shaders. Thanks!
