### ISSUE TITLE
Please bump bundled zstd to 1.3.2+

### ISSUE THREAD

**Issue by Tele42** [baldurk/renderdoc#1046]
## Description
Good day, I attempted to build renderdoc on a Gentoo Linux system. This failed when it hit https://github.com/facebook/zstd/issues/868.

Please bump the bundled zstd to 1.3.2 or newer to summary resolve this issue.

## Repro steps

Attempt to do a cpu-optimized build with an AVX2-enabled cpu.

## Environment

* RenderDoc build: v1.0 and git master
* Operating System: Gentoo Linux
* CPU: Intel i7-7700

Gentoo ebuilds grabbed from https://data.gpo.zugaina.org/AzP/dev-util/renderdoc/.

**Comment by baldurk** [comment]
Updated zstd to v1.3.5
