### ISSUE TITLE
Fail to replay OpenGL ES and Vulkan on Android

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1047]
## Description

I was capturing an OpenGL ES Android application and when I tried to replay it, RenderDoc crashed (same with Vulkan Android app). 
The problem is that **rdc** is null here:
```
ReplayStatus status = platform.InitialiseAPI(data, rdc->GetDriver());
```

in the **CreateReplayDevice** method of **gl_replay.cpp** (row 3246)

## Environment

* RenderDoc build: v1.x, 2018-07-19
* Operating System: Ubuntu Linux
* API: OpenGL ES, Vulkan

Android device: Samsung Galaxy S8+
Android version: 7.0

**Comment by baldurk** [comment]
There were a couple of bugs I fixed - including the one you found which assumed `rdc` when it is set to `NULL` for a local proxy (in this case on linux GL is used as the local proxy, on windows D3D11).
