### ISSUE TITLE
Double frame capture required and other oddities

### ISSUE THREAD

**Issue by rorydriscoll** [baldurk/renderdoc#1049]
## Description

For some reason, I need to capture two sequential frames to be able to see any events in RenderDoc. I'm not sure if it's an issue on my end, perhaps due to dynamically loading a dll, but I can't work out what it is.

It looks like even when I do get some events in RenderDoc, some of them may be missing (again, not sure if this is an issue on my end).

## Repro steps

See the repro application here:

https://www.dropbox.com/s/mtl1f2qwxtrkxjd/Repro.zip?dl=0

I've included a render doc settings file which shows the issue. If you launch the application, then Print Screen to capture then it will capture a frame, but there will be no events.

In order to actually see some events, I have to use the tools to trigger two sequential frames to be captured after a delay of zero.

## Environment

* RenderDoc v1.0
* Windows 10
* D3D11
* GeForce GTX 680, driver 391.35

**Comment by baldurk** [comment]
The reason sometimes you get empty captures (not always - if you're lucky you can get a single frame capture that contains events) is that your program seems to be calling Present twice with no work in between. Something like this:

1. Draws, etc...
2. Present()
3. Present()
4. Draws, etc..
5. Present()
6. Present()

Which means that sometimes the frame capture will start on present 3 and end on 5, meaning some drawcalls are enclosed and captured, and sometimes it will start on 5 and end on 6 (or 2->3) and be empty. It depends on the timing of when the button press or socket command from the UI is detected. Capturing two adjacent frames means you're always going to have one or the other.

There's no way around this from RenderDoc's side, it needs a way to know when the frame starts and end and the `Present()` boundary is as good as it gets. If you need to keep these extra `Present()` calls without any work in between, my recommendation would be to use the [in-application API](https://renderdoc.org/docs/in_application_api.html) to manually denote the start and end of a capture based on your own metrics and trigger condition.

As to the missing events, I don't know what events are supposed to be there so I'd need more information about that - it certainly seemed to do all the same rendering as the main program.

**Comment by rorydriscoll** [comment]
Yeah that was my mistake. I found two calls to present in my code  - I must have left one there when moving code into the dll. Sorry for wasting your time. I suspect the missing events could have been caused by this as well since it was possible for them to fall into another frame.
