### ISSUE TITLE
D3D12Device::CheckFeatureSupport returns E_INVALIDARG

### ISSUE THREAD

**Issue by bejitt** [baldurk/renderdoc#1051]
## Description

Based on the documentation for CheckFeatureSupport (https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/nf-d3d12-id3d12device-checkfeaturesupport), the device is expected to fill out the highest shader model it supports (up to the one passed in). If I call this with D3D_SHADER_MODEL_6_0 or higher, RenderDoc returns E_INVALIDARG, but returns S_OK if I pass D3D_SHADER_MODEL_5_1.

If RenderDoc doesn't support Shader Model 6.0 and above, it should be setting the highest shader model to 5.1 instead of hard failing on this function.

With RenderDoc failing on this function, I have to setup special case failure checks *just for RenderDoc* to handle its failure as the drivers will return S_OK with a lower shader model.

## Repro steps

Call ID3D12::CheckFeatureSupport with Feature set to D3D12_FEATURE_SHADER_MODEL and the D3D12_FEATURE_DATA_SHADER_MODEL struct filled out with D3D_SHADER_MODEL_6_0.

When running without RenderDoc, the function returns S_OK and the struct is updated with the highest shader model the driver supports up to 6.0. Running with RenderDoc, the function returns E_INVALIDARG.

## Environment

RenderDoc 1.1
Windows 10, 1803
DirectX 12

**Comment by baldurk** [comment]
That's my mistake, I misunderstood how the query was supposed to function.

Indeed SM6 is not supported, and I've updated the code to clamp the shader version instead of returning E_INVALIDARG.
