### ISSUE TITLE
Cannot capture through a network

### ISSUE THREAD

**Issue by Quincy0v0** [baldurk/renderdoc#1053]
## Description

I am connecting to my android device via network. I have successfully Launched the application, and the in-app prompts shows up, but it says "No remote access connection". Also, on my windows renderdoc client, Status->API shows 'None' and the "Trigger after delay" and "Queue Specific Frames" buttons become greyed out.
I wonder what is the cause of this problem. Maybe renderdoc cannot recognize the API? The device is using OpenGL ES 3.2 and The in-app prompts shows "OpenGLES"

## Repro steps
![untitled](https://user-images.githubusercontent.com/30424046/43241845-1099a920-90d0-11e8-9fb3-969c9d5f29fa.png)

## Environment

* RenderDoc build: 2018-07-17 nightly build.
* Operating System: Windows 7
* API: OpenGLES

**Comment by baldurk** [comment]
When you say the in-app prompt, do you mean the overlay rendered on top of the android application? If that shows up then it should indeed be working so it's strange that the connection is established but no API is identified.

Can you paste the android logcat? This should show the API use as well as the connection from the host, it might give some clue why the API isn't properly identified. Just to check - you don't have multiple programs running on the android device and might be connecting to the wrong one?

**Comment by tabikati** [comment]
If I connect the device via network it works all well for me on Linux.

**Comment by baldurk** [comment]
Without more information I can't investigate this, I'm closing this issue but if you do have more information to provide please comment here and it can be reopened.
