### ISSUE TITLE
Question: would be possible to have source release tarballs without compiled binaries?

### ISSUE THREAD

**Issue by cmarcelo** [baldurk/renderdoc#1055]
I'm looking to package Renderdoc in Clear Linux: https://clearlinux.org/. Clear Linux ships the upstream tarballs as part of the source packages (in the form of SRPMs), but it can't ship upstream tarballs that contain binaries.

The existing source release tarballs are generated directly from Git and contain binary files in the repository for certain 3rdparty libraries.

I know that you already generate compiled tarballs/zips for various platforms (and sign them) as part of the release, would be possible to also generate (and sign) a "clean" source tarball, without the precompiled 3rdparty libraries?

**Comment by baldurk** [comment]
No I don't think I'll provide tarballs like that. Depending on what you class as a binary it shouldn't be hard to strip out the folders you don't want. Most of it is in `qrenderdoc/3rdparty`, but bear in mind since binaries like the resources/icons and docs screenshots are needed on linux too.

**Comment by jljusten** [comment]
@baldurk: I'm guessing the question is related to the bundling of 3rdparty libraries that commonly are built as separate packages on Linux, and also Windows exe and dll files.

@cmarcelo: I'm not sure we got the stripping 100% correct, but you can find the debian stripped 1.0 tarballs at https://packages.debian.org/source/sid/renderdoc. Let me know of anything that I missed.
