### ISSUE TITLE
Can not  connet to the child process.

### ISSUE THREAD

**Issue by Cindy-xdZhang** [baldurk/renderdoc#1056]
## Environment

* RenderDoc build: v1.0 , or v0.34.
* Operating System: Windows 10
* API: e.g.  D3D11

Hi, sorry to bother,i know the renderdoc is not officially support the GTAV, but now its very crucial for me to capture the data from GTAV.
When I run the Renderdoc, and launch the steam ,GTAV,then i can find all the child process of the steam .
I find the GTA5 child process,but when i double click to get into it ,it open a new window,shows "conneting” and after a while,it come back to the original process window.
So I think probably there is something wrong  my with setting(ps: i ve tried in v0.34 and v1.1. all failed).
When i try to inject the GTA5  process,the Renderdoc gives error message,and ask me to view the log.
The log :
 RDOC 011408: [13:00:52]             core.cpp( 313) - Log     - RenderDoc v0.34 x64 Release (ec4899ec72fc94886e0f350c931bc7d2f08891e8) capturing application
RDOC 011408: [13:00:54]   win32_libentry.cpp(  67) - Log     - Loading into C:\WINDOWS\System32\wbem\wmic.exe
RDOC 010100: [13:01:31]   target_control.cpp( 412) - Log     - Got remote handshake: GTAVLauncher (D3D9) [7008]
RDOC 010100: [13:01:31]   target_control.cpp( 585) - Log     - Got a new child process: 1364 38925
RDOC 010100: [13:01:31]   target_control.cpp( 585) - Log     - Got a new child process: 13916 0
RDOC 010100: [13:01:31]   target_control.cpp( 585) - Log     - Got a new child process: 7844 0
The 7844 process is the GTA5  process which i want to open .
From the log i cant find anything wrong.
Could u help me.
Thanks s lot .

**Comment by baldurk** [comment]
As you are aware this is explicitly not supported. Saying that you really need it does not change that.
