### ISSUE TITLE
Renderdoc causes the application crashes on android

### ISSUE THREAD

**Issue by Cry-Mory** [baldurk/renderdoc#1057]
I noticed renderdoc causes **vkCreateInstance** fail due to  VK_ERROR_EXTENSION_NOT_PRESENT.

Should I put renderdoc's validation layer in application package?

**Comment by baldurk** [comment]
What set of instance extensions are you enabling? Have you checked that all of them are enumerated as available when running with renderdoc?

I'm not sure what you mean by a validation layer, I don't recommend using the lunarg validation layers on android at the same time as renderdoc.

**Comment by Cry-Mory** [comment]
@baldurk  thanks a lot for your reply. I just noticed it was a bug on our side. Your hint led me to a situation where I found the bug.

Thanks again.
