### ISSUE TITLE
D3D11 driver crashes during serialization of offsetted UpdateSubresource() call

### ISSUE THREAD

**Issue by decden** [baldurk/renderdoc#1059]
## Description

I have a D3D11 application, which runs fine on its own, but crashes whenever I try to make a capture with RenderDoc. After debugging the application, while running with the RenderDoc driver, I found out that the driver tried to access invalid memory during the serialization of an `UpdateSubresource` call.

The call which causes the crash tried to update the bottom right corner of a 1920x1200 texture:

    pDstBox = {left: 1524, top: 254, right: 1920, bottom: 1200}
    srcRowPitch = 1920 * 4

In my case RenderDoc first computes the number of rows which need to be updated 946 (= 1200 - 254). The size which it then tries to read is 946 * srcRowPitch. This results in an out of bounds access and crashes my application. This would probably not happen if the x-coordinate of the box would be 0.

I believe the line responsible for the erroneous size calculation is the following:
https://github.com/baldurk/renderdoc/blob/5293a2c991d0915d4b30131b717c94a067efc8f6/renderdoc/driver/d3d11/d3d11_context1_wrap.cpp#L119

## Repro steps

    // Initialization
    D3D11_TEXTURE2D_DESC desc = {};
    desc.Width = 1920;
    desc.Height = 1200;
    desc.MipLevels = 1;
    desc.ArraySize = 1;
    desc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
    desc.SampleDesc.Count = 1;
    desc.Usage = D3D11_USAGE_DEFAULT;
    desc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
    desc.CPUAccessFlags = 0;
    desc.MiscFlags = 0;
    HRESULT hr = _device->CreateTexture2D(&desc, nullptr, tex.GetAddressOf());
    
    // Capturing the following call causes the crash
    D3D11_BOX dstBox = {};
    dstBox.left = 1524;
    dstBox.top = 254;
    dstBox.right = 1920;
    dstBox.bottom = 1200;
    dstBox.back = 1;
    size_t offset = dstBox.left * 4 + dstBox.top * (1920 * 4);
    _immediateContext->UpdateSubresource(tex.Get(), 0, &dstBox, reinterpret_cast<const char*>(bgrabuffer) + offset, 1920 * 4, 0);

## Environment

* RenderDoc build: v1.1
* Operating System: Windows 10
* API: DirectX11

**Comment by baldurk** [comment]
Good catch! And thanks for debugging into it.

I'll double check before fixing, but if I understand right the issue is that the size read should be something more like `SrcRowPitch * (rows - 1) + WidthOfFinalRow` since the last row doesn't use the whole pitch? Just to check we're on the same patch, so this works only if SrcRowPitch - WidthOfFinalRow happens to land in valid memory, which will vary a lot.

**Comment by decden** [comment]
Thanks for the quick response!
You are spot on. It is also correct that the crash will only occur if the memory between `SrcRowPitch * (rows - 1) + WidthOfFinalRow` and `SrcRowPitch * rows` is invalid. Chances of triggering the crash are of course higher with larger textures and smaller values for `WidthOfFinalRow`.

**Comment by baldurk** [comment]
I believe the calculation is right now, and I added some manual tests against various dimensions and block compressed formats and things. Let me know if you still spot any problems in this area.
