### ISSUE TITLE
connect android 5.1 failed

### ISSUE THREAD

**Issue by wangjianpeng** [baldurk/renderdoc#1060]
## Repro steps
I use renderdoc to connect my android , but it failed and tell me "remote server not running and start failed". then i use adb to install the org.renderdoc.renderdoccmd.arm32.apk , it failed also and tell me "install failed with older sdk".

## Environment

* RenderDoc build: the latest release version V 1.1
* Operating System: Android 5.1 
* API: OPGL ES 3.0

**Comment by baldurk** [comment]
This is expected, Android 6.0 is the minimum supported version - according to Google's stats, 66% of end-users have at least Android 6.0 so it's expected that the proportion among developers should be higher.

I'll see about adding a more friendly error message for when an older device is detected but I don't plan to support older versions of Android.

**Comment by baldurk** [comment]
That commit should now detect unsupported Android versions and give you a direct error message.
