### ISSUE TITLE
Deletion of captures with delete key vs. right click->delete

### ISSUE THREAD

**Issue by MidwinterChase** [baldurk/renderdoc#1061]
## Description

Really, really minor interface gripe: if you select multiple captures and hit the delete key, it deletes all selected captures. But if you instead select multiple captures and right-click + delete, it only deletes one capture. It's no big deal but it does screw up my workflow enough to be a little annoying.

## Repro steps

1. Select multiple captures, either with box select or shift-click
2. Right click one of the selected captures.
3. Select "Delete" and "Yes" to the following prompt.

## Environment

* RenderDoc build: v1.1
* Operating System: Windows 10
* API: D3D11

**Comment by baldurk** [comment]
Interesting, the code is supposed to be going through the same function in either the [right-click](https://github.com/baldurk/renderdoc/blob/v1.x/qrenderdoc/Windows/Dialogs/LiveCapture.cpp#L172) 
 or [keypress](https://github.com/baldurk/renderdoc/blob/v1.x/qrenderdoc/Windows/Dialogs/LiveCapture.cpp#L883) path so this isn't something I'm explicitly doing.

Can you clarify - for me the behaviour seems to be that if I right click on a particular capture, then Qt first selects that item *then* pops up the menu. So clicking delete then deletes only the item clicked on. If you instead right click on blank space it seems to allow you to delete all selected items.

This isn't how it should behave, right clicking on a selected item should preserve the selection, but this might be a Qt behaviour that is hard to change without significant surgery, I'll need to investigate.

**Comment by MidwinterChase** [comment]
Yep -- you're completely right. If I right-click in the blank area, not over a capture thumbnail, then all are deleted.

Thanks for looking into this!

**Comment by baldurk** [comment]
Turns out it was my code, I had something in there to try and select an item when it was right-clicked. It doesn't seem to be necessary (not sure if it ever was) and was causing this. Should be fixed now.

**Comment by MidwinterChase** [comment]
Great, thanks baldurk!
