### ISSUE TITLE
Bug in replay device selection

### ISSUE THREAD

**Issue by kd-11** [baldurk/renderdoc#1062]
I have a setup with 2 GPUs, enumerated with an AMD card as device0 and NVIDIA as device1. When attempting to replay a capture from another PC captured on an NVIDIA card as device0, I get the incompatible hardware failure. I checked and realized that:
1. serialize_vkEnumeratePhysicalDevices properly identifies the best match (bestIdx) to be the nvidia card at index 1.
2. serialize_vkCreateDevice selects the physical device with `physicalDevice = m_ReplayPhysicalDevices[physicalDeviceIndex];` which actually grabs the AMD card again because the serialized physicalDeviceIndex == 0. I noticed that the enumeration step did store the correct handle in the m_PhysicalDevices[physicalDeviceIndex] slot, but when actually creating the device its not reading or comparing with that variable, although I probably misunderstood the design here, I was kinda in a rush.

Because of the implementation differences between the two cards, the replay fails because of a physicalDeviceFeatures mismatch, despite a compatible card being installed on the system. I can easily tell the AMD card was wrongly selected by just checking enumerated supportedExtensions list.

**Comment by baldurk** [comment]
Thanks for reporting this! Indeed you noticed the exact problem, `m_ReplayPhysicalDevices` is the list of physical devices during the replay but this could be arbitrarily mixed up or incompatible. The point of the remapping with `bestIdx` is to fill out the `m_PhysicalDevices` list with the closest matching physical device for each one in the capture, so it should have been using that list.

Worked for me in my testing and I was able to get this problem - there wasn't a physicalDeviceFeatures mismatch but there was a crash later. Let me know if you still have any trouble.
