### ISSUE TITLE
How do I trace wine?

### ISSUE THREAD

**Issue by xDShot** [baldurk/renderdoc#1064]
## Description

I want to trace windows app launched in wine. It doesn't launch.
## Repro steps
in gui I set Executable path: /usr/bin/wine. Working Directory is where the exe is located. Command-line Argument is game.exe -param1 -param2 etc. In Environment Variable I set WINEPREFIX to my wine prefix.

When I press Launch it shows this:
![2018-08-04 11-49-13](https://user-images.githubusercontent.com/4261659/43674459-e5d6533c-97dc-11e8-9f63-54a78ef0d2f2.png)

Here is content of Diagnostic Log:
```RDOC 013371: [11:50:18]             core.cpp( 300) - Log     - RenderDoc v1.1 64-bit Release (NO_GIT_COMMIT_HASH_DEFINED) loaded in replay application
RDOC 013371: [11:50:18]             core.cpp( 303) - Log     - Packaged for Arch (1.1) - https://aur.archlinux.org/packages/renderdoc
QTRD 013371: [11:50:18]       qrenderdoc.cpp(  88) - Log     - QRenderDoc initialising.
QTRD 013371: [11:50:18]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:50:18]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:50:25]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:50:25]              unknown(   0) - Warning - Empty filename passed to function
RDOC 013371: [11:50:33]    linux_process.cpp(  88) - Warning - Couldn't locate renderdoc target control listening port between 38920 and 38927 in /proc/13404/net/tcp
QTRD 013371: [11:50:33]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:50:33]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:50:40]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:50:40]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:50:48]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:50:48]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:50:55]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:50:55]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:03]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:03]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:10]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:10]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:18]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:18]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:25]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:25]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:33]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:33]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:40]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:40]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:48]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:48]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:55]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:51:55]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:03]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:03]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:10]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:10]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:18]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:18]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:25]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:25]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:33]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:33]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:40]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:40]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:48]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:48]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:55]              unknown(   0) - Warning - Empty filename passed to function
QTRD 013371: [11:52:55]              unknown(   0) - Warning - Empty filename passed to function
```

## Environment

* RenderDoc build: from https://aur.archlinux.org/packages/renderdoc
* Operating System: Arch Linux
* API: OpenGL

**Comment by baldurk** [comment]
It seems like the library probably isn't being loaded properly. Random guess: is wine a 32-bit program? I only support 64-bit builds of linux though I don't know what Arch's packaging does. There should be a log line immediately before the `Packaged for` line that gives the version number and bitness. Did you cut that off or is it missing from the log itself?

You could try running `LD_PRELOAD=/path/to/librenderdoc.so WINEPREFIX=... /usr/bin/wine` manually to see if you get any library load errors.

**Comment by xDShot** [comment]
>is wine a 32-bit program?

Yes
>There should be a log line immediately before the Packaged for line that gives the version number and bitness. Did you cut that off or is it missing from the log itself?

I put the log as it was. So I guess yes, that part didn't present initially.

**Comment by xDShot** [comment]
Looks like the wine binary itself is 32-bit

```
$ file /usr/bin/wine
/usr/bin/wine: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=d4c8b69712f1646cb0bb714ce7103154db7389aa, stripped
```

**Comment by baldurk** [comment]
> I put the log as it was. So I guess yes, that part didn't present initially.

That's strange, the lines are literally adjacent.

https://github.com/baldurk/renderdoc/blob/03c2507a254a22a020c7cfc54e840452cac3c6e6/renderdoc/core/core.cpp#L297-L304

It's a minor issue though.

> Looks like the wine binary itself is 32-bit

That explains it then. On linux renderdoc only supports capturing from an identical ABI to itself - in this case I assume that's 64-bit. To capture a 32-bit program you'll need a 32-bit build of RenderDoc. This should work but as I mention it's officially in an unsupported grey area on linux.

**Comment by doitsujin** [comment]
You can trace 64-bit Windows games by doing something like `renderdoccmd capture wine64 game.exe`. 32-bit won't work out of the box, but you can try building 32-bit `librenderdoc` + command line utilities (the UI won't compile).

**Comment by xDShot** [comment]
Tried building 32-bit version without Qt GUI and python bindings and running renderdoccmd and it seems worked. The app is launched, but I don't get it where it stores captured trace (if it did successfully).

**Comment by baldurk** [comment]
Once you've started the program through the 32-bit renderdoccmd you can use File -> Attach to running instance in the UI and should list there and be able to connect and manage captures as normal.

Worst case, you can manually find the captures which are by default in /tmp/RenderDoc, or you can specify the save location as an option to `renderdoccmd capture` - see `renderdoccmd capture --help`.

**Comment by xDShot** [comment]
No, it doesn't create, guess it failed...

**Comment by baldurk** [comment]
Do you get the renderdoc overlay on the program, and are you able to attach in the UI? If so when you trigger a capture what happens?

Posting the log for the new 32-bit run would be useful.

**Comment by xDShot** [comment]
I didn't see overlay. Currently cannot attach UI as for now I can only keep installed either self-compiled 32-bit version without UI or 64-bit one with UI. Might figure it out later.

Terminal output when I launch it:
```
[xdshot@lenovo-pc bin]$ export WINEPREFIX=~/wineprefixes/steam32/
[xdshot@lenovo-pc bin]$ renderdoccmd capture -w wine hlmv.exe -game ../csgo/
Launching 'wine' with params: hlmv.exe -game ../csgo/
ERROR: ld.so: object 'librenderdoc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
000b:fixme:winediag:start_process Wine Staging 3.13 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
0009:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0009:fixme:ntdll:EtwEventRegister ({47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x10007470, 0x10054c68, 0x10054c00) stub.
0009:fixme:ntdll:EtwEventRegister ({58a9201e-73b0-42ce-9821-7e134361bc70}, 0x10007470, 0x10054c08, 0x10054c98) stub.
0009:fixme:ntdll:EtwEventRegister ({3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x10007470, 0x10054ca0, 0x10054bf0) stub.
0009:fixme:ntdll:EtwEventRegister ({1432afee-73b0-42ce-9821-7e134361b433}, 0x10007470, 0x10054c38, 0x10054bf8) stub.
0009:fixme:ntdll:EtwEventRegister ({4372afee-73b0-42ce-9821-7e134361b519}, 0x10007470, 0x10054cd0, 0x10054d00) stub.
0009:fixme:nvapi:unimplemented_stub function 0x694d52e is unimplemented!
0009:fixme:nvapi:unimplemented_stub function 0xdad9cff8 is unimplemented!
0009:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x3be628, 0x3be638 0x3be62c
0009:fixme:nls:get_dummy_preferred_ui_language (0x38 0x3be628 0x3be638 0x3be62c) returning a dummy value (current locale)
0009:fixme:ole:CoInitializeSecurity ((nil),-1,(nil),(nil),0,3,(nil),0,(nil)) - stub!
0009:fixme:wbemprox:client_security_SetBlanket 0x7bd7782c, 0x1d1400, 10, 0, (null), 3, 3, (nil), 0x00000000
0009:fixme:wbemprox:client_security_Release 0x7bd7782c
Requested non-existent write path USRLOCAL!
Requested non-existent write path USRLOCAL!
Requested non-existent write path USRLOCAL!
Requested non-existent write path USRLOCAL!
0009:fixme:d3d:wined3d_check_device_format_conversion wined3d 0x197558, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B8G8R8A8_UNORM, dst_format WINED3DFMT_B8G8R8X8_UNORM stub!
0009:fixme:d3d9:D3DPERF_SetOptions (0x1) : stub
0009:fixme:d3d:wined3d_check_device_format_conversion wined3d 0x197558, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B8G8R8A8_UNORM, dst_format WINED3DFMT_B8G8R8X8_UNORM stub!
0009:fixme:nvapi:unimplemented_stub function 0xbe7692ec is unimplemented!
0041:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
0009:fixme:ver:GetCurrentPackageId (0x3bfe14 (nil)): stub
0009:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0009:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0009:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0009:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0009:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
'wine' finished executing.
[xdshot@lenovo-pc bin]$
```

The app is launched properly, but no visible overlay inside it's 3d view. 

And as well [RenderDoc_2018.08.04_14.44.42.log](https://github.com/baldurk/renderdoc/files/2259461/RenderDoc_2018.08.04_14.44.42.log)

**Comment by baldurk** [comment]
> Currently cannot attach UI as for now I can only keep installed either self-compiled 32-bit version without UI or 64-bit one with UI. Might figure it out later.

I'm not sure what you mean here, you can have two separate builds of RenderDoc - the 64-bit one with the UI, and then the 32-bit one you use to launch your program.

However:

> `ERROR: ld.so: object 'librenderdoc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

This suggests that the program is 64-bit after all? There are some GL contexts being created in the log but it might not be from the program you want to capture.

**Comment by xDShot** [comment]
I just made separate Arch package with 32-bit renderdoc which cannot be installed along with 64 bit one because of files conflicting. Will build 32bit renderdoc separately (not in package, just separate folder)

I'm pretty sure the .exe is 32-bit, maybe there is some kind of sorcery in wine itself so it handles bitness. Both renderdoccmds don't work as expected ¯\\\_(ツ)\_/¯

**Comment by baldurk** [comment]
Ah, I'd suggest building yourself rather than relying on the packages, that would also eliminate packaging as a source of problems.

I'm not sure what's going on. You could try the command that @doitsujin suggested - this problem feels more about debugging the particulars of wine and how it launches than something to do with renderdoc. It can work as I know people do debug wine, but I don't use wine myself so I can't help you with that part.

In principle it should just be that if you have a 64-bit program you launch it with a 64-bit build of renderdoc, and vice versa for 32-bit.

**Comment by xDShot** [comment]
Re-built wine to fully 32bit with no luck.
