### ISSUE TITLE
Vulkan: DispatchIndirect may has incorrect dispatch values in event browser

### ISSUE THREAD

**Issue by TiemoJung** [baldurk/renderdoc#1066]
Hi,

there seems to be a bug with the display of the dispatch dimensions for indirect dispatch (and probably all other indirect draws). The value in the event browser can differ from the actual source buffer value under certain circumstances.
We have 2 dispatches in a row, the first dispatch computes the dispatch dimensions for the following indirect dispatch. We put a barrier to flush those writes in between the dispatch and the dispatch indirect. But the event view for the indirect dispatch shows different values than the buffer view.

tested with nightly build 2018_08_02_04dc71ce_64

**Comment by baldurk** [comment]
Yes you're right, the current code won't correctly get indirect draw/dispatch parameters when they haven't been generated yet on the CPU timeline. Probably the best solution for this is to record extra readbacks in while loading to snoop the parameters, and patch them into the drawcalls after they have been submitted.

**Comment by baldurk** [comment]
With that commit, it should now fetch indirect parameters correctly at the time of dispatch/draw, and patch them in later. Let me know if you run into any issues.
