### ISSUE TITLE
renderdoc support on android P

### ISSUE THREAD

**Issue by z00318884** [baldurk/renderdoc#1067]
## Description

renderdoc support on android P ? If not do you have plan to support?

**Comment by baldurk** [comment]
Yes I plan to support it, currently I haven't tested it at all. It only came out a few days ago so I'll need to wait until it's available on a device I have for testing before I can make sure everything is working - Android being Android I assume something will have broken and will need to be fixed.

Anyone who does have it already, it would be useful to test it and report any issues you find.

**Comment by baldurk** [comment]
I've heard confirmation from someone that Android P should work at least on some devices so it should - in principle - work in general. I still don't have access to test myself but consider it supported.

If you run into any bugs then please file them and I'll do my best to find a fix.

**Comment by z00318884** [comment]
I have uesd on android P，It works ok.  thank you!
