### ISSUE TITLE
Build fails on OSX with 'custom_swig' error

### ISSUE THREAD

**Issue by expenses** [baldurk/renderdoc#1070]
Hi, having ran cmake with `cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild -H.`:

```
-- Calculating version
-- Building RenderDoc version 1.2
-- Disabling Vulkan and GLES drivers on apple
-- Could NOT find PySide2 (missing: PYSIDE2_INCLUDE_DIR PYSIDE2_PYTHON_PATH PYSIDE2_LIBRARY_DIR)
-- PySide2 not found - Qt will not be accessible in python scripting. See https://github.com/baldurk/renderdoc/wiki/PySide2
-- Enabled APIs:
--   - OpenGL
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   renderdoc

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/ashley/renderdoc/build
```

I got the following error when I ran `make -C build`:

```
[  0%] Built target include-bin
[  1%] Built target renderdoc_libentry
[ 35%] Built target rdoc
[ 37%] Built target rdoc_amd
[ 51%] Built target rdoc_gl
[ 68%] Built target rdoc_spirv
[ 92%] Built target renderdoc
[ 94%] Built target renderdoccmd
[ 94%] Performing configure step for 'custom_swig'
make[2]: *** [qrenderdoc/custom_swig-prefix/src/custom_swig-stamp/custom_swig-configure] Error 127
make[1]: *** [qrenderdoc/CMakeFiles/custom_swig.dir/all] Error 2
```

Any idea what the problem could be? The error messages are pretty vague. I've got swig already installed via homebrew incase that could be an issue.

**Comment by baldurk** [comment]
Having a copy of the system swig should be harmless as far as I know, there's no conflict as the build uses the built custom swig explicitly.

Unfortunately because of the way the build gets invoked, I'm not aware of any way to hide most of the usual swig build spam but still get errors, so currently it's completely hidden. If you go to `qrenderdoc/CMakeLists.txt` here, you can remove the `> /dev/null 2>&1` bits and then you'll get the full output, which should help diagnose the problem.

https://github.com/baldurk/renderdoc/blob/d7e40606981ac0e72239c5d1b94cc74108706811/qrenderdoc/CMakeLists.txt#L78-L85

btw, in case it changes your mind, even if you get renderdoc building then unless you want to do some hacking yourself it does not do anything useful currently - it cannot capture or replay anything, all it can do is launch android programs for capture (and then not be able to replay them). OSX is essentially not supported currently.

**Comment by expenses** [comment]
Oh ok, I didn't know it was _that_ unready. I'll try checkout what the error is regardless.

**Comment by baldurk** [comment]
Yeh I don't advertise the OSX "support" because it's so limited. It's really only placeholder keeping things compiling and preventing code-rot until it can actually do something useful.

**Comment by baldurk** [comment]
I'm going to close this issue as I don't think there's any problem on the repo side. I was compiling on most recent xcode & macOS over the weekend and it worked OK there too.

One other thing to check - I did have some issues until I had configured the xcode commandline tools - I think with `xcodebuild --install` although I can't remember exactly. Worth investigating to see if that's the problem for you.

**Comment by shebi** [comment]
I have been through this issue as well
```
[ 94%] Performing configure step for 'custom_swig'
make[2]: *** [qrenderdoc/custom_swig-prefix/src/custom_swig-stamp/custom_swig-configure] Error 127
make[1]: *** [qrenderdoc/CMakeFiles/custom_swig.dir/all] Error 2
```
and the solution to this was missing autotools. ```brew install autotools``` did the trick on 10.13.6.

I also had to add qlink to the PATH environment to have it successfully compile & link.

**Comment by baldurk** [comment]
Thanks for that, I'll add a note to the mac compilation instructions that it might be needed. I found that there was a compiler bug that broke things on 10.14 which I added a workaround for, but otherwise it worked OK for me.

**Comment by asmaloney** [comment]
I'm running into this on the v1.x branch (dfe84e962be2cdf909279b55d125adcbab68a2ee).

macOS 10.14.5
Apple LLVM version 10.0.1 (clang-1001.0.46.4)

autoconf 2.69 (from homebrew)
automake 1.16.1_1 (from homebrew)

```
[  1%] Built target include-bin
[  2%] Built target renderdoc_libentry
[  3%] Built target rdoc_version
+ test -d Tools/config
+ aclocal -I Tools/config
./autogen.sh: line 11: aclocal: command not found
make[2]: *** [qrenderdoc/custom_swig-prefix/src/custom_swig-stamp/custom_swig-configure] Error 127
```

It can't find `aclocal` for some reason. It is on my PATH:

```
$ which aclocal
/Users/maloney/brew/bin/aclocal
```

**Comment by baldurk** [comment]
Please don't comment on old bugs with new different issues. In your case I don't know why it's not finding `aclocal` but that seems like a system configuration issue and not a RenderDoc issue. Perhaps if you installed autotools after running the build once something is cached, so you need to run it again. Or open a new terminal to pick up the new program in PATH.
