### ISSUE TITLE
Capturing non-presenting (headless) Vulkan applications

### ISSUE THREAD

**Issue by skalarproduktraum** [baldurk/renderdoc#1074]
## Description

Hello @baldurk,

would it be possible to add support for capturing non-presenting Vulkan applications? I e.g. have a headless application I would like to capture. I guess this is probably a little problematic because it'd be hard to detect the start and end of a frame, but maybe an API call for marking those could be added?

**Comment by baldurk** [comment]
This already exists - check out [the documentation for the in-application API](https://renderdoc.org/docs/in_application_api.html), which allows you to control capturing for any application including headless rendering, using an API call as you mention (StartFrameCapture / EndFrameCapture).

**Comment by skalarproduktraum** [comment]
Oops, I had missed that. Thanks for pointing it out to me!
