### ISSUE TITLE
replay error

### ISSUE THREAD

**Issue by z00318884** [baldurk/renderdoc#1080]
## Description
"com.tencent.tmgp.pubgmhd" application replay not correct。
I don't know if it has anything to do with the fallowing errors。
"renderdoc: 'Error:glTexImage2D::<format>, <type> and <internalformat> are not a valid combination'".

 the internalformat is " <name="internalformat" typename="RDCGLenum" string="GL_DEPTH_STENCIL">".
In glTexImage2D  API, internalformat could be GL_DEPTH_STENCIL?

**Comment by zao** [comment]
Hi there!

It appears that you may be trying to trace a third party application outside of your control.
RenderDoc is intended for troubleshooting and inspecting your own software, snooping on third party programs is not within the scope of what should be supported.

If you're by some strange chance actually a developer for this software, I recommend that you address any API misuse you may have in the application.
Once it seems reasonably clean, submit some more information about what platform you're on and possibly send some RDC capture files.

**Comment by baldurk** [comment]
As @zao says I explicitly do not support capturing commercial/third party programs for a variety of reasons.
