### ISSUE TITLE
driver/ihv/amd/official/RGP/DevDriverComponents/listener/routerCore.cpp:401: bad expression ?

### ISSUE THREAD

**Issue by dcb314** [baldurk/renderdoc#1081]
renderdoc-1.1/renderdoc/driver/ihv/amd/official/RGP/DevDriverComponents/listener/routerCore.cpp:401]: (style) Boolean result is used in bitwise operation. Clarify expression with parentheses.

Source code is

   if (IsOutOfBandMessage(message) & !IsValidOutOfBandMessage(message))

Maybe better code

   if (IsOutOfBandMessage(message) && !IsValidOutOfBandMessage(message))

**Comment by baldurk** [comment]
Hi, can you file this issue upstream at https://github.com/GPUOpen-Tools/DevDriverTools so it can be fixed there? Then I'll pull an updated version once it is.

**Comment by dcb314** [comment]
Done.

**Comment by baldurk** [comment]
This code has been removed now in favour of an external module build, so I'm closing this issue.
