### ISSUE TITLE
GL default backbuffer parameters aren't stored per-context

### ISSUE THREAD

**Issue by DaBianYLK** [baldurk/renderdoc#1083]
## Description

Our game was developed with UE4 on Android platform. After creating three main GL contexts, the Engine will create other three GL contexts to precompile shaders during the boot process. Considering performance requirements, the contexts used for precompiling did not contain depth buffer and stencil buffer. Unfortunately, RenderDoc would overwrite the main GL context's init params with the one used for precompiling during the capture, which caused the depth test did not work in the replay.

Add depth bits validation counld avoid the main GL context's init params being overwritten. 
```
// ===========================================
// FILE: gl_driver.h
// LINE: 125

// Declare a flag to check if init params has been set
bool m_InitParamHasSet = false;

// ===========================================
// FILE: gl_driver.cpp
// LINE: 937
// FUNC: void WrapperOpenGL::CreateContext(...)

// check DepthBits here to avoid the main context's init params being overwritten.
if (!m_InitParamHasSet ||  initParam.depthBits != 0)
{
    m_InitParams = initParams;
    m_InitParamHasSet = true;
}
```
But to solve this problem from roots, it may need multiple GL contexts support.

## Environment

* RenderDoc build: 2018-08-14 nightly build.
* Operating System: Windows 10 and Android 8.0
* API: OpenGL ES

**Comment by baldurk** [comment]
Yes I agree, we could hack around maybe choosing the 'best' set of parameters - e.g. the most bits - but it wouldn't cover all cases properly.

I think the main problem with implementing this properly before was that I didn't properly have context sharing/non-sharing resource tracking. Now that it's implemented it should be possible to initialise the default framebuffer on a per-context basis, and then even a program that rendered to two different default framebuffers within a frame would get the right one each time.

**Comment by baldurk** [comment]
This should now work correctly, I tested with a program that created two windows, one smaller and with no depth buffer, but the first window created still had the proper backbuffer properties and dimensions.
