### ISSUE TITLE
Small deviation in the HLSL debugger/interpreter from GPU behavior

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#1084]
## Description

This is an enhancement or rather feature request, but might be considered a bug too (though that may be a stretch...).

The following HLSL idiom is used to speed up shader compilation (strictly speaking this may be undefined behavior, but it works on all GPUs and all vendors):

```cpp
//Original code:
uniform float4 value[4096];
float main( int idx : TEXCOORD0 ) : SV_Color0
{
    return value[idx];
}

//"Optimized" code:
uniform float4 value[2]; //<---Note this the only change
float main( int idx : TEXCOORD0 ) : SV_Color0
{
    return value[idx];
}
```

The reason for changing value[] from 4096 to 2 is that the emitted shader assembly is exactly the same (except for the reflection metadata in the comments), however fxc takes considerably less time to compile.

When compiling real shaders, this trick can cause fxc/D3DCompile() to reduce compilation times from 5-10 seconds to less than a second. It is a significant reduction in build time. The build speed improvements are even more dramatic if the variable type is complex (e.g. a struct containing structs inside)

This applies to Vertex/Pixel/Compute/etc shaders.

## The problem

When using this trick and idx >= 2; RenderDoc detects idx is out of bounds and thus returns 0 for value[idx].

However this does not match DX/GPU behavior, because the bounds computation should be performed **against the size of the currently bound buffer**, not the shader's declaration. If the buffer currently bound at that slot is big enough, value[idx] returns valid data. If the buffer is not large enough, DX guarantees value[idx] will return 0.

The request is for RenderDoc to perform bounds checking against the bound buffer, rather than what the shader declares.

Ogre 2.1 enables this optimization by default, and can be disabled by toggling "Fast Shader Build Hack" to Off. However it would be nice if RenderDoc matched what the GPU is doing.

## Environment

* RenderDoc build: v1.1
* Operating System: Any Windows
* API: D3D11

**Comment by baldurk** [comment]
Sorry but I don't plan to implement this. As you say yourself this is undefined behaviour so what you're asking is roughly bug-for-bug compatibility (or rather undefined-behaviour-for-undefined-behaviour compatibility). It might work on GPUs now, but it would be really bad if a GPU/driver combination came along that _didn't_ behave like this. Then the debugger is now lying about what's going on in a very unintuitive way.

It sucks that fxc requires hacks like this but the idea of a debugger is to be accurate and find bugs rather than hide undefined behaviour. If you find that this is guaranteed and contractual somewhere and not undefined, I'd be happy to change it, but until then I'm going to be conservative.

**Comment by darksylinc** [comment]
Ugh, in case this issue is ever raised back again:

I just opened the D3D11 spec (it's under NDA), and you're right. There's a paragraph about this. I can't say the specifics of what exactly happens due to the NDA, but I can say it's not contractually guaranteed to work as expected for all GPUs; and the debugger should not hide it.

**Comment by baldurk** [comment]
Yeh that's what I was worried about :disappointed:.

As an alternative if you want to go further down the undefined rabbit hole, you could post-patch the DXBC code to fix the constant buffer size and reflection data after compilation. It would only be a few DWORDs to change from 2 to 4096 (in this case). The hash algorithm is an open secret so you could do it (although that's obviously not recommended!) but it would be quite in-depth.

And of course, you can change renderdoc locally and maintain a patchset yourself. Not ideal but at least possible with open source.
