### ISSUE TITLE
Advanced Export features

### ISSUE THREAD

**Issue by eyewee** [baldurk/renderdoc#1086]
Hello, I'd like to know wether you are planning to implement a feature to mass export all the textures from a scene? And some more features like exporting scene geometry (into obj or some other more advanced formats rather than a .csv), preserving uv coordinates?

**Comment by zao** [comment]
I'm a bit curious to what kind of workflow one would need some of these features for when working with software that you control.

Is there any particular shortcomings in the mesh preview that would necessitate exporting to a standalone file? I've done this in the past for my own compat profile projects to inspect in a modeller, but never really seen a point in doing so for anything that RenderDoc targets.

Similarly, is there something in the texture visualiser that falls short? In something you've made yourself, you'd assumedly have most assets lying around on disk, and for anything generated I can't quite envision a workflow where you would need to indiscriminately export all referenced texture data from a capture frame.

You might find some luck in using the Python API to automate some investigations, I've got no idea how capable it is.

**Comment by baldurk** [comment]
I'd say much the same as @zao. What's the motivation behind needing a mass-export feature? It will always be lacking information compared to your original source assets.

The main reason I can think of is for ripping assets out of commercial games, which is explicitly not supported or endorsed.

**Comment by eyewee** [comment]
Well I think I should explain myself. Concerning the issue about ripping assets from commercial games, I could have simply use ninja ripper to quickly extract all textures and meshes I need, further more, here, I'm talking about Cities Skylines, which officially supports mods and you can even extract every assets by an ingame tools, so it is not about all this stuff.
What I'am interested in, is the technology of this game when it is about placing stuff of a map. So, I can create my own map with my own assets but I won't be able to get my scene outside of the game as long as the game uses its own system to place these objects on the map (and no external tool is close to what the game is capable of in terms of visual engineering).
Let me get straight to the point : We've got a commercial game where, thanks to mods, everything is made by the one who buys this game. So technically, the only think I want is coordinates of placed objects in the scene, in order to recreate the scene in a 3d editor. Basically, I'll use the game, legitimately bought, as a city builder in my 3d editor. I tought, it would save a lot of time if everything for this matter would be available in a single program as yours, so I won't have to go using a bunch of applications available on the net, to rip, texture, place objects..
I count on your comprehension.

**Comment by baldurk** [comment]
RenderDoc is a debugger for developers to use in to diagnose problems in their own programs. In no way do I support or condone capturing commercial games for any reason.

It's great that Cities Skylines provides tools for modding and/or extracting assets, but it's not my place to decide that because they've done so that any and all reverse engineering is acceptable.

**Comment by eyewee** [comment]
Sorry for this delay, well, at least, how am I actually able to open the exported csv? I've found a python script for blender but it messes up all vertexes when importing..

**Comment by baldurk** [comment]
The CSV file is just a text file, with each component of the mesh data (inputs or outputs) in a column and each vertex in a row. It's laid out exactly as you see in the mesh viewer. How you interpret it is up to you and outside the scope of RenderDoc.

As I said before I do not provide any support for ripping assets from games.
