### ISSUE TITLE
Remote hosts should remember last folder in capture file browser

### ISSUE THREAD

**Issue by gary-sweet** [baldurk/renderdoc#1094]
## Description

I believe it would be useful to have the executable file browser window (during launch) remember the last used location between runs of renderdoc. This would likely need to be remembered for local and remote connections separately.  It would make the process of starting renderdoc and launching an app from the same remote location a lot faster, for me at least. [I realise that I could use the save and load settings options, but I think remembering the last used path is still useful in addition to those.]

My current process looks like this:
- open the file browser on the remote
- make the browser window wider (I'll be going down a long way)
- 7 navigation clicks through the file system
- pick the executable

## Environment

* RenderDoc build: v1.1
* Operating System: Windows 10 UI, Embedded Linux remote server
* API: n/a

**Comment by baldurk** [comment]
This is already implemented somewhat, see `PersistantConfig::LastCapturePath` / `PersistantConfig::LastCaptureExe`.

It seems like what you're running into is that it's not applied to remote hosts, which I skipped initially because a single path doesn't make sense when you could have multiple hosts with different paths, and in the most common case of Android having a path doesn't make sense.

It should be OK though to save the last path with the remote host, and use that to start browsing each time. That way it's saved per-host.

**Comment by baldurk** [comment]
With that commit the path should now be remembered for remote hosts as well.

**Comment by gary-sweet** [comment]
Sadly, this isn't working quite right.
I'm running a qrenderdoc on Windows, connecting to a remote embedded Linux server to run the apps.

In the UI I browse to "/build/gsweet/builds/7278/bin/SaschaWillems/bin/gears" for the example.
When I re-open the browser window, it always starts back at "/" again.

Looking at the settings file, it appears that the Linux path has had an erroneous "C:" prepended to it:

    "RemoteHostList": [
        ...
        {
            "friendlyName": "",
            "hostname": "10.178.4.170",
            "lastCapturePath": "C:/build/gsweet/builds/7278/bin/SaschaWillems/bin",
            "runCommand": ""
        }
    ],

**Comment by baldurk** [comment]
My mistake, I only tested this on windows-windows and linux-linux, the Qt function I was using to get the `basename` of the path was normalising to the host operating system's path format, which broke in your case. It should work now.

**Comment by gary-sweet** [comment]
Thanks
