### ISSUE TITLE
Hangs while loading Vulkan captures from Filament sample apps (Win10 64)

### ISSUE THREAD

**Issue by robbiesri** [baldurk/renderdoc#1097]
## Description

I've been trialing Filament (https://github.com/google/filament), and was checking out the Vulkan support. Officially, the Vulkan rendering backend isn't supported on Windows, but I figured I'd start surfing through to see what bugs I could fix.

I ran into artifacts that might be related to the backend SPV->ISA compiler in the AMD driver, so I figured I'd get a RenderDoc capture and snoop around before filing a bug with AMD.

However, when I was trying to use RenderDoc to inspect captures, I found that RenderDoc was hanging when opening captures (the capture process seemed ok). I was on the stable release, so I decided to try the latest nightly. Also hung on trying to open/replay the capture.

## Repro steps
Long way:
* Clone Filament repo
* Follow [build process](https://github.com/google/filament/blob/master/README.md), except when you run CMake, add in -DFILAMENT_SUPPORTS_VULKAN=ON argument in order to enable Vulkan support for Windows.
* Run a sample, and try to capture and replay (I tried lightbulb and material_sandbox, both failed).

Shorter way:
* Use the attached repro with RenderDoc. You can right lightbulb with these arguments:
`.\lightbulb.exe -a vulkan .\assets\models\monkey\monkey.obj`

Shortest Way:
Open attached RenderDoc capture, included in the ZIP!
failing_capture.rd - I captured it with the 2018-08-28 nightly.

## Environment

* RenderDoc build: v1.1, and 2018-08-28 nightly Win64 build (https://github.com/baldurk/renderdoc/tree/76d9ddd5)
* Operating System: Windows 10 x64
* API: Vulkan
* GPU: AMD Radeon RX Vega 64
* Driver: 18.8.2 (https://www.amd.com/en/support/kb/release-notes/rn-rad-win-18-8-2)

[filament_repro.zip](https://github.com/baldurk/renderdoc/files/2333494/filament_repro.zip)

**Comment by baldurk** [comment]
As far as I can tell this is a filament bug where they have an invalid shader, containing (trimmed for clarity):

```
%float = OpTypeFloat 32
%v4float = OpTypeVector %float 4
%_runtimearr_float = OpTypeRuntimeArray %float
%_runtimearr_float_0 = OpTypeRuntimeArray %float
%gl_PerVertex = OpTypeStruct %v4float %float %_runtimearr_float %_runtimearr_float_0
%_ptr_Output_gl_PerVertex = OpTypePointer Output %gl_PerVertex
%_ = OpVariable %_ptr_Output_gl_PerVertex Output    
```

But the vulkan spec states that:

> OpTypeRuntimeArray must only be used for:
> * the last member of an OpTypeStruct that is in the StorageBuffer storage class decorated as Block, or that is in the Uniform storage class decorated as BufferBlock.
> * If the RuntimeDescriptorArrayEXT capability is supported, an array of variables with storage class Uniform, StorageBuffer, or UniformConstant, or for the outermost dimension of an array of arrays of such variables.

Neither of which is true here for an `Output` variable, nor is it valid to have two runtime arrays in a struct. This corresponds to `gl_CullDistance` and `gl_ClipDistance` in `gl_PerVertex` but they should be declared as  RenderDoc goes into an infinite loop because the array size is stored as 0xFFFFFFFF (for lack of a better 'infinite/indeterminate' value) and then it ends up looping forever trying to unroll the output signature parameters.

I'm not sure what shader compiler filament uses - worth checking it's a reasonably up to date glslang?

**Comment by robbiesri** [comment]
Thanks a bunch Baldur! I actually was hitting some validation errors re: gl_ClipDistance, but after searching online for more info about the validation complaints re: non-array ClipDistance, the general opinion was 'spurious', and I was going to chase it up later. Looks like that guidance (and myself) were wrong!

re: glslang
They're at HEAD of master right now.

Anyway, I got more work to do. Thanks for the help here, much appreciated!

**Comment by romainguy** [comment]
We use a recent version of glslang, but we've ran into a few errors around arrays/clipdistance/etc. Seems like something we should report to glslang (and possibly spirv-tools since we use their optimizer).
