### ISSUE TITLE
"No to all" option when closing .exe tab with multiple captured frames

### ISSUE THREAD

**Issue by jamiehayes** [baldurk/renderdoc#1101]
## Description

If you have a lot of captures from one run of an exe and then you close the tab or launch a new application, a confirmation box appears for each capture on the previous run. Often, I do not want to save any captures, and clicking "No" once for each capture is tedious. It would be nice if a "No to All" option was added to that message box to dismiss all remaining captures without further confirmation.

## Environment

* RenderDoc build: v1.1
* Operating System: Windows 10
* API: D3D11

**Comment by baldurk** [comment]
Done and done! When closing a connection more than one capture, it will add a 'no to all' option. Let me know if there are any issues.
