### ISSUE TITLE
RenderDoc freezes when an Android device is connected

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1102]
## Description

Sometimes RenderDoc is grayed out and doesn't respond when a remote Android device is connecting or when an Android app is launched to capture.
It happens since the QProcess hang problem fix was added (with commit faaaf7993c05b7f3fba07727da1c7fb63bf5ac28).

It seems to me that 2 threads are locked by the same **_zombieLock_** in the **ZombieWaiter(...)** or **SetupZombieCollectionHandler()** methods (posix_process.cpp), which are called inside **remoteProbe()** (MainWindow.cpp)

## Environment

* RenderDoc build: v1.x,  2018-09-11.
* Operating System: Ubuntu Linux
* Android Version: Android 7.0

**Comment by baldurk** [comment]
I don't understand what you mean that 2 threads are locked by the `zombieLock`. Do you mean that one thread is holding the lock and another is waiting, and the thread holding the lock is blocked on something else?

Can you paste the callstacks of each thread to show what the problem actually is?

**Comment by tabikati** [comment]
Yes, one thread is holding the lock and the other one is waiting. I'm sending the backtrace. They are Thread 1 and Thread 14.

[Backtrace 1.txt](https://github.com/baldurk/renderdoc/files/2379528/Backtrace.1.txt)

**Comment by baldurk** [comment]
The problem isn't threads deadlocking against each other, it's that on thread 14 the signal handler has been invoked inside malloc (holding a system lock) and then tries to malloc again inside the handler which isn't re-entrant:

```
Thread 14 (Thread 0x7fffc493a700 (LWP 28830)):
#0  __lll_lock_wait_private () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
#1  0x00007ffff310e22a in __GI___libc_malloc () at malloc.c:2911
#2  0x00007ffff3a00e78 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
... intermediate calls ...
#11 0x00007ffff6fe3537 in std::set<int, std::less<int>, std::allocator<int> >::operator= () at /usr/include/c++/5/bits/stl_set.h:268
#12 0x00007ffff6fe0310 in ZombieWaiter () at /home/tabikati/Workspace/renderdoc/renderdoc/os/posix/posix_process.cpp:84
#13 <signal handler called>
#14 _int_malloc () at malloc.c:3800
#15 0x00007ffff310e184 in __GI___libc_malloc () at malloc.c:2913
#16 0x00007ffff3a00e78 in operator new() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
... intermediate calls ...
#19 0x00007ffff621a087 in split<char> () at /home/tabikati/Workspace/renderdoc/renderdoc/strings/string_utils.h:103
#20 0x00007ffff6cd465b in Android::GetDefaultActivityForPackage () at /home/tabikati/Workspace/renderdoc/renderdoc/android/android.cpp:78#21 0x00007ffff6cd5317 in Android::StartAndroidPackageForCapture () at /home/tabikati/Workspace/renderdoc/renderdoc/android/android.cpp:193
```

Looking at the docs about this, the number of functions you can call inside a signal handler is extremely limited. I'll need to re-write the signal handler code to do use a home-grown data structure to track the PIDs, and a spin-lock because the pthreads lock isn't safe either.

It's ridiculous how much this requires just to tidy up after forked processes.

**Comment by baldurk** [comment]
That change should now only use safe functions inside the signal handler. It remains to be seen if the code itself is safe though, but from my testing at least it seems to be OK and I tried to keep it as simple as possible.

**Comment by tabikati** [comment]
It fixed the problem.
