### ISSUE TITLE
Support float data when saving textures with array slice remapping

### ISSUE THREAD

**Issue by gamax92** [baldurk/renderdoc#1103]
## Description

Whenever I save an texture from the Texture Viewer as EXR, exporting all slices, the half floats that get saved to the file do not match the values I see from the raw buffer viewer. Furthermore reopening the EXR in RenderDoc or other image applications shows that all dark colors seem to be quantized. If I try to save only a single slice then the half floats are saved properly and colors are smooth.

I also tested saving and reopening with the HDR format and the issue is also present there.

## Repro steps

View a texture of type R16G16B16A16 with multiple samples/slices  
Save it as an EXR or HDR file with 'Export All Slices' checked  

## Environment

* RenderDoc build: tested in both v1.1 and c9c51b5a
* Operating System: Windows 7
* API: D3D11

* GPU: GTX 1050 Ti
* Driver Version: 398.82

**Comment by baldurk** [comment]
Can you share a concrete repro case? I tried this on a capture I had and the EXR was saved accurately. Does it only happen on subnormal values maybe?

**Comment by baldurk** [comment]
Scratch that, I repro'd the bug just after posting - whoops.

Saving multiple slices to a format like EXR/HDR requires manual stitching to put it into a grid, and that manual stitching code only works with RGBA8 data, so it gets quantised for that process.

I should be able to write a separate path for HDR data, but I'd suggest if you want precise results you're better off saving to DDS which natively supports arrays and can just blit out the data without processing.

**Comment by gamax92** [comment]
Ahh, I wasn't aware that DDS would also work for this, it's even much simpler and easier to parse than the mess that is EXR. Thank you.

**Comment by baldurk** [comment]
Yeh I'd say DDS is definitely the better format if you can use it - it supports arrays, mips, and most resource formats that APIs use including block compressed etc, and the format is simple. The main reason to go for HDR/EXR is if you need interop with other tools.

**Comment by baldurk** [comment]
I've changed the (very simple) image processing code to upcast to RGBA 32-float data when outputting to a format that supports higher than 8bpp, that should now prevent any banding/compression issues.

I'd still recommend using DDS if you can and avoiding any of the remapping entirely, because with DDS the image data is read straight out of memory and written to disk without any change.
