### ISSUE TITLE
Failure to compile GL part on MacOS Mojave

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#1106]
## Description
```bash
[ 33%] Building CXX object renderdoc/driver/gl/CMakeFiles/rdoc_gl.dir/cgl_hooks.cpp.o
/Users/dmalyshau/Code/renderdoc/renderdoc/driver/gl/cgl_hooks.cpp:157:21: error: 'CGLCreateContext' is deprecated: first deprecated in macOS 10.14 - OpenGL API
      deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings) [-Werror,-Wdeprecated-declarations]
DECL_GL_HOOK_EXPORT(CGLCreateContext);
```
## Repro steps

Check out the source on MacOS 10.14 and build with GL support.

## Environment

* RenderDoc build: latest v1.0 branch
* Operating System: MacOS 10.14 beta-10
* API: OpenGL

**Comment by baldurk** [comment]
I've brought the GL headers in tree and stripped the deprecation warnings, so that should compile now as well as in future even if the headers are deleted entirely.
