### ISSUE TITLE
RenderDoc rendered incorrectly when replaying a captured frame for Vulkan game DawnOfWar3.

### ISSUE THREAD

**Issue by guwangfeng** [baldurk/renderdoc#1109]
Hi, I used RenderDoc v1.1 to capture a frame of Vulkan game DawnOfWar3, then replay it. Seemed RenderDoc rendered it incorrectly:

![image](https://user-images.githubusercontent.com/13742715/45737044-5d4aee80-bc1f-11e8-8e34-a1c04e7c68ac.png)

while the thumb.jpg in captured file (I use export ZIP+XML capture and check thumb.jpg in the zip file) is:

![image](https://user-images.githubusercontent.com/13742715/45737169-a69b3e00-bc1f-11e8-9cdb-9021f2c80cd7.png)

I didn't see any render error when playing the game, so it seems that it may be a capture bug or replay bug. Could you please have a look? Or should I provide additional information?

The GPU I used is AMD RX Vega. You can also see the information in the thumb.jpg.

**Comment by baldurk** [comment]
I do not provide any support for capturing commercial games in RenderDoc.
