### ISSUE TITLE
Crash using GL from library loaded RTLD_LOCAL on linux

### ISSUE THREAD

**Issue by LordOfDragons** [baldurk/renderdoc#1114]
Tested with latest stable release and nightly build from 26.9 and on 2 different computers.

Whenever running render doc with my application glXChooseVisual causes SEGFAULT on NULL pointer (applications runs without renderdoc). The code does nothing fancy:

```c++
int attrList[] = { GLX_RGBA, GLX_RED_SIZE, 8, GLX_GREEN_SIZE, 8, GLX_BLUE_SIZE, 8,
   GLX_ALPHA_SIZE, 8, GLX_DEPTH_SIZE, 24, GLX_STENCIL_SIZE, 8,
   GLX_DOUBLEBUFFER, None };
pVisInfo = glXChooseVisual( pDisplay, pScreen, attrList );
```

If I squeeze a gdb in between (running renderdoc on gdb set to run my application) it shows the SEGFAULT happens inside glXChooseVisual.

The logs from render doc look like this:
> RDOC 009091: [10:06:34]             core.cpp( 298) - Log     - RenderDoc v1.2 64-bit Development (0bad880e7296634425c9247bd16b6ec6b751b61a) loaded in replay application
> QTRD 009091: [10:06:34]       qrenderdoc.cpp(  88) - Log     - QRenderDoc initialising.
> RDOC 009110: [10:06:38]             core.cpp( 298) - Log     - RenderDoc v1.2 64-bit Development (0bad880e7296634425c9247bd16b6ec6b751b61a) capturing application
> RDOC 009110: [10:06:38]   posix_libentry.cpp(  59) - Log     - Using delay for debugger 0
> RDOC 009110: [10:06:38]   posix_libentry.cpp(  69) - Log     - Loading into /opt/testing/bin/delaunch
> RDOC 009110: [10:06:38]         gl_hooks.cpp( 191) - Log     - Registering OpenGL hooks
> RDOC 009110: [10:06:38]        glx_hooks.cpp( 749) - Log     - Registering GLX hooks
> RDOC 009110: [10:06:38]        egl_hooks.cpp( 635) - Log     - Registering EGL hooks
> RDOC 009110: [10:06:38]         vk_layer.cpp(  53) - Log     - Registering Vulkan hooks
> RDOC 009091: [10:06:39]   target_control.cpp( 535) - Log     - Got remote handshake: delaunch [9110]
> RDOC 009091: [10:06:41]    posix_network.cpp( 293) - Warning - recv: ECONNRESET: A connection was forcibly closed by a peer.
> RDOC 009091: [10:06:41]         streamio.cpp( 307) - Warning - Error reading from socket
> RDOC 009091: [10:06:41]    remote_server.cpp(1876) - Warning - Didn't get proper handshake

The last three lines repeat forever.

I've played with all the config settings available for capturing but no combination changed the behavior.

## Environment
* RenderDoc build: Stable and Nightly
* Operating System: Linux, 2 different systems (GenToo, Ubuntu 18.04)
* API: OpenGL 4.3 (system 1), OpenGL 3.3 (system 2)
* Driver: Open Source Radeon (MESA 18.1.5)

**Comment by baldurk** [comment]
Hi, can you give a small compilable sample program that will show this problem? This bug likely depends on how you're obtaining the GLX functions, how it's linked, etc. I tried a super-simple program like this:

```cpp
// gcc repro.c -lGL -lX11 -o repro

#include <GL/glx.h>
#include <stdio.h>

void main()
{
  Display *pDisplay = XOpenDisplay(NULL);
  int pScreen = 0;

  int attrList[] = { GLX_RGBA, GLX_RED_SIZE, 8, GLX_GREEN_SIZE, 8, GLX_BLUE_SIZE, 8,
    GLX_ALPHA_SIZE, 8, GLX_DEPTH_SIZE, 24, GLX_STENCIL_SIZE, 8,
    GLX_DOUBLEBUFFER, None };
  XVisualInfo *pVisInfo = glXChooseVisual( pDisplay, pScreen, attrList );
  printf("pVisInfo = %p\n", pVisInfo);
}
```

And it ran correctly, so I think there is a more specific trigger.

**Comment by LordOfDragons** [comment]
I managed to get a small test case working which shows the fail. It is linked with library loading:

repro2.cpp
```c++
// g++ -shared -o repro2.so -fPIC repro2.cpp -lGL -lX11
#include <GL/glx.h>
#include <stdio.h>
#include <stdlib.h>

extern "C" {
void InitLibrary();
}

void InitLibrary(){
  Display *pDisplay = XOpenDisplay(NULL);
  int pScreen = 0;

  int attrList[] = {GLX_RGBA, GLX_RED_SIZE, 8, GLX_GREEN_SIZE, 8, GLX_BLUE_SIZE, 8,
    GLX_ALPHA_SIZE, 8, GLX_DEPTH_SIZE, 24, GLX_STENCIL_SIZE, 8, GLX_DOUBLEBUFFER, None};
  XVisualInfo *pVisInfo = glXChooseVisual(pDisplay, pScreen, attrList);
  printf("pVisInfo = %p\n", pVisInfo);
  XFree(pVisInfo);
  XCloseDisplay(pDisplay);
}
```

repro.cpp
```c++
// g++ repro.cpp -ldl -lX11 -o repro
#include <stdio.h>
#include <stdlib.h>
#include <dlfcn.h>

typedef void (*FUNC_INITLIBRARY)(void);

int main(){
  void *handle = dlopen("repro2.so", RTLD_NOW);
  printf("handle %p\n", handle);
  FUNC_INITLIBRARY func = (FUNC_INITLIBRARY)dlsym(handle, "InitLibrary");
  printf("func %p\n", func);
  func();
  dlclose(handle);
  return 0;
}
```

Running "repro" in a terminal works. Running it in RenderDoc fails with the above mentioned symptoms.

**Comment by baldurk** [comment]
Thanks for that, I can repro now. It looks like the problem is that when `dlopen` is called without `RTLD_GLOBAL` the library _and all its dependencies_ are loaded without their exported symbols being made available for future symbol resolution. If you add `RTLD_GLOBAL` to the `dlopen` flags, it works fine for me.

That non-global behaviour is correct, but unfortunately the issue for me is that `repro2.so` loads `libGL` and calls functions in it, without `librenderdoc` ever either getting a handle directly - as it would if you called `dlopen("libGL")` - or being able to look up symbols with `RTLD_NEXT`. So when you call `glXChooseVisual` it calls into renderdoc's pass-through hook, but I'm not able to get the real symbol, and it segfaults.

I think I should be able to fix this, I already intercept `dlopen` so I think I'll need to check after each call to see if a library has been loaded, and if so grab a handle to it directly.

**Comment by LordOfDragons** [comment]
Unfortunately I need the non-global version to avoid symbol-clashes (for example two modules loading similar libpng for different purposes). Would be nice if the problem could be solved for the non-global case albeit more difficult to handle.

EDIT: Deleted the work-around. It was not working as I thought it would so better remove false info than make others trip over it.

**Comment by LordOfDragons** [comment]
Note for other people running into this problem and that do not want to wait until a fix is out, you can use this work-around:
- In RenderDoc open Environment Variables and add this variable: name="LD_PRELOAD" value="/usr/lib/x86_64-linux-gnu/libGL.so.1.0.0" (find the libGL on your system).
Doing so will force loading the GL library before the application runs and thus allows render doc to hook into it albeit loaded later on by a module.

**Comment by baldurk** [comment]
Yep I understand that you need local libraries for some cases, like I say it's perfectly valid and makes sense I just wanted to explain out the problem. I believe I have a fix for local library loads, I'll push it shortly.

**Comment by baldurk** [comment]
I believe that fix should address it - it works in a test of the repro above. If you find that you run into side-effects on a full program please let me know.

**Comment by LordOfDragons** [comment]
Tested the fix. It is working for the repro and my application.
