### ISSUE TITLE
IvyBridge crashes when capturing

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#112]
Seems to be happening inside the `Present()` call.

[Mini-dump](https://gist.github.com/kvark/1d937bf7f58cfdda6cdc/raw/d1e8aa5afaacbded274210b907c2cf399b9a56ae/IvyBridge-Present-Crash.zip)

System Info:
```
Windows 7 build 7601, 64-bit DEP enabled
Num Processors: 4
Memory: 8073MB
System BIOS: American Megatrends Inc. ACRVMBY1.86C.0062.B00.1109261227 (09/26/2011)
Video BIOS: 08/03/20
Driver 0:
     Device: Intel(R) HD Graphics 4000
     Provider: Intel Corporation
     Date: 5-17-2014
     Version: 10.18.10.3621
     VendorId: 8086
     ProductId: 166
     Stepping: 4
     Supports GPA Instrumentation
Install directory: C:\Intel\INDE\GPA\2014 R4\
Version: 14.4.235065
Current user is in Administrators group: YES
Current Graphics Performance Analyzers 2014 R4 (14.4.235065)
Secure Boot/Trusted Boot is Disabled
```

**Comment by baldurk** [comment]
Closing this issue as I'm not sure there's much to make of it anymore. I've certainly tested RenderDoc on other Intel hardware without problem, and I've also encountered more than one driver bug - which might explain this crash.
