### ISSUE TITLE
Library loading issue on Linux

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1120]
## Description

OpenGL ES and Vulkan desktop applications crash when launched to capture on Linux since this commit was added: https://github.com/baldurk/renderdoc/commit/6f1a458c8af7dcb47e38fd1f48a8e6f99992bece

We got an infinite loop when **CheckLoadedLibraries** method is called inside **intercept_dlopen** because **realdlopen** in **CheckLoadedLibraries** calls **intercept_dlopen** again.

Please find the backtraces here:
https://gist.github.com/tabikati/7877a8c544032c1f503da249097f7a76
https://gist.github.com/tabikati/34f0357cafbcde6b8369d3c2345fcc5d

## Environment

* RenderDoc build: v1.x, 2018-10-04.
* Operating System: Ubuntu Linux
* API: OpenGL ES, Vulkan

**Comment by baldurk** [comment]
I couldn't reproduce this locally, can you please test if that commit fixes the problem? It should hopefully prevent the callbacks from recursing.

**Comment by tabikati** [comment]
It has fixed the problem for GLES but still not good with Vulkan.

**Comment by baldurk** [comment]
Can you test again with that commit please? It should hopefully prevent early processing of loaded libraries while inside the real dlopen somewhere.

**Comment by tabikati** [comment]
It works fine now, thank you!
