### ISSUE TITLE
Vulkan: secondary command buffers inputs aren't captured correctly

### ISSUE THREAD

**Issue by jonathansty** [baldurk/renderdoc#1123]
## Description
When making a capture of a frame that executes a secondary command buffer using `vkCmdExecuteCommands`. The vertex buffer and index buffer are not captured correctly.

I filled both a index and vertex buffer with 200 elements and then made a capture drawing using the index and vertex buffer.

## Repro steps
1. Create a primary command buffer
2. Create a secondary command buffer that calls `vkCmdDrawIndexed` 
3. Make a capture
4. Look at the 'Vertex Input' pipeline state and open the index and vertex buffer.  Observe incorrect data being present 

I've verified that in NVIDIA nsight the data is correct. In my case I had filled my index buffer with elements ranging from 0 - 200 which was correct in nsight but incorrect in renderdoc. 

*Note: This happens on both Linux and Windows. *

## Environment

* RenderDoc build: V1.1 (built from c7d5aa86)
* Operating System: Windows 10 and Pop!_OS
* API: Vulkan
* gpu: GTX 1080 Ti

**Comment by baldurk** [comment]
Can you provide more information about your specific scenario? E.g. can you provide a copy of the application that fails to capture correctly? I'll need more information to reproduce the problem.

What you've described is quite general, and e.g. [Sascha Willems' multithreading example](https://github.com/SaschaWillems/Vulkan/tree/master/examples/multithreading) uses index and vertex buffers on secondary command buffers and it captures fine for me. Can you capture that successfully on your end?

**Comment by jonathansty** [comment]
@baldurk I would be willing to make my code public although I doubt it would be very useful seeing as it's written in Rust using a library called `vulkano`. 

It seems that it captures correctly in some cases for me. So I'm starting to think either something in `vulkano` is incorrectly submitting buffers or I'm doing something wrong with vulkan overall.

I'll try to outline the situation a bit more: 
I've got a render pass that has :
* 5 attachments
* 3 subpasses
    * Deferred
    * Composition
    * post processing stuff

Basically I'm trying to render IMGUI in the post processing subpass on top of everything else. Pseudo code looks like this for the rendering: 
```
// Create secondary command buffer
// For each list in the draw_data 
    // Update Vertex buffer
    // Update Index buffer

    // For each command in the imgui cmd buffer
        // Get the correct index buffer slice
        // bind vertex buffer
        // bind index buffer
        // draw indexed
```
Then the resulting command buffer will be added to our primary buffer using `vkCmdExecuteCommands`. 

Another thing I noticed is that the Attributes also don't match the vertex layout I give it. 
If you want I can make my project public so you can have a look at it although I don't know how familiar you are with rust.


Edit: I just noticed it seems to be using the wrong pipeline, it's using the pipeline of a previous event so it might be something more related to the libraries I'm using.

Disabling all primary command buffer draws seems to bind the right pipeline and this also fixes the wrong buffer issue. In the example of Sascha there is only secondary command buffer draws being executed while I'm doing both draws in the primary (before the secondary gets executed) and then have a secondary buffer do draws.

My suspicion was correct: moving everything to secondary command buffers that involves the drawing seems to bind the correct pipeline. 

Would you know of any examples that draw in both the primary and the secondary buffers?

**Comment by baldurk** [comment]
Having a reproducible test case is very helpful to me because then I'm able to run exactly what you are and see if I can find the problem. It doesn't matter what language or library the program is using. I'm not at all familiar with rust but that's fine, I don't even necessarily need to look at the source I just need to be able to compile it and run it - which I think I can do with rust.

**Comment by jonathansty** [comment]
Sure, You can find the code in this [repo](https://github.com/jonathansty/Rust-Experiments/tree/master/playground). 

To build and run you will first need to get the rust toolchain. (https://www.rust-lang.org/)
then execute: 
```
cargo run
```
in the playground folder.

It's quite messy code as it's a test project for learning rust and experimenting with things. The main thing you need to know is that the rendering code is in *main.rs* . 

To test both cases either comment/uncomment lines 905-906 or line 912-918. Make sure only one of these blocks is uncommented though.

**Comment by zao** [comment]
@jonathansty I gave building it a try to see if it worked, needs a bit of love.

Note that your `cargo.yaml` refers to your local checkouts of the vulkano repo.
The upstream repo commented out in the file doesn't have your changes to debug markers and have moved on with naming for other things.
I had to alter it to use your `debug_markers` branch of your fork of their repo.
```
vulkano = { git="https://github.com/jonathansty/vulkano.git", branch="debug_markers" }
vulkano-win = { git="https://github.com/jonathansty/vulkano.git", branch="debug_markers" }
vulkano-shader-derive = { git="https://github.com/jonathansty/vulkano.git", branch="debug_markers" }
```

Now when it finally runs, regardless of which lines I have commented out in main.rs, I panic with `AutoCommandBufferBuilderContextError(WrongSubpassType)`.

Traceback for the first case:
```
C:\Scratch\Rust-Experiments\playground>cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target\debug\playground.exe`
20:14:25 [INFO] Initialized logger.
VUID-VkDebugUtilsMessengerCreateInfoEXT-sType-sType(ERROR / SPEC): msgNum: 1138929675 - vkCreateDebugUtilsMessengerEXT: parameter pCreateInfo->sType must be VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT. The spec valid usage text states 'sType must be VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VUID-VkDebugUtilsMessengerCreateInfoEXT-sType-sType)
    Objects: 1
       [0] 0x0, type: 0, name: (null)
Validation(ERROR): msg_code: 1138929675:  [ VUID-VkDebugUtilsMessengerCreateInfoEXT-sType-sType ]  [ VUID-VkDebugUtilsMessengerCreateInfoEXT-sType-sType ] Object: VK_NULL_HANDLE (Type = 0) | vkCreateDebugUtilsMessengerEXT: parameter pCreateInfo->sType must be VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT. The spec valid usage text states 'sType must be VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VUID-VkDebugUtilsMessengerCreateInfoEXT-sType-sType)
20:14:26 [INFO] Power saving not active.
20:14:26 [INFO] Using device: GeForce GTX 1080
20:14:26 [INFO] Guessed window DPI factor: 1.25
20:14:26 [DEBUG] playground::render: Making swapchain with: [1000, 750] Opaque B8G8R8A8Unorm
20:14:26 [DEBUG] playground: Window resized: LogicalSize { width: 800.0, height: 600.0 }
20:14:26 [DEBUG] playground: Recreating swapchain [1000, 750]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AutoCommandBufferBuilderContextError(WrongSubpassType)', libcore\result.rs:945:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   4: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   5: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:390
   8: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:325
   9: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:77
  10: core::result::unwrap_failed<vulkano::command_buffer::auto::DrawError>
             at C:\projects\rust\src\libcore\macros.rs:26
  11: core::result::Result<vulkano::command_buffer::auto::AutoCommandBufferBuilder<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::auto::DrawError>::unwrap<vulkano::command_buffer::auto::AutoCommandBufferBuilder<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>,vulkano::command_buffer::auto::DrawError>
             at C:\projects\rust\src\libcore\result.rs:782
  12: playground::main
             at .\src\main.rs:904
  13: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  14: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  15: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  16: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  17: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  18: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  19: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  20: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  21: main
  22: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  23: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  24: BaseThreadInitThunk
  25: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\playground.exe` (exit code: 101)

C:\Scratch\Rust-Experiments\playground>
```

**Comment by jonathansty** [comment]
@zao  agh, sorry about that. I didn't really plan on making the repo public seeing as I was mostly using it to try out things and also work in vulkano at the same time requiring me to have a local checkout. I'm not sure if rust has a way for me to s

I've pushed a fix for that crash, it seems I forgot the set the correct mode for the subpass command buffer recording (inline vs secondary).

**Comment by baldurk** [comment]
I see the problem, it's not that the buffers have the wrong data it's that the wrong buffers are bound entirely.

When tracking the current state I'm looking at state changes in both the selected primary and selected secondary command buffers when replaying. But this means that the current state depends on what order the primary and secondary are recorded in. In this application the primary state setting happens afterwards (which is not unusual) so it incorrectly overrides what's considered the current state.

I'll need to add better filtering in, so that if the secondary command buffer is selected then the relevant state is only taken from that command buffer. Things like current renderpass and framebuffer will still need to be taken from the primary.

**Comment by baldurk** [comment]
That commit should now correctly track renderstate changes only within the secondary command buffer, except the current renderpass/subpass which happens in the primary.
