### ISSUE TITLE
DX11: cannot save one-channel regular texture as-is

### ISSUE THREAD

**Issue by gegogi** [baldurk/renderdoc#1124]
## Description

I have an R8 format render target image.
I tried to save it as a BMP file using TextureSave API but it resulted in an RGB color image.
I ran renderdoc using debugger to figure out the reason and got the following result. ( Please see the attached image. )
I am trying to sort all textures from my capture to investigate which texture is unexpectedly big by the way.

## Environment

* RenderDoc 2018-10-16 nightly build.
* Operating System:  Windows 10 64bit
* API: D3D11

![image](https://user-images.githubusercontent.com/639708/46592010-d2606400-caf9-11e8-95bc-1aa34a06c2e6.png)

**Comment by baldurk** [comment]
I'm not sure what is the problem exactly. Most file formats including BMP don't support complex texture formats, so yes it get expanded to RGB and perhaps reduced down to 8-bit per channel, but the original data should still exist as-is in the red channel for R8_UNORM. Are you seeing it getting lost or changed?

If you want to save a texture with its original format I recommend DDS which can support all D3D formats.

If you're trying to find the largest texture I'd recommend using the python API to [get all textures](https://renderdoc.org/docs/python_api/qrenderdoc/main.html#qrenderdoc.CaptureContext.GetTextures), then look at the [byteSize field](https://renderdoc.org/docs/python_api/renderdoc/enums_data.html#renderdoc.TextureDescription.byteSize), which accounts for arrays, mips, etc. That way you don't actually have to save every texture to disk.

**Comment by gegogi** [comment]
As you said, there is no information lost.
I wanted to save R8 textures into a format as similar as possible to the internal format so that I can browse all the texture files and compare them in approximate internal size at the same time.
I just realized that DDS file also support uncompressed format. Thanks.
