### ISSUE TITLE
Feature request: Access DebugName via python API

### ISSUE THREAD

**Issue by gegogi** [baldurk/renderdoc#1125]
## Description

RenderDoc displays DebugName ( e.g. set by SetPrivateData() in DX11 ) of a resource in GUI.
But it seems there is no way to access it from python.
It will be helpful to debug textures if, say, there is TextureDescription.debugName attribute.

**Comment by baldurk** [comment]
The debug name is accessible via the `ResourceDescription`, it's separated out to allow naming other objects like shaders, pipelines, etc, as well as to allow the dynamic renaming that the UI can do. Anything with a `ResourceId` has a `ResourceDescription`.

To access it within the UI you can call [`pyrenderdoc.GetResourceName()`](https://renderdoc.org/docs/python_api/qrenderdoc/main.html#qrenderdoc.CaptureContext.GetResourceName) to directly fetch the name from the UI - this also looks up the dynamic list of resource names that the user can rename at runtime.

If you're using the renderdoc API directly without the UI, you'd need to call and cache [`ReplayController.GetResources()`](https://renderdoc.org/docs/python_api/renderdoc/main_ifaces.html#renderdoc.ReplayController.GetResources) which is a list of all resources, then look up the matching description by `resourceId`.
