### ISSUE TITLE
Build fails with Ninja

### ISSUE THREAD

**Issue by nhaehnle** [baldurk/renderdoc#1126]
## Description

For CMake-based projects, ninja is increasingly the preferred replacement for make at least on Linux, for various reasons, and attempting to build RenderDoc with it currently simply fails.

## Repro steps

1. Configure cmake as usual, adding the `-GNinja` option to select the Ninja generator (as opposed to the Makefile generator)
2. Run `ninja` instead of `make`.
3. Observe the error: 
>   ninja: error: build.ninja:2690: bad $-escape (literal $ must be written as $$)

## Environment

* Ubuntu 18.04 with the standard development packages (cmake version 3.10.2, ninja version 1.8.2)

**Comment by baldurk** [comment]
I remember seeing someone hit this before. The problem IIRC is the use of `$(MAKE)` to inherit make parameters like parallel jobs which confuses ninja. The only fix I'm aware of is to change it to `${MAKE}` but that breaks compilation with normal `make`.

If there's a simple change that's compatible with both then let me know and I don't mind making it, but at the moment I only consider `make` officially supported so if other build environments break it's not something I'm going to look into fixing.

**Comment by baldurk** [comment]
Closing this issue, `ninja` is not supported at present and `make` works as expected. PRs that add ninja support with minimal disruption are welcome but it's not something I'm going to look at.
