### ISSUE TITLE
[VK] Invalid usage of VK_SHARING_MODE_CONCURRENT in Prepare_InitialState

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#1135]
https://github.com/baldurk/renderdoc/blob/c05f821235b6d2220926f1fe73a5284bfede0923/renderdoc/driver/vulkan/vk_initstate.cpp#L452-L456 

This chunk of code may break the valid usage of VkBufferCreateInfo, when physical device have only one queue. Vulkan spec says: 

> If sharingMode is VK_SHARING_MODE_CONCURRENT, queueFamilyIndexCount must be greater than 1

If there is only one queue available, `sharingMode` should be set to `VK_SHARING_MODE_EXCLUSIVE`

**Comment by baldurk** [comment]
Looks like this should be an easy enough fix, since in the case of only one queue we don't need `CONCURRENT` at all.

**Comment by baldurk** [comment]
As mentioned I made it conditionally set the sharing mode to `EXCLUSIVE` in this degenerate case, to be spec compliant.
