### ISSUE TITLE
qrenderdoc crashes on Linux

### ISSUE THREAD

**Issue by martinsustek** [baldurk/renderdoc#1142]
Hello,

On Linux, I've tried the latest stable, nightlybuild and also custom built version - QRenderDoc v1.2 (e8272626b28a6b2cd04da9ef830fec0b55072d26)

It successfully launched our Unity based OpenGL game (Planet Nomads), I've managed to take captures, but when I try to doubleclick on captured thubnail or open saved capture, it crashes. How can I help you to debug this?

$ ./qrenderdoc
Log     - QRenderDoc initialising.
Gtk-Message: 14:18:12.254: GtkDialog mapped without a transient parent. This is discouraged.
Log     - Opening RDCFile /home/martin/Plocha/pn.rdc
Log     - Opening RDCFile /home/martin/Plocha/pn.rdc
Log     - Checking enabled extensions, running as OpenGL 4.5
Log     - Emulating EXT_direct_state_access
Log     - Running GL replay on: X.Org / AMD Radeon (TM) R9 390 Series (HAWAII, DRM 3.26.0 AMD 18.30 , 4.15.0-38-generic, LLVM 6.0.1) / 4.5 (Core Profile) Mesa 18.1.0-rc4
Log     - [0]: GL_AMD_conservative_depth, [1]: GL_AMD_draw_buffers_blend, [2]: GL_AMD_performance_monitor, [3]: GL_AMD_pinned_memory, [4]: GL_AMD_seamless_cubemap_per_texture, [5]: GL_AMD_shader_stencil_export, [6]: GL_AMD_shader_trinary_minmax, [7]: GL_AMD_vertex_shader_layer, [8]: GL_AMD_vertex_shader_viewport_index, [9]: GL_ANGLE_texture_compression_dxt3, [10]: GL_ANGLE_texture_compression_dxt5, [11]: GL_ARB_ES2_compatibility, [12]: GL_ARB_ES3_1_compatibility, [13]: GL_ARB_ES3_2_compatibility, [14]: GL_ARB_ES3_compatibility, [15]: GL_ARB_arrays_of_arrays, [16]: GL_ARB_base_instance, [17]: GL_ARB_bindless_texture, [18]: GL_ARB_blend_func_extended, [19]: GL_ARB_buffer_storage, [20]: GL_ARB_clear_buffer_object, [21]: GL_ARB_clear_texture, [22]: GL_ARB_clip_control, [23]: GL_ARB_color_buffer_float, [24]: GL_ARB_compressed_texture_pixel_storage, [25]: GL_ARB_compute_shader, [26]: GL_ARB_compute_variable_group_size, [27]: GL_ARB_conditional_render_inverted, [28]: GL_ARB_conservative_depth, [29]: GL_ARB_copy_buffer, [30]: GL_ARB_copy_image, [31]: GL_ARB_cull_distance, [32]: GL_ARB_debug_output, [33]: GL_ARB_depth_buffer_float, [34]: GL_ARB_depth_clamp, [35]: GL_ARB_derivative_control, [36]: GL_ARB_direct_state_access, [37]: GL_ARB_draw_buffers, [38]: GL_ARB_draw_buffers_blend, [39]: GL_ARB_draw_elements_base_vertex, [40]: GL_ARB_draw_indirect, [41]: GL_ARB_draw_instanced, [42]: GL_ARB_enhanced_layouts, [43]: GL_ARB_explicit_attrib_location, [44]: GL_ARB_explicit_uniform_location, [45]: GL_ARB_fragment_coord_conventions, [46]: GL_ARB_fragment_layer_viewport, [47]: GL_ARB_fragment_shader, [48]: GL_ARB_framebuffer_no_attachments, [49]: GL_ARB_framebuffer_object, [50]: GL_ARB_framebuffer_sRGB, [51]: GL_ARB_get_program_binary, [52]: GL_ARB_get_texture_sub_image, [53]: GL_ARB_gpu_shader5, [54]: GL_ARB_gpu_shader_fp64, [55]: GL_ARB_gpu_shader_int64, [56]: GL_ARB_half_float_pixel, [57]: GL_ARB_half_float_vertex, [58]: GL_ARB_indirect_parameters, [59]: GL_ARB_instanced_arrays, [60]: GL_ARB_internalformat_query, [61]: GL_ARB_internalformat_query2, [62]: GL_ARB_invalidate_subdata, [63]: GL_ARB_map_buffer_alignment, [64]: GL_ARB_map_buffer_range, [65]: GL_ARB_multi_bind, [66]: GL_ARB_multi_draw_indirect, [67]: GL_ARB_occlusion_query2, [68]: GL_ARB_pipeline_statistics_query, [69]: GL_ARB_pixel_buffer_object, [70]: GL_ARB_point_sprite, [71]: GL_ARB_polygon_offset_clamp, [72]: GL_ARB_program_interface_query, [73]: GL_ARB_provoking_vertex, [74]: GL_ARB_query_buffer_object, [75]: GL_ARB_robust_buffer_access_behavior, [76]: GL_ARB_robustness, [77]: GL_ARB_sample_shading, [78]: GL_ARB_sampler_objects, [79]: GL_ARB_seamless_cube_map, [80]: GL_ARB_seamless_cubemap_per_texture, [81]: GL_ARB_separate_shader_objects, [82]: GL_ARB_shader_atomic_counter_ops, [83]: GL_ARB_shader_atomic_counters, [84]: GL_ARB_shader_ballot, [85]: GL_ARB_shader_bit_encoding, [86]: GL_ARB_shader_clock, [87]: GL_ARB_shader_draw_parameters, [88]: GL_ARB_shader_group_vote, [89]: GL_ARB_shader_image_load_store, [90]: GL_ARB_shader_image_size, [91]: GL_ARB_shader_objects, [92]: GL_ARB_shader_precision, [93]: GL_ARB_shader_stencil_export, [94]: GL_ARB_shader_storage_buffer_object, [95]: GL_ARB_shader_subroutine, [96]: GL_ARB_shader_texture_image_samples, [97]: GL_ARB_shader_texture_lod, [98]: GL_ARB_shader_viewport_layer_array, [99]: GL_ARB_shading_language_420pack, [100]: GL_ARB_shading_language_packing, 
Log     - [101]: GL_ARB_sparse_buffer, [102]: GL_ARB_stencil_texturing, [103]: GL_ARB_sync, [104]: GL_ARB_tessellation_shader, [105]: GL_ARB_texture_barrier, [106]: GL_ARB_texture_buffer_object, [107]: GL_ARB_texture_buffer_object_rgb32, [108]: GL_ARB_texture_buffer_range, [109]: GL_ARB_texture_compression_bptc, [110]: GL_ARB_texture_compression_rgtc, [111]: GL_ARB_texture_cube_map_array, [112]: GL_ARB_texture_filter_anisotropic, [113]: GL_ARB_texture_float, [114]: GL_ARB_texture_gather, [115]: GL_ARB_texture_mirror_clamp_to_edge, [116]: GL_ARB_texture_multisample, [117]: GL_ARB_texture_non_power_of_two, [118]: GL_ARB_texture_query_levels, [119]: GL_ARB_texture_query_lod, [120]: GL_ARB_texture_rectangle, [121]: GL_ARB_texture_rg, [122]: GL_ARB_texture_rgb10_a2ui, [123]: GL_ARB_texture_stencil8, [124]: GL_ARB_texture_storage, [125]: GL_ARB_texture_storage_multisample, [126]: GL_ARB_texture_swizzle, [127]: GL_ARB_texture_view, [128]: GL_ARB_timer_query, [129]: GL_ARB_transform_feedback2, [130]: GL_ARB_transform_feedback3, [131]: GL_ARB_transform_feedback_instanced, [132]: GL_ARB_transform_feedback_overflow_query, [133]: GL_ARB_uniform_buffer_object, [134]: GL_ARB_vertex_array_bgra, [135]: GL_ARB_vertex_array_object, [136]: GL_ARB_vertex_attrib_64bit, [137]: GL_ARB_vertex_attrib_binding, [138]: GL_ARB_vertex_shader, [139]: GL_ARB_vertex_type_10f_11f_11f_rev, [140]: GL_ARB_vertex_type_2_10_10_10_rev, [141]: GL_ARB_viewport_array, [142]: GL_ATI_blend_equation_separate, [143]: GL_ATI_meminfo, [144]: GL_ATI_texture_float, [145]: GL_ATI_texture_mirror_once, [146]: GL_EXT_abgr, [147]: GL_EXT_blend_equation_separate, [148]: GL_EXT_depth_bounds_test, [149]: GL_EXT_draw_buffers2, [150]: GL_EXT_draw_instanced, [151]: GL_EXT_framebuffer_blit, [152]: GL_EXT_framebuffer_multisample, [153]: GL_EXT_framebuffer_multisample_blit_scaled, [154]: GL_EXT_framebuffer_sRGB, [155]: GL_EXT_memory_object, [156]: GL_EXT_memory_object_fd, [157]: GL_EXT_packed_depth_stencil, [158]: GL_EXT_packed_float, [159]: GL_EXT_pixel_buffer_object, [160]: GL_EXT_polygon_offset_clamp, [161]: GL_EXT_provoking_vertex, [162]: GL_EXT_semaphore, [163]: GL_EXT_semaphore_fd, [164]: GL_EXT_shader_integer_mix, [165]: GL_EXT_texture_array, [166]: GL_EXT_texture_compression_dxt1, [167]: GL_EXT_texture_compression_rgtc, [168]: GL_EXT_texture_compression_s3tc, [169]: GL_EXT_texture_filter_anisotropic, [170]: GL_EXT_texture_integer, [171]: GL_EXT_texture_mirror_clamp, [172]: GL_EXT_texture_sRGB, [173]: GL_EXT_texture_sRGB_decode, [174]: GL_EXT_texture_shared_exponent, [175]: GL_EXT_texture_snorm, [176]: GL_EXT_texture_swizzle, [177]: GL_EXT_timer_query, [178]: GL_EXT_transform_feedback, [179]: GL_EXT_vertex_array_bgra, [180]: GL_IBM_multimode_draw_arrays, [181]: GL_KHR_blend_equation_advanced, [182]: GL_KHR_context_flush_control, [183]: GL_KHR_debug, [184]: GL_KHR_no_error, [185]: GL_KHR_robust_buffer_access_behavior, [186]: GL_KHR_robustness, [187]: GL_MESA_pack_invert, [188]: GL_MESA_shader_integer_functions, [189]: GL_MESA_texture_signed_rgba, [190]: GL_NVX_gpu_memory_info, [191]: GL_NV_conditional_render, [192]: GL_NV_depth_clamp, [193]: GL_NV_packed_depth_stencil, [194]: GL_NV_texture_barrier, [195]: GL_NV_vdpau_interop, [196]: GL_OES_EGL_image, [197]: GL_S3_s3tc, 
Log     - Function pointers available:
Log     - 1111111111111111111111111111111111111111111111111111111111111111
Log     - 1111111111111111111111111111111111111111111111111111111111111111
Log     - 1111111111111111111111111111111111111111111111111111111111111111
Log     - 1111111111111111111111111111111111111111111111111111111111111111
Log     - 1111111111111111111111111111111111111111111111111111111111111111
Log     - 1111111111111111111111111111111111111111111111111111111111111111
Log     - 1111111111111111111111111111111111111111111111111111111111111111
Log     - 1111111111111111111111111111111111111111111111111111111111111111
Log     - 1111111111111111111111111111111111111111111111111111111111111111
Log     - 1111111111111111111111111111111111111111111111111111111111111111
Log     - 1111111111111111111111111111111111111111111111111111111111111111
Log     - 1111111111111111111111111111111111111111111111111111111111111111
Log     - 1111111111111111111111111111111111111111111111110000000000000000
Log     - Created OpenGL replay device.
Log     - Vendor checks for 45 (X.Org / AMD Radeon (TM) R9 390 Series (HAWAII, DRM 3.26.0 AMD 18.30 , 4.15.0-38-generic, LLVM 6.0.1) / 4.5 (Core Profile) Mesa 18.1.0-rc4)
Warning - FBOs are shared on this implementation
Log     - GLSL version 450
Log     - AMD GPU detected - trying to initialise AMD counters
Warning - AMD GPU performance counters could not be initialized successfully. Are you missing the DLLs?
Log     - Created replay driver.
Neoprávněný přístup do paměti (SIGSEGV) (core dumped [obraz paměti uložen])

**Comment by baldurk** [comment]
Can you share the capture file that causes the crash? Or the program itself that you're capturing? I'll need information to be able to reproduce the problem in order to investigate.

If you can't, then can you use gdb to get a callstack of where the crash happens? In case it's a driver issue it would be worth updating to the latest version mesa.

**Comment by martinsustek** [comment]
Thank you for your answer. I am newbie with gdb, but was able to get this:

Thread 12 "si_shader:1" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc0c1e700 (LWP 23604)]
0x00007fffb9c3db40 in LLVMTypeOf () from /opt/amdgpu/lib/x86_64-linux-gnu/libLLVM-6.0.so

It really seems like a driver issue, I have uninstalled amdgpu and with xubuntu vanilla driver it works.

I am not sure, if you are able to debug it without proper hardware. If you are still interested, here is the crashing file: https://mega.nz/#!xihVmYYK!yAd1U6BGsBGxVpvZprlft41PNbCJcR3IAye4u4rVXzQ

**Comment by baldurk** [comment]
Thanks for sharing the capture. I can load it fine on my RX 480 with the default ubuntu 18.04 drivers:

`X.Org / AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.23.0 / 4.15.0-36-generic, LLVM 6.0.0) / 4.5 (Core Profile) Mesa 18.0.5`

As well as recently built drivers from the tip of mesa's respository:

`X.Org / AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.23.0, 4.15.0-36-generic, LLVM 6.0.0) / 4.5 (Core Profile) Mesa 18.3.0-devel (git-edf38019a0)`

So my guess is that this is indeed a driver bug, possibly one that has since been fixed. If it works for you without a custom driver build then you could if you want maybe try a more recent release (18.1.0-rc4 isn't the latest stable mesa), or else file a bug with mesa, but it doesn't look like there's anything to do from my side.
