### ISSUE TITLE
OpenGL DSA: Show actual entry-point names being used!

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [baldurk/renderdoc#1149]
## Description

My engine supports OpenGL 4.3 in non-DSA, EXT_DSA, ARB_DSA variants.

It emulates ARB_DSA with EXT_DSA or the plain glGetInteger, glBind*, modify, glBind* old.

The problem is that RenderDoc API explorer view reports calls like glCheckNamedFramebufferStatus as glCheckFramebufferStatus, glClearNamedFramebuffer as glClearBuffer, etc.

So its impossible for me to see which path is being used (except for the legacy emulation path, because it has the extra glBind* and glGetInteger)

I understand this is a "cosmetic" issue

## Repro steps

Run the smallest OpenGL 4.5 DSA example and capture using RenderDoc, the gl*Named* function variants will not appear as "Named" in the API explorer

## Environment

* RenderDoc build: 0.91 (because of 1.1 bug with multibind)
* Operating System: Debian Linux
* API: OpenGL 4.5 context on Nvidia 1050Ti and 1060 Mobile

**Comment by baldurk** [comment]
This was deliberately fixed in the design of the new serialisation of v1.0. Any version after v1.0 should serialise the entry point of aliased functions like that faithfully.

Please don't open bugs against older versions, particularly without testing a newer build to see if it's already been fixed.

**Comment by devshgraphicsprogramming** [comment]
>Please don't open bugs against older versions, particularly without testing a newer build to see if it's already been fixed.

Understood, forgive me.

I actually wanted to test against 1.1, and I somehow missed the fact that you have nightlies available.

**Comment by baldurk** [comment]
It's fine, no harm done! It's just that for the scope of the project and with only one active developer it doesn't make sense to have release branch management and patch releases. I just have a single main-line development, so as a result of that I can only fix bugs against the latest release.
