### ISSUE TITLE
DX11 crashes during init if renderdoc.dll is unloaded

### ISSUE THREAD

**Issue by bkaradzic** [baldurk/renderdoc#115]
After loading DLL I do RENDERDOC_GetAPIVersion check to see is DLL matching header version. If this check fails I unload RenderDoc DLL:
https://github.com/bkaradzic/bgfx/blob/master/src/renderdoc.cpp#L90

If this check fails, and RenderDoc DLL is unloaded DX11 will crash during loading DLL/initialization due to some lingering state left by RenderDoc.

**Comment by baldurk** [comment]
I'm assuming this is fixed with v0.23, so closing. If you're still having issues let me know, although as I mentioned above the goals of an injected DLL and a manually loaded DLL are kind of at odds here, so a special non-infecting voluntary build might be the way to go.
