### ISSUE TITLE
can I use Windows cmd（renderdoccmd.exe）to capture an APP in android.

### ISSUE THREAD

**Issue by z00318884** [baldurk/renderdoc#1150]
## Description
I want to use renderdoccmd.exe to capture an application api in android. Can I get it?

## Environment

* RenderDoc build: e.g. v1.1 or 2018-03-12 nightly build.
* Operating System:  Windows 10, 
* API: openGLES

**Comment by baldurk** [comment]
No, renderdoccmd does not support capturing on remote hosts at all, only replaying.

This could be supported for normal remote hosts relatively easily, but android incurs a significant complexity that I don't want to add into the command-line tool, so this would unlikely ever be supported.

**Comment by eddiedong** [comment]
> 

i think this is a good idea . how can i capture a rdc file by command line

**Comment by baldurk** [comment]
Please do not comment on old closed issues.
