### ISSUE TITLE
Problem with UE4

### ISSUE THREAD

**Issue by 18665825054** [baldurk/renderdoc#1163]
## Description
Hi baldurk,
Thanks for the wonderful tool !
When I capture a frame for a .exe generated with UE4 . It failed.
RenderDoc can launch the exe and when I press F12 , RenderDoc give me a tips that 
it captured at a centain number of frame! but when I shutdown the exe, it lost all the frames it just captured.
First,a tab "connecting " show for few seconds just beside the tap "Launch Application" and then
it closed. And everything get lost.

The RenderDoc is not the plugin for the UE4 but the native version!

## Environment

* UE4: Version: 4.20.2-4302132+++UE4+Release-4.20
* RenderDoc build: e.g. v1.1, 
* Operating System: e.g. Windows 7
* API: e.g. D3D11

**Comment by baldurk** [comment]
I will need more information to debug this, there is presumably something more specific than just launching a UE4 application which breaks it.

When the application is running and the 'connecting' tab disappears, can you then go to `File -> attach to running instance` and attach there? If you do, do the captures show up as expected?

It sounds like maybe something is causing the connection to fail. Can you paste the output log from `Help -> View Diagnostic log`? It sounds like maybe there's a problem with multiple processes - does your program use child processes?

**Comment by baldurk** [comment]
Closing this issue due to lack of information to be able to investigate. If you're able to provide more information feel free to comment here and I can open it up again.
