### ISSUE TITLE
Building for android on linux(Ubuntu) machine

### ISSUE THREAD

**Issue by gittmi** [baldurk/renderdoc#1167]
## Description

Hi,
   I am little confused about building renderdoc for android. I followed the build instructions for android and generated org.renderdoc.renderdoccmd.arm32.apk. 
To generate renderdoc executables on linux, I need to follow Linux build instructions separately. Is this correct? 
In that case How to link the generated apk file with linux host executable? Do I need to copy this apk onto connected Android device manually before capturin trace?

If I build renderdoc for linux by following Linux build instructions, will it generate/pick all the dependent files including the android apk also automatically? 

## Repro steps
Building for android:
mkdir build-android
cd build-android
cmake -DBUILD_ANDROID=On -DANDROID_ABI=armeabi-v7a ..
make

## Environment

* RenderDoc build: v1.x (latest)
* Operating System: Ubuntu Linux
* API: OpenGL

**Comment by baldurk** [comment]
The code is set up to look for the android APKs in a few places: firstly, if you have built something like this:

```
/                       # repo root
  /build                # linux build
  /build-android-arm32  # android build for arm32
  /build-android-arm64  # android build for arm64
```

Then the APKs will be automatically found and installed as normal, you'll get the same experience as a renderdoc build. Alternatively if you're only building one ABI you can build in `/build-android` and it will be installed from there, but you'll get warnings that arm64 is missing if your device supports arm64, and of course any arm64 package cannot be debugged.

Alternatively if you have your files set up like they would be installed naturally on linux, then you have

```
/                     # root of your install prefix
  /bin                # qrenderdoc in here
  /share
    /renderdoc
      /plugins
        /android      # Android APKs in here
```

This is intended to catch the two common scenarios when running on linux, the [search path code is here](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/android/android.cpp#L355-L360).

Regardless of all of that, if you want to then you can just install and run the built apk manually with something like `adb shell am start -n org.renderdoc.renderdoccmd.arm32/.Loader -e renderdoccmd remoteserver`, then the UI won't look for the APK at all, and will assume you know what you're doing and connecting to a compatible server.
