### ISSUE TITLE
RenderDoc fails to disassemble SPV (also applies to AMD disassemblies)

### ISSUE THREAD

**Issue by fredrikz** [baldurk/renderdoc#1168]
## Description
RenderDoc fails to disassemble SPIR-V 1.3 files when looking at a fragment shader. AMD assembly is also not available ("; Failed to Disassemble -") shows up for every option. spirv-dis and spirv-cross works. Current RGA can disassmble the file.

Renderdoc log is filled with:
RDOC 005996: [12:44:14] spirv_disassemble.cpp(2136) - Warning - Expected to find ID 2319 but didn't - returning dummy instruction
RDOC 005996: [12:44:14] spirv_disassemble.cpp(2136) - Warning - Expected to find ID 1512 but didn't - returning dummy instruction
RDOC 005996: [12:44:14] spirv_disassemble.cpp(2136) - Warning - Expected to find ID 2316 but didn't - returning dummy instruction
RDOC 005996: [12:44:14] spirv_disassemble.cpp(2136) - Warning - Expected to find ID 2312 but didn't - returning dummy instruction

## Repro steps
Get RenderDoc to disassemble the fragment SPV attched

## Environment
RenderDoc 1.1
Windows 10
Vulkan

[test.spv.txt](https://github.com/baldurk/renderdoc/files/2565778/test.spv.txt)

**Comment by baldurk** [comment]
Yes currently SPIR-V 1.3 is not supported as I haven't checked through it to see what I might need to support, and I plan to rewrite the current disassembly code completely as it's not really maintainable, so I'm not going to spend much time on improving it.

It looks like the latest RenderDoc with updated RGA work OK - can you check a recent nightly build to see if the GCN disassembly works OK for you?

**Comment by fredrikz** [comment]
Yes, I'll try it out tomorrow and report back

**Comment by fredrikz** [comment]
Yeah, the nightly build (2081-11-13) works fine for GCN disassembly, so I'll close this bug report.
