### ISSUE TITLE
Wpf hosting not working 

### ISSUE THREAD

**Issue by sueds** [baldurk/renderdoc#117]
Nothing is render when using wpf D3Dimage. I wondering why is that. I have my level editor and I cannot access any debug feature. 

BTW I'm using sharpdx and c#. I did test it in a winform windows and it works.

**Comment by ManIkWeet** [comment]
WPFs D3Dimage uses a shared DirectX 9 texture that DirectX 11 then renders to (in whatever way you want that to happen). It is fundamentally broken because it refreshes before your drawcalls are executed, resulting in flickering on heavy loads.

**Comment by baldurk** [comment]
Since this kind of situation won't be handled any better than it currently is (RenderDoc isn't going to support D2D or whatever else is using that texture and marking a frame boundary), I'm closing this. If there's anything else relevant feel free to reopen it.
