### ISSUE TITLE
the timeline can't  be grouped in AMD 2700x with nvidia 2080Ti.

### ISSUE THREAD

**Issue by jobgeodev** [baldurk/renderdoc#1173]
## 1173
When using laptop to debug my program, the timeline can be grouped.
Environment: (thinkpad t470 win10 i5-7200u)
![2](https://user-images.githubusercontent.com/13561917/48386411-d7ce5100-e72c-11e8-8c41-fca4d0868533.png)

But when using a new computer, the timeline can't group it.
Environment: win10 + AMD 2700x + nvidia 2080Ti
![1](https://user-images.githubusercontent.com/13561917/48386439-f03e6b80-e72c-11e8-96a6-b5d87b1073b1.png)

**Comment by baldurk** [comment]
If this is the same capture in both cases, please check `Tools` -> `Settings` -> `Event Browser` -> `Add fake markers if none present (requires capture reload)` as this is the option which controls these automatically generated marker regions. The option is on by default but perhaps you turned it off without realising.

I would recommend though that you add your own marker regions into your code as this will be *much* more useful and relevant to you than the auto-generated markers which are a very basic grouping.

**Comment by jobgeodev** [comment]
Thank you very much, this problem has been solved, because the graphics card driver is not compatible, after updating the latest driver, this problem has not reappeared, thank you again.
