### ISSUE TITLE
DXGI 1.6 is not supported

### ISSUE THREAD

**Issue by cugone** [baldurk/renderdoc#1174]
## Description

The Windows 64-bit version of RenderDoc cannot handle 64-bit applications. The application appears with a white background and closes after about 1 second instead of the normal behavior. See attached for test applications

## Repro steps

[RenderDocTests.zip](https://github.com/baldurk/renderdoc/files/2577600/RenderDocTests.zip)

1. Launch RenderDocTest32.exe from RenderDoc.
2. Observe normal as expected behavior.
3. Launch RenderDocTest64.exe from RenderDoc
4. Observe application appearing with white background for about 1 second then closes with no captures.

## Environment

* RenderDoc build: Windows 64-bit v1.1 built from c7d5aa86 (as per About window)
* Operating System: Windows 10 1809 (incl October 2018 update)
* API: D3D11
* GPU: NVIDIA GeForce GTX 980M and Intel HD Graphics 530

**Comment by baldurk** [comment]
As mentioned via email this is not a general bug affecting all 64-bit applications. The problem is that you're using DXGI 1.6, which hasn't been implemented yet. The unwrapped DXGI factory that you get back then crashes trying to initialise with a wrapped D3D11 device - I have no idea why that works on 32-bit.

**Comment by cugone** [comment]
Thanks for that clarification, I had an epiphany and figured out that this is why VS Graphical Debugger is ALSO crashing!

DXGI1.6 is really nice because getting an adapter that you expect to get is much easier with EnumAdapterByGPuPreference.

**Comment by baldurk** [comment]
Implemented support for DXGI1.6 with that commit, including `IDXGIFactory6::EnumAdapterByGpuPreference`, and the test case now runs fine in 32-bit and 64-bit.
