### ISSUE TITLE
Keep screen active while RenderDoc app is active on Android

### ISSUE THREAD

**Issue by annop-np** [baldurk/renderdoc#1178]
Please update the RenderDoc app on Android so that, while the app itself is active (and/or with active connection), the Android screen would be kept alive and do not go into sleep mode.

This can be done quite easily using the Android's Activity Window flag of the app.

Right now, if the remote debugging to an Android device continue longer than several minutes, the Android would go into sleep mode and thus terminate the connection, forcing the user to reconnect and restart everything again.

## Repro steps

1. Connect and open a captured frame on an Android device
2. Wait for several minutes, depends on the device's Sleep timer.
3. When the Android screen goes to sleep, observes that the connection is terminated and all current changes lost

## Environment

* RenderDoc build: v1.1
* Operating System: Windows 10, remote to Android 8
* API: Vulkan

**Comment by baldurk** [comment]
Ah, I think I usually set the device to keep the screen on while there's a usb connection active, but this makes sense.

> This can be done quite easily using the Android's Activity Window flag of the app.

Can you clarify this? I don't know that much about android especially the platform-specific bits. I found [this document](https://developer.android.com/training/scheduling/wakelock#screen) suggesting a call to `getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);` inside the `onCreate` method of the java bootstrap program, is that what you're meaning?

**Comment by annop-np** [comment]
Unfortunately, the device I'm running on right now have a maximum sleep time of 10 minutes, so I have to keep touching the screen to prevent it from sleeping.

And that is the flag yes.

**Comment by baldurk** [comment]
Ah, I meant the special one in developer options:

![image](https://user-images.githubusercontent.com/661798/48553724-3d107680-e8d4-11e8-92af-ee59596dd763.png)

I'll still add that flag as it will be useful for anyone who hasn't enabled that option, but that might be a useful workaround for you in the meantime (and I find it helpful in any case even when renderdoc isn't running).

**Comment by baldurk** [comment]
Added the flag, works as expected for me now to keep the screen on while in the foreground. Hopefully that should also prevent any interruptions while debugging.
