### ISSUE TITLE
Support for VK_EXT_conditional_rendering

### ISSUE THREAD

**Issue by doitsujin** [baldurk/renderdoc#1180]
Hello,

I'm currently having some trouble implementing D3D11 Predication in DXVK using the `VK_EXT_conditional_rendering` extension, so I'd like to ask for Renderdoc to support this extension if possible.

A demo that could be used for testing purposes is the "Conditional Rendering" sample in Sascha Willems' Vulkan samples.

**Comment by baldurk** [comment]
Implemented kindly by @werman in #1192, please file an issue if you notice any problems.
