### ISSUE TITLE
On windows function pointers copied to static variables can be obtained before hooking

### ISSUE THREAD

**Issue by ffelagund** [baldurk/renderdoc#1187]
## Description
We have an OpenGL 3.2, Core profile, but after several  tries and playing with the options we cannot make RenderDoc capture any draw command. All commands in the frame appear just in the SwapBuffers calll.

## Repro steps
They are hard for you to repro as it only happens with our application and we cannot distribute the source code. What we can do is provide a capture, or the application binaries. To reproduce the issue just launch the application and perform a capture.

Here is the capture: https://www.dropbox.com/s/hxrpo8g1zcyb214/a.rdc?dl=0
If it's not enough we can send the binaries.

## Environment

* RenderDoc build: v1.2,built from fa1c701c
* Operating System:  Windows 10
* API: OpenGL
* GPUs: We tried with different Geforce and Intel HD cards

Thanks!
Jacobo.

**Comment by baldurk** [comment]
The capture unfortunately isn't too informative - it's just empty as you described, there are some commands in recorded in the frame but no drawcalls.

If you're able to share the application binaries that would be very helpful, source code is sometimes useful but not needed to debug a problem like this. If you're concerned, you can share them directly to me [via email](baldurk@baldurk.org) rather than posting them here.

**Comment by ffelagund** [comment]
Mail with binaries sent! 
Hope it helps

**Comment by baldurk** [comment]
I'm reasonably sure from looking into this that it's not possible to solve without rewriting the hooking, as I don't see a way that I can patch the IAT with my own function pointers before the CRT init runs to fetch those function pointers into global variables.

The clearest alternative is to switch to trampolining/function patching which sidesteps this entirely, but brings up a lot of its own issues like incompatibility with other function patching programs like overlays which are often poorly written. I'm not sure if this case is worth fixing in that respect.

**Comment by baldurk** [comment]
Closing as above, the only fix has its own downsides and isn't worth the benefit of closing this loophole edge case.
