### ISSUE TITLE
Creating DX11.3 device succeeds when RenderDoc is present

### ISSUE THREAD

**Issue by bkaradzic** [baldurk/renderdoc#119]
My code is trying to create highest possible DX11 device, but when RenderDoc (v0.22) is present it succeeds even when GPU/OS is not capable of supporting device version.

Code here should fail on creating 11.3 and 11.2 on Win7:
https://github.com/bkaradzic/bgfx/blob/master/src/renderer_d3d11.cpp#L598

**Comment by baldurk** [comment]
I think that change should fix it so QueryInterface will only return a pointer and S_OK when the underlying device does. It works for me (although I can get a 11.2 device on Win7 it seems, I think I have that horrible KB patch that backports no useful support but still returns the ID3D11Device2), but can you check that it fixes it for you?

**Comment by bkaradzic** [comment]
This is fixed. Thanks! :+1:
