### ISSUE TITLE
Renderdoc on android for unreal engine with event name

### ISSUE THREAD

**Issue by pdlogingithub** [baldurk/renderdoc#1191]
## Description

Hi,sorry to bother,Im using renderdoc 1.1 with unreal engine project,when I capture on pc,the result will show all the function name,but when I capture on an android build on my phone,result only show the opengl function name,is there ways to view function name on android?
![image](https://user-images.githubusercontent.com/32954437/49295045-aeb10d00-f4ef-11e8-95cb-210bd4123154.png)

## Environment

renderdoc 1.1
windows 10

**Comment by baldurk** [comment]
Hi there, this isn't a RenderDoc issue. The application code (in this case UE4) must call API functions to insert these marker names. It's available for both GL and Vulkan.

I asked someone at Epic, who said that automatic enabling of these markers for android hasn't been implemented, but you should be able to enable it manually by opening the console (four finger tap) and typing `toggledrawevents`. For more information about how UE4 enables GPU markers you should check the unreal documentation or forums.

**Comment by pdlogingithub** [comment]
THANK YOU for such quick and resourceful reply!

**Comment by rachelmqxu** [comment]
Thank you Very Much!
