### ISSUE TITLE
glReadPixels call doesn't show up in API inspector

### ISSUE THREAD

**Issue by logixoul** [baldurk/renderdoc#1201]
## Description

Please see https://i.imgur.com/CNYsWfI.png .
I'm doing a glReadPixels in between the 2 glFramebufferTexture2D calls, but it doesn't show up in the list.

## Environment

* RenderDoc build: 1.2
* Operating System: Windows 10
* API: OpenGL
* GPU: Nvidia

**Comment by baldurk** [comment]
Yes this is by design, all 'get' type functions including glReadPixels are not serialised as they have no effect on the capture itself.
