### ISSUE TITLE
Build fails: error: cast from pointer to smaller type 'unsigned int' loses information

### ISSUE THREAD

**Issue by yurivict** [baldurk/renderdoc#1209]
clang-60 on FreeBSD defines ```NULL``` as ```nullptr```, based on the C++ standard, see https://en.cppreference.com/w/cpp/types/NULL. The build fails:
```
/usr/ports/devel/renderdoc/work/renderdoc-1.2/renderdoc/driver/vulkan/vk_resources.h:1007:20: error: cast from pointer to smaller type 'unsigned int' loses information
    NullResource = (unsigned int)NULL
                   ^~~~~~~~~~~~~~~~~~
```

**Comment by baldurk** [comment]
The use of `NULL` was a holdover from D3D anyway, it should have been `VK_NULL_HANDLE` which is just defined to `0` which works fine in an enum.
