### ISSUE TITLE
Doesn't build on BSD: use of undeclared identifier 'RTLD_DEEPBIND'

### ISSUE THREAD

**Issue by yurivict** [baldurk/renderdoc#1210]
There is no implementation for FreeBSD. The linux one doesn't work:

```
--- renderdoc/CMakeFiles/rdoc.dir/os/posix/linux/linux_hook.cpp.o ---
/usr/ports/devel/renderdoc/work/renderdoc-1.2/renderdoc/os/posix/linux/linux_hook.cpp:58:35: error: use of undeclared identifier 'RTLD_DEEPBIND'
    if(filename && ret && (flag & RTLD_DEEPBIND))
                                  ^
```

**Comment by baldurk** [comment]
I have no plans to support FreeBSD. If someone wants to contribute changes to support it and the changes either don't affect other platforms or are small enough as to have minimal effect I'm happy to merge them, but it will remain unsupported aside from such PRs.
