### ISSUE TITLE
Vulkan depth buffer is not visible

### ISSUE THREAD

**Issue by manhnt9** [baldurk/renderdoc#1212]
## Description

In Vulkan capturing, depth buffer is blank if the model is transformed.
With original vertex rendering (gl_Position = position;), I can see contents in depth buffer.
Tested with various Vulkan examples:
- [Sascha](https://github.com/SaschaWillems/Vulkan)'s texturing demo
- [V-EZ](https://github.com/GPUOpen-LibrariesAndSDKs/V-EZ)'s simple quad sample
- [Saga3D](https://gitlab.com/InnerPieceOSS/Saga3D/)'s mesh sample

## Repro steps
- Download and extract this [archive](https://drive.google.com/open?id=16uyf87yNLE8NxNKzq-6nS4S-qthD7Xdn) (only works in described environment)
- Capture `bin/02_triangle` application, the depth buffer will be seen as below
![screenshot_2018-12-16_14-43-09](https://user-images.githubusercontent.com/11463928/50051234-f4511500-0140-11e9-9667-a5519b6a9cf2.png)
- Capture `bin/03_mesh` application, depth buffer is blank
![screenshot_2018-12-16_14-46-07](https://user-images.githubusercontent.com/11463928/50051258-56aa1580-0141-11e9-8ffd-4594ac66b2e2.png)

Sascha's texturing example
![screenshot_2018-12-16_14-46-55](https://user-images.githubusercontent.com/11463928/50051265-7b9e8880-0141-11e9-97d1-f742c9fe1b29.png)

## Environment

* RenderDoc build: v1.2
* Operating System: Ubuntu 18.04
* API: Vulkan
* GPU: GTX 1050Ti
* Driver: NVIDIA 390.87

**Comment by baldurk** [comment]
Have you adjusted the visible range when the depth buffer is selected?

![image](https://user-images.githubusercontent.com/661798/50052735-a3c9bf80-0120-11e9-9251-5b8e1c406fdb.png)

In some programs the depth buffer usage is very narrow, e.g. in Sascha Willems' texture sample the quad is entirely within `0.99956` and `0.9997`, so shows up indistinguishable from white by default.

**Comment by manhnt9** [comment]
Solved. Not a bug. I can use a button to correct depth range. Thanks @baldurk.

![screenshot_2018-12-16_18-23-12](https://user-images.githubusercontent.com/11463928/50052996-eeb6f780-015f-11e9-90c5-4d3f4d3baa61.png)
