### ISSUE TITLE
OpenGL: Detects depth-only pass instead of a full color one

### ISSUE THREAD

**Issue by hrydgard** [baldurk/renderdoc#1215]
## Description

In my emulator project PPSSPP, in OpenGL mode, capturing the menu screen fails to capture the color part of the rendering.

## Repro steps

Repro: Download a build here: https://buildbot.orphis.net/ppsspp/ and start it. In settings, change backend to OpenGL which will cause it to restart. Then exit it, and make a capture the usual way.

Result:

![depthonly](https://user-images.githubusercontent.com/130929/50222883-e34f1080-0399-11e9-9afe-62ba63e620a0.JPG)

## Environment

* RenderDoc build: 1.2
* Operating System: Windows 10 RS5
* API: OpenGL

**Comment by baldurk** [comment]
The problem was that in this case it was having to retry the frame capture (a couple of times actually), and upon retry it wasn't properly setting up all the frame-initial stuff, in particular the details of FBO 0. So when FBO 0 was bound it was unknown, and ended up with no targets bound at all.

**Comment by hrydgard** [comment]
Hm, why did it have to retry? Anything I should fix?

**Comment by baldurk** [comment]
The error shows up in the overlay although maybe too fast in a release build - `Uncapped Map()/Unmap()`. It means you're mapping a buffer in one frame and unmapping it in another. When RenderDoc starts capturing a frame if there's a map in progress it likely wasn't intercepted so I don't have the data for it.

**Comment by hrydgard** [comment]
Oh, okay. Yeah, I think I can see how that would happen. Thanks, and thank you for the lightning fast fix!
