### ISSUE TITLE
unity: Calling Shader.WarmupAllShaders() crashes renderdoc

### ISSUE THREAD

**Issue by pixelmager** [baldurk/renderdoc#122]
Using Unity, a function that ensures all shaders have been compiled, crashes if renderdoc is injected (ie if the app is run from renderdoc).

Repro:
http://loopit.dk/ref/renderdoc_warmup_all_shaders.zip

Creating a unity-scene with a single script that contains e.g.
public class warmupscript : MonoBehaviour {
	void OnEnable() {
		Shader.WarmupAllShaders();
	}
}
- tested on amd-hardware, win8, unity4.3.

**Comment by baldurk** [comment]
I think this change should fix the issue. I don't know if you're compiling renderdoc yourself - if not then the nightly build will include it in ~10 hours.

The problem seemed to be some very oddly formatted DXBC (DX bytecode) blobs, which my parsing was choking on. I had a look and other DXBC parsers online - wine and HLSL-Cross-Compiler would also fail on this input, so I must admit I'm a little curious how it got like that. The shader in question was using a "UnityFFVertex" cbuffer if that narrows it down at all. I don't know if some odd transformation or compilation went on.

Hopefully it will all work now - the test case you provided (thank you for that!) certainly works now for me - but the joy of reverse engineering means that it might break some other time down the road :smile:.

**Comment by baldurk** [comment]
Fix verified :) https://twitter.com/pixelmager/status/560041441855279104
