### ISSUE TITLE
RenderDoc 1.0 is not taking effective on VkPipelineTessellationDomainOriginStateCreateInfoKHR.

### ISSUE THREAD

**Issue by jsnjkl** [baldurk/renderdoc#1228]
## Description
RenderDoc 1.0 is not taking effective on VkPipelineTessellationDomainOriginStateCreateInfoKHR.
VkPipelineTessellationDomainOriginStateCreateInfoKHR decides the tessellation origin, which decides the cw/ccw order of abstract tessllation. Looks like that RenderDoc 1.0 is not taking effective on VkPipelineTessellationDomainOriginStateCreateInfoKHR. If we set domainOrigin to VK_TESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT, we'll get incorrect(reversed) cw/ccw order.

## Environment

* RenderDoc 1.0.
* Operating System: Windows 10
* API: Vulkan

**Comment by baldurk** [comment]
Support for `VK_KHR_maintenance2` which includes `VkPipelineTessellationDomainOriginStateCreateInfoKHR` was not added until 1.1. In 1.0 the extension was not supported so would not have been reported to the application. A correct Vulkan application **must** enumerate the extensions available and only use those that are reported by the device.

It was implemented last year so if you use the latest version - 1.2 - it should work correctly. If there are any problems then please do open a bug about specific issues.
