### ISSUE TITLE
Validation error during load capture

### ISSUE THREAD

**Issue by jzulauf-lunarg** [baldurk/renderdoc#1230]
## Description
c.f. [Vulkan Validation Layers 547](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/547)

With validation layers enabled, during the load of a capture of:

https://github.com/Overv/VulkanTutorial/blob/master/code/29_multisampling.cpp the following error occurs.

```
Warning - [Validation:0/0]  [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated ] Object: 0x1d (Type = 23) | Descriptor set 0x1d bound as set #0 encountered the following validation error at vkCmdDraw() time: Descriptor in binding #1 at global descriptor index 1 is being used in draw but has not been updated.
```
## Repro steps
Run 29_multisampling.  Capture a frame.  Load the captured frame.  Prior to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/515 this will crash the ValidationLayers immediately after the error message.

## Environment

* RenderDoc build:  v1.2
* Operating System: Ubuntu Linux 16.04
* API:  Vulkan
* Compilers: seen with both Clang and GCC (C++17 capable required by 29_multisampling.cpp

Both the initial report and my repro were on nVidia 9 series hardware

**Comment by baldurk** [comment]
Should be fixed with that commit, for depth-only multisampled images I needed to bind a dummy stencil texture to the descriptor set. The same issue happened on capture as well if validation was enabled but it was just the mirror-version of the replay bug, so the same fix in either case.
