### ISSUE TITLE
Linux+EGL hardcodes usage to OpenGL ES

### ISSUE THREAD

**Issue by Sonicadvance1** [baldurk/renderdoc#1233]
## Description
Using an EGL application that uses OpenGL fails to capture correctly due to assumptions that anything using EGL will be use OpenGL ES.

## Repro steps
Run an application that uses a combination of OpenGL and EGL on Linux.
Watch i965 and renderdoc spam error messages during playback or capture due to assumptions that EGL = OpenGLES

## Environment

* RenderDoc build: 04ca50ba63904edd280e7bdc9595edd8bf0bd3bd
* Operating System: Ubuntu Linux 18.10
* API: OpenGL, EGL

Testing on the i965 mesa driver.
Mesa version 18.2.2
GL_RENDERER: Mesa DRI Intel(R) HD Graphics (Coffeelake 3x8 GT2)

**Comment by baldurk** [comment]
Can you provide a simple example of a program that uses OpenGL non-ES with EGL? The assumptions were there because I didn't know EGL supported GL, since wgl/glX already exists for that purpose. I tried searching around but I couldn't find one - all I could find was the reverse, using EGL to render with GLES on desktops.

**Comment by Sonicadvance1** [comment]
https://github.com/Sonicadvance1/simple_tri
This project draws a simple triangle.
Relies on the epoxy and waffle libraries.
Waffle is set up to create an OpenGL context using X11+EGL.
Also relies KHR_debug and GL 3.3 for no real reason other than quickly changing the example.

**Comment by baldurk** [comment]
Thanks for the simple & clear repro case. I added tracking of calls to `eglBindAPI` and update the used API accordingly. As long as the application calls this early before creating contexts everything should work as expected.

**Comment by Sonicadvance1** [comment]
Nice. Works perfectly for my use case.
