### ISSUE TITLE
ClearRenderTargetView (D3D12) shows the R value repeated instead of the actual RGBA value, in the event browser

### ISSUE THREAD

**Issue by Ashalah** [baldurk/renderdoc#1236]
## Description

In a D3D12 app doing ClearRenderTargetView(), the Event Browser will show the red channel clear value repeated for all channels, instead of the actual value for each channel.

Example 1:
`// RGBA 8bit texture`
`const float clearColor[] = { 0.40f, 0.40f, 0.40f, 0.0f };`
`m_commandList->ClearRenderTargetView(gameRenderTargetDescriptor, clearColor, 0, nullptr);`

displays in the event browser as:

`ClearRenderTargetView(0.400000, 0.400000, 0.400000, 0.400000)`

Example 2:
`// R32_UINT texture`
`const float objectIdClearColor[] = { 25, 0, 0, 0 };`
`m_commandList->ClearRenderTargetView(m_gameObjectIdTextureRTV, objectIdClearColor, 0, nullptr);`

displays in the event browser as:

`ClearRenderTargetView(25.000000, 25.000000, 25.000000, 25.000000)`

## Repro steps

Use any clear color that's not all 0, or is different value per channel. Render with D3D12 and call ClearRenderTargetView.

## Environment

* RenderDoc build: v1.2 (204724be)
* Operating System: Win10 64bit
* API: D3D12

Vega64, driver 18.12.3

**Comment by Ashalah** [comment]
I can email you a private capture file as well if needed.

**Comment by baldurk** [comment]
Thanks this was very clear. There was a silly copy-paste error in the function setting up the drawcall string, should be fixed with that commit.
