### ISSUE TITLE
renderdoc display incorrect texture format

### ISSUE THREAD

**Issue by horusli** [baldurk/renderdoc#1239]
## Description
there seems some issue when display texture resource detail.

for example, the texture configured is GL_COMPRESSED_RGBA8_ETC2_EAC

glGenTextures(1, {21573});
glBindTexture(GL_TEXTURE_2D, 21573);
glTextureParameteriEXTHWExt(21573, GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
glTextureParameteriEXTHWExt(21573, GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
glTextureParameteriEXTHWExt(21573, GL_TEXTURE_2D, GL_TEXTURE_BASE_LEVEL, 0);
glTextureParameteriEXTHWExt(21573, GL_TEXTURE_2D, GL_TEXTURE_MAX_LEVEL, 0);
glTextureStorage2DEXTHWExt(21573, GL_TEXTURE_2D, 1, GL_COMPRESSED_RGBA8_ETC2_EAC, 256, 256);

yet the final display format in renderdoc is 2 channl format EAC_RG_UNORM, do you guys met similiar issue before?

## Environment

* RenderDoc build: e.g. v1.2.
* Operating System: e.g. Windows 10 and Windows 7
* API: OpenGLES

**Comment by baldurk** [comment]
The code displaying the string name for formats wasn't decoding ETC2/EAC properly, it should now be corrected.
