### ISSUE TITLE
"Error launching ... for capture" "Renderdoc injection failed. ..."

### ISSUE THREAD

**Issue by nmr8** [baldurk/renderdoc#1243]
## Description

I don't seem to be able to launch my app for capture from qrenderdoc. 

When I click launch, I am presented with a dialog telling me about an error, and the process tab does not appear.

## Repro steps

Click launch. I'd like to share the app, but would prefer a private means of doing so.

## Environment

Renderdoc Version: 1.2+dfsg-1 from Debian testing
API is OpenGL, believe 3.3
Vega 64, Mesa 18.2, Linux 4.19.0-1

App does work stand-alone.
App does not set up an X window, just creates a pixmap and a context and then renders.
Launching the app does create a process which continues to run
That process has librenderdoc.so injected into it as observed via proc/pid/maps

Oddly, if I launch the app a second time from renderdoc I do not get an error. Both processes run and serve rendered images (via built in web server). I see the following console output when doing so:

```
Tectonic[void handleRequest(StitchedRenderer &, WPP::Request &, WPP::Response &):468] rendering /mt/d/0/0/0.png
Log     - Used API: OpenGL (Presenting & supported)
Tectonic[void handleRequest(StitchedRenderer &, WPP::Request &, WPP::Response &):496] rendered /mt/d/0/0/0.png in 1.77630805969238 seconds
Tectonic[void handleRequest(StitchedRenderer &, WPP::Request &, WPP::Response &):468] rendering /mt/d/0/0/0.png
Log     - Used API: OpenGL (Not presenting & supported)
Tectonic[void handleRequest(StitchedRenderer &, WPP::Request &, WPP::Response &):496] rendered /mt/d/0/0/0.png in 1.79321694374084 seconds
```

The first "Log" line is from the launch of the app that renderdoc reports the error on. The second "Log" line is from the launch of the app that creates a process tab in qrenderdoc.

**Comment by nmr8** [comment]
FWIW I suggest logging the most direct error to the diagnostic log, because all that's in there is warnings, that appear to me (the ignorant user) as irrelevant.

RDOC 028060: [08:46:09]    linux_process.cpp(  88) - Warning - Couldn't locate renderdoc target control listening port between 38920 and 38927 in /proc/31325/net/tcp
RDOC 031352: [08:46:12]        gl_common.cpp( 737) - Warning - FBOs are shared on this implementation

Notably the first warning does not occur the second time I launch the app.

**Comment by baldurk** [comment]
I'm not sure what you mean about logging the most direct error.

Does your application start any child processes? There was a bug on linux in v1.2 that would break if multiple processes got RenderDoc injected as the code was looking through `/proc/<pid>/net/tcp` as above without realising that this file is basically the same as `/proc/net/tcp` so is the same across the whole system and not per-process.

If you want to share anything with me privately you can always [send me an email](mailto:baldurk@baldurk.org).

**Comment by nmr8** [comment]
> I'm not sure what you mean about logging the most direct error.

Yeah, sorry, that was not very clear. What I mean is that ..

"Error launching ... for capture" "Renderdoc injection failed. ..."

.. doesn't tell me what actually went wrong. Did the exec fail? Did some sort of ld thing fail? What failed, specifically? I guess I am asking for "one level down" in terms of what the specific failure was.

Sorry took so long to reply, been under pressure to get something done. I aim to email you a repro when I get a chance.

> Does your application start any child processes? 

No, not to my knowledge.

> There was a bug on linux in v1.2 that would break if multiple processes got RenderDoc injected as the code was looking through /proc/<pid>/net/tcp as above without realising that this file is basically the same as /proc/net/tcp so is the same across the whole system and not per-process.

I do have 1.2 installed, it's the Debian testing package. It's probably worth a shot to try a later release or build from source.

**Comment by nmr8** [comment]
Here's the debug log, this log is from the nightly I just downloaded. Looks like the commit hash is in the log.

https://gist.github.com/nmr8/d1f633fc2437d26e70a3185a7661a26c

**Comment by baldurk** [comment]
Confirmed to be an issue with the program taking a long time to start up, and the code watching for the target control port not waiting long enough. Fixed by the commit above.
