### ISSUE TITLE
Something wrong  when I use the function "Export drawcall list on disk "

### ISSUE THREAD

**Issue by TheShot** [baldurk/renderdoc#1246]
## Description
Something wront with it. Wrong format and no "Name“”. If is a stupid question,I'm sorry about that.
[DrawCallData.txt](https://github.com/baldurk/renderdoc/files/2790962/DrawCallData.txt)

**Comment by baldurk** [comment]
Hi, I can see there's an encoding issue with the μs in the duration label, but otherwise this looks normal. Without seeing your capture file I can't tell what's missing.

Can you explain exactly what is missing, and what name you're referring to? If it's easier, can you share the capture so I can compare directly?

**Comment by TheShot** [comment]
Hello.Thank you for your reply. Missing "Name" label and data is chaotic. Fuethermore,would you please develop the function that users can save drawcall data more format such as".csv"?
![moreinfo](https://user-images.githubusercontent.com/43540332/51720805-0f8d3980-208a-11e9-94c6-bbd20b78b659.png)

**Comment by baldurk** [comment]
I don't think I can explain this without sounding a bit condescending, but you have notepad set to word-wrap and the window is too small to display the long lines. If you turn off word wrap or make the window bigger it will display correctly:

![image](https://user-images.githubusercontent.com/661798/51735893-832a4900-2080-11e9-9b3a-1dce59280f29.png)

![image](https://user-images.githubusercontent.com/661798/51735903-8a515700-2080-11e9-97f8-f766bf2308d4.png)

I don't plan to add an option to export to csv, there's limited utility for that as it's not a good format to display a tree hierarchy and keep it readable. If you need to export the data you can use the python API to process the data and display it in whatever format you want.

**Comment by TheShot** [comment]
Something wrong?  I have try ,but it not work. Thank you for your reply and Thank you for your patience.
![error](https://user-images.githubusercontent.com/43540332/51810307-05fe0e80-22e2-11e9-9fcc-e00eb16e9609.png)

**Comment by baldurk** [comment]
It seems like the text file is being written without DOS newlines on windows, I can fix that too. Your first screenshot was from notepad on windows 7, and I used windows 10 by coincidence since on my main win7 machine I have vim set up.

Any modern text editor will handle either just fine.

**Comment by TheShot** [comment]
Thank you so much. When I use notepad++,it is right~
