### ISSUE TITLE
apk's are arm only.

### ISSUE THREAD

**Issue by stolk** [baldurk/renderdoc#1249]
I am investigating a rendering issue that happens on my android emulator only. I tried to have renderdoc connect to my android emulator.

Unfortunately, there are only arm binaries available, no x86.

Are there any plans to build the APKs in `share/renderdoc/plugins/android/` for x86 as well?

**Comment by baldurk** [comment]
No I don't have any plans to support non-ARM platforms for Android. It's probably not too hard to get it compiling and working, it might even work out of the box, but I won't be officially supporting it or shipping APKs even if it does work.
