### ISSUE TITLE
Vulkan: Indirect draw parameters in secondary command buffers always 0

### ISSUE THREAD

**Issue by doitsujin** [baldurk/renderdoc#1251]
## Description
When using indirect draws in secondary command buffers, the draw parameters are all zero, including the draw count of `vkCmdDraw(Indexed)IndirectCountKHR`. I tested it using a primary command buffer as well and it works fine there.

This is similar to #1066, and it looks like the patching of indirect commands which fixed that issue does not get executed when using secondary command buffers.

## Repro steps

This capture should show the problem, the problematic draw calls are bookmarked.
[indirect.tar.gz](https://github.com/baldurk/renderdoc/files/2821179/indirect.tar.gz)

## Environment

* RenderDoc build: v1.x (38f68e1534ff2b5db30b64ca859fe850136e4ee0)
* Operating System: Arch Linux
* API: Vulkan

The attached capture was recorded on RADV 18.3 on Polaris (RX 480).

**Comment by baldurk** [comment]
The code needed to propagate any pending copies of indirect parameters back from secondary command buffers to primaries, so that it happened at the end of the renderpass in the primary.

**Comment by doitsujin** [comment]
Can confirm that it works now, thanks.
