### ISSUE TITLE
Vertex attributes are broken in OpenGL 3.3 Core application

### ISSUE THREAD

**Issue by JayFoxRox** [baldurk/renderdoc#1256]
## Description

The pipeline state VTX, "Vertex Attribute Formats" and "Vertex Array Object" contain garbage.

I've debugged this for a while and noticed that the VAO is probably wrong.

---

I was tracing a development branch of XQEMU, an Xbox emulator. When looking at the framebuffer with qrenderdoc, the output image is garbage - so there appears to be an error with replaying.

I have looked into why this might happen, and noticed that the "Mesh Output" shows 0.0 for all components, in every draw call.

In the API inspector I can still see a couple of {`glBindBuffer`, `glVertexAttribPointer`, `glEnableVertexAttribArray`} for the attributes (which implies enabled + correct offset), but the pipeline state VTX tab claims that everything is "Disabled" and at offset 0.
However, when manually using the information from the API inspector and looking at the offset in the linked buffer, I can also see that the data is *not* 0x00000000.

It implied that the VTX readback is broken, or that VTX data is never correctly set when replaying.

---

After looking around, I found:

https://github.com/baldurk/renderdoc/blob/2a80fd29d0c561673eb5a71b333743f327db387c/renderdoc/driver/gl/wrappers/gl_buffer_funcs.cpp#L3002-L3009

and noticed, that `prevVAO` is used instead of `vaobj.name` when replaying (`vao` will be same as `prevVAO`, but `vaobj.name` was used to set attributes):

https://github.com/baldurk/renderdoc/blob/2a80fd29d0c561673eb5a71b333743f327db387c/renderdoc/driver/gl/gl_replay.cpp#L754-L758

So there's certainly some discrepancy.

As I'm unfamiliar with the codebase I don't know how to recover the proper VAO for replay (pipeline saving), or where exactly the issue lies: wrong VAO when setting data, or, wrong VAO when replaying.

I have also tried to hardcode the VAO ID (as a cruel hack) and the VTX view seems to work: It shows correct offsets and marks attributes as enabled.
~~However, there still seems to be garbage in the index buffer (only about 10% of the "Mesh Output" appears to be valid) - but I'm not sure if that is related or not.~~ *(Edit: This seems to happen if I `glBindVertexArray` in my dirty hacky, before getting `GL_ELEMENT_ARRAY_BUFFER_BINDING`, as the indices seems to use `prevVAO`... - this VAO handling appears to be bad: inconsistency everywhere)*

Also, even with this change the actual output is also utterly broken (nothing renders except one solid color, or a couple of textures stretched to framebuffer size) - again, this is probably unrelated, so I'll create individual issues if I can provide more information.

## Repro steps

I have no time for making a demo. This happened when tracing "Halo: CE" in https://github.com/mborgerson/xqemu/commit/e5f78e973f05b75d316be803a5d97d797550c94c - unfortunately it requires a bios and the game, so it's not a good test case.

I have made a capture during the intro animation to avoid leaking game assets: [xqemu-ms-logo.zip](https://github.com/baldurk/renderdoc/files/2831144/xqemu-ms-logo.zip)

## Environment

* RenderDoc build: https://github.com/baldurk/renderdoc/commit/2a80fd29d0c561673eb5a71b333743f327db387c
* Operating System: Arch Linux
* API: OpenGL 3.3 Core
* Driver: mesa 18.3.2-1

**Comment by baldurk** [comment]
Discussed offline, the renderer in this case is making GL calls including present from multiple threads, which is not supported. That least to wrong state being serialised ending up in the VAO problems detailed above.
