### ISSUE TITLE
None of tested games opened

### ISSUE THREAD

**Issue by vorob1** [baldurk/renderdoc#1264]
I have an issue with basic things, maybe I'm missing smth? Tried Thief 2, Doom 3, Shadow of the Tomb Raider, Quake 1 Chasm mod, and none of them works. 

Doom 3 and Thief 2 won't just launch, Tomb Raider works, but nothing happens in the app and Quake shows some weird error: 

https://pp.userapi.com/c844721/v844721209/1a0be1/XAgfTqtSA6w.jpg

Maybe this app captures only Vulcan games?

**Comment by vorob1** [comment]
Okay, managed to take screenshot in metro last light, but only in menu. On game loading game crashes.

**Comment by baldurk** [comment]
I do not condone or support capturing commercial copyrighted games that you are not the owner and creator of.

RenderDoc is intended only for debugging your own code.
