### ISSUE TITLE
Launch Debugger Crash

### ISSUE THREAD

**Issue by sidney9111** [baldurk/renderdoc#1271]
## Description
I did new a project, it's frame could be captured by my smartphone Xiaomi

But I got this error by my project with some functions not so complicate, This project just add 2~3 third party plugin, and do some movement controll in the scene. it got this crash as below:

The difference between them to me is  the crash one was crash and could not inject after handshake

RDOC 009176: [21:16:02]          android.cpp( 247) - Log     - Setting up to launch the application as a debugger to inject.
RDOC 009176: [21:16:02]    android_tools.cpp( 292) - Log     - COMMAND: E:/Setup/Android/SDK/SDK/platform-tools/adb '-s 662e4e3e0211 shell am start -S -D -n com.stone.gudai/com.unity3d.player.UnityPlayerActivity '
RDOC 009176: [21:16:03]    android_tools.cpp( 292) - Log     - COMMAND: E:/Setup/Android/SDK/SDK/platform-tools/adb '-s 662e4e3e0211 shell ps -A | grep com.stone.gudai'
RDOC 009176: [21:16:03]    android_tools.cpp( 292) - Log     - COMMAND: E:/Setup/Android/SDK/SDK/platform-tools/adb '-s 662e4e3e0211 forward tcp:39970 localabstract:renderdoc_39920'
RDOC 009176: [21:16:03]    android_tools.cpp( 292) - Log     - COMMAND: E:/Setup/Android/SDK/SDK/platform-tools/adb '-s 662e4e3e0211 forward tcp:38970 localabstract:renderdoc_38920'
RDOC 009176: [21:16:03]    android_tools.cpp( 292) - Log     - COMMAND: E:/Setup/Android/SDK/SDK/platform-tools/adb '-s 662e4e3e0211 forward tcp:39027 jdwp:14768'
RDOC 009176: [21:16:04]    android_tools.cpp( 292) - Log     - COMMAND: E:/Setup/Android/SDK/SDK/platform-tools/adb '-s 662e4e3e0211 shell pm path org.renderdoc.renderdoccmd.arm32'
RDOC 009176: [21:16:09]   target_control.cpp( 560) - Log     - Got remote handshake: com.stone.gudai [14768]
RDOC 009176: [21:16:09]   target_control.cpp( 560) - Log     - Got remote handshake: com.stone.gudai [14768]

## Environment

* RenderDoc build: nightly build.
* Operating System: Android 7.0
-- * API: e.g. Vulkan, D3D11, OpenGL, etc

GPU - Power VR

**Comment by baldurk** [comment]
I'm sorry but I don't understand your description of the problem. Can you try to explain in more detail what is going wrong?

**Comment by baldurk** [comment]
Closing this issue due to lack of information. If you can clarify what's going wrong please comment and I can reopen it.
