### ISSUE TITLE
Need a way to inspect integer values in shader registers

### ISSUE THREAD

**Issue by steel3d** [baldurk/renderdoc#128]
While debugging a shader, the register values are always interpreted as float.

It would be very helpful to have a right click option or a tool tip, per register or per component, to show a few representations of the value: float, decimal int, decimal uint, hex, binary, etc. Or maybe a global switch like visual studio's hex/default format switch (worse). In the register tab the different representations could even just be different columns in the grid.

**Comment by steel3d** [comment]
Ahh I'm a dumbass. After rereading an old conversation with Baldur, I now see the int/float switch at the top of the shader debugger tab. So most of my concerns are alleviated. But the other suggestions might be useful as a low priority feature.

**Comment by baldurk** [comment]
In the latest version (anything after 0.21 I think) there's a tooltip that shows float, uint and int representations of the registers if you hover over them:
![tooltip](https://cloud.githubusercontent.com/assets/661798/6414757/e1a0df9e-be91-11e4-8d23-fd27c61bdfb5.png)

It's not ideal as it doesn't show binary, hex, etc but it should cover the typical cases. If you want more fine-grained control, the watch window in the shader debugger supports visual studio type expressions, so you can do e.g: `r9.xyz,x` to show in hex, or `r9.xyz,b` to show in binary - f u i do float/uint/int respectively.

Would that cover what you're needing, or is there another use-case that could be served? I don't want to just fill the debugger up with options and buttons, but if there's a good way to make it discoverable then that'd be nice.

**Comment by steel3d** [comment]
Aaah! That's awesome! 

If only the tooltip worked in the registers tab and constants tab, it would be discoverable enough.

If just hex was added to the tooltip, that would solve everything!

A right click option for the global switch would also help, like Visual Studio's hex switch. I assume a lot of programmers are used to doing that in VS, which is what I was trying to do.

Tx for the quick response!

**Comment by baldurk** [comment]
The tooltip now includes a row for hex, and it will show on the register and constants windows - which also allows you to use it for cbuffer variables, although they should be the right type unless it's a mixed float/int packed register.

I'll see about adding a right click option for the global float/int switch but since the edit controls are scintilla's I'm not sure if I can customise that menu,

**Comment by steel3d** [comment]
Thanks so much! Can't wait to try it!

**Comment by steel3d** [comment]
Love this!

I see an issue now with yesterday's nightly where the tooltip pops up and stays up as I move the mouse down to the windows taskbar, over the constants or registers .

**Comment by baldurk** [comment]
I think that latest commit should be what you were thinking of, having it available on the right click menu (as an added bonus, it adds run to cursor/toggle breakpoint too!).

**Comment by baldurk** [comment]
Closing this as it seems like everything is covered.

**Comment by steel3d** [comment]
Yup, it's been working great, thanks!
