### ISSUE TITLE
Mesh output preview pane not properly displaying

### ISSUE THREAD

**Issue by SaschaWillems** [baldurk/renderdoc#1280]
## Description

Trying to debug a complex scene in my Vulkan glTF PBR sample I noticed that the mesh output does not actually display the mesh preview anymore, but instead i get random contents from other views. I had a similar problem like that long time ago with the texture viewer, but this one is reproducible and only seems to happen with larger captures:

![image](https://user-images.githubusercontent.com/10283127/53297154-3326d980-381a-11e9-9de6-febe5247dd06.png)

I have tested this with the latest 1.2 release and the nightly from 2019-02-22 and both exhibit this problem, though I noticed that the nightly is slower on selecting the draw calls from the tree and sometimes crashes without any warnings.

## Repro steps

~~I have uploaded a capture from the latest nightly that exhibits this problem [here](https://nextcloud.saschawillems.de/index.php/s/azQ6zLdH9DgoWDS)
_Small warning: that file is 390 MBytes large, even though it's zipped._~~

If you want to manually test this:
- Download the Littlest Tokyo model from https://sketchfab.com/3d-models/littlest-tokyo-94b24a60dc1b48248de50bf087c0f042
- Fire up my Vulkan glTF PBR example from https://github.com/SaschaWillems/Vulkan-glTF-PBR
- Use "open glTF file" from the UI of my sample

## Environment

* RenderDoc build: Tested with v1.2 and the nightly from 2019-02-22
* Operating System: Windows 10
* API: Vulkan
* GPU: NVidia GTX 980
* Driver: NDA (but recent)

**Comment by SaschaWillems** [comment]
Small update: This may be caused by undefined application behavior, even though the sample runs fine by itself. Will do some additional testing :/

Edit: It actually was an application bug that caused this behavior, so closing this.

**Comment by SaschaWillems** [comment]
One thing I noticed though: I can barely work with this capture using the latest nightly. Selecting draw calls is extremely laggy and puts a high load on my system. So if you want to check that out, I have uploaded an updated nightly capture [here](https://nextcloud.saschawillems.de/index.php/s/dmAiaBq7GM5PQSB).

**Comment by baldurk** [comment]
What is 'extremely laggy' for you? When I open the capture it's certainly not lightning fast, it takes 0.25 - 0.5 seconds or so, but it's not slow either. How long does it take on your system?

**Comment by SaschaWillems** [comment]
On the latest nightly with that capture, my whole system is lagging for up to 10 seconds when selecting a draw call from the event list, and sometimes up to a point where RenderDoc stops responding at all. With the 1.2 build this works fine. My CPU is an AMD FX-6350 and a bit outdated, but the nightly seems to be much slower then the latest release build for me. I also noticed that the nightly trace for the same since is almost twice this size.

**Comment by baldurk** [comment]
That's definitely an extreme case. Can you record a ETW trace with [UIForETW](https://github.com/google/UIforETW) of what's taking the time?

Also I'd be interested to know when this changed, if you could bisect the builds since v1.2 that would be very helpful. The file size in itself isn't necessary a problem but I don't think anything should have changed.

**Comment by mwilkason** [comment]
> Small update: This may be caused by undefined application behavior, even though the sample runs fine by itself. Will do some additional testing :/
> 
> Edit: It actually was an application bug that caused this behavior, so closing this.

Hello, sorry for tagging you on an old issue, but I think I'm currently experiencing the same issue as you, and just out of curiosity I would like to know what the application bug was that caused this. I'm having a very difficult time tracking it down.

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
