### ISSUE TITLE
RenderDoc freezes computer when attribute is not provided

### ISSUE THREAD

**Issue by manhnt9** [baldurk/renderdoc#1283]
## Description

When a shader use an input attribute but the vertex layout description is missing for that attribute, whole computer freezes if open Mesh Output tab. Capturing, saving don't have problems. Running without RenderDoc doesn't freeze my computer.

## Repro steps

- Download and extract [freeze.zip](https://github.com/baldurk/renderdoc/files/2903669/freeze.zip)
- Load capture file
- Open Mesh Output tab 

## Environment

* RenderDoc build: 1.2
* Operating System: Ubuntu 18.04
* API: Vulkan

**Comment by baldurk** [comment]
This is not unexpected. The vulkan specification says in 14.2 Vertex Input Interface:

> When the vertex stage is present in a pipeline, the vertex shader input variables form an interface with the vertex input attributes. The vertex shader input variables are matched by the Location and Component decorations to the vertex input attributes specified in the pVertexInputState member of the VkGraphicsPipelineCreateInfo structure.
>
> All vertex shader inputs declared as above **must:** have a corresponding attribute and binding in the pipeline.

Which means that declaring and using a vertex input without declaring it in the pipeline descriptor is invalid. The validation layers do detect this and print an error:

> [Validation:0/0]  [ UNASSIGNED-CoreValidation-Shader-InputNotProduced ] Object: 0x167 (Type = 15) | Vertex shader consumes input at location 0 but not provided

RenderDoc does not validate API use, so any invalid behaviour like this can cause crashes. This error might not cause your graphics driver to show any problems but it could cause a different driver to freeze or crash just the same as RenderDoc does - there are no guarantees about what happens with invalid API use.

**Comment by manhnt9** [comment]
Ah OK I see, it could be errors from driver/OS/... etc.

**Comment by baldurk** [comment]
I didn't look into it but in this case my guess is that it's caused by the transformation from vertex shader to compute shader to fetch the vertex output. That changes an unbound vertex input that perhaps the driver allows silently to an unbound texel buffer input that the driver errors on access to.

On windows this just becomes VK_ERROR_DEVICE_LOST but on linux without a TDR system that might freeze the whole system.

**Comment by manhnt9** [comment]
Thanks, I'll take a closer look if it becomes necessary.
