### ISSUE TITLE
Suggestion: Comments inside of the event browser

### ISSUE THREAD

**Issue by sbarisic** [baldurk/renderdoc#1284]
I think it would be useful to add custom labels/comments to the event browser list using the API to better notate what is going on. Especially when you have many draw calls.

![jtladgwgk6](https://user-images.githubusercontent.com/3836060/53404050-212d6e00-39b5-11e9-8ed7-501f5d569bf8.png)

**Comment by baldurk** [comment]
Yes this is available as standard in all graphics APIs.

In OpenGL the extension you're after is [`KHR_debug`](https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_debug.txt) which provides functions to do a single marker line as you've put above:

```
glDebugMessageInsert(GL_DEBUG_SOURCE_APPLICATION, GL_DEBUG_TYPE_MARKER, 0,
                     GL_DEBUG_SEVERITY_NOTIFICATION, -1, "World geometry stencil pass");
```

Or else you could define nested marker regions - similar to the auto-generated ones "Colour Pass #N":

```
glPushDebugGroup(GL_DEBUG_SOURCE_APPLICATION, 0, -1, "Stencil pass");

glDrawArrays(...);
glDrawArrays(...);
glDrawArrays(...);

glPopDebugGroup();
```

For more information see the documentation page [about annotating your frame](https://renderdoc.org/docs/window/event_browser.html#annotating-your-frame).
