### ISSUE TITLE
Question about "write a python extension"

### ISSUE THREAD

**Issue by TheShot** [baldurk/renderdoc#1291]
## Description
HI~
For example, I have a . I wrotr functions in this file. Then I built package and install.Then I want to load it. Renderdoc told me "AttributeError: module 'example_pkg' has no attribute 'register'". Where should I define the function register? I have __init__.py,examply_pkg.py and setup.py. I define the register in examply_pkg.py. I try to define it in  setup.py,vs told me "pyrenderdoc is not define". I try to find something in renderdoc document but failed. What's wrong with me? 

1. 

## Environment

* RenderDoc build: e.g. v1.0, or 2018-03-12 nightly build.
* Operating System: e.g. Windows 10, Windows 7, Ubuntu Linux, etc
* API: e.g. Vulkan, D3D11, OpenGL, etc

**Comment by baldurk** [comment]
There's a documentation page on [how to write an extension](https://renderdoc.org/docs/how/how_python_extension.html) which is worth consulting.

The requirement for the python module is that it exports a function like this:

```python
def register(version, pyrenderdoc):
    # ...
```

In my tests I put this function in `__init__.py` but I believe python allows you to put it in other files and then export it publicly, there's no particular requirement but I'm not familiar enough with python to go into details.

It sounds like you got that far but then hit the "pyrenderdoc is not defined" error. I'm not clear on where that was actually happening - did you get that error message from within RenderDoc when trying to load the module?

**Comment by TheShot** [comment]
I have try many times. When I define 'register' in setup.py,I fail to build package.Command Line told me the "pyrenderdoc is not defined"which is before I load the moudle . When I define  'register' in 
'example_pkg.py',I got the message"AttributeError: module 'example_pkg' has no attribute 'register'". Maybe the error "pyrenderdoc is not defined" is still exist,but fail to load sothat the message is not displayed.

**Comment by baldurk** [comment]
> I fail to build package

Can you explain exactly what you mean here? there is no build step involved - you place the python module & extension.json in the appropriate folder and it is detected by RenderDoc at runtime.

> Command Line told me the "pyrenderdoc is not defined"

Which command line is this? RenderDoc extensions are loaded by the UI itself, if you're using the standalone python interpreter then you are doing something else and I don't understand what you're trying to do.

I've searched google and it seems like setup.py is used by a different python system for building & distribution. I don't know what that is about but it has nothing to do with writing a UI extension for RenderDoc.

**Comment by TheShot** [comment]
I understand it wrong. I build before load it. The command line is in the process I build the package. Now, I put __init__.py" and "example_pkg.py" in the folder which is opened by RenderDoc "Open Location" function directly. And RenderDoc told me "module 'example_pkg' has no attribute 'register'".But in "example_pkg.py", I define the "register" function.  I try to add "register" function in "__init__.py".Then RenderDoc told me "name 'pyrenderdoc' is not defined". What should I do? Thank you for your patience.

**Comment by TheShot** [comment]
For the"name 'pyrenderdoc' is not defined",whether should I import some packages or not? RenderDoc document told me that "  In addition to this, an additional global pyrenderdoc is always available.". In "__init__.py", I import nothing.When I import "renderdoc and qrenderdoc ",the same error message I got.

**Comment by baldurk** [comment]
I'm not entirely sure if it's the only/exact issue you're hitting but I did find that `pyrenderdoc` was not properly being set up as a global in the extension modules. It should now be available anywhere after `register()` is called.

**Comment by TheShot** [comment]
When I call the register function, I got some error message.RenderDoc document shows the register function has two parameters.The second parameter is pyrenderdoc,so I need to pass it to register function.I don't know what should do. I'm confused.Could you give me your test files? Maybe I can find out result by reading your test code.

**Comment by baldurk** [comment]
You should not call the register function yourself, it's called by RenderDoc with those parameters when the extension is loaded and enabled. You should not try to import your extension modules from the python shell as that will certainly cause problems.

Again I recommend reading the [documentation on writing an extension](https://renderdoc.org/docs/how/how_python_extension.html) since it seems like you are on the wrong path.

The simplest possible extension would consist of the `extension.json` listed in that documentation page and an `__init__.py` with just this:

```python
def register(version, pyrenderdoc):
    print('Registering extension for RenderDoc {}'.format(version))
```

**Comment by TheShot** [comment]
OK！ I don't know the register will be called automatically. I call it by myself. I got it. Thank you very much~
