### ISSUE TITLE
"Launching ... please wait" hangs indefinitely roughly 7/10 attempts (OpenGL 4.6 / Windows 10)

### ISSUE THREAD

**Issue by nauticaldev** [baldurk/renderdoc#1296]
## Description
The project is my game engine. (I am currently running v1.2, will try the nightly build)
- When I click the launch button, it opens my engine's console subsystem ( this is an MSVC debug build ) and the mouse cursor changes to the usual Windows 10 spinning blue wheel.
- After about 4-6 seconds, either the application launches and the injection works, or it doesn't.
- If the mouse cursor stops spinning I know that it will never open, so I just hit alt-f4 on the Please Wait box and hit the launch button again immediately. 
- After about 5 attempts or so, it works fine, the window changes and then I can debug.
- The "Launching..." window does not freeze, it always winds up working in the end. 
- Been going on for at least the last several months.
- Occasionally works on the first try, might even get a couple in a row. 
- As far as I can tell it doesn't make it into int main()

Things I've tried :
- I've tried reinstalling both 64bit and 32bit versions (as I usually run my engine in 32bit) same results
- Installing on SSD, same drive as application
- Disabling multi-threading in my application did not change the results.
- Loading a blank project, so there is little to no IO, does nothing either

## Repro steps
1) I open program
2) Click "Launch Application" tab
3) Click "Load Settings", select cap.cap, saved in same directory as executable
4) Click Launch, cross fingers. 

Here's the settings I always use. I tried toggling them all off and on individually, no changes

![settings](https://user-images.githubusercontent.com/10524299/53823996-c8675380-3f27-11e9-87d5-e48b01c9d6c9.PNG)

## Environment
GLEW Version: 2.1.0
GL Version: 4.6.0 NVIDIA 418.81
GL Vendor: NVIDIA Corporation
GL Renderer: GeForce GTX 980M/PCIe/SSE2
GLSL Version: 4.60 NVIDIA
Windows 10, Version 10.0.17763 build 17763
64-bit, Intel Core i7-4710HQ CPU@ 2.50GHz, 2494Mhz, 4 cores, 8 logical
24GB RAM

**Comment by baldurk** [comment]
You didn't list which version you're using but I assume you're running the latest v1.2. If your program is 32-bit then I think this is a known issue in that release. I never got an exact reproducible case that I could debug myself, but I put in place some speculative fixes that seemed to solve the problem for some people.

Can you try with a nightly build? That should have the latest fixes.

**Comment by nauticaldev** [comment]
Sorry about that, I bumped the enter button when changing the title.  Currently using v1.2, both 64 bit and 32 bit versions exhibit this behavior

**Comment by baldurk** [comment]
Thanks. To be clear I was asking specifically about whether _your_ program was 32-bit, not the build of RenderDoc. You should always run the build of RenderDoc matching your windows version - the 32-bit build of  RenderDoc is only there for people on 32-bit windows versions.

Does this happen with a 64-bit build of your program? Can you reproduce it on a nightly build of RenderDoc?

**Comment by nauticaldev** [comment]
The nightly build seems to have the error fixed well. Ran several tests, it exhibits none of the hanging behavior from RenderDoc v1.2. And yeah, I'm running my program with a 32-bit configuration, cannot test the 64-bit config right now because apparently I didn't update my 64-bit boost libraries.  

Doesn't matter though, great work man! Thanks for the tip about the nightly builds, didn't even know you had that on your page.

**Comment by baldurk** [comment]
OK, I suspect this is the bug I think it is. Either way if it's fixed in the nightly builds for you then it will be fixed in v1.3.

Thanks for testing!
