### ISSUE TITLE
rdc file play back failed on Unbutu 16.04 with remote android phone

### ISSUE THREAD

**Issue by horusli** [baldurk/renderdoc#1297]
## Description

the error log is like following, do you have any clue?

Log     - Opening RDCFile /tmp/RenderDoc/OGLESIntroducingPVRUtils_2019.03.03_19.51.15_frame109.rdc
Warning - Unsupported screen format: depth: 16, red_mask: 3f, blue_mask: f800
Warning - Using RGB16 fallback, if this works your X11 server is reporting a bad screen format.
Warning - Unsupported screen format: depth: 16, red_mask: 3f, blue_mask: f800
Warning - Using RGB16 fallback, if this works your X11 server is reporting a bad screen format.
Log     - Opening capture remotely
Log     - Capture open complete
Log     - Capture ready on replay host
**Error   - Couldn't choose default framebuffer config
Error   - Creating proxy driver failed: API initialisation failed**
Warning - Unsupported screen format: depth: 16, red_mask: 3f, blue_mask: f800
Warning - Using RGB16 fallback, if this works your X11 server is reporting a bad screen format.

BTW: this rdc file can be loaded without error on window10 connecting to android phone.

## Environment

* RenderDoc build: latest local build.
* Operating System: Ubuntu Linux 16.04
* API: OpenGLES
* GPU: AMD R7-350

**Comment by horusli** [comment]
and the GUI report Failed to open capture for replay: API initialisation failed

**Comment by baldurk** [comment]
Something seems to be wrong with your X server configuration beyond just RenderDoc. These messages:

```
Warning - Unsupported screen format: depth: 16, red_mask: 3f, blue_mask: f800
Warning - Using RGB16 fallback, if this works your X11 server is reporting a bad screen format.
```

Are coming from Qt itself. From a quick google it seems like it might be related to using VNC, but I don't know for sure. Are you able to run other Qt programs as normal, and also other GL/GLES programs?

This message from RenderDoc:

```
Error - Couldn't choose default framebuffer config
```

Means that `glXChooseFBConfig` returned `NULL` when looking for an RGBA 8-bit color framebuffer config, which also seems to align with Qt's error messages that something is wrong with the X server configuration.

**Comment by horusli** [comment]
yes, I was using VNC, I should have installed the AMD graphics card driver, and glxinfo/glxgears works properly.
but you suggestion, I try some gles program and they crashedat calling eglGetDisplay, seems there is something wrong not just renderdoc. I will further check why

thanks Baldurk!

**Comment by horusli** [comment]
one thing still puzzles me is that, If I choose to replay the trace on remote phone, do I still need to choose fbconfig from X server?

**Comment by horusli** [comment]
below are my glxinfo 
GLX Visuals
    visual  x   bf lv rg d st  colorbuffer  sr ax dp st accumbuffer  ms  cav
  id dep cl sp  sz l  ci b ro  r  g  b  a F gb bf th cl  r  g  b  a ns b eat
----------------------------------------------------------------------------
0x025 16 tc  1  16  0 r  y .   6  5  5  0 .  .  0 16  0  0  0  0  0  0 0 None
0x026 16 tc  1  16  0 r  y .   6  5  5  0 .  .  0 16  8 16 16 16  0  0 0 None
0x027 16 tc  1  16  0 r  y .   6  5  5  8 .  .  0 16  8 16 16 16 16  0 0 None
0x028 16 dc  1  16  0 r  y .   6  5  5  0 .  .  0 16  0  0  0  0  0  0 0 None
0x029 16 dc  1  16  0 r  y .   6  5  5  0 .  .  0 16  8 16 16 16  0  0 0 None
0x02a 16 dc  1  16  0 r  y .   6  5  5  8 .  .  0 16  8 16 16 16 16  0 0 None
0x02b 16 dc  1  16  0 r  . .   6  5  5  8 .  .  0 16  8 16 16 16 16  0 0 None

**Comment by baldurk** [comment]
RenderDoc needs to render textures, buffers and meshes locally on the host computer, even if the majority of the replay happens on the android device.

If that glxinfo output is not truncated then that definitely shows the problem, you should have many more visuals available on a normal system. The only visuals you have are 16-bit with 6-bit red, 5-bit green and blue. There are no visuals with full 24-bit colour (8-bit for red, green and blue). For example on my system the glxinfo output has a lot more visuals:

```
504 GLX Visuals
    visual  x   bf lv rg d st  colorbuffer  sr ax dp st accumbuffer  ms  cav
  id dep cl sp  sz l  ci b ro  r  g  b  a F gb bf th cl  r  g  b  a ns b eat
----------------------------------------------------------------------------
0x021 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 24  8  0  0  0  0  0 0 None
0x022 24 dc  0  32  0 r  y .   8  8  8  8 .  .  0 24  8  0  0  0  0  0 0 None
0x4cc 24 tc  0  32  0 r  . .   8  8  8  8 .  .  0  0  0  0  0  0  0  0 0 None
0x4cd 24 tc  0  32  0 r  . .   8  8  8  8 .  .  0  0  0 16 16 16 16  0 0 Slow
0x4ce 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0  0  0  0  0  0  0  0 0 None
0x4cf 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0  0  0 16 16 16 16  0 0 Slow
0x4d0 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0  0  0  0  0  0  0  0 0 None
0x4d1 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0  0  0 16 16 16 16  0 0 Slow
0x4d2 24 tc  0  32  0 r  . .   8  8  8  8 .  .  0 16  0  0  0  0  0  0 0 None
0x4d3 24 tc  0  32  0 r  . .   8  8  8  8 .  .  0 16  0 16 16 16 16  0 0 Slow
0x4d4 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 16  0  0  0  0  0  0 0 None
0x4d5 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 16  0 16 16 16 16  0 0 Slow
0x4d6 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 16  0  0  0  0  0  0 0 None
0x4d7 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 16  0 16 16 16 16  0 0 Slow
0x4d8 24 tc  0  32  0 r  . .   8  8  8  8 .  .  0 24  0  0  0  0  0  0 0 None
0x4d9 24 tc  0  32  0 r  . .   8  8  8  8 .  .  0 24  0 16 16 16 16  0 0 Slow
0x4da 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 24  0  0  0  0  0  0 0 None
0x4db 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 24  0 16 16 16 16  0 0 Slow
0x4dc 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 24  0  0  0  0  0  0 0 None
0x4dd 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 24  0 16 16 16 16  0 0 Slow
0x4de 24 tc  0  32  0 r  . .   8  8  8  8 .  .  0 24  8  0  0  0  0  0 0 None
0x4df 24 tc  0  32  0 r  . .   8  8  8  8 .  .  0 24  8 16 16 16 16  0 0 Slow
0x4e0 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 24  8 16 16 16 16  0 0 Slow
0x4e1 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 24  8  0  0  0  0  0 0 None
0x4e2 24 tc  0  32  0 r  y .   8  8  8  8 .  .  0 24  8 16 16 16 16  0 0 Slow
0x4e3 24 tc  0  32  0 r  . .   8  8  8  8 .  .  0  0  0  0  0  0  0  2 1 None
0x4e4 24 tc  0  32  0 r  . .   8  8  8  8 .  .  0  0  0  0  0  0  0  4 1 None
0x4e5 24 tc  0  32  0 r  . .   8  8  8  8 .  .  0  0  0  0  0  0  0  8 1 None
... many more ...
0x6b5 32 tc  0  32  0 r  . .   8  8  8  8 .  s  0  0  0  0  0  0  0  0 0 None
0x6b6 32 tc  0  32  0 r  y .   8  8  8  8 .  s  0  0  0  0  0  0  0  0 0 None
0x6b7 32 tc  0  32  0 r  y .   8  8  8  8 .  s  0  0  0  0  0  0  0  0 0 None
0x6b8 32 tc  0  32  0 r  . .   8  8  8  8 .  s  0 16  0  0  0  0  0  0 0 None
0x6b9 32 tc  0  32  0 r  y .   8  8  8  8 .  s  0 16  0  0  0  0  0  0 0 None
0x6ba 32 tc  0  32  0 r  y .   8  8  8  8 .  s  0 16  0  0  0  0  0  0 0 None
0x6bb 32 tc  0  32  0 r  . .   8  8  8  8 .  s  0 24  0  0  0  0  0  0 0 None
0x6bc 32 tc  0  32  0 r  y .   8  8  8  8 .  s  0 24  0  0  0  0  0  0 0 None
0x6bd 32 tc  0  32  0 r  y .   8  8  8  8 .  s  0 24  0  0  0  0  0  0 0 None
0x6be 32 tc  0  32  0 r  . .   8  8  8  8 .  s  0 24  8  0  0  0  0  0 0 None
0x6bf 32 tc  0  32  0 r  y .   8  8  8  8 .  s  0 24  8  0  0  0  0  0 0 None
0x6c0 32 tc  0  32  0 r  y .   8  8  8  8 .  s  0 24  8  0  0  0  0  0 0 None
```
