### ISSUE TITLE
Feature request: Change filtering type in the texture viewer

### ISSUE THREAD

**Issue by Gaktan** [baldurk/renderdoc#1300]
Sometimes when viewing a texture in the texture viewer, we don't necessarily want to view the texture with a point filtering. Sometimes we also want to view the texture with linear sampling. This is particularly useful when working with procedural textures, LUTs, BRDF texture, generated mip maps.

Currently the texture viewer displays all texture using a point sampler (shown in blue). We cannot change this sampling type, even by using a custom shader.
The texture is displayed using linear sampler in the Input/Output window (shown in red)

I propose two different ways of implementing this feature.

1. (purple) Allow the user to choose the filtering when making a custom shader.
2. (green) Add a button in the UI to be able to select the filtering

![image](https://user-images.githubusercontent.com/1674095/53960304-3a859700-40e6-11e9-8d4d-a541b71f7dc8.png)

**Comment by baldurk** [comment]
I'm not sure I understand exactly, this would be something that I'd suggest solving using a custom shader.

The custom shaders bind both linear and point sampler objects so you can choose which one to use when looking up the texture - does that do what you're after?

**Comment by Gaktan** [comment]
So maybe this is a bug?

I made a custom shader with linear sampler in the above screenshot. And as you can see, it still looks very pixelated just like using a point sampler. Here is the code:

```
float4 main(float4 pos : SV_Position, float4 UV : TEXCOORD0) : SV_Target0
{
	float2 uv = pos / RENDERDOC_TexDim;
	if (RENDERDOC_TextureType == 2)
	{
		return texDisplayTex2DArray.Sample(linearSampler, float3(uv.xy, 0.0));
	}
	else if (RENDERDOC_TextureType == 3)
	{
		return texDisplayTex3D.Sample(linearSampler, float3(uv.xy, float(RENDERDOC_SelectedSliceFace) / float(RENDERDOC_TexDim.z)));
	}
    return float4(0,0,0,1);
}
```

**Comment by baldurk** [comment]
Oh, no sorry. I didn't think it all the way through. Custom shaders are run a single time to a cached output texture the same dimension as the input, and then when displayed they use the same logic as displaying a texture by default - point sampled for upscaling, linear for downscaling. So in this sense custom shaders can only change the interpretation of the data not how the results are displayed.

The only way to change this would be to control whether point or linear sampling is used for upscaling the final display texture which is not currently externally configurable. I'll need to think about whether it makes sense to expose this as an option.

**Comment by baldurk** [comment]
I don't think the extra UI complexity for this feature is worthwhile in an already complex area. If you need this you can export the image to disk and view it in an external program that does whatever filtering you need.

**Comment by Gaktan** [comment]
What about being able to change the filtering in a custom shader?
This would be the perfect solution and the one that makes the most sense in my opinion (since filtering is only useful in very specific situations in Custom shaders right now). This would mean completely changing the way the textures are rendered in the Texture Viewer though.

Viewing the image in an external program can be very tricky, especially if you use multiple MIP levels and/or Cubemaps.

**Comment by baldurk** [comment]
As I say I don't believe the feature is worth the necessary implementation, maintenance, and UI complexity burden.
