### ISSUE TITLE
Missing glBufferData in the capture

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#1307]
## Description

There is a simple GL application issuing 2 draw calls. Before doing each, it binds a VAO and updates one of the vertex buffer contents with `glBufferData`. When capturing it and replaying, I no longer see the `glBufferData` of the first draw call, and the vertex data is reported wrong.

Here is what RenderDoc sees:
![renderdoc-buffer-data](https://user-images.githubusercontent.com/107301/54132145-15e13600-43ea-11e9-9856-98252f72de76.png)

Capture: [main.rdc.zip](https://github.com/baldurk/renderdoc/files/2952661/main.rdc.zip)

Here is what ApiTrace sees:
![apitrace-buffer-data](https://user-images.githubusercontent.com/107301/54132166-1f6a9e00-43ea-11e9-9cd6-32fd32eb573d.png)

Note: the bug icon doesn't appear to be obviously relevant, it's saying:
> api issue 131185: Buffer detailed info: Buffer object 3 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations. warning: dumping of instanced attributes (aData) not yet supported warning: message: low issue 131153: Pixel-path detailed info: The current pixel-path operation converts data from signed integer to unsigned integer, and may exhibit data loss. warning: message: low issue 131153: Pixel-path detailed info: The current pixel-path operation converts data from 4-bit integer to 1-bit integer, and may exhibit data loss.

Capture: [main.trace.zip](https://github.com/baldurk/renderdoc/files/2952666/main.trace.zip)

## Repro steps

Project: [wr.zip](https://github.com/baldurk/renderdoc/files/2952695/wr.zip)

Instructions, assuming it's unpacked to `wr` folder:
```bash
cd wr && target/wrench show wrench/reftests/transforms/flatten-preserve-3d-root.yaml
```

I set the launch options to capture the Frame 1:
![renderdoc-capture](https://user-images.githubusercontent.com/107301/54132713-14fcd400-43eb-11e9-8c25-ad990d093f94.png)

## Environment

* RenderDoc build: v1.2
* Operating System: Linux (Solus)
* API: OpenGL

**Comment by kvark** [comment]
Uploaded the source to https://github.com/kvark/webrender/tree/rd-repro-buffer-data
In order to build you need Rust and Cargo:
```bash
git clone https://github.com/kvark/webrender -b rd-repro-buffer-data wr
cd wr/wrench
cargo build # produces the ../target/debug/wrench
../target/debug/wrench show reftests/transforms/flatten-preserve-3d-root.yaml
```

**Comment by baldurk** [comment]
I don't think I'm looking at the same thing as you are. In the captures I make there are only ~190 events total so it doesn't line up with the screenshot you have above. The apitrace screenshot implies there should be a marker `B_Solid` that I don't get. For me I get events like this:

![image](https://user-images.githubusercontent.com/661798/54135485-cd3d7300-4411-11e9-97fe-db019ab7595d.png)

And both draws have a glBufferData where you seem to be missing one.

![image](https://user-images.githubusercontent.com/661798/54135505-d8909e80-4411-11e9-82aa-5daebf477666.png)

![image](https://user-images.githubusercontent.com/661798/54135538-e6462400-4411-11e9-86e9-a28c7ad206bf.png)

I'm on the right branch:

```
$ git remote -v && git status -s -b
origin	git@github.com:kvark/webrender.git (fetch)
origin	git@github.com:kvark/webrender.git (push)
## rd-repro-buffer-data...origin/rd-repro-buffer-data
```

And this is how I'm launching the program:

![image](https://user-images.githubusercontent.com/661798/54135632-0f66b480-4412-11e9-95a9-0660ddf7c864.png)

**Comment by kvark** [comment]
Thanks for testing it @baldurk !

> I don't think I'm looking at the same thing as you are. In the captures I make there are only ~190 events total so it doesn't line up with the screenshot you have above.

This is due to you capturing Frame 28. Could you auto-capture Frame 2 instead like I specified in the repro steps? Here is my breakdown:
![renderdoc-frame](https://user-images.githubusercontent.com/107301/54136940-13370e80-43f3-11e9-9cdb-d716765a625d.png)

>The apitrace screenshot implies there should be a marker B_Solid that I don't get. 

It's not in my renderdoc capture either. The application only inserts the markers if it sees "GL_ext_debug_marker" extension: https://github.com/kvark/webrender/blob/8d8dfa3cbc566e32a2dedd35cbf4774189a44be0/webrender/src/renderer.rs#L1991

I suspect that ApiTrace just exposes the extension and shows the markers, while RenderDoc doesn't do anything fancy, and the GL driver itself doesn't have that.

Also, my glxinfo output, just in case:
>OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 415.27
OpenGL core profile shading language version string: 4.60 NVIDIA

**Comment by baldurk** [comment]
> This is due to you capturing Frame 28. Could you auto-capture Frame 2 instead like I specified in the repro steps? Here is my breakdown:

Ah I see now, my mistake I didn't parse that bit of the screenshot properly.

The problem looks like it's because that glBufferData is the first one ever on that buffer. Since it's then considered 'initialisation' it gets added as a pre-frame call - which then means the data isn't re-uploaded at the right time in the frame. It's one of the _many_ downsides of GL having very mutable objects and no good differentiation between creation and update.

I've made a change to duplicate the call so that it appears once during initialisation to create the buffer, and again during the frame where it was made. That should fix the bug.

> It's not in my renderdoc capture either. The application only inserts the markers if it sees "GL_ext_debug_marker" extension: https://github.com/kvark/webrender/blob/8d8dfa3cbc566e32a2dedd35cbf4774189a44be0/webrender/src/renderer.rs#L1991
>
> I suspect that ApiTrace just exposes the extension and shows the markers, while RenderDoc doesn't do anything fancy, and the GL driver itself doesn't have that.

Yes RenderDoc doesn't add GL_EXT_debug_marker to the extensions list at the moment if it's not supported by the driver, but I could change that.

btw is there a reason you're using the old GL_EXT_debug_marker rather than the modern replacement GL_KHR_debug which supercedes those old extensions (EXT_debug_marker and EXT_debug_label)?

**Comment by kvark** [comment]
> I've made a change to duplicate the call so that it appears once during initialisation to create the buffer, and again during the frame where it was made. That should fix the bug.

Amazing, thank you!

> btw is there a reason you're using the old GL_EXT_debug_marker rather than the modern replacement GL_KHR_debug which supercedes those old extensions (EXT_debug_marker and EXT_debug_label)?

No particular reason, just being lazy. Interestingly, many drivers *do* support that even though it doesn't report the extension in the supported list :)
