### ISSUE TITLE
renderdoc capture wrong  with multi sample on

### ISSUE THREAD

**Issue by horusli** [baldurk/renderdoc#1308]
## Description

I was trying to capture a frame in pubgmgd  using renderdoc for analysis purpose, and it goes smoothly when I disable multi sample, things goes wrong when I turn on msaa, it become very slow and the rdc capture all goes wrong

and I try to replay the captured trace on discrete gpu card, the draw result is the same as capture.
the weird thing is if I disconnect renderdoc and relaunch the game along, all thing rendered correctly, do we have known issue related to multi-sample? from the phenomenon it seems some thing went wrong in capture with multi-sample on. 

I plan to upload the trace I got yet still finding way to put it in github.

## Environment

* RenderDoc build: v1.2.
* Operating System: RHEL7
* API: GLES

**Comment by horusli** [comment]
temporary put the trace under here, please check if it is useful
https://github.com/horusli/tempshare/blob/master/debug_file/hdr_msaa.rdc

**Comment by horusli** [comment]
btw, the capture is taking place on remote android phone with ARM GPU G76

**Comment by baldurk** [comment]
This appears to be a capture from a commercial product - PUBG mobile. RenderDoc is only intended for use with your own programs, and capturing copyrighted products that are not yours is not endorsed or supported.
