### ISSUE TITLE
Right arrow can't move in "Pixel Context"

### ISSUE THREAD

**Issue by liurui39660** [baldurk/renderdoc#1316]
## Description

I captured a frame, open it in the RenderDoc. Then I right click on the texture in "Texture Viewer", in the "Pixel Context", a cursor will show where the current pixel is.

When I click up, left and down arrow on my keyboard, the texture will move accordingly, but when I click right arrow, nothing happens.

## Repro steps

1. Open a `.rdc` file.
2. Right click on the texture in "Texture Viewer".
3. Press right arrow on the keyboard.
4. It's expected the texture in the "Pixel Context" move left by 1 "pixel", but nothing happens

## Environment

My working PC

- RenderDoc build: v1.2
- API: OpenGL 4.5
- OS: Windows 10 Education x64, version 1511, build 10586.1540, no .NET 4.7, can't upgrade.
- GPU: Nvidia GeForce GTX 1080 Ti

My laptop

- RenderDoc build: v1.2
- API: OpenGL 4.5
- OS: Windows 10 Enterprise
- GPU: Nvidia GeForce GTX 950m

**Comment by baldurk** [comment]
I'm not clear, does it only break on one of your computers and not the other?

I can't think of any reason that only one direction wouldn't work unless the selected pixel is on the edge of a texture. It sounds like it might be something specific to your computer like another program interfering with key presses. Does the right arrow key work in other windows like in a text edit field?

**Comment by liurui39660** [comment]
I tested it on both the computers mentioned above. The right arrow works for other programs (at least for Visual Studio, Notepad, Chrome). The pixel is not at the border of the texture. I think if some programs interfere the key press, why only RenderDoc is affected.

**Comment by baldurk** [comment]
I will still need more information to work with when I am able to investigate properly after next week, as the right arrow is not completely broken everywhere since I use it myself successfully.

**Comment by liurui39660** [comment]
It seems the cursor can only move within a square area.

My viewport is 1280 * 720, when the cursor reaches x = 719, the right arrow no longer works, but within in [0, 719] it can freely move.

I also tested a 720 * 1280 view port, but the up arrow seems fine.

**Comment by baldurk** [comment]
Thanks, there might be a mistaken bounds check somewhere. I'll look when I'm back at home.

**Comment by baldurk** [comment]
@vincentdm05 found this before I could look, fixed in that PR.
