### ISSUE TITLE
Remember Executable Path between runs

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#1318]
## Description

In the old UI (the C# one), RenderDoc would remember what .exe and folder was used the last time:
![Renderdoc](https://user-images.githubusercontent.com/3395130/54486153-c3c56800-4862-11e9-89bd-e7e42e4c28d1.png)

Hitting the "..." to open the Open File dialog still remembers the folder; however it is problematic when I have literally > 30 EXEs to chose from in that same folder.

This is a small usability suggestion / request.

It seems to affect at least Windows & Linux clients.

Cheers

**Comment by baldurk** [comment]
Hi there I'm currently away until the end of next week so I will look at this when I'm back.

**Comment by darksylinc** [comment]
No hurry!

I've actually thought this would get fixed quickly when the Qt version came out and that was like a year ago or.. two (I've been lazy to submit the report), so I can definitely wait one or two more weeks. :)

**Comment by manhnt9** [comment]
Well I also had some thoughts on this. Like application profiles that RenderDoc could save.
There're some apps that I have to set environment variables for and other settings.
So a new feature to save the Launch tab to multiple profiles so we can select and run is very helpful and good time-saving.

**Comment by darksylinc** [comment]
Such feature could be, UI/UX wise, be implemented using four new controls right in the "Launch Application" tab:

- Dropdown or Listbox: To select a session
- Button: Clone session
- Button: Rename session
- Button: Delete session

![Sessions](https://user-images.githubusercontent.com/3395130/54636179-9b0cc080-4a64-11e9-9112-3a7999173878.png)

or alternatively:

![Sessions2](https://user-images.githubusercontent.com/3395130/54636547-72d19180-4a65-11e9-98b0-6c98b5c423bd.png)

There's always a session called "Last Sesssion". Clone session would clone the currently selected session and add it to the dropdown.

The session would save all the settings (Executable Path, Allow Fullscreen, Queue Capture, etc)

This feels a bit more advanced though and feels like it should be in its own ticket.
What I originally asked (remembering last launched app) should take 5 minutes of coding and is basically restoring the behaviour the C# version had.

**Comment by baldurk** [comment]
It sounds like you are both describing the existing feature to save and load the capture settings to a .cap file, that's been there since the first release. See the save and load buttons at the bottom of the panel.

On recent nightly builds the last launched session is also auto saved and there's a button to restore it.

**Comment by manhnt9** [comment]
Ah yeah somehow I didn't notice the Save/Load Settings buttons.

**Comment by darksylinc** [comment]
> On recent nightly builds the last launched session is also auto saved and there's a button to restore it.

I'm talking about remembering the exec path automatically (i.e. an usability enhancement). I consider this a regression from RenderDoc 0.9.x

No need to press a button to restore it. I'm also not looking to restore all the other fields. Just exec path and working dir is enough.

> It sounds like you are both describing the existing feature to save and load the capture settings to a .cap file, that's been there since the first release. See the save and load buttons at the bottom of the panel.

When it comes to manhnt9's request, the functionality is there but the UX is not very productive nor obvious. As manhnt9 says it is very easy to miss and doesn't autosave/clone.

Again to *me* this is not very important.

**Comment by baldurk** [comment]
I understand your original request perfectly well, as I mentioned I'm currently away so I cannot look at it until I'm back. My previous comment was addressed to you both discussing a way to save and load the whole session, which already exists.

**Comment by baldurk** [comment]
I've re-added the code to save the executable as it worked in v0.x.
