### ISSUE TITLE
Can't compile X86 Development using Visual Studio 2017 Community

### ISSUE THREAD

**Issue by Andreyogld3d** [baldurk/renderdoc#1319]
Hi!

Visual Studio 2017 Community: Can't compile X86 Development:

renderdoc\qrenderdoc\3rdparty\qt\include\qtcore\qalgorithms.h(847): error C3615: constexpr function 'qCountLeadingZeroBits' cannot result in a constant expression
renderdoc\qrenderdoc\3rdparty\qt\include\qtcore\qalgorithms.h(858): note: failure was caused by call of undefined function or one not declared 'constexpr'
renderdoc\qrenderdoc\3rdparty\qt\include\qtcore\qalgorithms.h(858): note: see usage of 'qPopulationCount'

any X64 can be compiled sucessfully

RenderDoc was cloned from:
https://github.com/baldurk/renderdoc/commit/26d823905e18c97e07aefe3ee7a1a6d559dd77e7

**Comment by baldurk** [comment]
Hi there I'm currently away until the end of next week so I will look at this when I'm back.

**Comment by baldurk** [comment]
This seems to be a Qt bug, which was fixed in later Qt versions. I've backported the fix since it's fortunately just a change in the headers.
