### ISSUE TITLE
Wrong hover description for "Allow global process hooking - be careful"

### ISSUE THREAD

**Issue by Zicandar** [baldurk/renderdoc#132]
It seems to use the same hover text as the "Allow periodic anonymous update checks" that is just below it.
![wronghovertext](https://cloud.githubusercontent.com/assets/8311820/7183052/6410e1b6-e455-11e4-97e3-e53db283c40b.png)

Other then that this tool seems really awesome!
(Using it to debug Unity)

**Comment by baldurk** [comment]
Thanks for reporting this!
