### ISSUE TITLE
Wrong Texture Format when viewing a 3D Texture in the Texture Viewer

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [baldurk/renderdoc#1321]
## Description

I've made a minimal reproducible capture, it understands that I've made Texture 86 and 87 with TextureStorage3D having `internalformat` as `GL_R8_SNORM` and `GL_DEPTH24_STENCIL8`.

However when I open the textures in the TExture Viewer ("View Contents") the view reports them both as being of the `R8G8B8A8_UNORM` format.

(there's a ClearTexImage there as well, but i've tested with and without it and still same results)

## Repro steps

None, its possible to reproduce it with the capture (if you have an Nvidia GPU).

## Environment

* RenderDoc build: e.g. v1.2 **and** the 2019-03-19 nightly build.
* Operating System: Windows 10
* API: e.g. OpenGL
[RenderDoc3DTextureBug.zip](https://github.com/baldurk/renderdoc/files/2989421/RenderDoc3DTextureBug.zip)

**Comment by baldurk** [comment]
Hi there I'm currently away until the end of next week so I will look at this when I'm back.

**Comment by baldurk** [comment]
Both `glTextureStorage3D` calls are invalid, as they specify `levels = 0` and that parameter must be at least 1. That then breaks the queries for what the format is, and it falls back to RGBA8 as a default.

**Comment by devshgraphicsprogramming** [comment]
Ah crap, I should learn to never file bugs against RenderDoc ;)

But strange I got no error debug output when it failed on the glTextureStorage* call
(but yes I understand its not RenderDocs responsibility to glEnable(GL_DEBUG_OUTPUT) implicitly for me)
