### ISSUE TITLE
Vulkan: Replaying on Android fails with assertion

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#1326]
I'm trying to use RenderDoc to debug a test running through ANGLE on Android from Linux. I have RenderDoc built with `-DENABLE_GLES=OFF -DENABLE_GL=OFF`, and built the Android version both for arm32 and arm64 (through `-DBUILD_ANDROID=On -DANDROID_ABI=armeabi-v7a` and `-DBUILD_ANDROID=On -DANDROID_ABI=arm64-v8a` respectively. I'm debugging on a Pixel2 which is arm64, but RenderDoc refuses to run unless there's an arm32 build available).

I managed to take a capture successfully. However, when replaying on the Android device, RenderDoc crashes on an assertion:

```
Log     - Created device.
Log     - Got replay driver.
Log     - QRenderDoc - renderer created for "/storage/emulated/0/Android/data/org.chromium.native_test:test_process/files/RenderDoc/org.chromium.native_test:test_process_2017.12.19_07.47_frame0.rdc"
Error   - Assertion failed: 'm_Device != 0' 
Segmentation fault
```

Top-of-tree has a bug where running on Vulkan (both Linux and Android) hits an error complaining about some format being 0 (I don't have a running build at the moment for the exact message). So I'm testing on `v1.2`. I did test with `982ef03fd` as well (which has some Android changes) but I hit the same assert.

---

The assertion is in `vk_outputwindow.cpp`:

```
uint64_t VulkanReplay::MakeOutputWindow(WindowingData window, bool depth)
...
    // Assert hits in m_pDriver->GetDev()
    m_OutputWindows[id].Create(m_pDriver, m_pDriver->GetDev(), depth);
...
```

I put some logs around in `wrappers/vk_device_funcs.cpp` and I don't see `vkCreateDevice` getting called at all.

Are you aware of such an issue? How would you suggest I continue debugging this?

**Comment by ShabbyX** [comment]
Note that if I comment out this line, RenderDoc loads the capture just fine, and everything in the UI seems functional, except the "Texture Viewer" and other such tabs are not accessible (as in, they crash when clicked on).

Is it possible that there's a confusion in RenderDoc when replaying remotely, where the window system thinks Vulkan device should be there for viewing purposes, while in reality it's only initialized on the remote device?

**Comment by baldurk** [comment]
If you disable the GL driver then there won't be anything able to run the local proxy rendering needed for remote replay. It probably falls back to try and use Vulkan but proxying is currently not implemented for the Vulkan driver so this will crash - I'm honestly surprised it even gets any further if you comment out that line.

If you want to do remote debugging from linux you will need the GL driver enabled at build time. On windows D3D11 will be used in preference to GL but on linux GL is the only option.

**Comment by ShabbyX** [comment]
Thanks for the explanation. I can confirm that re-enabling GL made things work.
