### ISSUE TITLE
Display bound array slice content in the "Texture Viewer" "Inputs"

### ISSUE THREAD

**Issue by JPMMaia** [baldurk/renderdoc#1327]
## Description

I have created a texture with 3 array slices. The content of the array slice 0 is just red pixels. Array slice 1 has green pixels and array slice 2 has blue pixels.

I have also created a shader that expects 3 textures in different registers: currentFrameTexture, previousFrameTexture and beforePreviousFrameTexture. 

Then I bound array slice 0 to currentFrameTexture, array slice 1 to previousFrameTexture and array slice 2 to beforePreviousFrameTexture.

However, when looking at the "Inputs" panel on the "Texture Viewer", all three images are red. This is because they all reference the same texture, but are incorrectly displaying array slice 0.

![Actual Behaviour](https://user-images.githubusercontent.com/5596149/54987065-88dad700-4fbc-11e9-8b6a-c98e55712c88.png)

I think it would be more intuitive, if the thumbnails in the "Inputs" panel displayed the actual bound slice, and when clicked, the texture and corresponding array slice opened automatically. For instance, when clicking on the previousFrameTexture, it could change the array slice to 1 (if the texture was already opened but showing array slice 0).

![Expected Behaviour](https://user-images.githubusercontent.com/5596149/54987066-88dad700-4fbc-11e9-80c1-a27b927832f4.png)

## Environment

* RenderDoc build: v1.2
* Operating System: Windows 10
* API: D3D12

**Comment by baldurk** [comment]
I didn't have a D3D12 example to hand, but in testing on D3D11/GL examples that should now use the pipeline bound first mip/slice when displaying thumbnails.
