### ISSUE TITLE
Renderdoc reading wrong device features in multi driver environment

### ISSUE THREAD

**Issue by edrickhong** [baldurk/renderdoc#1331]
## Description

This concerns the renderdoc package that comes with Ubuntu 18.10 . I don't know if this has been fixed upstream. I have both the mesa radv and the amdvlk drivers installed on my system. This build of renderdoc requires shaderStorageImageMultisample to capture frames, which my current build of radv doesn't have but amdvlk does.

Setting the environment variable VK_ICD_FILENAMES within renderdoc to force the loading of the amdvlk driver is expected to work. My app loads amdvlk, but renderdoc still complains that shaderStorageImageMultisample is not avaiable. However, if I launch renderdoc with the environment variable set globally eg:

`VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json qrenderdoc`

renderdoc does the expected behavior and allows capture.

Also, running renderdoc without setting VK_ICD_FILENAMES within renderdoc actually allows me to capture on radv and bypasses the shaderStorageImageMultisample requirement.

It looks like renderdoc is loading a different driver than the application and thus the device features reported back does not tally with the respective driver. 

## Repro steps

Install both the amdvlk and the radv drivers. I built the amdvlk driver from source and installed it manually but i don't know if this is mandatory to recreate the behavior.

Run renderdoc on a vulkan application without the VK_ICD_FILENAMES environment set in renderdoc. It should allow capture eventhough the app reports using the radv driver.

Run renderdoc with the environment variable set in renderdoc. The app should load amdvlk, but after capturing it should complain about not having shaderStorageImageMultisample and abort the capture. 

Besides my own app, I have been able to recreate this issue with the vulkan-examples triangle demo. The example reports the driver loaded in the window title bar. 

## Environment
* RenderDoc build: v1.1+dfsg-1 (Installed from Ubuntu 18.10 )
* Operating System: Ubuntu 18.10
* API: Vulkan
* GPU: RX 560

**Comment by baldurk** [comment]
From what you describe this sounds like it's working as expected. To clarify if I understand right:

* radv is registered globally
* amdvlk is not registered and is only available if VK_ICD_FILENAMES is set
* If you run qrenderdoc (and the application subsequently) with VK_ICD_FILENAMES pointing to amdvlk, then capture and replay works on amdvlk
* If you don't ever set VK_ICD_FILENAMES then capture and replay works on radv
* If you set VK_ICD_FILENAMES to capture with amdvlk but then it's not set on replay, that breaks

This is expected - RenderDoc will try to match up the physical devices present during capture to the most compatible physical device available on replay, but if your amdvlk driver isn't registered globally then without setting VK_ICD_FILENAMES the only option it has available is radv. Your situation is no different to if you tried to capture on nvidia and replayed on amd - if the driver isn't available then the capture is unlikely to be compatible.

If you look in the RenderDoc log it will print verbosely the physical device mapping it has made for you to see. I would recommend not changing VK_ICD_FILENAMES unless you know exactly what you want, and if so then make sure it's set universally between capture and replay - as you've said both of those cases work correctly.

I'm not sure exactly which error about shaderStorageImageMultisample you're meaning. RenderDoc does not require that feature, though it will enable it when available and that might create an incompatibility trying to load on a driver that doesn't support it.

**Comment by edrickhong** [comment]
To clarify, both drivers are registered globally. Maybe the guys at Ubuntu changed the build settings but renderdoc will not capture without shaderStorageImageMultisample available. 

Anyway, the situation on the VK_ICD_FILENAMES is like this

When I run renderdoc without VK_ICD_FILENAMES set globally, renderdoc will be able to see both drivers. I then set the variable in renderdoc to force my app to use the amdvlk driver. The app loads the amdvlk driver, but during capture renderdoc will complain that the shaderStorageImageMultisample is not available, which is odd because amdvlk does have this feature, leaving me to believe that renderdoc is getting the device features from radv.

I believe the main bug here is that renderdoc is not running the same driver as the app. In the case where I mentioned that I managed to "bypass" the shaderStorageImageMultisample, I think under the hood renderdoc is using the amdvlk driver when my app is using the radv driver

I'll try to get more information on this later see if I can get the specific commit that ubuntu 18.10 is building from. 

I'll be uploading some files and screenshots when I get the time later in the day

**Comment by baldurk** [comment]
The debian package doesn't change any code to require `shaderStorageImageMultisample`, there are no build settings for this. You've already contradicted yourself more than once by saying first that it's required, and then later that the requirement is "bypassed", which does not make sense. What you are seeing is the feature being enabled optionally when running on one driver that supports it, and then it not being available on replay when using a different driver because you have forced that situation.

The solution is still the same - stop setting VK_ICD_FILENAMES to force anything. If both drivers are registered globally then leave that situation as-is and capture and replay normally, using whichever physical device the application selects. As you've said everything works correctly when doing that.

If you need to force the use of a particular driver then set the variable globally so that it's consistent across capture and replay. You've also said that _that_ works correctly.

**Comment by edrickhong** [comment]
If you don't want to support this case then it is fine. It can be worked around. However, if you are still interested in fixing this, these are the details.

I am sure it is as you said, the feature being enabled on my app's device, but renderdoc uses a different driver that doesn't have this feature, causing a failed capture.

I think I know the reason why. Without the environment variable set, radv is gpu index 0 and amdvlk is index 1. With the variable set, amdvlk becomes index 0 in my app. But on renderdoc's end, because it is not set under renderdoc, it still sees radv as 0 and amdvk as 1. At capture, it sees my app uses gpu index 0, thus selecting the radv driver aka the wrong one.

A solution is maybe to make a string has of the device name. Radv tends to name the devices differently from the official device name: "AMD RADV POLARIS11 (LLVM 7.0.0)" vs "Radeon RX 560 Series". A hack I know but it's a solution. Maybe using the VK_KHR_driver_properties extension could help with this? It uses VK_KHR_get_physical_device_properties2. While an app is not gauranteed to be using this, maybe renderdoc can slip this in and get the driver information at device creation time. 

I know what I want to do may seem hacky to you, but it is a documented behavior of the vulkan loader. To me, I think it is very important that renderdoc can guarantee that the device it is using to recreate my captures is the same device I used in my application.
