### ISSUE TITLE
Multi Sample Array Texture resource viewing produces complete garbage

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [baldurk/renderdoc#1333]
## Description

Basicaly my MSAA array texture preview starts off black (should be white after clearing depth to 1.f), then gets increasingly more corrupted as I switch to view depth/stencil and other slices than 0 in RenderDoc.

This one unfortunately I cannot provide a capture for.

## Repro steps

Create an MSAA Array Texture in DEPTH24_STENCIL8 format with ARB_texture_storage and ARB_direct_state_access .

Create a Framebuffer Object and attach the MSAA Array Texture with `glNamedFramebufferTexture`

Execute `glClearNamedFramebufferfi(FBO, GL_DEPTH_STENCIL, 0u, 1.f, 0)`

Note: I've had a 2GB MSAA array texture hooked up.

AFAIK I had no OpenGL errors, ARB_debug enabled and printing all levels of information.
## Environment

* RenderDoc build: e.g. v1.2
* Operating System: e.g. Windows 10 + NVidia 1050
* API: OpenGL 4.5

**Comment by baldurk** [comment]
It looks like I never implemented handling for multisampled array textures on GL, and no-one noticed until now!

That commit should add the necessary extra cases.
