### ISSUE TITLE
Shader Signatures gone wild in OpenGL

### ISSUE THREAD

**Issue by justkarli** [baldurk/renderdoc#1337]
## Description

Hi Baldur, 
I've set up a little OpenGL scene that is using tessellation + instancing and noticed this when viewing the input & output signature for the tessellation control shader: 
![tesselated_instances_tcs_signatures](https://user-images.githubusercontent.com/1123557/55637865-49836600-57c6-11e9-9b43-d9f8765ff379.png)

## Repro steps
Run the example from

https://bitbucket.org/justkarli/tessellated-instancing/src/2aa60ced35803d221e6e4e0459d5fa2a3238ab3c/src/main.cpp?at=master&fileviewer=file-view-default

and take a snapshot. Go to Pipeline -> TCS -> View the ShaderSource. 

## Environment

* RenderDoc build: v1.2
* Operating System: Windows 10
* API: OpenGL
* GPU: AMD Vega 64 (Radeon Softwareversion 19.4.1)

Ignore the render output in the example, because it is unfortunatly not working on AMD (Vega 64). I think there is another AMD driver bug happening, something with interface matching and the layout locations. Therefore I wanted to investigate this problem with renderdoc.. until I've seen the overlapping registries in the input signatures.

But on Intel & nvidia cards it should at least render four blue triangles.

**Comment by baldurk** [comment]
I can't repro this unfortunately, on my AMD system the input/output signature looks pretty much as I'd expect:

![image](https://user-images.githubusercontent.com/661798/55641223-4b005e80-57c5-11e9-99f5-c5c03a8c4125.png)

The builtins not being identified as such for you (i.e. `gl_PerVertex.gl_Position`) seems like the most clearly buggy thing here, and I'm not sure how that's happened. Can you post/upload your diagnostic log to see if there are any errors there? They should be matched by string name so I don't see how the name can be correct but they are treated like generic outputs.

As to the other locations, I honestly can't say for sure if that's wrong or not. For non-builtins the location is probably being returned directly from the driver and I'm not sure if the spec says anything about how locations are assigned for matrices in the tessellation shaders.

**Comment by justkarli** [comment]
Hmpf, ok, what AMD card and driver do you have? Is the example running or is everything still gray?
I just ran the example on our second AMD machine (RX 480, 19.3) where I can reproduce the problem (RenderDoc v1.1). I've added errorcallbacks to glfw & glew in the simple example, but my logs are empty.. :(

**Comment by baldurk** [comment]
Ah sorry I messed up. I tested on latest code by accident instead of checking v1.2. I can reproduce the problem on v1.2 but it works correctly on latest - can you try a recent nightly build?

To clarify, I do see the bug with things rendering incorrectly. The TES mesh output doesn't render for me by default, there seems to be some driver issue with `out vec3 normal;` being declared but never written to that interferes with transform feedback. Editing the shader to remove that gets me the TES output - something seems to be transforming all the vertices off the right side of the screen.

**Comment by justkarli** [comment]
Oh nice, thank you! At least I know I am not imagining things xD. I'll try that on the next working day. The funny thing is, as soon as I am removing all layout qualifier, the result is ok.

**Comment by justkarli** [comment]
Ok the issue, that the display order for glsl built in variables and in/out interface blocks are mixed, is fixed in the latest build! Thank you!
