### ISSUE TITLE
Is any testcase for renderdoc?

### ISSUE THREAD

**Issue by mimijava** [baldurk/renderdoc#1338]
## Description
Did you use QtTest for Ui test or other unit test frameworks to cover renderdoc's code ?

It's  a command renderdoccmd run unit,  but these are too few test cases.

How do you protect code quality？

Is any automation test framework that you are using?

**Comment by baldurk** [comment]
QtTest isn't used, and neither is any other kind of UI test framework.

Aside from the Catch2 unit tests, I run [auto testing](https://github.com/baldurk/renderdoc/tree/v1.x/util/test) nightly which exercises specific parts of the core library for capture/replay/analysis. I add tests to that set intermittently.

**Comment by mimijava** [comment]
@baldurk Thanks for your answer.
