### ISSUE TITLE
Use qt creator 4.8.0 build qrenderdoc  in windows, it's occur error while link program

### ISSUE THREAD

**Issue by mimijava** [baldurk/renderdoc#1342]
## Description
When I use qt creator 4.8.0 build qrenderdoc  in windows, it's occur error while link program.
Can you help me explain what's the reason?

**linking ..\x64\Development\qrenderdoc.exe 
LINK : fatal error LNK1104: 无法打开文件“D:\h00325234\gpu\Seagull\x64\Development\renderdoc.lib”
jom: D:\h00325234\gpu\Seagull\build-qrenderdoc-Desktop_Qt_5_12_0_MSVC2017_64bit-Debug\Makefile.Debug [..\x64\Development\qrenderdoc.exe] Error 1104
jom: D:\h00325234\gpu\Seagull\build-qrenderdoc-Desktop_Qt_5_12_0_MSVC2017_64bit-Debug\Makefile [debug] Error 2
15:42:09: 进程"D:\Qt5.12.0\Tools\QtCreator\bin\jom.exe"退出，退出代码 2 。
Error while building/deploying project qrenderdoc (kit: Desktop Qt 5.12.0 MSVC2017 64bit)
The kit Desktop Qt 5.12.0 MSVC2017 64bit has configuration issues which might be the root cause for this problem.
When executing step "Make"
15:42:09: Elapsed time: 01:24.**

**Comment by mimijava** [comment]
The problem is that I haven't compiled using Visual Studio.
But when i use debug mode build. An other problem appearence.

**LINK : warning LNK4098: 默认库“MSVCRT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library
PythonContext.obj : error LNK2019: 无法解析的外部符号 PyInit_renderdoc，该符号在函数 "public: static void __cdecl PythonContext::GlobalInit(void)" (?GlobalInit@PythonContext@@SAXXZ) 中被引用
PythonContext.obj : error LNK2019: 无法解析的外部符号 PyInit_qrenderdoc，该符号在函数 "public: static void __cdecl PythonContext::GlobalInit(void)" (?GlobalInit@PythonContext@@SAXXZ) 中被引用
..\x64\Development\qrenderdoc.exe : fatal error LNK1120: 2 个无法解析的外部命令
jom: D:\h00325234\gpu\Seagull\build-qrenderdoc-Desktop_Qt_5_12_0_MSVC2017_64bit-Debug\Makefile.Debug [..\x64\Development\qrenderdoc.exe] Error 1120
jom: D:\h00325234\gpu\Seagull\build-qrenderdoc-Desktop_Qt_5_12_0_MSVC2017_64bit-Debug\Makefile [debug] Error 2
16:07:49: 进程"D:\Qt5.12.0\Tools\QtCreator\bin\jom.exe"退出，退出代码 2 。
Error while building/deploying project qrenderdoc (kit: Desktop Qt 5.12.0 MSVC2017 64bit)
The kit Desktop Qt 5.12.0 MSVC2017 64bit has configuration issues which might be the root cause for this problem.**

**Comment by baldurk** [comment]
Building directly from qt creator is not supported, on windows you must use the visual studio solution to build. If you do want to try it then you're on your own to resolve any errors.

**Comment by mimijava** [comment]
@baldurk Thanks for reply.
