### ISSUE TITLE
The same renderdoc version, the same apk  run crash in android P Verison , and it success run in android Q version.

### ISSUE THREAD

**Issue by mimijava** [baldurk/renderdoc#1344]
## Description
With the same renderdoc version, the same apk  run crash in android P Verison , and it success run in android Q version.
Is it a bug with renderdoc ?

	Line 1366: 04-10 11:29:02.717 18870 18997 I renderdoc: @5cad62fe0000003f@ RDOC 018870: [11:29:02]     android_hook.cpp( 785) - Log     - Refreshing android hooks...
	Line 1368: 04-10 11:29:02.722 18870 18997 I renderdoc: @5cad62fe00000040@ RDOC 018870: [11:29:02]     android_hook.cpp( 787) - Log     - Refreshed
	Line 1369: 04-10 11:29:02.722 18870 18997 I renderdoc: @5cad62fe00000041@ RDOC 018870: [11:29:02]        egl_hooks.cpp( 206) - Debug   - eglCreateContext:
	Line 1370: 04-10 11:29:02.722 18870 18997 I renderdoc: @5cad62fe00000042@ RDOC 018870: [11:29:02]        egl_hooks.cpp( 213) - Debug   - 3098: 2
	Line 1372: 04-10 11:29:02.723 18870 18997 I renderdoc: @5cad62fe00000043@ RDOC 018870: [11:29:02]        gl_driver.cpp( 963) - Log     - Core context CDBE6480 created with attribs, sharing with context 00000000
	Line 1373: 04-10 11:29:02.724 18870 18997 I renderdoc: @5cad62fe00000044@ RDOC 018870: [11:29:02]        gl_common.cpp( 420) - Log     - Checking enabled extensions, running as OpenGL ES 3.2
	Line 1374: 04-10 11:29:02.724 18870 18997 I renderdoc: @5cad62fe00000045@ RDOC 018870: [11:29:02]      gl_emulated.cpp(3002) - Log     - Emulating ARB_clear_buffer_object
	Line 1375: 04-10 11:29:02.724 18870 18997 I renderdoc: @5cad62fe00000046@ RDOC 018870: [11:29:02]      gl_emulated.cpp(3017) - Log     - Emulating ARB_internalformat_query2
	Line 1376: 04-10 11:29:02.724 18870 18997 I renderdoc: @5cad62fe00000047@ RDOC 018870: [11:29:02]      gl_emulated.cpp(3179) - Log     - Emulating EXT_direct_state_access
	Line 1377: 04-10 11:29:02.724 18870 18997 I renderdoc: @5cad62fe00000048@ RDOC 018870: [11:29:02]      gl_emulated.cpp(3266) - Log     - Emulating ARB_direct_state_access
	Line 1378: 04-10 11:29:02.724 18870 18997 I renderdoc: @5cad62fe00000049@ RDOC 018870: [11:29:02]        gl_driver.cpp(1189) - Log     - Activating new GL context: ARM / Mali-G76 / OpenGL ES 3.2 v1.r16p0-01rel0.5bd61355ce280ef5eace000ac8736ec6
	Line 1379: 04-10 11:29:02.725 18870 18997 I renderdoc: @5cad62fe0000004a@ RDOC 018870: [11:29:02]        gl_common.cpp( 463) - Log     - Vendor checks for 32 (ARM / Mali-G76 / OpenGL ES 3.2 v1.r16p0-01rel0.5bd61355ce280ef5eace000ac8736ec6)
	Line 1380: 04-10 11:29:02.725 18870 18997 I renderdoc: @5cad62fe0000004b@ RDOC 018870: [11:29:02]        gl_common.cpp( 752) - Warning - Reading from the depth buffer using glReadPixels is not supported (GL_NV_read_depth)
	Line 1381: 04-10 11:29:02.725 18870 18997 I renderdoc: @5cad62fe0000004c@ RDOC 018870: [11:29:02]        gl_common.cpp( 756) - Warning - Reading from the stencil buffer using glReadPixels is not supported (GL_NV_read_stencil)
	Line 1382: 04-10 11:29:02.726 18870 18997 I renderdoc: @5cad62fe0000004d@ RDOC 018870: [11:29:02]        gl_common.cpp( 760) - Warning - Reading from the packed depth-stencil buffers using glReadPixels is not supported (GL_NV_read_depth_stencil)
	Line 1383: 04-10 11:29:02.728 18870 18997 W BinaryProgramHWUI: Current GPU Does not surport extension: GL_OES_get_program_binary
	Line 1384: 04-10 11:29:02.733 18870 18997 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
	**Line 1392: 04-10 11:29:02.786 18870 18997 I renderdoc: @5cad62fe0000004e@ RDOC 018870: [11:29:02]  gl_shader_funcs.cpp(1243) - Error   - Assertion failed: 'record' Couldn't identify object passed to function. Mismatched or bad GLuint? (program=1)**
	Line 1393: 04-10 11:29:02.786 18870 18997 D skia    : Program linking failed.
	Line 1395: 04-10 11:29:02.795 18870 18997 D skia    : Program linking failed.
	Line 1396: 04-10 11:29:02.795 18870 18997 D skia    : VS:
	Line 1397: 04-10 11:29:02.795 18870 18997 D skia    : SKSL:
	Line 1398: 04-10 11:29:02.795 18870 18997 D skia    :    1	#version 320 es
	Line 1399: 04-10 11:29:02.795 18870 18997 D skia    :    2	uniform float4 sk_RTAdjust;
	Line 1400: 04-10 11:29:02.795 18870 18997 D skia    :    3	in float2 position;
	Line 1401: 04-10 11:29:02.795 18870 18997 D skia    :    4	in float2 textureCoords;
	Line 1402: 04-10 11:29:02.795 18870 18997 D skia    :    5	in half4 color;
	Line 1403: 04-10 11:29:02.795 18870 18997 D skia    :    6	flat out half4 vcolor_Stage0;
	Line 1404: 04-10 11:29:02.795 18870 18997 D skia    :    7	out float2 vtextureCoords_Stage0;
	Line 1405: 04-10 11:29:02.795 18870 18997 D skia    :    8	void main() 
	Line 1406: 04-10 11:29:02.795 18870 18997 D skia    :    9	{
	Line 1407: 04-10 11:29:02.795 18870 18997 D skia    :   10		// Primitive Processor TextureGeometryProcessor
	Line 1408: 04-10 11:29:02.795 18870 18997 D skia    :   11		float2 pos2 = position;
	Line 1409: 04-10 11:29:02.795 18870 18997 D skia    :   12		vcolor_Stage0 = color;
	Line 1410: 04-10 11:29:02.795 18870 18997 D skia    :   13		vtextureCoords_Stage0 = textureCoords;
	Line 1411: 04-10 11:29:02.795 18870 18997 D skia    :   14		sk_Position = float4(pos2.x , pos2.y, 0, 1);
	Line 1412: 04-10 11:29:02.795 18870 18997 D skia    :   15	}
	Line 1413: 04-10 11:29:02.795 18870 18997 D skia    :   16	
	Line 1414: 04-10 11:29:02.796 18870 18997 D skia    : GLSL:
	Line 1415: 04-10 11:29:02.796 18870 18997 D skia    :    1	#version 320 es
	Line 1416: 04-10 11:29:02.796 18870 18997 D skia    :    2	
	Line 1417: 04-10 11:29:02.796 18870 18997 D skia    :    3	precision mediump float;
	Line 1418: 04-10 11:29:02.796 18870 18997 D skia    :    4	uniform highp vec4 sk_RTAdjust;
	Line 1419: 04-10 11:29:02.796 18870 18997 D skia    :    5	in highp vec2 position;
	Line 1420: 04-10 11:29:02.796 18870 18997 D skia    :    6	in highp vec2 textureCoords;
	Line 1421: 04-10 11:29:02.796 18870 18997 D skia    :    7	in mediump vec4 color;
	Line 1422: 04-10 11:29:02.796 18870 18997 D skia    :    8	flat out mediump vec4 vcolor_Stage0;
	Line 1423: 04-10 11:29:02.796 18870 18997 D skia    :    9	out highp vec2 vtextureCoords_Stage0;
	Line 1424: 04-10 11:29:02.796 18870 18997 D skia    :   10	void main() {
	Line 1425: 04-10 11:29:02.796 18870 18997 D skia    :   11	    highp vec2 pos2 = position;
	Line 1426: 04-10 11:29:02.796 18870 18997 D skia    :   12	    vcolor_Stage0 = color;
	Line 1427: 04-10 11:29:02.796 18870 18997 D skia    :   13	    vtextureCoords_Stage0 = textureCoords;
	Line 1428: 04-10 11:29:02.796 18870 18997 D skia    :   14	    gl_Position = vec4(pos2.x, pos2.y, 0.0, 1.0);
	Line 1429: 04-10 11:29:02.796 18870 18997 D skia    :   15	    gl_Position = vec4(gl_Position.x * sk_RTAdjust.x + gl_Position.w * sk_RTAdjust.y, gl_Position.y * sk_RTAdjust.z + gl_Position.w * sk_RTAdjust.w, 0.0, gl_Position.w);
	Line 1430: 04-10 11:29:02.796 18870 18997 D skia    :   16	}
	Line 1431: 04-10 11:29:02.796 18870 18997 D skia    :   17	
	Line 1432: 04-10 11:29:02.796 18870 18997 D skia    : 
	Line 1433: 04-10 11:29:02.796 18870 18997 D skia    : FS:
	Line 1434: 04-10 11:29:02.796 18870 18997 D skia    : SKSL:
	Line 1435: 04-10 11:29:02.796 18870 18997 D skia    :    1	#version 320 es
	Line 1436: 04-10 11:29:02.796 18870 18997 D skia    :    2	uniform lowp sampler2D uTextureSampler_0_Stage0;
	Line 1437: 04-10 11:29:02.796 18870 18997 D skia    :    3	flat in half4 vcolor_Stage0;
	Line 1438: 04-10 11:29:02.796 18870 18997 D skia    :    4	in float2 vtextureCoords_Stage0;
	Line 1439: 04-10 11:29:02.796 18870 18997 D skia    :    5	out half4 sk_FragColor;
	Line 1440: 04-10 11:29:02.796 18870 18997 D skia    :    6	void main() 
	Line 1441: 04-10 11:29:02.796 18870 18997 D skia    :    7	{
	Line 1442: 04-10 11:29:02.796 18870 18997 D skia    :    8		half4 outputColor_Stage0;
	Line 1443: 04-10 11:29:02.796 18870 18997 D skia    :    9		half4 outputCoverage_Stage0;
	Line 1444: 04-10 11:29:02.796 18870 18997 D skia    :   10		{
	Line 1445: 04-10 11:29:02.796 18870 18997 D skia    :   11			// Stage 0, TextureGeometryProcessor
	Line 1446: 04-10 11:29:02.796 18870 18997 D skia    :   12			outputColor_Stage0 = vcolor_Stage0;
	Line 1447: 04-10 11:29:02.796 18870 18997 D skia    :   13			float2 texCoord;
	Line 1448: 04-10 11:29:02.796 18870 18997 D skia    :   14			texCoord = vtextureCoords_Stage0;
	Line 1449: 04-10 11:29:02.796 18870 18997 D skia    :   15			outputColor_Stage0 = outputColor_Stage0 * texture(uTextureSampler_0_Stage0, texCoord);
	Line 1450: 04-10 11:29:02.796 18870 18997 D skia    :   16			outputCoverage_Stage0 = float4(1);
	Line 1451: 04-10 11:29:02.796 18870 18997 D skia    :   17		}
	Line 1452: 04-10 11:29:02.796 18870 18997 D skia    :   18		{
	Line 1453: 04-10 11:29:02.796 18870 18997 D skia    :   19			// Xfer Processor: Porter Duff
	Line 1454: 04-10 11:29:02.796 18870 18997 D skia    :   20			sk_FragColor = outputColor_Stage0 * outputCoverage_Stage0;
	Line 1455: 04-10 11:29:02.796 18870 18997 D skia    :   21		}
	Line 1456: 04-10 11:29:02.796 18870 18997 D skia    :   22	}
	Line 1457: 04-10 11:29:02.796 18870 18997 D skia    :   23	
	Line 1458: 04-10 11:29:02.796 18870 18997 D skia    : GLSL:
	Line 1459: 04-10 11:29:02.796 18870 18997 D skia    :    1	#version 320 es
	Line 1460: 04-10 11:29:02.796 18870 18997 D skia    :    2	
	Line 1461: 04-10 11:29:02.796 18870 18997 D skia    :    3	precision mediump float;
	Line 1462: 04-10 11:29:02.796 18870 18997 D skia    :    4	out mediump vec4 sk_FragColor;
	Line 1463: 04-10 11:29:02.796 18870 18997 D skia    :    5	uniform lowp sampler2D uTextureSampler_0_Stage0;
	Line 1464: 04-10 11:29:02.796 18870 18997 D skia    :    6	flat in mediump vec4 vcolor_Stage0;
	Line 1465: 04-10 11:29:02.796 18870 18997 D skia    :    7	in highp vec2 vtextureCoords_Stage0;
	Line 1466: 04-10 11:29:02.796 18870 18997 D skia    :    8	void main() {
	Line 1467: 04-10 11:29:02.796 18870 18997 D skia    :    9	    mediump vec4 outputColor_Stage0;
	Line 1468: 04-10 11:29:02.796 18870 18997 D skia    :   10	    {
	Line 1469: 04-10 11:29:02.796 18870 18997 D skia    :   11	        outputColor_Stage0 = vcolor_Stage0;
	Line 1470: 04-10 11:29:02.796 18870 18997 D skia    :   12	        highp vec2 texCoord;
	Line 1471: 04-10 11:29:02.796 18870 18997 D skia    :   13	        texCoord = vtextureCoords_Stage0;
	Line 1472: 04-10 11:29:02.796 18870 18997 D skia    :   14	        outputColor_Stage0 = outputColor_Stage0 * texture(uTextureSampler_0_Stage0, texCoord);
	Line 1473: 04-10 11:29:02.796 18870 18997 D skia    :   15	    }
	Line 1474: 04-10 11:29:02.796 18870 18997 D skia    :   16	    {
	Line 1475: 04-10 11:29:02.796 18870 18997 D skia    :   17	        sk_FragColor = outputColor_Stage0;
	Line 1476: 04-10 11:29:02.796 18870 18997 D skia    :   18	    }
	Line 1477: 04-10 11:29:02.796 18870 18997 D skia    :   19	}
	Line 1478: 04-10 11:29:02.796 18870 18997 D skia    :   20	
	Line 1485: 04-10 11:29:02.863 18870 18997 I renderdoc: @5cad62fe0000004f@ RDOC 018870: [11:29:02]  gl_shader_funcs.cpp(1243) - Error   - Assertion failed: 'record' Couldn't identify object passed to function. Mismatched or bad GLuint? (program=6)
	Line 1486: 04-10 11:29:02.863 18870 18997 D skia    : Program linking failed.
	Line 1487: 04-10 11:29:02.863 18870 18997 D skia    : Program linking failed.
	Line 1488: 04-10 11:29:02.863 18870 18997 D skia    : VS:
	Line 1489: 04-10 11:29:02.863 18870 18997 D skia    : SKSL:
	Line 1490: 04-10 11:29:02.863 18870 18997 D skia    :    1	#version 320 es
	Line 1491: 04-10 11:29:02.863 18870 18997 D skia    :    2	uniform float4 sk_RTAdjust;
	Line 1492: 04-10 11:29:02.863 18870 18997 D skia    :    3	in float2 position;
	Line 1493: 04-10 11:29:02.863 18870 18997 D skia    :    4	in float2 textureCoords;
	Line 1494: 04-10 11:29:02.863 18870 18997 D skia    :    5	in half4 color;
	Line 1495: 04-10 11:29:02.863 18870 18997 D skia    :    6	flat out half4 vcolor_Stage0;
	Line 1496: 04-10 11:29:02.863 18870 18997 D skia    :    7	out float2 vtextureCoords_Stage0;
	Line 1497: 04-10 11:29:02.863 18870 18997 D skia    :    8	void main() 
	Line 1498: 04-10 11:29:02.863 18870 18997 D skia    :    9	{
	Line 1499: 04-10 11:29:02.863 18870 18997 D skia    :   10		// Primitive Processor TextureGeometryProcessor
	Line 1500: 04-10 11:29:02.863 18870 18997 D skia    :   11		float2 pos2 = position;
	Line 1501: 04-10 11:29:02.863 18870 18997 D skia    :   12		vcolor_Stage0 = color;
	Line 1502: 04-10 11:29:02.863 18870 18997 D skia    :   13		vtextureCoords_Stage0 = textureCoords;
	Line 1503: 04-10 11:29:02.863 18870 18997 D skia    :   14		sk_Position = float4(pos2.x , pos2.y, 0, 1);
	Line 1504: 04-10 11:29:02.863 18870 18997 D skia    :   15	}
	Line 1505: 04-10 11:29:02.863 18870 18997 D skia    :   16	
	Line 1506: 04-10 11:29:02.864 18870 18997 D skia    : GLSL:
	Line 1507: 04-10 11:29:02.864 18870 18997 D skia    :    1	#version 320 es
	Line 1508: 04-10 11:29:02.864 18870 18997 D skia    :    2	
	Line 1509: 04-10 11:29:02.864 18870 18997 D skia    :    3	precision mediump float;
	Line 1510: 04-10 11:29:02.864 18870 18997 D skia    :    4	uniform highp vec4 sk_RTAdjust;
	Line 1511: 04-10 11:29:02.864 18870 18997 D skia    :    5	in highp vec2 position;
	Line 1512: 04-10 11:29:02.864 18870 18997 D skia    :    6	in highp vec2 textureCoords;
	Line 1513: 04-10 11:29:02.864 18870 18997 D skia    :    7	in mediump vec4 color;
	Line 1514: 04-10 11:29:02.864 18870 18997 D skia    :    8	flat out mediump vec4 vcolor_Stage0;
	Line 1515: 04-10 11:29:02.864 18870 18997 D skia    :    9	out highp vec2 vtextureCoords_Stage0;
	Line 1516: 04-10 11:29:02.864 18870 18997 D skia    :   10	void main() {
	Line 1517: 04-10 11:29:02.864 18870 18997 D skia    :   11	    highp vec2 pos2 = position;
	Line 1518: 04-10 11:29:02.864 18870 18997 D skia    :   12	    vcolor_Stage0 = color;
	Line 1519: 04-10 11:29:02.864 18870 18997 D skia    :   13	    vtextureCoords_Stage0 = textureCoords;
	Line 1520: 04-10 11:29:02.864 18870 18997 D skia    :   14	    gl_Position = vec4(pos2.x, pos2.y, 0.0, 1.0);
	Line 1521: 04-10 11:29:02.864 18870 18997 D skia    :   15	    gl_Position = vec4(gl_Position.x * sk_RTAdjust.x + gl_Position.w * sk_RTAdjust.y, gl_Position.y * sk_RTAdjust.z + gl_Position.w * sk_RTAdjust.w, 0.0, gl_Position.w);
	Line 1522: 04-10 11:29:02.864 18870 18997 D skia    :   16	}
	Line 1523: 04-10 11:29:02.864 18870 18997 D skia    :   17	
	Line 1524: 04-10 11:29:02.864 18870 18997 D skia    : 
	Line 1525: 04-10 11:29:02.864 18870 18997 D skia    : FS:
	Line 1526: 04-10 11:29:02.864 18870 18997 D skia    : SKSL:
	Line 1527: 04-10 11:29:02.864 18870 18997 D skia    :    1	#version 320 es
	Line 1528: 04-10 11:29:02.864 18870 18997 D skia    :    2	uniform lowp sampler2D uTextureSampler_0_Stage0;
	Line 1529: 04-10 11:29:02.864 18870 18997 D skia    :    3	flat in half4 vcolor_Stage0;
	Line 1530: 04-10 11:29:02.864 18870 18997 D skia    :    4	in float2 vtextureCoords_Stage0;
	Line 1531: 04-10 11:29:02.864 18870 18997 D skia    :    5	out half4 sk_FragColor;
	Line 1532: 04-10 11:29:02.864 18870 18997 D skia    :    6	void main() 
	Line 1533: 04-10 11:29:02.864 18870 18997 D skia    :    7	{
	Line 1534: 04-10 11:29:02.864 18870 18997 D skia    :    8		half4 outputColor_Stage0;
	Line 1535: 04-10 11:29:02.864 18870 18997 D skia    :    9		half4 outputCoverage_Stage0;
	Line 1536: 04-10 11:29:02.864 18870 18997 D skia    :   10		{
	Line 1537: 04-10 11:29:02.864 18870 18997 D skia    :   11			// Stage 0, TextureGeometryProcessor
	Line 1538: 04-10 11:29:02.864 18870 18997 D skia    :   12			outputColor_Stage0 = vcolor_Stage0;
	Line 1539: 04-10 11:29:02.864 18870 18997 D skia    :   13			float2 texCoord;
	Line 1540: 04-10 11:29:02.864 18870 18997 D skia    :   14			texCoord = vtextureCoords_Stage0;
	Line 1541: 04-10 11:29:02.864 18870 18997 D skia    :   15			outputColor_Stage0 = outputColor_Stage0 * texture(uTextureSampler_0_Stage0, texCoord);
	Line 1542: 04-10 11:29:02.864 18870 18997 D skia    :   16			outputCoverage_Stage0 = float4(1);
	Line 1543: 04-10 11:29:02.864 18870 18997 D skia    :   17		}
	Line 1544: 04-10 11:29:02.864 18870 18997 D skia    :   18		{
	Line 1545: 04-10 11:29:02.864 18870 18997 D skia    :   19			// Xfer Processor: Porter Duff
	Line 1546: 04-10 11:29:02.864 18870 18997 D skia    :   20			sk_FragColor = outputColor_Stage0 * outputCoverage_Stage0;
	Line 1547: 04-10 11:29:02.864 18870 18997 D skia    :   21		}
	Line 1548: 04-10 11:29:02.864 18870 18997 D skia    :   22	}
	Line 1549: 04-10 11:29:02.864 18870 18997 D skia    :   23	
	Line 1550: 04-10 11:29:02.864 18870 18997 D skia    : GLSL:
	Line 1551: 04-10 11:29:02.864 18870 18997 D skia    :    1	#version 320 es
	Line 1552: 04-10 11:29:02.864 18870 18997 D skia    :    2	
	Line 1553: 04-10 11:29:02.864 18870 18997 D skia    :    3	precision mediump float;
	Line 1554: 04-10 11:29:02.864 18870 18997 D skia    :    4	out mediump vec4 sk_FragColor;
	Line 1555: 04-10 11:29:02.864 18870 18997 D skia    :    5	uniform lowp sampler2D uTextureSampler_0_Stage0;
	Line 1556: 04-10 11:29:02.864 18870 18997 D skia    :    6	flat in mediump vec4 vcolor_Stage0;
	Line 1557: 04-10 11:29:02.864 18870 18997 D skia    :    7	in highp vec2 vtextureCoords_Stage0;
	Line 1558: 04-10 11:29:02.864 18870 18997 D skia    :    8	void main() {
	Line 1559: 04-10 11:29:02.865 18870 18997 D skia    :    9	    mediump vec4 outputColor_Stage0;
	Line 1560: 04-10 11:29:02.865 18870 18997 D skia    :   10	    {
	Line 1561: 04-10 11:29:02.865 18870 18997 D skia    :   11	        outputColor_Stage0 = vcolor_Stage0;
	Line 1562: 04-10 11:29:02.865 18870 18997 D skia    :   12	        highp vec2 texCoord;
	Line 1563: 04-10 11:29:02.865 18870 18997 D skia    :   13	        texCoord = vtextureCoords_Stage0;
	Line 1564: 04-10 11:29:02.865 18870 18997 D skia    :   14	        outputColor_Stage0 = outputColor_Stage0 * texture(uTextureSampler_0_Stage0, texCoord);
	Line 1565: 04-10 11:29:02.865 18870 18997 D skia    :   15	    }
	Line 1566: 04-10 11:29:02.865 18870 18997 D skia    :   16	    {
	Line 1567: 04-10 11:29:02.865 18870 18997 D skia    :   17	        sk_FragColor = outputColor_Stage0;
	Line 1568: 04-10 11:29:02.865 18870 18997 D skia    :   18	    }
	Line 1569: 04-10 11:29:02.865 18870 18997 D skia    :   19	}
	Line 1570: 04-10 11:29:02.865 18870 18997 D skia    :   20	
	Line 1982: 04-10 11:29:04.201 18870 18997 E CRASH   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
	Line 1983: 04-10 11:29:04.201 18870 18997 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
	Line 1984: 04-10 11:29:04.201 18870 18997 E CRASH   : Build fingerprint: 'kirin/kirin/kirin:9/PPR1.180610.011/8096:eng/test-keys'
	Line 1985: 04-10 11:29:04.201 18870 18997 E CRASH   : Revision: '0'
	Line 1986: 04-10 11:29:04.201 18870 18997 E CRASH   : pid: 18870, tid: 18997, name: RenderThread  >>> com.outfit7.mytalkingtomfree.HUAWEI <<<
	Line 1986: 04-10 11:29:04.201 18870 18997 E CRASH   : pid: 18870, tid: 18997, name: RenderThread  >>> com.outfit7.mytalkingtomfree.HUAWEI <<<
	Line 1987: 04-10 11:29:04.201 18870 18997 E CRASH   :     r0 00000000  r1 ca82dd00  r2 0000bf80  r3 00000000
	Line 1988: 04-10 11:29:04.201 18870 18997 E CRASH   :     r4 cdbeed00  r5 cdfc3e80  r6 cdfc4094  r7 c85f8de0
	Line 1989: 04-10 11:29:04.201 18870 18997 E CRASH   :     r8 ca839cc0  r9 00003ffc  sl f091bf50  fp 0000000c
	Line 1990: 04-10 11:29:04.201 18870 18997 E CRASH   :     ip f25715f4  sp c85f8c38  lr d106c3a7  pc f24e5eec  cpsr 0000004d
	Line 1991: 04-10 11:29:04.201 18870 18997 E CRASH   : 
	Line 1992: 04-10 11:29:04.201 18870 18997 E CRASH   : backtrace:
	Line 1995: 04-10 11:29:04.357 18870 18997 E CRASH   : 	#00  pc 00019eec  /system/lib/libc.so (memcpy+112)
	Line 1996: 04-10 11:29:04.357 18870 18997 E CRASH   : 	#01  pc 002d63a3  /data/app/org.renderdoc.renderdoccmd.arm32-yvz5KV03_Rcy51rPZ1chcA==/lib/arm/libVkLayer_GLES_RenderDoc.so (WrappedOpenGL::glUnmapNamedBufferEXT(unsigned int)+1026)
	Line 1997: 04-10 11:29:04.357 18870 18997 F mono    : * Assertion: should not be reached at mini.c:2215

**Comment by baldurk** [comment]
This is a known bug in Skia, you'll need to update the version you're using in your application as I believe it has been fixed in the latest code.

**Comment by mimijava** [comment]
Thank you for reply.
