### ISSUE TITLE
Open capture file failed.

### ISSUE THREAD

**Issue by mimijava** [baldurk/renderdoc#1345]
## Description
When I open a capture, It's error while opening。
I had trace code flow, but I didn't find any informations for that, can you help me?

RDOC 019596: [16:49:46]   target_control.cpp( 755) - Log     - Got a new capture: 0 (frame 798) (time 1554886186) 328830 byte thumbnail
RDOC 019596: [16:49:49]    android_tools.cpp( 308) - Log     - COMMAND: D:\Android\sdk\platform-tools\adb.exe '-s 88Y0119322000031 root'
RDOC 019596: [16:50:24]    remote_server.cpp(1419) - Log     - Opening capture remotely
RDOC 019596: [16:50:24]    win32_network.cpp( 336) - Warning - recv: WSAECONNABORTED: An established connection was aborted by the software in your host machine.
RDOC 019596: [16:50:24]         streamio.cpp( 319) - Warning - Error reading from socket
RDOC 019596: [16:50:24]    remote_server.cpp(1450) - Log     - Capture open complete
RDOC 019596: [16:50:24]    **remote_server.cpp(1454) - Error   - Error opening capture**

**Comment by baldurk** [comment]
When running on android the logging for capture and replay happens on the device via `adb logcat`. In recent RenderDoc nightly builds this logging is pulled from adb, but if you are running v1.2 you'll need to manually check the logcat output to get useful logging and error information.

Please provide at least that logcat output, but ideally please follow the provided template for bug reports which you deleted, which ask for repro steps for the bug as well as your environment including RenderDoc version, OS and hardware version, and other useful information. The more information you provide the more easily I can help fix the problem.

**Comment by mimijava** [comment]
Log file is so big to upload, I'll  use email send attachment to you .
