### ISSUE TITLE
Crash on capture for Vulkan application on Android

### ISSUE THREAD

**Issue by tim4864** [baldurk/renderdoc#1346]
Hi,

I'm using the latest RenderDoc v1.2 to try to capture Vulkan application on Android.
RenderDoc is connected successfully with debug UI that "Connected by username, FPS, etc." are shown on the app. But when I press the button of capture frame immediately, it just crashed and don't know why.

I've checked the diagnostic log, and wondering if libVkLayer_GLES_RenderDoc.so is needed. But I couldn't find it on the official website of RenderDoc nor GitHub.

Every hint would be very helpful. 
Thanks.

Device: Nexus 6P
Android version: 8.1.0
Adreno GPU: 430

Log here: (log from Launch is pressed to the crash of start capturing)
[log.txt](https://github.com/baldurk/renderdoc/files/3063416/log.txt)

**Comment by baldurk** [comment]
Hi, I think I got a report from you which I've responded to directly over email. If that's you we can continue this there as I need more information to diagnose the problem and it might be easier to give me directly.

If that isn't you, can you please attach the adb logcat output from your android device, as in v1.2 the logging from the device side unfortunately doesn't get included in the host's logfile.

**Comment by tim4864** [comment]
Yes, that's me.
I'll give you more info by email.
Thanks!

**Comment by tim4864** [comment]
It was because the memory issue.
The device starts killing processes during capturing.
After making the memory usage smaller in the Vulkan application,
it is able to do capture successfully.

I'll close this thread.
Thanks again, @baldurk .
