### ISSUE TITLE
Is any plan for support Android Q version?

### ISSUE THREAD

**Issue by mimijava** [baldurk/renderdoc#1352]
## Description
Is any plan for support Android Q version?

Because Android Q isn't supported apk visit other apk's sub-directory. So renderdoccmd apk can't visit the RDC files which generated in application sub-directory.

**Comment by baldurk** [comment]
Android Q isn't released yet. When it has been released I can see whether support works out of the box or whether changes are needed and then plan for those, but it is a waste of time to try to do that until it has actually shipped.
