### ISSUE TITLE
Plugins package misses Linux builds

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#1353]
Wiki [says](https://github.com/baldurk/renderdoc/wiki/GCN-ISA) https://renderdoc.org/plugins.zip would include Linux builds, but it currently only contains android and windows builds. Please update the package if Linux is still supported.

**Comment by baldurk** [comment]
The linux plugins were split out into https://renderdoc.org/plugins.tgz, the wiki not being part of the repository is subject to rot over time.

I'll remove the specific link there and direct to the relevant place in the source tree.

**Comment by ShabbyX** [comment]
Thank you
