### ISSUE TITLE
Can't launch qt app on mac os

### ISSUE THREAD

**Issue by ShaoyuanLi** [baldurk/renderdoc#1359]
## Description

When launching a Qt based application through renderdoc a error gets logged:

`RDOC 058048: [11:14:11] gl_texture_funcs.cpp(1407) - Error   - Called texture function with invalid/unrecognised texture, or no texture bound to implicit slot`

many times .Then:

```
RDOC 061166: [13:14:02]     cgl_platform.cpp( 197) - Error   - Legacy overlay not supported on macOS
RDOC 061153: [13:14:02]   target_control.cpp( 802) - Log     - Used API: OpenGL (Presenting & supported)
RDOC 061166: [13:14:02]     cgl_platform.cpp( 197) - Error   - Legacy overlay not supported on macOS
```

Then application would quit with no extra information.

## Repro steps

1. Create a graphics application with qt
2. Launch it through renderdoc
3. Application quit with no popped window
4. click on the renderdoc log
5. observe an error about 'gl_texture_funcs.cpp'

## Environment

* RenderDoc build: v1.3 built from 09b5b5df (nightly built)
* Operating System: macOS 10.14.4
* Computer: macbook pro 15-inch 2018
* QT: 5.11.2
* API: OpenGL

**Comment by baldurk** [comment]
I'll look into this, though it looks like a known issue from #1272 - the mac code (which bear in mind is currently still a work-in-progress and is expected to have bugs) does not detect when a GL application is correctly using core profile GL or when it's using legacy GL. If you know that the application is using legacy GL that would confirm this.

This can probably be more gracefully handled but I expect capturing will not be supported.

**Comment by ShaoyuanLi** [comment]
> I'll look into this, though it looks like a known issue from #1272 - the mac code (which bear in mind is currently still a work-in-progress and is expected to have bugs) does not detect when a GL application is correctly using core profile GL or when it's using legacy GL. If you know that the application is using legacy GL that would confirm this.
> 
> This can probably be more gracefully handled but I expect capturing will not be supported.

Legacy GL = Fix Function GL?
There is no doubt that my app is a modern GL application(in fact ,my app is a graphics effect editor) but the modern gl context of my application would start after **click** a button(**create new project**). Is this the reason why renderdoc can't launch my app?
If I guess correctly ,what can i do for my debugging ?I try to edit the property **Debugger Delay** but it has no effect.

**Comment by baldurk** [comment]
Yes RenderDoc has no support for any of legacy GL meaning the fixed function pipeline, and all other functionality deprecated in the core profile of GL 3.2.

If your application creates a modern GL context later then it's possible that if I fix the crash and allow the legacy context to be ignored, you'd be able to capture the modern one. As long as there is no sharing or overlap at all with the legacy GL use.

EDIT: The "Debugger Delay" option only works on Windows at the moment, it is intended to pause an application immediately after launch so you can attach a debugger, but this can only be reliably implemented on Windows to my knowledge.

**Comment by ShaoyuanLi** [comment]
Thanks very much . I would read renderdoc source code and try to fix it.

**Comment by baldurk** [comment]
If you're interested in trying to fix it, look at `cgl_hooks.cpp` where `CreateContext` is called. When a legacy GL context is created you need to set the `core` parameter (the first `true` there) to `false`. You might be able to do it by calling `CGLDescribePixelFormat` and checking for property `kCGLPFAOpenGLProfile`, but I'm not sure if that's reliable.

Bear in mind that I'm still not sure if this will work, legacy GL is not supported so using it at all may crash RenderDoc if some assumption is violated, even if you use modern GL elsewhere in the application. It might be feasible to fix the crash, or it might not, depending on what actually goes wrong.

**Comment by baldurk** [comment]
I wasn't able to repro any crashes but I did find some bugs that I've fixed. In particular one was misreporting the extensions on a legacy context, which could have caused crashes/bad behaviour depending on what rendering was happening.

I tested on the hellogl2 and hellogles3 Qt samples - the former runs correctly but will not capture due to using legacy GL, the latter (after a patch to request a core context) captures and replays correctly for me. If you're still having trouble I'll need more information and a reproducible test case I can investigate with.

**Comment by baldurk** [comment]
Without more information I can't look into this further, as I couldn't reproduce any crashes. I fixed some bugs that might affect programs using legacy GL contexts on macOS.

If you can share a specific case that crashes or fails then please comment and I can look into it.
