### ISSUE TITLE
DX12 no-resources bounded

### ISSUE THREAD

**Issue by giordi91** [baldurk/renderdoc#1362]
## Description
I am trying to debug a dx12 application (which is well behaved). It seems like I am not able to see any resource bound like textures:
![renderDocIssue](https://user-images.githubusercontent.com/2525797/56658392-72df3580-6692-11e9-9082-7f29b6b2a569.png)

## Repro steps
Just run a simple capture, any of the draw calls do not show bound resources

Please find traced and output log here:
https://1drv.ms/f/s!Ai0n7iKmKMz0gb88FPW2zZ7v1Yvcng

## Environment
Windows 10 1809.
Intel integrated graphics on the latest driver
DX12 API
Surface Pro 5

**Comment by baldurk** [comment]
The pipeline in question is using DXIL shaders, which RenderDoc does not support. Your application must query for whether or not shader model 6 is supported via `ID3D12Device::CheckFeatureSupport(D3D12_FEATURE_SHADER_MODEL)` before uploading DXIL to the API. If you do that under RenderDoc then it will report that only shader model 5.1 at most is supported, so if you have a DXBC fallback you can use it.

**Comment by giordi91** [comment]
Oh, cool to know! Is 6.0 in the roadmap at all?

**Comment by baldurk** [comment]
Currently I haven't yet decided, as supporting DXIL would be a very large and painful undertaking.

**Comment by giordi91** [comment]
Would compile with the new compiler but for 5.1 work under render doc? Or using the new compiler will still be an issue?

**Comment by baldurk** [comment]
DXIL is equivalent to SM6 - dxc only ever outputs DXIL and so it only supports SM6 and above. Only fxc can output DXBC bytecode for SM5.1 and below.
