### ISSUE TITLE
UV View option in Mesh Output view

### ISSUE THREAD

**Issue by jamiehayes** [baldurk/renderdoc#1363]
I came into a debugging scenario where it would have been nice if I was able to view the selected "Secondary" vertex attribute of the Mesh Output view projected in UV space in the Preview pane, with the additional ability to choose from the various textures bound and used by the batch to draw the projection over.

Would be very useful in debugging UV calculations.

**Comment by baldurk** [comment]
Not all of this is possible today, but some of it is - you can right click on a vertex attribute and select "Select as Position" and it will be rendered in the preview. You can then pick vertices etc as normal from there. Similarly you can do "Select as Secondary" to choose a secondary co-ordinate to render as colour, if you select the 'secondary' solid shading mode.

You can't render it over the top of a texture, but it might be something like what you need?

![image](https://user-images.githubusercontent.com/661798/56771420-7ff14700-67ae-11e9-8f47-1151a0aa2fc6.png)

**Comment by jamiehayes** [comment]
That is very similar to what I need, but it doesn't work so well in the VS Out pane. I need to check my UVs calculated from the VS, but when I choose my UVs in the VS Output as position, a) the wireframe of the geo from the VS output sticks around, and b) the geo it's rendering (all uvs from 0-1) appear way behind the camera.

**Comment by baldurk** [comment]
Hmm, I didn't think about output data. It's considered to be in projected space so it gets unprojected, that's probably what you're seeing. I might need to find some way to configure that without making the UI too overly convoluted.

**Comment by baldurk** [comment]
With that commit you should be able to select any output attribute as position and it will only try to unproject the actual system position output, anything else will be displayed as normal.
