### ISSUE TITLE
Inconsistent subresource index between unmap & map

### ISSUE THREAD

**Issue by Samana** [baldurk/renderdoc#1364]
https://github.com/baldurk/renderdoc/blob/be231884b4c9a05dc2ee5af7148740288da8670b/renderdoc/driver/d3d12/d3d12_initstate.cpp#L883
Seems should be copyDst->Unmap(i, ..); ?

**Comment by baldurk** [comment]
Yes that seems reasonable. Do you want to make a pull request, or should I make this change?

**Comment by baldurk** [comment]
I made that change in the above commit.
