### ISSUE TITLE
Viewing different slice in 3D texture is broken

### ISSUE THREAD

**Issue by kenchen3000** [baldurk/renderdoc#1366]
## Description
I just downloaded 1.4 version. when switch between different depth slices in a RWTexture3D, it seems to be only displaying the first slice. thanks.

## Repro steps
Record a capture with 3D texture, view the 2nd slice of 3D texture, it only display the 1st slice.

## Environment

* RenderDoc release:  v1.4
* Operating System: , Ubuntu Linux
* API:  Vulkan,

**Comment by baldurk** [comment]
Thanks for the report. I added clamping in for MSAA array textures but it was being incorrectly applied, that commit should fix it.

**Comment by kenchen3000** [comment]
thanks!
