### ISSUE TITLE
Update suggests older version

### ISSUE THREAD

**Issue by vvnurmi** [baldurk/renderdoc#1368]
## Description

RenderDoc v1.4 says that a new update is available. The update window says that the new version is v1.3 which obviously is older than what I'm already running.

![renderdoc-14-update](https://user-images.githubusercontent.com/1328286/56966983-edafc100-6b68-11e9-9309-6019a1b2a039.png)

## Environment

* RenderDoc v1.4 (built from 214d85228538e71cc63a0d7fa11dd75b1d56cc81)
* Operating System: Windows 10

**Comment by baldurk** [comment]
Did you check for updates on an earlier version, e.g. v1.2, and then manually install v1.4 by hand without going through the updater?

I didn't really account for updating behind the system's back, so it's probably just displaying an old cached update message. The next time it checks for updates it should clear it, but you can force that if you go to help -> check for updates.

**Comment by vvnurmi** [comment]
I had v1.2 and I think that I did the update to v1.4 manually.

Good to know that the situation will resolve itself and that I can do it myself by explicitly checking for updates. It's not really a problem as such, just a somewhat confusing and amusing situation.

**Comment by baldurk** [comment]
No it's not a big problem but it's not ideal either! I can add a check in so that any cached update data gets checked on startup, and if it's for an old version then it gets cleared implicitly.

**Comment by baldurk** [comment]
With that commit it should save the version at the time the update is cached, and invalidate that when you run with a different version.
