### ISSUE TITLE
about glesversion

### ISSUE THREAD

**Issue by z00318884** [baldurk/renderdoc#1372]
## Description

in file ./driver/gl/gl_common.cpp
“
RDCLOG("test6------111FetchEnabledExtensions,version=%s,GLCoreVersion=%d", version, GLCoreVersion);
    if(strncmp(version, "OpenGL ES", 9) == 0)
    {
      IsGLES = true;

      int mj = int(version[10] - '0');
      int mn = int(version[12] - '0');
      GLCoreVersion = RDCMAX(GLCoreVersion, mj * 10 + mn);
    }
”
If the version is "OpenGL ES-CM 1.1 v1.r14p0-00cet0.d976e5b2d78148ce6020c4eb3ff0a2a3"

Then the GLCoreVersion will be a wrong number. Such as this is 174.

Is there a problem here?

## Environment

* RenderDoc build: e.g. v1.0, or 2018-03-12 nightly build.
* Operating System: e.g. Windows 10, 
* API: e.g., OpenGLES,

**Comment by baldurk** [comment]
RenderDoc doesn't support GLES 1.x. I can fix this check to be more robust but it will make no difference in practical terms as it's quite possible something else will break that is not so easy to fix.
