### ISSUE TITLE
eglCreateImageKHR not surpport？

### ISSUE THREAD

**Issue by z00318884** [baldurk/renderdoc#1378]
## Description

eglCreateImageKHR  not hook，unsupport？

## Environment

* RenderDoc build: e.g. v1.5, or 2019-04-30 nightly build.
* Operating System: e.g. Windows 10,
* API: e.g. OpenGLES,

**Comment by baldurk** [comment]
All egl functions are currently passed through as to my knowledge they don't need to be hooked for baseline functional support. In the case of eglCreateImageKHR I don't think it necessarily has to be hooked. If an application exports an image and it is modified elsewhere this won't show up in the capture but from looking at the sharing extensions on GLES this would not be possible to support anyway.

The corresponding `OES_EGL_image` and `OES_EGL_image_external` extensions for importing textures are not supported and I have no plans to support them.
