### ISSUE TITLE
X_GetGeometry error on ArchLinux when trying to capture Blender 2.8

### ISSUE THREAD

**Issue by Smjert** [baldurk/renderdoc#1381]
## Description
The capture immediately stops after launching it with Blender 2.8, I get the following in the console:

```
Log     - QRenderDoc initialising.
Log     - Initialising adb using 'adb'
Warning - Couldn't locate adb. Ensure adb is in PATH, ANDROID_SDK or ANDROID_HOME is set, or you configure your SDK location
Log     - Got remote handshake: bash [9573]
Read prefs: /home/smjert/.config/blender/2.80/config/userpref.blend
Received X11 Error:
	error code:   9
	request code: 14
	minor code:   0
	error text:   BadDrawable (invalid Pixmap or Window parameter)
Received X11 Error:
	error code:   9
	request code: 14
	minor code:   0
	error text:   BadDrawable (invalid Pixmap or Window parameter)
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  14 (X_GetGeometry)
  Resource id in failed request:  0x3a0001a
  Serial number of failed request:  222
  Current serial number in output stream:  222
```
I've compiled RenderDoc from source and in Debug. 

## Repro steps
1) Open RenderDoc and select the path to Blender 2.8 binary
2) Launch the capture

## Environment

* RenderDoc build: built from source, commit cfa5dd3ea 
* Operating System: ArchLinux
* API: OpenGL 

Following the diagnostic log too:
[renderdoc_diagnostic_log.txt](https://github.com/baldurk/renderdoc/files/3166935/renderdoc_diagnostic_log.txt)

**Comment by baldurk** [comment]
Does it work with the tagged commit at v1.4? Going by the log this might be a regression in 346d01b not handling proxy texture targets.

**Comment by Smjert** [comment]
Thanks for the quick response!

I just tried but it has the same issue, the console gives the same message.

Following the diagnostic log:
[renderdoc1.4_diagnostic_log.txt](https://github.com/baldurk/renderdoc/files/3167032/renderdoc1.4_diagnostic_log.txt)

The errors went away from the log it seems, though the behaviour is the same.

**Comment by baldurk** [comment]
I was using `XGetGeometry` to fetch the dimensions of windows, but that's not compatible with `GLXPixmap` which blender uses in some cases. I'm not sure why it didn't fail before, but the fix is easy enough to use `glXQueryDrawable` instead which works nicely in my testing.
