### ISSUE TITLE
Failed to replay Vulkan desktop app

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1385]
## Description

I get SIGSEGV when I'm trying to replay a Vulkan capture on desktop since this commit: https://github.com/baldurk/renderdoc/commit/699f8753af5cc3e22633b8e87d3a0eaf674e532e

The error happens in the `VulkanReplay::RenderCheckerboard()` method in `vk_replay.cpp`:
`635    vt->CmdDraw(Unwrap(cmd), 4, 1, 0, 0);`

Before the error, I get warnings like "Non-linear image 0x1b is aliased with linear buffer 0x1f which may indicate a bug.". Here is the full log: [vulkan_replay_log.txt](https://github.com/baldurk/renderdoc/files/3187168/vulkan_replay_log.txt)

(This Vulkan application doesn't have any textures.)

## Environment

* RenderDoc build: v1.x, or 2019-05-16
* Operating System: Ubuntu Linux
* API: Vulkan

**Comment by baldurk** [comment]
Please provide more information that I can use to reproduce the problem. Vulkan capture works fine for me on linux so there must be some other factor at work, perhaps specific to your application or system.

For example does it break if you capture one of Sascha Willems' samples? If not can you share the program or capture that you are using?

When attaching a log please include the full logfile as found via Help -> View Diagnostic log. Editing only a subset of the log may hide important information such as in this case your GPU and driver version, which hinders finding a fix.

**Comment by tabikati** [comment]
I have tried it with Sascha Willems' triangle example and the same thing happened. I get the error when I'm trying to replay a capture and I select the Texture Viewer tab. 
The full diagnostic log is here: [diagnostic_log.txt](https://github.com/baldurk/renderdoc/files/3191721/diagnostic_log.txt)

Vulkan API Version: 1.0.61
GPU: NVIDIA Corporation GM206 [GeForce GTX 960]

**Comment by baldurk** [comment]
I tried to repro this on my linux NV system with the triangle example but it didn't show any problems for me. I'm on a different GPU model but I wouldn't expect that to change the behaviour on a simple triangle demo.

The driver listed in your log is extremely outdated - 384.130 is over 1 year old. Can you update to a recent driver and see if that fixes the problem?

**Comment by baldurk** [comment]
I also just noticed (3a89a56cc3e25674d5bbeb82ff24029bdd844899) that I'd accidentally committed code to force on the vulkan validation layers. It worked OK for me still, but perhaps your copy of the validation layers had a bug that was causing crashes?

**Comment by tabikati** [comment]
I have updated the driver (to 390.87) and the Vulkan (to 1.1.73), it fixed the crash indeed. Also, that commit https://github.com/baldurk/renderdoc/commit/3a89a56cc3e25674d5bbeb82ff24029bdd844899 fixed it, thank you.

**Comment by baldurk** [comment]
I can't understand if updating the driver or the commit mentioned fixed the crash, but I'm glad it's sorted either way. Note that 390.87 is still 9 months old or so, I'd recommend using a recent driver.
