### ISSUE TITLE
Overlay not observed when capturing D3D12 games

### ISSUE THREAD

**Issue by GraphicsCoder** [baldurk/renderdoc#1388]
Here're the logs when capturing D3D12 games(The_Divison, Sniper_Elite_4) which the overlay aren't been observed. I can't tell whether it's a bug in RenderDoc or unsupported features. Can you help to take a look?
[RenderDoc_2019.05.17_18.07.36(The_Divison).log](https://github.com/baldurk/renderdoc/files/3200480/RenderDoc_2019.05.17_18.07.36.The_Divison.log)
[RenderDoc_2019.05.17_14.37.29(Sniper_Elite_4).log](https://github.com/baldurk/renderdoc/files/3200482/RenderDoc_2019.05.17_14.37.29.Sniper_Elite_4.log)

## Environment
* RenderDoc build: v1.4 - 29 Apr, 2019
* Operating System: Windows 10
* API: D3D12

**Comment by baldurk** [comment]
I do not condone or support capturing commercial copyrighted games that you are not the owner and creator of.

RenderDoc is intended only for debugging your own code.
