### ISSUE TITLE
Android 4.4.4 device not supported

### ISSUE THREAD

**Issue by qiankanglai** [baldurk/renderdoc#1390]
## Description

Startup and crash for a quite old android device

## Repro steps

adb logcat

	I/renderdoc(24694): @5ce4b50200000028@ RDOC 024694: [10:33:38]     android_hook.cpp(1118) - Log     - Refreshed
	I/renderdoc(24694): @5ce4b50200000029@ RDOC 024694: [10:33:38]     android_hook.cpp(1077) - Log     - Fetching 1268 original function pointers over 6 libraries
	I/renderdoc(24694): @5ce4b5020000002a@ RDOC 024694: [10:33:38]     android_hook.cpp(1093) - Log     - Finished
	I/renderdoc(24694): @5ce4b5020000002b@ RDOC 024694: [10:33:38]        egl_hooks.cpp( 701) - Debug   - EGL library hooked
	F/libc    (24694): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)
	D/dalvikvm(  950): GC_EXPLICIT freed 107K, 68% free 22551K/69848K, paused 3ms+10ms, total 116ms
	I/DEBUG   (18893): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
	I/DEBUG   (18893): Build fingerprint: 'Xiaomi/gucci/gucci:4.4.4/KTU84P/V9.2.2.0.KHKCNEK:user/release-keys'
	I/DEBUG   (18893): Revision: '0'
	I/DEBUG   (18893): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
	D/dalvikvm(23660): GC_EXPLICIT freed 554K, 39% free 10902K/17864K, paused 1ms+5ms, total 30ms
	I/DEBUG   (18893):     r0 65255f4f  r1 00000000  r2 00000001  r3 6786e940
	I/DEBUG   (18893):     r4 63ddbc55  r5 400b0d4d  r6 5eb2cb6c  r7 be930e10
	I/DEBUG   (18893):     r8 0000001b  r9 400b4678  sl 00000001  fp 65372eb8
	I/DEBUG   (18893):     ip 6537ae04  sp be930de0  lr 642bc17d  pc 00000000  cpsr 60070010
	I/DEBUG   (18893):     d0  72617262696c204c  d1  64656b6f6f682079
	I/DEBUG   (18893):     d2  20205d38333a3333  d3  6765202020202020
	I/DEBUG   (18893):     d4  2e736b6f6f685f6c  d5  3130372028707063
	I/DEBUG   (18893):     d6  75626544202d2029  d7  4745202d20202067
	I/DEBUG   (18893):     d8  0000000000000000  d9  0000000000000000
	I/DEBUG   (18893):     d10 0000000000000000  d11 0000000000000000
	I/DEBUG   (18893):     d12 0000000000000000  d13 0000000000000000
	I/DEBUG   (18893):     d14 0000000000000000  d15 0000000000000000
	I/DEBUG   (18893):     d16 0000000d00000011  d17 0000000000000000
	I/DEBUG   (18893):     d18 0000002000000004  d19 0000000000000020
	I/DEBUG   (18893):     d20 6d202c302e30203d  d21 302e31203d207861
	I/DEBUG   (18893):     d22 0000000400000000  d23 000000000000000e
	I/DEBUG   (18893):     d24 0000000000000001  d25 0000000a00000008
	I/DEBUG   (18893):     d26 000000010000000e  d27 0000000000000000
	I/DEBUG   (18893):     d28 0000000100000001  d29 0000001000000000
	I/DEBUG   (18893):     d30 0000000a00000020  d31 ffffffff00000001
	I/DEBUG   (18893):     scr 80000012
	I/DEBUG   (18893):
	I/DEBUG   (18893): backtrace:
	I/DEBUG   (18893):     #00  pc 00000000  <unknown>
	I/DEBUG   (18893):     #01  pc 0054917b  /data/app-lib/-2/libVkLayer_GLES_RenderDoc.so (EGLHooked(void*)::$_0::operator()(char const*) const+58)
	I/DEBUG   (18893):
	I/DEBUG   (18893): stack:
	I/DEBUG   (18893):          be930da0  00000002
	I/DEBUG   (18893):          be930da4  6786fbe8
	I/DEBUG   (18893):          be930da8  00000001
	I/DEBUG   (18893):          be930dac  7c34617e
	I/DEBUG   (18893):          be930db0  63ddbc55  /data/app-lib/-2/libVkLayer_GLES_RenderDoc.so (_GLOBAL__sub_I_posix_libentry.cpp)
	I/DEBUG   (18893):          be930db4  5eb2cb6c
	I/DEBUG   (18893):          be930db8  be930dd8  [stack]
	I/DEBUG   (18893):          be930dbc  6509050b  /data/app-lib/-2/libVkLayer_GLES_RenderDoc.so (_ZN21ScopedSuppressHookingC2Ev+70)

## Environment

RenderDoc 2019-05-21 Nightly Build
Android Device XiaoMi HM Note 1S (quite old one)
GL ES

## My try to fix:
after some bisection and try, I found `EGL.GetProcAddress==null` when running  ` GL.PopulateWithCallback` (https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/gl/egl_hooks.cpp#L733)

I tried a simple fix: adding `EGL_HOOKED_SYMBOLS(EGL_FETCH)` here (https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/gl/egl_hooks.cpp#L717) and it can startup now.

But when I capture successfully and replayed locally, these is only a small capture file with `swapBuffer` only
![IMG20190522_145133](https://user-images.githubusercontent.com/1546130/58153237-1d05a980-7ca1-11e9-9611-68745e5d86ae.png)

I didn't go deep into codes and any help is highly appreciated. 

Thanks in advance 😄

**Comment by baldurk** [comment]
If I understand right you're using Android 4.4.4, which is not supported - only Android 6.0 and above is supported.

You should have gotten a popup message warning you about this when selecting the device - did you? Can you upload your full log from Help -> View Diagnostic Log, and also specifically the output from `adb shell getprop ro.build.version.sdk`?

**Comment by qiankanglai** [comment]
Yes it is below Android 6.0
`adb shell getprop ro.build.version.sdk` returns 19.

I modified your code a little (just commenting out `android_dlopen_ext` which exists after API 21) and makes it runnable. Other devices work well in fact. (RenderDoc is the only tool helping me debug rendering issues on old devices, so I made some workaround)

	RDOC 015792: [15:23:22]             core.cpp( 351) - Log     - RenderDoc v1.5 Windows 64-bit Release (775fa9b63521678ea16dde7b31f77125885cc752) loaded in replay application
	QTRD 015792: [15:23:22]       qrenderdoc.cpp(  88) - Log     - QRenderDoc initialising.
	RDOC 015792: [15:23:23]    android_tools.cpp( 334) - Log     - Initialising adb using 'E:\Android\android-sdks\platform-tools\adb.exe'
	RDOC 015792: [15:23:24]    android_tools.cpp( 308) - Log     - COMMAND: E:\Android\android-sdks\platform-tools\adb.exe '-s 44ad7793 root'
	RDOC 015792: [15:23:24]    android_tools.cpp( 308) - Log     - COMMAND: E:\Android\android-sdks\platform-tools\adb.exe '-s 44ad7793 shell getprop ro.product.manufacturer'
	RDOC 015792: [15:23:24]    android_tools.cpp( 308) - Log     - COMMAND: E:\Android\android-sdks\platform-tools\adb.exe '-s 44ad7793 shell getprop ro.product.model'
	RDOC 015792: [15:23:24]    android_tools.cpp( 308) - Log     - COMMAND: E:\Android\android-sdks\platform-tools\adb.exe '-s 44ad7793 shell getprop ro.build.version.sdk'
	RDOC 015792: [15:23:24]    android_utils.cpp( 147) - Warning - Device '' is on api version 0 which is not supported
	RDOC 015792: [15:23:32]   target_control.cpp( 566) - Log     - Got remote handshake:  [4814]
	RDOC 015792: [15:23:33]   target_control.cpp( 566) - Log     - Got remote handshake:  [4814]
	RDOC 015792: [15:23:33]   target_control.cpp( 802) - Log     - Used API: OpenGLES (Presenting & supported)
	RDOC 015792: [15:23:48]   target_control.cpp( 802) - Log     - Used API: OpenGLES (Not presenting & supported)
	RDOC 015792: [15:24:01]   target_control.cpp( 802) - Log     - Used API: OpenGLES (Presenting & supported)
	RDOC 015792: [15:24:07]   target_control.cpp( 755) - Log     - Got a new capture: 0 (frame 37) (time 1558509851) 57740 byte thumbnail

**Comment by baldurk** [comment]
It's strange that the version is detected as 0 instead of 19 - is the output not a simple number, does it have some other text? Can you paste the raw output from that command?

Either way though that means that it should have been detected as unsupported. If you didn't get the popup about it being an unsupported device then I'd like to fix that, but otherwise there's nothing I'm going to do here to fix this.

Realistically I cannot support old Android versions indefinitely. I already have a lot of trouble reproducing problems people have even on newer devices due to the wide variety that's available, I can't also try to handle really old versions of Android that I can't run.

With that said I'm glad you found a local workaround that works and obviously that's fine even if I can't support it myself. If you can find a way to make the fix which won't break newer Android versions with 100% certainty then you can open a pull request, but I don't want to risk breaking supported Android devices.

**Comment by qiankanglai** [comment]
It is indeed a lot of hard work to support so many API & platforms. So I'm just asking for some guidence or possible reasons, not asking for official support.

Really appreciate your great work 👍

**Comment by baldurk** [comment]
Yeh I understand, but even guidance and help is a form of official support since it takes time away from other issues. Also unfortunately especially with hooking/interception problems like this it's very device and platform specific so I can't even guess what the problem would be without being able to reproduce on a similar device.

If you have it working from your own fix then that's great, and like I say if you have fixes for unsupported platforms/versions like this which can be safely added without breaking supported platforms, I'm happy to include them - I just can't then support them from there on.
