### ISSUE TITLE
Should VK_LAYER_RENDERDOC_Capture be enabled on instance creation?

### ISSUE THREAD

**Issue by Zingam** [baldurk/renderdoc#1392]
When I create a Vulkan instance should I also add VK_LAYER_RENDERDOC_Capture to the enabled layers? I wasn't able to see any mentioning of it in the docs.

https://renderdoc.org/docs/behind_scenes/vulkan_support.html#stadia

P.S. Thank you very much for: https://renderdoc.org/renderdoc-history.html A great and inspirational story to read.

**Comment by baldurk** [comment]
You should never add the vulkan layer manually, always launch your program through RenderDoc as documented to ensure it is set up correctly.

**Comment by Zingam** [comment]
@baldurk Does by any chance the installation of  RenderDoc and the layer impact the performance of other Vulkan applications?

**Comment by baldurk** [comment]
If RenderDoc has a capture open for replay it will have some performance impact just like any other program using the GPU, and there is a cost to having RenderDoc active and capturing an application. If you mean just having RenderDoc installed but not running in any way, then no that won't affect anything.
