### ISSUE TITLE
Wrong time in capture file timestamp

### ISSUE THREAD

**Issue by bioglaze** [baldurk/renderdoc#1393]
## Description
I took a capture when my Windows clock was 12:35 but the capture time in RenderDoc was displayed as 10:35 so it looks like it doesn't handle timezones. My timezone is UTC + 2.

## Environment

* RenderDoc build: e.g. v1.4
* Operating System: Windows 10 version 1809
* API: D3D12

**Comment by baldurk** [comment]
It seems like creating a date in Qt defaults to local time even if I'm trying to create the time_t epoch which should be UTC. I think it should be fixed with that commit.
