### ISSUE TITLE
Newly built renderdoccmd apk size is more compared to apk in released binary tar ball 

### ISSUE THREAD

**Issue by gittmi** [baldurk/renderdoc#1398]
## Description
I am building RenderDoc v1.4 on Linux for arm 64 android device.
After building I could see that the size of org.renderdoc.renderdoccmd.arm64.apk is around 51 MB. 
I checked out the Release tar binary and I found org.renderdoc.renderdoccmd.arm64.apk is just 5.8 MB. I followed the instructions from the documentation provided.
libVkLayer_GLES_RenderDoc.so is of size 250MB. 

How can I build for release binaries?

## Environment

* RenderDoc build: v1.4
* Operating System: Ubuntu Linux

**Comment by baldurk** [comment]
The official builds have symbols stripped out to produce a smaller download. For local builds I don't recommend this as you need to debug with your local build, and you don't have anything to download.
