### ISSUE TITLE
Feature request: Export constant buffers to CSV

### ISSUE THREAD

**Issue by inequation** [baldurk/renderdoc#140]
For instance, for quick comparison between captures.

**Comment by baldurk** [comment]
FYI you can select some constants and hit ctrl-c to copy the contents to clipboard, but yes an explicit export in a fixed CSV format should be added.

**Comment by inequation** [comment]
Thanks, that will do for a temporary workaround. ;)

**Comment by inequation** [comment]
Works as advertised. :)
