### ISSUE TITLE
glDeleteProgram is called for 0 value

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1406]
## Description

When I switch between captures to replay on Android, `glDeleteProgram` is called for 0 value many times in `GLReplay::DeleteDebugData()` (gl_debug.cpp), and I get debug callback messages like 'not a program object' and ' unable to delete program'.

It would be good to check if a program is not zero before calling `glDeleteProgram` like it's already checked for **DebugData.overlayProg** here:
https://github.com/baldurk/renderdoc/blob/217506869fa0f345e3014a98d0842ddfced00445/renderdoc/driver/gl/gl_debug.cpp#L1073

For example, **DebugData.quadoverdrawResolveProg** doesn't get any value for GLES and **DebugData.meshProg**[1/2/3] depends on extensions, so if they remain 0, calling `glDeleteProgram` for them will cause unnecessary debug messages.

The same thing happens for this shader too: https://github.com/baldurk/renderdoc/blob/217506869fa0f345e3014a98d0842ddfced00445/renderdoc/driver/gl/gl_debug.cpp#L1087

## Environment

* RenderDoc build:  v1.x
* Operating System: Android 7.0
* API: OpenGL ES

**Comment by baldurk** [comment]
This is clearly a driver bug. The GL and GLES specs are very clear that glDeleteProgram and glDeleteShader do nothing when passed 0. E.g.:

> If program is not current for any GL context, is not the active program for any program pipeline object, and is not the current program for any stage of any program pipeline object, it is deleted immediately. Otherwise, program is flagged for deletion and will be deleted after all of these conditions become true. When a program object is deleted, all shader objects attached to it are detached. **`DeleteProgram` will silently ignore the value zero.**

> If shader is not attached to any program object, it is deleted immediately. Otherwise, shader is flagged for deletion and will be deleted when it is no longer attached to any program object. If an object is flagged for deletion, its boolean status bit `DELETE_STATUS` is set to true. The value of `DELETE_STATUS` can be queried with `GetShaderiv` (see section 7.12). **`DeleteShader` will silently ignore the value zero.**

I can put in a check anyway, especially since Android being a terrible platform means this bug will likely never be fixed.

**Comment by tabikati** [comment]
We can make a pull request for it if it's good for you.

**Comment by baldurk** [comment]
As I said in the comment above, I will add checks for it since it's not a big deal to check for 0 redundantly.

**Comment by tabikati** [comment]
Thank you for the commit, it is really better now but I noticed that this line was removed:

`1132            DebugData.minmaxResultProgram[i] = 0;`

It is in an embedded 'for' cycle, and since DebugData.minmaxResultProgram[i]  won't be 0,  it will try to delete the same program more times and it causes these debug messages:

- Got a Debug message from GL_DEBUG_SOURCE_API, type GL_DEBUG_TYPE_ERROR, ID 1281, severity GL_DEBUG_SEVERITY_HIGH:
'GL_INVALID_VALUE error generated. Handle does not refer to a shader or program object.'

- Got a Debug message from GL_DEBUG_SOURCE_API, type GL_DEBUG_TYPE_ERROR, ID 2147483647, severity GL_DEBUG_SEVERITY_HIGH:
'program %d is not a program object'

Since it is in an embedded 'for' cycle, `glDeleteProgram` is called more times than it is needed. I think it would be better to move it to a separate for cycle like here: https://github.com/tabikati/renderdoc/commit/2212cd23cd10723dff561f02f0baf9f30a4c2917
Would you like me to send a pull request for this fix?

**Comment by baldurk** [comment]
Fixed in that commit.
