### ISSUE TITLE
Feature: show shader code after pre-processor

### ISSUE THREAD

**Issue by ssylvan** [baldurk/renderdoc#1408]
## Description
We have a lot of horrible #defines and macros in our shaders. I just spent a whole day tracking down an issue with macros in GLSL. I kinda knew it was probably something to do with preprocessing a while back, but didn't have a convenient way to see the post-preprocessed version of the shader. If Renderdoc would show me the shader after pre-processing (on a toggle) I probably would've found this issue many hours ago. So here's a feature request for that!

**Comment by baldurk** [comment]
I don't think this merits being a first class feature, similar to #709, but as in that issue you can get the results you want by configuring a shader processing tool to do the transformation for you. If you set up a tool with GLSL as input and GLSL output that pipes the source through a pre-processor, then you can select it as a 'disassembly' view in the shader viewer.
