### ISSUE TITLE
Linux host app building in release mode

### ISSUE THREAD

**Issue by gittmi** [baldurk/renderdoc#1410]
## Description

I am trying to build the linux host app in release mode using 
_cmake -DCMAKE_BUILD_TYPE=Release -Bbuild -H._
But, When I am trying to run the host app on other Linux machine, It is depending on Qt libs.

I observed the release binaries downloaded from official release package seems to be statically linked with Qt libs.
How to build Linux host app same as the ones you packaged in release binaries?

I am doing this beacuse I added support for x86 platform. 
I want to rebuild the binaries in the packaged format by stripping out all un-needed symbols. So that, they can be run on any linux host machine with minimum binary size.

BTW, I tried building using the below command also from compile_docker.sh script.
_CC=clang CXX=clang++ CFLAGS="-fPIC -fvisibility=hidden" LDFLAGS="-static-libstdc++" 
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=./io/dist/  -DSTATIC_QRENDERDOC=ON -DQRENDERDOC_NO_CXX11_REGEX=ON renderdoc_

## Environment

* RenderDoc build: v1.4
* Operating System:  Ubuntu Linux
* API: OpenGL

**Comment by baldurk** [comment]
I don't know what you mean by 'host app' - I assume you mean the normal program.

I strongly recommend against static linking or stripping symbols, as unless you're very careful with your dependencies it's easy to produce a program that doesn't work on other machines with slightly different system library versions. When you are using a locally modified version on your own computers then there's negligible gain in being conservative about your program size or dependencies. Instead you could build it yourself once then install the appropriate Qt libraries on any computer you want to run it on.

If you still want to try it then the [build scripts I use for nightly and official builds are public](https://github.com/baldurk/renderdoc/tree/v1.x/util/buildscripts) which I assume you've already seen as you referenced them above. You can refer to them if you want to see how the static linking is done, but you're on your own as to any problems you encounter. I can only feasibly help with compiling the unmodified github code from source, or running the binary builds I produce.
