### ISSUE TITLE
Capture Queue capture nothing

### ISSUE THREAD

**Issue by lagorsse** [baldurk/renderdoc#1411]
Hi,

I am having an issue with the queue capture functionality, which for me doesn't work at all if I understand it correctly, I saw some unresolved related issue but closed. (#857)

I am using the injection functionality, I am injecting at the right moment and normal capture works fine, but if I check the box to get some specifics frame (in my case frame 0) and some subsequence frame, I don't know yet if I need them or not. It doesn't work at all, nothing is captured, even if I set frame 200 it won't capture it when I pass this frame.

Is it how this feature is supposed to work?

I am on OpenGL but it's for an OpenGL + Vulkan app, W10
Render doc 1.4 https://github.com/baldurk/renderdoc/commit/214d85228538e71cc63a0d7fa11dd75b1d56cc81

**Comment by baldurk** [comment]
I believe that commit should fix it. Specifically when injecting the callback that handled queuing captures wasn't run.

All that being the case I would very strongly recommend *not* relying on injecting into running processes as it is unreliable and fragile, there are a number of cases where it simply won't work correctly which can be very hard to track down. It's much more reliable to use the normal capture workflow where RenderDoc launches the process.
