### ISSUE TITLE
DrawAuto() primitive counts are garbage when calling ClearState after stream out

### ISSUE THREAD

**Issue by chrvoss** [baldurk/renderdoc#1412]
## Description

In D3D11, the following sequence of events results in an incorrectly replayed capture as the stream out primitive count isn't queried correctly:

    // [Snip other state setup]
    ID3D11Buffer* streamOutBuffer = /*...*/;
    context->SOSetTargets(1, &streamOutBuffer, nullptr);
    context->Draw();
    context->ClearState();

    // [Snip other state setup]
    context->IASetVertexBuffers(0, 1, &streamOutBuffer, &vertexStrides, &vertexOffsets);
    context->DrawAuto();

In the replayed capture, the vertex count for DrawAuto() is always shown as some random small number or 0.

## Repro steps

The root cause appears to be that RDC auto-inserts D3D11_QUERY_DATA_SO_STATISTICS queries to capture the primitive count before SOSetTargets, and ends these queries on the next call to SOSetTargets that changes or resets the stream out setup. However the code for inserting the query End() call is skipped if the state is reset via ClearState() instead.

Inserting a call to SOSetTargets(0, nullptr, nullptr); before calling ClearState() results in correctly replaying the capture with the expected vertex counts.

Unfortunately I can't share the full repro capture, and I was unable to find a public sample that uses DrawAuto. If you have a test app for DrawAuto I'd be happy to reproduce the bug with it.

## Environment

* RenderDoc build: v1.4
* Operating System: Windows 10
* API: D3D11

**Comment by baldurk** [comment]
Thanks for the detailed bug report, your analysis is exactly right. I've added the handling to stop those queries in ClearState() and it should work correctly. I used a simple test-case to verify but it would be good if you could double check.

In theory there are other ways for the stream-out buffers to become unbound without going through either SOSetTargets() or ClearState() but hopefully no-one will hit those cases...

**Comment by chrvoss** [comment]
Awesome, thank you for fixing this so quickly!
