### ISSUE TITLE
AndroidManifest.xml is malformed after patching

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1415]
## Description

After patching a not debuggable APK with RenderDoc, the patched APK can't be decoded with apktool because the AndroidManifest.xml is malformed (it has a wrong closing tag name).
Analyzing the patched APK with Android Studio, I get the following AndroidManifest.xml: [patched_manifest.txt](https://github.com/baldurk/renderdoc/files/3285059/patched_manifest.txt)

It happens when the "debuggable" attribute is added to the manifest file and it's size increases but the "end" point is not updated to the new manifest size. In this case, when the stringpool ids are updated, the loop does not reach the end because the original manifest end point is used.

A possible fix for this issue which I have tested and works for me: 
https://github.com/tabikati/renderdoc/commit/8eae2658292b65dafad14394a9b2e8d0731b0230
I will create a pull request if you would like. 

## Environment

* RenderDoc build: v1.x, 2019-06-12.
* Operating System: Android

**Comment by baldurk** [comment]
Can you share a repro case for this so that I can investigate? Either the APK you were testing with or an equivalent build that still reproduces the problem?

**Comment by tabikati** [comment]
Here is the APK: [app.zip](https://github.com/baldurk/renderdoc/files/3285665/app.zip)

**Comment by baldurk** [comment]
This should be fixed with that commit.
