### ISSUE TITLE
Renderdoc leaks file descriptors

### ISSUE THREAD

**Issue by DataBeaver** [baldurk/renderdoc#1424]
## Description

Renderdoc opens a new pipe every few seconds but does not close it.  Eventually I get messages like this on the console:

Error   - Could not create AF_NETLINK socket (Too many open files)
Error   - Could not create stdout pipe
Error   - Could not create stderr pipe

This does not seem to be immediately fatal, but trying to start a process in this state will crash renderdoc as it can't open the pipes needed to communicate with the process.

The rate seems to be about one fd every 3.75 seconds, and the granularity is two fds at once, so most likely renderdoc tries to open one pipe (two fds) every 7.5 seconds.

## Repro steps

1. Start renderdoc
2. Observe /proc/`pidof qrenderdoc`/fd and see the number of fds increasing
3. After some time, the fd limit will be reached and messages will be printed (this could take upwards of an hour with typical ulimit values)

## Environment

* Renderdoc v1.x 38f0d27 (self-compiled)
* Debian unstable (mostly up-to-date)
* RTX 2070
* Nvidia driver 418.74

**Comment by baldurk** [comment]
Thanks for the report! When opening pipes to communicate with a child process I wasn't properly closing the pipes if the process failed to run. `adb` is run intermittently to watch for android devices being connected or disconnected, and that was what was leaking here.
