### ISSUE TITLE
DXGI_FORMAT_A8_UNORM is reported as R8_UNORM with D3D11

### ISSUE THREAD

**Issue by cperthuisoc** [baldurk/renderdoc#1426]
## Description

Textures created with DXGI_FORMAT_A8_UNORM are reported as R8_UNORM in the status bar while correctly being interpreted as A8: float4(0,0,0,A) in the 2D texture view. 
I think that it would be best to identify them as A8_UNORM to avoid any confusion.

![image](https://user-images.githubusercontent.com/50219093/60119818-3385a180-9734-11e9-98f2-65081ad8eab9.png)

## Repro steps

Create a DXGI_FORMAT_A8_UNORM and use it in a drawcall. 

## Environment

* RenderDoc build: v1.4,  214d8522
* Operating System: Windows 10
* API: D3D11

**Comment by baldurk** [comment]
It should display correctly with that commit. Alpha-only formats had been deprecated in modern GL so I didn't realise that D3D still had such a format, since AFAIK it's redundant on modern GPUs and only really made sense on fixed function pipelines.
