### ISSUE TITLE
Android Q Preview handshake failed.

### ISSUE THREAD

**Issue by mimijava** [baldurk/renderdoc#1429]
## Description
When Android Phone update to Android Q Preview Version. It's can't handshake.

RDOC 022792: [17:40:10]    android_tools.cpp( 308) - Log     - COMMAND: D:/Android/sdk/platform-tools/adb '-s URM0119405000969 shell pm path com.tencent.tmgp.pubgmhd'
RDOC 022792: [17:40:10]    android_tools.cpp( 308) - Log     - COMMAND: D:/Android/sdk/platform-tools/adb '-s URM0119405000969 shell ls /data/app/com.tencent.tmgp.pubgmhd-moIoZLShS0EqwB-kIW9C0A==//lib/*/libVkLayer_GLES_RenderDoc.so'
RDOC 022792: [17:40:10]          android.cpp( 242) - Log     - No library found in /data/app/com.tencent.tmgp.pubgmhd-moIoZLShS0EqwB-kIW9C0A==//lib/*/libVkLayer_GLES_RenderDoc.so for com.tencent.tmgp.pubgmhd - assuming injection is required.
RDOC 022792: [17:40:10]          android.cpp( 252) - Log     - Launching package 'com.tencent.tmgp.pubgmhd' with activity 'com.epicgames.ue4.SplashActivity'
RDOC 022792: [17:40:10]          android.cpp( 256) - Log     - Setting up to launch the application as a debugger to inject.
RDOC 022792: [17:40:10]    android_tools.cpp( 308) - Log     - COMMAND: D:/Android/sdk/platform-tools/adb '-s URM0119405000969 shell am start -S -D -n com.tencent.tmgp.pubgmhd/com.epicgames.ue4.SplashActivity '
RDOC 022792: [17:40:11]    android_tools.cpp( 308) - Log     - COMMAND: D:/Android/sdk/platform-tools/adb '-s URM0119405000969 shell ps -A | grep com.tencent.tmgp.pubgmhd'
RDOC 022792: [17:40:11]    android_utils.cpp( 648) - Warning - Couldn't find last line. Potentially missed logcat messages.
RDOC 022792: [17:40:11]    android_tools.cpp( 308) - Log     - COMMAND: D:/Android/sdk/platform-tools/adb '-s URM0119405000969 forward tcp:22019 localabstract:seagull-gator-socket'
RDOC 022792: [17:40:11]    android_tools.cpp( 308) - Log     - COMMAND: D:/Android/sdk/platform-tools/adb '-s URM0119405000969 forward tcp:39930 localabstract:seagull-trace-socket'
RDOC 022792: [17:40:11]    android_tools.cpp( 308) - Log     - COMMAND: D:/Android/sdk/platform-tools/adb '-s URM0119405000969 forward tcp:39970 localabstract:renderdoc_39920'
RDOC 022792: [17:40:11]    android_tools.cpp( 308) - Log     - COMMAND: D:/Android/sdk/platform-tools/adb '-s URM0119405000969 forward tcp:38970 localabstract:renderdoc_38920'
RDOC 022792: [17:40:11]    android_tools.cpp( 308) - Log     - COMMAND: D:/Android/sdk/platform-tools/adb '-s URM0119405000969 forward tcp:39021 jdwp:20271'
RDOC 022792: [17:40:12]         streamio.cpp( 319) - Warning - Error reading from socket
RDOC 022792: [17:40:12]          android.cpp( 293) - Error   - Failed to inject using JDWP

## Repro steps
1. Launcher a game apk failed.

## Environment
* RenderDoc build: newest
* Operating System: Windows 10
* API: OpenGL

**Comment by mimijava** [comment]
Connection::Connection(Network::Socket *sock)
    : writer(sock, Ownership::Nothing), reader(sock, Ownership::Nothing)
{
  // the first thing we do is write the handshake bytes and expect them immediately echo'd back.
  const int handshakeLength = 14;
  const char handshake[handshakeLength + 1] = "JDWP-Handshake";

  writer.Write(handshake, handshakeLength);
  writer.Flush();

  char response[15] = {};
  reader.Read(response, handshakeLength);

  if(memcmp(handshake, response, 14))
  {
error here: ///    RDCERR("handshake failed - received >%s< - expected >%s<", response, handshake);
    error = true;
  }

respone is empty.

**Comment by baldurk** [comment]
You opened an issue a few months ago #1352 asking if Android Q was supported and I said there that it won't be supported until at least after it is released. That hasn't changed because it still hasn't been released - once it's out I will see what needs to happen to support it.
