### ISSUE TITLE
Issue with ld_structured_indexable in shader debugger

### ISSUE THREAD

**Issue by jamiehayes** [baldurk/renderdoc#143]
I'm using RenderDoc 0.25 and I think I'm seeing a bug in the shader debugger where an ld_structured_indexable isn't returning what I ought to expect. Here's some info:

* I'm creating an SRV for a single element of a larger structured buffer. In this case, the start index is 5, the number of elements is 1.
* The structure is just 5 uints, and I can see the first three in the struct are non-zero in the buffer view on the batch in question
* In the vertex shader, I'm only loading the first three uints, and the last uint of the first element of the buffer. The loads look like this:

ld_structured_indexable(structured_buffer, stride=20)(mixed,mixed,mixed,mixed) r0.x, l(0), l(16), mybuffer.xxxx
ld_structured_indexable(structured_buffer, stride=20)(mixed,mixed,mixed,mixed) r0.yzw, l(0), l(0), mybuffer.xxyz

The first load above shows zero in r0.x, which I expect. However, none of the three values loaded into r0.yzw should be zero, based on the contents of the buffer view. Maybe a bug in the swizzle handling of this instruction in the debugger?

If I get desperate, I might dig into the source to try the source of the problem myself. If I discover it, I'll respond to this thread.

**Comment by baldurk** [comment]
I think this should do the trick. I was adding the first element offset onto the index before checking against the number of elements, which is wrong, so the lookup was getting written with 0s for out of bounds.

**Comment by jamiehayes** [comment]
I can confirm that this fixed my issue. Thanks!

**Comment by baldurk** [comment]
Awesome :).

**Comment by EvgeniiG** [comment]
Is there any chance this bug is back in 1.5?
My ld_structured_indexable appears to return 0s, which contradicts the view of the contents of the buffer.

Edit: tested 1.4 and the issue does not seem to show up.

**Comment by baldurk** [comment]
It wasn't this bug, but yes I believe there was a regression in v1.5 that could cause structured and raw buffer loads to incorrectly return 0. It has since been fixed, so if you try a recent nightly build the shader debugger should return the correct results.

**Comment by EvgeniiG** [comment]
Excellent. Thank you, Baldur!
