### ISSUE TITLE
"Unexpected storage class for global: StorageBuffer" and SPIR-V 1.3 support

### ISSUE THREAD

**Issue by godlikepanos** [baldurk/renderdoc#1431]
## Description

Storage buffers don't appear in the "pipeline state" view. Getting the following message in stdout:
```
Unexpected storage class for global: StorageBuffer
```

The shader source also fails to display . The message is:
```
SPIR-V 1.3:

Unsupported version
```

These issues are probably related.

## Repro steps

This is a capture file: https://drive.google.com/file/d/17VabaeuROzNXpHZEcOVSsSx5CtP82liq/view?usp=sharing

(The file doesn't have an extension. It's impossible from the gnome's file dialog to find out which is the extension renderdoc is using)

Try to view the resources of the first vkCmdDispatch. It should be having two storage buffers. One in set 1, binding 0 and the other in set 1, binding 2.

## Environment

* RenderDoc build: Built from source. Branch v1.x at 10f83298beafe4b0390ddbd9ec749ea47b9b7977
* Operating System: Ubuntu Linux 18.04
* API: Vulkan

**Comment by baldurk** [comment]
That commit should handle the new SPIR-V storage class for SSBOs. Disassembly is still not supported, I've got a new json-based disassembler in the works so I'm not planning to update that legacy disassembler to work beyond being able to reflect shaders correctly.

> (The file doesn't have an extension. It's impossible from the gnome's file dialog to find out which is the extension renderdoc is using)

I thought this must be some kind of bug on my side, but no this really is how GNOME works apparently and I can repro it. In fact the file browser does actually filter to the right extension (which is `.rdc` FYI) but then doesn't append it or display it anywhere for you to manually add it when typing a filename. I could append it myself if it's not there, but then you have the risk of creating an overwrite that wasn't prompted for. Urgh.
