### ISSUE TITLE
sigsegv when trying to inspect a drawcall

### ISSUE THREAD

**Issue by Jiboo** [baldurk/renderdoc#1432]
## Description

Crash while trying to inspect a vkCmdDrawIndexed.
~It's probably related to my program, though I'm not seeing any validation warning and wished to inspect the problem with renderdoc.~
I can use the pipeline inspection widget on the vkCmdEndRenderPass just after the draw call, ~although the vertices buffer seems completely off, and am not sure I should inspect there.~ Edit: I get the same behaviour with "vkcube".
Might be related to #554.

## Repro steps

Open the provided capture, unfold "Colour Pass #1", click on "vkCmdDrawIndexed(6, 1)".

## Environment

* RenderDoc built from sources 10f83298beafe4b0390ddbd9ec749ea47b9b7977
* Operating System: Fedora 30
* mesa 19.0.6, kernel 5.1.15
* API: Vulkan
* vulkaninfo: https://gist.github.com/Jiboo/32f0ad6add5c26bf0b7b9873f6c697ce
* Pretty sure the selected device by the application was the Vega20.
* Sample frame capture that reproduce the crash: https://drive.google.com/file/d/1FLyOF-UKbYiM3RaOmhSn-82f-PE6O3nS/view?usp=sharing
* ~x64 linux version of the program to reproduce (any frame after the font is loaded would do), but probably not usable as is: https://drive.google.com/file/d/1x-W0Ym9qI45IvSW9DwkcNrbmJuydPzNV/view?usp=sharing~ edit: same behaviour with vkcube
* valgrind log: https://gist.github.com/Jiboo/b109d2635622c7054593357f9269b5b6
* gdb log: https://gist.github.com/Jiboo/53342c5de94dc489ce737bd64a36f8bb

**Comment by baldurk** [comment]
Looks like this was a regression added at the end of last week, should be fixed with that commit.

In general if you don't need the latest code for something it's a good idea to stick with the stable versions since they get the most testing, bleeding edge branch tip can get broken sometimes.
