### ISSUE TITLE
Oculus Quest app crashes when loading demanding scene with RenderDoc attached

### ISSUE THREAD

**Issue by jkant** [baldurk/renderdoc#1435]
## Description

I'm trying to diagnose a scene in an Oculus Quest title (in development) that is hitting the device's GPU hard. I am able to attach RenderDoc to the Quest, launch/attach to the game, and capture frames from other parts of the game.

However, as soon as I try to load into the scene in question, the app crashes out and RenderDoc disconnects. Unfortunately I'm not seeing particularly useful messages in the relevant log files. While the scene is demanding on the device (hence wanting to capture it) it doesn't crash unless RenderDoc is attached.

Including log files from RenderDoc and adb. Any help would be much appreciated! Thanks.

[bugreport-256550.6810.0-2019-07-02-12-22-36.txt](https://github.com/baldurk/renderdoc/files/3352058/bugreport-256550.6810.0-2019-07-02-12-22-36.txt)
[CrashLog.log](https://github.com/baldurk/renderdoc/files/3352060/CrashLog.log)

## Repro steps

Attach RenderDoc to Oculus Quest replay context
Launch app in question
Load into scene in question
Crash

## Environment

* RenderDoc build: 6/30/2019 nightly build
* Operating System: profiling Oculus Quest/Android on Windows 10
* API: OpenGLES 3.1

**Comment by baldurk** [comment]
Unfortunately I don't have any immediate ideas what this might be. The repro steps are not too useful if I don't have your app to be able to follow them - are you able to share your app with me privately?

Normally if there's an actual crash then the android system dumps out a callstack which would appear in the log, but there's nothing like that - it maybe suggests you're hitting out-of-memory and the crash is actually a forced process kill? I don't know what the bugreport.txt is from and without being familiar with it I can't find much useful in it. There are some mentions of out of memory errors but I can't tell whether or not they happened at the same time as the crash.

It could be that the scene you're interested in is skating very close to the memory limit, and the extra overhead that RenderDoc brings in GLES mode pushes it over the top. At the moment there's not much that you can do about that apart from maybe loading lower resolution textures or smaller asset LODs - if that still reproduces your bug you might then be able to get a capture.

**Comment by DmitrySoshnikov** [comment]
@jkant, can you contact also Oculus Store Ops passing the App ID, and the app title? If your app is still under development, and you can't share it here, Oculus developers should be able to test it, and probably check specific scene issue. Also, does this crash happens while your app is running in background in Renderdoc, or on Active capture?

**Comment by jkant** [comment]
Turns out this was an out of memory issue. Sorry for the false alarm!!

**Comment by DmitrySoshnikov** [comment]
@jkant, thanks for confirming. Yes, we're investigating OOM issue right now (https://github.com/baldurk/renderdoc/pull/1434 is for Active capturing, and we'll need to look into background capturing issues as well).
