### ISSUE TITLE
QRenderDoc not responding during load

### ISSUE THREAD

**Issue by kyamant** [baldurk/renderdoc#1436]
## Description

Capturing a single frame from a simple app works.
During the reload QRenderDoc becomes "not responding" with heavy cpu usage.

## Repro steps
Start the app, capture a frame and reload of that capture file causes hang.
I would like to try a known good capture file so that the problem can be further narrowed down.
[MyRenderCapture.zip](https://github.com/baldurk/renderdoc/files/3352102/MyRenderCapture.zip)

## Environment

* RenderDoc build: 1.4
* Operating System: Windows 10 Pro x64
* API: Vulkan 1.1.82.1
* GPU: Nvidia GTX 1050Ti
* GPU Driver: 417.22

**Comment by baldurk** [comment]
I'm able to load this capture fine on both of my nvidia systems, so I don't think there's anything intrinsically wrong with what's been captured.

There's a couple of things you could try: your nvidia driver is a little old, updating to a recent driver might fix the issue. I notice from the capture that you also have an intel GPU in your system, it's worth updating the graphics drivers for that as well as recently there have been some crashes and problems caused by out of date Intel drivers on hybrid GPU laptops.

It would also be useful to know if you have problems with a known-good sample such as `vkcube.exe` from the Vulkan SDK. If that still has issues for you then you know that it's something with your system configuration and not the program you're capturing.

**Comment by kyamant** [comment]
I tried loading a previously saved rdc file.  The bottom of the screen reads "...rdc loaded. No problems detected", but the app just froze. 
I am attaching the log file from this session.
Nvidia gpu activity shows qrenderdoc.exe
[RenderDoc_2019.07.03_02.57.35.log](https://github.com/baldurk/renderdoc/files/3354458/RenderDoc_2019.07.03_02.57.35.log)

**Comment by baldurk** [comment]
OK but can you please follow the debugging steps from my previous comment - update your nvidia and Intel drivers to ensure that that's not the issue, and try capturing `vkcube.exe` to see if that has the same problems.

**Comment by kyamant** [comment]
1. While it seemed old the Intel driver was the recommended one; the newer version did not get installed.
2. Updated Nvidia  driver from 417.22 to 430.86.
3. Ran the cube example that came with LunarG's Vulkan SDK with similar result;  session files are attached.
[RenderDoc_2019.07.03_04.36.21.zip](https://github.com/baldurk/renderdoc/files/3354811/RenderDoc_2019.07.03_04.36.21.zip)

**Comment by baldurk** [comment]
That's quite strange. I can still open the vkcube captures fine (though I wouldn't expect to see a problem with them). Your SDK is also fairly out of date - 1.1.82.1 - but that shouldn't make a difference.

Can you attach visual studio to the running qrenderdoc.exe while it is hung, pause execution, and save a minidump with heap? If you zip it then it shouldn't be too big but it will still be about 100MB.

You can also use the [symbol server](https://renderdoc.org/symbols) to resolve the callstack on the main UI thread to maybe see what is hanging.

**Comment by kyamant** [comment]
I am willing to do the Visual Studio debugging.
Specific instructions are always welcome

**Comment by baldurk** [comment]
As I mentioned in the previous comment the best thing is to attach visual studio, pause, and save a minidump with heap. Then I can open the minidump and see what the threads are doing.

**Comment by kyamant** [comment]
Done. It is 654MB large, can I upload that to github?

**Comment by baldurk** [comment]
No github only allows attachments up to 10MB. As I mentioned before you can zip it which should reduce the size quite a lot, but you'd have to share it on a file sharing site like google drive, dropbox, or similar.

**Comment by kyamant** [comment]
I'll work on that. In the meanwhile: 

Dump Summary
------------
Dump File:	qrenderdoc.dmp : D:\Users\Vector\Downloads\qrenderdoc.dmp
Last Write Time:	03-Jul-19 09:43:33
Process Name:	qrenderdoc.exe : C:\Program Files\RenderDoc\qrenderdoc.exe
Process Architecture:	x64
Exception Code:	0x80000004
Exception Information:	A trace trap or other single-instruction mechanism signaled that one instruction has been executed.
Heap Information:	Present

System Information
------------------
OS Version:	10.0.17134
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
qrenderdoc.exe	C:\Program Files\RenderDoc\qrenderdoc.exe	1.4.0.0
ntdll.dll	C:\Windows\System32\ntdll.dll	10.0.17134.556
kernel32.dll	C:\Windows\System32\kernel32.dll	10.0.17134.753
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	10.0.17134.753
apphelp.dll	C:\Windows\System32\apphelp.dll	10.0.17134.1
AcLayers.dll	C:\Windows\System32\AcLayers.dll	10.0.17134.619
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.17134.1
user32.dll	C:\Windows\System32\user32.dll	10.0.17134.376
win32u.dll	C:\Windows\System32\win32u.dll	10.0.17134.1
gdi32.dll	C:\Windows\System32\gdi32.dll	10.0.17134.285
gdi32full.dll	C:\Windows\System32\gdi32full.dll	10.0.17134.753
msvcp_win.dll	C:\Windows\System32\msvcp_win.dll	10.0.17134.619
ucrtbase.dll	C:\Windows\System32\ucrtbase.dll	10.0.17134.677
shlwapi.dll	C:\Windows\System32\shlwapi.dll	10.0.17134.1
combase.dll	C:\Windows\System32\combase.dll	10.0.17134.619
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	10.0.17134.648
bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	10.0.17134.1
winspool.drv	C:\Windows\System32\winspool.drv	10.0.17134.753
kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	10.0.17134.112
propsys.dll	C:\Windows\System32\propsys.dll	7.0.17134.619
oleaut32.dll	C:\Windows\System32\oleaut32.dll	10.0.17134.706
SHCore.dll	C:\Windows\System32\SHCore.dll	10.0.17134.112
sechost.dll	C:\Windows\System32\sechost.dll	10.0.17134.319
IPHLPAPI.DLL	C:\Windows\System32\IPHLPAPI.DLL	10.0.17134.1
bcrypt.dll	C:\Windows\System32\bcrypt.dll	10.0.17134.112
sfc.dll	C:\Windows\System32\sfc.dll	10.0.17134.1
sfc_os.dll	C:\Windows\System32\sfc_os.dll	10.0.17134.1
SortWindows61.dll	C:\Windows\System32\SortWindows61.dll	10.0.17134.1
imm32.dll	C:\Windows\System32\imm32.dll	10.0.17134.1
shell32.dll	C:\Windows\System32\shell32.dll	10.0.17134.441
cfgmgr32.dll	C:\Windows\System32\cfgmgr32.dll	10.0.17134.1
shiboken2.dll	C:\Program Files\RenderDoc\shiboken2.dll	0.0.0.0
python36.dll	C:\Program Files\RenderDoc\python36.dll	3.6.4150.1013
windows.storage.dll	C:\Windows\System32\windows.storage.dll	10.0.17134.765
Qt5Widgets.dll	C:\Program Files\RenderDoc\Qt5Widgets.dll	5.9.4.0
advapi32.dll	C:\Windows\System32\advapi32.dll	10.0.17134.471
profapi.dll	C:\Windows\System32\profapi.dll	10.0.17134.1
powrprof.dll	C:\Windows\System32\powrprof.dll	10.0.17134.1
ws2_32.dll	C:\Windows\System32\ws2_32.dll	10.0.17134.1
fltLib.dll	C:\Windows\System32\fltLib.dll	10.0.17134.1
ole32.dll	C:\Windows\System32\ole32.dll	10.0.17134.765
Qt5Core.dll	C:\Program Files\RenderDoc\Qt5Core.dll	5.9.4.0
Qt5Svg.dll	C:\Program Files\RenderDoc\Qt5Svg.dll	5.9.4.0
Qt5Network.dll	C:\Program Files\RenderDoc\Qt5Network.dll	5.9.4.0
crypt32.dll	C:\Windows\System32\crypt32.dll	10.0.17134.1
msasn1.dll	C:\Windows\System32\msasn1.dll	10.0.17134.1
msvcp140.dll	C:\Windows\System32\msvcp140.dll	14.11.25506.0
Qt5Gui.dll	C:\Program Files\RenderDoc\Qt5Gui.dll	5.9.4.0
VCRUNTIME140.dll	C:\Windows\System32\VCRUNTIME140.dll	14.11.25506.0
version.dll	C:\Windows\System32\version.dll	10.0.17134.1
uxtheme.dll	C:\Windows\System32\uxtheme.dll	10.0.17134.1
dwmapi.dll	C:\Windows\System32\dwmapi.dll	10.0.17134.1
mpr.dll	C:\Windows\System32\mpr.dll	10.0.17134.677
winmm.dll	C:\Windows\System32\winmm.dll	10.0.17134.1
dnsapi.dll	C:\Windows\System32\dnsapi.dll	10.0.17134.441
nsi.dll	C:\Windows\System32\nsi.dll	10.0.17134.1
WINMMBASE.dll	C:\Windows\System32\WINMMBASE.dll	10.0.17134.1
renderdoc.dll	C:\Program Files\RenderDoc\renderdoc.dll	1.4.0.0
setupapi.dll	C:\Windows\System32\setupapi.dll	10.0.17134.1
comdlg32.dll	C:\Windows\System32\comdlg32.dll	10.0.17134.1
comctl32.dll	C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.17134.765_none_f95445c33093f8bb\comctl32.dll	5.82.17134.765
d3dcompiler_47.dll	C:\Program Files\RenderDoc\d3dcompiler_47.dll	10.0.17134.12
dbghelp.dll	C:\Program Files\RenderDoc\dbghelp.dll	6.2.9200.20512
symsrv.dll	C:\Program Files\RenderDoc\symsrv.dll	6.2.9200.16384
CRYPTBASE.DLL	C:\Windows\System32\CRYPTBASE.DLL	10.0.17134.1
qwindows.dll	C:\Program Files\RenderDoc\qtplugins\platforms\qwindows.dll	5.9.4.0
qsvg.dll	C:\Program Files\RenderDoc\qtplugins\imageformats\qsvg.dll	5.9.4.0
cryptsp.dll	C:\Windows\System32\cryptsp.dll	10.0.17134.1
rsaenh.dll	C:\Windows\System32\rsaenh.dll	10.0.17134.254
_ctypes.pyd	C:\Program Files\RenderDoc\_ctypes.pyd	3.6.4150.1013
QtCore.pyd	C:\Program Files\RenderDoc\PySide2\QtCore.pyd	0.0.0.0
pyside2.dll	C:\Program Files\RenderDoc\PySide2\pyside2.dll	0.0.0.0
QtGui.pyd	C:\Program Files\RenderDoc\PySide2\QtGui.pyd	0.0.0.0
QtWidgets.pyd	C:\Program Files\RenderDoc\PySide2\QtWidgets.pyd	0.0.0.0
DWrite.dll	C:\Windows\System32\DWrite.dll	10.0.17134.376
msctf.dll	C:\Windows\System32\msctf.dll	10.0.17134.619
clbcatq.dll	C:\Windows\System32\clbcatq.dll	2001.12.10941.16384
dataexchange.dll	C:\Windows\System32\dataexchange.dll	10.0.17134.1
d3d11.dll	C:\Windows\System32\d3d11.dll	10.0.17134.441
dcomp.dll	C:\Windows\System32\dcomp.dll	10.0.17134.1
dxgi.dll	C:\Windows\System32\dxgi.dll	10.0.17134.112
twinapi.appcore.dll	C:\Windows\System32\twinapi.appcore.dll	10.0.17134.137
rmclient.dll	C:\Windows\System32\rmclient.dll	10.0.17134.556
TextInputFramework.dll	C:\Windows\System32\TextInputFramework.dll	10.0.17134.376
CoreUIComponents.dll	C:\Windows\System32\CoreUIComponents.dll	10.0.17134.376
CoreMessaging.dll	C:\Windows\System32\CoreMessaging.dll	10.0.17134.471
WinTypes.dll	C:\Windows\System32\WinTypes.dll	10.0.17134.523
ntmarta.dll	C:\Windows\System32\ntmarta.dll	10.0.17134.1
comctl32.dll	C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17134.765_none_fb42a1a930655896\comctl32.dll	6.10.17134.765
edputil.dll	C:\Windows\System32\edputil.dll	10.0.17134.1
dui70.dll	C:\Windows\System32\dui70.dll	10.0.17134.112
duser.dll	C:\Windows\System32\duser.dll	10.0.17134.1
WindowsCodecs.dll	C:\Windows\System32\WindowsCodecs.dll	10.0.17134.345
thumbcache.dll	C:\Windows\System32\thumbcache.dll	10.0.17134.441
Windows.Globalization.dll	C:\Windows\System32\Windows.Globalization.dll	10.0.17134.556
BCP47mrm.dll	C:\Windows\System32\BCP47mrm.dll	10.0.17134.1
Bcp47Langs.dll	C:\Windows\System32\Bcp47Langs.dll	10.0.17134.1
globinputhost.dll	C:\Windows\System32\globinputhost.dll	10.0.17134.1
ntshrui.dll	C:\Windows\System32\ntshrui.dll	10.0.17134.1
sspicli.dll	C:\Windows\System32\sspicli.dll	10.0.17134.376
srvcli.dll	C:\Windows\System32\srvcli.dll	10.0.17134.1
cscapi.dll	C:\Windows\System32\cscapi.dll	10.0.17134.1
StructuredQuery.dll	C:\Windows\System32\StructuredQuery.dll	7.0.17134.228
atlthunk.dll	C:\Windows\System32\atlthunk.dll	10.0.17134.1
Windows.StateRepositoryPS.dll	C:\Windows\System32\Windows.StateRepositoryPS.dll	10.0.17134.1
Windows.Storage.Search.dll	C:\Windows\System32\Windows.Storage.Search.dll	10.0.17134.1
cldapi.dll	C:\Windows\System32\cldapi.dll	10.0.17134.1
coml2.dll	C:\Windows\System32\coml2.dll	10.0.17134.407
OneCoreUAPCommonProxyStub.dll	C:\Windows\System32\OneCoreUAPCommonProxyStub.dll	10.0.17134.1
linkinfo.dll	C:\Windows\System32\linkinfo.dll	10.0.17134.1
secur32.dll	C:\Windows\System32\secur32.dll	10.0.17134.1
samcli.dll	C:\Windows\System32\samcli.dll	10.0.17134.1
samlib.dll	C:\Windows\System32\samlib.dll	10.0.17134.1
netutils.dll	C:\Windows\System32\netutils.dll	10.0.17134.1
drprov.dll	C:\Windows\System32\drprov.dll	10.0.17134.1
winsta.dll	C:\Windows\System32\winsta.dll	10.0.17134.1
ntlanman.dll	C:\Windows\System32\ntlanman.dll	10.0.17134.677
davclnt.dll	C:\Windows\System32\davclnt.dll	10.0.17134.1
davhlpr.dll	C:\Windows\System32\davhlpr.dll	10.0.17134.1
wkscli.dll	C:\Windows\System32\wkscli.dll	10.0.17134.1
dlnashext.dll	C:\Windows\System32\dlnashext.dll	10.0.17134.1
PlayToDevice.dll	C:\Windows\System32\PlayToDevice.dll	10.0.17134.1
DevDispItemProvider.dll	C:\Windows\System32\DevDispItemProvider.dll	10.0.17134.1
actxprxy.dll	C:\Windows\System32\actxprxy.dll	10.0.17134.1
EhStorShell.dll	C:\Windows\System32\EhStorShell.dll	10.0.17134.1
cscui.dll	C:\Windows\System32\cscui.dll	10.0.17134.1
MMDevAPI.dll	C:\Windows\System32\MMDevAPI.dll	10.0.17134.1
devobj.dll	C:\Windows\System32\devobj.dll	10.0.17134.1
PortableDeviceApi.dll	C:\Windows\System32\PortableDeviceApi.dll	10.0.17134.1
wintrust.dll	C:\Windows\System32\wintrust.dll	10.0.17134.556
NetworkExplorer.dll	C:\Windows\System32\NetworkExplorer.dll	10.0.17134.1
EhStorAPI.dll	C:\Windows\System32\EhStorAPI.dll	10.0.17134.1
wtsapi32.dll	C:\Windows\System32\wtsapi32.dll	10.0.17134.1
vulkan-1.dll	C:\Windows\System32\vulkan-1.dll	1.1.97.0
nvoglv64.dll	C:\Windows\System32\DriverStore\FileRepository\nvamsi.inf_amd64_a40b0383c29fe9b4\nvoglv64.dll	26.21.14.3086
igvk64.dll	C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_2cd0802aadb1c6f8\igvk64.dll	21.20.16.4599
opengl32.dll	C:\Windows\System32\opengl32.dll	10.0.17134.1
glu32.dll	C:\Windows\System32\glu32.dll	10.0.17134.1
VkLayer_monitor.dll	d:\VulkanSDK\1.1.82.1\Bin\VkLayer_monitor.dll	0.0.0.0
imagehlp.dll	C:\Windows\System32\imagehlp.dll	10.0.17134.1
gpapi.dll	C:\Windows\System32\gpapi.dll	10.0.17134.1
cryptnet.dll	C:\Windows\System32\cryptnet.dll	10.0.17134.1
nvspcap64.dll	C:\Windows\System32\nvspcap64.dll	3.19.0.107
nvcbl64.dll	C:\Windows\System32\DriverStore\FileRepository\nvamsi.inf_amd64_a40b0383c29fe9b4\nvcbl64.dll	26.21.14.3086
nvfatbinaryLoader.dll	C:\Windows\System32\nvfatbinaryLoader.dll	26.21.14.3086
nvapi64.dll	C:\Windows\System32\nvapi64.dll	26.21.14.3086
mscms.dll	C:\Windows\System32\mscms.dll	10.0.17134.1
ColorAdapterClient.dll	C:\Windows\System32\ColorAdapterClient.dll	10.0.17134.1
userenv.dll	C:\Windows\System32\userenv.dll	10.0.17134.1
nvrtum64.dll	C:\Windows\System32\DriverStore\FileRepository\nvamsi.inf_amd64_a40b0383c29fe9b4\nvrtum64.dll	26.21.14.3086

**Comment by baldurk** [comment]
That information isn't useful, what I want is the callstack on the UI thread where I assume it's blocking. If you want to debug further yourself then as mentioned above you can resolve the renderdoc symbols using the [symbol server](https://renderdoc.org/symbols) to get the callstack.

**Comment by kyamant** [comment]
Uploading to google drive, will give you the link when done

**Comment by kyamant** [comment]
Just shared it on the google drive of my other gmail account, you should have received an email.

**Comment by baldurk** [comment]
The hang is due to the `VK_LAYER_LUNARG_monitor` layer being active. This layer is buggy and will deadlock if WSI is used on a non-main thread:

```
 	win32u.dll!00007ff855c51164()	Unknown
 	user32.dll!SendMessageWorker()	Unknown
 	user32.dll!GetWindowTextA()	Unknown
 	VkLayer_monitor.dll!00007ff84303bff2()	Unknown
 	renderdoc.dll!VulkanReplay::OutputWindow::CreateSurface(VkInstance_T * inst) Line 52	C++
 	renderdoc.dll!VulkanReplay::OutputWindow::Create(WrappedVulkan * driver, VkDevice_T * device, bool depth) Line 204	C++
 	renderdoc.dll!VulkanReplay::MakeOutputWindow(WindowingData window, bool depth) Line 1076	C++
 	renderdoc.dll!ReplayOutput::ReplayOutput(ReplayController * parent, WindowingData window, ReplayOutputType type) Line 106	C++
 	renderdoc.dll!ReplayController::CreateOutput(WindowingData window, ReplayOutputType type) Line 1874	C++
 	qrenderdoc.exe!TextureViewer::OnCaptureLoaded::__l2::<lambda>(IReplayController * r) Line 2652	C++
```

The cube demo does not enable this layer, so either you have `VK_INSTANCE_LAYERS` variable set globally that force-enables it, or you used `vkconfig` to enable it and since your SDK is older it is the extremely buggy version of `vkconfig` that will keep layers enabled forever.

I'd recommend updating your Vulkan SDK to latest and disabling whatever you have on your system that is enabling `VK_LAYER_LUNARG_monitor`, as it will cause crashes or hangs in vulkan applications.

**Comment by kyamant** [comment]
I had enabled VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_monitor to get a fps value on the window title bar.
Thanks for your help on this problem and for developing RenderDoc in general.
