### ISSUE TITLE
Drawing with empty/invalid viewport rects should be more obvious in RenderDoc

### ISSUE THREAD

**Issue by MrZoner** [baldurk/renderdoc#144]
I had a hard to diagnose rendering error that ended up being viewport clipping.  When I ran a capture of our game from before my draw call being reported missing, I did a side by side comparison of the pipeline state between the builds and eventually found the viewport being present in one and empty in the other.

When the viewport width/height is are 0,0 the pipeline state merely renders an empty list in the viewports array.  It should probably render a red row here instead of a completely empty list.

**Comment by baldurk** [comment]
Hi sorry I was away at SIGGRAPH the past week. This is a fair point and it might be partially because I was lazy and passed non-existant viewports through as 0,0 without a way to distinguish from an enabled viewport that's 0,0.

**Comment by baldurk** [comment]
Should now be much easier to spot invalid/empty viewports that are set.
