### ISSUE TITLE
Launcher app crash 

### ISSUE THREAD

**Issue by mimijava** [baldurk/renderdoc#1440]
## Description

ADRD 013328: [20:07:49]        gl_common.cpp( 490) - Log     - Vendor checks for 32 (ARM / Mali-G72 / OpenGL ES 3.2 v1.r14p0-00cet0.0416641283c5d6e2d53c163d0ca99357)
ADRD 013328: [20:07:49]        gl_common.cpp( 790) - Warning - Reading from the depth buffer using glReadPixels is not supported (GL_NV_read_depth)
ADRD 013328: [20:07:49]        gl_common.cpp( 794) - Warning - Reading from the stencil buffer using glReadPixels is not supported (GL_NV_read_stencil)
ADRD 013328: [20:07:49]        gl_common.cpp( 798) - Warning - Reading from the packed depth-stencil buffers using glReadPixels is not supported (GL_NV_read_depth_stencil)
ADRD 013328: [20:07:49]  gl_buffer_funcs.cpp(2414) - Error   - Failed to map buffer for update
ADRD 013328: [20:07:49]  gl_shader_funcs.cpp(1242) - Error   - Assertion failed: 'record' Couldn't identify object passed to function. Mismatched or bad GLuint? (program=1)
ADRD 013328: [16:34:39]                 libc(   0) - Fatal   - Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 13415 (RenderThread), pid 13328 (encent.mobileqq)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   - *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   - Build fingerprint: 'kirin/kirin/kirin:9/PPR1.180610.011/8082:user/test-keys'
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   - Revision: '0'
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   - ABI: 'arm'
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   - pid: 13328, tid: 13415, name: RenderThread  >>> com.tencent.mobileqq <<<
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   - signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   - Cause: null pointer dereference
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     r0  c738c73a  r1  00000000  r2  c739c73a  r3  fff7fff7
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     r4  c2bfcfd0  r5  c1d77cf0  r6  00000004  r7  00000001
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     r8  c1d77ca0  r9  c2bfd020  r10 c2bfcfd0  r11 00000002
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     ip  38b538b4  sp  c2bfcfa8  lr  38be38be  pc  dbef3c3c
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   - backtrace:
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #00 pc 00429c3c  /vendor/lib/egl/libGLES_mali.so (cmem_heap_is_imported+44)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #01 pc 005e9b4c  /vendor/lib/egl/libGLES_mali.so (cobjp_surface_instance_get_import_handles_virtual+116)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #02 pc 005e763c  /vendor/lib/egl/libGLES_mali.so (cobj_instance_get_import_handles+28)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #03 pc 006278c4  /vendor/lib/egl/libGLES_mali.so (cframe_manager_add_object_dependency+496)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #04 pc 0063499c  /vendor/lib/egl/libGLES_mali.so (cframep_manager_set_all_surface_dependency+704)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #05 pc 006356c4  /vendor/lib/egl/libGLES_mali.so (cframep_manager_per_draw_call_checks_full+692)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #06 pc 0062c9dc  /vendor/lib/egl/libGLES_mali.so (cframep_manager_add_job+1232)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #07 pc 0062cd7c  /vendor/lib/egl/libGLES_mali.so (cframe_manager_add_job+112)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #08 pc 004cb2a8  /vendor/lib/egl/libGLES_mali.so (gles_draw_call_finish+220)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #09 pc 004ca4e4  /vendor/lib/egl/libGLES_mali.so (gles_drawp_draw_common+5924)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #10 pc 004cc434  /vendor/lib/egl/libGLES_mali.so (gles_draw_draw_arrays+52)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #11 pc 004b9354  /vendor/lib/egl/libGLES_mali.so (glDrawArrays+452)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #12 pc 000cf545  /data/app/org.renderdoc.renderdoccmd.arm32--h8zcRA3riO4k6IIbjKH0Q==/lib/arm/libVkLayer_GLES_RenderDoc.so (WrappedOpenGL::RenderOverlayStr(float, float, char const*)+4172)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #13 pc 000ce57d  /data/app/org.renderdoc.renderdoccmd.arm32--h8zcRA3riO4k6IIbjKH0Q==/lib/arm/libVkLayer_GLES_RenderDoc.so (WrappedOpenGL::RenderOverlayStr(float, float, char const*)+132)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #14 pc 000ce4c5  /data/app/org.renderdoc.renderdoccmd.arm32--h8zcRA3riO4k6IIbjKH0Q==/lib/arm/libVkLayer_GLES_RenderDoc.so (WrappedOpenGL::RenderOverlayText(float, float, char const*, ...)+140)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #15 pc 0011a1af  /data/app/org.renderdoc.renderdoccmd.arm32--h8zcRA3riO4k6IIbjKH0Q==/lib/arm/libVkLayer_GLES_RenderDoc.so (WrappedOpenGL::SwapBuffers(void*)+3030)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #16 pc 00552bed  /data/app/org.renderdoc.renderdoccmd.arm32--h8zcRA3riO4k6IIbjKH0Q==/lib/arm/libVkLayer_GLES_RenderDoc.so (eglSwapBuffersWithDamageKHR_renderdoc_hooked+228)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #17 pc 0009e45b  /system/lib/libhwui.so (android::uirenderer::renderthread::EglManager::swapBuffers(android::uirenderer::renderthread::Frame const&, SkRect const&)+86)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #18 pc 0037c0fd  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::swapBuffers(android::uirenderer::renderthread::Frame const&, bool, SkRect const&, android::uirenderer::FrameInfo*, bool*)+48)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #19 pc 0009b745  /system/lib/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+272)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #20 pc 0037f931  /system/lib/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+932)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #21 pc 00346c77  /system/lib/libhwui.so (android::uirenderer::WorkQueue::process()+122)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #22 pc 000a4667  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+182)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #23 pc 0000c12b  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+170)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #24 pc 00064e37  /system/lib/libc.so (__pthread_start(void*)+22)
ADRD 013434: [16:34:39]                DEBUG(   0) - Fatal   -     #25 pc 0001e8a5  /system/lib/libc.so (__start_thread+32)

## Environment

* RenderDoc build: e.g. v1.0, or 2019-07-03 nightly build.
* Operating System: e.g. Windows 10, Windows 7, Ubuntu Linux, etc
* API: e.g. Vulkan, D3D11, OpenGL, etc

**Comment by baldurk** [comment]
Nothing in this report indicates a RenderDoc error. You haven't given any description of what goes wrong, only posted a partial log with no explanation. The callstack in the crash shows that it crashes inside the driver, and the few log lines that are present indicate that there are driver and/or application errors prior to that with a map failing and an unrecognised program being used.

If you have fixed these issues and there is still a crash indicating a RenderDoc bug please open a new issue with full information about what your environment is and what is going wrong, and any repro steps you can share.
