### ISSUE TITLE
GL vs GL ES GPU counter differences

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1442]
## Description
Using the GPU counters for GL ES on Android there are a few interesting results/findings:

- We get GL_INVALID_ENUM error when glBeginQuery is called for GL_SAMPLES_PASSED and it results in a wrong value (-1) for the Samples Passed performance counter on Android.
Officially there is no GL_SAMPLES_PASSED in GLES but we could use GL_ANY_SAMPLES_PASSED instead.

- Also, there is no GL_QUERY_BUFFER and GL_QUERY_BUFFER_BINDING in GLES, and it causes errors when glGetIntegerv and glBindBuffer are called with these targets.

When we fetch the table again and glGenQueries called, the error check will detect these previous errors for the invalid enums, and the query will be deleted. It will result in a wrong (negative or NaN) value to be displayed in the table for the GPU duration. We could clear GL errors after every fetching.

- In GLES, GL_TIME_ELAPSED is provided by the EXT_disjoint_timer_query extension, so it would be good to check for safety whether it is supported or not.

An example of the wrong values on Android:

| EID | GPU duration | Samples Passed
| ------- | ------- | -------
| 5 | -1000000.00 µs |18446744073709551615 |
| 8 | 770.312 µs | 18446744073709551615 |
| 9 | 50.469 µs | 18446744073709551615 |

A possible fix for this issue is here: https://github.com/tabikati/renderdoc/commit/84d4ea99f6a0aeb55b48d0e2f8bd2879e1836685
I will create a pull request if you would like.

## Environment

* RenderDoc build: v1.x, 2019-07-02
* Operating System: Android 7.0
* API: OpenGL ES

**Comment by baldurk** [comment]
That commit should fix this with the correct extension checks.

**Comment by tabikati** [comment]
It has fixed the problem, thank you. Can we query GL_ANY_SAMPLES_PASSED for GLES?

**Comment by baldurk** [comment]
I don't see any value in providing that counter since it provides virtually no useful information.
