### ISSUE TITLE
PySide2 and cmake

### ISSUE THREAD

**Issue by SR-dude** [baldurk/renderdoc#1444]
Cmake fails to find PySide2. I installed it with pip and the suite was placed in
/usr/lib/python3.7/site-packages/PySide2. But still, it won't configure.

This is my cmake invocation line.
`PYSIDE2_INCLUDE_DIR=/usr/lib/python3.7/site-packages/PySide2/include
PYSIDE2_PYTHON_PATH=/usr/lib/python3.7/site-packages/PySide2 
PYSIDE2_LIBRARY_DIR=/usr/lib/python3.7/site-packages/PySide2 
cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild -H.`

Maybe I'm setting them wrong. Any suggestions?

**Comment by baldurk** [comment]
I'm not very familiar with pip but my understanding is that pip packages are just the python modules for use in python standalone, they aren't intended as a development library for C programs to link against. PySide2 pulls double duty as both python bindings to access Qt on top of being a way for C programs to expose Qt objects to python - the latter part is redundant when accessed purely through python but is why RenderDoc uses it. When linked to a C program already using Qt and python you need to get a PySide2 version that matches the version of both that's installed, whereas pip will only be looking to match python version.

I'm guessing you're missing some necessary files as part of the pip package, though you're going about specifying a custom path the wrong way - PySide is located via the normal cmake search mechanisms which means you need to specify `-DCMAKE_PREFIX_PATH` to the root of the PySide directory.

I believe if you want PySide2 support on linux you will need to build it from source and reference that build result. At the very least that's the only way I've tested it and I know that produces the correct artifacts.

Can I ask why you want to configure PySide2 in the first place? RenderDoc builds without it and it's really only present to provide avenues for extreme customisation/scripting that want to access the UI itself.

**Comment by SR-dude** [comment]
That cmake invocation line is what I passed to renderdoc. I have removed pyside2 via pip and recompiled the package with source instead but that did help  rendedocs cmake build  scripts.

However, after reading your advice I have just simply compiled renderdoc without pyside2
support. That is how production distributions package renderdoc, anyway.

Thank You for the advice.
