### ISSUE TITLE
Non-Activity Android components are added to the Activity list

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1445]
## Description

Android Receivers and Services are added to the Activity list because they have the same line format as the Activities in the `dumpsys package` output.
Components other than Activities shouldn't be displayed in the list and the `adb shell am start` command can only launch Activities anyways.

A `dumpsys package` output structure should look like this:
- ...
- Activity Resolver Table: ...
- Receiver Resolver Table: ...
- Service Resolver Table: ...
- Provider Resolver Table: ...
- ...

We could prevent adding non-Activity components if we search in the 'Activity Resolver Table' block only and stop the searching when we reach the 'Receiver Resolver Table'. (If it doesn't have any Receiver, it would go through the whole output.)

A possible fix is: https://github.com/tabikati/renderdoc/commit/6970e014dca613e111b7d1b215a2b1ef874f0d65. I'll open a PR if it is OK with you.

## Environment

* RenderDoc build: v1.x, 2019-07-05
* Operating System: Android

**Comment by baldurk** [comment]
Can you please provide a repro case that demonstrates this problem so I can look into it? You don't need to provide a fix for each bug report, but I do need to be able to reproduce and investigate the problem so that I can see exactly what is wrong.

**Comment by tabikati** [comment]
Sure, here is an APK with Receiver and Service: [demo_app.zip](https://github.com/baldurk/renderdoc/files/3380886/demo_app.zip)

**Comment by baldurk** [comment]
That commit should only process activities within the section that lists activities.
