### ISSUE TITLE
Direct3D 11.3 support

### ISSUE THREAD

**Issue by oscarbg** [baldurk/renderdoc#145]
Hi,
just seen apitrace supports 11.3 and it wasn't much work to enable..
is that the case for Renderdoc i.e. can we expect 11.3 well before D3D12 support?

**Comment by baldurk** [comment]
FYI I don't know much about apitrace's internals but given that it's not single-frame capture like RenderDoc I think it has an easier time supporting new APIs, it's not an apples-to-apples comparison.

Looking at the docs it seems like the API-facing changes in 11.3 are fairly minimal so this could be an easy update to support. It's worth noting though that RenderDoc doesn't fully support 11.2 as I haven't implemented tiled resource handling properly, as I couldn't find any code actually using it.

This is probably lower priority though as I imagine there won't be many people using 11.3. It's locked to new OSes (10? or maybe 8.1? certainly it doesn't work on 7) so the use-case is pretty narrow between 11.0 and 12.0.

**Comment by oscarbg** [comment]
yes 11.3 is Windows 10 only?
but seems useful 11.3 for example adds 3D texture as new tiled texture.. useful for "Sparse Fluid Simulation in DirectX":
http://on-demand.gputechconf.com/siggraph/2015/presentation/SIG1506-Alex-Dunn.pdf
Regarding 11.2 tiled sample this is the "canonical" sample:
https://code.msdn.microsoft.com/Direct3D-Tiled-Resources-80ee7a6e
