### ISSUE TITLE
Only one face shown for certain cube maps in texture viewer

### ISSUE THREAD

**Issue by DataBeaver** [baldurk/renderdoc#1451]
## Description

My own 3D graphics engine renders environment cube maps one face at a time.  When I look at the contents of the cube map, the X+ face is shown regardless of which face I select from the dropdown.  This is also the face that is rendered first.

## Repro steps

A capture which includes the problem is available at ~~http://www.tdb.fi/~tdb/cube_map_bug.rdc.gz~~ http://www.tdb.fi/~tdb/tmp/cube_map_bug.rdc.gz

Source code for the engine and the demo program (desertpillars) can be found at http://git.tdb.fi/?p=libs/gl.git .  Environment map rendering is located in source/environmentmap.cpp.  It requires several other libraries and a custom build system which are located on the same server.  To make the program use an OpenGL 3.2 core context and enable RenderDoc to capture it, apply this patch: [desertpillars_gl3.2.txt](https://github.com/baldurk/renderdoc/files/3381821/desertpillars_gl3.2.txt).

If necessary I can try to make a minimal test case using OpenGL calls directly, though that may have to wait until next month.

## Environment

* RenderDoc build: 328df297 (self-built)
* Operating System: Debian Unstable (kernel 4.18.11)
* API: OpenGL
* GPU: GeForce RTX 2070 (driver 418.74)

**Comment by baldurk** [comment]
The link to the capture is 404'ing for me, is it possible to fix that? Otherwise I can build the demo myself to test but that might have to wait a little while.

**Comment by DataBeaver** [comment]
Apologies, I typed the URL by hand and neglected to test it.  The correct one is http://www.tdb.fi/~tdb/tmp/cube_map_bug.rdc.gz .

**Comment by baldurk** [comment]
I wasn't properly multiplying the number of slices by 6 for cubemaps, which lead to it being clamped. It should be fixed with that commit.
