### ISSUE TITLE
Fails to build with python 3.8 beta 2 (3.8.0b2)

### ISSUE THREAD

**Issue by gicmo** [baldurk/renderdoc#1455]
Fedora 32 will switch ([ChangeProposal](https://fedoraproject.org/wiki/Changes/Python3.8) to Python 3.8). The latter should be release around 2019-10-21 ([3.8 schedule](https://www.python.org/dev/peps/pep-0569/#schedule)). Currently (1.4) the build fails because the custom swig (swig-modified-6) generates code that uses a deprecated symbol that got removed in 3.8 (`_PyObject_GC_UNTRACK`). I included a [patch](https://src.fedoraproject.org/rpms/renderdoc/blob/master/f/swig-py38.patch) in the Fedora rpm to make it compile. It seems that upstream [builtin.swg#L120@master](https://github.com/swig/swig/blob/3872890c1cdc67efd71abb3a1a588fb06d3f1edf/Lib/python/builtin.swg#L120) also still uses that marco (`_PyObject_GC_UNTRACK`), so just updating swig will (for now) to solve the issue. Maybe that will change until Python 3.8 is released.

**Comment by baldurk** [comment]
(Assuming you meant that "updating swig will (for now) **not** solve the issue"). I'm already pretty committed to maintaining the swig fork indefinitely, so applying that patch should be fine I think. Since this is only in the `.swg` files it's pretty easy to update, I'll just need to bump the swig fork's version which is a bit tedious.

**Comment by gicmo** [comment]
@baldurk ah yes, sorry, indeed meant "*not* solve the issue". This is not super urgent because we have some time until 3.8 is released but I wanted this to be on the radar. Just for the record, the docu for [`_PyObject_GC_UNTRACK`](https://docs.python.org/3/c-api/gcsupport.html#c._PyObject_GC_UNTRACK) stating "Deprecated since version 3.6: This macro is removed from Python 3.8.". I am a bit puzzled but I don't even see an issue for that on the swig repo.

**Comment by gicmo** [comment]
I filed a issue [swig#1586](https://github.com/swig/swig/issues/1586) and submitted a PR [#1587](https://github.com/swig/swig/pull/1587), with a patch that should also be backwards compatible.

**Comment by baldurk** [comment]
You might be waiting a while, from what I saw before swig isn't a very responsive project. Either way I'll need to manually backport it so I'll take your patch directly whether or not it's merged upstream.

**Comment by gicmo** [comment]
Upstream took the patch 🎉, since they only support 2.7 and >= 3.2 they even went for the simpler version, which is identical code-wise with the [patch](https://src.fedoraproject.org/rpms/renderdoc/blob/master/f/swig-py38.patch) I stuck in the RPM. Want me to file a PR against renderdoc's custom swig repo?

**Comment by baldurk** [comment]
I merged your patch into the branch manually because it can be a bit of a pain to handle the swig fork. I've also updated the tag with that commit above. Thanks for this.
