### ISSUE TITLE
"Target doesn't match the texture's target." plus GL_INVALID_VALUE

### ISSUE THREAD

**Issue by stolk** [baldurk/renderdoc#1461]
## Description

**GL_INVALID_VALUE** generated by app, but only if running through renderdoc.

Renderdoc will also report:

```
Log     - Got a Debug message from GL_DEBUG_SOURCE_API, type GL_DEBUG_TYPE_ERROR, ID 1282, severity GL_DEBUG_SEVERITY_HIGH:
'GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.'
```

## Repro steps

Run through renderdoc: gl error is generated.

Run stand alone: no gl error.

## Isolation

I tried to isolate the issue, and from what I can tell, it seems to be triggered by binding a GL_UNIFORM_BUFFER with glBindBuffer().

I've used renderdoc quite a bit, and never saw this behaviour before. I'm trying to find out what changed.

## Environment

* RenderDoc build: 1.4 (tried 1.3 as well: same issue.)
* Operating System: Ubuntu LTS.
* API: OpenGL

**Comment by stolk** [comment]
I think it may actually be triggered by `glBindBufferBase( GL_UNIFORM_BUFFER, ...)` instead of `glBindBuffer( GL_UNIFORM_BUFFER, ...)`.

**Comment by baldurk** [comment]
I can't investigate this without more information, ideally a repro case that shows the problem. I don't think that binding a uniform buffer with `glBindBufferBase` is sufficient on its own to show the problem.

If you can provide a sample either here or privately please get in touch. Otherwise it would be useful to know for example what the callstack is when the debug message is produced, or exactly what is happening when you detect `GL_INVALID_VALUE`.

**Comment by stolk** [comment]
[GL_INVALID_VALUE.zip](https://github.com/baldurk/renderdoc/files/3418435/GL_INVALID_VALUE.zip)

Here's the zipped .rdc file.
I am pretty sure the GL error is created in the renderdoc code, because I see it the first thing when I draw a new frame.

**Comment by stolk** [comment]
As soon as you load that capture file into renderdoc, you get:

```
Log     - Got a Debug message from GL_DEBUG_SOURCE_API, type GL_DEBUG_TYPE_ERROR, ID 1282, severity GL_DEBUG_SEVERITY_HIGH:
'GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.'
Log     - Got a Debug message from GL_DEBUG_SOURCE_API, type GL_DEBUG_TYPE_ERROR, ID 1282, severity GL_DEBUG_SEVERITY_HIGH:
'GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.'
Log     - Got a Debug message from GL_DEBUG_SOURCE_API, type GL_DEBUG_TYPE_ERROR, ID 1282, severity GL_DEBUG_SEVERITY_HIGH:
'GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.'
Log     - Got a Debug message from GL_DEBUG_SOURCE_API, type GL_DEBUG_TYPE_ERROR, ID 1282, severity GL_DEBUG_SEVERITY_HIGH:
'GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.'
```

Which I think is the cause of the GL error each frame, when the app runs in renderdoc.

This error, and the GL_INVALID_VALUE error are probably related.

**Comment by baldurk** [comment]
In that capture there's a texture `render1msaa` which looks like it's generated and first initialised as `GL_TEXTURE_2D_MULTISAMPLE`, but then it has some parameters set via `GL_TEXTURE_2D` before eventually having storage allocated with `glTexImage2DMultisample`. The texture parameters being set via `GL_TEXTURE_2D` seem to be the source of the errors.

Does that make sense with what your application is doing? It might be a mistaken capture, though to debug that I'd need to be able debug the application at capture time, or give you a build with extra logging enabled.

From the capture I can't tell where or when the `GL_INVALID_VALUE` is happening. I don't ever call `glGetError()` myself and I rely on modern drivers to have debug output callbacks, I didn't get anything that would suggest a `GL_INVALID_VALUE` error.

**Comment by stolk** [comment]
Thank you for catching that. I removed the glTexParameter calls for the MSAA texture.

The GL_INVALID_OPERATION error is now gone.
Thanks!

The GL_INVALID_VALUE is still there. I will zip up my build, if you want to take a look at it.
The build runs without gl errors when running stand alone.

**Comment by stolk** [comment]
Although, I am on linux, which may be a hassle for you. Maybe I should try a build with more logging instead?

**Comment by baldurk** [comment]
I've got a Ubuntu box I can run programs on, that's no problem, as long as I can get the right required dependencies etc.

**Comment by stolk** [comment]
The tar ball is here, and has everything you need to run it:
http://stolk.org/tmp/train.tgz

run 'Train' in the 'Train/' directory.

After launch, select NEW GAME, and the GL ERRORs will start.

**Comment by baldurk** [comment]
The issue seems to be a weird non-reflexive query on GL. If you bind a uniform buffer with `glBindBufferBase` then the queried size of the binding comes back as zero, which is then invalid to pass into `glBindBufferRange`. I've fixed it with an if() and a check, it's just a shame that `glBindBufferBase` isn't a simple subset of `glBindBufferRange`.
