### ISSUE TITLE
Resource Visualisation for CS resources

### ISSUE THREAD

**Issue by pthiben** [baldurk/renderdoc#147]
Feature request: it would be great ot visualize the resources for Compute shaders the same way we do for pixel shaders (in the Texture viewer, with thumbnails)
UAV could be the equivalent of OM Target, and CS SRVs the equivalent of PS resources

Cheers !

**Comment by baldurk** [comment]
This is a good suggestion. Honestly the "OM Target" and "PS Resources" is a bit ugly, really the PS Resources should be just "Shader Inputs" or something and include VS, and other stages. As well as fixing up the behaviour for compute events, it would be nice to also get copies and resolves etc to show source/target.

**Comment by baldurk** [comment]
This should what you were wanting, so please check that it works for you. I'm going to leave this issue open until I have implemented showing other stages on draws (ie. show vertex textures as well). Shouldn't be hard, I just didn't want to make the change bigger than it needed to be right now.

**Comment by pthiben** [comment]
That's exactly what I had in mind, thanks.

Looking forward to the other stages as well :)

Cheers
