### ISSUE TITLE
Hooked GetProcAddress does not behave as original GetProcAddress

### ISSUE THREAD

**Issue by nem0** [baldurk/renderdoc#1476]
## Description
GetProcAddress(nullptr, *) on windows returns pointers from current module, while hooked version returns nullptr.

## Repro steps

in following function, ```xx``` is nullptr. If I get ```xx``` before I try to load renderdoc, it's not nullptr.

```cpp
static RENDERDOC_API_1_0_2* g_rdoc_api;
static void init_render_doc()
{
    HMODULE lib = LoadLibrary("renderdoc.dll");
	if (!lib) return;

	pRENDERDOC_GetAPI RENDERDOC_GetAPI = (pRENDERDOC_GetAPI)GetProcAddress(lib, "RENDERDOC_GetAPI");
	if (RENDERDOC_GetAPI) {
		RENDERDOC_GetAPI(eRENDERDOC_API_Version_1_0_2, (void **)&g_rdoc_api);
		g_rdoc_api->MaskOverlayBits(~RENDERDOC_OverlayBits::eRENDERDOC_Overlay_Enabled, 0);
	}

    auto xx = GetProcAddress(nullptr, "foo_test");
    xx = xx; // xx is nullptr here
}

extern "C" __declspec(dllexport) void foo_test() {}
```

https://github.com/baldurk/renderdoc/blob/7206a0cd2550fecf34335a8b01048dfbd54a23f9/renderdoc/os/win32/win32_hook.cpp#L706

## Environment

* RenderDoc build: latest commit - f82cce065d687ab69df6b2272a52c3e88c3a70bc
* Windows 10
* OpenGL, but happens before any initialization

**Comment by nem0** [comment]
If I replace https://github.com/baldurk/renderdoc/blob/7206a0cd2550fecf34335a8b01048dfbd54a23f9/renderdoc/os/win32/win32_hook.cpp#L706-L707
```cpp
  if(mod == NULL || func == NULL)
    return GetProcAddress(mod, func);
```
everything works fine

**Comment by baldurk** [comment]
Thanks for catching this! I hadn't appreciated that NULL was a special handle which is valid and points to the executable. That commit should fix it, the same way as you've identified.
