### ISSUE TITLE
shade wrath of angels dont show any character in game

### ISSUE THREAD

**Issue by mrdeathjr28** [baldurk/renderdoc#1492]
## Description

shade wrath of angels dont show any character in game

## Repro steps

PC Demo

https://www.moddb.com/games/shade-wrath-of-angels/downloads/shade-wrath-of-angels-demo-1-01

## Environment

* RenderDoc build: e.g. v1.0, or 2018-03-12 nightly build.
* Operating System: e.g. Windows 10, Windows 7, Ubuntu Linux, etc
* API: e.g. Vulkan, D3D11, OpenGL, etc

Nvidia Drivers 418.52.18 (run package)

Xubuntu 18.04 x64 - Kernel 4.17.12 generic (ubuntu mainline) - 

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz + Zalman CNPS 10x Performa+

MEMORY: 8GB DDR4 2400mhz (4x2) Mushkin (dual channel: 37.5 gb/s)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

**Comment by baldurk** [comment]
Capturing commercial products is not endorsed or supported. Even a free demo remains copyright the original creator.

**Comment by mrdeathjr28** [comment]
sorry posting in wrong side
