### ISSUE TITLE
Interactive Python Shell - Saving Script Introduces Newlines

### ISSUE THREAD

**Issue by Waffle1434** [baldurk/renderdoc#1493]
## Description
Saving python script files in the UI adds blank lines between lines (an extra carriage return character).

## Repro steps
Interactive Python Shell -> Run Scripts -> Type the following example code:
```
line1
line2
line3
```
Save As "test.py" -> Open "test.py" in a text editor like notepad++

Notepad++ with all characters shown:
![Notepad++ with all characters shown](https://i.imgur.com/M2lrfy7.png)
Expected:
![Expected](https://i.imgur.com/40cOX0E.png)
## Environment

* RenderDoc build: v1.4
* Operating System: Windows 10

**Comment by baldurk** [comment]
Thanks for the clear bug report. The scintilla control deals with newlines itself assuming no conversion at all to DOS newlines on save. That means you get `\r\n` in the text buffer which is then double-converted to `\r\r\n` if it's saved to disk.

That commit should strip out the `\r` characters before save.
