### ISSUE TITLE
Python API Doc - GetShaderReflection Return Type

### ISSUE THREAD

**Issue by Waffle1434** [baldurk/renderdoc#1497]
## Description
[renderdoc.PipeState.GetShaderReflection()](https://renderdoc.org/docs/python_api/renderdoc/pipelines/common.html?highlight=getshaderreflection#renderdoc.PipeState.GetShaderReflection) return type is listed as [ShaderBindpointMapping](https://renderdoc.org/docs/python_api/renderdoc/enums_data.html#renderdoc.ShaderBindpointMapping).
In practice, return type seems to be [ShaderReflection](https://renderdoc.org/docs/python_api/renderdoc/enums_data.html?highlight=shaderreflection#renderdoc.ShaderReflection).
Not certain if this is another possible return type or a typo in the documentation.

**Comment by baldurk** [comment]
Thanks for reporting this. The type information etc in the documentation is manual so it's susceptible to copy-paste errors like this one.

That commit should fix it, please let me know if you spot anything else!
