### ISSUE TITLE
RenderDoc_1.4_64. not able to load 32 bit applications

### ISSUE THREAD

**Issue by nihalkenkre** [baldurk/renderdoc#1500]
Loads the 64 version of the app correctly.

Windows 10 version 1809. Visual Studio 2019.

Thank you
Nihal

**Comment by baldurk** [comment]
Please provide more information in your bug report. I was able to successfully capture a 32-bit application fine with build v1.4, so the problem you have must be more specific than that. Without more information it is hard for me to investigate the problem.

The issue template which you deleted guides you towards the kind of information that is useful: Giving repro steps - which might include in this case sharing your application or any test application you can reproduce the problem on, describing what happens more precisely than "not able to load" which is vague, and listing more complete environment information including the graphics API that you're using.

**Comment by nihalkenkre** [comment]
Hello,

Thank you for getting back, and apologies for the curt ticket.

Will post a detailed query once i am at the workstation again.

Than you for the amazing tool.
Nihal Kenkre.

**Comment by nihalkenkre** [comment]
Hello

Using

Vulkan - Version 1.1.114.0.
Visual Studio 2019 - Version 16.2.3.
Windows SDK - Version 10.0.18632
Platform Toolset - Visual Studio 2019 (Version v142)

Using C through out the application. ( do not know if this info would help). 

What kind of information would need in addition to this ?

Thank you,
Nihal Kenkre.

**Comment by nihalkenkre** [comment]
This behaviour is observed with the vkcube samples provided by the Vulkan SDK. Renderdoc works as expected with the 64 bit version of he vkcube exe. The 32 bit version of the vkcube app stope immediately after launching through RenderDoc

**Comment by baldurk** [comment]
I was able to reproduce it on vkcube, it was a vulkan-specific bug with the wrong calling convention on one layer entry point. That commit should fix the issue.

**Comment by nihalkenkre** [comment]
Hello, 

Could you tell me if there be a pre compiled binary which can be updated to, from the RenderDoc application, or would I have to download the source and compile ?

Thank you,
Nihal Kenkre.

**Comment by baldurk** [comment]
There are builds made every night from the latest code on the [downloads page](https://renderdoc.org/builds) which is linked both from the main README and homepage.

**Comment by nihalkenkre** [comment]
Thank you for your response.

I ended up cloning the git repo and building.

However, 64 bit builds can only capture on 64 bit apps. and 32 bit builds
only capture on 32 bit apps.

Seems to be by design.

Also showing the log files within the ui is great, with RED marking on the
error lines.

Cheers.
Nihal

**Comment by baldurk** [comment]
> However, 64 bit builds can only capture on 64 bit apps. and 32 bit builds only capture on 32 bit apps.
>
> Seems to be by design.

This is not correct. 32-bit builds can only capture 32-bit programs because those builds should only ever be used on a 32-bit version of Windows. But if you have built the 32-bit build then the 64-bit build can use it to capture a 32-bit application, exactly the same as stable and nightly builds can.

There is even a log message for exactly this case to inform you that you need to build both 32-bit and 64-bit builds before you can capture an 32-bit application from the 64-bit build properly.
