### ISSUE TITLE
qt5-default on Ubuntu

### ISSUE THREAD

**Issue by ntropy83** [baldurk/renderdoc#1502]
Just a hint, I was trieing to build renderdoc on a clean Ubuntu 18.04 and the lib qt5-default was missing in the dependencies manual. Without that it wouldnt compile.

**Comment by baldurk** [comment]
qt5-default is not required to compile on Ubuntu. From what I can see that package changes the system default Qt package to Qt5 with qtchooser, so would not be appropriate to recommend as a dependencies as it might interfere with what the user wants as their default.

What the instructions do explicitly state is that you might need to select Qt5 if it's not already the default, via a distribution-specific way. E.g. with qtchooser as Ubuntu uses you can export `QT_SELECT`:

> On any distribution if you find qmake isn't available under its default name, or if `qmake -v` lists a Qt4 version, make sure you have qtchooser installed in your package manager and use it to select Qt5. This might be done by exporting `QT_SELECT=qt5`, but check with your distribution for details.

**Comment by ntropy83** [comment]
I see ok. We'll I am no big friend of Qt, always having issues with it :)
