### ISSUE TITLE
Adding a no-op and recompiling the shader introduces artifacts 

### ISSUE THREAD

**Issue by gurchetansingh** [baldurk/renderdoc#1505]
Renderdoc version: 09e6d7

Platform: Intel Open Source Technology Center / Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)  / 4.5 (Core Profile) Mesa 19.2.0-devel (git-2bb4dc4054). Also reproduced on Mesa 17.3.9.

1) Open random OpenGL app. 
3) Pipeline State --> FS --> edit the fragment shader.
4) Add a single nop to the end of the fragment shader.  I added the follow line:

vec3 a = vec3(1.0, 1.0, 1.0);

6) Click the refresh to recompile shader.
7) Go to final frame via texture viewer -- observe no-op line causing rendering artifacts.  

Probably reproducible with other EIDs too.

**Comment by baldurk** [comment]
I do not condone or support capturing commercial copyrighted games that you are not the owner and creator of.

RenderDoc is intended only for debugging your own code.

**Comment by gurchetansingh** [comment]
Thanks for the clarification, edited details.  I'll see if I can get a repro with a simple test program.
