### ISSUE TITLE
add another overlay mode on adroid failed

### ISSUE THREAD

**Issue by shalouzx** [baldurk/renderdoc#1506]
hi, i am using renderdoc to check mobile game performance on android phone, the overlay option is a perfect function。now，i want to add another choice into the overlay option, it's called "overdraw", not like the quad overdraw, but the transparent overdraw. Firstly,i did the work on PC, i modified the d3d11_overlay.cpp, it worked perfectly, as you can see, it showed a paticlesystem in an overdraw mode.
![image](https://user-images.githubusercontent.com/21994073/63822077-d00d2f80-c981-11e9-9934-86e8d9f74ed6.png)

So i modified the gl_overlay.cpp file，i did the same thing, but when i connect to my phone, choose the same overlay, nothing changed... i tried to rebuilt the whole project, nothing changed. so i want to know how can i add a new overlay option on the android device？

I have met another problem with the android debug, i downloaded the renderdoc-1.4 sourcecode, i built the project, when i connected to my cellphone, it alwals reminded me no apk filed found, so i download the release version of renderdoc 1.4, i copied the plugins file folder into my built renderdoc directory, it only worked with the release and x86 mode in the visual studio 2017. I guess it is about the plugins version. So can i build the plugins myself, so i can get my own "org.renderdoc.renderdoccmd.arm32.apk"?

looking forward to answers!

**Comment by baldurk** [comment]
The visual studio solution only compiles the Windows build. If you need to build for Android then you should follow the instructions for the Android platform in [the documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Compiling.md#android). This produces the remote server APKs.
