### ISSUE TITLE
RenderDoc cannot get performance counters for OpenGL apps with NvPmApi.Core.dll provided

### ISSUE THREAD

**Issue by haozhigh2** [baldurk/renderdoc#1507]
## Description

Currently, getting data from counters works only with D3D11 replay.
NvPmApi could be used with D3D10, OpenGL, D3D9 APIs.

## Environment

RenderDoc build: v1.4
Operating System: Windows 10
API: OpenGL

**Comment by baldurk** [comment]
The IHV counter library support has been contributed by users. A pull request to expand support for NvPerfKit to OpenGL would be accepted, but I do not plan to do so myself since RenderDoc is not a profiler and the library has already been deprecated by nvidia.

**Comment by haozhigh2** [comment]
Thanks a lot for this quick reply.
