### ISSUE TITLE
Renderdoc silently aborts application when passing empty strings to glShaderSource

### ISSUE THREAD

**Issue by mickvangelderen** [baldurk/renderdoc#1508]
# Problem

I believe Renderdoc silently aborts application when passing empty strings to glShaderSource.

# Environment

 * Version: 1.2, 1.4
 * OS: Ubuntu 18.04
 * API: OpenGL

**Comment by mickvangelderen** [comment]
Unfortunately I don't have time to do more than just reporting right now.

**Comment by baldurk** [comment]
Can you please provide more information in your report? I don't expect you to create a minimal simple repro application but I need to have some idea of what you're doing to be able to reproduce and investigate the problem.

I ran some code like this and it worked fine for me:

```
      int zerolength = 0, nulltermlength = -1;
      const char *emptystr = "";

      glShaderSource(shad, 1, &emptystr, NULL); // without length
      glShaderSource(shad, 1, &emptystr, &zerolength); // with explicit zero length
      glShaderSource(shad, 1, &emptystr, &nulltermlength); // with implicit null terminated length
```

**Comment by mickvangelderen** [comment]
1. I'm passing the lenghts.
2. The strings are *not* null-terminated.
3. The address value for the empty string is 0x1. 

An example call:
```
pointers: [0x55588c3a856f, 0x55588c3a838c, 0x55588c3a8446, 0x1, 0x55588de76c00]
lengths : [273, 186, 297, 0, 252]
```

I'm not sure what the address of "" is in c/c++ but I think in rust a pointer to an empty array is set to the alignment of its elements, because references must be non-zero for a memory optimization. 

It is also possible something else, which has to do with compiling/linking shaders causes the application to silently stop.

**Comment by baldurk** [comment]
In C "" is a valid string with a null-terminator, so it points somewhere into the data segment. A pointer to 0x1 is invalid, but it's fine with a length of 0 since it's never dereferenced.

The GL spec doesn't explicitly say whether pointers are allowed to be garbage when the length is 0 but it's at least well defined so I can just skip over it.

**Comment by zao** [comment]
@mickvangelderen The 0x1 smells like you're using `String::as_ptr()` or `<Vec<u8>>::as_ptr()` in FFI, which sounds a bit iffy, as they don't guarantee much about `as_ptr` except that it can be used to reconstruct a `String` from parts, and that it's supposedly documented as a pointer to the first byte. As you've found out, it leverages `Unique::empty()` deep down, which is a non-null invalid pointer.

You may want to consider using types like `std::ffi::CString` for robustness which produce valid pointers for empty strings when using APIs which may incidentally care about the validity of a pointer.

**Comment by baldurk** [comment]
That commit should fix the crash, if the length is 0 the pointer should not be dereferenced.

**Comment by mickvangelderen** [comment]
@zao you are correct. I chose to not use CString because I didn't need a null-terminated string since OpenGL allows you to pass the string length here. I hadn't considered empty strings when implementing. 

If I don't think CString is appropriate, do you see other options than checking for Vec<u8>::is_empty and use `0x0` rather than `as_ptr()`.

@baldurk thanks for your work!
