### ISSUE TITLE
GL_ONE as blend factor displayed as GL_LINES

### ISSUE THREAD

**Issue by hrydgard** [baldurk/renderdoc#1517]
Just happened to notice this, in the API inspector:

![gl_lines](https://user-images.githubusercontent.com/130929/64654581-f4f5ae00-d429-11e9-842a-440e7c9198ac.PNG)

GL_LINES and GL_ONE both have the value 1, which probably explains the behavior. There's no 1:1 mapping between GL enum values and names :)

Seems this is another instance of #1452, which wasn't fixed by https://github.com/baldurk/renderdoc/commit/85738ad571034bc22374b0440ca42e2b5dce3598 .

**Comment by baldurk** [comment]
Yes this is the same as #1452 and it's simply down to GL being a badly designed API with enums that alias. The only way to completely fix this is to go and manually specialise the serialisation at every point where the enums overlap, and I'm not going to do that.

The blend state is displayed correctly in the pipeline state viewer which is easier to find and easier to read, so there's little advantage to changing the display of serialised function calls.
