### ISSUE TITLE
Replay Capture without saving to disk first

### ISSUE THREAD

**Issue by RicardSilva** [baldurk/renderdoc#1523]
## Description
Hi Baldur,

First of all thanks for making RenderDoc and open sourcing it. It is a really cool tool!

I am using RenderDoc to perform some analysis frame by frame.

My use case:
1.st save captures periodically
2.nd open captures with ReplayController and export a text file with some metrics

Is there any way to process the frame directly without needing to save to disk first and then reading it from disk again? I would like to capture and process directly without saving to disk first.

Is this possible?
Thanks!

**Comment by baldurk** [comment]
No there is no support for creating a capture entirely in memory. If the I/O overhead is too much for your case you could perhaps create a ramdisk or something like that, but this isn't something I'll support upstream.
