### ISSUE TITLE
Crash when updating immutable samplers in Vulkan

### ISSUE THREAD

**Issue by Pilzschaf** [baldurk/renderdoc#1528]
## Description

In Vulkan descriptors of type VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER and VK_DESCRIPTOR_TYPE_SAMPLER can be created with an immutable sampler. In this case the value of VkDescriptorImageInfo.sampler is ignored by Vulkan when vkUpdateDescriptorSets is called. So it should be safe to set VkDescriptorImageInfo.sampler to 0 in this case. Doing this results in a crash when recording the application with renderdoc as it seems to access the sampler even though the descriptor set has been created with an immutable sampler.

## Environment

* RenderDoc v1.4
* Operating System: Windows 10, Manjaro Linux
* API: Vulkan

**Comment by baldurk** [comment]
RenderDoc should handle a sampler set to `VK_NULL_HANDLE` in this case but it probably doesn't handle it if the sampler is set to garbage - is that what you're seeing?

**Comment by Pilzschaf** [comment]
You're right. Setting it to VK_NULL_HANDLE explicitly works. I think it should be completely ignored though as the Vulkan spec doesn't require it to be VK_NULL_HANDLE.

**Comment by baldurk** [comment]
100% agreed, I just wanted to check that there wasn't some other bug with sampler being NULL that I was missing. That commit should correctly ignore the sampler parameter in updates when the set layout defines immutable samplers.

**Comment by Pilzschaf** [comment]
That's what I call a quick fix :) Thanks
