### ISSUE TITLE
Vulkan captures are too big

### ISSUE THREAD

**Issue by Vincent-P** [baldurk/renderdoc#1537]
## Description

Vulkan capture are from 2 to 26 times bigger than the same capture in DX11. My biggest Vulkan capture is 4.11GB whereas the DX11 capture is 134MB.

It takes minutes to make and open a capture and Renderdoc uses all the RAM available to open a capture (64GB).
The weird thing is that taking a capture in the same application using DX11 is really fast and captures are small.

Do you have any ideas to explain the difference in size and what can I do about it?

## Environment

* RenderDoc build: nightly v1.5 built from 76622f65
* Operating System: Windows 10 Pro 1809
* API: Vulkan
* GPU: RTX 2070, v431.07

**Comment by baldurk** [comment]
This depends entirely on what the application is doing in DX11 and in Vulkan. There's nothing intrinsically about Vulkan captures that make them larger, but your application might be doing something different on Vulkan that leads to an increased size and slower capture.

Can you share an equivalent DX11 and Vulkan capture? I can compare them and tell you why the Vulkan capture is bigger and if it's expected.

My guess is that if the capture is 4GB and it's using many times more than that RAM, it probably means your application is mapping and unmapping large memory allocations where not much has changed or is even used, so there is a lot of empty data that gets heavily compressed to disk.

**Comment by Vincent-P** [comment]
Thank you for your quick answer!
Unfortunately I don't know if I can make and share an equivalent capture yet.
But there are indeed a lot of `vkUnmapMemory` at the start of the frame that DirectX doesn't have, I will look into it.

**Comment by Vincent-P** [comment]
I got rid of the `vkUnmapMemory` and now the captures have the same size as DX11 captures.
It is still a bit slow to take the capture but it is now at least usable.
Thank you for taking time to help me :)
