### ISSUE TITLE
D3D12_CreateGraphicsPipelineState crash

### ISSUE THREAD

**Issue by RicardSilva** [baldurk/renderdoc#1542]
Hello,

I am trying to capture an D3D12 application but it crashes as soon as the window opens.

The error message is "NvAPI_D3D12_CreateGraphicsPipelineState" failed with E_FAIL

Do you have any idea of what could be causing this issue? I have attached a print screen and the log file

Thanks in advance for your help!

![Screenshot (1)](https://user-images.githubusercontent.com/9673695/66220861-1ca90080-e6ce-11e9-9b63-fd72374b3c53.png)

**Comment by RicardSilva** [comment]
RDOC 004484: [17:22:57]  sys_win32_hooks.cpp(  82) - Log     - Registering Win32 system hooks
RDOC 004484: [17:22:57]      d3d11_hooks.cpp( 125) - Log     - Registering D3D11 hooks
RDOC 004484: [17:22:57]      d3d12_hooks.cpp( 125) - Log     - Registering D3D12 hooks
RDOC 004484: [17:22:57]       d3d8_hooks.cpp(  36) - Log     - Registering D3D8 hooks
RDOC 004484: [17:22:57]       d3d9_hooks.cpp(  45) - Log     - Registering D3D9 hooks
RDOC 004484: [17:22:57]       dxgi_hooks.cpp(  77) - Log     - Registering DXGI hooks
RDOC 004484: [17:22:57]        egl_hooks.cpp( 751) - Log     - Registering EGL hooks
RDOC 004484: [17:22:57]         gl_hooks.cpp( 223) - Log     - Registering OpenGL hooks
RDOC 004484: [17:22:57]        wgl_hooks.cpp( 594) - Log     - Registering WGL hooks
RDOC 004484: [17:22:57]         vk_layer.cpp(  53) - Log     - Registering Vulkan hooks
RDOC 004484: [17:22:57]        wgl_hooks.cpp( 578) - Debug   - WGL library hooked
RDOC 012624: [17:22:57]    win32_process.cpp( 411) - Debug   - Injecting call to INTERNAL_SetCaptureOptions
RDOC 012624: [17:22:57]    win32_process.cpp( 411) - Debug   - Injecting call to INTERNAL_GetTargetControlIdent
RDOC 004484: [17:23:19]      d3d11_hooks.cpp( 420) - Warning - NvAPI disabled: Returning NULL for nvapi_QueryInterface(1053fa5)
RDOC 004484: [17:23:19]      d3d11_hooks.cpp( 420) - Warning - NvAPI disabled: Returning NULL for nvapi_QueryInterface(2926aaad)
RDOC 004484: [17:23:19]      d3d11_hooks.cpp( 420) - Warning - NvAPI disabled: Returning NULL for nvapi_QueryInterface(6c2d048c)
RDOC 004484: [17:23:19]      d3d11_hooks.cpp( 420) - Warning - NvAPI disabled: Returning NULL for nvapi_QueryInterface(48b3ea59)
RDOC 004484: [17:23:19]      d3d11_hooks.cpp( 420) - Warning - NvAPI disabled: Returning NULL for nvapi_QueryInterface(e5ac921f)
RDOC 004484: [17:23:19]      d3d12_hooks.cpp( 208) - Debug   - Call to Create_Internal Feature Level b000
RDOC 004484: [17:23:19]      d3d12_hooks.cpp( 218) - Debug   - Calling real createdevice...
RDOC 004484: [17:23:19]      dxgi_common.cpp(1621) - Warning - Querying IDXGIAdapter for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 004484: [17:23:19]      dxgi_common.cpp(1616) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 004484: [17:23:20]      d3d12_hooks.cpp( 239) - Debug   - Called real createdevice... HRESULT: S_OK
RDOC 004484: [17:23:20]      d3d12_hooks.cpp( 243) - Debug   - succeeded and hooking.
RDOC 004484: [17:23:20]     d3d12_device.cpp( 379) - Debug   - Couldn't get ID3D12InfoQueue.
RDOC 004484: [17:23:20]      d3d12_hooks.cpp( 280) - Debug   - created wrapped device.
RDOC 004484: [17:23:20]      d3d11_hooks.cpp( 420) - Warning - NvAPI disabled: Returning NULL for nvapi_QueryInterface(6ef4d2d1)
RDOC 004484: [17:23:20]      d3d11_hooks.cpp( 420) - Warning - NvAPI disabled: Returning NULL for nvapi_QueryInterface(d44d3c4e)
RDOC 004484: [17:23:20]      d3d11_hooks.cpp( 420) - Warning - NvAPI disabled: Returning NULL for nvapi_QueryInterface(6c2d048c)
RDOC 004484: [17:23:20]       shader_cache.h( 139) - Debug   - Successfully loaded 10 shaders from shader cache
RDOC 004484: [17:23:20]      d3d12_hooks.cpp( 208) - Debug   - Call to Create_Internal Feature Level b000
RDOC 004484: [17:23:20]      d3d12_hooks.cpp( 218) - Debug   - Calling real createdevice...
RDOC 004484: [17:23:20]      dxgi_common.cpp(1616) - Warning - Querying IDXGIAdapter for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 004484: [17:23:20]      dxgi_common.cpp(1616) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 004484: [17:23:20]      d3d12_hooks.cpp( 239) - Debug   - Called real createdevice... HRESULT: S_OK
RDOC 004484: [17:23:20]      d3d12_hooks.cpp( 243) - Debug   - succeeded and hooking.
RDOC 004484: [17:23:20]     d3d12_device.cpp( 379) - Debug   - Couldn't get ID3D12InfoQueue.
RDOC 004484: [17:23:20]      d3d12_hooks.cpp( 280) - Debug   - created wrapped device.
RDOC 004484: [17:23:20]      d3d11_hooks.cpp( 420) - Warning - NvAPI disabled: Returning NULL for nvapi_QueryInterface(6ef4d2d1)
RDOC 004484: [17:23:20]      d3d11_hooks.cpp( 420) - Warning - NvAPI disabled: Returning NULL for nvapi_QueryInterface(d44d3c4e)
RDOC 004484: [17:23:20]       shader_cache.h( 139) - Debug   - Successfully loaded 10 shaders from shader cache
RDOC 004484: [17:23:43]  sys_win32_hooks.cpp( 224) - Debug   - Calling real CreateProcessA
RDOC 004484: [17:23:43]  sys_win32_hooks.cpp( 226) - Debug   - Called real CreateProcessA

**Comment by baldurk** [comment]
RenderDoc does not support nvapi, and your application must detect and handle errors in unsupported nvapi functions according to their docs. The message box you're showing is from your own application, not from RenderDoc.
