### ISSUE TITLE
Texture Viewer does not show slices of 3d images with Slice/Face dropdown

### ISSUE THREAD

**Issue by Raikiri** [baldurk/renderdoc#1544]
As the name says, it does not work and always shows the first slice of the image.

**Comment by zao** [comment]
There was a bug (#1366) addressed just after 1.4 that seems quite similar to your problem.

Is this with a release version of RenderDoc or a Nightly or own build? You may want to try a Nightly build to see if it still happens - https://renderdoc.org/builds

**Comment by Raikiri** [comment]
I was running 1.4. This problem is indeed fixed in a nightly build.
