### ISSUE TITLE
Application launch failed，Game is launch ok.

### ISSUE THREAD

**Issue by mimijava** [baldurk/renderdoc#1558]
## Description
https://github.com/baldurk/renderdoc/commit/24fb676aa1a9e1415675e04f20d8c41bb0307f10

I found the application could not be launch from this summit, and socket communication exception occurred during the launch.  Game is Ok.

RDOC 022076: [14:44:08]    android_tools.cpp( 308) - Log     - COMMAND: D:\Android\sdk\platform-tools\adb.exe '-s QFF0119701000296 shell ls /data/app/com.sina.weibo-iZYWgk9gMaQ0n5pFEUxKlA==//lib/*/libVkLayer_GLES_RenderDoc.so'
RDOC 022076: [14:44:08]          android.cpp(1097) - Log     - No library found in /data/app/com.sina.weibo-iZYWgk9gMaQ0n5pFEUxKlA==//lib/*/libVkLayer_GLES_RenderDoc.so for com.sina.weibo - assuming injection is required.
RDOC 022076: [14:44:08]          android.cpp(1107) - Log     - Launching package 'com.sina.weibo' with activity 'com.sina.weibo.SplashActivity'
RDOC 022076: [14:44:08]          android.cpp(1136) - Log     - Launching APK with no debugger or direct injection.
RDOC 022076: [14:44:08]    android_tools.cpp( 308) - Log     - COMMAND: D:\Android\sdk\platform-tools\adb.exe '-s QFF0119701000296 shell am start -n com.sina.weibo/com.sina.weibo.SplashActivity '
RDOC 022076: [14:44:08]    android_tools.cpp( 308) - Log     - COMMAND: D:\Android\sdk\platform-tools\adb.exe '-s QFF0119701000296 forward tcp:22019 localabstract:seagull-gator-socket'
RDOC 022076: [14:44:08]    android_tools.cpp( 308) - Log     - COMMAND: D:\Android\sdk\platform-tools\adb.exe '-s QFF0119701000296 forward tcp:39930 localabstract:seagull-trace-socket'
RDOC 022076: [14:44:08]    android_tools.cpp( 308) - Log     - COMMAND: D:\Android\sdk\platform-tools\adb.exe '-s QFF0119701000296 forward tcp:38969 localabstract:renderdoc_39920'
RDOC 022076: [14:44:08]    android_tools.cpp( 308) - Log     - COMMAND: D:\Android\sdk\platform-tools\adb.exe '-s QFF0119701000296 forward tcp:38960 localabstract:renderdoc_38920'
**RDOC 022076: [14:44:09]         streamio.cpp( 319) - Warning - Error reading from socket
RDOC 022076: [14:44:09]    android_tools.cpp( 308) - Log     - COMMAND: D:\Android\sdk\platform-tools\adb.exe '-s QFF0119701000296 shell ps -A | grep com.sina.weibo'
RDOC 022076: [14:44:10]         streamio.cpp( 319) - Warning - Error reading from socket
RDOC 022076: [14:44:10]    android_tools.cpp( 308) - Log     - COMMAND: D:\Android\sdk\platform-tools\adb.exe '-s QFF0119701000296 shell ps -A | grep com.sina.weibo'
RDOC 022076: [14:44:12]         streamio.cpp( 319) - Warning - Error reading from socket**

[normal log as this]
RDOC 021468: [15:28:45]    android_tools.cpp( 308) - Log     - COMMAND: D:\Android\sdk\platform-tools\adb.exe '-s QFF0119701000296 forward tcp:38960 localabstract:renderdoc_38920'
**RDOC 021468: [15:28:45]    android_tools.cpp( 308) - Log     - COMMAND: D:\Android\sdk\platform-tools\adb.exe '-s QFF0119701000296 forward tcp:39501 jdwp:16480'
RDOC 021468: [15:28:46]    android_tools.cpp( 308) - Log     - COMMAND: D:\Android\sdk\platform-tools\adb.exe '-s QFF0119701000296 shell pm path org.renderdoc.renderdoccmd.arm32'
RDOC 021468: [15:28:46]             jdwp.cpp( 160) - Log     - Injecting RenderDoc from library in /data/app/org.renderdoc.renderdoccmd.arm32-q1P5QJ2H0nMSIntmhepIIg==/lib/arm
RDOC 021468: [15:28:46]             jdwp.cpp( 209) - Log     - Got android.app.ApplicationLoaders.getClassLoader signature (Ljava/lang/String;IZLjava/lang/String;Ljava/lang/String;Ljava/lang/ClassLoader;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)Ljava/lang/ClassLoader;
ADRD 016480: [23:28:49]    posix_network.cpp( 403) - Log     - Created and bind socket: 44**

**Comment by baldurk** [comment]
Please provide a **full** bug report when reporting an issue. Include as detailed a description as you possibly can of what you are doing, what is happening, and what goes wrong. The issue template is provided for a reason since it asks for information which is necessary for almost all bug reports. Deleting the sections asking for repro steps and your environment such as the version of RenderDoc and API & OS in use only cause everyone more problems as I then will very likely need to ask you explicitly to provide those details.

When including the diagnostic log then please upload the log in full and unedited, since otherwise you might delete some lines that are important.

**Comment by mimijava** [comment]
## Repro steps
1.Install a application
2.launcher the application
3.failed launch
[RenderDoc_2019.10.21_18.21.01.log](https://github.com/baldurk/renderdoc/files/3750196/RenderDoc_2019.10.21_18.21.01.log)

## Environment
* RenderDoc build: RenderDoc_2019_09_10_173a2684_64 nightly build.
* Operating System: e.g. Windows 10, 
* API: opengles

**Comment by baldurk** [comment]
Your application is using an unsupported ABI, `armeabi`. RenderDoc only supports `armeabi-v7a` and `arm64-v8a`, the NDK deprecated and removed `armeabi` support last year.

I can add some better error message handling for this but you will need to compile the application against a supported ABI to capture.
