### ISSUE TITLE
unity crash when click "Load RenderDoc" menu

### ISSUE THREAD

**Issue by songtm** [baldurk/renderdoc#1560]
## Description

Unity crash when click "Load RenderDoc" menu,and here is the log
```
RDOC 010568: [18:17:41]             core.cpp( 370) - Log     - RenderDoc v1.5 Windows 64-bit Release (a94f238e37cfe2f142093eb8e5da7775abaa88c6) capturing application
RDOC 010568: [18:17:41]      crash_handler.h( 175) - Log     - Timer Waiting for crash handling server - 58.803 ms
RDOC 010568: [18:17:41]      crash_handler.h( 181) - Log     - Created crash-handling server \\.\pipe\RenderDocBreakpadServer2177723999081
RDOC 010568: [18:17:41]      crash_handler.h(  93) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer2177723999081
RDOC 010568: [18:17:41]   win32_libentry.cpp(  66) - Log     - Loading into E:\Program Files\Unity\2017.4.32f1\Editor\Unity.exe
RDOC 010568: [18:17:41]  sys_win32_hooks.cpp(  82) - Log     - Registering Win32 system hooks
RDOC 010568: [18:17:41]      d3d11_hooks.cpp( 125) - Log     - Registering D3D11 hooks
RDOC 010568: [18:17:41]      d3d12_hooks.cpp( 181) - Log     - Registering D3D12 hooks
RDOC 010568: [18:17:41]       d3d8_hooks.cpp(  36) - Log     - Registering D3D8 hooks
RDOC 010568: [18:17:41]       d3d9_hooks.cpp(  45) - Log     - Registering D3D9 hooks
RDOC 010568: [18:17:41]       dxgi_hooks.cpp( 250) - Log     - Registering DXGI hooks
RDOC 010568: [18:17:41]        egl_hooks.cpp( 958) - Log     - Registering EGL hooks
RDOC 010568: [18:17:41]         gl_hooks.cpp( 255) - Log     - Registering OpenGL hooks
RDOC 010568: [18:17:41]        wgl_hooks.cpp( 610) - Log     - Registering WGL hooks
RDOC 010568: [18:17:41]         vk_layer.cpp(  53) - Log     - Registering Vulkan hooks

```

## Repro steps

- install the renderdoc
- open a new unity project 
- click the "Load RenderDoc" menu on the scene view

## Environment

* RenderDoc build: v1.5.
* Operating System: Win10, GTX 1050 Ti
* API: D3D11

There is some one same [here](https://issuetracker.unity3d.com/issues/crash-when-trying-to-load-renderdoc-while-using-opengl-graphics-api-backend)

**Comment by baldurk** [comment]
As far as I'm aware this has been a known issue in Unity for a number of versions, I've observed the crash myself in a few versions, and it seems like I can reproduce it in this one (though as in the linked bug report, only for GL and not for D3D11 as you reported).

If you launch the Unity editor through RenderDoc as a normal program instead of using the "Load RenderDoc" menu item it should work fine, since the underlying issue is a Unity bug with reloading the graphics system.
