### ISSUE TITLE
Crash vulkan in Linux

### ISSUE THREAD

**Issue by sdelta13** [baldurk/renderdoc#1561]
## Description

Crash renderdoc if view image from swapchains in vulkan.
![crash](https://user-images.githubusercontent.com/11386592/67391209-e52fc480-f5a6-11e9-983b-50290ef6635c.png)

## Repro steps
Unzip and open [test.rdc.zip](https://github.com/baldurk/renderdoc/files/3762249/test.rdc.zip)
Open "Texture View"

## Environment

* RenderDoc build: e.g. v1.6, unstable build from source code.
* Operating System: Arch Linux 
* API: e.g. Vulkan
*Use optirun+primus_vk and nvidia driver 435.21

**Comment by baldurk** [comment]
This capture shows many cases where the program is using vulkan in an invalid way. You should run your program with the vulkan validation layers and ensure that you fix all problems that they identify, as invalid API use can lead to crashes in RenderDoc even if it doesn't cause crashes in the program.

Could you please also test without using this optirun/primus_vk project, as the callstack in the crash you are showing indicates that the crash happens somewhere inside the vulkan call, either in a layer or in the driver, so this could be causing the problem.

If it still crashes for you when using the nvidia (or intel) driver directly on a program with no validation issues at all, please share another capture and I can look into it further.

**Comment by sdelta13** [comment]
I'm sorry, this error in primus_vk (In Intel driver work is correct).
