### ISSUE TITLE
Shader compile errors when replaying GLES

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1563]
## Description

I got these shader compile error messages in the histogram.comp when I replayed GLES:

- OpenGL does not allow swizzles on scalar expressions
for example:
https://github.com/baldurk/renderdoc/blob/875e27d84449c46e938aaa7f30476c0d94ecb217/renderdoc/data/glsl/histogram.comp#L72
Scalar swizzling could be replaced by vec4/uvec4.

- implicit cast from "int" to "float"
for example:
https://github.com/baldurk/renderdoc/blob/875e27d84449c46e938aaa7f30476c0d94ecb217/renderdoc/data/glsl/histogram.comp#L82

- implicit cast from "int" to "uint"
for example:
https://github.com/baldurk/renderdoc/blob/875e27d84449c46e938aaa7f30476c0d94ecb217/renderdoc/data/glsl/histogram.comp#L90
Constant types could be explicitly specified.

A possible fix: https://github.com/tabikati/renderdoc/commit/336d26db909ce6d402b6c2c77cccd018c01113ec

## Environment

* RenderDoc build: v1.x, 2019-10-24.
* Operating System: Ubuntu Linux
* API: OpenGL ES

**Comment by baldurk** [comment]
Closed with #1562
