### ISSUE TITLE
RenderDoc v1.5 can not open some DDS files in Texture Viewer

### ISSUE THREAD

**Issue by m0lz** [baldurk/renderdoc#1567]
RenderDoc v1.5 - Windows 10 v1903 x64

RenderDoc throws errors when trying to open certain dds files in Texture Viewer

See the files here https://sourceforge.net/p/openil/svn/HEAD/tree/trunk/Test%20Images/DDS/

The following file names would not load from that list ..

DDS_cxv8u8.dds
DDS_d32f_lockable.dds
DDS_dxt2.dds
DDS_dxt4.dds
DDS_uyvy.dds
DDS_yuy2.dds

**Comment by baldurk** [comment]
I've added support for a couple of formats that were trivial (`DXT2` and `DXT4` are just the same as DXT3 and `DXT5` = `BC2` and `BC3`, `D32F` is easy).

I also added support for `YUY2`/`UYVY` where the underlying displaying graphics API can support that format (D3D11 supports it on windows 10, but not on windows 7. GL doesn't support it at all).

`CxV8U8` however is a legacy format that is not supported on any modern API so support for that format in DDS isn't going to happen. The error message you already get is clear - the image file is recognised but the specific format is not supported.

**Comment by zao** [comment]
Note that the error is more clear in in nightly builds than it is in the v1.5 that the reporter used.

v1.5: `Failed to open capture for replay: ReplayStatus(12).`
Recent build: `Failed to open capture for replay: The image file is recognised but the format is unsupported.`

**Comment by baldurk** [comment]
Oh oops I forgot I fixed that independently a little while ago. That's a fair point!

**Comment by m0lz** [comment]
Wow that was all fixed quickly

Thank you Baldurk :)

Edit : And my apologies, I should have included error details
