### ISSUE TITLE
Resource Release (D3D11) is crashing

### ISSUE THREAD

**Issue by midnite8177** [baldurk/renderdoc#157]
Hello,
We take advantage of releasing resources on different threads, sometimes concurrently. If we are using RenderDoc this can cause a crash because the use of STL map is not protected by a critical section. For example:

	virtual ~WrappedID3D11Buffer()
	{
		if(m_BufferList.find(GetResourceID()) != m_BufferList.end())
			m_BufferList.erase(GetResourceID());

		Shutdown();
	}

In this case m_BufferList.erase can crash if other threads are modifying it at the same time.

**Comment by baldurk** [comment]
Good catch! I will fix this.

**Comment by baldurk** [comment]
I had to make a couple of locks a bit more aggressive than they might need to be, otherwise there was a risk of them deadlocking with the more general lock around serialising/resource management.
