### ISSUE TITLE
Structured Buffer not being read correctly in compute shader replay

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#1575]
## Description

I have an issue where a structured buffer isn't being read correctly in the compute shader replay. I have a repro, but I need to send a capture.

## Steps to reproduce

Open the capture. Observe how the buffer is correctly populated (if looking at it in the buffer viewer) but the replay thinks all reads are 0. Therefore debugging the subsequent results is incorrect. I have now verified that this works in renderdoc 1.4.

## Environment

* RenderDoc version: 1.5
* Operating System: Windows 10
* API: D3D11

**Comment by baldurk** [comment]
Yes this was a regression in 1.5 while fixing some other cases of buffer loads. It has since been fixed so if you run a recent nightly build it should work correctly. If it is still broken please let me know.

**Comment by redorav** [comment]
Ah I see. I'll stick to 1.4 for now then. Thanks for the quick reply.

For peace of mind I'll also have you know the nightly works :)
