### ISSUE TITLE
IsFrameCapturing API hook returns 0 during captures started with TriggerCapture

### ISSUE THREAD

**Issue by mkgski** [baldurk/renderdoc#158]
The IsFrameCapturing call works fine for Start/EndFrameCapture pairs but not for TriggerCapture.  Was that intentional, or just an oversight? Also, am I right in assuming that the default capture behavior (PrintScreen/F12) routes through TriggerCapture as well?

**Comment by baldurk** [comment]
Yes you're right, the way that IsFrameCapturing tracks things it does rely on explicit calls to Start/EndFrameCapture - this shouldn't be hard to fix.

And yes the default keybinds do go through TriggerCapture.

**Comment by baldurk** [comment]
IsFrameCapturing should behave correctly now with that commit.

**Comment by baldurk** [comment]
Sorry I missed the email notification of your comment on the commit somehow, and otherwise they are pretty subtle to see (just a little speech bubble). You were absolutely right and it should be correct now hopefully.

**Comment by baldurk** [comment]
Closing as this was fixed for v0.27, re-open if it's not properly resolved.
