### ISSUE TITLE
OpenGLES captured RDC file replaying output is black at Android Q version

### ISSUE THREAD

**Issue by xidian10000** [baldurk/renderdoc#1582]
## Description

I was capturing an OpenGL ES Android application （com.netease.hyxd.apk）and when I tried to replay it, RenderDoc replay result is always black。The problem is happened android Q.

## Steps to reproduce
1. capture any frame，and replay is black。
game app link:
https://adl.netease.com/d/g/hy/c/1028azxfcsyd?type=android

2. but I tried to modify file ： gl_common.cpp   
fuction ：static void CheckExtFromString(const char *ext) 
Judging the condition from “||” to "&&"  the following line，then captured new frame，and the playback result is normal。

#define EXT_TO_CHECK(ver, glesver, extname)                                       \
  if((!IsGLES && GLCoreVersion >= ver) || (IsGLES && GLCoreVersion >= glesver) **||** \
     !strcmp(ext, STRINGIZE(extname)))                                            \
    HasExt[extname] = true;
to
#define EXT_TO_CHECK(ver, glesver, extname)                                       \
  if(((!IsGLES && GLCoreVersion >= ver) || (IsGLES && GLCoreVersion >= glesver)) **&&** \
     !strcmp(ext, STRINGIZE(extname)))                                            \
    HasExt[extname] = true;

Please confirm if there is a bug, can I modify it like this?

## Environment

* RenderDoc version: v1.x branch @ 2b7753af, 2019-11-06
* Operating System: win10 x64
* API: OpenGL ES
* Android device: huawei mate30
* Android version: 10.0

**Comment by baldurk** [comment]
Unfortunately the apk you've provided is not debuggable, so I can't try to reproduce the problem with it. Can you share a debuggable APK with me? You can do so privately if you don't want to share it publicly.

The change your propose is wrong. That code is checking to see either if an extension string is supported, or if the current context version is high enough that the extension has been promoted to core (with different core versions for proper GL and GLES). Any of the conditions is sufficient for the extension to be considered supported.

**Comment by xidian10000** [comment]
Sorry, I can't share a debuggable APK because I have not . I feel strange that the  game will emulating opengl es 1.1 and opengl es 3.2.
First emulating opengl es 1.1 ,  ARB_program_interface_query is not support, The code executes the following judgment conditions：

  if(!HasExt[ARB_program_interface_query])
    {
      RDCLOG("Emulating ARB_program_interface_query");
      EMULATE_FUNC(glGetProgramInterfaceiv);
      EMULATE_FUNC(glGetProgramResourceIndex);
      EMULATE_FUNC(glGetProgramResourceName);
      EMULATE_FUNC(glGetProgramResourceiv);
    } 

Second emulating opengl es 3.2， ARB_program_interface_query is support, but glGetProgramInterfaceiv still calling  glEmulate::_glGetProgramInterfaceiv.

So it will lead to capture the apk（com.netease.hyxd.apk）and  replay result is always black

The following is the part  log of capturing frame:
ADRD 004008: [19:21:39]        gl_driver.cpp(1128) - Log     - Core context CD6E3EC0 created with attribs, sharing with context 00000000
ADRD 004008: [19:21:39]        gl_common.cpp( 443) - Log     - Checking enabled extensions, running as OpenGL ES 1.0
ADRD 004008: [19:21:39]      gl_emulated.cpp(2966) - Log     - Emulating glTransformFeedbackBufferBase
ADRD 004008: [19:21:39]      gl_emulated.cpp(2967) - Log     - Emulating glTransformFeedbackBufferRange
ADRD 004008: [19:21:39]      gl_emulated.cpp(2968) - Log     - Emulating glClearNamedFramebufferiv
ADRD 004008: [19:21:39]      gl_emulated.cpp(2969) - Log     - Emulating glClearNamedFramebufferuiv
ADRD 004008: [19:21:39]      gl_emulated.cpp(2970) - Log     - Emulating glClearNamedFramebufferfv
ADRD 004008: [19:21:39]      gl_emulated.cpp(2971) - Log     - Emulating glClearNamedFramebufferfi
ADRD 004008: [19:21:39]      gl_emulated.cpp(2972) - Log     - Emulating glBlitNamedFramebuffer
ADRD 004008: [19:21:39]      gl_emulated.cpp(2973) - Log     - Emulating glVertexArrayElementBuffer
ADRD 004008: [19:21:39]      gl_emulated.cpp(2974) - Log     - Emulating glVertexArrayVertexBuffers
ADRD 004008: [19:21:39]      gl_emulated.cpp(3014) - Log     - Emulating ARB_copy_image
ADRD 004008: [19:21:39]      gl_emulated.cpp(3021) - Log     - Emulating ARB_clear_buffer_object
ADRD 004008: [19:21:39]      gl_emulated.cpp(3036) - Log     - Emulating ARB_internalformat_query2
ADRD 004008: [19:21:39]      gl_emulated.cpp(3045) - Log     - Emulating ARB_separate_shader_objects
ADRD 004008: [19:21:39]      gl_emulated.cpp(3116) - Log     - Emulating ARB_program_interface_query
ADRD 004008: [19:21:39]      gl_emulated.cpp(3177) - Log     - Emulating GLES 3.x functions
ADRD 004008: [19:21:39]      gl_emulated.cpp(3184) - Log     - Emulating GLES 3.1 functions
ADRD 004008: [19:21:39]      gl_emulated.cpp(3192) - Log     - Emulating GLES 3.2 functions
ADRD 004008: [19:21:39]      gl_emulated.cpp(3222) - Log     - Emulating EXT_direct_state_access
ADRD 004008: [19:21:39]      gl_emulated.cpp(3309) - Log     - Emulating ARB_direct_state_access
ADRD 004008: [19:21:39]        gl_driver.cpp(1351) - Log     - Activating new GL context: ARM / Mali-G72 / OpenGL ES-CM 1.1 v1.r14p0-00cet0.fa9a6fc9126cea3e3658a189f54fe6da
ADRD 004008: [19:21:39]        gl_common.cpp( 494) - Log     - Vendor checks for 0 (ARM / Mali-G72 / OpenGL ES-CM 1.1 v1.r14p0-00cet0.fa9a6fc9126cea3e3658a189f54fe6da)
ADRD 004008: [19:21:39]        gl_common.cpp( 817) - Warning - Reading from the depth buffer using glReadPixels is not supported (GL_NV_read_depth)
ADRD 004008: [19:21:39]        gl_common.cpp( 821) - Warning - Reading from the stencil buffer using glReadPixels is not supported (GL_NV_read_stencil)
ADRD 004008: [19:21:39]        gl_common.cpp( 825) - Warning - Reading from the packed depth-stencil buffers using glReadPixels is not supported (GL_NV_read_depth_stencil)
RDOC 042856: [15:03:27]   target_control.cpp(1047) - Log     - Used API: OpenGLES (Not presenting & supported)
ADRD 004008: [19:21:39]     android_hook.cpp( 797) - Log     - Refreshing android hooks...
ADRD 004008: [19:21:39]     android_hook.cpp( 799) - Log     - Refreshed
ADRD 004008: [19:21:39]        egl_hooks.cpp( 287) - Debug   - eglCreateContext:
ADRD 004008: [19:21:39]        egl_hooks.cpp( 294) - Debug   - 3098: 2
ADRD 004008: [19:21:39]        gl_driver.cpp(1128) - Log     - Core context BE962E80 created with attribs, sharing with context 00000000
ADRD 004008: [19:21:39]        gl_common.cpp( 443) - Log     - Checking enabled extensions, running as OpenGL ES 3.2
ADRD 004008: [19:21:39]      gl_emulated.cpp(3021) - Log     - Emulating ARB_clear_buffer_object
ADRD 004008: [19:21:39]      gl_emulated.cpp(3036) - Log     - Emulating ARB_internalformat_query2
ADRD 004008: [19:21:39]      gl_emulated.cpp(3045) - Log     - Emulating ARB_separate_shader_objects
ADRD 004008: [19:21:39]      gl_emulated.cpp(3116) - Log     - Emulating ARB_program_interface_query
ADRD 004008: [19:21:39]      gl_emulated.cpp(3177) - Log     - Emulating GLES 3.x functions
ADRD 004008: [19:21:39]      gl_emulated.cpp(3222) - Log     - Emulating EXT_direct_state_access
ADRD 004008: [19:21:39]      gl_emulated.cpp(3309) - Log     - Emulating ARB_direct_state_access
ADRD 004008: [19:21:39]        gl_driver.cpp(1351) - Log     - Activating new GL context: ARM / Mali-G72 / OpenGL ES 3.2 v1.r14p0-00cet0.fa9a6fc9126cea3e3658a189f54fe6da

**Comment by baldurk** [comment]
OpenGL ES 1.x is not supported by RenderDoc at all and may indeed cause problems if the application is creating a 1.x context. You should modify your app to not create any GLES 1 contexts as the API is unsupported.
