### ISSUE TITLE
RenderDoc 1.2 Can´t Initialize API: Missing extensions

### ISSUE THREAD

**Issue by Fugaxo** [baldurk/renderdoc#1587]
## Description
Hello

I am having trouble with renderdoc 1.2 when openning a capture. Somehow it seems renderdoc is unable to find some extensions. Here is my log : 

RDOC 002900: [16:19:31]             core.cpp( 310) - Log     - RenderDoc v1.2 64-bit Release (204724bebe2484ee2d14a572d9f1074dd3f933a9) loaded in replay application
RDOC 002900: [16:19:31]      crash_handler.h( 112) - Log     - Creating crash-handling server
RDOC 014920: [16:19:31]             core.cpp( 310) - Log     - RenderDoc v1.2 64-bit Release (204724bebe2484ee2d14a572d9f1074dd3f933a9) loaded in replay application
QTRD 002900: [16:19:31]       qrenderdoc.cpp(  88) - Log     - QRenderDoc initialising.
QTRD 002900: [16:19:47]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange () 0
QTRD 002900: [16:19:47]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange () 0
QTRD 002900: [16:19:48]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///D:/Users/Pedro/Desktop/Captures/capture.rdc")) 1
RDOC 002900: [16:19:49]          rdcfile.cpp( 240) - Log     - Opening RDCFile D:/Users/Pedro/Desktop/Captures/capture.rdc
RDOC 002900: [16:19:49]          rdcfile.cpp( 240) - Log     - Opening RDCFile D:/Users/Pedro/Desktop/Captures/capture.rdc
RDOC 002900: [16:19:49]        gl_replay.cpp(3496) - Log     - Creating an OpenGL ES replay device
RDOC 002900: [16:19:49]        gl_replay.cpp(3510) - Log     - Initialising GLES replay via libEGL
RDOC 002900: [16:19:50]        gl_common.cpp( 461) - Log     - Checking enabled extensions, running as OpenGL ES 3.0
RDOC 002900: [16:19:50]      gl_emulated.cpp(2057) - Log     - Emulating ARB_copy_image
RDOC 002900: [16:19:50]      gl_emulated.cpp(2064) - Log     - Emulating ARB_clear_buffer_object
RDOC 002900: [16:19:50]      gl_emulated.cpp(2079) - Log     - Emulating ARB_internalformat_query2
RDOC 002900: [16:19:50]      gl_emulated.cpp(2133) - Log     - Emulating EXT_direct_state_access
RDOC 002900: [16:19:50]      gl_emulated.cpp(2220) - Log     - Emulating ARB_direct_state_access
RDOC 002900: [16:19:50]        gl_common.cpp(  76) - Log     - Running GL replay on: Google Inc. / ANGLE (NVIDIA GeForce GTX 960M Direct3D11 vs_5_0 ps_5_0) / OpenGL ES 3.0 (ANGLE 2.1.0.8613f4946861)
RDOC 002900: [16:19:50]        gl_common.cpp(  90) - Log     - [0]: GL_OES_element_index_uint, [1]: GL_OES_packed_depth_stencil, [2]: GL_OES_get_program_binary, [3]: GL_OES_rgb8_rgba8, [4]: GL_EXT_texture_format_BGRA8888, [5]: GL_EXT_read_format_bgra, [6]: GL_NV_pixel_buffer_object, [7]: GL_OES_mapbuffer, [8]: GL_EXT_map_buffer_range, [9]: GL_EXT_color_buffer_half_float, [10]: GL_OES_texture_half_float, [11]: GL_OES_texture_half_float_linear, [12]: GL_OES_texture_float, [13]: GL_OES_texture_float_linear, [14]: GL_EXT_texture_rg, [15]: GL_EXT_texture_compression_dxt1, [16]: GL_ANGLE_texture_compression_dxt3, [17]: GL_ANGLE_texture_compression_dxt5, [18]: GL_OES_compressed_ETC1_RGB8_texture, [19]: GL_EXT_sRGB, [20]: GL_ANGLE_depth_texture, [21]: GL_OES_depth32, [22]: GL_EXT_texture_storage, [23]: GL_OES_texture_npot, [24]: GL_EXT_draw_buffers, [25]: GL_EXT_texture_filter_anisotropic, 
RDOC 002900: [16:19:50]        gl_common.cpp( 107) - Log     - [26]: GL_EXT_occlusion_query_boolean, [27]: GL_NV_fence, [28]: GL_EXT_disjoint_timer_query, [29]: GL_EXT_robustness, [30]: GL_EXT_blend_minmax, [31]: GL_ANGLE_framebuffer_blit, [32]: GL_ANGLE_framebuffer_multisample, [33]: GL_ANGLE_instanced_arrays, [34]: GL_ANGLE_pack_reverse_row_order, [35]: GL_OES_standard_derivatives, [36]: GL_EXT_shader_texture_lod, [37]: GL_EXT_frag_depth, [38]: GL_ANGLE_texture_usage, [39]: GL_ANGLE_translated_shader_source, [40]: GL_EXT_discard_framebuffer, [41]: GL_EXT_debug_marker, [42]: GL_OES_EGL_image, [43]: GL_EXT_unpack_subimage, [44]: GL_NV_pack_subimage, [45]: GL_EXT_color_buffer_float, [46]: GL_OES_vertex_array_object, [47]: GL_KHR_debug, [48]: GL_ANGLE_lossy_etc_decode, 
RDOC 002900: [16:19:50]        gl_common.cpp( 146) - Error   - RenderDoc requires these missing extensions: ARB_vertex_attrib_binding ARB_program_interface_query ARB_shading_language_420pack ARB_separate_shader_objects . Try updating your drivers.
RDOC 002900: [16:19:50] replay_controller.cpp(1927) - Error   - Couldn't create a replay device :(.
RDOC 002900: [16:19:50] replay_controller.cpp( 188) - Log     - Shutting down replay renderer

I can open the capture on Renderdoc 1.5 but i need it to work on 1.2 as that is the build that the blender plugin importer i am trying to use rely on. The capture was made using 1.2

 The thing is that a couple of months back it used to work very well so something must have changed in my system which made it stop. I ve been trying to figure it out but no luck....

If someone can give me a hint i would much appreciate it. Thank you

## Environment

* RenderDoc version: 1.2 64 Bit Portable
* Operating System: Window 10
* API: XXX

**Comment by baldurk** [comment]
If the bug has been fixed on a recent version then there's nothing more to do, I do not backport fixes to older versions nor spend time determining where a fix happened in history if the bug has been fixed.

Your issue also does not correctly follow the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md)  for any future issues. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

In addition I'm assuming you're referring to the blender plugin that is not authorised or endorsed and is used for illegal copyright infringement. No support whatsoever is provided for using RenderDoc for such purposes, any issues filed about such uses will be immediately closed.
