### ISSUE TITLE
Depth test overlay misleadingly shows red/green even if test is disabled

### ISSUE THREAD

**Issue by inequation** [baldurk/renderdoc#159]
As explained in the Twitter thread here: https://twitter.com/TheIneQuation/status/652127105732489216

![depthtest](https://cloud.githubusercontent.com/assets/320285/10369300/c8e8534a-6dd9-11e5-9ef0-ebe06b70a5cf.jpg)

Log sent privately.

**Comment by baldurk** [comment]
Just closing this directly since we already followed up off-bug to find the issue in the first place.
