### ISSUE TITLE
D3D texture sharing support across devices

### ISSUE THREAD

**Issue by zowua** [baldurk/renderdoc#1595]
## Description
Renderdoc v1.5 does not support launching apps that use some variant of texture sharing across different d3d devices. For example, app that calls [ID3D11Device1::OpenSharedResource1](https://docs.microsoft.com/en-us/windows/win32/api/d3d11_1/nf-d3d11_1-id3d11device1-opensharedresource1) will encountrer "Unimplemented" renderdoc warning and crash due to unwrap resources not wrapped. 

A typical error message when such app is launched with renderdoc. 
> Core     PID   7824: [19:06:05]    target_control.cpp(802) - Log     - Used API: D3D12 (Not presenting & supported)
Core     PID  24288: [19:06:05] d3d11_device1_wrap.cpp(325) - Warning - Unimplemented: Not wrapping OpenSharedResource1
Core     PID  24288: [19:06:05] d3d11_device1_wrap.cpp(325) - Warning - Unimplemented: Not wrapping OpenSharedResource1
Core     PID  24288: [19:06:05]      d3d11_manager.cpp(48) - Error   - UnwrapResource(): Unexpected non-wrapped resource
Core     PID  24288: [19:06:05]   d3d11_resources.cpp(370) - Error   - Unknown type for ptr 0x000001E7938939B8
Core     PID  24288: [19:06:05]   d3d11_resources.cpp(370) - Error   - Unknown type for ptr 0x000001E7938939B8
Core     PID  24288: [19:06:05] d3d11_context_wrap.cpp(5641) - Error   - Assertion failed: 'srcRecord' 

## Steps to reproduce

I've created a standalone D3D console app [SharedTextureArray](https://github.com/zowua/SharedTextureArray) with different flavors of texture sharing cases that are used in my production code.  The app doesn't have a swapchain and thus relies on the Renderdoc API to scope present boundaries. 

Steps:
1) Please compile the app with VS2019. 
2) Run the app first without going though renderdoc (on Nvidia graphics card). 
You are expected to see all test cases passing with 'succeeded!' in the console. 
3) Run the app launched through RenderDoc v1.5 with default settings. 

- OpenSharedResource1 failure
You are expected to see the app getting stuck in [TryIntermediateTextureCopyFromD3D12ToD3D11](https://github.com/zowua/SharedTextureArray/blob/master/SharedTextureArray.cpp#L646), in which OpenSharedResource1 is called. 

- OpenSharedHandle on fence failure
You can selectively uncomment TryIntermediateTextureCopyFromD3D12ToD3D11 to let the app proceed to different test cases. In [TryShareD3D11FenceToD3D12](https://github.com/zowua/SharedTextureArray/blob/master/SharedTextureArray.cpp#L665), a fence is created in D3D11 device and to be opened in D3D12 device through [ID3D12Device::OpenSharedHandle](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-opensharedhandle). This is also an unimplemented case. 

- Implicitly sharing textures between different D3D12 devices without calling any sharing API
You can comment out other test cases, leaving only [TryD3D12ImplicitResourceSharing](https://github.com/zowua/SharedTextureArray/blob/master/SharedTextureArray.cpp#L676)
In this case, the app creates 2 unique d3d12 devices, with the second device placing barriers on the texture created by the first device. When launched though Renderdoc, the app will crash in [D3D12ResourceManager::ApplyBarriers](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/d3d12/d3d12_manager.cpp#L680). Renderdoc only reference resources explicitly without crossing the device boundary; thus in this case m_resourcesStates of the second device cannot find the resource though it's Id, causing the crash. 

4) I also notice [WrappedID3D12Device::QueryInterface](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/d3d12/d3d12_device.cpp#L620) is missing the case of querying ID3D12Device interface. If a wrapped D3D12 device is first cast to IUnknown and then QueryInterface to back to ID3D12Device, it will return not the wrapped one, but the raw one. See [TryIUnknownCasting](https://github.com/zowua/SharedTextureArray/blob/master/SharedTextureArray.cpp#L670) test case in the same app. 

5) Note that the app is by default running with macro [RDOC_CAPTURE_DX11](https://github.com/zowua/SharedTextureArray/blob/master/SharedTextureArray.cpp#L26), which captures the command through d3d11 device. Please also enable RDOC_CAPTURE_DX12 and disable RDOC_CAPTURE_DX11 to capture dx12 commads in the UI to see if it also works. Note if I enable both to generate 2 captures at the same time, the d3d12 capture doesn't contain valid commands, which appears to be a bug. 

## Environment

* RenderDoc version: 1.5
* Operating System: Windows 10 1903
* API: Direct3D 11, Direct3D 12

* GPU: NVIDIA GTX 1070
* Driver: 26.21.14.3200 (WDDM 2.6)

**Comment by baldurk** [comment]
First, thank you for the extremely thorough bug report, this makes it very easy to see the problem and understand what needs to happen.

I believe the `TryD3D12ImplicitResourceSharing` test is invalid, it is not legal to share resources between devices like this. It seems to work when the devices are from the same adapter, but it crashes with a D3D12 debug message if the devices come from different adapters. I believe the only way to share between devices is with explicit DXGI sharing.

I also found that one of the tests failed on AMD, though all passed on nvidia. Is that expected?

I'll update this bug as I fix issues, some of them will be quicker to fix than others.

**Comment by zowua** [comment]
Thank your for your prompt reply!  

For implicit resource sharing on the same adapter, I don't think there's official documentation on this behavior. But this behavior doesn't seem to have been changed for quite a while. I found a [post](https://www.gamedev.net/forums/topic/692925-difference-between-texture-sharing-across-devices-and-adapters/) from 2 years ago that showed it was working at that time. I guess it's reasonable to think it won't be changed in the future for back-compat reasons. Also, given Renderdoc doesn't support capture across adapters (and we have to choose which adapter to capture from), you can assume all D3D12 devices are from the same adapter, with their resources implicitly shareable. 

Yes, I have also seen the AMD quirk with texture array sharing; it appears to be a driver bug.

**Comment by baldurk** [comment]
This actually came up coincidentally in a different bug report, and I got some clarification from the MS folks which is now properly [on MSDN](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-d3d12createdevice) - when calling D3D12CreateDevice twice in a single process for the same adapter it is guaranteed that you will get **the same device pointer back, with an additional reference count**.

So it's still invalid to share resources between different device pointers as I thought (e.g. on D3D11 where this guarantee isn't present and you'll get different device pointers for the same adapter), but what RenderDoc was missing was handling this kind of singleton behaviour and it wrongly returned separate devices for the same adapter. What you actually end up with on the same adapter is a single device pointer - it's not even sharing at that point, it's just creating multiple resources on the same device.

**Comment by baldurk** [comment]
OK I believe those commits should address all the issues shown in your repro project. At least I can capture from both APIs simultaneously, everything is a success and the capture looks plausible - though I'm not 100% sure what it should look like so if there's something missing I won't have seen that.

I've closed this for now but if you find more issues or if something still isn't working quite right, comment here and I can re-open and investigate further.

**Comment by zowua** [comment]
Thank you so much for addressing these bugs so quickly! 
I've just tested our real app that hits all the bugs in my repro app and now with the latest build all issues are gone. I'll let you know when I hit other corner cases.

**Comment by baldurk** [comment]
No problem, it was only possible to fix them so quickly because you had an excellent repro program. Thanks again for such a good bug report!
