### ISSUE TITLE
Failed to capture the first Frame with Renderdoc on Android Q

### ISSUE THREAD

**Issue by seag-code** [baldurk/renderdoc#1596]
## Description
Sometimes, when the the first frame is very fast to perform, Renderdoc will miss it, and failed to capture the first frame. 
I have checked the Queue Capture checkbox with parameters "Frame0 #Frames 1", it seems failed to capture the first frame only with the newest Renderdoc on Android Q, while this problem was not appreared on Android P.
## Steps to reproduce
1. prepared an Android Q phone
2. in order to simulate the very fast first frame, i put a breakpoint at target_control.cpp line 599 
` 
 597 void QueueCapture(uint32_t frameNumber, uint32_t numFrames)
 598  {
 599   WRITE_DATA_SCOPE();
 600   SCOPED_SERIALISE_CHUNK(ePacket_QueueCapture);
 601
 602   SERIALISE_ELEMENT(frameNumber);
 603   SERIALISE_ELEMENT(numFrames);
 604
 605   if(ser.IsErrored())
 606     SAFE_DELETE(m_Socket);
 607  }
`
3. launch application
4. wait for a few seconds
5. press F5 to continue
6. the first frame will missed 

## Environment
RenderDoc version: v1.x branch @ 2b7753a, 2019-11-06
Operating System: win10 x64
API: OpenGL ES
Android device: huawei mate30
Android version: 10.0

**Comment by seag-code** [comment]
please help with this issue , thanks!

**Comment by baldurk** [comment]
This is most likely caused by the new hooking method in Android 10, and though I'll check in with Google about it I don't think it's fixable. The problem is that the renderdoc library isn't loaded until a GL context or Vulkan instance is created, and that leaves a very small window to trigger the first frame capture.

I would suggest instead you use the [in-application API](https://renderdoc.org/docs/in_application_api.html) to begin a capture after creating the device, and end it whenever you wish, e.g. at the first present call which is the default behaviour for capturing frame 0. That will work correctly, though you will have to be sure to only load the API after creating a GL context or Vulkan instance, to be sure that the renderdoc library is loaded.

**Comment by seag-code** [comment]
Hi baldurk
I have a workaround solution and it seems work well. Could you please help check  if it is acceptable? 

I will not pass the data through the socket connection.
There is an environment variable "RENDERDOC_CAPOPTS", 
in posix_libentry.cpp : 
const char *opts = Process::GetEnvVariable("RENDERDOC_CAPOPTS");
I can get config from this environment variable.

Below is the detail，all my modifications aremarked with "ADD by ### ### seag-code":
1. in capture_options.cpp, add three variables which represent the state of queue capture checkbox, and queuedFrame and numFrames. Of course, the corresponding .h file should also be modified.
@capture_options.cpp 
CaptureOptions::CaptureOptions()
{
  allowVSync = true;
  ......
  ......
  debugOutputMute = true;
  **// ADD by seag-code begin
  queueFrameCap = false;
  queuedFrame = 0;
  numFrames = 1;
  // ADD by seag-code end**
}

2. get the ui parameters
@seag-code CaptureDialog.cpp：
CaptureSettings CaptureDialog::Settings()
{
  ......
  ......
  ret.options.delayForDebugger = (uint32_t)ui->DelayForDebugger->value();
  ret.options.verifyBufferAccess = ui->VerifyBufferAccess->isChecked();
  **// ADD by seag-code begin**
  **ret.options.queueFrameCap = ui->queueFrameCap->isChecked();**
  **// ADD by seag-code end**
  if(ui->queueFrameCap->isChecked())
  {
    **// ADD by seag-code begin
    ret.options.queuedFrame = (uint32_t)ui->queuedFrame->value();
    ret.options.numFrames = (uint32_t)ui->numFrames->value();
    // ADD by seag-code end**
    ret.queuedFrameCap = (uint32_t)ui->queuedFrame->value();
    ret.numQueuedFrames = (uint32_t)ui->numFrames->value();
  }
  return ret;
}

3. Then the options can be obtained when library_loaded and set to RenderDoc::m_Options
// DllMain equivalent
void library_loaded()
{
  ......
    RenderDoc::Inst().Initialise();
    const char *capturefile = Process::GetEnvVariable("RENDERDOC_CAPFILE");
    const char *opts = Process::GetEnvVariable("RENDERDOC_CAPOPTS");
    if(opts)
    {
      CaptureOptions optstruct;
      optstruct.DecodeFromString(opts);
      RDCLOG("Using delay for debugger %u", optstruct.delayForDebugger);
      RenderDoc::Inst().SetCaptureOptions(optstruct);
    }
    ......
}

4.  then I can decided to trigger capture or not by checking the state of queueFrameCap in core.cpp
void RenderDoc::SetCaptureOptions(const CaptureOptions &opts)
{
  m_Options = opts;
  **// ADD by seag-code begin
  if(m_Options.queueFrameCap) {
    RenderDoc::Inst().QueueCapture(m_Options.queuedFrame);
    RenderDoc::Inst().TriggerCapture(m_Options.numFrames);
  }
  // ADD by seag-code end**
  LibraryHooks::OptionsUpdated();
}

Thanks

**Comment by baldurk** [comment]
You can make that change locally if you want but I don't want to change that upstream. The `Process::GetEnvVariable` implementation on android uses a really buggy and unreliable mechanism of passing data so I don't want to use it any more than I have to, and I don't want to duplicate codepaths and have multiple ways of doing the same thing.

Using the renderdoc API to start the capture from your own code will be much more reliable so I strongly recommend you do that instead.

**Comment by seag-code** [comment]
Understand,  thanks for the explanation. 
And if you get any feedback from google please let me know. Thanks~

**Comment by baldurk** [comment]
It doesn't look like this will change or there's any other workaround on Android 10. The library will get loaded either at `vkCreateInstance` time, or when first calling an egl function e.g. `eglGetDisplay` or `eglGetProcAddress`. The UI needs to connect and send the queued frame capture command between this time and the time of `vkCreateDevice` / `eglCreateContext`, which doesn't leave much time compared to most platforms or before Android 10 when the socket would be listening immediately on process startup.

As above, I strongly recommend that you use the in-application API to start the capture yourself after create time and then end it once it has captured all the initialisation you want. This will be more reliable and precise than using the queued frame capture and will work on all versions of Android, the API is not difficult to use.

In a future android version it may be possible that the layer can get loaded earlier at process startup time, similar to how it was injected before Android 10, but I don't know if that will happen.
