### ISSUE TITLE
Pixel shader debugger shows invalid input data (coming from vertex shader)

### ISSUE THREAD

**Issue by TaaTT4** [baldurk/renderdoc#1598]
## Description

When you try to debug a pixel shader, it seems that the data coming from vertex shader contains invalid values. Eg, in my scenario, texture coordinates have always `0.0; 0.0` value no matter what pixel I try to debug. I'm pretty sure that this issue is related to shader debugging only because vertex shader outputs correct values and I don't see any visual artifact.

## Steps to reproduce

- Open the RenderDoc capture at the following URL: [https://drive.google.com/open?id=1XvKIfewGlvUyy1582uSok_q-_r3h6ToN](https://drive.google.com/open?id=1XvKIfewGlvUyy1582uSok_q-_r3h6ToN)
- Debug pixel 60; 500 at EID call 449 and inspect value of `inPs.uv0`
- Do the same at pixel 1200; 450
- `inPs.uv0` should have different values

![Annotazione 01](https://user-images.githubusercontent.com/7291478/68953226-c72e3c00-07c1-11ea-8d69-8d497c76666d.png)
![Annotazione 02](https://user-images.githubusercontent.com/7291478/68953227-c7c6d280-07c1-11ea-881b-af46cd4e642b.png)

As you can see below, vertex shader outputs correct data. If `inPs.uv0` was equal to `0.0; 0.0`, I wouldn't see the terrain textures sampled correctly.
![Annotazione 03](https://user-images.githubusercontent.com/7291478/68953536-67846080-07c2-11ea-92d7-152bd43dda43.png)
![Annotazione 04](https://user-images.githubusercontent.com/7291478/68953616-8daa0080-07c2-11ea-9290-7d4894e0cc37.png)

## Environment

* RenderDoc version: 1.5 (issue happens in nightly build 2019-11-14 too)
* Operating System: Windows 10, version 18362.449
* API: D3D11 (custom engine based on [OGRE 2.2](https://github.com/OGRECave/ogre-next))
* GPU: NVIDIA GeForce GTX 1060, driver version 441.20

**Comment by baldurk** [comment]
More than only the UVs were wrong here. For the pixel shader debugging I need to exactly match the HLSL definition that produces the input register mapping of the original shader. Unfortunately with FXC trying to reverse engineer the exact behaviour to ensure the same packing/arrangement is not easy. This was a case where a uint followed by a float was detected wrongly as the float being an array, which messed up all the packing after there.
