### ISSUE TITLE
when format is GL_LUMINANCE_ALPHA， allocate the R8 texture？

### ISSUE THREAD

**Issue by z00318884** [baldurk/renderdoc#1599]
## Description

Hi，baldurk，

in file gl_emulated.cpp，the function _glGetTexImage，when texture format is GL_LUMINANCE_ALPHA， you also allocate a R8 texture.

source code is:
     // allocate the R8 texture
     GL.glTexParameteri(target, eGL_TEXTURE_MAX_LEVEL, 0);
    GL.glTexImage2D(target, 0, eGL_R8, width, height, 0, remapformat, eGL_UNSIGNED_BYTE, NULL);
-------->
Need to be modified to the following code?

 if(format == eGL_LUMINANCE_ALPHA){
   GL.glTexImage2D(target, 0, eGL_RG8, width, height, 0, remapformat, eGL_UNSIGNED_BYTE, NULL);
 }
 else{
   GL.glTexImage2D(target, 0, eGL_R8, width, height, 0, remapformat, eGL_UNSIGNED_BYTE, NULL);
 }

## Environment

* RenderDoc version: 1.5
* Operating System: android
* API: gles

**Comment by baldurk** [comment]
That commit should set the internal format to `GL_RG8` when reading back a `GL_LUMINANCE_ALPHA` texture.
