### ISSUE TITLE
Texture Views dont work with MultiBind (or any bind) as well as Uniform Structs

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [baldurk/renderdoc#1606]
## Description

RenderDoc is unable to capture and properly replay a working simple OpenGL 4.5 core profile application.

Application uses a compute shader with image views (rgba8 views of srgb8_alpha8 textures) to read from a texture and then invert its colours.

A blit of the output texture to the screen is performed so that the output can be seen on screen.

While capturing/stand alone execution the correct image (yellow square on a white screen) can be seen.

[imageViewsAndStructs.zip](https://github.com/baldurk/renderdoc/files/3870472/imageViewsAndStructs.zip)

When replaying I can see that the PIpeline inspector shows (mistakenly) that the Compute Shader Storage Images are not bound.

Finally the values of my uniform struct are 0s despite calling the correct `glProgramUniform` function at the correct location (this works, otherwise standalone execution/while capturing would have not worked).

## Steps to reproduce

Git clone the source of the engine and example
https://github.com/buildaworldnet/IrrlichtBAW/tree/i_broke_renderdoc_0
Make sure to git submodule recursive init

CMake will generate one Visual Studio solution per example, you want example 02

Alternatively just make an application that executes the series of OpenGL calls in the capture with identical data.

## Environment

* RenderDoc version: 1.5 Latest
* Operating System: Windows 10
* API: OpenGL 4.6 Nvidia 1050

**Comment by devshgraphicsprogramming** [comment]
Sorry it seems that multibind does finally work, but the uniform value passing is the problem.

**Comment by devshgraphicsprogramming** [comment]
Additional info 
> if you don't put the location = 0 in the GLSL shader source NVidia will tell you u_pushConstants.imgSize has location 2

Maybe your location counting in the RenderDoc OpenGL layer is a bit off?

**Comment by baldurk** [comment]
I don't have time to build the repro project right now, I can look into that tomorrow and investigate properly. From a quick initial look I have a hunch what the problem is - does it work if you capture a later frame? In particular if the program you're using is created _before_ the capture starts, and not mid-way through the capture.

EDIT: If I'm right then I think it'd also work if you replaced the call to `glCreateShaderProgramv` with a more verbose `glCreateProgram`, attach shader, `glLinkProgram`.

**Comment by devshgraphicsprogramming** [comment]
Yes it works on the second frame.

**Comment by baldurk** [comment]
That commit should fix the problem. When a program is created mid-capture I need to prepare a uniform remapping table, and while I was doing that for `glLinkProgram` I forgot to do it for `glCreateShaderProgramv`.
