### ISSUE TITLE
Cannot create Replay, Error - libEGL not available

### ISSUE THREAD

**Issue by faxlab** [baldurk/renderdoc#1610]
Description:

```
Hi. I am trying to capture 3d data, however when I try to open capture, I am receiving following error:
https://i.imgur.com/ZT4LVWn.png
```
Capture and log:

`https://drive.google.com/file/d/1DFqakyw3E-qm47TjHbTC-ElK7awpsonm/view?usp=sharing`

Steps to reproduce:

`Take snapshot, open snapshot`

Environment:
```
RenderDoc version: 1.5/1.1/1.2

- Operating System: WIN10 x64 LTSC
- API: OpenGLES
- Hardware: Ryzen 2700x / AMD RX480 Gpu /

Error occurs with the newest AMD driver and with 18.10
```

**Comment by baldurk** [comment]
You have not followed the issue template and you filed an issue only a few hours ago where you were told that you will receive absolutely no support for illegal copyright infringing use of RenderDoc.

Do not open any more issues, you will not get any assistance here.

**Comment by faxlab** [comment]
However I am not doing this for profit, but ok

**Comment by zao** [comment]
@faxcorp Regardless of legality and compensation, troubleshooting the capture process when the application is not under your control tends to incur a large drain of time and energy which can be better spent on supporting users with problems that are in scope.

In particular, wild applications tend to have some amount of broken behaviour and legacy API use, while RenderDoc presumes some will and ability of the user to make their application behave under instrumentation.
