### ISSUE TITLE
GL_PIXEL_UNPACK_BUFFER causes RenderDoc's overlay UI to be a black box

### ISSUE THREAD

**Issue by LukasBanana** [baldurk/renderdoc#1614]
## Description

If the application does not unbind `GL_PIXEL_UNPACK_BUFFER`, RenderDoc draws the UI (including API information and FPS counter) with a solid black box.

Recording a capture via `Queue Capture` works just fine, but recording a capture at runtime using the F12 or PrintScreen key results in corrupted output (which might be due to the application, but at least the UI should be drawn correctly).

## Steps to reproduce

I attached a ZIP file including the RenderDoc trace as well as the Windows executable and GLSL shader:
[PixelUnpackBuffer.zip](https://github.com/baldurk/renderdoc/files/3889843/PixelUnpackBuffer.zip)

## Environment

* RenderDoc version: 1.5 (built from a94f238e)
* Operating System: Windows 10
* API: OpenGL

**Comment by baldurk** [comment]
Thank you for the clear repro, indeed there were some cases causing both problems that were not properly temporarily removing the pixel unpack buffer. Pixel pack/unpack is a really nasty gotcha in the API :(.

**Comment by LukasBanana** [comment]
Totally agree, also the entire pixel store configuration cost me a lot of time when I started learning OpenGL a decade ago.
