### ISSUE TITLE
when building android version with arm64-v8a, get error.

### ISSUE THREAD

**Issue by coudyyuan** [baldurk/renderdoc#1616]
## Description

when I want to build arm64 version of renderdoc
$ cmake -DBUILD_ANDROID=On -DANDROID_ABI=arm64-v8a ..
output:
-- Using JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64
-- Using Android SDK found in ~/android-sdk
-- Using Android NDK found in ~/android-sdk/android-ndk-r14b
-- Calculating version
-- Building RenderDoc version 1.6
-- Disabling qrenderdoc for android build
-- Disabling renderdoc python modules for android build
-- Using Android ABI arm64-v8a
-- Using Android native API level 21
-- Interceptor-lib not enabled (USE_INTERCEPTOR_LIB) - android hooking will use sometimes less reliable PLT-interception method. 
-- Using Android build-tools version 26.0.1
-- Using android.jar from platform android-23
-- Building APK versionCode 16, versionName 86c2352a375e915c26651e3ae904ce718b1fa3de
-- Enabled APIs:
--   - OpenGL ES (EGL)
--   - Vulkan
-- Configuring done
-- Generating done
-- Build files have been written to: /home/coudy/SG/renderdoc/build-android-arm64

but when make, I get error.
$make -j48
[ 87%] Linking CXX shared library ../lib/libVkLayer_GLES_RenderDoc.so
/usr/bin/ld: unrecognised emulation mode: aarch64linux
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
renderdoc/CMakeFiles/renderdoc.dir/build.make:1467: recipe for target 'lib/libVkLayer_GLES_RenderDoc.so' failed
make[2]: *** [lib/libVkLayer_GLES_RenderDoc.so] Error 1
CMakeFiles/Makefile2:223: recipe for target 'renderdoc/CMakeFiles/renderdoc.dir/all' failed
make[1]: *** [renderdoc/CMakeFiles/renderdoc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

## Environment

* RenderDoc version: 1.x
* Operating System: ubuntu 18.04
* API: XXX

**Comment by baldurk** [comment]
This looks like a misconfiguration in your android build environment, as `/usr/bin/ld` should not be getting run to link for android, but instead the build should be using the linker from the NDK. Searching for google shows that this error has been encountered in many other cases and one suggestion is to check that your extracted NDK has proper execute permissions.

I can't provide support for general Android issues that are not RenderDoc specific, so closing this issue.

**Comment by junjiehuang** [comment]
hey guys, i want to compile renderdoc for android in win10. when i exec this commands to generate project, there was something error like that:
 
![image](https://user-images.githubusercontent.com/7741773/85291447-14e3f300-b4cd-11ea-9e7e-07c567b54198.png)  

how can i fix this problem?thks!

**Comment by baldurk** [comment]
Please do not comment on old closed and unrelated issues with problems. If you have a problem open a new issue.

Compiling for android using visual studio is not supported, please follow the instructions for building on android as that is the only supported way to build the project.
