### ISSUE TITLE
Replay issue reading a RW texture

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#1619]
## Description

I have a capture where the reading of a RW texture whose format is R32_UINT incorrectly returns 0.

## Steps to reproduce

Load the capture, inspect a certain thread for a certain compute shader, observe the load fail, even after inspecting the texture and making sure it's not 0. I can send you the capture for inspection and details on an email.

Update: If I treat them as read-only then I can make it work, but subsequently another RW R32G32_UINT texture I'm using manifests the same behavior. It doesn't return 0, but seems to be returning an entry that is incorrect for the integer coordinate I'm passing in.

## Environment

* RenderDoc version: 1.6 2019-11-26 (latest nightly as of bug report date)
* Operating System: Windows 10
* API: D3D11

I have tried the latest nightly because it was failing in a previous nightly.

**Comment by baldurk** [comment]
Just to let you know your email with the repro hasn't come through. I checked my junk folder just in case (though I rarely get false positives there) and it's not there either.

**Comment by redorav** [comment]
Sorry, that was my bad, I didn't actually send it. It should be in your inbox now.

**Comment by baldurk** [comment]
There was a swizzle not being applied, which meant the data ended up in the wrong component and didn't get through. That commit should fix the problem.

**Comment by redorav** [comment]
That's great, thanks a lot for the quick turnaround
