### ISSUE TITLE
Ikarus antivirus detects this as a Trojan.Win64.CoinMiner

### ISSUE THREAD

**Issue by Jacob-Tate** [baldurk/renderdoc#1620]
## Description
Your `RenderDoc_1.5_64.msi` file is being detected by the ikarus antivirus as a Trojan.Win64.CoinMiner according the virus totals website. The msi is downloaded from https://renderdoc.org/builds with the SHA-256 hash of `d37cbb9ffa17ca0fbbc6463be6a31257c086b99d952f0fd0ff3435a035ec8013`

This is most likely a false positive and I have contacted the company in regards to the detection but someone on the team may also want to take a look to ensure this is a false positive!

## Steps to reproduce

https://www.virustotal.com/gui/file/d37cbb9ffa17ca0fbbc6463be6a31257c086b99d952f0fd0ff3435a035ec8013/details

**Comment by baldurk** [comment]
Most/all anti-virus programs are complete snake oil and have false positives regularly. Especially when there's only one mostly-unknown program complaining it's pretty much guaranteed.

The SHA-256 does match the file I have, and all builds are signed using my public key with PGP and on windows they are code-signed by a verified CA so you can be sure of file integrity that way.
