### ISSUE TITLE
RenderDoc hangs when loading Vulkan captures on Intel

### ISSUE THREAD

**Issue by akb825** [baldurk/renderdoc#1625]
## Description

When running RenderDoc to capture Vulkan on a laptop running Linux and an Intel GPU, it hangs when attempting to load the capture.

## Steps to reproduce

1. Load a Vulkan application. In my case, I am using my testers from my project here: https://github.com/akb825/DeepSea The simplest tester you can run from that project is deepsea_test_cube_app. (after building, run <build directory>/output/deepsea_test_cube_app)
2. Capture a frame.
3. Either double-click the capture to open it or close the app to have it automatically open the capture.
4. The "Please Wait" dialog for loading the capture hangs indefinitely at ~75%.

## Environment

* RenderDoc version: 1.5
* Operating System: Arch Linux
* API: Vulkan
* GPU: Intel UHD Graphics 630
* Driver version: Mesa 19.2.6

## RenderDoc log

Log     - QRenderDoc initialising.
Log     - Initialising adb using '/usr/bin/adb'
Log     - Created device.
Log     - Got remote handshake: deepsea_test_cube_app [8136]
info: [TestCube] Render using Vulkan
info: [TestCube] Press '1' to toggle anti-aliasing.
info: [TestCube] Press '2' to toggle vsync.
info: [TestCube] Press '3' to toggle anisotropic filtering.
debug: [vulkan] Using device: Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)
Log     - Used API: Vulkan (Not presenting & supported)
Log     - Used API: Vulkan (Presenting & supported)
Log     - Got a new capture: 0 (frame 126) (time 1575172041) 96905 byte thumbnail
Log     - Opening RDCFile /tmp/RenderDoc/deepsea_test_cube_app_2019.12.01_03.47.16_frame126.rdc
Log     - Opening RDCFile /tmp/RenderDoc/deepsea_test_cube_app_2019.12.01_03.47.16_frame126.rdc
Log     - Not enabling API validation during replay
Log     - Using default GPU replay selection algorithm
Log     - Replay optimisation level: Balanced
Log     - AMD RGP Interop is not enabled
Log     - Inst Ext 0: VK_EXT_acquire_xlib_display
Log     - Inst Ext 1: VK_EXT_debug_report
Log     - Inst Ext 2: VK_EXT_debug_utils
Log     - Inst Ext 3: VK_EXT_direct_mode_display
Log     - Inst Ext 4: VK_EXT_display_surface_counter
Log     - Inst Ext 5: VK_KHR_device_group_creation
Log     - Inst Ext 6: VK_KHR_display
Log     - Inst Ext 7: VK_KHR_external_fence_capabilities
Log     - Inst Ext 8: VK_KHR_external_memory_capabilities
Log     - Inst Ext 9: VK_KHR_external_semaphore_capabilities
Log     - Inst Ext 10: VK_KHR_get_display_properties2
Log     - Inst Ext 11: VK_KHR_get_physical_device_properties2
Log     - Inst Ext 12: VK_KHR_get_surface_capabilities2
Log     - Inst Ext 13: VK_KHR_surface
Log     - Inst Ext 14: VK_KHR_surface_protected_capabilities
Log     - Inst Ext 15: VK_KHR_wayland_surface
Log     - Inst Ext 16: VK_KHR_xcb_surface
Log     - Inst Ext 17: VK_KHR_xlib_surface
Log     - Enabling VK_EXT_debug_report
Log     - Created device.
Log     - Created replay driver.
Log     - Replay has physical device 0 available:
Log     -    - Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) (ver 19.2 patch 0x6) - 8086:3e9b
Log     -    - VK_DRIVER_ID_INTEL_OPEN_SOURCE_MESA_KHR driver: Intel open-source Mesa driver (Mesa 19.2.6) - CTS 1.1.2.0
Log     - Replay has physical device 1 available:
Log     -    - Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) (ver 19.2 patch 0x6) - 8086:3e9b
Log     -    - VK_DRIVER_ID_INTEL_OPEN_SOURCE_MESA_KHR driver: Intel open-source Mesa driver (Mesa 19.2.6) - CTS 1.1.2.0
Log     - Found capture physical device 0:
Log     -    - Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) (ver 19.2 patch 0x6) - 8086:3e9b
Log     -    - VK_DRIVER_ID_INTEL_OPEN_SOURCE_MESA_KHR driver: Intel open-source Mesa driver (Mesa 19.2.6) - CTS 1.1.2.0
Log     - Mapping during replay to best-match physical device 0
Log     - Found capture physical device 1:
Log     -    - Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) (ver 19.2 patch 0x6) - 8086:3e9b
Log     -    - VK_DRIVER_ID_INTEL_OPEN_SOURCE_MESA_KHR driver: Intel open-source Mesa driver (Mesa 19.2.6) - CTS 1.1.2.0
Log     - Mapping during replay to best-match physical device 1
Log     - Enabling VK_KHR_driver_properties
Log     - Enabling VK_KHR_pipeline_executable_properties
Log     - Enabling VK_EXT_transform_feedback extension
Log     - Enabling VK_EXT_buffer_device_address
Log     - Capture describes queue family 0:
Log     -    - 1 queues available with VK_QUEUE_GRAPHICS_BIT | VK_QUEUE_COMPUTE_BIT | VK_QUEUE_TRANSFER_BIT
Log     -      36 timestamp bits (1,1,1) granularity
Log     - Remapping to queue family 0:
Log     -    - 1 queues available with VK_QUEUE_GRAPHICS_BIT | VK_QUEUE_COMPUTE_BIT | VK_QUEUE_TRANSFER_BIT
Log     -      36 timestamp bits (1,1,1) granularity
Warning - shaderStorageImageMultisample = false, accurately replaying 2DMS textures will not be possible
Log     - Dev Ext 0: VK_KHR_8bit_storage (1)
Log     - Dev Ext 1: VK_KHR_16bit_storage (1)
Log     - Dev Ext 2: VK_KHR_bind_memory2 (1)
Log     - Dev Ext 3: VK_KHR_create_renderpass2 (1)
Log     - Dev Ext 4: VK_KHR_dedicated_allocation (1)
Log     - Dev Ext 5: VK_KHR_depth_stencil_resolve (1)
Log     - Dev Ext 6: VK_KHR_descriptor_update_template (1)
Log     - Dev Ext 7: VK_KHR_device_group (1)
Log     - Dev Ext 8: VK_KHR_draw_indirect_count (1)
Log     - Dev Ext 9: VK_KHR_driver_properties (1)
Log     - Dev Ext 10: VK_KHR_external_fence (1)
Log     - Dev Ext 11: VK_KHR_external_fence_fd (1)
Log     - Dev Ext 12: VK_KHR_external_memory (1)
Log     - Dev Ext 13: VK_KHR_external_memory_fd (1)
Log     - Dev Ext 14: VK_KHR_external_semaphore (1)
Log     - Dev Ext 15: VK_KHR_external_semaphore_fd (1)
Log     - Dev Ext 16: VK_KHR_get_memory_requirements2 (1)
Log     - Dev Ext 17: VK_KHR_image_format_list (1)
Log     - Dev Ext 18: VK_KHR_imageless_framebuffer (1)
Log     - Dev Ext 19: VK_KHR_incremental_present (1)
Log     - Dev Ext 20: VK_KHR_maintenance1 (1)
Log     - Dev Ext 21: VK_KHR_maintenance2 (1)
Log     - Dev Ext 22: VK_KHR_maintenance3 (1)
Log     - Dev Ext 23: VK_KHR_multiview (1)
Log     - Dev Ext 24: VK_KHR_pipeline_executable_properties (1)
Log     - Dev Ext 25: VK_KHR_push_descriptor (1)
Log     - Dev Ext 26: VK_KHR_relaxed_block_layout (1)
Log     - Dev Ext 27: VK_KHR_sampler_mirror_clamp_to_edge (1)
Log     - Dev Ext 28: VK_KHR_sampler_ycbcr_conversion (1)
Log     - Dev Ext 29: VK_KHR_shader_atomic_int64 (1)
Log     - Dev Ext 30: VK_KHR_shader_draw_parameters (1)
Log     - Dev Ext 31: VK_KHR_shader_float16_int8 (1)
Log     - Dev Ext 32: VK_KHR_storage_buffer_storage_class (1)
Log     - Dev Ext 33: VK_KHR_swapchain (70)
Log     - Dev Ext 34: VK_KHR_uniform_buffer_standard_layout (1)
Log     - Dev Ext 35: VK_KHR_variable_pointers (1)
Log     - Dev Ext 36: VK_EXT_buffer_device_address (1)
Log     - Dev Ext 37: VK_EXT_calibrated_timestamps (1)
Log     - Dev Ext 38: VK_EXT_conditional_rendering (1)
Log     - Dev Ext 39: VK_EXT_depth_clip_enable (1)
Log     - Dev Ext 40: VK_EXT_descriptor_indexing (2)
Log     - Dev Ext 41: VK_EXT_display_control (1)
Log     - Dev Ext 42: VK_EXT_external_memory_dma_buf (1)
Log     - Dev Ext 43: VK_EXT_external_memory_host (1)
Log     - Dev Ext 44: VK_EXT_fragment_shader_interlock (1)
Log     - Dev Ext 45: VK_EXT_global_priority (1)
Log     - Dev Ext 46: VK_EXT_host_query_reset (1)
Log     - Dev Ext 47: VK_EXT_index_type_uint8 (1)
Log     - Dev Ext 48: VK_EXT_inline_uniform_block (1)
Log     - Dev Ext 49: VK_EXT_line_rasterization (1)
Log     - Dev Ext 50: VK_EXT_memory_budget (1)
Log     - Dev Ext 51: VK_EXT_pci_bus_info (2)
Log     - Dev Ext 52: VK_EXT_pipeline_creation_feedback (1)
Log     - Dev Ext 53: VK_EXT_post_depth_coverage (1)
Log     - Dev Ext 54: VK_EXT_sampler_filter_minmax (1)
Log     - Dev Ext 55: VK_EXT_scalar_block_layout (1)
Log     - Dev Ext 56: VK_EXT_separate_stencil_usage (1)
Log     - Dev Ext 57: VK_EXT_shader_demote_to_helper_invocation (1)
Log     - Dev Ext 58: VK_EXT_shader_stencil_export (1)
Log     - Dev Ext 59: VK_EXT_shader_viewport_index_layer (1)
Log     - Dev Ext 60: VK_EXT_subgroup_size_control (2)
Log     - Dev Ext 61: VK_EXT_texel_buffer_alignment (1)
Log     - Dev Ext 62: VK_EXT_transform_feedback (1)
Log     - Dev Ext 63: VK_EXT_vertex_attribute_divisor (3)
Log     - Dev Ext 64: VK_EXT_ycbcr_image_arrays (1)
Log     - Dev Ext 65: VK_GOOGLE_decorate_string (1)
Log     - Dev Ext 66: VK_GOOGLE_hlsl_functionality1 (1)
Log     - Dev Ext 67: VK_NV_compute_shader_derivatives (1)
Log     - Intel GPU detected - no counters available

**Comment by baldurk** [comment]
This was a bug on my side if memory allocations are created without aligned sizes, and I align them to a certain degree internally (e.g. in this case it was 552 bytes, rounded up to a multiple of 16). This would lead to a `vkCmdFillBuffer` call that pointed off the end of the buffer, which seemed to hang inside mesa.

That commit should prevent the bad behaviour.
