### ISSUE TITLE
Error launching for capture with a root device

### ISSUE THREAD

**Issue by JingChangzz** [baldurk/renderdoc#1626]
## Description

I want capture frame with a root device, and the target app is undebuggable.
But failed:
![企业微信截图_157528690622](https://user-images.githubusercontent.com/13314441/69957161-0340fb00-153d-11ea-9041-a7496568b8c0.png)

![企业微信截图_15752869409249](https://user-images.githubusercontent.com/13314441/69957171-089e4580-153d-11ea-8375-2ef0b2dccacf.png)

It seems that renderdoc injected failed

## Steps to reproduce

(1) connect a root device
(2) set the launch activity of a undebuggable game app
(3) click launch

## Environment

* RenderDoc version: 1.5
* Operating System: win10 64
* API: opengl es

**Comment by baldurk** [comment]
Capturing an undebuggable app on a rooted device does work for me. It may be something to do with your specific device - so you could test on a different device from a different manufacturer - but most likely this issue is specific to your app.

Can you please share an apk that reproduces the problem? It doesn't have to be your apk, but one that shows the problem for you.

**Comment by JingChangzz** [comment]
> Capturing an undebuggable app on a rooted device does work for me. It may be something to do with your specific device - so you could test on a different device from a different manufacturer - but most likely this issue is specific to your app.
> 
> Can you please share an apk that reproduces the problem? It doesn't have to be your apk, but one that shows the problem for you.

 You can download the apk from following url:
1、 https://wap.game.xiaomi.com/index.php?c=app&v=download&package=com.tencent.tmgp.pubgmhd&channel=meng_1449_1_android
2、 http://dlied4.myapp.com/myapp/1104466820/cos.release-40109/2017_com.tencent.tmgp.sgame_h600877_1.51.1.23_362bct.apk

I have tried these two apps on my rooted devices， and all failed.  
My phone:
 * Android 9
 * Xiao Mi 6

**Comment by baldurk** [comment]
Those apks are commercial products and I do not provide any support for capturing copyrighted games that you do not have the rights to. Can you please provide evidence that you work at the developer or or are otherwise authorised to be capturing those APKs?

**Comment by JingChangzz** [comment]
> Those apks are commercial products and I do not provide any support for capturing copyrighted games that you do not have the rights to. Can you please provide evidence that you work at the developer or or are otherwise authorised to be capturing those APKs?

I‘m sorry that I cannot provide. But I promiss I just want to study… 
And It‘’s ok to capture with the tool of GAPID from google
Thank you for your reply.

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by 111304037** [comment]
> > Capturing an undebuggable app on a rooted device does work for me. It may be something to do with your specific device - so you could test on a different device from a different manufacturer - but most likely this issue is specific to your app.
> > Can you please share an apk that reproduces the problem? It doesn't have to be your apk, but one that shows the problem for you.
> 
> You can download the apk from following url: 1、 https://wap.game.xiaomi.com/index.php?c=app&v=download&package=com.tencent.tmgp.pubgmhd&channel=meng_1449_1_android 2、 http://dlied4.myapp.com/myapp/1104466820/cos.release-40109/2017_com.tencent.tmgp.sgame_h600877_1.51.1.23_362bct.apk
> 
> I have tried these two apps on my rooted devices， and all failed. My phone:
> 
> * Android 9
> * Xiao Mi 6

好家伙，居然在这看到农药:D
