### ISSUE TITLE
uninitialized structure members in CheckFeatureSupport in DX12 with D3D12_FEATURE_D3D12_OPTIONS5

### ISSUE THREAD

**Issue by Atrix256** [baldurk/renderdoc#1627]
After loading the rederdoc DLL in a process and initializing it, this function returns a struct which is uninitialized except for the raytracing tier value.

I chatted with you on the games tech slack and you said that the struct wasn't passing back the other values from directX.

Thanks!

## Environment
Win10 1809
nvidia driver 441.41

* RenderDoc version: 1.5 (https://github.com/baldurk/renderdoc/commit/a94f238e37cfe2f142093eb8e5da7775abaa88c6)
* Operating System: windows 10
* API: 1.4.0

**Comment by baldurk** [comment]
This should have been fixed in d0c27b352f1f3ffad5b2e7b445246ff948c457bd.
