### ISSUE TITLE
Textures Viewer doesn't show all inputs

### ISSUE THREAD

**Issue by moradin** [baldurk/renderdoc#163]
I was searching for another bug but I haven't found anything for this although it sounds like a big missing thing for me. When I select a drawcall, I only see the shaders bound to the pixel/fragment shader in the input panel. I can't test it at the moment with vertex textures but I'm seeing this with tessellation shaders. Looking into TextureViewer.cs I see a few places the pixel and compute shaders mentioned specifically so I'm assuming vertex/tessellation textures would be missing. I'm not sure if I'm not completely off, I haven't spent that much time investigating this.

**Comment by baldurk** [comment]
Yes this was first raised in #147, only PS or CS inputs are shown at the moment. I need to tidy up how it works rather than copy-pasting the existing code for the other shader stages.

**Comment by baldurk** [comment]
This should be fixed now with some refactorings pushed up with the vulkan work.

**Comment by baldurk** [comment]
Closing as this was implemented for v0.27. Re-open if it's not properly resolved.
