### ISSUE TITLE
Support for VK_EXT_tooling_info

### ISSUE THREAD

**Issue by Tobski** [baldurk/renderdoc#1632]
## Description

The Vulkan specification recently added the VK_EXT_tooling_info extension which adds queries to Vulkan about the tools that are currently active on a system, allowing developers to find out more information about the system environment, potentially saving many headaches. It would be great if RenderDoc could add support for this extension to advertise its presence.

## Environment

* RenderDoc version: Latest
* Operating System: Any
* API: Vulkan

**Comment by baldurk** [comment]
Implemented in that commit, though I can't double check that it works with another tool present.
