### ISSUE TITLE
No remote access connection

### ISSUE THREAD

**Issue by pengfei666** [baldurk/renderdoc#1634]
## Description

when I use Renderdoc on mac, I got `no remote access connection` on my app. 

And I saw some error in the log.
<img width="635" alt="Screen Shot 2019-12-10 at 19 40 13" src="https://user-images.githubusercontent.com/25144819/70589651-18dda280-1b85-11ea-8e6c-a2cc7b47c3fc.png">

## Steps to reproduce

Just try to run my app via RenderDoc

## Environment

RenderDov version: v1.6 built from https://github.com/baldurk/renderdoc/commit/723c29341434060a38854a8b253703fecc121f4b

Operating System:
    Name: macOS 10.14.6 (build 18G103)
    Locale: en_US

CPU Information:
    Architecture: x64
    Cores count: 8

GPU #1 Information:
    Name: Intel HD Graphics 630
    Vendor id: 0x8086
    Product id: 0x591B
    Stepping: 4

GPU #2 Information:
    Name: Radeon Pro 560
    Vendor id: 0x1002
    Product id: 0x67EF
    Stepping: 192

Machine:
    Name: PLi
    Memory: 16384 MB
    Screen: 3360x2100, Retina, 24 bit

**Comment by pengfei666** [comment]
The error is reported at here https://github.com/baldurk/renderdoc/blob/6d1d30249136e13f742f03c32ef18e09647be116/renderdoc/os/posix/apple/apple_process.cpp#L134

**Comment by baldurk** [comment]
mac is not a currently supported platform, nightly builds are only provided as a convenience to RenderDoc developers. Any contributions to fix bugs or improve features are welcome but I will not be actively fixing issues on it.
