### ISSUE TITLE
Can't open any captures 

### ISSUE THREAD

**Issue by Okluckej** [baldurk/renderdoc#1644]
## Description

Unable to open any capture due to 

![Error](https://user-images.githubusercontent.com/31667453/70997016-5b970180-20d4-11ea-8f6b-24343e449819.PNG)

## Steps to reproduce

1. Install provided Build.apk
2. Take capute (Default settings)
3. Open capture

[ReproHonorV9Play.zip](https://github.com/baldurk/renderdoc/files/3973328/ReproHonorV9Play.zip)

Contains: Apk, Diagnostics log from render doc, log from ADB, Capture and screenshot of the error

## Environment

* RenderDoc version: 1.5 and nightly build from 11.12.2019
* Operating System: Windows 10/Android
* API: 7.0.0

Honor V9 Play
CPU TK MT6750 Octa Core
GPU Mali-T860

**Comment by baldurk** [comment]
Discussed over email, this seems to be a device or OS specific bug that I can't reproduce. Something appears to be dropping socket communication after a certain point at which point eventually the server times out waiting on PC. It may also be an adb bug as the port forwarding is unreliable (the same as almost everything on android) and there was previously an adb bug that would cause port forwarding to silently drop packets.
