### ISSUE TITLE
Can only use the x group when debugging a compute shader

### ISSUE THREAD

**Issue by mischa** [baldurk/renderdoc#1646]
## Description

I can only set the x dimension of the debug group. If i set other dimensions it ignores them.

When debugging a compute shader, I set the groups to: (20, 2, 0) and click "debug".

In the debug window, I get "id: (20, 20, 20)" instead of (20, 2, 0).

## Steps to reproduce

1. set up unity project with compute shader that operates on textures
2. capture frame in renderdoc
3. Try to debug the shader with 2, 3, 0 or something.
4. It will be 2, 2, 2

## Environment

* RenderDoc version: 1.6 https://github.com/baldurk/renderdoc/commit/2c80a7206bf7d9070cc6622cb0f882f920ce48de

* Operating System: Win10
* API: D3D11

**Comment by baldurk** [comment]
Can you clarify, does this only apply to the HLSL variable display for these inputs? I can reproduce this but only when viewing the HLSL variables, the underlying registers still have the correct values and it is debugging the correct thread. Your description seems to suggest that the wrong thread is being debugged which isn't what I'm seeing.

**Comment by mischa** [comment]
Ah, yes thank you.

It is just as you say.

The hlsl variable is not correct, but the register is correct and it is indeed debugging the correct thread.

**Comment by mischa** [comment]
LMK if I should update the original issue?

**Comment by baldurk** [comment]
That's fine, I just wanted to verify that there wasn't a different bug to what I was seeing. That commit should fix the problem (at least it does in my repro test).

**Comment by mischa** [comment]
Great, thank you!
