### ISSUE TITLE
jdwp connection error on Android 9

### ISSUE THREAD

**Issue by sand0u** [baldurk/renderdoc#1654]
## Description
 Upon launching a dialog appears "Error connecting to debugger".
The diagnostics log file displays the following:
RDOC 003608: [17:08:19]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 root'
RDOC 003608: [17:08:19]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell getprop ro.product.manufacturer'
RDOC 003608: [17:08:19]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell getprop ro.product.model'
RDOC 003608: [17:08:19]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell getprop ro.build.version.sdk'
RDOC 003608: [17:08:29]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell getprop ro.build.version.sdk'
RDOC 003608: [17:08:33]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell pm list packages -3'
RDOC 003608: [17:08:34]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell dumpsys package'
RDOC 003608: [17:08:36]          android.cpp( 484) - Log     - Timer Fetching android packages and activities - 3103.094 ms
RDOC 003608: [17:08:45]    android_patch.cpp( 466) - Log     - Checking that APK is debuggable
RDOC 003608: [17:08:45]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell dumpsys package com.netease.wyclx'
RDOC 003608: [17:08:45]    android_patch.cpp( 498) - Log     - com.netease.wyclx/#DefaultActivity is not debuggable
RDOC 003608: [17:08:45]    android_patch.cpp( 430) - Log     - Checking for root access on 192.168.0.107:5555
RDOC 003608: [17:08:45]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 root'
RDOC 003608: [17:08:45]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell whoami'
RDOC 003608: [17:08:46]    android_patch.cpp( 503) - Log     - Root access detected
RDOC 003608: [17:08:47]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell cmd package resolve-activity -c android.intent.category.LAUNCHER com.netease.wyclx'
RDOC 003608: [17:08:47]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 forward --remove tcp:39501'
RDOC 003608: [17:08:47]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell am force-stop com.netease.wyclx'
RDOC 003608: [17:08:47]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell getprop ro.build.version.sdk'
RDOC 003608: [17:08:48]          android.cpp(1011) - Log     - Using pre-Android 10 Vulkan layering and JDWP injection
RDOC 003608: [17:08:48]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell setprop debug.vulkan.layers VK_LAYER_RENDERDOC_Capture'
RDOC 003608: [17:08:48]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell setprop debug.vr.profiler 1'
RDOC 003608: [17:08:48]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell mkdir -p /sdcard/Android/data/com.netease.wyclx'
RDOC 003608: [17:08:48]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell setprop debug.rdoc.RENDERDOC_CAPOPTS ababaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaa'
RDOC 003608: [17:08:49]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell pm path com.netease.wyclx'
RDOC 003608: [17:08:49]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell ls /data/app/com.netease.wyclx-wH8jDknRarYNUORFFIMWfw==//lib/*/libVkLayer_GLES_RenderDoc.so'
RDOC 003608: [17:08:49]          android.cpp(1051) - Log     - No library found in /data/app/com.netease.wyclx-wH8jDknRarYNUORFFIMWfw==//lib/*/libVkLayer_GLES_RenderDoc.so for com.netease.wyclx - assuming injection is required.
RDOC 003608: [17:08:49]          android.cpp(1061) - Log     - Launching package 'com.netease.wyclx' with activity 'com.netease.game.MessiahNativeActivity'
RDOC 003608: [17:08:49]          android.cpp(1065) - Log     - Setting up to launch the application as a debugger to inject.
RDOC 003608: [17:08:49]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell am start -S -D -n com.netease.wyclx/com.netease.game.MessiahNativeActivity '
RDOC 003608: [17:08:50]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell ps -A | grep com.netease.wyclx'
RDOC 003608: [17:08:50]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 forward tcp:38969 localabstract:renderdoc_39920'
RDOC 003608: [17:08:51]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 forward tcp:38960 localabstract:renderdoc_38920'
RDOC 003608: [17:08:51]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 forward tcp:39501 jdwp:6055'
RDOC 003608: [17:08:52]    android_tools.cpp( 319) - Log     - COMMAND: C:/Users/MECHREV/AppData/Local/Android/Sdk/platform-tools/adb '-s 192.168.0.107:5555 shell pm path org.renderdoc.renderdoccmd.arm32'
RDOC 003608: [17:08:52]             jdwp.cpp( 160) - Log     - Injecting RenderDoc from library in /data/app/org.renderdoc.renderdoccmd.arm32-lBTFETgHT5V9VUGqdQMtkw==/lib/arm
RDOC 003608: [17:08:52]             jdwp.cpp( 209) - Log     - Got android.app.ApplicationLoaders.getClassLoader signature (Ljava/lang/String;IZLjava/lang/String;Ljava/lang/String;Ljava/lang/ClassLoader;Ljava/lang/String;)Ljava/lang/ClassLoader;
RDOC 003608: [17:08:54]  jdwp_connection.cpp(  98) - Error   - Didn't get matching reply packet for 64/100
RDOC 003608: [17:08:54]  jdwp_connection.cpp( 438) - Error   - Expected event packet, but got 0/0
RDOC 003608: [17:08:54]             jdwp.cpp( 383) - Error   - Didn't hit android.app.Application.onCreate()
RDOC 003608: [17:08:54]          android.cpp(1108) - Error   - Failed to inject using JDWP

## Steps to reproduce

Happens after clicking on Launch button.

## Environment

version: RenderDoc_2019_12_18_fe405462_64
Operating System: Windows 10
GPU: Qualcomm Adreno 512
Android 9

**Comment by baldurk** [comment]
Hi there, you have **not** properly followed the issue template. Writing something under each heading is not sufficient. "Happens after clicking on Launch button" is not a set of steps I can follow to reproduce the problem, that's restating your description.

Judging by the error the issue is that your application is not calling `android.app.Application.onCreate()`. This is supposed to be impossible as all Android applications should reach this point, but Android is a terrible and unreliable platform where no behaviour is guaranteed or consistent so it's not impossible that there is case I haven't seen where this happens.

Unless I can reproduce the problem I can't investigate it, please share your application either here or privately, or an equivalent application that still demonstrates the problem. Then at least I can try it on my devices to see if I get the same problem. You might also want to try running your application on a different device, since Android being awful there are many devices and versions of the operating system that are just broken.

**Comment by sand0u** [comment]
Thanks for your quick reply. I have sent my application download link to baldurk@baldurk.org.

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
