### ISSUE TITLE
IDXGIDeviceSubObject::GetDevice() does not return wrapped device

### ISSUE THREAD

**Issue by shimaowo** [baldurk/renderdoc#1658]
## Description

Not really a bug, but a question:
I have what is probably an uncommon situation, but I wanted to see if it was possible to still use RenderDoc for debugging in this case.

I have a d3d11 application that is properly hooked by RenderDoc, and captures work correctly.  However, we also provide a few plugin interfaces for rendering, including one low-level that gives direct access to DX resources.  The swapchain is passed into these plugins, and it can then be used to get the device etc as necessary.

The problem is that the returned device (ultimately from IDXGIDeviceSubObject::GetDevice()) is the raw, unwrapped device even when running under RenderDoc.  This still "works" for rendering, but it means that renderdoc will refuse to capture any events originating from this device, because it does not match the entry in its map.

This essentially means that it is impossible to debug render plugins with RenderDoc because they render outside of its knowledge.  I can rework things eventually to include the device pointer directly, but there are existing plugins that it would be nice to work with without having to rebuild them all.

Is there a way to either get the wrapped device (automatically hooked, or via the API - I could not find a way to do that in either case), or to have the map lookup be a bit smarter and realize it already has a wrapped version of a given device?

## Steps to reproduce

I haven't made a simplified test application for this specifically, but the steps should be:
* Use any hooked method(s) to create a device and swapchain - eg, D3D11CreateDeviceAndSwapChain()
* Observe the address of the frame capturer device in the diagnostic log in RenderDoc
* Use IDXGIDeviceSubObject::GetDevice() via the swapchain pointer to get the device pointer
* Note the new device pointer address is not that of the wrapped device

I confirmed the different addresses by adding a log to RenderDoc when it creates the wrapped device, logging both the real and wrapped device addresses.  GetDevice() returns the same real device pointer.  If captures only work on the wrapped device, I would expect a way to exist to get that device instead.

Relevant sections of the log from a sample run.  The errors at the bottom were an attempt to call StartFrameCapture() via the api directly.  Note that the mismatched device matches what was reported in the log as the "real device" and not the frame capturer.
``` d3d11_hooks.cpp(236) - Debug   - Called real createdevice...
 d3d11_hooks.cpp(249) - Debug   - succeeded and hooking.
  shader_cache.h(141) - Debug   - Successfully loaded 246 shaders from shader cache
       core.cpp(1684) - Log     - Adding D3D11 device frame capturer for 0x000001D2BED305E8
d3d11_device.cpp(149) - Log     - Real device was 000001D2CE02B8E8
d3d11_device.cpp(174) - Log     - New D3D11 device created: nVidia / NVIDIA GeForce GTX 1080 26.21.14.4097
d3d11_device.cpp(239) - Debug   - Couldn't get ID3D11InfoQueue.
 d3d11_hooks.cpp(263) - Debug   - created wrapped device.
       core.cpp(1717) - Log     - Adding D3D11 frame capturer for 0x000001D2BED305E8 / 0x0000000000110BC2
d3d11_device.cpp(720) - Warning - Returning a dummy ID3D11InfoQueue that does nothing. RenderDoc takes control of the debug layer.
d3d11_device.cpp(725) - Warning - If you want direct access, enable API validation and query for GUID {3fc4e618-3f70-452a-8b8f-a73accb58e3d}. This will return the real ID3D11InfoQueue - be careful as it is unwrapped so you should not call QueryInterface on it.
 d3d11_hooks.cpp(429) - Warning - NvAPI disabled: Returning NULL for nvapi_QueryInterface(4b708b54)
     app_api.cpp(343) - Log     - Initialising RenderDoc API version 1.4.0 for requested version 10400
        core.cpp(736) - Error   - Couldn't find frame capturer for device 000001D2CE02B8E8 window 0000000000110BC2
        core.cpp(704) - Error   - Couldn't find matching frame capturer for device 000001D2CE02B8E8 window 0000000000110BC2 from 1 device frame capturers and 1 frame capturers
        core.cpp(736) - Error   - Couldn't find frame capturer for device 000001D2CE02B8E8 window 0000000000110BC2
        core.cpp(704) - Error   - Couldn't find matching frame capturer for device 000001D2CE02B8E8 window 0000000000110BC2 from 1 device frame capturers and 1 frame capturers
```

## Environment

* RenderDoc version: Current release build
* Operating System: Win10 1903 (18362.476)
* API: 1.4 (where applicable, but isn't directly relevant here)

Thanks for any insight - it would be great if this could be made to work without having to force updates of our plugins.

**Comment by baldurk** [comment]
Can you please tell me which interface you're querying for in the `GetDevice` call? Testing locally I can query for the `ID3D11Device` interface from the swapchain's `GetDevice` and it returns the same pointer as my original device, but given what a rat's nest DXGI is you might be querying for an interface I haven't handled properly since there's no documentation of what is valid where.

**Comment by shimaowo** [comment]
So in looking into this more with the partner originally having the issue, it looks like it is most likely caused by some strangeness in their setup.  They have automation running multiple tools simultaneously that are all hooking D3D in various ways, and apparently no issues manifested with that until they also added RenderDoc on top.  I'm still not entirely sure how this particular issue is happening, but it seems as though the pointers we receive when doing resource creation (device, swapchain, etc) are sometimes the RenderDoc wrapped pointers, and sometimes not... which explains the manifestation of this issue, if not how exactly it occurs.

Regardless, I don't think this is a use case that RenderDoc should reasonably be expected to support.  If it does turn out that there is an easy enhancement that would make this setup work (eg, hooking another interface or similar), I will post that back here once we've gotten things resolved.  But for now I'm chalking this up to configuration error.

Thanks for the response, and apologies for the confusion!

**Comment by baldurk** [comment]
Yeh unfortunately D3D hooking tends to be a one-user-only issue. In theory different tools could each hook each other in a chain, but in practice they will stomp on top of each other. If you can reproduce the issue with only RenderDoc active then it's definitely worth fixing, but otherwise it could be down to unsolvable incompatibilities as you say.
