### ISSUE TITLE
Renderdoc bricks my DirectX

### ISSUE THREAD

**Issue by DreadFox17** [baldurk/renderdoc#1659]
Every time I try to use Renderdoc it completely bricks my DirectX (At least I think that's what's happening)
When I try to launch an application through Renderdoc (Elite: Dangerous, in this case), it crashes to desktop and then _none_ of my games work after that at all.
Every time I try to run a game after using Renderdoc they crash to desktop with a "fatal error".
The only thing I can do to fix this issue is a system restore.

Steps to reproduce:
-Install Renderdoc
-Run Renderdoc
-Try to launch application through Renderdoc

* RenderDoc version: 1.5
* Operating System: Windows 10
* API: ?

**Comment by zao** [comment]
If you're the developer of the software in question, you may need to make some concessions in how it uses the GPU to work well with RenderDoc. It should be mostly non-intrusive but may restrict the API functionality available.

If you're not, please don't file issues on instrumenting closed-source and commercial titles that you do not control, as there's very little that RenderDoc can do about the assumptions that applications make about how the graphics API works.

If you can reproduce a problem with an open-source sample for the graphics API, or have your own codebase that manifests this driver problem, an issue submitted with that information may be more actionable.

**Comment by baldurk** [comment]
I don't believe they are the developer of Elite: Dangerous. Closing this issue immediately.

**Comment by DreadFox17** [comment]
> I don't believe they are the developer of Elite: Dangerous. Closing this issue immediately.

Sorry.
To clarify I wasn't trying to do anything shady or anything like that.
I wanted to try my hand at making a fan made ship interior and I needed one of the ship models for size and position referencing.
