### ISSUE TITLE
Shader pipeline state becomes invalid after modifying shader

### ISSUE THREAD

**Issue by moradin** [baldurk/renderdoc#166]
Maybe this is a totally expected thing but maybe it's not, if it's not a bug please feel free to close this.

Again tested in GL, after modifying the shader the pipeline state for the stage that got modified becomes invalid. Contents of buffers become 0, the whole shader stage looks like there was no shader bound to it.

**Comment by baldurk** [comment]
Sounds like a bug indeed. Maybe the necessary reflection information isn't fetched for edited shaders. There is one long-standing bug that I haven't had the motivation to figure out, which is that after editing a shader the pipeline state will be stale until you refresh it by changing drawcalls (even just away then back to where you started). I assume that's what you're seeing - after editing a shader it's stale until you refresh it, then it's all invalid?

**Comment by moradin** [comment]
I tried switching to a different drawcall and back but it doesn't seem to help. The shader stays unbound and the constant buffers are zeroed out as long as the shader source editor window is open. As soon as I close that everything gets back to normal.

**Comment by baldurk** [comment]
Closing as this was fixed for v0.27. Re-open if it's not properly resolved.
