### ISSUE TITLE
Cannot launch app with two windows

### ISSUE THREAD

**Issue by greenkalx** [baldurk/renderdoc#1660]
## Description

I have a very simple directx11 app that crashes or hangs when launched from RenderDoc.
Couldn't find any mention of 'multithreaded' in the doggo.

In PIX, I can see only the 'Present' in the event stack, where I see ClearRenderTarget, Draw, Present in my single threaded app.

## Steps to reproduce

Try to launch a multithreaded app.
There is MultithreadedRendering11 in directx-sdk-samples (github), though that is more complex than my app.

Rather not share my code but it's pretty simple.

## Environment

* RenderDoc version: 1.5 (built from https://github.com/baldurk/renderdoc/commit/a94f238e37cfe2f142093eb8e5da7775abaa88c6
* Operating System: Windows 10 Pro
* API: dx11

nvidia geforce 1050 ti

**Comment by greenkalx** [comment]
Note, I'm drawing to two windows. Whereas MultithreadedRendering11 is single window.

**Comment by greenkalx** [comment]
Tried MultithreadedRendering11, does not crash.
Problem must be my two windows.
PIX also works with MultithreadedRendering11.

**Comment by greenkalx** [comment]
Updates:

@greenkalx FYI renderdoc has a SetActiveWindow to allow you to specify active window. I'm not sure how PIX picks though.
See https://renderdoc.org/docs/in_application_api.html#_CPPv215SetActiveWindow23RENDERDOC_DevicePointer22RENDERDOC_WindowHandle

Thanks for the reply! I need to attach after my app starts because it crashes in RenderDoc on launch. Not possible on windows? https://github.com/baldurk/renderdoc/wiki/Attaching-to-running-programs

Today at 6:09 PM
Should be fine on windows, though you need to have RenderDoc running before DirectX initializes, as the "Launch For GPU Capture" in PIX.
But I guess that may cause the crash anyway...

**Comment by baldurk** [comment]
Please update this bug with repro steps that show the problem, by your own comments the original repro steps of "capture MultithreadedRendering11" does not work.

If you're capturing a program with multiple windows, renderdoc always captures the rendering between Present() boundaries. So from the present of the active window to the next present of the same window - the active window can be changed either with the API you linked or with F11 key, and it's shown in the overlay.

I highly recommend against trying to inject into a running program, and if your problems only happen when doing that I won't help as it's too unreliable and easy to break. It's provided as an "if you know what you're doing" option that's only useful when reproducing the start conditions of your process is too difficult. Launching your program through renderdoc is more reliable and whatever crash you are experiencing is quite possibly going to happen anyway when injected.

**Comment by greenkalx** [comment]
Still running two windows, but I made some other threading changes. And now I can capture in RenderDoc, nice!

Great tool, thanks for your help. Also using Graphics Debugging (PIX) in Visual Studio 2017, good to have some comparison from different tools.

Issue can be closed

**Comment by baldurk** [comment]
Closing as issue was confirmed to be an application bug.
