### ISSUE TITLE
Android device connect with renderdoc show "Conldn't correctly verify intalled APK version"

### ISSUE THREAD

**Issue by CastleDeng** [baldurk/renderdoc#1662]
## Description
Connecting to my Android devide will show the Conldn't correctly verify intalled APK version warning window

## Steps to reproduce
I install the latest version of renderdoc v1.5. I try connect my Andoid phone Xiao MI 9s with renderdoc. So I click the bottom left button select my device, and than the connect shut down and showed the window saying "Conldn't correctly verify intalled APK version,".

## Environment

* RenderDoc version: 1.5
* Operating System: Android 9

The error log show below:

- RDOC 014228: [10:18:36]    remote_server.cpp(1112) - Warning - Didn't get proper handshake
RDOC 014228: [10:18:44]    win32_network.cpp( 336) - Warning - recv: WSAECONNRESET: An existing connection was forcibly closed by the remote host.
RDOC 014228: [10:18:44]         streamio.cpp( 319) - Warning - Error reading from socket
RDOC 014228: [10:18:44]    remote_server.cpp(1112) - Warning - Didn't get proper handshake
RDOC 014228: [10:18:46]    win32_network.cpp( 336) - Warning - recv: WSAECONNABORTED: An established connection was aborted by the software in your host machine.
RDOC 014228: [10:18:46]         streamio.cpp( 319) - Warning - Error reading from socket
RDOC 014228: [10:18:46]    remote_server.cpp(1112) - Warning - Didn't get proper handshake
RDOC 014228: [10:18:46]    android_tools.cpp( 308) - Log     - COMMAND: D:\Program Files\RenderDoc/plugins/android/adb '-s 1fdac29a shell getprop ro.build.version.sdk'
RDOC 014228: [10:18:46]    android_tools.cpp( 308) - Log     - COMMAND: D:\Program Files\RenderDoc/plugins/android/adb '-s 1fdac29a shell pm list packages org.renderdoc.renderdoccmd'
RDOC 014228: [10:18:47]    android_tools.cpp( 308) - Log     - COMMAND: D:\Program Files\RenderDoc/plugins/android/adb '-s 1fdac29a shell getprop ro.product.cpu.abi'
RDOC 014228: [10:18:47]          android.cpp( 836) - Log     - Starting RenderDoc server, supported ABIs:
RDOC 014228: [10:18:47]          android.cpp( 838) - Log     -   - armeabi_v7a
RDOC 014228: [10:18:47]          android.cpp( 838) - Log     -   - arm64_v8a
RDOC 014228: [10:18:47]    android_tools.cpp( 308) - Log     - COMMAND: D:\Program Files\RenderDoc/plugins/android/adb '-s 1fdac29a shell getprop ro.product.cpu.abi'
RDOC 014228: [10:18:47]          android.cpp( 285) - Log     - Checking for server APK in D:\Program Files\RenderDoc/plugins/android/
RDOC 014228: [10:18:47]          android.cpp( 292) - Log     - APKs found: D:\Program Files\RenderDoc/plugins/android/
RDOC 014228: [10:18:47]    android_tools.cpp( 308) - Log     - COMMAND: D:\Program Files\RenderDoc/plugins/android/adb '-s 1fdac29a install -r -g "D:\Program Files\RenderDoc/plugins/android/org.renderdoc.renderdoccmd.arm32.apk"'
RDOC 014228: [10:18:47]          android.cpp( 327) - Log     - Installed package 'D:\Program Files\RenderDoc/plugins/android/org.renderdoc.renderdoccmd.arm32.apk', checking for success...
RDOC 014228: [10:18:47]          android.cpp( 186) - Log     - Checking installed version of org.renderdoc.renderdoccmd.arm32 on 1fdac29a
RDOC 014228: [10:18:47]    android_tools.cpp( 308) - Log     - COMMAND: D:\Program Files\RenderDoc/plugins/android/adb '-s 1fdac29a shell pm dump org.renderdoc.renderdoccmd.arm32'
RDOC 014228: [10:18:47]          android.cpp( 205) - Error   - Unable to determine versionCode for: org.renderdoc.renderdoccmd.arm32
RDOC 014228: [10:18:47]          android.cpp( 214) - Error   - Unable to determine versionName for: org.renderdoc.renderdoccmd.arm32
RDOC 014228: [10:18:47]          android.cpp( 231) - Warning - RenderDoc server versionCode:versionName (:) is incompatible with host (15:a94f238e37cfe2f142093eb8e5da7775abaa88c6)
RDOC 014228: [10:18:47]          android.cpp( 334) - Log     - Failed to install APK. stdout: , stderr: adb: failed to install D:\Program Files\RenderDoc/plugins/android/org.renderdoc.renderdoccmd.arm32.apk:
RDOC 014228: [10:18:47]          android.cpp( 335) - Log     - Retrying...
RDOC 014228: [10:18:47]    android_tools.cpp( 308) - Log     - COMMAND: D:\Program Files\RenderDoc/plugins/android/adb '-s 1fdac29a install -r "D:\Program Files\RenderDoc/plugins/android/org.renderdoc.renderdoccmd.arm32.apk"'
RDOC 014228: [10:18:48]          android.cpp( 186) - Log     - Checking installed version of org.renderdoc.renderdoccmd.arm32 on 1fdac29a
RDOC 014228: [10:18:48]    android_tools.cpp( 308) - Log     - COMMAND: D:\Program Files\RenderDoc/plugins/android/adb '-s 1fdac29a shell pm dump org.renderdoc.renderdoccmd.arm32'
RDOC 014228: [10:18:48]          android.cpp( 205) - Error   - Unable to determine versionCode for: org.renderdoc.renderdoccmd.arm32
RDOC 014228: [10:18:48]          android.cpp( 214) - Error   - Unable to determine versionName for: org.renderdoc.renderdoccmd.arm32
RDOC 014228: [10:18:48]          android.cpp( 231) - Warning - RenderDoc server versionCode:versionName (:) is incompatible with host (15:a94f238e37cfe2f142093eb8e5da7775abaa88c6)
RDOC 014228: [10:18:48]    android_tools.cpp( 308) - Log     - COMMAND: D:\Program Files\RenderDoc/plugins/android/adb '-s 1fdac29a install -r -g "D:\Program Files\RenderDoc/plugins/android/org.renderdoc.renderdoccmd.arm64.apk"'
RDOC 014228: [10:18:49]          android.cpp( 327) - Log     - Installed package 'D:\Program Files\RenderDoc/plugins/android/org.renderdoc.renderdoccmd.arm64.apk', checking for success...
RDOC 014228: [10:18:49]          android.cpp( 186) - Log     - Checking installed version of org.renderdoc.renderdoccmd.arm64 on 1fdac29a
RDOC 014228: [10:18:49]    android_tools.cpp( 308) - Log     - COMMAND: D:\Program Files\RenderDoc/plugins/android/adb '-s 1fdac29a shell pm dump org.renderdoc.renderdoccmd.arm64'
RDOC 014228: [10:18:49]          android.cpp( 205) - Error   - Unable to determine versionCode for: org.renderdoc.renderdoccmd.arm64
RDOC 014228: [10:18:49]          android.cpp( 214) - Error   - Unable to determine versionName for: org.renderdoc.renderdoccmd.arm64
RDOC 014228: [10:18:49]          android.cpp( 231) - Warning - RenderDoc server versionCode:versionName (:) is incompatible with host (15:a94f238e37cfe2f142093eb8e5da7775abaa88c6)
RDOC 014228: [10:18:49]          android.cpp( 334) - Log     - Failed to install APK. stdout: , stderr: adb: failed to install D:\Program Files\RenderDoc/plugins/android/org.renderdoc.renderdoccmd.arm64.apk:
RDOC 014228: [10:18:49]          android.cpp( 335) - Log     - Retrying...
RDOC 014228: [10:18:49]    android_tools.cpp( 308) - Log     - COMMAND: D:\Program Files\RenderDoc/plugins/android/adb '-s 1fdac29a install -r "D:\Program Files\RenderDoc/plugins/android/org.renderdoc.renderdoccmd.arm64.apk"'
RDOC 014228: [10:18:50]          android.cpp( 186) - Log     - Checking installed version of org.renderdoc.renderdoccmd.arm64 on 1fdac29a
RDOC 014228: [10:18:50]    android_tools.cpp( 308) - Log     - COMMAND: D:\Program Files\RenderDoc/plugins/android/adb '-s 1fdac29a shell pm dump org.renderdoc.renderdoccmd.arm64'
RDOC 014228: [10:18:50]          android.cpp( 205) - Error   - Unable to determine versionCode for: org.renderdoc.renderdoccmd.arm64
RDOC 014228: [10:18:50]          android.cpp( 214) - Error   - Unable to determine versionName for: org.renderdoc.renderdoccmd.arm64
RDOC 014228: [10:18:50]          android.cpp( 231) - Warning - RenderDoc server versionCode:versionName (:) is incompatible with host (15:a94f238e37cfe2f142093eb8e5da7775abaa88c6)
RDOC 014228: [10:18:50]    android_tools.cpp( 308) - Log     - COMMAND: D:\Program Files\RenderDoc/plugins/android/adb '-s 1fdac29a shell pm list packages org.renderdoc.renderdoccmd'
RDOC 014228: [10:18:50]          android.cpp( 361) - Error   - Couldn't find any installed APKs. stderr: 
RDOC 014228: [10:18:50]          android.cpp( 864) - Error   - Failed to install RenderDoc server app
RDOC 014228: [10:18:51]    win32_network.cpp( 336) - Warning - recv: WSAECONNRESET: An existing connection was forcibly closed by the remote host.
RDOC 014228: [10:18:51]         streamio.cpp( 319) - Warning - Error reading from socket
RDOC 014228: [10:18:51]    remote_server.cpp(1112) - Warning - Didn't get proper handshake

**Comment by baldurk** [comment]
This looks like a problem with your android device failing to install the APKs properly. I'm not too surprised since android is terrible and nothing works reliably on all devices, there's already a fallback path for some devices which can't handle `-g`.

If you manually run these commands, what output do you get?

```
"D:/Program Files/RenderDoc/plugins/android/adb" -s 1fdac29a install -r "D:/Program Files/RenderDoc/plugins/android/org.renderdoc.renderdoccmd.arm64.apk"
"D:/Program Files/RenderDoc/plugins/android/adb" -s 1fdac29a shell pm dump org.renderdoc.renderdoccmd.arm64
```

**Comment by CastleDeng** [comment]
Thank you for your reply! I try these commands manually and finally find out the problem. I get the log about "INSTALL_CANCELED_BY_USER", the message mean the phone prohibit any app install by USB. So I turn off the prohibition and every thing run good. Thank you very much again!
