### ISSUE TITLE
Problem replaying frames with shadow effects

### ISSUE THREAD

**Issue by z00318884** [baldurk/renderdoc#1663]
## Description

When I open the game's shadow feature to capture the frame, and then play back, it will appear that the playback result is not consistent with the actual.

An error occurred here
ADRD 032444: [18:49:04] gl_resources.cpp( 462) - Error - Unhandled Base Format case GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC!

But this error is not the cause of the problem, I modified the error and the problem still exists.

## Steps to reproduce

Cannot provide you app and capture for some reason but
You can download the officially released version and reproduce the problem.
in the game，open [setting]->[drawing]->[shadow].

the game is “PUBG Mobile”

## Environment

* RenderDoc version: 1.5
* Operating System: android 
* Graphics API: opengles

[RenderDoc_2019.12.25_10.45.46.log](https://github.com/baldurk/renderdoc/files/4029571/RenderDoc_2019.12.25_10.45.46.log)

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by z00318884** [comment]
my own programs can‘t provide to you，but have the same problem。So if you have to test, you can use the release version

**Comment by baldurk** [comment]
I have zero tolerance for capturing copyrighted programs. Unless you can prove to me you are an authorised developer I will not provide any support and any other issues that are opened will be immediately closed.
