### ISSUE TITLE
Feature request - viewing offsets of elements in cbuffers

### ISSUE THREAD

**Issue by Nielsbishere** [baldurk/renderdoc#1664]
## Description
When debugging data layout of cbuffers, it could be handy to see the offsets the shader expects for certain cbuffer elements. You can view the buffer's contents, but this is the data that is uploaded by the cpu and can mismatch what the gpu expects. 
I tried finding this feature, but I couldn't find it in RenderDoc v1.5

## Steps to reproduce
Open up a cbuffer, it would be nice to see a column besides Name, Value, Type that said Offset. Since this is already present in RenderDoc, it should be doable to display that (since it looks up the memory at that offset in the buffer).

## Environment
* RenderDoc version: v1.5 (built from https://github.com/baldurk/renderdoc/commit/a94f238e37cfe2f142093eb8e5da7775abaa88c6)
* Operating System: Win10 1809 17763.914
* Graphics API: D3D12 11_0

**Comment by baldurk** [comment]
In among some other refactors to the buffer viewers, you can now see the offsets for fixed variables like in constant buffers. There is also an option to toggle visible padding to more easily see where packing requires particular alignments:

![image](https://user-images.githubusercontent.com/661798/169555461-90a3ffb3-1b9a-41d5-aa93-daf867894bfb.png)

**Comment by Nielsbishere** [comment]
Awesome, thank you 👍
