### ISSUE TITLE
Cannot run tests due to failed tkinter import

### ISSUE THREAD

**Issue by skarolewics** [baldurk/renderdoc#1668]
## Description

After syncing to 8f909275a79118cc962d8910557569a2587dea7a, running tests via `renderdoccmd test functional` will fail with the error `ModuleNotFoundError: no module named 'tkinter'`

I've verified that tkinter was installed with Python - running `python -m tkinter` displays the sample window as expected.

## Steps to reproduce

Run functional tests with `renderdoccmd test functional`. It errors and exits immediately. Specifying a test filter that omits the RGP test doesn't avoid the error.

## Environment

* RenderDoc version: 8f909275a79118cc962d8910557569a2587dea7a
* Operating System: Windows 10
* Graphics API: Any, but the crashing test uses D3D12
* Python version: 3.6.8

**Comment by baldurk** [comment]
Yeh I ran into this running the tests on linux so I made the import local to the test, which would have fixed the case where you filtered the test out. I didn't consider the `renderdoccmd test functional` use where even on windows most modules aren't available.

FYI running the tests that way uses RenderDoc's embedded python runtime so any modules you have installed if you run `python` won't be available.

That commit should handle it properly, by catching the import failure and using that to disable the test.
