### ISSUE TITLE
IA-VS signature mismatch should filter out system-value semantics

### ISSUE THREAD

**Issue by moarmand** [baldurk/renderdoc#167]
If a vertex shader use system-value semantics, renderdoc will incorrectly report that IA and VS signatures does not match.

**Comment by baldurk** [comment]
Can you give some more details? I don't doubt that there is a bug, but I don't think this is a general problem any time system-value semantics are used anywhere.

If you could give me a capture that would be ideal, but at least e.g. the shader signature used to generate both the IA bytecode and VS bytecode and the input-layout descriptors.

**Comment by moarmand** [comment]
Sure, sorry for being vague. I took a capture of the Microsoft InstancingFX11 sample as an example ( https://code.msdn.microsoft.com/Effects-11-Win32-Samples-cce82a4d ). 

You can grab it here https://www.dropbox.com/s/j3cq2wdy1eakvu8/InstancingFX11_2015.10.25_23.07.40_frame227.rdc?dl=0

The problem can be found on the event 92. Both IA and VS has the same signature except for the additional "SV_VertexID" on the vertex shader side. I used renderdoc v0.26.

**Comment by baldurk** [comment]
Thanks! I see what you mean now, trailing 'extra' system-value elements are allowed, since the rest of the signature remains the same. That commit should fix the false positive.

**Comment by baldurk** [comment]
Closing as this was fixed for v0.27. Re-open if it's not properly resolved.
