### ISSUE TITLE
[OpenGL] Crash when separable shader program cannot be created

### ISSUE THREAD

**Issue by SirTimothy** [baldurk/renderdoc#168]
In my case, it was when I had a Tessellation Evaluation Shader without gl_PerVertex being redeclared. In application, the set of shaders is linked in a single program object, and worked without any warnings or errors, but RenderDoc crashed without a word when I went to a drawcall using the program.

So I built Profile config locally and before the crash I hit an error in MakeSeparableShaderProgram(), with "error C7592: ARB_separate_shader_objects requires built-in block gl_PerVertex to be redeclared before accesing its members". Sure enough, shader didn't redeclare it.

Continuing through a couple more related errors, this led to GLReplay::SavePipelineState giving a null ShaderReflection* to GetBindpointMapping, and crash.

Was able to fix on my end by adding gl_PerVertex to the shader, but probably be nice to not crash if that happens :)

**Comment by baldurk** [comment]
Oh how I despise that stupid redeclaration requirement...

I agree that it shouldn't crash regardless, I'll check to see what's going on there and make sure there's some kind of graceful fallback (although RenderDoc won't be able to operate correctly without that separable prorgam).

However, in MakeSeparableShaderProgram I attempt to add a redeclaration of gl_PerVertex if it doesn't already exist, for this exact reason - can you see if it thinks the block is already declared, or is the compilation failing even with the block added?

If you're able to send me a capture or even just the shaders, I'll try and reproduce and investigate more myself.

**Comment by SirTimothy** [comment]
aha! it doesn't get added to this particular shader! our preprocessor apparently turns `#version 450 core` into `# version 450 core`. with a space in there. So MakeSeparableShaderProgram doesn't find `#version` and doesn't do the insertion

**Comment by baldurk** [comment]
Ahhh, of course, I need to allow for whitespace between `#` and `version`. That should be easy enough to do. Thanks :).

**Comment by baldurk** [comment]
Sorry that took a little while for something easy enough, been busy on side-branches :). This should fix the issue of having whitespace in preprocessor directives messing with my shader patching.

**Comment by SirTimothy** [comment]
That seems to have done it, thanks!
