### ISSUE TITLE
Texture Viewer broken after taking/opening second capture

### ISSUE THREAD

**Issue by FilipVaverka** [baldurk/renderdoc#1680]
## Description
Texture Viewer contents get scrambled when second capture is taken (Launch Application) or even same stored capture reopened during single session (i.e. Open Capture -> Close Capture -> Open Capture again). Images below show Texture Viewer contents after the capture is opened the first time and same capture opened second time.

Capture opened after launching RenderDoc:
![instance_1](https://user-images.githubusercontent.com/10695212/72463382-69bf6700-37d3-11ea-983f-56e8b86e55b1.png)

Capture opened after closing the first one (same capture file):
![instance_2](https://user-images.githubusercontent.com/10695212/72463391-6cba5780-37d3-11ea-9a8e-0593feb29e4e.png)
It should be noted that the window is not necessarily gray, it sometimes contains some colors present in the texture. The content also reacts to input (zoom, shift, ...), however not in the expected way.

After further testing the issue seems to be dependent on the application which is being captured. Minimal capture file that seems to trigger the issue is attached below.
[test_capture.zip](https://github.com/baldurk/renderdoc/files/4067088/test.zip)

## Steps to reproduce
* Launch RenderDoc
* Take or Open capture
* Close the capture
* Open or Take another/same capture (without closing RenderDoc)

## Environment

* RenderDoc version: 1.6 (this happened in any previous versions I used too)
* Operating System: Windows 10 x64 (build 1909)
* Graphics API: OpenGL
* GPU: Radeon RX Vega 64 (Radeon Software 19.12.3)

**Comment by baldurk** [comment]
This is unfortunately a known AMD driver bug that affects OpenGL. It has been fixed but a public driver is not yet available containing the fix. The only workaround I know of is to restart RenderDoc between opening captures (or not use GL as all other APIs work, but that's not really practical).
