### ISSUE TITLE
Couple bugs with Texture Viewer + Custom Shader

### ISSUE THREAD

**Issue by Gaktan** [baldurk/renderdoc#1688]
##  Description

I found a couple of bugs when using a custom shader to display a DDS texture loaded from disk.
Not sure if those bugs only happen in this specific condition or if it's a general bug with the Texture Viewer and custom shaders.

## Steps to reproduce

The steps to reproduce might not be relevant, but writing them just in case it is.

1. Load a cubemap dds file in renderdoc. Texture must contain mip levels
2. Create a new Custom Shader with the following code:
```
return texDisplayTex2DArray.SampleLevel(linearSampler, float3(uv.xy, RENDERDOC_SelectedSliceFace), RENDERDOC_SelectedMip);
```
3. Note when inspecting MIP levels in the Texture Viewer that it doesn't match the original texture

This behavior is very counter intuitive. You should expect the UVs to always be between [0..1].
A workaround to this is to modify UV coordinates like so:
```
float2 UV = uv.xy * pow(2.0, RENDERDOC_SelectedMip);
```

**Another issue with custom shaders:**

1. Load a cubemap dds file in renderdoc. Texture must contain mip levels
2. Create a new Custom shader with the following code:
```
return 0;
```
3. Note when right clicking the texture in the Texture Viewer, the color picker shows the previous result and not 0 as expected

4. Also note that when switching back from "Custom Shader" to "RGBA", the color picker only shows the red channel

## Environment

* RenderDoc version: 1.6
* Operating System: Win 10 ()
* Graphics API: D3D11

**Comment by baldurk** [comment]
I believe those commits should fix the issues you've described. Let me know if the next nightly build still has problems.

**Comment by Gaktan** [comment]
Yes, all problems fixed. Thanks
