### ISSUE TITLE
[Feature] Support reverse-Z projection in mesh output

### ISSUE THREAD

**Issue by inequation** [baldurk/renderdoc#169]
UE4 has a reverse-Z projection matrix that is constructed in the following way:
```
FORCEINLINE FReversedZPerspectiveMatrix::FReversedZPerspectiveMatrix(float HalfFOV, float Width, float Height, float MinZ)
	: FMatrix(
		FPlane(1.0f / FMath::Tan(HalfFOV),	0.0f,									0.0f, 0.0f),
		FPlane(0.0f,						Width / FMath::Tan(HalfFOV) / Height,	0.0f, 0.0f),
		FPlane(0.0f,						0.0f,									0.0f, 1.0f),
		FPlane(0.0f,						0.0f,									MinZ, 0.0f)
	)
{ }
```
Such matrices are currently not well supported by RenderDoc. When vertices are transformed by them, they all receive a Z coordinate that equals the near plane (`MinZ` from the above code snippet), while the W coordinate varies. Currently, in RenderDoc's VS Output preview window, this results in the entire mesh being flattened to the near plane.

A good heuristic to detect reverse-Z projection is to check for all `SV_Position`s' Z components being equal.

**Comment by baldurk** [comment]
Took a *little* longer than I'd hope :smile: but that should do the trick I think.

**Comment by inequation** [comment]
Great, thanks! Will check this on a nightly.

**Comment by inequation** [comment]
Apologies for the delay. Just verified, works just as expected in the nightly, thanks! :)
