### ISSUE TITLE
Vulkan layer fails to register through renderdoccmd

### ISSUE THREAD

**Issue by skarolewics** [baldurk/renderdoc#1690]
## Description

If running renderdoccmd from a different build location from where the Vulkan layer was registered, it will try to register it and then fail. Renderdoccmd was run without admin rights, but a UAC popup asked for permission which was granted.

`.. Vulkan layer needs to be registered: VulkanLayerFlags.RegisterAll|NeedElevation|OtherInstallsRegistered
.. My JSONs: ['D:\\Dev\\RenderDoc2\\x64\\Development\\renderdoc.json', 'D:\\Dev\\RenderDoc2\\x64\\Development\\x86\\renderdoc.json'], Other JSONs: ['D:\\Dev\\RenderDoc3\\x64\\Development\\renderdoc.json', 'D:\\Dev\\RenderDoc3\\x64\\Development\\x86\\renderdoc.json']
.. Couldn't register vulkan layer properly, might need admin rights`

If I instead run qrenderdoc, I can register the Vulkan layer there, and then renderdoccmd will work afterward. If I run renderdoccmd from an already elevated command prompt, then registering the Vulkan layer works.

## Steps to reproduce

1. Register the Vulkan layer with a build of renderdoc.
2. Build renderdoc with a new solution/location
3. With the new solution, run "renderdoccmd test functional" from an unelevated command prompt

## Environment

* RenderDoc version: 78c68d643a00541c69244d379e6b85230a14e5f9
* Operating System: Windows 10 Build 18363
* Graphics API: Vulkan

**Comment by baldurk** [comment]
The python script was relying on elevating and running itself, but assumed it was running in the python interpreter. I've made the `vulkanregister` command that was linux-only available everywhere, and used that for registration when running this way.
