### ISSUE TITLE
Benchmark Car Chase capture and open fail

### ISSUE THREAD

**Issue by JingYongWang** [baldurk/renderdoc#1692]
## Description

I trying to capture GFXBench Benchmark, the Test case Car_Chase on renderDoc, After Capture finish, open xxx.rdc will display "Failed to open capture for replay. Network I/O operation fail"
So I pull the part of capture log

RDOC 011061: [13:41:57]        gl_common.cpp( 814) - Warning - Reading from the depth buffer using glReadPixels is not supported (GL_NV_read_depth)
RDOC 011061: [13:41:57]        gl_common.cpp( 818) - Warning - Reading from the stencil buffer using glReadPixels is not supported (GL_NV_read_stencil)
RDOC 011061: [13:41:57]        gl_common.cpp( 822) - Warning - Reading from the packed depth-stencil buffers using glReadPixels is not supported (GL_NV_read_depth_stencil)
RDOC 011061: [13:41:57]         gl_debug.cpp( 484) - Log     - GLSL version 320
RDOC 011061: [13:41:59]        gl_replay.cpp( 322) - Log     - ARM GPU detected - no counters available
RDOC 011061: [13:42:07]     gl_initstate.cpp(1813) - Warning - Technically you could try and readback the contents of a RenderBuffer via pixel copy.
RDOC 011061: [13:42:07]     gl_initstate.cpp(1814) - Warning - Currently we don't support that though, and initial contents will be uninitialised.

## Steps to reproduce

1. Install apk on Google Play : GFXBench Benchmark
2. Test selection
3. chose only Car Chase 
4. Start

## Environment

* RenderDoc version: v1.5
* Operating System: win7 x64
* Android version: 10.0

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
