### ISSUE TITLE
Array buffer format repeats first element

### ISSUE THREAD

**Issue by ag-rutger** [baldurk/renderdoc#1694]
## Description

When specifying buffer format in the buffer contents view with an array (float[4] for example), the first value is repeated for every element (1.00, 1.00, 1.00, 1.00 for example). When using float; float; float; float; the data will be correct (1.00, 1.00, 0.00, 1.00 for example).

## Steps to reproduce

1. Create a capture on an Android device of an OpenGL ES 3.2 application
2. Replay this capture on the same device
3. View contents of any buffer which has different elements (so not all 0)
4. In the buffer format, specify any array format, float[4] for example, and hit apply
5. Notice that in the buffer contents all elements in a row are the same
6. Change the buffer format to not use the array specification, float; float; float; float; in this example
7. Notice that in the buffer contents the elements on a row are different

![Bug](https://user-images.githubusercontent.com/54446192/72824278-4aae5280-3c75-11ea-9b7c-d8d1523bbb90.png)

Due to NDA I can't share the capture. In 1.15 (atleast with a dx11 capture) this was working correctly. 

## Environment

* RenderDoc version: 1.6 (0e7f7725)
* Operating System: Windows 10 (Renderdoc), captured on a Samsung Galaxy S10+ (Android 10) and replayed on the same phone and a huawei phone.
* Graphics API: OpenGL ES

**Comment by baldurk** [comment]
Yes this was unfortunately a regression between 1.5 (I assume that's what you meant rather than 1.15) and 1.6. A fix was made a few days ago in 4a587da167ed201939d1f69b4c5c45778853527f so if you try again with a nightly build this should work correctly now.
