### ISSUE TITLE
Impossible to build project with jdk 13

### ISSUE THREAD

**Issue by ituraevRender** [baldurk/renderdoc#1697]
## Description

The renderdoc project doesn't build with latest jdk version 13. After many attempts with different versionы the only convenient version is version provided by Android Studio.

## Steps to reproduce

Preconditions: 

- Prepare a environment for renderdoc: setup CMake with MinGW; Set Environment variables for them.

- Download and install latest jdk by Oracle. (Currently it's https://www.oracle.com/technetwork/java/javase/downloads/jdk13-downloads-5672538.html)
Set it as JAVA_HOME variable.

Steps to reproduce.

1. Build project with:
cmake -DBUILD_ANDROID=On -DANDROID_ABI=armeabi-v7a -DENABLE_VULKAN=On -G "MinGW Makefiles" ..

## Environment

* RenderDoc version: 1.6
* Operating System: Windows 10

**Comment by baldurk** [comment]
I can reproduce this, I'll try to see if there is a fix for this but I expect that it's not fixable and Android is just being a terrible platform as usual. I'd recommend you install JDK 8 and use that for building.

**Comment by baldurk** [comment]
This is a misconfiguration in your build environment. I've [clarified in the docs](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Dependencies.md#android) the supported versions for android building:

> RenderDoc is currently known to build with NDK 14b, SDK tools 3859397, SDK build-tools 26.0.1, SDK platform android-23, Java 8 (also known as 1.8).

Those versions definitely work. If you want to use other versions it's up to you to ensure you have a working build setup as the interactions between these are complicated and cross-compatibility is not guaranteed by the android SDKs.
