### ISSUE TITLE
WSAECONNRESET:  program closes immediately after launch

### ISSUE THREAD

**Issue by philoez98** [baldurk/renderdoc#1702]
## Description

When launching from Renderdoc, the program window appears for a couple of seconds and then it shuts down without errors.
The application works standalone and through Nvidia Nsight debugger.

## Steps to reproduce

Here is the log file:

```
Core     PID  11868: [11:56:43]              core.cpp(370) - Log     - RenderDoc v1.5 Windows 64-bit Release (a94f238e37cfe2f142093eb8e5da7775abaa88c6) loaded in replay application
Core     PID   8828: [11:56:43]              core.cpp(370) - Log     - RenderDoc v1.5 Windows 64-bit Release (a94f238e37cfe2f142093eb8e5da7775abaa88c6) loaded in replay application
Core     PID  11868: [11:56:43]       crash_handler.h(175) - Log     - Timer Waiting for crash handling server - 39.592 ms
Core     PID  11868: [11:56:43]       crash_handler.h(181) - Log     - Created crash-handling server \\.\pipe\RenderDocBreakpadServer709158530327
Core     PID  11868: [11:56:43]        crash_handler.h(93) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer709158530327
UI       PID  11868: [11:56:43]         qrenderdoc.cpp(88) - Log     - QRenderDoc initialising.
Core     PID  11868: [11:56:43]        crash_handler.h(51) - Log     - Re-using crash-handling server \\.\pipe\RenderDocBreakpadServer709158530327
Core     PID  11868: [11:56:43]        crash_handler.h(93) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer709158530327
Core     PID  11868: [11:56:43]      d3d11_replay.cpp(123) - Log     - Running replay on nVidia / NVIDIA GeForce GTX 1660 Ti 26.21.14.4187
Core     PID  11868: [11:56:43]      d3d12_replay.cpp(135) - Log     - Running replay on nVidia / NVIDIA GeForce GTX 1660 Ti 26.21.14.4187
Core     PID  11868: [11:56:44]     android_tools.cpp(334) - Log     - Initialising adb using 'C:\Program Files\RenderDoc/plugins/android/adb'
Core     PID  11868: [11:56:44]        vk_replay.cpp(4218) - Log     - Created device.
Core     PID  11868: [11:56:49]     android_tools.cpp(350) - Log     - Started adb server
Core     PID  11868: [11:56:56]     win32_process.cpp(531) - Log     - Running process **path-to-my-executable**
Core     PID  11868: [11:56:56]     win32_process.cpp(616) - Log     - Injecting renderdoc into process 6108
Core     PID  11868: [11:56:56]     win32_process.cpp(327) - Warning - CreateToolhelp32Snapshot(6108) -> 0x00000018
Core     PID   6108: [11:56:56]              core.cpp(370) - Log     - RenderDoc v1.5 Windows 64-bit Release (a94f238e37cfe2f142093eb8e5da7775abaa88c6) capturing application
Core     PID   6108: [11:56:56]       crash_handler.h(175) - Log     - Timer Waiting for crash handling server - 41.708 ms
Core     PID   6108: [11:56:56]       crash_handler.h(181) - Log     - Created crash-handling server \\.\pipe\RenderDocBreakpadServer709292202334
Core     PID   6108: [11:56:56]        crash_handler.h(93) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer709292202334
Core     PID   6108: [11:56:56]     win32_libentry.cpp(66) - Log     - Loading into **path-to-my-executable**
Core     PID   6108: [11:56:56]    sys_win32_hooks.cpp(82) - Log     - Registering Win32 system hooks
Core     PID   6108: [11:56:56]       d3d11_hooks.cpp(125) - Log     - Registering D3D11 hooks
Core     PID   6108: [11:56:56]       d3d12_hooks.cpp(181) - Log     - Registering D3D12 hooks
Core     PID   6108: [11:56:56]         d3d8_hooks.cpp(36) - Log     - Registering D3D8 hooks
Core     PID   6108: [11:56:56]         d3d9_hooks.cpp(45) - Log     - Registering D3D9 hooks
Core     PID   6108: [11:56:56]        dxgi_hooks.cpp(250) - Log     - Registering DXGI hooks
Core     PID   6108: [11:56:56]         egl_hooks.cpp(958) - Log     - Registering EGL hooks
Core     PID   6108: [11:56:56]          gl_hooks.cpp(255) - Log     - Registering OpenGL hooks
Core     PID   6108: [11:56:56]         wgl_hooks.cpp(610) - Log     - Registering WGL hooks
Core     PID   6108: [11:56:56]           vk_layer.cpp(53) - Log     - Registering Vulkan hooks
Core     PID   6108: [11:56:56]        crash_handler.h(51) - Log     - Re-using crash-handling server \\.\pipe\RenderDocBreakpadServer709292202334
Core     PID   6108: [11:56:56]        crash_handler.h(93) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer709292202334
Core     PID  11868: [11:56:56]    target_control.cpp(566) - Log     - Got remote handshake: Engine [6108]
Core     PID   6108: [11:56:57]   vk_device_funcs.cpp(766) - Log     - Initialised capture layer in Vulkan instance.
Core     PID   6108: [11:56:57]  vk_device_funcs.cpp(1372) - Log     - physical device 0: GeForce GTX 1660 Ti (ver 441.87 patch 0x0) - 10de:2182
Core     PID  11868: [11:56:57]    target_control.cpp(802) - Log     - Used API: Vulkan (Not presenting & supported)
Core     PID  11868: [11:56:59]     win32_network.cpp(255) - Warning - recv: WSAECONNRESET: An existing connection was forcibly closed by the remote host.

```

It seems like the connection gets closed immediately after launching the process. 
This happens with RenderDoc 1.5 and 1.6 when trying to debug a vulkan application

## Environment

* RenderDoc version: 1.5
* Operating System: Windows 10 build 18363
* Graphics API: Vulkan 1.0 and 1.1

GPU: NVIDIA GeForce 1660 Ti
NVIDIA Drivers: 441.87 (Latest stable)

**Comment by baldurk** [comment]
While you have followed the letter of the template you have not genuinely filled it out. A paste of a log file with no useful information in it is not a set of steps to reproduce the issue, and the description of the bug is very vague.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

Please provide a reproducible test case and steps I can follow, or else if that is not possible due to being unable to share your program then explain that and give as much detailed and specific information about what is going wrong as you are able to, or find a simplified case that still reproduces your problem which you can share.

You've also stated that you're using RenderDoc v1.5, when v1.6 has been released and has been prompting for updates for a couple of weeks now. It's possible whatever bug you are encountering has already been fixed so updating to the latest stable release would be a useful thing to try.

**Comment by philoez98** [comment]
Sorry for the lack of information, I will try to make a simple repro case which I can share.
This actually happens also on the newest version of RenderDoc. I tried to revert back to the previous version to see if it worked.

When launching the application from RenderDoc, it starts up as expected (I can see the window) but after a few seconds it shuts down.
I tried to disable validation layers and all sort of stuff, which I thought might have changed between different builds, with no positive results.

I don't know exactly how a connection refused error is caused from the application itself. Any general pointers here?

**Comment by baldurk** [comment]
A connection refused error is a very different error, as it says in the log this is a connection **closed** error. It's not caused from the application at all, it's from RenderDoc's injected code and all it means is that the socket used for communication between the UI and the application was unexpectedly shut down from one end, which as I say doesn't tell us anything.

It sounds like possibly your process is simply crashing. Have you tried attaching a debugger to the program before it closes to see where it crashes? You can use the 'debugger delay' option when launching to cause the process to pause on startup and give you time to attach if the window isn't open long enough.

Be sure that you don't have any warnings or errors from the vulkan validation layers, as undefined behaviour can cause crashes in RenderDoc, even if it doesn't on the particular driver you're using or other tools.

**Comment by philoez98** [comment]
Now it seems to work. Deleting and rebuilding the latest version of RenderDoc from source seems to have fixed the issue. No other changes on my part. Thanks for the quick and helpful support.
