### ISSUE TITLE
very big amount, like 1.844E+13ms

### ISSUE THREAD

**Issue by HennessyTennessy** [baldurk/renderdoc#1705]
Hello!

## Description

When I look "Time Durations for Drawcalls", i see very big amount, like 1.844E+13ms, for random EID, either "Unnamed command buffer", or "Render.TransparentGeometry"...

Diagnostic Log say me errors:
"Failed to cap frame - we saw an Unmap() that we didn't capture the corresponding Map() for"
"Failed to cap frame - we saw an FlushMappedBuffer() that we didn't capture the corresponding Map() for"

## Steps to reproduce

1) Launch Application
2) Capture Frame Immediately
3) Look Event Browser
4) CheckUp "Time Durations for Drawcalls"

## Environment

* RenderDoc version:  1.6 15 Jan 2020, Nightly 2020-01-30, both versions, same trouble
* Operating System: Windows 10
* Graphics API: OpenGl ES 3.0

**Comment by baldurk** [comment]
The duration timer can be quite unreliable depending on platform, API, driver, other programs running, etc. It's provided purely for legacy reasons (it was added a long time ago and I don't want to remove it), but there's no guarantee that it produces reliable results - see #65.

RenderDoc is not a profiler so performance analysis is not in scope for the tool.

**Comment by HennessyTennessy** [comment]
@baldurk 
Oh okay, thanks for answer. Btw very good program.
 Do you know any good GPU profiler for Android, like this?

**Comment by baldurk** [comment]
I'm not really familiar with profilers I'm afraid. I believe the different IHVs on mobile have profiling tools but you'd need to investigate.

**Comment by HennessyTennessy** [comment]
Ah okay, thank you.
