### ISSUE TITLE
Vulkan headless compute - empty captures and segfaults in qrenderdoc

### ISSUE THREAD

**Issue by ScottTodd** [baldurk/renderdoc#1711]
## Description

I'm trying to use RenderDoc with a [project that I work on](https://github.com/google/iree) for the first time. The project uses Vulkan for compute, both headlessly (with no graphics) and together with some Vulkan GUI code in [one of our sample programs](https://github.com/google/iree/blob/master/iree/samples/vulkan/vulkan_inference_gui.cc).

I can record a capture via "Launch Application" in `qrenderdoc` of the GUI sample, but when I do the same with the headless program, no capture is recorded. Logs:
```
RDOC 213313: [10:33:03]   target_control.cpp( 576) - Log     - Got remote handshake: iree-run-mlir [215079]
RDOC 215079: [10:33:03]             core.cpp(1691) - Log     - Adding Vulkan device frame capturer for 0x0000000002D697D0
RDOC 215079: [10:33:03]  vk_device_funcs.cpp( 763) - Log     - Initialised capture layer in Vulkan instance.
RDOC 215079: [10:33:03]  vk_device_funcs.cpp(1352) - Log     - physical device 0: Quadro P1000 (ver 430.50 patch 0x0) - 10de:1cb1
RDOC 215079: [10:33:03]          vk_core.cpp(1339) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
RDOC 215079: [10:33:03]          vk_core.cpp(1339) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
RDOC 215079: [10:33:03]          vk_core.cpp(1339) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
RDOC 215079: [10:33:03]          vk_core.cpp(1339) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
RDOC 215079: [10:33:03]          vk_core.cpp(1683) - Log     - Starting capture, frame 4294967295
RDOC 213313: [10:33:03]   target_control.cpp( 814) - Log     - Used API: Vulkan (Not presenting & supported)
RDOC 215079: [10:33:03]             core.cpp(1707) - Log     - Removing device frame capturer for 0x0000000002D697D0
RDOC 215079: [10:33:03]         vk_manager.h( 201) - Error   - Assertion failed: 'm_ResourceRecords.empty()' 
```

I've tried [integrating with RenderDoc's API](https://github.com/ScottTodd/iree/commit/cea42c29853dcb62e004568ed4cea6d66fb643e9) to control when capture starts/stops, but then I get captures that segfault RenderDoc when opened. Trimmed logs:

```
RDOC 216822: [10:34:55]             core.cpp( 421) - Log     - RenderDoc v1.6 Linux 64-bit Release (0e7f772596035137416be01766c2d61205efc63e) capturing application
RDOC 216822: [10:34:55]   posix_libentry.cpp(  56) - Log     - Using delay for debugger 0
RDOC 216822: [10:34:55]   posix_libentry.cpp(  69) - Log     - Loading into /usr/local/google/home/scotttodd/.cache/bazel/_bazel_scotttodd/9e82052937ca42451e1b3d0e47f9949a/execroot/iree_core/bazel-out/k8-opt/bin/iree/tools/iree-run-mlir
RDOC 216822: [10:34:55]         gl_hooks.cpp( 255) - Log     - Registering OpenGL hooks
RDOC 216822: [10:34:55]        glx_hooks.cpp( 719) - Log     - Registering GLX hooks
RDOC 216822: [10:34:55]        egl_hooks.cpp( 967) - Log     - Registering EGL hooks
RDOC 216822: [10:34:55]         vk_layer.cpp(  53) - Log     - Registering Vulkan hooks
RDOC 216822: [10:34:55]          app_api.cpp( 343) - Log     - Initialising RenderDoc API version 1.4.0 for requested version 10400
RDOC 213313: [10:34:55]   target_control.cpp( 576) - Log     - Got remote handshake: iree-run-mlir [216822]
RDOC 216822: [10:34:55]             core.cpp(1691) - Log     - Adding Vulkan device frame capturer for 0x000000000230CF30
RDOC 216822: [10:34:55]  vk_device_funcs.cpp( 763) - Log     - Initialised capture layer in Vulkan instance.
RDOC 216822: [10:34:55]  vk_device_funcs.cpp(1352) - Log     - physical device 0: Quadro P1000 (ver 430.50 patch 0x0) - 10de:1cb1
RDOC 216822: [10:34:55]          vk_core.cpp(1339) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
RDOC 216822: [10:34:55]          vk_core.cpp(1339) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
RDOC 216822: [10:34:55]          vk_core.cpp(1339) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
RDOC 216822: [10:34:55]          vk_core.cpp(1339) - Warning - VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address
RDOC 216822: [10:34:55]          vk_core.cpp(1683) - Log     - Starting capture, frame 4294967295
RDOC 213313: [10:34:55]   target_control.cpp( 814) - Log     - Used API: Vulkan (Not presenting & supported)
RDOC 216822: [10:34:55]          vk_core.cpp(1709) - Log     - Finished capture, Frame 0
RDOC 216822: [10:34:55]          rdcfile.cpp(1163) - Log     - Finishing write to section 1 (renderdoc/internal/framecapture). Compressed from 25178368 bytes to 108210
RDOC 216822: [10:34:55]             core.cpp(1635) - Log     - Written to disk: /tmp/RenderDoc/iree-run-mlir_2020.02.05_18.34.55_frame0.rdc
RDOC 216822: [10:34:55]          rdcfile.cpp( 244) - Log     - Opening RDCFile /tmp/RenderDoc/iree-run-mlir_2020.02.05_18.34.55_frame0.rdc
RDOC 213313: [10:34:55]   target_control.cpp( 767) - Log     - Got a new capture: 0 (frame 0) (time 1580927695) 0 byte thumbnail
QTRD 213313: [10:34:55]              unknown(   0) - Warning - QImage::scaled: Image is a null image
RDOC 216822: [10:34:55]             core.cpp(1707) - Log     - Removing device frame capturer for 0x000000000230CF30
RDOC 216822: [10:34:55]             core.cpp( 478) - Log     - 'Leaking' unretrieved capture /tmp/RenderDoc/iree-run-mlir_2020.02.05_18.34.55_frame0.rdc
RDOC 213313: [10:34:55]          rdcfile.cpp( 244) - Log     - Opening RDCFile /tmp/RenderDoc/iree-run-mlir_2020.02.05_18.34.55_frame0.rdc
RDOC 213313: [10:34:55]          rdcfile.cpp( 244) - Log     - Opening RDCFile /tmp/RenderDoc/iree-run-mlir_2020.02.05_18.34.55_frame0.rdc
RDOC 213313: [10:34:55]             core.cpp(  49) - Log     - Not enabling API validation during replay
RDOC 213313: [10:34:55]             core.cpp(  54) - Log     - Using default GPU replay selection algorithm
RDOC 213313: [10:34:55]             core.cpp(  63) - Log     - Replay optimisation level: Balanced
...
RDOC 213313: [10:34:55]  vk_device_funcs.cpp(2569) - Log     - Dev Ext 0: VK_KHR_8bit_storage (1)
RDOC 213313: [10:34:55]  vk_device_funcs.cpp(2569) - Log     - Dev Ext 1: VK_KHR_16bit_storage (1)
...
VK_NVX_device_generated_commands (3)
RDOC 213313: [10:34:55]  vk_device_funcs.cpp(2569) - Log     - Dev Ext 71: VK_NVX_multiview_per_view_attributes (1)
RDOC 213313: [10:34:56]         vk_debug.cpp(1692) - Log     - nVidia GPU detected - no counters available
(Segmentation fault here)
```

and logs from the headless compute program:

```
I iree/tools/run_mlir_main.cc:459] Evaluating all functions in module for backend 'vulkan'...
I iree/tools/run_mlir_main.cc:482] Creating target backend driver 'vulkan'...
I iree/hal/vulkan/renderdoc_api.cc:108] StartFrameCapture
EXEC @simple_mul
I iree/tools/run_mlir_main.cc:336] result[0]: Buffer<float32[4]>
4xf32=3 6 9 12
I iree/hal/vulkan/renderdoc_api.cc:116] EndFrameCapture
```

To sanity check headless compute in general, I recorded a capture of [SaschaWillem's computeheadless example](https://github.com/ScottTodd/Vulkan/commit/f1fe0d8b358964e0563ff7235fe45c4b67899d9b), which loads without issues.

It's entirely possible that

* Our headless compute program is doing weird things (like how we [load Vulkan symbols](https://github.com/google/iree/blob/master/iree/hal/vulkan/dynamic_symbols.h) - the GUI program [links against Vulkan statically](https://github.com/google/iree/blob/3fce4cdbe008c9db1f5d05f76c82820f7a4918d8/iree/samples/vulkan/vulkan_inference_gui.cc#L17-L24))
* I'm starting/stopping recording at the wrong times
* I'm misusing RenderDoc in some other way

...but the validation layers don't complain and I would hope that RenderDoc would not crash.

## Steps to reproduce

Here are three captures: [renderdoc_captures.zip](https://github.com/baldurk/renderdoc/files/4161348/renderdoc_captures.zip)

1) `computeheadless` is the sanity check from SaschaWillems/Vulkan. That's working as expected.
2) `vulkan_inference_gui` is our GUI. It loads, and shows our compute in the middle with some related graphics calls around it.
3) `iree-run-mlir` is our headless program. That capture crashes RenderDoc.

You can also try building/running by following our [Getting Started docs](https://github.com/google/iree/blob/master/docs/getting_started_on_linux.md) if you really want, and I can also update those and/or get more parts building with CMake instead of Bazel, or on Windows as needed.

## Environment

* RenderDoc version: 1.6 [(0e7f772596035137416be01766c2d61205efc63e)](https://github.com/baldurk/renderdoc/commit/0e7f772596035137416be01766c2d61205efc63e)
* Operating System: Linux (Debian), I could test on Windows but haven't yet
* Graphics API: Vulkan 1.1.126

**Comment by baldurk** [comment]
I see the problem. RenderDoc needs a graphics queue to function but there's no graphics queue included in the capture because all the work happens on a compute-only queue. Sascha Willems' computeheadless sample still uses a graphics/compute queue for its work it seems.

It should be easy enough to fix since the hard work is ensuring a graphics queue is allocated on device create, but if you need a workaround in the short term using a graphics + compute queue anywhere in the captured reason should fix it. Even if you just do a dummy empty `vkQueueSubmit`.

**Comment by baldurk** [comment]
That commit should ensure the queue is always present, and allows me to open your headless capture successfully. It'll be included in the next nightly build, let me know if it works for you.

**Comment by ScottTodd** [comment]
Thanks for the fast response!

If I change [this part of my project code](https://github.com/google/iree/blob/7b1347701e20d9f9afa7520245139965f1f40658/iree/hal/vulkan/vulkan_device.cc#L92-L96) to allow VK_QUEUE_GRAPHICS_BIT, I can record and view captures with headless compute on RenderDoc 1.6. Here's a sample: [rdoc_with_graphics_queue.zip](https://github.com/baldurk/renderdoc/files/4162231/rdoc_with_graphics_queue.zip).

I built RenderDoc locally with your commit and I still see the crash. This branch is not entered for me:
```
if(m_Queue == VK_NULL_HANDLE && m_Device != VK_NULL_HANDLE && m_QueueFamilyIdx > 0)
```

* `m_Queue` is `VK_NULL_HANDLE` (that's fine)
* `m_Device` is _not_ `VK_NULL_HANDLE` (that's fine)
* `m_QueueFamilyIdx` *is* 0. In fact, I don't actually see where it could be set to non-zero?

**Comment by ScottTodd** [comment]
Oh, and if I comment out `&& m_QueueFamilyIdx > 0` in that check, I _am_ able to view the captures that were crashing.

**Comment by baldurk** [comment]
Whoops, my bad. That test is indeed wrong, it should be `m_QueueFamilyIdx != ~0U` to check that a valid queue family index was selected (which should always be the case). I added that test after testing the crashing case, then tested with one of the other captures which worked regardless...

**Comment by ScottTodd** [comment]
:+1: thanks, https://github.com/baldurk/renderdoc/commit/380e7715acc73c193a620719f3c17cf11aa28dbd fixes the crash for me and I'm able to record/view captures with headless compute now (without needing to update the `VK_QUEUE_GRAPHICS_BIT` handling in my project).

**Comment by tuket** [comment]
Hi,
I see this issue has been closed but I can't figure out how to capture my compute-only program.

My code looks like this:
```cpp
int main()
{
	RENDERDOC_API_1_4_1* rdoc_api = NULL;
	if (HINSTANCE mod = GetModuleHandleA("renderdoc.dll"))
	{
		printf("BE\n");
		pRENDERDOC_GetAPI RENDERDOC_GetAPI =
			(pRENDERDOC_GetAPI)GetProcAddress(mod, "RENDERDOC_GetAPI");
		int ret = RENDERDOC_GetAPI(eRENDERDOC_API_Version_1_4_1, (void**)&rdoc_api);
		assert(ret == 1);
	}

        // all my Vulkan code goes here
       // ......

	if (rdoc_api) {
		rdoc_api->EndFrameCapture(NULL, NULL);
	}
}
```

And then I just launch my program from RenderDoc. Am I missing something?

**Comment by baldurk** [comment]
Please do not comment on bugs from over a year ago that have been closed and fixed. If you have a bug to report please open a new issue and fill out the issue template.
