### ISSUE TITLE
Vulkan debug Utils tag set via vkSetDebugUtilsObjectTagEXT not displayed

### ISSUE THREAD

**Issue by SaschaWillems** [baldurk/renderdoc#1714]
## Description

A tag for a shader module using ```vkSetDebugUtilsObjectTagEXT``` does not seem to be displayed anywhere in RenderDoc. A name set by ```vkSetDebugUtilsObjectNameEXT``` works fine and is displayed as expected.

## Steps to reproduce

Set a tag for a shader module using ```vkSetDebugUtilsObjectTagEXT``` :

```cpp
std::vector<uint8_t> buffer = vkb::fs::read_shader(file);
VkDebugUtilsObjectTagInfoEXT info = {VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_TAG_INFO_EXT};
info.objectType                   = VK_OBJECT_TYPE_SHADER_MODULE;
info.objectHandle                 = (uint64_t) shader_stage.module;
info.tagName                      = 1;
info.tagSize                      = buffer.size() * sizeof(uint8_t);
info.pTag                         = buffer.data();
vkSetDebugUtilsObjectTagEXT(device->get_handle(), &info);
```

(For this example I'm trying to pass the source glsl code as a tag for a shader to be displayed in RenderDoc)

If you run an application with the above code through RenderDoc, no tag info is displayed for that shader module:

![image](https://user-images.githubusercontent.com/10283127/74082802-eb668580-4a5d-11ea-92ca-b4e98aa89794.png)

Source for the sample: https://github.com/SaschaWillems/Vulkan-Samples/blob/debug_utils/samples/extensions/debug_utils/debug_utils.cpp

Capture: 
[vulkan_samples_debug_utils_capture.zip](https://github.com/baldurk/renderdoc/files/4173993/vulkan_samples_debug_utils_capture.zip)

## Environment

* RenderDoc version: Tested with stable 1.6 and latest nightly (1.7, 2020-02-06)
* Operating System: Windows 10
* Graphics API: Vulkan 1.x
* Vulkan SDK: 1.1.130.0

**Comment by baldurk** [comment]
`vkSetDebugUtilsObjectTagEXT` is not required to be processed by any implementation, it's implementation defined which tag values are actually used, any others may be discarded. For RenderDoc it does not support attaching GLSL after the fact to a shader module so this tag value is ignored.
