### ISSUE TITLE
Render to mipmap in OpenGL is wrong displayed

### ISSUE THREAD

**Issue by SchwandtTobias** [baldurk/renderdoc#172]
If I render into certain mipmap levels of a texture, RenderDoc (v0.27) displays the final image like a pyramide. It writes only into the first mipmap level. In the image is shown mipmap level zero but every color should be in its own mipmap level.

![mipmap](https://cloud.githubusercontent.com/assets/10806141/12532620/b04ae3c8-c218-11e5-8eb7-dd1dbbf3cc61.jpg)

**Comment by baldurk** [comment]
Can you give any more information, like which API are you using. I assume you're using OpenGL from the bottom-left corner. How do you set up the mip rendering?

Do you have a repro sample (either logfile or ideally runnable program) that you could share with me?

**Comment by SchwandtTobias** [comment]
I could share a capture log. Would this be helpful? Otherwise I would send you some code snippets.

**Comment by baldurk** [comment]
Yes please, both capture log and code snippets would really help. The capture log might show enough in this case but it doesn't always represent how a program got to the captured state, for which code snippets would also help. If you don't want to share them publicly you can email me directly.

**Comment by SchwandtTobias** [comment]
I have send you an email. :-)

**Comment by baldurk** [comment]
Thanks! I've pushed a fix up that works on the capture and it should sort the problem for you, but it's worth double checking.

**Comment by SchwandtTobias** [comment]
Good that I could help. In my case, the capturing works fine now. Thank you!
