### ISSUE TITLE
Python extension debugging

### ISSUE THREAD

**Issue by sindney** [baldurk/renderdoc#1721]
## Description

I'm trying to write a RenderDoc UI extension. Some operation must happen on another thread (for example we don't want to hang the ui when doing some background calculations), like this: 

```
pyrenderdoc.Replay().BlockInvoke(myCallback)
```

this is totally fine. But when i wrote something  wrong in the myCallback function, the error log  in RenderDoc's Diagnostic Log window reports the same issue no matter what: 

```
Error   - Traceback (most recent call last):
Error   - File "C:/xxx\__init__.py", line 227, in export
Error   - pyrenderdoc.Replay().BlockInvoke(myCallback)
Error   - SystemError: <built-in method BlockInvoke of qrenderdoc.ReplayManager object at 0x0000023113E53870> returned NULL without setting an error
```

so it's hard to tell what i did wrong only with this little information. Is there any walkaround or hint when programming extension functions like this? thanks

## Steps to reproduce

Just use this in your extension and write some code with runtime error

```
pyrenderdoc.Replay().BlockInvoke(myCallback)
```

## Environment

* RenderDoc version: 1.6
* Operating System: Windows10
* Graphics API: D3D12

**Comment by baldurk** [comment]
The python context that extensions were executing in was missing some handling to properly catch exceptions on the replay thread and rethrow them.

Note that I strongly recommend against using the replay thread for anything other than replay work. It's not a generic background worker thread and should only be used for safely accessing the underlying replay interface (which is not thread safe). Using it for general tasks could cause a blockage as many UI operations will require access to the replay thread to function.
