### ISSUE TITLE
DirectX error when i want to capture a log of FIFA18 game.

### ISSUE THREAD

**Issue by XezXey** [baldurk/renderdoc#1726]
## Description
I want to capture the log of FIFA18 game and i did following your tutorial : https://www.youtube.com/watch?v=aBC2zmw4PCY&t and some error have raised. I will explain in more details in the Repro section.

## Steps to reproduce

I'm trying to capture a log by using a renderdoc on FIFA 18. There's an error as below
1. The first error that happend is seems renderdoc try to open the FIFA 18 by using DirectX11 which is my PC is not support then i go to change the DirectX version in FIFAsetup
2. Then an error below is occured.
I did following on the youtube video. I don't know do i miss something or what i've to do before open the FIFA18 with renderdoc? But i still can see the overlay and the tab for capturing frames at the first time i run the renderdoc.
Here is some screenshot

Here is my GPU and DxDiag information
![image](https://user-images.githubusercontent.com/15362184/74587898-b4c6d700-502a-11ea-9f45-8226bee80e34.png)

Here's the renderdoc screenshot while an error occured
![image](https://user-images.githubusercontent.com/15362184/74587926-efc90a80-502a-11ea-8ff1-0856f1d1b57d.png)

Here's the FIFA 18 screen
![image](https://user-images.githubusercontent.com/15362184/74587934-02dbda80-502b-11ea-9d24-2cbc9090dd72.png)

Thank you for your help

## Environment

* RenderDoc version: v1.6
* Operating System: Windows 10
* Graphics API: DirectX 12

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
