### ISSUE TITLE
Unsupported protocol : custom_swig cannot download while compile renderdoc1.4

### ISSUE THREAD

**Issue by XezXey** [baldurk/renderdoc#1727]
## Description
I'm trying to compile a renderdoc1.4 but the problem is it try to download when the URL_HASH check is failed.
Here is the download attempt 
![image](https://user-images.githubusercontent.com/15362184/74591141-0e89ca00-5048-11ea-8651-5a8e76b3ac04.png)
and it show that the libcurl seem not support protocol
![image](https://user-images.githubusercontent.com/15362184/74591204-63c5db80-5048-11ea-99df-2c06f1e76060.png)
But the link that you provided still can access. I already check it. So how can i solve this problem?

## Environment

* RenderDoc version: 1.4
* Operating System: ubuntu 18.04
* Graphics API: -

**Comment by XezXey** [comment]
It's 1.x from github repos not 1.4

**Comment by baldurk** [comment]
This is not a renderdoc bug, since as you've mentioned the URL is valid. It looks like cmake is using a version of libcurl compiled without ssl support, whether that's an issue with cmake or libcurl I don't know but you'd need to diagnose the problem on your system yourself.

**Comment by XezXey** [comment]
For those who have a problem like me you have to build and install cmake again by using your system-curl not cmake-curl
Also you can following this solution It works fine for me.
https://stackoverflow.com/questions/44633043/cmake-libcurl-was-built-with-ssl-disabled-https-not-supported
