### ISSUE TITLE
Global Hook: "Can't launch 64-bit renderdoccmd from '敲摮牥潤⹣汤屬敲摮牥潤捣摭攮數攀摲捯搮汬'"

### ISSUE THREAD

**Issue by tmek** [baldurk/renderdoc#1728]
## Description

I'm using RenderDoc 64-bit v1.6 - 15 Jan, 2020  stable binary release.  

When trying to use global hook I get messages like this with what seem to be Asian characters.

`RDOC 030888: [22:34:58]    win32_process.cpp(1514) - Error   - Can't launch 64-bit renderdoccmd from '敲摮牥潤⹣汤屬敲摮牥潤捣摭攮數攀摲捯搮汬'`

I saw a post about secure boot causing an issue, which i'm not sure if my machine has, but I do know all our machines hard drives are encrypted with Windows bit-locker, could that have something to do with it?  

## Environment
* RenderDoc version: 1.6 built from https://github.com/baldurk/renderdoc/commit/0e7f772596035137416be01766c2d61205efc63e
* Operating System: Windows 10 Version	10.0.17763 Build 17763
* Graphics API:

**Comment by baldurk** [comment]
This has been fixed since v1.6, if you run a nightly build it should work correctly.
