### ISSUE TITLE
Error "Capture requires extension 'VK_EXT_tooling_info' which is not supported"

### ISSUE THREAD

**Issue by doomtr666** [baldurk/renderdoc#1731]
## Description
I'm trying to debug a simple Vulkan triangle application (which is buggy). Capture overlay seems to work, but when I close the application I got a popup with this error message: "Failed to open capture for replay: current hardware not supported or incompatible with captured hardware".

## Steps to reproduce
1) launch my app with renderdoc
2) capture a frame
3) close the app / try to open the capture with renderdoc

## Environment

* RenderDoc version: 1.6
* Operating System: Windows 10
* Graphics API: Vulkan 1.2

I've attached the diagnositc log and a capture:
[rdoc_err.log](https://github.com/baldurk/renderdoc/files/4227208/rdoc_err.log)
[capture.zip](https://github.com/baldurk/renderdoc/files/4227232/capture.zip)

**Comment by baldurk** [comment]
There was a bug in v1.6 where use of `VK_EXT_tooling_info` in an application would be available during capture but then fail to be ignored properly on replay when nothing else provides the extension. Either temporarily disable use of that extension or run a recent nightly build of RenderDoc where the bug has been fixed.

I also note that you are forcing use of a specific GPU on replay. While this is possible it's highly inadvisable for Vulkan where captures from one GPU are rarely portable to another. It's strongly recommended that you leave the GPU selection as default and choose the physical device you want to use in your application - RenderDoc will then use the same physical device on replay.

**Comment by doomtr666** [comment]
Ok, just try a nightly build and it works fine, thank you ! 
(and for the tip about forcing a GPU for capture)
