### ISSUE TITLE
Vertex shader debugging produces wrong output for some packed data

### ISSUE THREAD

**Issue by skarolewics** [baldurk/renderdoc#1736]
## Description

Running vertex shader debugging on vertex 0 for the demo d3d11_vertex_attr_zoo produces output that does not match what the mesh viewer reports. It appears that the register mapping for the output is incorrect.

Output from debugging with RenderDoc v1.2:
![vs_debug_v1_2](https://user-images.githubusercontent.com/2215106/75101851-33c28f00-5598-11ea-8112-2d5b4b070d6c.png)

Output from debugging with latest, aacf14820124e7b801116ebbea6225797aca791e:
![vs_debug_latest](https://user-images.githubusercontent.com/2215106/75101854-476df580-5598-11ea-8580-74b2baee91ee.png)

## Steps to reproduce

1. Launch the demos program from RenderDoc
2. Run the D3D11_Vertex_Attr_Zoo demo and take a capture
3. Select the draw, go to the mesh viewer, and right click vertex 0 to debug
4. Execute shader to the end and observe the output values

## Environment

* RenderDoc version: commit aacf14820124e7b801116ebbea6225797aca791e
* Operating System: Windows 10
* Graphics API: D3D11

**Comment by baldurk** [comment]
This was a mistake in leaving array variables as arrays even when we're selecting an individual element. That commit should fix it.
