### ISSUE TITLE
Duplicate GL_KHR_debug extension

### ISSUE THREAD

**Issue by xPaw** [baldurk/renderdoc#1739]
## Description

Launching an app through renderdoc crashed because there's an GL extension listed twice

## Steps to reproduce

We use OpenTK, and listed all extensions into a dictionary, which caused a duplicate key, specifically with `GL_KHR_debug`.

See https://github.com/SteamDatabase/ValveResourceFormat/compare/6c5bb02ca3cb818fe61be363316a7c20266aa77c...322b4f5017d9d922e6e337c268df2d8d4a5bc90c for example code (and the fix).

It boils down to this:
```csharp
var count = GL.GetInteger(GetPName.NumExtensions);
for (var i = 0; i < count; i++)
{
    var extension = GL.GetString(StringNameIndexed.Extensions, i);
    // Printing this list will reveal that there's GL_KHR_debug listed twice
}
```

## Environment

* RenderDoc version: 1.6_64 and 2020_02_24_4673f29d_64
* Operating System: Windows 10 1909
* Graphics API: OpenGL
* Driver: nvidia 442.19

**Comment by xPaw** [comment]
A simple repro by using https://github.com/gkv311/wglinfo/releases

`.\renderdoccmd.exe capture .\wglinfo64.exe`

In the dump you can see where its listed twice:
> GL_KHR_blend_equation_advanced_coherent, GL_KHR_context_flush_control,
**GL_KHR_debug**, GL_KHR_no_error, GL_KHR_parallel_shader_compile,
GL_KHR_robust_buffer_access_behavior, GL_KHR_robustness,
WGL_EXT_swap_control, GL_EXT_debug_tool, **GL_KHR_debug**, GL_EXT_debug_label,
GL_EXT_debug_marker, GL_GREMEDY_frame_terminator, GL_GREMEDY_string_marker.

Looking at the code in gl_driver.cpp, seems to be caused by the following:
1. `WrappedOpenGL::BuildGLExtensions()` adds GL_KHR_debug
2. It's added again `ctxdata.glExts.push_back("GL_KHR_debug");` in `WrappedOpenGL::ActivateContext`

**Comment by baldurk** [comment]
It wasn't quite the duplication you found - `BuildGLExtensions` builds up a whitelist of extensions which is then applied to the driver-reported extensions, but indeed the second case where the extension is reported even if the driver doesn't support it should not have added duplicates. That commit should fix it.
