### ISSUE TITLE
Error creating swap chain with non-hooked device

### ISSUE THREAD

**Issue by vinz243** [baldurk/renderdoc#174]
Hi,
I tried to run RenderDoc on Star Wars Battlefront and it fails. I tried first with normal hook it did not work, with global hook I get this in logs and no overlay:

```
RENDERDOC: [18:29:54] core.cpp( 245) - Log - RenderDoc v0.26 x64 (ebe442d1d8059d4dd076deff8f35978ac580319d-official) capturing application
RENDERDOC: [18:29:55] win32_libentry.cpp( 70) - Log - Loading into C:\Program Files (x86)\Steam\steamapps\common\STAR WARS Battlefront\starwarsbattlefront.exe
RENDERDOC: [18:29:55] hooks.cpp( 49) - Log - Loaded and hooked into kernel32.dll, PID 8356
RENDERDOC: [18:29:55] hooks.cpp( 49) - Log - Loaded and hooked into d3d11.dll, PID 8356
RENDERDOC: [18:29:55] hooks.cpp( 49) - Log - Loaded and hooked into d3d9.dll, PID 8356
RENDERDOC: [18:29:55] hooks.cpp( 49) - Log - Loaded and hooked into dxgi.dll, PID 8356
RENDERDOC: [18:29:55] hooks.cpp( 49) - Log - Loaded and hooked into opengl32.dll, PID 8356
RENDERDOC: [18:30:02] dxgi_wrapped.cpp( 563) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RENDERDOC: [18:30:02] dxgi_wrapped.cpp( 82) - Error - Creating swap chain with non-hooked device! 
```

ReShade.me framework works well though
Thanks in advance

**Comment by baldurk** [comment]
So it seems like battlefront is creating the swapchain in a way I haven't encountered before and isn't getting caught by my DXGI code. The fix could be simple or complex depending on what is happening exactly.

I don't have the game so I can't investigate this myself, I'm going to rename this issue in case someone else who can help narrow down the cause sees it and can help.

**Comment by vinz243** [comment]
Thanks for the info! I guess i'll have to wait then

**Comment by vinz243** [comment]
But since ReShade works, they might have foun the workaround, no?

**Comment by baldurk** [comment]
I don't know exactly how ReShade works, and from a quick look it's not open source so I can't check. I've not used it but from the description of the project it seems like they could probably skip a bunch of things I do since the scope of the project is smaller. It might not even care about the swapchain actually.

**Comment by vinz243** [comment]
OK, thanks! Will have to wait. A pity, this game soo much deserved an in depth analysis.One of the best looking game ever with best

**Comment by baldurk** [comment]
It's possible this was caused by battlefront using a newer version of DXGI or D3D11 maybe that wasn't supported until recently. Without more information I can't reproduce, so you could test on v0.30 to see if you have more success.

**Comment by vinz243** [comment]
Thanks I will try it in a few days once I get home

Le mar. 2 août 2016 à 10:18, Baldur Karlsson <notifications@github.com> a
écrit :
