### ISSUE TITLE
Constant buffers do not display values in shader viewer

### ISSUE THREAD

**Issue by skarolewics** [baldurk/renderdoc#1742]
## Description

When debugging a shader, the constant buffers display all error values. This occurs regardless of whether reflection info exists for the shader.  It appears to be unique to this display - the constant buffer displays values correctly when viewed from the pipeline state viewer, and CB fetches during debugging are correct as well.

![debug_cbs](https://user-images.githubusercontent.com/2215106/75325339-81a3f500-582d-11ea-90e9-83cf877b9a0c.png)

## Steps to reproduce

1. Launch the demos program from RenderDoc
2. Select the D3D11_CBuffer_Zoo demo
3. Take a capture and load it
4. Select a white pixel in the draw call, and debug the pixel
5. Observe the values in the "Constants & Resources" pane.

## Environment

* RenderDoc version: 4673f29da17810f0674584c7720dae3fc38ad7af
* Operating System: Windows 10
* Graphics API: D3D11

**Comment by baldurk** [comment]
Fixed in that commit, as well as some row/column major mistakes.
