### ISSUE TITLE
Is Vulkan 1.2 without the bufferDeviceAddress feature supported

### ISSUE THREAD

**Issue by Vincent-P** [baldurk/renderdoc#1744]
## Description

I want to use some Vulkan 1.2 features in a small personal project, but the latest AMD driver reports `bufferDeviceAddress`, `bufferDeviceAddressCaptureReplay` and `bufferDeviceAddressMultiDevice` features to false.
I can launch my project with renderdoc and take a capture, but renderdoc cannot create a logical device when opening the capture.

## Steps to reproduce

- Take a capture of an application with a `VkPhysicalDeviceVulkan12Features` structure in the `pNext` chain of `VkDeviceCreateInfo`
- Open it

## Environment

* RenderDoc version: RenderDoc_2020_02_24_4673f29d_64
* Operating System: Window 10 Pro
* Graphics API: Vulkan
* Amd Catalyst driver: 20.1.3
* Gpu: AMD RX 5700 XT

**Comment by baldurk** [comment]
I can't reproduce with only your steps. I added an empty `VkPhysicalDeviceVulkan12Features` to a demo on `VkDeviceCreateInfo`'s `pNext` chain and the capture loads fine. I'm testing on windows 10, on 20.2.1 (slightly newer driver) on an RX 480.

Can you explain what happens when the capture loads? Does it crash, or produce an error message - if so which error message and can you upload or paste the diagnostic log?

**Comment by Vincent-P** [comment]
Here is the diagnostic log  [RenderDoc_2020.02.26_15.52.44.log](https://github.com/baldurk/renderdoc/files/4256368/RenderDoc_2020.02.26_15.52.44.log).

**Comment by Vincent-P** [comment]
Here is a minimal program that have this problem: https://gist.github.com/Vincent-P/c2cd4f0062218cac17faff5583cc4aa9 .
Does your `VkPhysicalDeviceVulkan12Features` have `bufferDeviceAddress` set to `false` if you use `vkGetPhysicalDeviceFeatures2`?

EDIT: In the gist I linked, if the define PUTS_VK12FEATURES is set to 0 renderdoc works fine

**Comment by baldurk** [comment]
Yes all the buffer device address features are FALSE for me as only RADV supports that feature on AMD at the moment, the official drivers don't.

I find vulkan.hpp code very hard to read - what is the `PUTS_VK12FEATURES` block doing - does that query the available features and then enable them all unconditionally? So you mean that if you don't do that, it works?

**Comment by Vincent-P** [comment]
The block just adds a Vulkan12Features to the structure chain.

```cpp
#if PUT_VK12FEATURES
    VkPhysicalDeviceVulkan12Features vk12features;
    Vk:PhysicalDeviceFeatures2 features;
    features.pNext = &vk12features;
    vkGetPhysicalDeviceFeatures2(physical_device, &features);
#else
    VkPhysicalDeviceFeatures2 features;
    vkGetPhysicalDeviceFeatures2(physical_device, &features);
#endif
```

**Comment by Vincent-P** [comment]
From what I understand of this code: https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/vulkan/wrappers/vk_device_funcs.cpp#L2721
Renderdoc seems to always enable the `bufferDeviceAddress` if the API version if >= 1.2?

**Comment by baldurk** [comment]
Yeh that definitely seems broken - debugging through my code it's setting that feature unconditionally for me too. Now I'm not sure why I couldn't reproduce it, since the driver on my end should also be returning `VK_ERROR_FEATURE_NOT_PRESENT` too.

**Comment by baldurk** [comment]
That commits adds an availability check before setting `bufferDeviceAddress`. I can't test it exactly for unknown reasons, but it should do the trick.

**Comment by Vincent-P** [comment]
I compiled it and it works great thanks!

**Comment by tbotting** [comment]
Was experiencing the same issue with the latest stable release on a 5700XT GPU. Vulkan 1.2, latest AMD drivers. 

Nightly build of 'v1.x branch @ a39569e9, 2020-03-01' does fix this issue, for anyone else out there experiencing the same issues. 

Thanks for your hard work :) @baldurk
