### ISSUE TITLE
[Bug] Mesh viewer is blank for Print Screen captures *only*

### ISSUE THREAD

**Issue by mcclure** [baldurk/renderdoc#1746]
## Description

![image](https://user-images.githubusercontent.com/277318/75509701-919b1080-59b6-11ea-9377-27b3a510c883.png)

Instead of mesh there is grey Void

## Steps to reproduce

I tell RenderDoc to launch my application and auto-capture on frame 3 or 4 or something. I scroll through the Event Browser and select a particular draw call. I open the Mesh Viewer pane. It shows me my mesh, yay expected behavior ✨

I tab back into my still-running application. I adjust the camera and take another capture using the "print screen" button. Again I scroll through the Event Browser, select a draw call, and open the mesh viewer pane. There is no mesh, only gray 😞

I save the capture. I close RenderDoc and my application. I open RenderDoc. I open the saved capture. *Now* my meshes display. ✨

I try testing again. I close RenderDoc and my application. I take a capture with Print Screen. The bug reproduces, no mesh 😞

## Analysis

The problem does not occur for captures taken automatically by the Launch Application pane and does not occur with captures loaded with Open Capture. It only happens for captures taken with Print Screen after the application has been started.

Because the same capture that could not display meshes was able to display meshes when I saved the capture and reloaded it, I conclude the problem is with the mesh viewer UI and the capture was fine.

I have the saved capture. I can send it to you but suspect you will find only that it is a perfectly good capture. I would prefer to send it via email or something rather than post it publicly on github if this is possible.

## Environment

I am running a newly downloaded Renderdoc v1.6 on Windows 10 10.0.18363 Build 18363. AMD Radeon R9 390 Series graphic card, "Radeon Software Version 20.2.1" (I think this is driver version??). My application uses OpenGL and it is drawing into a framebuffer vended from the Oculus API.

I have not tried rebooting the computer.

**Comment by baldurk** [comment]
This is unfortunately a known AMD driver bug. With OpenGL captures, any time you open a second capture (all displays will be super "zoomed in" essentially, so what you're seeing in your screenshot is an extremely zoomed version of the checkerboard background.

Unfortunately until a fix lands in AMD's drivers the only known workaround is to restart RenderDoc every time you open a capture. I've checked with AMD and there isn't another hack in the meantime :(.

Also for next time please use the bullet list template for the environment, it's a bit easier to parse.
