### ISSUE TITLE
GPU crash/hang/segfault when opening renderdoc capture

### ISSUE THREAD

**Issue by simonvanderveldt** [baldurk/renderdoc#1750]
## Description

Opening a renderdoc capture captured on the same machine crashes/hangs my GPU.
The only thing I see in my logs is this line from the kernel
```
Mar 01 11:33:45 [kernel] GpuWatchdog[13667]: segfault at 0 ip 0000557a284d5fa2 sp 00007fd8665ae600 error 6 in chrome[557a2458f000+7287000]
```
I did get these lines in the renderdoc output on the terminal, don't know if they matter or not
```
[0301/114543.275:ERROR:network_change_notifier_win.cc(157)] WSALookupServiceBegin failed with: 8
[0301/114545.584:ERROR:gpu_process_transport_factory.cc(1031)] Lost UI shared context.
[0301/114545.590:ERROR:command_buffer_proxy_impl.cc(130)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
[0301/114547.276:WARNING:cert_verify_proc_win.cc(104)] Unknown error -2146762482 mapped to net::ERR_FAILED
```
## How to reproduce
Open one of the renderdoc files from the link and watch your machine hang

## More details
Capture was made for a graphics corruption issue in Heroes of the Storm in wine on Linux using DXVK with mesa >= 19.3.0 but a capture made with mesa 19.2.8 which doesn't have this corruption also results in the same hang, so the hang after opening a renderdoc capture doesn't seem to be related to the graphics corruption.
See https://gitlab.freedesktop.org/mesa/mesa/issues/2458 for more details.

The most recent captures are https://gitlab.freedesktop.org/mesa/mesa/uploads/9cee2420585a3f4591a897e6d351ba39/mesa-19.2.8-wine64-preloader_2020.03.01_11.45_frame5351.rdc and https://gitlab.freedesktop.org/mesa/mesa/uploads/fbde32a9fcba12e789f91fa2c6bdfcce/mesa-20.0.0-wine64-preloader_2020.03.01_11.28_frame2863.rdc

The hang also happened to someone else (Samuel) who tried to open the capture, see https://gitlab.freedesktop.org/mesa/mesa/issues/2458#note_408842

## Environment

* RenderDoc version: 1.6
* Operating System: Linux: gentoo, kernel 4.15.17, mesa 19.2.8/20.0.0 using RADV
* Graphics API: Vulkan
* GPU: RX480

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by simonvanderveldt** [comment]
@baldurk Why is it relevant who wrote the program? I just want to troubleshoot issues with Vulkan calls.

Also irrespective of which program was traced I don't think it is correct behavior for Renderdoc to crash and even worse hang a GPU when opening a trace it created.

**Comment by zao** [comment]
@simonvanderveldt There is limited developer bandwidth and spending it on software which cannot be changed is less valuable than improving the tool for developer-facing scenarios.

Such software might be misusing the APIs or may not be prepared to handle the restrictions in the API that RenderDoc presents, and without the software developer to adapt to this, the only real resort you have is accumulating hacks in RenderDoc to handle software that is outside of scope in the first place.

While there may be some legitimate uses for instrumenting software you don't control (educational, debugging other infrastructure around it like drivers or OS), the majority of such attempts are people trying to lift assets for illicit use.
