### ISSUE TITLE
crash when I open my captured rdc file

### ISSUE THREAD

**Issue by z00318884** [baldurk/renderdoc#1751]
## Description

Crash when opening the RDC file I captured.
The place where the crash occurred is the following code：
Serialise_glPointParameteri（...）
{
...
  if(IsReplayingAndReading())
  {
    GL.glPointParameteri(pname, param);///crash here
  }
}
According to the stack information,It is replay “glPatchParameteriEXT“，then to Serialise_glPointParameteri.
The source code is：
    case GLChunk::glPatchParameteriEXT:
    case GLChunk::glPatchParameteriOES:
    case GLChunk::glPointParameteri: return Serialise_glPointParameteri(ser, eGL_NONE, 0);

why glPatchParameteriEXT return Serialise_glPointParameteri(ser, eGL_NONE, 0);？
Instead of  Serialise_glPatchParameteri？
## Steps to reproduce

open the rdc file I captured.(The rdc file contain "glPatchParameteriEXT" API)

## Environment

* RenderDoc version: Nightly builds  v1.x branch @ 9d3e4dc5, 2020-02-20
* Operating System: android
* Graphics API: gles

**Comment by baldurk** [comment]
I don't see any link to the rdc file mentioned in your repro steps, please provide it so that your steps to reproduce can be followed.

**Comment by z00318884** [comment]
You can just check in file "gl_driver.cpp" :
"case GLChunk::glPatchParameteriEXT:
case GLChunk::glPatchParameteriOES:
case GLChunk::glPointParameteri: return Serialise_glPointParameteri(ser, eGL_NONE, 0);"
Is it reasonable？
or need to be changed to 
“case GLChunk::glPatchParameteriEXT:
 case GLChunk::glPatchParameteriOES:
 return Serialise_glPatchParameteri(ser, eGL_NONE, 0);
case GLChunk::glPointParameteri: return Serialise_glPointParameteri(ser, eGL_NONE, 0);“

I'm confused why you wrote that。

**Comment by baldurk** [comment]
Your steps to reproduce say "open the rdc file I captured." but I don't have that capture file so I can't do that.

If you're reporting a bug please provide steps that I can follow to reproduce the problem so it can be investigated, if that happens when opening a capture file then please share the capture file.

**Comment by zhouhuamin** [comment]
> You can just check in file "gl_driver.cpp" :
> "case GLChunk::glPatchParameteriEXT:
> case GLChunk::glPatchParameteriOES:
> case GLChunk::glPointParameteri: return Serialise_glPointParameteri(ser, eGL_NONE, 0);"
> Is it reasonable？
> or need to be changed to
> “case GLChunk::glPatchParameteriEXT:
> case GLChunk::glPatchParameteriOES:
> return Serialise_glPatchParameteri(ser, eGL_NONE, 0);
> case GLChunk::glPointParameteri: return Serialise_glPointParameteri(ser, eGL_NONE, 0);“
> 
> I'm confused why you wrote that。

I also confused about there.I think it's a bug.

**Comment by baldurk** [comment]
If you're encountering a crash then please provide a clear explanation of what the problem is and reproducible steps I can follow to replicate the crash and investigate the bug.

**Comment by baldurk** [comment]
Closing this issue due to lack of repro steps and inactivity.
