### ISSUE TITLE
Shader viewer CB registers are incorrect for partial float4 entries

### ISSUE THREAD

**Issue by skarolewics** [baldurk/renderdoc#1754]
## Description

For constant buffers that pack multiple values into a single float4, the registers listed in the shader viewer do not specify the correct swizzle values.

## Steps to reproduce

1. Capture d3d11_cbuffer_zoo from the demos program
2. Debug a pixel from the draw call
3. Observe the CB registers. Screenshot below, where for example both c and d are listed in cb0[2].xy. d is actually in cb0[2].zw
![cb_registers](https://user-images.githubusercontent.com/2215106/75834340-88bc8d00-5d70-11ea-9e34-5ae07f58df41.png)

## Environment

* RenderDoc version: 2ca43b82bdcd978e06cf0049ffb3ad3048e14bb5
* Operating System: Windows 10
* Graphics API: D3D11

**Comment by baldurk** [comment]
This got broken accidentally when I added support for matrix debug variables, should be fixed in that commit.
