### ISSUE TITLE
Crash on Intel HD

### ISSUE THREAD

**Issue by nicovanbentum** [baldurk/renderdoc#1756]
## Description

RenderDoc seems to crash when I try to load any capture from an OpenGL application I'm working on. It works fine on my desktop (Nvidia card) but crashes on my laptop (Intel HD520).

## Steps to reproduce

Zip file with rdc, log and dump file can be found [here](https://drive.google.com/open?id=1A4AZmNbJsPgpVbxXTDYXTT12JgVjq6cv) . The application can be found [here](https://drive.google.com/open?id=1mC6zm4Wc3-kQuQU08tkdLlgI16O20Wa5) , it is a debug build so it might be slow.

I open the .rdc capture in RenderDoc, the loading bar gets about halfway then RenderDoc closes and the RenderDoc bug reporter pops up.

## Environment

* RenderDoc version: Version 1.6 (built from [0e7f7725](https://github.com/baldurk/renderdoc/commit/0e7f772596035137416be01766c2d61205efc63e))
* Operating System: Windows 10 Enterprise LTSC
* Graphics API: OpenGL 4.5
* GPU: Intel HD520

**Comment by baldurk** [comment]
Looking at the minidump, this is a known Intel driver bug I've seen before. It returns an invalid length for a reflected shader property which then leads to a crash allocating space for the string.

Your driver version is over 2 years old, from the start of 2018. I'd recommend trying again with an updated driver as it may have fixed the bug. At least on my Intel machine with similar GPU (same generation) but up to date drivers, the capture loads correctly.
