### ISSUE TITLE
Vulkan: VkDescriptorSetLayoutBinding::binding is ignored

### ISSUE THREAD

**Issue by TiemoJung** [baldurk/renderdoc#176]
Hi,

VkDescriptorSetLayoutBinding::binding is not taken into account, which will lead to crashes when a descriptor set is sparsely defined.

**Comment by baldurk** [comment]
Oh wow, good catch! Thank you for letting me know, I will get this fixed.

**Comment by baldurk** [comment]
Should be fixed now, at least from a simple test case (I defined a descriptor set layout with binds 0, 1, 2, 3 and 9 and it worked fine).

**Comment by TiemoJung** [comment]
Hi,

its working for our cases just fine now.
Tanks
