### ISSUE TITLE
RenderDocCmd does not read config settings

### ISSUE THREAD

**Issue by skarolewics** [baldurk/renderdoc#1763]
## Description

When running tests from renderdoccmd, the config settings are not loaded, so any API properties or other state dependent on config settings will differ from running with the UI.

## Steps to reproduce

1. Add `"d3d12ShaderDebugging": "true"` to your UI.config "ConfigSettings" block
1. Run `renderdoccmd.exe test functional -t "D3D12_CBuffer_Zoo"`
2. Note that "Debugged output matched as expected" does not appear in the test output

## Environment

* RenderDoc version: c6a1a23adbf7568ce4001c400b0577048f31ed38
* Operating System: Windows 10
* Graphics API: D3D12

**Comment by baldurk** [comment]
This is intentional. As the file suggests, it is for UI configuration only so it's not loaded in renderdoccmd.
