### ISSUE TITLE
serialization of `vkCreateDescriptorUpdateTemplateEntry` modifying const object

### ISSUE THREAD

**Issue by allanmac** [baldurk/renderdoc#1765]
My app silently crashes when invoking `vkCreateDescriptorUpdateTemplate`.

Stepping through a debug version of RenderDoc shows that the serialization of the `vkCreateDescriptorUpdateTemplate` function will serialize and **mutate** the create info's `VkDescriptorUpdateTemplateEntry` entries.

This results in a fault.

The create info structure and its entries appear to be properly `const` all the way through RenderDoc up until `void DoSerialise(SerialiserType &ser, VkDescriptorUpdateTemplateEntry &el)`.

I see there is a fair bit of documentation above this routine so maybe there was a strong reason for doing this?  Or perhaps it was code leftover from a previous debugging session?

It's worth noting that the CreateInfo and its entries are on the stack in my application.  

Maybe that helped to reveal this issue.

Commenting out the offending lines resolved the issue and the frame capture appears to be correct.

```
diff --git a/renderdoc/driver/vulkan/vk_serialise.cpp b/renderdoc/driver/vulkan/vk_serialise.cpp
index 3ce5767ae..9f61b7189 100644
--- a/renderdoc/driver/vulkan/vk_serialise.cpp
+++ b/renderdoc/driver/vulkan/vk_serialise.cpp
@@ -4049,8 +4049,8 @@ void DoSerialise(SerialiserType &ser, VkDescriptorUpdateTemplateEntry &el)
     uint64_t stride = el.stride;
     ser.Serialise("offset"_lit, offset);
     ser.Serialise("stride"_lit, stride);
-    el.offset = (size_t)offset;
-    el.stride = (size_t)stride;
+    // el.offset = (size_t)offset;
+    // el.stride = (size_t)stride;
   }
 #if DISABLED(RDOC_APPLE)
   else
```
## Steps to reproduce

Here is the snippet that expands out into the creation of a number of update templates:

```
  //
  // DUT -- create descriptor update templates
  //
  VkDescriptorUpdateTemplateCreateInfo dutci = {
    .sType                      = VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO,
    .pNext                      = NULL,
    .flags                      = 0,
    .descriptorUpdateEntryCount = 0,
    .pDescriptorUpdateEntries   = NULL,
    .templateType               = VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET,
    .descriptorSetLayout        = VK_NULL_HANDLE,
    .pipelineBindPoint          = VK_PIPELINE_BIND_POINT_COMPUTE,
    .pipelineLayout             = VK_NULL_HANDLE,
    .set                        = 0
  };

#define SPN_VK_DUT_CREATE(id)                                                                      \
  dutci.descriptorUpdateEntryCount = ARRAY_LENGTH_MACRO(SPN_VK_DUTE_NAME(id));                     \
  dutci.pDescriptorUpdateEntries   = SPN_VK_DUTE_NAME(id);                                         \
  dutci.descriptorSetLayout        = instance->dsl.named.id;                                       \
  vk(CreateDescriptorUpdateTemplate(environment->d,                                                \
                                    &dutci,                                                        \
                                    environment->ac,                                               \
                                    &instance->dut.named.id))

#undef SPN_VK_DS_EXPAND_X
#define SPN_VK_DS_EXPAND_X(idx, id, desc) SPN_VK_DUT_CREATE(id);

  SPN_VK_DS_EXPAND();
```

## Environment

This fails on the stable (1.6), nightly and master versions.

I'm running on a Debian variant.

NVIDIA 440.26.

**Comment by baldurk** [comment]
Yeh casting away the const is deliberate but setting the values should be protected so it only happens when loading the capture, that was what was missing. The macros for serialisation normally handle that but I have a few places where I forcibly serialise size_t as uint64_t to ensure 32-bit/64-bit captures are compatible and I forgot to add the extra protection here.

That commit should fix the issue, thanks for the report!
