### ISSUE TITLE
Vulkan: "Vulkan capture is not configured. Click here to set up Vulkan capture." error showing up incorrectly

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#177]
It seems like RenderDoc gets confused if it is launched from a Windows Share.

In my case I have separate dev & test workstations. I use the former to build the binaries. The result directory is then exposed as a Window Share. If I now launch the RenderDoc executable from the other machine, RenderDoc warns me about Vulkan capture not being configured, as presented on the picture below:

![image](https://cloud.githubusercontent.com/assets/9154207/13113658/371b33aa-d590-11e5-832c-e1b10b26f0f7.png)

Letting RenderDoc do his duties with the registry does not do any good, as the note does not go away.

**Comment by baldurk** [comment]
Ah I guess this must be a case of two distinct paths that point to the same files, and when doing comparisons I'm not properly unifying them.

As long as the registry entry is pointing to the right files, one way or another, you can safely ignore the message. I'll fix the false positive.

**Comment by kbiElude** [comment]
Yeah, it works fine except the false warning :)

**Comment by baldurk** [comment]
Right, that should do the trick I think. Converts any network drive to a UNC path and uses that everywhere consistently.

**Comment by kbiElude** [comment]
Issue resolved, thanks!
