### ISSUE TITLE
Debian linux: Collected callstack always displays ??? symbols for those functions within the main executable

### ISSUE THREAD

**Issue by kakashidinho** [baldurk/renderdoc#1773]
## Description

 I'm facing a strange issue with the way callstack is recorded and resolved in Debian linux.
It always displays `???` symbols for those symbols within the main executable, while the symbols in the shared objects are fine.

 I won't be able to share the capture file since the callstack requires the actual libraries files to resolve the symbols. And I won't be able to share the libraries either. 

## Steps to reproduce

* Enable "Collect Callstacks".
* Launch the app "helloworld".
* Capture the frame.
* Resolve symbols.
* All the symbols within the app are displayed as `???`.
* Symbols from libraries such as Qt are fine.
* From the look of `/proc/self/maps`, its content is:
  *  `00400000-05cdc000 r-xp 00000000 00:51 12974779926     helloworld`
  *  Which means the base address of `helloworld` program is 0x400000.
* The callstack's addreses in this example is:
  * 0x400001
  * 0x400003
  * Qt addreses ...
* When symbols are resolved, it becomes:
  * ???
  * ???
  * QtEvent::resize() ...

## Environment

* RenderDoc compiled from source: b0f0dad7fdfd72e0c6f659ec074e6212c29450d2
* Operating System: Debian 9.
* Graphics API: OpenGL.
* The executable was compiled on a Debian 7 machine.

## More detailed on my investigations

* I looked at `linux_callstack.cpp` source code.
* When renderdoc tries to resolve the symbols, it deducts the value of callstack's address by the base address of the executable:
  * `0x400001 - 0x400000 = 1`
  * Then this offset is passed to addr2line in `linux_callstack.cpp` like this:
    * `addr2line -fCe hellowork 0x1`
  * However this produces `???` result, i.e. invalid offset.
  * But if I mofify `linux_callstack.cpp` to not subtract the callstack's address, but pass the actual value to add2line command:
    * `addr2line -fCe hellowork 0x400001`, then it returns correct function name and line number such as `BoxFrame::render() + 1`
* The thing is if the address in within a shared object, then an absolute address won't work while a deducted offset will.
* I'm not sure this is linux version specific issue or not.

**Comment by baldurk** [comment]
Your repro steps mention a program "helloworld", can you please share that so that I can follow them as this is quite likely to be program-specific. If you can't share your program you could try building a simple test application like [gears3d](https://github.com/gears3d/gears3d). If the problem replicates there then we can use that as a test case.

**Comment by kakashidinho** [comment]
Here is the capture file: [https://1drv.ms/u/s!Au3ABfehsKzjgpAJ4eDrjeMswlT_tA?e=HcULp0](https://1drv.ms/u/s!Au3ABfehsKzjgpAJ4eDrjeMswlT_tA?e=HcULp0)
Here is the gears3d executable: [https://1drv.ms/u/s!Au3ABfehsKzjgpAKZAeOzHXVAXAnMQ?e=i6myfS](https://1drv.ms/u/s!Au3ABfehsKzjgpAKZAeOzHXVAXAnMQ?e=i6myfS)

I have just noticed that this only happens if I compile the executable on Debian 7. It doesn't happen if the executable is compiled on Debian 9.

For reference, this is Debian 9 version of the gears3d executable [https://1drv.ms/u/s!Au3ABfehsKzjgpAMQ9JYfAlPqofCKQ?e=PzqKKL](https://1drv.ms/u/s!Au3ABfehsKzjgpAMQ9JYfAlPqofCKQ?e=PzqKKL). This executable's symbols can be resolved in renderdoc.

I think it has something to do with the ELF's LOAD header's VirtAddr. Running `readelf -l gears3d` on the 2 versions of gears3d, I noticed a difference in the LOAD header's VirtAddr.

**Comment by baldurk** [comment]
The problem is that the debian 7 built executable is not a PIE (position independent executable). In the case of non-PIE code I guess addr2line expects the absolute addresses rather than the RVA normally provided.

I'll see if there's a way to fix this, but I believe code should generally always be built as PIE nowadays which is probably why it works fine on Debian 9 with a newer compiler that generates PIE by default. I'd recommend doing that, or manually enabling PIE on older debian versions.

**Comment by baldurk** [comment]
That commit should fix things to handle non-PIE code with the different offset, at least it works on the test executables you sent.

**Comment by kakashidinho** [comment]
Thanks
