### ISSUE TITLE
Never save a capture

### ISSUE THREAD

**Issue by GeorchW** [baldurk/renderdoc#1788]
## Description

My general workflow when debugging graphics is as follows:

1. Write some graphics code
2. Start the application to try it out
3. Wonder why it doesn't work
4. Open RenderDoc and capture a frame to analyze the problem (through app integration)
5. Change the code to fix it
6. Go to 2

I'm not sure whether that's how its supposed to be used, but when I use it that way, I open and close a lot of RenderDoc instances (one per cycle). I never want to save any of the captures, however, each time I close an instance, it asks me whether I want to save the capture. Can you add an option "never ask again", or something similar in the settings?

## Environment

* RenderDoc version: v1.7
* Operating System: all
* Graphics API: all

**Comment by baldurk** [comment]
I'm not going to add this. I'm not aware of any other program that allows you to destroy unsaved data without a prompt, even on an option. Adding such an option would be very error-prone as some users might click it by accident or without realising what it does, and others might misinterpret it as "don't ask me again this session".

If explicitly discarding captures is a bottleneck for your workflow you can always make a custom local build and disable that prompt.

**Comment by GeorchW** [comment]
> I'm not aware of any other program that allows you to destroy unsaved data without a prompt, even on an option.
That depends on your definition of "user data". Firefox asks you (or at least used to ask) whether you want to save your tabs for later, with an option to never (or always) save any tabs. 

I see how users might click it by accident, but could there be a setting in the settings window? It's very unlikely that users are going to accidentally open the settings, find that checkbox and tick it.

Or is my workflow just extremely rare? To me, it seems like the obvious way to use RenderDoc, but I'm happy to learn about others.

Btw I promise to make the PR by myself if you greenlight this :-)

**Comment by baldurk** [comment]
The example of Firefox isn't directly comparable because that's not any data being permanently lost. The webpages are still there even if the tab is closed.

Unfortunately it's quite possible for users to enable things without really understanding exactly what they do - I've seen it happen. The potential risk of someone accidentally losing their data far outweighs the negligible improvement of saving you a prompt here and there. It's common enough to make temporary captures but I'm not aware of anyone else who considers the dialog to be a significant burden.

You're free to make the change locally as I suggested, but if you open a PR it will be rejected. I didn't close the issue because I don't have time to implement the change - the implementation itself is quite straightforward.

**Comment by GeorchW** [comment]
My impression is that similar to how the webpage is still there because the web server still exists, the information of a capture is still there because the application still exists, too. It (usually) just takes a key press to get the capture back, similar to how you (usually) just need the link to get the web page back. But if that's your final decision, that's fine.

**Comment by Ceffa93** [comment]
I'd like to second this, as I find quite frustrating the lack of this feature.

I understand your reasons for not wanting it, but I would't consider negligible the amount of iteration time and the loss in experience quality this causes.
I don't have any usage statistics to claim this, but based on my experience I think many people use RenderDoc extensively to aid the development process, without caring about storing the data. I think supporting them is worth the risk of having a user that wants to save the data AND mistakenly sets a wrong option (which is disabled by default and clearly documented) AND forgets to manually save AND is in a situation where the data cannot be reproduced easily.

Just my honest feedback.
Thank you for keeping up the great work!

**Comment by Const-me** [comment]
For anyone else struggling with the lack of that option, note the following command instantly quits RenderDoc without any questions asked:
`taskkill /f /im qrenderdoc.exe`
