### ISSUE TITLE
Vulkan buffer type 11 but only 0, 7, 9, 10 are allowed

### ISSUE THREAD

**Issue by jimon** [baldurk/renderdoc#1794]
## Description

When trying to open a capture from recently released vulkan game the following error appears in the log:
```
RDOC 012708: [18:27:23] vk_resource_funcs.cpp( 324) - Warning - Can't create buffer covering memory allocation ResourceId::183
RDOC 012708: [18:27:23] vk_resource_funcs.cpp( 214) - Error   - Trying to bind Buffer ResourceId::199 to memory ResourceId::183 which is type 11, but only these types are allowed: 0, 7, 9, 10
RDOC 012708: [18:27:23] vk_resource_funcs.cpp( 214) - Error   - This is most likely caused by incompatible hardware or drivers between capture and replay, causing a change in memory requirements.
```

## Steps to reproduce

- Set env var `ENABLE_VULKAN_RENDERDOC_CAPTURE` to `1`.
- Run Doom Eternal and attach RenderDoc.
- Press F12 in the game to make a capture.
- Try to open the capture.

## Environment

* RenderDoc version: 1.7 / 1.8 55437ee0
* Operating System: Windows 10 1909 18363.720
* Graphics API: Vulkan
* GPU driver: NVIDIA v445.75

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by jimon** [comment]
@baldurk Ok. Just want to mention that under EU Directive 2009/24 part 14 "A person having a right to use a computer program should not be prevented from performing acts necessary to observe, study or test the functioning of the program, provided that those acts do not infringe the copyright in the program"
https://eur-lex.europa.eu/legal-content/EN/TXT/?qid=1435057541496&uri=CELEX:32009L0024

So please consider that observing and studying programs is legal in European Union. But yes, using the knowledge to create competing products is patent/copyright infringement.
