### ISSUE TITLE
Saving a texture does not save it at the specified location

### ISSUE THREAD

**Issue by lobneroO** [baldurk/renderdoc#1795]
## Description

Saving a texture does not save it at the specified location (neither the default location, nor the one chosen in the file chooser dialog).
No entry in the Diagnostic Log has been made.

I found them in the RenderDoc executable folder (C:/Program Files/RenderDoc/ for me), but they didn't contain the correct (or any) file extension in their name. E.g. saving something as a Png with name "Depth" would create the file C:/Program Files/RenderDoc/Depth whereas I would have expected it to store the file in my chosen default folder with the extension, like path/to/default/Depth.png

## Steps to reproduce

Open a capture and select a texture. Save the texture to file. Look into the specified directory, which should not containt it. Look into the folder of the executable, where you can find the (extensionless) file.

## Environment

* RenderDoc version: 1.7 (built from a56af589)
* Operating System: Windows 10
* Graphics API: DirectX 11
* GPU: Nvidia RTX 2080

I had used RenderDocs internal issue report feature, you can find that report here:
https://renderdoc.org/bugreporter/report/qpZqcLf4b39XvE

**Comment by baldurk** [comment]
I followed your repro steps and the texture saved correctly for me. Can you please give more detail and be precise in your description of the steps you take. You gloss over what you're doing at the step "save the texture to file" - are you typing in the path manually, or are you using the file browser? Both work for me. You mention a "chosen default folder" or a "default location" but I don't know what you're talking about, as there is no default folder for saving textures.

Also I don't understand how the file could be written under Program Files unless RenderDoc is running as administrator since otherwise the file should fail to write. Are you running RenderDoc as admin?

**Comment by lobneroO** [comment]
With Default Location I meant the Settings in the "General" section:
Default save directory for captures (though I realize now, this is not for textures, but the renderdoc internal captures. sorrry)
I didn't write a file path manually, since I assumed the "default location" to be used, which was obviously wrong in my thinking. I retried with the file chooser and it works now.

I couldn't write the screenshots at first, which is why I restarted it as an admin and loaded the previously created capture and then saved the texture. Otherwise I wouldn't run RenderDoc as an admin.

It boils down to me assuming the wrong things and expecting a different output, sorry. 
It would make it easier to see (for me) though, if there was a label displaying the "calculated" file path beneath the File Path box. Like when you don't enter any filepath, it is obviously the Executable filepath, simply entering "test.png" would output "C:/Program Files/RenderDoc/test.png". On the other hand, if I didn't have the wrong assumption of the "default file path" to start with, perhaps I would have realized what was up.

Thanks for your time

**Comment by baldurk** [comment]
There's no deliberate "calculated" file path. I suppose there's a bug that if you don't properly put a path in that dialog then it continues to try and write anyway and I guess maybe uses the current working directory. I'll add a check that a proper absolute path to an existing directory is selected.

**Comment by baldurk** [comment]
That commit will prevent an invalid path being specified when saving.
