### ISSUE TITLE
Crashes when capturing frames for game DOOM Eternal

### ISSUE THREAD

**Issue by yjaelex** [baldurk/renderdoc#1796]
## Description
DOOM Eternal will crashes when try to capture one frame.
Turns out capturing will issue a bunch of invalid vulkan API calls;
vkCmdCopyImageToBuffer() with no memory object bound to dstBuffer;
or vkCmdCopyBuffer() with no memory object bound to srcBuffer;
or Map a buffer with no memory object bound to it.

## Steps to reproduce
Open renderdoc v1.7 launch window; choose DOOMEternalx64vk.exe
Launch game with 4K ultra nightmare mode;
Choose campaign menu to start a new campaign.
Press F12 and it will crash in a minute.

## Environment

* RenderDoc version: v1.7 64bit and v1.6 64bit
* Operating System: Windows 10
* Graphics API: Vulkan
* GPU:  AMD 5700XT 8G

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
