### ISSUE TITLE
Feature request - copy resource debug name to clipboard

### ISSUE THREAD

**Issue by tom-seddon** [baldurk/renderdoc#1798]
## Description

When viewing a shader that has a D3D11 debug name, it appears to be impossible to to copy that debug name to the clipboard. You might want to use this name in code when investigating something that you've seen in RenderDoc, and it would be nice to be able to guarantee you've transcribed it correctly.

Its name in the Shader section of the Pipeline State is not selectable, only clickable.

Its name in the Resource Inspector is not selectable.

Its name in the `ID3D11Resource::SetDebugName` section of the Resource Initialisation Parameters section of the Resource Inspector is not selectable.

Its name is not shown in the shader disassembler.

You can't copy its name from the shader disassembler tab.

I've mainly found this annoying with shaders, but I suppose being able to copy any resource's debug name would be nice.

## Environment

* RenderDoc version: Version v1.7 (built from a56af589)
* Operating System: Version 1903 (OS Build 18362.720)
* Graphics API: Direct3D11 (running over Remote Desktop, if that makes a difference...)

**Comment by baldurk** [comment]
> Its name in the `ID3D11Resource::SetDebugName` section of the Resource Initialisation Parameters section of the Resource Inspector is not selectable.

I'm not sure what you mean by this. I can select the row, and while it's not _editable_ so you don't get a cursor, using `ctrl+c` while that row is selected gives something like: `"Name MyShaderName"` on the clipboard.

Also alternatively for any resource if you click the `Rename Resource` button then the editable text box to is populated with the current name, which you can also copy-paste from.

I don't think this merits having a dedicated UI button, so these methods seem sufficient for me. Please clarify if you're talking about something else, and I've misunderstood.
