### ISSUE TITLE
Vulkan: HGRAM_TILES_PER_BLOCK is too high, given Vulkan 1.0 limit minmaxes

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#180]
As per Vulkan spec, minimum value permitted for the _maxComputeWorkGroupInvocations_ limit is 128.As per spec, this value corresponds to:

```
maxComputeWorkGroupInvocations is the maximum total number of compute shader invocations in a single local work group. 
```

However, minmaxtile.comp defines local work-group size to be:

```
layout (local_size_x = HGRAM_TILES_PER_BLOCK, local_size_y = HGRAM_TILES_PER_BLOCK) in;
```

where

```
#define HGRAM_TILES_PER_BLOCK  32u
```

which gives us 1024 invocations per work-group. This causes issues on older generation of our hardware. Would it be OK to reduce this number to 10 or 11 so that it's conformant with the spec, please?

Thanks!

**Comment by baldurk** [comment]
Yes that should be fine, one block 32x32 full of 64x64 pixel tiles still only covers 2048^2 textures, so after that we start scaling up the vkCmdDispatch() dimensions. Reducing the size of a block will just mean larger dispatch dimensions and a larger intermediate texture - no problem there.

I'll make this change and double check everything is working, just in case :).

**Comment by baldurk** [comment]
Works OK for me with the reduced count, so I'm fine with this. You can double check it's working on the older hw then close.

**Comment by kbiElude** [comment]
That looks good to me, thanks!
