### ISSUE TITLE
Assertion failure VK_ERROR_DEVICE_LOST and VK_TIMEOUT

### ISSUE THREAD

**Issue by raywan** [baldurk/renderdoc#1800]
## Description
**NOTE**:  Screenshot and diagnostic log are attached below.

Loading a Vulkan capture on v1.7 breaks UI rendering and other features. This was first experienced from my own Vulkan application but I also loaded an example app from [SaschaWillems/Vulkan](https://github.com/SaschaWillems/Vulkan), specifically the push constants example which can be seen in the logs. Switch between tabs and resize the window to see effects on UI.

Looking at the logs, we can see that there are many assertion failure:
```
RDOC 015088: [14:12:55]          vk_core.cpp( 278) - Error   - Assertion failed: '(vkr) == (VK_SUCCESS)' (vkr=VK_ERROR_DEVICE_LOST, VK_SUCCESS=VK_SUCCESS)
```

Furthermore, when I click different events in the Event Browser, another assertion failure comes up in the log.

```
RDOC 015088: [14:13:04]          vk_core.cpp( 493) - Error   - Assertion failed: '(vkr) == (VK_SUCCESS)' (vkr=VK_TIMEOUT, VK_SUCCESS=VK_SUCCESS)
```

## Steps to reproduce
1. Open RenderDoc 1.7 and go to Launch Application
2. Select a Vulkan app in Executable Path e.g. something from [SaschaWillems/Vulkan](https://github.com/SaschaWillems/Vulkan)
3. Click Launch
4. Capture a Frame
5. Exit example application
6. Load capture
7. Switch between tabs, resize window, click events in the Event Browser

## Environment

* RenderDoc version: 1.7
* Graphics API: Vulkan

System information outputted by NVIDIA control panel

```
NVIDIA System Information report created on: 03/28/2020 14:15:23

[Display]
Operating System:	Windows 10 Home, 64-bit
DirectX version:	12.0 
GPU processor:		GeForce RTX 2070 with Max-Q Design
Driver version:		445.75
Driver Type:		DCH
Direct3D API version:	12
Direct3D feature level:	12_1
CUDA Cores:		2304 
Core clock:		1185 MHz 
Memory data rate:	12.00 Gbps
Memory interface:	256-bit 
Memory bandwidth:	384.06 GB/s
Total available graphics memory:	16333 MB
Dedicated video memory:	8192 MB GDDR6
System video memory:	0 MB
Shared system memory:	8141 MB
Video BIOS version:	90.06.3C.00.55
```

![Capture](https://user-images.githubusercontent.com/3066609/77830496-4849f800-70ff-11ea-8243-d620291eb8b1.PNG)

[20200328_DIAGNOSTIC.log](https://github.com/baldurk/renderdoc/files/4397653/diagnostic.log)

**Comment by baldurk** [comment]
The log indicates that the Intel GPU is being used for replay which means it was also used for capture. I don't think Sascha Willems' demos do any sophisticated physical device selection - if you force it to use the NV gpu does that work? I think you can use `-gpu 0` and `-gpu 1` command line parameters and check what the overlay says is being used.

I also can't easily tell when that Intel driver version is from, but the CTS release listed is a fair bit older so I'd suggest checking to see if a newer Intel driver is available.

**Comment by raywan** [comment]
Hello, I just tried your suggestion and passed `-gpu 1` as an argument. That seems to resolve the issue. The screenshot attached shows that Intel GPU is not being used. Regarding Intel drivers, I usually keep my PC up-to-date and from what I'm reading online that should also keep Intel graphics drivers up-to-date as well. Just to make sure, I went ahead and downloaded this utility https://www.intel.com/content/www/us/en/support/detect.html to scan for driver updates. With that, I don't see any graphics driver updates available. 

Is the situation a _real_ RenderDoc issue or should I just be mindful of what physical device is being used next time? To be honest, I had assumed that my NVIDIA GPU was being used this entire time so I didn't bother carefully checking, which is an oversight on my part. If this isn't a real issue then I apologize for wasting your time and thank you for taking a look regardless.

![Capture](https://user-images.githubusercontent.com/3066609/77834973-5c9ded00-711f-11ea-8bb0-157a893cc1be.PNG)

**Comment by baldurk** [comment]
This looks like a driver bug then. If you're on a laptop then it wouldn't surprise me if you're stuck on older intel drivers because it seems like most laptop vendors cripple the driver updates and don't allow timely intel drivers to be installed. You could check in dxdiag for the actual reported intel driver version and search to see when it was released.

With your own vulkan applications I'd recommend always picking the discrete GPU over the integrated GPU, Sascha's demos I believe always picks physical device 0 by default. With a recent loader (which should come with the recent nvidia driver you have) then the system GPU preference order is used on windows, which means that the GPU connected to the display (i.e. the integrated GPU) is the first in the list.
