### ISSUE TITLE
Crash when importing renderdoc using Python3.7

### ISSUE THREAD

**Issue by MixKCet** [baldurk/renderdoc#1801]
## Description

Python3.7 interpreter crashes when attempting to import a freshly built renderdoc.pyd

I've ensured that:
- I'm running the same Python architecture as the build (both Win32 and x64 fail)
- Both the Debug/Release builds fail
- The freshly built qrenderdoc.exe and binary installed stable build can run the python script

## Steps to reproduce

- Install Python3.7
- Build renderdoc1.x (nightly or stable)
- Write simple Python script importing renderdoc
- Point "os.environ["PATH"]" to output folder, and append pymodules to sys.path
- Run

## Environment

* RenderDoc version: Nightly/Stable
* Operating System: Windows 10, x64
* Graphics API: Unrelated

**Comment by MixKCet** [comment]
Sorry for the duplicate issue, found a response here:
[https://github.com/baldurk/renderdoc/issues/1519#issue-492996548](url)

Since the Python 3.6 interpreter is no longer distributed as a binary for Windows, would it be possible to make renderdoc work with Python3.7?

**Comment by baldurk** [comment]
You can still download binaries of python 3.6.8, only newer versions seem to have no windows binaries. You can also download the source for newer versions of 3.6 and build them yourself, or you could build renderdoc against python 3.7. I have no plans at the moment to change the version of python renderdoc is built against by default.
