### ISSUE TITLE
Bug - Simple GL program with just a glClear has a error with Vertex Array

### ISSUE THREAD

**Issue by Ihaa21** [baldurk/renderdoc#1802]
## Description

I have a GL 4.0 program which does nothing but call glClear on the default frame buffer. I get a error in RenderDoc 1.7 saying "5 API High Miscellaneous 3007 glGetVertexAttribfv failed because the specified vertex attribute can not be queried for generic attribute 0 (GL_INVALID_OPERATION)". The API call that is being highlighted is glClear. I tried binding a default VAO that is empty prior to calling glClear but it made no difference. If I setup a DebugMessageCallback in my application, I do not get a error.

## Steps to reproduce

I setup a GL program that runs the following code in its main loop:

    glBindVertexArray(OpenGLState->DefaultVao);
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    glClearColor(1, 1, 0, 1);
    glClear(GL_COLOR_BUFFER_BIT);

I also attached a RDC with the error.

## Environment

* RenderDoc version: Occurs on mainline 1.7 as well as Nightly Build 1.7 e22ed4b8
* Operating System: Windows 7
* Graphics API: OpenGL 4.3
* GPU: Radeon RX 580

[VAO Error.zip](https://github.com/baldurk/renderdoc/files/4399407/VAO.Error.zip)

**Comment by baldurk** [comment]
The error I think is a mistaken error reported by AMD's driver while in renderdoc's internal state gathering. Either way the error shouldn't appear in the UI when it's from renderdoc's internal code, so that commit should hide it.
