### ISSUE TITLE
Vulkan: Missing image usage flag bit when setting up the font table

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#181]
VkImageCreateInfo descriptor that RenderDoc uses to set up the font table is as below:

```c
VkImageCreateInfo imInfo = {
			VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO, NULL, 0,
			VK_IMAGE_TYPE_2D, VK_FORMAT_R8_UNORM,
			{ width, height, 1 }, 1, 1, VK_SAMPLE_COUNT_1_BIT,
			VK_IMAGE_TILING_OPTIMAL,
			VK_IMAGE_USAGE_SAMPLED_BIT,
			VK_SHARING_MODE_EXCLUSIVE,
			0, NULL,
			VK_IMAGE_LAYOUT_PREINITIALIZED,
		};
```

Later on, the application transfers the image to VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL image layout:

```
VkImageMemoryBarrier barrier = {
				VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER, NULL,
				0, 0,
				VK_IMAGE_LAYOUT_PREINITIALIZED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
				VK_QUEUE_FAMILY_IGNORED, VK_QUEUE_FAMILY_IGNORED,
				Unwrap(m_TextAtlas),
				{ VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 }
			};
```

This action is illegal given that the image cannot be used as a transfer destination as per information specified at create info. The fix is simple: you need to also pass VK_IMAGE_USAGE_TRANSFER_DST_BIT when setting up the image.

I'm going to propose a pull request in a few minutes which fixes this.

**Comment by kbiElude** [comment]
(by the way, this would've been caught by validation layers.. :-) )

**Comment by baldurk** [comment]
Nice catch! :). Looks like I forgot to update the image creation flags when I made the image OPTIMAL tiled and copied into it, rather than LINEAR and samples straight out of host visible memory that I mapped directly.

I'll re-test with the validation layers, I was clean not too long ago (barring mistaken/buggy/ignorable messages).

**Comment by baldurk** [comment]
Thanks!
