### ISSUE TITLE
OOM allocating upload buffer memory during replaying an .rdc trace

### ISSUE THREAD

**Issue by alexv1n** [baldurk/renderdoc#1816]
## Description

Recent change (929bcfc) modified the behavior  of selecting which memory type/heap is chosen for resource allocations. Before this change, Upload type allocations would come out of host (system) memory on our environment. After this change it comes out of device (vram) memory. Our device has 8GB of VRAM and some heavier traces now fail to replay because of OOM. You do have a code to exclude some limited heaps of less than 512MB. But this does not fully solve OOM cases.

## Steps to reproduce

I can share a sample .rdc that makes over 8GB or allocations that as of commit 929bcfc now come out of GPU memory and fail to replay. But basically our GPU declares two heaps - host memory (VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT) of 32GB in size and device (VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT | VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT) of 8GB. The commit mentioned earlier now favors the heap with VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT because of this change: https://github.com/baldurk/renderdoc/commit/929bcfc0ce6b10e9479b842a86cff6b353bff2db#diff-c551a9e8d8a78a189169dadacd7bd655R48

So, now allocations come out of (limited) device memory and heavy traces can no longer be replayed.

I think a more flexible fall-back mechanism need to be implemented. Like if the allocation from the preferred device local memory fails, try to repeat the allocation out of host-visible memory heap?

## Environment

* RenderDoc version: fc639643355cdd90aa512e39a9842af987418d91
* Operating System: Linux
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Yes please share the capture with me so that I can properly reproduce the issue.

**Comment by alexv1n** [comment]
Shared with your privately (you should have received an email with a link to download it by now)
