### ISSUE TITLE
feature : “GL_SAMPLER_EXTERNAL_OES” not support

### ISSUE THREAD

**Issue by z00318884** [baldurk/renderdoc#1817]
## Description
Hi，I want to ask a feature question.
here has some error：
ADRD 003350: [10:44:09] gl_program_iterate.cpp( 943) - Error   - Unhandled uniform type 'GL_SAMPLER_EXTERNAL_OES'
ADRD 003350: [10:44:09] gl_program_iterate.cpp( 547) - Error   - Unhandled uniform type 'GL_SAMPLER_EXTERNAL_OES'

and in xml file，I can't searched my  shader as below
“{"
#extension GL_OES_EGL_image_external : require
precision mediump float;
uniform samplerExternalOES CC_Texture0;
varying lowp vec4 v_diffuse;
varying mediump vec2 v_texture0;
void main()
{
lowp vec4 local_0 = texture2D(CC_Texture0, v_texture0);
lowp vec4 local_1 = v_diffuse * local_0;
gl_FragColor = local_1;
}
"};”

so  GL_OES_EGL_image_external and GL_SAMPLER_EXTERNAL_OES need to surpport？

## Environment

* RenderDoc version:1.2.8
* Operating System: android
* Graphics API: gles

**Comment by baldurk** [comment]
RenderDoc does not support `GL_OES_EGL_image_external`. Your application must properly check for extensions to see if they're available before using them, otherwise it is invalid use of GL.
