### ISSUE TITLE
Failed to capture the Google 3D model using Renderdoc

### ISSUE THREAD

**Issue by lichard001** [baldurk/renderdoc#1818]
Description

After opening renderdoc, select the chrome GPU process and inject. The api shows that it has been activated, but it will disappear in an instant. After repeating three times, the activation will fail and stop in the fourth time. I repeated this several times, and when I rebooted the computer, it was the same.Has anyone encountered the same problem as me? I would be very grateful if anyone can help.

I added this command to the chrome browser shortcut
(C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog")

Environment

* RenderDoc version: v1.6 v1.7
* Operating System: win10 64bit
* GPU:GTX960M
* Chrome:80.0.3987.163

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
