### ISSUE TITLE
Search for bind in pipeline state viewer

### ISSUE THREAD

**Issue by skarolewics** [baldurk/renderdoc#1819]
## Description

With bindless tables, the number of resources listed in the pipeline state viewer can get out of hand. Even with the filtering to used/non-empty entries, there are still a lot of resources to scroll through to find a specific entry. Having a button to search for a specific bind, by register space and shader register, would help when you know about where you're looking (such as when shader debugging an error with a wrong resource array index).

## Steps to reproduce

1. Create a shader with a very large bindless table
2. Fill it in with a lot of entries
3. Pick one of the entries and find the needle in the haystack

## Environment

* RenderDoc version: latest commit
* Operating System: Windows 10
* Graphics API: D3D12

**Comment by baldurk** [comment]
Is this still relevant now that bindless feedback is supported on D3D12 as well? You can still have a lot of resources used in some rare cases, and in theory you could search for other things like resources by name, but now that bindless tables aren't all listed exhaustively this feels like quite low utility and unless you disagree I'm going to close this as the underlying motivation has been addressed in a better way.

**Comment by skarolewics** [comment]
I think with bindless feedback, this is pretty low priority, feel free to close.

The only useful scenario I can think of that wouldn't be solved is when you're accessing a resource with a dynamic index, there's a bug in that logic, and seeing all resources (or being able to filter a range) could help narrow down the problem. But that's a pretty niche issue that has alternatives to track down (such as shader debugging the logic).
