### ISSUE TITLE
Failed to open capture for replay: Network I/O operation failed

### ISSUE THREAD

**Issue by zhangpaopao0215** [baldurk/renderdoc#1827]
## Description

i use renderdoc to capture and game asphalt 9 on the android device sumsung note 10(qualcomm gpu Adreno 640 non root device). i can capture it . but when i loading the trace file. it report the following error
Android PID 6293: [08:39:11] remote_server.cpp(410) - Log - File received.
Android PID 6293: [08:39:16] posix_network.cpp(312) - Warning - Timeout in recv
Android PID 6293: [08:39:16] streamio.cpp(415) - Warning - Error reading from socket
Android PID 6293: [08:39:16] remote_server.cpp(894) - Log - Closing active connection from 127.0.0.1.
Android PID 6293: [08:39:16] remote_server.cpp(896) - Log - Ready for new active connection...
Core PID 3256: [16:39:18] remote_server.cpp(1564) - Log - Opening capture remotely
Core PID 3256: [16:39:18] core.cpp(49) - Log - Not enabling API validation during replay
Core PID 3256: [16:39:18] core.cpp(54) - Log - Using default GPU replay selection algorithm
Core PID 3256: [16:39:18] core.cpp(63) - Log - Replay optimisation level: Balanced
Core PID 3256: [16:39:18] streamio.cpp(415) - Warning - Error reading from socket
Core PID 3256: [16:39:18] remote_server.cpp(1598) - Log - Capture open complete
Core PID 3256: [16:39:18] remote_server.cpp(1602) - Error - Error opening capture
Android PID 6293: [08:39:46] remote_server.cpp(1055) - Log - Connection received from 127.0.0.1.
Android PID 6293: [08:39:46] remote_server.cpp(1088) - Log - Making active connection
Android PID 6293: [08:39:51] streamio.cpp(415) - Warning - Error reading from socket
![image](https://user-images.githubusercontent.com/53023417/79023577-826ebd00-7b35-11ea-894c-0f0ac1558b87.png)

## Steps to reproduce

1) need samsung note 9 and android development env
2) open capture the trace file. it will crashed. popup the error massage.( i already send you the trace in the previous email. if you didn't receive it , please let me know)

## Environment

* RenderDoc version: v1.7
* Operating System: android(no-rooted), windows, saumsung note 9
* Graphics API: opengles 3.2
* GPU: adreno 640.

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
