### ISSUE TITLE
Vulkan: WrappedVulkan::Prepare_InitialState() impl assumes all images are TRANSFER_SRC-enabled

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#183]
When frame contents is being captured, one of the steps taken by RenderDoc is transitioning all sensible image subresource ranges to TRANSFER_SRC_OPTIMAL image layout, for the purpose of copying the data to buffer memory.

However, as per spec, this requires the image, which acts as a parent for each discussed subresource range, to be initialized with VK_IMAGE_USAGE_TRANSFER_SRC_BIT usage bit set. For obvious reasons, apps do not light that bit if they don't need it.

One of the workarounds for this seems to be setting the bit when we intercept vkCreateImage() call, as per example below:

![image](https://cloud.githubusercontent.com/assets/9154207/13220182/0be2c084-d975-11e5-993f-7aeaeed9bf7a.png)

Is this an acceptable solution? If so, I'll go ahead and create a pull request.

**Comment by baldurk** [comment]
Ah yes you're absolutely right. I modify the `VkImageCreateInfo` on replay in `Serialise_vkCreateImage` but I've forgotten to do it on capture.

I like the proposed solution to create a copy of the `VkImageCreateInfo` and modify that, then pass the unmodified version further on to the serialise function. A pull request would be very welcome :).
