### ISSUE TITLE
RecursionError when running extension with pyd

### ISSUE THREAD

**Issue by JingChangzz** [baldurk/renderdoc#1833]
## Description
There is a RecursionError when running extension which are pyd files  
But it is ok to running the same extension which are py files 

## Steps to reproduce  
[example.zip](https://github.com/baldurk/renderdoc/files/4491292/example.zip)  
1.  download example.zip, and extract  
2.  copy example folder to  renderdoc extension path  
3.  load extension in RenderDoc  

**Experiment 1**：  run extension which are py files
1.  delete test.pyd， then load extension named test
2.  click Tools -> test,  then click button "123",  everything is ok

**Experiment 2**：  run extension which are pyd files
1.  delete test.py， then load extension named test
2.  click Tools -> test,  then click button "123",  **RecursionError **  occurred in my PC

**Experiment 3**：  run test.py or test.pyd out RenderDoc
1.  run cmd ```python main.py```
2.  click button "123",  everything is ok

## Environment

* RenderDoc version: 1.5
* Operating System: Win10
* Graphics API: XXX

**Comment by baldurk** [comment]
How did you generate the .pyd? I can reproduce the problem but it is caused by something inside the pyd.

I do not expect that compiling the python scripts will work especially if they use PySide, since it will likely require a very specific set of compatible versions between e.g. RenderDoc's python interpreter, the python version used to compile the module, and the python version used to compile PySide.

**Comment by JingChangzz** [comment]
I use python 3.6.4 64bit  
![企业微信截图_1587126107899](https://user-images.githubusercontent.com/13314441/79568787-11a54300-80e9-11ea-87f3-92019a6218ac.png)

And I tried 2 ways to generate the .pyd file:  
1、Cython          0.29.16  
2、easycython      1.0.7  
  
I generate the .pyd file with my system python which contains PySide2  version 5.14.1

**Comment by JingChangzz** [comment]
> How did you generate the .pyd? I can reproduce the problem but it is caused by something inside the pyd.
> 
> I do not expect that compiling the python scripts will work especially if they use PySide, since it will likely require a very specific set of compatible versions between e.g. RenderDoc's python interpreter, the python version used to compile the module, and the python version used to compile PySide.

I use python 3.6.4 64bit
![](https://user-images.githubusercontent.com/13314441/79568787-11a54300-80e9-11ea-87f3-92019a6218ac.png)


And I tried 2 ways to generate the .pyd file:
1、Cython 0.29.16
2、easycython 1.0.7

I generate the .pyd file with my system python which contains PySide2 version 5.14.1

**Comment by baldurk** [comment]
If you're using the PySide2 version from your system python install then that may be the cause of the problem with a version incompatibility. I don't know how cython or easycython works but the existing interfaces are already quite version-specific.

Regardless of that, I do not plan to support compiled python files in extensions as there are way too many ways for it to break and there's no reason to do so. The extension works fine as a normal python script so you should use that.
