### ISSUE TITLE
can't launch unity in renderdoc

### ISSUE THREAD

**Issue by gitcoolguy** [baldurk/renderdoc#1834]
## Description
can't launch unity in renderdoc

## Steps to reproduce
1.open renderdoc and click File/LaunchApplication
2.fill in Executable Path and Command-line Arguments
3.click Launch
4.error information popup

## Environment

* RenderDoc version: v1.7
* Operating System: Win 10
* Graphics API: DX11

unity: 2019.3.6f1

log:
RDOC 010236: [20:24:47]    win32_process.cpp( 514) - Log     - Running process C:\Program Files\Unity\Hub\Editor\2019.3.6f1\Editor\Unity.exe
RDOC 010236: [20:24:48]    win32_process.cpp( 597) - Log     - Injecting renderdoc into process 16680
RDOC 010236: [20:24:49]    win32_process.cpp( 385) - Error   - Couldn't find module 'renderdoc.dll' among 92 modules
RDOC 010236: [20:24:49]    win32_process.cpp( 940) - Error   - Can't locate renderdoc.dll in remote PID 16680

**Comment by baldurk** [comment]
Unity these days has a complex relationship with the Unity Hub and so doesn't always directly launch its editor process (instead asking the Hub process to launch it instead). The only way I've found to do it is to ensure no unity processes are running and the launch the hub itself through RenderDoc and ensure you enable capturing child processes.

However Unity has [built-in RenderDoc integration](https://docs.unity3d.com/Manual/RenderDocIntegration.html) which I recommend you use instead if you're unable to configure it for launch correctly.

**Comment by gitcoolguy** [comment]
I have tried to use Unity built-in RenderDoc, but when i clicked Load RenderDoc, unity crashed.

**Comment by baldurk** [comment]
Some Unity versions have had bugs that cause crashes loading RenderDoc. Check that you're running the latest version as AFAIK they've been fixed.
