### ISSUE TITLE
python 3.8.2 64bit can not import python api

### ISSUE THREAD

**Issue by poople** [baldurk/renderdoc#1838]
## Description
I compile the renderdoc project， and get the python api，release and development。while I use python 3.8.2 to import the latest api，I failed， it tell me cannot load dlls
ImportError: DLL load failed while importing renderdoc
I put the path to environment path or use sys.path.apend, all don't work

`import os
os.environ["PATH"] += os.pathsep + os.path.abspath('F:\Development')

import sys
sys.path.append('F:\Development\pymodules')

import renderdoc as rd
print(rd.CullMode.FrontAndBack)
`
I tried all i can, all failed. can you help me to solve this, thanks very much!

## Steps to reproduce
1,install python 3.8.2 64bit
2,build the latest renderdoc,
3, try to import api

## Environment

* RenderDoc version: v1.8
* Operating System: win10 professional 64bit
* Graphics API: opengl es 3.0
* Python version: 3.8.2 64bit
* visual studio: 2017

* RenderDoc version: XXX
* Operating System: XXX
* Graphics API: XXX

**Comment by poople** [comment]
I use python 3.6.4,i works , so in python 3.8.2, i has some bugs

**Comment by baldurk** [comment]
RenderDoc's python module is only compatible with a precise major and minor version (and possibly patch version as well, I'm not sure). Whichever version you build against must be the exact version you use to import the module, which is 3.6.4 by default on Windows.

**Comment by giyangx** [comment]
I want to know how to get renderdoc,pyd and qrenderdoc,pyd python dynamic library files? I tried several times to compile without success,please help me

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
