### ISSUE TITLE
Capture GLES APIs issued outside the "swapbuffers" (frame) boundary

### ISSUE THREAD

**Issue by samikhawaja** [baldurk/renderdoc#1842]
## Description

I want to capture GLES APIs issue by an application outside the swapbuffers boundary. My application does some offscreen rendering on framebuffer objects and prepares a final texture. This is done in separate thread. This texture is copied to the default(0) framebuffer using glBlit* API. When I use renderdoc to do the capture the frame, The API calls used to do offscreen rendering are not captured. I noticed that renderdoc has a concept of "Background capture", is this something that can be used to capture the GLES APIs which are outside the frame boundary?

## Environment

* RenderDoc version: e216fa7e1258161266b28539e05646c37b8eb3ae
* Operating System: ubuntu 18.04
* Graphics API: OpenGL ES 3.1

**Comment by baldurk** [comment]
You can use RenderDoc's [in-application API](https://renderdoc.org/docs/in_application_api.html) to control capture at arbitrary points, in particular you can call [`StartFrameCapture`](https://renderdoc.org/docs/in_application_api.html#_CPPv417StartFrameCapture23RENDERDOC_DevicePointer22RENDERDOC_WindowHandle) and [`EndFrameCapture`](https://renderdoc.org/docs/in_application_api.html#_CPPv415EndFrameCapture23RENDERDOC_DevicePointer22RENDERDOC_WindowHandle) to start and end the frame capture.
