### ISSUE TITLE
Feature request - Allow saving/exporting values of Cbuffers.

### ISSUE THREAD

**Issue by Gh0stBlade** [baldurk/renderdoc#1843]
## Description
 Allow us to export or save the cbuffer values to a text file and binary for further analysis.

## Steps to reproduce 
Debug a pixel shader, you can't save or export the cbuffer values for further analysis.

## Environment
     * RenderDoc version: v1.7
     * Operating System: Win10 1809 17763.914
     * Graphics API: D3D11

**Comment by baldurk** [comment]
Constant buffers can be exported from the constant buffer viewer, as opened from the pipeline state, using the 'export to CSV' button. If you need to save directly to binary you can open the buffer in a raw viewer view the resource inspector and export to binary from there.
