### ISSUE TITLE
Vertex Shader debugging issue.

### ISSUE THREAD

**Issue by Gh0stBlade** [baldurk/renderdoc#1844]
## Description
I am trying to use shaders from a game that are already compiled. After doing so I noticed that even though I pass exactly the same input values I get completely different output values.

## Steps to reproduce 
Original Game says:
![image](https://user-images.githubusercontent.com/6951235/80033575-df2e8800-84e4-11ea-840b-7d0b4bf08db2.png)

My Engine says:

![image](https://user-images.githubusercontent.com/6951235/80033694-14d37100-84e5-11ea-8fe4-652451b69bb2.png)

As you can see, though the input values are identical, it's producing 0.0f, 0.0f, 0.0f, 0.0f in register r1 which isn't correct.

## Environment
     * RenderDoc version: v1.7
     * Operating System: Win10 1809 17763.914
     * Graphics API: D3D11

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
