### ISSUE TITLE
Bug: D3D12: Buffer contents view for matrix is incorrect

### ISSUE THREAD

**Issue by kch86** [baldurk/renderdoc#1848]
## Description
When inspecting buffer contents matrices are not displayed correctly. For example: float4x3 is displayed as a float4x4. float3x4 is displayed as a float3x3. Contents for members proceeding a matrix are correct (i.e. the byte offset for that data seems correct). But overall stride seems to be  wrong (e.g. following elements will be shifted when displayed). 

Example:
A buffer with format:
```
struct Data
{
  float4 pos;
  float4x3 transform;
  float4 color;
}
```
And displayed in the buffer contents view (I've made elements 1 and 2 be the same to demonstrate what's happening): 
Element  | Position              | Transform                         | Color
--------- | :------------: | --------------------------- | -------
0  |           5.0 6.0 1.0 1.0  | 1.00  0.00  0.00  2.8226 |   2.8226 3.0677  2.5881 0.5
| | |                                0.00  1.00  0.00  3.0677 |    
| | |                                   0.00  0.00  1.00  2.5881  | 
| | |                                   -5.1  10.0  8.09  0.5     |     
1 |          1.00 0.00 0.00 -5.1  | 0.00  0.00  2.8226  x |   x y z w
| | |                                          1.00  0.00  3.0677 y |    
| | |                                          0.00  1.00  2.5881  z | 
| | |                                         10.0  8.09  0.5  w |     

Looking at Element 0, Transform bleeds into color, but color is still displayed correctly. Looking at Element 1, if you notice, the contents are shifted by one float4. Here, x/y/z/w is bleeding into the position for the element at index 2 (not shown). 

If I convert the format to the following:
```
struct Data
{
  float4 pos;
  float3 transform0;
  float3 transform1;
  float3 transform2;
  float3 transform3;
  float4 color;
}
```
Then the buffer contents are displayed correctly.

## Steps to reproduce
1. Take a capture of a d3d12 application
2. Inspect the buffer contents of any buffer containing float4x3/float3x4 data.

## Environment

* RenderDoc version: 1.7 @ ( a56af589 & f8c5c287 )
* Operating System: Windows 10 1903
* Graphics API: D3D12
* GPU: Nvidia 2080
* Driver: 441.66

**Comment by baldurk** [comment]
This was caused by some buggy handling of column-major rectangular matrices, some bits were using the row size and others the major-dimension-size which led to the problems you described. That commit should fix the issues.

**Comment by kch86** [comment]
Awesome, thanks!
