### ISSUE TITLE
glslang 3rd-party library does not compile on modern Clang

### ISSUE THREAD

**Issue by ebatsin** [baldurk/renderdoc#1851]
## Description

I get a compilation error in glslang using Clang 10.0.0 (In PoolAlloc.h, `setAllocator` tries to call private `operator=` on a `TPoolAllocator`). This issue only happens on modern versions of Clang that try to compile this method even if it is not used by renderdoc.

This issue have been fixed upstream here: https://github.com/KhronosGroup/glslang/pull/2010

The first version of glslang that contains the changes should be 8.13.3559 (but simply removing the `setAllocator` method fixes the issue if updating glslang version is a problem).

## Steps to reproduce

CMake and build renderdoc with Clang 10 with the default CMake options (I just forced BUILD_TYPE to "Release")

## Environment

* RenderDoc version: master (f29fe58)
* Operating System: Arch Linux
* Compiler: Clang++10
* Build System: Ninja
* Graphics API: -

**Comment by baldurk** [comment]
Updated glslang to latest and also fixed another warning elsewhere that was firing on clang 10.
