### ISSUE TITLE
decode_mesh.py variable vertexOffset is not defined

### ISSUE THREAD

**Issue by poople** [baldurk/renderdoc#1852]
## Description

In the page：https://renderdoc.org/docs/python_api/examples/renderdoc/decode_mesh.html
For the example of “Decoding Mesh Data”
in function getIndices
line 195 of the script 
“return tuple(range(vertexOffset, vertexOffset+mesh.numIndices))“
the vertexOffset is not defined
is this reffered mesh.vertexByteOffset?
## Environment

* RenderDoc version: any
* Operating System: windows
* Graphics API: any

**Comment by baldurk** [comment]
This was leftover code from some other iteration I think, the `vertexOffset` from the drawcall should be applied earlier. I've updated the example code appropriately.
