### ISSUE TITLE
Help installing RenderDoc on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by jimiblender** [baldurk/renderdoc#1856]
## Description

Hi there. I'm new to github and I've never compiled anything from source before. I don't actually understand what the process is and I'd like to clarify it before doing something stupid. I checked my dependencies were up to date, so there should be no issues there.

## Steps to reproduce
I downloaded the renderdoc_1.7.tar.gz tarball but I get lost at the next step:
**cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild -H.
make -C build**
First, where should I put the tarball for installation?
Second, do I have to extract it first, or do those compilation commands work on a zipped tar?

## Environment

* RenderDoc version: 1.7
* Operating System: 18.04 LTS
* Graphics API: OpenGL, version unknown

Any help for a struggling newbie would be greatly appreciated! My ultimate goal is to compile a Blender add-on from source which uses data extracted from RenderDoc to build 3D models. It's open source but it's only available for Windows, so I thought I'd give it a go, but the first step is to get RenderDoc working!
Cheers.

**Comment by baldurk** [comment]
I know which blender add-on you're talking about, and I will not provide any support related to it at all. RenderDoc is only intended for capturing and debugging your own programs. Illegally extracting copyrighted assets using RenderDoc is absolutely not endorsed or supported.

**Comment by jimiblender** [comment]
Hello, well I must have missed something there then. The video didn't give me the impression there was anything illegal about it; it looked legit to me. Sorry for any misunderstanding and all the best with your project.
