### ISSUE TITLE
Crash while replaying GLES capture on Linux

### ISSUE THREAD

**Issue by null77** [baldurk/renderdoc#1857]
## Description

I built renderdoc from source and debugged a crash I was getting when capturing/replaying a frame from a trace we captured from an Android GLES benchmark. Everything ran perfectly fine, the capture worked, however when the app exited and the replay started, rdoc crashed here:

https://github.com/baldurk/renderdoc/blob/b9a9542f3b77ecf3685dc57aa93bd92430606933/qrenderdoc/Windows/Dialogs/LiveCapture.cpp#L1043

With a nullptr m_Connection. I found that checking for nullptr made the replay seemed to work ok:

https://github.com/null77/renderdoc/commit/e5afbbc43132ec5aeadb2543db46287d82834c7b

Unsure if you want to accept that kind of CL or if that's a correct fix.

## Steps to reproduce

Unfortunately my repro steps are convoluted and rely on internal capture data that I can't as easily share. If necessary we can work to get a way to repro this to you in-house.

## Environment

* RenderDoc version: ToT x1.x (ccab431cd19d827d26ff76c76bbf31a2b7ff4134)
* Operating System: Linux Ubuntu based
* Graphics API: NVIDIA / GLES

**Comment by baldurk** [comment]
That definitely looks suspicious now that I look at it, `m_Connection` will get set to `NULL` when the connection is closed, and so it generally shouldn't be accessed outside of the connection thread. I think what's happening is that the capture is reported and it invokes onto the GUI thread to populate the UI, but that's then racing against the application closing and the connection disappearing in the meantime.

I think the better fix is to read the properties that we need on the connection thread before calling `captureAdded`, I'll do that now. I can also see that one other place is buggy, accessing `m_Connection` incorrectly which I'll fix at the same time.

Just to clarify one thing that shouldn't matter but just to be sure I'm not missing something - were you making multiple captures? You said that when the application exits then the replay starts before the crash happens, which makes sense only if there was already a previously-added capture which then started opening up. In order for the above race to happen that would need to be a second capture coming in - does that make sense for your application?

**Comment by null77** [comment]
RenderDoc is only making one capture and one replay. The confusion is because the application itself is running a capture using a different tool. So we capture into a file without RenderDoc, then replay with the application and RenderDoc captures this running application. Finally RenderDoc replays using its own replay harness and that triggers the bug. Clear as mud.

Thanks for the quick response!

**Comment by baldurk** [comment]
Ah so you mean that _RenderDoc's_ replay hadn't started, it was the other tool's replay? That would make sense - what I didn't get was how RenderDoc would have started replaying if there was a race on the capture being made, unless you made one capture and opened it manually or with a python script and then the application closed right after making a second one. That would be possible but seemed highly specific :).

**Comment by null77** [comment]
In this case I was replaying the capture of a replay of a capture.

**Comment by baldurk** [comment]
That commit should fix the crash, let me know if you're still seeing issues.
