### ISSUE TITLE
Problem acquiring Python module (renderdoc.pyd/renderdoc.so)

### ISSUE THREAD

**Issue by rkxiaotc** [baldurk/renderdoc#1859]
## Description

Sorry to bother but I just failed to find any instruction on how to acquire the Python module for Renderdoc. I have built a copy of Renderdoc, but still I don't see how I may obtain the Python module.  
&nbsp;
Could you please make the instruction (or related information if possible) more accessible?

**Comment by baldurk** [comment]
The python module is built by default, on linux it's output in the `lib/` folder under the build root, and on windows under the `pymodules` folder in the architecture/build type folder.

**Comment by rkxiaotc** [comment]
Sorry but still I fail to find any file under the `pymodules` folder.
Actually, it seems that even the `pymodules` folder itself is not always automatically created. There was no such folder under the `Release` folder until I tried debugging for several times.

I am building `Release` with VS 2015 and there wasn't any error/warning. I am not sure what information would help so I simply attach the output window content here.

[build.txt](https://github.com/baldurk/renderdoc/files/4567455/build.txt)
[Debug_output.txt](https://github.com/baldurk/renderdoc/files/4567456/Debug_output.txt)

**Comment by ThisIsTian** [comment]
In case anyone uses VS2019 to compile tag 1.13 but the module does not show up, the Python module is not built by default. Need to explicitly select the qrenderdoc_module project to build in order to get the it.

**Comment by baldurk** [comment]
Please do not comment on year-old bugs.
