### ISSUE TITLE
Makefile flaw

### ISSUE THREAD

**Issue by Marqin** [baldurk/renderdoc#186]
Hello, [releases](https://github.com/baldurk/renderdoc/releases) are just archives with code and not a git repository, but... in [Makefile](https://github.com/baldurk/renderdoc/blob/master/renderdoc/Makefile) you use:

    -DGIT_COMMIT_HASH="\"$(COMMIT)\""
where:

    COMMIT=`git rev-parse HEAD`

and because this is not a repository, building v0.27 gives many errors:

    fatal: Not a git repository (or any of the parent directories): .git

**Comment by baldurk** [comment]
That's a fair point, I hadn't thought about the case where you're not actually building from the git repository (or maybe that git isn't installed even).

The git commit hash isn't required, it's defined to "NO_GIT_COMMIT_HASH_DEFINED" on windows where there's no nice way to run git as part of the build process, it was just a nicety on linux. Let me try and change the command so it will build OK even if not in a git repository.

**Comment by baldurk** [comment]
That should do the trick from a quick test, but it'd be good to verify that it works for you.

**Comment by Marqin** [comment]
It works for me :+1:
