### ISSUE TITLE
The value of SV_VertexID seems to be wrong in renderdoc when used with ID3D11DeviceContext::DrawIndexed

### ISSUE THREAD

**Issue by LazyLemonBen** [baldurk/renderdoc#1862]
## Description

The value of SV_VertexID seems to be wrong in renderdoc when used with ID3D11DeviceContext::DrawIndexed when a vertex buffer has not been bound. I believe that renderdoc adds the index value to the BaseVertexLocation value (the 3rd argument in ID3D11DeviceContext::DrawIndexed) to generate the value for SV_VertexID in the vertex shader when debugging and in the Mesh Viewer. This is what the Microsoft Docs seem to indicate should happen but I think this is only true if a vertex buffer is set. Without a vertex buffer, Directx11 just passes the raw index value.

## Steps to reproduce

Create an index buffer and then call ID3D11DeviceContext::DrawIndexed without a vertex buffer bound. Look at the value generated for SV_VertexID in the vertex shader. DirectX11 does not add BaseVertexLocation, but renderdoc does.
## Environment

* RenderDoc version: 1.7
* Operating System: Win10
* Graphics API: DirectX11

**Comment by baldurk** [comment]
From testing this doesn't seem to be related to vertex buffers being bound at all, which I don't think would make sense given that there would have to be complex rules defining how that worked when multiple vertex buffers are in use and depending on the input layout. Instead it seems to me like `SV_VertexID` doesn't include `BaseVertexLocation` regardless.

**Comment by LazyLemonBen** [comment]
Hi. Thanks for looking into it. I agree. I've just done a test with the Visual Studio Graphics Analyzer and can see that `BaseVertexLocation` isn't considered. It just seems to be RenderDoc exhibiting this behavior.

**Comment by baldurk** [comment]
That commit should fix the handling of `BaseVertexLocation` both in shader debugging and the mesh output.
