### ISSUE TITLE
Launched application crashes if it uses Windows Graphics Capture

### ISSUE THREAD

**Issue by jpark37** [baldurk/renderdoc#1864]
## Description

When running an application with RenderDoc that uses Windows Graphics Capture, WGC internally calls OpenSharedResource1 with an IUnknown GUID, and that causes WrappedID3D11Device::OpenSharedResourceInternal to return E_NOINTERFACE, leading to a crash later on.

This is my attempted fix: https://github.com/jpark37/renderdoc/commit/50ab0f416f2afb6a5dea5dbb07fad39d668dd483

## Steps to reproduce

I'm seeing this in OBS Studio, but the MS sample also reproduces and is easier to build:
https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/tree/master/cpp/ScreenCaptureforHWND

Just build and launch from RenderDoc, and try to capture a window.

## Environment

* RenderDoc version: HEAD (current nightly is 2020-05-01)
* Operating System: Windows 10 20H1, should probably just need 1903 though
* Graphics API: D3D11

**Comment by baldurk** [comment]
Closed with a8cf6f2. Thanks!
