### ISSUE TITLE
Find windows "Find Previous" button does the same as "Find Next".

### ISSUE THREAD

**Issue by Karmiska** [baldurk/renderdoc#1866]
## Description

When using Find, the "Find Previous" and "Find Next" buttons both move to the next occurrence.

## Steps to reproduce

- Open any capture.
- Select any draw or dispatch call.
- In pipeline state, select pixel/compute (or any stage).
- In shader window, click View
- click cursor to somewhere in the shader source
- press ctrl+f
- type a search term that can be found in multiple locations in the file
- click "Find Next". observe search going forward.
- click "Find Previous". observe search going forward when it should go backwards.

## Environment

* RenderDoc version: v1.7 (built from a56af589)
* RenderDoc version: v1.8 nightly 2020-05-03 (built from 85bd6782)
* Operating System: Windows 10
* Graphics API: Vulkan and DX12

**Comment by baldurk** [comment]
Fixed with that commit, I missed setting the direction implicitly when I switched to those buttons from a user-defined direction toggle.
