### ISSUE TITLE
Feature Request: Copy to Clipboard in the Texture Viewer

### ISSUE THREAD

**Issue by jshofmann** [baldurk/renderdoc#1872]
## Description

Can we get a 'Copy to Clipboard' option in the Texture Viewer's Actions toolbar? This would be very useful for copying a texture displaying some artifact or corruption to a chat client (e.g. Slack, Telegram) to bring to the attention of other team members. Currently, you either have to use Save Selected Texture and drag the file created to the chat client (assuming that the file could be created, or the image format understood by the chat client), or you need to use a third-party tool like Greenshot. Thanks!

## Environment

* RenderDoc version: 1.7 (built from a56af589)
* Operating System: Windows 10 Professional
* Graphics API: Vulkan 1.1

**Comment by baldurk** [comment]
No I don't want to add this. There are a number of complexities with how to map a texture to the clipboard depending on what the user actually wants, and it's better to let the user do what you're talking about - pressing alt-printscreen or saving the texture to disk to do exactly what they're after.
