### ISSUE TITLE
Buffer Viewer doesn't pick-up `row_major` qualifier from the SSBO and UBO layouts

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [baldurk/renderdoc#1873]
## Description

I have a shader which declares
```glsl
struct DrawData_t
{
    mat4 modelViewProjMatrix;
    mat3 normalMatrix;
};

layout(binding = 0, std430) restrict writeonly buffer PerDraw
{
    layout(row_major) DrawData_t drawData[];
} _355;
```

Then the Buffer Viewer shows me
```glsl
struct root_struct
{
    mat4 modelViewProjMatrix;
    mat3 normalMatrix;
    xint pad[3];
}

struct PerDraw
{
    root_struct drawData;
}
```

I expect to see
```glsl
struct root_struct
{
    row_major mat4 modelViewProjMatrix;
    row_major mat3 normalMatrix;
}

struct PerDraw
{
    root_struct drawData;
}
```

## Steps to reproduce

Declare a UBO or SSBO with `row_major` qualifier and see it in the buffer viewer

## Environment

* RenderDoc version: 2020_05_07_8638dddb
* Operating System: Windows
* Graphics API: OpenGL 4.6

**Comment by devshgraphicsprogramming** [comment]
I have a repro case here:
https://github.com/baldurk/renderdoc/issues/1874#issuecomment-626017947

**Comment by baldurk** [comment]
That commit should ensure matrices are properly declared as row major.
