### ISSUE TITLE
Padding is computed wrongly for `row_major` matrices in the Buffer Viewer

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [baldurk/renderdoc#1874]
## Description

When I type the following in the Buffer Viewer
```glsl
struct root_struct
{
    row_major mat4 modelViewProjMatrix;
    row_major mat3 normalMatrix;
}

struct PerDraw
{
    root_struct drawData;
}
```

It forgets that under both std430 and std140 rules (this is an SSBO I'm looking at) the mat3 would have been padded by 4 bytes after each column.

The only way to get properly aligned display is to apply the view as
```glsl
struct root_struct
{
    row_major mat4 modelViewProjMatrix;
    vec4 normalMatrix[3];
}

struct PerDraw
{
    root_struct drawData;
}
```

Most notably `vec3 normalMatrix[3]` does not work either.

## Steps to reproduce

See the description.

## Environment

* RenderDoc version: 2020_05_07_8638dddb
* Operating System: Windows
* Graphics API: OpenGL 4.6

**Comment by devshgraphicsprogramming** [comment]
This has two captures, one from 1.7 and the other from yesterday's nightly build.
The 1.7 crashes if I go poking around in the Mesh and Pipeline viewer while on the MDI call

[MDI_bug_nightly_07_05_20.zip](https://github.com/baldurk/renderdoc/files/4601585/MDI_bug_nightly_07_05_20.zip)

**Comment by baldurk** [comment]
That commit will add padding after each row/column of a matrix that has padding in its stride.
