### ISSUE TITLE
Corrupted textures in Vulkan on Oculus Quest 

### ISSUE THREAD

**Issue by Piotr-B** [baldurk/renderdoc#1882]
## Description

When viewing a capture from Quest of a Vulkan app created in UE4.24.3 most textures appear corrupted.
In addition **Highlight Drawcall** and **Wireframe Mesh** overlays either don't show up at all or are misplaced (looks like they're coming from the wrong tiles).
This happens both on 1.7 stable and on latest Nightly (2020_05_11_da2af696_64) builds.

## Steps to reproduce

1. Open Unreal Engine 4.24.3 and create a new project based on the "Virtual Reality" template
2. Configure project for Quest development ([guide here](https://developer.oculus.com/documentation/unreal/unreal-quick-start-guide-quest/))
3. Set "MotionControllerMap" as the default map
4. Enable "Mobile Multi-View" and "Mobile Multi-View Direct"
5. Enable "Support Vulkan"
6. Package project for Android ASTC
7. Deploy to device
8. Capture a frame
9. Open the captured frame ([uploaded here](https://drive.google.com/open?id=1bPKU3-2l1QbuXE6_8t7Fy-WBN8V4cf6U))
10. Navigate to "M_HandMat" or "M_Sky_Panning_Clouds2" drawcall and inspect the textures, most of them are corrupted
11. Try viewing the frame buffer with a "Hightlight Drawcall" or "Wireframe Mesh" overlay for any drawcall

## Environment

* RenderDoc version: 1.7 and Nightly (2020_05_11 da2af696)
* Operating System: Android (Oculus Quest, software version 16.0)
* Graphics API: Vulkan

![Renderdoc_Screenshot_1](https://user-images.githubusercontent.com/8913735/81725709-8704f900-9486-11ea-8a79-e5c6754cdf5a.jpg)
![Renderdoc_Screenshot_2](https://user-images.githubusercontent.com/8913735/81725843-bddb0f00-9486-11ea-910c-8fe48e0f1d51.jpg)

**Comment by baldurk** [comment]
That commit should fix the corrupted ASTC texture bug, the next nightly build should work correctly. The broken overlays appears to be a QC driver bug, but I've added a workaround for it separately.

Thank you for the very clear and direct bug repro steps, it made it a lot easier to investigate!

**Comment by Piotr-B** [comment]
Thanks for the quick fix!
Testing on Nightly 2020_05_17 22d5cf23 the textures are displaying correctly.

The overlays work better but are positioned wrong unless I switch to slice 1 of the FB.
Depth Test overlay is wrong in either slice. It looks like it's using position from slice 1 but depth info from slice 0.
A capture from the nightly is [here](https://drive.google.com/open?id=106vdOWktT1C6mTwptJWNLwIsxcgOAgWf).
(This should probably be a separate issue...)

![Capture_22d5cf2_1](https://user-images.githubusercontent.com/8913735/82249260-c67d8a80-9949-11ea-8a8c-87e0f14ae6d8.PNG)
![Capture_22d5cf2_2](https://user-images.githubusercontent.com/8913735/82249272-c9787b00-9949-11ea-8c55-8ef170d1a648.PNG)

**Comment by baldurk** [comment]
It's probably related to multiview which the overlays don't handle, but yes please file a new issue. Trying to merge multiple bugs into one issue makes things confusing and hard to track.

**Comment by Piotr-B** [comment]
Done. New issue: #1895
