### ISSUE TITLE
Feature request: Have explicit X,Y offset values in the Texture Viewer view

### ISSUE THREAD

**Issue by c4stan** [baldurk/renderdoc#1885]
## Description

Currently the only way to move around the texture viewport when viewing a zoomed in texture in the Texture Viewer is to either use the horizontal/vertical scrollbars or the mouse drag. These work fine but it makes very hard to reproduce a view, for example if I need to view the same exact texture portion in two different captures. Having explicit X and Y offset fields in a text field, similarly to what we already have for the zoom, would solve this.

**Comment by baldurk** [comment]
The scrollbars and mouse drag are not the only way to select a pixel. You can jump directly to a pixel co-ordinate with the go-to button (shortcut ctrl+g):

![image](https://user-images.githubusercontent.com/661798/81912345-5deb8200-95c6-11ea-9921-0d91ed2fd0a1.png)

Which gives you the text fields you want:

![image](https://user-images.githubusercontent.com/661798/81912519-94290180-95c6-11ea-991f-266888bc99c0.png)

And you can further narrow the selected pixel with the arrow keys.

**Comment by c4stan** [comment]
Sorry if I wasn't clear enough in my description, I was referring to the texture viewer, not the specific pixel pick. For example, say that I have this capture where I'm looking at the detail in the bottom left

![example_1](https://user-images.githubusercontent.com/3864311/81992809-3f52ae80-95f9-11ea-8338-54386d032945.png)

and let's say that I change something in my shader, causing a slight change in the final frame, relaunch the exe and grab another capture from the same view point in the same scene.

![example_2](https://user-images.githubusercontent.com/3864311/81992812-4083db80-95f9-11ea-8cb7-ee6391c2900b.png)

Now what I'd like to do is to look again at the bottom left and visually compare the images, for example having them side by side. Right now I can replicate the zoom but not the offset.

Hope this is more clear. I'd find this feature useful, but also I'd understand if you think it's not something that most people would find useful. Thank you.

**Comment by baldurk** [comment]
That commit will scroll the selected pixel into the centre when you go-to one, which is reasonable behaviour and sounds like it's possibly what you're after. I don't want to add a permanent x/y offset edit box as the texture viewer controls are already over-complex as they are and there's little value in adding it.

For what it's worth if you're only editing shaders you can do that from within the renderdoc capture without having to re-capture. That might improve your iteration cycle.
