### ISSUE TITLE
RenderDoc v1.7 can not open some DDS files

### ISSUE THREAD

**Issue by Witek902** [baldurk/renderdoc#1888]
## Description

Trying to open some formats results in this error:
![obraz](https://user-images.githubusercontent.com/5882734/81986723-a8a5e200-9638-11ea-8c37-08e29f4a66b6.png)

Formats that do not work:
- R16_UNORM
- R8_UNORM
- R8G8_UNORM
- B4G4R4A4_UNORM

Probably there's more. Would be nice if RenderDoc supported all DXGI formats.

## Steps to reproduce

Generate some DDS file using for example [texconv ](https://github.com/microsoft/DirectXTex/tree/master/Texconv) tool.

## Environment

* RenderDoc version: 1.7
* Operating System: Windows 10
* Graphics API: N/A

**Comment by baldurk** [comment]
Looks like DirectXTex emits some formats with legacy DDS headers without the DXGI_FORMAT enum present. I've added code to handle that case rather than only simple RGBA8.
