### ISSUE TITLE
RenderDoc crashes due to a NPE

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#189]
1. Record a frame when running Cube test app from Vulkan SDK.
2. Open it
3. Click the "Colour Pass #1 / VkCmdDraw()" command.
4. Observe the crash: (l. 292 in the first picture, _wrapped->record_ is null)

![image](https://cloud.githubusercontent.com/assets/9154207/13244574/91baee92-da07-11e5-9865-303ee14b7d16.png)
![image](https://cloud.githubusercontent.com/assets/9154207/13244581/9c5ffacc-da07-11e5-824c-e7910978ae36.png)

**Comment by baldurk** [comment]
Whooops. That will teach me to code late at night without testing sufficiently :cry:.

**Comment by DominikWitczakAMD** [comment]
Fixed :-)
