### ISSUE TITLE
'RenderDoc injection failed' error with Unreal Engine 4.21 game

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#1893]
## Description

I'm trying to use this program with Tiny Metal Full Metal Rumble (unreal engine 4.21) game.
Game screen appears, but program itself shows up 'RenderDoc injection failed' error.

## Steps to reproduce

Just open Milk.exe as it shows here: http://prntscr.com/sig5tf and click 'Launch' button and error appears.

## Environment

I had run both 32 and 64 bits versions of v1.7 of this program (portable mode, but this error also happens with installable one).

* RenderDoc version: 1.7
* Operating System: Windows 10 Pro 64 bits.
* Graphics API: I sincerally don't know about this one, when someone is able to describe me about this part, i'll be able to fill it with correct info.

That game is 32 bits, so, i believe that only 32 bits version of RenderDoc should work with it.

The PC i'm using has Nvidia GeForce GTX 1070, 16GB RAM.

The program told me to check diagnostic log and it looks like this: http://prntscr.com/sig95j

The program's folder structure: http://prntscr.com/sig9fu

I used the template as asked to and i believe this is enough info. If more details are needed, lemme know.

Thanks. =]

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
