### ISSUE TITLE
wgpu-rs examples (linux, vulkan) freeze after the window has been created.

### ISSUE THREAD

**Issue by expenses** [baldurk/renderdoc#1894]
When loading a wgpu-rs example with `qrenderdoc` the following error is printed:

`RDOC 161649: [23:52:45]          vk_core.cpp(1268) - Warning - Spec versions of VK_EXT_debug_utils are different between supported extension (1) and reported (2)!`

A window is opened but nothing is drawn to it (nor is it cleared) and frames can't be captured:

![1589750385](https://user-images.githubusercontent.com/13566135/82160654-2535fc00-9897-11ea-9f4c-f9562d0004f4.png)

## Steps to reproduce:

Here is my `vulkaninfo`: https://gist.github.com/expenses/dbb273edcba750f58f565cc275a5aa37

This seems like it could be a gpu/driver specific issue, but here is what I did:

1. Install renderdoc commit `22d5cf23136720e22966b80d7cab2b36367923f8`.
2. Clone [wgpu-rs](https://github.com/gfx-rs/wgpu-rs) and checkout commit `c830faa06b4ddf6fe7c747159e949d6c363e0460`.
3. Run `cargo build --example hello-triangle` (requires rust to be installed).
4. Run `target/debug/examples/hello-triangle` to make sure it runs normally.
5. Run `qrenderdoc` and select `target/debug/examples/hello-triangle`.

## Environment

* RenderDoc version: `22d5cf23136720e22966b80d7cab2b36367923f8`
* Operating System: Arch Linux 5.6.13
* Graphics API: Vulkan 1.2.140

**Comment by baldurk** [comment]
The vulkan loader 1.2.140 has [a bug](https://github.com/KhronosGroup/Vulkan-Loader/issues/400) that causes a hang when RenderDoc is enabled, which I suspect is the problem you're hitting. If you run with the latest stable version of the loader 1.2.135 it should work correctly.

**Comment by expenses** [comment]
Oh great, thanks!
