### ISSUE TITLE
Render Overlays partly broken when using Multiview on Vulkan

### ISSUE THREAD

**Issue by Piotr-B** [baldurk/renderdoc#1895]
## Description

When replaying a capture of an app using Multiview on Vulkan some of the render overlay visualization options render incorrectly. 

## Steps to reproduce

1. Capture a frame of a Vulkan app that is using the Multiview extension (Here I'm using a UE 4.24.3 app based on the "Virtual Reality" template running on Oculus Quest: [capture download](https://drive.google.com/open?id=106vdOWktT1C6mTwptJWNLwIsxcgOAgWf))
2. Replay the capture in RenderDoc
3. Try using various overlay modes on the render target and switching between slices

Some of the issues:
* **Highlight Drawcall** and **Wireframe Mesh** overlays display incorrectly when on Slice 0 but correctly on Slice 1
* **Backface Cull** overlay displays incorrectly on Slice 0 but correctly on Slice 1 (except for the first drawcall?)
* **Depth Test** overlay displays using position from slice 1 but depth values from slice 0

It would be useful to have at least one of the slices show the overlays reliably.

## Environment

* RenderDoc version: Nightly 2020_05_17 22d5cf2
* Operating System: Android (Oculus Quest, software version 16.0)
* Graphics API: Vulkan

![Capture_22d5cf2_1](https://user-images.githubusercontent.com/8913735/82263882-254ffd80-9964-11ea-99c3-1672e6baceb7.PNG)
![Capture_22d5cf2_2](https://user-images.githubusercontent.com/8913735/82263894-28e38480-9964-11ea-8c1b-6f2010a993b5.PNG)

**Comment by baldurk** [comment]
That commit should fix the overlays for array textures and when using multiview.
