### ISSUE TITLE
Android server crash during GLES capture with unsigned short 565 texture

### ISSUE THREAD

**Issue by lrg-devrel** [baldurk/renderdoc#1907]
## Description
The server crashes on an Android device during a GLES capture with the following as the last part of the output:
```
gl_emulated.cpp(2659) - Debug   - Doing manual blit from GL_RGB to allow readback
gl_emulated.cpp(2864) - Debug   - Done blit
gl_emulated.cpp(2929) - Debug   - Reading as GL_RGBA/GL_UNSIGNED_SHORT_5_6_5 but impl supported pair is GL_RGBA/GL_UNSIGNED_BYTE
```
Looking at the code there was a recent change to remap some RGB textures to read back as RGBA https://github.com/baldurk/renderdoc/commit/9ea49d6b6ea4b92609f7fe22606383d323bae911

A second change was made to exclude a particular type: https://github.com/baldurk/renderdoc/blob/9014daf76c42c4f7433ea24eed07d353687b5467/renderdoc/driver/gl/wrappers/gl_emulated.cpp#L2657

I made a local change to exclude eGL_UNSIGNED_SHORT_5_6_5 as well which appears to solve this issue. From looking at the code I think that by trying to read this texture as RGBA8 it is writing 32-bit values into a buffer that is expecting 16-bit values, causing an overrun. I think this could also affect the eGL_UNSIGNED_BYTE_3_3_2 format but I don't have a test case for that. Other packed formats include alpha so I don't think they should be affected.

## Steps to reproduce

- Boot up RenderDoc
- Attach to Android remote device
- Start game (a Unity based game in this instance)
- Capture a frame 

In my role as a developer support engineer for Samsung I have been testing RenderDoc against a number of commercial titles to look for issues which might affect developers wanting to debug their games. This was a Unity based title - I can email you with the details if you need them.

## Environment

* RenderDoc version: v1.x branch https://github.com/baldurk/renderdoc/commit/1db2947c86a1d04de5a59ee8d9f20aae572b40c8
* Operating System: Windows 10/Android 9.0
* Graphics API: OpenGLES
* Android device: Samsung Note 10+ 5G (Exynos) - SM-N976B - running Android 9.0

**Comment by baldurk** [comment]
Does the remote server crash or the application? Your description and title says the remote server is crashing but your repro steps seem to indicate that it's the application being captured that crashes.

Either way I need specific repro steps that I can follow. Your repro steps suggest that _all_ unity games on _all_ android devices will crash, and this is simply not true. It may be true that _a_ unity program on _an_ android device will crash, but that is a more specific scenario and I will need more specifics to reproduce the problem and investigate it. If you can't share your program publicly you can email it to me privately at baldurk@baldurk.org.

**Comment by lrg-devrel** [comment]
You're right, it's not the server, but it's not strictly the app either - it's the interception layer, is that the right term?  I'll email you the details about the game I can repro this on.

**Comment by baldurk** [comment]
That commit should make the handling of remapping textures on readback more reliable, including the repro you sent.
