### ISSUE TITLE
Renderdoc crashes on capturing Cinder Vulkan Fish Tornado app!

### ISSUE THREAD

**Issue by oscarbg** [baldurk/renderdoc#191]
Hi,
Some days ago I compiled the Cinder Vulkan Fish Tornado app and it works ok..
Sadly also starting Renderdoc capture crashes the program..
I have 32bit and 64bit Debug and Release builds and all 4 combinations fail..
As building it takes some time I'm attaching binary build with 4 exes in case want to avoid building:
bit.ly/1Q8HFZ2

**Comment by baldurk** [comment]
Thanks! This should definitely work so I'll check into it.

**Comment by baldurk** [comment]
Hmm, so running on my GTX 970 on win7 with 356.39 I get the results:

* FishTornado64d.exe - runs fine, and captures & replays fine. No problems
* FishTornado64.exe - runs OK but crashes when left-clicking to pan, even without renderdoc. If I avoid that, it captures & replays fine too.

I didn't try the 32bit builds. But it means that it's working for me.

Which OS/hardware/driver are you on? I assumed nvidia from the other bug filed.

**Comment by chaoticbob** [comment]
Hi,
I'm the maintainer of the Cinder's Vulkan parts and updater of FishTornado. Happy to help take a look at this as well. Would be super of Cinder could make use of the awesome RenderDoc.

**Comment by baldurk** [comment]
Hey, right now I'm at the "trying to reproduce" stage :). I've made a few fixes since the bug was filed - nothing that should fix a crash but you never know.

Do you have any issues running RenderDoc using the latest nightly build?

**Comment by vinjn** [comment]
Can't repro on my 64bits build.
Both capture and replay works!
Amazing.

**Comment by oscarbg** [comment]
Sorry for lag in testing..
now seems also works for me..
