### ISSUE TITLE
Fail to detect the supported ABI of an x86 Android device

### ISSUE THREAD

**Issue by 06393993** [baldurk/renderdoc#1912]
## Description

Renderdoc fails to detect the ABI support for an x86 Android device, because [this line](https://github.com/baldurk/renderdoc/blob/b9a9542f3b77ecf3685dc57aa93bd92430606933/renderdoc/android/android_utils.cpp#L103) uses `x86-v7a` to test the `ro.product.cpu.abi`, but this property will be `x86` on an x86 device instead of `x86-v7a`. You can verify this by calling `adb shell getprop ro.product.cpu.abi` on an Android Emulator with an x86 image.

## Steps to reproduce

1. Launch the Android Emulator installed with the Android studio with an x86 image.
1. Call `adb devices` to verify that the Android Emulator is connected with the `adb`.
1. Launch the Renderdoc, click the button at bottom left corner and choose the "Google Android SDK built for x86".
1. An alert box will pop up with the message "Couldn't determine supported ABIs for your device, please check device connection and status."
1. Call `adb shell getrpop ro.product.cpu.abi` to make sure the image does have a valid `ro.product.cpu.abi` property

## Environment

* RenderDoc version: v1.8 (built from 8b491e15)
* Operating System: Windows 10 Enterprise 18362.836
* Graphics API: N/A

**Comment by baldurk** [comment]
Neither android emulators nor x86 based ABIs on android are supported by RenderDoc.
