### ISSUE TITLE
Crash in WSAStartup_hook during Renderdoc initialization

### ISSUE THREAD

**Issue by arkgmarion** [baldurk/renderdoc#1916]
## Description

During initialization I experience a systematic crash on line 174 of  sys_win32_hooks.cpp :
    int ret = syshooks.WSAStartup()(wVersionRequested, lpWSAData);

The WSAStartup function pointer resolves to NULL.

I eventually managed to track down the cause of it :
- At the end of RegisterHooks(), the 2 hooks pointers WSAStartup & WSACleanup are correctly initialized and registered in the FunctionHooks array of the DllHookset of ws2_32.dll
- Then at the beginning of LibraryHooks::EndHookRegistration(), std::sort is called on the FunctionHooks array
- the sort tries to swap the 2 entries for WSAStartup & WSACleanup. After this swap, the WSAStartup orig field becomes NULL.

I fixed it by adding a copy constructor and a copy operator to the FunctionHooks struct.

It seems from the history that no code has changed in hooks management for a very long time, so I don't know what caused this behavior to appear during my upgrade from 1.6 to 1.8.
Maybe a compiler upgrade on our side, we are now using Visual C++ 2017 (version 19.16.27031.1)

## Steps to reproduce

Probably as simple as :
- initialize renderdoc
- call WSAStartup 
- crash

## Environment

* RenderDoc version: 1.8
* Operating System: Win 10 build 1909
* Graphics API: D3D11

**Comment by baldurk** [comment]
Something doesn't sound right here. I compiled with VS 2017 (not the exact same version - I'm on latest 15.9.23 and it looks like 19.16.27031.1 is an older version 15.9.12) and I can't repro this problem.

I'm far from a C++ standard expert but I don't see anything that should prevent that struct from having a normal auto-generated copy constructor and assignment operator generated for it that will do the correct thing. Even if there wasn't an auto-generated one for some reason, that should be a compile error to use it, something like this (I added a reference to prevent the automatic copy constructor):

```

1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\algorithm(3835): error C2280: 'FunctionHookBlah &FunctionHookBlah::operator =(const FunctionHook &)': attempting to reference a deleted function
1>t:\tmp\foo\renderdoc\os\win32\win32_hook.cpp(894): note: compiler has generated 'FunctionHook::operator =' here
1>t:\tmp\foo\renderdoc\os\win32\win32_hook.cpp(894): note: 'FunctionHook &FunctionHook::operator =(const FunctionHook &)': function was implicitly deleted because 'FunctionHook' has a data member 'FunctionHook::b' of reference type
1>t:\tmp\foo\renderdoc\os\win32\win32_hook.cpp(893): note: see declaration of 'FunctionHook::b'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\algorithm(4023): note: see reference to function template instantiation '_BidIt std::_Insertion_sort_unchecked<_RanIt,_Pr>(_BidIt,const _BidIt,_Pr)' being compiled
1>        with
1>        [
...
```

This sounds more like a compiler bug than a renderdoc bug from what you're describing. Do you see the same behaviour on the official 1.8 build (built with VS 2015)? Can you try the latest VS2017 version, or another compiler?

Does the whole struct get destroyed, or are `name` and `hook` swapped properly? What's the assembly for the autogenerated copy constructor if you step into it in debug?

**Comment by arkgmarion** [comment]
name & hook are swapped properly, only orig is not
I just tried using the development config for renderdoc and everything works as intended

Digging into the asm of the release config right now, I hate debugging stl stuff.
I'll upgrade my compiler after I'm done with the asm analysis

I mixed up an info about the compiler : 
the game is compiled with 19.16.27031.1 but renderdoc with 19.00.24215.1

**Comment by baldurk** [comment]
That's very weird, that's the exact same compiler version I am using in that case.

Before going too far, it might be worth doing a clean & rebuild all in case it's a weird compiler glitch from a previous compile. There haven't been any significant changes to those files but there have been some less significant changes so it could be re-using previous compilation in a weird way.

For reference here's the assembly for the auto-generated `FunctionHook::FunctionHook(FunctionHook && __that)` in release for me, showing the call to `rdcstr(rdcstr&&)` as well as moving the orig pointer at +0x18 and the hook pointer at +0x20:

```
000007FEB84256F0  mov         qword ptr [rsp+10h],rdx  
000007FEB84256F5  mov         qword ptr [rsp+8],rcx  
000007FEB84256FA  push        rdi  
000007FEB84256FB  sub         rsp,20h  
000007FEB84256FF  mov         rdi,rsp  
000007FEB8425702  mov         ecx,8  
000007FEB8425707  mov         eax,0CCCCCCCCh  
000007FEB842570C  rep stos    dword ptr [rdi]  
000007FEB842570E  mov         rcx,qword ptr [this]  
000007FEB8425713  mov         rax,qword ptr [__that]  
000007FEB8425718  mov         rcx,qword ptr [this]  
000007FEB842571D  mov         rdx,rax  
000007FEB8425720  call        rdcstr::rdcstr (07FEB7CD474Ah)  
000007FEB8425725  mov         rax,qword ptr [this]  
000007FEB842572A  mov         rcx,qword ptr [__that]  
000007FEB842572F  mov         rcx,qword ptr [rcx+18h]  
000007FEB8425733  mov         qword ptr [rax+18h],rcx  
000007FEB8425737  mov         rax,qword ptr [this]  
000007FEB842573C  mov         rcx,qword ptr [__that]  
000007FEB8425741  mov         rcx,qword ptr [rcx+20h]  
000007FEB8425745  mov         qword ptr [rax+20h],rcx  
000007FEB8425749  mov         rax,qword ptr [this]  
000007FEB842574E  add         rsp,20h  
000007FEB8425752  pop         rdi  
000007FEB8425753  ret  
000007FEB8425754  int         3  
000007FEB8425755  int         3 
```

and `operator =(FunctionHook&&)`:

```
000007FEB8425E30  mov         qword ptr [rsp+10h],rdx  
000007FEB8425E35  mov         qword ptr [rsp+8],rcx  
000007FEB8425E3A  push        rdi  
000007FEB8425E3B  sub         rsp,20h  
000007FEB8425E3F  mov         rdi,rsp  
000007FEB8425E42  mov         ecx,8  
000007FEB8425E47  mov         eax,0CCCCCCCCh  
000007FEB8425E4C  rep stos    dword ptr [rdi]  
000007FEB8425E4E  mov         rcx,qword ptr [this]  
000007FEB8425E53  mov         rax,qword ptr [__that]  
000007FEB8425E58  mov         rcx,qword ptr [this]  
000007FEB8425E5D  mov         rdx,rax  
000007FEB8425E60  call        rdcstr::operator= (07FEB7CF26EBh)  
000007FEB8425E65  mov         rax,qword ptr [this]  
000007FEB8425E6A  mov         rcx,qword ptr [__that]  
000007FEB8425E6F  mov         rcx,qword ptr [rcx+18h]  
000007FEB8425E73  mov         qword ptr [rax+18h],rcx  
000007FEB8425E77  mov         rax,qword ptr [this]  
000007FEB8425E7C  mov         rcx,qword ptr [__that]  
000007FEB8425E81  mov         rcx,qword ptr [rcx+20h]  
000007FEB8425E85  mov         qword ptr [rax+20h],rcx  
000007FEB8425E89  mov         rax,qword ptr [this]  
000007FEB8425E8E  add         rsp,20h  
000007FEB8425E92  pop         rdi  
000007FEB8425E93  ret  
000007FEB8425E94  int         3  
000007FEB8425E95  int         3
```

**Comment by arkgmarion** [comment]
Everything was inlined and much shorter than that

However, after upgrading my compiler, everything went back to normal and is working fine with the stock renderdoc code.

Sorry for the false alarm, it was probably a compiler bug.

**Comment by baldurk** [comment]
That's definitely a weird glitch. Glad you got it working though, I'm going to close this issue then.
