### ISSUE TITLE
Vulkan application stops responding when executed with renderdoc

### ISSUE THREAD

**Issue by SiebenCorgie** [baldurk/renderdoc#1917]
## Description
Hi, for some reason RenderDoc stopped working for me on Linux with my hobby vulkan application. The issue is, that when I run my applications in renderdoc, the applications stops responding at the create-Instance step.

Note that the application is written in Rust and uses the ash wrapper around vulkan. If you don't want to search for the problem, just let me know. That would be totally understandable.

However, it worked up to a point and now doesn't, so it might be some interesting bug.

I tested it on a system with ryzen1700x + AMD vega 56 as well as a intel hd4000 base Dell XPS13.

## Steps to reproduce
The code can be found on the master branch as of writing the issue [here](https://gitlab.com/tendsinmende/marp) (hash: 487b8dca). However, after hopefully fixing the issue the master branch will change.

Steps to reproduce:
1. install rust toolchain via rustup
2. change into `marp/` directory and execute `cargo run --example cube_textures --release` (this will build my vulkan wrapper (marp) and execute the "textured cube" example). This should work.
3. copy the executable to the projects root, for instance `cp target/release/examples/cube_textures run.bin`
4. try to launch `run.bin` in renderdoc and observe, that the application hangs. Launching without renderdoc should still work fine.

The interesting bits are:
- in marp/src/instance/mod.rs [link](https://gitlab.com/tendsinmende/marp/-/blob/master/marp/src/instance/mod.rs#L65) where the vulkan call for creating the instance is issued
- marp-utils/src/mod.rs first line of `create_device_and_gfx_queue()` [link](https://gitlab.com/tendsinmende/marp/-/blob/master/marp-utils/src/lib.rs#L58) where the instance creation parameters are set

According to my print debugging it starts not responding when the createInstance call is issued. 
If there is more I can do to debug the issue, just let me know.

## Environment
* RenderDoc version: 1.8
* Operating System: ArchLinux 5.6.14
* Graphics API: 
1. AMD Vega 56 with amvlk2020.Q2.3-1 (closed source driver) and mesa
2. intel hd4000 with vulkan-intel 20.0.7-3

**Comment by baldurk** [comment]
Since you're using Arch linux I assume you're using a bleeding-edge loader 1.2.140, which [has a bug that causes this deadlock](https://github.com/KhronosGroup/Vulkan-Loader/issues/400). Revert to the last stable loader 1.2.135 and this issue should go away.
