### ISSUE TITLE
adb devices disconnects RenderDoc

### ISSUE THREAD

**Issue by pemgithub** [baldurk/renderdoc#1922]
## Description

For certain tests, I want to run an (adb shell am broadcast) command to run a particular frame.

However, running any adb command, even (adb devices) disconnects RenderDoc.  There should be a way to issue an adb command from RenderDoc that doesn't cause RenderDoc to disconnect.

## Steps to reproduce

In general, connect RenderDoc to an Android device, open an APK from RenderDuc GUI then run (adb devices).

Here's a specific example of what I want to do...

1) Install GFXBench5

2) In RenderDoc connect to Android device, then launch:

net.kishonti.gfxbench.vulkan.v50000.corporate/net.kishonti.app.MainActivity

3) run this on adb shell:

adb shell am broadcast -a net.kishonti.testfw.ACTION_RUN_TESTS -n net.kishonti.gfxbench.vulkan.v50000.corporate/net.kishonti.benchui.corporate.CommandLineSession -e test_ids "gl_manhattan" --ei raw_config.single_frame 56400 --ei raw_config.max_rendered_frames 1 --es -screenshot_frames 0

## Environment

* RenderDoc version: 1.8
* Operating System: Windows 10
* Graphics API: GLES

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by pemgithub** [comment]
@baldurk yes I have a license for GFXBench5 which includes source code.  This is for GPU development (business partner).  Sorry about the confusion.

Also, the real problem is that adb commands such as (adb devices) or (adb am shell broadcast) cause RenderDoc to disconnect.  I was just using GFXBench5 (adb shell am broadcast) as an example.

**Comment by baldurk** [comment]
That's easy to claim but I have no way to verify that. People abusing RenderDoc is too common for me to try to argue each case, my policy is clear and not up for debate.

**Comment by pemgithub** [comment]
What is the relationship between "running any adb command, even (adb devices) disconnects RenderDoc" and "copyrighted programs"?  Sorry I am confused on this.  To me, it seems unrelated.

**Comment by pemgithub** [comment]
I don't know how it works in terms of legal agreements.  However, GPU developers (IHV's) run public builds of games and apps to develop, debug, test, and research their GPU hardware, drivers, tools, etc.  Presumably this is good for ISV's too.  I think RenderDoc can be useful to GPU vendors and probably to others who are doing R&D for related software and hardware.

**Comment by baldurk** [comment]
Please do not comment on old closed issues.
