### ISSUE TITLE
Vulkan Color Attachments show as completely black after every draw call on Windows

### ISSUE THREAD

**Issue by thatcosmonaut** [baldurk/renderdoc#1926]
## Description

I am currently helping to develop the Vulkan backend for FNA3D. When capturing output from the game Wizorb, the color attachment displays black on every draw command. I tested this with Renderdoc v1.8 on Windows and Linux on the same hardware, and it only happens on Windows.

## Steps to reproduce

1. Build FNA.dll and FNA3D.dll from source
2. Download the Linux depot of Wizorb (the assemblies are portable, so the executable will work on windows)
2. Place the dlls into the Wizorb directory
3. Launch the game through Renderdoc
4. All color attachments will display completely black

RDC: https://send.firefox.com/download/1afbe6be4d42ce43/#I-Jm9wcuAoLdd9m70Ke4OA

## Environment

* RenderDoc version: 1.8
* Operating System: Windows 10 64-bit
* Graphics API: Vulkan

* Graphics card: NVIDIA GTX 970
* Vulkan Driver: NVIDIA 445.75
* Vulkan Conformance Version: 1.1.0

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by flibitijibibo** [comment]
The FNA3D Vulkan renderer is being developed under my supervision, and I am the Linux/macOS developer for Wizorb:

http://www.flibitijibibo.com/index.php?page=Portfolio/Ports#28_wizorb.txt

All of the Vulkan work is being done in FNA or FNA3D, same as the overall rendering and GL work that currently ships in the Steam depot. The Steam version just happens to be the most convenient way to pull down a stable version.

**Comment by baldurk** [comment]
The rules are clear and not up for discussion.
