### ISSUE TITLE
BufferFormatter::GetVarSize is wrong for non-square matrices

### ISSUE THREAD

**Issue by simondeschenes** [baldurk/renderdoc#1927]
## Description

The code may be wrong only under the Vulkan API however.

The incorrect size leads to having padBytes be 0xfffffff0 in BufferFormatter::DeclareStruct, which then freezes RenderDoc when trying to view the buffer that uses this struct.

The problematic code is :
```
  if(var.type.descriptor.rows > 1)
  {
    if(var.type.descriptor.rowMajorStorage)
      size = var.type.descriptor.matrixByteStride * var.type.descriptor.columns;
    else
      size = var.type.descriptor.matrixByteStride * var.type.descriptor.rows;
  }
```

I have a structure that contains 2 row_major mat4x3.
The "SPIR-V (RenderDoc)" output for this struct is:
```
struct MyBufferType {
  float4x3 M0 : [[RowMajor, MatrixStride(16), Offset(0)]];
  uint M1 : [[Offset(48)]];
  uint M2 : [[Offset(52)]];
  uint M3 : [[Offset(56)]];
  uint M4 : [[Offset(60)]];
  float4x3 M5 : [[RowMajor, MatrixStride(16), Offset(64)]];
}
```

The generated SPIR-V declaration for the mat4x3 type is :
```
%v3float = OpTypeVector %float 3
%mat4v3float = OpTypeMatrix %v3float 4
%MyBufferType = OpTypeStruct %mat4v3float %uint %uint %uint %uint %mat4v3float
```

The decoration on the SPIRV struct members is effectively RowMajor :
```
OpMemberDecorate %MyBufferType 0 Offset 0
OpMemberDecorate %MyBufferType 0 MatrixStride 16
OpMemberDecorate %MyBufferType 0 RowMajor
OpMemberDecorate %MyBufferType 1 Offset 48
OpMemberDecorate %MyBufferType 2 Offset 52
OpMemberDecorate %MyBufferType 3 Offset 56
OpMemberDecorate %MyBufferType 4 Offset 60
OpMemberDecorate %MyBufferType 5 Offset 64
OpMemberDecorate %MyBufferType 5 MatrixStride 16
OpMemberDecorate %MyBufferType 5 RowMajor
```

Here is what happens when the application freezes.

```
const uint32_t size = GetVarSize(*lastChild);
uint32_t padBytes = requiredByteStride - (lastMemberStart + size);

if(padBytes > 0)
      ret += lit("    ") + DeclarePaddingBytes(padBytes);
```

requiredByteStride = 112
lastMemberStart = 64

The last member of the struct is really 48 bytes, but the function returns 64, 
This translates to:
```
uint32_t padBytes = 112 - (64 + 64);
// uint32_t padBytes = 112 - 128;
```
Instead of:
```
uint32_t padBytes = 112 - (64 + 48);
// uint32_t padBytes = 112 - 112;
```

This underflow causes the code to call DeclarePaddingBytes with the underflowing value 0xfffffff0 (4294967280).

RenderDoc then spends a lot of time trying to read a buffer with structs having around 4GB of padding.

## Steps to reproduce

Create a struct equivalent to the one above and use it as the type for a Buffer you will bind to any shader stage.

Try to look at the content of the Buffer inside of RenderDoc.
Notice the application freezes.

Note that the shader is coded in HLSL and compiled to Vulkan using DirectXShaderCompiler. However, I would assume the same behaviour would occur with a shader coded in glsl.

## Environment

* RenderDoc version: 1.8
* Operating System: Windows 10
* Graphics API: Vulkan 1.2

**Comment by baldurk** [comment]
Thanks, that commit should fix the issue at least from my tests. If you still have issues please share a reproducible test case.

**Comment by simondeschenes** [comment]
Everything works fine, thanks
