### ISSUE TITLE
Failing to get sudo fails silently.

### ISSUE THREAD

**Issue by rukai** [baldurk/renderdoc#1932]
## Description

When I install and run renderdoc it asks me to run vulkan layer registration.
So I click the message to do so, press yes, then yes again.
But then nothing happens.
Through some investigation I found this issue https://github.com/baldurk/renderdoc/issues/927
which reveals that it will fall back to many ways of getting sudo.
However I happen to have none of those installed.

After installing xterm it popped up an xterm window and i could give it sudo access.
I think that running out of ways to get sudo should not fail silently.
Instead it should provide a message saying something like "none of the sudo providers are installed please install one from this list"

## Steps to reproduce
Install and run renderdoc.
Click on the vulkan layer registration button -> yes -> yes

## Environment

* RenderDoc version: 1.8
* Operating System: Arch Linux
* Graphics API: Vulkan

**Comment by baldurk** [comment]
That commit should promote the error messages that are printed to be error dialogs.

What terminal emulator did you have installed? I thought that most modern distros set up x-terminal-emulator as an alias which is set up with symlink/alternatives to point to the preferred emulator.

**Comment by rukai** [comment]
Thanks, that change sounds good to me.

I use termite.
x-terminal-emulator does not seem to be a thing on arch.

**Comment by edap** [comment]
I have the same issue. running `sudo ./qrenderdoc --install_vulkan_layer 1` did not install the vulkan layer, it quits without errors/logs.
I can use renderdoc just running it with sudo from the command line

**Comment by baldurk** [comment]
Please do not comment on old closed issues. If you have a problem please open a new issue with clear steps to reproduce.
