### ISSUE TITLE
RenderDoc 1.8 Fails to compile on Arch Linux

### ISSUE THREAD

**Issue by Ryp** [baldurk/renderdoc#1936]
## Description

The binary release is giving me problems, so I wanted to try a local build to see if my problem persisted. During that process the build fails when it can't find a `swig` binary.

## Steps to reproduce

Install the `renderdoc` package from [AUR](https://aur.archlinux.org/packages/renderdoc/). Take a look at the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=renderdoc) to clearly see what is the build command executed by the package manager.

Here's the log for the failure I'm encountering:
```
Scanning dependencies of target renderdoccmd
[ 95%] Building CXX object renderdoccmd/CMakeFiles/renderdoccmd.dir/renderdoccmd.cpp.o
[ 95%] Performing install step for 'custom_swig'
[ 96%] Building CXX object renderdoccmd/CMakeFiles/renderdoccmd.dir/renderdoccmd_linux.cpp.o
[ 96%] Linking CXX executable ../bin/renderdoccmd
[ 96%] Built target renderdoccmd
[ 96%] Completed 'custom_swig'
[ 96%] Built target custom_swig
Scanning dependencies of target swig-bindings
[ 97%] Generating renderdoc_python.cxx, renderdoc.py
[ 97%] Generating qrenderdoc_python.cxx, qrenderdoc.py
/bin/sh: ../bin/swig: No such file or directory
make[2]: *** [qrenderdoc/CMakeFiles/swig-bindings.dir/build.make:108: qrenderdoc/renderdoc_python.cxx] Error 127
make[2]: *** Waiting for unfinished jobs....
/bin/sh: ../bin/swig: No such file or directory
make[2]: *** [qrenderdoc/CMakeFiles/swig-bindings.dir/build.make:141: qrenderdoc/qrenderdoc_python.cxx] Error 127
make[1]: *** [CMakeFiles/Makefile2:600: qrenderdoc/CMakeFiles/swig-bindings.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```
Let me know if you think this is a package issue, in that case I'll dig some more. 

## Environment

* RenderDoc version: 1.8
* Operating System: Arch Linux
* Graphics API: Vulkan

**Comment by baldurk** [comment]
I do not provide any support for downstream packages. If you have a problem building directly from this repository's source then open an issue outlining how you're building and what goes wrong.
