### ISSUE TITLE
Crash loading a vulkan frame capture

### ISSUE THREAD

**Issue by tambry** [baldurk/renderdoc#194]
So, I've been frustrated with trying to get my Vulkan application to work (it doesn't render anything :(), so I was suggested to use RenderDoc.

Steps:
1. Select my application to be captured
2. Start the capture
3. Press F12 to capture a frame
4. Close the application to view the capture information
5. RenderDoc crashes during loading of the capture information

I tried both RenderDoc 0.27 and the latest nightly. Both crash.
My application .exe: http://puu.sh/nkO5T/f64982796f.rar
Full source code: https://github.com/NGEmu/NGEmu

System specifications:
Windows 10 Pro 64-bit
GTX 770
Driver 356.43

**Comment by baldurk** [comment]
Thanks for the report! This could be a couple of things, I'll need to repro it to investigate. I will do that tonight.

Can you share your windows version/hardware/driver?

**Comment by tambry** [comment]
@baldurk Thank you. Sorry for forgetting to include those.
My system:
Windows 10 Pro 64-bit
GTX 770
Driver 356.43

**Comment by baldurk** [comment]
I can't build your code unfortunately so I'm not able to verify this fix, but it looks like the problem is in ImGuiVulkanRenderer::imgui_render - you delete the framebuffer before submitting the command buffer that uses it, and renderdoc crashes since the framebuffer is not available on replay.

Also FYI it seems like a lot of creation structures have pNext set to uninitialised values, since I get a lot of asserts firing that they're not NULL (as expected since right now nothing makes use of them). Probably the ICDs don't care right now and ignore these, but it's a good idea to set them to NULL.

**Comment by tambry** [comment]
@baldurk Thank you. Wouldn't it be possible for RenderDoc to detect this and instead of crashing display an error message?
Also, what problems have you encountered building the code?

**Comment by baldurk** [comment]
In this case it would perhaps be possible, but in the general case for an API like Vulkan RenderDoc is not in a position to validate API usage. I assume the application is correctly formed and not doing anything illegal, so this is exactly the kind of thing that should instead be caught by validation layers.

Let me know if it works for you after changing that code.

At first I wasn't sure how to set up the submodules in the right place. I tried to compile just Common and NGEmu (in case maybe the glslang-build and vulkan-build projects are optional) and I eventually ran into an error "LINK : fatal error LNK1158: cannot run 'rc.exe'".
I have built other projects with VS2015, but it's possible the install of VS2015 or the win10 SDK or both is messed up on my system. I use VS2010 for RenderDoc.

**Comment by tambry** [comment]
After fixing the framebuffer deletion, RenderDoc now seems to correctly load the frame dump. Thank you.

The submodules should be initialized by executing _git submodule update --init_. After opening NGEmu solution and building the solution should correctly build all the required dependencies and submodules. But judging by that you managed to get to the linking stage, I assume you probably managed that.
The message about linking failing is strange and I'm not sure why you would encounter it. According to a quick Google search it may be caused by not all required executables being on the path correctly. You could try repairing your VS2015 installation and/or updating to VS2015 Update 1, if you want to.
