### ISSUE TITLE
`wglGetProcAddress(...)` succeeds (?), but still reports an error

### ISSUE THREAD

**Issue by geometrian** [baldurk/renderdoc#1942]
## Description

It seems that when running in RenderDoc on Windows, certain arguments to `wglGetProcAddress(...)` will return a pointer, but still set the error. However, according to [the documentation](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-wglgetprocaddress), that function must either set an error and return null or else not set an error and return a pointer.

I believe this to be a problem with RenderDoc, since this problem does not occur in other environments (such as freestanding, or indeed, in other debuggers, such as NSight Graphics).

Most of the time the function works as expected. I noticed the incorrect behavior when loading every function pointer (in this case, the first failure was `"glInsertEventMarkerEXT"`).

It should also be noted that other return values than null or a pointer have been known to exist (not necessarily in RenderDoc) (see e.g. [here](https://www.khronos.org/opengl/wiki/Load_OpenGL_Functions#Windows) for an attestation of return values of `(PROC)(-1)`, `(PROC)1`, `(PROC)2`, and `(PROC)3`, which are also erroneous). However, that does not seem to be the case here. For `"glInsertEventMarkerEXT"`, I got `0x00007FFD3F9DC5E0`, which looks like a reasonable pointer to me.

## Steps to reproduce

After creating a context in the usual way, run some code like this (simplified from actual code):

```cpp
PROC load_fn(char const* name) {
	HMODULE module = LoadLibraryA("opengl32.dll");
	assert(GetLastError()==0);

	//Attempt to load from GL <= 1.1
	PROC proc = GetProcAddress(module,name);
	if (proc!=nullptr) {
		assert(GetLastError()==0);
		return proc;
	}
	//Ignore error; it just means function doesn't exist, or belongs to API GL >= 1.2
	SetLastError(0);
	assert(GetLastError()==0);

	//Attempt to load from GL >= 1.2
	proc = wglGetProcAddress(name);
	if (proc!=nullptr) {
		assert(GetLastError()==0); //#### MARKED LINE ####
		return proc;
	}
	//Ignore error; it just means function doesn't exist
	SetLastError(0);
	assert(GetLastError()==0);

	return nullptr;
}
```
Call this function with `load_fn("glInsertEventMarkerEXT")`, and the marked line will fail. The error (from `FormatMessage(...)`) will be `"The specified procedure could not be found.\n"`. Again, this is incorrect, because it has been found.

This should be enough to reproduce the problem, but I've also attached my actual debug-mode application which reproduces it:
[issue-materials.zip](https://github.com/baldurk/renderdoc/files/4768030/issue-materials.zip)
When run in freestanding mode, it will abort due to not finding art assets. When run in RenderDoc, it will crash before that because it will fail to load the function pointers.

## Environment

* RenderDoc version: v1.8 (built from 8b491e1) (current)
* Operating System: Windows 10 Pro (Version 1909, build 18363.900) (current)
* Graphics API: OpenGL 4.5 (debug context)
* GPU: NVIDIA GeForce GTX 1080
* Driver: 446.14 (current)

**Comment by baldurk** [comment]
I believe that commit should fix the GetLastError() you're seeing.

Note however that the behaviour you're relying on is _not_ what the documentation says. From the linked wglGetProcAddress page:

> When the function succeeds, the return value is the address of the extension function.
>
> When no current rendering context exists or the function fails, the return value is NULL. To get extended error information, call GetLastError.

You said that this means either NULL should be return and an error is set, or else a valid pointer should be returned and no error is set. However in the case where the function succeeds and a pointer is returned there is nothing said about whether an error is set or not.

In particular if you look at the documentation for [GetLastError](https://docs.microsoft.com/en-gb/windows/win32/api/errhandlingapi/nf-errhandlingapi-getlasterror) it calls this out specifically:

> The Return Value section of the documentation for each function that sets the last-error code notes the conditions under which the function sets the last-error code. Most functions that set the thread's last-error code set it when they fail. **However, some functions also set the last-error code when they succeed. If the function is not documented to set the last-error code, the value returned by this function is simply the most recent last-error code to have been set; some functions set the last-error code to 0 on success and others do not.**

Bolding mine, but the short version is that you shouldn't be relying on GetLastError() being 0 when you've been told that the function succeeds, you should only check it when the function has returned an error (and in that case you are able to rely that it gives you an error code).

**Comment by geometrian** [comment]
Thank you for the quick response! Building from source, I confirm that this seems to fix the problem.
<hr/>
For completeness: my original statement depended implicitly on exactly that same paragraph you quoted. Namely, `GetLastError()` should not set the error code on success, because that is not a condition under which `wglGetProcAddress(...)` is documented to set it.

> The Return Value section of the documentation for each function that sets the last-error code notes the conditions under which the function sets the last-error code.

Therefore, the success/no-set-error and failure/set-error cases are exclusive. You are correct that this is _not_ true for any random function. Also, of course, set errors could propagate from other functions, which is why I put asserts (e.g. after `LoadLibrary`) to ensure any set error came from a known place.
