### ISSUE TITLE
Fails to capture applications with unknown ABI on Android 10

### ISSUE THREAD

**Issue by tabikati** [baldurk/renderdoc#1944]
## Description

For some Android applications, the primaryCpuAbi field is 'null' in the 'adb shell pm dump <packagename>' output. Since it is not an empty string, we won't get an error message for it when the ABI is determined (the ABI will be 'null' too) and it continues by getting the appropriate RenderDoc package name for this ABI which will be invalid ('org.renderdoc.renderdoccmd.unsupported').
On Android 10, this package name will be set as the gpu_debug_layer_app, and the capture will fail as an incorrect layer app is specified.

Our suggestion is to try to use the 64-bit package name ('org.renderdoc.renderdoccmd.arm64') as the gpu_debug_layer_app if the ABI can not be determined, or check the primaryCpuAbi field if it's 'null' and throw an error message in this case too. What do you think which one would be the better approach? We are happy to do the implementation for both cases.

## Steps to reproduce

- Try to capture an Android application whose primaryCpuAbi field is 'null' in the 'adb shell pm dump <packagename>' output, on a device with Android 10.

## Environment

* RenderDoc version: 1478aeddde1664acab4828948e77c9051948eaaa
* Operating System: Android 10

**Comment by baldurk** [comment]
Can you please share a reproducible APK that can be used to demonstrate this problem, at the moment I can't follow your steps to reproduce because I don't understand how a program can have no ABI at all.

**Comment by tabikati** [comment]
Some applications don't contain any native libraries. These libraries can be found in the APK's "lib" folder, under the "arm64" subfolder in case of 64-bit ABI, and the "arm" subfolder in case of 32-bit ABI. (On the device, the path is: /data/app/<packagename>/lib/arm(64).)
If there are no such folders, the ABI can't be determined by retrieving the primaryCpuAbi field from the "adb shell pm dump" output because it will be 'null'. (It doesn't mean that they don't have an ABI, it's just that it can't be determined this way.)
Here are the steps in the getBundledAppAbi method:
https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/pm/PackageAbiHelperImpl.java

This APK doesn't contain any native libraries so we can reproduce the issue with it: 
[gles_demo_app-debug.apk.zip](https://github.com/baldurk/renderdoc/files/4797022/gles_demo_app-debug.apk.zip)



Executing this adb command we can see that it's primaryCpuAbi is null:

adb shell pm dump com.example.tabikati.glesdemo
```
...
Packages:
  Package [com.example.tabikati.glesdemo] (35edb80):
    userId=10116
    pkg=Package{6a255b1 com.example.tabikati.glesdemo}
    codePath=/data/app/com.example.tabikati.glesdemo-Bv5CqVf0IIAuwWIFVBhaKw==
    resourcePath=/data/app/com.example.tabikati.glesdemo-Bv5CqVf0IIAuwWIFVBhaKw==
    legacyNativeLibraryDir=/data/app/com.example.tabikati.glesdemo-Bv5CqVf0IIAuwWIFVBhaKw==/lib
    primaryCpuAbi=null
    secondaryCpuAbi=null
... 
```

**Comment by baldurk** [comment]
That commit falls back to the preferred device ABI, which works for me on my tests with that example.
