### ISSUE TITLE
Push constants not set when capturing vertex outputs

### ISSUE THREAD

**Issue by krys-g** [baldurk/renderdoc#1945]
## Description

I have a simple Vulkan application that has that vertex shader:

```
#version 420
  
layout(location = 0) in vec2 pos;
layout(location = 1) in vec2 tcl;
layout(location = 2) in vec2 tcs;

layout(location = 0) out vec2 otcl;
layout(location = 1) out vec2 otcs;
layout(location = 2) out vec4 debug;
layout(location = 3) out vec4 debug2;

layout(push_constant, std140) uniform PC
{
    mat4 mvp;
    uint frame;
    uint object_id;
} pc;

void main()
{
    otcs = tcs;
    otcl = tcl;

    vec4 p = vec4(pos.x, pos.y, 0.0, 1.0);
    debug = p;
    debug2 = vec4(pc.frame, pc.object_id, p.x, p.y);
    gl_Position = pc.mvp * p;
}
```

Running the application in renderdoc produces the expected frame; but the captured `gl_Position` coordinates in the "Mesh Viewer" panel are all zeros. It appears that values from the push_constant buffer are not set when capturing the vertex outputs (I assume you replay the vertex shader as some sort of compute job, since the actual output is correct).

![s1](https://user-images.githubusercontent.com/1149772/84568581-aabaa800-ad80-11ea-9a23-f829dd937fd8.png)

Interestingly, the push constants _are_ correctly displayed in the "Pipeline State" panel.

![s2](https://user-images.githubusercontent.com/1149772/84568585-aee6c580-ad80-11ea-8b4e-4d06bdb4b165.png)

## Steps to reproduce

- Have an Vulkan application that runs a pipeline with the attached vertex shader. If my guess is correct, any vertex draw call that uses push constants for the MVP matrix should exhibit the issue. 
- I can share the capture file privately, that's probably more convenient. (it contains IP that I do not own, though it probably falls under Fair Use).
- Go to the `vkCmdDrawIndexed` call that uses the pipeline (EID=21)
- Switch to the Mesh Viewer -> all `gl_PerVertex.gl_Position` are zeros. The debug values based on push constant sources are also zeros.

## Environment

* RenderDoc version: v1.7+dfsg-2 (official Debian amd64 package)
* Operating System: Linux 64-bit
* Graphics API: Vulkan
* GPU: NVidia

**Comment by baldurk** [comment]
You're running an old version, this is a bug that has already been fixed in v1.8, where push constant ranges that covered more than one shader stage weren't properly applied when fetching the mesh output.
