### ISSUE TITLE
RenderDoc calls vkCmdEndRenderPass() without moving to the final subpass

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#195]
To reproduce:

1. Build & run Fish Tornado application from Cinder library (https://github.com/cinder/Cinder/tree/vulkan)
2. Capture a single frame.
3. Wait for the log to load.

At certain point, the following code will be executed:

![image](https://cloud.githubusercontent.com/assets/9154207/13394580/b5c93a96-dee9-11e5-83d5-9401d3c9ab25.png)

vkCmdEndRenderPass() is fine for single-subpass renderpasses, however for cases where a renderpass consists of multiple subpasses, I'm seeing an issue where RenderDoc calls vkCmdEndRenderPass() without moving through the whole subpass chain. This is required, as per spec language:

![image](https://cloud.githubusercontent.com/assets/9154207/13394626/f5ab79b2-dee9-11e5-9ada-fdbe3a10f1f9.png)

This seems to be the case with the Fish Tornado application.

**Comment by baldurk** [comment]
Thanks, this just needs some logic to look up the number of subpasses and call CmdNextSubpass the appropriate number of times. Similar to [this code](https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/vulkan/vk_state.cpp#L109-L110) to advance to the desired subpass. There's probably also at least one other part of the code that needs to handle this.

This might be related to the crash reported in #191.

**Comment by baldurk** [comment]
This should now call CmdNextSubpass N times to be valid with the spec. I can't check that it's doing it correctly very easily since I didn't get any errors before, but at least setting breakpoints it seemed to do the right thing :).

**Comment by kbiElude** [comment]
The issue no longer reproduces *as often*, however it's still there.

To reproduce:

1. Use the same app as above.
2. Capture one frame, close the app.
3. Click on "Colour Pass #1 (1 Targets)" in the Event Browser.

It does seem to occur for each pass I click **for the first time**, but if I then click on one of the "Colour Pass" tree items I've already clicked earlier, I'm not seeing it reproduce anymore.

Here's the obligatory call stack:

![image](https://cloud.githubusercontent.com/assets/9154207/13426008/1bbaa008-dfab-11e5-9644-30494cb76f49.png)

..and where the offending call's coming from..:

![image](https://cloud.githubusercontent.com/assets/9154207/13426015/290e36f2-dfab-11e5-8f66-6cb677a15e34.png)

**Comment by baldurk** [comment]
Oh of course, yes. I will need to add an equivalent to BeginRenderPassAndApplyState to end the render pass also.

**Comment by baldurk** [comment]
Closing this issue as the bug should be fixed in [v0.30](https://github.com/baldurk/renderdoc/releases/tag/v0.30). Feel free to re-open if it's not as you expect!
