### ISSUE TITLE
Show empty Vulkan render passes with color storeOp=Don't Care in the usage list for the color attachment

### ISSUE THREAD

**Issue by mihnea-epic** [baldurk/renderdoc#1951]
## Description

I've got an empty render pass with a multisample color attachment set to Load/Don't Care and a resolve attachment set to Don't Care/Store. The "usage in frame" list for the color target doesn't show this event at all. The usage list for the resolve attachment correctly shows the event as "Resolve".

This pass is an app bug, and it's what I was trying to track down with Renderdoc (the color attachment was used as a PS input later in the frame, but the don't care store op destroyed it). I was looking at the events which used the image, trying to figure out which one messes it up, but the list was missing precisely the problem event, which made debugging a bit hard. :)

Maybe an end render pass command with storeOp=Don't Care can be listed as a discard event? I've seen unwanted discards such as this one quite a few times, and I think showing them explicitly can help track down problems much quicker (if you see a Discard followed by a PS - Texture event, you instantly know where the problem is).

To make things clearer, this is the render pass:
![image](https://user-images.githubusercontent.com/54374501/84756639-bbab2980-afcb-11ea-9720-34f0d8022c6d.png)

This is the usage list for the color target, no mention of EIDs 589-590:
![image](https://user-images.githubusercontent.com/54374501/84756734-dbdae880-afcb-11ea-8e8c-800983ef5429.png)

This is the usage list for the resolve attachment used in that pass, showing 590 as resolve:
![image](https://user-images.githubusercontent.com/54374501/84756824-fad97a80-afcb-11ea-9c99-a9e7e938e96f.png)

Also, maybe RD can also show "resolve source" events for the color attachments in a pass, if there are corresponding resolve attachments? It's not as important to me personally, but it's nice to have information (and it would have helped in this case, though not in other cases of unwanted discards).

Thanks,
Mihnea

## Environment

* RenderDoc version: 1.8
* Operating System: Win10 1909
* Graphics API: Vulkan

**Comment by baldurk** [comment]
That commit adds Discard usage when `DONT_CARE` load or store ops are specified, as well as resolve source.
