### ISSUE TITLE
Missing vertices in .obj file created from Renderdoc .csv data

### ISSUE THREAD

**Issue by k3mono** [baldurk/renderdoc#1954]
## Description

When exporting the .csv data to an .obj file (using csv2obj) vertices are missing in the mesh. 
 
I would like to export the mesh I am viewing into Blender. When I attempt to do this, by exporting VS output data into a .csv file and converting this into .obj (using this tool: https://github.com/sergeyreznik/csv2obj) the mesh appears to have holes in it. 

## Steps to reproduce
I have uploaded the .rdc, .csv, .obj and .blend files to this MEGA.nz folder: https://mega.nz/folder/mjARQIDT#kpFyGOwWOMeui84_05Wx-Q

I open b1.rdc. I select EID 1188 / Draw # 46. 

![Screenshot (1772)](https://user-images.githubusercontent.com/67212600/85236372-5913bc80-b415-11ea-99af-63c840d4d847.png)

I right click under the 'VS Output' file to export gl_Positions as a .csv file. 
I use csv2obj to convert .csv data to an .obj file to view in Blender.

After the .obj is created from b1buildingtest.csv, I open it in Blender.
As shown here, several vertices are missing in b1buildingtest.obj.

![Screenshot (1770)](https://user-images.githubusercontent.com/67212600/85236465-1999a000-b416-11ea-93f1-0a3875501e8f.png)
![Screenshot (1771)](https://user-images.githubusercontent.com/67212600/85236467-1dc5bd80-b416-11ea-8725-5a9c62bbb7db.png)

I do not see any missing vertices when looking at the mesh in Renderdoc:
![Screenshot (1774)](https://user-images.githubusercontent.com/67212600/85236551-cbd16780-b416-11ea-8be5-d6d58741392e.png)

## Environment

* RenderDoc version: 1.8
* Operating System: Windows 10 Home v1909
* Graphics API: OpenGL

* GPU: NVIDIA RTX 2060
* CPU: AMD Ryzen 7, 3750H
* RAM: 16GB

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
