### ISSUE TITLE
OpenXR fails to create session when launched through RenderDoc

### ISSUE THREAD

**Issue by LaylBongers** [baldurk/renderdoc#1957]
## Description

When launching an application that uses OpenXR through RenderDoc, creating an OpenXR session fails with `ERROR_GRAPHICS_DEVICE_INVALID`.

My suspicion is that Oculus' driver does not interact well with the RenderDoc layer, if the device handle is affected. OpenXR has a requirement to query the device, and the way RenderDoc affects the device may have resulted in a false positive mismatch detected by the Oculus driver. This is all just guesswork on my part however.

## Steps to reproduce

- Launch included application through RenderDoc
- Application closes with `ERROR_GRAPHICS_DEVICE_INVALID`

## Environment

* RenderDoc version: 1.8 (build from 8b491e15)
* Operating System: Windows 10 x64
* Graphics API: Vulkan (1.1 requested)
* OpenXR driver: Oculus v1.49.0
* Graphics Driver: AMD Radeon 20.4.2

**Comment by baldurk** [comment]
Your reproduction steps mention an included application but there is nothing that I can see provided.

Also RenderDoc does not currently support OpenXR. I assume `ERROR_GRAPHICS_DEVICE_INVALID` is either an application error or an OpenXR error since it's not a Vulkan error. I can't provide support for APIs that RenderDoc does not interact with or support, you would need to explain what the problem is in terms of the APIs that are supported such as Vulkan in this case.

**Comment by LaylBongers** [comment]
Sorry I forgot to include the ZIP with the application
[openxr-application.zip](https://github.com/baldurk/renderdoc/files/4820186/openxr-application.zip)

`ERROR_GRAPHICS_DEVICE_INVALID` is an error returned by OpenXR when `xrCreateSession` is called. My assumption is that the Oculus driver does something internally that doesn't interact well with the RenderDoc Vulkan layer, specifically misidentifying the device, but I don't know what it is as I don't have access to the driver's code.

I'll investigate what API calls are being made using `vktrace` to see if I can provide some more information.

I understand OpenXR isn't directly supported by RenderDoc, but it would be very helpful if I could debug Vulkan applications that happen to use it with a bit of manual code to make it work. My plan was to use the RenderDoc API to manually specify frames.

**Comment by baldurk** [comment]
Running the application gives this error:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LoadLibraryW { source: Os { code: 126, kind: Other, message: "The specified module could not be found." } }', code\binary-windows\src\main.rs:39:20                     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Does it need some extra dependency? This is running on a system with a VR headset connected.

If the error is happening inside Oculus's driver then I can't help with that, you'd need to go to Oculus for assistance. If there's a way to get more verbose error messages than just that code that would be useful. Unless RenderDoc is doing something that's invalid according to the Vulkan spec it's not something I can address.

**Comment by LaylBongers** [comment]
Additional dependency is the openxr loader which needs to be in library path.
This is happening within the Oculus driver, I'll see if I can contact oculus then.
