### ISSUE TITLE
It's maybe gcc version required?

### ISSUE THREAD

**Issue by mimijava** [baldurk/renderdoc#1966]
## Description
Build error in ubuntu. It's maybe gcc version required?

renderdoc/driver/shaders/spirv/spirv_debug_glsl450.cpp:52:16: error: ‘isinf’ was not declared in this scope
     if(!isinf(x) && !isnan(x))
                ^
renderdoc/driver/shaders/spirv/spirv_debug_glsl450.cpp:52:16: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/ming/renderdoc/api/replay/rdcstr.h:29,
                 from /home/ming/renderdoc/api/replay/stringise.h:28,
                 from /home/ming/renderdoc/driver/shaders/spirv/spirv_common.h:30,
                 from /home/ming/renderdoc/driver/shaders/spirv/spirv_debug.h:29,
                 from /home/ming/renderdoc/driver/shaders/spirv/spirv_debug_glsl450.cpp:25:
/usr/include/c++/5/cmath:621:5: note:   ‘std::isinf’
     isinf(_Tp __x)

## Steps to reproduce
build in ubuntu
## Environment

* RenderDoc version: v1.x
* Operating System: ubuntu
* Graphics API: N/a

**Comment by baldurk** [comment]
This bug report is also missing the critical information of which compiler and version you are using. You also haven't specified which version of ubuntu you're using which may be relevant. The nightly builds and automatic CI builds all happen on ubuntu and work fine.

**Comment by mimijava** [comment]
Build system is gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
I use below code replace it, it's well done.

#if defined(__clang__)
        var.value.uv[c] = isinf(var.value.fv[c]) ? 1 : 0;
#else
        var.value.uv[c] = std::isinf(var.value.fv[c]) ? 1 : 0;
#endif

**Comment by baldurk** [comment]
This looks like a glibc/libstdc++ bug that has been fixed in newer versions. Update those and it should work.
