### ISSUE TITLE
Saving a frame log of a Vulkan app does not put the file under File/Recent Logs

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#197]
The file only lands there if I open an existing log file.

(if this is how "recent logs" are supposed to work, please feel free to nuke this ticket :) )

**Comment by baldurk** [comment]
I think this is just an oversight, I agree that should happen.

**Comment by baldurk** [comment]
Should work as expected now.

**Comment by kbiElude** [comment]
Works like a charm.
