### ISSUE TITLE
Deadlock when starting remote server from qrenderdoc

### ISSUE THREAD

**Issue by dor666** [baldurk/renderdoc#1970]
There is a deadlock when asking qrenderdoc to start remote server on PC target.

```
ReplayStatus RemoteHost::Launch()
{
[...]
  {
    QMutexLocker autolock(&m_data->mutex);
    run = RunCommand();
  }
[...]
}

rdcstr RemoteHost::RunCommand() const
{
  QMutexLocker autolock(&m_data->mutex);
  return m_data->m_runCommand;
}

```

One line fix for me was to remove lock from Launch() function.

## Steps to reproduce

1. Start QRenderdoc
2. File -> Attach to running instance
3. Fill hostname
4. Fill Run Command ( it hangs before executing it )
5. Click update
6. Select host
7. Click "Run Server"
8. Observe hang

## Environment
* RenderDoc version: 1.8
* Operating System: Windows 10
* Graphics API: Any

**Comment by baldurk** [comment]
Thank you for the clear report with easy to follow repro steps. That commit should avoid the recursive mutex lock, in the way your suggested fix was.
