### ISSUE TITLE
Unknown error with no diagnostic infomation

### ISSUE THREAD

**Issue by lianera** [baldurk/renderdoc#1979]
## Description
When launching and inject to the process, a error dialog shows:
>Error kicking capture
>Error launching D:\software\mumu\emulator\nemu\EmulatorShell\NemuPlayer.exe for capture.
>Unknown error. Check the diagnostic log in the help menu for more details

While the Diagnostic Log window shows nothing related to the error:

> Core     PID   2696: [10:01:19]              core.cpp(421) - Log     - RenderDoc v1.8 Windows 64-bit Release (8b491e15300544332f641b8ec025819d6c0855ee) loaded in replay application
Core     PID   7428: [10:01:19]              core.cpp(421) - Log     - RenderDoc v1.8 Windows 64-bit Release (8b491e15300544332f641b8ec025819d6c0855ee) loaded in replay application
Core     PID   7428: [10:01:19]          settings.cpp(459) - Log     - Loading config from C:\Users\duanlian01\AppData\Roaming\renderdoc\renderdoc.conf
Core     PID   7428: [10:01:19]          settings.cpp(310) - Log     - Android.SDKDirPath has been customised from  to D:/software/Android/AndroidSDK
Core     PID   7428: [10:01:19]          settings.cpp(310) - Log     - Android.JDKDirPath has been customised from  to C:/Program Files/Java/jdk-14.0.1
Core     PID   2696: [10:01:19]       crash_handler.h(150) - Log     - Timer Waiting for crash handling server - 56.871 ms
Core     PID   2696: [10:01:19]       crash_handler.h(156) - Log     - Created crash-handling server \\.\pipe\RenderDocBreakpadServer22582924744
Core     PID   2696: [10:01:19]        crash_handler.h(87) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer22582924744
Core     PID   2696: [10:01:19]          settings.cpp(459) - Log     - Loading config from C:\Users\duanlian01\AppData\Roaming\renderdoc\renderdoc.conf
Core     PID   2696: [10:01:19]          settings.cpp(310) - Log     - Android.SDKDirPath has been customised from  to D:/software/Android/AndroidSDK
Core     PID   2696: [10:01:19]          settings.cpp(310) - Log     - Android.JDKDirPath has been customised from  to C:/Program Files/Java/jdk-14.0.1
UI       PID   2696: [10:01:19]         qrenderdoc.cpp(88) - Log     - QRenderDoc initialising.
UI       PID   2696: [10:01:19]         qrenderdoc.cpp(91) - Log     - Running as administrator
Core     PID   2696: [10:01:19]        crash_handler.h(51) - Log     - Re-using crash-handling server \\.\pipe\RenderDocBreakpadServer22582924744
Core     PID   2696: [10:01:19]        crash_handler.h(87) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer22582924744
Core     PID   2696: [10:01:19]      d3d11_replay.cpp(122) - Log     - Running replay on nVidia / NVIDIA GeForce GTX 1050 26.21.14.3086
Core     PID   2696: [10:01:20]      d3d12_replay.cpp(101) - Log     - Running replay on nVidia / NVIDIA GeForce GTX 1050 26.21.14.3086
Core     PID   2696: [10:01:20]     android_tools.cpp(354) - Log     - Initialising adb using 'D:/software/Android/AndroidSDK/platform-tools/adb'
Core     PID   2696: [10:01:20]        vk_replay.cpp(4104) - Log     - Created device.
UI       PID   2696: [10:01:22]                 unknown(0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///D:/software/mumu/emulator/nemu/EmulatorShell/NemuPlayer.exe")) 1
UI       PID   2696: [10:01:24]                 unknown(0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///D:/software/mumu/emulator/nemu/EmulatorShell/NemuPlayer.exe")) 1
Core     PID   2696: [10:01:29]     win32_process.cpp(514) - Log     - Running process D:\software\mumu\emulator\nemu\EmulatorShell\NemuPlayer.exe
Core     PID   2696: [10:01:29]     win32_process.cpp(597) - Log     - Injecting renderdoc into process 9924
Core     PID   7280: [10:01:29]              core.cpp(421) - Log     - RenderDoc v1.8 Windows 32-bit Release (8b491e15300544332f641b8ec025819d6c0855ee) loaded in replay application
Core     PID   7280: [10:01:29]          settings.cpp(459) - Log     - Loading config from C:\Users\duanlian01\AppData\Roaming\renderdoc\renderdoc.conf
Core     PID   7280: [10:01:29]          settings.cpp(310) - Log     - Android.SDKDirPath has been customised from  to D:/software/Android/AndroidSDK
Core     PID   7280: [10:01:29]          settings.cpp(310) - Log     - Android.JDKDirPath has been customised from  to C:/Program Files/Java/jdk-14.0.1
Core     PID   7280: [10:01:29]     win32_process.cpp(597) - Log     - Injecting renderdoc into process 9924

The renderdoc process runs with administrator privilege as the target process needed.

## Steps to reproduce

* Download mumu player: https://mumu.163.com/global/download/en/index.html and install
* Launch renderdoc with administrator privilege
* Launch mumu player with renderdoc 

## Environment

* RenderDoc version: 8b491e15
* Operating System: Windows 10 (1809)
* Graphics API: before graphics initialize. both OpenGL and DirectX show the error

NVIDIA GeForce GTX 1050 with driver version 26.21.14.3086

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
