### ISSUE TITLE
Feature request: Preview of human-readable form of SPIR-V code for active pipeline stages

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#198]
Another thing that would be a nice-to-have is being able to check what SPIR-V code is assigned to each of the pipeline stages, defined for the selected draw call. I don't think that's possible at the moment.

**Comment by baldurk** [comment]
I might be misunderstanding, but this sounds like just the shader view. On the pipeline state view, click the shader (or the 'go arrow' next to it) to open the shader viewer with my own flavour of SPIR-V disassembly. NOTE: The edit button doesn't work as shader editing isn't supported currently for Vulkan.

![image](https://cloud.githubusercontent.com/assets/661798/13395428/eb7b7514-deee-11e5-94b3-62bbb68055d0.png)

![image](https://cloud.githubusercontent.com/assets/661798/13395432/f42aef32-deee-11e5-8ae2-23cfbcbe2bfd.png)

**Comment by kbiElude** [comment]
That's exactly what I had in mind. Apologies!
