### ISSUE TITLE
Mac core profile 4.1 Segfault opening capture

### ISSUE THREAD

**Issue by ROTARTSI82** [baldurk/renderdoc#1981]
## Description

When I try to debug my application with RenderDoc, it would segfault when I try to open a capture. 

My application is running in a opengl **4.1** (not 3.2) core profile with forward compat.
In my code I have:

```
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
```

## Steps to reproduce

Try to open a capture. File > Open Capture (or Open Capture with Options) would crash. Double clicking the capture would segfault (so would opening, doesn't matter new instance or this instance, both cases segfault).

Quitting my application with an existing capture would crash (bc I'm pretty sure renderdoc tries to open the capture when i quit my app), but quitting would be fine if there's no capture.

## Environment

`GL_VERSION` string is `4.1 INTEL-14.5.22`, and i'm using GLEW 2.1.0 and GLFW.

* RenderDoc version: v1.x branch b0f4a11b and 724b6185 (probably others too)
* Operating System: Mac OSX 10.15.4 (Catalina)
* Graphics API: OpenGL 4.1 Core Profile (\w Forward Compat)

On Mac Book Air (mid 2012, 13'' model) with Intel HD Graphics 4000 1536 MB

I will also send an email to baldurk@baldurk.org with the settings.cap file and the capture.rdc file.

**Comment by baldurk** [comment]
Mac is not a supported platform. If you're able to find any fixes for problems then a pull request is very welcome, or else I can investigate if you're able to reproduce a problem on a supported platform such as windows, linux or even android.
