### ISSUE TITLE
Overlapping vertex attributes break the API and GUI. 

### ISSUE THREAD

**Issue by OptimisticPeach** [baldurk/renderdoc#1989]
## Description

Overlapping attributes break the internal api for RenderDoc and the api which RenderDoc uses to render its GUI when doing the steps listed below with the repository I linked.

After following the steps, I get a diagnostics log full of errors, and the gui starts to bug out if I switch to TextureViewer or move the window around on my screen:

![image](https://user-images.githubusercontent.com/24464956/88347072-d9308900-cd17-11ea-930d-801f1c5b15fe.png)
Notice how I've selected the "Texture Viewer" tab and views from the "Mesh Viewer" and "Diagnostics Log" tabs appear. 

## Steps to reproduce

Here's my repo dedicated to this bug: https://github.com/OptimisticPeach/renderdocbug

- Have Rust installed.
- Have an internet connection to download dependencies.
- Have a Vulkan-compatible driver. 
- Compile using `cargo build` or run directly with `cargo run`. (Give it a minute, this may take a while).

There's a RenderDoc capture there, along with a diagnostics log.

Relevant to RenderDoc:

- Capture application (which is in `<my repo>/target/debug/renderdocbug.exe`.
- Open captured frame.
- Select relevant pass.
- Open "Pipeline State" tab.
- "Vertex Input" should be selected as the pipeline stage.
- Click on "Mesh View".
- View data (Should be fine)

Relevant shader is in `<my repo>/src/terrain_shader.vert`, recompile using `make` (Requires having `glslangValidator` available). The attributes which are overlapped are `colour` and `example` near the top of the file, and are decorated with `layout(location = [2/3]) in` attributes.

Vertex attributes are listed in the array at line 297 of `src/main.rs`. In this case I interpret a `[u8; 4]` (an array of exactly four unsigned bytes) both as a normalized `vec4` in the shader (`colour`), and as a non-normalized value under `ivec4` (`example`). 

## Environment

* RenderDoc version: RenderDoc Version v1.9 (built from 22dbb188).
* Operating System: Windows 10 Home version 1909.
* Graphics API: Vulkan (Not sure what else to put here?).

Please do reply asking for more debugging information, I'd be very happy to give you more.

**Comment by baldurk** [comment]
The capture provided contains an invalid mismatch between the pipeline vertex attribute descriptions and the shader. In the pipeline vertex attribute 3 is given format `VK_FORMAT_R8G8B8A8_UINT` but the shader declares an input as a *signed* integer (look at the GLSL, `in ivec4 example`). The base format of these must match, either both signed or both unsigned.

The validation layers identify this problem:

> [UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch] Validation Error: [ UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch ] Object 0: handle = 0x4f0c9200000001e8, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0xb6cf33fe | Attribute type of `VK_FORMAT_R8G8B8A8_UINT` at location 3 does not match vertex shader input type of `ptr to input vec4 of sint32`
> [UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch] Validation Error: [ UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch ] Object 0: handle = 0x4f0c9200000001e8, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0xb6cf33fe | Attribute type of `VK_FORMAT_R8G8B8A8_UINT` at location 3 does not match vertex shader input type of `ptr to input vec4 of sint32`

You should always make sure to fix any validation layer problems identified, as RenderDoc itself does not generally handle invalid API use. This may also break on some drivers depending on how the undefined behaviour manifests.
