### ISSUE TITLE
Feature request: Present image layout information for image bindings

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#199]
One of the issues we often see in apps are images which have been transferred to incorrect image layout before a dispatch/draw call was fired.

Having a way of checking what layout any image, to which an active image descriptor points to, has been set to before a vkCmdDispatch() / vkCmdDraw*() call was executed, would be of tremendous help when debugging broken applications.

**Comment by baldurk** [comment]
Plumbing the data through to the UI is the easy part, displaying it is the tricky part.

I think the best place to put this is on the pipeline state view, on each descriptor element (and on the framebuffer section for the bindings). Does that seem reasonable? There's also the worst case to consider of an image with 10 mips with alternating layouts for each mip - displaying all that data is ugly.

**Comment by kbiElude** [comment]
Totally works for me.

Admittedly, it could get pretty complex if each subresource was transitioned to a different layout, but that's the worst-case scenario. Frankly, I'd prefer to have access to all that data, rather than not have it at all :-)

**Comment by baldurk** [comment]
I've added the image layout information to the informational tooltips that pop up over image views in the pipeline state.

At the moment it just displays the first layout for a subresource (assuming the whole image is in the same layout) - I'm not sure this is the right place to put it, so I'd appreciate feedback :).

**Comment by baldurk** [comment]
Closing this issue as the feature is (at least partially) implemented in [v0.30](https://github.com/baldurk/renderdoc/releases/tag/v0.30). I'll consider multi-subresource layouts as a separate feature on my todo list.
