### ISSUE TITLE
latest 1.9 release fails to build: "stringise.h:36: undefined reference to `rdcstr DoStringise<long>(long const&)'"

### ISSUE THREAD

**Issue by david-geiger** [baldurk/renderdoc#1991]
# Description

I tried on Mageia Linux (Cauldron) to build latest 1.9 release but it fails to build due to an underlinking issue:

> stringise.h:36: undefined reference to `rdcstr DoStringise<long>(long const&)'

## Steps to reproduce

Simply compile latest 1.9 release with "-Wl,--no-undefined" as ldflags. Because our build system enables underlinking as default build flags. Attached also the full build log.

> /BC7_Encode_Kernel.cpp.o CMakeFiles/rdoc.dir/data/glsl_shaders.cpp.o CMakeFiles/rdoc_version.dir/replay/version.cpp.o   -L/home/iurt/rpmbuild/BUILD/renderdoc-1.9/build/renderdoc  -lm -ldl -lrt -lX11 -lxcb -lxcb-keysyms -lpthread -lrenderdoc_libentry 
/usr/bin/ld: CMakeFiles/rdoc.dir/os/posix/linux/linux_process.cpp.o: in function `StringConverter<long, false>::Do(long const&)':
/home/iurt/rpmbuild/BUILD/renderdoc-1.9/renderdoc/api/replay/stringise.h:36: undefined reference to `rdcstr DoStringise<long>(long const&)'
/usr/bin/ld: /home/iurt/rpmbuild/BUILD/renderdoc-1.9/renderdoc/api/replay/stringise.h:36: undefined reference to `rdcstr DoStringise<long>(long const&)'
/usr/bin/ld: /home/iurt/rpmbuild/BUILD/renderdoc-1.9/renderdoc/api/replay/stringise.h:36: undefined reference to `rdcstr DoStringise<long>(long const&)'
/usr/bin/ld: /home/iurt/rpmbuild/BUILD/renderdoc-1.9/renderdoc/api/replay/stringise.h:36: undefined reference to `rdcstr DoStringise<long>(long const&)'
/usr/bin/ld: /home/iurt/rpmbuild/BUILD/renderdoc-1.9/renderdoc/api/replay/stringise.h:36: undefined reference to `rdcstr DoStringise<long>(long const&)'
/usr/bin/ld: CMakeFiles/rdoc.dir/os/posix/linux/linux_process.cpp.o:/home/iurt/rpmbuild/BUILD/renderdoc-1.9/renderdoc/api/replay/stringise.h:36: more undefined references to `rdcstr DoStringise<long>(long const&)' follow
collect2: error: ld returned 1 exit status
gmake[2]: *** [renderdoc/CMakeFiles/renderdoc.dir/build.make:1320: lib/librenderdoc.so] Error 1

Full build log:
[build.0.20200725044602.log](https://github.com/baldurk/renderdoc/files/4975378/build.0.20200725044602.log)

## Environment

* RenderDoc version: 1.9
* Operating System: Linux (Mageia Cauldron)
* Graphics API:
* Cmake: 3.18.0
* GCC: 10.2.0
* Qt: 5.15.0

**Comment by baldurk** [comment]
This isn't an underlinking issue as RenderDoc builds with `-Wl,--no-undefined` anyway. You're building for i586 on linux and that's not supported, only x86-64 is supported on linux.

**Comment by david-geiger** [comment]
Oh ok that is why, thanks.

So also aarch64 is also no more supported?

**Comment by baldurk** [comment]
Neither of them have ever been supported, x86-64 is the only architecture that I officially support on linux.

**Comment by gicmo** [comment]
We currently provide i686 builds in Fedora and was not aware that only x86-64 is supported. I am running into the same issue. From a glance it does not seem to be to hard to fix by providing a implementation for the missing specialization, but I can also drop the i686 builds if giving up on those is preferred.

**Comment by baldurk** [comment]
As long as the fix is appropriate and it doesn't break the supported platforms I don't mind if someone wants to investigate and provide a PR, but it wouldn't be as simple as providing the missing specialization since I deliberately only instantiate stringise support for the explicitly sized types (int32_t, uint64_t, etc) to avoid problems where other integer types are aliases on some compilers and not on others. Whatever is generating the need for this specialization would need to be fixed to use an explicitly sized type.

Regardless of whether someone fixes it or not, x86-64 will remain the only supported architecture on linux and I have no plans to change that. For that reason I won't investigate build breakages or bugs that only occur on 32-bit or ARM on linux.

**Comment by gicmo** [comment]
> As long as the fix is appropriate and it doesn't break the supported platforms I don't mind if someone wants to investigate and provide a PR, but it wouldn't be as simple as providing the missing specialization since I deliberately only instantiate stringise support for the explicitly sized types (int32_t, uint64_t, etc) to avoid problems where other integer types are aliases on some compilers and not on others. Whatever is generating the need for this specialization would need to be fixed to use an explicitly sized type.

ACK.

> Regardless of whether someone fixes it or not, x86-64 will remain the only supported architecture on linux and I have no plans to change that. For that reason I won't investigate build breakages or bugs that only occur on 32-bit or ARM on linux.

Fair. I think I will drop 32bit support then, just to avoid work now and future work. Thanks for the quick reply!
