### ISSUE TITLE
[GL3.3] Renderdoc doesn't seem to utilize texture unit 0 properly.

### ISSUE THREAD

**Issue by Lokathor** [baldurk/renderdoc#1994]
## Description

I've been doing the LearnOpenGL demos again just for fun, and when I went to check one of them in RenderDoc it showed different output than when the program shows when run on its own without RenderDoc. Specifically, RenderDoc doesn't seem to utilize texture unit 0, so basically one of the textures doesn't show up.

What should happen is the two demo textures are blended together and shown in the frame. What does happen is that the "arrows" in texture unit 0 don't shows up, only the "brick" in texture unit 1.

If I change the program so that it uses units 1 and 2 instead of units 0 and 1, then things display fine within RenderDoc. So really this is actually not a huge deal, since I have the work around. However, [the GL docs](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glActiveTexture.xhtml) say that texture unit 0 is supposed to be valid for use so I'm just very confused as to if this is a RenderDoc bug, or if I'm actually using GL wrong somehow.

## Steps to reproduce

* [GitHub repository link](https://github.com/Lokathor/manganese)
* [The Specific Example](https://github.com/Lokathor/manganese/blob/main/src/bin/06_coordinates.rs) that is exhibiting the problem.
* [capture fie on google drive](https://drive.google.com/file/d/1rSQhNLs3kn1O-vaiAL5cdQ8e-vidnLdb/view?usp=sharing)

It's all in Rust, but if you have that available then `cargo run` should just run it on Windows (it uses Nightly rust). It uses SDL2 for windowing, which it can build on its own with no special files on Windows, but on Mac/Linux you'll need the SDL2 static link files available from the package manager I guess.

## Environment

* RenderDoc version: 1.9 (built from 22dbb188)
* Operating System: Windows 10
* Graphics API: OpenGL Core 3.3
* Graphics Card: nVidia GeForce GTX 1060 3GB, driver version 391.25

**Comment by StygianLightning** [comment]
I tested this on Ubuntu 18.04 on a GeForce GTX 1080, with the proprietary NVIDIA drivers (nvidia-driver-440).
Everything worked correctly with Renderdoc v1.5, built from [a94f238e37](https://github.com/baldurk/renderdoc/commit/a94f238e37cfe2f142093eb8e5da7775abaa88c6).
After upgrading to the latest downloadable version, v1.9 built from [22dbb188c](https://github.com/baldurk/renderdoc/commit/22dbb188ceac48479764540ee0df3e4f28b6f0b3), I get the same behaviour Lokathor describes.

**Comment by baldurk** [comment]
I've already found the issue and fixed it, which will be pushed soon. It was a regression between v1.8 and v1.9.

**Comment by baldurk** [comment]
That commit should fix the issue, it was caused by wrong push/pop of texture units when the context is first presented while I create internal text rendering textures.
