### ISSUE TITLE
RenderDoc appears not to update FB outputs used by draw calls for subsequent subpass iterations

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#200]
I'm not sure if I'm not understanding the information RenderDoc presents correctly, or it's an app issue, so I thought I'd share this.

I'm looking at Fish Tornado I mentioned in my previous ticket right now. The app creates a renderpass with two color attachments. The renderpass is built of two subpasses, where subpass 0 renders to color attachment 0 and subpass 1 renders to color attachment 1. Now, here's how Event Browser presents how the renderpass is used to update the attachments:

![image](https://cloud.githubusercontent.com/assets/9154207/13427538/fde6e42e-dfb4-11e5-83f6-4aebf5314144.png)

So far so good. For the only draw call issued in the zeroth subpass, we have..:

![image](https://cloud.githubusercontent.com/assets/9154207/13427565/30994fc4-dfb5-11e5-86db-bb565fc2e21a.png)

Now, if I move to the draw call fired in the next subpass, not much changes:

![image](https://cloud.githubusercontent.com/assets/9154207/13427594/5c4e453e-dfb5-11e5-88e0-b9195df00db8.png)

Shouldn't < FragColor > move to attachment 1, according to the description above?

One thing that could be confusing RenderDoc here is the fact that the FS, used in subpass 1, renders to color attachment 0, but - as per subpass description - this attachment is actually "bound" (using GL speak) to FB attachment 1.

**Comment by baldurk** [comment]
Probably just a case I didn't see before, I'll check into it.

**Comment by baldurk** [comment]
Also, happy 200th bug to me!

**Comment by baldurk** [comment]
Should display properly now using the indices into the framebuffer from the current subpass. These screenshots are taken with 'show disabled' enabled. Without it, the italicised entries would be omitted:

![image](https://cloud.githubusercontent.com/assets/661798/13437759/33884452-dfe6-11e5-8ae6-6bc68918e821.png)

![image](https://cloud.githubusercontent.com/assets/661798/13437774/42013d4a-dfe6-11e5-9388-c7178b60e55f.png)

**Comment by kbiElude** [comment]
Works as expected :) Thanks!
