### ISSUE TITLE
Problems installing renderdoc server

### ISSUE THREAD

**Issue by zgy001** [baldurk/renderdoc#2001]
## Description
i compile the project by myself.But both on windows and linux,when i select my mobile device,i got the info:Problems installing renderdoc server.Could not find APK folder . please check you installation is complete.
![image](https://user-images.githubusercontent.com/43093592/88927038-6b510800-d2a9-11ea-85cd-7a9c2f14b373.png)

## Steps to reproduce
i just followed the steps Compiling.md provides.

## Environment

on windows:win10,VS2019,x64,development
on linux:ubuntu20.0.4
my mobile device:mi5,android8,
* RenderDoc version: the source code on github now
* Operating System: XXX
* Graphics API: opengl
by the way,i can use the builded renderdoc.but why i failed when i build for myself?

**Comment by baldurk** [comment]
Do not spam the repository with issues, it is rude and it causes mess and confusion.

**Comment by zgy001** [comment]
i'm new here,sorry
