### ISSUE TITLE
capture the game of  “com.netease.sky.huawei/#DefaultActivity” --- Application crash

### ISSUE THREAD

**Issue by luopan007** [baldurk/renderdoc#2003]
**Description**

capture the game of  “com.netease.sky.huawei/#DefaultActivity” --- Application crash

**Log：**

07-31 11:25:39.991 I/renderdoc( 7557): @5f238f3300000982@ __rdoc_internal_android_logcat 326801359
07-31 11:25:40.030 W/DevicePolicyManager( 1079): Package com.netease.sky.huawei (uid=10222, pid=14273) cannot access Device IDs
07-31 11:25:40.030 W/TelephonyPermissions( 1938): reportAccessDeniedToReadIdentifiers:com.netease.sky.huawei:getDeviceId:isPreinstalled=false:isPrivApp=false
07-31 11:25:40.027 W/ease.sky.huawei(14273): type=1400 audit(0.0:494262): avc: granted { getattr } for pid=14273 name="/" dev="sdcardfs" ino=109 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=filesystem app=com.netease.sky.huawei
07-31 11:25:40.037 I/renderdoc(14273): @5f238f3400000015@ RDOC 014273: [11:25:40]     android_hook.cpp( 813) - Log     - Not refreshing android hooks with no libraries registered
07-31 11:25:40.037 I/renderdoc(14273): @5f238f3400000016@ RDOC 014273: [11:25:40]        gl_driver.cpp(1132) - Log     - Core context 000000796A9FF380 created with attribs, sharing with context 0000000000000000
07-31 11:25:40.038 I/renderdoc(14273): @5f238f3400000017@ RDOC 014273: [11:25:40]             core.cpp(1757) - Log     - Adding OpenGLES device frame capturer for 0x000000796A9FF380
07-31 11:25:40.038 I/renderdoc(14273): @5f238f3400000018@ RDOC 014273: [11:25:40]        gl_common.cpp( 422) - Log     - Checking enabled extensions, running as OpenGL ES 1.0
07-31 11:25:40.038 I/renderdoc(14273): @5f238f3400000019@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3379) - Log     - Emulating glTransformFeedbackBufferBase
07-31 11:25:40.038 I/renderdoc(14273): @5f238f340000001a@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3380) - Log     - Emulating glTransformFeedbackBufferRange
07-31 11:25:40.038 I/renderdoc(14273): @5f238f340000001b@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3381) - Log     - Emulating glClearNamedFramebufferiv
07-31 11:25:40.038 I/renderdoc(14273): @5f238f340000001c@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3382) - Log     - Emulating glClearNamedFramebufferuiv
07-31 11:25:40.038 I/renderdoc(14273): @5f238f340000001d@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3383) - Log     - Emulating glClearNamedFramebufferfv
07-31 11:25:40.038 I/renderdoc(14273): @5f238f340000001e@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3384) - Log     - Emulating glClearNamedFramebufferfi
07-31 11:25:40.038 I/renderdoc(14273): @5f238f340000001f@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3385) - Log     - Emulating glBlitNamedFramebuffer
07-31 11:25:40.038 I/renderdoc(14273): @5f238f3400000020@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3386) - Log     - Emulating glVertexArrayElementBuffer
07-31 11:25:40.038 I/renderdoc(14273): @5f238f3400000021@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3387) - Log     - Emulating glVertexArrayVertexBuffers
07-31 11:25:40.038 I/renderdoc(14273): @5f238f3400000022@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3427) - Log     - Emulating ARB_copy_image
07-31 11:25:40.038 I/renderdoc(14273): @5f238f3400000023@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3434) - Log     - Emulating ARB_clear_buffer_object
07-31 11:25:40.038 I/renderdoc(14273): @5f238f3400000024@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3449) - Log     - Emulating ARB_internalformat_query2
07-31 11:25:40.038 I/renderdoc(14273): @5f238f3400000025@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3458) - Log     - Emulating ARB_separate_shader_objects
07-31 11:25:40.038 I/renderdoc(14273): @5f238f3400000026@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3529) - Log     - Emulating ARB_program_interface_query
07-31 11:25:40.038 I/renderdoc(14273): @5f238f3400000027@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3590) - Log     - Emulating GLES 3.x functions
07-31 11:25:40.038 I/renderdoc(14273): @5f238f3400000028@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3597) - Log     - Emulating GLES 3.1 functions
07-31 11:25:40.039 I/renderdoc(14273): @5f238f3400000029@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3605) - Log     - Emulating GLES 3.2 functions
07-31 11:25:40.039 I/renderdoc(14273): @5f238f340000002a@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3635) - Log     - Emulating EXT_direct_state_access
07-31 11:25:40.039 I/renderdoc(14273): @5f238f340000002b@ RDOC 014273: [11:25:40]      gl_emulated.cpp(3722) - Log     - Emulating ARB_direct_state_access
07-31 11:25:40.039 I/renderdoc(14273): @5f238f340000002c@ RDOC 014273: [11:25:40]        gl_driver.cpp(1374) - Log     - Activating new GL context: ARM / Mali-G76 / OpenGL ES-CM 1.1 HivoyagerV100R001C10B127
07-31 11:25:40.039 I/renderdoc(14273): @5f238f340000002d@ RDOC 014273: [11:25:40]        gl_common.cpp( 479) - Log     - Vendor checks for 0 (ARM / Mali-G76 / OpenGL ES-CM 1.1 HivoyagerV100R001C10B127)
07-31 11:25:40.039 I/renderdoc(14273): @5f238f340000002e@ RDOC 014273: [11:25:40]        gl_common.cpp( 813) - Warning - Reading from the depth buffer using glReadPixels is not supported (GL_NV_read_depth)
07-31 11:25:40.039 I/renderdoc(14273): @5f238f340000002f@ RDOC 014273: [11:25:40]        gl_common.cpp( 817) - Warning - Reading from the stencil buffer using glReadPixels is not supported (GL_NV_read_stencil)
07-31 11:25:40.039 I/renderdoc(14273): @5f238f3400000030@ RDOC 014273: [11:25:40]        gl_common.cpp( 821) - Warning - Reading from the packed depth-stencil buffers using glReadPixels is not supported (GL_NV_read_depth_stencil)
07-31 11:25:40.043 W//system/bin/netd(  592): A binder object at 0x7ab7093580 is being transacted on, however, this object is in the same process as its proxy. Transacting with this binder is expensive compared to just calling the corresponding functionality in the same process.
07-31 11:25:40.043 I/PreDnsController(  592): canPreDnsQuery,persist.sys.predns is false!
07-31 11:25:40.043 W/System.err(14273): java.io.FileNotFoundException: /data/anr/anr_2020-07-30-15-55-28-267: open failed: EACCES (Permission denied)
07-31 11:25:40.043 W/System.err(14273): 	at libcore.io.IoBridge.open(IoBridge.java:496)
07-31 11:25:40.043 W/System.err(14273): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
07-31 11:25:40.043 W/System.err(14273): 	at com.netease.androidcrashhandler.entity.anr.AnrCore.getANRContent(AnrCore.java:3)
07-31 11:25:40.043 W/System.err(14273): 	at com.netease.androidcrashhandler.entity.anr.AnrCore.start(AnrCore.java:7)
07-31 11:25:40.043 W/System.err(14273): 	at com.netease.androidcrashhandler.entity.anr.AnrProxy.start(AnrProxy.java:3)
07-31 11:25:40.043 W/System.err(14273): 	at com.netease.androidcrashhandler.NTCrashHunterKit.start_t(NTCrashHunterKit.java:19)
07-31 11:25:40.043 W/System.err(14273): 	at com.netease.androidcrashhandler.NTCrashHunterKit.startHuntingCrash(NTCrashHunterKit.java:10)
07-31 11:25:40.043 W/System.err(14273): 	at O00000o.O0000Oo0.O000000o.O00000Oo.c.O00000Oo(CrashHunterUtil.java:8)
07-31 11:25:40.035 I/ease.sky.huawei(14273): type=1400 audit(0.0:494264): avc: denied { getattr } for pid=14273 path="/data/anr" dev="sdd74" ino=93 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:anr_data_file:s0 tclass=dir permissive=1 app=com.netease.sky.huawei
07-31 11:25:40.043 W/System.err(14273): 	at O00000o.O0000Oo0.O000000o.O00000Oo.c.O000000o(CrashHunterUtil.java:8)
07-31 11:25:40.044 W/System.err(14273): 	at com.tgc.sky.netease.GameActivity_Netease.onCreate(GameActivity_Netease.java:9)
07-31 11:25:40.044 W/System.err(14273): 	at android.app.Activity.performCreate(Activity.java:7805)
07-31 11:25:40.044 W/System.err(14273): 	at android.app.Activity.performCreate(Activity.java:7794)
07-31 11:25:40.044 W/System.err(14273): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
07-31 11:25:40.035 I/ease.sky.huawei(14273): type=1400 audit(0.0:494265): avc: denied { read } for pid=14273 name="anr" dev="sdd74" ino=93 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:anr_data_file:s0 tclass=dir permissive=1 app=com.netease.sky.huawei
07-31 11:25:40.044 W/System.err(14273): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
07-31 11:25:40.044 W/System.err(14273): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
07-31 11:25:40.044 W/System.err(14273): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
07-31 11:25:40.044 W/System.err(14273): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-31 11:25:40.044 W/System.err(14273): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-31 11:25:40.044 W/System.err(14273): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
07-31 11:25:40.044 W/System.err(14273): 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-31 11:25:40.044 W/System.err(14273): 	at android.os.Looper.loop(Looper.java:214)
07-31 11:25:40.044 W/System.err(14273): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
07-31 11:25:40.044 W/System.err(14273): 	at java.lang.reflect.Method.invoke(Native Method)
07-31 11:25:40.035 I/ease.sky.huawei(14273): type=1400 audit(0.0:494266): avc: denied { open } for pid=14273 path="/data/anr" dev="sdd74" ino=93 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:anr_data_file:s0 tclass=dir permissive=1 app=com.netease.sky.huawei
07-31 11:25:40.044 W/System.err(14273): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
07-31 11:25:40.044 W/System.err(14273): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
07-31 11:25:40.044 W/System.err(14273): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
07-31 11:25:40.044 W/System.err(14273): 	at libcore.io.Linux.open(Native Method)
07-31 11:25:40.044 W/System.err(14273): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
07-31 11:25:40.044 W/System.err(14273): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
07-31 11:25:40.044 W/System.err(14273): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
07-31 11:25:40.044 W/System.err(14273): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
07-31 11:25:40.044 W/System.err(14273): 	at libcore.io.IoBridge.open(IoBridge.java:482)
07-31 11:25:40.044 W/System.err(14273): 	... 24 more
07-31 11:25:40.046 W/Settings(14273): Setting adb_enabled has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
07-31 11:25:40.051 E/ResolverController(  592): No valid NAT64 prefix (100, <unspecified>/0)
07-31 11:25:40.057 I/ease.sky.huawe(14273): jit_compiled:[OK] void java.util.zip.ZipOutputStream.write(byte[], int, int) @ /apex/com.android.runtime/javalib/core-oj.jar
07-31 11:25:40.074 I/ease.sky.huawe(14273): jit_compiled:[OK] void java.util.zip.ZipOutputStream.ensureOpen() @ /apex/com.android.runtime/javalib/core-oj.jar
07-31 11:25:40.081 E/libc    (14273): The property "ro.build.fingerprint" has a value with length 96 that is too large for __system_property_get()/__system_property_read(); use __system_property_read_callback() instead.
07-31 11:25:40.092 I/renderdoc( 7557): @5f238f3400000983@ __rdoc_internal_android_logcat 326801461
07-31 11:25:40.112 W/System.err(14273): java.io.FileNotFoundException: crashhunter_so_uuid_md5.txt
07-31 11:25:40.112 W/System.err(14273): 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
07-31 11:25:40.112 W/System.err(14273): 	at android.content.res.AssetManager.open(AssetManager.java:824)
07-31 11:25:40.112 W/System.err(14273): 	at android.content.res.AssetManager.open(AssetManager.java:801)
07-31 11:25:40.112 W/System.err(14273): 	at com.netease.androidcrashhandler.util.CUtil.getAssetFileContent(CUtil.java:3)
07-31 11:25:40.112 W/System.err(14273): 	at com.netease.androidcrashhandler.so.SoHandleCore$1.run(SoHandleCore.java:1)
07-31 11:25:40.112 W/System.err(14273): 	at java.lang.Thread.run(Thread.java:926)
07-31 11:25:40.113 I/trace   (14273): ###################################################################
07-31 11:25:40.113 I/trace   (14273): JNI [NCSetCfgInfo]
07-31 11:25:40.113 I/trace   (14273): key = is_open_libunwind
07-31 11:25:40.113 I/trace   (14273): info = false
07-31 11:25:40.113 I/trace   (14273): ###################################################################
07-31 11:25:40.113 I/trace   (14273): JNI [NCCrashHandler] dont open libunwind function
07-31 11:25:40.115 W//system/bin/netd(  592): A binder object at 0x7ab7093580 is being transacted on, however, this object is in the same process as its proxy. Transacting with this binder is expensive compared to just calling the corresponding functionality in the same process.
07-31 11:25:40.115 I/PreDnsController(  592): canPreDnsQuery,persist.sys.predns is false!
07-31 11:25:40.118 W//system/bin/netd(  592): A binder object at 0x7ab7093580 is being transacted on, however, this object is in the same process as its proxy. Transacting with this binder is expensive compared to just calling the corresponding functionality in the same process.
07-31 11:25:40.118 I/PreDnsController(  592): canPreDnsQuery,persist.sys.predns is false!
07-31 11:25:40.119 W//system/bin/netd(  592): A binder object at 0x7ab7093580 is being transacted on, however, this object is in the same process as its proxy. Transacting with this binder is expensive compared to just calling the corresponding functionality in the same process.
07-31 11:25:40.119 E/ResolverController(  592): No valid NAT64 prefix (100, <unspecified>/0)
07-31 11:25:40.119 I/PreDnsController(  592): canPreDnsQuery,persist.sys.predns is false!
07-31 11:25:40.120 E/ResolverController(  592): No valid NAT64 prefix (100, <unspecified>/0)
07-31 11:25:40.121 W/DevicePolicyManager( 1079): Package com.netease.sky.huawei (uid=10222, pid=14273) cannot access Device IDs
07-31 11:25:40.121 W/TelephonyPermissions( 1938): reportAccessDeniedToReadIdentifiers:com.netease.sky.huawei:getSubscriberId:isPreinstalled=false:isPrivApp=false
07-31 11:25:40.122 W/DevicePolicyManager( 1079): Package com.netease.sky.huawei (uid=10222, pid=14273) cannot access Device IDs
07-31 11:25:40.123 W/TelephonyPermissions( 1938): reportAccessDeniedToReadIdentifiers:com.netease.sky.huawei:getSubscriberId:isPreinstalled=false:isPrivApp=false
07-31 11:25:40.124 I/NGPush_PushLog(14273): init
07-31 11:25:40.128 I/HiAdKit.OpenDeviceIdentifierBindService( 8205):  onBind
07-31 11:25:40.130 I/HiAd    ( 8205):  
07-31 11:25:40.130 I/HiAd    ( 8205): ============================================================================
07-31 11:25:40.130 I/HiAd    ( 8205): ====== HiAd-3.4.30.307
07-31 11:25:40.130 I/HiAd    ( 8205): ====== Brand: kirin990 Model: kirin Release: 10 API: 29
07-31 11:25:40.130 I/HiAd    ( 8205): ============================================================================
07-31 11:25:40.130 E/FileLogNode( 8205): Failed to initialize the file logger.
07-31 11:25:40.130 E/NGPush_PushLog(14273): android.provider.Settings$SettingNotFoundException: NtUniSdkDebug_key
07-31 11:25:40.130 E/NGPush_PushLog(14273): s_clazzImpl:class com.netease.ntunisdk.base.UniSdkUtils, s_bDebug:false
07-31 11:25:40.130 I/HiAdKit.KitNetHandler( 8205):  request pps kit config
07-31 11:25:40.132 W/DevicePolicyManager( 1079): Package com.netease.sky.huawei (uid=10222, pid=14273) cannot access Device IDs
07-31 11:25:40.132 W/TelephonyPermissions( 1938): reportAccessDeniedToReadIdentifiers:com.netease.sky.huawei:getDeviceId:isPreinstalled=false:isPrivApp=false
07-31 11:25:40.133 I/HiAdKit.SystemUtil( 8205):  isDeviceProvisioned: true
07-31 11:25:40.134 W//system/bin/netd(  592): A binder object at 0x7ab7093580 is being transacted on, however, this object is in the same process as its proxy. Transacting with this binder is expensive compared to just calling the corresponding functionality in the same process.
07-31 11:25:40.134 I/PreDnsController(  592): canPreDnsQuery,persist.sys.predns is false!
07-31 11:25:40.134 I/HiAdKit.HttpCall( 8205):  oobe: false
07-31 11:25:40.135 I/HiAdKit.CountryCodeBean( 8205):  getCountryCode get country code from SIM_COUNTRY
07-31 11:25:40.135 W/HiAdKit.CountryCodeBean( 8205):  fail to get grs countryCode
07-31 11:25:40.136 I/HiAdKit.HttpUrl.Builder( 8205):  countryCode:UNKNOWN
07-31 11:25:40.138 D/AppLogManager( 8205): PrintWoker poll timeout , shutdown
07-31 11:25:40.138 W/NetworkSdk_AbstractLocalManager( 8205): [W/HMSCore/NetworkSdk_AbstractLocalManager 8205:6075 :35] PPS-Net-pool-thread-8|null|o.aiz|b|16|addresses not found by routeby in local config{com.huawei.cloud.pps.kit}
07-31 11:25:40.138 E/HiAdKit.GRSApiImpl( 8205):  Query GRS returns a null or an empty.
07-31 11:25:40.140 D/HMSAgent(14273): Activity(1234)->Application(406)->ActivityMgr(180)->onActivityStarted
07-31 11:25:40.140 D/HMSAgent(14273): onStarted:com.tgc.sky.netease.GameActivity_Netease@6d7db9a
07-31 11:25:40.141 V/threaded_app(14273): Start: 0x79e456b980
07-31 11:25:40.141 W/HiAdKit.KitNetHandler( 8205):  requestKitConfig IllegalArgumentException
07-31 11:25:40.142 I/HiAdKit.HiAdRequestDataLogger( 8205):  upper thread name: PPS-Net-pool-thread-8 request data: {"androidApiVer":"29","buildVer":"Error: /preas/xxx not found in /hw_product/hw_oem//parent_cust.cfg","maker":"UNKNOWN","model":"KIRIN","ppsKitVersion":"3.4.30.307","localeCountry":"******","serCountry":"******","simCountryIso":"******"} 
07-31 11:25:40.143 D/Zygote  (  593): Forked child process 14447
07-31 11:25:40.147 I/GRALLOC (  633): getCallingPid=633, shrFd=37,fmt=0x1,intFmt=0x1,btStrd=5120,size=12288000,pid=633 
07-31 11:25:40.147 I/GRALLOC (  633): 	 yuv=2,w=1176,h=2400,Stride u=0 v=0,offset u=0 v=0 
07-31 11:25:40.147 I/GRALLOC (  633): 	 iova_size=12288000,conUsg=0x0,proUsg=0x80000008000100,	 strd=1280,[afbc]HdrStrd=0 PyldStrd=0 Scrmbl=0, ionhnd = 0 
07-31 11:25:40.148 I/ActivityManager( 1079): Start proc 14447:com.netease.sky.huawei:PushService/u0a222 for service {com.netease.sky.huawei/com.netease.pushservice.PushService}
07-31 11:25:40.149 I/GRALLOC (  633): getCallingPid=633, shrFd=42,fmt=0x1,intFmt=0x1,btStrd=5120,size=12288000,pid=633 
07-31 11:25:40.149 I/GRALLOC (  633): 	 yuv=2,w=1176,h=2400,Stride u=0 v=0,offset u=0 v=0 
07-31 11:25:40.149 I/GRALLOC (  633): 	 iova_size=12288000,conUsg=0x0,proUsg=0x80000008000100,	 strd=1280,[afbc]HdrStrd=0 PyldStrd=0 Scrmbl=0, ionhnd = 0 
07-31 11:25:40.150 I/GRALLOC (  633): getCallingPid=633, shrFd=46,fmt=0x1,intFmt=0x1,btStrd=5120,size=12288000,pid=633 
07-31 11:25:40.150 I/GRALLOC (  633): 	 yuv=2,w=1176,h=2400,Stride u=0 v=0,offset u=0 v=0 
07-31 11:25:40.150 I/GRALLOC (  633): 	 iova_size=12288000,conUsg=0x0,proUsg=0x80000008000100,	 strd=1280,[afbc]HdrStrd=0 PyldStrd=0 Scrmbl=0, ionhnd = 0 
07-31 11:25:40.150 I/wei:PushServic(14447): Reinit property: dalvik.vm.checkjni= false
07-31 11:25:40.151 E/ResolverController(  592): No valid NAT64 prefix (100, <unspecified>/0)
07-31 11:25:40.151 I/GRALLOC (  633): getCallingPid=633, shrFd=57,fmt=0x1,intFmt=0x1,btStrd=5120,size=12288000,pid=633 
07-31 11:25:40.151 I/GRALLOC (  633): 	 yuv=2,w=1176,h=2400,Stride u=0 v=0,offset u=0 v=0 
07-31 11:25:40.151 I/GRALLOC (  633): 	 iova_size=12288000,conUsg=0x0,proUsg=0x80000008000100,	 strd=1280,[afbc]HdrStrd=0 PyldStrd=0 Scrmbl=0, ionhnd = 0 
07-31 11:25:40.153 I/GRALLOC (  633): getCallingPid=633, shrFd=59,fmt=0x1,intFmt=0x1,btStrd=5120,size=12288000,pid=633 
07-31 11:25:40.153 I/GRALLOC (  633): 	 yuv=2,w=1176,h=2400,Stride u=0 v=0,offset u=0 v=0 
07-31 11:25:40.153 I/GRALLOC (  633): 	 iova_size=12288000,conUsg=0x0,proUsg=0x80000008000100,	 strd=1280,[afbc]HdrStrd=0 PyldStrd=0 Scrmbl=0, ionhnd = 0 
07-31 11:25:40.154 V/threaded_app(14273): activityState=10
07-31 11:25:40.154 D/NativeActivity(14273): APP_CMD_START
07-31 11:25:40.155 I/PlayCore(14273): UID: [10222]  PID: [14273] SplitInstallService : getSessionStates
07-31 11:25:40.156 I/PlayCore(14273): UID: [10222]  PID: [14273] SplitInstallService : Initiate binding to the service.
07-31 11:25:40.156 I/PlayCore(14273): UID: [10222]  PID: [14273] SplitInstallListenerRegistry : registerListener
07-31 11:25:40.157 I/GRALLOC (  633): getCallingPid=633, shrFd=48,fmt=0x1,intFmt=0x1,btStrd=5120,size=12288000,pid=633 
07-31 11:25:40.157 I/GRALLOC (  633): 	 yuv=2,w=1176,h=2400,Stride u=0 v=0,offset u=0 v=0 
07-31 11:25:40.157 I/GRALLOC (  633): 	 iova_size=12288000,conUsg=0x0,proUsg=0x80000008000100,	 strd=1280,[afbc]HdrStrd=0 PyldStrd=0 Scrmbl=0, ionhnd = 0 
07-31 11:25:40.160 I/Finsky  ( 9933): [1] wgo.a(25): Connecting InstallListener to SplitInstallService broadcaster...
07-31 11:25:40.161 D/HMSAgent(14273): Activity(1265)->Application(436)->ActivityMgr(190)->onActivityResumed
07-31 11:25:40.161 D/HMSAgent(14273): onResumed:com.tgc.sky.netease.GameActivity_Netease@6d7db9a
07-31 11:25:40.161 D/HMSAgent(14273): ApiClientMgr(423)->ApiClientMgr(242)->ApiClientMgr(292)->resetApiClient
07-31 11:25:40.161 D/HMSAgent(14273): reset client
07-31 11:25:40.162 I/HMSSDK_HMSBIInitializer(14273): Builder->biInitFlag :false
07-31 11:25:40.163 I/HMSSDK_HMSBIInitializer(14273): Builder->biSetting :false
07-31 11:25:40.163 E/ResolverController(  592): No valid NAT64 prefix (100, <unspecified>/0)
07-31 11:25:40.164 W/NetworkKit_c(14273): 14273-14469|null|com.huawei.hms.framework.network.grs.c.c|a|78|local config file is not exist.filename is {grs_app_global_route_config.json}
07-31 11:25:40.165 W/NetworkKit_AbstractLocalManager(14273): 14273-14469|null|com.huawei.hms.framework.network.grs.local.a|d|10|getConfigMgr configContent is null.
07-31 11:25:40.166 I/FA      (14273): Tag Manager is not found and thus will not be used
07-31 11:25:40.171 W//system/bin/netd(  592): A binder object at 0x7ab7093580 is being transacted on, however, this object is in the same process as its proxy. Transacting with this binder is expensive compared to just calling the corresponding functionality in the same process.
07-31 11:25:40.171 I/PreDnsController(  592): canPreDnsQuery,persist.sys.predns is false!
07-31 11:25:40.172 E/ResolverController(  592): No valid NAT64 prefix (100, <unspecified>/0)
07-31 11:25:40.173 W/NetworkKit_AbstractLocalManager(14273): 14273-14469|null|com.huawei.hms.framework.network.grs.local.a|a|126|updateCountryGroupMap return null because {null == countryGroups}
07-31 11:25:40.173 I/NetworkKit_GrsClient(14273): 14273-14469|null|com.huawei.hms.framework.network.grs.GrsClient$1|a|21|load V2 assets failed and then load V1
07-31 11:25:40.173 W/NetworkKit_c(14273): 14273-14469|null|com.huawei.hms.framework.network.grs.c.c|a|78|local config file is not exist.filename is {grs_sdk_global_route_config.json}
07-31 11:25:40.173 W/NetworkKit_AbstractLocalManager(14273): 14273-14469|null|com.huawei.hms.framework.network.grs.local.a|d|10|getConfigMgr configContent is null.
07-31 11:25:40.179 W/NetworkKit_AbstractLocalManager(14273): 14273-14469|null|com.huawei.hms.framework.network.grs.local.a|a|126|updateCountryGroupMap return null because {null == countryGroups}
07-31 11:25:40.179 I/NetworkKit_c(14273): 14273-14469|null|com.huawei.hms.framework.network.grs.a.c|<init>|20|get pkgname from context is{com.netease.sky.huawei}
07-31 11:25:40.180 I/NetworkKit_c(14273): 14273-14469|null|com.huawei.hms.framework.network.grs.a.c|<init>|20|get pkgname from context is{com.netease.sky.huawei}
07-31 11:25:40.181 I/NetworkKit_GrsBaseInfo(14273): 14273-14469|null|com.huawei.hms.framework.network.grs.GrsBaseInfo|getGrsParasKey|51|serviceAppName is not empty and localAppName is not config.
07-31 11:25:40.181 I/NetworkKit_c(14273): 14273-14469|null|com.huawei.hms.framework.network.grs.a.c|<init>|20|get pkgname from context is{com.netease.sky.huawei}
07-31 11:25:40.181 I/NetworkKit_c(14273): 14273-14469|null|com.huawei.hms.framework.network.grs.a.c|<init>|20|get pkgname from context is{com.netease.sky.huawei}
07-31 11:25:40.181 I/NetworkKit_a(14273): 14273-14469|null|com.huawei.hms.framework.network.grs.a.a|a|81|{initCache} get pkgname from context is{com.netease.sky.huawei}
07-31 11:25:40.182 I/NetworkKit_GrsBaseInfo(14273): 14273-14273|null|com.huawei.hms.framework.network.grs.GrsBaseInfo|getGrsParasKey|51|serviceAppName is not empty and localAppName is not config.
07-31 11:25:40.182 I/NetworkKit_c(14273): 14273-14273|null|com.huawei.hms.framework.network.grs.a.c|<init>|20|get pkgname from context is{com.netease.sky.huawei}
07-31 11:25:40.182 I/NetworkKit_GrsBaseInfo(14273): 14273-14273|null|com.huawei.hms.framework.network.grs.GrsBaseInfo|getGrsParasKey|51|serviceAppName is not empty and localAppName is not config.
07-31 11:25:40.183 I/NetworkKit_c(14273): 14273-14273|null|com.huawei.hms.framework.network.grs.a.c|<init>|20|get pkgname from context is{com.netease.sky.huawei}
07-31 11:25:40.183 I/NetworkKit_a(14273): 14273-14273|null|com.huawei.hms.framework.network.grs.a|a|16|get url from sp is not empty.
07-31 11:25:40.185 I/HMSSDK_HMSBIInitializer(14273): BI URL acquired successfully
07-31 11:25:40.186 I/HMSSDK_HiAnalyticsUtil(14273): not ChinaROM
07-31 11:25:40.186 I/HMSSDK_HiAnalyticsUtil(14273): Get OOBE failed

**Comment by luopan007** [comment]
07-31 11:25:49.062 I/renderdoc(14273): @5f238f3d00000063@ RDOC 014273: [11:25:49]       vk_resources.h(1300) - Error   - Invalid aspect mask (1) in image with aspects (6)
07-31 11:25:49.062 I/renderdoc(14273): @5f238f3d00000064@ RDOC 014273: [11:25:49]       vk_resources.h(1300) - Error   - Invalid aspect mask (1) in image with aspects (6)
07-31 11:25:49.062 I/renderdoc(14273): @5f238f3d00000065@ RDOC 014273: [11:25:49]  vk_image_states.cpp( 919) - Error   - Assertion failed: 'it->range().ContainedIn(range)'

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
