### ISSUE TITLE
Wrap the top banner to next line for smaller windows

### ISSUE THREAD

**Issue by nihalkenkre** [baldurk/renderdoc#2004]
## Description

![RenderDoc](https://user-images.githubusercontent.com/463752/89006505-8b71dd00-d324-11ea-98a5-9005b53e30c0.png)

Could the top banner wrap around to the next line for smaller window sizes.

## Environment

* RenderDoc version: 1.x branch
* Operating System: Windows 10
* Graphics API: Vulkan

Best regards.
Nihal Kenkre.

**Comment by baldurk** [comment]
I don't see any need for this. The overlay doesn't show anything particularly useful except whether the window is active, which is the first thing in the text the window would have to be ridiculously small for that not to show up. Wrapping the overlay would just interfere with actually seeing what's going on in smaller windows and the idea is to not be too intrusive.
