### ISSUE TITLE
overlay doesn't show in renderdoc v1.9 when launching uplay games like Tom Clancy's Ghost Recon Breakpoint

### ISSUE THREAD

**Issue by pandurangkatkar** [baldurk/renderdoc#2005]
## Description

overlay doesn't show in renderdoc v1.9 when launching uplay games like Tom Clancy's Ghost Recon Breakpoint

## Steps to reproduce
launch render doc -> launch application > browse uplay path or game path 

observe " Blocked loading of file "C:\Program Files\RenderDoc\renderdoc.dll" 

## Environment

* RenderDoc version: Version v1.9 
* Operating System: Windows 10 version 2004
* Graphics API: Vulkan

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
