### ISSUE TITLE
capture the game of "com.netease.sky.huawei/#DefaultActivity", the app crash

### ISSUE THREAD

**Issue by luopan007** [baldurk/renderdoc#2007]
## Description

capture the game of "com.netease.sky.huawei/#DefaultActivity", the app crash;

**The Error Log as follow:**

07-31 11:25:49.062 I/renderdoc(14273): @5f238f3d00000063@ RDOC 014273: [11:25:49] vk_resources.h(1300) - Error - Invalid aspect mask (1) in image with aspects (6)
07-31 11:25:49.062 I/renderdoc(14273): @5f238f3d00000064@ RDOC 014273: [11:25:49] vk_resources.h(1300) - Error - Invalid aspect mask (1) in image with aspects (6)
07-31 11:25:49.062 I/renderdoc(14273): @5f238f3d00000065@ RDOC 014273: [11:25:49] vk_image_states.cpp( 919) - Error - Assertion failed: 'it->range().ContainedIn(range)'

## Steps to reproduce

First: Download the renderdoc 1.9 exe file or source and build to install
Second: Using the Huawei mate 20 Pro phone and install the "Sky光·遇"
Third: Using the renderdoc connect to the phone 
Fourth: using the renderdoc Launch the “com.netease.sky.huawei/#DefaultActivity”

## Environment

* RenderDoc version:1.9
* Operating System: Host is Window 10; Device is Android 10
* Graphics API: Vulkan 1.2.145

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by luopan007** [comment]
bool tmp= (info.Aspects() == (VK_IMAGE_ASPECT_DEPTH_BIT + VK_IMAGE_ASPECT_STENCIL_BIT));
 // VK_IMAGE_ASPECT_COLOR_BIT is an alias for "all planes" in multi-planar formats
if(aspectMask == VK_IMAGE_ASPECT_COLOR_BIT && ((info.Aspects() & VK_IMAGE_ASPECT_PLANE_0_BIT) || tmp)){
}
