### ISSUE TITLE
Texture Viewer freeze

### ISSUE THREAD

**Issue by LaG1924** [baldurk/renderdoc#2008]
## Description

I have used this software successfully several years ago. Unfortunately, it has become more unstable now.

Tried the latest stable release. It crashes (after the first few frames, but before the main menu GUI is fully rendered) my application (the stacktrace leads somewhere inside the ndivia driver or SDL SwapBuffers() function). I've tried several versions, it stops working since 1.7 (in 1.6 it's still ok).

In version 1.6 RenderDoc hangs when loading capture. After closing my app, it switches to the Texture Viewer tab and starts loading (and looks like loaded because the data appears in the "Event Browser"), but when doing some post-processing, the progress bar at the bottom of the interface is displayed for a long time. After clicking in a random area, it freezes, later a Windows message "Application not responding" appears. There are 520 reported issues (which I want to solve with Renderdoc).

UPD: The saved capture file is loaded successfully, but when you manually switch to the "Texture Viewer" tab, it still freezes, even in 1.9

## Steps to reproduce

App (binary and sources): https://github.com/LaG1924/AltCraft/releases
Capture that causes long-loading: [capture.zip](https://github.com/baldurk/renderdoc/files/5026617/capture.zip)

## Environment

* RenderDoc version: 1.6 / 1.7+
* Operating System: Windows10-1909 x64
* Graphics API: OpenGL 3.3

* GPU: GTX 1070 Ti
* GPU Driver: 451.67

**Comment by baldurk** [comment]
I'm able to capture that program fine in v1.9 on multiple computers here, and I can also load the capture with no problems.

Given that and your description I have a feeling this may be a driver bug. Do you have a dual Intel/nvidia GPU system? If so what Intel driver version do you have? Similar kinds of problems have been reported by users on extremely old Intel drivers, and updating those might fix the problem.

If you can test on a different system that might also be able to eliminate the computer as a source of programs.

**Comment by LaG1924** [comment]
My CPU is Ryzen 2700X so it doesn't have Intel integrated graphics. And I have only one GPU in the system, but I have updated the drivers several times over the last six months (and it was not always without problems, but now everything is stable).
I have played many games without any problems on this PC, so I don't think the problem is with the video card drivers.
I also disabled any third-party software that might interfere with the capture process (sometimes there were problems with monitoring MSI Afterburner), however that did not help.

I checked RenderDoc on my old PC where I used RenderDoc successfully before (Intel processor with integrated graphics and discrete AMD graphics) and it works fine. It looks like my hardware or OS is to blame, but I'm not sure what exactly is the reason. Unfortunately, right now I cannot reinstall the OS.

**Comment by baldurk** [comment]
In that case I'm afraid there's not much I'll be able to do to help so I'm going to close this issue. The only thing I can think to suggest is to do a complete wipe of drivers using [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) and start from scratch.

The symptoms you describe still do seem to point to some system issue - the crash happens during presentation in the nvidia drivers (presentation often being a 'special case' where interaction with the system and other work happens), and the hang happening so late in loading suggests it's happening while RenderDoc is creating swapchains for presentation as well. You could try attaching a debugger to RenderDoc and using the [symbol server](https://renderdoc.org/symbols) to see what the threads are doing at the time.
