### ISSUE TITLE
renderdoccmd.exe replay exit .... python equivalent

### ISSUE THREAD

**Issue by pemgithub** [baldurk/renderdoc#2010]
## Description

1) If I understand correctly, (renderdoccmd.exe replay foo.rdc) replays an RDC file's frame once.  I'd like an option to play back the full frame once, dump to png file optional), then exit.

2) The ability to do this using the python API.  If I understand correctly, OpenCapture() does not replay the full frame.  Thought I may have misread the doc.  I think maybe to replay the full frame, we'd need to mimic the "Display texture in window" example.  Which loops through each draw using SetFrameEvent().  But I was hoping for a ReplayFrame function that replays the full frame from start to end, which is what I think renderdoccmd.exe replay does.

## Environment

* RenderDoc version: 1.9
* Operating System: Windows 10
* Graphics API: Vulkan

**Comment by pemgithub** [comment]
https://renderdoc.org/docs/python_api/renderdoc/main_ifaces.html#replaycontroller

I see there's a ReplayLoop().  But I don't see an option to just replay the entire frame one time (or N times) (then stop).

> Goes into a blocking loop, repeatedly replaying the open capture as fast as possible, displaying the selected texture in a default unscaled manner to the given output window.

**Comment by baldurk** [comment]
renderdoccmd is an internal tool only and should not be used directly by any user.

If you want scripted/automated access to captures then you should use the python API. This is not very high level so it doesn't provide a single function to do exactly what you want, but it contains all the functionality needed to open and manipulate captures in the same way that the UI does. You will need to put that together yourself to accomplish what you want to do. The documentation you have already found and there are a number of explained example programs there, as well as [the auto-testing scripts](https://github.com/baldurk/renderdoc/tree/v1.x/util/test) being less documented but more extensive examples.

**Comment by pemgithub** [comment]
Is there a simple example which just replays the frame's GPU API calls (Vulkan) one time (from start to finish)?
