### ISSUE TITLE
Segfault when using VK_KHR_get_physical_device_properties2 on 1.0 instance

### ISSUE THREAD

**Issue by Friz64** [baldurk/renderdoc#2012]
## Description

Calling `vkCreateInstance` with `VK_KHR_get_physical_device_properties2` in the extensions array and `VkApplicationInfo` `apiVersion` set to `1.0.0` segfaults while running in RenderDoc. Either running the application without RenderDoc, removing `VK_KHR_get_physical_device_properties2` from the extensions array or setting the `apiVersion` to `1.1.0` resolves this issue.

## Steps to reproduce

I don't think it is necessary to supply a example as this is very basic code.

It may be possible that this bug only occurs on certain drivers/hardware/operating systems.

## Environment

* RenderDoc version: 1.9 (https://aur.archlinux.org/packages/renderdoc-bin/)
* Operating System: Arch Linux latest
* Graphics API: Vulkan
* GPU: RX 580
* Drivers: Mesa 20.1.5

**Comment by baldurk** [comment]
Usually I try hard to be polite, as it's easy for someone reading along to get the wrong impression from a rude reply that may not be seen in context.

I hope though that anyone can see the sheer arrogance required for someone to decide that they are too important to bother providing the reproducible test case explicitly asked for when filing a bug asking for free support on a free program. Closing this issue.

**Comment by Friz64** [comment]
I am very sorry about this, i thought i would be less of a hassle for reproducers to setup a quick test program than trying to set up my program.
