### ISSUE TITLE
vkGetSwapchainImagesKHR is different form the official api description

### ISSUE THREAD

**Issue by luopan007** [baldurk/renderdoc#2017]
##Description

I capture a frame on a Mate 30 Pro mobile(android), the graphics api is **Vulkan**,  I double click to open the RDC file and export as zip.xml file。When I analyze the trace file of zip.xml, I found the api **vkGetSwapchainImagesKHR** different from khronos spec description。Here is the log:
``` xml
<chunk id="1024" index="5" name="vkGetSwapchainImagesKHR" length="28" threadID="529413422416" timestamp="52914285" duration="0">
    <ResourceId name="device" typename="VkDevice" width="8" string="ResourceId::2455">2455</ResourceId>
    <ResourceId name="Swapchain" typename="VkSwapchainKHR" width="8" string="ResourceId::2537">2537</ResourceId>
    <uint name="SwapchainImageIndex" typename="uint32_t" width="4">0</uint>
    <ResourceId name="SwapchainImage" typename="VkImage" width="8" string="ResourceId::2539">2539</ResourceId>
</chunk>
<chunk id="1024" index="6" name="vkGetSwapchainImagesKHR" length="28" threadID="529413422416" timestamp="52914307" duration="0">
    <ResourceId name="device" typename="VkDevice" width="8" string="ResourceId::2455">2455</ResourceId>
    <ResourceId name="Swapchain" typename="VkSwapchainKHR" width="8" string="ResourceId::2537">2537</ResourceId>
    <uint name="SwapchainImageIndex" typename="uint32_t" width="4">1</uint>
    <ResourceId name="SwapchainImage" typename="VkImage" width="8" string="ResourceId::2540">2540</ResourceId>
</chunk>
<chunk id="1024" index="7" name="vkGetSwapchainImagesKHR" length="28" threadID="529413422416" timestamp="52914311" duration="0">
    <ResourceId name="device" typename="VkDevice" width="8" string="ResourceId::2455">2455</ResourceId>
    <ResourceId name="Swapchain" typename="VkSwapchainKHR" width="8" string="ResourceId::2537">2537</ResourceId>
    <uint name="SwapchainImageIndex" typename="uint32_t" width="4">2</uint>
    <ResourceId name="SwapchainImage" typename="VkImage" width="8" string="ResourceId::2541">2541</ResourceId>
</chunk>

```

### The API description:
```
// Provided by VK_KHR_swapchain
VkResult vkGetSwapchainImagesKHR(
    VkDevice                                    device,
    VkSwapchainKHR                       swapchain,
    uint32_t*                                     pSwapchainImageCount,
    VkImage*                                    pSwapchainImages);
```
### Parameters
```
device is the device associated with swapchain.
swapchain is the swapchain to query.
pSwapchainImageCount is a pointer to an integer related to the number of presentable images available or queried, as described below.
pSwapchainImages is either NULL or a pointer to an array of VkImage handles.
```
### Purpose trace as follow:
`vkGetSwapchainImagesKHR({"device":527600705536, "pSwapchainImageCount":3, "pSwapchainImages":[2500,2535,2566], "swapchain":527600705538})`

### Question
1. Why the renderdoc save the swapchain image parted？
2. Why not save the swapchain Image in an array?

3. The last Question:  are you planning to fix this problem and consistent with the official api description?

## Environment

* RenderDoc version:  1.9
* Operating System: Windows 10 and Android 9
* Graphics API: Vulkan 1.2.141
* GPU Device: Mali-G76
* ADB version: 1.0.41

**Comment by baldurk** [comment]
RenderDoc's zip.xml export is the raw conversion of its internal serialised data. It is not a 100% exact representation of API calls.

**Comment by luopan007** [comment]
The zip.xml export is confused, how many this different in the RenderDoc ? if I want to keep with the API, i must modify the serialised method? thank you for your answer.

**Comment by luopan007** [comment]
> RenderDoc's zip.xml export is the raw conversion of its internal serialised data. It is not a 100% exact representation of API calls.

The zip.xml export is confused, how many this different in the RenderDoc ? if I want to keep with the API, i must modify the serialised method? thank you for your answer.

**Comment by baldurk** [comment]
I'm sorry but I don't understand what you're asking.

If you want an exact list of every API call and parameter then you should use a different tool, like the api_dump layer or vktrace.

**Comment by luopan007** [comment]
> I'm sorry but I don't understand what you're asking.
> 
> If you want an exact list of every API call and parameter then you should use a different tool, like the api_dump layer or vktrace.

yes you are right, I want an exact list of every API call and parameter. But I want to use renderdoc, this is a condition. can you give me a suggestion? thank you very much again!

**Comment by baldurk** [comment]
I don't have any suggestions because what you are asking for is not possible. If you want a precise API dump, then you should use a different tool. That is not how RenderDoc works and that will not change.
