### ISSUE TITLE
[Regression, bisect] Glitch when using glMultiDrawElementsIndirect

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#2019]
## Description

When using glMultiDrawElementsIndirect, overall playback is correct but when stepping through each draw call, rendering will be incorrect and/or glitched.

Either the geometry is all wrong (spiky triangles) or I see geometry that belongs to a different draw call (e.g. 256 spheres are drawn when it should be drawing 4 cubes) with the material of the current draw call

Bug was introduced in:

> commit e8b342f33210548a5b5198bc0a5e8c816bdf07fe
> Author: baldurk <baldurk@baldurk.org>
> Date:   Fri Feb 21 16:52:36 2020 +0000
> 
>    Add event for base of GL multi draw commands

Git bisect log:
```

git bisect start
# good: [0e7f772596035137416be01766c2d61205efc63e] Add Vulkan 1.2 support
git bisect good 0e7f772596035137416be01766c2d61205efc63e
# bad: [a56af589d94dc851809fd5344d0ae441da70c1f2] Don't modify descriptor update template while writing. Closes #1765
git bisect bad a56af589d94dc851809fd5344d0ae441da70c1f2
# good: [e012c82168f6655c3ec250e3350b9d144522217f] Update tests to use new interfaces
git bisect good e012c82168f6655c3ec250e3350b9d144522217f
# good: [4ec8280ee8391c865da061f0e957248c813b86c2] Add test of KHR/EXT GL debug marker behaviour
git bisect good 4ec8280ee8391c865da061f0e957248c813b86c2
# bad: [4873a9fdc338c41bb62ccce3eb32c30520298a78] Add missing calls to FreeTrace
git bisect bad 4873a9fdc338c41bb62ccce3eb32c30520298a78
# bad: [d034c916861ebe226a76519ac46dcae9922102be] Check for supported capability/extensions when debugging
git bisect bad d034c916861ebe226a76519ac46dcae9922102be
# bad: [c05dd34962e8c7bd4f0b99d31c3a489893163419] Switch back to setPointSizeF for scaling fonts
git bisect bad c05dd34962e8c7bd4f0b99d31c3a489893163419
# bad: [70913fdda5c73adcd76ba3547a1fb5907aebde91] Add test that GL multi-draw mesh output works with builtins
git bisect bad 70913fdda5c73adcd76ba3547a1fb5907aebde91
# bad: [81110ceca3091c58b3c6841911308b4d0e0aaf92] Fix accidental stomping of relative byte offsets in tests
git bisect bad 81110ceca3091c58b3c6841911308b4d0e0aaf92
# bad: [e8b342f33210548a5b5198bc0a5e8c816bdf07fe] Add event for base of GL multi draw commands
git bisect bad e8b342f33210548a5b5198bc0a5e8c816bdf07fe
# first bad commit: [e8b342f33210548a5b5198bc0a5e8c816bdf07fe] Add event for base of GL multi draw commands
```

## Steps to reproduce

1. Grab Ogre 2.2 ([build from source scripts](https://bintray.com/darksylinc/ogre-next/download_file?file_path=build_ogre_scripts-v2.2.3.7z), get [Windows binary samples](https://bintray.com/darksylinc/ogre-next/download_file?file_path=ogre-sdk-v2.2.3-vc19-x64.7z))
2. Capture bin/Release/Sample_PbsMaterials.exe
3. Single step through the GL multi draw commands

Note: I only tested Linux

RenderDoc capture: https://mega.nz/file/srxBSD4B#HFfPKpm8ItoLSv1gNhWGk-Djmd98cJRqTQpCltwW8yU

Video before regression: [2020-08-20 13-09-52.mkv.zip](https://github.com/baldurk/renderdoc/files/5104302/2020-08-20.13-09-52.mkv.zip)

Video after regression: [2020-08-20 13-25-21.mkv.zip](https://github.com/baldurk/renderdoc/files/5104305/2020-08-20.13-25-21.mkv.zip)

## Environment

* RenderDoc version: 1.7 - 1.9
* Operating System: Xubuntu 18.04 LTS
* Graphics API: OpenGL

**Comment by AllianceDarkSylinc** [comment]
> Either the geometry is all wrong (spiky triangles) or I see geometry that belongs to a different draw call (e.g. 256 spheres are drawn when it should be drawing 4 cubes) with the material of the current draw call

On closer inspection I think these two diagnostics: spiky triangles vs seeing geometry from a different draw, are the same bug.

I suspect RenderDoc is showing me the geometry of draw i (correct) and draw i+1 (incorrect).

When spiky triangles appear, I think it's because draw i+1 will be using a different vertex format (e.g. float32x3 vs half16x4)

**Comment by darksylinc** [comment]
> Either the geometry is all wrong (spiky triangles) or I see geometry that belongs to a different draw call (e.g. 256 spheres are drawn when it should be drawing 4 cubes) with the material of the current draw call

On closer inspection I think these two diagnostics: spiky triangles vs seeing geometry from a different draw, are the same bug.

I suspect RenderDoc is showing me the geometry of draw i (correct) and draw i+1 (incorrect).

When spiky triangles appear, I think it's because draw i+1 will be using a different vertex format (e.g. float32x3 vs half16x4), hence it's garbage when read with the wrong vertex format

**Comment by baldurk** [comment]
I didn't fix up the event calculation during partial replay to match, that commit should fix things.
