### ISSUE TITLE
Crash during D3D11 capture when a buffer is mapped simultaneously on 2 threads (different crash than issue 1913)

### ISSUE THREAD

**Issue by arkgmarion** [baldurk/renderdoc#2023]
## Description

During a D3D11 capture triggered by code, a race condition can happen if the same buffer is mapped / unmapped on 2 different deferred contexts approximately at the same time. The crash never happens on the first capture, but can happen on any subsequent one.

## Steps to reproduce

I attach a cpp file which reproduces the crash.
The crash usually happens during the 2nd or 3rd loop iteration.

[RenderDocTest1.zip](https://github.com/baldurk/renderdoc/files/5128653/RenderDocTest1.zip)

From what I understood the crash happens when the buffer is mapped from different threads on each successive capture.
I tracked it down to 2 issues :
- at the end of the first capture, CleanupCapture calls FreeContextID then sets used = false on the DeferredShadow array elements but GetContextID doesn't set it to true again when it doesn't need to allocate a new slot and reuse an unused one. It can lead to the same slot being reused on 2 contexts
- Even when fixing this issue, another one can occur : the per-context contextid cache for each resource (m_MapResourceRecordAllocs) is not cleared at the end of the capture, so the next capture skip the call to GetContextID if the same context is reused. But if another context which in the previous captures never mapped the buffer now maps it, it can allocate the same contextid than the other context.

The following code fixes both issues for me and I don't have the crash anymore :

in the function void WrappedID3D11DeviceContext::CleanupCapture() :
add
 	m_MapResourceRecordAllocs.clear(); 
just after the following loop
    for(auto it = m_MapResourceRecordAllocs.begin(); it != m_MapResourceRecordAllocs.end(); ++it)
    {
      D3D11ResourceRecord *record = m_pDevice->GetResourceManager()->GetResourceRecord(it->first);
      if(record)
      {
        if(record->NumSubResources > 0)
          record = record->SubResources[0];
        record->FreeContextID(it->second);
      }
    }

in size_t D3D11ResourceRecord::GetContextID() :
replace the loop with
    for(size_t i = 0; i < DeferredShadow.size(); i++)
    {
      if(!DeferredShadow[i].used)
      {
		DeferredShadow[i].used = true;
        return i + 1;
      }
    }

## Environment

* RenderDoc version: 1.8
* Operating System: Windows 10 build 1909
* Graphics API: DX11

**Comment by baldurk** [comment]
Thanks for the detailed analysis, it's entirely correct and I've applied the fixes as you suggested.

FYI in future if you'd like to make your fix directly and have proper attribution you can open a pull request with the changes.
