### ISSUE TITLE
Fragment shader running twice when using vkCmdDrawIndirect

### ISSUE THREAD

**Issue by LDeakin** [baldurk/renderdoc#2025]
## Description
When replaying a Vulkan app, the fragment shader is being invoked twice per fragment when using vkCmdDrawIndirect.

## Steps to reproduce
I've emailed you a capture under subject _Renderdoc bug report: Fragment shader running twice when using vkCmdDrawIndirect_.
The fragment shader should output vec4(0.5f), but seems to run twice and incorrectly outputs vec4(1.0f), blending is additive.

**Desired output**
![image](https://user-images.githubusercontent.com/5069739/91382919-2f8c6c80-e86e-11ea-8b23-205144b08f4d.png)

**Observed output when replaying indirect draw**
![image](https://user-images.githubusercontent.com/5069739/91382958-4af77780-e86e-11ea-8507-a7c8bca199b6.png)

## Environment

* RenderDoc version: 2020_08_25_753806d5_64
* Operating System: Windows 10
* Graphics API: Vulkan
* GPU: GeForce GTX 1070, driver 451.98

**Comment by baldurk** [comment]
The event counting was off in the case where a "multidraw" wasn't actually multiple draws but just one, where it gets inlined as a single draw in the event browser. That would lead to the draw being replayed twice when selected. That commit should fix it.
