### ISSUE TITLE
Disable Showing LOADDONTCARE In Texture Viewer

### ISSUE THREAD

**Issue by tkgamegroup** [baldurk/renderdoc#2027]
## Description
when i capture a frame that use a renderpass with load-dont-care option, it display this in the Texture Viewer:
![20200827174040](https://user-images.githubusercontent.com/12348900/91424510-77ba8780-e88c-11ea-9280-c88656093dc3.png)
because my texture was cleared by another cmd before begining the renderpass, i suggest not to display that text and use the color of the last clear cmd if theres is a such cmd.
## Environment

* RenderDoc version: 1.9
* Operating System: Window 10
* Graphics API: Vulkan

**Comment by Anteru** [comment]
You specified "Don't care", which means the implementation is allowed to replace it with any content it wants (and some implementations will do so!) If you want to preserve the input, you cannot use "Don't care" -- use `LOAD_OP_LOAD` instead.

**Comment by baldurk** [comment]
RenderDoc is showing you that you have a bug in your code which may break depending on GPU or driver behaviour. If you clear and _then_ use `LOAD_DONT_CARE` in a renderpass then the contents will be undefined. RenderDoc fills with a specific pattern precisely to let you know about the problem.
