### ISSUE TITLE
Grey out dead code (ubershaders)

### ISSUE THREAD

**Issue by dor666** [baldurk/renderdoc#2032]
## Description

When debugging ubershaders, there is usually a lot of dead code in context of currently selected draw call, when branching is based on uniforms:

```
if (uniform.effect == 1){
    if (uniform.effectDetail == 1){
        [...]
    }
    if (uniform.effectDetail == 2){
        [...]
    }
}
else if(uniform.effect = 2){
        [...]
}
else(){
        [...]
}
```

It would be nice if Renderdoc could grey-out non-reachable sections in shader View/Edit/Debug.
Currently I have to switch to pipeline view, navigate to stage and see/remember `uniform` values.

## Environment

* RenderDoc version: 1.9
* Operating System: Windows
* Graphics API: Vulkan

**Comment by baldurk** [comment]
I rarely close feature requests but this is one I think is too high in complexity and too low in value to ever be worthwhile implementing.
