### ISSUE TITLE
unexpected error when press the capture button using renderdocui.exe

### ISSUE THREAD

**Issue by Rubics-Xuan** [baldurk/renderdoc#2033]
Sorry to interrupt you.I have been stuck in step 9 of the "Setup for Capturing" of the following tutorial [https://bitbucket.org/visinf/projects-2016-playing-for-data](url).After doing all the preparations using Cmake and VS2013 which gives no errors,I open the renderdocui.exe with "run as administrator".But after I adding the excecutable path to the GTAVLauncher.exe and  selectinng hook into children options,when I press the capture it gives errors like this:

Error launching F:\GTA5\steamapps\common\Grand Theft Auto V\GTAV launcher.exe for capture. Check diagnostic log in Help menus for details.

and the diagnostic log file is like this:

*RENDERDOC: [20:10:11] core.cpp( 242) - Log - RenderDoc v0.27 x64 (NO_GIT_COMMIT_HASH_DEFINED) loaded in replay application

RENDERDOC: [20:10:18] win32_process.cpp( 307) - Log - Injecting renderdoc into process 3108

RENDERDOC: [20:10:18] win32_process.cpp( 164) - Error - Couldn't find module 'renderdoc.dll' among 31 modules

RENDERDOC: [20:10:18] win32_process.cpp( 420) - Error - Can't locate renderdoc.dll in remote PID 3108*

I believe it has no erros inside my preparation works cause I saw another questions asked by others at this[https://github.com/baldurk/renderdoc/issues/1365](url).It seems like the official renderdoc sometimes also shows this error.I am really looking forward to your reply,please give me some advice cause I have been stuck here for almost four weeks.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by Rubics-Xuan** [comment]
Thanks for your reply,sir.So I will contact you by this email directly.Here is the bug report in the following.



Description

To be mentioned,the renderdoc I used is not the official copyright.I have been stuck in step 9 of the "Setup for Capturing" of the following tutorial&nbsp;https://bitbucket.org/visinf/projects-2016-playing-for-data.After finishing all the preparation works before this step,I start to use renderdoc to capture GTAV Game.However,after I adding the GTAVLauncher.exe into the executable path and selectinng hook into children options,when I press the capture button it shows some errors like this:



Error launching F:\GTA5\steamapps\common\Grand Theft Auto V\GTAV launcher.exe for capture. Check diagnostic log in Help menus for details.

and the diagnostic log file is like this:

RENDERDOC: [20:10:11] core.cpp( 242) - Log - RenderDoc v0.27 x64 (NO_GIT_COMMIT_HASH_DEFINED) loaded in replay application

RENDERDOC: [20:10:18] win32_process.cpp( 307) - Log - Injecting renderdoc into process 3108

RENDERDOC: [20:10:18] win32_process.cpp( 164) - Error - Couldn't find module 'renderdoc.dll' among 31 modules

RENDERDOC: [20:10:18] win32_process.cpp( 420) - Error - Can't locate renderdoc.dll in remote PID 3108

No matter I press the capture button or I use the global hook option, it doesn't show the overlay in the upper left corner in the Game.All the preparation works before this step——press the capture button gives no errors,so I am really confused where the problem might be.

Actually,I think it has nothing to do with the compling renderdoc cause there are others using official renderdoc also happens this error,here is the website I saw—https://github.com/baldurk/renderdoc/issues/1365.So I guess the errors might have something to do with the game GTAV,I've also seen your comments below the renderdoc tutorial videos,you say that the game itself might have protections.But this paper&nbsp;&nbsp;https://bitbucket.org/visinf/projects-2016-playing-for-data(In ECCV 2016),already made it,so I am really confused and really need your guidance,thanks for your time.

Steps to reproduce

To be mentioned,Release.zip(in the email) is the whole renderdoc folder after&nbsp;Compiling the complete&nbsp;renderdoc&nbsp;solution before the "Setup for capturing:" according to the&nbsp;https://bitbucket.org/visinf/projects-2016-playing-for-data.
1.unzip the Release.zip and run&nbsp;renderdocui.exe&nbsp;with admin privileges.
2.Specify the path where dumped frames are stored:&nbsp;Tools/Options/Directory for temporary capture files.
3.Point the&nbsp;Executable Path&nbsp;to GTAVLauncher.exe(which is downloaded from steam).
4.press the capture button and it will give errors mentioned above.

Environment

·Visual Studio version:2013
·Operating System: Windows 10
·GTAV version:the latest version from steam
·renderdoc version:RenderDoc Unofficial release(v0.27- NO_GIT_COMMIT_HASH_DEFINED)——according to the project
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baldurk/renderdoc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月29日(星期六) 晚上11:10
收件人:&nbsp;"baldurk/renderdoc"<renderdoc@noreply.github.com&gt;;
抄送:&nbsp;"旅于人生"<524286559@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baldurk/renderdoc] unexpected error when press the capture button using renderdocui.exe (#2033)





 
Hi there, your issue has been closed due to not correctly following the issue template. Please read the documentation about filing issues and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.
 
I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!
 
In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is documentation going into more detail about what makes a good issue.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

Release.zip (67.87M, 2020年09月29日 10:45 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=25323662ca30f39f3ac8097d1237034b01515452575108064807535a511a050257501b5b50055749510a575a0300550052020655343c3136005e530347521f1e0c42365f&code=e26b471d
