### ISSUE TITLE
Unexpected error when press the capture button using renderdocui.exe 

### ISSUE THREAD

**Issue by Rubics-Xuan** [baldurk/renderdoc#2035]
## Description

To be mentioned,the renderdoc I used is not the official copyright.I have been stuck in step 9 of the "Setup for Capturing" of the following tutorial [https://bitbucket.org/visinf/projects-2016-playing-for-data].After finishing all the preparation works before this step,I start to use renderdoc to capture GTAV Game.However,after I adding the GTAVLauncher.exe into the executable path and selectinng hook into children options,when I press the capture button it shows some errors like this:

_Error launching F:\GTA5\steamapps\common\Grand Theft Auto V\GTAV launcher.exe for capture. Check diagnostic log in Help menus for details._

and the diagnostic log file is like this:

_RENDERDOC: [20:10:11] core.cpp( 242) - Log - RenderDoc v0.27 x64 (NO_GIT_COMMIT_HASH_DEFINED) loaded in replay application_

_RENDERDOC: [20:10:18] win32_process.cpp( 307) - Log - Injecting renderdoc into process 3108_

_RENDERDOC: [20:10:18] win32_process.cpp( 164) - Error - Couldn't find module 'renderdoc.dll' among 31 modules_

_RENDERDOC: [20:10:18] win32_process.cpp( 420) - Error - Can't locate renderdoc.dll in remote PID 3108_

No matter I press the capture button or I use the global hook option, it doesn't show the overlay in the upper left corner in the Game.All the preparation works before this step——press the capture button gives no errors,so I am really confused where the problem might be.

Actually,I think it has nothing to do with the compling renderdoc cause there are others using official renderdoc also happens this error,here is the website I saw—[https://github.com/baldurk/renderdoc/issues/1365].So I guess the errors might have something to do with the game GTAV,I've also seen your comments below the renderdoc tutorial videos,you say that the game itself might have protections.But this paper  [https://bitbucket.org/visinf/projects-2016-playing-for-data](In ECCV 2016),already made it,so I am really confused and really need your guidance,thanks for your time.

## Steps to reproduce

To be mentioned,Release.zip(in the email) is the whole renderdoc folder after Compiling the complete renderdoc solution before the "Setup for capturing:" according to the [https://bitbucket.org/visinf/projects-2016-playing-for-data].
1.unzip the Release.zip and run renderdocui.exe with admin privileges.
2.Specify the path where dumped frames are stored: Tools/Options/Directory for temporary capture files.
3.Point the Executable Path to GTAVLauncher.exe(which is downloaded from steam).
4.press the capture button and it will give errors mentioned above.

## Environment

* Visual Studio version:2013
* Operating System: Windows 10
* GTAV version:the latest version from steam
* renderdoc version:RenderDoc Unofficial release(v0.27- NO_GIT_COMMIT_HASH_DEFINED)——according to the project

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by Rubics-Xuan** [comment]
I am sorry,I really understand your thoughts,I think you might misunderstood me.I just tryna reproduce the project work according to the&nbsp;the paper Playing for Data: Ground Truth from Computer Games. Stephan Richter, Vibhav Vineet, Stefan Roth, and Vladlen Koltun. In ECCV 2016. I just wanna make a dataset for my major CV using renderdoc and GTAV ,nothing else, I understood your meaning,I am sorry to interrupt you .




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baldurk/renderdoc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月30日(星期天) 晚上10:33
收件人:&nbsp;"baldurk/renderdoc"<renderdoc@noreply.github.com&gt;;
抄送:&nbsp;"旅于人生"<524286559@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baldurk/renderdoc] Unexpected error when press the capture button using renderdocui.exe  (#2035)





 
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
