### ISSUE TITLE
Performance Counters (FetchSize, WriteSize)

### ISSUE THREAD

**Issue by massemibrahim** [baldurk/renderdoc#2037]
## Description

Hi, using RenderDoc, I was able to capture and analyze frames for the sake of understanding graphics workloads. The captured frames are from 3DMark (Time Spy). I observed an unreasonable behavior across the captured frames (the attached frame is one of them). For a given frame, the overall frame duration seems reasonable and inline with the reported FPS. However, the FetchSize + WriteSize, reported in **bytes**, seems unreasonable as we observed terabytes of requested data from memory. Such size along with the frame duration leads to unrealistic bandwidth. The used GPU has a memory bandwidth of 1 TB/Second. **I suspect that FetchSize and WriteSize are reporting 1000X more.**

## Steps to reproduce

1) Open RenderDoc.
2) Open the attached capture with the default options.
**OneDrive Link (RDC File + Log File):** https://1drv.ms/u/s!AuNZOSQ8XvnBg-gzE7Fl7lv5F6VoXw?e=FSFpyr
3) Open the Performance Counter Viewer. 
4) Select AMD -> GlobalMemory -> FetchSize/WriteSize Counters.
5) Capture counters.

## Environment

* RenderDoc Version v1.9 
* AMD Radeon VII GPU
* Windows 10 Pro, Version 2004
* AMD Ryzen Threadripper 2950x 16-Core Processor 3.5 GHz
* 128 GB RAM
* 3DMark (Time Spy)

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
