### ISSUE TITLE
Secondary command buffers not traced (example attached)

### ISSUE THREAD

**Issue by michaelworcester** [baldurk/renderdoc#204]
Attached!

[simple.zip](https://github.com/baldurk/renderdoc/files/162335/simple.zip)

**Comment by baldurk** [comment]
The attached sample doesn't seem to run for me anymore (it used to), but I tried with a different secondary command buffer example. I think this should all be working now, but let me know if you find any edge-cases or places where it breaks down!

**Comment by baldurk** [comment]
Closing this issue as the feature is implemented in [v0.30](https://github.com/baldurk/renderdoc/releases/tag/v0.30). Feel free to re-open if it's not as you expect!
