### ISSUE TITLE
Run Itanium name demangling on OpNames.

### ISSUE THREAD

**Issue by seanbaxter** [baldurk/renderdoc#2044]
## Description

I wrote a C++ compiler and have been adding a SPIR-V backend to generate shaders directly from C++. Since shaders can be function templates, and interface variables can be variable templates, and uniform and storage buffers can be class templates, I use Itanium name mangling to encode the identifier and type names in the SPIRV module.

Can RenderDoc run name-demangling to print OpNames so things look pretty? Basically run __cxa_demangle on all OpName literals and it'll return the status code if it was a success.

[Here's an image of the problem](https://pbs.twimg.com/media/EhZJmy1XsAAgXnG?format=jpg&name=large). Interface variables all mangled.

## Environment

* RenderDoc version: 1.9
* Operating System: Linux
* Graphics API: OpenGL

**Comment by baldurk** [comment]
This is the responsibility of the SPIR-V frontend, so it's not something I would add to RenderDoc. There's no restriction to what you can use as the OpName string so you can demangle before emitting OpName if you want to do so.
