### ISSUE TITLE
Remote attach using RenderDoc API failing to detect graphics API

### ISSUE THREAD

**Issue by Pixelbear** [baldurk/renderdoc#2047]
## Description

I am attempting to attach RenderDoc to a currently running application using the API and capture a single frame. While the diagnostic log successfully reports a handshake with the application, it seems to fail to detect the graphics API and says "API: None". I attempt to make calls to StartFrameCapture/EndFrameCapture regardless, but they fail to capture a frame.

The application uses OpenGL 3.3, but the OpenGL context is not created until after a pre-load period. It is probably also worth noting that the application itself is a CAD application and the 3D view port only updates when a user interacts with it.

[This is the Diagnostic Log.](https://github.com/baldurk/renderdoc/files/5195618/renderdoc_log.log)

## Steps to reproduce

Unfortunately the application is closed source. Specifically within the code however, I make the following API calls immediately after the OpenGL context has been created:

1. SetActiveWindow
2. LaunchReplayUI

which successfully opens up RenderDoc with my application attached, albeit with API: None. I then also surround the drawing code with StartFrameCapture and EndFrameCapture, but EndFrameCapture returns 0.

## Environment

* RenderDoc version: 1.9
* Operating System: Windows 10 Pro
* Graphics API: OpenGL 3.3

* GPU: NVIDIA Quadro P2000
* Driver: 25.21.14.1917

**Comment by baldurk** [comment]
The log you've uploaded there only shows the log from the LaunchReplayUI where it's trying to attach to RenderDoc's control connection, it doesn't share a logfile with anything. I'd need to see the log from the original instance of the RenderDoc UI where you first launched your program to see why it's not properly detecting the OpenGL context.

**Comment by Pixelbear** [comment]
Apologies, but I am confused. I launch the program from Visual Studio and the LaunchReplayUI opens RenderDoc. I do not launch the program from RenderDoc. This is the entire log file from that (as far as I am aware?)

If this is incorrect then just to clarify the steps I need to follow are:

1. start RenderDoc independently
2. launch the program from there
3. copy the diagnostic log?

**Comment by baldurk** [comment]
If you're not launching the program from RenderDoc then that is almost certainly why it's not working, because your program isn't being properly hooked. Please read the documentation on how to use RenderDoc and follow the correct workflow.
