### ISSUE TITLE
Stencil values as binary too

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#2052]
## Description

I am using the pipeline state to debug stencil bits in the engine. We have stencil flags that mean different features or behavior, and in combination, they result in an 8-bit number shown in hex.

However, one thing that would be very useful to me is to see that same representation in binary, all 8 digits. So, for example, if I have the combination 0b10110000 which results in 0xB0, it would be useful at the bottom to be able to see 0xB0 (10110000) or something similar to that. It saves me having to constantly go to the calculator all the time to verify that certain bits I care about are set.

This would apply both to the pixel value as well as the Output Merger section of the pipeline state.

Thanks!

## Environment

* RenderDoc version: 1.9
* Operating System: Windows 10
* Graphics API: DX11

**Comment by baldurk** [comment]
I don't think displaying the binary value directly is worth it. Hex values are already a directly human readable format for bits, so displaying binary values as well would add extra UI space and clutter in a place where it's at a premium.

What I can do as a middle ground is add a tooltip to those fields showing hex/decimal/binary values.

It might be worthwhile looking into writing a custom visualisation shader that decodes stencil values and displays the relevant bits that you care about in different colour combinations. You could even use screen-space techniques to add simple cross-hatching for combining different colours depending on your use case.

**Comment by redorav** [comment]
The tooltip solution would be good enough for me. Hex values are human readable to some extent, but I find it easier to not have to decode them, maybe I'm just slow ^o^

The shader with different colors is something I hadn't thought of, I can give that a try too. Thanks!

**Comment by baldurk** [comment]
That commit adds tooltips to the texture viewer status bar and the stencil displays in the pipeline state views with decimal, hex, and binary.

**Comment by redorav** [comment]
Hi Baldur, that's really cool and very fast turnaround. Thank you for taking the time to implement it. I'm back home tomorrow and I'll be sure to try it out. Renderdoc just keeps getting better :)
