### ISSUE TITLE
crash after open a capture in macos

### ISSUE THREAD

**Issue by spotsking** [baldurk/renderdoc#2053]
Crash Log:

Process:               qrenderdoc [1528]
Path:                  /Applications/RenderDoc.app/Contents/MacOS/qrenderdoc
Identifier:            org.renderdoc.qrenderdoc
Version:               1.10.0 (0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           qrenderdoc [1528]
User ID:               501

Date/Time:             2020-09-16 14:56:11.579 +0800
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Anonymous UUID:        F3E5B565-3707-F79B-ABA5-E3D2D84E7ECE

Time Awake Since Boot: 590 seconds

System Integrity Protection: enabled

Crashed Thread:        22  ReplayManager

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [1528]

Application Specific Information:
dyld: in dlopen()
-[NSOpenGLContext setView:] must be called from the main thread.

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6cc39dfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6cc3a170 mach_msg + 60
2   com.apple.SkyLight            	0x00007fff61d628ac SLSSetWindowDepth + 207
3   com.apple.AppKit              	0x00007fff2ffc7c41 __NSCGSWindowBackingStoreMark__block_invoke + 617
4   com.apple.AppKit              	0x00007fff2ffc69de NSCGSTransactionRunPreCommitActionsForOrder_ + 247
5   com.apple.AppKit              	0x00007fff2ffc68c6 NSCGSTransactionRunPreCommitActions_ + 31
6   com.apple.AppKit              	0x00007fff2ffc6893 __39+[_NSCGSTransaction currentTransaction]_block_invoke.32 + 34
7   com.apple.QuartzCore          	0x00007fff3e670454 CA::Transaction::run_commit_handlers(CATransactionPhase) + 106
8   com.apple.QuartzCore          	0x00007fff3e670da6 CA::Context::commit_transaction(CA::Transaction*, double) + 2014
9   com.apple.QuartzCore          	0x00007fff3e66f304 CA::Transaction::commit() + 644
10  com.apple.AppKit              	0x00007fff3012e076 _NSTryRunModal + 70
11  com.apple.AppKit              	0x00007fff302c1e4f -[NSApplication runModalSession:] + 128
12  libqcocoa.dylib               	0x0000000109f9bb57 0x109f64000 + 228183
13  org.qt-project.QtCore         	0x0000000107f09d97 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 439
14  org.qt-project.QtWidgets      	0x000000010720ffde QDialog::exec() + 510
15  org.renderdoc.qrenderdoc      	0x0000000101b488af ShowProgressDialog(QWidget*, QString const&, std::__1::function<bool ()>, std::__1::function<float ()>, std::__1::function<void ()>) + 799
16  org.renderdoc.qrenderdoc      	0x0000000101b1654e CaptureContext::LoadCapture(rdcstr const&, ReplayOptions const&, rdcstr const&, bool, bool) + 2750
17  org.renderdoc.qrenderdoc      	0x0000000101bcb674 MainWindow::LoadCapture(QString const&, ReplayOptions const&, bool, bool) + 3124
18  org.renderdoc.qrenderdoc      	0x0000000101bca4e4 MainWindow::LoadFromFilename(QString const&, bool) + 212
19  org.renderdoc.qrenderdoc      	0x0000000101bc9979 MainWindow::on_action_Open_Capture_triggered() + 345
20  org.renderdoc.qrenderdoc      	0x0000000101f63a2e MainWindow::qt_metacall(QMetaObject::Call, int, void**) + 62
21  org.qt-project.QtCore         	0x0000000107f4022d 0x107d1d000 + 2241069
22  org.qt-project.QtWidgets      	0x0000000107007886 QAction::activate(QAction::ActionEvent) + 310
23  org.qt-project.QtCore         	0x0000000107f381f6 QObject::event(QEvent*) + 950
24  org.qt-project.QtWidgets      	0x0000000107010c76 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 262
25  org.qt-project.QtWidgets      	0x0000000107012042 QApplication::notify(QObject*, QEvent*) + 466
26  org.qt-project.QtCore         	0x0000000107f0dbd4 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
27  org.qt-project.QtCore         	0x0000000107f0ed53 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 803
28  org.renderdoc.qrenderdoc      	0x0000000101af7faf main + 12415
29  libdyld.dylib                 	0x00007fff6caf8cc9 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff6ccf8b68 start_wqthread + 0

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff6cc3c756 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff6cbbfeea nanosleep + 196
2   libsystem_c.dylib             	0x00007fff6cbbfde4 usleep + 53
3   librenderdoc.dylib            	0x00000001036f3180 AndroidController::ThreadEntry() + 240
4   librenderdoc.dylib            	0x00000001038b6d6d Threading::sThreadInit(void*) + 141
5   libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

Thread 3:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff6cc3c882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6ccfd425 _pthread_cond_wait + 698
2   org.qt-project.QtCore         	0x0000000107d461e9 0x107d1d000 + 168425
3   org.qt-project.QtCore         	0x0000000107d45f5e 0x107d1d000 + 167774
4   org.qt-project.QtCore         	0x0000000107d45ed3 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 83
5   org.qt-project.QtCore         	0x0000000107d4286d 0x107d1d000 + 153709
6   org.qt-project.QtCore         	0x0000000107d3e399 0x107d1d000 + 136089
7   libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

Thread 4:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff6cc3c882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6ccfd425 _pthread_cond_wait + 698
2   org.qt-project.QtCore         	0x0000000107d461e9 0x107d1d000 + 168425
3   org.qt-project.QtCore         	0x0000000107d45f5e 0x107d1d000 + 167774
4   org.qt-project.QtCore         	0x0000000107d45ed3 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 83
5   org.qt-project.QtCore         	0x0000000107d4286d 0x107d1d000 + 153709
6   org.qt-project.QtCore         	0x0000000107d3e399 0x107d1d000 + 136089
7   libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

Thread 5:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff6cc3c882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6ccfd425 _pthread_cond_wait + 698
2   org.qt-project.QtCore         	0x0000000107d461e9 0x107d1d000 + 168425
3   org.qt-project.QtCore         	0x0000000107d45f5e 0x107d1d000 + 167774
4   org.qt-project.QtCore         	0x0000000107d45ed3 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 83
5   org.qt-project.QtCore         	0x0000000107d4286d 0x107d1d000 + 153709
6   org.qt-project.QtCore         	0x0000000107d3e399 0x107d1d000 + 136089
7   libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

Thread 6:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff6cc3c882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6ccfd425 _pthread_cond_wait + 698
2   org.qt-project.QtCore         	0x0000000107d461e9 0x107d1d000 + 168425
3   org.qt-project.QtCore         	0x0000000107d45f5e 0x107d1d000 + 167774
4   org.qt-project.QtCore         	0x0000000107d45ed3 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 83
5   org.qt-project.QtCore         	0x0000000107d4286d 0x107d1d000 + 153709
6   org.qt-project.QtCore         	0x0000000107d3e399 0x107d1d000 + 136089
7   libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

Thread 7:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff6cc3c882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6ccfd425 _pthread_cond_wait + 698
2   org.qt-project.QtCore         	0x0000000107d461e9 0x107d1d000 + 168425
3   org.qt-project.QtCore         	0x0000000107d45f5e 0x107d1d000 + 167774
4   org.qt-project.QtCore         	0x0000000107d45ed3 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 83
5   org.qt-project.QtCore         	0x0000000107d4286d 0x107d1d000 + 153709
6   org.qt-project.QtCore         	0x0000000107d3e399 0x107d1d000 + 136089
7   libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

Thread 8:: Remote Probe
0   libsystem_kernel.dylib        	0x00007fff6cc3c756 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff6cbbfeea nanosleep + 196
2   org.qt-project.QtCore         	0x0000000107f6e14b 0x107d1d000 + 2429259
3   org.renderdoc.qrenderdoc      	0x0000000101bdc3ea std::__1::__function::__func<MainWindow::MainWindow(ICaptureContext&)::$_3, std::__1::allocator<MainWindow::MainWindow(ICaptureContext&)::$_3>, void ()>::operator()() + 138
4   org.renderdoc.qrenderdoc      	0x0000000101b02aea LambdaThread::process() + 42
5   org.qt-project.QtCore         	0x0000000107f40252 0x107d1d000 + 2241106
6   org.qt-project.QtCore         	0x0000000107d3db68 QThread::started(QThread::QPrivateSignal) + 56
7   org.qt-project.QtCore         	0x0000000107d3e37f 0x107d1d000 + 136063
8   libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
9   libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

Thread 9:: QThread
0   libsystem_kernel.dylib        	0x00007fff6cc403d6 poll + 10
1   org.qt-project.QtCore         	0x0000000107f6e91a qt_safe_poll(pollfd*, unsigned int, timespec const*) + 474
2   org.qt-project.QtCore         	0x0000000107f70047 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 983
3   org.qt-project.QtCore         	0x0000000107f09d97 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 439
4   org.renderdoc.qrenderdoc      	0x0000000101bdc5d1 std::__1::__function::__func<MainWindow::MainWindow(ICaptureContext&)::$_5, std::__1::allocator<MainWindow::MainWindow(ICaptureContext&)::$_5>, void ()>::operator()() + 33
5   org.renderdoc.qrenderdoc      	0x0000000101b02aea LambdaThread::process() + 42
6   org.qt-project.QtCore         	0x0000000107f40252 0x107d1d000 + 2241106
7   org.qt-project.QtCore         	0x0000000107d3db68 QThread::started(QThread::QPrivateSignal) + 56
8   org.qt-project.QtCore         	0x0000000107d3e37f 0x107d1d000 + 136063
9   libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
10  libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

Thread 10:
0   libsystem_pthread.dylib       	0x00007fff6ccf8b68 start_wqthread + 0

Thread 11:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff6cc3c882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6ccfd425 _pthread_cond_wait + 698
2   org.qt-project.QtCore         	0x0000000107d461e9 0x107d1d000 + 168425
3   org.qt-project.QtCore         	0x0000000107d45f5e 0x107d1d000 + 167774
4   org.qt-project.QtCore         	0x0000000107d45ed3 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 83
5   org.qt-project.QtCore         	0x0000000107d4286d 0x107d1d000 + 153709
6   org.qt-project.QtCore         	0x0000000107d3e399 0x107d1d000 + 136089
7   libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

Thread 12:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff6cc3c882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6ccfd425 _pthread_cond_wait + 698
2   org.qt-project.QtCore         	0x0000000107d461e9 0x107d1d000 + 168425
3   org.qt-project.QtCore         	0x0000000107d45f5e 0x107d1d000 + 167774
4   org.qt-project.QtCore         	0x0000000107d45ed3 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 83
5   org.qt-project.QtCore         	0x0000000107d4286d 0x107d1d000 + 153709
6   org.qt-project.QtCore         	0x0000000107d3e399 0x107d1d000 + 136089
7   libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

Thread 13:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff6cc3c882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6ccfd425 _pthread_cond_wait + 698
2   org.qt-project.QtCore         	0x0000000107d461e9 0x107d1d000 + 168425
3   org.qt-project.QtCore         	0x0000000107d45f5e 0x107d1d000 + 167774
4   org.qt-project.QtCore         	0x0000000107d45ed3 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 83
5   org.qt-project.QtCore         	0x0000000107d4286d 0x107d1d000 + 153709
6   org.qt-project.QtCore         	0x0000000107d3e399 0x107d1d000 + 136089
7   libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

Thread 14:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff6cc39dfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6cc3a170 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff32bb20b5 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff32bb0b82 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff32bafffe CFRunLoopRunSpecific + 462
5   com.apple.AppKit              	0x00007fff2ffd05b4 _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

Thread 15:
0   libsystem_pthread.dylib       	0x00007fff6ccf8b68 start_wqthread + 0

Thread 16:
0   libsystem_pthread.dylib       	0x00007fff6ccf8b68 start_wqthread + 0

Thread 17:: Dispatch queue: com.apple.root.utility-qos
0   dyld                          	0x000000010accdfc6 getattrlist + 10
1   dyld                          	0x000000010acc71c3 realpath$DARWIN_EXTSN + 819
2   dyld                          	0x000000010ac91d7f ImageLoaderMachO::getRPaths(ImageLoader::LinkContext const&, std::__1::vector<char const*, std::__1::allocator<char const*> >&) const + 627
3   dyld                          	0x000000010ac87caf dlopen_internal + 277
4   libdyld.dylib                 	0x00007fff6cae3d8a dlopen + 171
5   librenderdoc.dylib            	0x00000001038aa813 interposed_dlopen(char const*, int) + 35
6   libDiagnosticMessagesClient.dylib	0x00007fff69609b02 __get_core_analytics_framework_block_invoke + 21
7   libdispatch.dylib             	0x00007fff6ca9f658 _dispatch_client_callout + 8
8   libdispatch.dylib             	0x00007fff6caa07de _dispatch_once_callout + 20
9   libDiagnosticMessagesClient.dylib	0x00007fff69609aeb __call_analytics_send_event_lazy_block_invoke + 108
10  libdispatch.dylib             	0x00007fff6ca9f658 _dispatch_client_callout + 8
11  libdispatch.dylib             	0x00007fff6caa07de _dispatch_once_callout + 20
12  libDiagnosticMessagesClient.dylib	0x00007fff69609a7d call_analytics_send_event_lazy + 71
13  libDiagnosticMessagesClient.dylib	0x00007fff6960a062 msgtracer_vlog_with_keys_skip_nulls + 146
14  libDiagnosticMessagesClient.dylib	0x00007fff69609fb2 msgtracer_log_with_keys + 126
15  com.apple.opengl              	0x00007fff3d6ad9da 0x7fff3d6a0000 + 55770
16  libdispatch.dylib             	0x00007fff6ca9e6c4 _dispatch_call_block_and_release + 12
17  libdispatch.dylib             	0x00007fff6ca9f658 _dispatch_client_callout + 8
18  libdispatch.dylib             	0x00007fff6caadaa8 _dispatch_root_queue_drain + 663
19  libdispatch.dylib             	0x00007fff6caae097 _dispatch_worker_thread2 + 92
20  libsystem_pthread.dylib       	0x00007fff6ccf99f7 _pthread_wqthread + 220
21  libsystem_pthread.dylib       	0x00007fff6ccf8b77 start_wqthread + 15

Thread 18:
0   libsystem_pthread.dylib       	0x00007fff6ccf8b68 start_wqthread + 0

Thread 19:: Dispatch queue: com.apple.root.user-interactive-qos
0   libsystem_kernel.dylib        	0x00007fff6cc3c062 __psynch_mutexwait + 10
1   libsystem_pthread.dylib       	0x00007fff6ccfa917 _pthread_mutex_firstfit_lock_wait + 83
2   libsystem_pthread.dylib       	0x00007fff6ccf8937 _pthread_mutex_firstfit_lock_slow + 222
3   com.apple.AppKit              	0x00007fff2ffc8d3f __39+[_NSCGSTransaction currentTransaction]_block_invoke_2 + 32
4   com.apple.QuartzCore          	0x00007fff3e670454 CA::Transaction::run_commit_handlers(CATransactionPhase) + 106
5   com.apple.QuartzCore          	0x00007fff3e671a7b CA::Context::commit_transaction(CA::Transaction*, double) + 5299
6   com.apple.QuartzCore          	0x00007fff3e66f304 CA::Transaction::commit() + 644
7   com.apple.AppKit              	0x00007fff2fe86fe4 NSPerformVisuallyAtomicChange + 154
8   com.apple.AppKit              	0x00007fff300d5a6c __42-[NSAnimation(NSInternal) _runInNewThread]_block_invoke + 80
9   libdispatch.dylib             	0x00007fff6ca9e6c4 _dispatch_call_block_and_release + 12
10  libdispatch.dylib             	0x00007fff6ca9f658 _dispatch_client_callout + 8
11  libdispatch.dylib             	0x00007fff6caadaa8 _dispatch_root_queue_drain + 663
12  libdispatch.dylib             	0x00007fff6caae097 _dispatch_worker_thread2 + 92
13  libsystem_pthread.dylib       	0x00007fff6ccf99f7 _pthread_wqthread + 220
14  libsystem_pthread.dylib       	0x00007fff6ccf8b77 start_wqthread + 15

Thread 20:
0   libsystem_pthread.dylib       	0x00007fff6ccf8b68 start_wqthread + 0

Thread 21:: LoadCapture
0   libsystem_kernel.dylib        	0x00007fff6cc3c756 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff6cbbfeea nanosleep + 196
2   org.qt-project.QtCore         	0x0000000107f6e14b 0x107d1d000 + 2429259
3   org.renderdoc.qrenderdoc      	0x0000000101afe2aa ReplayManager::OpenCapture(QString const&, ReplayOptions const&, std::__1::function<void (float)>) + 1226
4   org.renderdoc.qrenderdoc      	0x0000000101b171b4 CaptureContext::LoadCaptureThreaded(QString const&, ReplayOptions const&, QString const&, bool, bool) + 164
5   org.renderdoc.qrenderdoc      	0x0000000101b296cb std::__1::__function::__func<CaptureContext::LoadCapture(rdcstr const&, ReplayOptions const&, rdcstr const&, bool, bool)::$_28, std::__1::allocator<CaptureContext::LoadCapture(rdcstr const&, ReplayOptions const&, rdcstr const&, bool, bool)::$_28>, void ()>::operator()() + 187
6   org.renderdoc.qrenderdoc      	0x0000000101b02aea LambdaThread::process() + 42
7   org.qt-project.QtCore         	0x0000000107f40252 0x107d1d000 + 2241106
8   org.qt-project.QtCore         	0x0000000107d3db68 QThread::started(QThread::QPrivateSignal) + 56
9   org.qt-project.QtCore         	0x0000000107d3e37f 0x107d1d000 + 136063
10  libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
11  libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

Thread 22 Crashed:: ReplayManager
0   com.apple.AppKit              	0x00007fff301d365c -[NSOpenGLContext setView:] + 229
1   librenderdoc.dylib            	0x0000000102e6f651 NSGL_createContext + 209
2   librenderdoc.dylib            	0x0000000102e70f31 CGLPlatform::InitialiseAPI(GLWindowingData&, RDCDriver, bool) + 417
3   librenderdoc.dylib            	0x0000000102ae1e0d CreateReplayDevice(RDCDriver, RDCFile*, ReplayOptions const&, GLPlatform&, IReplayDriver**&) + 381
4   librenderdoc.dylib            	0x0000000102ae28c8 GL_CreateReplayDevice(RDCFile*, ReplayOptions const&, IReplayDriver**) + 328
5   librenderdoc.dylib            	0x00000001036685fe RenderDoc::CreateReplayDriver(RDCFile*, ReplayOptions const&, IReplayDriver**) + 622
6   librenderdoc.dylib            	0x00000001037510bf ReplayController::CreateDevice(RDCFile*, ReplayOptions const&) + 543
7   librenderdoc.dylib            	0x000000010371f48c CaptureFile::OpenCapture(ReplayOptions const&, std::__1::function<void (float)>) + 220
8   org.renderdoc.qrenderdoc      	0x0000000101b02700 ReplayManager::run(int, QString const&, ReplayOptions const&, std::__1::function<void (float)>) + 2144
9   org.renderdoc.qrenderdoc      	0x0000000101b03183 std::__1::__function::__func<ReplayManager::OpenCapture(QString const&, ReplayOptions const&, std::__1::function<void (float)>)::$_0, std::__1::allocator<ReplayManager::OpenCapture(QString const&, ReplayOptions const&, std::__1::function<void (float)>)::$_0>, void ()>::operator()() + 131
10  org.renderdoc.qrenderdoc      	0x0000000101b02aea LambdaThread::process() + 42
11  org.qt-project.QtCore         	0x0000000107f40252 0x107d1d000 + 2241106
12  org.qt-project.QtCore         	0x0000000107d3db68 QThread::started(QThread::QPrivateSignal) + 56
13  org.qt-project.QtCore         	0x0000000107d3e37f 0x107d1d000 + 136063
14  libsystem_pthread.dylib       	0x00007fff6ccfd109 _pthread_start + 148
15  libsystem_pthread.dylib       	0x00007fff6ccf8b8b thread_start + 15

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
