### ISSUE TITLE
build snapshot requires more tools under util/buildscripts/support

### ISSUE THREAD

**Issue by xwang186** [baldurk/renderdoc#2054]
## Description

I want to use tools under util/buildscripts/build.sh --snapshot some_name. However, the LLVM tool setting is not set correct. Automatically it is set to util/buildscripts/support/<llvm_arm32 or llvm_arm64>
According to the util/buildscripts/support/README.md, _llvm_arm32, llvm_arm64 - used for building android with interceptor-lib._
 But for now the folder is empty and I didn't find any resources to replace.

## Steps to reproduce

<Maybe after some settings like set $ANDROID_HOME, prepare alll the dependencies>
util/buildscripts/build.sh --snapshot renderdoc_archive

## Environment

N/A

**Comment by baldurk** [comment]
This is not a bug, you are expected to either place the relevant builds of llvm in those folders or specify paths to them with `--llvm_arm32` and `--llvm_arm64`. See the documentation on compiling for more information.
