### ISSUE TITLE
Crash when creating a swapchain with DXGI_SWAP_EFFECT_FLIP_DISCARD

### ISSUE THREAD

**Issue by baehny** [baldurk/renderdoc#2055]
## Description

Renderdoc crashs when creating a swapchain with DXGI_SWAP_EFFECT_FLIP_DISCARD.

`RDOC 013128: [09:56:33]     dxgi_wrapped.cpp( 515) - Error   - Failed to get swapchain backbuffer 1: HRESULT: DXGI_ERROR_INVALID_CALL`
`Exception thrown at 0x00007FFBB855B589 (renderdoc.dll) in WorkbenchBR.Windows.exe: 0xC0000005: Access violation reading location 0x0000000000000000.`

I'm not quite sure but I think the error came with the update to Renderdoc 1.10 but I dont remember the number of the previous version.

RenderDoc calls IDXGISwapChain::GetBuffer with buffer = 1 but this seems to be invalid for a swapchain that was created with 
`DXGI_SWAP_EFFECT_FLIP_DISCARD` .
MSDN states:
```If the swap chain's swap effect is DXGI_SWAP_EFFECT_DISCARD, this method can only access the first buffer; for this situation, set the index to zero.```

It seems that this is also true for `DXGI_SWAP_EFFECT_FLIP_DISCARD`.

**Update:** 
The fix described below is in a pull request: https://github.com/baldurk/renderdoc/pull/2056
I tested it and it seems to work but I'm still not sure if other changes are necessary or if this change has some side effect.

Possible fix:
I have found a possible solution for the crash but I did not test it and I don't know if other changes are necessary.
In dxgi_wrapped.cpp: `WrappedIDXGISwapChain4::WrapBuffersAfterResize()` the DXGI_SWAP_EFFECT_FLIP_DISCARD case is not handled so this could be added:

```
void WrappedIDXGISwapChain4::WrapBuffersAfterResize()
{
//...
  if(desc.SwapEffect == DXGI_SWAP_EFFECT_DISCARD)
    bufCount = 1;
//NEW:
if(desc.SwapEffect == DXGI_SWAP_EFFECT_FLIP_DISCARD)
    bufCount = 1;
///...
}
```

## Steps to reproduce

The following code is the smallest C# 9 program to reproduce the error.
Sorry that I do not provide a C++ example but the swapchain construction should be very similar to C++ and show what parameters were used.
```
using System;
using System.Windows.Forms;
using SharpDX.DXGI;

// create simple windows forms window
Form form = new Form();
form.Show();

// create Direct3D11 device
var device = new SharpDX.Direct3D11.Device(SharpDX.Direct3D.DriverType.Hardware);

// create swapchain with DXGI_SWAP_EFFECT_FLIP_DISCARD
SharpDX.DXGI.SwapChainDescription swapChainDesc;
swapChainDesc.BufferCount = 2; //The buffer count must be at least 2 for flip model
swapChainDesc.Flags = SwapChainFlags.None;
swapChainDesc.IsWindowed = true;
swapChainDesc.OutputHandle = form.Handle;
swapChainDesc.SampleDescription = new SampleDescription(1, 0);
swapChainDesc.ModeDescription = new ModeDescription(
    form.ClientSize.Width,
    form.ClientSize.Height,
    new Rational(0, 1),
    Format.R8G8B8A8_UNorm);
swapChainDesc.Usage = Usage.RenderTargetOutput;

swapChainDesc.SwapEffect = SwapEffect.FlipDiscard;

var dxgiDevice = device.QueryInterface<SharpDX.DXGI.Device1>();
var dxgiAdapter = dxgiDevice.GetParent<SharpDX.DXGI.Adapter>();
var factory = dxgiAdapter.GetParent<SharpDX.DXGI.Factory>();

var DXGISwapChain = new SharpDX.DXGI.SwapChain(factory, device, swapChainDesc);
// crashs here: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
// more detailed from another program:
// Exception thrown at 0x00007FFBB855B589 (renderdoc.dll) in WorkbenchBR.Windows.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

while(form.Visible)
{
    DXGISwapChain.Present(0, PresentFlags.None);
    Application.DoEvents();
}
```

## Environment

* RenderDoc version: 1.10
* Operating System: Windows 10 2004 x64 
* Graphics API: Direct3D 11
* Hardware: GTX 1070
* Driver: 452.06

**Comment by baldurk** [comment]
Someone else ran into this yesterday as well and we needed some clarification from MS about exactly what is legal here since the docs are lacking as usual. That commit should fix it by only querying for buffer 0 in D3D11 for `DXGI_SWAP_EFFECT_FLIP_DISCARD`.

**Comment by Devaniti** [comment]
Had same crash on creation of DXGI_SWAP_EFFECT_FLIP_DISCARD swapchain
1.10 is broken, nightly build (https://github.com/baldurk/renderdoc/commit/2ea17af719bfefb96f968175604e9115b90fd446) is ok
