### ISSUE TITLE
Some textures (GL_INTENSITY_EXT format) not captured properly

### ISSUE THREAD

**Issue by OndrejSpanel** [baldurk/renderdoc#2057]
## Description

I use RenderDoc to debug rendering of a Java GUI toolkit. Everything works fine, the only issue is the font textures are broken when captured, their content is garbled and instead of containing the font data only some nonsense is there. When checking the texture in the resource inspector I can see the texture initialization data as captured is not good. Following fields do not seem to match well together - the `SubresourceContents` does not match `width` and `height`:

```text
Internal: Initial Contents                              
  id                         Texture 120                
  Type                       Texture                    
  TextureState               TextureStateInitialData()  
    internalformat           GL_INTENSITY_EXT           
    isView                   False                      
    width                    256                        
    height                   256                        
    depth                    1                          
    samples                  0                          
    dim                      2                          
    type                     GL_TEXTURE_2D              
    mips                     1                          
    baseLevel                0                          
    maxAniso                 1.00                       
  SubresourceContents        (1 bytes)
```

It is very likely by the texture being of format GL_INTENSITY. When I have changed the font renderer to use GL_RED instead, the issue disappeared.

## Steps to reproduce

I have attached the capture demonstrating the issue. The problematic texture is 120.

[gl-swing.zip](https://github.com/baldurk/renderdoc/files/5261971/gl-swing.zip)

## Environment

* RenderDoc version: XXX
* Operating System: Win10 x64 
* Graphics API: OpenGL 3.1

The application is a Java application using JOGL. I use RenderDoc a lot to debug OpenGL Java applications and it has always worked fine for me - well done. This is the first situation I am experiencing any issues.

**Comment by baldurk** [comment]
RenderDoc does not support deprecated OpenGL features, it only supports the OpenGL core profile. GL_INTENSITY is deprecated functionality and was removed from the core profile.

**Comment by i-make-robots** [comment]
@OndrejSpanel can you share your method for attaching renderdoc to a jogl program?  I'm using jogamp and this is my first try with renderdoc.  It's asking for an exe and I've only got my jar file...

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
