### ISSUE TITLE
VkAttachmentDescription initialLayout VK_IMAGE_LAYOUT_UNDEFINED inconsistency

### ISSUE THREAD

**Issue by kudaba** [baldurk/renderdoc#2058]
## Description

When trying to debug why my render target was being unexpectedly cleared, even with VK_ATTACHMENT_LOAD_OP_LOAD, I noticed render doc was showing different results between the capture and the final swap chain present. I ended up fixing my issue when stumbling on this post: https://stackoverflow.com/questions/48654621/issue-with-vkrenderpass-load-operation-for-skybox-rendering

This makes me think that renderdoc is not respecting that a render pass with layout undefined will clear its contents no matter what the load op is.

## Steps to reproduce

1. Create a render pass with a single color attachment that has
initialLayout = VK_IMAGE_LAYOUT_UNDEFINED
loadOp = VK_ATTACHMENT_LOAD_OP_LOAD

2. Render to it, use the same render pass to render to a second target, then switch back to the original render target.

The application result (on my GeForce GTX 1060) is that the first texture is cleared but rederdoc shows that it's properly rendered to.

[capture.zip](https://github.com/baldurk/renderdoc/files/5263597/capture.zip)

This is the application image that was captured and what the application actually looked like for that capture:
<img src="https://user-images.githubusercontent.com/22896740/93929109-3329dc80-fcd0-11ea-84c7-0435c6204981.png" width="300" height="250">

This is what renderdoc shows as a final result:
<img src="https://user-images.githubusercontent.com/22896740/93929837-530dd000-fcd1-11ea-9325-1ea2ca50e7a4.png" width="400" height="250">

## Environment

* RenderDoc version:  1.10
* Operating System: Windows 10 (2004)
* Graphics API: Vulkan
* GeForce GTX 1060: 27.21.14.5167

**Comment by baldurk** [comment]
Looks like this is a case that was missed when adding the discard patterns in v1.9, it should fill the contents with an undefined pattern each time but that got missed since it's not an explicit pipeline barrier from `UNDEFINED` _or_ a `DONT_CARE` load op.

I'll look into this but it won't be until later next week as I'm off work just now.

**Comment by baldurk** [comment]
That commit should now properly fill attachments with a `UNDEFINED` pattern when loading from undefined.
