### ISSUE TITLE
[REGRESSION] Impossible playback in v1.10 with a capture in Vulkan

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#2060]
## Description

Running my Ogre 2.3 program Sample_Tutorial_DynamicCubemap causes RenderDoc 1.10 to glitch entirely on playback, sometimes leading to X11 crashing (i.e. Linux-half-equivalent of TDR). While RenderDoc 1.9 runs fine.

A run in RenderDoc 1.9 indicates that my sample is wrong, as it seems to discard important information:

![1 9](https://user-images.githubusercontent.com/3395130/94047795-faaa0180-fda8-11ea-83fa-e0507eb060b8.jpg)

However a run in RenderDoc 1.10 the entire RenderDoc panels are glitched. Not just the window. But everything. **Even the Geometry panels in the mesh viewer** are completely glitched (hard to screenshot without TDR'ing the system)

![1 10](https://user-images.githubusercontent.com/3395130/94047979-347b0800-fda9-11ea-9dea-3ceb6470f6b4.jpg)

## Steps to reproduce

Windows/Linux steps:

1. Download [Quick Build Scripts](https://bintray.com/darksylinc/ogre-next/download_file?file_path=build_ogre_scripts-master.7z)
2. Execute any of the compile scripts best suited to your system and compiler
3. Navigate to ogre-next/build/Release (or Debug) and execute and capture Sample_Tutorial_DynamicCubemap

Note: This bug was detected on Linux. It is unknown if it is present on Windows.

## Environment

* RenderDoc version: 1.10
* Operating System: Xubuntu 18.04 LTS
* Graphics API: Vulkan

```
System:    Host: matias-ubuntu Kernel: 5.4.0-47-generic x86_64
           bits: 64 gcc: 7.5.0
           Desktop: Xfce 4.12.3 (Gtk 2.24.31) dm: lightdm
           Distro: Ubuntu 18.04.5 LTS
CPU:       Quad core Intel Core i7-7700 (-MT-MCP-) 
           arch: Skylake rev.9 cache: 8192 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 28800
           clock speeds: min/max: 800/4200 MHz 1: 799 MHz 2: 1823 MHz
           3: 3120 MHz 4: 2903 MHz 5: 1751 MHz 6: 2419 MHz 7: 2585 MHz
           8: 2197 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Baffin [Radeon RX 550 640SP / RX 560/560X]
           bus-ID: 01:00.0 chip-ID: 1002:67ff
           Display Server: x11 (X.Org 1.20.8 )
           drivers: amdgpu (unloaded: radeon,intel)
           Resolution: 1920x1080@60.00hz
           OpenGL: renderer: Radeon RX 560 Series (POLARIS11, DRM 3.35.0, 5.4.0-47-generic, LLVM 10.0.1)
           version: 4.6 Mesa 20.1.3 (git-663fa46287) Direct Render: Yes
```

**Comment by baldurk** [comment]
I'll look into this but it won't be until later next week as I'm off work just now.

In the meantime I'd recommend using the vulkan validation layers to make sure you don't have any errors, as RenderDoc does not handle invalid API use. If you have extra time it would also be helpful to bisect where the problem started, and/or test on a different driver as well. If you can share the diagnostic log that might also give some indication of what's wrong.

**Comment by darksylinc** [comment]
I'm running a bisect as we speak

**Comment by darksylinc** [comment]
BISECTED:

211d8532fa6555e146f745f83744b34ae0b96986 is the first bad commit
commit 211d8532fa6555e146f745f83744b34ae0b96986
Author: baldurk <baldurk@baldurk.org>
Date:   Tue Aug 4 14:24:06 2020 +0100

    Use GPU readbacks for mapped memory in PCI-E window
    
    * On discrete GPUs that expose PCI-E window memory (device local but still host
      visible) this memory is extremely slow to read from on the CPU. It's
      significantly faster to issue a command buffer to get the GPU to copy into CPU
      memory and wait on that command buffer to finish, then read from the copy.
    * We do this for detected coherent writes in queue submit, issuing the copy on
      the queue being submitted to. We do *not* do this for memory unmaps or
      explicit application flushes. This does mean those will remain slow, however
      with no queue to use the synchronisation challenges become more significant
      and most applications leave memory persistently mapped.

:040000 040000 8c6174364b74d220d3158d36f7989f01de3be062 df367e553eebe8b4420f44df94c0fdd636575a98 M	renderdoc

Log:

```
git bisect start
# good: [22dbb188ceac48479764540ee0df3e4f28b6f0b3] Document the new custom shader directories setting
git bisect good 22dbb188ceac48479764540ee0df3e4f28b6f0b3
# bad: [381fdbe06bc413fb95faaf4ff9461b1e89be7406] Fix missing format argument in error message
git bisect bad 381fdbe06bc413fb95faaf4ff9461b1e89be7406
# bad: [6d810f2ca1a8afbdf83b1708c3f1755c2733230b] Fix naming getting muddled for indirect draws
git bisect bad 6d810f2ca1a8afbdf83b1708c3f1755c2733230b
# bad: [73248c848819cc4672ed852de39825dd4a8813bf] Include RenderDoc logfile after test runs
git bisect bad 73248c848819cc4672ed852de39825dd4a8813bf
# good: [7b1995a7ba27f8b11112a7a49969a19606ba1092] Properly handle offsets on memory maps in vulkan
git bisect good 7b1995a7ba27f8b11112a7a49969a19606ba1092
# bad: [152170dc58b1beec29e2bc522185359354c6a48a] Fix reference data not being updated at right place after map write
git bisect bad 152170dc58b1beec29e2bc522185359354c6a48a
# bad: [6af18a56228c8c5c75ef9a3bdbd766840fbf74dd] Patch another form of handle string in vulkan debug messages
git bisect bad 6af18a56228c8c5c75ef9a3bdbd766840fbf74dd
# bad: [9547b049e3b6913fd41b2f205f68d28fcac402ff] Update version number on in-application API documentation
git bisect bad 9547b049e3b6913fd41b2f205f68d28fcac402ff
# bad: [31b7c35bae6ee5aefaa539feefb4ac172dde77ff] Fix logfiles not being deleted if captured application is the last user
git bisect bad 31b7c35bae6ee5aefaa539feefb4ac172dde77ff
# bad: [211d8532fa6555e146f745f83744b34ae0b96986] Use GPU readbacks for mapped memory in PCI-E window
git bisect bad 211d8532fa6555e146f745f83744b34ae0b96986
# first bad commit: [211d8532fa6555e146f745f83744b34ae0b96986] Use GPU readbacks for mapped memory in PCI-E window

```

- [x] **Validation layers don't report any errors**

**Comment by darksylinc** [comment]
Diagnostic Log on bad 1.10:

[DiagLog.log](https://github.com/baldurk/renderdoc/files/5270368/DiagLog.log)

Diagnostic Log on good 1.9:

[DigaLog1.9.log](https://github.com/baldurk/renderdoc/files/5270396/DigaLog1.9.log)

**Comment by baldurk** [comment]
Your system only has 3GB of system RAM? It looks like possibly it's just running out of memory allocating the host-side readback memory, and I'm not properly handling that case. It only allocates enough for the PCI window heap which is normally 256MB and I didn't expect that to be a problem on systems with discrete CPUs (it's disabled on integrated GPUs), but if that's 8% of your total system memory it might genuinely be running out of memory by allocating that on top of everything else.

If that's the case the solution is probably just to add error handling to that case. Normally I consider OOM to be a fatal error in any situation but in this case its maybe survivable just with a high performance cost - though you are probably likely to run into OOM if you run any more resource intensive program.

As a possible workaround in the meantime you can go into the config editor (in the UI Settings window &rarr; Core &rarr; Config Editor) and find the Vulkan &rarr; GPUReadbackDeviceLocal setting. Turn that off and try to see if that helps.

**Comment by darksylinc** [comment]
- I have 2GB of GPU VRAM
 - I have 32GB of regular RAM
 - Disabling GPUReadbackDeviceLocal did not fix the error
 - Fixing the "store don't care" error on my side did not fix the capture/replay problem either

**Comment by darksylinc** [comment]
> It only allocates enough for the PCI window heap which is normally 256MB and I didn't expect that to be a problem on systems with discrete CPUs

Unrelated to this issue, I shall comment that 256MB is system-wide (due to GART legacy issues) and is shared with kernel driver. Allocating 256MB of device-local, host-visible memory is usually a bad thing to do(tm)

**Comment by baldurk** [comment]
I realise that it's system-wide, I'm certainly not allocating 256MB out of the PCI window heap. I'm allocating 256MB of host memory *for* that heap as shadow memory for readbacks. Then instead of having the CPU do a slow direct readback from any mapped memory in that device-local host-visible memory, the GPU can issue a copy from that memory to plain host RAM and then the CPU can read that for comparison. I was only going by a guess that this allocation was the cause of the out of memory errors, maybe it's unrelated.

Strangely the log seems to show that the driver is only reporting 3GB available in the host heaps. This is true even on v1.9:

```
RDOC 027481: [18:44:11]        vk_memory.cpp(  62) - Log     -   Memory type 0: VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT in heap 0 (VK_MEMORY_HEAP_DEVICE_LOCAL_BIT | VK_MEMORY_HEAP_MULTI_INSTANCE_BIT) (1.8 GB) [GPULocal]
RDOC 027481: [18:44:11]        vk_memory.cpp(  62) - Log     -   Memory type 1: VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT in heap 1 (VkMemoryHeapFlagBits(0)) (3.0 GB) [upload]
RDOC 027481: [18:44:11]        vk_memory.cpp(  62) - Log     -   Memory type 2: VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT | VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT in heap 2 (VK_MEMORY_HEAP_DEVICE_LOCAL_BIT | VK_MEMORY_HEAP_MULTI_INSTANCE_BIT) (0.3 GB) []
RDOC 027481: [18:44:11]        vk_memory.cpp(  62) - Log     -   Memory type 3: VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT | VK_MEMORY_PROPERTY_HOST_CACHED_BIT in heap 1 (VkMemoryHeapFlagBits(0)) (3.0 GB) [readback]
```

Note the 3.0 GB for types 1 and 3.

Can you upload the log from a run with `GPUReadbackDeviceLocal` disabled?

**Comment by darksylinc** [comment]
> Strangely the log seems to show that the driver is only reporting 3GB available in the host heaps. This is true even on v1.9:

That is correct. The driver reports 3.something of GB. It's not a RenderDoc bug.

[DiagLog.1.10.GPUReadBackDisabled.log](https://github.com/baldurk/renderdoc/files/5272084/DiagLog.1.10.GPUReadBackDisabled.log)

Btw I can't help notice `Failed to allocate descriptor set ResourceId::1059 from pool ResourceId::678 on replay. Assuming pool was reset and re-used mid-capture, so overflowing.`

I suspect RenderDoc captured my program incorrectly and during replay tries to allocate an ever-growing descriptor pool until it goes OoM.

**Comment by darksylinc** [comment]
I just noticed I've been using amdvlk driver. On RADV RenderDoc just crashes with msg (GPUReadBack disabled):

```
amdgpu: Not enough memory for command submission.
vk: error: failed to submit CS

Aborted (core dumped)
```

[RenderDoc_2020.09.23_18.55.35.log](https://github.com/baldurk/renderdoc/files/5272119/RenderDoc_2020.09.23_18.55.35.log)

**Comment by baldurk** [comment]
The descriptor set message is not in itself an indicator of a problem. On replay RenderDoc can allocate more descriptor sets at once than fit in a pool, given that the application can free and allocate descriptors within a capture and on replay all descriptors at all points are allocated.

I'm not sure what the problem is then, it still seems to point to an OOM issue but I'm not sure why disabling that option didn't fix it. As I mentioned I will look at it next week when I'm back at work, since this doesn't seem to be an obvious problem.

**Comment by darksylinc** [comment]
I'm now testing it on WIndows 10, AMD Radeon HD 7770 1GB VRAM (differeng GPU).

It works, however the first time I did it, it caused visual corruption of textures on display right after the capture (they were fine before the capture). Couldn't repro that again (GPU Readback ENABLED).

[WindowsRadeonHD7770Log.log](https://github.com/baldurk/renderdoc/files/5272145/WindowsRadeonHD7770Log.log)

**Comment by darksylinc** [comment]
I just tried on Windows 10 (same system as Linux). It works normally.

On Windows, the driver exposes a lot more RAM. It may like you say be a true OoM condition, but it's weird the new code consumes more RAM.

Attaching the log (GPU Readback ENABLED).

[RenderDoc1.10.Windows10.log](https://github.com/baldurk/renderdoc/files/5272909/RenderDoc1.10.Windows10.log)

There is no rush for this bug. Enjoy your time off.

**Comment by darksylinc** [comment]
Welp!

You were right. There may be more to it (i.e. a RenderDoc bug using way more memory than it should), but increasing the exposed memory on Linux to 8GB fixed it.

If anyone is curious, exposed memory can be increased by adding `amdgpu.gttsize=8192` to boot params.

**Comment by darksylinc** [comment]
If you're interested in debugging memory usage pre-211d853 and post-211d853 (i.e. to see if there is something fishy in the amount used by RenderDoc) and now that we've determined Windows didn't crash because it exposed more RAM,

here is a [prebuilt Windows build](http://www.mediafire.com/file/0iw60srb0kkbrhr/ogre-sdk-v2.3.0-unstable-vc19-x64.7z/file)

**Comment by baldurk** [comment]
I believe this is purely an OOM issue. I wasn't able to repro even by deliberately reducing the CPU heap size down, but I did notice that I messed up with the allocation of the readback buffer. In the original commit you bisected to it was always allocated at startup when capturing, and I changed it shortly after to be lazily allocated only when needed. So I *thought* that disabling the `GPUReadBack` option should nop out any memory impact. However I messed up and actually it was still allocating at startup and then allocating again lazily, meaning more memory overhead instead of less and disabling the option only removed one of those allocations.

I've fixed that so it now should truly only allocate when necessary (desktop discrete cards with host-visible device-local memory) and when the option is enabled. It also only allocates enough for whichever memory object it needs to read back, so that will further reduce the memory overhead there if it's only reading back small amounts of memory.

The sample itself has a fair amount of memory impact when running under renderdoc - it creates two memory allocations that are both 384MB which renderdoc shadows on capture, and other assorted resources add up to about 500MB of memory. With the extra 256MB there I could see it pushing it over the limit, so even with this fix in place you may still be bumping up against OOM very soon. The default behaviour of amdgpu to only expose 3GB in your case is not ideal but I assume there are good reasons for it.

**Comment by darksylinc** [comment]
So in the end this was a combination of things which lead to a bit of code allocating a bit more than what's necessary; and it was only detected because my app was already almost over the edge. Talk about a series of unfortunate events!

Indeed, I haven't yet monitored our memory consumption. It's quite possible we're over-allocating way more than we need.

Thanks for looking at it!

> The default behaviour of amdgpu to only expose 3GB in your case is not ideal but I assume there are good reasons for it.

I suspect 3GB was 'good enough' for a 2GB model back when the OpenGL would swap things in and out; and now with Vulkan apps popping out eating memory for breakfast the algorithm that auto-calculates exposed memory will need revisiting.

On Windows 10, 16GB are exposed.
