### ISSUE TITLE
qrenderdoc forgets the UI layout after it's closed

### ISSUE THREAD

**Issue by liquidev** [baldurk/renderdoc#2064]
## Description

Each time I start up qrenderdoc, this happens:
![image](https://user-images.githubusercontent.com/16415678/94414764-03218400-017d-11eb-9fb9-4e254be792f8.png)

## Steps to reproduce

Honestly, I have no clue. It's been like this for a few months now, and it's driving me nuts whenever I go to debug my OpenGL applications. All I really know is that resetting the config directory reverts the layout back to normal, but I don't want to do that each time I start up qrenderdoc because simply repositioning the panes is faster and easier. Next time I start up the app, the layout's broken all over again.

If you have any clues about what might be causing this, feel free to ask for extra details that might be needed for debugging.

## Environment

* RenderDoc version: 1.10
* Operating System: Artix Linux 5.4.62-1-lts
* Qt version: 5.15.0

**Comment by baldurk** [comment]
Does this definitely still happen for you on v1.10? i.e. if you reset the config when running on v1.10 does it still not save correctly? There was a problem I found where a new Qt version introduced a backwards-compatibility breaking change to its JSON encode/decode, which I fixed between v1.9 and v1.10. Before then it would break in exactly the way you are showing here.

Can you share the diagnostic log from loading the broken layout config, as well as the DefaultLayout.config itself from the qrenderdoc config directory?

**Comment by liquidev** [comment]
Hm, seems like it's fixed in renderdoc 1.10 after removing all configs. Maybe the broken config was carried over from 1.9, as I haven't upgraded renderdoc via the package manager yet (I'm doing that right now, actually).

Thanks for the quick response!
