### ISSUE TITLE
PixelShader debug: Remove line numbers

### ISSUE THREAD

**Issue by usuarionuevor** [baldurk/renderdoc#2069]
## Description

Add option to remove/hide line numers in code, or at least, when selecting text ignore them?

## Environment

* RenderDoc version: 1.10
* Operating System: W10 x64
* Graphics API: D3D11

![remove line number](https://user-images.githubusercontent.com/35457371/95440845-b21e4680-0959-11eb-897f-4e4dbe4f19de.png)

**Comment by baldurk** [comment]
As outlined in the [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues-Features.md) can you please explain what your ultimate end goal is and why you need this?

**Comment by usuarionuevor** [comment]
not necessary remove but at least making them dummy like the ones on the left, to be more friendly to work with the code, because is too annoying removing them manually or making script to do it after you copy-paste the code.

**Comment by baldurk** [comment]
I don't consider this change worthwhile. Copying the assembly text I don't think is a particularly common workflow as I'm not sure what you would do with it from there, and the instruction numbers are easy to remove with regexp replacement or column select in any text editor. You could also disassemble the bytecode yourself without them using fxc.
