### ISSUE TITLE
Device extension VK_KHR_ray_tracing not supported by selected physical device (RTX 3080).

### ISSUE THREAD

**Issue by jims1990** [baldurk/renderdoc#2070]
## Description

RenderDoc can't launch ray-tracing code saying that VK_KHR_ray_tracing is not suported on RTX3080. (outside RenderDoc code work perfectly):

Screen of log:

![image](https://user-images.githubusercontent.com/10166312/95529816-ffc29f80-09a9-11eb-886b-b8d8833546b3.png)

## Steps to reproduce

Launch any ray-tracing code using VK_KHR_ray_tracing. 
Tested on ray-tracing samples:
https://github.com/SaschaWillems/Vulkan
and 
https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR

## Environment

* RenderDoc version: 1.11 2020-10-7 (Win64)
* Operating System: Win10
* Graphics API: 
Driver Version: 456.62
Vulkan Instance Version: 1.2.148

**Comment by baldurk** [comment]
This isn't a bug, that extension is not supported. RenderDoc removes unsupported extensions from the list of those supported, it's up to the application to properly enumerate the available extensions and handle that.

**Comment by jims1990** [comment]
Thank you for your replay. I'm not sure if I understood you correctly: The extension is not supported by RenderDoc or by device (gpu)? I mean, it is supported by graphic card, vulkaninfo list it as "VK_KHR_ray_tracing : extension revision 8". 
I would think that ray-tracing samples (based on VK_KHR_ray_tracing would not work without extension.
Is there something I am missing here? Why wouldn't it be supported?

Code where extension is initialized: 
![image](https://user-images.githubusercontent.com/10166312/95600786-9e89e300-0a20-11eb-90fe-52eef92753b0.png)

**Comment by baldurk** [comment]
The extension is not supported by RenderDoc. It's up to the application code to enumerate the available extensions if they want to have any graceful error checking. Otherwise `vkCreateDevice` will fail with `VK_ERROR_EXTENSION_NOT_PRESENT` when RenderDoc refuses to create a device with an unsupported extension.

**Comment by dor666** [comment]
Side question: Is there any plan for supporting VK_KHR_ray_tracing in future?

**Comment by baldurk** [comment]
There's no plan currently, and I don't expect to start looking any time soon. I hope that at some point in the future it will be supported, but realistically right now the priority of ray tracing is simply not high enough for the huge amount of work necessary to properly support it.

**Comment by crocdialer** [comment]
sad to hear that @baldurk 
while I can fully understand your reasoning to not bother with that (at the moment), it makes RenderDoc practically unusable for projects, which started to integrate `VK_KHR_ray_tracing` and contain (optional) code-paths using it.

meaning, I would already be very happy if I could just continue to use RenderDoc to debug rasterization-pipelines, blending out or blackboxing anything using VK_KHR_ray_tracing.

sincerely,
Fabian
