### ISSUE TITLE
Launching Apple Maps on macOS fails with lsof unable to parse output (n*:*)

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#2071]
## Description

Tracing Apple Maps using renderdoc is not possible. renderdoc fails to inject into the process.

I'm not sure what API Apple Maps is using; but eitherway, I feel that the error message should be more informative + the underlying issue should be resolved.

## Steps to reproduce

1. Start qrenderdoc.
2. Set "Executable Path" to `/System/Applications/Maps.app`.
3. Press Launch.
4. You'll get an error about "Error launching [...]; RenderDoc injection failed. Check the diagnostic log [...]".
5. Log reports:
    - Failed to parse output from lsof
    - p2589
    - f4
    - n*:*

The code for that is here:

https://github.com/baldurk/renderdoc/blob/89af50a76c1cf98f800a6ff8ece5c31f3ff5504c/renderdoc/os/posix/apple/apple_process.cpp#L84-L89

## Environment

* RenderDoc version: 89af50a76c1cf98f800a6ff8ece5c31f3ff5504c
* Operating System: macOS 10.15.7
* Graphics API: (Unknown)

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
