### ISSUE TITLE
Firefox tabs with WebGL crash when launched through RenderDoc on macOS

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#2072]
## Description

On macOS, trying to trace a WebGL tab in Firefox will lead to that tab crashing.

## Steps to reproduce

1. Open qrenderdoc.
2. Set "Executable Path" to `/Applications/Firefox.app`.
3. Set "Command-line Arguments" to `--no-remote --new-instance -p robot` (create a profile named "robot" for Firefox in "Profile Manager").
4. Press Launch.
5. Open a website which uses WebGL like https://www.google.com/maps/?force=webgl or Shadertoy.
6. After about a second, Firefox will report "Gah. Your tab just crashed".

## Environment

* RenderDoc version: 89af50a76c1cf98f800a6ff8ece5c31f3ff5504c
* Operating System: macOS 10.15.7
* Graphics API: WebGL / (Unknown backend in Firefox)
* Firefox: 81.0.1 (64-bit)

**Comment by baldurk** [comment]
OS X is not a supported platform. Fixes are welcome but otherwise no support or help will be provided.
