### ISSUE TITLE
Cannot launch Unreal Engine 4.25 with RenderDoc v1.10

### ISSUE THREAD

**Issue by Songsong97** [baldurk/renderdoc#2078]
## Description
I am running a project with Unreal Engine 4.25.1 and it crashes when using RenderDoc to launch. It might be related to D3D11 and only happens in version 1.10 so probably the same issue as #2075 . This happens both in a standalone RenderDoc or launching the engine editor directly with RenderDoc Plugin for Unreal enabled.

## Steps to reproduce

Launch the Unreal Engine 4.25.1 in RenderDoc and open a project. Then before the project is loaded the crash will happen.
```
Exception thrown at 0x00007FFB1DDDB589 (renderdoc.dll) in UE4Editor.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```

The call stack is:

```
renderdoc.dll!WrappedID3D11Device::NewSwapchainBuffer(IUnknown * backbuffer) Line 1436	C++
renderdoc.dll!WrappedIDXGISwapChain4::WrapBuffersAfterResize() Line 373	C++
renderdoc.dll!WrappedIDXGISwapChain4::WrappedIDXGISwapChain4(IDXGISwapChain * real, HWND__ * w, ID3DDevice * device) Line 250	C++
renderdoc.dll!WrappedIDXGIFactory::CreateSwapChainForHwnd(IUnknown * pDevice, HWND__ * hWnd, const DXGI_SWAP_CHAIN_DESC1 * pDesc, const DXGI_SWAP_CHAIN_FULLSCREEN_DESC * pFullscreenDesc, IDXGIOutput * pRestrictToOutput, IDXGISwapChain1 * * ppSwapChain) Line 1335	C++
```

## Environment

* RenderDoc version: v1.10
* Operating System: Windows 10
* Graphics API: D3D11
* GPU: Geforce RTX 2080 super

**Comment by baldurk** [comment]
This is not the same as #2075 but it is the same as #2055.
