### ISSUE TITLE
Log files are automatically deleted now

### ISSUE THREAD

**Issue by alexv1n** [baldurk/renderdoc#2080]
## Description

As of change 31b7c35bae6ee5aefaa539feefb4ac172dde77ff, it doesn't seem to be possible to retain logs from renderdoccmd. We used this in automated tests trying to replay a bunch of .rdc files as part of a regression test. We'd call `renderdoccmd replay <trace.rdc>` and set `RENDERDOC_DEBUG_LOG_FILE=/path/to/log.txt` and would store the log.txt file produced in test artifacts, so when replay fails, we'd know exactly what happened on RenderDoc side. Now the file is deleted and we no longer have this information to go by. What is the recommended way of collecting replay logs?

## Steps to reproduce

```
RENDERDOC_DEBUG_LOG_FILE=/path/to/log.txt renderdoccmd replay sample.rdc
```

The produced log file is deleted when renderdoccmd quits and it is not possible to get debug log messages that might point to the reason why replay failed (like specific driver compatibility issues)

## Environment

* RenderDoc version: 11719a2588544a12947f809a384c4cfe57a1e03e
* Operating System: Linux
* Graphics API: Vulkan

**Comment by baldurk** [comment]
`renderdoccmd` and `RENDERDOC_DEBUG_LOG_FILE` are internal implementation details and are not user facing, you should not be referencing these directly yourself. What you're describing is not a bug, you were relying on broken behaviour which has now been fixed.

If you use the renderdoc replay API e.g. with a python script you can obtain the log path with [`renderdoc.GetLogFile()`](https://renderdoc.org/docs/python_api/renderdoc/funcs.html#renderdoc.GetLogFile) and read the file contents to store them, as happens in the [functional tests](https://github.com/baldurk/renderdoc/blob/v1.x/util/test/rdtest/runner.py#L365-L368).
