### ISSUE TITLE
UI freeze on Linux/vulkan replay

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#2083]
## Description

Capturing and replaying a relatively simple workload freezes the UI and makes it unusable.

## Steps to reproduce

- download and unpack [wgpu-trace.zip](https://github.com/baldurk/renderdoc/files/5452115/wgpu-trace.zip)
- download and unpack [wgpu.zip](https://github.com/baldurk/renderdoc/files/5452109/wgpu.zip)
- `cd wgpu/player`
- `cargo build --features renderdoc` - this may take a bit of time, requires Cargo + Rust. The artifact we are interested in is `../target/debug/play`, and that's what we'll be running from renderdoc, passing the `wgpu-trace` path as a parameter.
- launch the app from Renderdoc using the following settings:
![renderdoc-capture-settings](https://user-images.githubusercontent.com/107301/97442344-21a3a800-1900-11eb-9019-5e8f4af40786.png)

You'd need to change the paths to `wgpu` and `wgpu-trace`. It will finish quickly and produce a capture automatically.
Navigating to the draw call (EID 43, for example, and then to EID 9) would show the progress bar at the bottom, which never stops and freezes the UI:
![renderdoc-progress-bar](https://user-images.githubusercontent.com/107301/97442673-7cd59a80-1900-11eb-961f-7184e4a3b35c.png)

The application stops responding and can only be killed after that.

## Environment

* RenderDoc version: 1.10
* Operating System: Solus linux
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Can you share the capture itself that hangs? I can more easily look into that since it means I won't have to figure out how to set up cargo + rust. If not that's fine it might just be a little longer before I can repro this.

**Comment by kvark** [comment]
Here we go: [renderdoc-bug-capture.zip](https://github.com/baldurk/renderdoc/files/5452211/renderdoc-bug-capture.zip)

**Comment by baldurk** [comment]
This seems like it may be the same as #1863 . I can replay the capture fine with latest mesa on my hardware, but looking at it I can see that your application still maps memory behind GPU render targets and there was a bug that meant renderdoc was still replaying mapped memory updates into that.

Please try again with that commit, if it still doesn't work let me know and I can investigate again. If it does still happen I'd particularly be interested to know if it still happens on your nvidia card, or on intel if you don't map memory with render targets bound.

**Comment by kvark** [comment]
I confirm your fix works. Thanks for the quick turnaround (and unblocking me)! 🥇
