### ISSUE TITLE
Sky光·遇 replay single frame crash 

### ISSUE THREAD

**Issue by luopan007** [baldurk/renderdoc#2087]
##Description

I capture a frame on a Mate 40 Pro mobile(android), the graphics api is **Vulkan**,  I double click to open the RDC file and replay it。The operation was failed。Here is the log:
``` xml
ADRD 024057: [08:46:04] vk_resource_funcs.cpp( 249) - Error   - Trying to bind Image ResourceId::1633 to memory ResourceId::1634 which is type 0, but at offset 0x0 the reported size of 0x408000 won't fit the 0x400000 bytes of memory.
ADRD 024057: [08:46:04] vk_resource_funcs.cpp( 249) - Error   - This is most likely caused by incompatible hardware or drivers between capture and replay, causing a change in memory requirements.
```

### The question code:
``` cpp
  // verify size
  if(mrq.size > memInfo.size - memoryOffset)
  {
    RDCERR(
        "Trying to bind %s to memory %s which is type %u, "
        "but at offset 0x%llx the reported size of 0x%llx won't fit the 0x%llx bytes of memory.\n"
        "This is most likely caused by incompatible hardware or drivers between capture and "
        "replay, causing a change in memory requirements.",
        resourceName, ToStr(memOrigId).c_str(), memInfo.memoryTypeIndex, memoryOffset, mrq.size,
        memInfo.size);
    m_FailedReplayStatus = ReplayStatus::APIHardwareUnsupported;
    return false;
  }
```
### what Doubt is?
The image real requirment memory size is **bigger** than the trace file record image size.

### We can see the function: Serialise_vkBindImageMemory
``` cpp
template <typename SerialiserType>
bool WrappedVulkan::Serialise_vkBindImageMemory(SerialiserType &ser, VkDevice device, VkImage image,
                                                VkDeviceMemory memory, VkDeviceSize memoryOffset)
{
  SERIALISE_ELEMENT(device);
  SERIALISE_ELEMENT(image);
  SERIALISE_ELEMENT(memory);
  SERIALISE_ELEMENT(memoryOffset);

  SERIALISE_CHECK_READ_ERRORS();

  if(IsReplayingAndReading())
  {
    ResourceId resOrigId = GetResourceManager()->GetOriginalID(GetResID(image));
    ResourceId memOrigId = GetResourceManager()->GetOriginalID(GetResID(memory));

    VkMemoryRequirements mrq = {};
    ObjDisp(device)->GetImageMemoryRequirements(Unwrap(device), Unwrap(image), &mrq);
    bool ok = CheckMemoryRequirements(("Image " + ToStr(resOrigId)).c_str(), GetResID(memory),
                                      memoryOffset, mrq);

    if(!ok)
      return false;
    {
      LockedImageStateRef state = FindImageState(GetResID(image));
      if(!state)
      {
        RDCERR("Binding memory for unknown image %s", ToStr(GetResID(image)).c_str());
      }
      else
      {
        state->isMemoryBound = true;
        state->boundMemory = GetResID(memory);
        state->boundMemoryOffset = memoryOffset;
        state->boundMemorySize = mrq.size;
      }
    }

    GetResourceDesc(memOrigId).derivedResources.push_back(resOrigId);
    GetResourceDesc(resOrigId).parentResources.push_back(memOrigId);

    AddResourceCurChunk(memOrigId);
    AddResourceCurChunk(resOrigId);
  }

  return true;
}

```
1. We can see the mrq is the current device to replay the image  needed condition.
2. The funtion CheckMemoryRequirements checks the condition is right.

### May Fix
In order to fix this question, I add as follow code in this function:
``` cpp
// ....
VkDeviceSize memoryOffsetTmp = memoryOffset;
if (m_CrossPlatform) {
    memoryOffsetTmp = memoryOffsetTmp + mrq.alignment - 1;
    memoryOffsetTmp = memoryOffsetTmp / mrq.alignment;
    memoryOffsetTmp = memoryOffsetTmp * mrq.alignment;
}
if (mrq.size > memInfo.size - memoryOffsetTmp) {
    VkMemoryAllocateInfo AllocateInfo = {
    VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
    nullptr,
    0,
    0
};
AllocateInfo.allocationSize = mrq.size;
for (uint32_t i = 0; i < 32; i++) {
    if (mrq.memoryTypeBits & (1U << i)) {	
        AllocateInfo.memoryTypeIndex = i;
		break;
    }
}
VkDeviceMemory mem = VK_NULL_HANDLE;
VkResult ret = ObjDisp(device)->AllocateMemory(Unwrap(device), &AllocateInfo, NULL, &mem);
RDCASSERTEQUAL(ret, VK_SUCCESS);
GetResourceManager()->ReleaseWrappedResource(memory);
ResourceId live = GetResourceManager()->WrapResource(Unwrap(device), mem);
GetResourceManager()->AddLiveResource(memOrigId, mem);
m_CreationInfo.m_Memory[live].Init(GetResourceManager(), m_CreationInfo, &AllocateInfo);
m_CreationInfo.m_Memory[live].wholeMemBuf = VK_NULL_HANDLE;
AddResource(memOrigId, ResourceType::Memory, "Memory");
DerivedResource(device, memOrigId);
bool ok = CheckMemoryRequirements(("Image " + ToStr(resOrigId)).c_str(), GetResID(memory),
                                      memoryOffset, mrq);
```

I add this code, the question did not recurrent, but i do not know that new issue was **Caused**.

## Environment

* RenderDoc version:  1.9
* Operating System: Windows 10 and Android 10
* Graphics API: Vulkan 1.2.141
* GPU Device: Mali-G78
* ADB version: 1.0.41

**Comment by baldurk** [comment]
I'm afraid I don't understand what you are saying. This isn't a bug, vulkan captures are not always compatible across different devices. The error message has caught the problem and told you that this capture cannot be opened on the device you are trying to open it on. You should open the capture on the same device it was made on.

**Comment by luopan007** [comment]
> I'm afraid I don't understand what you are saying. This isn't a bug, vulkan captures are not always compatible across different devices. The error message has caught the problem and told you that this capture cannot be opened on the device you are trying to open it on. You should open the capture on the same device it was made on.

hi, I capture and open on the same device.

**Comment by baldurk** [comment]
In that case the most likely explanation is that your application is not allocating enough memory for the object during capture, since RenderDoc assumes valid API use and doesn't check memory requirements until replay.

Please run the validation layers on your application and fix any issues that they show. If you still find this problem after that then please open a new issue with reproduction steps including a debuggable APK of your application.

**Comment by luopan007** [comment]
> In that case the most likely explanation is that your application is not allocating enough memory for the object during capture, since RenderDoc assumes valid API use and doesn't check memory requirements until replay.
> 
> Please run the validation layers on your application and fix any issues that they show. If you still find this problem after that then please open a new issue with reproduction steps including a debuggable APK of your application.

ok, I will try it again. tks
