### ISSUE TITLE
Feature request - Change hotkey for capture

### ISSUE THREAD

**Issue by kymani37299** [baldurk/renderdoc#2089]
## Description

The problem I have right now is I want to capture moment in game and I must use hotkey F12 but F12 is also hardcoded
for debug menu. So every time I want to open debug menu I will capture also (and vice versa).

Instead of hardcoding F12 for capture hotkey in game it would be nice if you could configure what key is for capture.
Also it would be nice if you can configure hotkeys from cmd also (because of remote connections).

## Environment

* RenderDoc version: 1.9
* Operating System: Windows 10
* Graphics API: Vulkan/DX11

**Comment by baldurk** [comment]
The [in-application API](https://renderdoc.org/docs/in_application_api.html#_CPPv414SetCaptureKeysP21RENDERDOC_InputButtoni) provides you with a way to customise which key is used to trigger a capture, or you can manually start and stop the capture with any custom trigger you like.

Note that there are two capture keys by default for this reason in case one of them is already used - F12 and print screen. The overlay shows which keys are usable explicitly:

![image](https://user-images.githubusercontent.com/661798/98675137-c044f580-2351-11eb-98cf-a910b3348856.png)
