### ISSUE TITLE
Application crashes when loaded by qrenderdoc / with ENABLE_VULKAN_RENDERDOC_CAPTURE=1

### ISSUE THREAD

**Issue by mupuf** [baldurk/renderdoc#2093]
## Description

When trying to launch an application using qrenderdoc (or ENABLE_VULKAN_RENDERDOC_CAPTURE=1), the application segfaults when creating the device.

This may very well be a loader/Mesa issue, but since it only seems to manifest when using renderdoc, I would like to get your opinion on this before starting to chase my own tail!

## Steps to reproduce

 * Download and compile the official Vulkan Demos
 * build/app/bin/Debug/x86_64/vulkan_samples --sample terrain_tessellation
 * Observe a segfault

The issue is pretty much happening with all apps, except vkcube which doesn't seem to be using the same codepath (GetPhysicalDeviceProperties vs GetPhysicalDeviceProperties2KHR, see the next section).

## Steps to work around the issue

It appears like the issue comes from calling GetPhysicalDeviceProperties2KHR. It succeeds when not involving renderdoc, but fails when it is. Forcing using `GetPhysicalDeviceProperties` works around the issue.

```diff
diff --git a/src/vulkan/device-select-layer/device_select_layer.c b/src/vulkan/device-select-layer/device_select_layer.c
index 5b708bcd58b..ca0f6904d55 100644
--- a/src/vulkan/device-select-layer/device_select_layer.c
+++ b/src/vulkan/device-select-layer/device_select_layer.c
@@ -245,9 +245,9 @@ static bool fill_drm_device_info(const struct instance_info *info,
 
    if (info->has_props2 && info->has_pci_bus)
       properties.pNext = &ext_pci_properties;
-   if (info->GetPhysicalDeviceProperties2KHR)
+   /*if (info->GetPhysicalDeviceProperties2KHR)
      info->GetPhysicalDeviceProperties2KHR(device, &properties);
-   else
+   else*/
      info->GetPhysicalDeviceProperties(device, &properties.properties);
 
    drm_device->cpu_device = properties.properties.deviceType == VK_PHYSICAL_DEVICE_TYPE_CPU;
```

## Environment

* RenderDoc version: 1375a176828fa6f09d2495cf7eb12737a403c8c8 or renderdoc 1.10.
* Operating System: Arch Linux
* Graphics API: Vulkan
* Driver: RADV on mesa HEAD, or Mesa 20.2.2.

**Comment by baldurk** [comment]
This was a crash in the mesa device select layer, calling `GetPhysicalDeviceProperties2` from `EnumeratePhysicalDevices` inside renderdoc's `vkCreateInstance`, which fails since the layer doesn't configure those extension functions until it returns to the trampoline function.

**Comment by meisme-dev** [comment]
I think I have the same problem on both NVIDIA, RADV and llvmpipe on Fedora
valgrind:
```
==22826==  Access not within mapped region at address 0x0
==22826==    at 0x48495F6: strlen (vg_replace_strmem.c:499)
==22826==    by 0x1D9523: core::ffi::c_str::CStr::from_ptr (c_str.rs:289)
==22826==    by 0x1B4A50: vkcr::core::debug::debug_callback (debug.rs:13)
==22826==    by 0x2163C1BA: ??? (in /home/redacted/vulkansdk/1.3.236.0/x86_64/lib/librenderdoc.so)
==22826==    by 0x4A193D1: util_SubmitDebugUtilsMessageEXT.part.3 (debug_utils.c:98)
==22826==    by 0x4A3E6BB: loader_log (log.c:150)
==22826==    by 0x4A48E45: linux_read_sorted_physical_devices (loader_linux.c:248)
==22826==    by 0x4A3D1D8: setup_loader_term_phys_devs (loader.c:6147)
==22826==    by 0x4A3D307: terminator_EnumeratePhysicalDevices (loader.c:6303)
==22826==    by 0x215C5E77: ??? (in /home/redacted/vulkansdk/1.3.236.0/x86_64/lib/librenderdoc.so)
==22826==    by 0x20DE88BF: device_select_EnumeratePhysicalDevices (device_select_layer.c:482)
==22826==    by 0x4A40E07: vkEnumeratePhysicalDevices (trampoline.c:731)

**Comment by baldurk** [comment]
Do not comment on old closed issues.
