### ISSUE TITLE
glBindFramebufferEXT and glBindRenderbufferEXT are not aliases

### ISSUE THREAD

**Issue by Mikayex** [baldurk/renderdoc#2096]
## Description

According to [EXT_framebuffer_object](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_framebuffer_object.txt), section `Dependencies on ARB_framebuffer_object and OpenGL 3.0`, `glBindFramebufferEXT` and `glBindRenderbufferEXT` are not aliases of `glBindFramebuffer` and `glBindRenderbuffer` repectively.
The difference is that the EXT versions can be shared across contexts whereas the non EXT versions are not shareable.

The application I'm currently debugging uses the fact that EXT versions are shareable. This causes a crash of my application in [GLResourceManager::MarkFBOAttachmentsReferenced](https://github.com/baldurk/renderdoc/blob/f63a948392dda16ea6163e93ebd418bdbae0fc23/renderdoc/driver/gl/gl_manager.cpp#L91) : record is nullptr.

It seems there is a detection of the shared behavior in `DoVendorChecks` however it is not called in my case because I use compatibility profile and there is an `if(ver > GLCoreVersion || (!GLIsCore && ctxdata.isCore))` that prevent calling it. (`ver == GLCoreVersion` in my case)

If I put  `ver >= GLCoreVersion` instead of `ver > GLCoreVersion`, then there is no crash, but I have black renders. This is the result I have when replacing `glBindFramebufferEXT` with `glBindFramebuffer`, along with an OpenGL error `GL_INVALID_OPERATION: Object is owned by another context and may not be bound here.`. This is due to the aforementioned difference between them. If I replace the call to `glBindFramebuffer` with `glBindFramebufferEXT`, it works correctly.

## Steps to reproduce

Unfortunately I can't share the source code and I do not have time to do a minimal working example.
However I can build patches against renderdoc sources and test for you.

## Environment

* RenderDoc version: `f63a948392dda16ea6163e93ebd418bdbae0fc23` compiled myself but I have the crash also on 1.10
* Operating System: Windows 10 1909
* Graphics API: OpenGL

**Comment by baldurk** [comment]
As you point out this is technically valid behaviour based on the extension interactions, but I'm sorry it's not something I ever intend to support. I don't have any other suggestion except to either use a different debugging tool or to refactor your code to use the ARB/core behaviour of framebuffers which is effectively universally supported at this point.

The check for sharing there is intended to work around drivers that treat all framebuffers as shared no matter what. There are a few corners of the GL spec which are too fundamentally badly designed and rarely used to be worth supporting, and this is one.
