### ISSUE TITLE
Export .dds in the correct pixel format

### ISSUE THREAD

**Issue by GenderMurasaki** [baldurk/renderdoc#2097]
## Description

[Edit] sorry, I realized the mistake in my question.

**Comment by baldurk** [comment]
Your description is incorrect. Listing the fourcc as a decimal number is a confusing way to present it, but `808540228` corresponds to the code `DX10` (0x30315844) indicating that the dx10 dds header is present to specify the format. RenderDoc certainly doesn't encode anything to a block compressed format on export as that would be complete nonsense.

DDS files are always exported as the exact format with no encoding, if the pixel format isn't representable the export fails.
