### ISSUE TITLE
Crash during replay

### ISSUE THREAD

**Issue by 9cxndy** [baldurk/renderdoc#2098]
## Description

renderdoc crashes when trying to replay a dump.

## Steps to reproduce

Capture: http://ipfs.io/ipfs/QmeU6BahJ2a41Jv1rRdLwyXUS3ctyJ7D4jkYgdtBzB3ypp

(Rename it to `.tar.xz`. File is ~400M, please let me know if there's download problems.)

## Environment

* RenderDoc version: 0d4194afc57fa8498a6cde3df5ece2b21c744a83
* Operating System: Arch Linux
* Graphics API: Vulkan, RADV

**Comment by 9cxndy** [comment]
Could also be capture generated an invalid file.

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
