### ISSUE TITLE
Vulkan driver: vkQueueSubmit() serializer passes the same <fence> over and over again without resetting it

### ISSUE THREAD

**Issue by kbiElude** [baldurk/renderdoc#210]
vkResetFences() calls are not passed down to the driver, instead being replaced with wait-idle calls. This works most of the time, but I think there's at least one case that's been missed.

Consider an app which re-uses the same fence for vkQueueSubmit() calls. Before the second submission, it calls vkResetFences() to reset the fence. This invocation is removed by RenderDoc serializer. However, the same fence handle is later passed to vkQueueSubmit() call, which is against the following spec language:

```
Valid usage:

(..)

* fence must be unsignalled
```

**Comment by baldurk** [comment]
Simple fix should work I think - just need to actually replay the vkResetFences(). It's not used for explicit waiting or anything but it's still passed into vkQueueSubmit.

**Comment by DominikWitczakAMD** [comment]
Works for me! Thanks, Baldur :)
