### ISSUE TITLE
Add Game Render Wireframe

### ISSUE THREAD

**Issue by mengxinxiaoqiang** [baldurk/renderdoc#2105]
## Description

<!I want to display the rendered wireframe like GPA, used to view the distribution density-->

<I want to display the rendered wireframe like GPA, used to view the distribution density ->

## Environment

* RenderDoc version: 1.1
* Operating System: Win10
* Graphics API: D3D11

**Comment by baldurk** [comment]
You have to explain what you are asking for in more detail, I don't understand what you want.

RenderDoc v1.1 is also a very old version, you should update to the latest version of RenderDoc.

**Comment by mengxinxiaoqiang** [comment]
> 您必须更详细地解释您的要求，我不明白您想要什么。
> 
> RenderDoc v1.1也是一个很旧的版本，您应该更新到最新版本的RenderDoc。
The game you want to attach, rendered in wireframe form

**Comment by baldurk** [comment]
I'm sorry I still don't understand what you're asking for. Using machine translation it seems that the first two lines are what I said above, translated?

I understand that there is a language barrier here. If you can please explain in much more detail what feature you are asking for and what you want to use it for, with a much longer explanation, then there's more chance I can understand what you want.

**Comment by mengxinxiaoqiang** [comment]
I want to use RenderDoc to view the wireframe drawing in the game to distinguish the density of the area. Like interl GPA, I tried to modify it to no avail. I ask for your help. It should be because I am a Chinese, so I have a language barrier. Thanks for the help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baldurk/renderdoc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月2日(星期三) 晚上6:55
收件人:&nbsp;"baldurk/renderdoc"<renderdoc@noreply.github.com&gt;;
抄送:&nbsp;"小强"<1767137127@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baldurk/renderdoc] Add Game Render Wireframe (#2105)





 
I'm sorry I still don't understand what you're asking for. Using machine translation it seems that the first two lines are what I said above, translated?
 
I understand that there is a language barrier here. If you can please explain in much more detail what feature you are asking for and what you want to use it for, with a much longer explanation, then there's more chance I can understand what you want.

**Comment by baldurk** [comment]
In the mesh viewer you can view a wireframe rendering of the currently selected draw if that's what you want. I don't understand what you mean about the "density of the area". If the feature exists in intel GPA can you share a screenshot of what you're asking for?

**Comment by mengxinxiaoqiang** [comment]
As shown in the figure, the wireframe display is rendered in the game instead of the wireframe display in the editor


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baldurk/renderdoc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月2日(星期三) 晚上8:53
收件人:&nbsp;"baldurk/renderdoc"<renderdoc@noreply.github.com&gt;;
抄送:&nbsp;"小强"<1767137127@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baldurk/renderdoc] Add Game Render Wireframe (#2105)





 
In the mesh viewer you can view a wireframe rendering of the currently selected draw if that's what you want. I don't understand what you mean about the "density of the area". If the feature exists in intel GPA can you share a screenshot of what you're asking for?

**Comment by baldurk** [comment]
What figure? You mention a figure but I don't know which one you mean.

**Comment by mengxinxiaoqiang** [comment]
![image](https://user-images.githubusercontent.com/56524631/101152434-0bef7400-365e-11eb-8d58-892dce1193d0.png)
![image](https://user-images.githubusercontent.com/56524631/101152456-13af1880-365e-11eb-8b30-6971c47c3fe2.png)

**Comment by baldurk** [comment]
That looks like it's changing the rendering in the actual running process, not in the captured frame, is that correct?

**Comment by mengxinxiaoqiang** [comment]
Yes, I hope RenderDoc can have the same function

**Comment by baldurk** [comment]
No, I'm not going to change the game's rendering or add functionality to the in-application overlay like that. RenderDoc works by capturing frames and analysing them, only that analysis would do anything like this and functionality like that already exists.

If you need wireframe rendering in your application you can change the fill mode yourself in your own rendering code on a toggle, you don't need a tool to do that.
