### ISSUE TITLE
The color of the last draw is darker

### ISSUE THREAD

**Issue by zhouhuamin** [baldurk/renderdoc#2111]
## Description

1. open the rdc file, The color of the last draw is darker. What is the reason?
## Steps to reproduce

1. Open the rdc file and click the last draw

## Environment

* RenderDoc version: RenderDoc_1.11_64.msi
* Operating System: win10
* Graphics API: OpenGL ES 3.2

[001.zip](https://github.com/baldurk/renderdoc/files/5673400/001.zip)

**Comment by zhouhuamin** [comment]
Running GL replay on: Qualcomm / Adreno (TM) 509 / OpenGL ES 3.2 V@415.0

**Comment by baldurk** [comment]
The final draw samples from a texture that's R8G8B8A8_SRGB but then writes out to the backbuffer as R8G8B8A8_UNORM without any sRGB correction. The backbuffer is always implicitly interpreted as sRGB, thus there's a missing correction. If it were to write out R8G8B8A8_SRGB to the backbuffer it would look correct.
