### ISSUE TITLE
Error writing to file qrenderdoc.exe during installation

### ISSUE THREAD

**Issue by Haeri** [baldurk/renderdoc#2112]
## Description

Installer fails on Windows with error message: 
`Error writing to file: c:\Program Files\RenderDoc\qrenderdoc.exe. Verify that you have access to the directory.`

![Snipaste_2020-12-10_20-53-29](https://user-images.githubusercontent.com/7956606/101823205-b9fd9100-3b2a-11eb-95fe-9054545ffa63.png)

## Steps to reproduce

- Download the RenderDoc_1.11_64.msi installer and execute.
- Choose typical installation

## Environment

* RenderDoc version: 1.11 x64
* Operating System: Windows 10 Pro 19042.630
* Graphics API: none

**Comment by baldurk** [comment]
Did you have RenderDoc installed before? Is it running, or did you overwrite the qrenderdoc.exe file with a copy from another source? If you don't have RenderDoc installed but there's something at that location, can you delete the folder to empty it out and try again?

**Comment by Haeri** [comment]
This is super awkward. RenderDoc crashed on me and since I was unable to start it up again nor uninstall it, I thought maybe an update would help. I did make sure to delete the old RenderDoc folder but it still didn't let me install. 

Well as always a good old **restart fixed the problem**. 

Apparently some process was still running and blocking the installer. Don't know how I didn't think about restarting as the very first thing. Apologies and thanks for the quick replay 👍
