### ISSUE TITLE
While The RDC replay was finishing, the socket between Android phone and PC disconnect.

### ISSUE THREAD

**Issue by luopan007** [baldurk/renderdoc#2114]
## Description

I capture a frame on a Mate 40 Pro mobile(android), the graphics api is **Vulkan**,  I double click to open the RDC file and replay it。The renderdoc show Events successfully, but **socket** between Android phone and PC **disconnect**.。Here is the log:
``` xml
ALOG 011865: [19:37:16] vk_resource_funcs.cpp( 375) - Warning - Can't create buffer covering memory allocation ResourceId::15302
ALOG 011865: [19:37:18] vk_resource_funcs.cpp( 375) - Warning - Can't create buffer covering memory allocation ResourceId::16238
ALOG 011865: [19:37:21] vk_resource_funcs.cpp( 375) - Warning - Can't create buffer covering memory allocation ResourceId::16465
ALOG 011865: [19:37:22] vk_resource_funcs.cpp( 375) - Warning - Can't create buffer covering memory allocation ResourceId::16714
ALOG 011865: [19:37:23] vk_resource_funcs.cpp( 375) - Warning - Can't create buffer covering memory allocation ResourceId::17832
ALOG 011865: [19:37:30] vk_resource_funcs.cpp( 375) - Warning - Can't create buffer covering memory allocation ResourceId::18603
SQCC 003500: [11:12:32]    remote_server.cpp(1628) - Log     - Capture open complete
SQCC 003500: [11:12:32]    remote_server.cpp(1654) - Log     - Capture ready on replay host
SQCC 003500: [11:12:32]     d3d11_replay.cpp( 125) - Log     - Running replay on Intel / Intel(R) UHD Graphics 630 25.20.100.6519
ALOG 011865: [19:37:31]          vk_core.cpp(2361) - Log     - Timer chunk initialisation - 21461.974 ms
SQCC 003500: [11:12:33] replay_controller.cpp(2021) - Log     - Got replay driver.
SQCC 003500: [11:12:33]    remote_server.cpp(1683) - Log     - Remote capture open complete & proxy ready
QTUI 003500: [11:12:33]    replaymanager.cpp( 461) - Log     - QRenderDoc - renderer created for "/sdcard/Android/data/com.org.renderdoc.arm64/files/RenderDoc/com.org.renderdoc.arm64_2020.12.13_11.37.rdc"
SQCC 003500: [11:12:36]         streamio.cpp( 415) - Warning - Error reading from socket
SQCC 003500: [11:12:36]     replay_proxy.cpp(2725) - Error   - Error during processing of RemoteExecutionFinished
SQCC 003500: [11:12:36]     replay_proxy.cpp(2725) - Error   - Error during processing of ReplayLog
SQCC 003500: [11:12:36]    win32_network.cpp( 242) - Warning - send: WSAENOTSOCK: An operation was attempted on something that is not a socket
SQCC 003500: [11:12:36]         streamio.cpp( 570) - Warning - Error writing to socket
SQCC 003500: [11:12:36]     replay_proxy.cpp(2725) - Error   - Error during processing of ReplayLog
SQCC 003500: [11:12:36]     replay_proxy.cpp(2725) - Error   - Error during processing of RemoteExecutionFinished
SQCC 003500: [11:12:36]     replay_proxy.cpp(2725) - Error   - Error during processing of ReplayLog
SQCC 003500: [11:12:36]     replay_proxy.cpp(2725) - Error   - Error during processing of SavePipelineState
SQCC 003500: [11:12:36]     replay_proxy.cpp(2725) - Error   - Error during processing of RemoteExecutionFinished
```

### RenderDoc_1.8_64
The question was not present. 
### RenderDoc_1.9_64
The question was first present.
### During 2020.5.20~2020.7.22, I compare all Nightly version
I found this commit ID **02a54be6ad35f12aaaff1ad80707af00f67ef98c**, as follow code:
```cpp
GetDebugManager()->FillWithDiscardPattern(commandBuffer, DiscardType::RenderPassLoad,
                                                        image, initialLayout, viewInfo.range,
                                                        RenderPassBegin.renderArea);
```
This Discard pattern Function result in more memory was allocated, the android lowmemorykiller killed this program. Log as follow:
```xml
12-13 11:37:34.430 <6>[243616.553527s][pid:12043,cpu6,Thread-2]lowmemorykiller: Killing '.orgrendderdoc.arm64' (11865) (tgid 11865), adj 0,
```

## Environment

* RenderDoc version:  1.
* Operating System: Windows 10 and Android 10
* Graphics API: Vulkan 1.2.141
* GPU Device: Mali-G78
* ADB version: 1.0.41

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
