### ISSUE TITLE
The time which the glInvalidateFrameBuffer function spend seems to be wrong.

### ISSUE THREAD

**Issue by chena1982** [baldurk/renderdoc#2116]
## Description

When i profile on SamSung S20, i found that glInvalidateFrameBuffer function seems to use too much time.

![1111](https://user-images.githubusercontent.com/5953033/102061427-6c389f80-3e2e-11eb-9907-81f5a6926686.png)

when i use snapdragon profiler, it seems the glInvalidateFrameBuffer function is very fast.

![image](https://user-images.githubusercontent.com/5953033/102061611-a73ad300-3e2e-11eb-96b4-4d8f2e32ddda.png)

glInvalidateFrameBuffer is in the glClear
![image](https://user-images.githubusercontent.com/5953033/102061684-be79c080-3e2e-11eb-9b30-67433b4c8f00.png)

So, is the renderdoc get the wrong time or the snapdragon profiler get wrong time?

![image](https://user-images.githubusercontent.com/5953033/102066390-b9b80b00-3e34-11eb-8180-0a39e19213ae.png)

It seems renderdoc fill the RT with string "invalidated", is this process use too much time?

## Steps to reproduce

I create a simple project to reproduce the problem, it's a unity project:

[testshadow.zip](https://github.com/baldurk/renderdoc/files/5687704/testshadow.zip)

If you can't test it on android, you can test it on windows, set project api to opengles, you can test the function time use renderdoc and nsight, you will get similar result.

this is the compiled exe for windows:
[Output.zip](https://github.com/baldurk/renderdoc/files/5688006/Output.zip)

## Environment

* RenderDoc version: 1.1
* Operating System: win7
* Graphics API: opengles
* Phone: SamSung S20

**Comment by baldurk** [comment]
RenderDoc is not a profiler, so you should not rely on the timings provided as they may be affected by other factors. In this case it's most likely caused by the discard pattern, but in general this may be caused by driver issues, hardware variances, internal renderdoc overheads or more.
