### ISSUE TITLE
Request new Python API to get filename of current opened rdc.

### ISSUE THREAD

**Issue by vinjn** [baldurk/renderdoc#2117]
## Needs a new API to get filename of current opened rdc.

I am trying to make a python script to extract information from rdc file and turn that into a html webpage, so that developers can share and inspect rdc reports anywhere, once he/she got a brower.

The tool is called `render-doctor` and will soonly be released on https://github.com/xindong/render-doctor.

In order to automate the report generation, I'd like to have the ability to generate html filenames w.r.t. original rdc filenames.

## Environment

* RenderDoc version: 1.11
* Operating System: Windows 10
* Graphics API: OpenGL / OpenGL ES

**Comment by baldurk** [comment]
There's already a function to get the filename of the currently loaded capture: [`CaptureContext.GetCaptureFilename`](https://renderdoc.org/docs/python_api/qrenderdoc/main.html#qrenderdoc.CaptureContext.GetCaptureFilename).

**Comment by vinjn** [comment]
Thanks baldurk, really appreciate it.
