### ISSUE TITLE
RenderDoc crashes in EndFrameCapture, accessing deleted captureWriter object

### ISSUE THREAD

**Issue by decden** [baldurk/renderdoc#2121]
## Description

I am seeing a reproducible application crash when trying to serialize a capture. The crash occurs in WrappedID3D11Device::EndFrameCapture at the following line:

d3d11_device.cpp:2155
```cpp
    RDCLOG("Captured D3D11 frame with %f MB capture section in %f seconds",
           double(captureWriter->GetOffset()) / (1024.0 * 1024.0),
           m_CaptureTimer.GetMilliseconds() / 1000.0);
```

The application basically SEGFAULTS because captureWriter has already been deleted by this point, causing the crash.

Bypassing this line of code in the debugger leads to a successful capture and no crash.

Stepping through the code it appears that a `WriteSerializer ser` instance is created that takes ownership of the `captureWriter`. The `ser` object is however destroyed before reaching this logging line, deleting the `captureWriter`.

## Steps to reproduce

While the bug seems to be reliably reproducible on my machine with my particular application. I am unable to provide exact conditions for when this happens. I use renderDOC quite often in other scenarios on the same machine and it does not lead to crashes.

If however, my observations are correct this bug should be quite easy to fix and verify by code review alone.

## Environment

* RenderDoc version: v1.11
* Operating System: Windows 10 (1809)
* Graphics API: Direct3D 11

**Comment by baldurk** [comment]
Thanks for reporting that, the same bug was present in the other APIs as well so I've fixed it everywhere. I guess in the vast majority of cases nothing re-used that free memory in between the serialiser being destroyed and the log, so it managed to survive unnoticed.
