### ISSUE TITLE
Zero instances calls opengl generate errors.

### ISSUE THREAD

**Issue by samrrr** [baldurk/renderdoc#2124]
## Description

When i try call draw with 0 instances renderdoc shows errors.

This my render file:
[Render.txt](https://github.com/baldurk/renderdoc/files/5717674/Render.txt)
GlDebugOutput isnt called. So i dont see errors in my program. 

Opengl reference pages: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBufferData.xhtml
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDrawElementsInstanced.xhtml
I see zero is valid arg.

This renderdoc show:
![image](https://user-images.githubusercontent.com/18705603/102652178-bb5c3880-417e-11eb-9a2e-96f2e8e89570.png)

## Steps to reproduce
load this capture:
https://drive.google.com/file/d/1MdQlHLN-LT6uLGAkrt-UE2_EvJgLZYsK/view?usp=sharing

## Environment

* RenderDoc version: v1.11
* Operating System: Windows 10
* Graphics API: Opengl 4.6

AMD card.

**Comment by baldurk** [comment]
The text of these errors does not mention the instance count at all. The errors are pointing out that the vertex buffer setup is invalid.

That commit will not check for validity if the draw is empty and has 0 vertices or instances.
