### ISSUE TITLE
Warning: Querying ID3D11Device + WSAECONNRESET

### ISSUE THREAD

**Issue by gig67** [baldurk/renderdoc#2128]
edited by baldurk: removed link to hostile and parasitic project.

## Description

I am trying to capture a few buildings from Google Maps into Blender via RenderDoc.
I follow the process as described in REMOVED_LINK and also tried some other variants with no difference
I never manage to get to a stage where I can record frames in RenderDoc

## Steps to reproduce
See the steps indicated in REMOVED_LINK under section "Usage". I can reproduce up to step 4. 
Some people say that Chrome in debug mode should start with a bluish top line, mine stays white.
At this stage RenderDoc shows Target PID, Connection status: Connected, API: None
When I click OK in the chrome dialog (Step 5 of the above process), in RenderDoc the connection seems to be gone. 
Looking at the log reproduced below there seem to be  some connectivity problem with the graphics card
I try to proceed with steps 6 (I can see Google Maps in Satellite/3D mode) and 7 but there is no capture showing up in RenderDoc

## Environment

* RenderDoc v1.11 Windows 64-bit Release (c5480aa)
* Operating System: Windows 10
* Graphics API: Dell Laptop e7240 with HD Graphics 4400, driver 20.19.15.5063 downloaded from Dell website

## Log from RenderDoc

RDOC 005052: [11:07:40] win32_process.cpp( 597) - Log - Injecting renderdoc into process 6232
RDOC 006232: [11:07:40] core.cpp( 440) - Log - RenderDoc v1.11 Windows 64-bit Release (c5480aa) capturing application
RDOC 006232: [11:07:40] core.cpp( 282) - Warning - Disabling crash handling server due to detected chrome.
RDOC 006232: [11:07:40] settings.cpp( 460) - Log - Loading config from C:\Users\giuli\AppData\Roaming\renderdoc\renderdoc.conf
RDOC 006232: [11:07:40] win32_libentry.cpp( 66) - Log - Loading into C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
RDOC 006232: [11:07:40] sys_win32_hooks.cpp( 82) - Log - Registering Win32 system hooks
RDOC 006232: [11:07:40] d3d11_hooks.cpp( 44) - Log - Registering D3D11 hooks
RDOC 006232: [11:07:40] amd_hooks.cpp( 151) - Log - Registering AMD hooks
RDOC 006232: [11:07:40] nvapi_hooks.cpp( 117) - Log - Registering nvidia hooks
RDOC 006232: [11:07:40] d3d12_hooks.cpp( 173) - Log - Registering D3D12 hooks
RDOC 006232: [11:07:40] d3d8_hooks.cpp( 36) - Log - Registering D3D8 hooks
RDOC 006232: [11:07:40] d3d9_hooks.cpp( 45) - Log - Registering D3D9 hooks
RDOC 006232: [11:07:40] dxgi_hooks.cpp( 250) - Log - Registering DXGI hooks
RDOC 006232: [11:07:40] egl_hooks.cpp( 941) - Log - EGL hooks disabled by RENDERDOC_HOOK_EGL environment variable - if GLES emulator is in use, underlying API will be captured
RDOC 006232: [11:07:40] gl_hooks.cpp( 263) - Log - Registering OpenGL hooks
RDOC 006232: [11:07:40] egl_hooks.cpp( 941) - Log - EGL hooks disabled by RENDERDOC_HOOK_EGL environment variable - if GLES emulator is in use, underlying API will be captured
RDOC 006232: [11:07:40] wgl_hooks.cpp( 616) - Log - Registering WGL hooks
RDOC 006232: [11:07:40] vk_layer.cpp( 99) - Log - Registering Vulkan hooks
RDOC 005052: [11:07:40] target_control.cpp( 585) - Log - Got remote handshake: chrome [6232]

[Now I press the OK button on the Chrome dialog]

RDOC 006232: [11:10:40] dxgi_common.cpp(1633) - Warning - Querying IDXGIAdapter for unsupported/undocumented interface: IDXGIAdapterInternal2
RDOC 006232: [11:10:40] core.cpp(1798) - Log - Adding D3D11 device frame capturer for 0x000001CDD2775798
RDOC 006232: [11:10:40] d3d11_device.cpp( 159) - Log - New D3D11 device created: Intel / Intel(R) HD Graphics Family 20.19.15.5063
RDOC 006232: [11:10:40] dxgi_common.cpp(1659) - Warning - Querying ID3D11Device for unknown/unhandled interface: GUID {26c5dc23-e49c-4b0a-8f79-e7b1ac804d32}
RDOC 005052: [11:10:55] win32_network.cpp( 261) - Warning - recv: WSAECONNRESET: An existing connection was forcibly closed by the remote host.

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by gig67** [comment]
You are of course free to support whomever you wish to, but I take copyrights seriously and I do not accept your statement that I do not have rights to that information. 
My objective is to use Maps data for personal, non-commercial use. This is not prohibited by Google general Terms of Service and Maps specific Terms of Service: "You may not use output, or use third party tools to capture output, from Google Earth, Google Earth Pro, or Earth Studio to reconstruct 3D models or create similar content, or to create other content, products, or services that may violate our Terms of Service." Such ToS indicate the Prohibited Conduct such as redistributing or selling content, mass download, etc. none of which I intend to violate. Kind regards
