### ISSUE TITLE
Overwatch cannot be captured anymore—no API detected

### ISSUE THREAD

**Issue by mahalis** [baldurk/renderdoc#2133]
## Description

I’m trying to capture a frame from [Overwatch](https://us.shop.battle.net/en-us/family/overwatch), which I remember having been able to do a year or two ago, and I’m now unable to get it working; the status panel shows its connection "established" but the API as "none".

The log looks like this:

> RDOC 006020: [12:49:27]    win32_process.cpp( 514) - Log     - Running process D:\Games\Overwatch\_retail_\Overwatch.exe
> RDOC 006020: [12:49:27]    win32_process.cpp( 597) - Log     - Injecting renderdoc into process 7836
> RDOC 007836: [12:49:27]             core.cpp( 440) - Log     - RenderDoc v1.11 Windows 64-bit Release (c5480aa622a2f5447c87d23ccc0b08fb320b0169) capturing application
> RDOC 007836: [12:49:27]      crash_handler.h( 150) - Log     - Timer Waiting for crash handling server - 30.122 ms
> RDOC 007836: [12:49:27]      crash_handler.h( 156) - Log     - Created crash-handling server \\.\pipe\RenderDocBreakpadServer855469142856
> RDOC 007836: [12:49:27]      crash_handler.h(  87) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer855469142856
> RDOC 007836: [12:49:27]         settings.cpp( 460) - Log     - Loading config from C:\Users\noah\AppData\Roaming\renderdoc\renderdoc.conf
> RDOC 007836: [12:49:27]   win32_libentry.cpp(  66) - Log     - Loading into D:\Games\Overwatch\_retail_\Overwatch.exe
> RDOC 007836: [12:49:27]  sys_win32_hooks.cpp(  82) - Log     - Registering Win32 system hooks
> RDOC 007836: [12:49:27]      d3d11_hooks.cpp(  44) - Log     - Registering D3D11 hooks
> RDOC 007836: [12:49:27]        amd_hooks.cpp( 151) - Log     - Registering AMD hooks
> RDOC 007836: [12:49:27]      nvapi_hooks.cpp( 117) - Log     - Registering nvidia hooks
> RDOC 007836: [12:49:27]      d3d12_hooks.cpp( 173) - Log     - Registering D3D12 hooks
> RDOC 007836: [12:49:27]       d3d8_hooks.cpp(  36) - Log     - Registering D3D8 hooks
> RDOC 007836: [12:49:27]       d3d9_hooks.cpp(  45) - Log     - Registering D3D9 hooks
> RDOC 007836: [12:49:27]       dxgi_hooks.cpp( 250) - Log     - Registering DXGI hooks
> RDOC 007836: [12:49:27]        egl_hooks.cpp( 992) - Log     - Registering EGL hooks
> RDOC 007836: [12:49:27]         gl_hooks.cpp( 263) - Log     - Registering OpenGL hooks
> RDOC 007836: [12:49:27]        wgl_hooks.cpp( 616) - Log     - Registering WGL hooks
> RDOC 007836: [12:49:27]         vk_layer.cpp(  99) - Log     - Registering Vulkan hooks
> RDOC 007836: [12:49:27]      crash_handler.h(  51) - Log     - Re-using crash-handling server \\.\pipe\RenderDocBreakpadServer855469142856
> RDOC 007836: [12:49:27]      crash_handler.h(  87) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer855469142856
> RDOC 006020: [12:49:27]   target_control.cpp( 585) - Log     - Got remote handshake: Overwatch [7836]

## Steps to reproduce

1. Install Overwatch with Blizzard’s [launcher](https://www.blizzard.com/en-us/apps/battle.net/desktop)—if you don’t already own a copy please let me know and I can gift you a license
2. Point RenderDoc at its executable (located at [the install path]\_retail_\Overwatch.exe)
3. Launch it
4. Observe the inability to capture

## Environment

* RenderDoc version: 1.1.1
* Operating System: Windows 10 Pro x64  20H2 (19042.685)
* Graphics API: DirectX 11, as far as I know
* GPU: RTX 2080 (MSI Ventus 8G OC)
* Driver version: 460.79
* Overwatch version: 1.5.5.0.0.76333

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by mahalis** [comment]
Got it. Sorry to bother you.
