### ISSUE TITLE
Support for Vulkan extensions

### ISSUE THREAD

**Issue by Simoncl** [baldurk/renderdoc#2134]
## Description

Support for Vulkan extensions such as sparse texture residency. 

## Environment

* RenderDoc version: 1.11
* Operating System: Windows 10
* Graphics API: Vulkan 

Support for Vulkan extensions such as sparse texture residency. Support for the ray tracing API.

**Comment by baldurk** [comment]
Sparse textures are not an extension. This is already tracked in #333, closing this as a duplicate.
