### ISSUE TITLE
Running NBA2k19 fail

### ISSUE THREAD

**Issue by x1ngzai** [baldurk/renderdoc#2136]
## Description

I try to use "Launch Application" to run nba2k19 on win10,the capture options are Allow fullscreen and Allow VSync.
When i try to launch it,the game shows up for about 1 second,then disappare.I try to debug that game(by cheate engine).It shows "dxgi_error_device_removed".

## Steps to reproduce

This is what the RenderDoc's log looks like:

> Core 20604 21:03:44 core.cpp(440)             Log   RenderDoc v1.11 Windows 64-bit Release (c5480aa622a2f5447c87d23ccc0b08fb320b0169) loaded in replay application
Core 21756 21:03:44 core.cpp(440)             Log   RenderDoc v1.11 Windows 64-bit Release (c5480aa622a2f5447c87d23ccc0b08fb320b0169) loaded in replay application
Core 21756 21:03:44 settings.cpp(460)         Log   Loading config from C:\Users\panicboy\AppData\Roaming\renderdoc\renderdoc.conf
Core 20604 21:03:44 crash_handler.h(150)      Log   Timer Waiting for crash handling server - 66.253 ms
Core 20604 21:03:44 crash_handler.h(156)      Log   Created crash-handling server \\.\pipe\RenderDocBreakpadServer2758153340415
Core 20604 21:03:44 crash_handler.h(87)       Log   Connecting to server \\.\pipe\RenderDocBreakpadServer2758153340415
Core 20604 21:03:44 settings.cpp(460)         Log   Loading config from C:\Users\panicboy\AppData\Roaming\renderdoc\renderdoc.conf
UI 20604 21:03:44 qrenderdoc.cpp(89)        Log   QRenderDoc initialising.                          
UI 20604 21:03:44 qrenderdoc.cpp(92)        Log   Running as administrator                          
Core 20604 21:03:45 crash_handler.h(51)       Log   Re-using crash-handling server \\.\pipe\RenderDocBreakpadServer2758153340415
Core 20604 21:03:45 crash_handler.h(87)       Log   Connecting to server \\.\pipe\RenderDocBreakpadServer2758153340415
Core 20604 21:03:45 d3d11_replay.cpp(125)     Log   Running replay on nVidia / NVIDIA GeForce RTX 2070 SUPER 27.21.14.5730
Core 20604 21:03:45 d3d12_replay.cpp(102)     Log   Running replay on nVidia / NVIDIA GeForce RTX 2070 SUPER 27.21.14.5730
Core 20604 21:03:45 vk_replay.cpp(4235)       Log   Created device.                                   
Core 20604 21:03:45 android_tools.cpp(354)    Log   Initialising adb using 'C:\Program Files\RenderDoc/plugins/android/adb'
UI 20604 21:03:45 ToolWindowManager.cpp(1528) Warning area parameter ignored for this type              
Core 20604 21:03:51 android_tools.cpp(369)    Log   Started adb server                                
UI 20604 21:04:11 unknown(0)                Debug QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///D:/NBA 2K19/NBA2K19/NBA2K19.exe")) 1
UI 20604 21:04:11 unknown(0)                Debug QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///D:/NBA 2K19/NBA2K19/NBA2K19.exe")) 1
UI 20604 21:04:12 unknown(0)                Debug QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///D:/NBA 2K19/NBA2K19/NBA2K19.exe")) 1
Core 20604 21:04:14 win32_process.cpp(514)    Log   Running process D:\NBA 2K19\NBA2K19\NBA2K19.exe   
Core 20604 21:04:14 win32_process.cpp(597)    Log   Injecting renderdoc into process 9320             
Core 9320 21:04:15 core.cpp(440)             Log   RenderDoc v1.11 Windows 64-bit Release (c5480aa622a2f5447c87d23ccc0b08fb320b0169) capturing application
Core 9320 21:04:15 crash_handler.h(150)      Log   Timer Waiting for crash handling server - 65.004 ms
Core 9320 21:04:15 crash_handler.h(156)      Log   Created crash-handling server \\.\pipe\RenderDocBreakpadServer2758462053807
Core 9320 21:04:15 crash_handler.h(87)       Log   Connecting to server \\.\pipe\RenderDocBreakpadServer2758462053807
Core 9320 21:04:15 settings.cpp(460)         Log   Loading config from C:\Users\panicboy\AppData\Roaming\renderdoc\renderdoc.conf
Core 9320 21:04:15 win32_libentry.cpp(66)    Log   Loading into D:\NBA 2K19\NBA2K19\NBA2K19.exe      
Core 9320 21:04:15 sys_win32_hooks.cpp(82)   Log   Registering Win32 system hooks                    
Core 9320 21:04:15 d3d11_hooks.cpp(44)       Log   Registering D3D11 hooks                           
Core 9320 21:04:15 amd_hooks.cpp(151)        Log   Registering AMD hooks                             
Core 9320 21:04:15 nvapi_hooks.cpp(117)      Log   Registering nvidia hooks                          
Core 9320 21:04:15 d3d12_hooks.cpp(173)      Log   Registering D3D12 hooks                           
Core 9320 21:04:15 d3d8_hooks.cpp(36)        Log   Registering D3D8 hooks                            
Core 9320 21:04:15 d3d9_hooks.cpp(45)        Log   Registering D3D9 hooks                            
Core 9320 21:04:15 dxgi_hooks.cpp(250)       Log   Registering DXGI hooks                            
Core 9320 21:04:15 egl_hooks.cpp(992)        Log   Registering EGL hooks                             
Core 9320 21:04:15 gl_hooks.cpp(263)         Log   Registering OpenGL hooks                          
Core 9320 21:04:15 wgl_hooks.cpp(616)        Log   Registering WGL hooks                             
Core 9320 21:04:15 vk_layer.cpp(99)          Log   Registering Vulkan hooks                          
Core 9320 21:04:15 crash_handler.h(51)       Log   Re-using crash-handling server \\.\pipe\RenderDocBreakpadServer2758462053807
Core 9320 21:04:15 crash_handler.h(87)       Log   Connecting to server \\.\pipe\RenderDocBreakpadServer2758462053807
Core 20604 21:04:16 target_control.cpp(585)   Log   Got remote handshake: NBA2K19 [9320]              
Core 9320 21:04:17 dxgi_common.cpp(1633)     Warning Querying IDXGIAdapter for unsupported/undocumented interface: IDXGIAdapterInternal2
Core 9320 21:04:23 nvapi_hooks.cpp(312)      Log   Initialised nvapi, version NVidia Complete Version 1.10
Core 9320 21:04:23 nvapi_hooks.cpp(414)      Warning NvAPI disabled: Returning NULL for nvapi_QueryInterface(NvAPI_EnumPhysicalGPUs)
Core 9320 21:04:23 core.cpp(1798)            Log   Adding D3D11 device frame capturer for 0x000001D5D376FEC8
Core 9320 21:04:23 d3d11_device.cpp(159)     Log   New D3D11 device created: nVidia / NVIDIA GeForce RTX 2070 SUPER 27.21.14.5730
Core 9320 21:04:24 nvapi_hooks.cpp(414)      Warning NvAPI disabled: Returning NULL for nvapi_QueryInterface(NvAPI_EnumPhysicalGPUs)
Core 9320 21:04:24 core.cpp(1798)            Log   Adding D3D11 device frame capturer for 0x000001D5D376F8C0
Core 9320 21:04:24 d3d11_device.cpp(159)     Log   New D3D11 device created: nVidia / NVIDIA GeForce RTX 2070 SUPER 27.21.14.5730
Core 9320 21:04:24 d3d11_device.cpp(836)     Warning Returning a dummy ID3D11Debug that does nothing. This ID3D11Debug will not work!
Core 9320 21:04:24 d3d11_device.cpp(782)     Warning Returning a dummy ID3D11InfoQueue that does nothing. RenderDoc takes control of the debug layer.
Core 9320 21:04:24 d3d11_device.cpp(787)     Warning If you want direct access, enable API validation and query for GUID {3fc4e618-3f70-452a-8b8f-a73accb58e3d}. This will return the real ID3D11InfoQueue - be careful as it is unwrapped so you should not call QueryInterface on it.
Core 9320 21:04:24 core.cpp(1831)            Log   Adding D3D11 frame capturer for 0x000001D5D376F8C0 / 0x0000000000071006
Core 20604 21:04:24 target_control.cpp(831)   Log   Used API: D3D11 (Presenting & supported)          
Core 9320 21:04:24 nvapi_hooks.cpp(414)      Warning NvAPI disabled: Returning NULL for nvapi_QueryInterface(0xd451e834)
Core 20604 21:04:26 win32_network.cpp(261)    Warning recv: WSAECONNRESET: An existing connection was forcibly closed by the remote host.

## Environment

* RenderDoc version: 1.11
* Operating System: Windows 10 Pro x64
* Graphics API: Direct3D11
* GeForce RTX 2070 SUPER
* Driver 457.30

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
