### ISSUE TITLE
Docs cannot be built on Linux: undefined symbol

### ISSUE THREAD

**Issue by xwang186** [baldurk/renderdoc#2138]
## Description

Error occurs while building documents. In docs folder, I followed README but get failed with error info as bellow:
WARNING: autodoc: failed to import class 'PersistantConfig' from module 'qrenderdoc'; the following exception was raised:
/home/xiaohan/repo/renderdoc/build/lib/qrenderdoc.so: undefined symbol: RENDERDOC_IsReleaseBuild

## Steps to reproduce

1. build project using 
  cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild -H.  (Also tried with Release)
  make -C build
2. cd docs && make html

## Environment

* RenderDoc version: v1.x , commit: c1ecd9d375f0085cc590af1074f5f78ca87e0f9c
* Operating System: Ubuntu20

**Comment by baldurk** [comment]
This is not a bug as the CI builds the documentation on linux at every commit, [including the exact commit you quote](https://github.com/baldurk/renderdoc/runs/1608270622). The nightly builds also build documentation on linux.

You must have some system configuration problem or build issue that is local to your computer. Perhaps you have some stale build artifacts that you need to delete.

**Comment by xwang186** [comment]
Probably right.. But I cannot get it correct even I cleaned the build folder and rebuild.

-- Calculating version
-- Building RenderDoc version 1.11
-- Building RenderDoc in Release mode: Release
-- Building using Qt 5.12.8
-- PySide2 not found - Qt will not be accessible in python scripting. See https://github.com/baldurk/renderdoc/wiki/PySide2
-- Enabled APIs:
--   - OpenGL (with additional EGL support)
--   - OpenGL ES (EGL)
--   - Vulkan
-- Enabled Window System Support:
--   - XLib
--   - XCB
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xiaohan/repo/renderdoc/build

And I didn't get a build error or warning.

A symbol missing doesn't seem to be an issue of build environment though, but if the IC build works then probably there should be more cmake parameters needed to be set.

Yes and I agree that it can be my local build issue.
