### ISSUE TITLE
Unable to start D3D11 capturing

### ISSUE THREAD

**Issue by holance** [baldurk/renderdoc#2145]
## Description

I have a program using SharpDX DirectX 11. RenderDoc was used to work fine before v1.10. Starting v1.10, when I try to launch the program from RenderDoc, the program exits/crashed immediately.

## Steps to reproduce
1. Download the test program from [Test App]( https://github.com/holance/Test/blob/main/Debug.zip) .
2. Launch "CoreTest.exe" from RenderDoc.

## Environment

* RenderDoc version: 1.10
* Operating System: Windows 10
* Graphics API: DirectX 11

**Comment by baldurk** [comment]
This was an issue with the changes in v1.11 to optimise refcounting and defer destruction of resources. In some cases (in your example with Direct2D) resources could get destroyed, then the same pointer value gets recreated and re-wrapped and destroyed again, leading to a double delete when those deferred destructions finally happen.
