### ISSUE TITLE
RenderDoc records OpenGLES on an Android Vulkan app on Xiaomi Redmi Note 8

### ISSUE THREAD

**Issue by alecazam** [baldurk/renderdoc#2146]
## Description

RenderDoc records OpenGLES on an Android Vulkan app on Xiaomi Redmi Note 8.  This app only uses Vulkan, but there seems to be no way to force only Vulkan to record.   It looks like RenderDoc connects to an overlay, but I just see glClear and eglSwapBuffers in the captures.  There is an initial error message on launch, but I'm able to "attach to instance", but it seems like RenderDoc is stuck in "ES" mode.

## Steps to reproduce

1. Set "USB Debugging" in developer mode on the Android device
2. Connect to device from RenderDoc from Windows 10 Pro from MacOS Parallels connected to USB connection
3. Error dialog pops up about "Error connecting to debugger".  Says Android Studio is possibly connected, but that's not the case.  See image below
4. Overlay says "OpenGLES Connected" and there are various timings underneath that.
5. Run "Attach to Instance" and pick the app and #DefaultActivity within that.
6. RenderDoc says "Vulkan (active), OpenGLES (Not Presenting).
7. All captures are not Vulkan, but a tiny ES capture.  See image below.

## Environment

* RenderDoc version: 11.1
* Operating System: WIndows 10 Pro (on Parallels)
* Graphics API: Vulkan on Android 9

## Additional Data

This is the error dialog when Launch is pressed
![image](https://user-images.githubusercontent.com/3750359/104238238-1b589e80-540e-11eb-8c1b-16538a1e2338.png)

This is the capture of ES calls from a Vulkan only application
![image](https://user-images.githubusercontent.com/3750359/104238002-c7e65080-540d-11eb-8b9a-796703928b56.png)

**Comment by baldurk** [comment]
Why have you opened the exact same bug twice? Closing.
