### ISSUE TITLE
On Linux, with DPI scaling enabled, "Texture Viewer" tracks cursor incorrectly

### ISSUE THREAD

**Issue by nyanpasu64** [baldurk/renderdoc#2148]
## Description

On Linux KDE X11 with display scaling enabled, when I hover a texture in RenderDoc's texture viewer, the wrong pixel is shown in the color picker and "pixel context" views.

The texture is shown with 1:1 physical pixel scaling, but the mouse position is read using device-independent pixels. If my display is at 125% scale, every time I move my cursor 5 pixels down/right, RenderDoc thinks I moved it 4 pixels. That means that pixel being inspected is closer to the top-left corner of the window/panel than it should be.

![renderdoc dpi](https://user-images.githubusercontent.com/913957/104526256-cdcb6580-55b6-11eb-9b7c-6828e6fc6326.png)

## Steps to reproduce

- Install Linux and KDE, and precompiled RenderDoc from the official website.
- Launch KDE in X11 mode.
- In KDE's "Display Configuration" settings panel, set "Global scale" to 125% or so.
- Open RenderDoc and open a capture.
- In the "Texture Viewer" tab, hover the texture and look at the status bar. Alternatively right-click a point on a texture and look at "Pixel Context".

## Environment

* RenderDoc version: v1.11
* Operating System: Arch Linux, AUR package `renderdoc-bin`, aka https://renderdoc.org/stable/1.11/renderdoc_1.11.tar.gz, using bundled Qt 5.6.2
* Graphics API: OpenGL

I'm not sure if using RenderDoc with a newer Qt version will change the bug. Nor if the bug behaves differently at integer scale factors (Qt sometimes behaves differently).

**Comment by baldurk** [comment]
That commit switches to using the fractional pixel scale for calculating co-ordinates, it doesn't make a difference on my windows test but maybe on linux it will.

I'd also suggest trying either the latest nightly builds which are linked against a newer Qt which might have some relevant DPI-related fixes, or try building from source yourself. If none of that helps then this is either a Qt bug or a bug with some other part of your system such as desktop environment/scaling setup/something.

Your screenshot shows quite a few other rendering issues with icons being completely broken and lines blurred, so there are more problems there than just the one you mention. 125% DPI scaling is effectively nonsense so changing instead to just a larger font would likely produce more consistent results.

**Comment by nyanpasu64** [comment]
It seems fixed. Thanks!

> Your screenshot shows quite a few other rendering issues with icons being completely broken and lines blurred, so there are more problems there than just the one you mention. 125% DPI scaling is effectively nonsense so changing instead to just a larger font would likely produce more consistent results.

oof, I just got used to broken icons and lost hope of them getting better...
