### ISSUE TITLE
Error 0x501 in map_buffer when capturing

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#2149]
## Description

Running [wrench](https://github.com/servo/webrender/tree/master/wrench) on specific inputs panics with GL error 0x501 in `map_buffer`, but only when being captured by RenderDoc. Running without capturing (in or out of renderdoc) doesn't have this error.

## Steps to reproduce

```bash
git clone https://github.com/kvark/webrender -b rd-map-buffer-bug wr
cd wr/wrench
cargo build # requires Rust+Cargo
../target/debug/wrench show reftests/border/border-suite.yaml
```
The last command needs to be launched from RD with queued capturing of frame 1:
![renderdoc-launch-options](https://user-images.githubusercontent.com/107301/104784213-d0b08c80-5755-11eb-9934-72109b0a48b8.png)

## Environment

* RenderDoc version: 1.11
* Operating System: "Linux 5.10.7-168.current"
* Graphics API: OpenGL-3

I added logging of what is getting mapped/unmapped:
```
OpenGL version 3.2.0 NVIDIA 460.32.03, GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2
hidpi factor: 2 (native 2)
Shader override path: None
Mapping VBOId(37) for 352 instances
Unmapping VBOId(37)
Mapping VBOId(38) for 320 instances
Unmapping VBOId(38)
Mapping VBOId(39) for 4096 instances
Unmapping VBOId(39)
Mapping VBOId(32) for 672 instances
Unmapping VBOId(32)
Mapping VBOId(32) for 4 instances
Caught GL error 501 at map_buffer
```

It looks like RenderDoc handling of the mapping (which only works during capturing) doesn't expect the buffer to be completely reinitialized. I.e. in the example above buffer ID 32 was re-initialized with `glBufferData(..., new_size, null)` before we map it again. My suspicion is that RenderDoc has an expectation that mapped buffers don't get re-initialized.

**Comment by baldurk** [comment]
Is there any chance you could share a binary build of your program? It's not necessary but would speed things up for me since then I don't have to install and configure a new toolchain to build it.

What are you doing inside your map_buffer function - are you calling glMapBuffer or glMapBufferRange? Do you use persistent mapping at all? Orphaning buffers with glBufferData() even mid frame capture should be handled correctly but there might be an interaction with mapping or a specific set of buffer flags that causes problems, I will repro when I'm able and investigate. Do you change the buffer size when you orphan, or are you only orphaning at the same size?

If you enable API validation in the capture options do you get any more useful/specific error information than just `GL_INVALID_VALUE`, especially if you don't make that a fatal error?

**Comment by kvark** [comment]
I sent the build via wetransfer (it's 50megs). [Here is](https://github.com/kvark/webrender/blob/7fe1078f48743d595f23f6fb553d5ff5b51435df/webrender/src/device/gl.rs#L3418) the code that re-initializes a buffer and maps it (via `glMapBuffer` on GL). It's not persistent, and the only parameter is `gl::WRITE_ONLY`.

> Do you change the buffer size when you orphan, or are you only orphaning at the same size?

The size is changed, as you can see from the log I posted. I.e. first it's allocated for "672 instances", then for "4 instances".

> If you enable API validation in the capture options do you get any more useful/specific error information than just GL_INVALID_VALUE, especially if you don't make that a fatal error?

Tried that, got the following hint in RenderDoc error log:

> 309 API High Miscellaneous 1281 GL_INVALID_VALUE error generated. Offset and/or size is out of range.

**Comment by baldurk** [comment]
Thanks, I can look at this on Monday. I have a hunch, does the problem still happen if you keep the buffer size the same, e.g. by picking a single conservative size?

**Comment by baldurk** [comment]
This looks like it was indeed to do with buffer resizing. If a buffer is resized from a larger size to a smaller size during the frame capture, the recorded metadata wouldn't be updated so inside `glMapBuffer` the size would be too large when it called `glMapBufferRange`. I don't know if this would have any negative effects other than the error, but that commit should fix it as well as some other edge cases this kind of legacy usage could produce.

**Comment by kvark** [comment]
Thank you for the fix!
