### ISSUE TITLE
Vulkan cannot create device

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#2152]
## Description

On my own application, but also in Sascha Willems' demos, attaching renderdoc causes the application to fail to create the vulkan logical device (i.e. the call to vkCreateDevice). I have managed to track down the last nightly where it worked, which is RenderDoc_2020_10_04_41746240_64. Thank you for keeping these! Just to be clear, for me nightly RenderDoc_2020_10_05_99171cc7_64 is broken.

## Steps to reproduce

Get renderdoc 1.11, attach any of deferred.exe from Sascha Willems' demo collection. Run.

## Environment

* RenderDoc version: 1.11 (nightly also broken)
* Operating System: Windows 10
* Graphics API: Vulkan

I have two GPUs, an NVIDIA 1060 GTX and Intel UHD Graphics 630.

Let me know if there are any other details I could supply to help out with this.

**Comment by baldurk** [comment]
This works fine for me on 1.11 and on the nightlies. I use Sascha Willems' demos for smoke testing releases and general testing, so I'd be surprised if it were globally broken.

There are few commits in that range, and one of them is a fix to be spec compliant in `vkGetInstanceProcAddr`. Do you have any programs on your system that might be enabling layers globally? If you run vulkaninfo what layers are listed as available? If you break the debugger in the demo after the `vkCreateDevice` failure can you list the DLLs loaded in the process?

Are you doing anything else? Your steps are a little unclear when you say 'attach', I presume you mean launch the deferred.exe from RenderDoc. Are you enabling any capture options or is it all default - in particular are you enabling API validation?

**Comment by redorav** [comment]
Yeah I would have been very surprised if it was broken globally.

In answer to your questions:
- Whether I enable the debug layers or not doesn't affect it
- These are the available layers:

GalaxyOverlayVkLayer (Galaxy Overlay Vulkan Layer) Vulkan version 1.1.73, layer version 1:
GalaxyOverlayVkLayer_DEBUG (Galaxy Overlay Vulkan Layer) Vulkan version 1.1.73, layer version 1:
GalaxyOverlayVkLayer_VERBOSE (Galaxy Overlay Vulkan Layer) Vulkan version 1.1.73, layer version 1:
VK_LAYER_EOS_Overlay (Vulkan overlay layer for Epic Online Services) Vulkan version 1.2.136, layer version 1:
VK_LAYER_EOS_Overlay (Vulkan overlay layer for Epic Online Services) Vulkan version 1.2.136, layer version 1:
VK_LAYER_KHRONOS_validation (Khronos Validation Layer) Vulkan version 1.2.162, layer version 1:
VK_LAYER_LUNARG_api_dump (LunarG API dump layer) Vulkan version 1.2.162, layer version 2:
VK_LAYER_LUNARG_device_simulation (LunarG device simulation layer) Vulkan version 1.2.162, layer version 1:
VK_LAYER_LUNARG_gfxreconstruct (GFXReconstruct Capture Layer Version 0.9.5) Vulkan version 1.2.162, layer version 36869:
VK_LAYER_LUNARG_monitor (Execution Monitoring Layer) Vulkan version 1.2.162, layer version 1:
VK_LAYER_LUNARG_screenshot (LunarG image capture layer) Vulkan version 1.2.162, layer version 1:
VK_LAYER_NV_optimus (NVIDIA Optimus layer) Vulkan version 1.2.142, layer version 1:
VK_LAYER_RENDERDOC_Capture (Debugging capture layer for RenderDoc) Vulkan version 1.2.131, layer version 12:
VK_LAYER_VALVE_steam_fossilize (Steam Pipeline Caching Layer) Vulkan version 1.2.136, layer version 1:
VK_LAYER_VALVE_steam_overlay (Steam Overlay Layer) Vulkan version 1.2.136, layer version 1:
VK_LAYER_bandicam_helper (Vulkan Bandicam Helper) Vulkan version 1.1.73, layer version 1:

- When I say attach I mean I either load app through renderdoc or load manually (in my app) by loading the layer. Both crash
- Loaded dlls in deferred.exe are

ntdll.dll
kernel32.dll
KernelBase.dll
user32.dll
win32u.dll
gdi32.dll
gdi32full.dll
vulkan-1.dll
msvcp_win.dll
ucrtbase.dll
imm32.dll
cfgmgr32.dll
advapi32.dll
msvcp140d.dll
msvcrt.dll
vcruntime140d.dll
vcruntime140_1d.dll
sechost.dll
rpcrt4.dll
ucrtbased.dll
renderdoc.dll
ws2_32.dll
shlwapi.dll
setupapi.dll
bcrypt.dll
comdlg32.dll
combase.dll
SHCore.dll
shell32.dll
comctl32.dll
ole32.dll
oleaut32.dll
vcruntime140.dll
msvcp140.dll
vcruntime140_1.dll
dbghelp.dll
symsrv.dll
mswsock.dll
windows.storage.dll
wldp.dll
D3DCompiler_47.dll
cryptsp.dll
opengl32.dll
glu32.dll
dxgi.dll
kernel.appcore.dll
version.dll
nvoglv64.dll
wtsapi32.dll
msasn1.dll
cryptnet.dll
crypt32.dll
cryptbase.dll
devobj.dll
wintrust.dll
ntmarta.dll
igvk64.dll
dwmapi.dll
igdgmm64.dll
igc64.dll
igdmd64.dll
bdcamvk64.dll
DXCore.dll
nvspcap64.dll
profapi.dll
uxtheme.dll

**Comment by redorav** [comment]
I have figured out how to fix it. I have a program called Bandicam which has a layer and a dll as well, uninstalling it makes it work again. I don't know why it is an issue though or how it conflicts with renderdoc.

**Comment by baldurk** [comment]
It means you had buggy software installed and uninstalling it fixed the problem because it was no longer being buggy in all vulkan processes :smile:. I'll add that layer to the disabled layers in RenderDoc so that it won't break for others hopefully.

**Comment by redorav** [comment]
😁 what I mean is, does it force a layer of some sort without the application knowing? I don't know much about how that works, but I guess each vulkan layer is a dll. Why would that crash renderdoc and not apps running with it though? Thanks for taking a look, this software is not one I normally have enabled and I've been scratching my head all evening

**Comment by baldurk** [comment]
Yes, for arguable benefit vulkan layers are allowed to be globally enabled. i.e. opt-out, not opt-in. Looking around it seems like bandicam is one of these, meaning it is automatically loaded as a layer into every vulkan application that runs on the system and that means any bugs it has are added to every running vulkan application.

**Comment by redorav** [comment]
I see. That's a bit sad :(
