### ISSUE TITLE
Can't edit compute shader when shader is bytecode

### ISSUE THREAD

**Issue by chena1982** [baldurk/renderdoc#2158]
## Description

If the shader is bytecode, for example shader is DXIL, when click the edit button, renderdoc try to convert DXIL to hlsl
but sometimes the convert is failed, if we can select don't convert the shader, just edit the DXIL shader?
I know DXIL is hard to edit, but at least it can edit the shader, better than can't edit shader.
Thanks.

## Environment

* RenderDoc version: 1.1
* Operating System: win10
* Graphics API: dx12

**Comment by baldurk** [comment]
RenderDoc doesn't have any feature for converting DXIL to hlsl, and I don't know of any program that does that.

Editing shaders on D3D requires that you build your shaders with debug info so that the original source is available. If you do that, you should be able to edit the shaders and recompile as normal.

**Comment by chena1982** [comment]
when i click the edit button, i get that:

![Snipaste_2021-01-21_23-57-50](https://user-images.githubusercontent.com/5953033/105376696-fac9e900-5c44-11eb-8baa-46fe73c5e8d4.png)

So if it's possible to direct edit DXIL?

**Comment by baldurk** [comment]
That is just a generated stub source created from the reflection data when no source is available, it's not an editable shader. As I mentioned above you should build your shaders with debug information enabled and then the original source will be available for editing.

**Comment by chena1982** [comment]
> That is just a generated stub source created from the reflection data when no source is available, it's not an editable shader. As I mentioned above you should build your shaders with debug information enabled and then the original source will be available for editing.

Sometimes we don't get the source code, just have bytecode, and want to edit the shader.
