### ISSUE TITLE
Renderdoc crash when edit compute shader

### ISSUE THREAD

**Issue by chena1982** [baldurk/renderdoc#2159]
## Description
I use "Decompile with SPIRV-Cross" to edit the compute shader.
I edit the shader, click refresh, renderdoc crashed. 

## Steps to reproduce

1. open a capture file.
2. select a compute shader, click edit.
3. edit the shader, just change a vector4.w to 1.0.
4. click refresh, renderdoc crash. 

## Environment

* RenderDoc version: 1.1
* Operating System: win10
* Graphics API: vulkan

converted shader file:

[11.txt](https://github.com/baldurk/renderdoc/files/5850678/11.txt)

the dumps file:
[XnI14.zip](https://github.com/baldurk/renderdoc/files/5850694/XnI14.zip)

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
