### ISSUE TITLE
Incorrect line counter

### ISSUE THREAD

**Issue by LuridHound** [baldurk/renderdoc#2160]
## Description
Expected to see correct accordance of the lines in "Find Results" window and in "Disassembly".
In the parentheses you can see number 35, meanwhile this line is one line above the place, where the necessary instruction is written.

## Steps to reproduce

In my capture.
0) Unzip capture.
1) Open a command with in Event browser with EID 296.
2) Go to Pipeline State window.
3) Choose vertex shader.
4) Click on "View" near the shader.
5) Press "Crtl" + "F" and write down "ld_indexable".
6) Find all.

I've sent a capture to the mail with the theme "Hardspace Shipbreaker.zip".

## Environment

* RenderDoc version: 1.11
* Operating System: Windows 10
* Graphics API: DirectX11

I've not tested it on all events, but I've seen the same problem everywhere, where I've tried to.

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by Triang3l** [comment]
Opening any DXBC shader and using text search should probably be enough as reproduction steps.

**Comment by LuridHound** [comment]
I finally understood what was incorrect.
I thought that :
1) check this on NDA project will change the steps. (it won't)
2) After closed first issue I thought it will be better to open a new one( bad idea)
3) Even in new issue I didn't give a minimal example to reproduce the bug.
I wasn't right. Sorry, Baldur Karlsson.
