### ISSUE TITLE
CloneTemporaryContext fails with code EGL_BAD_CONTEXT

### ISSUE THREAD

**Issue by JohnnyonFlame** [baldurk/renderdoc#2162]
## Description

Remote capturing on a Mali G31 powered device (RK3326 SoC) fails to create temporary sandboxed contexts in EGLPlatform::CloneTemporaryContext due to a mismatch in the EGL_CONTEXT_CLIENT_VERSION attribute, causing failures such as garbage data in textures and other adverse effects, resulting in a partially corrupted capture.

For reference - [the following workaround was attempted](https://github.com/JohnnyonFlame/renderdoc/commit/55ac1b243bdd432f7e91eb616ee47f5605dd1048) and provides successful captures in the few applications I've tested so far.

## Steps to reproduce

1) Launch remote server
1) Launch application on said server
1) Attempt a capture
1) Sandboxed context creation fails apparently silently
1) Capture continues regardless
1) Capture fails to fetch textures and other adverse effects

## Environment

* RenderDoc version: git-c5480aa622a2
* Operating System: Ubuntu 19.10 (aarch64)
* Graphics API: OpenGL ES 2.x
* Graphics Drivers: Mali-TDVX / v1.r6p0-01rel0.871ae322bd66147fe999503abdaa6f0d

**Comment by baldurk** [comment]
As discussed on IRC this seems to be a driver bug since there's nothing invalid about what the context creation is doing, GLES2 and GLES3.x are the same API type and should be compatible. That commit adds error logging and a fallback along the lines of what you had to try a GLES2 context in case it works.

**Comment by JohnnyonFlame** [comment]
```
RDOC 000725: [17:50:16]        gl_driver.cpp(1142) - Log     - Core context 011BFFB0 created with attribs, sharing with context 00000000
RDOC 000725: [17:50:16]     egl_platform.cpp(  91) - Warning - Creating cloned context failed. Trying again with queried old EGL client version: 2
RDOC 000725: [17:50:16]        gl_driver.cpp(1155) - Log     - Created new sharegroup 011B2858
```

Works great, thank you.
