### ISSUE TITLE
Diagnostic Log keeps jumping to tail of new messages when you've scrolled back.

### ISSUE THREAD

**Issue by alecazam** [baldurk/renderdoc#2163]
## Description

On my Android device, I had a repeating message show up in the Diagnostic Log.  This then caused the UI to scroll to the bottom to show it, but I was holding onto the scroll bar widget, and had scrolled up to read earlier message.

## Steps to reproduce

1. Run any app that keeps logging to the "Diagnostic Log".  
2. Try to read earlier entries by scrolling to the top.

Expected that once I'm scrolled to a part of the scrollView, that I stay there even if new data is coming in.  This may be a QT thing across more parts of the app.   

## Environment

* RenderDoc version: v1.11
* Operating System: macOS
* Graphics API: Vulkan (on Android)

**Comment by baldurk** [comment]
There's a button at the top of the log view labelled "Follow new messages". You can toggle it off if you prefer.

**Comment by alecazam** [comment]
Yes, thanks.
