### ISSUE TITLE
DiscardResource causes incorrect profiling results

### ISSUE THREAD

**Issue by apayen** [baldurk/renderdoc#2172]
## Description

Since a few versions, DiscardResource (or equivalent calls on other APIs) now fills the target with "DISCARDEDIMG" pattern on all the channels. While this is a very handy feature to track hazard, it also impacts frame captures profiling, and reports very high durations ~10ms for a 4k RT.

Of course, we ignore the timings reported for discard as we understand these are only side-effects from the replay, however they add up in our debug marker's aggregates, which makes it less convenient to figure out how much a pass is taking as we have to substract the cost from each discard below in the tree.

The issue does not happen if Replay optimisation level is set to Fastest (but lose the benefit tracking of discarded regions).
The issue does happen with No optimisation.

When profiling, the replay loop should not perform extra work intended solely for debug visualisation.
Ideally, disabling replay optimisation and profiling should be as close as possible to the original workload (with shader edits if any).

## Steps to reproduce

* Set Replay optimisation level to Balanced or No optimization in Renderdoc's option
* Capture the attached DX11 application and profile it
* DiscardResource on the swapchain image will take more than 1ms (depending on your GPU ofc)

[Direct3DGame1.zip](https://github.com/baldurk/renderdoc/files/5923581/Direct3DGame1.zip)

## Environment

* RenderDoc version: v1.12
* Operating System: windows 10
* Graphics API: DX11 (but other APIs may be affected)

**Comment by baldurk** [comment]
RenderDoc is a debugger only, not a profiler. Specifically profiling workflows are not something I intend to support or work on, and trying to use it that way is known to be problematic or inaccurate for more reasons than just this.

As you've found the discard patterns can be disabled when replaying at the fastest optimisation level, that's intended to be the only toggle for the behaviour in case you don't need the visualisation and want the best replay performance.
