### ISSUE TITLE
VK_DEVICE_LOST when capturing more that one frame

### ISSUE THREAD

**Issue by nickyc95** [baldurk/renderdoc#2185]
## Description
Capturing multiple frames from a vulkan application causes VK_DEVICE_LOST.

## Steps to reproduce
- Run a Vulkan application via RenderDoc
- Set to "Capture 2 Sequential Frames"
- Click capture frames immediately
- See that first capture is fine, but the second thumbnail is black and the contents are broken

I tested on a few different applications and got the same result.
(I have attached the log from capturing Sascha Willems GLTF rendering demo)

![image](https://user-images.githubusercontent.com/7304264/108598212-3ced6400-7384-11eb-9f9d-05ec8e72f2d8.png)

## Environment
RenderDoc version: Tested v1.2 and v1.13 from nightly build
Operating System: Windows 10
Graphics API: Vulkan
Graphics Card: Nvidia GTX 770
Graphics Driver: 461.40 (01/26/2021) (Latest)

[log.log](https://github.com/baldurk/renderdoc/files/6015120/log.log)

**Comment by baldurk** [comment]
I could only repro this on old NV cards, the only one I had was a 970. It looks like an issue to do with the special nv memory types that are only available to images. There was a bug meaning a buffer got bound to them anyway and in certain circumstances on captures after the first (at any time, doesn't have to be sequential) the capture would try to copy out of it and that triggered the device lost.

That commit should fix it and allow multiple captures just fine.
