### ISSUE TITLE
linear size for block compressed dds files is calculated incorrectly

### ISSUE THREAD

**Issue by expenses** [baldurk/renderdoc#2189]
## Description

[This page on the DDS_HEADER structure](https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dds-header) states that `dwPitchOrLinearSize` is 'the total number of bytes in the top level texture for a compressed texture.', however `dwPitchOrLinearSize` is currently calculated based on the texture width and block size, which is incorrect.

https://github.com/baldurk/renderdoc/blob/795d7e0910056bf1971dbb8752581dc5bfa06fdf/renderdoc/common/dds_readwrite.cpp#L771-L777

Instead, it should be something like:

```cpp
header.dwPitchOrLinearSize = RDCMAX(1U, ((header.dwWidth + 3) / 4)) * blockSize * depth * height / 4;
```

This issue is not a huge deal, because the library I am using does not use `dwPitchOrLinearSize` when reading files.

## Steps to reproduce

Save a texture to a dds file and use a tool or library to display the header. For a 128x128x128 BC6H compressed texture I get the following:
```
  Header:
    flags: CAPS | HEIGHT | WIDTH | PIXELFORMAT | LINEARSIZE | DEPTH
    height: 128, width: 128, depth: Some(128)
    pitch: None  linear_size: Some(512)
    mipmap_count: None
    caps: COMPLEX | TEXTURE, caps2 VOLUME
    Pixel Format:
      flags: FOURCC
      fourcc: Some(FourCC(808540228))
      bits_per_pixel: None
      RGBA bitmasks: None, None, None, None
```

where `linear_size` should instead be 128 * 128 * 128 = 2097152.

## Environment

* RenderDoc version: QRenderDoc v1.13 (795d7e0910056bf1971dbb8752581dc5bfa06fdf)
* Operating System: Arch Linux x86_64 5.10.16-arch1-1
* Graphics API: OpenGL 4.6

**Comment by baldurk** [comment]
That is an extremely stupidly specified field. Indeed I looked at what DirectXTex does and it seems like it calculates the slice pitch for block compressed textures, so the linear size you were expecting is also apparently wrong at least for 3D or array textures. Most likely every DDS reader will just ignore that field (at least for compressed textures) as uselessly unreliable.

**Comment by expenses** [comment]
@baldurk okay, thanks!
