### ISSUE TITLE
Suggestion: disable OpenGL support for MacOS

### ISSUE THREAD

**Issue by artyomd** [baldurk/renderdoc#2192]
## Description

I am trying to debug an application under MacOs which uses Vulkan API. When building renderdoc with OpenGL support, all displayed textures are red. Then I tried to disable OpenGL support and everything worked as expected. I just want to suggest disabling OpenGL support for macOS and it will be really helpful in debugging Vulkan applications. Sooner or later Apple will remove OpenGL support :)

## Steps to reproduce

I checked out commit: 0a3a236540ab2f10d81828ba754f81f74d57d4f3 and just build and debug. Attached screendshot with opengl enabled.

## Environment

* RenderDoc version: 0a3a236540ab2f10d81828ba754f81f74d57d4f3
* Operating System: Macos 11.2.2
* Graphics API: Vulkan

![2021-02-28 20 44 44](https://user-images.githubusercontent.com/22776744/109426230-f17f2980-7a05-11eb-8018-7301c762a9d0.jpg)

**Comment by baldurk** [comment]
Mac is not supported in any way, so vulkan and GL are equal in this regard. I will not be making any changes to the build or fixing any bugs on an unsupported platform.
