### ISSUE TITLE
D3D12_PSO_SUBOBJECT type list incomplete

### ISSUE THREAD

**Issue by jdswebb** [baldurk/renderdoc#2193]
## Description

The switch statement at:

https://github.com/baldurk/renderdoc/blob/a083680b08290541e50f1c9a3c79668769f8b364/renderdoc/driver/d3d12/d3d12_common.cpp#L1022

Is missing the following entries:

        D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_AS	= 24,
        D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_MS	= 25,

This means that PSO streams using these types will cause RenderDoc to fail with (e.g.):

d3d12_common.cpp(1172) - Error   - Unknown subobject type 25

## Steps to reproduce

- In any D3D12 application, call CreatePipelineState() on a D3D12_PIPELINE_STATE_STREAM_DESC which contains either of these subobject types.
- Run with RenderDoc and observe previously mentioned error.

## Environment

* RenderDoc version: 1.12
* Operating System: Windows 10
* Graphics API: Direct3D 12

**Comment by baldurk** [comment]
Is it valid to pass those subobjects when D3D reports no mesh shading support? RenderDoc reports that, and I assumed that meant it was invalid to call any mesh shading functions or pass any mesh shading data to the API.

How do you query to know if you're running on D3D12 where mesh shading is allowed? Is there anything other than `D3D12_FEATURE_D3D12_OPTIONS7`?

**Comment by jdswebb** [comment]
I don't know the answer to the first question but I will try to find out. I only have hardware that supports it so haven't hit that case.

I'm using `D3D12_FEATURE_D3D12_OPTIONS7` and that's the only way of querying it that I'm aware of.

**Comment by baldurk** [comment]
When running under RenderDoc you should see that mesh shading is explicitly listed as unsupported inside the `D3D12_FEATURE_D3D12_OPTIONS7`. Is your code checking for that support before passing in mesh shaders?

FYI even if it is somehow valid (knowing D3D12 being consistently messy this may be the case), it's only going to mean that I print a _different_ error message that's more specific and still fail the `CreatePipelineState`.

**Comment by jdswebb** [comment]
Ah sorry, I hadn't realised that running under RenderDoc would actually cause a different return value on the query. When the query returns that there is no support, the engine will not actually create any mesh shaders, the struct just still exists in the PSO_STREAM with the shader set to null.

I asked @turanszkij about this who develops the engine I am trying to run. He has used a 1070 GTX under this scheme without any issue. He also asked on the DirectX discord where a MS employee responded that they thought it should be valid if there is no output from the debug layer (there is not) and if the Windows version is recent enough to support mesh shaders. This is probably as concrete of an answer as I can find.

A more specific error message would be helpful enough I think if that seems the best solution to you - it is easy enough to elide the subobjects when support is no available :).

**Comment by turanszkij** [comment]
```cpp
struct PSO_STREAM
{
	CD3DX12_PIPELINE_STATE_STREAM_ROOT_SIGNATURE pRootSignature;
	CD3DX12_PIPELINE_STATE_STREAM_VS VS;
	CD3DX12_PIPELINE_STATE_STREAM_HS HS;
	CD3DX12_PIPELINE_STATE_STREAM_DS DS;
	CD3DX12_PIPELINE_STATE_STREAM_GS GS;
	CD3DX12_PIPELINE_STATE_STREAM_PS PS;
	CD3DX12_PIPELINE_STATE_STREAM_RASTERIZER RS;
	CD3DX12_PIPELINE_STATE_STREAM_DEPTH_STENCIL DSS;
	CD3DX12_PIPELINE_STATE_STREAM_BLEND_DESC BD;
	CD3DX12_PIPELINE_STATE_STREAM_PRIMITIVE_TOPOLOGY PT;
	CD3DX12_PIPELINE_STATE_STREAM_INPUT_LAYOUT IL;
	CD3DX12_PIPELINE_STATE_STREAM_IB_STRIP_CUT_VALUE STRIP;
	CD3DX12_PIPELINE_STATE_STREAM_DEPTH_STENCIL_FORMAT DSFormat;
	CD3DX12_PIPELINE_STATE_STREAM_RENDER_TARGET_FORMATS Formats;
	CD3DX12_PIPELINE_STATE_STREAM_SAMPLE_DESC SampleDesc;
	CD3DX12_PIPELINE_STATE_STREAM_SAMPLE_MASK SampleMask;

	CD3DX12_PIPELINE_STATE_STREAM_MS MS;
	CD3DX12_PIPELINE_STATE_STREAM_AS AS;
} stream = {};
```

The PSO desc structure is defined at compile time in this case to allow attaching mesh shader if requested. It is null initialized by default. If there is no mesh shader support, it is still valid to create the pso with this struct. It is not valid if we initialize `MS` or `AS` fields but there is no mesh shader support. This needs driver support for this version of the API and a recent win10 version.

The workaround is to dynamically create the stream and only add the fields that are really needed. It is only a bit more inconvenient, but we can fix on our side easily.

**Comment by baldurk** [comment]
Right, RenderDoc intercepts the D3D calls for feature support and intends to act like a driver/runtime version that does not support features like this which I don't support, even when the driver does support them.

If I understand right your code only runs on bleeding edge versions of win10 where even if the hardware doesn't support it, the runtime does support it enough to be able to parse and ignore those empty subobject fields? And it would crash/misbehave if running on another win10 version? I was wondering if there was a graceful query for that, but I guess there probably isn't.

I can definitely add support for parsing those subobjects and should be able to ignore them if they're empty at least.

**Comment by turanszkij** [comment]
Yes, in our case we rely on bleeding edge win/driver version. If I understand correctly, we can assume in this case that this is the same problem as running on outdated driver, so it's our problem to handle this correctly.

**Comment by baldurk** [comment]
That commit should handle the subobjects and ignore the AS/MS fields if they're empty. It will also properly detect if they're non-empty and fail the pipeline create. I can't test it because I don't run a windows version that supports those subobjects so I get something familiar looking like this:

```
D3D12 ERROR: ID3D12Device::CreatePipelineState: Unknown Subobject Type detected in stream: UNKNOWN (25) [ STATE_CREATION ERROR #1019: CREATEPIPELINESTATE_UNKNOWN_SUBOBJECT]
D3D12 ERROR: ID3D12Device::CreatePipelineState: Stream parsing failed. [ STATE_CREATION ERROR #1021: CREATEPIPELINESTATE_INVALID_STREAM]
```

**Comment by jdswebb** [comment]
Thanks! I've tested it and when the MS is empty I can now run with RenderDoc fine. If the MS is non-empty I see the expected error:

`RDOC 026720: [15:55:58]     d3d12_common.cpp(1184) - Error   - MS passed to D3D12_PIPELINE_STATE_STREAM_DESC but mesh shaders not supported`

**Comment by Alekssasho** [comment]
@baldurk When will mesh shaders be supported ?

**Comment by baldurk** [comment]
I currently have no plans to look at mesh shaders so I can't give a timeline of when they may be supported.

Please do not comment on old bugs that have been resolved.
