### ISSUE TITLE
Not able to attach to simple gl es program on Raspberry Pi.

### ISSUE THREAD

**Issue by Fredrum** [baldurk/renderdoc#2194]
## Description
I built renderdoc today on My Raspberry Pi4b running 32bit Raspbian Buster.
This was the latest commit when I cloned the renderdoc source: 741b2c1671bcc615a3ccdaae4bd803e213febe28
The build seemed to go fine.

But I'm not able to attach to a simple Gl ES 3 program that I'm working on. My program takes video images from a camera and uses dmabuf'ers to pass to gl texture making using eglCreateImageKHR(). Then I run a fragment shader and display the result to a some flat polygons in a glfw window.

I'm also creating a bunch of fbo's + render target textures but those are currently not in use.

Using qrenderdoc.

Here's a link to the renderdoc log output,
https://pastebin.com/ZfxJf0sz

I tried to launch+attach using the default setttings.
I also tried a few seconds debugger delay.

I can see two errors that log but I don't know what they mean or if they are what causes it not to attach.

Would renderdoc be sensitive to the type of compositor/KMS ?

## Environment

* RenderDoc version: commit   741b2c1671bcc615a3ccdaae4bd803e213febe28
* Operating System: Raspbian Buster 32 bit.
* Graphics API: OpenGL ES 3.1 Mesa 19.3.2,  Renderer: V3D 4.2, no Vulkan stuff.
* Kernel version:   Linux raspberrypi 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux

Cheers
Fred

**Comment by baldurk** [comment]
RenderDoc does not support ARM on linux, it only supports 64-bit x86 architectures.
