### ISSUE TITLE
Can't get right albedo texture for some objects

### ISSUE THREAD

**Issue by x1ngzai** [baldurk/renderdoc#2198]
## Description

I used renderdoc to capture a frame in a game.Then i used renderdoc to open that rdc file.
But only for some accessories of the body.Like for this shoulder pad in the picture,there's no right albedo texture in the input texture of it(in the texture viewer).You can see the first albedo texture is almost red.But for other objects except these accessories are all right.
Could you give me some ideas to solve it?

## Environment

* RenderDoc version: 1.11
* Operating System: win10
* Graphics API: D3D11
<img width="596" alt="1" src="https://user-images.githubusercontent.com/21998571/110230939-db1e2400-7f57-11eb-9f9a-4c456d3fe5d3.png">
<img width="155" alt="2" src="https://user-images.githubusercontent.com/21998571/110231150-33095a80-7f59-11eb-978a-1842b8ce477c.png">

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
