### ISSUE TITLE
API Calls: Access masks should be displayed as text strings, instead of ints

### ISSUE THREAD

**Issue by DominikWitczakAMD** [baldurk/renderdoc#220]
With the latest build created from the master, if I try to have a look at the arguments passed to a vkCmdPipelineBarrier() call, I get this:

![image](https://cloud.githubusercontent.com/assets/17761066/13701551/fe3a1cda-e788-11e5-8d2a-2251d48d2433.png)

Since I don't have the access mask bit values learned by heart, it would be of tremendous value if we could replace these with human-readable text strings :)

**Comment by baldurk** [comment]
Ah this shouldn't be hard to fix, I just need to cast the VkFlags (which is just typedef'd to uint32 so I cannot serialise it as strings) to a VkFlagBits, then just handle multiple flags being set. I do it for some other flag types.

**Comment by baldurk** [comment]
![image](https://cloud.githubusercontent.com/assets/661798/13715806/7a1b37d2-e7d7-11e5-8170-7fbad3b8ebe3.png)

**Comment by DominikWitczakAMD** [comment]
Awesome :)
