### ISSUE TITLE
Minor typo in Insert menu of custom shader

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#2201]
## Description

There is a typo in one of the menus

## Steps to reproduce

Go to the menu and look at screenshot

![image](https://user-images.githubusercontent.com/700032/110250056-550ed700-7f71-11eb-8a30-6e36c02cd6b9.png)

## Environment

* RenderDoc version: 1.12/nightly
* Operating System: Windows 10
* Graphics API: all

**Comment by baldurk** [comment]
Fixed in that commit, thanks for the report.
