### ISSUE TITLE
Unexpected xoffset (128) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)

### ISSUE THREAD

**Issue by zhouhuamin** [baldurk/renderdoc#2209]
## Description

When grabbing the two-dimensional texture array case, the following warning message was encountered:
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (768) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (896) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (0) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
## Steps to reproduce

ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (768) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (896) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (0) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (768) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (896) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (0) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (768) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (896) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (0) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (768) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (896) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (0) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (768) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (896) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (0) and/or yoffset (640) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (640) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (640) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (640) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (640) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (640) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (768) and/or yoffset (640) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (896) and/or yoffset (640) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (0) and/or yoffset (768) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (768) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (768) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (768) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (768) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (768) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (768) and/or yoffset (768) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (896) and/or yoffset (768) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (0) and/or yoffset (896) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (896) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (896) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (896) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (896) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (896) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (768) and/or yoffset (896) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (896) and/or yoffset (896) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (768) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (896) and/or yoffset (0) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (0) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (768) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (896) and/or yoffset (128) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (0) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (768) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (896) and/or yoffset (256) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (0) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (768) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (896) and/or yoffset (384) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (0) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (128) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (256) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (384) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (512) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
ADRD 010452: [03:21:28] gl_texture_funcs.cpp(3633) - Warning - StoreCompressedTexData: Unexpected xoffset (640) and/or yoffset (512) (tex:ResourceId::378, target:GL_TEXTURE_2D_ARRAY)
## Environment

* RenderDoc version: RenderDoc v1.12 Windows 64-bit Release (40b86b63fbb990b26cc083ced32cb55f11ad263c)
* Operating System: win 10
* Graphics API: OpenGL ES 3.2

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Leaving the provided section headers but ignoring what they mean is not any better than ignoring the template entirely. When asked for steps to reproduce, pasting a partial log output with no context is not acceptable and gives me very little to work with. It's especially unhelpful to paste the same log again under the description. You must give actual information about what you are doing and what I can do to reproduce it - as mentioned in [the documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) I understand that it is not always possible due to privacy or other issues to share the exact reproducible case but when that is true you must provide as much information as you can about what you're doing.

You have been asked repeatedly before to [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open issues which follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion. If you open another issue that is badly formatted or does not provide useful information I will temporarily block you.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
