### ISSUE TITLE
VK_KHR_synchronization2 support

### ISSUE THREAD

**Issue by HurricanKai** [baldurk/renderdoc#2212]
## Description
I would like the Vulkan `VK_KHR_synchronization2` extension to be supported. It simplifies and improves synchronization in Vulkan, and I'd expect lots of applications to use it in the future, so I believe Renderdoc support would make sense.

## Environment
* RenderDoc version: RenderDoc v1.12 Release (40b86b63fbb990b26cc083ced32cb55f11ad263c)
* Operating System: Windows 10
* Graphics API: Vulkan 1.2.170.0

**Comment by baldurk** [comment]
This has already been implemented, shortly after the extension came out: 5cb9b90f5fb5c5ebb0d2c3ad3bcceff488c5d00e

It's available in any recent nightly build and it will go into the next stable version when that is released.
