### ISSUE TITLE
Renderdoc may crash by memory overwrite.

### ISSUE THREAD

**Issue by freecnjet** [baldurk/renderdoc#2219]
## Description
Our project update to UE4.26.1, one of our material use some material parameter collection, as we all know, which will cause too much constant buffer used on pixel shader(DX11 API).  To resolve the crash we change the maximum constant buffer count from 14 to 24. UE4 can run correctly. But if we enable RenderDoc plugin, it crash again. After using source code to verify, we found constant buffer array was over write and next area value changed.
    UINT CBCounts[D3D11_COMMONSHADER_CONSTANT_BUFFER_API_SLOT_COUNT];                        <---------Over write
    ID3D11ShaderResourceView *SRVs[D3D11_COMMONSHADER_INPUT_RESOURCE_SLOT_COUNT];

I know D3D11_COMMONSHADER_CONSTANT_BUFFER_API_SLOT_COUNT is a standard limitation. But if the tracking code can show some error directly instead of unexpected error. 

## Steps to reproduce
Using more than 14 const buffer on a pixel shader by DX11 API.

## Environment

* RenderDoc version: 1.12
* Operating System: Windows 10
* Graphics API: Direct3D 11

Because our project use Renerdoc frequently, if it possible, I can help to add some code to avoid crash. Thanks in advance.

**Comment by baldurk** [comment]
Using more than 14 constant buffers in DX11 is illegal use of the API and will trigger validation errors. RenderDoc does not handle invalid use of the API, you need to run your application through the API validation and fix any invalid use before using RenderDoc.

**Comment by freecnjet** [comment]
Thanks baldurk, you are right, we have submit a issue to UE4 team.
