### ISSUE TITLE
Visual Studio 2015 Warnings after upgrade

### ISSUE THREAD

**Issue by null77** [baldurk/renderdoc#222]
When opening the solution for the first time, and building in Release/Win32, I got the following:

1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): error C2220: warning treated as error - no 'object' file generated
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): error C2220: warning treated as error - no 'object' file generated (compiling source file minidump_generator.cc)
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file minidump_generator.cc)
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file minidump_generator.cc)
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): error C2220: warning treated as error - no 'object' file generated (compiling source file client_info.cc)
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file client_info.cc)
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file client_info.cc)
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): error C2220: warning treated as error - no 'object' file generated
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): error C2220: warning treated as error - no 'object' file generated (compiling source file crash_generation_server.cc)
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file crash_generation_server.cc)
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file crash_generation_server.cc)
4>------ Build started: Project: renderdoc, Configuration: Release Win32 ------
4>LINK : fatal error LNK1181: cannot open input file 'C:\src\renderdoc\\renderdoc\3rdparty\breakpad\Win32\Release\crash_generation_client.lib'
5>------ Build started: Project: renderdoccmd, Configuration: Release Win32 ------
5>  renderdoccmd_win32.cpp
5>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): error C2220: warning treated as error - no 'object' file generated
5>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
5>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
========== Build: 0 succeeded, 5 failed, 11 up-to-date, 0 skipped ==========

It seems to be all in a Windows header, but obviously doesn't build out of the box on this system.

**Comment by zao** [comment]
Does it also do this if you move the solution to the 10.0.10240.x or 10.0.10586.0 SDKs?
I've always handpatched away the warnings in dbghelp.h and suchlike in previous builds of my software, as they to my knowledge are not circumventable.

**Comment by null77** [comment]
Created pull request 223: https://github.com/baldurk/renderdoc/pull/223

**Comment by baldurk** [comment]
This is kind of ridiculous that microsoft haven't fixed this. I remember encountering this before win10 came out in one of their pre-release SDKs and I assumed it'd be fixed by release.

RE: The pull request I'd rather not make that change everywhere, especially if it's needed in breakpad - I avoid making non trivial in-repo changes to external libraries so in that case it'd need to have a separate fork set up, apply the changes, and sync to my fork.

I think a better solution is as @zao suggested, just hand-patch the warnings in dbghelp.h and include it in renderdoc's source tree and `#include` that. It's a bit more awkward to find a location since it's needed in several different places. I think the best place is to put it in `renderdoc/3rdparty/dbghelp/dbghelp.h` and instead of doing the `#pragma push/pop` dance you'd do `#include dbghelp/dbghelp.h` - I think all projects should have `renderdoc/3rdparty` in their include search path. Maybe pdblocate won't, in which case just add it.

Not a particularly pleasant solution, but that's how it works cleaning up someone else's mess :(.

**Comment by null77** [comment]
I'm a bit concerned that including DbgHelp.h from a particular Windows SDK version might cause problems with other Windows SDK versions... do you have any testing to cover this? I don't want to break something down the line.

Alternately we could simply suppress this warning in the breakpad project and use the push/pop in the renderdoc-owned code. (Sorry, I hadn't noticed that you pull in some third party code)

**Comment by baldurk** [comment]
Yeh I can understand that. It should be fine though as I already ship a bunch of sdk headers for d3d to remove dependency on the sdk. The dbghelp api is stable so there shouldn't be any issue.

**Comment by Anteru** [comment]
Why not simply have a `rd_dbghelp.h` which solely consist of the `#pragma` to disable warnings and includes the MSFT `<dbghelp.h>`? That way you don't have a local copy, and you can protect the pragmas with a version check, and warnings are fixed as well.

**Comment by baldurk** [comment]
Closing this issue as code compiles without warnings now (I think appveyor builds as VS2015. Or at least as VS2013 maybe). Let me know if you're still running into any build failures.

**Comment by monajalal** [comment]
```
1>------ Build started: Project: spirv, Configuration: Debug Win32 ------
2>------ Build started: Project: crash_generation_client, Configuration: Debug Win32 ------
3>------ Build started: Project: crash_generation_server, Configuration: Debug Win32 ------
4>------ Build started: Project: exception_handler, Configuration: Debug Win32 ------
2>  crash_generation_client.cc
4>  exception_handler.cc
3>  client_info.cc
3>  minidump_generator.cc
3>  crash_generation_server.cc
1>  PpTokens.cpp
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): error C2220: warning treated as error - no 'object' file generated
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): error C2220: warning treated as error - no 'object' file generated (compiling source file minidump_generator.cc)
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file minidump_generator.cc)
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file minidump_generator.cc)
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): error C2220: warning treated as error - no 'object' file generated (compiling source file client_info.cc)
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file client_info.cc)
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file client_info.cc)
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): error C2220: warning treated as error - no 'object' file generated (compiling source file crash_generation_server.cc)
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file crash_generation_server.cc)
3>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file crash_generation_server.cc)
4>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): error C2220: warning treated as error - no 'object' file generated
4>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
4>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
1>..\..\..\3rdparty\glslang\glslang\MachineIndependent\preprocessor\PpTokens.cpp(218): error C2220: warning treated as error - no 'object' file generated
1>..\..\..\3rdparty\glslang\glslang\MachineIndependent\preprocessor\PpTokens.cpp(218): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\string.h(119): note: see declaration of 'strcpy'
1>..\..\..\3rdparty\glslang\glslang\MachineIndependent\preprocessor\PpTokens.cpp(223): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\string.h(119): note: see declaration of 'strcpy'
5>------ Build started: Project: renderdoc, Configuration: Debug Win32 ------
5>  core.cpp
5>  win32_callstack.cpp
5>  replay_renderer.cpp
5>  serialiser.cpp
5>serialise\serialiser.cpp(493): error C2220: warning treated as error - no 'object' file generated
5>serialise\serialiser.cpp(493): warning C4456: declaration of 'memoryBufEnd' hides previous local declaration
5>  serialise\serialiser.cpp(493): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
5>  serialise\serialiser.cpp(446): note: see declaration of 'memoryBufEnd'
5>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): error C2220: warning treated as error - no 'object' file generated (compiling source file os\win32\win32_callstack.cpp)
5>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file os\win32\win32_callstack.cpp)
5>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file os\win32\win32_callstack.cpp)
5>replay\replay_renderer.cpp(49): fatal error C1083: Cannot open include file: 'ImfOutputFile.h': No such file or directory
5>core\core.cpp(854): error C2220: warning treated as error - no 'object' file generated
5>core\core.cpp(854): warning C4456: declaration of 'it' hides previous local declaration
5>  core\core.cpp(854): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
5>  core\core.cpp(839): note: see declaration of 'it'
6>------ Build started: Project: renderdoccmd, Configuration: Debug Win32 ------
6>  renderdoccmd_win32.cpp
6>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): error C2220: warning treated as error - no 'object' file generated
6>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
6>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
========== Build: 0 succeeded, 6 failed, 9 up-to-date, 0 skipped ==========
```

I was done with step 5 of OPENEXR preparation and then in the Preparation step 1 which says compile all  of the renderdoc solution I got the above error https://bitbucket.org/visinf/projects-2016-playing-for-data

I have used CMake 3.7.1, Windows 10 Home Edition, Visual Studio 14 2015 Enterprise Edition. Please suggest fix/solution.

**Comment by baldurk** [comment]
It seems like you're building from a fork that doesn't have these fixes. This was already solved above and the appveyor CI builds vs2015 every commit, so it definitely works. You'll have to talk to the people in charge of the fork for issues like this.

**Comment by monajalal** [comment]
![warning_level](https://cloud.githubusercontent.com/assets/1892917/21246848/e43c1d62-c2f0-11e6-9e4c-9625dc3b16de.PNG)
