### ISSUE TITLE
Show indication in GUI if capture is not possible

### ISSUE THREAD

**Issue by DataBeaver** [baldurk/renderdoc#2222]
## Description

RenderDoc requires an OpenGL 3.2+ context to do captures.  If the context is not compatible with capturing, a warning is displayed, but only in the application window.  When working with remote targets it would be nice to have that displayed in the RenderDoc GUI as well (and why not for locally running programs too, for symmetry).

## Environment

* RenderDoc version: v1.13 (69661b0cb)
* Operating System: Debian unstable
* Graphics API: OpenGL

**Comment by baldurk** [comment]
That commit isn't _perfect_, if you have multiple windows some of which use legacy contexts and some use modern ones it will still show up as supported even if the current active window can't be captured. That's a rare case though and this should work for the majority of programs. I have an idea of how I can improve this area of the UI more in future.
