### ISSUE TITLE
Build Android Exception At Win10 System

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#2223]
cmake result: 
![image](https://user-images.githubusercontent.com/81604381/112930021-250bbb80-914c-11eb-85ff-538749746548.png)

 

## Description
execute command error
![image](https://user-images.githubusercontent.com/81604381/112929624-62bc1480-914b-11eb-900b-762ee6f428e7.png)

## Steps to reproduce

![image](https://user-images.githubusercontent.com/81604381/112929733-91d28600-914b-11eb-874f-c9f71312b461.png)

pop a dialog window ， tip “include-bin.exe” not find 

and empty files.
![image](https://user-images.githubusercontent.com/81604381/112929811-b890bc80-914b-11eb-826d-0b1f091c33e5.png)

## Environment
* Android Build
* RenderDoc version: 1.12
* Operating System: win10

**Comment by baldurk** [comment]
Can you please give more information, what do you mean by:

> pop a dialog window ， tip “include-bin.exe” not find

what exactly is the error?

My guess is that when you're building with mingw the include-bin.exe gets a dependency on some mingw DLL which is not available in your default path. Check that in your build environment programs produced with `c++` can be run without any extra setup.

**Comment by ghost** [comment]
solve by  [https://zhuanlan.zhihu.com/p/339673291](https://zhuanlan.zhihu.com/p/339673291)。
maybe environment is incorrect。 Before using the windows version Cmake + mingw-setup， this link using mingw cmake。
It is recommended to provide a complete compilation kit zip。

**Comment by baldurk** [comment]
I'm sorry but I don't understand what you're saying. You don't have to use mingw cmake, I use a normal windows cmake and it works fine.

It sounds like you have it working though so I'm going to close this issue.
