### ISSUE TITLE
Line Numbers Cropped If Many Lines

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#2227]
## Description

This is a cosmetic issue, hopefully not too difficult to fix. A shader with too many lines will hide the lines on the left as shown in the image. Maybe they want to be aligned to the right?

![Shader Line Numbers](https://user-images.githubusercontent.com/700032/113136500-5a330f00-921b-11eb-8a51-6479c19a59bb.png)

## Steps to reproduce

Load shader with more than a thousand lines of code. Line numbers get cropped.

## Environment

* RenderDoc version: 1.13
* Operating System: Windows 10
* Graphics API: D3D12

**Comment by baldurk** [comment]
That commit should properly calculate the size of the margins using the font size, instead of hardcoding it. As a bonus it also scales to 100,000 line shaders!
