### ISSUE TITLE
No capturing child processes

### ISSUE THREAD

**Issue by spiiin** [baldurk/renderdoc#2235]
## Description

I am trying to capture frame for android emulator Nox - https://www.bignox.com/
It create child process NoxVMHandle.exe (look's like it virtual box headless vm, other android emulators works similar), but renderdoc can't capture it (I tried "capture child processes" option, and "enable global hook" option - both didn't work, I use renderdoc 1.13).

Solution for intel gpa - https://community.intel.com/t5/Intel-Graphics-Performance/Unable-to-capture-frame-on-NoxPlayer-Android-Emulator/m-p/1210260#M2025, it can capture child process with "Auto-detect launched applications").

NoxVmHandle can use directx (looks like virtualbox somehow translate android opengl calls to directx) and opengl 4.6 backends for render, but intel gpa only works with directx backend to capture and analyze frames.

Also, looks like some previous pair of versions RenderDoc+Nox was worked together (post in Russian, author only wrote, that he got success to capture frame from Nox with RenderDoc, but he didn't point, what versions of apps he tried :( )
https://uengine.ru/forum/viewtopic.php?p=39804&sid=f6995d42f6067b203fa68ff7c8d0d7f4#p39804

Also, just for clarify - android emulator is windows app, so issue is about windows, not android platform.

Sorry for my english, it's not my native.

## Steps to reproduce
I'm trying to capture - NoxPlayer 7.0.1.0 https://www.bignox.com/ on Windows 10, I tried "capture child processes" option, and "Enable global hook" option - both didn't work (not show injected gui inside application, not show any information about created child process, a)

There is no child proccessed showed, but nox create NoxVMHandle.exe proccess (it can be configured to use opengl 4.6 api, or directx 11 api).
![image](https://user-images.githubusercontent.com/1622049/113516251-e9c12080-9581-11eb-8ac3-bbb2cc88d8fa.png)

## Environment

* RenderDoc version: 1.13
* Operating System: Windows 10
* Graphics API:  OpenGL 4.6, DirectX 11
Nvidia geforce rtx 2060, latest nvidia driver (465.89)

**Comment by spiiin** [comment]
I'll try to provide additional info, if it can help. Looks like issue is about a way to track the start of child processes, but I don't know, what additional information may help, I can't find emulator with open source code to check, what method they are used to create backend vm.

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by spiiin** [comment]
Thank you for your answer. It's possible to explore only my own applications with that way too, without any copyright violations. So it can be legal using that's way?

But Renderdoc can be used to illegal explore commercial windows applications too, as I know, can you explain, what's the difference with using it for android?
