### ISSUE TITLE
Limit the Buffer size in the buffer window

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#224]
When viewing a 128MB buffer, it becomes painful slow.

We actually bind a small fraction of the buffer. For example we may bind 5MB of data as an SSBO in OpenGL, so double clicking on the buffer to view its contents should default to displaying the range of data that was bound and not the whole buffer.

This should also be user-tweakable in case I need to expand my view (or shrink it)

Cheers
Thanks

**Comment by baldurk** [comment]
This did the trick in my artificial test case, let me know how it works for you if you'd want to tweak it.

**Comment by AllianceDarkSylinc** [comment]
Thanks! I'll check it.... on a nightly (I haven't ever compiled it <sad face>) :)

**Comment by darksylinc** [comment]
Sorry for taking this long.

I checked it and it works as requested.
Though it's not entirely intuitive (yet).

Right now it shows the first 200k rows and if you click the yellow message, it shows you the next 200k.
So far so good. But:

1. It would be nice if the UI allowed me to go beyond 200k (it's ok if by default it shows me the first 200k, but if I manually enter 300k, honour that request at my own risk. Give me a warning dialog box if you want)
2. When I double click a buffer it shows "Rows 1440000" (which is the actual length), but it limits to 200k. If I change the format (i.e. type unorm; unorm; unorm; unorm;) and then hit apply, it will show "Rows 200000". This is inconsistent.

The way I see this could be tackled intuitively is if you just add a fourth edit box telling how much it is limited, like in the picture (edited in GIMP):
![limit](https://cloud.githubusercontent.com/assets/3395130/14836343/c58451ae-0be5-11e6-8d89-829dc40c4595.png)

When I click "Show the next 200k" it should advance the Byte Offset and decrease the Rows proportionally (right now the byte offset advances, but the number of Rows remains the same).

So if I just want to see everything in one swoop, I can set the limit to a very large number.

**Comment by baldurk** [comment]
The 200k limit won't be raised - the .NET control simply doesn't handle large numbers of rows or columns, so I don't want people to enter a high number thinking it will be OK if slow, then the whole thing crashing out of nowhere.

I can work on the other improvements though, like maintaining the 'viewed range' as a separate thing from the current 200k window. At the moment they're probably unnecessarily linked.

Can you share that capture btw so that I have a nice test case to work against?

**Comment by AllianceDarkSylinc** [comment]
Sorry! Sure I can upload a capture later (right now not at machine that can take the capture)

**Comment by darksylinc** [comment]
Test case is in #263 the GL version (D3D11 is obviously busted).
Funny thing, I took a capture w/ 0.28 and I realized D3D11 was crashing...

**Comment by darksylinc** [comment]
Btw for your ease the data in that capture is best visualized as ubyte; ubyte; ubyte; ubyte; as in the picture (instead of the default uint RenderDoc gets from reflection - This is ok and it's not a bug)

**Comment by baldurk** [comment]
I punted on this issue for a year on the C# UI, but on Qt it's much easier to fix - the table view handles way more rows or columns with ease, so the 200k row limit is just completely gone and you only have the offset/length defined by the view (or by yourself if you adjust them).

So I think that keeps everyone happy now :). Like I say it's not fixed on the existing UI, but that will be going away soon.

**Comment by baldurk** [comment]
Closing this issue as it's fixed in v0.34 - albeit only in qrenderdoc. As mentioned above though, I'm not going to be doing any significant new work for the C# UI.
