### ISSUE TITLE
Texture Viewer not showing content from scissored renderbuffer read with pixel pack buffer

### ISSUE THREAD

**Issue by tksuoran** [baldurk/renderdoc#2242]
## Description

* I am rendering ID buffer for mouse picking
* Objects / polygons are rendered with unique colors
* For rendering there is an active 64x64 pixel scissor region around mouse pointer
* Rendering happens to a framebuffer with color and depth renderbuffers
* After rendering, pixel pack buffer is bound and both color and depth is asynchronously read from the scissored area
* Four pixel pack buffers are cycled, so next frame does not use the same pixel pack buffer.

## Steps to reproduce

* Download capture from https://neure.dy.fi/erhe.rdc
* Open capture with RenderDoc
* Event Browser, expand Id_renderer::render() content
* There are three glMultiDrawElementsIndirect() calls.
* Examining any of these and their sub-items together with Texture Viewer
* **Expected**: Something should be visible in color/depth outputs
* **Actual:** Color and depth outputs remain black
* Workaround: In Texture Viewer, activate and then deactivate  Viewport/Scissor Region overlay. 

## Environment

* RenderDoc version: v1.13
* Operating System: Windows 10
* Graphics API: OpenGL 4.6
* GL Vendor: NVIDIA Corporation
* GL Renderer: GeForce RTX 3090/PCIe/SSE2
* GL Version: 4.6.0 NVIDIA 461.40
* GLSL Version: 4.60 NVIDIA

**Comment by baldurk** [comment]
I wasn't aware that it's valid to call `glRenderbufferStorageMultisample` with samples=0, but the spec explicitly calls this out as being equivalent to creating a non-multisampled render buffer with `glRenderbufferStorage`. That commit should fix the handling and it displays the contents of the texture in the capture correctly for me now.
