### ISSUE TITLE
Vulkan: Shader debugging with input attachments

### ISSUE THREAD

**Issue by luc4s** [baldurk/renderdoc#2247]
## Description
Hello,
I have a render pass which consists of 4 subpasses (implementation of order independent transparency), 2 of these subpasses reads from the other two subpass color attachments as input attachments.

Now, I want to debug the shader of one of these subpass that has two input attachments. The problem is that the displayed values in the shader do not reflect what the input attachment actually contains (texture viewer shows correct values though).

## Steps to reproduce

1. In provided capture, select any draw event in color pass #2, preferably near end of pass, e.g. event 666
2. In texture viewer, show output color attachment
3. Select any pixel (right click) in drawing zone, e.g. 560;449
4. Show history (first issue: history is showing input/output pixel values as 'Unavailable')
5. Debug pixel of any event related to a draw command, e.g. EIG 616
6. In shader debugging, press Run forwards
7. In high level variables, `b0 = (0, 0, 0, 0)`, but should be `(4.52353, 0.71981, 0.41018, 0.16476)` (can be checked in texture viewer)

Capture file:
[DebugInputAttachment.zip](https://github.com/baldurk/renderdoc/files/6323880/DebugInputAttachment.zip)

## Environment

* RenderDoc version: 1.13
* Operating System: Windows 10
* Graphics API: Vulkan 1.2.154.1
* GPU: NVidia quadro P2000
* Driver version: 451.48

**Comment by baldurk** [comment]
This was caused by the pixel-relative co-ordinates not being properly transformed, so it was reading from 0,0 in the source texture. That commit should fix it.
