### ISSUE TITLE
GPU Selection with Nvidia Optimus

### ISSUE THREAD

**Issue by kyamant** [baldurk/renderdoc#2250]
## Description
When I run Sascha Willems' Vulkan samples in VisualStudio or simply the executable(s), they run on the Nvidia GPU. When I run them through RenderDoc v1.12 they run on the Intel GPU (unless I explicitly make the executable to use Nvidia through Nvidia Control Panel)
## Steps to reproduce
On a laptop with Nvidia Optimus:
Take the subpass example of Sascha Willems'. It has debug markers.
The GPU selection in the samples is straightforward: picks the first device from vkEnumeratePhysicalDevices()  (how could that change through RenderDoc?)
Setting RenderDoc to run with Nvidia GPU (from explorer or from nvidia control panel) does not change this behavior.

## Environment
* RenderDoc version: 1.12
* Operating System: Windows 10
* Graphics API: Vulkan 1.2.162.1
* Nvidia 1050Ti: 461.92
* Intel HD Graphics 630: 27.20.100.9466
* From Vulkan Configurator:
_Physical Devices:
   - GeForce GTX 1050 Ti (Discrete GPU) with Vulkan 1.2.155
   - Intel(R) HD Graphics 630 (Integrated GPU) with Vulkan 1.2.170_

**Comment by baldurk** [comment]
RenderDoc disables the nvidia optimus layer since it can cause bugs. It's up to the application to select the appropriate physical device that it wants on vulkan.
