### ISSUE TITLE
SIGSEV on Fedora 34 - rdclog_filename()

### ISSUE THREAD

**Issue by pumkinpal** [baldurk/renderdoc#2262]
## Description

Both qrenderdoc and rendedoccmd crash on launch on Fedora 34 after receiving SIGSEV.
From GDB the crash seems to be occuring in `rdcstr`'s copy constructor called from `rdclog_filename`. I've attached a copy of the backtrace GDB outputs.
[gdb.txt](https://github.com/baldurk/renderdoc/files/6396372/gdb.txt)

## Steps to reproduce

Run any renderdoc command whether it be renderdoccmd or qrenderdoc. The crash even occurs when running the --help command.

## Environment

* RenderDoc version: 1.10 (package version is 1.10-2.fc34.x86_64
* Operating System: Fedora 34
* Graphics API: Any

**Comment by pumkinpal** [comment]
Just an update:
I compiled v1.10 myself and it runs fine which led me to suspect that the bug may be related to LTO being enabled by default for Fedora packages. I managed to recreate the crash by rebuilding renderdoc with LTO enabled (GCC).

I'm not sure if you want to consider this a packaging issue, if so feel free to close the issue and I'll instead file a bug with Fedora to opt-out of LTO for the Renderdoc package.

**Comment by baldurk** [comment]
I do not provide any support for distribution packages. If you can't reproduce the issue on a source build of RenderDoc then indeed this is not my bug.

**Comment by pumkinpal** [comment]
Just to be clear, I did manage to reproduce the crash myself by building v1.10 from source and enabling LTO. Does this mean that compiling renderdoc with LTO enabled is not supported? Either way thanks for the quick reply.

**Comment by baldurk** [comment]
You're welcome to customise the build however you like, but if you run into problems then it's up to you to investigate and either find fixes or disable those changes. I only support the build as it comes by default with no modifications, on any compiler above the minimum requirements. I cannot feasibly support all possible compilers as well as all possible custom invocations or flags.

**Comment by ohsix** [comment]
to be clear, if any of these options are changed the build is not supported?

https://github.com/baldurk/renderdoc/blob/v1.x/CMakeLists.txt#L179

**Comment by baldurk** [comment]
Those options disable certain components and it's fine to turn them off if you want to build without them. Passing custom compiler or linker arguments is not supported.

Please don't comment on old resolved issues in future.
