### ISSUE TITLE
Add support for (What If) scenarios

### ISSUE THREAD

**Issue by SergioAlapontARM** [baldurk/renderdoc#2264]
## Description

It would be really useful to have these "What If" scenarios (like console graphics debuggers/profilers) that allow you to configure some aspects of the rendering pipeline and replay the frame with these to see how the new configuration affects the quality. Some of the features I refer to are:
- Allow to change the resolution of a particular RenderTarget (or RTs within a framebuffer talking in terms of the Vulkan limitations).
- Configure a particular SamplerState
- Configure Blending, Raster, Depth test configuration for a graphics pipeline
- ...

This would come really handy to do quick experiments without needing to go to the source of the engine and change these which sometimes can be trickier to do depending on how the configuration of these within the engine is abstracted.

## Environment

* RenderDoc version: v1.12
* Operating System: Windows 10
* Graphics API: Vulkan

**Comment by baldurk** [comment]
RenderDoc is not a profiler, so performance analysis features like this are not considered in scope.
