### ISSUE TITLE
`GL_ONE` and `GL_ZERO` misinterpreted when used with `glBlendFuncSeparate`

### ISSUE THREAD

**Issue by diaphore** [baldurk/renderdoc#2265]
## Description

RenderDoc misinterprets `GL_ONE` and `GL_ZERO` when called with `glBlendFuncSeparate` :

## Steps to reproduce

```C
glBlendFuncSeparate(GL_ONE, GL_ZERO, GL_ONE, GL_ZERO);
```

<img width="142" alt="Screenshot 2021-04-30 155332" src="https://user-images.githubusercontent.com/10867111/116705312-ae711080-a9cc-11eb-8437-e43c54fbecb8.png">

## Environment

* RenderDoc version: 1.13
* Operating System: Windows 10
* Graphics API: OpenGL

> GL_VENDOR = NVIDIA Corporation
> GL_RENDERER = NVIDIA GeForce GTX 970/PCIe/SSE2
> GL_VERSION = 4.6.0 NVIDIA 466.11

**Comment by baldurk** [comment]
This is a design flaw in GL, as these "enums" (not actual enums, just defines) have the same value - 0x1 and 0x0. The automatic stringification in the serialisation can't tell the difference and this is not worth adding a bunch of manual fixups for.

The blend function is displayed correctly in the pipeline state viewer along with the other state, which is the recommended place to get this information.
