### ISSUE TITLE
Color values in sRGB textures: which color space?

### ISSUE THREAD

**Issue by jweg** [baldurk/renderdoc#227]
In a fragment shader, I output the hard-coded color (0.3333, 1, 0.6666, 1). This gets written to a texture w/ format SRGB8_ALPHA8 with `GL_FRAMBUFFER_SRGB` enabled. The color should therefore be interpreted as linear and converted to sRGB before storing in the texture (if my mental model isn't completely off again).

However, RenderDoc shows me a color value of (0.33203, 1, 0.664, 1). This looks a lot like it (or someone else) applied the reverse transformation automatically. Is this the case? I'm struggling to understand our sRGB issues as it is and it'd be really helpful to see the raw values as they are stored in the texture.

**Comment by baldurk** [comment]
Sorry, I've been laid up with a nasty cold so I didn't reply earlier. Yes the values that RenderDoc displays should be the actual "values" of the pixels. Which means if a texture is marked as using SRGB storage, the values are decoded appropriately before being displayed.

So basically a value of 0.5 should always be displayed as 0.5, whether it's stored as 189 in SRGB 8-bit, or 127 in linear 8-bit, or 0x3800 in half floats.
