### ISSUE TITLE
Improve UI for Environment Variables

### ISSUE THREAD

**Issue by StefanoLanza** [baldurk/renderdoc#2274]
## Description

Under the Launch Application tab you can list environment variables for your application. May I suggest these improvements:
* It should be possible to maximize the environment variables window. By default it opens with a small size, which is annoying when you are editing long values (e.g. PATH). Also, the window does not remember its previous size.
* Environment variables should be able to include and expand other environment variables e.g.
```
 ANOTHER_PATH   Set     someFolder
 PATH           Append  %ANOTHER_PATH%
```
For PATH to be correctly set, I had to expand  ANOTHER_PATH manually. That is unexpected behaviour.
* In the UI, it should be possible to append multiple values to the same var:
```
  PATH Append   someFolder
  PATH Append   anotherFolder
```
## Environment

* RenderDoc version: 1.13
* Operating System: Windows 10
* Graphics API: OpenGL

**Comment by baldurk** [comment]
I appreciate that the environment variables editor is quite basic and these would be good improvements, but it's intended for simple setups only and the value in having a complex editor seems low to me. There are additional complexities to handle such as when nested environment expansions happen that are not trivial to resolve. I'd accept a pull request if someone else wanted to implement these changes, but this is low priority enough that it's effectively not something I would ever implement myself so I'm going to close the issue.

Instead I would recommend that if your program requires a complex environment setup that you create a wrapper batch file or other script, and then launch that with child process capture enabled. That way you can do whatever setup you like with the full flexibility of a script/shell language.
