### ISSUE TITLE
Improved "Find All" text search with double click & highlight

### ISSUE THREAD

**Issue by BBI-JohnwillKeating** [baldurk/renderdoc#2277]
## Description

When debugging a pixel and tracing through the shader code, it would be useful to perform a "Find All" text search and then highlight all the text matches in the main code window with a bright color, similar to Visual Studio.  Also, would be useful if I could double click one of the find results in the search window and have the cursor jump to that line of code in the main code window.
This workflow arises when I'm trying to figure out where in a large shader file a particular variable is being modified.  See the attached image for what I mean by highlighting and performing a text search.
![image](https://user-images.githubusercontent.com/75271593/118556491-cceb4180-b718-11eb-9503-14e7c583fb50.png)

## Environment

* RenderDoc version: 1.13
* Operating System: Windows10
* Graphics API: DirectX

**Comment by baldurk** [comment]
I'm not sure I quite follow, is the only thing you're asking for to be able to double click on the results to jump to the matching lines? Since the find all feature already highlights matches as shown in your screenshot.

**Comment by BBI-JohnwillKeating** [comment]
Yes, I'd like to be able to double click on the search results to jump to the matching lines.  This is a feature common to other IDEs that I've become used to, and I really notice when it's missing.  The text highlighting already exists (as you pointed out) but it would be better if it was a brighter color (like orange) so the matches can be easily seen at a glance when scrolling quickly through pages of text.  I often don't notice the light grey if I'm scrolling fast.

**Comment by baldurk** [comment]
OK I understand, I was a bit confused because the description read to me like you were asking for both features as if they didn't exist.

Being able to jump to search results is a fair improvements, but I'm not sure I'll change the colour as that kind of thing can be very subjective. In an ideal world all the colours would be fully customisable but that is a bunch of UI work that is not high priority.

**Comment by baldurk** [comment]
That commit will allow you to double click on any results and jump to where they are. The colour of the results highlight has been slightly tweaked also.

**Comment by BBI-JohnwillKeating** [comment]
Thank you!
