### ISSUE TITLE
MaskOverlayBits doesn't turn off overlay on Vulkan

### ISSUE THREAD

**Issue by Reedbeta** [baldurk/renderdoc#2279]
## Description

We have a bgfx-based app. When we start up, bgfx loads renderdoc.dll and calls `MaskOverlayBits(0, 0)` to turn off the in-app overlay. In the DX11/12 backends this works as expected. But when we run the Vulkan backend, the overlay continues to show up and seemingly cannot be turned off.

bgfx currently calls `MaskOverlayBits` prior to device creation, but I have tried moving the call after device creation (and even repeating it on every frame), but the results are the same.

## Steps to reproduce

This can be reproduced on the bgfx example apps, such as `example-01-cubes`. On Windows, build the Debug x64 version of the app and copy renderdoc.dll to the `.build\win64_vs2019\bin` directory. Launch the app from Visual Studio; it will use DX11 by default and the RenderDoc overlay won't be visible. Change the command line arguments to `--vk`. Launch again and now the overlay shows up, even though it shouldn't:

![bgfx example-01-cubes running on VK backend with overlay visible](https://user-images.githubusercontent.com/1578730/118900446-d239bf00-b8c5-11eb-85a6-77958c213d3a.png)

For reference, bgfx calls `MaskOverlayBits` from the `loadRenderDoc()` function in `src\debug_renderdoc.cpp`.

## Environment

* RenderDoc version: v1.13
* Operating System: Win10 20H2
* Graphics API: Vulkan 1.2

**Comment by baldurk** [comment]
You mention copying the renderdoc.dll around in your reproduction steps. You should absolutely not do this as it is not supported and it will break things - especially for vulkan where the layer registration and paths is especially important.

Does this problem still happen if you don't copy renderdoc.dll out of RenderDoc's installation and instead use `GetModuleHandle` or equivalent to obtain the module handle once the program is launched from RenderDoc?

**Comment by Reedbeta** [comment]
> Does this problem still happen if you don't copy renderdoc.dll out of RenderDoc's installation and instead use `GetModuleHandle`

Nope, that solved the problem for the case where the app is launched from RenderDoc!

> You should absolutely not do this as it is not supported and it will break things

OK. I guess I thought copying the dll was the standard way for apps to load it even if they're not being launched from RenderDoc. Should I rather add the RenderDoc directory to my PATH?

**Comment by baldurk** [comment]
No copying the dll around has never been supported.

It should work to add RenderDoc to your PATH though I wouldn't necessarily recommend it as it may have other side-effects (e.g. programs using RenderDoc's version of Qt or d3dcompiler etc). I'd suggest either locating RenderDoc through a config option in your program or through looking up its location in the registry, but generally speaking the best option is to launch your program from RenderDoc as that is the only way to ensure it is reliably launched.

**Comment by Reedbeta** [comment]
OK. You might want to chat with @bkaradzik about how it's done in bgfx, as it simply does `LoadLibrary("renderdoc.dll")`, and from what you're saying that seems wrong now. In any case, thanks for the help. :)

**Comment by baldurk** [comment]
Nothing has changed, that _can_ work and is how e.g. the unity and UE4 integrations function, but it's intended only for advanced users who know exactly what they're doing. It's too easy to get wrong so I can't feasibly support it. Copying renderdoc.dll around has never been supported though and as you've found that can cause problems especially on vulkan, you still have to load the correct renderdoc.dll from its normal location.

I don't have any association with bgfx, so if there's a bug in bgfx's renderdoc integration you'd need to report that to them.
