### ISSUE TITLE
Support capturing android services using vulkan

### ISSUE THREAD

**Issue by bethau** [baldurk/renderdoc#2281]
## Description

We have an service running on android which uses the Vulkan API for rendering operations. We would like to use RenderDoc to capture frames from this service to be able to debug it the same way we debug regular android apps. RenderDoc currently only allows to debug activities which have a launch target. Debugging services is not supported.

There are two possible ways RenderDoc could go about this:
* RenderDoc launches the service and inserts the required hooks during startup
* RenderDoc supports attaching to an already running android process and inserts the hooks later.

## Environment

* RenderDoc version: 1.13
* Operating System: Android
* Graphics API: Vulkan

## Workarounds
Any suggestions / ideas for workarounds would also be greatly appreciated. We would be happy to add code which loads the RenderDoc vulkan layer and does other required initialization steps in order to be able to debug our service.

**Comment by baldurk** [comment]
I'm sorry but I don't think this is something I would ever consider supporting, at least not something I want to support right now. Android already contributes disproportionately to the support burden in RenderDoc, I don't want to worsen that by supporting a new niche/obscure type of program with potentially many unique problems.

My only suggestion would be to (if possible) create a test bench which is a normal android program but does the same rendering that you'd like to debug, and launch that from RenderDoc. I would imagine you've considered that though, and if that's not feasible then I don't have any other ideas.

If you find a way to make this work and want to contribute any patches then I'm happy to take a PR, even if this isn't something I support as long as any changes won't break any supported workflows/platforms I'd accept them.
