### ISSUE TITLE
About  VkDescriptorSet, I found some bugs?

### ISSUE THREAD

**Issue by luopan007** [baldurk/renderdoc#2284]
## Description

 I Write a vulkan demo, using Renderdoc v1.13 capture and replay single frame. The GLSL code as follow,:

Vertext Shader:
```glsl
#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(binding = 0) uniform UniformBufferObject {
    mat4 model;
    mat4 view;
    mat4 proj;
} ubo;

layout(location = 0) in vec3 inPosition;
layout(location = 1) in vec3 inColor;
layout(location = 2) in vec2 inTexCoord;

layout(location = 0) out vec3 fragColor;
layout(location = 1) out vec2 fragTexCoord;

void main() {
    gl_Position = ubo.proj * ubo.view * ubo.model * vec4(inPosition, 1.0);
    fragColor = inColor;
    fragTexCoord = inTexCoord;
}
```

Fragment Shader:
```glsl
#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(binding = 3) uniform sampler2D texSampler;

layout(location = 0) in vec3 fragColor;
layout(location = 1) in vec2 fragTexCoord;

layout(location = 0) out vec4 outColor;

void main() {
    outColor = texture(texSampler, fragTexCoord);
}
```
In this shader program, I write the bind value is: 0 and 3. And in the vkCreateDescriptorSetLayout, using the follow code:
```c++
VkDescriptorSetLayoutBinding uboLayoutBinding = {};
uboLayoutBinding.binding = 0;
uboLayoutBinding.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
uboLayoutBinding.descriptorCount = 1;
uboLayoutBinding.pImmutableSamplers = nullptr;
uboLayoutBinding.stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
	
VkDescriptorSetLayoutBinding samplerLayoutBinding{};
samplerLayoutBinding.binding = 3;
samplerLayoutBinding.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
samplerLayoutBinding.descriptorCount = 1;
samplerLayoutBinding.pImmutableSamplers = nullptr;
samplerLayoutBinding.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;

std::array<VkDescriptorSetLayoutBinding, 2> bindings = { uboLayoutBinding, samplerLayoutBinding };
	
VkDescriptorSetLayoutCreateInfo layoutInfo{};
layoutInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
layoutInfo.pNext = nullptr;
layoutInfo.bindingCount = static_cast<uint32_t>(bindings.size());
layoutInfo.pBindings = bindings.data();
	
if (vkCreateDescriptorSetLayout(device, &layoutInfo, nullptr, &descriptorSetLayout) != VK_SUCCESS) {
	throw::std::runtime_error("Failed to create descriptor set layout");
}
```
Please note the  samplerLayoutBinding.binding = 3 value. And I update the VkDescriptorSet, as follow code:
```c++
VkDescriptorBufferInfo bufferInfo{};
bufferInfo.buffer = uniformBuffers[i];
bufferInfo.offset = 0;
bufferInfo.range = sizeof(UniformBufferObject);

VkDescriptorImageInfo imageInfo{};
imageInfo.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
imageInfo.imageView = textureImageView;
imageInfo.sampler = textureSampler;

std::array<VkWriteDescriptorSet, 2> descriptorWrites{};

descriptorWrites[0].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
descriptorWrites[0].dstSet = descriptorSets[i];
descriptorWrites[0].dstBinding = 0;
descriptorWrites[0].dstArrayElement = 0;
descriptorWrites[0].descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
descriptorWrites[0].descriptorCount = 1;
descriptorWrites[0].pBufferInfo = &bufferInfo;

descriptorWrites[1].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
descriptorWrites[1].dstSet = descriptorSets[i];
descriptorWrites[1].dstBinding = 3;
descriptorWrites[1].dstArrayElement = 0;
descriptorWrites[1].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
descriptorWrites[1].descriptorCount = 1;
descriptorWrites[1].pImageInfo = &imageInfo;

// 更新描述符
vkUpdateDescriptorSets(device, static_cast<uint32_t>(descriptorWrites.size()), descriptorWrites.data(), 0, nullptr);
```

But, I capture this app, the xml is:
```xml
<chunk id="1012" index="443" name="vkCreateDescriptorSetLayout" length="86" threadID="482873412944" timestamp="10950653" duration="5">
	<ResourceId name="device" typename="VkDevice" width="8">74</ResourceId>
	<struct name="CreateInfo" typename="VkDescriptorSetLayoutCreateInfo">
		<enum name="sType" typename="VkStructureType" string="VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO">32</enum>
		<null name="pNext" typename="void *" />
		<enum name="flags" typename="VkDescriptorSetLayoutCreateFlags" string="VkDescriptorSetLayoutCreateFlagBits(0)">0</enum>
		<uint name="bindingCount" typename="uint32_t" width="4">2</uint>
		<array name="pBindings">
			<struct typename="VkDescriptorSetLayoutBinding">
				<uint name="binding" typename="uint32_t" width="4">3</uint>
				<enum name="descriptorType" typename="VkDescriptorType" string="VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER">1</enum>
				<uint name="descriptorCount" typename="uint32_t" width="4">1</uint>
				<enum name="stageFlags" typename="VkShaderStageFlags" string="VK_SHADER_STAGE_VERTEX_BIT">1</enum>
				<array name="pImmutableSamplers" typename="VkSampler" />
			</struct>
			<struct typename="VkDescriptorSetLayoutBinding">
				<uint name="binding" typename="uint32_t" width="4">0</uint>
				<enum name="descriptorType" typename="VkDescriptorType" string="VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER">6</enum>
				<uint name="descriptorCount" typename="uint32_t" width="4">1</uint>
				<enum name="stageFlags" typename="VkShaderStageFlags" string="VK_SHADER_STAGE_VERTEX_BIT">1</enum>
				<array name="pImmutableSamplers" typename="VkSampler" />
			</struct>
		</array>
	</struct>
	<null name="pAllocator" typename="VkAllocationCallbacks" />
	<ResourceId name="SetLayout" typename="VkDescriptorSetLayout" width="8">1539</ResourceId>
</chunk>
```
As the xml file, the binding order is Reverse order. the binding=0 and biding=3 was exchanged. Why?

At the same time, I found, vk_initstate.cpp -->Serialise_InitialState() --> If the type == eResDescriptorSet, The renderdoc structure the VkWriteDescriptorSet struct, the code is follow:
```c++
for(uint32_t j = 0; j < initialContents.numDescriptors; j++)
{
// some code

writes[bind].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
writes[bind].pNext = NULL;

// template for this write. We will expand it to include more descriptors as we find valid
// descriptors to update.
writes[bind].dstSet = (VkDescriptorSet)(uint64_t)res;
writes[bind].dstBinding = j; // WHY is j? j belongs to descriptorSetLayout binding value set?
writes[bind].dstArrayElement = 0;
// descriptor count starts at 0. We increment it as we find valid descriptors
writes[bind].descriptorCount = 0;
writes[bind].descriptorType = layout.bindings[j].descriptorType;
//some code
}
```
**WHY is j? j belongs to descriptorSetLayout binding value set?**
**WHY is j? j belongs to descriptorSetLayout binding value set?**
**WHY is j? j belongs to descriptorSetLayout binding value set?**
 
## Environment

* RenderDoc version: 1.13
* Operating System: Windows 10
* Graphics API: 1.2.141
* GPU Device: Intel UHD 560

## The Doubt Point
The vulkan spec:
• dstBinding must be less than or equal to the maximum value of binding of all
VkDescriptorSetLayoutBinding structures specified when dstSet’s descriptor set layout
was created.

**WHY is j? j belongs to descriptorSetLayout binding value set?**
**WHY is j? j belongs to descriptorSetLayout binding value set?**
**WHY is j? j belongs to descriptorSetLayout binding value set?**

Thanks for your answer.

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. If you have a bug to report you should provide steps to reproduce and a description of what the problem is. You should not point to things in the code and ask questions about how it works, as issues should not be used for general questions. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by luopan007** [comment]
> Hi there, your issue has been closed due to not correctly following the issue template. If you have a bug to report you should provide steps to reproduce and a description of what the problem is. You should not point to things in the code and ask questions about how it works, as issues should not be used for general questions. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.
> 
> I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!
> 
> In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

What fuck close. can not see the code taht you write?
