### ISSUE TITLE
Vulkan: missing calling convention causes crashes

### ISSUE THREAD

**Issue by TiemoJung** [baldurk/renderdoc#230]
Both hooked_vkCreateInstance and hooked_vkDestroyInstance have no explicit calling convention set, they will be default (__cdecl) and will trigger crashes.

**Comment by baldurk** [comment]
Good catch, since these weren't in the macros I had forgotten the calling convention. I think the above commit should sort this out now (I wasn't seeing crashes, I guess by luck!)

**Comment by TiemoJung** [comment]
Hi,

looks ok.
No clue why it does not crash every time. just was odd when occasionally some stuff was crashing when renderdoc was enabled.
