### ISSUE TITLE
[Vulkan] KHR_pipeline_executable_properties/AMD_shader_info are not updated after editing a shader

### ISSUE THREAD

**Issue by werman** [baldurk/renderdoc#2300]
## Description

KHR_pipeline_executable_properties and AMD_shader_info are not updated after editing a shader while SPIRV/GLSL disassemblies are updated. 

## Steps to reproduce

Happens in any capture of any VK app. E.g. `gears` from Sascha Willems' examples

1. Pick draw call
2. Open Pipeline State
3. Note the KHR_pipeline_executable_properties/AMD_shader_info contents
4. Close the table with this shader
5. Edit de-compiled GLSL and hit refresh
6. "View" the shader again, SPIRV/GLSL disassemblies are updated, while KHR_pipeline_executable_properties and AMD_shader_info are not

## Environment

* RenderDoc version: latest 1.15 6212e98
* Operating System: Linux
* Graphics API: Vulkan

## Details

https://user-images.githubusercontent.com/3993671/123443196-34709880-d5c5-11eb-8be3-50c50767cebb.mp4

**Comment by baldurk** [comment]
That commit should fix the issue, pipeline-based disassembly targets weren't properly being updated by the shader itself being edited.

**Comment by werman** [comment]
Thanks a lot!
