### ISSUE TITLE
Regression when hooking to child processes in RenderDoc since 1.13

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#2301]
## Description

Trying to inject into [Ignition gazebo](https://ignitionrobotics.org/) stopped working starting with commit https://github.com/baldurk/renderdoc/commit/287da369fcd

Gazebo works by running a ruby script (the process 'ign' is actually ruby script) which launches two processes:
 1. A CLI server (has OpenGL support and is injectable by RenderDoc)
 2. A client GUI (has OpenGL support and is also injectable by RenderDoc)

There are two ways to launch gazebo:

1. `ign gazebo -v4 shapes.sdf` spawns both server and client. RenderDoc never handled this properly.
2. `ign gazebo -s -v4 shapes.sdf` and `ign gazebo -g` for server and GUI respectively. RenderDoc before 287da369fcd handled this fine and hooked fine to both server and GUI (server is hard to capture without source code modifications because swap buffers is never called).

## Steps to reproduce

1. Use Ubuntu 20.04 LTS. I used Virtualbox and worked for me. I strongly suggest you use 'matias' as username (due to a path being hardcoded), but there is a workaround using shared links. I also had Guest Additions installed although I don't know if it's necessary. The VM will need at least 14GB so I suggest to give it plenty of space (e.g. 30GB) to be safe)
2. Execute these commands to install dependencies:
```
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
wget https://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
sudo apt-get update
sudo apt -y install \
binutils-dev build-essential cmake curl freeglut3-dev libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libbenchmark-dev libcurl4-openssl-dev libdart-collision-bullet-dev libdart-collision-ode-dev libdart-dev libdart-external-ikfast-dev libdart-external-odelcpsolver-dev libdart-utils-urdf-dev libeigen3-dev libfreeimage-dev libgflags-dev libglew-dev libgts-dev libjsoncpp-dev libogre-1.9-dev libogre-2.1-dev libprotobuf-dev libprotoc-dev libsqlite3-dev libswscale-dev libtinyxml2-dev liburdfdom-dev libwebsockets-dev libxi-dev libxml2-utils libxmu-dev libyaml-dev libzip-dev libzmq3-dev pkg-config protobuf-compiler python-psutil python-yaml qml-module-qtcharts qml-module-qtgraphicaleffects qml-module-qt-labs-folderlistmodel qml-module-qt-labs-platform qml-module-qt-labs-settings qml-module-qtqml-models2 qml-module-qtquick2 qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-dialogs qml-module-qtquick-layouts qml-module-qtquick-templates2 qml-module-qtquick-window2 qtbase5-dev qtdeclarative5-dev qtquickcontrols2-5-dev rubocop ruby ruby-dev ruby-ronn swig uuid-dev xvfb 
```
3. Download [this build I prepared](https://mega.nz/file/Yy4G1ICR#mYwLFVzureh1m1k4JD_FVy6ownKPXwJmFZvZorDZ6lw) and unzip it to _exactly_ /home/**matias**/Projects/ign (do NOT replace the username). If unpacked correctly you should be looking at the following in /home/**matias**/Projects/ign/install:
![Untitled](https://user-images.githubusercontent.com/3395130/125213878-9e0dc980-e28a-11eb-9ae5-15e68dd4d4ce.png)
If the username is not matias, then you can use shared links as workaround:
```
sudo mkdir -p /home/matias/Projects/ign
sudo chown $USER:$USER /home/matias
sudo chown $USER:$USER /home/matias/Projects
sudo chown $USER:$USER /home/matias/Projects/ign
cd /home/matias/Projects/ign
ln -s /path/to/unzipped/gazebo install
```
4. Open a terminal and type `. /home/matias/Projects/ign/install/setup.bash` (notice the dot at the beginning) This will add the following environment variables:
```
CMAKE_PREFIX_PATH=/home/matias/Projects/ign/install
COLCON_PREFIX_PATH=/home/matias/Projects/ign/install
LD_LIBRARY_PATH=/home/matias/Projects/ign/install/lib
PATH=/home/matias/Projects/ign/install/lib:/home/matias/Projects/ign/build/ignition-rendering5/lib:/home/matias/Projects/ign/install/bin:${PATH}
PKG_CONFIG_PATH=/home/matias/Projects/ign/install/lib/pkgconfig
```
5. Launch gazebo in server mode: `ign gazebo -s -v4 shapes.sdf`
6. Open a new terminal, repeat step 4 and open qrenderdoc from command line to inherit the env variables (you can avoid step 4 and set these env vars manually from within RenderDoc's gui, but this is way faster)
7. Set the following:
```
ExcutablePath: /home/matias/Projects/ign/install/bin/ign
WorkingDir: /home/matias/Projects/ign/install/bin
Cmdline args: gazebo -g
```

If done correctly using RenderDoc 1.12, you will see the following:
![RenderDoc01](https://user-images.githubusercontent.com/3395130/123530046-ad0e4c80-d6cc-11eb-868d-c0626dca855f.png)
![RenderDoc02](https://user-images.githubusercontent.com/3395130/123530047-aed81000-d6cc-11eb-83d3-be4d287cc2a4.png)

But when trying it on RenderDoc 1.13+, RenderDoc will not hook and immediately abort injection, as if all processes finished. The gazebo GUI opens fine, but no injection takes place.

**Virtualbox Notes:**

1. In Oracle Virtualbox it said "OpenGL. Only OpenGL 3.2 contexs are supported.", so capturing won't work; but RenderDoc 1.12 is hooking correctly, while 1.13+ does not hook and doesn't say anything at all
2. In the VM the GUI hangs on exit. Just kill it.

I can provide binaries for Ubuntu 18.04 as well, if needed

## Environment

* RenderDoc version: 1.13+ (since 287da369fcd)
* Operating System: Ubuntu 20.04 LTS
* Graphics API: OpenGL

Note: The GUI uses Qt which initializes OpenGL (I believe compatibility profile 3.x) with shared context to a core 3.3 profile for Ogre to use and RenderDoc captures fine.

Note 2: Alternatively, since ign is a ruby script, `/usr/bin/ruby /home/userign/install/bin/ign gazebo -v 4 -g` works too

**Comment by baldurk** [comment]
I'm not able to set up the program to run using your steps unfortunately.

Running the dependency install command doesn't work. Looking at what it's doing, it's trying to find files like `packages*.apt` under the current directory, though at step 2 I'm not sure where the current directory is supposed to be (it first failed for me because I was in renderdoc's build folder).

I thought maybe you intended for me to extract the build from step 3 first and then run it in there, but the build I downloaded doesn't have any such files so it still doesn't work.

Just in case I tried running the program without the dependencies but it failed, I presume because I'm missing some package:

```
$ ls
install
$ ls install/
bin            lib                       _local_setup_util_sh.py  setup.sh
build          local_setup.bash          local_setup.zsh          setup.zsh
COLCON_IGNORE  local_setup.ps1           log                      share
include        local_setup.sh            setup.bash
install        _local_setup_util_ps1.py  setup.ps1
$ find . -iname 'packages-'`lsb_release -cs`'.apt' -o -iname 'packages.apt' | grep -v '/\.git/'
$ . install/setup.bash 
$ ign -s -v4 shapes.sdf
I cannot find any available 'ign' command:
	* Did you install any ignition library?
	* Did you set the IGN_CONFIG_PATH environment variable?
	    E.g.: export IGN_CONFIG_PATH=$HOME/local/share/ignition
```

One thing - I'm on Ubuntu 20.10, though it looked like the apt repository has entries for 20.10 and it doesn't seem like that would affect the above directly (though maybe it's a problem later?). A note on that btw - since the URLs you provided have https support I really strongly suggest that you use https instead of http. Adding apt repositories from random http sources and installing keys from there doesn't make me feel _great_ :smile:.

**Comment by darksylinc** [comment]
Hi

> I cannot find any available 'ign' command:
> 	* Did you install any ignition library?
> 	* Did you set the IGN_CONFIG_PATH environment variable?
> 	    E.g.: export IGN_CONFIG_PATH=$HOME/local/share/ignition

This error AFAIK happened because of missing dependencies (or maybe because the libraries I compiled use a library that is not ABI compatible, hence it failed to load in 20.10; and that's why it says it couldn't find any ignition library. They were found... they just refused to load). You executed setup.bash properly. Without it, you'd get instead:

> Command 'ign' not found, did you mean:
> 
>   command 'igv' from deb igv
>   command 'idn' from deb idn
> 
> Try: sudo apt install <deb name>

As for the dependencies, I'm afraid only Ubuntu LTS distros are supported / has deps provided :(

The packages file in groovy (Ubuntu 20.10) is just an empty file.

That's why:
> find . -iname 'packages-'`lsb_release -cs`'.apt' -o -iname 'packages.apt' | grep -v '/\.git/'

did nothing for you. It just found no packages. After successful execution it would have started `apt install` and asked if you want to continue installing the packages.

> since the URLs you provided have https support I really strongly suggest that you use https instead of http. Adding apt repositories from random http sources and installing keys from there doesn't make me feel great

You're right, I've updated the instructions to fetch the key from HTTPS.
Note apt prefers to use HTTP sources, it has its own validation system (that's why the key is for). But indeed if the key is fetched from an untrusted source then the whole thing is vulnerable to compromise.

**Comment by baldurk** [comment]
Is there any way around that? I could try installing the listed dependencies for 20.04, in principle I'd expect them to be ABI backwards compatible and allow me to run still. I don't think I can downgrade this installation and I believe I needed to update to 20.10 for something else anyway so I wouldn't really want to. I'm not sure when I'll be able to make the time to set up a new portable installation of Ubuntu 20.04 for this.

I'm still unclear on how that command is supposed to work at all to install the packages, regardless of distro version. As I mentioned above you didn't specify a working directory for that step so depending on where I ran it if I had some packages.apt files from something else it could install almost anything. If it's meant to be run from the extracted build there are no .apt files at all, regardless of what `lsb_release` outputs:

```
$ ls install/
bin            install           local_setup.sh            log         setup.zsh
build          lib               _local_setup_util_ps1.py  setup.bash  share
COLCON_IGNORE  local_setup.bash  _local_setup_util_sh.py   setup.ps1
include        local_setup.ps1   local_setup.zsh           setup.sh
$ find . -iname 'packages-'focal'.apt' -o -iname 'packages.apt' | grep -v '/\.git/'
$ find . | grep apt
$
```

**Comment by darksylinc** [comment]
Hi!

The working dir for that command should have been irrelevant? Perhaps it's meant to be executed from the cloned repos (which I was trying to avoid). The official instructions can be [found here](https://ignitionrobotics.org/docs/edifice/install_ubuntu_src).

There's also [binary-only installation instructions](https://ignitionrobotics.org/docs/edifice/install_ubuntu) which I was hoping we could easily avoid (seems not...) because the experience is different (because ign is installed in system folders instead of any folder)

> Is there any way around that? I could try installing the listed dependencies for 20.04, in principle I'd expect them to be ABI backwards compatible and allow me to run still.

I tried running a build for 18.04 on a 20.04 machine and it refused. So I don't think so.

> I don't think I can downgrade this installation and I believe I needed to update to 20.10 for something else anyway so I wouldn't really want to. I'm not sure when I'll be able to make the time to set up a new portable installation of Ubuntu 20.04 for this.

Well, I guess I'll have to use an older version (or undo that commit for the newer versions) and wait until then.

Btw if you've got a spare drive you can backup the partition there via (using a live USB distro, because you shouldn't do this while the partition is mounted):

```
# Back up
sudo dd if=/dev/sdb1 bs=16M status=progress | lz4 > backup.lz4
# Restore
lz4 -dc backup.lz4 | sudo dd of=/dev/sdb1 bs=16M status=progress
```

**Comment by darksylinc** [comment]
Btw is it ok if I try to repro this problem in a Virtual Machine? (e.g. Virtualbox).

If I manage to repro the problem there I can send you the VM.

**Comment by baldurk** [comment]
Yeh I don't want to state the obvious but if you're running running `find .` to locate files named `packages.apt` or `packages-focal.apt` then the current directory is definitely relevant :smile:.

Briefly looking at those instructions it looks like yes that command is run after cloning all the source via a 3rd party tool, which would then pick up files like [ign-common/packages.apt](https://github.com/ignitionrobotics/ign-common/blob/ign-common4/.github/ci/packages.apt) or [ign-gazebo/packages-focal.apt](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo5/.github/ci/packages-focal.apt).

I know there are ways to back up and restore an install but I don't want to go that route.

If you can repro in a VM then there's no need to send me it, I can set one up quickly enough. I'll try tomorrow installing the packages from those repositories and see if it works or maybe try the binary install.

**Comment by baldurk** [comment]
I tried installing all the packages from those repos, but I got the same result unfortunately (cannot find any available 'ign' command). If this repros in a VM then I can try that, otherwise like I say this will need to wait a bit. In practice very specific distro requirements are hard for me to satisfy unless it's e.g. the latest version of ubuntu, as I can upgrade easily enough within reason.

**Comment by darksylinc** [comment]
Yeah! I will try to repro this in a VM to make it as easy as possible.

Thank you for your patience. I don't want to waste your time; please wait until I've managed to better repro it in a VM.

**Comment by darksylinc** [comment]
Updated instructions!

I followed them step by step and was able to repro the problem. Hopefully you will be able to find the problem

**Comment by baldurk** [comment]
I followed the updated steps and used the username 'matias' but when I got to step 5 the program doesn't seem to run:

```
$ ign -s -v4 shapes.sdf
The 'ign' command provides a command line interface to the ignition tools.

  ign <command> [options]

List of available commands:

  help:          Print this help text.
  gazebo:        Run and manage Gazebo.
  log:           Record or playback topics.
  topic:         Print information about topics.
  service:       Print information about services.
  plugin:        Print information about plugins.
  sdf:           Utilities for SDF files.
  msg:           Print information about messages.
  gui:           Launch graphical interfaces.
  fuel:          Manage simulation resources.
  launch:        Run and manage executables and plugins.

Options:

  --force-version <VERSION>  Use a specific library version.
  --versions                 Show the available versions.
  --commands                 Show the available commands.
Use 'ign help <command>' to print help for a command.
```

I tried running the remaining steps with the second terminal and `ign gazebo -g` but it only displays a black screen (this is just running it normally to ensure my configuration is correct, not running from renderdoc).

Step 4 mentions running `. /home/matias/ign/install/setup.bash` but that path doesn't exist because I put it in `/home/matias/Projects/ign` as outlined earlier. I don't know if that's a typo, since you mentioned hardcoded paths?

I'm using VMWare FYI since that's the VM software I have installed. I assume that's not a problem but if your program requires virtualbox specifically I can set that up.

**Comment by darksylinc** [comment]
Agh!

It's

`ign gazebo -s -v4 shapes.sdf`

I had it written well first then wrong, which is why I didn't notice.

Without the server running the gui client will be stuck waiting

**Comment by darksylinc** [comment]
> Step 4 mentions running . /home/matias/ign/install/setup.bash but that path doesn't exist because I put it in /home/matias/Projects/ign as outlined earlier. I don't know if that's a typo, since you mentioned hardcoded paths?

Check the path in the picture I posted in step 3. I posted the picture because it's always confusing to explain where should be unpacked

**Comment by baldurk** [comment]
Yeh that's what I wasn't sure about, the steps and the picture imply that everything should be unzipped under a `Projects/` subfolder in the homedir `/home/matias/`. But that means that there's no `ign` subfolder in the homedir for `/home/matias/ign/install/setup.bash` to exist. Sounds like maybe just another typo then?

I can try this again tomorrow.

**Comment by darksylinc** [comment]
Yup. Typos all around SMH.

Edited the steps hopefully you'll get it working this time.

> I'm using VMWare FYI since that's the VM software I have installed. I assume that's not a problem but if your program requires virtualbox specifically I can set that up.

It shouldn't matter as long as OpenGL (mesa software llvmpipe is enough) can open a recent-enough OpenGL so that Ogre 2.1 can initialize.

**Comment by baldurk** [comment]
That commit should fix it, at least it does in my testing. Looks like I missed some variants of exec() which `/usr/bin/env` ended up using to launch ruby, so the child process got missed. Running ruby directly with the script name worked for me at least, FWIW. v1.12 was working because child process hooking was broken in the sense that processes *always* inherited the hooking environment vars from the parent, even if you didn't want them to. It should now work correctly and respect the capture option.

I tried looking at why `ign gazebo -v4 shapes.sdf` doesn't work, and it looks like it's because ruby doesn't spawn 'clean' new processes with fork and exec. It does a fork but then executes whatever in the child process. That won't play nice with how RenderDoc expects to see a new process so it will likely behave unpredictably. For me the connection window shows the parent process only as unsupported and doesn't pick up any child processes, but they do get hooked and I can make a capture and open it manually. That's **not** guaranteed though and this mode is not supported.

**Comment by darksylinc** [comment]
Thanks Baldur you're the best!

And thanks for having the patience with me on this one!

> For me the connection window shows the parent process only as unsupported and doesn't pick up any child processes, but they do get hooked and I can make a capture and open it manually. That's not guaranteed though and this mode is not supported.

Yeah, capture errors caused by the process itself are our own. Thanks for explaining what makes it go wrong!
