### ISSUE TITLE
Can't capture.

### ISSUE THREAD

**Issue by indianaliam1** [baldurk/renderdoc#2304]
## Description

I can't capture. No matter how may times I smash my f12 key, no matter how may reboots, whatever.

## Steps to reproduce

Step 1: Open RenderDoc.
Step 2: Use it to open Nox's multi player thing, rigging children too.
Step 3: Open Miitomo.
Step 4: Spend the next TWO fucking hours tearing hair out wondering why this software won't give me my gahddamn Mii 

## Environment

RenderDoc .91, although was using the latest stable build until the tutorial I was using absolutely specified 0.91 with an absolute dying fury. They were very strict in that.
Windows 10
I tried OpenGL, but now using DirectX

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
