### ISSUE TITLE
D3D12 CopyTextureRegion argument order is not the same as the api

### ISSUE THREAD

**Issue by monamimani** [baldurk/renderdoc#2306]
## Description

I was looking at a GPU capture and got confused because the order of the arguments of the CopyTextureRegion is the opposite of the D3D API. In RenderDoc Event Browser the arguments are Src than Dst, but in the API the order is Dst and Src. 
I understand this is minor, but I am debugging an issue that might be that I am overwriting my textures instead of copying from.
Also, the event browser looks like an API call, I would assume that arguments are the same as the API.
The fact that the arguments are in different order makes it harder and takes more mental energy to understand what is going on.
I would understand if this won't be fixed but at least you know.

## Steps to reproduce

Make a capture with a CopyTextureRegion in it ( probably all the Copy***** family of texture are the same)
I could share a capture but this is so simple and not a bug per say. I can do it if you actually want one.

## Environment

* RenderDoc version: 1.14
* Operating System: Windows 1809
* Graphics API: D3D12

**Comment by baldurk** [comment]
This wasn't intentional, maybe from having to decode those structs I'm not sure. Looks like it was only for CopyTextureRegion, so I've fixed it in that commit.

**Comment by monamimani** [comment]
Great! Thanks alot!
