### ISSUE TITLE
Exporting mesh window title is "Export buffer to bytes" even when exporting to CSV

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2311]
## Description

When exporting a mesh to CSV, the save window title is "Export buffer to bytes", which is the same as when actually exporting to bytes.

https://github.com/baldurk/renderdoc/blob/cad267eb41ae7cbc7a642d0d1c3b5f2ce6993982/qrenderdoc/Windows/BufferViewer.cpp#L4024-L4031

## Steps to reproduce

1. Capture any 3D scene.  (I don't think the specifics matter, but if for some reason a specific capture is needed, I can upload one.)
2. Select some event in the event browser.
3. Navigate to the mesh viewer.
4. Click the dropdown next to the floppy disk icon, and then click "Export to CSV"
5. Observe that the save window is titled "Export buffer to bytes", though the save type is still CSV.

![image](https://user-images.githubusercontent.com/8334194/124843232-57e0ff00-df46-11eb-83b7-7a5a8af399ba.png)

## Environment

* RenderDoc version: 1.14
* Operating System: Windows 10
* Graphics API: D3D11, unlikely to matter though

**Comment by baldurk** [comment]
That commit should tailor the dialog title to the export format.
