### ISSUE TITLE
crash in unreal  launch

### ISSUE THREAD

**Issue by eaglefly628** [baldurk/renderdoc#2319]
here is call stack,version is 1.13,1.14

Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #00 pc 00000000000714b0  /apex/com.android.runtime/lib64/bionic/libc.so (strlen+16) (BuildId: 3d6110ae7e9358c1f52bab6316ac8f93)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #01 pc 0000000000299a48  /system/lib64/libhwui.so (GrGLProgramBuilder::CreateProgram(GrRenderTarget*, GrSurfaceOrigin, GrPrimitiveProcessor const&, GrTextureProxy const* const*, GrPipeline const&, GrProgramDesc*, GrGLGpu*)+1420) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #02 pc 0000000000296858  /system/lib64/libhwui.so (GrGLGpu::ProgramCache::refProgram(GrGLGpu*, GrRenderTarget*, GrSurfaceOrigin, GrPrimitiveProcessor const&, GrTextureProxy const* const*, GrPipeline const&, bool)+308) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #03 pc 0000000000294874  /system/lib64/libhwui.so (GrGLGpu::flushGLState(GrRenderTarget*, GrSurfaceOrigin, GrPrimitiveProcessor const&, GrPipeline const&, GrPipeline::FixedDynamicState const*, GrPipeline::DynamicStateArrays const*, int, bool)+128) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #04 pc 00000000002937b8  /system/lib64/libhwui.so (GrGLGpu::draw(GrRenderTarget*, GrSurfaceOrigin, GrPrimitiveProcessor const&, GrPipeline const&, GrPipeline::FixedDynamicState const*, GrPipeline::DynamicStateArrays const*, GrMesh const*, int)+188) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #05 pc 00000000002936ec  /system/lib64/libhwui.so (GrGLGpuRTCommandBuffer::onDraw(GrPrimitiveProcessor const&, GrPipeline const&, GrPipeline::FixedDynamicState const*, GrPipeline::DynamicStateArrays const*, GrMesh const*, int, SkRect const&)+56) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #06 pc 000000000025338c  /system/lib64/libhwui.so (GrGpuRTCommandBuffer::draw(GrPrimitiveProcessor const&, GrPipeline const&, GrPipeline::FixedDynamicState const*, GrPipeline::DynamicStateArrays const*, GrMesh const*, int, SkRect const&)+388) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #07 pc 0000000000252eec  /system/lib64/libhwui.so (GrOpFlushState::executeDrawsAndUploadsForMeshDrawOp(GrOp const*, SkRect const&, GrProcessorSet&&, unsigned int, GrUserStencilSettings const*)+348) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #08 pc 000000000054d980  /system/lib64/libhwui.so (_ZN12_GLOBAL__N_19TextureOp9onExecuteEP14GrOpFlushStateRK6SkRect$ab67424b01b2ae857b75443a16f18610+96) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #09 pc 0000000000270e08  /system/lib64/libhwui.so (GrOp::execute(GrOpFlushState*, SkRect const&)+92) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #10 pc 0000000000270bb8  /system/lib64/libhwui.so (GrRenderTargetOpList::onExecute(GrOpFlushState*)+328) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #11 pc 00000000002dc7d0  /system/lib64/libhwui.so (GrDrawingManager::flush(GrSurfaceProxy*, SkSurface::BackendSurfaceAccess, GrFlushFlags, int, GrBackendSemaphore*, void (*)(void*), void*)+2048) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #12 pc 00000000002dbed4  /system/lib64/libhwui.so (GrDrawingManager::prepareSurfaceForExternalIO(GrSurfaceProxy*, SkSurface::BackendSurfaceAccess, GrFlushFlags, int, GrBackendSemaphore*, void (*)(void*), void*)+196) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #13 pc 00000000002dbcc8  /system/lib64/libhwui.so (GrRenderTargetContext::prepareForExternalIO(SkSurface::BackendSurfaceAccess, GrFlushFlags, int, GrBackendSemaphore*, void (*)(void*), void*)+116) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #14 pc 00000000002742f4  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode>>> const&, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>, SkMatrix const&)+224) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #15 pc 0000000000273ee8  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode>>> const&, android::uirenderer::FrameInfoVisualizer*)+388) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #16 pc 00000000002d4cf8  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+748) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #17 pc 00000000002d3db8  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+380) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #18 pc 00000000002dee68  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+228) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #19 pc 00000000002deb48  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+576) (BuildId: ddf3849ed841da3c51d700414bb9c702)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #20 pc 0000000000013654  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+328) (BuildId: 8d6304818aed89ed4db84f9373cc00d7)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #21 pc 00000000000d9ce0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 3d6110ae7e9358c1f52bab6316ac8f93)
Android  PID  19632: [17:54:16]                   DEBUG(0) - Fatal   - #22 pc 00000000000765ac  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 3d6110ae7e9358c1f52bab6316ac8f93)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
