### ISSUE TITLE
IDXGISwapChain3 causes crashes because it's not wrapped

### ISSUE THREAD

**Issue by nlguillemot** [baldurk/renderdoc#232]
Using `IDXGISwapChain3` will cause the captured executable to crash. This happens because `IDXGISwapChain3::GetBuffer` is not wrapped by RenderDoc, so it returns a plain `ID3D11Resource`. Future calls to RenderDoc-wrapped D3D11 using this resource will cause crashes, because RenderDoc expects the resource to be wrapped.

Current workaround: use `IDXGISwapChain2` until support for `IDXGISwapChain3` is added to RenderDoc.

**Comment by baldurk** [comment]
You should be able to use newer DXGI interfaces without problems now.

**Comment by baldurk** [comment]
Closing this issue as the feature is implemented in [v0.30](https://github.com/baldurk/renderdoc/releases/tag/v0.30). Feel free to re-open if it's not as you expect!
