### ISSUE TITLE
Export shader messages as txt or add multirow selection

### ISSUE THREAD

**Issue by ichlubna** [baldurk/renderdoc#2321]
## Description
The current state of Shader messages window is that the messages are sorted as standalone rows which can be copied one by one. This is unsuitable for cases when the user needs to copy multiple rows or simply export the messages as a log. 

I think that the same options as in Diagnostic window would suffice (being able to select and copy multiple rows or export txt). My use-case is for example to printf a large number of values in a loop and then make a chart of them.

## Environment
* RenderDoc version: 1.15 (92efebd5)
* Operating System: Arch Linux
* Graphics API: Vulkan

![image](https://user-images.githubusercontent.com/43234438/126602749-243a2cb8-4fdc-47f9-976e-97dbe2d2eb1b.png)
Thank you for this amazing tool anyway :-),

**Comment by baldurk** [comment]
That commit should add multiselection (it seems like it's not the default behaviour so I needed to specify it), and also adds export to either text or CSV. The export respects the current filter so only the visible data is exported.

**Comment by ichlubna** [comment]
> That commit should add multiselection (it seems like it's not the default behaviour so I needed to specify it), and also adds export to either text or CSV. The export respects the current filter so only the visible data is exported.

Amazing! Thanks! I will try!
