### ISSUE TITLE
Opt for left-handed or right-handed coordinate system for Mesh Viewer

### ISSUE THREAD

**Issue by JoaoBaptMG** [baldurk/renderdoc#2322]
## Description

The "handedness" of the world coordinate system is normally defined by the application and (normally) is independent of the graphics API chosen. Is is possible to convert from a right-handed to a left-handed coordinate system by using a reflection matrix on the z-axis (which is normally baked in on the perspective matrix).

When debugging an application using RenderDoc, sometimes I want to peek the attributes passed in to the pipeline for a certain vertex, which I need to locate in the Mesh Viewer by comparing to the screen output. However, it seems that Mesh Viewer uses a *left-handed* world coordinate system, whereas the app I am debugging draws to the screen assuming a *right-handed* world coordinate system, which implies in a reflection on the z-axis. That means the image generated by the app and the preview created by Mesh Viewer are mirrors of each other, as shown in the following images:

![image](https://user-images.githubusercontent.com/13079799/126631995-416b8ed0-3f6d-4163-a680-05b2d1bf850d.png)

![image](https://user-images.githubusercontent.com/13079799/126632196-5f48d77d-ec7e-4857-a168-372b6ca84da7.png)

This can make it too troublesome, for example, to look for matching vertices to examinate in the presence of graphical glitches. Henceforth, I propose either a feature to toggle a reflection of the coordinate system based on handedness or maybe even trying to detect it (by "extracting" and examining a projection matrix, for example).

## Environment

* RenderDoc version: v1.11+dfsg-5
* Operating System: pop!_OS 21.04
* Graphics API: OpenGL

**Comment by dpwiz** [comment]
I have the same issue with my vulkan-native meshes being upside-down in VS In.

I wouldn't be surprised if someone would need a front-to-back flip too.

**Comment by baldurk** [comment]
Yes indeed, it's not as simple as just left-handed vs right-handed for object-space since you can really have whichever axis convention you prefer. You probably want a way to choose any particular axis mapping, though shortcuts for the most common ones would make sense as I doubt there are very many who use X+ for left or down.

**Comment by baldurk** [comment]
This is fully implemented by @orsonbraines and @jskattuk in the above PR and #2406
