### ISSUE TITLE
Shader messages export problem - Thread column mixed with Message

### ISSUE THREAD

**Issue by ichlubna** [baldurk/renderdoc#2324]
## Description

The export is working now but seems like the columns are shifted. The Thread one is skipped and its values are placed in the Message one. Here:
![export](https://user-images.githubusercontent.com/43234438/126743371-48b339d1-04b3-4156-adda-fc152e64a23f.jpg)

## Environment

* RenderDoc version: 1.15 (4c4b0c58)
* Operating System: Arch Linux
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Sorry, I forgot that the number of columns was different for compute shaders. That commit should fix it.

In future **please** use the correct issue template. This is a bug report and not a feature request so it should use the bug report template, including steps to reproduce (even if they are trivial). This keeps things smoother for everyone.

**Comment by ichlubna** [comment]
@baldurk Thanks and sorry. I must have chosen the bad one. ^_^"
