### ISSUE TITLE
VC 2015 U 2 Compile error

### ISSUE THREAD

**Issue by TiemoJung** [baldurk/renderdoc#233]
Hi,

after updating vc 2015 to update 2 the compiler complaints about this:
tinyexr\tinyexr.cpp(2097): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
with treat warnings as errors this turns into an error.

**Comment by baldurk** [comment]
Yes this will probably need to become an issue upstream in tinyexr, but in the meantime I can commit a workaround so that renderdoc still compiles.

**Comment by baldurk** [comment]
I updated to the latest version of the library, and also made a manual fix for this warning (and opened an issue about it upstream).

**Comment by TiemoJung** [comment]
Hi,

compiles now without any error, thanks!
