### ISSUE TITLE
Document and/or fail build early on unsupported platforms

### ISSUE THREAD

**Issue by autumnontape** [baldurk/renderdoc#2332]
## Description

I tried building RenderDoc on an armv7h device running Arch Linux ARM today. The build took a while and proceeded to the linking stage before failing. I went to the issue tracker for information and found issue #2194, which revealed the platform wasn't supported and that I wasn't the first to make this mistake.

This is a risk I took by building on a platform I hadn't been able to confirm was supported, but it's also close to a worst-case scenario. I tried to find information on whether ARM-based desktop Linux systems were supported by RenderDoc before building, but I found none until I went to the issue tracker. An easy-to-find list of supported platforms or an earlier failure would have saved me a lot of time.

## Environment

* RenderDoc version: 1.15
* Operating System: Arch Linux ARM (armv7h)
* Graphics API: N/A

**Comment by baldurk** [comment]
I've added a note that only 64-bit x86 is supported both to the README as well as to the documentation on compiling and dependencies.
