### ISSUE TITLE
Shortcut button to reset edited shader to default input

### ISSUE THREAD

**Issue by tayfunkayhan** [baldurk/renderdoc#2334]
## Description

It's often the case that after editing an existing shader of a given operation, be it a draw or dispatch, I need to reset the shader to default source. To do this, I go back to Pipeline State and re-click Edit shader to start over with a good base. Having a UI button to reset shader currently being edited (maybe next to Refresh) could speed up and simplify this process a lot.

Note that I am aware of undo functionality, but after a changes in a long shader, it gets hard to keep track of what's exactly undone and what's not, so I go with "reset" path to be sure.

## Environment

* RenderDoc version: 1.15
* Operating System: Windows
* Graphics API: Vulkan

**Comment by baldurk** [comment]
That commit should add a reset button. I also thought it might be useful to have a quick way to toggle between the edited shader and the original one, without losing your changes (and without having to force a compile error where it defaults back to the original shader).

**Comment by tayfunkayhan** [comment]
Even better! I just tested it, it looks great. Thank you!
