### ISSUE TITLE
Shadow does not show display

### ISSUE THREAD

**Issue by zhouhuamin** [baldurk/renderdoc#2336]
## Description

I have an OpenGL ES Demo program. The shadow texture is rendered in the first frame and the texture is referenced in the subsequent frames, but the shadow cannot be seen in playback after the capture. Is there a problem with the captured shadow data? Does the program have a way to solve this situation?

## Steps to reproduce

There is an apk program in the compressed package: NativeActivity-debug.apk
[NativeActivity-debug.zip](https://github.com/baldurk/renderdoc/files/6949139/NativeActivity-debug.zip)

## Environment

* RenderDoc version: RenderDoc v1.15
* Operating System: Win 10
* Graphics API: OpenGL ES 3.2

**Comment by baldurk** [comment]
That commit implements emulated depth readbacks on OpenGL ES, which is necessary for properly replaying depth textures with contents from previous frames. The application captures and replays correctly with that change.
