### ISSUE TITLE
The tab for viewing shader source has no title on Vulkan

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2337]
## Description

The tab for viewing shader source has no title when using Vulkan.  This does not affect D3D11 or D3D12, but does affect both pixel and vertex shaders.  Actual debugging seems to work correctly, though.

![image](https://user-images.githubusercontent.com/8334194/128609302-f7afdad3-5a07-4e8a-9784-d1ad48f4e5c1.png)

## Steps to reproduce

Download and open [Lesson08.rdc](https://github.com/baldurk/renderdoc/files/6949540/Lesson08Vulkan.zip).  Debug a pixel or a vertex.  Observe that the disassembly tab has a name, but not the source tab.

The attached capture was made using Dolphin 5.0-14841 with the [lesson08 demo](https://github.com/devkitPro/gamecube-examples/tree/master/graphics/gx/neheGX/lesson08).  The Vulkan backend was selected, and "Enable API Validation Layers" is also checked (which is what enables source attachment now that dolphin-emu/dolphin#9996 has been merged).

## Environment

* RenderDoc version: v5.15
* Operating System: Windows 10.0.19042.1110
* Graphics API: Vulkan

**Comment by baldurk** [comment]
This is working as it should - the SPIR-V modules in that capture specify that the filename is a blank string:

```
          %1 = OpString ""
               OpSource GLSL 450 %1 "
  // Target GLSL 4.5.
  #version 450 core
  #define ATTRIBUTE_LOCATION(x) layout(location = x)
  ...
```

The `%1` parameter being the filename.

**Comment by Pokechu22** [comment]
That makes sense (since it's a generated shader), but I think it would be useful to have a fallback name for the tab since it's still a bit confusing.

**Comment by baldurk** [comment]
If you want a filename then you can specify it in the SPIR-V when building the shader. I don't see that as a good reason to override what is explicitly specified since then there's no way for someone to specify an empty filename if they want it.

**Comment by Pokechu22** [comment]
Under what context would an explicitly empty filename be useful?  I don't think any OS lets you have a file with an empty name (though you can have one starting with a `.`).  I don't have much familiarity with SPIR-V, but looking at the documentation it seems like both File and Source in [OpSource](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpSource) are optional, and source comes second, which makes me assume that to specify Source, File also needs to be specified.

I will look into specifying a name of some sort to specify the parameters to the generated shader since that could be useful, but it still seems like odd behavior.

**Comment by baldurk** [comment]
I don't know off hand but I would need a much stronger reason to block this from working. The filename is entirely arbitrary and doesn't have to correspond to an on-disk filename.

It's behaving as specified and no functionality is broken - you can still see the source and select that tab - it's just that you personally want a fallback filename instead of an empty filename. If you don't have a filename and want to only provide the source, as you mentioned the filename is required in that case (similar to C++ default parameters) but you can specify whichever placeholder makes sense for you as easily as I can in RenderDoc, and it means that someone who might want an empty filename can do so.

**Comment by Pokechu22** [comment]
I did some more testing, and it seems like the filename _isn't_ actually required, but Glslang acts like it is... somewhat.  See 
[Lesson08Vulkan_ModifiedGlslang.zip](https://github.com/baldurk/renderdoc/files/6963968/Lesson08Vulkan_ModifiedGlslang.zip).

Dolphin currently only calls [`glslang::TIntermediate::addSourceText`](https://github.com/KhronosGroup/glslang/blob/aa2d4bd2f48184974961dbbbae3f29d967c45803/glslang/MachineIndependent/localintermediate.h#L976), not [`glslang::TIntermediate::setSourceFile`](https://github.com/KhronosGroup/glslang/blob/aa2d4bd2f48184974961dbbbae3f29d967c45803/glslang/MachineIndependent/localintermediate.h#L974).  However, the `sourceFile` field defaults to `""` as an uninitialized `std::string`.  `TGlslangToSpvTraverser`'s constructor calls [`builder.setSourceFile(glslangIntermediate->getSourceFile())`](https://github.com/KhronosGroup/glslang/blob/master/SPIRV/GlslangToSpv.cpp#L1518) if `generateDebugInfo` is enabled, which [allocates a new StringId if needed](https://github.com/KhronosGroup/glslang/blob/aa2d4bd2f48184974961dbbbae3f29d967c45803/SPIRV/SpvBuilder.h#L102-L105), even for an empty string, and that replaces the default value of [`sourceFileStringId` (`NoResult`)](https://github.com/KhronosGroup/glslang/blob/aa2d4bd2f48184974961dbbbae3f29d967c45803/SPIRV/SpvBuilder.cpp#L64), which means the current logic doesn't allow the source file to be optional.  Additionally, [`Builder::dumpSourceInstructions`](https://github.com/KhronosGroup/glslang/blob/aa2d4bd2f48184974961dbbbae3f29d967c45803/SPIRV/SpvBuilder.cpp#L3249-L3252) assumes that `fileId != NoResult` is required for `text.size() > 0`.  Both of these can be worked around, though.

<details><summary>Draft code to create a file with source text but no file</summary>

```diff
diff --git a/Externals/glslang/SPIRV/GlslangToSpv.cpp b/Externals/glslang/SPIRV/GlslangToSpv.cpp
index 0c8a87e3ce..be9fa2b090 100644
--- a/Externals/glslang/SPIRV/GlslangToSpv.cpp
+++ b/Externals/glslang/SPIRV/GlslangToSpv.cpp
@@ -1369,7 +1369,7 @@ TGlslangToSpvTraverser::TGlslangToSpvTraverser(unsigned int spvVersion, const gl

     if (options.generateDebugInfo) {
         builder.setEmitOpLines();
-        builder.setSourceFile(glslangIntermediate->getSourceFile());
+        // builder.setSourceFile(glslangIntermediate->getSourceFile());

         // Set the source shader's text. If for SPV version 1.0, include
         // a preamble in comments stating the OpModuleProcessed instructions.
diff --git a/Externals/glslang/SPIRV/SpvBuilder.cpp b/Externals/glslang/SPIRV/SpvBuilder.cpp
index bd208952e0..45200e50de 100644
--- a/Externals/glslang/SPIRV/SpvBuilder.cpp
+++ b/Externals/glslang/SPIRV/SpvBuilder.cpp
@@ -3040,7 +3040,8 @@ void Builder::dumpSourceInstructions(const spv::Id fileId, const std::string& te
         sourceInst.addImmediateOperand(source);
         sourceInst.addImmediateOperand(sourceVersion);
         // File operand
-        if (fileId != NoResult) {
+        if (fileId != NoResult || text.size() > 0)
+        {
             sourceInst.addIdOperand(fileId);
             // Source operand
             if (text.size() > 0) {
```
</details>

As far as I can tell, this works without issue for most use cases, and I don't think it violates the spec, but RenderDoc still has a blank tab name in this case.  The disassembly does change (showing `Source(GLSL, 450);` instead of `Source(GLSL, 450, file: _1);`), though.

I'll look into sending a PR to Glslang to not set the source file to an empty string if `setSourceFile` is never called, but for now it's probably not that important.
