### ISSUE TITLE
[Vulkan] Adding tags to shader modules via VK_EXT_debug_utils

### ISSUE THREAD

**Issue by corporateshark** [baldurk/renderdoc#2338]
## Description

As of RenderDoc 1.15, it can show disassembled source code of Vulkan shader modules. It is useful to tag a shader module with the original shader source code and other textual information provided by the app.

## App usage example

```
const VkDebugUtilsObjectTagInfoEXT ti = {
  .sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_TAG_INFO_EXT,
  .objectType = VK_OBJECT_TYPE_SHADER_MODULE,
  .objectHandle = shaderModule,
  .tagName = 0,							// a tag ID understandable by RenderDoc
  .tagSize = shaderSourceCodeLength,
  .pTag = shaderSourceCodeString
};
vkSetDebugUtilsObjectTagEXT(device_, &ti);
```

## Environment

* RenderDoc version: 1.15
* Operating System: Windows
* Graphics API: Vulkan

**Comment by baldurk** [comment]
The source can already be passed in as part of the SPIR-V module itself, along with other debug information like variable names etc. I do not want to add an alternate way of specifying this that only covers part of the problem and requires specifying how e.g multiple files will be passed etc.
