### ISSUE TITLE
Capture load hang up if many indirect draws are used

### ISSUE THREAD

**Issue by tomdrinKEENSWH** [baldurk/renderdoc#2341]
## Description

Hello, I'm experiencing a problem where many draw calls (100k+) inside DirectX12 ExecuteIndirect commands result in RenderDoc freeze during capture loading.

## Steps to reproduce
I have sent the email to baldurk@baldurk.org with link to sample application (subject is the same as issue)

1. Run sample application
2. Hit F12 
3. Exit application
4. Observe capture loading hang up

## Environment

* RenderDoc version: 1.15
* Operating System: Windows 10
* Graphics API: DirectX12

**Comment by baldurk** [comment]
I replied over email as well, but the application doesn't run for me (on its own, not through renderdoc).

**Comment by tomdrinKEENSWH** [comment]
I can confirm the issue has been fixed. At least for my use cases. Thanks a lot.
