### ISSUE TITLE
Showing "SPIRV-Cross (GLSL)" disassembly doesn't use the entry point

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#2342]
## Description

I use a single SPIRV module with 2 entry points. When I Pipeline state -> FS -> view shader, and I switch to "SPIRV-Cross (GLSL)", it shows me the vertex function. I assume the logic just takes the first entry point? It needs to use the actual entry point of the stage, instead.

## Steps to reproduce

[nvidia-flat-interpolation.rdc.zip](https://github.com/baldurk/renderdoc/files/6971213/nvidia-flat-interpolation.rdc.zip)

1. Load the capture on NVidia/Linux.
2. Navigate to EID 19
3. Select "Pipeline State" tab
4. Select "FS"
5. View shader module
6. Switch to "SPIRV-Cross (GLSL)"

## Environment

* RenderDoc version: 1.15
* Operating System: linux x86_64
* Graphics API: Vulkan

**Comment by baldurk** [comment]
I believe that commit should do the trick. Indeed I wasn't specifying the entry point at all for spirv-cross so spirv-cross's behaviour was to default to the first one.
