### ISSUE TITLE
GPUCounter.EventGPUDuration claims to be type Float, but the real value seems to be in result.value.d

### ISSUE THREAD

**Issue by charmatt** [baldurk/renderdoc#2343]
## Description

I ran into this issue while trying to measure GPU frame timings using the renderdoc Python API. `ReplayController.DescribeCounter(renderdoc.GPUCounter.EventGPUDuration).resultType` returns "CompType.Float", and so I would expect to read its value from `CounterValue.f` . However, this was giving me garbage results. Digging into the RenderDoc source, I see that `EventBrowser::SetTimes()` uses `r.value.d`, and using this in my own code gives reasonable numbers. Looking at the CompType class, there's no entry for Double, so I'm assuming it treats Doubles as Floats - it would be helpful if this was explicitly stated in the docs for `CounterResult`. 

## Steps to reproduce

- From the Python API, load any capture into a ReplayController 
- query controller.DescribeCounter(renderdoc.GPUCounter.EventGPUDuration).resultType - returns "CompType.Float"
- compare the values of `result.value.f` and `result.value.d` in the results of controller.FetchCounters([rd.GPUCounter.EventGPUDuration]) - result.value.d contains the real data

## Environment

* RenderDoc version: 1.15
* Operating System: Windown 10 64-bit
* Graphics API: D3D11

**Comment by baldurk** [comment]
You've only used half of the information that `CounterDescription` gives about the result type. The `CompType` enumeration describes only the _base type_ of the data - i.e. float, signed integer, unsigned integer. From [the documentation of `CompType.Float`](https://renderdoc.org/docs/python_api/renderdoc/formats.html#renderdoc.CompType.Float):

> **Float**
> An IEEE floating point value of 64-bit, 32-bit or 16-bit size.

The other important part is `CounterDescription.resultByteWidth` which tells you which size, and you should see that it returns `8` when the information is stored in doubles, which tells you that you need to look in `CounterResult.d`. If it returned `4` then the data would be stored in `CounterResult.f`.
