### ISSUE TITLE
Crash when creating a VkImage using VMA

### ISSUE THREAD

**Issue by MarcasRealAccount** [baldurk/renderdoc#2344]
## Description
I'd like to create a **`VkImage`** using **VMA** (Vulkan Memory Allocator).
But whilst debugging using **RenderDoc** it causes a crash as soon as I call **`vmaCreateImage`**.
That should obviously not happen.

To be more specific it crashes when **VMA** calls **`vkGetImageMemoryRequirements2KHR`**.

I have stepped through the assembly code and it seems like it crashes at [vk_get_funcs.cpp#L304](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/vulkan/wrappers/vk_get_funcs.cpp#L304).
Though I should say I haven't built **RenderDoc** with debug information, so I couldn't step through the actual source code, I'm just assuming it probably is that line due to it crashing at the first **`call`** instruction which calls a function ptr it seems.

The program runs just fine on it's own without **RenderDoc**

## Steps to reproduce
The main file containing all code is [here](https://github.com/MarcasRealAccount/VulkanTemplate/blob/05348a8b77ce988fc5908da80aeb12ab2dcae524/VulkanProgram/src/Main.cpp) and the crash happens at [main.cpp#L369](https://github.com/MarcasRealAccount/VulkanTemplate/blob/05348a8b77ce988fc5908da80aeb12ab2dcae524/VulkanProgram/src/Main.cpp#L369)
If you need to build it, all you have to do is just do a git clone recursive thingy, then if you have premake5 installed you just generate with that, it assumes the **`VULKAN_SDK`** environment variable has been set.

## Environment
* RenderDoc version: 1.15 built from a4906060
* Operating System: Windows 11 21H2 build 22000.120
* Graphics API: Vulkan 1.2
* GPU: RTX 2080 Super Founders Edition, Driver version: 471.68

**Comment by baldurk** [comment]
Your code looks to me like it's invalid. You're explicitly creating a 1.0 instance but the instance version you're passing to vma is whatever is enumerated from the driver, for your GPU and driver that would presumably be 1.2. This will cause VMA to use core 1.2 functionality like `vkGetImageMemoryRequirements2` which is not valid on a 1.0 instance.

Please check that your code behaves correctly and doesn't have any validation errors. RenderDoc does not handle invalid API use.

**Comment by MarcasRealAccount** [comment]
Ah yes, it wasn't so much a bug as I thought.
I think what happened was that when I didn't use **RenderDoc** the vulkan implementation had no problems calling **`vkGetImageMemoryRequirements2KHR`**, but as soon as a layer was introduced that implemented an override for that function it had no idea how to pass information to the layer.
Honestly a bit weird as it should've crashed with or without **RenderDoc**

The code did behave correctly without **RenderDoc** and I had no validation errors either, which was also a bit weird.

**Comment by baldurk** [comment]
You should double check that your system is configured correctly, because this should have been crashing or at least giving a validation error even without RenderDoc. With a 1.0 instance with only WSI extensions enabled on the device VMA should have been obtaining `NULL` for these functions. I tried building your program at the previous commit and it crashed immediately for me inside `vmaCreateImage`.

I'd guess that the cause is that you have a buggy layer installed on your system. If you have any software like RTSS, OBS, overwatch, etc these layers can cause misbehaviour.

**Comment by MarcasRealAccount** [comment]
Yeah I've got OBS installed, but I wouldn't believe that it could cause that tho, but now I know :)
