### ISSUE TITLE
Is there any way to capture the The Division?

### ISSUE THREAD

**Issue by yonjiang** [baldurk/renderdoc#2346]
# Description
Hello,
I have try to capture the Tom Clancy's: The Division with renderdoc, but the game seems to launch after the Ubisoft client interface launches. The call to steam is also included. After that, there is no renderdoc information display in the upper left corner. Is that interrupts renderdoc calls? Is there any way to solve  this?

# Environment
Windows 10
Renderdoc 1.15

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by yonjiang** [comment]
Thank you for raising my copyright awareness!!
