### ISSUE TITLE
EndFrameCapture crashes after vkDestroyDevice

### ISSUE THREAD

**Issue by scygan** [baldurk/renderdoc#2349]
## Description

The issue happens for some of dEQP (https://github.com/KhronosGroup/VK-GL-CTS) Vulkan tests, when run under RenderDoc.  

_Note: for me, RenderDoc proved extremely helpful when debugging these tests, both in terms of getting the idea of what the test is submitting, so as narrowing the actual problems._ 

As dEQP is (mostly and especially Vulkan CTS) a faceless application, it uses in-app RenderDoc API to start and end 'frame' capture between the tests. 

The problem is:

- some of tests require more VK extensions or features in the VkDevice than provided by the framework, so they create own VkDevice. 
- this causes the tests to end with vkDestroyDevice, where the `WrappedVulkan::m_Device` gets zeroed. 
- however, `m_Device` is later used in `EndFrameCapture()`, leading to a crash. 

After skimming through the code, it looks like currently RenderDoc does not have support for having multiple devices.

Still, would it be possible for either: 
 - modify `EndFrameCapture()`, so it does not touch the VkDevice if it is deleted?
 - Making m_Device a kind of set, so `vkDestroyDevice()` would just pop one device and some other device would take place?
?

## Steps to reproduce

Download VK-GL-CTS from https://github.com/KhronosGroup/VK-GL-CTS,  build Vulkan CTS according to bundled instructions. 
Run: 
`deqp-vk.exe -n dEQP-VK.multiview.masks.1_2_4_8 --deqp-renderdoc=enable`

## Environment
* RenderDoc version: 1.15
* Operating System: Windows 10
* Graphics API: Vulkan

 * Drivers: tried Intel or Nvidia (should not matter)

**Comment by baldurk** [comment]
As you've seen RenderDoc does not support multiple devices (in particular it doesn't support multiple _simultaneous_ devices, it should function correctly if you create and destroy such that only one device is alive at any given time) but I think that's tangential to what you're describing.

If I understand right you are destroying the vulkan device before calling `EndFrameCapture`? That is not supported and I don't plan to change that, RenderDoc needs to do a significant amount of device work to finish the capture and that can't happen if the device has been destroyed. Deferring destruction is also not generally safe or possible in this case.

I'll leave this open for now in case you want to clarify - if I haven't understood correctly let me know. But if I've got the right idea then at most this is something that should be more explicitly documented in the API, I hadn't considered someone doing this before. You will need to either call `EndFrameCapture` before destroying the device, or else avoid calling `EndFrameCapture` entirely - that will probably leak but if you're about to destroy the instance and shut down the process it should be fine.

**Comment by scygan** [comment]
Thank you for your answer!  You understood correctly.

To be more specific,  there are two VkDevices involved, created (but not 'used') _simultaneously_, both from the same instance and physical device:

pseudocode:
````
dev1 = vkCreateDevice(instance, ...)

StartFrameCapture(instance, ...)

dev2 = vkCreateDevice(instance, ...{more features / extensions}.. )
// .. a workload to be debugged submitted to dev2 ..
vkDestroyDevice(dev2, ...)

EndFrameCapture(instance,  ...)  // crashes here

vkDestroyDevice(dev1, ...)   

````

Nothing is submitted to dev1 between StartFrameCapture / EndFrameCapture.

I think my question would be: understanding that EndFrameCapture needs to have a device, does it need the exactly same device the workload was submitted on?

**Comment by baldurk** [comment]
Yes there must only be one VkDevice alive at any time, and the same device must be used for everything - starting capture, all work being captured, and ending the capture.

As soon as you call the second `vkCreateDevice` without `vkDestroyDevice(dev1)` first that's not supported, and I can't guarantee anything will work after that. I know this is illegal vulkan but there's no way to sensibly express this limitation (I guess I could make the second `vkCreateDevice` return `VK_ERROR_INITIALIZATION_FAILED` but that's not particularly useful or intuitive either so I don't think that would help anyone) and it's not something I plan to change so is unlikely to be supported in future.

If you skipped the create and destroy of `dev1` this would be fine, or if you destroyed `dev1` before creating `dev2` that would also work, but the pseudocode you outline is not something I intend to support.
