### ISSUE TITLE
ID3D11Device3::CreateRasterizerState2 crash

### ISSUE THREAD

**Issue by bkaradzic** [baldurk/renderdoc#235]
I'm getting crash when using ID3D11Device3::CreateRasterizerState2 on Windows 10.

If you need repro case you can do it by running bgfx on Windows 10:
https://github.com/bkaradzic/bgfx/blob/master/src/renderer_d3d11.cpp#L2984

**Comment by baldurk** [comment]
This is down to the same underlying reason as #232 - ID3D11Device3 or ID3D11DeviceContext3 isn't wrapped yet.

**Comment by baldurk** [comment]
I believe this should do the trick - I removed the renderdoc restriction on device level and let bgfx create a ID3D11RasterizerState2 and it seemed to capture fine.

**Comment by baldurk** [comment]
Closing this issue as newer D3D11 and DXGI support is implemented in [v0.30](https://github.com/baldurk/renderdoc/releases/tag/v0.30). I tested with bgfx with the hack backed out, but feel free to re-open if it's not as you expect or it's buggy!
