### ISSUE TITLE
Saving a capture with ctrl+s when the launched application is still running results in the capture still acting as if it was unsaved when closing RenderDoc

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2352]
## Description

If a capture is saved using <kbd>ctrl</kbd>+<kbd>s</kbd> or the file menu (with either "save capture" or "save capture as"), while the tab for captures collected from a process is still open, then later closing renderdoc will show a warning that that capture is not saved, but trying to save it fails.

## Steps to reproduce

1. Open RenderDoc.
2. Launch any application (I used Dolphin.)
3. Make a capture, but _don't_ close the launched application.
4. Switch back to RenderDoc.
5. Double-click the capture (or right-click and select "open in"&rarr;"this instance")
6. Save the capture with <kbd>ctrl</kbd>+<kbd>s</kbd> (or "File"&rarr;"Save Capture" or "File"&rarr;"Save Capture As", but <em>not</em> by right-clicking the capture and selecting save)
7. Close the program that was launched earlier.
8. Attempt to close RenderDoc.
9. Despite saving the capture, an unsaved captures warning will appear.  Select "yes" on this warning.
10. Enter a new name to save the capture with.
11. A "cannot save" message will appear, with text similar to "Couldn't copy file to C:/Users/Pokechu22/Documents/Test2.rdc" "Cannot open C:\Users\Pokechu22\AppData\Local\Temp\RenderDoc\Dolphin_2021.08.27_04.18.56_frame58.rdc for input".
12. Selecting "OK" will close that message and leave RenderDoc open.  The only way to close RenderDoc is to say no on the unsaved captures warning.

A related way of reproducing:

1. Open RenderDoc.
2. Launch any application (I used Dolphin.)
3. Make two captures, and then close the application.
4. Switch back to RenderDoc.
5. Double-click the first capture (or right-click and select "open in"&rarr;"this instance")
6. Save the capture with <kbd>ctrl</kbd>+<kbd>s</kbd> (or "File"&rarr;"Save Capture" or "File"&rarr;"Save Capture As", but <em>not</em> by right-clicking the capture and selecting save)
7. Attempt to close RenderDoc.
8. Despite saving the capture, an unsaved captures warning will appear for the first capture.  Select "yes" on this warning.
9. Enter a new name to save the capture with.
10. A "cannot save" message will appear, with text similar to "Couldn't copy file to C:/Users/Pokechu22/Documents/Test2.rdc" "Cannot open C:\Users\Pokechu22\AppData\Local\Temp\RenderDoc\Dolphin_2021.08.27_04.18.56_frame58.rdc for input".
11. Selecting "OK" will close that message and leave RenderDoc open.  The only way to close RenderDoc is to say no on the unsaved captures warning for the first capture (saying "yes" on the second capture is fine).

Note that two captures or not closing the application is required because if exactly one capture is made, RenderDoc will open it automatically and hide the captures list.

A different, but probably related issue happens when replacing the "attempt to close RenderDoc" step with double-clicking the capture a second time (which is something that may be reasonably done when multiple captures are made, but can also be done with just one capture and leaving the application open).  In that case, an "Error opening capture" message will appear, with text like "Couldn't open file 'C:\Users\Pokechu22\AppData\Local\Temp\RenderDoc\Dolphin_2021.08.27_04.35.09_frame27.rdc'" "File not found: Can't open capture file 'C:\Users\Pokechu22\AppData\Local\Temp\RenderDoc\Dolphin_2021.08.27_04.35.09_frame27.rdc' for read - errno 2".  I'd be fine with creating a separate report for this if needed, but it feels like it probably has the exact same root cause as the unsaved captures issue.

I most likely ran into this because Dolphin has one window for emulation, which I usually close after I've made my capture, but then a separate game list window that I sometimes forget to close.  That would follow the first steps to reproduce.

## Environment

* RenderDoc version: v1.15
* Operating System: Windows 10.0.19042.1165
* Graphics API: Tested with D3D11.

**Comment by baldurk** [comment]
Thanks for the very clear explanation, that commit should close this hole in the workflow.

**Comment by Pokechu22** [comment]
Confirmed fixed in Nightly v1.16 - 1b192083233.  I did find a separate, related bug, though: #2358
