### ISSUE TITLE
Quad Overdraw not working in D3D12

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#2356]
## Description

I have a D3D12 application, and I can't get quad overdraw to work, both the pass and draw versions. I've used this in the past in D3D11 and it looks to still be working. Is it just a limitation in the current implementation?

## Steps to reproduce

1) Load any D3D12 capture
2) Select a geometry action
3) Select quad overdraw from the dropdown

## Environment

* RenderDoc version: 1.15
* Operating System: Windows 10
* Graphics API: D3D12
* GPU: RTX 2060 SUPER

**Comment by baldurk** [comment]
The feature is supported on all APIs and works fine for me if I test it on MS's ModelViewer D3D12 demo. It's also tested in the automated nightly tests.

Please provide a specific reproducible test case such as a capture or your application, so I can investigate further.

**Comment by baldurk** [comment]
This was an annoying and silly requirement from D3D12 where the pixel shader input signature needs to match the vertex shader signature, even if there is no interpolated data at all (the quad overdraw replaces the pixel shader with one which reads coverage and pixel co-ordinate). That commit will graft the vertex shader output signature onto the pixel shader.
