### ISSUE TITLE
Wireframe (Pass) in debug overlays

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#2357]
## Description

I've been told by one of our artists that it would be useful to have a Wireframe (pass) overlay. They want to see what the entire scene looks like from a vert vs pixel perspective. I'm not entirely sure that filling it all with yellow would be useful, perhaps making every mesh a different color would help (like the heatmap). Just something to consider.

## Environment

* RenderDoc version: 1.15
* Operating System: Windows 10
* Graphics API: D3D12

**Comment by baldurk** [comment]
I'm not sure I fully understand what you're asking for. Can you please describe in more detail exactly what problem you're trying to solve and what you're trying to debug that would need this? Taking a step back to describe the situation and why you want this tool for debugging helps me understand the motivation and scope and I can consider it with more context.

I also don't know what you mean about making every mesh a different colour "like the heatmap" - the only heatmap is the quad overdraw view which is not a per-mesh colouring at all.

For what it's worth the mesh viewer allows you to select 'show whole pass' in the dropdown of what context to show, which lets you see the whole pass. As with anything though in wireframe, with sufficient density it becomes not very usable.

**Comment by redorav** [comment]
In the same way there is a quad overdraw (pass) and a quad overdraw (draw) they were asking for a mode where you can see the wireframe for an entire pass. 

Since a single color is (like you mention) not very useful for very dense scenes, I was suggesting having a color per rendered mesh, with the same color palette as the heatmap (sorry my wording was poor there) to be able to distinguish the meshes better.

They want this to assess the overall density of a scene, and spot particularly bad cases where maybe a LOD is missing, etc. As I'm saying this, perhaps the triangle size is adequate, although it does take a relatively long time to do for a big pass.

Hopefully it's clearer now.

**Comment by baldurk** [comment]
What you're describing seems like a profiling/performance analysis use-case. RenderDoc is a debugger only, not a profiler, so functionality like that is not in scope and isn't something I plan on adding.

**Comment by redorav** [comment]
That's fair enough, thanks for taking the time
