### ISSUE TITLE
SEGV error launching Android application on Oculus Quest

### ISSUE THREAD

**Issue by slopate** [baldurk/renderdoc#2362]
## Description

I am having issues launching my  Android app with RenderDoc. I am using UE4 and testing on an Oculus Quest (Open GL ES3.1).
When I try to launch the app, I get a segmentation fault in the RenderDoc thread (callstack below). I have used RenderDoc successfully before so I know the issue is likely on my end, I am just not sure what changed or where to look. I have also searched through the GitHub issues and saw some people have experienced the same issue, but I wasn't able to find a solution that worked for me. 

## Steps to reproduce

1. In Unreal Engine settings, ensure ForDistribution = false.
2. Build Android (ASTC) Development build. 
3. Deploy build to Quest, and connect to Quest via adb
4. Locate "Oculus Quest" device in RenderDoc and attempt to launch application executable.
5. Quickly after attempting to launch my application fails with the callstack below.

```
F/DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3a02
F/DEBUG   :     x0  0000000000003a02  x1  0000007cbeb695e0  x2  0000007c3b42a7c0  x3  0000007bd80055e0
F/DEBUG   :     x4  0000000000000000  x5  0000007c3b4447c0  x6  0000007bd4e4a67c  x7  0000000000000000
F/DEBUG   :     x8  8b3a79eeed5ef9a2  x9  0000007bd4e4be18  x10 0000000000003a02  x11 0000007ba1ec8000
F/DEBUG   :     x12 e000000000000000  x13 0000000000000001  x14 0000007bd55a9540  x15 0000007b80000000
F/DEBUG   :     x16 0000007cbcbe1110  x17 0000007cbcbd67b4  x18 0000007bb70d2000  x19 0000007cbda779c8
F/DEBUG   :     x20 0000000000000000  x21 0000007bd4e4c980  x22 0000007c295f2a00  x23 0000007cbda77a70
F/DEBUG   :     x24 0000007cbeb57151  x25 0000007cbeb57805  x26 0000000000000000  x27 0000000000000000
F/DEBUG   :     x28 0000007bd4e52020  x29 0000007bd4e4b620
F/DEBUG   :     sp  0000007bd4e4b5b0  lr  0000007bce5663d8  pc  0000007bce5662f8
F/DEBUG   : 
F/DEBUG   : backtrace:
F/DEBUG   :       #00 pc 00000000009662f8  /data/app/com.oculus.renderdoccmd.arm64-oz-QYKQqsXrCLIPqffD5ig==/lib/arm64/libVkLayer_GLES_RenderDoc.so (GetKey(void*)+20) (BuildId: db54eed065f1ab5bfbf15dfad2ce6c114d76e0e5)
F/DEBUG   :       #01 pc 00000000009663d4  /data/app/com.oculus.renderdoccmd.arm64-oz-QYKQqsXrCLIPqffD5ig==/lib/arm64/libVkLayer_GLES_RenderDoc.so (InitInstanceTable(VkInstance_T*, void (*)() (*)(VkInstance_T*, char const*))+36) (BuildId: db54eed065f1ab5bfbf15dfad2ce6c114d76e0e5)
F/DEBUG   :       #02 pc 0000000000fa8b5c  /data/app/com.oculus.renderdoccmd.arm64-oz-QYKQqsXrCLIPqffD5ig==/lib/arm64/libVkLayer_GLES_RenderDoc.so (WrappedVulkan::vkCreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**)+5172) (BuildId: db54eed065f1ab5bfbf15dfad2ce6c114d76e0e5)
F/DEBUG   :       #03 pc 0000000000ef8f0c  /data/app/com.oculus.renderdoccmd.arm64-oz-QYKQqsXrCLIPqffD5ig==/lib/arm64/libVkLayer_GLES_RenderDoc.so (hooked_vkCreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**)+80) (BuildId: db54eed065f1ab5bfbf15dfad2ce6c114d76e0e5)
F/DEBUG   :       #04 pc 0000000000012a0c  /system/lib64/libvulkan.so (vulkan::api::CreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**)+1844) (BuildId: 66f345141474d8683c56ee52cba9c151)
```

A few things I have tried, unsuccessfully:
- Different versions of RenderDoc (30.4, 30, 29, and 25)
- Development and shipping builds
- Nativized and non-nativized builds
- Verified Android SDK and JDK paths are pointing to the correct places

Also, I'm not sure why RenderDoc is making calls into the Vulkan API, as my application does not support Vulkan. Don't want to make assumptions about what's happening behind the scenes though.

## Environment

* RenderDoc version: 30.4
* Operating System: Windows 10 Home (PC) / Android 7 (Quest)
* Graphics API: NVIDIA GeForce RTX 2060, Driver version 466.11 (PC) / OpenGL ES3.1 (Quest)
* ADB Version 1.0.41
* UE4 Version 4.26.2

Let me know if there's any other info I can provide. Like I said, I'm fairly sure this is an issue on my end, just hoping I could get some help with troubleshooting. Thank you!

**Comment by baldurk** [comment]
I can look into this but can you please share your APK? I don't use Unreal engine so skipping over how to set up a project that's compatible leaves out a lot. How the APK is built shouldn't matter as long as I can run it.

You're listing nonsense version numbers for RenderDoc. I don't know what versions these could mean, if you're running builds as old as v0.34 and v0.30 then please update as those are _many years old_!

**Comment by slopate** [comment]
A couple things:

Sorry, I didn't specify I'm using the RenderDoc For Oculus: https://developer.oculus.com/blog/renderdoc-for-oculus/
When I was saying the version numbers I was referring to those numbers. I'm not sure exactly how that differs from the source version. If you recommend I try the non-Oculus version I can do that. In the past I had used the Oculus version since I'm running on a Quest.

Let me know if the above detail changes anything; if not I can email you the APK.

**Comment by baldurk** [comment]
Please don't file issues here related to other people's software, I can't provide any support for what someone else has done with RenderDoc with unknown modifications, so if you want assistance with Oculus's fork please contact Oculus.

If you have a problem with this version of RenderDoc then please test again with the latest version of RenderDoc and file a new issue.
