### ISSUE TITLE
When launched in RenderDoc, a Vulkan app reports fewer extensions via `vkEnumerateDeviceExtensionProperties`

### ISSUE THREAD

**Issue by expenses** [baldurk/renderdoc#2364]
## Description

I'm writing a program using the vulkan ray tracing api that I'd like to be able to debug. For this, I'm using Vulkan 1.2 with a few extensions such as `VK_KHR_swapchain` (of course), `VK_KHR_deferred_host_operations`, `VK_KHR_acceleration_structure` etc.

I do a check at startup for these extensions via `vkEnumerateDeviceExtensionProperties` (technically through the [`ash`](https://crates.io/crates/ash) function [`enumerate_device_extension_properties`](https://docs.rs/ash/0.33.3+1.2.191/ash/struct.Instance.html#method.enumerate_device_extension_properties)).

When I run my program through RenderDoc, the list of extensions is a bit shorter (missing 16, including `VK_KHR_deferred_host_operations` and `VK_KHR_acceleration_structure` but not `VK_KHR_swapchain`) and it is also in a different order.

Here's a diff of the different log output:

https://gist.github.com/expenses/b4f2f404cedea56b9f2567112248e376

The reported API and driver versions remained the same, so I'm not sure what could be causing this. Could different layers be being used? How would you recommend I debug this?

## Steps to reproduce

The source code is here: https://github.com/expenses/ray-tracing-gallery/. I'm not sure that helps though as this is probably a problem specific to my environment.

## Environment

* RenderDoc version: v1.15
* Operating System: Windows 10 Pro 19042.928
* Graphics API: Vulkan 1.2
* Vulkan SDK: 1.2.189.1
* GPU: AMD Radeon RX 6900 XT
* GPU Vulkan API version: 1.2.182
* Vulkan driver version: 2.0.193

**Comment by baldurk** [comment]
Yes this is deliberate correct behaviour. RenderDoc removes unsupported extensions from the list of those reported, as otherwise the use of them would crash or otherwise cause broken captures. The same happens on all other APIs with queryable functionality which isn't supported.

By removing the reported functionality it allows applications with a fallback to use that path to continue automatically, and applications without a fallback can at least detect the problem and display a message or similar before exiting.

**Comment by expenses** [comment]
Cool, thanks for the swift response. Is there a list of supported extensions somewhere?

**Comment by baldurk** [comment]
It's not explicitly documented, and generally that's not needed as the extensions you see in your application is automatically filtered. Applications should not need a list of the supported extensions in RenderDoc nor try to code specifically to the list as it may change. You can look in [the source here](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/vulkan/vk_core.cpp#L814) or I maintain [this page for vulkan specifically](https://github.com/baldurk/renderdoc/wiki/Vulkan-extension-support) for my own tracking, though it may not be fully up to date.

As I mention though you don't have to have any special handling as it behaves exactly as it would on different drivers with different capabilities, the idea is to work seamlessly with any code that handles different GPUs.
