### ISSUE TITLE
Capture gets corrupted on replay

### ISSUE THREAD

**Issue by martin936** [baldurk/renderdoc#2367]
## Description

Hi, I'm running into a issue with renderdoc v1.15 and dx12 where upon replay, the data in most of the batches seems to get corrupted if I enable a specific feature in the game. If I disable the feature, the replay works fine. I'm able to get a correct capture from pix with the feature turned on. Neither RenderDoc nor Pix seem to detect something wrong with the capture.

## Steps to reproduce

I've sent you by mail two captures from RenderDoc (ok.rdc with the feature turned off and fail.rdc with the feature turned on).
I added as well a capture from pix with the feature turned on (no_fail.wpix)

## Environment

* RenderDoc version: v1.15
* Operating System: Windows 10
* Graphics API: DirectX 12

I've reproduced this on a RTX 3080 (471.96) and a GTX 960 (471.96)

**Comment by baldurk** [comment]
Resolved over email, fixed in 8901880d1557c008d59ea8a0d18a4d9bd1ceea39 .
