### ISSUE TITLE
Mesh viewer setting for object space coordinates

### ISSUE THREAD

**Issue by dpwiz** [baldurk/renderdoc#2375]
## Description

VS Out flipping was landed in #1971, with a comment that there's no canonical object space coordinates.

Sure, but can we have a setting for that? It is needlessly confusing to see your models flipped and do a double-take on whatever the input values are correct.

I have to deal with custom mesh formats and need to know if the buffer data is stored and loaded correctly.

## Environment

* RenderDoc version: 1.15
* Operating System: Linux
* Graphics API: Vulkan

**Comment by baldurk** [comment]
This is a duplicate/instance of #2322 .
