### ISSUE TITLE
Scrollbars in texture viewer are at the wrong position after changing the zoom level

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2377]
## Description

The scrollbars on the texture viewer start in the wrong position after changing the zoom level.  Moving the scrollbar gives correct results, but only for that scrollbar specifically, so both scrollbars need to be moved for their positions to actually make sense (and moving them also means that you start from the wrong location).

Where the scroll bars start:
![image](https://user-images.githubusercontent.com/8334194/135549946-1d749842-91db-4567-b70e-3a4c760cad6a.png)

The actual position the scrollbars should be at:
![image](https://user-images.githubusercontent.com/8334194/135550800-633a49fe-db7d-4756-91c9-ba14339628cd.png)

Clicking the `1:1` button twice moves the scrollbars to the correct position, though that position is not the center of the image.

## Steps to reproduce

To generate the attached capture:

1. Download [Dolphin 5.0-15105](https://dolphin-emu.org/download/dev/4b8b53ac732645f6c0fd3f4b11733cb3d86c9c41/) and the [lesson08 fifolog](https://fifo.ci/media/dff/Lesson08.dff).
2. Launch Dolphin using RenderDoc.
3. In Dolphin, click "Graphics", and change the backend to Vulkan.
4. In Dolphin, switch to the enhancements tab under graphics and set Internal Resolution to "8x Native (5120x4224) for 5K" (if your monitor is absurdly large and this resolution isn't big enough to reproduce, you can add `MaxInternalResolution = 25` to `Config/GFX.ini` under `[Settings]` to set the maximum value to 25x; you will still need to change the actual value)
5. In Dolphin, switch to the advanced tab under graphics and check "Enable API Validation Layers" (this is not required to reproduce, but it enables debug symbols and source attachment for the shader)
6. In Dolphin, close the graphics window and open the config window.  Uncheck "Enable Dual Core" (as the fifoplayer doesn't work well with it).
7. In Dolphin, close the graphics window, and then select "open".  Open the Lesson08.dff file from before.
8. Save a capture.  Dolphin can now be closed.

To reproduce:

1. Open [Lesson08_Vulkan_8x.zip](https://github.com/baldurk/renderdoc/files/7263355/Lesson08_Vulkan_8x.zip)
2. Navigate to an internal-resolution draw (in this capture, EID 15).
3. Click `1:1` or set the zoom to 100%.
4. The scrollbars will be at the top and left positions, but the image will be in approximately the center (though not the exact center?).
5. Clicking the `1:1` button again or changing the zoom level again will update the scroll-bar positions (for `1:1`, to the actual position; I'm not sure if changing the zoom uses the new position or the old position though.)

## Environment

* RenderDoc version: v1.15
* Operating System: Windows 10.0.19042.1237
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Thanks again for the very clear bug report. This was an order-of-operations issue, the scale for the scrollbars was being updated _after_ changing their position, so it got clamped wrongly. That commit should sort it out.
