### ISSUE TITLE
RenderDoc seems to incorrectly interpret vertex attributes of type double (dvec3, dvec4, dmatNxM)

### ISSUE THREAD

**Issue by matusfedorko** [baldurk/renderdoc#2380]
## Description

I think RenderDoc does not interpret (display) vertex attributes of type double (dvec3, dvec4, dmatNxM) correctly.

In the screenshot below `v_data2` is of type `dmat4x3`, `v_data1` of `dmat3x4`, `v_data0`  is `dmat4`, `v_position0` is `dvec3`, `v_normal0` is `dvec3` and `v_texCoord0` is `dvec2`. ![Screenshot 2021-10-01 232831](https://user-images.githubusercontent.com/82540779/135688612-3566d2df-2922-47bc-8003-a5c47b6a0a85.png)
 
If I interpret the specification correctly (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#interfaces-iointerfaces-locations), then `dmat4x3` takes up 8 locations in total, `dmat3x4` takes up 6 locations, `dmat4` 8 locations, `dvec3` 2 and `dvec2` only 1. So I would expect to see 8 entries in the table for `v_data2` and `v_data0`, 6 entries for `v_data1`, 2 for `v_position0` and `v_normal0` and 1 for `v_texCoord0`. Or at least I would like to see each matrix column displayed as starting at the correct location (I mean for example for `v_data0:col1` I'd expect to see location 21, for `v_data0:col2` location 23, ...).

Moving on from the Vertex Input view to Mesh Viewer, the data displayed there looks also incorrect. I have initialized vertex data on the CPU like this:
```
	glm::dmat3x4(glm::dvec3(1), glm::dvec3(2), glm::dvec3(3), glm::dvec3(4));
```
so I'd expect to see the first colum of `v_data2` to be all 1s. the second column to be all 2s, ...
![Screenshot 2021-10-01 233131](https://user-images.githubusercontent.com/82540779/135689944-8a0e8eed-5813-4444-b3b8-0df9c433e39e.png)

Also the preview of the vertex shader output looks broken.

## Steps to reproduce

The screenshot above is from a larger program that I cannot share and I don't have a simple demo at hand to attach here, but hopefully it is not needed and it is easy enough to craft a custom example for the problem.

## Environment

* RenderDoc version: 1.16
* Operating System: Windows 10 Home
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Please provide steps to reproduce the problem. If you can't share the program publicly but you can privately, you can get in touch with me via email to share it. If you think this can be easily reproduced in a custom example then please create that and share it here.

**Comment by matusfedorko** [comment]
ok, I have modified an old tutorial code. Steps to reproduce:
1) Unzip and compile the project from the attached archive. It is Visual Studio 2019 project and hopefully everything is included (except Vulkan SDK. You need to have that installed), so you can just F5 to build and run (in case you need to recompile shaders, run `compile.bat` from the `shaders` folder)
2) Launch the compiled test app in RenderDoc and capture
3) Open the capture and go to the Vertex input view and Mesh Viewer views and observe what I describe above.
[doubles_test.zip](https://github.com/baldurk/renderdoc/files/7272081/doubles_test.zip)

**Comment by baldurk** [comment]
That commit should fix the issue. The only underlying problem it seems was the location assignment being incorrect for 64-bit types, everything else was a cascading failure from there.

**Comment by matusfedorko** [comment]
Thanks for jumping on this so quickly and fixing it.
