### ISSUE TITLE
Export Text Customization

### ISSUE THREAD

**Issue by keelanstuart** [baldurk/renderdoc#2382]
## Description

Ability to customize more export settings, specifically:
 - Ability to disable hierarchy view or adornment text in output -- just display raw API calls in order
 - Ability to turn off EID and/or action number text in output
 - Cleanup of HTML tags in export text (only the params are marked up currently, so they're hard to read in a text editor... meanwhile, the other text isn't marked up at all so you can't view it in a browser)
 - Optional HTML / plain text
 - (stretch) Collapsible groups for hierarchy in HTML output

The first two would greatly help when using diff tools; currently, the first difference breaks the chain because all subsequent EID / action numbers are different.
The others would also help when showing others and for general readability.

## Environment

RenderDoc 1.15 (https://github.com/baldurk/renderdoc/commit/a490606012b4ba1785cec109180acb21990f7594)
Windows 10
OpenGL

Thanks!! RenderDoc is awesome!

**Comment by baldurk** [comment]
From what you're describing I assume you're talking about the export from the event browser, though I'm not sure what you mean about markup for parameters.

I don't think this is a valuable enough feature to add though. If you wanted more customisable/sophisticated export options you could write a UI extension to add whichever features you want, but I don't think this merits adding extra complexity.

**Comment by keelanstuart** [comment]
Yes, the event browser export is what I meant.

I've attached an example of the html markup - it's hard to read in a normal text editor (notepad++), but impossible to read in a web browser, because it's not _all_ marked up with html tags.

As for the other things (removing EIDs / action numbers)... if I add code to strip those (and the tree characters) and insert check boxes in the options dialog to control that, would you accept a pull request for the changes?

[parameters_in_html.txt](https://github.com/baldurk/renderdoc/files/7280657/parameters_in_html.txt)

**Comment by baldurk** [comment]
OK that is definitely a bug, those are not meant to be there. That's purely for styling in the UI. I'll fix the code to strip those tags properly.

I would not want a pull request for those changes, if I thought the feature was beneficial to add I would leave the issue open to implement eventually - I don't expect/require user contributions or close on those grounds. As I say if you want it on the main builds you could write a UI extension, or else if you'd prefer to make the changes you could build a modified version of RenderDoc locally.
