### ISSUE TITLE
RenderDoc doesn't capture frames from 32-bit Vulkan applications

### ISSUE THREAD

**Issue by miller36** [baldurk/renderdoc#239]
Selecting "Executable Path" and clicking "Capture" runs the application but without the overlay. Pressing F12 / PrtSrn or clicking "Trigger Capture" doesn't do anything. That's with RenderDoc 0.27.
Nightly 2016-04-07 is a bit different, it crashes selected executable.

For testing purposes you can use cube and tri examples from Vulkan SDK \Bin32 subfolder. 64-bit versions (\Bin subfolder) work without a problem. Overlay is attached and frames are captured properly.

Vulkan SDK version: 1.0.5.0
OS: Windows 7 x64

**Comment by baldurk** [comment]
v0.27 shipped with broken 32-bit support (it was only supported very late in the pre-release cycle so there wasn't enough time to verify it).

The current crash seems a bit worse though. I repro'd it and it seems like it might be a memory trample - likely something assuming pointer sizes are 64-bit somewhere and overwriting its bounds.

**Comment by baldurk** [comment]
Found it, as expected. That should do the trick now.

**Comment by miller36** [comment]
Excellent. Thank You!

For the first time ever I can debug my 32-bit VK program.
