### ISSUE TITLE
API QueryPerformanceCounter takes too long

### ISSUE THREAD

**Issue by Archer-zty** [baldurk/renderdoc#2394]
## Description

Hi, all my graphics programs run slowly launched by RenderDoc.
I have found that "QueryPerformanceCounter"(win32_threading.cpp Line40) takes too long on my 2 AMD platforms(5950x and 5900HX(laptop)). Bug is fixed after code gets commented. But the same issue doesn't encounter on an Intel 10900F platform. Any ideas? Thank you.

## Steps to reproduce

Specified platform launch.

## Environment

* RenderDoc version: 1.6
* Operating System:
Edition	Windows 10 Pro
Version	21H1
Installed on	‎2/‎10/‎2021
OS build	19043.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0

* Graphics API: DX11
* CPU info
AMD 5950x
* GPU info
MSI SUPRIM X 3080Ti (Driver version 471.68)

**Comment by baldurk** [comment]
I don't know what you mean that it takes "too long". Do you mean the program is hanging there?

Also v1.6 is a very old version, I would suggest that first you update to the latest version before anything else.

**Comment by Archer-zty** [comment]
> I don't know what you mean that it takes "too long". Do you mean the program is hanging there?
> 
> Also v1.6 is a very old version, I would suggest that first you update to the latest version before anything else.

Sorry, version 1.16 in fact.
I mean that frame time increases significantly. FPS drops from 120 to 20~30 owing to QueryPerformanceCounter takes a lot of time.

**Comment by baldurk** [comment]
`QueryPerformanceCounter` is a standard system call and RenderDoc only makes a few hundred calls per frame under normal operation, if it's causing that much of a slowdown this isn't a RenderDoc bug, but something systemic or potentially hardware related. Check any anti-virus or other similar software you might have installed.

Also doing a very quick google I found [these](https://www.asawicki.info/news_1667_when_queryperformancecounter_call_takes_long_time) [articles](https://gpuopen.com/learn/threadripper-for-gamedev-ue4/) that mention that it might be related to specific AMD motherboards and the HPET timer, so you may be able to fix it that way.

**Comment by Archer-zty** [comment]
Yes, it seems to be a special circumstance in my environment. I fix it by replacing the `renderdoc.dll` built by myself.
Thank you for your response.
