### ISSUE TITLE
Event Browser now shows loadOp DONT_CARE as VkAttachmentLoadOp(2)

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#2405]
## Description

I upgraded my build of renderdoc to 5bee6490 to give the VK_EXT_load_store_op_none stuff a try, and noticed this issue. In the Event Browser, when VK_ATTACHMENT_LOAD_OP_DONT_CARE is used, instead of DS=DONT_CARE (produced previously), I now see DS=VkAttachmentLoadOp(2).

![Screenshot from 2021-11-05 22-10-43](https://user-images.githubusercontent.com/1067408/140594378-1cdf5bee-154e-469a-9616-36d4cee33612.png)

## Steps to reproduce

- Trace an application that uses a render pass with D/S attachment using loadOp=DONT_CARE. For completeness, here are the complete ops of the color and D/S attachments in the image above:

```
pAttachments     VkAttachmentDescription[2]
  [0]            VkAttachmentDescription()
    flags        VkAttachmentDescriptionFlagBits(0)
    format       VK_FORMAT_B8G8R8A8_UNORM
    samples      VK_SAMPLE_COUNT_1_BIT
    loadOp       VK_ATTACHMENT_LOAD_OP_CLEAR
    storeOp      VK_ATTACHMENT_STORE_OP_STORE
    stencilLoadOp VK_ATTACHMENT_LOAD_OP_DONT_CARE
    stencilStoreOp VK_ATTACHMENT_STORE_OP_DONT_CARE
    initialLayout VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
    finalLayout  VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
  [1]            VkAttachmentDescription()
    flags        VkAttachmentDescriptionFlagBits(0)
    format       VK_FORMAT_D32_SFLOAT_S8_UINT
    samples      VK_SAMPLE_COUNT_1_BIT
    loadOp       VK_ATTACHMENT_LOAD_OP_DONT_CARE
    storeOp      VK_ATTACHMENT_STORE_OP_DONT_CARE
    stencilLoadOp VK_ATTACHMENT_LOAD_OP_DONT_CARE
    stencilStoreOp VK_ATTACHMENT_STORE_OP_DONT_CARE
    initialLayout VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL
    finalLayout  VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL
```

- Observe the ops as described in the Event Browser for this render pass.

## Environment

* RenderDoc version: 5bee6490
* Operating System: Linux
* Graphics API: Vulkan
* GPU Driver: SwiftShader 70f3a0ff7 (chosen as it supports VK_EXT_load_store_op_none, and my nvidia drivers are not yet so up-to-date)

**Comment by baldurk** [comment]
This looks like a bad merge/copy-paste that removed the DONT_CARE enum stringise case. Fixed in that commit.
