### ISSUE TITLE
[OpenGL] "Error - Unexpected enum as texture target: GL_NONE" when binding a texture view

### ISSUE THREAD

**Issue by cmp-** [baldurk/renderdoc#2408]
## Description

When trying to bind a texture view, RenderDoc outputs the following error:
`RDOC 027340: [21:32:18]        gl_common.cpp(1323) - Error   - Unexpected enum as texture target: GL_NONE`
The texture view is bound successfully regardless of the error and the RenderDoc UI displays it correctly.
The only issue is that the error spam makes the application output unusable.

## Steps to reproduce

Run this program:
[Repro.executable.zip](https://github.com/baldurk/renderdoc/files/7523336/Repro.executable.zip)

or compile and run this code:
[Repro.source.zip](https://github.com/baldurk/renderdoc/files/7523360/Repro.source.zip)

or execute this code in an OpenGL application:
```
uint32_t TexId;
glCreateTextures(GL_TEXTURE_2D, 1, &TexId);
glTextureStorage2D(TexId, 1, GL_RGBA8, 16, 16);

uint32_t ViewId;
glGenTextures(1, &ViewId);
glTextureView(ViewId, GL_TEXTURE_2D, TexId, GL_RGBA8, 0, 1, 0, 1);

glBindTextureUnit(0, ViewId);
```

## Environment

* RenderDoc version: 1.17 Nightly (15944e2b41ff270c058b8c10702cbf1228bb63c2)
* Operating System: Windows 10
* Graphics API: OpenGL 4.6 Core
* Graphics Adapter: NVIDIA Geforce 1080 Ti
* Driver Version: 496.49

**Comment by baldurk** [comment]
Thanks for the report. This was a gap in handling the billion different ways GL has of creating and binding textures, in this particular path the internal target for the texture view wasn't properly set which led to the error message. That commit should fix it.
