### ISSUE TITLE
Incorrect vkUpdateDescriptorSets overflow behavior

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#2410]
## Description

We discussed this over Discord:

There could be a bug in "overflow behavior" handling of VkWriteDescriptorSet via vkUpdateDescriptorSets?
I believe I may have found a bug; unless I wrongly understand how it works

I'm getting no validation errors, and rendering looks fine (I'm developing a new technique so I can be 100% certain it looks as intended). But according to render doc half of the textures are not bound which would either trigger a TDR or severe corruption; and that's obviously not happening.

For example RenderDoc says texShadowMap0 isn't bound, and I see that it thinks the shadow map is at vctProbeZ[0]; but rendering has correct shadows.

![Buggy](https://user-images.githubusercontent.com/3395130/141688221-8731ffff-5eda-4bdc-8da6-df212fd2ffb9.png)

I'm doing the following:

```
layout( set = 1, binding = 4 ) uniform texture3D vctProbes[2];
layout( set = 1, binding = 6 ) uniform texture3D vctProbeX[2];
layout( set = 1, binding = 8 ) uniform texture3D vctProbeY[2];
layout( set = 1, binding = 10 ) uniform texture3D vctProbeZ[2];
layout( set = 1, binding = 12 ) uniform texture2DArray ltcMatrix;
layout( set = 1, binding = 13 ) uniform texture2D texShadowMap0;
```

The PSO defines for these textures 6 descriptors; the first 4 have an arrayCount of descriptorCount = 2. So far so good.
That's a total of 10 textures (4x2 + 2x1).

Notice that bindings 5, 7, 9 and 11 do not exist (shader never declares them, and PSO never defines it either)

Now when updating (you'll hate me for this) via vkUpdateDescriptorSets; I write:

```
writeDescSets->dstSet = 1;
writeDescSets->dstBinding = 4;
writeDescSets->dstArrayElement = 0;
writeDescSets->descriptorCount = 10;
writeDescSets->pImageInfo = ...; // pointer to an array holding 10 VkDescriptorImageInfo

vkUpdateDescriptorSets( device->mDevice, 1, writeDescSets, 0u, 0 );
```

![unknown](https://user-images.githubusercontent.com/3395130/141688257-0be9de14-f8ab-4513-8d81-3beb0444c01e.png)

That is: I upload 10 textures together and rely on the overflow behavior to fill them all.

Now I have a simple theory about what RenderDoc is doing. I think RenderDoc is incorrectly assuming there is binding 5, 7, 9 and 11. Those bindings do not exist.

Because I can see that vctProbes is filled fine, but vctProbeX[0] contains what vctProbeX[1] should have. And vctProbeX[1] has what is in vctProbeY[0].

And then when I see vctProbeY[0] it has what vctProbeZ[0] contains. Visually:

```
layout( set = 1, binding = 4 ) uniform texture3D vctProbes[2]; // Fine
layout( set = 1, binding = 5 ) uniform texture3D nonExistant = vctProbeX[0];
layout( set = 1, binding = 6 ) uniform texture3D vctProbeX[2] = { vctProbeX[1], vctProbeY[0]; }
layout( set = 1, binding = 7 ) uniform texture3D nonExistant = vctProbeY[1];
layout( set = 1, binding = 8 ) uniform texture3D vctProbeY[2] = { vctProbeZ[0], vctProbeZ[1]; }
layout( set = 1, binding = 9 ) uniform texture3D nonExistant = ltcMatrix;
layout( set = 1, binding = 10 ) uniform texture3D vctProbeZ[2] = { texShadowMap0, NoResource }
layout( set = 1, binding = 11 ) uniform texture3D nonExistant = NoResource;
layout( set = 1, binding = 12 ) uniform texture2DArray ltcMatrix = NoResource;
layout( set = 1, binding = 13 ) uniform texture2D texShadowMap0 = NoResource;
```

I think this is definitely what RenderDoc is doing; but I'm not sure if that behavior is RenderDoc bug, or my bug (I'm inclined to think it's RenderDoc's)

## Steps to reproduce

1. Download [the small repro I prepared](https://mega.nz/file/prhwkATA#n0MLGtDQa6U1X1CrdI54RQrP-VUD9znjka5mKtgn9v0)
2. Open RenderDocTest\bin\RelWithDebInfo\Sample_Postprocessing.exe
   - It's strongly recommended to have VulkanSDK installed to get debug layers and thus get debug names; this is a special build)
   - OpenGL and Vulkan backends work. D3D11 will not.
3. Hit the letter '1'. The screen should have a cyan tint
![Tint](https://user-images.githubusercontent.com/3395130/141688374-41e3fe97-6651-46f6-a891-2a25022f5d14.jpg)
4. Capture with RenderDoc
5. Go to QUAD 12 event
    - myTexA[0] should have rt0[Value...] bound. This is correct
    - myTexA[1] should have A1.png bound. This is correct
    - myTexB[0] should have B0.png bound. This is buggy. RenderDoc says B1.png
    - myTexB[1] should have B1.png bound. This is buggy. RenderDoc says C0.png
    - myTexC should have C0.png bound. This is buggy. RenderDoc says Dummy, which is a texture created by Ogre
    - set 0 binding 8 (not shown on pic, because it's unused) should show Dummy. Instead it says not bound
    - set 0 binding 9 (not shown on pic, because it's unused) should show Dummy. Instead it says not bound

![Untitled](https://user-images.githubusercontent.com/3395130/141688610-2100bcd3-1630-448b-81bf-71b7807b5b5c.png)

## Environment

* RenderDoc version: 1.16
* Operating System: Windows 10 20H2 (also Xubuntu 18.04)
* Graphics API: Vulkan

The app works fine and tested on (and the RenderDoc bug repros identically):
 - Radeon RX 560 2GB - Windows 10
 - GeForce 1060 3GB - Windows 10
 - Radeon 6800 XT - Linux Mesa 21.1.6

**Comment by baldurk** [comment]
That commit will correctly skip the empty/undefined bindings in between the valid ones when overflowing.
