### ISSUE TITLE
Invalid spirv generated when inspecting dEQP-VK.subgroups.quad.graphics.subgroupquadswaphorizontal_bool

### ISSUE THREAD

**Issue by werman** [baldurk/renderdoc#2417]
## Description

Invalid (per spirv-val and Mesa) spirv generated by `FetchVSOut` when inspecting draw calls of `dEQP-VK.subgroups.quad.graphics.subgroupquadswaphorizontal_bool` and any other similar tests.

## Steps to reproduce

1. Capture `dEQP-VK.subgroups.quad.graphics.subgroupquadswaphorizontal_bool` with RADV
2. Open and try to inspect first draw call
3. RADV segfaults with error:
```
SPIR-V parsing FAILED:
    In file ../src/compiler/spirv/vtn_private.h:789
    SPIR-V id 23 is the wrong kind of value
    10092 bytes into the SPIR-V binary
```

`spirv-val` output:

```
error: line 310: Interface variable id <26> is used by entry point 'rdc' id <326>, but is not listed as an interface
  %SubgroupLocalInvocationId = OpVariable %_ptr_Input_uint Input
```

Failing spirv: [fail-0.spirv.zip](https://github.com/baldurk/renderdoc/files/7570626/fail-0.spirv.zip)

[deqp-vk_2021.11.19_13.36.30_capture.zip](https://github.com/baldurk/renderdoc/files/7570640/deqp-vk_2021.11.19_13.36.30_capture.zip)

## Environment

* RenderDoc version: f068494
* Operating System: Linux
* Graphics API: Vulkan
* Driver: Latest RADV
* spirv-val: spirv-tools-2021.3-1

**Comment by baldurk** [comment]
I wasn't handling SPIR-V < 1.4 modules where subgroup variables that are kept as Input instead of being patched to Private need to be kept in the entry point interface. That commit should fix the issue.

**Comment by werman** [comment]
Works now, thanks!
