### ISSUE TITLE
Pixel value inspected in renderdoc texture viewer is not same as the output color of shader debugger

### ISSUE THREAD

**Issue by wsyOverflow** [baldurk/renderdoc#2418]
## Description

Pixel value inspected in texture viewer is different from the output color of shader debugger. You can check this weird behavior in the following picture.
- pixel in texture viewer
![pixel value](https://user-images.githubusercontent.com/41018796/142714781-60e40a0c-fe91-4dff-9f2d-fe531cfde84f.PNG)

- output of shader debugger
![debug shader](https://user-images.githubusercontent.com/41018796/142714792-faa07880-8435-4dbb-bd3e-2cd309803695.PNG)

## Steps to reproduce

The abnormal pixel 
[pixel mismatch.zip](https://github.com/baldurk/renderdoc/files/7573965/pixel.mismatch.zip)
can be found in action 1270 of my capture. And the pixel position is (627, 735).
 

## Environment

![image](https://user-images.githubusercontent.com/41018796/142714876-714887f1-6622-434b-b6aa-5dc081536b7e.png)

* RenderDoc version: v1.16
* Operating System: win10
* Graphics API: vulkan

**Comment by wsyOverflow** [comment]
I save the above render target to ppm file, the ppm file has same pixel value as the texture viewer at the pixel position  (627, 735). It seems shader debugger displays wrong value

**Comment by baldurk** [comment]
This shader is very numerically unstable, and small differences within the bounds of what's allowed by SPIR-V and the Vulkan spec seem to be magnified and cause large differences in the output. Loading the capture on a different driver (AMD's) produces different results in the output and in that case it does matches the shader debugging.

The shader debugger should produce accurate results as allowed by the specification, but may not bitwise match the hardware as this is not feasible. Shaders with such instability which can magnify a few ULPs difference in an operation to a large difference will diverge from the hardware as this is quite similar relying on undefined behaviour.
