### ISSUE TITLE
Vulkan: crash on vkCmdPipelineBarrier

### ISSUE THREAD

**Issue by TiemoJung** [baldurk/renderdoc#242]
Hi,

we encounter a crash on calls to vkCmdPipelineBarrier.
Setup:
for one image there are 2 barriers, the first is for mip level 0 and for all array layers (0 + VK_REMAINING_ARRAY_LAYERS).
second barrier is for mip level 1 and all remaining levels (1 + VK_REMAINING_MIP_LEVELS) and all array layers.

It crashes inside `VulkanResourceManager::RecordSingleBarrier` where `size_t count = it->second.subresourceRange.levelCount * it->second.subresourceRange.layerCount` results in a very big number (on 64bit builds or an overflow in 32bit builds) because `layerCount` is `VK_REMAINING_ARRAY_LAYERS`. count is then used as a counter to copy the remaining image states over into the new state array.

**Comment by baldurk** [comment]
Can you share a repro or give the creation info of the image and the barrier definition?

The iterator in `VulkanResourceManager::RecordSingleBarrier` that you're talking about is iterating through the list of subresource ranges known for the image, and should be set up at creation time to contain the actual number of mips and layers in the image.

Use of `VK_REMAINING_ARRAY_LAYERS` or `VK_REMAINING_MIP_LEVELS` in the barrier should be handled in `VulkanResourceManager::RecordBarriers` where those special values are replaced by the actual values.

**Comment by TiemoJung** [comment]
Under certain circumstances `it->second.subresourceRange.layerCount` is `VK_REMAINING_ARRAY_LAYERS`.

The steps to re-produce it:
memory barrier for image:
[0] = {mip = 0, mipCount = 1, array = 0, arrayCount = VK_REMAINING_ARRAY_LAYERS, dstLayout = transfer_src, srcLayout = color_target }
[1] = {mip = 1, mipCount = VK_REMAINING_MIP_LEVELS, array = 0, arrayCount = VK_REMAINING_ARRAY_LAYERS, dstLayout = transfer_dst, srcLayout = color_target }
....
some operations, in our case blit mip 0 onto all other levels to get a simple mip gen
....
memory barrier for image:
[0] = {mip = 0, mipCount = 1, array = 0, arrayCount = VK_REMAINING_ARRAY_LAYERS, dstLayout = transfer_src, srcLayout = sampled }
[1] = {mip = 1, mipCount = VK_REMAINING_MIP_LEVELS, array = 0, arrayCount = VK_REMAINING_ARRAY_LAYERS, dstLayout = transfer_src, srcLayout = sampled }

The crash occurs at the second memory barrier (bad_alloc exception).

**Comment by baldurk** [comment]
OK I will look into this. What are the parameters for the creation of the image?

**Comment by TiemoJung** [comment]
Its a 2d image with 128with and height, 4 array layers and 8 mipmap levels, format is rgba16 signed float and it can be used as color target, sampled from, copied to and from.

**Comment by baldurk** [comment]
I believe this commit should fix the crash.

One thing though, this kind of pattern hits a poor case (currently) in renderdoc, where instead of having a single layout for many mips/layers, the series of barriers causes the code to split it all up and track them individually (so even if it gets restored to the same layout for all mips/layers, it will still track all 32 separately). This should work, but it might be inefficient or run into bugs I haven't seen before - let me know if you have other problems and there might be more work I can do to improve it.

**Comment by TiemoJung** [comment]
It seems your fix works, tanks!
