### ISSUE TITLE
Crash in 3D views with Vulkan

### ISSUE THREAD

**Issue by Helco** [baldurk/renderdoc#2422]
## Description

When viewing the output of a specific drawcall either in the texture viewer or in the mesh viewer, a loading bar appears in the footer of the RenderDoc application which never ends; the UI for the texture viewer is not redrawn so graphical glitches in the RenderDoc UI occur.
When either waiting for too long or trying to close RenderDoc it crashes.

## Steps to reproduce

1. Open the capture downloadable here: https://1drv.ms/u/s!Ar4T0mmxxmFehiv4jYua1wAVvg6-?e=0ZPdsH
2. Open "Colour Pass 1"
3. Click on EID 716 "vkCmdDraw(4, 1)"
4. Switch between Pipeline State and Texture Viewer
5. Try to close RenderDoc

## Environment

* RenderDoc version: v1.17 as well as v1.18 (d6ef7d51)
* Operating System: Windows 10.0.19042
* Graphics API: Vulkan
* GPU: NVIDIA GeForce RTX 2080 Ti
* GPU driver: 496.49 as well as 496.76

**Comment by baldurk** [comment]
Your program is has invalid use which is invoking undefined behaviour. The draw in question has a vertex input declared at location 6 and used:

```
               OpDecorate %75 Location 6
; ...
         %75 = OpVariable %_ptr_Input_v4float Input
; ...
         %76 = OpLoad %v4float %75
               OpStore %73 %76
```

but the pipeline only declares vertex attributes for locations 0 through 5.

You should run your application with the validation layers and fix the problems that they identify, including this one:

> `[ UNASSIGNED-CoreValidation-Shader-InputNotProduced ] Object 0: handle = Shader Module 317, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x23e43bb7 | Vertex shader consumes input at location 6 but not provided`

RenderDoc does not handle invalid use and errors like this can cause crashes in drivers or they may work by coincidence and crash in tools like RenderDoc (or on different drivers).

**Comment by Helco** [comment]
That is a detailed cause description, thank you very much!
By figuring out how you got this info I found the API validation flag in the Renderdoc settings (and I thought Validation layer was already enabled in my app wtihout RenderDoc, oh well...) so such bug reports shall not happen by me again.

However it is a bit odd that a program designed to find erroneous behavior would crash if it actually finds some. Maybe a mesh/texture viewer could be disabled if RenderDoc detects validation errors in related calls?

**Comment by baldurk** [comment]
RenderDoc is not an API validator, the flag in the capture settings is a convenience for some types of errors that are survivable but it's not guaranteed to work depending on your particular API misuse. You should enable the vulkan validation layers in your own program first and foremost and fix any errors reported there, as this will prevent any false positive or false negative errors from interactions between RenderDoc and the validation layers, as well as ensure you don't run into crashes in RenderDoc as a result.

Detecting invalid API use is not at all what RenderDoc is for, and detecting/handling invalid API use would require duplicating the entire work of every API's validation which is a huge amount of wasted effort. RenderDoc is for debugging when your API use is valid but your program is not doing what you expected or wanted.
