### ISSUE TITLE
Support for Gallium Nine (d3d9) on linux

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#2423]
## Description

Mesa allows to implement d3d9 on linux via "gallium nine" state tracker. Unfortunately presently it's not possible to use renderdoc with it. I kindly request this feature. :) 

## Environment

* RenderDoc version: all
* Operating System: linux
* Graphics API: d3d9

**Comment by baldurk** [comment]
I have no plans on ever supporting D3D9 proper on windows, so a linux mesa wrapper is even less likely to be supported.
