### ISSUE TITLE
[Feature request] VK_KHR_fragment_shading_rate

### ISSUE THREAD

**Issue by godlikepanos** [baldurk/renderdoc#2426]
## Description

I was wondering if it's possible to support the VK_KHR_fragment_shading_rate extension. If you'd like an application that supports it to test please let me know. Thanks in advance.

## Environment

* RenderDoc version: 1.17
* Operating System: Ubuntu
* Graphics API: Vulkan

**Comment by baldurk** [comment]
The feature request is still valid on most recent code but I'd strongly recommend you update to the latest version, 1.7 is almost two years old at this point.

And yes a sample application showing the use of the extension would be useful, ideally one that can compile on windows too so that I have a debugger available.

**Comment by godlikepanos** [comment]
I'm sorry, typo. I meant ver 1.17. 

I have one more thing to implement and then I can share a github repo with instructions on how to build for Windows. It might not cover all functionality though. It will cover pipeline and attachment shading rate but not per-primitive shading rate. Please let me know if that would be a problem in order for me to see if I should add more functionality.

**Comment by godlikepanos** [comment]
Sorry for the late update. I have a demo that uses shading rate attachments and pipeline shading rate. VRS is applied in the G-buffer pass and in the light shading pass. Unfortunately the demo won't cover all possible cases and combinations.

Building is easy. Need to checkout the master in https://github.com/godlikepanos/anki-3d-engine and use the instructions to build for Windows (pretty standard CMake stuff really).

Then running `Sponza.exe` with a few command line arguments should do the trick. The command line arguments are:
- `GrVrs 1`
- `GrDebugMarkers 1` (For VK debug markers)

Vulkan samples also include 2 VRS samples that could be used.

Please let me know if there are problems or if I can help with any other way.

**Comment by baldurk** [comment]
That commit adds support for the extension, tested on your example. I'll add some small micro-tests later for the nightly checks, based on the D3D12 VRS tests I have, but please let me know if you spot anything broken.

**Comment by godlikepanos** [comment]
Awesome! I'll test that soon

**Comment by godlikepanos** [comment]
Sorry for the late update. It seems it's working from my side as well. I can see the relevant state in the Pipeline State tab. So all good! Thank you!
