### ISSUE TITLE
[Feature request] Support DXIL Shader Debug

### ISSUE THREAD

**Issue by whbwhb521** [baldurk/renderdoc#2427]
## Description
Shader debug is an excellent function. It would be great to support debugging for DXIL in renderdoc

## Environment
* RenderDoc version: 1.17
* Operating System: Windows 10
* Graphics API: D3D12

**Comment by baldurk** [comment]
This is planned for feature parity at some point, but I can't promise any particular timeline and I don't expect it to be very soon since DXIL is an utterly terrible format and is awful to work with unfortunately.

**Comment by xoyojank** [comment]
I can use dxil-spirv to decompile DXIL to HLSL, edit & apply works, but the shader does not take effect
![image](https://user-images.githubusercontent.com/2873643/174421521-69a57634-9f8e-4630-9375-ce4684740b2d.png)

**Comment by welkin0307** [comment]
我想知道您那个DXIL转HLSL的工具是可以分享的吗

**Comment by bengHinterland** [comment]
That would be exellent to debug unreal shaders.

**Comment by vito0719** [comment]
> 

I believe you can debug Unreal shaders just fine by uncommenting a few lines in ConsoleVariables.ini.

**Comment by bengHinterland** [comment]
I did that but Renderdoc still says it can't debug pixel shaders because they are in DXIL

**Comment by baldurk** [comment]
This issue is not the appropriate place for Unreal questions or support. The feature request has been made so you can follow this issue if you are interested in it, otherwise Unreal questions should go to a more appropriate forum.

**Comment by baldurk** [comment]
The recently released [v1.36](https://github.com/baldurk/renderdoc/releases/tag/v1.36) includes support for debugging DXIL shaders.
