### ISSUE TITLE
Stencil attachment with format VK_FORMAT_S8_UINT replays as D8 with incorrect results

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#2428]
## Description

Using a render pass with a stencil attachment with format VK_FORMAT_S8_UINT, RenderDoc detects it as a depth attachment with the D8 format. This causes the replay to look incorrect, for example the values read from the stencil texture show as float depth values, the contents show as LOAD DONTCARE (because depth load is dont't care), the overlay shows stencil test failing, and overall the result is incorrect.

RenderDoc capture on Nvidia/Linux: https://drive.google.com/file/d/1l_i6JLkiAQvN8SOHrRMLxPxkPvklmN5b/view

## Steps to reproduce

- Create a render pass with color and stencil attachment. Use VK_FORMAT_S8_UINT for stencil format.
- Use load/store=DONT_CARE and stencilLoad/Store=LOAD/STORE
- Capture and replay through RenderDoc, observe that the stencil attachment is detected as a depth attachment with D8 format

- Here is a capture of a test that is similar to the above (has 2 render passes, but that's inconsequential): https://drive.google.com/file/d/1l_i6JLkiAQvN8SOHrRMLxPxkPvklmN5b/view

## Environment

* RenderDoc version: tag: v1.17 (built from source with `-DCMAKE_BUILD_TYPE=Release -Bbuild -H. -DENABLE_GLES=OFF -DENABLE_GL=OFF`)
* Operating System: Linux
* Graphics API: Vulkan
* GPU: Nvidia Quadro P1000

**Comment by baldurk** [comment]
Thanks for the repro case. That commit should fix the issue - S8 should be correctly identified as stencil and everything else falls out from there. There's slight overlap between this and #2437 so the fix for that issue also applies here (properly respecting the stencil load/store ops for stencil aspect instead of using the depth ones for discard patterns).
