### ISSUE TITLE
Unable to capture from a simple Vulkan test program

### ISSUE THREAD

**Issue by io7m** [baldurk/renderdoc#2429]
## Description

Hello! I'm unable to capture from a small Java test application that calls the Vulkan API. The Java application is just a Vulkan "hello world" that displays a triangle onscreen, and it runs correctly (without RenderDoc) without any kind of validation errors with the validation layer enabled. However, when I try to run the same application in RenderDoc, I run into a similar error that seems to have been described (poorly) in this old ticket:

https://github.com/baldurk/renderdoc/issues/1487

In my case, this _isn't_ an Android application, it's just a plain Java desktop application.

## Steps to reproduce

I'm unsure what would be the easiest way to give you the code to run. I'm assuming as a native code developer, you probably aren't set up to build a Java project. If you _do_ want to try building the Java code, clone the `jcoronado` repository:

https://github.com/io7m/jcoronado

You'll need [Apache Maven](https://maven.apache.org/index.html) and [JDK 17](https://jdk.java.net/17/). You don't have to use that particular JDK - any JDK 17+ implementation should work (Amazon Coretto, Azul, Adoptium, etc). Once you have those, you should be able to build the project with:

```
$ mvn clean package
```

That will produce a jar file at `com.io7m.jcoronado.examples/target/com.io7m.jcoronado.examples-0.0.1-SNAPSHOT-main.jar` that you can run with `$ java -jar com.io7m.jcoronado.examples/target/com.io7m.jcoronado.examples-0.0.1-SNAPSHOT-main.jar`. The example in question that I'm trying to trace is the `hello-vma` example:

```
$ java -jar com.io7m.jcoronado.examples/target/com.io7m.jcoronado.examples-0.0.1-SNAPSHOT-main.jar hello-vma
```

If you _don't_ want to do all of this yourself, I can try attaching an executable jar file to this ticket. It's 34mb, and I'm unsure how portable it is, so that's why I've not included it yet.

Assuming you have that jar file, it's pretty straightforward to trace the execution in RenderDoc. Just set the
executable to trace to your `java` binary, and the command-line arguments to match the `-jar ...` invocation above. I used this:

![args](https://user-images.githubusercontent.com/612494/146925561-c3733afc-4f8e-45ca-b96d-ae78bc4fd561.png)

If I click `Launch`, the Java program runs, and then immediately seems to exit, and I see this in RenderDoc:

![error](https://user-images.githubusercontent.com/612494/146925781-2795783b-7d12-4929-912b-41cc88abdb60.png)

There doesn't seem to be a capture file I can send you, but there is a log file:

[cap.log.txt](https://github.com/baldurk/renderdoc/files/7755078/cap.log.txt)

Please let me know if there's anything else I can give you, or if you need the jar file above.

## Environment

```
$ renderdoccmd version
renderdoccmd x64 v1.18 built from f8476b53b55e21b640897a8bdc5c0e11a777de28
Packaged for Arch (1.17+2.gf8476b53b5) - https://aur.archlinux.org/packages/renderdoc-git
APIs supported at compile-time: Vulkan, GL, GLES.
Windowing systems supported at compile-time: xlib, XCB, Wayland (CAPTURE ONLY), Vulkan KHR_display.
```
```
Linux sunflower.int.arc7.info 5.15.10-arch1-1 #1 SMP PREEMPT Fri, 17 Dec 2021 11:17:37 +0000 x86_64 GNU/Linux
```

[vulkaninfo.txt](https://github.com/baldurk/renderdoc/files/7755094/vulkaninfo.txt)

**Comment by io7m** [comment]
For reference, I am able to trace `/usr/bin/vkcube` without issue, so there's something about this particular setup that's upsetting RenderDoc.

**Comment by baldurk** [comment]
Can you please test with either a clean build from source or one of the binary builds from renderdoc.org? Distribution packages are not considered reliable especially when yours seems to enable a broken and unsupported compile configuration option. That would eliminate a problem with your package as the issue.

Does your program have error logging for failure cases? What you're describing would be consistent if the program was exiting early without doing anything, so if you're able to eliminate anything your code might be doing to exit early that would be helpful. If you have any hardcoded assumptions in your code about what you expect from vulkan they may not hold when run under RenderDoc, as it assumes a relatively portable program (or that the program reports errors if it can't run portably).

Otherwise if neither of the above produces any results I'll follow your repro steps and look into this.

**Comment by io7m** [comment]
> Can you please test with either a clean build from source or one of the binary builds from renderdoc.org? Distribution packages are not considered reliable especially when yours seems to enable a broken and unsupported compile configuration option. That would eliminate a problem with your package as the issue.

Yep, I'll do that today. I assumed the Arch package was OK, as they typically use very vanilla settings... Clearly not the case here, though.

> 
> Does your program have error logging for failure cases? What you're describing would be consistent if the program was exiting early without doing anything, so if you're able to eliminate anything your code might be doing to exit early that would be helpful. If you have any hardcoded assumptions in your code about what you expect from vulkan they may not hold when run under RenderDoc, as it assumes a relatively portable program (or that the program reports errors if it can't run portably).

It has a lot of logging, yes. There aren't any errors logged, and the application ends up sitting there waiting for the device to idle.

**Comment by io7m** [comment]
It seems that compiling from source using the default README instructions results in a version of RenderDoc that can trace this program without any problems.

I'll let the Arch people know that their package is broken. Thanks for the quick response, and sorry for the noise!
