### ISSUE TITLE
[Feature Request] Accurate EID in debug messages.

### ISSUE THREAD

**Issue by dorian-apanel-intel** [baldurk/renderdoc#2430]
## Description

Renderdoc has a nice feature to get messages via VkDebugUtilsMessengerEXT and it is very useful.
It has a limitation of not showing exactly from within which api call the message was sent.

Here is an example of messages order and EID assigned (using vkCube frame and custom messages)
![image](https://user-images.githubusercontent.com/72810961/147298978-a5a1978e-34d5-4e9f-bb3b-53d7199aadc4.png)

I would like messages from vkCreateDevice to be marked with EID 0, messages from vkBeginCommandBuffer with EID 4, from vkEndCommandBuffer with EID 13, etc.

## Environment

* RenderDoc version: 1.17
* Operating System: Windows
* Graphics API: Vulkan

I see there is a eventId searching code in vk_core.cpp that is not executed during those messages processing:
(m_State is LoadingReplaying).
```
      // during replay we can get an eventId to correspond to this message.
      if(IsActiveReplaying(m_State))
      {
        // look up the EID this action came from
        ActionUse use(m_CurChunkOffset, 0);
        auto it = std::lower_bound(m_ActionUses.begin(), m_ActionUses.end(), use);

        if(it != m_ActionUses.end())
          msg.eventId = it->eventId;
      }
```

**Comment by baldurk** [comment]
This is clearly a bug report, not a feature request. Please open a new issue using the correct issue template and fill out the relevant sections including providing a reproducible test case.
