### ISSUE TITLE
Crashes if VkRenderingInfoKHR::pStencilAttachment is not set.

### ISSUE THREAD

**Issue by jbmcgee** [baldurk/renderdoc#2432]
## Description

Using the latest released [`VK_KHR_dynamic_rendering`](https://www.khronos.org/blog/streamlining-render-passes) extension. Renderdoc crashes if `pDepthAttachment` in `VkRenderingInfoKHR` is set to an attachment but `pStencilAttachment` is set to NULL. I don't see anything in the [spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkRenderingInfoKHR.html) that requires `pStencilAttachment` to be set when `pDepthAttachment` is set to a valid attachment.

## Steps to reproduce
Set  `pDepthAttachment` in `VkRenderingInfoKHR` to an attachement and set `pStencilAttachment` to NULL. You will need Vulkan SDK 1.2.198.1 and latest [AMD driver or Nvidia beta driver](https://github.com/KhronosGroup/Vulkan-Docs/issues/1677). A single [source file](https://gist.github.com/jbmcgee/2ce1bbbf26436b12d25501403ac260f9) repro of the issue. Uncomment line 329 for renderdoc to not crash. The example doesn't use a stencil buffer.

## Environment

* RenderDoc version: v1.17
* Operating System: win10
* Graphics API: vulkan 1.2.198.1

**Comment by baldurk** [comment]
Thanks for the repro - this was a simple copy-paste failure on my part implementing, and I'd only tested with with neither depth&stencil or with both.
