### ISSUE TITLE
Wrong EID of some debug messages. 

### ISSUE THREAD

**Issue by dorian-apanel-intel** [baldurk/renderdoc#2435]
## Description

I'm trying to use VkDebugUtilsMessengerEXT to detect some events and print them in RenderDoc "Errors and Warnings" window.
Some messages have incorrect EID assigned.

See following screenshot for example (single frame of vkcube.exe form VulkanSDK, replayed with my test layer):
![image](https://user-images.githubusercontent.com/72810961/147707536-565d4ae4-da63-4b41-975f-63ceff782080.png)

API Inspector shows EndCommandBuffer with EID 8. No debug message is displayed with EID 8, but there are two EndCommandBuffers with EID 5.
## Steps to reproduce

To reproduce it easier, I wrote a simple layer that captures debug message callback provided by renderdoc (if validation layers are enabled) and calls it with vulkan api function name.

1. Install VulkanSDK
2. Download layer windows binary from [here](https://github.com/dorian-apanel-intel/VulkanTools/releases/tag/debugMessageTest_v.0.0.1) or [compile ](https://github.com/dorian-apanel-intel/VulkanTools/blob/debugMessageTest_v.0.0.1/BUILD.md)it [from source](https://github.com/dorian-apanel-intel/VulkanTools/tree/debugMessageTest_v.0.0.1). Layer is [very simple](https://github.com/dorian-apanel-intel/VulkanTools/commit/a253faa3d71c248b29bcaff1859f42fbd992dcdb), based on [layer factory from LunarG](https://github.com/dorian-apanel-intel/VulkanTools/tree/master/layer_factory).
3. Set layer as instance layer (either by [vkconfig ](https://vulkan.lunarg.com/doc/sdk/1.2.198.1/windows/vkconfig.html) or environment variables or registry entries)
4. Capture first frame of vkcube.exe from VulkanSDK using RenderDoc.
5. Load capture with RenderDoc option to use validation layers.
6. Inspect "Errors and Warnings" window in RenderDoc.
7. See that some EID's do not have its message and some have more. Begin and End of command buffers seems to be incorrect.

Additionally, if you capture not "Frame 0" but "Frame 1" of vkCube, then after loading capture, each click on different EID that replays frame will result in more and more debug messages printed.

## Environment

* RenderDoc version: 1.17
* Operating System: Windows 10
* Graphics API: Vulkan

**Comment by baldurk** [comment]
That commit should fix the issues you mentioned. Though the debug messages aren't intended to work with arbitrary layers so you shouldn't expect a direct 1:1 correspondance it at least better ties together the messages with command buffer events.

**Comment by dorian-apanel-intel** [comment]
It woks much better now. Thank you :)
