### ISSUE TITLE
Vulkan - Depth/stencil attachment's depth STORE_OP_DONT_CARE is forced onto stencil (STORDONTCARE)

### ISSUE THREAD

**Issue by z-adams** [baldurk/renderdoc#2437]
Apologies if this is a Vulkan issue, but this behavior only occurs in RenderDoc (and not in Nvidia NSight) and I cannot find any relevant details in the Vulkan spec to suggest I'm doing anything wrong.

## Description

My application renders the scene in a number of renderpasses. The first pass writes to the stencil buffer, and subsequent passes read from it. After each pass, the depth buffer is cleared. This scheme is to allow a huge scene to be rendered with several projection matrices to avoid Z precision issues.

Here is the configuration of my first pass (which writes to the stencil buffer):
```cpp
{
    // ...
    .depthLoadOp = VK_ATTACHMENT_LOAD_OP_CLEAR,    // clear depth each pass
    .depthStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,  // don't care about storing depth since it will be cleared
    .stencilLoadOp = VK_ATTACHMENT_LOAD_OP_CLEAR,   // clear stencil at frame beginning
    .stencilStoreOp = VK_ATTACHMENT_STORE_OP_STORE,  // save stencil for subsequent passes
    .depthStencilInitialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
    .depthStencilFinalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL
}
```
and of my subsequent passes:
```cpp
{
    // ...
    .depthLoadOp = VK_ATTACHMENT_LOAD_OP_CLEAR,
    .depthStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
    .stencilLoadOp = VK_ATTACHMENT_LOAD_OP_LOAD,   // load stencil from previous pass
    .stencilStoreOp = VK_ATTACHMENT_STORE_OP_STORE,
    .depthStencilInitialLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
    .depthStencilFinalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL
}
```

As far as I know, "don't care"-ing the depth buffer is perfectly alright if you don't need to re-use the values in a later pass.

**The problem:** with this configuration, the depth buffer is properly cleared and functions properly, but the stencil buffer is broken. Viewing the stencil channel of the D/S buffer in the subsequent passes displays `STORDONTCARE` everywhere, despite the fact that the stencil's storeOp is `VK_ATTACHMENT_STORE_OP_STORE`. While my application behaves correctly during capture, during replay the frame contents are messed up (consistent with a nonfunctioning stencil test). Changing the **depth's** storeOp to `VK_ATTACHMENT_STORE_OP_STORE` fixes the problem. If the first pass `STORE`s the depth value, the next pass's stencil will work, but as soon as a pass `DONT_CARE`s the depth store, the next pass's stencil will be broken.

The discrepancy between the capture and replay made me think I was invoking some sort of UB from Vulkan, but the validation layers are silent and the spec makes no mention of any conflict between depth and stencil load/store operations. Furthermore, this issue does not arise when inspecting the application with Nvidia NSight Graphics 2021.4.1; the stencil buffer appears fine and the replay preview looks normal.

## Steps to reproduce

1. Create a multi-pass rendering setup with two renderpasses, each with one subpass and implicit subpass dependencies
2. Configure the first pass to clear both the stencil and depth buffer, store the stencil buffer, and "don't care" the depth buffer
3. Configure the second pass to clear the depth buffer on load, and load the stencil buffer.
4. Capture a frame of the application. Scrub to an event in the first renderpass and ensure the stencil buffer is working properly. Scrub to an event in the second renderpass and observe the erroneous `STORDONTCARE` contents of the stencil buffer. RenderDoc itself reports the correct stencil load/store ops when inspecting the renderpass resource.

Hopefully this is enough background information, but if necessary I can provide the capture.

## Environment

* RenderDoc version: v1.17
* Operating System: Windows 10 Home 19043.1415
* Graphics API: Application running Vulkan 1.2.162 from the 1.2.198 SDK
* GTX 1070, driver version 27.21.14.6192

**Comment by baldurk** [comment]
If you have a capture to provide as a repro case then please share it. I understand that in some cases a capture can't be shared publicly if it contains sensitive information, in which case you can share it with me privately, or that in some cases not even that is possible. However if you say you're able to provide a capture then please do that immediately.

There's no benefit to trying to solve the bug with less information, and a capture gives me an immediate way to precisely replicate your problem as best as possible rather than trying to spend time re-implementing your problem from a higher level description and potentially missing some key component because of miscommunication or omission.

**Comment by baldurk** [comment]
That should fix the issue, thanks for sharing your repro case via email. I wasn't properly respecting the separate stencil load/store ops as you suspected so the depth op was being applied to both aspects.
