### ISSUE TITLE
DX11 input showing as unbound

### ISSUE THREAD

**Issue by midnite8177** [baldurk/renderdoc#244]
I haven't been able to find concrete documentation on the subject of what DirectX considers a conflict - whether it is at the resource level or subresource level.

According to [VSSetShaderResources](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476494(v=vs.85).aspx) it is at the resource level.

According to [OMSetRenderTargets](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476464(v=vs.85).aspx) it is at the subresource level.

Our personal experience indicates it is at the subresource level.

We have a mipmap generation pixel shader that is updating the mipmaps of a 3D texture. In a loop we are binding an RTV at a curr_mip level (and single W-slice) and an SRV of the same resource but viewing at a curr_mip-1 level. So, while the RTV and SRV are of the same resource, they are different subresources.

It appears to work just fine for us when running the game. However, if we do a RenderDoc capture (0.27 release), for each of these batches, it says the input texture of the PS stage is unbound. It appears that RenderDoc checks for the conflict at the resource level.

Do you know for sure for resource vs subresource? Since DX10 we've been writing code that assumes it is at the subresource level with no problems. I have not been able to find any concrete documentation of one way or the other. Perhaps we've just been getting lucky?

**Comment by baldurk** [comment]
Oh the joys of painfully bad D3D11 documentation.

RenderDoc does indeed track hazards and conflicts at resource level. Unfortunately I kind of need to do it manually otherwise the replay can diverge and cause bugs.

I'll do some experiments to see, but I suspect you're right that it happens at subresource level - for the exact case of mip-map generation. I'll need to update my tracking code to verify.

**Comment by baldurk** [comment]
I believe I've updated the tracking to correctly allow for RTVs and SRVs to both be bound referring to the same resource but different subresources, without losing any cases where an invalid bind should go to NULL. Please let me know if this fixes it for your case!

**Comment by baldurk** [comment]
Closing this issue as the bug is fixed in [v0.30](https://github.com/baldurk/renderdoc/releases/tag/v0.30). Feel free to re-open if it's not as you expect!
