### ISSUE TITLE
Nested structs are padded incorrectly

### ISSUE THREAD

**Issue by strandborg** [baldurk/renderdoc#2441]
## Description
Buffer viewer seems to pad nested struct types incorrectly, at least on DX11.

## Steps to reproduce

Consider the following HLSL code:

----
```
struct Inner
{
    uint data;
}

struct Outer
{
    Inner a;
    float3 b;
}

RWStructuredBuffer<Outer> MyBuf;
```
----

DX11 treats the Outer struct as being tightly packed and having size of 16 bytes (4 x 4 bytes).
When a shader containing the code above (and accessing MyBuf so that it won't get optimized away) is captured on RenderDoc, and the buffer contents is displayed, the Buffer Format tab displays following:

----
```
struct Inner
{
    uint data;
    xint pad[3]; // <-- Wrong!
}

struct Outer
{
    Inner a;
    float3 b;
}
```
----

As a result, the buffer stride is incorrect and the contents display is off accordingly. To work around the issue, the line 'xint pad[3];' can be commented out entirely, and the buffer contents are now displayed correctly.

## Environment

* RenderDoc version: 1.17
* Operating System: Windows 10 64-bit
* Graphics API: DX11

**Comment by baldurk** [comment]
Can you share a capture that demonstrates this, or at least the particular shader DXBC file? That ensures that I'm looking exactly the shader you are describing and there aren't any potential differences in compiler etc that could cause issues.

**Comment by strandborg** [comment]
I managed to reproduce the same problem by modifying the Compute shader example found in https://bitbucket.org/catlikecodingunitytutorials/basics-05-compute-shaders/src/master/

In original version, the _Positions array contains float3's. I modified it to this:

```
struct A
{
    float p;
};

struct Positions
{
    A _x;
    A _y;
    A _z;
};

RWStructuredBuffer<Positions> _Positions;
```

Both versions of the code render correctly, but the buffer contents in RenderDoc contains 3 padding uints for each instance of A, causing incorrect buffer contents display.

Capture attached:
[rd_repro.zip](https://github.com/baldurk/renderdoc/files/7829073/rd_repro.zip)

**Comment by baldurk** [comment]
I believe that commit should fix the issue, at least it does for the repro case. Differing packing rules are a nightmare and this is somewhat of a bandaid fix, but I plan to make a bigger refactor in this area to do away with the generated padding members anyway so hopefully that should make this more robust.

**Comment by strandborg** [comment]
awesome, and thanks again for RenderDoc, it's simply great!
