### ISSUE TITLE
OpenGL - GL_FIXED not accounted in vertex attributes

### ISSUE THREAD

**Issue by pent0** [baldurk/renderdoc#2442]
## Description

When use GL_FIXED as data type for glVertexAttribPointer, RenderDoc does not recognise GL_FIXED and instead treat it as a byte vector.

![image](https://user-images.githubusercontent.com/25717050/148693907-cb9dd2b5-d779-4779-8d02-51e86391bf80.png)

## Steps to reproduce

Call glVertexAttribPointer with type as GL_FIXED.
The mesh viewer will treat the attribute called as R8G8B8A8 or so.

## Environment

* RenderDoc version: v1.17 (commit hash 22d4dc45)
* Operating System: Windows 10 Pro 2004 19041.1415
* Graphics API: OpenGL 4.5

## Capture

Here's a [small renderdoc](https://mega.nz/file/3nI2gLCJ#8uiYzDnWZ_GCe7K1HBBXwa-x-c69HtS9boTcAdEcSAo) for the debugging. If the type is treated right the output mesh should not be gibberish. (I put the link on MEGA!). No special configurations here.

The expected output image: 
![image](https://user-images.githubusercontent.com/25717050/148693952-89aa7a22-d35d-46dc-881c-169b321ea464.png)

I do note that no sane person would use GL_FIXED in 2022, this is just from a thin GLES1 layer. Thank you very much on the work on Renderdoc!

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by pent0** [comment]
I don't understand. It's an emulator...

**Comment by pent0** [comment]
If you don't feel free I will try to add one. Disappointed by the response, literally emulator developer can't live... Have a good day.

**Comment by hieu-van** [comment]
> Capturing copyrighted programs

Irrelevant problem as it's an example, please focus on the main issue
