### ISSUE TITLE
[Feature Request] Use better default interface font (for Windows 10 in Chinese locale) or let users change it

### ISSUE THREAD

**Issue by ghost** [baldurk/renderdoc#2443]
## Description

RenderDoc's default interface font (宋体, `simsun.ttc`) for Windows 10 **in Chinese locale** is really ugly and unreadable.   
Setting Global Font Scale help a little bit but the main issue is the font.

![RenderDoc using 宋体](https://user-images.githubusercontent.com/59071629/148705649-23b0ccd1-778b-45a0-9bf8-8427375a766e.png)
(RenderDoc using 宋体)

Although ReaderDoc is in English, it will still use the English part of 宋体. The **actual default** interface font in **Windows 10** is 微软雅黑 (`Microsoft YaHei UI`), which is a okay sans-serif font for English. I think this should also be the default in RenderDoc.

![微软雅黑](https://user-images.githubusercontent.com/59071629/148705905-76d4b0d6-6f61-470a-ab1b-ab7c345e76be.png)
(Windows 10's File Explorer using 微软雅黑)

---

This is a common issue in Qt apps. Musescore and Krita solve this by letting users to change interface font. (they use 微软雅黑 as default in recent versions)

![Font selection UI](https://user-images.githubusercontent.com/59071629/148706812-c4ef1c50-0df5-4827-a82e-8787392b3f13.png)
(Interface font selection UI in Krita and Musescore, also comparsion between 宋体, 微软雅黑 and Roboto)

I would like RenderDoc to use similar solutions, or at least use 微软雅黑 as the default.

## Environment

* RenderDoc version: v1.17
* Operating System: Windows 10 1703
* Graphics API: OpenGL, Vulkan, DX12

**Comment by baldurk** [comment]
Thanks for reporting this, it's certainly a blind-spot of mine so I welcome any feedback like this.

I'm a little uncomfortable changing the default font based only on one report, especially without being familiar with the options and renderdoc not really being localised in any way (aside from the code being somewhat prepared for translation). Being able to change the default font though is an entirely reasonable request and so that commit should let you customise it to any on your system that Qt reports.

Please let me know if this works for you and addresses the issue. I'm certainly willing to make further changes to improve the experience with RenderDoc on other languages and locales, but I want to be sure I'm doing the right thing since it's not something I can verify myself.

**Comment by ghost** [comment]
> Please let me know if this works for you and addresses the issue. I'm certainly willing to make further changes to improve the experience with RenderDoc on other languages and locales, but I want to be sure I'm doing the right thing since it's not something I can verify myself.

Thanks, but I don't have the build environment and am not willing to set it up, do I need to wait for nightly builds on https://renderdoc.org/builds#nightly or are there other places for binary releases?

---

> I'm a little uncomfortable changing the default font based only on one report, especially without being familiar with the options and renderdoc not really being localised in any way (aside from the code being somewhat prepared for translation).

I agreed. For now allowing customization is enough.  
When Chinese user base become large that localization is needed, it's probably the time for setting the default. (by the way, Chinese part of that font is even more horrible, sigh...)

**Comment by ghost** [comment]
## Working as expected, thanks!

![yh](https://user-images.githubusercontent.com/59071629/148898793-c1fe3d65-099c-4890-9c5a-039e6e7604b6.png)

---

There are however a minor issue, and a (good) side effect I find during trying to solve it:
The font in the red rect looks like Courier New (which is not really bad so I'm fine with that), and I can't make RenderDoc choose the custom font for this (by trying all combinations of "prefer mono fonts" and choose custom proportional/mono fonts)

![mono](https://user-images.githubusercontent.com/59071629/148899138-3f531ec0-93d8-4fa8-9807-17f11c945ff3.png)

The side effect I find is that now I can choose mono font as the main interface font (JetBrains Mono in this picture), and I see some people wanting mono fonts for interface in previous issues. I think ultimately the solution to this is maybe allowing two custom fonts, one for main interface (proportional is common, but mono can be choosed) and one for tables, logs, console and script editor, etc. (mono is common, but proportional can be choosed). This also get rid of the "prefer mono" boolean since we can just choose the same font.

**Comment by baldurk** [comment]
Yes builds are created nightly (on western europe time) at that build. For reference there's no complex build environment needed, you only need a somewhat recent visual studio installed (2015 is the minimum) which if you're developing on windows you presumably already have.

I'm not sure I understand what the problem you're describing is. You say the default monospace font is fine as-is and that's what I'd have said as well, and being able to choose a monospace font for the default is also not a problem and I'd agree there.

The 'prefer monospaced' option is there specifically for elements which typically use the default font for things like resource and event names which are considered 'text' so use the default font that is likely proportional, but some people prefer that to be considered 'data' and use a monospaced font.

**Comment by ghost** [comment]
> The 'prefer monospaced' option is there specifically for elements which typically use the default font for things like resource and event names which are considered 'text'

I guess I interpreted this option wrong, I thought that it's for forcing tables, consoles, script editor, etc. to use mono font.

What I'm suggesting is to allow **seperate** custom font for those elements too. Since main UI font is now customizable, it feels a bit weird that those don't mirror that. This is not totally unconventional in complex programs, for example Blender allows you to customize both. The current default is indeed okay and usable (not great though), so I'd say this is just a minor issue, and I'm fine if you decide not to implement this.

> you only need a somewhat recent visual studio installed (2015 is the minimum)

Yeah... that's the part I hate, I use gcc and do stuff manually, but it's not worth going into since testing without building from source is viable.

**Comment by baldurk** [comment]
I think that makes sense. I'm still not sure there's much need for customising the monospace font but it's straightforward to add and I can certainly appreciate that it makes for a more consistent customisation.

That commit adds the ability to change it, and also tries to clarify what the 'prefer monospace' toggle is for - as above it's more about switching some of the UI elements which typically use a default font for places like the event browser and pipeline state listings where mostly you will see resource names and a fixed width font has limited utility.
