### ISSUE TITLE
[MSVC][std:c++latest][permissive-] renderdoc failed to build on MSVC

### ISSUE THREAD

**Issue by xiaoxiao-Xu** [baldurk/renderdoc#2453]
## Description
Hi All,

The MSVC team recently added renderdoc as part of RWC testing to detect compiler regressions. And we found the same errors when building renderdoc with '/std:c++latest' and '/permissive-'. Could you please help look at this issue or provide some workarounds? Thanks in advance.

## Steps to reproduce
1. git clone https://github.com/baldurk/renderdoc F:\gitP\baldurk\renderdoc
2. set _CL_= /std:c++latest or set _CL_= /permissive-
3. msbuild /m /p:Platform=x64 /p:Configuration=Release /p:PlatformToolset=v142 renderdoc.sln /t:Rebuild

## Environment

* RenderDoc version: v1.17
* Operating System: Windows server 2019
* Graphics API: XXX

Build log:
'/std:c++latest' : [build.log](https://github.com/baldurk/renderdoc/files/7885385/build.log)
'/permissive-': [build.log](https://github.com/baldurk/renderdoc/files/7885388/build.log)

**Comment by baldurk** [comment]
Can you please give more information, which version of visual studio are you building on? I think toolset v142 is VS2019 but visual studio's version numbering is often inconsistent so it would be good to know for sure. The CI currently tests on VS2019 so I don't think there should be any compile errors there.

Does this still happen if you don't provide any custom compile options? If it doesn't then this is not something I'd look into as too often custom compile options can trigger false positive warnings/errors or other compiler bugs, or enable options which I do not wish to be using so are not intended to work. Briefly looking at the log posted that certainly seems to be the case as at least some of those errors look to be wrong.

**Comment by xiaoxiao-Xu** [comment]
Thanks for the quick reply!

We build renderdoc project with visual studio 2019 16.11.8. It would not appear without '/std:c++latest' and '/permissive-' options. Also, we didn't set any custom compile options.

**Comment by baldurk** [comment]
Sorry I'm unclear what you mean. Did you have to set '/std:c++latest' and '/permissive-' options for the problem to appear, or did it show errors without any custom options set?

**Comment by xiaoxiao-Xu** [comment]
Yes. When I set '/std:c++latest' or '/permissive-', the issue only will appear. And, I attached build log above. Please check it.

**Comment by baldurk** [comment]
OK if the errors only appear when you enable custom compile options then this isn't something I'll look into. I've tested again on the latest point release of VS2019 and it compiles cleanly on development and release.

I'd recommend not enabling any options like that so you can build the project, since as I mentioned above I don't support any arbitrary custom compile options being selected.
