### ISSUE TITLE
Pixel context looks incorrect when using custom visualization shaders with Vulkan

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2459]
## Description

The "Pixel context" window is too dark when using custom visualization shaders with Vulkan.  This doesn't happen with other APIs (including OpenGL).  This issue happens with GLSL on NVIDIA and both GLSL and HLSL on Intel (see #2458 for why HLSL on NVIDIA didn't work).  This doesn't affect the built-in RGBM and YUVA decode modes.

## Steps to reproduce

To generate the attached capture:

1. Download Dolphin and the [lesson08 fifolog](https://fifo.ci/media/dff/Lesson08.dff).
2. Launch Dolphin using RenderDoc.
3. In Dolphin, click "Graphics", and change the backend to Vulkan.
4. In Dolphin, switch to the advanced tab under graphics and check "Enable API Validation Layers" (this is not required to reproduce, but it enables debug symbols and source attachment for the shader)
5. In Dolphin, close the graphics window and open the config window.  Uncheck "Enable Dual Core" (as the fifoplayer doesn't work well with it).
6. In Dolphin, close the graphics window, and then select "open".  Open the Lesson08.dff file from before.
7. Save a capture.  Dolphin can now be closed.

To reproduce:

1. Open [Lesson08_Vulkan.zip](https://github.com/baldurk/renderdoc/files/7919669/Lesson08_Vulkan.zip)
2. Navigate to an internal-resolution draw (in this capture, EID 59).
3. Click on the input texture.
4. In the texture viewer, under channels, select "custom".
5. In the drop-down next to that, enter `RA.glsl` and click the green `+` button.
6. Enter the following in the new shader:
    ```glsl
    #version 420 core
    
    layout(binding = 7) uniform sampler2DArray tex2DArray;
    layout (location = 0) in vec2 uv;
    layout (location = 0) out vec4 color_out;
    
    void main()
    {
        color_out = vec4(texture(tex2DArray, vec3(uv, 0)).ra, 0, 1);
    }
    ```
7. Click "apply changes"
8. Switch back to the texture viewer.
9. Right-click a pixel.
10. Observe that the preview in the "Pixel Context" window is much darker than the actual texture.

![image](https://user-images.githubusercontent.com/8334194/150666175-91931c40-1fe6-4be8-aa29-4770772687b4.png)

## Environment

* RenderDoc version: v1.17
* Operating System: Windows 10.0.19042.1466
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Looks like this was caused by a dangling typecast. When the texture itself is UNORM and the custom shader output is written to R16G16B16A16_SFLOAT, the unorm cast is left over and the texture is displayed as R16G16B16A16_UNORM. This was fixed in the main display but not in the pixel context - that commit should sort it out.
