### ISSUE TITLE
Scrollbars in texture viewer are at the wrong position/size after changing textures

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2470]
## Description

The scrollbars on the texture viewer start in the wrong position after changing between textures of different sizes (very similar to #2377).  Moving the scrollbar gives correct results, but only for that scrollbar specifically, so both scrollbars need to be moved for their positions to actually make sense (and moving them also means that you start from the wrong location).  If the old texture didn't have scroll bars, then the scroll bars will be unusable on the new texture.

Where the scroll bars display:
![image](https://user-images.githubusercontent.com/8334194/151481624-1e0bfbb2-eced-4be2-aba2-d2a93711e0ea.png)

The actual image position corresponding to those scrollbars:
![image](https://user-images.githubusercontent.com/8334194/151481655-a82136fd-49be-4909-8512-2cc5b47ec75a.png)

## Steps to reproduce

To reproduce:

1. Open a capture, such as [Lesson08_Vulkan.zip](https://github.com/baldurk/renderdoc/files/7919669/Lesson08_Vulkan.zip) from #2459 (don't use Lesson08_Vulkan_8x.zip from #2377, as the size differences there are too big, which makes it hard to experiment (though the issue does still happen))
2. Navigate to an internal-resolution draw (in this capture, EID 59).
3. Zoom in on the center of the output texture enough that scrollbars appear (for me, zooming in 1000% worked well for reproducing)
4. Switch to the input texture.
5. Move the scrollbar slightly, and observe that the image jerks to a different location.

Note that the scrollbars do appear to move when switching between textures, but their new position is wrong.  Also note that panning the image by dragging updates the scrollbars, but does not get rid of the jerking behavior.

## Environment

* RenderDoc version: v1.18
* Operating System: Windows 10.0.19042.1446
* Graphics API: Vulkan

**Comment by baldurk** [comment]
This bug was similar to the one you linked, the scrollbar bounds weren't properly being re-calculated when switching textures.
