### ISSUE TITLE
RenderDoc file got imported to blender with currypted mishes

### ISSUE THREAD

**Issue by AliAlherz64** [baldurk/renderdoc#2473]
## Description

 if you select intersect face and then applied [intersect (knife)], blender will crash  .

## Steps to reproduce

Open attached (compressed blender ) file , you will see it is in [Edit Mode] and a face got selected.
apply [intersect (knife)]
blender will collapse. 

[Googled Haram.zip](https://github.com/baldurk/renderdoc/files/7966327/Googled.Haram.zip)

## Environment
Operating system: Windows-10-10.0.19044-SP0 64 Bits
Graphics card: Intel(R) HD Graphics 630 Intel 4.5.0 - Build 27.20.100.9664

Blender Version
Broken: version: 3.0.0, branch: master, commit date: 2021-12-02 18:35, hash: rBf1cca3055776
Worked: (newest version of Blender that worked as expected)

* RenderDoc version: 1.7
* Operating System: XXX
* Graphics API: XXX

I tried to attach renderdoc file , but it is not included in the list.

**Comment by baldurk** [comment]
You're describing a crash in blender but that is a different program and there is no relationship between RenderDoc and blender. If you're encountering a problem with blender, you need to report the bug to them.

If you have a problem with RenderDoc please open an issue describing the problem with RenderDoc and how to reproduce the problem there, not in unrelated programs.

**Comment by AliAlherz64** [comment]
Dear
I was importing mishes from rdc file, which got generated by rendderDoc . I tried to attach it, but I am not able to .
regards

**Comment by baldurk** [comment]
That doesn't change anything, if the crash is happening in blender you need to report it to blender. RenderDoc doesn't provide any mechanism for exporting meshes or interoperating with blender, so however you have done that is presumably custom code you would need to debug yourself.

This issue tracker is only for RenderDoc bugs, not bugs in other software.
