### ISSUE TITLE
I can't install the Vulkan layer

### ISSUE THREAD

**Issue by edap** [baldurk/renderdoc#2474]
## Description
I can't install the Vulkan layer.

## Steps to reproduce

- Open RenderDoc, click on the warning message
![error-msg](https://user-images.githubusercontent.com/161152/151751463-1e0f9c6b-8ea6-4d50-8207-d0eaf321a513.png)
- Click on yes on both the dialogue messages
![error2](https://user-images.githubusercontent.com/161152/151751521-c401dccd-95a9-49e4-b91f-95beac868fb0.png)
![error-3](https://user-images.githubusercontent.com/161152/151751531-b9bf785c-a970-42b2-867d-048a2715ed09.png)
- Nothing happens

## What I have tried to fix the issue
- Install the vulkan layer through command line with `sudo ./qrenderdoc --install_vulkan_layer 1`. But it quits silently.

My current workaround is to run RenderDoc as sudouser with  `sudo ./qrenderdoc`. Then I am able to capture applications and analyze frames.

## Environment

* RenderDoc version: 1.18
* Operating System: PopOs 21.10 (based on Ubuntu 21.10)
* Graphics API: Vulkan
* GPU: [AMD] Renoir/Cezanne

**Comment by baldurk** [comment]
I'm assuming you're running version 1.18 not 0.18.

Please do not run random undocumented commands to try and fix the issue, it only makes it harder to identify what the real problem is. In this case the command you've run will have registered the layer at a user level for the root user, so while it then means RenderDoc will work when running at root I do not recommend that for obvious reasons.

Can you tell me if you have any of the programs `kdesudo`, `gksudo`, or `beesu` installed? If not, do you have any of the terminal emulators `x-terminal-emulator`, `gnome-terminal`, `konsole`, `xterm`?

Can you also please share the diagnostic log (from Help -> View Diagnostic Log) after running RenderDoc as a **normal** user and following the steps you listed above.

**Comment by edap** [comment]
Hello, thanks for your reply. Yes, I meant RenderDoc 1.18(I have corrected my bug report). Among the packages that you have listed, only `gnome-terminal` is installed.

This is the output of the diagnostic log:

```
RDOC 013856: [11:25:12]             core.cpp( 483) - Log     - RenderDoc v1.18 Linux 64-bit Release (3996d037b9ec86cde4aa482b7ac4f6aa50068ec4) loaded in replay application
RDOC 013856: [11:25:12]             core.cpp( 494) - Warning - Couldn't open socket for target control
RDOC 013856: [11:25:12]         settings.cpp( 460) - Log     - Loading config from /home/dapx/.renderdoc/renderdoc.conf
QTRD 013856: [11:25:12]                     (   0) - Log     - QRenderDoc initialising.
RDOC 013856: [11:25:12]    android_tools.cpp( 347) - Log     - Initialising adb using 'adb'
RDOC 013856: [11:25:12]    android_tools.cpp( 354) - Warning - Couldn't locate adb. Ensure adb is in PATH, ANDROID_SDK or ANDROID_HOME is set, or you configure your SDK location
QTRD 013856: [11:25:12]                     (   0) - Warning - area parameter ignored for this type
RDOC 013856: [11:25:12]        vk_replay.cpp(4499) - Log     - Created device.
QTRD 013856: [11:25:55]                     (   0) - Warning - Only C and default locale supported with the posix collation implementation
QTRD 013856: [11:25:55]                     (   0) - Warning - Only C and default locale supported with the posix collation implementation
QTRD 013856: [11:25:55]                     (   0) - Warning - Case insensitive sorting unsupported in the posix collation implementation
QTRD 013856: [11:25:55]                     (   0) - Warning - Numeric mode unsupported in the posix collation implementation
QTRD 013856: [11:25:57]                     (   0) - Warning - Only C and default locale supported with the posix collation implementation
QTRD 013856: [11:25:57]                     (   0) - Warning - Only C and default locale supported with the posix collation implementation
QTRD 013856: [11:25:57]                     (   0) - Warning - Case insensitive sorting unsupported in the posix collation implementation
QTRD 013856: [11:25:57]                     (   0) - Warning - Numeric mode unsupported in the posix collation implementation
```

**Comment by baldurk** [comment]
OK thanks. Can you please run:

`gnome-terminal -e "bash -c 'echo Running \"/path/to/qrenderdoc --install_vulkan_layer root\" as root.;echo;sudo /path/to/qrenderdoc --install_vulkan_layer root'"`

and let me know if that works?

**Comment by edap** [comment]
If I run that command, a terminal opens:
`Running /path/to/qrenderdoc --install_vulkan_layer root as root.`
And then ask me the password.
Let me know if there is something I can do to help you debugging this issue.

**Comment by baldurk** [comment]
Just to check, if you put in your password is the vulkan layer then correctly registered? I assume so since it sounds like the problem is in launching the terminal emulator not in the registration.

If so, please delete the file `/etc/vulkan/implicit_layer.d/renderdoc_capture.json` so we can continue to investigate.

Are you launching that command in exactly the same way as you're launching qrenderdoc? As the same user and from the same environment?

**Comment by edap** [comment]
I have entered the password but nothing happened, the terminal `gnome-terminal` window closed without any message. If I launch qrenderdoc the warning message is still there.
I do not have any files inside `/etc/vulkan/implicit_layer.d/`.
I am launching the command `./qrenderdoc` from `terminator`, that is another linux terminal. I have just tried lunching it from `gnome-terminal` and the result does not change, same problem as well.

May it be related to the fact that I have installed the vulkan layer using sudo? where can i find it and remove it?

**Comment by baldurk** [comment]
It shouldn't be related but it's a good idea to remove. There should be a `/root/.local/share/vulkan/implicit_layer.d/renderdoc_capture.json` and you should delete that file.

It sounds like there are two problems then, one that gnome-terminal is not properly being launched when trying to fix the warning in qrenderdoc, and second that the system-level registration is failing.

Taking them one at a time, can you elevate to root in a terminal (`su` or `sudo bash`) and then run `strace -o qrd.log ./qrenderdoc --install_vulkan_layer root` and share the qrd.log that's produced? Also in the meantime can you clone the repository and build a debug build of RenderDoc so we can debug it or add logging/patches.

**Comment by edap** [comment]
I am cloning the repository right now, file `renderdoc_capture.json` deleted.
Log in attachment.
[qrd.log](https://github.com/baldurk/renderdoc/files/7971799/qrd.log)

**Comment by edap** [comment]
I am cloning the repository right now, file `renderdoc_capture.json` deleted.
Log in attachment.
[qrd.log](https://github.com/baldurk/renderdoc/files/7971799/qrd.log)

**Comment by baldurk** [comment]
That log shows the file under /etc being written as expected:

```
openat(AT_FDCWD, "/etc/vulkan/implicit_layer.d/renderdoc_capture.json", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 7
newfstatat(7, "", {st_mode=S_IFREG|0644, st_size=0, ...}, AT_EMPTY_PATH) = 0
write(7, "{\n  \"file_format_version\" : \"1.1"..., 1619) = 1619
close(7)                                = 0
```

So I don't understand how it would be missing afterwards. Are you absolutely sure you don't have that file after running the `sudo qrenderdoc` command? Please double check that you haven't written a typo when checking the path.

**Comment by edap** [comment]
If I run `sudo ./qrenderdoc` no `/etc/vulkan/implicit_layer.d/renderdoc_capture.json` is created. If I run `strace -o qrd.log ./qrenderdoc --install_vulkan_layer root` the file is created.

**Comment by baldurk** [comment]
Just to be absolutely clear, you should never be running just `sudo ./qrenderdoc`. The full command as tested above via gnome-terminal for interactivity is `sudo ./qrenderdoc --install_vulkan_layer root`, which you said didn't create the file. I'm not sure if you were running the wrong command there or just shortening for brevity, but in that case please don't shorten anything so that we're all on the same page :).

Also checking, the strace is run from a root shell? what happens if you run the `./qrenderdoc --install_vulkan_layer root` from that same root shell, does that create the file correctly?

As a final check, can you try running `sudo strace -o qrd_sudo.log ./qrenderdoc --install_vulkan_layer root`.

**Comment by edap** [comment]
1) The command `strace -o qrd.log ./qrenderdoc --install_vulkan_layer root` was executed in a root shell
2) The command `sudo ./qrenderdoc --install_vulkan_layer root` executed in a root shell creates the expected file `renderdoc_capture.json`
3) the command `sudo strace -o qrd_sudo.log ./qrenderdoc --install_vulkan_layer root` created the expected file also.

**Comment by baldurk** [comment]
Running `sudo` in a root shell is a no-op at best. I'm trying to figure out if there's a difference between elevating yourself and then running the command, vs running via sudo from a normal command (as RenderDoc tries to do, and as seemed to fail above).

I'm assuming command 2 will also work without the `sudo` but please verify that.

Did you run command 3 from inside a root shell? I wouldn't have thought so otherwise, but you mentioned that you ran command 2 from a root shell so I want to be sure.

Can you also try running `sudo ./qrenderdoc --install_vulkan_layer root` from a non-root shell? That's what you did above inside gnome-terminal and you said it didn't produce the layer file, but maybe it's a gnome-terminal problem of some kind so running the command manually should check that.

**Comment by edap** [comment]
If I have run sudo from a root shell I did it yesterday by mistake, because I know that it does not make any sense.

Reagrding point 2) the command `./qrenderdoc --install_vulkan_layer root` does not create the file `/etc/vulkan/implicit_layer.d/renderdoc_capture.json`.  I think it makes sense because a normal user does not have the rights to write into `/etc/vulkan/implicit_layer.d`.If I run  `sudo ./qrenderdoc --install_vulkan_layer root` the file `renderdoc_capture.json` is created.
Regarding point 3), `sudo strace -o qrd_sudo.log ./qrenderdoc --install_vulkan_layer root` creates the expected file.

All commands where executed from a non root shell.

Let me know if there is something else that I can do to help you debugging this issue, and many thanks for your support

**Comment by baldurk** [comment]
I know that running the command plainly from a non-root shell won't work, I was asking if it would work from a root shell to narrow down what's going wrong. Either way if `sudo ./qrenderdoc --install_vulkan_layer root` works when run manually then that's enough, but I'm still confused as to what's happening as this doesn't make much sense.

Can you try again to run it via gnome-terminal? Exactly the same way as you did in the earlier comment, with the command `gnome-terminal -e "bash -c 'echo Running \"/home/dapx/Applications/renderdoc_1.18/bin/qrenderdoc --install_vulkan_layer root\" as root.;echo;sudo /home/dapx/Applications/renderdoc_1.18/bin/qrenderdoc --install_vulkan_layer root'"`. You said before that after running that you still had the vulkan layer warning in RenderDoc and no file was created. Can you check again just to be extra sure that it fails when run via gnome-terminal like that but then still works when run manually?

**Comment by edap** [comment]
I have run from the gnome-terminal the command `gnome-terminal -e "bash -c 'echo Running \"/home/dapx/Applications/renderdoc_1.18/bin/qrenderdoc --install_vulkan_layer root\" as root.;echo;sudo /home/dapx/Applications/renderdoc_1.18/bin/qrenderdoc --install_vulkan_layer root'"` from the gnome-terminal. I have entered my password and this time the file `renderdoc_capture.json` was created. If I open renderdoc, the warning is no longer visible and I can capture a frame. For completeness, from the gnome-terminal, I have received this warning.
```
# Option “-e” is deprecated and might be removed in a later version of gnome-terminal.
# Use “-- ” to terminate the options and put the command line to execute after it.
```

I have tried to run the same command from terminator(my default terminal), and the file was created.

**Comment by baldurk** [comment]
I'm really confused now. Has anything changed in your system configuration, environment, or anything between the first time you ran that command yesterday and this time? does it work consistently every time you run it or does it randomly work and we got lucky/unlucky? I don't understand why it would work now when it didn't before.

**Comment by edap** [comment]
I have run an update yesterday night.I have tried the command 3 times now, and the file was always created. Do you want me to: delete the  `renderdoc_capture.json` file, build the project and put some print statement when I click on the warning message? If yes, which branch?

**Comment by baldurk** [comment]
Maybe something in the update changed things, though that seems highly coincidental. I'm not sure how else to explain that running the exact same command failed yesterday and works today. Either way, I guess we can discount that potential bug and investigate why RenderDoc was not properly launching gnome-terminal.

Can you check out v1.x which is the current and default branch and apply this patch: [extra_logs.txt](https://github.com/baldurk/renderdoc/files/7978072/extra_logs.txt), or if you're not comfortable applying patches, search in QRDUtils.cpp for `run terminal sudo with emulator` and replace the whole section from there to the first `return true;` with this snippet:

```c++
    // run terminal sudo with emulator
    QStringList termParams;
    termParams << lit("-e")
               << lit("bash -c 'echo Running \"%1 %2\" as root.;echo;sudo %1 %2'")
                      .arg(fullExecutablePath)
                      .arg(params.join(QLatin1Char(' ')));

    qInfo() << "Running" << term << "with parameters" << termParams;

    process->start(term, termParams);

    // when the process exits, call the callback and delete
    QObject::connect(process, OverloadedSlot<int, QProcess::ExitStatus>::of(&QProcess::finished),
                     [parent, process, finishedCallback](int exitCode) {
                       qInfo() << "Process finished with" << exitCode << "and error"
                               << process->error();

                       QByteArray stdoutput = process->readAllStandardOutput();
                       QByteArray stderrors = process->readAllStandardError();

                       qInfo() << "stdout:" << QString::fromLatin1(stdoutput);
                       qInfo() << "stderr:" << QString::fromLatin1(stderrors);

                       process->deleteLater();
                       GUIInvoke::call(parent, finishedCallback);
                     });

    QObject::connect(process, &QProcess::errorOccurred, [process](QProcess::ProcessError err) {
      qInfo() << "Process errored with" << process->exitCode() << "and error" << err << "("
              << process->error() << ")";

      QByteArray stdoutput = process->readAllStandardOutput();
      QByteArray stderrors = process->readAllStandardError();

      qInfo() << "stdout:" << QString::fromLatin1(stdoutput);
      qInfo() << "stderr:" << QString::fromLatin1(stderrors);
    });

    return true;
```

Then make sure the json under /etc is deleted, run qrenderdoc from a non-root shell as normal, check that it detects the vulkan layer is not registered and click on the warning, and select yes to both registering the layer and registering it at root level. When it fails to launch gnome-terminal check the diagnostic log again via help -> view diagnostic log and share the log here.

**Comment by edap** [comment]
I can't build it. I have installed the dependencies `sudo apt-get install qt5-qmake libqt5svg5-dev libqt5x11extras5-dev`.
But I am receiving the error:

```
--   No package 'xcb-keysyms' found
CMake Error at /usr/share/cmake-3.18/Modules/FindPkgConfig.cmake:545 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)
  renderdoc/CMakeLists.txt:69 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/dapx/Applications/renderdoc/build/CMakeFiles/CMakeOutput.log".

```

I have installed, in order: `libxcb-xrm-dev`, `libx11-xcb-dev` and `libx11-xcb-dev`, and I have tried to build every time after installing a package, but the error message persists.

**Comment by baldurk** [comment]
Please check the [CONTRIBUTING documentation with information about the dependencies required](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Dependencies.md). If you're using an apt based distro then I'd suggest starting with the packages for Ubuntu or debian to see if they're available on your distro. It sounds like you're missing `libxcb-keysyms1-dev` at least given that error

**Comment by edap** [comment]
Installing the package `libxcb-keysyms1-dev` solved the problem, I can now run `cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild -H.`.  Maybe it could be useful to add it to [Ubuntu section](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Dependencies.md#ubuntu) and change the required dependencies from `sudo apt-get install qt5-qmake libqt5svg5-dev libqt5x11extras5-dev` to `sudo apt-get install qt5-qmake libqt5svg5-dev libqt5x11extras5-dev  libxcb-keysyms1-dev`.
But I have another issue, after running `make -C build`, almost at the end of the build process I have this error:

```
[ 93%] Built target renderdoc
make[2]: Entering directory '/home/dapx/Applications/renderdoc/build'
Scanning dependencies of target custom_swig
make[2]: Leaving directory '/home/dapx/Applications/renderdoc/build'
make[2]: Entering directory '/home/dapx/Applications/renderdoc/build'
[ 93%] Creating directories for 'custom_swig'
[ 94%] Performing download step (download, verify and extract) for 'custom_swig'
-- Downloading...
   dst='/home/dapx/Applications/renderdoc/build/qrenderdoc/custom_swig-prefix/src/renderdoc-modified-7.zip'
   timeout='none'
-- Using src='https://github.com/baldurk/swig/archive/renderdoc-modified-7.zip'
-- [download 100% complete]
-- Downloading... done
-- extracting...
     src='/home/dapx/Applications/renderdoc/build/qrenderdoc/custom_swig-prefix/src/renderdoc-modified-7.zip'
     dst='/home/dapx/Applications/renderdoc/build/qrenderdoc/custom_swig-prefix/src/custom_swig'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 94%] No update step for 'custom_swig'
[ 94%] No patch step for 'custom_swig'
[ 95%] Performing configure step for 'custom_swig'
make[2]: *** [qrenderdoc/CMakeFiles/custom_swig.dir/build.make:128: qrenderdoc/custom_swig-prefix/src/custom_swig-stamp/custom_swig-configure] Error 127
make[2]: Leaving directory '/home/dapx/Applications/renderdoc/build'
make[1]: *** [CMakeFiles/Makefile2:675: qrenderdoc/CMakeFiles/custom_swig.dir/all] Error 2
make[1]: Leaving directory '/home/dapx/Applications/renderdoc/build'
make: *** [Makefile:149: all] Error 2
make: Leaving directory '/home/dapx/Applications/renderdoc/build'

```

**Comment by baldurk** [comment]
The ubuntu section already lists the correct dependencies including `libxcb-keysyms1-dev`. Quoting from that page linked:

> For Ubuntu 14.04 or above you'll need:
>
> `sudo apt-get install libx11-dev libx11-xcb-dev mesa-common-dev libgl1-mesa-dev libxcb-keysyms1-dev cmake python3-dev bison autoconf automake libpcre3-dev`
>
> For the base dependencies. On Ubuntu 18.04 and above Qt is available in the default repositories:
>
> `sudo apt-get install qt5-qmake libqt5svg5-dev libqt5x11extras5-dev `
>
> For older versions of Ubuntu they might not include a recent enough Qt version, so [...]

Did you install all of the dependencies correctly? It looks like you only ran the command for new Ubuntu versions that installs the Qt packages from the system sources instead of from a ppa/elsewhere.

**Comment by edap** [comment]
My system is based on Ubuntu 21.10, therefore I have installed only these dependencies `qt5-qmake libqt5svg5-dev libqt5x11extras5-dev` and then I have added `libxcb-keysyms1-dev`. I have now installed also the dependencies listed in the section `For Ubuntu 14.04 or above` and I was able to compile with the adjustments you were suggesting.
I have deleted the file `/etc/vulkan/implicit_layer.d/renderdoc_capture.json` and I have launched the qrenderdoc version just built, I have clicked on the warning message, I have replied both times "yes" and my default terminal (terminator) opened and asked me for my password. I have entered it, and the file `/etc/vulkan/implicit_layer.d/renderdoc_capture.json` was created, but the warning message is still there. 
If I close renderdoc and I launch it again, the warning is gone.

Many thanks for your time&patience and for this wonderful tool. If there is something else that I can do to help you debugging this issue just let me know. I can confirm that with this patch a terminal opens and the file is correctly created.

**Comment by baldurk** [comment]
OK, yes you do need to install all of the required dependencies not just some of them. This is explained in the linked documentation.

Can you please remove the file, repeat the steps, and share the log as I requested before? The patch doesn't fix or change any logic, it only adds logging. If it works now presumably the only difference is a self-compiled version vs the pre-compiled binary. If the warning is staying until RenderDoc is restarted that's possibly just because the terminal doesn't block before returning, which there's not much I can do.

Can you also please re-test the original steps in the original bug report with the binary download of RenderDoc? In case it is now working as well.

**Comment by edap** [comment]
Sure, which log are you talking about exactly, the `qrd.log`? should I get it using the command `strace -o qrd.log ./qrenderdoc --install_vulkan_layer root` ?

I am 100% sure that the terminal did not showed up yesterday when I have clicked on the warning. And I am sure because I did it multiple times. But now I have just tried to remove the `/etc/vulkan/implicit_layer.d/renderdoc_capture.json` file, open the downloaded version of renderdoc, click on the warning, reply yes 2 times and the terminal opens. I have entered the password and the file was created. I close the downloaded version of renderdoc, I open it again and the warning message is gone.

**Comment by baldurk** [comment]
If it's working now in the downloaded version then there's nothing that can be investigated, as if the bug is not reproducible anymore we can't draw any conclusions. I'm glad you have it sorted, the warning message staying as I say is unavoidable in the case where the terminal does not block, since it's impossible to tell when the process has finished.
