### ISSUE TITLE
Color Preview for Inspector Values

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#2475]
## Description

Hi, during a shader debugging session I was looking at variables and seeing what their color values were, to see how they're evolving and visually see anything wrong, e.g. where albedo goes black, or some nan or something like that. I thought to myself that it'd be useful if somehow a preview of the colors was easily accesible it would instantly point to a suspicious behavior. I realize that for many quantities the color doesn't make sense. Let me know what you think

![image](https://user-images.githubusercontent.com/700032/151776806-c7ab9d6d-8d62-4452-a8be-6e42356f461c.png)

![image](https://user-images.githubusercontent.com/700032/151777813-d22bca9c-e385-4110-96db-a183924c4980.png)

## Environment

* RenderDoc version: 1.17
* Operating System: Windows 10
* Graphics API: DX11

**Comment by baldurk** [comment]
I don't think this is a common enough use-case to merit a new column.

Potentially this could be added as a new watch window option, in addition to specifiers like `r1,f` for float or `r1,x` for hex, you could have `r1,c` for colour and the value column could show the colour.

**Comment by redorav** [comment]
Would it be possible for it to be a column that is hidden by default? I like the fact that I can just track everything automatically, if I have to manually input things it kind of loses that fast inspection quality, and it takes me a similar time to copy it. It would be more useful to see the float and color values at the same time. Black isn't the same if it has negative values, or white if it's HDR, etc.

**Comment by baldurk** [comment]
I imagined that display as colour would also display the float value, since as you say the colour on its own is quite low in utility. Similar to how your mockup looks, but with the colour swatch and float value in the same column. I don't think it's a significant enough feature to have an option and hidden column.

**Comment by redorav** [comment]
Ah I see what you mean. If you're talking about something like this:

![image](https://user-images.githubusercontent.com/700032/151791689-ae570cf5-2959-4b43-ad3c-7eb91ab20e2e.png)

than I'm 100% with you. The column was just the first thing that came to my mind, but being next to the float totally works.

**Comment by baldurk** [comment]
I've added a `,c` watch specifier to show the variables with a colour swatch. You can either add it manually or there's a new context menu entry to change the interpretation of a watch variable between the different typecasts:

![image](https://user-images.githubusercontent.com/661798/152184826-237ff781-fc4c-4ffa-bf98-43d3c94cfd47.png)

**Comment by redorav** [comment]
That actually looks really nice! Is this only available in the watch? Variables will jump between registers so it would be hard to track unless I add all registers to the watch. It would be nice to be able to see them in the variables window, maybe through the context menu as well? What do you think?

**Comment by baldurk** [comment]
Yes I've only added this to the watch. If you want to track a particular variable even as it moves between registers I'd recommend building your shaders with debug information and applying a watch to the local variable itself, then the watch will automatically update.

**Comment by redorav** [comment]
Just for context, often I don't have the debug information (either because I forgot to generate it or because I don't have it handy at the time when I discovered the bug) so that's not necessarily an option for me every time I'm debugging. I can adapt and add the registers for my debug session although it's a bit clumsier than I would like it to be. If that is your final word though, still thanks a ton for the quick turnaround :)
