### ISSUE TITLE
Download speed of update through Renderdoc's update utility is slower than downloads directly from Renderdoc's site

### ISSUE THREAD

**Issue by tbasch** [baldurk/renderdoc#2477]
## Description

Downloading an update through Renderdoc's update utility is much slower than downloading directly from [Renderdoc's site.](https://renderdoc.org/builds)

## Steps to reproduce

1. Run an older version of Renderdoc
2. When Renderdoc shows that an update is available, click Update.

Depending on your geographic location, download speeds may be very slow compared to the speeds you could get obtaining the latest build directly from the web site.  My geographic location is midwestern U.S.

There is no relevant capture.

## Environment

* RenderDoc version: 1.17 to 1.18
* Operating System: Windows 11 x64, Chrome 97.0.4692.99 
* Graphics API: N/A

## Other info

The URL that the updater uses (for version 1.118, 64-bit) is: https://renderdoc.org/stable/1.18/update/RenderDoc_1.18_64.zip

The URL that the web site uses (for version 1.18, 64-bit standalone ZIP) is: https://renderdoc.org/stable/1.18/RenderDoc_1.18_64.zip

Downloading the update URL via Chrome is fast, so this issue is perplexing.

**Comment by baldurk** [comment]
I'm honestly not sure there's much I can do about this. The server side is clearly fine if it works in a browser for you, and geographically you're much closer to the server than I am. The updater also works for me so I don't think there's any fundamental issue with the code, besides which I'm just using Qt's network manager. I could certainly believe there's some delta between a browser optimised for HTTP transfers and whatever network code Qt implements, but I wouldn't expect either to be awful.

My best guess is that there's some system configuration issue which is causing Qt's downloads to go very slowly. Do you have any kind of proxy setup or any other network configuration like that? Are you able to test this on a different machine, or a VM?

You say 'very slow' but can you give exact numbers? How fast does it peak at and is that steady over time? For me it starts at <1MB/s but quickly stabilises at around 2MB/s which is the same as I get in the browser, so less than a minute to download the whole package.

I've compiled the [default Qt downloader example](https://doc.qt.io/qt-5/qtnetwork-download-example.html) and attached it here: [downloader.zip](https://github.com/baldurk/renderdoc/files/7973122/downloader.zip), can you run that on the command line like `download.exe https://renderdoc.org/stable/1.18/update/RenderDoc_1.18_64.zip` and see how long that takes?

**Comment by tbasch** [comment]
Q. Do you have any kind of proxy setup or any other network configuration like that?

A. Nope.  I'm doing this from home, which is just a standard PC -> router -> modem setup, and no fancy network configs for the OS, no proxies or VPN.

Q. Are you able to test this on a different machine, or a VM?

A. Haven't tried that yet.  Will try that.

Q. You say 'very slow' but can you give exact numbers?

A. Roughly 200KB/s.  Download speeds through browser at least 2 MB/s.  I apologize for the omission of specific numbers.

I ran the downloader utility you provided, it finished in about 30 seconds.  I also downloaded 1.17 and tried to update it again, and wouldn't you know, it downloaded at about 4 MB/s.  So, let's just close this.  Sorry for the noise.

**Comment by baldurk** [comment]
Ah I see. It's possible that when you updated and it was slow, the server was overloaded or one of the internet pipes was clogged. Something like that is impossible to diagnose in retrospect and has a decent chance of not being caused by something under my control.

**Comment by tbasch** [comment]
Thank you for the super fast response and helpful assistance!

**Comment by NarutoUA** [comment]
Same bug hunts me for years, it takes ~30 minutes to update regardless of ISP, location, network configuration etc. 
![image](https://github.com/user-attachments/assets/bd21e491-3bbd-4f48-bfa8-00c84eb9e7ba)

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
