### ISSUE TITLE
[OT] Inject a rigged character into an arbitrary 3D game to either act as an enemy or the player

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [baldurk/renderdoc#2478]
Offtopic, but you might be the person to know this:

My goal is to inject a rigged character I made in Blender into an arbitrary 3D game to either act as an enemy or the player itself.

So the goal is for the program to inject itself into any game and replace the character live.

For this it needs an autodetection of bones and an on-screen menu that lets you choose which character should be replaced.

I am looking for keywords to search for, because my own research on google yielded no results.

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
