### ISSUE TITLE
`renderdoccmd extract --list-sections` incorrectly requires `section` & `file` options to be supplied (also `embed` variant)

### ISSUE THREAD

**Issue by follower** [baldurk/renderdoc#2484]
## Description

I wanted to see what possible sections there are in an `.rdc` file.

> _(For completeness: Because I wanted to see if the Vulkan part of a Renderdoc API-initiated capture did actually get stored in a capture file which `qrenderdoc` created as an OpenGL capture due to the "parent" application--I realise this isn't necessarily supported architecture/configuration/functionality but that's a different issue I'm not raising here. :) )_

Executing the command `renderdoccmd extract --list-sections` unexpectedly results in an error message stating: 

```
need option: --file
need option: --section
```

As a workaround, supplying dummy values for `file` & `section` produces reasonable output, e.g.:

```
$ ./bin/renderdoccmd extract --file "" --section "" --list-sections
Known sections:
SectionType(0)
renderdoc/internal/framecapture
renderdoc/internal/resolvedb
renderdoc/ui/bookmarks
renderdoc/ui/notes
renderdoc/ui/resrenames
amd/rgp/profile
renderdoc/internal/exthumb
renderdoc/internal/logfile
renderdoc/ui/edits
renderdoc/internal/d3d12core
renderdoc/internal/d3d12sdklayers
```

## Steps to reproduce

Executing this (with any valid `.rdc` file [*]):

```
./bin/renderdoccmd extract --list-sections /<path>/capture.rdc
```

> [*] _While writing up this issue I realised the `.rdc` capture file isn't actually necessary but the outcome is the same either way._

Produces the following error message instead of the expected output:

```
Errors:
need option: --file
need option: --section

usage: renderdoccmd extract --section=<string> --file=<string> [options ...] <capture.rdc>

options:
  -s, --section          The embedded section name. (string)
  -f, --file             The file to write the section contents to. (string)
  -n, --no-clobber       Don't overwrite the file if it already exists.
      --list-sections    Print a list of known sections.
  -?, --help             print this message
```

This also occurs with the `embed` command variant:

```
./bin/renderdoccmd embed --list-sections /<path>/capture.rdc
```

Which produces this output:

```
Errors:
need option: --file
need option: --section

usage: renderdoccmd embed --section=<string> --file=<string> [options ...] <capture.rdc>

options:
  -s, --section          The embedded section name. (string)
  -f, --file             The file to read the section contents from. (string)
  -n, --no-clobber       Don't overwrite the section if it already exists.
      --lz4              Use LZ4 to compress the data.
      --zstd             Use Zstandard to compress the data.
      --list-sections    Print a list of known sections.
  -?, --help             print this message
```

A workaround is to supply dummy values for the `--file` & `--section` options, e.g. executing this:

```
./bin/renderdoccmd extract --section="dummy" --file="/tmp/foo798.bin" --list-sections /<path>/capture.rdc
```

Produces this seemingly reasonable/expected output:

```
Known sections:
SectionType(0)
renderdoc/internal/framecapture
renderdoc/internal/resolvedb
renderdoc/ui/bookmarks
renderdoc/ui/notes
renderdoc/ui/resrenames
amd/rgp/profile
renderdoc/internal/exthumb
renderdoc/internal/logfile
renderdoc/ui/edits
renderdoc/internal/d3d12core
renderdoc/internal/d3d12sdklayers
```

## Environment

* RenderDoc version: `renderdoccmd x64 v1.18 built from 3996d037b9ec86cde4aa482b7ac4f6aa50068ec4`
* Operating System: `Linux 5.4.0-87-generic x86_64`
* Graphics API: N/A

(via `$ ./bin/renderdoccmd --version`:

```
renderdoccmd x64 v1.18 built from 3996d037b9ec86cde4aa482b7ac4f6aa50068ec4
APIs supported at compile-time: Vulkan, GL, GLES.
Windowing systems supported at compile-time: xlib, XCB, Vulkan KHR_display.
```
)

## Speculation

Based on the `need option` text in the error message, it seems the error is being generated by the `cmdline` "library" here:

https://github.com/baldurk/renderdoc/blob/5f61bf15105ca73f75895623b76af12a8d5ebd32/renderdoccmd/3rdparty/cmdline/cmdline.h#L527-L530

The Renderdoc-specific code seems to suggest the `--list-sections` option is _intended_ to run without the `file` & `section` options, e.g.:

https://github.com/baldurk/renderdoc/blob/3471e64c8f8127567b2aa373328474590b4cea70/renderdoccmd/renderdoccmd.cpp#L1059-L1072

> _[Side note: Oh, actually, and, while re-looking at the code it seems it's intended to run without a `.rdc` file too--which was actually what I expected originally--it's intended as a list of "known sections specified in the format", not "known sections specified in the format that exist in this file", I guess.]_

and:

https://github.com/baldurk/renderdoc/blob/3471e64c8f8127567b2aa373328474590b4cea70/renderdoccmd/renderdoccmd.cpp#L1089-L1095

#### Possible fix

While not exactly the same, I noticed a similar option `--list-formats` for the `convert` command has the other options specified as `optional string`:

```
$ ./bin/renderdoccmd convert --help
usage: renderdoccmd convert [options ...]

options:
  -f, --filename          The file to convert from. (optional string)
  -o, --output            The file to convert to. (optional string)
  -i, --input-format      The format of the input file. (optional string) Options are:
                            * rdc - Native RDC capture file format.
                            * zip.xml - XML+ZIP capture
  -c, --convert-format    The format of the output file. (optional string) Options are:
                            * rdc - Native RDC capture file format.
                            * chrome.json - Chrome profiler JSON
                            * xml - XML capture
                            * zip.xml - XML+ZIP capture
      --list-formats      Print a list of target formats.
  -?, --help              print this message

```

As specified here:

https://github.com/baldurk/renderdoc/blob/3471e64c8f8127567b2aa373328474590b4cea70/renderdoccmd/renderdoccmd.cpp#L691-L698

So perhaps the same needs to be done for `embed`/`extract` here:

https://github.com/baldurk/renderdoc/blob/3471e64c8f8127567b2aa373328474590b4cea70/renderdoccmd/renderdoccmd.cpp#L1033-L1046

### Thanks!

Thanks for your work on Renderdoc!

(I used Renderdoc to verify a Vulkan Compute shader was *actually* being executed by my Vulkan Compute shader add-on for (OpenGL-only) Godot 3 (<https://rancidbacon.itch.io/godot-3-vulkan-compute-addon>) by viewing the debug printf output.

And *then* discovered I could even use Renderdoc to view the `debugPrintfEXT()` output even on a computer whose Vulkan GPU driver didn't support the required Vulkan `SPV_KHR_non_semantic_info`/`VK_KHR_shader_non_semantic_info` extension, which was even more helpful. :D ) 

> _(Also, BTW I appreciate & wanted to acknowledge the care & work you've clearly put into the amount of detail you provide regarding issue/PR creation while also being clear that a new-comer isn't expected to read it all & that you're open to helping first time committers through the process._
> 
> _I think explicitly stating that context is likely to go a long way to creating a more welcoming & inclusive environment for potential new contributors to what could otherwise seem like quite an intimidating project to which to make a first-time contribution due to its highly specialized/niche knowledge nature. :) )_

Thanks!

**Comment by baldurk** [comment]
`renderdoccmd` is an internal tool only, and should not be run directly by users. For this reason it is not documented or directly supported.
