### ISSUE TITLE
Secondary vulkan windows won't be captured when simultaneously present their swapchain.

### ISSUE THREAD

**Issue by holyodin776** [baldurk/renderdoc#2492]
## Description

When calling ‘vkQueuePresentKHR ‘ with multiple swapchains，RenderDoc would only captrue the first one. Both press F11 and manually click the ‘cycle active window’ button won't actually activate those window except for the first one. RenderDoc's overlay fonts are also missing from those windows.
However calling 'vkQueuePresentKHR' for each  swapchain separately works fine.

## Steps to reproduce

Filling multiple swapchains in the 'pSwapchains' member of 'VkPresentInfoKHR' and calling vkQueuePresentKHR once.

## Environment

RenderDoc version: v1.18
Operating System: Windows10 pro
Graphics API: Vulkan 1.2.141.2
GPU: NVIDIA GTX 2080, driver 511.23

**Comment by baldurk** [comment]
That commit should add support for batched presentation, by splitting up and iterating over the array in the info structure.
