### ISSUE TITLE
API (OpenGL) is active but cannot capture frame

### ISSUE THREAD

**Issue by SamLeungguy** [baldurk/renderdoc#2498]
## Description

After running my application, I found that the Capture Frame button is not working as expected. 
Pressing it does not capture any frames.
And there is no message (OpenGL. F12, PrtScrn to capture. Frame: .....) on the top-left corner of my application

The photo below is another application with Renderdoc that works as expected.
![image](https://user-images.githubusercontent.com/47981405/154191635-a6cf2f85-132b-46c2-b65f-fd567ff536af.png)

## Steps to reproduce

I cannot share my application since it is my school project right now.
as the below image shows, the API is active however it cannot capture frame.
![image](https://user-images.githubusercontent.com/47981405/154192381-10fa12e6-47da-4f83-bd58-9e1933d528fb.png)

here is the log from Renderdoc
[renderdoc_failed_to_capture.log](https://github.com/baldurk/renderdoc/files/8076600/renderdoc_failed_to_capture.log)

PS: sorry for the poor English

## Environment

* RenderDoc version: 1.18
* Operating System: windows10
* Graphics API: OpenGL
* GPU: AMD Radeon RX 5600 XT

**Comment by baldurk** [comment]
Without a way to reproduce this there's no way I can investigate what is happening. Are you able to find a demo program which reproduces this problem for you? or either cut down your program sufficiently that you can share it, or find a way to modify a demo program to be close enough to your program to exhibit the problem?

To clarify if you're concerned about sharing the source code for your school project, a binary-only repro case is fine.

**Comment by SamLeungguy** [comment]
Hello, thank you for replying! I have sent a basic version of my project which can reproduce the problem through email.

**Comment by baldurk** [comment]
Thanks for sharing it. The problem is that you use `wglMakeContextCurrentARB` which it seems I'd never encountered an OpenGL program using before, possibly because it's rare to need separate read and draw DCs. That commit adds support, and with that RenderDoc properly tracks the contexts, which was the problem you were seeing.

**Comment by SamLeungguy** [comment]
Thank you for your time. It works now!
