### ISSUE TITLE
Missing support for GLFW Vulkan presentation on Linux

### ISSUE THREAD

**Issue by sloder75** [baldurk/renderdoc#2501]
## Description

Expected behavior: RenderDoc properly launches the application and is ready to capture.
Observed behavior: Application closes instantly due to code checking for missing requirements.

I'm developing a hobby project in Vulkan and use GLFW to handle the windows and surfaces. Previosuly I used to do it on Windows 10 where I have successfully used RenderDoc to debug problems. Some time ago I switched over to Pop!_OS, and have not been able to get my project to run from within RendeDoc. After digging around trying to locate the issue, I managed to isolate it to the GLFW function call [glfwGetPhysicalDevicePresentationSupport](https://www.glfw.org/docs/latest/vulkan_guide.html#vulkan_present). When i run my project directly, a window is created and rendering begins, but when launched from within RenderDoc, the check for physical device's support for presentation fails. 

Here's a small excerpt from debug prints i inserted into my code:
```
Queue families: 3
Has required bits: 1, Supports presentation: 0
Has required bits: 0, Supports presentation: 0
Has required bits: 0, Supports presentation: 0
Evaluated device: NVIDIA GeForce RTX 3060 Ti, score: 0
```
For a device to be accepted, both of those have to return true, but in this case the aforementioned function call returns false.

As a comparison, here are the same prints when the project is launched directly and everything works:
```
Queue families: 3
Has required bits: 1, Supports presentation: 1
Evaluated device: NVIDIA GeForce RTX 3060 Ti, score: 101
```
(there's less lines since the first queue family is accepted after both checks pass)

I've read somewhere that RenderDoc seems to somehow proxy the physical devices (mainly that it provides only one really useful queue) so I believe the lack of presentation support is a bug in either RenderDoc or a weird interaction between RenderDoc and GLFW on Linux.

Just in case it becomes relevant, I also include the Diagnostic Log:
```
RDOC 167154: [01:51:18]             core.cpp( 437) - Log     - RenderDoc v1.11 Linux 64-bit Release (NO_GIT_COMMIT_HASH_DEFINED) loaded in replay application
RDOC 167154: [01:51:18]             core.cpp( 443) - Log     - Packaged for Ubuntu (1.11+dfsg-5) - https://salsa.debian.org/xorg-team/app/renderdoc
RDOC 167154: [01:51:18]         settings.cpp( 460) - Log     - Loading config from /home/<user>/.renderdoc/renderdoc.conf
QTRD 167154: [01:51:18]              unknown(   0) - Log     - QRenderDoc initialising.
RDOC 167154: [01:51:18]        vk_replay.cpp(4235) - Log     - Created device.
RDOC 167154: [01:51:18]    android_tools.cpp( 354) - Log     - Initialising adb using 'adb'
RDOC 167154: [01:51:18]    android_tools.cpp( 359) - Warning - Couldn't locate adb. Ensure adb is in PATH, ANDROID_SDK or ANDROID_HOME is set, or you configure your SDK location
QTRD 167154: [01:51:18]              unknown(   0) - Warning - area parameter ignored for this type
RDOC 167154: [02:15:15]    posix_process.cpp( 831) - Log     - Running process /home/<user>/Documents/Projects/cpp/<project>/build/VulkanRenderer for injection
RDOC 168578: [02:15:15]             core.cpp( 437) - Log     - RenderDoc v1.11 Linux 64-bit Release (NO_GIT_COMMIT_HASH_DEFINED) capturing application
RDOC 168578: [02:15:15]             core.cpp( 443) - Log     - Packaged for Ubuntu (1.11+dfsg-5) - https://salsa.debian.org/xorg-team/app/renderdoc
RDOC 168578: [02:15:15]         settings.cpp( 460) - Log     - Loading config from /home/<user>/.renderdoc/renderdoc.conf
RDOC 168578: [02:15:15]   posix_libentry.cpp(  56) - Log     - Using delay for debugger 0
RDOC 168578: [02:15:15]   posix_libentry.cpp(  69) - Log     - Loading into /home/<user>/Documents/Projects/cpp/<project>/build/VulkanRenderer
RDOC 168578: [02:15:15]         gl_hooks.cpp( 263) - Log     - Registering OpenGL hooks
RDOC 168578: [02:15:15]        glx_hooks.cpp( 725) - Log     - Registering GLX hooks
RDOC 168578: [02:15:15]        egl_hooks.cpp( 992) - Log     - Registering EGL hooks
RDOC 168578: [02:15:15]         vk_layer.cpp(  99) - Log     - Registering Vulkan hooks
RDOC 167154: [02:15:15]   target_control.cpp( 585) - Log     - Got remote handshake: VulkanRenderer [168578]
RDOC 168578: [02:15:15]          vk_core.cpp(1319) - Warning - Spec versions of VK_EXT_debug_report are different between supported extension (9) and reported (10)!
RDOC 168578: [02:15:15]          vk_core.cpp(1319) - Warning - Spec versions of VK_EXT_debug_report are different between supported extension (9) and reported (10)!
RDOC 168578: [02:15:15]          vk_core.cpp(1319) - Warning - Spec versions of VK_EXT_debug_report are different between supported extension (9) and reported (10)!
RDOC 168578: [02:15:15]          vk_core.cpp(1319) - Warning - Spec versions of VK_EXT_debug_report are different between supported extension (9) and reported (10)!
RDOC 168578: [02:15:15]          vk_core.cpp(1319) - Warning - Spec versions of VK_EXT_debug_report are different between supported extension (9) and reported (10)!
RDOC 168578: [02:15:15]          vk_core.cpp(1319) - Warning - Spec versions of VK_EXT_debug_report are different between supported extension (9) and reported (10)!
RDOC 168578: [02:15:15]             core.cpp(1798) - Log     - Adding Vulkan device frame capturer for 0x0000000000718F70
RDOC 168578: [02:15:15]  vk_device_funcs.cpp( 814) - Log     - Initialised capture layer in Vulkan instance.
RDOC 168578: [02:15:15]  vk_device_funcs.cpp(1427) - Log     - physical device 0: NVIDIA GeForce RTX 3060 Ti (ver 470.86 patch 0x0) - 10de:2489
RDOC 168578: [02:15:15]  vk_device_funcs.cpp(1427) - Log     - physical device 1: llvmpipe (LLVM 12.0.1, 256 bits) (ver 0.0 patch 0x1) - 10005:0000
RDOC 168578: [02:15:15]             core.cpp(1814) - Log     - Removing device frame capturer for 0x0000000000718F70
```

## Environment

* RenderDoc version: 1.11+dfsg-5 (latest available through ubuntu apt)
* Operating System: Pop!_OS 21.10
* Graphics API: Vulkan 1.2.182
* GLFW version: 3.3.3
* GPU: RTX 3060 Ti
* GPU Driver: 470.57.01
* Compiler: Clang 13.0.0

**Comment by sloder75** [comment]
Quick update: i went ahead and installed RenderDoc 1.18 directly from the tarball and the issue still persists.

**Comment by baldurk** [comment]
Please continue testing with an up to date version like v1.18, as v1.11 is very out of date being a year and a half old and may have problems which have been fixed and obscure the real issue. Note that RenderDoc doesn't have anything to do with library toolkits like GLFW, it only works at the graphics API level, so any issue would be with functions from the graphics API itself.

Since you are on linux, please ensure that you're not using Wayland as this is not currently supported. I don't know how that works with glfw whether you need to select which system to use or if glfw will automatically try both wayland and X11, you would need to consult your library's documentation.

Finally since this is a bug report and you should have selected the bug report template when creating an issue, please provide steps to reproduce the problem: E.g. share your program, or a public demo/example/tutorial that shows the problem, or whatever is most convenient for you to share but does reproduce the problem on your system.

**Comment by sloder75** [comment]
Here's a small demo that replicates my issue. I can also confirm that X11 is being used, not Wayland.

[test.zip](https://github.com/baldurk/renderdoc/files/8090929/test.zip)

**Comment by baldurk** [comment]
I tried to reproduce using this program but it works as expected for me (according to what I believe it should do). Looking at the output to stdout via the console that launched qrenderdoc shows that it found a presentable queue family:

```
$ ./bin/qrenderdoc 
Number of devices to evaluate: 2
Queue families: 1
Has required bits: 1, Supports presentation: 1
Evaluated device: llvmpipe (LLVM 12.0.1, 256 bits), Supports presentation: 1
Queue families: 3
Has required bits: 1, Supports presentation: 1
Evaluated device: NVIDIA GeForce RTX 2080 Ti, Supports presentation: 1
```

(Similar output when testing on AMD but with a different GPU and number of queue families).

I would guess then that this may be caused by interference from a layer on your system. I'd recommend running vulkaninfo and checking to see which layers are available, and temporarily disable any other than the RenderDoc layer. You could also try running with `VK_LOADER_DEBUG=all` before launching qrenderdoc and checking the output to see which layers are being loaded.

It's also possible (though I think very unlikely) that a slight difference in glfw versions is the problem. I didn't easily see how to build the repro with the included cmake file as it referenced a program that wasn't in my package manager, so since it was only one file I built it straight with clang against my system glfw, which in this case is version 3.3.2. If you're using a different version you could try compiling against exactly 3.3.2 - in which case it may be a regression on glfw.

**Comment by sloder75** [comment]
I've run qrenderdoc in a terminal with `VK_LOADER_DEBUG=all` and as far as i can tell, RenderDoc's layers are indeed the only ones active. By your suggestion I also tried compiling my project with GLFW 3.3.2 instead, and it had no effect. I even tried with the newest version, 3.3.6, but no dice. I started digging a little further and found a neat little [error reporting function](https://www.glfw.org/docs/latest/intro_guide.html#error_handling) in GLFW. That produced a result in the form of this message: `error: 65542, description: X11: Vulkan instance missing VK_KHR_xcb_surface extension`. I thought it weird, since GLFW comes with a function that returns all of its requirements and I was passing them inside the instance create info. I tried printing them to the console too and true enough:
```
Required extensions:
VK_KHR_surface
VK_KHR_xcb_surface
```
Right away I went to inspect the create info in the debugger but as far as i can tell it isn't malformed in any way. I'm still looking into why the extension doesn't become enabled but wanted to post the update in case you could have an idea why it's happening.

**Comment by baldurk** [comment]
Looks like that error comes [if glfw can't find vkGetPhysicalDeviceXcbPresentationSupportKHR](https://github.com/glfw/glfw/blob/df8d7bc892937a8b0f7c604c92a9f64f383cf48c/src/x11_window.c#L3121-L3122), but I'm not sure why that would be.

What version of the vulkan loader (libvulkan.so) do you have?

**Comment by sloder75** [comment]
It should be 1.2.182. I installed the SDK using the instructions for ubuntu packages on LunarG's [website](https://vulkan.lunarg.com/sdk/home#linux).

**Comment by baldurk** [comment]
Typically the SDK does not install the system vulkan libraries, it just provides development files like headers, validation layers, shader compilers etc. Please double check what version of the loader is actually being used by your program and renderdoc, and what version it is.

**Comment by sloder75** [comment]
Running vulkaninfo reports the loader version as 1.2.182. Interesting enough, the GPU driver reports as 1.2.175, though I imagine nothing breaks because i'm not using any advanced capabilities of vulkan. None of that is important though because it seems you hit the bullseye with the loader idea. I had one version of the loader installed together with the driver, but my project was actually using a different loader i was getting off conan as a dependency. I changed it around to depend on vulkan-headers instead of vulkan-loader and after a recompile RenderDoc no longer has a problem with my application. My guess would be that somehow i was using two different loaders at once and that was causing the discrepancies in used instance extensions. Many thanks, i'm still rather fresh to vulkan and probably wouldn't have been able to resolve this without your help :)
