### ISSUE TITLE
Freeze when inspecting glMultiDrawElementsIndirect

### ISSUE THREAD

**Issue by Oribow** [baldurk/renderdoc#2505]
## Description

I've created a capture of my application and opening the second multidrawcall causes RenderDoc to freeze.
The application renders correctly, aside from some messed up uvs.

## Steps to reproduce

1. Load this capture: [endless_loading.zip](https://github.com/baldurk/renderdoc/files/8104036/endless_loading.zip)
2. Try to open the second glMultiDrawElementsIndirect in the Colour Pass 1
3. RenderDoc should freeze now

## Environment

* RenderDoc version: 1.18
* Operating System: Windows 10
* Graphics API: OpenGL

**Comment by Oribow** [comment]
Here is a capture that is even simpler then the initially provided. Only 1 multidrawindirect call and the capture is only 140kb large.
[endless_loading2.zip](https://github.com/baldurk/renderdoc/files/8112112/endless_loading2.zip)

**Comment by baldurk** [comment]
Both of these captures have shaders declaring and using ARB_bindless_texture, which is not supported by RenderDoc. A basic rule in OpenGL is your code **must check for extensions** before using them by checking extension strings with `glGetStringi(GL_EXTENSIONS, 0..n)`. When running under RenderDoc only supported extensions will be reported.

Does this reproduce for you if you're not using ARB_bindless_texture?

**Comment by Oribow** [comment]
Damn, that was it. If I remove the usage of bindless textures it all works again. 
Thanks to your hint I found this issue: https://github.com/baldurk/renderdoc/issues/850 where you explain why it isn't support. Also found a recent similar question on reddit: https://www.reddit.com/r/opengl/comments/sszn3f/why_does_using_extension_gl_arb_bindless_texture/

I just wish renderdoc could give a hint when unsupported extensions are used instead of freezing.

**Comment by baldurk** [comment]
As I say above it's not RenderDoc's responsibility to warn on invalid extension use. A correctly written OpenGL application **must** check that extensions are reported as supported before using them. If it does so, it will find for itself that some extensions are not supported by RenderDoc and either have a fallback path or exit gracefully.

If an application continues to use unsupported extension functionality even after it's reported as unsupported then it will misbehave in RenderDoc and it will likely misbehave or even crash when run on a driver or GPU that doesn't support that extension.

**Comment by Oribow** [comment]
Okay, makes sense. Just for my personal understanding though, if renderdoc restrict the available extensions shouldn't this line have caused shader compilation to fail?
`#extension GL_ARB_bindless_texture : require`

I thought it would throw an error when the extension doesn't exist.
Any way thanks for all the help and your awesome tool! It really helped me learn and fix my mistakes. Without it I'd thrown my keyboard out of the window long ago.

**Comment by baldurk** [comment]
No, shader compilation still happens in the driver. If the extension were shader only that may work by coincidence (though it is still not supported), but for example in the case of ARB_bindless_texture it's impossible to actually use it without calling `glGetTextureHandleARB` at minimum to get the handle for a texture. That is a case where your code must check for the extension to be available before calling it - indeed most reliable extension loader libraries will do this for you and the function pointer will be NULL if the extension is not supported.
