### ISSUE TITLE
VC 2015 Compiler warning since 01a17281a971472a41b7e398f4db9f1ded178eb0

### ISSUE THREAD

**Issue by TiemoJung** [baldurk/renderdoc#252]
Hi,

with commit 01a17281a971472a41b7e398f4db9f1ded178eb0 you introduced new vc 2015 compiler warnings.

driver/vulkan/vk_debug.cpp:1159 `VkSampleCountFlagBits msaa[] = { VK_SAMPLE_COUNT_1_BIT, VK_SAMPLE_COUNT_1_BIT, VK_SAMPLE_COUNT_1_BIT, VK_SAMPLE_COUNT_2_BIT };`

hides `VkPipelineMultisampleStateCreateInfo msaa = { ...` in line 867.

**Comment by baldurk** [comment]
Thanks for letting me know!
