### ISSUE TITLE
Incorrect D3D11 sampler addressing listed for unbound samplers

### ISSUE THREAD

**Issue by epicabsol** [baldurk/renderdoc#2520]
## Description

In RenderDoc v1.18, Direct3D11 unbound samplers list their addressing mode as `UVW: Wrap` when really the default behavior is clamp. (Docs: https://docs.microsoft.com/en-us/windows/win32/api/d3d11/ns-d3d11-d3d11_sampler_desc#remarks)

## Steps to reproduce

 - Open a capture with a D3D11 draw where the pixel shader uses a sampler that is not bound. (See attached capture)
 - Select the draw in RenderDoc (EID 19 in attached capture), open the Pipeline State tab, and click the Pixel Shader section.
 - In the Samplers category, the sampler that has no sampler resource bound shows the text `UVW: Wrap` in the Addressing column when it should indicate clamping instead.
 - Open the Texture Viewer tab for the draw to verify that the texture coordinates are actually being clamped, in accordance with the D3D11 docs on the default sampler state.

In addition, creating and binding a sampler with the addressing set to Wrap results in the expected wrapping, confirming that the default sampler values are responsible for the clamping.

Capture: 
[clamp_issue_repro.zip](https://github.com/baldurk/renderdoc/files/8252588/clamp_issue_repro.zip)

## Environment

* RenderDoc version: 1.18
* Operating System: Windows 11 21H2 (Build 22000.556)
* Graphics API: Direct3D11
* GPU: RTX 3070 Ti (Drivers: v30.0.15.1123)

**Comment by epicabsol** [comment]
It looks like the LOD Clamp and Filter columns for unbound samplers also might not be matching the defaults listed in the docs.

**Comment by baldurk** [comment]
Thanks for the clear repro case. This would have had whatever sampler parameters were last bound in that slot (or whatever values correspond to 0 enums if not, as you saw). I had implemented default value setting for the state objects which could be NULL, but not for samplers. That commit should fix the problem.
