### ISSUE TITLE
Vertex attributes not updating in Mesh Viewer after vkCmdSetVertexInputEXT calls

### ISSUE THREAD

**Issue by ameerj** [baldurk/renderdoc#2527]
## Description

Renderdoc does not take into account vertex attributes updated via `vkCmdSetVertexInputEXT`.
The Pipeline state and Mesh Viewer seem to continue using the attribute data found in the graphics pipeline create info instead.

This causes the VS Input and the VS In/VS Out mesh renders to display in the format specified by the pipeline, rather than what was updated by `vkCmdSetVertexInputEXT`.

Non-Dynamic Vertex Input |  Dynamic Vertex Input
:-------------------------:|:-------------------------: 
![es2_gears](https://user-images.githubusercontent.com/52414509/159208216-a0bcf9ee-66ff-4b57-990f-0f5bdb652416.png) | ![es2_gears_dynamic_vertex_input](https://user-images.githubusercontent.com/52414509/159208229-18910560-066b-4a0c-9138-8cfa9be33a55.png)

## Steps to reproduce

This was detected in yuzu Emulator. The following captures are of the [open-sourced es2gears homebrew port](https://github.com/switchbrew/switch-examples/tree/master/graphics/opengl/es2gears) running in-emulator.

[RenderDoc es2gears Vertex Input Captures](https://github.com/baldurk/renderdoc/files/8313269/renderdoc_vertex_input.zip)

`es2_gears.rdc` shows the correct values for the vertex attributes, as it does not use `vkCmdSetVertexInputEXT`

`es2_gears_dynamic_vertex_input.rdc` makes use of `vkCmdSetVertexInputEXT`, and has the incorrect format for the vertex attributes, and subsequently incorrect mesh viewer renders of the geometry. This capture is instead expected to present the same information as the previous capture.

## Environment

* RenderDoc version: RenderDoc_2022_03_20_7a29e6a6_64
* Operating System: Windows 10
* Graphics API: Vulkan
* Graphics Device: RTX 3070
* Driver Version: 511.79

**Comment by baldurk** [comment]
Thank you for the clear repro case. Looks like a few bits of code hadn't properly been updated to pull the vertex input from dynamic state tracking (which is filled out from the pipeline when the dynamic extension isn't used). That commit updates it and should handle those cases properly.

**Comment by ameerj** [comment]
Thank you for very promptly looking into this! I've pulled down the source and can confirm it working as intended now.
