### ISSUE TITLE
PIXBeginEvent colors

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#2537]
## Description

I'm trying to get marker colors in D3D12 so they work the same way as the Vulkan colors I already have set up. I am using the WinPixEventRuntime library as is recommended for D3D12 these days and the code looks roughly like this:

```cpp
void CrCommandBufferD3D12::BeginDebugEventPS(const char* eventName, const float4& color)
{
	BYTE r = (BYTE)(color.r * 255);
	BYTE g = (BYTE)(color.g * 255);
	BYTE b = (BYTE)(color.b * 255);

	wchar_t wEventName[256];
	mbstowcs(wEventName, eventName, sizeof_array(wEventName));
	PIXBeginEvent(m_d3d12GraphicsCommandList, PIX_COLOR(r, g, b), wEventName);
}
```

The markers appear correctly in RenderDoc and everything seems to work fine, except for the colors. Is this still possible in D3D12? I remember having colors in D3D11 in the past, but the API for it was different.

## Environment

* RenderDoc version: 1.19
* Operating System: Windows 11
* Graphics API: D3D12

**Comment by baldurk** [comment]
Normally I advise against the weird and over-engineered PIXEvent style markers, but it seems in D3D12 that is indeed the only way to get colours on markers. That commit should add support for them, as it was just being skipped over in the decode step so was easily available. This will require captures to be re-created as the color was not being serialised before.

**Comment by redorav** [comment]
Amazing, thanks a ton. No worries about the captures, they are normally short-lived for now while I get things up and running.
