### ISSUE TITLE
Crashing with Segmentation Fault SIGSEGV while running renderdoccmd on our target_machine[remote server]

### ISSUE THREAD

**Issue by dkjiban** [baldurk/renderdoc#2539]
## Description

We are trying to run RenderDoc on Tizen based Linux Platform.
RenderDoc is crashing with Segmentation Fault SIGSEGV. 

We tried to debugged it by putting a break point in the main function.
It's not even hitting the main function.

Starting program: /usr/local/bin/renderdoccmd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x42debc36 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned int, unsigned int, char const*, unsigned int) () from /lib/libstdc++.so.6

## Steps to reproduce

1. Disable flags in CMakeLists.txt
	a. GL driver
	b. GL ES driver
	c. qrenderdoc
	d. xlib windowing support
	e. xcb windowing support
	
2. Build with vbs build. 
vbs build -A armv7l --include-all

3. Generated below three files we copied to target.
	renderdoccmd /usr/local/bin/
	librenderdoc.so /usr/local/lib/
	renderdoc_capture.json /etc/vulkan/implicit_layer.d/
	
4. export HOME=/
renderdoccmd vulkanregister --system
renderdoccmd remoteserver &

After running above command Segmentation fault

## Environment

* RenderDoc version: v1.18 and v1.1 both we checked
* Operating System: ARM CPU Linux 32 bit
* Graphics API: Vulkan

**Comment by baldurk** [comment]
ARM linux is not a supported platform. Only x86-64 is supported on linux.

**Comment by dkjiban** [comment]
Is there any specific reason for not supporting ARM Linux Platform ?
Do you have any plan in the near future to support this on the ARM Linux Platform ?

**Comment by baldurk** [comment]
Linux already has challenges with the amount of variation present between different distributions and configurations that exist, so increasing the support burden to support different architectures with further variation doesn't make sense for the small minority of a minority of users that would benefit. Particularly when I would have no way of reproducing or investigating any issues that are ARM specific.

I will still of course investigate any issues that are generally applicable to linux and can be reproduced on 64-bit x86, and if anyone wants to contribute fixes for ARM or 32-bit x86 or anything that is welcome as long as it's not going to add significant bugs/cost to the supported path.
