### ISSUE TITLE
Add "Expand All" option to tree control nodes

### ISSUE THREAD

**Issue by jshofmann** [baldurk/renderdoc#254]
A nice convenience to add to the Event Browser would be an "Expand All" option to the "+" controls in the Event Browser's tree control, perhaps bound to the right-click. This command would expand the selected node and all child nodes, and reduce the amount of clicks necessary to navigate a nested frame capture hierarchy. Not a high priority item, but a convenience that should hopefully be easy to add.

**Comment by baldurk** [comment]
That was a nice easy one :grinning:. Should do the trick, I added "Collapse All" while I was at it, since that might also be useful for cleaning up when you've looked for one draw and want to find another in a different part of the frame.

**Comment by baldurk** [comment]
Closing this issue as the feature is implemented in [v0.30](https://github.com/baldurk/renderdoc/releases/tag/v0.30). Feel free to re-open if it's not as you expect!

**Comment by jshofmann** [comment]
Can we get the "Expand All" and "Collapse All" commands added to the Controls toolbar in the Event Browser as well? (RenderDoc 1.6 for Windows 10, Vulkan and DirectX 11 APIs, but that's not relevant to this feature.) Thanks!

**Comment by baldurk** [comment]
Please don't comment on resolved issues that are over 3 years old with separate requests or follow-ups, open a new issue to discuss it.

In this case I'll save going around that loop. I don't want to add those commands to the toolbar as I don't think there's much value to be gained vs the additional clutter in the UI. Having them available on a right click context menu is enough, and a typical UI pattern.
