### ISSUE TITLE
Self-built v1.19 Windows, cannot open captures

### ISSUE THREAD

**Issue by AndyCGYan** [baldurk/renderdoc#2548]
## Description

Cannot open captures on a self-built copy from the [v1.19](https://github.com/baldurk/renderdoc/tree/v1.19) tree.

## Steps to reproduce

- Confirm that official v1.19 works on the target Android device, both capturing and opening said capture
- Clone and checkout v1.19 source
- Build for Windows with Visual Studio 2022 + Build Tools 2015 (no retargeting or change to code whatsoever)
- Build for Android with Ubuntu, OR just use the apks from official v1.19 (commit ID matches)
- With the built copy, capture then open - observe that it errors out as below:

![11](https://user-images.githubusercontent.com/18655204/163552815-b91bc744-501a-4534-b40a-3a9d2ee59b84.png)

Notably:

- Diagnostic Log shows that Core was "creating a D3D11 replay device", which shouldn't happen with a GLES capture
- Save the capture from the self-built version, and it can be opened normally from official

## Environment

* RenderDoc version: v1.19 (eb1e625)
* Operating System: Windows 10
* Graphics API: OpenGLES

**Comment by AndyCGYan** [comment]
Side note: I also encountered https://github.com/baldurk/renderdoc/issues/1616 and chmodding the r14b NDK isn't enough. I moved to r23b (keeping all other dependencies the same) and it built just fine.

**Comment by baldurk** [comment]
Can you please share the entire diagnostic log? As the error mentions this could be caused by a few different issues, so I would need to see the log to understand more. I don't know what you mean that creating a D3D11 replay device "shouldn't happen with a GLES capture".

The CI currently builds android using the v14 NDK, though only on linux not on windows. Unfortunately Android is a terrible platform and the development tools often break in unpredictable ways so it's not possible to diagnose all possible failures like this on Android, if you got it working somehow then that's the main thing.

**Comment by AndyCGYan** [comment]
Captured an opensource debuggable app so that I can upload the log publicly - [jmini3d.android.demo.log](https://github.com/baldurk/renderdoc/files/8495342/jmini3d.android.demo.log)

> I don't know what you mean that creating a D3D11 replay device "shouldn't happen with a GLES capture"

I'm attempting to open the capture with the device connected, so it should open on-device, and Android certainly doesn't do D3D11 (does it?)

> The CI currently builds android using the v14 NDK, though only on linux not on windows

Even on Ubuntu (both full VM and Docker) I wasn't able to get r14b working after a day of headbanging. With another NDK version, as long as it builds, it should be functionally identical?

**Comment by baldurk** [comment]
D3D11 isn't used on the android device, but it is used on the PC side to transfer and render the contents of the capture.

It looks like you've built a development build of RenderDoc but you don't have the D3D11 debug layers installed. Assuming you're on windows 10 this requires [some manual steps to configure](https://docs.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-devices-layers#debug-layer), but the simplest solution is to build a release build of RenderDoc which will not require them by default.

And yes using a new SDK _should_ be identical, though with Android it wouldn't surprise me if new SDKs broke in some way. Either way it doesn't seem to be related to this issue.

**Comment by AndyCGYan** [comment]
Confirm, installing the Graphics Tools FoD got it working. Installing that itself is a pain though, our environment prevents unaudited Windows updates, and MS doesn't provide offline packages. Either way, thanks for the help.
