### ISSUE TITLE
Application crash to desktop only when runnig through renderdoc

### ISSUE THREAD

**Issue by Avokadoen** [baldurk/renderdoc#2549]
## Description

Running developed vulkan application crashes in a specific environment (linux + amd), but works if running stand alone and/or on windows + nvidia with renderdoc. The application expect max images returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR to be atleast 1, but it is 0 given the specific environment.

* vkGetPhysicalDeviceSurfaceCapabilitiesKHR capabilities without renderdoc:  ``vkSurfaceCapabilitiesKHR{ .min_image_count = 2, .max_image_count = 16, ...``
* vkGetPhysicalDeviceSurfaceCapabilitiesKHR capabilities with renderdoc:  ``vkSurfaceCapabilitiesKHR{ .min_image_count = 3, .max_image_count = 0, ...``

## Steps to reproduce
 - *Make sure to have similar environment* 
 - git clone https://github.com/Avokadoen/zig_vulkan with its submodules i.e: ``git clone --recurse-submodules -j4 git@github.com:Avokadoen/zig_vulkan.git``
 - download the zig *master branch* compiler from here: https://ziglang.org/download/
 - run ``zig build`` to build debug, or ``zig build -Drelease-safe`` for a release binary (either triggers bug)
 - launch binary from renderdoc (binary is by default in ``projectdir/zig-out/bin/zig_vulkan``)

## Environment

* RenderDoc version: QRenderDoc v1.19 (eb1e625b96bb2e9d43df4f8a2245438b29524721)
* Operating System: Ubuntu 20.04
* Graphics API: Vulkan SDK 1.3, application target 1.2
* GPU: AMD RX 6800xt
* lshw output: 
``
*-display                 
       description: VGA compatible controller
       product: Advanced Micro Devices, Inc. [AMD/ATI]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:03:00.0
       version: c1
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:138 memory:c0000000-cfffffff memory:d0000000-d01fffff ioport:e000(size=256) memory:dfa00000-dfafffff memory:c0000-dffff
``

**Comment by Avokadoen** [comment]
Reading vulkan documentation and it seems like my application is misbehaving as the following is stated:
``
maxImageCount is the maximum number of images the specified device supports for a swapchain created for the surface, and will be either 0, or greater than or equal to minImageCount. A value of 0 means that there is no limit on the number of images, though there may be limits related to the total amount of memory used by presentable images.
``

I'll let @baldurk close this issue in case there is a bug that causes vulkan to return something else on vkGetPhysicalDeviceSurfaceCapabilitiesKHR using renderdoc

**Comment by baldurk** [comment]
What window system are you using? RenderDoc only supports X11 so if you are using wayland (or optionally wayland or X11) then the availability of extensions may change when under RenderDoc since wayland is not supported.

As you say, this is valid to be returned so your code should handle it. RenderDoc doesn't change this value deliberately but it could vary depending on extension or feature use.

**Comment by Avokadoen** [comment]
patching the application so it runs now. While running the application through renderdoc the output is corrupted:
![image](https://user-images.githubusercontent.com/26302304/163597120-3be5d6a2-40e2-4815-8383-8af5c8216878.png)

Even when launching the application directly while renderdoc is running in the background the output is corrupted. If i close renderdoc the output becomes as expected
![image](https://user-images.githubusercontent.com/26302304/163597275-359de768-1f6a-491a-aa22-869167c6a2f7.png)

**Comment by Avokadoen** [comment]
> What window system are you using? 

According to ubuntu about page i'm running x11 as configured

**Comment by Avokadoen** [comment]
Discard my comment about corrupted image while using renderdoc, pretty sure that's a bug on my end (maybe) :skull:

**Comment by Avokadoen** [comment]
Noticed just now that the VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT is also set to false in the vkSurfaceCapabilitiesKHR.supportedUsageFlags
