### ISSUE TITLE
Renderdoc closes when debugging a pixel with Vulkan

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2550]
## Description

Renderdoc exits when debugging a pixel with Dolphin's Vulkan backend (tested with Dolphin 5.0-16101).  Debugging the pixel successfully opens a new tab with the shader disassembly, but renderdoc freezes and then closes a few seconds afterwards.  No crash window appears.  This seems to happen only on regular draws; draws related to framebuffer copies are not affected.  (It may be that `vkCmdDrawIndexed` is broken and `vkCmdDraw` works, but I'm not 100% sure of this.)

<details><summary>Old info</summary>

Renderdoc crashes when debugging a pixel with Dolphin running a specific hardware test I am working on.  This only happens with this specific hardware test, and only with a specific EID, and only with debugging a pixel; viewing the pixel shader works properly, as does debugging a vertex with the same EID, as does debugging a pixel earlier on.  The test case itself is a bit broken currently so it's likely that this is hitting some kind of edge case due to my own mistake, but renderdoc should still handle this more gracefully.  Debugging the pixel successfully opens a new tab with the shader disassembly, but renderdoc freezes and then closes a few seconds afterwards.  No crash window appears, either.

</details>

## Steps to reproduce

1. Download this capture [Lesson08_Vulkan_crash.zip](https://github.com/baldurk/renderdoc/files/8500764/Lesson08_Vulkan_crash.zip) (generated from the lesson08 fifolog)
2. Select a pixel on EID 15
3. Select "debug"
4. Renderdoc exits

<details><summary>Old info</summary>

To reproduce with my capture:

1. Download [gxtest_copyfilter_bad.zip](https://github.com/baldurk/renderdoc/files/8498850/gxtest_copyfilter_bad.zip)
5. Open gxtest_copyfilter_bad.rdc
6. Navigate to EID 89
7. In the texture viewer, select pixel 0, 0
8. Select debug

To generate that capture:

1. Download [gxtest_copyfilter_bad.zip](https://github.com/baldurk/renderdoc/files/8498850/gxtest_copyfilter_bad.zip)
2. Launch Dolphin from RenderDoc with a capture queued for frame 1 (not frame 0)
3. In Dolphin, open gxtest_copyfilter_bad.elf.  (The source code for this is [here](https://github.com/Pokechu22/hwtests/tree/archive/efb-copy-filter-renderdoc-issue); note that I commented out the networking function for this version so the info in the readme is not relevant)
4. Wait for the capture to complete
5. Stop emulation (no need to wait for the test to finish), and then close Dolphin.  You will probably need to hit the close button twice (as the first time triggers a simulated power button press, but the test program doesn't actually respond to that)

</details>

## Environment

* RenderDoc version: 1.19
* Operating System: Windows 10
* Graphics API: Tested with Vulkan (both Intel and NVidia).  D3D11 allows debugging normally.

**Comment by Pokechu22** [comment]
It turns out that this happens in a lot more general of a case; I'm editing the issue description to generalize it.

**Comment by baldurk** [comment]
This was an issue with handling arrayed-resource bindings. The number of children was getting double counted and wrongly iterated, that commit should fix it as well as some display issues with the variables that I noticed.
