### ISSUE TITLE
"Discarding all captures" appears after the first "unsaved capture" prompt; selecting "no" gives weird results

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2554]
## Description

The "discarding all captures" popup appears at weird times and behaves in a less-than-useful manner.  It only appears if a connection has multiple captures in it, and only after selecting "no to all" on the unsaved capture window.  Weirder still, selecting "no" on the "discarding all captures" window undoes the "no to all", prompting about the next capture in the connection, while selecting "yes" closes captures for all connections; there's no way to discard all captures for one connection but chose individually for the next connection.  And, if the first connection only has a single capture, the "discarding all captures" prompt doesn't appear until after selecting "no to all" on a connection with multiple captures.  Lastly, this also means that you need to make 2 clicks if you actually want to discard all captures from all connections, in a rather confusing manner.

This does seem to be [how the code is written to work](https://github.com/baldurk/renderdoc/blob/a51b20369f685b4e57ccd97fe203483c6d5c5d1f/qrenderdoc/Windows/Dialogs/LiveCapture.cpp#L719-L756), but it still feels less useful than it could be.

The behavior I would expect is instead that the "discarding all captures" prompt appears if there are multiple connections (regardless of how many captures are in the connection), asking whether all captures from all connections should be discarded, and with yes/no/cancel there; then for each connection, it prompts to discard captures individually, with "no to all" moving on to the next connection and "no" moving to the next capture in that connection.

## Steps to reproduce

1. Launch any application.
2. Make 2 captures.
3. Launch the application again.
4. Make 2 more captures.
5. Attempt to close renderdoc.
6. Select "no to all" on the first "unsaved capture" prompt.
7. Select "no" on the "discarding all captures" dialog
8. Observe that the second capture from the first connection now shows the unsaved prompt, instead of the first capture from the second connection.

Here are the dialogs that appear when selecting "no to all" for "unsaved capture" and "no" on discarding all captures (which shows where the prompts occur, but isn't a normal workflow):

<details><summary>3 connections, with 2 captures each</summary>

```
---------------------------
Unsaved capture
---------------------------
Save this capture 'Dolphin Frame #0' at 10:53:41?
---------------------------
Cancel   &Yes   &No   N&o to All   
---------------------------
---------------------------
Discarding all captures
---------------------------
Multiple connections open have potentially unsaved captures, are you sure you wish to discard them all?
---------------------------
&Yes   &No   
---------------------------
---------------------------
Unsaved capture
---------------------------
Save this capture 'Dolphin Frame #1' at 10:53:44?
---------------------------
Cancel   &Yes   &No   N&o to All   
---------------------------
---------------------------
Discarding all captures
---------------------------
Multiple connections open have potentially unsaved captures, are you sure you wish to discard them all?
---------------------------
&Yes   &No   
---------------------------
---------------------------
Unsaved capture
---------------------------
Save this capture 'Dolphin Frame #0' at 10:54:14?
---------------------------
Cancel   &Yes   &No   N&o to All   
---------------------------
---------------------------
Discarding all captures
---------------------------
Multiple connections open have potentially unsaved captures, are you sure you wish to discard them all?
---------------------------
&Yes   &No   
---------------------------
---------------------------
Discarding all captures
---------------------------
Multiple connections open have potentially unsaved captures, are you sure you wish to discard them all?
---------------------------
&Yes   &No   
---------------------------
---------------------------
Unsaved capture
---------------------------
Save this capture 'Dolphin Frame #0' at 10:54:39?
---------------------------
Cancel   &Yes   &No   N&o to All   
---------------------------
---------------------------
Discarding all captures
---------------------------
Multiple connections open have potentially unsaved captures, are you sure you wish to discard them all?
---------------------------
&Yes   &No   
---------------------------
---------------------------
Unsaved capture
---------------------------
Save this capture 'Dolphin Frame #1' at 10:54:42?
---------------------------
Cancel   &Yes   &No   N&o to All   
---------------------------
---------------------------
Discarding all captures
---------------------------
Multiple connections open have potentially unsaved captures, are you sure you wish to discard them all?
---------------------------
&Yes   &No   
---------------------------
```

</details>
<details><summary>2 connections, with a single capture each</summary>

(the program must be left open, or else the capture is automatically opened and starting the program again will discard the capture)

```
---------------------------
Unsaved capture
---------------------------
Save this capture 'Dolphin Frame #0' at 10:57:17?
---------------------------
Cancel   &Yes   &No   
---------------------------
---------------------------
Unsaved capture
---------------------------
Save this capture 'Dolphin Frame #0' at 10:57:34?
---------------------------
Cancel   &Yes   &No   
---------------------------
```

</details>
<details><summary>1 capture followed by 2 captures</summary>

```
---------------------------
Unsaved capture
---------------------------
Save this capture 'Dolphin Frame #0' at 12:24:18?
---------------------------
Cancel   &Yes   &No   
---------------------------
---------------------------
Unsaved capture
---------------------------
Save this capture 'Dolphin Frame #0' at 12:24:50?
---------------------------
Cancel   &Yes   &No   N&o to All   
---------------------------
---------------------------
Discarding all captures
---------------------------
Multiple connections open have potentially unsaved captures, are you sure you wish to discard them all?
---------------------------
&Yes   &No   
---------------------------
---------------------------
Unsaved capture
---------------------------
Save this capture 'Dolphin Frame #47' at 12:24:53?
---------------------------
Cancel   &Yes   &No   N&o to All   
---------------------------
---------------------------
Discarding all captures
---------------------------
Multiple connections open have potentially unsaved captures, are you sure you wish to discard them all?
---------------------------
&Yes   &No   
---------------------------
```

</details>
<details><summary>2 captures followed by 1 capture</summary>

```
---------------------------
Unsaved capture
---------------------------
Save this capture 'Dolphin Frame #1' at 12:30:23?
---------------------------
Cancel   &Yes   &No   N&o to All   
---------------------------
---------------------------
Discarding all captures
---------------------------
Multiple connections open have potentially unsaved captures, are you sure you wish to discard them all?
---------------------------
&Yes   &No   
---------------------------
---------------------------
Unsaved capture
---------------------------
Save this capture 'Dolphin Frame #1987' at 12:30:59?
---------------------------
Cancel   &Yes   &No   N&o to All   
---------------------------
---------------------------
Discarding all captures
---------------------------
Multiple connections open have potentially unsaved captures, are you sure you wish to discard them all?
---------------------------
&Yes   &No   
---------------------------
---------------------------
Unsaved capture
---------------------------
Save this capture 'Dolphin Frame #1' at 12:31:28?
---------------------------
Cancel   &Yes   &No   
---------------------------
```

</details>

## Environment

* RenderDoc version: v1.19
* Operating System: Windows 10
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Unfortunately with this I've found that I can't please everyone, because different people have different workflows they want to support that are in some ways mutually exclusive, and not all usecases look the same.

The specific issues you've identified I've fixed in that commit - the 'no to all' not appearing for connections with one capture was not intended for this case, and in retrospect you're right that if the user clicks no after the 'no to all' prompt indicates it will discard all connections, it doesn't make much sense to only discard that one capture being prompted. I've changed it to cancel the entire process instead.

I'm not going to support a more involved UI flow to either discard all captures or go connection-by-connection either discarding everything in one capture or individually. This prompt is intended to be prevention against accidentally losing a capture you want to keep when closing the program, to ensure that you have been prompted about it and nothing is silently deleted. It's not intended to be a way to do complex prompting and processing of which captures to save and keep. If you want to do something like what you're describing, you should go through the captures deliberately and choose to discard or save as appropriate before closing RenderDoc.
