### ISSUE TITLE
CHM shows nothing

### ISSUE THREAD

**Issue by ylz-at** [baldurk/renderdoc#2558]
## Description

CHM was downloaded from [the link of README](https://renderdoc.org/docs/renderdoc.chm).

But the content of each section is just empty.
![image](https://user-images.githubusercontent.com/8112071/164048512-3fcd59ed-854f-4423-9a87-beed4ecd5562.png)

## Steps to reproduce

- download https://renderdoc.org/docs/renderdoc.chm
- open it and click on TOC.

## Environment

* RenderDoc version: v1.19
* Operating System: Windows 21H2
* Graphics API: N/A

**Comment by baldurk** [comment]
Windows sometimes likes to mark downloaded files as "suspicious", where for executable files it will give a prompt like:

> Are you sure you want to run this file that was downloaded from the internet?

But depending on how you open it, it doesn't always prompt that for chm files and instead will just silently refuse to display the contents.

If you go into the file properties, do you have an option at the bottom related to security or mentioning that the file is downloaded, and with a checkbox to unblock it?
