### ISSUE TITLE
Crash debugging a compute shader (D3D11, float3x3 ctor)

### ISSUE THREAD

**Issue by TaaTT4** [baldurk/renderdoc#2560]
## Description

As the title says, RenderDoc crashes trying to debug a D3D11 compute shader. It seems the culprit is a `float3x3` constructor:
```
#define buildFloat3x3( row0, row1, row2 ) transpose( float3x3( row0, row1, row2 ) )

...

float3 up = abs( N.z ) < 0.999 ? float3( 0, 0, 1 ) : float3( 1, 0, 0 );
float3 tangent = normalize( cross( up, N ) );
float3 bitangent = cross( N, tangent );
float3x3 R = buildFloat3x3( tangent, bitangent, N );
```

The log does not contain any error: [RenderDoc_2022.04.21_09.58.47.log](https://github.com/baldurk/renderdoc/files/8528896/RenderDoc_2022.04.21_09.58.47.log)

## Steps to reproduce

Here you can find the RenderDoc capture: https://drive.google.com/file/d/1hL2Rc3j5oxrAqvYqpbnTgDSsEZjuCBFj/view?usp=sharing
Just debug the compute shader at `EID 855` (no matter what Dispatch Thread ID combination you choose) and, as soon as the program counter reaches the line 351, RenderDoc crashes.

## Environment

* RenderDoc version: 1.19
* Operating System: Windows 11 Pro; build 22000.613
* Graphics API: D3D11; NVIDIA GeForce GTX 1060 with 512.15 driver

[DxDiag.txt](https://github.com/baldurk/renderdoc/files/8529102/DxDiag.txt)
[NVIDIA System Information 04-21-2022 10-15-58.txt](https://github.com/baldurk/renderdoc/files/8529103/NVIDIA.System.Information.04-21-2022.10-15-58.txt)

**Comment by baldurk** [comment]
I believe this is a duplicate of #2536, can you please test with the latest nightly build?

**Comment by TaaTT4** [comment]
You're right! The crash doesn't happen with the latest nightly build. Thanks for the help!
