### ISSUE TITLE
Error Opening capture

### ISSUE THREAD

**Issue by zrp2016** [baldurk/renderdoc#2566]
## Description

Well,I downloaded one .rdc file from UPR Website, As I doubleclick this file,I got an error

## Steps to reproduce

![image](https://user-images.githubusercontent.com/17512844/165277586-f3974bf5-e5e0-4021-b91c-389775447588.png)
![image](https://user-images.githubusercontent.com/17512844/165277607-ac6ff879-1b3e-45cc-a5b3-bb37e1921d58.png)
![image](https://user-images.githubusercontent.com/17512844/165277628-4c4adf8b-2433-46e7-bc8c-961c0f050469.png)

## Environment

* RenderDoc version: 1.19
* Operating System: Win64
* Graphics API:

**Comment by baldurk** [comment]
I can't reproduce this because I don't have a login for that website to download any capture. If you can share the rdc file I can look into it, but I can't do anything with these steps as they are impossible for me to follow.

Check also that you downloaded the file properly, because as the message says the file was corrupted so the most likely explanation may be that the download didn't succeed.

**Comment by zrp2016** [comment]
[1641882239730.01.ZIP](https://github.com/baldurk/renderdoc/files/8562412/1641882239730.01.ZIP)
Im sure its completely downloaded,I follwed the example ,you can also download by your self
https://upr.unity.cn/sample/report/bbd4d9bb-df40-44dc-bbf5-c4d1b1174e87#renderDoc

**Comment by baldurk** [comment]
The error message that you saw in the first place is exactly accurate, the capture file is corrupted as it contains all 0 bytes after 5MB - both in your zip copy and me downloading it (tried twice).

Also I note that the capture is made on RenderDoc version v1.10, which is very old at this point. I strongly recommend you update to the most recent version.

**Comment by zrp2016** [comment]
Thanks for your reply timely reply. I don‘t know why the file is corrupted while downloading, I don't know how to resolve it,and there are other two questions:
1.I uses UPR with RenderDoc,so RD is installed automatically by UPR,I don't know how to upgrade RD's version manually if the version is too low as you say
2.While using UPR,I turn on RD ,click right bottom button Render Doc While testing,so the capture data is uploading,but when I download the capture data,i find it contains 0byte,I cant figure out it
![1650974543565_1FA610D4-4C83-4eba-A439-B744D7672BFF](https://user-images.githubusercontent.com/17512844/165300506-79de9c80-f070-44e8-84bd-203940b39809.png)
![1650974584100_02D922C8-9BA4-47a1-84D1-E79DD7566A33](https://user-images.githubusercontent.com/17512844/165300531-8f89afe7-b5f9-4d9f-8786-47dcb1363c2d.png)
![1650974961850_4842C9EB-FB08-473b-A3B6-BCEB9556B695](https://user-images.githubusercontent.com/17512844/165300545-b4ba68dd-4814-40f8-b5ee-b91b1827e339.png)

Any suggestion could you provide for me,there is my project link below:
https://upr.unity.cn/report/878704db-b404-41bc-a7fb-7854d2eafd48

**Comment by baldurk** [comment]
I don't know what UPR is and it has nothing to do with RenderDoc, so I can't provide any support for any problems you have with it.

**Comment by zrp2016** [comment]
It's about Advanced Unity Profiler .........alright I'll figure it out and thank you
