### ISSUE TITLE
Display pixel values in the Hover display

### ISSUE THREAD

**Issue by jshofmann** [baldurk/renderdoc#257]
Another (hopefully) easy addition with a big impact - in the Texture Viewer, right now the pixel value is only displayed as part of the 'Right click' part of the status display. While that's useful, I find more utility if the pixel values were part of the "Hover" display as well, especially when examining depth or stencil buffers. That makes it much easier to determine how the values vary over an area. If screen space in that status bar is an issue, of the values currently displayed in the texture viewer's status bar the uv coordinates are the information i use the least, and the pixel values are the information I use the most.

**Comment by baldurk** [comment]
I'm not entirely sure what you mean - how would this be different from simply holding down the right mouse button while moving the cursor over the pixel values that you want to browse/scan?

At the moment the scheme is that the text pixel values only update when you are holding the right mouse button, which lets you both scan over an area but also let go of right mouse to get a precise pixel. You can also use the arrow keys which isn't too obvious, but that lets you hone in on a precise pixel if you do need that (which is the opposite of what you want, but useful to know about!).

**Comment by jshofmann** [comment]
I've tried holding the right-mouse button down, and I find that the pixel values don't update nearly as often as the pixel coordinate values do - that is, the pixel values are frequently frozen at some outdated value, while the pixel coordinate values are updated as expected. It can be upwards of a second between pixel value updates, during which the mouse has moved well away from the pixel whose value is displayed. The speed at which the mouse moves does not affect the update rate of the pixel values - moving the mouse slowly does not improve the pixel value display. If the display is frozen at the time the right-button is released, then an incorrect value is displayed in the status bar. Perhaps this should be considered as a bug report instead?

**Comment by jshofmann** [comment]
I had forgotten about that right-drag feature, please disregard this enhancement request. Thanks!

**Comment by baldurk** [comment]
Yes that sounds like a bug, please file a new issue with more repro details since the update rate is fine for me:

![pixel_pick](https://cloud.githubusercontent.com/assets/661798/14799721/568a5174-0b3e-11e6-83da-67455eed6ca0.gif)
