### ISSUE TITLE
Depth/stencil does not work in Vulkan capture replays

### ISSUE THREAD

**Issue by matusfedorko** [baldurk/renderdoc#2579]
## Description

when debugging our program with RenderDoc whilst using Vulkan backend, I get incorrect capture replay. I think there is something wrong with depth stencil buffers (they stay zero-ed out). Using our OpenGL backend or running our program with Vulkan backend outside of RenderDoc, things work correctly.

This is the (correct) output from OpenGL capture:

![Screenshot 2022-05-09 171608](https://user-images.githubusercontent.com/82540779/167443344-bfc16c42-c0b0-42a4-a302-1ae04eb27705.png)

This is the (incorrect) output from Vulkan capture:

![Screenshot 2022-05-09 172602](https://user-images.githubusercontent.com/82540779/167443671-f2ee25e3-ba89-48ef-a347-384d0e07a887.png)

(the checkerboard square in the bottom right corner is OK, it should be there)

## Steps to reproduce

I have attached the faulty Vulkan capture as well as the working OpenGL capture. Simply open either one of them and observe what I describe above.

[capture_vk.zip](https://github.com/baldurk/renderdoc/files/8653181/capture_vk.zip)
[capture_gl.zip](https://github.com/baldurk/renderdoc/files/8653182/capture_gl.zip)

## Environment

* RenderDoc version: v1.19 (built from eb1e625b) (Qt version 5.15.2)
* Operating System: Windows 10 Home (version 21H2)
* Graphics API: Vulkan
* GK : NVidia GeForce RTX 3060
* Driver version : 461.79

This is a laptop and there is also an integrated AMD GPU, but the capture and replay ran on the dedicated NVidia card.

**Comment by baldurk** [comment]
To correct/clarify what you said, the opengl capture was made on the nvidia GPU but the vulkan capture uses the AMD physical device. Unfortunately the resulting capture is not easily compatible with the AMD GPUs I have available. Can you make a vulkan capture using the nvidia GPU and share that, or share your application so I can capture it myself? If you can't share either I can try and edit the capture to load it, but it may take some time.

I also note that your AMD driver is very old, it seems to date from 2020 some time. I would strongly recommend updating it regardless.

**Comment by matusfedorko** [comment]
hm, interesting, I thought that both captures were made with the same GPU (NVidia). I mentioned AMD just as a "by the way in case it mattered". Why would RenderDoc pick a different GPU for Vulkan and OpenGL ? I vaguely recall something similar on a different laptop. RenderDoc would pick Intel integrated GPU over the dedicated NVidia one. I'll try to make the capture on NVidia.

**Comment by baldurk** [comment]
On OpenGL there is only ever one GPU available due to the limitations of the API, so there is no choice to make. On Vulkan the choice of which GPU to use is up to your application - you call `vkEnumeratePhysicalDevices` and select the one to use for `vkCreateDevice` by whichever method you wish. You would need to check how you choose the physical device from multiple available. It works similarly on D3D11 and D3D12. RenderDoc never makes that decision for you.

On replay unless you override the GPU selection, by default RenderDoc will pick the closest matching physical device by vendor and device and use that for replay.

**Comment by matusfedorko** [comment]
Thanks for pointing this out to me. The way I pick physical device was to simply select the first one from the list, but the order of devices in that list is different when using RenderDoc vs. not.

This may also explain the occasional crashes (VK_ERROR_DEVICE_LOST) that I sometimes experienced when debugging through RenderDoc.

With NVidia things work as expected, so I guess you can close this report. Or do you want me to try to update the AMD driver and test again ?

**Comment by baldurk** [comment]
I think you should try again with an updated driver but that does suggest this may be a driver side issue.

I believe on newer vulkan loaders the physical devices are ordered in preference order according to the OS, if the OS supports it (only windows 10 and up), but in general it's a good idea to have some way of specifying one particular. You may also want to not rely on a specific order and e.g. pick the discrete card over any integrated card.
