### ISSUE TITLE
Exception in replay frame when device does not support 8 render targets.

### ISSUE THREAD

**Issue by Qinja** [baldurk/renderdoc#2580]
## Description

Some mobile phone may support at most 4 render targets. But RenderDoc seems to insert a shader using 8 render target when replaying a frame, rasing exceptions.

![image](https://user-images.githubusercontent.com/12295257/167571287-062dda73-6241-43e8-9d62-48d22063a08f.png)

Shader path : `renderdoc\data\glsl\discard.frag`

It is not a fatal crash, but print many log after then.

## Steps to reproduce

Replay a frame in some android device, such as HUAWEI Nova 4.

## Environment

* RenderDoc version: 1.19 (built form eb1e625b)
* Operating System: Windows 11 x64
* Graphics API: Opengles (android phone: HUAWEI Nova 4)

**Comment by baldurk** [comment]
Can you please explain what the actual problem you are seeing is? If it doesn't crash, what doesn't work or behaves incorrectly?

**Comment by Qinja** [comment]
No fatal issues, just lots of error logs.

I saw that RenderDoc compiles a shader (renderdoc\data\glsl\discard.frag) on the device, causing the device to print out these error logs, guessing it's because the current device doesn't support 8 render targets but there are 8 render targets involved in the shader. Maybe you can have RenderDoc check the maximum number of render targets supported by the device before calling this shader, or maybe ignore the issue. It's ok.

**Comment by baldurk** [comment]
The log is internal and for RenderDoc developers only, if you don't observe any actual problems using RenderDoc then I don't consider this a bug. Especially on mobile devices with GL, the errors could be anything.
