### ISSUE TITLE
Crash when using `vkCmdSetEvent2` on Windows

### ISSUE THREAD

**Issue by Ryp** [baldurk/renderdoc#2582]
## Description

I'm using Vulkan device-local events in my app to do DX12-style split barriers. This works fine, and I don't get validation errors across both setup I'm developing for (Linux + Intel GPU and Windows + AMD GPU).
If I start my app which the renderdoc integration enabled, it will crash at the first call of `vkCmdSetEvent2`. The callstack shows my code, then renderdoc layer, and it crashes two steps down in the AMD driver.

## Steps to reproduce

I can't provide a capture with the issue since renderdoc would crash on Windows. However, this doesn't happen on my Linux machine, and I think a capture has interesting info that could be useful here.
Here it is: https://www.dropbox.com/s/nuvhfrm0tzncn5v/reaper-capture-strange-validation-issue.rdc?dl=0
What's interesting is that I get validation errors this way that I didn't get otherwise. I get 4 warnings that all coincide with a vkCmdSetEvent2 call with the following message:
```
Validation Error: [ VUID-VkImageMemoryBarrier2-image-parameter ] Object 0: handle = Instance 7, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xa2d5467b | Invalid VkImage Object 0x560a424837d0. The Vulkan spec states: image must be a valid VkImage handle (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageMemoryBarrier2-image-parameter)
```

If this not enough info to give a clue, I'll provide complete steps to reproduce from [source](https://github.com/Ryp/reaper) (which I assume you want to do as a last resort)

## Environment

* RenderDoc version: v1.19
* Operating System: Windows
* Graphics API: Vulkan

**Comment by baldurk** [comment]
I tried to build your program from the linked github repository but I got stuck trying to figure out how to satisfy the bullet dependency. I compiled the project from https://github.com/bulletphysics/bullet3 and while it compiled successfully I couldn't figure out how to persuade cmake to look at it (or even if what I had compiled was what was needed).

I didn't find any binary builds of that library. Is there a particular set of instructions to follow on how to compile that?

**Comment by Ryp** [comment]
Sorry about the current build state of the project, I didn't think you'd go compiling right away.
Here: https://gist.github.com/Ryp/abdd3ed676efea2b4c2f5624ba68b5a9
This should get you going for Windows.

**Comment by baldurk** [comment]
Running the program is the only way I can reproduce the problem, since you say it crashes during capture.

What compiler does your program support on windows? I'm building with VS2019 but I get some errors I can't easily figure out how to solve:

```
1>main.cpp
1>T:\renderdoc\cap_samples_vk\reaper\external\fmt\fmt\format.h(797,1): error C2660: 'std::allocator<wchar_t>::allocate': function does not take 2 arguments
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xmemory(838,65): message : see declaration of 'std::allocator<wchar_t>::allocate'
1>T:\renderdoc\cap_samples_vk\reaper\external\fmt\fmt\format.h(793): message : while compiling class template member function 'void fmt::internal::MemoryBuffer<wchar_t,500,std::allocator<wchar_t>>::grow(size_t)'
1>T:\renderdoc\cap_samples_vk\reaper\external\fmt\fmt\format.h(1041): message : see reference to class template instantiation 'fmt::internal::MemoryBuffer<wchar_t,500,std::allocator<wchar_t>>' being compiled
1>T:\renderdoc\cap_samples_vk\reaper\external\fmt\fmt\format.h(797,1): error C2660: 'std::allocator<char>::allocate': function does not take 2 arguments
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xmemory(838,65): message : see declaration of 'std::allocator<char>::allocate'
1>T:\renderdoc\cap_samples_vk\reaper\external\fmt\fmt\format.h(793): message : while compiling class template member function 'void fmt::internal::MemoryBuffer<char,500,std::allocator<char>>::grow(size_t)'
1>T:\renderdoc\cap_samples_vk\reaper\external\fmt\fmt\format.h(1055): message : see reference to class template instantiation 'fmt::internal::MemoryBuffer<char,500,std::allocator<char>>' being compiled
1>Done building project "reaper.vcxproj" -- FAILED.
1>ExecuteFrame.cpp
1>T:\renderdoc\cap_samples_vk\reaper\external\span-lite\include\nonstd/span.hpp(1522,70): fatal error C1012: unmatched parenthesis: missing ')'
1>Done building project "reaper_renderer.vcxproj" -- FAILED.
```

**Comment by Ryp** [comment]
I'm using MSVC from VS 2017 - probably you can get it to compile by using it, or targeting a slightly older C++ version

**Comment by Ryp** [comment]
I just updated the git submodules for these dependencies, they seem to fix the errors you're getting but for VS 2022. Please use `git pull` and execute `git submodule update`.
I also updated the [patch](https://gist.github.com/Ryp/abdd3ed676efea2b4c2f5624ba68b5a9) I'm using to compile on Windows with VS 2022

**Comment by baldurk** [comment]
Thanks, I was able to get it building in VS2019 with a couple of changes to your code (missing include and an incorrect function parameter).

I was weirdly only able to reproduce this on one AMD system and not another, even though the bug is clearly present. I'm also surprised this didn't reproduce in the test I have of VK_Synchronization_2 which runs through the exact same codepath. I only run my tests nightly on NV due to multiple AMD driver bugs causing false positives, but I'd still expect it to fail. I can only guess that in those cases the driver was applying a global barrier and not anything image-specific in those cases.

Either way, that commit should fix the problem.

**Comment by Ryp** [comment]
Thanks for the quick turnaround, that's awesome!
I saw that `VK_Synchronization_2` while browsing the source, it's really weird because it really is the same calls. The only difference I see is the reset command you do at start but I don't see why that would do anything since events start unsignaled anyway.

**Comment by baldurk** [comment]
The problem reproduced on that demo too, just only on this particular AMD GPU, which I don't run in autotests as I mentioned above. The other drivers and GPUs I tested worked fine both on your example and the demo. As I say it presumably means not all drivers actually make use of the specific image handle.
