### ISSUE TITLE
Crash when using Verify Buffer Access on Unmap on a Mappable 3D Texture

### ISSUE THREAD

**Issue by bartwe** [baldurk/renderdoc#2583]
## Description

Crash when using Verify Buffer Access on Unmap on a Mappable 3D Texture.

## Steps to reproduce

In util/test/demos/d3d11/d3d11_texture_3d.cpp

```
    ID3D11Texture3DPtr mappable = MakeTexture(DXGI_FORMAT_R32_UINT, 64, 128, 256).Mappable().SRV();

    while(Running())
    {
      ClearRenderTargetView(bbRTV, {0.2f, 0.2f, 0.2f, 1.0f});
      
      D3D11_MAPPED_SUBRESOURCE msr;
      ctx->Map(mappable, 0, D3D11_MAP_WRITE_DISCARD, 0, &msr);
      ctx->Unmap(mappable, 0);
```

To make this reliably fail enable the debug page heap using:
"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\gflags.exe" /p /enable demos_x64.exe /full

at this point run the d3d11_texture_3d test through renderdoc with Verify Buffer Access enabled.

## Environment

* RenderDoc version: Development Build v1.20 from git commit date 10/05/2022 12:36:02
* Operating System: Windows 10
* Graphics API: D3D11

**Comment by bartwe** [comment]
line 7748 of d3d11_context_wrap.cpp: (WrappedID3D11DeviceContext::Serialise_Unmap) 
there is a memcpy into the D3D11ResourceRecord::GetDataPtr() which doesn't fit, i'm wondering if this is because it is a texture3d 
The memcpy was passed the length of the mapping, but the buffer returned by GetDataPtr() was 192 bytes in size based on the remaining space in the page of the address in the pointer (alignments apply)

**Comment by baldurk** [comment]
I believe that commit should fix it. The map verification was only really designed with buffer maps in mind, since I think generally textures are updated with UpdateSubresource rather than Map on D3D11. At least I assume so since that bug has been there for a long time and no-one else ran into that case.
