### ISSUE TITLE
D3D12 -  Missing Barrier "Usage in Frame"

### ISSUE THREAD

**Issue by mickbeaver** [baldurk/renderdoc#2589]
## Description

I found an odd edge case this week. If I executed a command list that contained nothing but a single call to `ID3D12GraphicsCommandList::ResourceBarrier()`, that barrier would not show up in the resource's "Usage in Frame." If I added other calls to the command list, such as `PIXBeginEvent()`/`PIXEndEvent()`, then the barrier usage would show up in the resource's "Usage in Frame."

I would have expected the Barrier EID to show up under the "Usage in Frame," even in the case where the command list contained nothing but the barrier.

## Steps to reproduce

In D3D12, create a command list that only contains one single command for the executed frame, a `ResourceBarrier`. Take a capture of your frame and note that the resource that is reference in your barrier does not mention the barrier's EID in the "Usage in Frame."

I've reproduced the issue in the D3D12 samples (https://github.com/Microsoft/DirectX-Graphics-Samples), using a slightly modified D3D12HelloTriangle (DirectX-Graphics-Samples\Samples\Desktop\D3D12HelloWorld\src\HelloTexture).

[D3D12HelloTriangle.rdc.zip](https://github.com/baldurk/renderdoc/files/8733648/D3D12HelloTriangle.rdc.zip)
[D3D12HelloTriangle.src.zip](https://github.com/baldurk/renderdoc/files/8733656/D3D12HelloTriangle.src.zip)

## Environment

* RenderDoc version: 1.19
* Operating System: Microsoft Windows 10 Enterprise 10.0.19044 Build 19044
* Graphics API: D3D12
* GPU: NVIDIA GeForce GTX 1080
* Driver: 472.12

![Screenshot 2022-05-19 141410](https://user-images.githubusercontent.com/4925235/169385035-bb7c0b65-96c1-47b3-adc0-398e5d5367b5.png)

**Comment by baldurk** [comment]
Thanks for the clear report - that commit should address it. Looks like trailing resource usage in a command buffer not attached to an action (draw/dispatch/etc) wasn't being processed, I just fixed a similar bug on vulkan recently so I should have fixed this at the same time.

**Comment by mickbeaver** [comment]
Thank you for looking into this! Great fix!
