### ISSUE TITLE
[Vulkan] Device lost when replaying a capture

### ISSUE THREAD

**Issue by corporateshark** [baldurk/renderdoc#2590]
## Description

Device is lost while trying to navigate within a capture file.

## Steps to reproduce

1) Open capture [Test_SceneGraph_Debug_(Intel_Sponza).rdc](http://linderdaum.com/Test_SceneGraph_Debug_(Intel_Sponza).rdc)

2) Click to expand "Render pass: Light"

3) Click on "Batch 000"

![image](https://user-images.githubusercontent.com/2510143/169509785-002eab19-c56b-4259-ade6-0e5322c06afa.png)

3) Observe the device lost message:

![image](https://user-images.githubusercontent.com/2510143/169509450-1c906060-24b8-4fb6-a8a8-19bd802d5416.png)

## Environment

* RenderDoc version: v1.19
* Operating System: Windows 10 x64
* Graphics API: Vulkan 1.3 (RTX 3070 512.77)

**Comment by baldurk** [comment]
Thanks for the report, it was implicitly selecting the event past the end of an indirect draw and replaying one extra draw which it shouldn't. That commit will fix the problem, or as a workaround you can expand the marker and select the draws from within which should work fine on v1.19.
