### ISSUE TITLE
Show dynamic offsets in event browser

### ISSUE THREAD

**Issue by SupinePandora43** [baldurk/renderdoc#2592]
## Description

It'd be pretty useful if RenderDoc showed dynamic offsets of `vkCmdBindDescriptorSets`

(Because right now it just looks like a reduant DescriptorSet set)

## Environment

* RenderDoc version: 1.19
* Operating System: Windows 11 x64
* Graphics API: Vulkan

**Comment by baldurk** [comment]
This is already possible if you want to see every parameter exhaustively to a function call. Click on 'settings and help' on the event filter, and enable the 'show all parameters' checkbox. For more information see [the documentation for the event browser](https://renderdoc.org/docs/window/event_browser.html#event-display).
