### ISSUE TITLE
GS/DS Output panel is empty even though geometry shader is used in Vulkan when using Multi View

### ISSUE THREAD

**Issue by jerry411** [baldurk/renderdoc#2595]
## Description

Mesh Viewer -> GS/DS Output panel is empty even though geometry shader is used in a Vulkan 1.3 app. But only when Multi View rendering is used.

I have created a simple pass-through geometry shader. It takes 1 triangle and outputs 1 triangle with the same attributes - only changes gl_Position so I can be sure that geometry shader actually did something. The output of the fragment shader is exactly as expected if the geometry shader did its work. All other panels (VS Input and VS Output) show expected data. GS/DS Output shows nothing but column headers: VTX, IDX, _sig13._child0, ... (some of them, duplicated - see screenshot below). GS/DS Out panel under Preview (the one used for preview of 3D data) shows no data as well.

However, this happens only when Multi View rendering is used. I have 2 passes for G-buffers and 1 actual pass for swapchain (each is implemented as a separate render pass with a single subpass). G-buffer passes (using only off-screen color framebuffer attachments/render targets) use Multi View rendering (in my case 10 draws of the same scene with different view matrices provided by UBO). Each draw outputs to a separate layer of the image. Multi View works flawlessly. When I used a similar pass-through geometry shader in my only color pass that provides the final color for swapchain image, and which does not use Multi View, GS/DS Output panel worked without problems. This panel displays data also in case I change my G-buffer draws from Multi View to standard  (single-layer) ones. Using Multi View with a single layer does not help.

There are no warnings or errors provided by validation layers. Device features for GeometryShader, Multiview as well as MultiviewGeometryShader are all available and turned on.

Screenshots:
[VS Output](https://dl.dropboxusercontent.com/s/i5xzjau8dhzn4rl/qrenderdoc_6OMYlJzHux.png)
[GS/DS Output](https://dl.dropboxusercontent.com/s/67s306f1piv5o23/qrenderdoc_FIbGTpTzsh.png)

Geometry shader code:
```glsl
#version 450
#extension GL_KHR_vulkan_glsl : enable
#extension GL_EXT_multiview : enable

layout (triangles) in;
layout (triangle_strip, max_vertices = 3) out;

// IN attributes (from VS)
layout (location = 0) in vec3[] inWorldPos;
layout (location = 1) in vec3[] inNormal;
layout (location = 2) in vec3[] inColor;

// OUT attributes (to FS)
layout (location = 0) out vec3 outWorldPos;
layout (location = 1) out vec3 outNormal;
layout (location = 2) out vec3 outColor;

void main()
{
    gl_Position = gl_in[0].gl_Position + vec4(2, 2, 0, 0);
    outWorldPos = inWorldPos[0];
    outNormal = inNormal[0];
    outColor = inColor[0];
    EmitVertex();

    gl_Position = gl_in[1].gl_Position + vec4(1, 1, 0, 0); // this is used intentionally for obvious distortion of image
    outWorldPos = inWorldPos[1];
    outNormal = inNormal[1];
    outColor = inColor[1];
    EmitVertex();

    gl_Position = gl_in[2].gl_Position + vec4(2, 2, 0, 0);
    outWorldPos = inWorldPos[2];
    outNormal = inNormal[2];
    outColor = inColor[2];
    EmitVertex();

    EndPrimitive();
}
```

## Steps to reproduce

I have shared a capture file via provided e-mail.

I am not aware of doing anything special in my app so reproduction steps should be as straightforward as creating Vulkan 1.3 app with a simple pipeline consisting of VS, GS, and FS and using Multi View rendering. GS can be as simple as pass-through (see code above). Run app in RenderDoc 1.18 or 1.19 and look at Mesh Viewer -> GS/DS Output panel which is empty. Turn off Multi View rendering and GS/DS Output should have data in it.

## Environment

* RenderDoc version: stable 1.18 and 1.19 (versions 1.17 and lower do not support Vulkan 1.3 so I could not test it)
* Operating System: Windows 11
* Graphics API: Vulkan 1.3

I am running RTX 3070 Ti with driver version 512.59.

**Comment by baldurk** [comment]
This is unfortunately due to effectively a hardware/implementation limitation. Geometry and tessellation shader outputs are only available in RenderDoc via transform feedback, and transform feedback cannot be used with multiview. Unless a new extension is provided in future to allow this it won't work in RenderDoc, and I don't expect that to ever happen.

In theory for geometry shaders with no expansion and providing there's no tessellation active, it would be possible to implement the mesh output without using transform feedback as is done for vertex shaders. However given that geometry shaders are used rarely at best, and I would imagine their use with multiview even rarer still, this is so niche a case that I don't think I would even accept a pull request of an implementation that does that given the tradeoff of code complexity vs benefit.

**Comment by jerry411** [comment]
That is totally understandable. However, it would be nice to at least show something along the lines "GS/DS Output is not supported when Multi View is used". I have spent hours wondering why my GS provides no output.
