### ISSUE TITLE
Capturing Deathloop under vkd3d crashes the game and results in corrupt capture.

### ISSUE THREAD

**Issue by Malexandra-de** [baldurk/renderdoc#2596]
## Description

I am currently attempting to reverse engineer the upscaling process in Deathloop.
I am running the game under vkd3d to avoid issues due to possible Ray Tracing calls.
Capturing the game causes the screen to freeze (as expected) but it never unfreezes.
The capture file is successfully written (see log,) but loading it only results in this error message:
![image](https://user-images.githubusercontent.com/6448982/170769288-bc855827-7b52-43f5-9c8d-2afef801c6a7.png)

## Steps to reproduce

The capture file can be downloaded here:
https://uni-muenster.sciebo.de/s/xlTyFDuCt3k9Q1F
This bug can be easily reproduced by launching Deathloop with Proton 7.0-2 with the Renderdoc Vulkan Layer.
The launch options are: `ENABLE_VULKAN_RENDERDOC_CAPTURE=1 %command%`
The crash occurs for me after entering "the Complex" in the morning and capturing just outside the starting bunker.
The Anomaly (the big microphone shaped structure) and the skybox are both visible, but I don't know if this has any influence.

## Environment

* RenderDoc version: 1.20
* Operating System: Ubuntu 22.04
* Graphics API: Vulkan

GPU: AMD RX 6700XT
GPU driver: Mesa 22.1.0 - kisak-mesa **PPA**
[vkinfo.txt](https://github.com/baldurk/renderdoc/files/8789092/vkinfo.txt)
Log:
https://uni-muenster.sciebo.de/s/mhYjwRLYTtA8ljn

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by Malexandra-de** [comment]
Fair enough.
