### ISSUE TITLE
Crashed in libVkLayer_GLES_RenderDoc.so if doing glBlitFramebuffer on android GLES and launched from renderdoc

### ISSUE THREAD

**Issue by jarodljl** [baldurk/renderdoc#2597]
## Description
We use glBlitFramebuffer to copy an offscreen surface to backbuffer on android GLES, and it works fine, but it would crash if I launch it from RenderDoc(tested on 1.18 and 1.20)
The callstack is 
`F/DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
F/DEBUG   : Build fingerprint: 'samsung/beyondxxx/beyondx:11/RP1A.200720.012/G977BXXS8FUE5:user/release-keys'
F/DEBUG   : Revision: '9'
F/DEBUG   : ABI: 'arm64'
F/DEBUG   : Timestamp: 2022-05-29 10:11:07+0800
F/DEBUG   : pid: 25861, tid: 26334, name: RHIThread  >>> com.YourCompany.MyProject5New <<<
F/DEBUG   : uid: 10408
F/DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa8
F/DEBUG   : Cause: null pointer dereference
F/DEBUG   :     x0  00000078d1af3e18  x1  00000077789fb480  x2  0000000000000000  x3  0000000000000010
F/DEBUG   :     x4  0000000000000000  x5  0000000000000000  x6  0000007b1957e000  x7  0000000003f26330
F/DEBUG   :     x8  2909469e7c0644b1  x9  2909469e7c0644b1  x10 2909469e7c0644b1  x11 0000000000000000
F/DEBUG   :     x12 000000005fae7d9b  x13 000000000000018b  x14 0000000000000000  x15 0000000000000140
F/DEBUG   :     x16 00000077aff33940  x17 0000007b160cdbd0  x18 0000007851ae8fd0  x19 0000000000000004
F/DEBUG   :     x20 0000000000000000  x21 0000007921ac50b0  x22 0000007841bb14d0  x23 0000000000000000
F/DEBUG   :     x24 0000007921ac53a0  x25 0000000000000000  x26 0000000000000001  x27 0000000000000000
F/DEBUG   :     x28 00000077a8dd1450  x29 00000077789fb4f0
F/DEBUG   :     lr  00000077aebcbb30  sp  00000077789fb450  pc  00000077aebcbb34  pst 0000000060000000
F/DEBUG   : backtrace:
F/DEBUG   :       #00 pc 000000000026eb34  /data/app/~~SzQxKc5ch66s6YeJIlUG7g==/org.renderdoc.renderdoccmd.arm64-xuNXa8sW0p2sEBHilXq9gA==/lib/arm64/libVkLayer_GLES_RenderDoc.so (BuildId: f599712989946cb35d76e32a16814855fa79ac7a)
F/DEBUG   :       #01 pc 000000000026ea6c  /data/app/~~SzQxKc5ch66s6YeJIlUG7g==/org.renderdoc.renderdoccmd.arm64-xuNXa8sW0p2sEBHilXq9gA==/lib/arm64/libVkLayer_GLES_RenderDoc.so (BuildId: f599712989946cb35d76e32a16814855fa79ac7a)
F/DEBUG   :       #02 pc 0000000000355c9c  /data/app/~~SzQxKc5ch66s6YeJIlUG7g==/org.renderdoc.renderdoccmd.arm64-xuNXa8sW0p2sEBHilXq9gA==/lib/arm64/libVkLayer_GLES_RenderDoc.so (BuildId: f599712989946cb35d76e32a16814855fa79ac7a)
F/DEBUG   :       #03 pc 00000000003efed0  /data/app/~~SzQxKc5ch66s6YeJIlUG7g==/org.renderdoc.renderdoccmd.arm64-xuNXa8sW0p2sEBHilXq9gA==/lib/arm64/libVkLayer_GLES_RenderDoc.so (BuildId: f599712989946cb35d76e32a16814855fa79ac7a)
F/DEBUG   :       #04 pc 000000000a52d238  /data/app/~~6yCc7Xkl_3bqXbxN36o3MA==/com.YourCompany.MyProject5New-pFXhl6StZtCH2Mvh96yZKA==/lib/arm64/libUnreal.so (BuildId: e1a5383fa822a52156a05378d38091fad0602ecf)
F/DEBUG   :       #05 pc 000000000a524d04  /data/app/~~6yCc7Xkl_3bqXbxN36o3MA==/com.YourCompany.MyProject5New-pFXhl6StZtCH2Mvh96yZKA==/lib/arm64/libUnreal.so (BuildId: e1a5383fa822a52156a05378d38091fad0602ecf)
F/DEBUG   :       #06 pc 0000000005ff9058  /data/app/~~6yCc7Xkl_3bqXbxN36o3MA==/com.YourCompany.MyProject5New-pFXhl6StZtCH2Mvh96yZKA==/lib/arm64/libUnreal.so (BuildId: e1a5383fa822a52156a05378d38091fad0602ecf)
F/DEBUG   :       #07 pc 0000000006052734  /data/app/~~6yCc7Xkl_3bqXbxN36o3MA==/com.YourCompany.MyProject5New-pFXhl6StZtCH2Mvh96yZKA==/lib/arm64/libUnreal.so (BuildId: e1a5383fa822a52156a05378d38091fad0602ecf)
F/DEBUG   :       #08 pc 0000000006051f20  /data/app/~~6yCc7Xkl_3bqXbxN36o3MA==/com.YourCompany.MyProject5New-pFXhl6StZtCH2Mvh96yZKA==/lib/arm64/libUnreal.so (BuildId: e1a5383fa822a52156a05378d38091fad0602ecf)
F/DEBUG   :       #09 pc 00000000049b5060  /data/app/~~6yCc7Xkl_3bqXbxN36o3MA==/com.YourCompany.MyProject5New-pFXhl6StZtCH2Mvh96yZKA==/lib/arm64/libUnreal.so (BuildId: e1a5383fa822a52156a05378d38091fad0602ecf)
F/DEBUG   :       #10 pc 00000000049b35b0  /data/app/~~6yCc7Xkl_3bqXbxN36o3MA==/com.YourCompany.MyProject5New-pFXhl6StZtCH2Mvh96yZKA==/lib/arm64/libUnreal.so (BuildId: e1a5383fa822a52156a05378d38091fad0602ecf)
F/DEBUG   :       #11 pc 00000000049b2248  /data/app/~~6yCc7Xkl_3bqXbxN36o3MA==/com.YourCompany.MyProject5New-pFXhl6StZtCH2Mvh96yZKA==/lib/arm64/libUnreal.so (BuildId: e1a5383fa822a52156a05378d38091fad0602ecf)
F/DEBUG   :       #12 pc 000000000616ef20  /data/app/~~6yCc7Xkl_3bqXbxN36o3MA==/com.YourCompany.MyProject5New-pFXhl6StZtCH2Mvh96yZKA==/lib/arm64/libUnreal.so (BuildId: e1a5383fa822a52156a05378d38091fad0602ecf)
F/DEBUG   :       #13 pc 0000000004acf34c  /data/app/~~6yCc7Xkl_3bqXbxN36o3MA==/com.YourCompany.MyProject5New-pFXhl6StZtCH2Mvh96yZKA==/lib/arm64/libUnreal.so (BuildId: e1a5383fa822a52156a05378d38091fad0602ecf)
F/DEBUG   :       #14 pc 00000000049ae970  /data/app/~~6yCc7Xkl_3bqXbxN36o3MA==/com.YourCompany.MyProject5New-pFXhl6StZtCH2Mvh96yZKA==/lib/arm64/libUnreal.so (BuildId: e1a5383fa822a52156a05378d38091fad0602ecf)
F/DEBUG   :       #15 pc 00000000000b10e8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: f85239005a40452d2a5d593676124555)
F/DEBUG   :       #16 pc 0000000000050a58  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: f85239005a40452d2a5d593676124555)`

## Steps to reproduce
I send a repro apk to baldurk@baldurk.org from 88908136@qq.com

## Environment

* RenderDoc version: 1.18, 1.20
* Operating System: Android 11, 
* Graphics API: GLES 3.2

I teseted on both Samsung S10 adreno and mali, all crashed.

**Comment by baldurk** [comment]
This program relies on framebuffers being shared between contexts, which is not legal on OpenGL ES. Framebuffers must be treated as context-local objects.

**Comment by jarodljl** [comment]
Thank you very much. It works fine if I create the frame buffer at local context.
