### ISSUE TITLE
Immutable samplers not recorded (Vulkan)

### ISSUE THREAD

**Issue by RangerWu** [baldurk/renderdoc#260]
The API _vkCreateDescriptorSetLayout _may use some immutable samplers in parameter _VkDescriptorPoolCreateInfo_, yet it seems current codes do not add references to the referenced samplers, maybe some calls to AddBindFrameRef needed here?

**Comment by baldurk** [comment]
Yes I believe you're right, the samplers don't seem to be frame ref'd anywhere that I can see.

**Comment by baldurk** [comment]
This should do the trick, it works for me on the immutable_samplers demo from LunarG.

**Comment by RangerWu** [comment]
[immutableSampler.zip](https://github.com/baldurk/renderdoc/files/297314/immutableSampler.zip)
Hi Baldurk,

Sorry that my verification using tip codes does not work, and the attached is my logged scripts, the immutable sampler is shown in fragment shader resources yet the final result is black, not very sure what is missing, or anything wrong on my side.

Not sure how you test it, since the sample only present once, to capture it, I add a _FirstFrame_ function in class WrappedVulkan as WrappedID3D11Device::FirstFrame, and called it in WrappedVulkan::vkCreateSwapchainKHR.
`void WrappedVulkan::FirstFrame(VkSwapchainKHR swapChain)
{
	VkResourceRecord *swaprecord = GetRecord(swapChain);
	RDCASSERT(swaprecord->swapInfo);

	SwapchainInfo &swapInfo = *swaprecord->swapInfo;

	// if we have to capture the first frame, begin capturing immediately
	if (m_State == WRITING_IDLE && RenderDoc::Inst().ShouldTriggerCapture(0))
	{
		RenderDoc::Inst().StartFrameCapture(LayerDisp(m_Instance), swapInfo.wndHandle);

		m_AppControlledCapture = false;
	}
}`
Thanks!

**Comment by baldurk** [comment]
Thanks for the repro case. I had missed some logic which wasn't exposed in the LunarG sample, where `vkUpdateDescriptorSets` calls were ignored because the sampler was NULL (even though that's valid, when immutable samplers are set). Please try again when you can.

**Comment by RangerWu** [comment]
Yes it is working, many thanks!
