### ISSUE TITLE
How do you attach a debugger to traced app

### ISSUE THREAD

**Issue by z-s-e** [baldurk/renderdoc#2603]
## Description

Sorry, not sure whether this should be a bug, a feature request (for better documentation), or just a question. I'm trying to attach gdb to a launched (Vulkan) application. When using `renderdoccmd capture --opt-delay-for-debugger 20 <my-app>` and then attaching to the PID of the launched application, and resuming execution, I get a SIGHUP and the app terminates. When trying this from the GUI, instead I see in gdb the app constantly receiving SIGSTOP. Am I doing something wrong? Any hints appreciated.

## Steps to reproduce

After launching an app to trace, `gdb -p PID` and `continue` inside gdb.

## Environment

* RenderDoc version: 1.20
* Operating System: Ubuntu 22.04
* Graphics API: Vulkan

**Comment by baldurk** [comment]
FYI: renderdoccmd is an internal undocumented tool and should not be used by users directly.

I have seen the same behaviour when setting the 'debugger delay' option. As far as I can tell it's a problem with gdb which doesn't handle attaching to previously-ptraced programs very well, and gets stuck on resuming from the SIGSTOP. The only workaround I'm aware of is to run `handle SIGSTOP ignore` in gdb and then continue (multiple times if necessary for multiple threads).
