### ISSUE TITLE
VK_EXT_depth_clip_control extension support

### ISSUE THREAD

**Issue by kieroooo** [baldurk/renderdoc#2606]
## Description

Add support for VK_EXT_depth_clip_control extension. It allows to match NDC depth value range to OpenGL and thus helps with code migration. Info about the state in the UI and proper replay handling would be enough. 

## Environment

* RenderDoc version: 1.20
* Operating System: Windows/Linux
* Graphics API: Vulkan

**Comment by baldurk** [comment]
This was implemented in #2688 which is now merged.
