### ISSUE TITLE
Renderdoc Attached to Unity met an abnormal Texture Viewer

### ISSUE THREAD

**Issue by zrp2016** [baldurk/renderdoc#2612]
## Description

 Texture Viewer of RD showed wrongly with content of backbuffer color

## Steps to reproduce

1.Its a RD plugin in Unity,I always use it for debugging captured image.As I click RD button in Unity,double click the captured img in Rd window,there is a correct showing of texture viewer as following:
![image](https://user-images.githubusercontent.com/17512844/174061706-b80e2da1-9c2e-46a2-99dd-748df31b9a7d.png)

2.Then something went wrong in some unity project as I use RD,with the same operation as above,I get a confusing result as following:
![image](https://user-images.githubusercontent.com/17512844/174062154-566daef5-e8b7-4200-9071-940acd03ee16.png)
what's the backbuffer color，I dont know how did it happen,it's can't be fixed with reinstall RD or restart my computer.

3.But I'm sure I did not meet this problem before until unity is crashing this afternoon,which occured when I use RD to capture the current screen where a shader is running.For this shader is running with _Time related logic operations,which I guess resulted in the Unity crashing as I repeat many times and get the same crashing result.

4.And from then on,the RD's texture viewer always show the backbuffer color.Nevertheless,other project useing this plugin shows the correct thing in texture viewer.

What should I do with it?

## Environment

* RenderDoc version: v1.20
* Operating System: Win64

**Comment by baldurk** [comment]
Please provide actual steps I can follow to reproduce what's going wrong, or the capture that is incorrect, or something else that is concrete. Unless I have something I can investigate there is nothing I can do.

If you can't share the capture please provide more information. Is only the backbuffer incorrect, do other textures display fine? If it happens only on some projects then what is the difference between the cases where it works and the cases where it doesn't?

**Comment by zrp2016** [comment]
[1 - copy.zip](https://github.com/baldurk/renderdoc/files/8919154/1.-.copy.zip)
it's the incorrect capture

**Comment by baldurk** [comment]
This seemed to be an issue only on Intel where GLES captures would get inconsistent extensions if some contexts were created as not explicitly GLES.

Note that I strongly recommend against trying to use GLES on desktop, as it doesn't give you any significant portability guarantees given that most desktop drivers will silently let you use GL functionality and the difference between desktop and mobile drivers is orders of magnitude larger than the difference between GLES and a comparable subset of GL. GLES is effectively a broken and worse version of GL for mobiles, but there's no reason to use it on desktop.

**Comment by zrp2016** [comment]
Thankou you,you are awesome.Diffirent Unity project is in different platform,the wrong capture generated in unity in pc platform is using openglES3 API I switch from D3D11 some days ago,and it turns to be correct as I switch back to D3D11. 
And I tried unity in Android using openglES3 works correctly too.
Thank you so much. 666!(equal to awesome in Chinese)
