### ISSUE TITLE
4d8fdf4e31b3d18aba064e138ace17f91bede916 broke aarch64 build

### ISSUE THREAD

**Issue by werman** [baldurk/renderdoc#2614]
## Description

https://github.com/baldurk/renderdoc/commit/4d8fdf4e31b3d18aba064e138ace17f91bede916 unconditionally uses x86-64 asm.

It's invalid on arm, so the build fails with:

```
/tmp/cc9ekx10.s: Assembler messages:
/tmp/cc9ekx10.s:2282: Error: unknown mnemonic `int' -- `int $0x03'

```

## Steps to reproduce

- Try to build RenderDoc on non x86-64 architecture.
- Build fails due to unknown assembly.

## Environment

* RenderDoc version: 0fce39ff04401d1b21c54c4a17addde35dd2d722
* Operating System: Linux on aarch64
* Graphics API: -

**Comment by baldurk** [comment]
ARM is not supported for building on linux, only on Android.

If you would like to PR a fix then that's fine as long as it doesn't break the supported platforms, but this isn't something I will address myself.

**Comment by werman** [comment]
Oh, I see. I'll make one later since RenderDoc support is crucial for development of Vulkan driver on ARM.
