### ISSUE TITLE
glEGLImageTargetTexture2DOES unsupported

### ISSUE THREAD

**Issue by zhaoboqiang** [baldurk/renderdoc#2615]
## Description
In client, renderdoc output:
``` log
OpenGLES. Captures disbabled.
Unsupported function used:
- glEGLImageTargetTexture2DOES
```
The older version of renderdoc can capture.

## Environment

* RenderDoc version: >=1.19
* Operating System: Android 11 (OnePlus 9 5G)
* Graphics API: OpenGLES

**Comment by baldurk** [comment]
Your program must not use extensions without first checking that they are available. If you correctly enumerate which extensions are available you will see which are not supported, and can avoid calling those functions.

**Comment by jilinxiaohuo** [comment]
The same issue on my mi10 phone。It works well after I rollback renderdoc to version1.14。I didn‘t call glEGLImageTargetTexture2DOES in my code，maybe this is a bug in 1.19。
