### ISSUE TITLE
[Bug] Loss of fragment output interface states when rasterizerDiscardEnable is true + VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE

### ISSUE THREAD

**Issue by werman** [baldurk/renderdoc#2617]
## Description

When capturing certain CTS tests RenderDoc could create an invalid per spec situation:
- `rasterizerDiscardEnable` is true
-  There is `VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE`
- `pMultisampleState`, `pColorBlendState`, etc. are NULL

While the spec says:

> If the value of [VkPipelineRasterizationStateCreateInfo](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VkPipelineRasterizationStateCreateInfo)::rasterizerDiscardEnable in the [pre-rasterization shader state](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#pipeline-graphics-subsets-pre-rasterization) is VK_FALSE or the VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE dynamic state is enabled [fragment shader state](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#pipeline-graphics-subsets-fragment-shader) and [fragment output interface state](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#pipeline-graphics-subsets-fragment-output) is included in a complete graphics pipeline.

Meaning that if there is `VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE` - there should be "fragment output interface state".

- In the test Zink creates pipelines with `rasterizerDiscardEnable == true` and `VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE` but with **valid** fragment output interface states.
- In RenderDoc I see these pipelines not having fragment output interface states,

Resulting capture on RADV:  [glcts_2022.06.17_08.39.39_frame0.zip](https://github.com/baldurk/renderdoc/files/8926266/glcts_2022.06.17_08.39.39_frame0.zip)

## Steps to reproduce

- Capture `KHR-GL46.gpu_shader_fp64.builtin.mod_dvec2` through ZINK on RADV or Turnip;
- When opening the capture the driver crashes due to dereference of `pMultisampleState`/`pViewportState`/etc. which are nullptr.  

## Environment

* RenderDoc version: 0fce39ff04401d1b21c54c4a17addde35dd2d722
* Operating System: Linux
* Graphics API: Vulkan
* Driver: RADV or Turnip

**Comment by baldurk** [comment]
I believe that commit should fix the issue. Unfortunately the way the spec is worded RenderDoc needs to match this (somewhat) complex logic to know whether or not pointers are valid and can be dereferenced to serialise, they're not required to either be valid or NULL :(

**Comment by werman** [comment]
Yeah, the spec is too permissive... This commit fixes the issue, thanks!
