### ISSUE TITLE
Poor scaling on captures with large number of drawcalls (> 200k)

### ISSUE THREAD

**Issue by SaschaWillems** [baldurk/renderdoc#262]
I recently made some portability changes to the Vulkan Stardust demo by Intel (see my fork at https://github.com/SaschaWillems/stardust_vulkan, note that the .exe is not updated, so you may have to compile yourself) to make the demo work with other vendors like NVIDIA and AMD.

Trying to load a capture from that demo renderdoc seems to be stuck half-way through loading. 

This seems to be caused by the log file getting spammed with warning messages from an unbound descriptor set :

> RENDERDOC:  [21:14:50]          vk_core.cpp(2140) - Warning - At draw 130, shader referenced a descriptor set 0 that was not bound

Since the demo does lots of draw calls to demonstrate multi-core usage in Vulkan the log file is hammered with those warnings and seems to cause the capture to never finish loading (at least not in a reasonable amount of time).

I have uploaded a package containing the capture and the log file at http://www.saschawillems.de/files/vulkan/renderdoc_stardust.7z

I have not yet checked the example against the validation layers, so I guess this is actually wrong in the example and should be fixed, but it would be great if renderdoc could still load that trace and e.g. omit warnings of the same kind if there are too many of them.

**Comment by baldurk** [comment]
![image](https://cloud.githubusercontent.com/assets/661798/15028395/01df5c48-1249-11e6-96be-9d3bb978fe17.png)

This loads, FYI, but there's more than just that log spam that doesn't scale nicely with the number of drawcalls in this scene (a smidgen over 200,000). I'm going to hang onto this capture/bug as a stress-test of making sure the UI can scale.

**Comment by baldurk** [comment]
Closing this as it seems to have mostly been addressed in the UI rewrite for 1.0. While the UI in v1.4 isn't lightning-fast if you really bump up the number of draws it's at least appropriately speedy given the scope of the capture.
