### ISSUE TITLE
PyCharm 2022.1.2 intelligence not work

### ISSUE THREAD

**Issue by xoyojank** [baldurk/renderdoc#2621]
## Description
cannot import module correcty even if I placed .pyd files in site-packages
![image](https://user-images.githubusercontent.com/2873643/174422449-75997ee8-0b1e-4a7d-aaa5-44742e7a0912.png)

I tried python3.9(recompiled with RENDERDOC_PYTHON_PREFIX64 ) and 3.6, the results are the same
python_stubs has been deleted and the intelligence not work

## Steps to reproduce

![image](https://user-images.githubusercontent.com/2873643/174422181-737bd748-82a1-4b19-978d-b45f48cd84a6.png)
![image](https://user-images.githubusercontent.com/2873643/174422479-e1c1c31c-d090-454f-b9e1-39b943ca7ed6.png)

## Environment

* RenderDoc version: 1.21 (github)
* Operating System: Win11 Pro
* Graphics API: DX12
* Python: 3.6 or 3.9
* PyCharm: 2022.1.2

**Comment by baldurk** [comment]
I can't feasibly help to debug problems in third party programs like pycharm. This is known to work so it's not a bug, I can't help with misconfigurations apart from to suggest checking again with [the documentation](https://renderdoc.org/docs/python_api/dev_environment.html) that explains how to set it up and double check to make sure you have followed all of the steps to ensure the python module is available and can be loaded together with the main DLL.
