### ISSUE TITLE
D3D12 Renderpass crash with MSAA Resolve

### ISSUE THREAD

**Issue by turanszkij** [baldurk/renderdoc#2622]
## Description

Using MSAA Resolve with a DX12 render pass will close the application while RenderDoc is attached. The crash appears to be coming from EndRenderPass() call (D3D12Core.dll)
If RenderDoc is not attached, the application works correctly. I have checked debug layer with GPU Based Validation, and I didn't see an error related to this.

## Steps to reproduce

The attached file contains Editor_Windows.exe, it is a D3D12 application. The crash can be reproduced by Clicking on "Renderer" in the bottom right corner menu, then when a window is drawn, scrolling down to "MSAA" selection box, and choosing "2", "4" or "8" will trigger the crash: [Editor.zip](https://github.com/baldurk/renderdoc/files/8936132/Editor.zip)

Step 1:
![image](https://user-images.githubusercontent.com/12954849/174495172-d8817b6b-9e49-4075-b662-9c239d576294.png)

Step 2:
![image](https://user-images.githubusercontent.com/12954849/174495233-7ffe3c18-3a19-461d-8d41-1d5b8f09f684.png)

If it is running with RenderDoc attached, it will immediately exit the application.

## Environment

* RenderDoc version: v1.20 (built from https://github.com/baldurk/renderdoc/commit/70676a57a4054e310e2550d12b6e0d6787da9495 )
* Operating System: Windows 10
* Graphics API: DirectX 12

Nvidia RTX 2060, driver: 516.40

**Comment by baldurk** [comment]
Thanks for the clear and easy repro, I believe that commit fixes the capture issue as well as some problems I noticed replaying. Please let me know if you notice any other issues since this is an undertested area as I don't think renderpasses are widely used on D3D12 (since I don't think desktop GPUs really do much with them).

**Comment by turanszkij** [comment]
Thank you!
