### ISSUE TITLE
incorrect VS Input Display for R10G10B10A2_UNORM Cast to float in mesh viewer

### ISSUE THREAD

**Issue by xuetaolu** [baldurk/renderdoc#2628]
## Description

VS Input data incorrent in Mesh Viewer

## Steps to reproduce
It is no changes result below
![image](https://user-images.githubusercontent.com/36478973/175512680-ad0b7269-0d09-4b12-9a52-028d8d7d0ef4.png)
out_attr3 is NormalDirection, which calc from in_attr0(ObjectPosition) and in_attr1(ObjectNormal)

but in_attr1(ObjectNormal) display is no incorrect. 

if I edit the vert shader, 
`out_attr3.xyzw = in_attr1.xyzw;`
out_attr3 is not equal to in_attr1
![image](https://user-images.githubusercontent.com/36478973/175513231-10e5050c-827d-436a-8657-b241f63b8606.png)

maybe it cause by the format of in_attr1, which is R10G10B10A2_UNORM Cast to float

I also try to set in_attr1 value manually, using the data showed in mesh view, but the result is also changed.
![image](https://user-images.githubusercontent.com/36478973/175513925-4f86685e-137b-4758-952c-74de9ea23246.png)

## Environment

* RenderDoc version: v1.20 built form 70676a57 Qt version 5.15.2

* Operating System: 
处理器	AMD Ryzen 5 5600G with Radeon Graphics            3.90 GHz
机带 RAM	32.0 GB (31.4 GB 可用)

版本	Windows 10 企业版 G 
版本号	21H2
安装日期	‎2021/‎10/‎14
操作系统内部版本	19044.1766
体验	Windows Feature Experience Pack 120.2212.4180.0

* Graphics API: OpenGL
![image](https://user-images.githubusercontent.com/36478973/175514389-d0cd74cb-fe71-4073-9151-dcb39a39e9f4.png)

* Captured software
Ryujinix 1.1.152
Game Animal Crossing: New Horizons v2.0.5

* the .rdc file:
[rose_weed_4_42_pm.z02.zip](https://github.com/baldurk/renderdoc/files/8975359/rose_weed_4_42_pm.z02.zip)
[rose_weed_4_42_pm.zip](https://github.com/baldurk/renderdoc/files/8975361/rose_weed_4_42_pm.zip)
[rose_weed_4_42_pm.z01.zip](https://github.com/baldurk/renderdoc/files/8975362/rose_weed_4_42_pm.z01.zip)

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
