### ISSUE TITLE
Regression: Crash with D3D11 Compute Shader

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#263]
The following dump was captured with RenderDoc 0.28 x64.
It crashes when trying to check out the only "Dispatch" call.

Funny thing is, it opens ok in RenderDoc 0.27 x64 despite having been captured on a newer version.

I'm uploading a D3D11 version (which crashes):
[CrashD3D11_Sample_TutorialCompute02_UavBuffer_2016.04.28_15.10.03_frame136.zip](https://github.com/baldurk/renderdoc/files/241175/CrashD3D11_Sample_TutorialCompute02_UavBuffer_2016.04.28_15.10.03_frame136.zip)

And a GL version for comparison (which works ok).
[Sample_TutorialCompute02_UavBuffer_2016.04.28_15.15.15_frame392.zip](https://github.com/baldurk/renderdoc/files/241176/Sample_TutorialCompute02_UavBuffer_2016.04.28_15.15.15_frame392.zip)

I can provide the exes too if you want, I would just have to compile the release dlls and package all the media files which I don't have time to do at the moment.

**Comment by baldurk** [comment]
I think this is the crash fixed in 766ab416635feabf3687a582f91b1beee2dc9f53. Can you check a recent nightly build?

It might qualify for needing a new stable build depending on how many people run into this :/.

**Comment by darksylinc** [comment]
Got some time. Crash repro uploaded.
[ReproBins.zip](https://github.com/baldurk/renderdoc/files/241210/ReproBins.zip)

**Comment by darksylinc** [comment]
OK I'll check a nightly

**Comment by darksylinc** [comment]
The crash is fixed in the nightly, however I noticed that 0.27 correctly identified the RWBuffer was an uint, whereas nightly doesn't know the format:

`uint pixelBuffer;` (correct) vs nothing.

It's a minor bug though.

**Comment by baldurk** [comment]
Hmm, when I load the D3D11 log with latest code I get `uint pixelBuffer;` as the format as well. Is that on GL that the format isn't detected?

**Comment by darksylinc** [comment]
Dammit. It works now. Maybe it was some timing issue during the capture or an error on my part. *Sigh*
Sorry for wasting your time.

I'm closing this ticket. Remember you have a test case now for the 200k row enhancement.
