### ISSUE TITLE
Renderdoc segfaults on launch

### ISSUE THREAD

**Issue by Piras314** [baldurk/renderdoc#2637]
## Description

qrenderdoc as well as renderdoccmd both Segmentation Fault on run, I was simply trying to launch the application and I expected it to open.

## Steps to reproduce

On ubuntu 22.04, install renderdoc using `sudo apt install renderdoc` and try running qrenderdoc or renderdoccmd

## Environment

* RenderDoc version: 1.18
* Operating System: Ubuntu Mate 22.04 LTS
* Graphics API: OpenGL 3.3
* APU: AMD A6-3420M APU which uses AMD ATI Radeon HD 6520G graphics.

**Comment by baldurk** [comment]
I do not provide any support for distribution packages.

If you build from source, or use the binary packages from [renderdoc.org](https://renderdoc.org/builds) do they work? Please use an up to date version, v1.18 is relatively out of date though none of the versions crash on launch.

**Comment by Piras314** [comment]
Interesting.. @baldurk so the distribution package was the issue, latest version from your webpage runs just fine it seems. I'll close this now.
