### ISSUE TITLE
Support ARB_shading_language_include

### ISSUE THREAD

**Issue by ItsFlare** [baldurk/renderdoc#2646]
## Description

It appears RenderDoc doesn't process invocations of shaders compiled via `glCompileShaderIncludeARB`, neither does it allow for the source code to be inspected. I'm not sure how widely used this extension is, but support would be in every adopter's interest.

## Environment

* RenderDoc version: 1.20
* Operating System: Windows 10
* Graphics API: OpenGL

**Comment by baldurk** [comment]
This extension is supported, but it looks like there is a bug that wouldn't properly pass through the include paths. So shaders that relied on the search paths would fail to compile properly. That commit fixes it.
