### ISSUE TITLE
Support glEGLImageTargetTexture2DOES API

### ISSUE THREAD

**Issue by Angiewei** [baldurk/renderdoc#2649]
## Description
when I try to capture our game on the phone using v1.20 renderdoc,  inject debug success,  but I can not capture frame, the information on the screen  show "OpenGL. Capture disabled, Unsupported function used: - glEGLImageTargetTexture2DOES" .  I thought it may be an unsupoort feature that you  know, so I want to ask , when is it be supported ? Thank you! 

## Environment

* RenderDoc version: v1.20
* Operating System: Android 10
* Graphics API: OpenGL

**Comment by baldurk** [comment]
This message indicates your program is not behaving correctly. You should not call GL functions for extensions that are not reported as supported - you must first check that the extension is supported before trying to call any functions it provides. If you do, this error message will appear, capturing will be disabled, and the program may not function correctly.
