### ISSUE TITLE
GetSupportedABIs() assumes 64-bit Android support 32-bits as well

### ISSUE THREAD

**Issue by jcortell68** [baldurk/renderdoc#2652]
## Description
The function GetSupportedABIs() in `android_utils.cpp` assumes that a 64-bit Android also supports 32-bit. One of our Android BSPs only supports 64-bit. This means the arm32 apk can't be installed. So, where does the assumption in the code create a problem?

First of all, it's an inconvenience rather than a show-stopping problem. The symptom is that if I reboot my device or terminate the replay server (via the device or via adb), the next time I try to choose the device in RenderDoc, the existing replay server will be uninstalled then re-installed. This has two downsides. First, it's wasteful (time-wise). But far more cumbersome is the fact that, because the server app was uninstalled then reinstalled, I have to re-grant the replay server the permissions it needs. This means interacting with the device, which can be particularly problematic in test-farm environments.

Why does RenderDoc uninstall the replay server app in this environment? This code:
https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/android/android.cpp#L1027

## Steps to reproduce
With an Android arm64 device that does not support arm32
1. Uninstall the replay server with `adb uninstall org.renderdoc.renderdoccmd.arm64`
2. Launch RenderDoc
3. Select the Android device for the replay context
4. Note the permissions-grant screen on the device. This is expected. Grant the requested permissions.
5. Terminate the replay server with: `adb shell am force-stop org.renderdoc.renderdoccmd.arm64`
6. Re-select the Android device for the replay context
7. Note the permissions-grant screen on the device. This is *not* expected and is indicative that the replay server was uninstalled then re-installed.

## Environment

* RenderDoc version: 1.20
* Operating System: 
   * host: ANY
   * device: ANY Android device that supports only 64-bit
* Graphics API: N/A

**Comment by baldurk** [comment]
This is not something I intend to support. I'd be open to a PR if there was a small change that could support such a system but realistically it would need to be very clear that it is safe and won't cause problems on other systems that are supported.

Or as a workaround you could either install and run the server yourself and just connect to it, at which point RenderDoc will only do a simple version check, or else locally modify the source to remove the reference to arm32.

**Comment by jcortell68** [comment]
> else locally modify the source to remove the reference to arm32.

That's what I did, and it sounds like the path of least resistance. I'll stick with it. I mostly wanted to document and share awareness of the issue via this ticket.
