### ISSUE TITLE
Per-render-pass duration timing for TB(D)R

### ISSUE THREAD

**Issue by James2022-rgb** [baldurk/renderdoc#2659]
## Description
Partially a duplicate of #2335 , but intended for solving a different problem.

The "Time durations for the actions" feature as it stands inserts a `vkCmdWriteTimestamp` query before and after each draw command and subtracts the results to fetch the per-draw-call GPU timings,
and the duration value for a `vkCmdBeginRenderPass` is simply the sum of its child draw commands' duration values.

While this can be useful on immediate-mode rendering GPUs, any timestamp value inside a render pass is nonsensical[^tbdr-timestamp-behavior] on tile-based rendering GPUs including Adreno and Mali; "draw calls" do not exist in any meaningful discrete form, making the very concept of timing them entirely meaningless.
From this it follows that the value for a `vkCmdBeginRenderPass` is also nonsensical on these GPUs.

What _can be_ useful on TB(D)Rs is inserting a timestamp query before and after each render pass and subtracting the results to yield per-render-pass GPU timings.
Of course this still is subject to non-trivial error due to pipelining of render passes on TB(D)R etc. , but RenderDoc is not a profiler and this type of timings is still very useful.

As for the actual change that would be needed, I don't imagine it to be too far from what is noted on #2335.
(I've only had a cursory look on `FetchCounters` etc.)

I'm more than happy to invest my time if you're open to accepting a PR for this, but I'm definitely going to need directions.

## Environment

* RenderDoc version: 1.20
* Operating System: Android
* Graphics API: Vulkan

(Worth noting is that the same reasoning should hold for Metal on Apple SoCs, seeing that Metal support seems to be in development)

[^tbdr-timestamp-behavior]: At least on [Adreno](https://gitlab.freedesktop.org/mesa/mesa/-/blob/6de68c5dcad60c354856a0a574c711e5fc2f5d0a/src/freedreno/vulkan/tu_query.c#L1590) and [Mali](https://community.arm.com/support-forums/f/graphics-gaming-and-vr-forum/6869/gl_ext_disjoint_timer_query-for-performance), the actual value we get _seems_ to be the timestamp value written when the last executed tile's fragment shading completes for the draw call, having been overwritten with each tile execution, but this behavior is in no way defined by the API.

**Comment by baldurk** [comment]
RenderDoc is not a profiler and there are no plans to change that in the foreseeable future, so new profiling-related features and improvements like this are effectively not in scope for the project. Any changes to the existing profiling features are restricted purely to porting of the functionality already exposed (e.g. to new APIs or IHV toolkits for per-draw counters).
