### ISSUE TITLE
VK_EXT_acquire_drm_display extension support

### ISSUE THREAD

**Issue by bl4ckb0ne** [baldurk/renderdoc#2664]
## Description

I'm trying to debug [Monado](https://gitlab.freedesktop.org/monado/monado) on Wayland, and it is using the functions from the [VK_EXT_acquire_drm_display](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_acquire_drm_display.html) to create a VkSurface for the HMD. 

Renderdoc fails to capture because the instance extension is not yet supported. 

## Environment

* RenderDoc version: v1.17
* Operating System: AlpineLinux
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Note that wayland is also not supported, see #853 .

**Comment by bl4ckb0ne** [comment]
Ive managed to get successful captures with GL on Wayland, with `QT_QPA_PLATFORM=xcb`. The extension itself is not designed for Wayland tho, so it should not be a problem.

**Comment by jansol** [comment]
That makes you run in Xwayland. Was the captured application perhaps running in Xwayland too? That would make it just a normal X11 capture.

**Comment by bl4ckb0ne** [comment]
Ive managed to run a capture from OpenGL with `qrenderdoc` using `QT_QPA_PLATFORM=wayland-egl`, but I need `QT_QPA_PLATFORM=xcb` to be able to replay that capture.

In this case Wayland is not require for the extension to work, but uses information sent by the compositor (DRM FD, connector ID). 
`

**Comment by misyltoad** [comment]
+1

I would also like this for SteamVR and other projects.

**Comment by baldurk** [comment]
That commit should add support for this extension, but I have no way of testing this myself. It's straightforward enough that I don't expect any problems but let me know if it doesn't work.

**Comment by bl4ckb0ne** [comment]
Ill try to give it a go soon, thanks!
