### ISSUE TITLE
Crash when opening the texture viewer after loading a Vulkan trace

### ISSUE THREAD

**Issue by SaschaWillems** [baldurk/renderdoc#267]
If the texture viewer tab is not visible and a Vulkan trace is loaded, renderdoc crashes when opening the texture viewer tab.

This happens with the latest release as well as a self-compiled version from the master branch.

It looks like the swap chain can't be created and returns a validation failed ext error :

![2016-05-04 20_51_50-renderdoc debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/10283127/15025565/2428aed0-123a-11e6-8ce5-b5dee17958c9.png)

I can reproduce this with all Vulkan sample applications I have tested and attached a small replay file from my triangle example :

[triangle_replay_renderdoc.zip](https://github.com/baldurk/renderdoc/files/249393/triangle_replay_renderdoc.zip)

System details :
Windows 7 x64
NVIDIA GTX 980
Vulkan SDK 1.0.11.0

**Comment by baldurk** [comment]
By a circuitous route I think the above mistaken code was getting an invalid (or perhaps valid but not shown) window handle through to the create swapchain. I'm not sure if that should break, but it's easily fixed. Let me know if this works for you, it did for my repro at least.

**Comment by SaschaWillems** [comment]
I can confirm that this is fixed. Thx :+1:
