### ISSUE TITLE
Crash when starting vulkan fragment shader debug

### ISSUE THREAD

**Issue by AirGuanZ** [baldurk/renderdoc#2670]
## Description

RenderDoc crashes when I start debugging a Vulkan fragment shader.

## Steps to reproduce

1. Load the attached capture file.
2. Navigate to `Color Pass #1/vkCmdDraw(6, 1)` (the only one drawcall)
3. Debug any pixel on the output quad. This will immediately trigger the crash.

[test.zip](https://github.com/baldurk/renderdoc/files/9228046/test.zip)

## Environment

* RenderDoc version: v1.21
* Operation System: Windows 11 22000.795
* Graphics API: Vulkan

## Misc

I tried to figure out how this crash happens with a local debug-built RenderDoc.

Source version: commit 44a1de01d48ecf5d542f5c1f766d542b75b6f831

1. `renderdoc\driver\shaders\spirv\spirv_debug_setup.cpp, line 1452` uses `var.type != VarType::Struct` to exclude the structure types, without considering `VarType::Unknown`. In this capture, `var.type` does be `VarType::Unknown`, while it's actually a structure type.
2. Then `sourceVar.rows/columes` are copied from `var`, which are 0s.
3. At `line 1463`, the sourceVar without any `variables` are pushed back to `state.sourceVars`. A later access at `qrenderdoc\Windows\ShaderViewer.cpp, line 3931` assumes the `variables` are non-empty, thus triggering the crash.

Replacing `var.type != VarType::Struct` with `var.type != VarType::Struct && var.type != VarType::Unknown` mentioned in `1.` seems to be able to fix this problem. However, I'm not sure this is the root problem. So I created this issue instead of a PR.

Thank you for making this nice tool!

**Comment by baldurk** [comment]
Can you please give more information about how you compiled your shader? It looks like you have compiled with an unsupported/undocumented set of compile flags.

**Comment by AirGuanZ** [comment]
[Quad.zip](https://github.com/baldurk/renderdoc/files/9234193/Quad.zip)
The shader was slightly modified so I cannot strictly reproduce the originally compiled result. But it can still cause a crash.
I compile the shader with:
```
dxc.exe Quad.hlsl -E VSMain -T vs_6_0 -spirv -fvk-use-dx-layout -fvk-use-dx-position-w -fspv-target-env="vulkan1.3" -fvk-stage-io-order=alpha -Od -Zi -fspv-debug=vulkan-with-source
dxc.exe Quad.hlsl -E FSMain -T ps_6_0 -spirv -fvk-use-dx-layout -fvk-use-dx-position-w -fspv-target-env="vulkan1.3" -fvk-stage-io-order=alpha -Od -Zi -fspv-debug=vulkan-with-source
```
DXC version is the recent [official release](https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.7.2207/dxc_2022_07_18.zip)

**Comment by baldurk** [comment]
The `-fspv-debug=vulkan-with-source` parameter is not documented and is not yet producing stable output. Note also that `-Od` is not guaranteed to produce valid SPIR-V as HLSL as a language is not tightly specified and requires legalisation optimisations.
