### ISSUE TITLE
Shader source attachment is no longer visible for Vulkan with Dolphin

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2673]
## Description

Captures from Dolphin have no source attachment when opened in RenderDoc v1.21, though they did in the past.  This seems to be related to Dolphin not setting a source file name (see #2337), as setting one does result in it working, but this still prevents using captures from older versions of Dolphin (and older versions of RenderDoc).

```patch
diff --git a/Source/Core/VideoCommon/Spirv.cpp b/Source/Core/VideoCommon/Spirv.cpp
index 0fc22e1731..c909ee33a2 100644
--- a/Source/Core/VideoCommon/Spirv.cpp
+++ b/Source/Core/VideoCommon/Spirv.cpp
@@ -124,8 +124,9 @@ CompileShaderToSPV(EShLanguage stage, APIType api_type,
   if (g_ActiveConfig.bEnableValidationLayer)
   {
     // Attach the source code to the SPIR-V for tools like RenderDoc.
     intermediate->addSourceText(pass_source_code, pass_source_code_length);
+    intermediate->setSourceFile("Generated");
 
     options.generateDebugInfo = true;
     options.disableOptimizer = true;
     options.optimizeSize = false;
```

* D3D12 and D3D11 are not affected, but this isn't particularly useful as since https://github.com/dolphin-emu/dolphin/pull/10673, HLSL shaders are generated using SPIRV-Cross, which makes them less readable (as comments are not present).
* This issue affects both debugging a pixel or vertex and viewing a shader's source from the pipeline state tab.

## Steps to reproduce

1. Launch Dolphin via RenderDoc.
2. Under Graphics, set the backend to Vulkan on the general tab, and check "Enable API Validation Layers" on the advanced tab (which also enables source attachment, see dolphin-emu/dolphin#9996)
3. Open the [Lesson08 test case](https://fifo.ci/media/dff/Lesson08.dff)
4. Wait for the capture to complete
5. Stop emulation and close Dolphin
6. In renderdoc, go to a draw, and then attempt to debug a pixel
7. Observe that shader disassembly is present, but no source is present

This affects captures from previous versions of RenderDoc and Dolphin (including ones from some of my earlier bug reports, such as [this one](https://github.com/baldurk/renderdoc/files/6949540/Lesson08Vulkan.zip)), not just ones saved with current Dolphin/RenderDoc.

## Environment

* RenderDoc version: v1.21
* Operating System: Windows 10.0.19044.1826
* Graphics API: Vulkan

I think this issue wasn't present in v1.20, but I'm not 100% certain of this. It definitely wasn't present in v1.19. My guess is that this is related to the "Vulkan: Don't generate an empty source file when an `OpSource` is encountered with no source, only a language (and/or filename)." change mentioned in v1.21's changelog.

**Comment by baldurk** [comment]
That should fix the issue I believe, though I would strongly suggest that you apply that diff on your side to give your files a default filename, as I wouldn't be surprised if other tools have bugs/issues around this since a file without a filename generally doesn't make sense. This is also likely to break in future in RenderDoc if you have multiple files without filenames as they'll no longer be distinguishable.

**Comment by Pokechu22** [comment]
Thanks!

> This is also likely to break in future in RenderDoc if you have multiple files without filenames as they'll no longer be distinguishable.

Wouldn't the same thing happen if all of the files have the exact same default filename? (For the most part, I haven't had any issue finding the right shader since I'm usually finding it by looking for a specific event and then debugging a specific pixel or vertex, so the name is irrelevant. Dolphin also has a _lot_ of generated shaders, so looking through a big list of them wouldn't be super useful, but I imagine with more typical programs this is less of an issue.)

**Comment by baldurk** [comment]
To clarify I mean having multiple source files _in the same SPIR-V module_ with the same filename would be a problem, but different modules with the same filename is totally fine (blank or not).

**Comment by Pokechu22** [comment]
Done: dolphin-emu/dolphin#10945. I believe Dolphin currently only ever has one source file per module, but that is something to keep in mind.
