### ISSUE TITLE
Grouped GPU timings wrong with glMultiDrawArrays

### ISSUE THREAD

**Issue by LordOfDragons** [baldurk/renderdoc#2679]
## Description

Taking a capture of a rendering using multiple calls to glMultiDrawArrays causes the group added by RenderDoc (here "Depth-only Pass") to show the summed GPU time of all calls in the group excluding glMultiDrawArrays calls. This causes the summed GPU time to be wrong which makes it hard to analyse the rendering.

## Steps to reproduce

This bug happens with all renderings, no matter if depth-only, color-only or color-depth mixed.

Render a glClearBufferfv followed by one or more glMultiDrawArrays. Optionally repeat this but a clear followed by a render call is enough to show the problem. Even render a single triangle is enough. Take a capture and let RenderDoc calculate GPU timings. The render pass group is going to show only the sum of the glClearBufferfv calls but misses the glMultiDrawArrays calls.

The screenshot below shows a capture using a regular glDrawArrays (which shows the correct GPU timing sum) and next to it one using glMultiDrawArrays (which shows the incorrect GPU timing sum).
[Screenshot](http://rptd.ch/misc/debug/renderdoc_wrong_timing.png)

## Environment

* RenderDoc version: 1.21
* Operating System: GenToo
* Graphics API: OpenGL

**Comment by baldurk** [comment]
This was not limited to glMultiDrawArrays, but was specific to the fake added markers. If you add proper markers (as I'd recommend for any non-trivial program) it would accumulate the times properly. That commit fixes it to work in either case.

Please note RenderDoc is not a profiler, so using it for performance analysis is not a supported use case.

**Comment by LordOfDragons** [comment]
Thanks. With neither the AMD nor the nVidia performance tool working properly under Linux, RenderDoc is the only tool available to get examine performance problems better. It's not perfect but helps.

**Comment by LordOfDragons** [comment]
@baldurk I tried finding documentation on these "markers" but failed. Can you point me to the documentation part which states how I add such "markers" in RenderDoc for OpenGL use?

**Comment by baldurk** [comment]
Markers are not RenderDoc specific, every API provides ways of adding markers since they are used by almost all graphics tools.

Searching the RenderDoc documentation for 'marker' goes to this page: [How do I annotate a capture?](https://renderdoc.org/docs/how/how_annotate_capture.html?highlight=marker) which shows the process in general, and specifically for OpenGL using the `KHR_debug` extension.

**Comment by LordOfDragons** [comment]
Thanks. That should help.
