### ISSUE TITLE
VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT and VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT with Android 11+ and Vulkan 1.1

### ISSUE THREAD

**Issue by Goshido** [baldurk/renderdoc#2681]
## Description

_RenderDoc_'s command server can't establish **full** connection (explain later) with my own _Vulkan_ C++ application for _Android_ (called `android-vulkan`). I able to find package and run application from _RenderDoc_'s _GUI_. But after that the application failed during initialization inside native code. So obviously I'm not able to make a capture.

`android-vulkan` project uses _Vulkan validation layers_ from commit `bbff1dc59468540736f2535cdfbad3ff436e26ec` _[Date: 7/21/2022]_. In addition two more optional validation categories are activated:

- `VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT`
- `VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT`

At this point `android-vulkan` project does not produce any warning, performance or error messages except the following from _best practices_ category:

Description | Reason
--- | ---
Attempting to enable deprecated extension VK_EXT_debug_report, but this extension has been deprecated by VK_EXT_debug_utils. | There is no alternative on _Android 11_ platform.
Attempting to enable extension VK_EXT_debug_report, but this extension is intended to support use by applications when debugging and it is strongly recommended that it be otherwise avoided. | Yeah. I'm pretty aware about that. Thank you.
Allocating a VkDeviceMemory of size XXX. This is a very small allocation (current threshold is XXX bytes). You should make large allocations and sub-allocate from one large VkDeviceMemory. | Should think about it. Custom memory allocator task.
Trying to bind VkImage (...) to a memory block which is fully consumed by the image. The required size of the allocation is 1088, but smaller images like this should be sub-allocated from larger memory blocks. | Should think about it. Custom memory allocator task.
Performance Warning: This app has > 250 memory objects. | Should think about it. Custom memory allocator task.

So I think current implementation is more or less normal from _Vulkan_ usage point of view.
I also tired to disable _Vulkan_ validation layers to not mess around _RenderDoc_'s own Vulkan layers and system _Vulkan_ loader. But unfortunately it did not help. The result behavior is identical.

I also found strange error from `android-vulkan` as well when _RenderDoc_ is active:

```logcat
2022-08-09 06:24:45.004 E/android_vulkan::C++: Renderer::TryAllocateMemory - Can't allocate image memory
(Texture2D::CreateCommonResources). Hardware does not support the following memory type:
VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT.
2022-08-09 06:24:45.080 I/renderdoc: @62f1d37d00000299@ __rdoc_internal_android_logcat 3505458
```

Indeed `android-vulkan` is using an optimization with `VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT` and `VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT` to use tile memory for render targets as _best practices validation_ suggests. I'm familiar with some _RenderDoc_ "faking" concepts to get more information from the app. The best example is _GLES_, shader blobs, and faking _glGetProgramiv_ + `GL_LINK_STATUS` to get shader source from the application. Or faking `glGetString(i)` to publish [`GL_EXT_debug_label`](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_debug_label.txt) extension with further emulation. Maybe similar concepts are applied to _Vulkan_? If so could it be improved to make real support of the `VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT` and `VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT`?

## Steps to reproduce

1. Pickup _Android 11+_ device with _Vulkan_ support
2. Install debug _apk_ (direct link is [here](https://drive.google.com/file/d/1e3euzSArJFNJBzqqH4DrxRR5OxNPo9jH/view?usp=drivesdk))
3. Start _RenderDoc 1.21_
4. Start `logcat` with filter regexp for tag `^(?:android_vulkan\:\:C\+\+|libc|DEBUG|gralloc|ion|Gralloc3|renderdoc)$`. My suggestion is to use _Android Studio_ with custom filter.
5. Run _RenderDoc_ session. package: `com.goshidoInc.androidVulkan`, activity `com.goshidoInc.androidVulkan.Activity`

**Problem:** The _Capture Frames(s) Immediately_ button is not active. The _RenderDoc_'s connection state: Established. API state: Vulkan (Not Presenting). There is an error near _Vulkan_ memory index selection:

```logcat
2022-08-09 06:24:45.004 E/android_vulkan::C++: Renderer::TryAllocateMemory - Can't allocate image memory
(Texture2D::CreateCommonResources). Hardware does not support the following memory type:
VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT.
2022-08-09 06:24:45.080 I/renderdoc: @62f1d37d00000299@ __rdoc_internal_android_logcat 3505458
```

**Expected:** The _Capture Frames(s) Immediately_ button is active. `VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT` and `VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT` supported.

## Environment

* RenderDoc version: _1.20_ and _1.21_
* Operating System: _Android 11_ and _Android 12_; _Windows 10 (10.0, Build 19041)_ and _Windows 11 (10.0, Build 22000)_
* Graphics API: _Vulkan 1.1.131_
* GPUs:
  - [_Android 11, Mali-G76, driver 26.0.0_](http://vulkan.gpuinfo.org/displayreport.php?id=12030)
  - _Android 12, Adreno 660, driver 512.530.0_

**P.S.** The `Diagnostic log` window is missing in recent _RenderDoc's_ versions. I'm curious what's the reason for this? I can't find any details in the internet, bug tracker or release changelog.

**Comment by baldurk** [comment]
I'm sorry I've read your description but there's quite a bit of unrelated information so I'm not quite sure I'm understanding the relevant description of the bug.

If I've understood right you're seeing an error message about not seeing a memory type with VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT, but that error is coming from your application? If your application is assuming the presence of such a memory type then that is the problem. There is no guarantee of that in the vulkan specification so you cannot assume it will be available if you want your application to be portable, you need to have a fallback for drivers where it's not advertised.

You say at the start of the description that you can't connect to the application though which sounds like a different problem, but I'm unclear where that comes from exactly or under what circumstances.

Please note that the validation layers have absolutely nothing to do with RenderDoc, they are a separate project entirely. I generally do not recommend using the validation layers together with RenderDoc as this can cause false positives and negatives and bugs in one could cause mistaken results in the other.

**Comment by Goshido** [comment]
> If I've understood right you're seeing an error message about not seeing a memory type with VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT, but that error is coming from your application? If your application is assuming the presence of such a memory type then that is the problem. 

This memory type disappeared only if _RenderDocCmd_ is running. Without any _RenderDocCmd_ running instance such memory presents and `android-vulkan` works as intended.

> There is no guarantee of that in the vulkan specification so you cannot assume it will be available if you want your application to be portable, you need to have a fallback for drivers where it's not advertised.

I perfectly understand that such type of memory is optional. My goal is not to create portable solution for every single smartphone or PC. I limited small amount of devices which I have and small amount of _Android OS_. I just need to know that removing `VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT` feature is required by _RenderDocCmd_ to preview render targets in _RenderDoc_ client _PC_ side (just speculation). I mean it's by design of the _RenderDoc_ implementation, it has strong reason and there is nothing to do with that.

> I generally do not recommend using the validation layers together with RenderDoc as this can cause false positives and negatives and bugs in one could cause mistaken results in the other.

Roger that.

**P.S.** It is perfectly fine for me to adopt `android-vulkan` project to have fallback to another memory type. _RenderDoc_ integration is too important for project because there is no too many tools such caliber on _Android_ platform.

**Comment by baldurk** [comment]
Yes RenderDoc makes no more guarantees than the specification about available features. If you want to write an application which is very specialised to only run on one or two devices/drivers and is not portable, then the cost of that is that RenderDoc may not work. This is not a bug but intentional behaviour in the presence of optional features which RenderDoc may not support.

This case is no different to any other optional or vendor-specific extension which RenderDoc does not support, except that it's much easier to write code which transparently makes use of this feature (the expectation is that a sensibly written application will set `VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT` and then prefer memory types with `VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT` when selecting a memory type from those available, but not require it. That way it will make use of the hint if available and gracefully handle things if it's not).

**Comment by Goshido** [comment]
Thank you for such great response @baldurk 👍
