### ISSUE TITLE
Can RenderDoc support Vk 1.3 without bufferDeviceAddressCaptureReplay?

### ISSUE THREAD

**Issue by meup** [baldurk/renderdoc#2682]
## Description

This question relates to issue #2653.  I have a hardware that supports Vk 1.3 but doesn't support the bufferDeviceAddressCaptureReplay feature of bufferDeviceAddress.

For the previous app I was working with, I was able to work with how RenderDoc reverts to Vk 1.2 support in this situation.

However, a new app has come up that depends upon Vk 1.3 features (such as extended dynamic state 2).

I am faced with the choice:
- Try to get hardware vendor to support bufferDeviceAddressCaptureReplay
- Try to get RenderDoc to support Vk 1.3 without bufferDeviceAddressCaptureReplay
- Put up with no RenderDoc for this app

I am wondering if it is possible for RenderDoc to maintain Vk 1.3 support even when bufferDeviceAddressCaptureReplay is not present?

Btw, the app is also going to use extended dynamic state 3, so support for that will be needed as well, eventually.

## Environment

* RenderDoc version: 1.20
* Operating System: (private)
* Graphics API: Vulkan

**Comment by baldurk** [comment]
No this is not possible. Vulkan 1.3 requires support for bufferDeviceAddress, and capturing bufferDeviceAddress requires bufferDeviceAddressCaptureReplay. There is no legal way to advertise Vulkan 1.3 support without also advertising bufferDeviceAddress that is then impossible to support, so instead RenderDoc does not advertise Vulkan 1.3 support. It still advertises all the supported component features and extensions that comprise 1.3.

I mentioned this to Khronos at the time and this was a deliberate decision - I believe the expectation is that drivers that don't already support bufferDeviceAddressCaptureReplay will do soon.
