### ISSUE TITLE
Exception in OpenGL Intel drivers when launching from RenderDoc

### ISSUE THREAD

**Issue by weary-adventurer** [baldurk/renderdoc#2692]
## Description

I have a simple OpenGL program that uses GLFW:

```c
#include <stdio.h>

#include <glad/glad.h>
#include <GLFW/glfw3.h>

#pragma comment(lib, "glfw/lib-vc2022/glfw3dll.lib")

int main() {
    if (!glfwInit()) {
        fprintf(stderr, "glfwInit() failed\n");
        return 1;
    }

    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 6);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

    GLFWwindow* window = glfwCreateWindow(800, 600, "My window", NULL, NULL);
    if (window == NULL) {
        glfwTerminate();
        fprintf(stderr, "glfwCreateWindow() failed\n");
        return 1;
    }

    glfwMakeContextCurrent(window);

    if (!gladLoadGLLoader((GLADloadproc) glfwGetProcAddress)) {
        glfwTerminate();
        fprintf(stderr, "gladLoadGLLoader() failed\n");
        return 1;
    }

    glfwSwapInterval(0);

    printf("GL_VENDOR: %s\n", glGetString(GL_VENDOR));
    printf("GL_VERSION: %s\n", glGetString(GL_VERSION));
    printf("GL_RENDERER: %s\n", glGetString(GL_RENDERER));

    while (!glfwWindowShouldClose(window)) {
        glfwPollEvents();

        glClearColor(0.1f, 0.2f, 0.3f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);

        glfwSwapBuffers(window);
    }

    return 0;
}
```

When compiled with:

```console
cl /I ./glad/include /I ./glfw/include /Zi main.c ./glad/src/glad.c
```

It prints the strings and opens an empty blue window:

```
GL_VENDOR: Intel
GL_VERSION: 4.6.0 - Build 26.20.100.7811
GL_RENDERER: Intel(R) UHD Graphics 630
```

![image](https://user-images.githubusercontent.com/30081929/185141349-faaa5d1d-7fbf-48b3-aac6-8f23a2963e0e.png)

But when launched from RenderDoc, it triggers an exception:

![unhandled](https://user-images.githubusercontent.com/30081929/185142040-0ddf890e-5de8-43f2-9920-6b2a75233878.png)

When opened in the Visual Studio debugger, it seems the exception happens in the `glfwCreateWindow` call:

![exception](https://user-images.githubusercontent.com/30081929/185142533-5b1c05f7-1884-4d12-9842-b172315dd7da.png)

Looking at the call stack, it looks like some Intel driver code is reading something from a NULL pointer:

![null_ptr](https://user-images.githubusercontent.com/30081929/185143328-f3b921ff-a558-4bf0-b529-d1a047e1ee65.png)

---

This is running on a laptop that has two graphics cards.

When forced to use the NVIDIA card with this code:
```c
__declspec(dllexport) unsigned int NvOptimusEnablement = 0x00000001;
```

The application successfully launches in RenderDoc:

![image](https://user-images.githubusercontent.com/30081929/185147199-1f7bc9c9-4a37-4754-b8a2-4546f787d84a.png)

## Steps to reproduce

1. Compile the program
2. Use Launch Application in RenderDoc to run the compiled program from an Intel GPU

## Environment

* RenderDoc version: v1.21 (built from 98a93408)
* Operating System: Windows 10.0.19043
* Graphics API: OpenGL 4.6 with GLFW 3.3.8

**Comment by baldurk** [comment]
Can you please test with the latest nightly build? I believe this is the same bug as #2691 .

**Comment by weary-adventurer** [comment]
> Can you please test with the latest nightly build? I believe this is the same bug as #2691 .

Works great in v1.22 dd47f5a3!

**Comment by BleuBleu** [comment]
Oh thanks so much for the fix! I was having the same issue. Nightly is working. :)

-Mat
