### ISSUE TITLE
Take into account that functions from VK_EXT_extended_dynamic_state are in VK 1.3

### ISSUE THREAD

**Issue by werman** [baldurk/renderdoc#2695]
## Description

If application doesn't require `VK_EXT_extended_dynamic_state` but relies on corresponding functions to be in VK 1.3, RenderDoc just never calls the dynamic state functions when inspecting pipeline (in `VulkanRenderState::BindPipeline`).

Because their call is gated behind `vk->ExtendedDynamicState()` which depends on whether `VK_EXT_extended_dynamic_state` was required by the application.

In my particular case the issue is that `CmdBindVertexBuffers2` is never called and this somehow brings down my whole qcom board =(

## Steps to reproduce

- Capture an app that doesn't require `VK_EXT_extended_dynamic_state` but uses corresponding dynamic state set function for VK 1.3
- In capture select any draw which expect dynamic state set.

Sorry, I don't have a capture I could share.

## Environment

* RenderDoc version: 6bd7e7cc1ae2f9795caeec0280f4bc8992abf445
* Operating System: Linux, any
* Graphics API: Vulkan

**Comment by baldurk** [comment]
From your description I think that commit should fix it, but without a repro I can't confirm. Can you check to see if that addresses the problem?

I think this was missed because unlike e.g. `separateDepthStencilLayouts` there's a feature bit for the extension but no feature bit when promoted.

**Comment by werman** [comment]
Yep, fixed now. Thanks!
