### ISSUE TITLE
Transformice | No interface | Linux/Windows

### ISSUE THREAD

**Issue by justuser-31** [baldurk/renderdoc#2699]
## Description

Running game "Transformice" from Renderdoc.
Interface of program is not shown or game is not shown.
With other games it works.

transformice.sh (official script):
\------------------------------------------
\#!/usr/bin/env bash

\# Important pour le préchargement d'electron
LD_PRELOAD="" ./Transformice
\---------------------------------------------

## Steps to reproduce

https://user-images.githubusercontent.com/53183489/186139816-62e4ee31-dbc0-45b0-8263-26edfeaf73d2.mp4

## Environment

* RenderDoc version: 1.21 / 1.12 / 1.5 (I tried this versions)
* Operating System: Linux 5.18 / Windows 10
* Graphics API: Vulkan (Nvidia + Linux) / D3D11 (Default in Windows)

* Model GPU: Nvidia Geforce GTX 1050
* Driver: 515

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Comment by justuser-31** [comment]
Good,but i founded solution.(It can be and my game, doesn't matter. And...Not you help me,somebody else help.)

## Add "&& bash transformice.sh" to command-line args.
Maybe need run first game from bash.

https://user-images.githubusercontent.com/53183489/186146909-c388d1eb-a2d8-4235-8891-6521cc0329af.mp4
