### ISSUE TITLE
Colorize debug marker entries from VK_EXT_debug_marker

### ISSUE THREAD

**Issue by SaschaWillems** [baldurk/renderdoc#270]
VkDebugMarkerMarkerInfoEXT structure contains a field for passing debug marker colors to a debugging application.

It would be nice if these colors would also be used in the Event browser to make debug markers a bit easier to distinguish from actual API calls :wink:

**Comment by baldurk** [comment]
Yeh colors have been there since the original d3d9/d3d11 markers, but I've not applied them. It probably shouldn't be too hard but there's a question of how to display them - should the whole section underneath a marker (until the next one, I guess) be coloured? or just the root node?

I suspect just the root node. I'll have to experiment though :).

**Comment by SaschaWillems** [comment]
The "how" part is tricky I guess, especially as colors can be set to any value (including white). And white text on white background is hard to read.

Maybe it's possible to do something like the productivity power tools for Visual Studio :

![vs_colors](https://cloud.githubusercontent.com/assets/10283127/15532080/2a85e818-225e-11e6-9526-7ace595962da.png)

And color the lines with the colors set by the debug marker?

**Comment by baldurk** [comment]
I was thinking that the node would get its background colour from the marker colour, and the text would automatically pick a contrasting colour for visibility.

Hastily drawn poor mockup:

![image](https://cloud.githubusercontent.com/assets/661798/15532571/ba26b130-2260-11e6-9398-95e1edb86d6a.png)

But this could be a configurable option depending on how many different permutations I'm willing to implement :).

To some degree I'm willing to give people enough rope to hang themselves with - if you pick alternating black and white then it will look horrible... but that's what you asked for!

**Comment by SaschaWillems** [comment]
Looks fine, and developers are responsible for the colors anyway :wink: 

But one thing that I'm finding a bit hard (which is mostly the fault of how a tree view works) is spotting the actual scope of the debug region, and especially where it ends.

Having some kind of visual queue in there would surely help. Not sure how to implement that (or if it's actually possible with the tree view you use) but this is something I threw together in PS :

![renderdoc_debugregions](https://cloud.githubusercontent.com/assets/10283127/15550552/35bdb392-22b2-11e6-9690-4956d8fd00db.png)

**Comment by baldurk** [comment]
Yes that's a fair point, there should be something to show the extent of the section. I'll need to play around with it a bit, because e.g. in that example the green is slightly visible on render scene but basically invisible on the line because it's so thin.

**Comment by baldurk** [comment]
I've done a first pass at this, here's what it looks like roughly (garish colours I chose not withstanding):

![image](https://cloud.githubusercontent.com/assets/661798/15615816/aa5e8a02-2440-11e6-900e-e217d5943f59.png)

There are options to control whether colouring is enabled at all, and to control whether or not the row on the event browser or just keep the vertical bar on the side.

**Comment by SaschaWillems** [comment]
Perfect. Looks even better than I imagined :+1:
