### ISSUE TITLE
"Dianostic log" is missing in 1.21

### ISSUE THREAD

**Issue by Darkgrouptw** [baldurk/renderdoc#2701]
## Description
"Dianostic log" is missing in RenderDoc ver1.21
It's not in "Window" => "Diagnostic Log"

## Steps to reproduce
1. Install https://renderdoc.org/stable/1.21/RenderDoc_1.21_64.msi
2. Choose Complete Install
3. Open RenderDoc

## Environment

* RenderDoc version: 1.21
* Operating System: Windows10 (x64)

**Comment by iiiwk** [comment]
Misleading information removed.

**Comment by Darkgrouptw** [comment]
Thank you so much!!!

**Comment by baldurk** [comment]
The diagnostic log is *not* intended for users, it is for RenderDoc developers only. Please do not comment, trying to answer issues on my behalf.
