### ISSUE TITLE
cannot configure python module with Python 3.6.4 & PyCharm 2020.3.3

### ISSUE THREAD

**Issue by noobdawn** [baldurk/renderdoc#2704]
## Description

Maybe the doc "Python development environment" need to be updated? I tried about 3 hours to configure python module, but the Intelligence is not working.

At the beginning I thought it was caused by an incorrect version of Python (3.6.8), maybe it was too new to RenderDoc, so I tried 3.6.4, which was told in [#1838](https://github.com/baldurk/renderdoc/issues/1838), it says "3.6.4 by default". But still not works.

I tried to use the enviroment enumerated in the documentation, I installed PyCharm 2020.3.3, but nothing different really happened. I saw the file ".failed__renderdoc" in "python_stubs" directory and content "1.147" within.

Perhaps in the latest few versions, the generated .pyd files are no longer compatible with Python 3.6.

I am a newbie in python, and I am not a native English speaker, this issue is written by google translate, looking forward to your reply : )

## Steps to reproduce

1. Compile RenderDoc(x64) and copy "pymodules" directory.
2. Install PyCharm and python 64-bit executable installer
3. Replace "module_redeclarator.py"
4. Configure python module in project settings
5. Failed to import even if delete the "python_stubs"

## Environment

* RenderDoc version: 1.22 (github)
* Operating System: Win 11 Pro
* Graphics API: DX12
* Python: 3.6.8 / 3.6.4
* PyCharm: 2022.2.1 / 2020.3.3

**Comment by baldurk** [comment]
This works correctly for me following the steps on PyCharm 2022.2.1, and it was working as well on PyCharm 2021. I cannot feasibly provide debugging support for users making mistakes using third party software like that. If you can show clear evidence there is a RenderDoc bug then I can look into it, but this seems like you have not properly configured the interpreter which is out of scope of this project.
