### ISSUE TITLE
Display debug names instead of IDs in API calls

### ISSUE THREAD

**Issue by SaschaWillems** [baldurk/renderdoc#271]
For example buffers that are named will be displayed with their names for API calls that bind them :

![renderdoc_bufferids_apiview](https://cloud.githubusercontent.com/assets/10283127/15554807/1dbc942a-22c6-11e6-9ff9-c75c9a799e03.png)

But the API calls still refer to them by their ID, which is no longer visible in e.g. the vertex input view, making it hard to match between the views. 

Having the API call display the same debug names fro all objects used too would be a nice addition.

**Comment by baldurk** [comment]
Yeh the API calls view is just a raw dump of the serialized data so there's not currently any formatting or niceties like applying names. There's a number of improvements that could be made to it if it were made more intelligent like being able to click on buffers/textures etc to see creation information or jumping to where they are in the pipeline, but I think it will need a refactor of the serialisation system so it's not likely to happen soon.

**Comment by baldurk** [comment]
The new serialisation system mentioned above is now merged, and at least for buffers and textures that already have names given, the UI will display them properly. I'm planning to change things around a bit to pipe through names for other types of objects, which will be related to implementing #356.

Please try with the next v1.x build (you will need to re-capture - the .rdc files are now binary incompatible) and let me know how you get on.

**Comment by baldurk** [comment]
v1.0 has now released, including this improvement based around the new resource inspector panel.
