### ISSUE TITLE
vkCreateInstance fails with VK_ERROR_EXTENSION_NOT_PRESENT due to lack of VK_KHR_wayland_surface extension support on Ubuntu 22.04

### ISSUE THREAD

**Issue by buzmeg** [baldurk/renderdoc#2711]
## Description

When trying to use qrenderdoc on Ubuntu 22.04.1, my app fails at vkCreateInstance with VK_ERROR_EXTENSION_NOT_PRESENT.  I eventually ran the issue down to requesting VK_KHR_wayland_surface.

App runs fine when launched from terminal command line but fails when launched from qrenderdoc.

This is unsurprising as Wayland is not listed as one of the compile-time supported windowing systems.  However, Wayland is becoming the default on more OS's and I had to take specific steps to disable it before being able to launch the app.

I'm really not sure what should be done to resolve this but felt it should be noted for other people who might bump into this.

## Steps to reproduce

Launch an app requesting VK_KHR_wayland_surface under qrenderdoc and note it fails.

## Environment

* RenderDoc version: ./renderdoccmd --version
renderdoccmd x64 v1.21 built from 98a93408c6df02502f9e7dbbc35fa234c8da024e
APIs supported at compile-time: Vulkan, GL, GLES.
Windowing systems supported at compile-time: xlib, XCB, Vulkan KHR_display.

* Operating System: uname -srvmpio
```Linux 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```

* Graphics API: Mesa Intel® UHD Graphics 620 (WHL GT2)

Thanks.

**Comment by baldurk** [comment]
Wayland is not supported, see #853 . Your application should enumerate available instance extensions before trying to enable any.
