### ISSUE TITLE
VK_Counters failures due to small runtime rounded to 0

### ISSUE THREAD

**Issue by meup** [baldurk/renderdoc#2719]
## Description

The test VK_Counters seems to time how long it takes to draw a single triangle (GPU Duration of draw).
On modern hardware, this test can run so fast that it reports taking 0 time, which causes the test to fail.
At least, that is my assumption of what is happening.

Perhaps the issue can be resolved by rendering more geometry?

## Steps to reproduce

This is just running the VK_Counters test on an Nvidia GTX 1060.

## Environment

* RenderDoc version: 1.20
* Operating System: Windows 10
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Bug reports should only be opened for bugs on RenderDoc itself. The tests are only intended for RenderDoc developers, and are not for general users so not in scope for bug reports.

**Comment by meup** [comment]
Granted, this is not a RenderDoc bug.  Still, it would probably make lives easier for RenderDoc developers if this issue were resolved.
