### ISSUE TITLE
Feature request: Add "100%" button next to the 'Fit' button in the Texture Viewer

### ISSUE THREAD

**Issue by jshofmann** [baldurk/renderdoc#272]
A nice convenience in the Texture Viewer would be to have a 100% button next to the Fit button in the texture viewer, to quickly reset the display to 1:1. As I recall, both Sony's Razor GPU and NVIDIA's NSight have such features.

**Comment by baldurk** [comment]
That commit should do the trick I think.

![zoomcontrols](https://cloud.githubusercontent.com/assets/661798/15591519/dd9fd8ba-239d-11e6-97a3-b164e9e53d24.png)

**Comment by baldurk** [comment]
Closing this issue as the feature was implemented in [v0.30](https://github.com/baldurk/renderdoc/releases/tag/v0.30). Feel free to re-open if it's not as you expect!
