### ISSUE TITLE
Cyberpunk2077 replay failed with unsupported VK_DESCRIPTOR_TYPE_MUTABLE_VALVE usage

### ISSUE THREAD

**Issue by ilqvya** [baldurk/renderdoc#2724]
## Description

I've captured Cyberpunk2077 trace on Linux Ubuntu 20.04 
The capture cannot be replayed with error:
```
$ ~/linbin/renderdoc_master/build/bin/renderdoccmd replay /tmp/RenderDoc/gfxrecon-replay_2022.09.14_10.59_frame66.rdc 
Replaying '/tmp/RenderDoc/gfxrecon-replay_2022.09.14_10.59_frame66.rdc' locally..
Couldn't load and replay '/tmp/RenderDoc/gfxrecon-replay_2022.09.14_10.59_frame66.rdc': Replaying the capture failed at the API level:
```
I've debugged the issue and found that it fails on the next line:
`RDCERR("Unexpected descriptor type %d", writes[bind].descriptorType);`
renderdoc/driver/vulkan/vk_initstate.cpp

The writes[bind].descriptorType shows VK_DESCRIPTOR_TYPE_MUTABLE_VALVE descriptor type which is unsupported by renderdoc

## Steps to reproduce

Download capture: https://drive.google.com/drive/folders/1QdrAt8Ks-LPnDOGxq6GLOsEuY1jVm0we
Try to replay it
See the error

## Environment

* RenderDoc version: v1.x - 8f14374b5
* Operating System: Ubuntu 20.04.5 LTS
* Graphics API: Vulkan
* Mesa main branch with 6c0215eb09e commit
* Intel® Core™ i5-10300H CPU @ 2.50GHz × 8
* Mesa Intel® UHD Graphics (CML GT2)

**Comment by ilqvya** [comment]
Note: GFXReconstruct capture and replaying works fine with this PR applied: https://github.com/LunarG/gfxreconstruct/pull/803

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
