### ISSUE TITLE
Vulkan sampler debug marker object name not displaying in pipeline state

### ISSUE THREAD

**Issue by SaschaWillems** [baldurk/renderdoc#273]
Setting debug object names for Vulkan images works fine, but it seems sampler names are not displayed.

Setting name for the sampler:

![renderdoc_sampler_debugname](https://cloud.githubusercontent.com/assets/10283127/15586345/2b7cc90e-2384-11e6-8329-8301dccb3a89.png)

Display in fragment shader pipeline stage:

![renderdoc_sampler_noname](https://cloud.githubusercontent.com/assets/10283127/15586352/35a108d2-2384-11e6-96d0-7c94fbf15bb7.png)

While the image's debug name is visible, the sampler's name is not.

I'm using a combined image sampler btw.

**Comment by baldurk** [comment]
It was just missing some plumbing to get the name through to the UI and apply it :smile:.

**Comment by SaschaWillems** [comment]
Thx for the quick fix, my sampler names now show up :+1:
