### ISSUE TITLE
Python3.11 support

### ISSUE THREAD

**Issue by gicmo** [baldurk/renderdoc#2730]
## Description

Trying to compile renderdoc on a system with Python 3.11 fails.

## Steps to reproduce

Use Fedora rawhide and try to compile renderdoc. Observe compilation errors: https://kojipkgs.fedoraproject.org//work/tasks/2208/92292208/build.log
https://koji.fedoraproject.org/koji/taskinfo?taskID=92292208

Relevant Python 3.11 change:
https://docs.python.org/3.11/whatsnew/3.11.html:

> The [PyFrameObject](https://docs.python.org/3.11/c-api/frame.html#c.PyFrameObject) structure members have been removed from the public C API.

## Environment

* RenderDoc version: 1.22
* Operating System: Fedora Rawhide (with Python 3.11)

**Comment by baldurk** [comment]
Python 3.11 has not even been released yet, please don't open issues that only happen when using currently beta third party software.

**Comment by gicmo** [comment]
It is blocking the inclusion of renderdoc in Fedora 37, which is going to use Python 3.11, see https://bugzilla.redhat.com/show_bug.cgi?id=2049621

**Comment by gicmo** [comment]
Quick update: 
renderdoc got indeed retired from Fedora (see https://src.fedoraproject.org/rpms/renderdoc).

I think the issue is now fixed via https://github.com/baldurk/renderdoc/commit/9df7d402417d8068d3e0f3550635182875646b66
