### ISSUE TITLE
Repeated search in a new capture fails to find anything

### ISSUE THREAD

**Issue by WoodyPWX** [baldurk/renderdoc#2734]
## Description
If I make a capture with markers, I can use Event Browser -> "Find event by string" to search my marker. If I then open another capture, the string for search is remembered so I just press enter to find the same marker in this new capture, but nothing is found. I need to first change the string before it finds anything.

## Steps to reproduce
Make a capture with string markers and search for any string in the Event Browser by clicking on Binoculars icon. After a successful search open a different capture in the same RenderDoc instance and try to search for the same string by clicking on search and enter. Please note that reopening the same capture will not reproduce the issue.

## Environment

Any recent RenderDoc version for at least a year is reproducing the issue.

* RenderDoc version: 1.22
* Operating System: Windows 11 64bit
* Graphics API: tested with D3D11, D3D12 and Vulkan

**Comment by baldurk** [comment]
Thanks, the cache of find results wasn't properly being cleared so it would work in other captures only as long as the EIDs matched up exactly (which is why it didn't repro if you loaded the same capture again).
