### ISSUE TITLE
qrenderdoc crash when loading a Vulkan capture

### ISSUE THREAD

**Issue by randomgraphics** [baldurk/renderdoc#2738]
## Description

qrenderdoc crashes (coredump) when openining a capture that was succesfully captured by the same qrenderdoc binary. The behavior is very simialr as this issue: https://github.com/baldurk/renderdoc/issues/2727

But this capture has no multiple devices involved. So could be different underlying reason.

## Steps to reproduce

- open the attached capture file using qrenderdoc version 1.22.
- the proces crash with coredump.

[rdc-crash.zip](https://github.com/baldurk/renderdoc/files/9697754/rdc-crash.zip)

## Environment

* RenderDoc version: 1.22
* Operating System: Ubuntu 20.04
* Graphics API: Vulkan
* GPU: NVIDIA Gefore 3070
* Driver Version: 515.57
* CUDA Version: 11.7

**Comment by baldurk** [comment]
This capture contains invalid use of vulkan, and RenderDoc does not generally handle invalid API use.

The `vkCreateDevice` call has a `VkPhysicalDeviceExtendedDynamicStateFeaturesEXT` struct chained on, but the device does not enable the `VK_EXT_extended_dynamic_state` extension. Vulkan applications must only pass structs in the pNext chain which are defined by enabled extensions and core  versions.

**Comment by randomgraphics** [comment]
Thanks for the quick response. That indeed fixed the issue. It slipped through our check cause VK validation layer didn't say anything about it...
