### ISSUE TITLE
Handle `vkCmdBeginRendering`/`vkCmdEndRendering` being in secondary command buffer

### ISSUE THREAD

**Issue by werman** [baldurk/renderdoc#2740]
## Description

Secondary command buffers are allowed to have renderpasses made with `vkCmdBeginRendering`/`vkCmdEndRendering`.

At the moment, when selecting draw call inside dynamic renderpass, RenderDoc replays`vkCmdBeginRendering` into one command buffer, but replays drawcalls into another one.

## Steps to reproduce

- Capture e.g. `dEQP-VK.draw.dynamic_rendering.complete_secondary_cmd_buff.multiple_clears_within_render_pass.clear_clear_draw_c_r8g8b8a8_snorm_d_d32_sfloat_triangle_strip`
- Try to select any draw call in the renderpass
![image](https://user-images.githubusercontent.com/3993671/194409615-a8b6271e-2502-4207-aa65-bfed91df89eb.png)
- The driver would crash

## Environment

* RenderDoc version: 849fe18ac18e011fdd15ae724919ea0fba4c4b99
* Operating System: Linux
* Graphics API: Vulkan
* Driver: Latest Mesa main. RADV, Turnip

**Comment by baldurk** [comment]
Yes unfortunately niche bits of functionality like this are technically valid even though no-one in their right mind should be using them, so they cause wonderful chaos for tools/driver developers. If only secondary command buffers had been completely excised when dynamic rendering made them redundant.

That commit should handle it correctly but I was only testing against validation errors as my driver didn't crash on this case.

**Comment by werman** [comment]
Thanks! It works now.

Yeah, these secondary command buffers are also especially nasty for tiling GPUs...
