### ISSUE TITLE
Support width-specific type names for buffer formatting

### ISSUE THREAD

**Issue by didito** [baldurk/renderdoc#2742]
## Description

Eg. using `int64_t` in a custom buffer format declaration yields

> Error: Failed to parse declaration:
> int64_t foo
> Unrecognized type 'int64_t'.

Same for `uint64_t`, `int32_t`, `uint32_t`, `float16_t`, `float32_t` and `float64_t`. And their vector forms. 

https://github.com/microsoft/DirectXShaderCompiler/wiki/16-Bit-Scalar-Types#dxil-scalar-type

SM 6.0 / HLSL 2016 introduced 64bit integers.
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/hlsl-shader-model-6-0-features-for-direct3d-12#shader-model-60
https://github.com/microsoft/DirectXShaderCompiler/wiki/Shader-Model-6.0

HLSL 2018 "add[ed] width-specific types for floats and ints, for 16, 32 and 64 bit widths".
https://github.com/microsoft/DirectXShaderCompiler/wiki/Language-Versions

SM 6.6 added support for packed data types (uint8_t4_packed / int8_t4_packed).
https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_Pack_Unpack_Intrinsics.html#packed-datatypes
https://devblogs.microsoft.com/directx/in-the-works-hlsl-shader-model-6-6/

Now RenderDoc already offers [support](https://renderdoc.org/docs/how/how_buffer_format.html#basic-types) via different type names (e.g. long/ulong) but it would be very practical to support the standard width-specific types names mentioned above, since structs could just be copied from host (C/C++) or device (HLSL) code.

## Environment

* RenderDoc version: 1.22
* Operating System: Win10 Pro x64 21H2 build 19044.2006
* Graphics API: DX12 (but VK too)

**Comment by didito** [comment]
I guess for VK `int8_t` and `uint8_t` would already be interesting too.

See:

- [VK_KHR_shader_float16_int8](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_shader_float16_int8.html)
- [GL_EXT_shader_explicit_arithmetic_types](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_shader_explicit_arithmetic_types.txt)

**Comment by baldurk** [comment]
I'm not completely sold on these types especially with how ugly they become for specifying vectors (`uint64_t3` isn't exactly as naturally intuitive to me), and from what I remember nsight didn't support them when I checked so I figured there wasn't much use for them. But that said I can see that they're useful in the case where you're copy-pasting definitions from somewhere that uses these types and the suffixed `_t` types are at least better than unsuffixed versions.

That said I would expect that in almost every situation you have debug information enabled and the struct definition is automatically populated for you, so there should hopefully only be rare cases where you need to do this.
