### ISSUE TITLE
FetchTessGSOut does not consider Stream output var decoration when changing XFB buffer

### ISSUE THREAD

**Issue by werman** [baldurk/renderdoc#2745]
## Description

When changing transform feedback decorations for GS output - `Stream` decoration is not taken into account when changing XFB buffer.

SPIRV spec says:

> All Stream [Decorations](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Decoration) must be the same for all objects decorated with the same XfbBuffer XFB Buffer Number.

GS output before modification:

```
layout(location = 1, xfb_buffer = 1, xfb_stride = 16, xfb_offset = 0, stream = 1) out vec4 _33;
layout(location = 0, xfb_buffer = 0, xfb_stride = 16, xfb_offset = 0, stream = 0) out vec4 _38;
```
(different stream with different buffers)

After `FetchTessGSOut`:

```
layout(location = 1, xfb_buffer = 0, xfb_stride = 32, xfb_offset = 16, stream = 1) out vec4 _33;
layout(location = 0, xfb_buffer = 0, xfb_stride = 32, xfb_offset = 0, stream = 0) out vec4 _38;
```

(different stream with the SAME buffer)

## Steps to reproduce

- Capture `dEQP-VK.transform_feedback.simple.multiquery_omit_write_1` test
- Click on a draw call
- Driver may crash (at least debug builds of RADV and Turnip)

## Environment

* RenderDoc version: 9254eff4904f31bbe529d5803234d25780df02e8
* Operating System: Linux
* Graphics API: Vulkan
* Driver: debug builds of RADV and Turnip

**Comment by baldurk** [comment]
Should be fixed with that commit.
