### ISSUE TITLE
shader debugger output is different than actual shader output in texture viewer

### ISSUE THREAD

**Issue by randomgraphics** [baldurk/renderdoc#2746]
## Description

I have a capture file that I'm trying to repro a "black color" issue of a Vulkan app. After the capture is loaded, the image in texture viewer shows the black issue. The pixel history window also shows the pixel shader output is "0,0,0,1". But when I debug one of the black pixel, the output value in debugger is quite different (gray color), instead of black.

![image](https://user-images.githubusercontent.com/18158085/194873248-13a9081c-0624-4f14-86a2-79fe41f15a97.png)

## Steps to reproduce

- Open this capture file: https://drive.google.com/file/d/1ZeFABEyrn-e8PTkvOtpvDaEu3TS4hn9h/view
- Go to EID 85.
- On texture viewer, you should see an area of black pixels.
- Right click any of the black pixel and try debug it.
- In shader debugger, press F5 to go all the way to the end of the shader.
- Actual result: the shader output says the final color is (0.49, 0.49, 0.49, 1). The actual value might be slightly different depending on which black pixel is selected for debugging.
- Expected result: the shader output should be (0, 0, 0, 1). Or at least very close to (0, 0, 0, 1)

## Environment

* RenderDoc version: 1.2.2
* Operating System: Windows 11 22h2 (BUILD 22621.525)
* Graphics API: Vulkan
* GPU: Nvidia 308. Driver 496.13

**Comment by randomgraphics** [comment]
Ok, I think I found the issue. It is the following line in refractive.frag:

![image](https://user-images.githubusercontent.com/18158085/194882738-ce3e440d-2ce2-4b1a-8c67-32c0aca90f09.png)

    normalize(vec3(0,0,1000.0) - v_worldPos);

The shader is running in medium precision. And this line causes floating point overflow, since v_worldPos.z is rather small.

**Comment by baldurk** [comment]
Yes if your shader invokes undefined or implementation-defined behaviour (in this case, potentially overflowing the implementation-defined calculation width of relaxed precision calculations) then it's expected that RenderDoc's debugger may not match the result from the GPU. If defined sized types are used then these are debugged accurately.

I note that in your case the relaxed precision decoration is not applied to the intermediate result being normalized so even if RenderDoc were somehow able to tell the precision the GPU would use and apply it, it would not be applied to this calculation regardless.
