### ISSUE TITLE
Makefile ignores CPP variable

### ISSUE THREAD

**Issue by Marqin** [baldurk/renderdoc#275]
[Here](https://github.com/baldurk/renderdoc/blob/master/COMPILE.md) it's written that to use another compiler than G++ you have to:

> this can be overwridden via variables CC and CPP

But it does not work. Make still uses `/usr/bin/c++`, whenever I'll feed it via:

`make CPP=/usr/bin/clang++`

`CPP=/usr/bin/clang++ make`
 or even
```
export CPP=/usr/bin/clang++
make
```

I've also tried using CXX variable (which is standard variable name for C++ compiler), but also didn't worked.

I'm on Arch Linux.

**Comment by baldurk** [comment]
Looks like COMPILE.md just wasn't updated when the build system was changed to cmake. I don't really know cmake myself but it looks like exporting CC and CXX should work fine as I mentioned in #274. I'll update the instructions though.

**Comment by Marqin** [comment]
It wasn't working for `CXX` until I've removed whole renderdoc directory and unpacked in again. It seems that cmake/make saves somewhere which compiler you used first time and keeps using it even if you change it later via variable.

**Comment by baldurk** [comment]
Yes I'm not really familiar with cmake - it was added to make it easier for cross-platform dev or something like that. I don't use it on windows. I think the build configuration is cached inside the 'build' folder created in the root. I updated the COMPILE.md to reflect the current status.

**Comment by baldurk** [comment]
Closing this issue as it wasn't really something to fix, just documentation out of date from the build system. Re-open if it's still not working as expected.
