### ISSUE TITLE
Better error messages when compiler tools paths are outdated.

### ISSUE THREAD

**Issue by dorian-apanel-intel** [baldurk/renderdoc#2751]
## Description

I noticed that when I tried to edit shader module, opened `decompiled` tab is empty. 
Then Error tab shows such message:
```
Running "E:/dapanel/RenderDoc_Custom_v1.21.2_64/plugins/spirv/spirv-cross.exe" --vulkan-semantics --entry main --stage frag --output C:/Users/myuser/AppData/Local/Temp/shader_output C:/Users/myuser/AppData/Local/Temp/shader_input

Process exited with code 0.
Output file is 0 bytes
```

`E:/dapanel/RenderDoc_Custom_v1.21.2_64` path does not exist. It used to be there, but now I'm using `E:/dapanel/RenderDoc_Custom_v1.22.0_64`. 

Under debugger I noticed, that `E:/dapanel/RenderDoc_Custom_v1.21.2_64` path is read from persistent UI config file: `C:/Users/myuser/AppData/Roaming/qrenderdoc/UI.config`

I don't remember if I changed those tools path manually.

It would be nice to have more descriptive message, like:
Renderdoc printing `"E:/dapanel/RenderDoc_Custom_v1.21.2_64/plugins/spirv/spirv-cross.exe" does not exist. Adjust Shader Processing Tools paths in Settings->Shader Viewer->Shader Processing Tools.` In Errors tab.

## Steps to reproduce

I was not able to reproduce it by unzipping new renderdoc, using it and renaming its folder. This time it was using VulkanSDK boundled tools.

## Environment

* RenderDoc version: 1.22 with little differences.
* Operating System: Windows
* Graphics API: Vulkan

**Comment by baldurk** [comment]
That commit should fix it, using a different error code from Qt's process launching to detect this case.
