### ISSUE TITLE
FB view in Vulkan wrong indices used for Target Blends

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#2756]
## Description

Take the following render pass:

- Attachments: 0, 1 and 2 are both color
- Subpass pColorAttachments are:
   * 0: attachment 0
   * 1: attachment 1
   * 2: VK_ATTACHMENT_UNUSED
   * 3: attachment 2

In this scenario, the Target Blends table shows "Slots" 0, 1 and 2, with the contents of slot 2 invalid (including "Write Mask" set as "____", and default blend parameters).

I suspect this is due to the fact that render pass attachment indices and subpass attachment indices are confused somewhere.

## Steps to reproduce

Capture can be found here: https://drive.google.com/file/d/1CEUf6efhwsugmII_F4qdKqdUVHpPy85g/view

See the second draw call for example. Note that in this capture, subpass attachment 0 is intentionally masked out in this draw call, so Write Mask ____ is normal there. Slot 2 is the problem (as you could see, blend functions of that slot are also (incorrectly) different).

## Environment

* RenderDoc version: 387a9e57
* Operating System: Linux (but should be agnostic)
* Graphics API: Vulkan

Capture was taken on Nvidia hardware.

**Comment by ShabbyX** [comment]
I'd fix the bug, but don't know when I'll find the time

**Comment by baldurk** [comment]
That commit should fix the issue, iterating from the renderpass attachments and looking up in the FB rather than the other way around, which makes it easier to match the iteration for blends too.

**Comment by ShabbyX** [comment]
Thanks a lot, confirmed that it works like a charm.
