### ISSUE TITLE
OpenGL with custom texture viewer needs layout specifier removed

### ISSUE THREAD

**Issue by jtpatches** [baldurk/renderdoc#2757]
## Description

When viewing a texture in an OpenGL capture, using a custom shader requires the custom shader _not_ to have a location specifier on the `uv` input variable, but the default brand new custom shader _does_ have the location specifier.

I thought this might be the Mesa driver not following the spec during glLinkProgram but I couldn't see anything in the OpenGL spec saying that a shader without an explicit output location could be linked with one that has an explicit input location or vice versa.

## Steps to reproduce

Open any OpenGL capture.  Create a custom shader. Do not change the declaration of `uv`. Refer to `uv` somewhere in the shader.

### Workaround

The following piece of [vandalism](https://github.com/jtpatches/renderdoc/tree/vandalism) has worked for me but it probably breaks in some other circumstances.

    diff --git a/renderdoc/data/glsl/blit.vert b/renderdoc/data/glsl/blit.vert
    index 263e10b29..af3c7fdbc 100644
    --- a/renderdoc/data/glsl/blit.vert
    +++ b/renderdoc/data/glsl/blit.vert
    @@ -32,7 +32,13 @@
     layout(num_views = NUM_VIEWS) in;
     #endif
     
    -IO_LOCATION(0) out vec2 uv;
    +#ifdef VANDALIZED
    +#define OUT_LOCATION(l) layout(location = l)
    +#else
    +#define OUT_LOCATION(l) IO_LOCATION(l)
    +#endif
    +
    +OUT_LOCATION(0) out vec2 uv;
     
     void main(void)
     {
    diff --git a/renderdoc/driver/gl/gl_debug.cpp b/renderdoc/driver/gl/gl_debug.cpp
    index 74229b097..e4921dfe8 100644
    --- a/renderdoc/driver/gl/gl_debug.cpp
    +++ b/renderdoc/driver/gl/gl_debug.cpp
    @@ -453,9 +453,6 @@ void GLReplay::InitDebugData()
         }
       }
     
    -  // used to combine with custom shaders.
    -  DebugData.texDisplayVertexShader = CreateShader(eGL_VERTEX_SHADER, vs);
    -
       for(int i = 0; i < 3; i++)
       {
         rdcstr defines = rdcstr("#define SHADER_BASETYPE ") + ToStr(i) + "\n";
    @@ -503,6 +500,11 @@ void GLReplay::InitDebugData()
     
       RDCLOG("GLSL version %d", glslVersion);
     
    +  rdcstr vandalism = "#define VANDALIZED 1\n";
    +  vs = GenerateGLSLShader(GetEmbeddedResource(glsl_blit_vert), shaderType, glslVersion, vandalism);
    +  // used to combine with custom shaders.
    +  DebugData.texDisplayVertexShader = CreateShader(eGL_VERTEX_SHADER, vs);
    +
       vs = GenerateGLSLShader(GetEmbeddedResource(glsl_blit_vert), shaderType, glslBaseVer);
     
       DebugData.fixedcolFragShader = DebugData.quadoverdrawFragShader = 0;

## Environment

* RenderDoc version: v1.22, and v1.x (commit 101dbda8c34888bf2051c3c257da3a1702705ef9)
* Operating System: Debian Bullseye, x86_64
* Graphics API: OpenGL
 
Mesa 20.3.5 AMD Kaveri integrated GPU,
Mesa 22.3.0-devel same GPU
Mesa 22.3.0-devel llvmpipe.

**Comment by baldurk** [comment]
Looks like indeed GL has a characteristically stupid rule that means variables which otherwise match will _not_ match if one of them has an explicit location:

> An output variable is considered to match an input variable in the subsequent shader if:
> – the two variables match in name, type, and qualification, **and neither has a location qualifier**, or
> – the two variables are declared with the same location and component layout qualifiers and match in type and qualification.

It seems like most drivers sensibly ignore this and fall back to matching by name if the locations don't match, but mesa strictly follows the spec.

That commit should fix the issue, though it does introduce the problem that custom display shaders now _must_ have the explicit location. It doesn't seem feasible to support both cases, and the explicit location has been standard for the template for 5+ years. If anyone wants to run on a system where the GL driver doesn't support explicit locations they won't be able to use custom display shaders, but that seems unavoidable and the lesser evil.
