### ISSUE TITLE
D3D12 Support ID3D12Device10 and ID3D12Device11

### ISSUE THREAD

**Issue by MarcasRealAccount** [baldurk/renderdoc#2760]
## Description

A few days ago, I had a few problems with DX12 and wanted to look at what it was that caused it, so I launched up Renderdoc and launched my program as I had done previously for Vk and OpenGL apps, but sadly Renderdoc didn't want to capture anything, and I had no idea why because you disabled the log view (thanks btw xD). After figuring out some python code to dock the log view back in I found out it did detect DX12 correctly, but it failed to attach to the ID3D12Device10 interface I used. So, I had to revert to ID3D12Device9 to make it work. However later on I do want to pursue the enhanced barrier system that was added, which turns out is given in ID3D12Device10, but that would mean I would be incapable of using Renderdoc in the event I fail somewhere.
I also found out ID3D12Device11 is out with the Agility SDK.

## Environment

* RenderDoc version: v1.22
* Operating System: Windows 11 22H2 22623.870
* Graphics API: DX12

**Comment by baldurk** [comment]
These APIs are only available in the beta version of D3D12, I have no plans to support pre-release interfaces, when they are released as stable I can investigate.

**Comment by MarcasRealAccount** [comment]
Yeah so, you're actually wrong, ID3D12Device10 is not preview, not anymore, and hasn't been for a month ish.
Because it was released with 22H2, which is not preview.
