### ISSUE TITLE
Android apps with multiple processes do not show for capture

### ISSUE THREAD

**Issue by bylaws** [baldurk/renderdoc#2763]
## Description

Our app uses the `android:process` on a separate activity to run our Vulkan component in a separate process, when renderdoc is used to launch the main activity and then the new separate process activity is launched renderdoc stays connected to the old one and the new one has 'no remote access connection'.  Trying to use attach to running instance doesn't work either as only the main activity is shown.

## Steps to reproduce

- Install app from email and copy pixel painter nro into a directory.
- Select that directory after launching the app, then close it again and launch with renderdoc
- Now, with RD running and attached, select the pixel painter icon in the app, RD should have detached without any way to attach

## Environment

* RenderDoc version: v1.21
* Operating System: Arch Linux/Android
* Graphics API: Vulkan

**Comment by baldurk** [comment]
This is more or less a feature request for multiple process support on android, and it's not one I ever plan to support so I'm going to close this issue.

You may be able to get this to work with a combination of manual setting of android properties and possibly manual port forwarding (in the range `38921-38929` for multiple processes, forwarded from tcp on localhost to `localabstract:renderdoc_38921`... on android) but that's not something I have tested or will provide any support with.
