### ISSUE TITLE
Do not  lockout CMake building on Windows

### ISSUE THREAD

**Issue by p01arst0rm** [baldurk/renderdoc#2764]
## Description
CMake lockout on windows makes including renderdoc within other project buildsystems painful. Projects should always allow the end user the option of how to build the project.

## Steps to reproduce
build or import with cmake.

CMake Error at CMakeLists.txt:234 (message):
  CMake is not needed on Windows, just open and build renderdoc.sln

## Environment

* RenderDoc version: v1.22
* Operating System: Windows 11 22H2 22621.675
* Graphics API: N/A

please allow an override option to force building on windows with CMake.

**Comment by baldurk** [comment]
No I never plan to support cmake on windows. RenderDoc is an application not a library so its build system is not intended to be referenced or included elsewhere.

**Comment by p01arst0rm** [comment]
renderdoc is often embedded in other projects and to do that the source code is integrated within those buildsystems. not supporting cmake requires extensive porting or patching the project to get it to work.

**Comment by baldurk** [comment]
I've never heard of renderdoc ever being embedded in another project, I'm not even sure how that would work. I've only heard of  custom forks or use of the in-application API, and neither of those requires build system integration.

**Comment by p01arst0rm** [comment]
no, but it complicates the process of building a toolchain as msvc doesnt give much flexibility regarding build time settings

**Comment by baldurk** [comment]
You seem to be moving the goalposts, if it's not about embedding renderdoc in another buildsystem. I don't know what you mean about building a toolchain or build time settings flexibility.

Regardless, the answer is the same - I am never going to support cmake on windows.

**Comment by p01arst0rm** [comment]
the buildsystems of other projects that require the project use automated scripts to install dependencies to a toolchain, this binaries in this toolchain are then checked for by the buildsystem. no goalposts have been moved. installing to a toolchain is not as easy to do with msvc compared to cmake, hence the request for cmake override. 

thats fine, the source can just be patched to remove the dependence on windows tools.
