### ISSUE TITLE
renderdoc.EnumerateRemoteTargets Block Process in Python

### ISSUE THREAD

**Issue by whbwhb521** [baldurk/renderdoc#2765]
## Description
when i call the function renderdoc.EnumerateRemoteTargets in python, it will block the process due to GIL. when CreateClientSocket failed, it will block a long time.

## Environment

* RenderDoc version: 1.22
* Operating System: Win10
* Graphics API: dx11

**Comment by baldurk** [comment]
Yes this is normal, EnumerateRemoteTargets can take over a second in the worst case if there are no programs running on the remote host. If that's a concern I suggest putting the call on a different thread.

**Comment by whbwhb521** [comment]
but in python, even if it is executed in a different thread, the main thread will block

**Comment by baldurk** [comment]
Yes that is a python limitation and not something I can address.

**Comment by whbwhb521** [comment]
it can be solved byPy_BEGIN_ALLOW_THREADS and Py_END_ALLOW_THREADS in cxx.
![image](https://user-images.githubusercontent.com/51041226/200212130-fb958f6c-7487-4e6a-bd77-113e7b1012d9.png)
