### ISSUE TITLE
qrenderdoc crashes immediately

### ISSUE THREAD

**Issue by zfigura** [baldurk/renderdoc#2772]
## Description

qrenderdoc crashes immediately when run from the command line:

```
whatsit@camazotz:~/git/vkd3d64$ qrenderdoc 
Segmentation fault (core dumped)
```

Taking a backtrace in gdb, it looks like it's crashing trying to call the host glGetString, which is NULL for some reason. I don't know why this would be. This is 64-bit qrenderdoc; 64-bit glxgears works fine. Using `renderdoccmd capture` and `renderdoccmd replay` also works fine.

```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff622cfd7 in glGetString_renderdoc_hooked (name=eGL_VERSION) at ./renderdoc/driver/gl/gl_hooks.cpp:158
#2  glGetString (name=eGL_VERSION) at ./renderdoc/driver/gl/gl_hooks.cpp:158
#3  0x00007ffff3622359 in getGlString (param=7938) at ./src/plugins/platforms/xcb/gl_integrations/xcb_glx/qglxintegration.cpp:144
#4  updateFormatFromContext (format=...) at ./src/plugins/platforms/xcb/gl_integrations/xcb_glx/qglxintegration.cpp:174
#5  0x00007ffff3623b7e in QGLXContext::init (this=0x55555663ad30, screen=<optimized out>, share=<optimized out>) at ./src/plugins/platforms/xcb/gl_integrations/xcb_glx/qglxintegration.cpp:416
#6  0x00007ffff36211b7 in QXcbGlxIntegration::createPlatformOpenGLContext (this=<optimized out>, context=0x7fffffffd0f0) at ./src/plugins/platforms/xcb/gl_integrations/xcb_glx/qxcbglxintegration.cpp:197
#7  0x00007ffff4f827bd in QOpenGLContext::create (this=0x7fffffffd0f0) at kernel/qopenglcontext.cpp:612
#8  0x00007ffff01bd03c in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/KDEPlasmaPlatformTheme.so
#9  0x00007ffff48b7aaf in QCoreApplicationPrivate::init() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff4f37b8c in QGuiApplicationPrivate::init (this=0x55555652c620) at kernel/qguiapplication.cpp:1530
#11 0x00007ffff57684c9 in QApplicationPrivate::init() () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x0000555555820884 in main ()
```

## Steps to reproduce

Run qrenderdoc as described.

## Environment

* RenderDoc version: 1.22 from Debian package (1.22+dfsg-1)
* Operating System: Debian bookworm
* Graphics API: N/A

GL from Mesa 22.2.2.

**Comment by baldurk** [comment]
I do not provide support for distribution packages and debian packages in particular are known to be unreliable and crashing. Does this still reproduce if you build RenderDoc from source or run the binary builds from https://renderdoc.org/builds ?

**Comment by zfigura** [comment]
It does not reproduce with the linked binary 1.22 or with current git built from source (742e3de252c). I'll report this to Debian, thanks.

**Comment by baldurk** [comment]
This might also be related to #2752 which was caused by KDE injecting unwanted code into the application at runtime, if you're using KDE it might be that bug which has had a workaround put into place.

**Comment by zfigura** [comment]
It looks like the same issue, judging by the backtrace and symptoms (and I am indeed using KDE).
