### ISSUE TITLE
D3D12 Replay IASetIndexBuffer No Resource

### ISSUE THREAD

**Issue by mengxinxiaoqiang** [baldurk/renderdoc#2774]
## Description
"Uncharted Legacy of Thieves Collection-InsaneRamZes" Captrue Frame IASetIndexBuffer No Resource
![image](https://user-images.githubusercontent.com/56524631/201878576-953c5b44-1b39-4bf1-ba91-d674644062f0.png)

## Environment

* RenderDoc version: 1.22
* Operating System: Win10
* Graphics API: D3D12

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
