### ISSUE TITLE
RenderDoc hangs in a Vulkan replay

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#2779]
## Description

In one particular capture, I've hit a case where RenderDoc hangs when switching between draw calls. gdb shows every thread blocked on something (futex, poll etc, so it didn't look like RenderDoc is actually doing anything). I was not able to figure out what the issue is.

## Steps to reproduce

1. Take this capture: <redacted>
2. Open the capture
3. Randomly click on draw calls all over the trace (not just the initial ones), observe RenderDoc hangs after a few clicks

I'm running RenderDoc on Linux. Things I've tried:

- The hang happens on v1.22 as well as ToT (de2d6e7b)
- The hang happens in both the following builds:
   * `cmake -DCMAKE_BUILD_TYPE=Release -Bbuild-with-gl -H.`
   * `cmake -DCMAKE_BUILD_TYPE=Release -Bbuild -H. -DENABLE_GLES=OFF -DENABLE_GL=OFF`
- The hang happens regardless of whether I run RenderDoc over Nvidia or SwiftShader
- The hang happens also when clicking on History of a pixel, or selecting an Overlay
- Clicking on a single draw call doesn't yet hang RenderDoc (i.e. can inspect pipelines etc), but reloading the capture and clicking on a draw call immediately hangs

I don't have this issue with other captures, so there's something specific about this one.

## Environment

* RenderDoc version: v1.22, de2d6e7b and a number of random ones in between (bdff6cd8, 101dbda8, ea4aa164)
* Operating System: Linux
* Graphics API: Vulkan
* GPU: Nvidia and SwiftShader

**Comment by ShabbyX** [comment]
I simplified the capture by a lot: <redacted>

With this capture, I can reproduce the hang by clicking on the very first draw call, then the second draw call. Clicking between the copy commands before the first draw call doesn't cause any issues/

The draw call itself is not the issue, this is a capture that removes the first draw call, you could still click on the (new) first draw call then the second draw call to create the hang: <redacted>

Even the first render pass is not the issue, this is a capture that removes all draw calls in the first render pass, you can still click on the (new) first draw call then the second draw call to create the hang: <redacted>

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
