### ISSUE TITLE
Does not support index buffer with glVertexArrayElementBuffer

### ISSUE THREAD

**Issue by finalpatch** [baldurk/renderdoc#278]
Specifying index buffer with OpenGL 4.5 function glVertexArrayElementBuffer doesn't work in RenderDoc(0.29 Win64).  If I replace the glVertexArrayElementBuffer with glBindVertexArray() followed by glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ...) then the index buffer is captured correctly in RenderDoc.

**Comment by baldurk** [comment]
Do you have a repro sample showing the bug you can share? Eyeballing the code I don't see anything obviously standing out as wrong so I'll have to construct something to test it, and there's the chance I might not make my sample in the same way as yours and it won't repro the bug.

**Comment by finalpatch** [comment]
Hi thanks for the quick response.  I made a repo for you that shows this problem: https://github.com/finalpatch/rd278 

Sorry for the language used being Pascal. You will need the Lazarus IDE if you want to build it. I have only tested this on Windows 10 x64.

In the file glhelpers.pas,  there is a line near the beginning "{$define RENDERDOC}".  If the RENDERDOC path is enabled, RenderDoc captures the index buffer. Otherwise RenderDoc is unable to capture the index buffer.  Either way, the rendering result in the window looks correct.

**Comment by baldurk** [comment]
I think that should do the trick (ignore the commit listed twice). I was binding a buffer to the VAO without properly restoring the previous binding, so for this case where the bind is part of VAO state I was trashing it.

I also fixed an issue where buffers created via glCreate() and never going via glBindBuffer*() would be wrongly listed as 'uninitialised buffer' in the UI.

Let me know if that sorts it out for you.

**Comment by finalpatch** [comment]
Just tried the latest nightly, works flawlessly. Thanks a lot!
