### ISSUE TITLE
[Feature request]: View mesh output in world space

### ISSUE THREAD

**Issue by Nielsbishere** [baldurk/renderdoc#2781]
## Description

Currently, renderdoc is already superior to debugging output of shaders compared to PIX or nsight, but it's missing a really nice feature. Even though you can see SV_Position output, it would be nice to inspect world output too. This could mean providing a drop down to select the semantic / vertex attribute that is the world position. This would allow a more intuitive view than a model in clip space. And perhaps it could be nice to show an attribute that could be output to color as well. For example; showing uv output as colors so that it's easy to see what's going on there.

## Environment

N.A. but directx12

**Comment by baldurk** [comment]
I'm not sure I understand how what you're asking for differs from what's already there. Can you please explain in more detail exactly what you're asking for?

**Comment by Nielsbishere** [comment]
So basically, you would have a toggle to switch between world positions and clip positions in the fly through camera window (as a rasterized mesh). Unless that's already possible? So one would show the SV_Position and another would show a different vs attribute that is output by the shader (that is in world space). 
And the other feature would be for quick visualization if there are any errors in for example the uv coordinates

**Comment by baldurk** [comment]
I'm not sure what you mean, the mesh viewer never shows anything in clip space. The final rasterizer output is unprojected so it's effectively displayed in view space, which with a movable camera is more or less equivalent to world space?

If you have some other attribute (whether it's actually a position or e.g. texture co-ordinates) that you want to use as the position for display then you can select it as position and it will be displayed directly in whatever local space it's in - relative to the centre of its bounding box. If that attribute is world space you're going to get a very similar view to plain output, comparable to e.g. the default vertex input view.

I don't know what you mean about the other feature. How would it be different from the existing secondary display?

**Comment by Nielsbishere** [comment]
Sorry @baldurk, I'm an idiot and didn't find it. It's already under right click. Amazing tool
