### ISSUE TITLE
Can Only Patch Release Build Once

### ISSUE THREAD

**Issue by JasonGuthrie89** [baldurk/renderdoc#2782]
## Description

The message "Android application not setup for RenderDoc capture" only appears the first time you debug an application.

As a result, I can't patch if I update a build and injection fails.

## Steps to reproduce

Load a non development/debug build onto a Quest 2 (I use Meta Quest Developer Hub to do so).
Attach RenderDoc and point it towards the build.
Hit the message mentioned above to allow it to patch the app so its debuggable.
Launch the app.
Uninstall the app from the headset.
Install a new version of the app.
Attempt to launch via RenderDoc.

At this point the app will launch but injection will fail.
No message will appear to allow you to patch the build.

If you make a new build with a different name, you will see the option to patch again.

## Environment

* RenderDoc version: 1.22
* Operating System: Windows
* Graphics API: OpenGL 3

**Comment by baldurk** [comment]
The patching code was never intended to ship and its inclusion was an oversight from early prototyping code, it has been deleted entirely. You should build your package as debuggable in the first place and not rely on any hacky patching.

**Comment by JasonGuthrie89** [comment]
That's a shame. I've found it useful since release and debug rendering in Unity is different.

Any tips for me to get it to reappear without having to rename builds? Reinstalling RenderDoc for example doesn't bring it up again.

**Comment by baldurk** [comment]
I would recommend that you report a bug to Unity then, either to allow debugging of release builds or to fix whatever rendering is different between those builds.
