### ISSUE TITLE
Show real OpenGL name for resources

### ISSUE THREAD

**Issue by OndrejSpanel** [baldurk/renderdoc#2785]
### Motivation

I am debugging an issue where a framebuffer is reported as GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE. I try to track corresponding resource creating in the application, and I try to verify my findings in RenderDoc. One thing which seems to make this more complicated than I would like is the fact RenderDoc uses some numbers which seem arbitrary to me to identify OpenGL resources. While the resources names as returned by OpenGL are small numbers (1-10) in my situation, RenderDoc identifies them with different numbers (like 40 - 80). I understand there are probably reasons for this, but could it be at least made possible to check the real OpenGL resouce name as obtained by `glGenTextures` and similar calls? Correlating RenderDoc with application log or application as seen in debugger would be much easier then.

### Summary

Have some way to get real OpenGL names for the resources RenderDoc is showing.

## Environment

* RenderDoc version: 1.23 (built from df7a3562be505eb9140ec4d5a24714bca322e475)
* Operating System: Windows 10, Windows 11
* Graphics API: OpenGL 4.6.0 NVIDIA 456.71, NVIDIA Corporation, GeForce GT 1030/PCIe/SSE2

RenderDoc view:

![image](https://user-images.githubusercontent.com/6927223/205241737-6b501fb1-3efe-47e7-97b4-03620d3892db.png)

Application log:

```text
bindTexture (TEXTURE_2D,Handle(5),TEXTURE0,TEXTURE0)
bindTexture (TEXTURE_2D_MULTISAMPLE,Handle(6),TEXTURE0,0xffffffff)
setupFrameBufferTexture Handle(4) three.js.renderers.WebGLRenderTarget@74eb909f 4
texImage2DMultisample (TEXTURE_2D_MULTISAMPLE,4,RGBA8,800,600,RGBA,UNSIGNED_BYTE)
bindFramebuffer FRAMEBUFFER 4
framebufferTexture2DMultisampleEXT (COLOR_ATTACHMENT0,TEXTURE_2D_MULTISAMPLE,Handle(6),0,4)
```

**Comment by baldurk** [comment]
No for various architectural reasons this will not be supported.

I would suggest that you give your resources proper human-readable names rather than relying on the auto-generated handles, that way you can be sure that you can tie the resources you see in captures to the original variables.

**Comment by OndrejSpanel** [comment]
> No for various architectural reasons this will not be supported.

Understood. I was afraid there are some.

> you give your resources proper human-readable names

I guess you mean using ObjectLabel from https://registry.khronos.org/OpenGL/extensions/KHR/KHR_debug.txt - that works fine, thanks for the tip.

Actually as a first step I have assigned the OpenGL numeric "names" from the application as labels, getting exactly the functionality I was requesting.
