### ISSUE TITLE
Step over broken in shader debugger

### ISSUE THREAD

**Issue by phantom10111** [baldurk/renderdoc#2786]
## Description

I'm trying to debug shaders compiled to DXBC called from D3D11 code and the "Step Over" function appears to be broken.

Using "Step forwards Over", the debugger actually steps into functions. When that happens using "Step forwards Over" again steps out of the function and goes to the point where the debugger should have been in the first place. A similar thing also happens with "Step backwards Over".

I managed to bisect the issue to commit 935fa49c984f4131fff0223b47ef87c8ad57041b

## Steps to reproduce

Unfortunately, I'm hitting the issue in an application were I can't share the capture. However, I suspect that this issue should be easily reproducible on any nontrivial shader with function calls. In my case the shader is compiled to DXBC using `D3DCompile()` with flags `D3DCOMPILE_DEBUG | D3DCOMPILE_SKIP_OPTIMIZATION | D3DCOMPILE_ENABLE_STRICTNESS`

Sorry for not providing any better reproduction steps, I have spent already quite a lot of time bisecting the issue (because a lot of commits near the offending commit were crashing and had to be skipped). In case this isn't easily reproducible, please let me know and I'll try to provide a capture.

## Environment

* RenderDoc version: Any after commit 935fa49c984f4131fff0223b47ef87c8ad57041b
* Operating System: Windows 10.0.19045
* Graphics API: D3D11
* GPU: NVidia RTX 3070, driver version 527.37

**Comment by baldurk** [comment]
I don't know if it's exactly what you're seeing (it sounds like what you're describing mostly, I think?) but I do see that there's an off-by-one error, where the callstack could be wrong for one instruction when entering a function. Step over was working but because of this there would be an off-by-one when stepping that would jump into a function, but otherwise it would step correctly.

The branch is currently soft locked so I'm not going to commit a fix yet, but you could test this change to see if it works for you:

```patch
diff --git a/renderdoc/driver/shaders/dxbc/dxbc_debug.cpp b/renderdoc/driver/shaders/dxbc/dxbc_debug.cpp
index d734a5255..e72710791 100644
--- a/renderdoc/driver/shaders/dxbc/dxbc_debug.cpp
+++ b/renderdoc/driver/shaders/dxbc/dxbc_debug.cpp
@@ -1953,15 +1953,18 @@ void ThreadState::StepNext(ShaderDebugState *state, DebugAPIWrapper *apiWrapper,

   const Operation &op = program->GetInstruction((size_t)nextInstruction);

-  if(state && debug)
-    debug->GetCallstack(nextInstruction, op.offset, state->callstack);
-
   apiWrapper->SetCurrentInstruction(nextInstruction);
   nextInstruction++;

   if(nextInstruction >= program->GetNumInstructions())
     nextInstruction--;

+  if(state && debug)
+  {
+    const Operation &nextOp = program->GetInstruction((size_t)nextInstruction);
+    debug->GetCallstack(nextInstruction, nextOp.offset, state->callstack);
+  }
+
   rdcarray<ShaderVariable> srcOpers;

   VarType optype = OperationType(op.operation);
```

**Comment by phantom10111** [comment]
Thank you, I can confirm that the fix works for me
