### ISSUE TITLE
R8G8B8_UNORM texture save to png, data is power 2.2 

### ISSUE THREAD

**Issue by CatDroid** [baldurk/renderdoc#2787]
## Description

save R8G8B8_UNORM to png , the data is  (rgb)^2.2， not the origin data（display gamma? power 2.2 ） 

## Steps to reproduce

OpenGlES Texture format is R8G8B8_UNORM （not sRGB）
Save This Texture to Png  
Open this Png in another RenderDoc (Texture Format of png is R8G8B8A8_sRGB)
Location the same position pixel ,  see the color (in Texture Viewer) 

"OpenGlES Texture( format R8G8B8_UNORM)" is 0.1098,  0.47451,  0.35294  (for examle)
"Png( format R8G8B8A8_sRGB) " is 0.0116 ,  0.19141,  0.10205 

0.35294^2.2 is 0.1011 ~= 0.10205  

In Texture Viewer , after Right Click, the color of selected position is the origin data ?
And why the data is changed after saving to the png file ?  

## Environment

* RenderDoc version: v1.22
* Operating System:  Android （host is Window 10） 
* Graphics API:OpenglES

**Comment by baldurk** [comment]
If I have understood you correctly then this is working as expected. PNG files are always considered to be in sRGB space implicitly, so it is not possible to represent linear data in a PNG file. If you have linear data in a texture the PNG file will effectively re-interpret the underlying data as sRGB. RenderDoc does not try to compensate this by reversing the gamma transform before saving as this would be lossy.

The same byte value is stored in each, so e.g. `28, 121, 90` interpreted as plain linear UNORM is `28/255, 121/255, 90/255` = `0.1098, 0.47451, 0.35294`, but when interpreted as sRGB through the png file it is `0.0116, 0.191, 0.102`.

If you want to save the data precisely as linear, especially the case if it's more than 8-bit data, you could use DDS which explicitly supports linear formats. Or you could choose to interpret the PNG data as linear with a custom load, as the same data is there.

**Comment by CatDroid** [comment]
"Note that RenderDoc shows picked texel values in linear float format, so if you pick a pixel that is 0.5, 0.5, 0.5, the actual bytes might be stored as say 186, 186, 186."
in FAQ [Gamma display of linear data, or “Why doesn’t my texture look right?”  ](https://renderdoc.org/docs/getting_started/faq.html)

That means  TextureViewer show data in linear space ? 
 If it's SRGB (e.g png file,  R8G8B8_SRGB),  TextureViewer will convert it to linear space ?  
If it's R8G8A8_Uniform, TextureViewer will show the data Directly ?

**Comment by CatDroid** [comment]
I create a PNG file(a.png) with Drawer,  the data is R,G,B=0,0,128 
then I load it(a.png) in RenderDoc,  Texture Viewer will display its format is R8G8B8A8_SRGB, 
and I save it to anthoer PNG file(b.png),
I found b.png is different from a.png , it's more dark, because B channel is change to 55(not 128).

(128/256)^2.2 * 256  ~= 55 

So texture format is R8G8B8A8_SRGB, and export to png file ,  RenderDoc will export pixel data in linear space(convert sRGB to linear) to png file ? 
 

Do it work as expected ?

**Comment by baldurk** [comment]
That commit should fix this issue, looks like there was an oversight that would cause an incorrect sRGB conversion (or rather, lack of) when saving an SRGB formatted texture to PNG/JPG.

In future please open a new issue for a new bug rather than commenting on an old closed issue.
