### ISSUE TITLE
vkEnumerateDeviceExtensionProperties does not overwrite 'pPropertyCount' when 'pProperties' is non-null.

### ISSUE THREAD

**Issue by bmuzzin** [baldurk/renderdoc#279]
Calling vkEnumerateDeviceExtensionProperties within capturing application, will not properly return the number of extensions in 'pPropertyCount', when 'pProperties' is non-null. If the application depends on this, it may cause it to crash (eg. by inspecting extensions that don't exist, because the input number was too high).

There seems to be some clarification in the latest spec, that 'pPropertieCount' should always be overwritten.

**Comment by baldurk** [comment]
See discussion about this on #280.
