### ISSUE TITLE
Captured BC7 Texture may have wrong mip data

### ISSUE THREAD

**Issue by qiankanglai** [baldurk/renderdoc#2792]
## Description

Replay in renderdoc has strange data with some bc7 textures.

## Steps to reproduce

1. using a BC7 texture with size(560x220) and 6 mips
2. mip0 is fine, but higher mip has wrong data (just use `SampleLevel(uv, 2)` for visualization)
3. game window is running ok(right), but replaying in renderdoc has strange data (left)
![image](https://user-images.githubusercontent.com/1546130/206986323-c40f1a1c-a639-459e-bbd7-d55841266e02.png)

Texture for test is attached here: [seafloor.zip](https://github.com/baldurk/renderdoc/files/10205521/seafloor.zip)

## Environment

* RenderDoc version: 1.24 and 1.25 development
* Operating System: Win 11
* Graphics API: DX11

**Comment by qiankanglai** [comment]
I tried debugging for more information in this way:
- dump data from `WrappedID3D11Device::Serialise_CreateTexture2D` into dds container
- mip0 has the right image, but other mips already have artifacts

![image](https://user-images.githubusercontent.com/1546130/206988418-69910fbd-63ea-4282-934c-86fca4a233d1.png)

I'll try later after work for more details. Any help is highly appreciated 😃

**Comment by baldurk** [comment]
There was some code handling linearised access to block textures which wasn't properly calculating the number of rows when the mip was non-power-of-two. That's been fixed and it seems to work for me now.

**Comment by qiankanglai** [comment]
This commit works and thanks a lot for quick response.
