### ISSUE TITLE
VK_LAYER_RENDERDOC_Capture layer invokes a debug_utils msg callback with null "pMessageIdName"

### ISSUE THREAD

**Issue by djewsbury** [baldurk/renderdoc#2793]
## Description

VK_LAYER_RENDERDOC_Capture uses debug_utils to send a message during vkCreateDevice that reads "While debugging through RenderDoc, debug output through validation layers is suppressed.\n...". This message has a null pMessageIdName member. If a capturing application has a debug callback installed through vkCreateDebugUtilsMessengerEXT, they will recieve this msg, and must correctly handle the null input.

I'm not sure if the extension specs allows nullptr for this particular member (prehaps correct clients must handle nulls) but it may be preferable to make this an empty string, particularly considering that Renderdoc is a useful tool to use while developing an unfinished client.

If the client doesn't correctly handle null here, the experience is pretty confusing -- because the application will just crash immediately when launched from Renderdoc. There's no indication from renderdoc that there was a crash in vkCreateDevice. And as far as I know, on Windows at least, it's difficult to catch this situation in a debugger. This is also the only message I've come across with null for pMessageIdName.

I had this issue and found the cause almost accidentially -- so given that if anyone encounters this problem they may find it nontrivial to solve, and hoping that the solution is an easy one, I wanted to suggest changing it.

## Steps to reproduce

1. In https://github.com/KhronosGroup/Vulkan-Tools/blob/master/cube/cube.c, add the following line before line 524:
		assert(pCallbackData->pMessageIdName);
2. compile in debug configuration
3. attempt to capture in Renderdoc with --validate on the command line
		(or explicitly enable the VK_LAYER_RENDERDOC_Capture instance layer)

## Environment

* RenderDoc version: RenderDoc_2022_12_07_cdf1bf5e_64
* Operating System: Windows 10
* Graphics API: Vulkan 1.2

**Comment by baldurk** [comment]
A NULL value for `pMessageIdName` is entirely valid, and so yes applications should be handling this correctly. Compare 

> VUID-VkDebugUtilsMessengerCallbackDataEXT-pMessageIdName-parameter
> If pMessageIdName is not NULL, pMessageIdName must be a null-terminated UTF-8 string

with

> VUID-VkDebugUtilsMessengerCallbackDataEXT-pMessage-parameter
> pMessage must be a null-terminated UTF-8 string

There are any number of ways where an application could misbehave and crash only when run by RenderDoc if they don't behave validly and it's not feasible to fix them all. Some other application with a bug may skip a NULL string here but break if the string is non-NULL and empty, expecting it to contain some actual ID (for which RenderDoc's message has no ID to put).

Also note you should never manually enable the RenderDoc layer by hand. You should always run your program from RenderDoc correctly.

In future if you want to attach a debugger then you can make use of the 'debugger delay' capture option when launching your program, to attach a debugger before any code runs, assuming you don't have a just-in-time debugger configured to catch the unhandled exception.

**Comment by djewsbury** [comment]
Fair enough; I can see your reasoning & I wasn't aware of the debugger delay feature previously, but can see how it can help in this case. Just wanted to throw it out there.
