### ISSUE TITLE
Performance counter viewer: Capture counters crash

### ISSUE THREAD

**Issue by bkhan-dev** [baldurk/renderdoc#2795]
## Description

When I load a capture that contains a compute pipeline, and attempt to fetch counters in the performance counter viewer, the application crashes (not responding). 

For testing, I used one of the official Khronos samples: Compute shader N-Body simulation https://github.com/KhronosGroup/Vulkan-Samples).
As well as a sample from Sascha Willems' older vulkan samples repo (https://github.com/SaschaWillems/Vulkan): cloth simulation

## Steps to reproduce

1. Launch application for capture:
Exe path: <path_to_vulkan_samples_exe>
Working Directory: <path_to_vulkan_samples_root>
Command-line arguments: sample compute_nbody
2. Take the capture
3. Go to performance counter viewer, click capture counters, select all generic counters, and press sample counters.

For your convenience, I have emailed you the compute shader n-body simulation capture. 

## Environment

* RenderDoc version: 1.22 (tried 1.24 too)
* Operating System: Windows 11
* Graphics API: Vulkan
* GPU: RTX 3060 TI

**Comment by baldurk** [comment]
It looks like this only happens when you have command buffers on a compute-only queue. Compute dispatches on a normal graphics queue work fine with the counters. I'll look into fixing this, but if you avoid compute-only queues that would be a workaround in the meantime.

**Comment by baldurk** [comment]
That commit should fix the issue, though unfortunately it seems there's a driver bug on NV that causes a device lost error (may easily manifest in an infinite progress bar fetching counters). It's been reported to NV and should hopefully be fixed in the next vulkan developer driver.
