### ISSUE TITLE
ModuleNotFoundError: No module named 'encodings'

### ISSUE THREAD

**Issue by byte-sized-emi** [baldurk/renderdoc#2797]
## Description

While installing RenderDoc with the tarball on Pop_OS! 20.04 (based on Ubuntu 20.04), I run into a problem - whenever I try and execute `qrenderdoc`, I get the following output:

```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fdf14e2ac00 (most recent call first):
[1]    14069 IOT instruction (core dumped)  qrenderdoc
```
I have python3 installed from apt (as well as python-is-python3), there are no other versions installed, there should be no venv, so I'm not sure what is causing this. PYTHONHOME and PYTHONPATH are both not set. Python is up-to-date.

## Steps to reproduce

 - Copy qrenderdoc and renderdoccmd from the most recent tarball (v1.24) into /usr/bin
 - execute `qrenderdoc`

## Environment

* RenderDoc version: v1.24
* Operating System: Pop_OS! 20.04
* Graphics API: not needed

If you need anymore info, please ask.

**Comment by IoIxD** [comment]
Hi, I'm having this exact issue, do you remember what you did to fix this?

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
