### ISSUE TITLE
GLSL (SPIRV-Cross) uses --vulkan-semantics for OpenGL shader

### ISSUE THREAD

**Issue by hanfling** [baldurk/renderdoc#2798]
## Description

I'm debugging an OpenGL application which uses SPIRV shader with OpenGL specific buildins like gl_VertexID. When I view shader disassembly and select the GLSL (SPIRV-Cross) option, it will fail for shaders with OpenGL only buildins like gl_VertexID:

	Running "C:/VulkanSDK/1.2.135.0/Bin/spirv-cross.exe" --vulkan-semantics --entry main --stage vert --output C:/Users/Han/AppData/Local/Temp/shader_output C:/Users/Han/AppData/Local/Temp/shader_input
	SPIRV-Cross threw an exception: Cannot implement gl_VertexID in Vulkan GLSL. This shader was created with GL semantics.

	Process exited with code 1.
	Output file is 0 bytes

Note that this will work for at least for some shaders (which are likely using a subset of the intersection of OpenGL and Vulkan GLSL feature set).

My expectation is that this should produce GLSL code instead of an error message.

## Steps to reproduce

Capture an OpenGL application using SPIRV Shaders, which uses gl_VertexID buildin in the vertex shader.

For example: https://github.com/hanfling/ogglepie/tree/master/TriangleNoVertexAttributes
Capture of above [TriangleNoVertexAttributes.rdc.zip](https://github.com/baldurk/renderdoc/files/10253859/TriangleNoVertexAttributes.rdc.zip)

Get to the shader disassembly view and select "GLSL (SPIRV-Cross)" from the dropdown menu.

## Environment

* RenderDoc version: 1.24 (Qt version 5.15.2)
* Operating System: Win10
* Graphics API: OpenGL
* Stuffed Animal: Puschl
* GPU Vendor: NVIDIA

**Comment by hanfling** [comment]
Forgot to mention: As of now loading renderdoc captures of OpenGL applications using SPIRV shaders crashes with AMD's current Windows driver (Adrenalin 22.11.2). This issue is already fixed on AMD's end, but will take some time to hit a public driver. Just in case you run into this issue, to save you some headache and needless work. :)

**Comment by hanfling** [comment]
From spirv-cross.exe output:

	Select backend:
					By default, OpenGL-style GLSL is the target, with #version and GLSL/ESSL information inherited from the SPIR-V module if present.
					[--vulkan-semantics] or [-V]:
									Emit Vulkan GLSL instead of plain GLSL. Makes use of Vulkan-only features to match SPIR-V.

So looks like for opengl glsl the --vulkan-semantics option just needs to be removed.

**Comment by baldurk** [comment]
I'll have a think about this, but I don't think I want to entangle the capture's current API into how shader processing tools are configured. Especially if it's only relevant for a very narrow use-case like SPIR-V on GL.

I would suggest that you configure a new 'SPIRV-Cross (OpenGL)' with the appropriate options. You can make it higher priority than the default SPIRV-Cross if you want it to appear first on the list.

**Comment by baldurk** [comment]
I've put in a workaround which is ugly but minimally impactful, pretending that GL SPIR-V and Vulkan SPIR-V are distinct and unique shader formats and duplicating the builtin tools to handle both, rather than trying to hook in the API as an additional parameter. This means there's nothing to stop you from misconfiguring a shader tool but it will at least automatically select the appropriate tool for SPIR-V cross, and allow you to configure custom tools to work automatically if you are using GL SPIR-V.

**Comment by hanfling** [comment]
Thank you.
