### ISSUE TITLE
RenderDoc not detecting Vulkan API when VkApplicationInfo.apiVersion is set to a non-valid Vulkan API version

### ISSUE THREAD

**Issue by Extevious** [baldurk/renderdoc#2800]
## Description

RenderDoc not detecting Vulkan API when `VkApplicationInfo.apiVersion` is set to a non-valid Vulkan API version. RenderDoc should display a error message in the status box like "unsupported version" instead of "none".

![image](https://user-images.githubusercontent.com/51515448/208880856-6862311f-a481-43da-83f9-f9bc069ea973.png)

## Steps to reproduce

Change the `apiVersion` of your `VkApplicationInfo` to an invalid version (I did `~1u` for testing purposes.)

Either use my example test repo: https://github.com/Extevious/VulkanTestEnvironment (edit line 20 to see effect)
***OR***
Modify your own project.

## Environment
* RenderDoc version: 1.24
* Operating System: Windows 10 19045
* Graphics API: Vulkan 1.3.231.1

**Comment by baldurk** [comment]
RenderDoc does not support invalid API use. It may work, or it may crash, or anything in between when encountered.
