### ISSUE TITLE
Workarounds for proprietary Adreno VK driver are also applied to Turnip because they share same vendorID

### ISSUE THREAD

**Issue by werman** [baldurk/renderdoc#2804]
## Description

Turnip has the same `vendorID` (https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/freedreno/vulkan/tu_device.c#L1312) as proprietary driver, to _potentially_ improve compatibility with apps tuning their perf settings. This causes RenderDoc to apply the same workarounds to Turnip as to proprietary driver: https://github.com/baldurk/renderdoc/blob/5e04ab288d8cddf9f0e226edb435a3c48c7cfd85/renderdoc/driver/vulkan/vk_common.cpp#L1029-L1043

On the other hand we have `driverID == VK_DRIVER_ID_MESA_TURNIP`. I think if `driverID` is available it should also be taken into consideration.

## Steps to reproduce

- Do any capture on Turnip
- Notice that Qualcomm driver workarounds are enabled.

## Environment

* RenderDoc version: 5e04ab2
* Operating System: Linux
* Graphics API: Vulkan
* Driver: Turnip

**Comment by baldurk** [comment]
That commit prefers the driverID over the vendorID which should address this, though I can't run turnip so I can't verify it for sure.

**Comment by werman** [comment]
Thanks!

@baldurk that change trips `-Werror`:
```
../renderdoc/driver/vulkan/vk_common.cpp:977:47: error: this statement may fall through [-Werror=implicit-fallthrough=]
  977 |     case VK_DRIVER_ID_MESA_LLVMPIPE: m_Vendor = GPUVendor::Software;
      |                                      ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
../renderdoc/driver/vulkan/vk_common.cpp:978:5: note: here
  978 |     case VK_DRIVER_ID_MOLTENVK: metalBackend = true;
      |     ^~~~
cc1plus: all warnings being treated as errors
```

Otherwise works as expected.

**Comment by baldurk** [comment]
Thanks, fixed. A little worrying that CI or my local build didn't catch that as I should have case fallthrough warnings enabled...
