### ISSUE TITLE
glBlendFunc(GL_ONE, GL_ONE) is reported as (GL_LINE, GL_LINE)

### ISSUE THREAD

**Issue by LordOfDragons** [baldurk/renderdoc#2806]
## Description
Whenever a "glBlendFunc" is listed in the Callstack window with a parameter "GL_ONE" the wrong name "GL_LINE" is instead shown. This bug seems to affect only the "GL_ONE" constant. For example "GL_SRC_ALPHA" and "GL_ONE_MINUS_SRC_ALPHA" are correctly shown.

## Steps to reproduce
- Load a program using "glBlendFunc".
- Find a use of "glBlendFunc" with the parameter "GL_ONE"
- The line will read "GL_LINE" instead

## Environment
* RenderDoc version: 1.24
* Operating System: Linux
* Graphics API: OpenGL

**Comment by baldurk** [comment]
This is a design flaw in GL, as these "enums" (not actual enums, just defines) have the same value - 0x1 and 0x0. The automatic stringification in the serialisation can't tell the difference and this is not worth adding a bunch of manual fixups for.

The blend function is displayed correctly in the pipeline state viewer along with the other state, which is the best and recommended place to get this information.

**Comment by LordOfDragons** [comment]
Can you explain this to me? If I check in OpenGL then "GL_ONE" has a value of "1" but "GL_LINE" has a value of "0x1B01". Why are these equal? Doesn't make sense to me or am I missing something here?

**Comment by baldurk** [comment]
If it's actually showing `GL_LINE` then that's a bug, yes. I was assuming you had made a typo in your report and it was showing up as `GL_LINES`.

**Comment by LordOfDragons** [comment]
You are right, my bad. It's "GL_LINES". Then it makes sense.
