### ISSUE TITLE
Impossible to select certain pixels in the texture viewer with certain texture sizes on D3D

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2807]
## Description

Certain pixels cannot be selected in the texture viewer with certain texture sizes on D3D11 and D3D12. I haven't done extensive testing, but I did run into this where y=15 and y=30 cannot be selected on an 80 by 58 texture. My guess is that it is related to texture sizes that aren't divisible by 4, but I haven't done extensive testing on this. (**EDIT**: That isn't accurate: 40 by 30, 20 by 16, 10 by 8, 6 by 4, and 4 by 2 are all unaffected.) This even applies when using the goto location function. The pixels do appear properly on screen in the texture viewer and in the raw buffer viewer, though.

This affects the texture when used both as an input and as an output (the attached test case only shows it as an output, though).

The attached test case is something I quickly hacked together by adding a 80 by 58 framebuffer copy to the existing demo, as I had ran into this in a different game. Oddly, it wasn't possible for me to just resize Glass.bmp to be 80 by 58; the wii homebrew toolchain automatically resizes it to be 80 by 60 in that case (and I'm not 100% sure why, as I'm pretty sure nothing actually prevents 80 by 58 textures, although there are some limitations with non-power-of-2 textures on the GameCube and Wii).

## Steps to reproduce

1. In Dolphin, run `lesson08_efbcopy.dol` from [lesson08_efbcopy.zip](https://github.com/baldurk/renderdoc/files/10301996/lesson08_efbcopy.zip).
2. Make a capture.
3. Select the draw command corresponding to that (in the attached `lesson08_efb_copy_80by58.rdc`, this is EID 162)
4. In the texture viewer, attempt to right-click a pixel at y=15. It will never be selected, instead always giving y=14 or y=16; this applies even when using the goto location function. The same also applies for y=30.

## Environment

* RenderDoc version: 1.24
* Operating System: Windows 10
* Graphics API: D3D11 or D3D12 (OpenGL is **not** affected. Vulkan is untested due to #2805).

**Comment by baldurk** [comment]
Looks like there was a rounding error introduced in 234262649f7 where calculating the per-mip integer co-ordinate would round incorrectly because of float order of operations and then get floor'd. That commit should fix it.
