### ISSUE TITLE
Mark GL_EXT_shader_framebuffer_fetch as supported on non-ES OpenGL

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2809]
## Description

Dolphin currently uses built-in blending behaviors. However, there are a couple of games where this causes problems (e.g. making assumptions on what happens when an alpha value of 1/255 is used, or bloom ends up being too strong due to different rounding). I've been looking into using framebuffer fetch to more accurately handle this. This doesn't seem to be supported on many devices, but it seems like desktop intel GPUs support it on OpenGL (there's also support on mac and mobile GPUs apparently, but I don't have easy access to those). However, RenderDoc currently only includes it in the list of extensions on OpenGL ES, not on OpenGL. This makes it harder for me to debug my code using it, as it ends up detecting the extension as not supported.

Since things appear to work properly if I add `#extension GL_EXT_shader_framebuffer_fetch: enable` to my shader despite it not being in the extensions list, I think all that is needed is to add it into the extensions list (and remove [the comment](https://github.com/baldurk/renderdoc/blob/5047c68318b5deca35148743c518f2fed7274511/renderdoc/driver/gl/gl_driver.cpp#L301) saying it's not supported). Based on skimming over [EXT_shader_framebuffer_fetch.txt](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_shader_framebuffer_fetch.txt), I don't think there's any difference in behavior between the extension on regular OpenGL and OpenGL ES. Please let me know if I'm mistaken.

An alternative fix would be for Dolphin to create an OpenGL ES context instead, but currently Dolphin's WGL implementation [only supports desktop GL](https://github.com/dolphin-emu/dolphin/blob/f6fbeaf3554b3af06d9e1584189bcf2274838063/Source/Core/Common/GL/GLInterface/WGL.cpp#L304-L305). I'm going to look into fixing this (which probably involves [WGL_EXT_create_context_es2_profile](https://registry.khronos.org/OpenGL/extensions/EXT/WGL_EXT_create_context_es2_profile.txt)), but it would be nice to not require this.

## Environment

* RenderDoc version: v1.24
* Operating System: Windows 10
* Graphics API: OpenGL

**Comment by baldurk** [comment]
That commit should allow the extension, since indeed it's mostly shader-side and has no effect on replay. I definitely wouldn't recommend using GLES when GL is available, since GLES is just a crappy knock-off version of proper GL :).

**Comment by Pokechu22** [comment]
Thanks. FYI, it looks like it's still listed in the comment of unsupported extensions [here](https://github.com/baldurk/renderdoc/blob/f8b3dc77e9440eb1ea540c8781bb87020fa3cbaf/renderdoc/driver/gl/gl_driver.cpp#L302).

I'm going to still look into also supporting GLES via WGL since there are times when it would have been helpful for investigating issues related to GLES compatibility (on other platforms where GLES is already available or the only option). But it won't be a priority.
