### ISSUE TITLE
Windows ARM64 Support

### ISSUE THREAD

**Issue by Beyley** [baldurk/renderdoc#2810]
## Description

I recently bought a Windows ARM Developer kit (aka Volterra) and have been using it as the main device for Windows (D3D11/12) development on my game engine (as my workstation is Linux-only, and stands in as a Linux testing box too)

I attempted to use the x86-64 version of renderdoc to capture my app, but it complains that it cannot inject into the process, which i believe is just a problem with the x86-64 to ARM64 emulation layer, if possible, a native ARM64 version of renderdoc would be nice to have, as renderdoc is an essential part of my graphics development workflow when doing VK or OpenGL development on Linux

## Environment

* RenderDoc version: v1.24
* Operating System: Windows 11 on ARM64
* Graphics API: Direct3D11 + Direct3D12

**Comment by baldurk** [comment]
I have no plans of ever supporting ARM on non-Android platforms.

**Comment by maluoi** [comment]
Vulkan just recently released a beta of their Windows ARM SDK, and I was poking around with it on my Snapdragon X Elite device. I ran into the same issue as OP here. Is this at all open to re-evaluation given the recent wave of ARM64 hardware?

**Comment by Zorro666** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
