### ISSUE TITLE
Crash when selecting a vkCmdWaitEvents2

### ISSUE THREAD

**Issue by farnoy** [baldurk/renderdoc#2814]
## Description

I'm updating my app to use VkEvents all over the place and I noticed that RenderDoc crashes when selecting one of these wait barriers. It captures just fine, and the UI otherwise seems to work until I select any of the related commands.

Capture causing the crash: https://gofile.io/d/Ut9shC
Crash Dump: [dzsk3.zip](https://github.com/baldurk/renderdoc/files/10344598/dzsk3.zip)

## Steps to reproduce

1. Open the attached capture
2. Select one of the vkCmdWaitEvents2 in the action list
3. The app crashes, Bug Reporter opens up

## Environment

* RenderDoc version: 1.24
* Operating System: Windows 11
* Graphics API: Vulkan 1.3
* Nvidia: 526.98 on a 4090

**Comment by farnoy** [comment]
I think my VkEvent usage is fine, it passes the sync validation as of the latest Vulkan SDK without issues.

**Comment by baldurk** [comment]
I believe this is fixed in 7b9c4c782ecafce85c39f67c966e3870d9e81a50 since v1.24. If you try any nightly build from the last week or so it should work.

Out of interest, what's your motivation for having those event commands included in the event browser filter and selecting them?

**Comment by farnoy** [comment]
Thanks, I can confirm it's working fine as of [f8b3dc77](https://github.com/baldurk/renderdoc/tree/f8b3dc77), 2023-01-04

> Out of interest, what's your motivation for having those event commands included in the event browser filter and selecting them?

I wanted to use RenderDoc to ensure I'm setting up my resource transitions correctly. It would be ideal if RenderDoc supported Events in the "Usage in frame" panel, but I can track them easily by tagging regions with debug markers, and naming VkEvents  so that they mention source & destination call sites.

![image](https://user-images.githubusercontent.com/345808/210784535-f7d41b13-f90f-4457-a779-21e55407356b.png)
