### ISSUE TITLE
Crash in DiscardView on DX11.1 context

### ISSUE THREAD

**Issue by DrGr4f1x** [baldurk/renderdoc#282]
My application is crashing in RenderDoc on a call to DiscardView on ID3D11DeviceContext1, with an RTV parameter.  The RTV is bound to the swapchain backbuffer, if that case is somehow weird in RenderDoc.  If I remove the DiscardView call, my application runs as expected and I can get captures.

**Comment by baldurk** [comment]
Yeh this was just completely broken before. I think it should be working now.

**Comment by baldurk** [comment]
Closing this issue as the bug should be fixed in [v0.30](https://github.com/baldurk/renderdoc/releases/tag/v0.30). Feel free to re-open if it's not as you expect!
