### ISSUE TITLE
RenderDoc failed to launch a glProgramBinary sample.

### ISSUE THREAD

**Issue by tonyx123** [baldurk/renderdoc#2821]
## Description

Attempt to use RenderDoc to capture an OpenGL sample but failed. The application is a sample of glProgramBinary, https://github.com/g-truc/ogl-samples/blob/master/samples/gl-410-program-binary.cpp. When launching with RenderDoc it always failed after glProgramBinary & glGetProgramiv, the "glGetProgramiv(ProgramName[program::VERT], GL_LINK_STATUS, &Success);" Success is GL_FALSE. It's fine if the application runs without RenderDoc.

## Steps to reproduce

1. Clone and build https://github.com/g-truc/ogl-samples 
2. Manually delete \ogl-samples\data\gl-410\*.bin and run gl-410-program-binary.exe to re-generate the binary.
3. Launch gl-410-program-binary.exe with RenderDoc, the graphical window fails to show and can't be launched.

## Environment

* RenderDoc version: v1.24 (e5e68ef2)
* Operating System: Win10
* Graphics API: OpenGL
* GPU: RTX2060
* Driver: 527.86 (Nvidia Vulkan Beta driver from https://developer.nvidia.com/vulkan-driver)

**Comment by baldurk** [comment]
This is not a RenderDoc bug - the program you've mentioned seems to fatal error if a program binary is rejected by GL, but it is legal for any GL implementation to reject a program binary for any reason at any time. That is the behaviour you're seeing.

I would recommend that any program using program binaries have a fallback to upload glsl if the program binary fails to upload.

**Comment by tonyx123** [comment]
Thank you for the explanation, so it's legal to fail to launch the program. I want to know if RenderDoc is able to view the shader source for glProgramBinary cases, could you tell me that directly?

**Comment by baldurk** [comment]
The program launches fine, that doesn't fail. The program then has a fatal error when the program binary fails to load - that's fine but is entirely up to the program's logic and it would be quite possible to fall back to uploading shader source.

Program binaries are forced to fail precisely because there is no shader source to process, so the question doesn't really make sense.
