### ISSUE TITLE
vkCreateComputePipelines does not handle chained VkShaderModuleCreateInfo

### ISSUE THREAD

**Issue by doitsujin** [baldurk/renderdoc#2826]
## Description
On implementations that support `VK_EXT_graphics_pipeline_library`, we will do the following in DXVK:

```c++
VkShaderModuleCreateInfo codeInfo = { VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO };
codeInfo.codeSize = ...;
codeInfo.pCode = ...;

VkComputePipelineCreateInfo info = { VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO };
...
info.stage = { VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, &codeInfo };
info.stage.stage = VK_SHADER_STAGE_COMPUTE_SHADER_BIT;
info.stage.pName = "main";

VkPipeline pipeline = VK_NULL_HANDLE;
VkResult vr = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
```

This will currently crash RenderDoc during capture.

While the extension obviously mostly interacts with graphics pipelines, the spec allows chaining a `VkShaderModuleCreateInfo` struct for compute and ray tracing pipelines as well.

## Steps to reproduce

I've bundled a test application from our [dxvk-tests](https://github.com/doitsujin/dxvk-tests) repo with a current build of DXVK that runs into this issue: [repro.tar.gz](https://github.com/baldurk/renderdoc/files/10456688/repro.tar.gz)

It's probably easiest to run this on Windows with an up-to-date Nvidia driver, other vendors still do not seem to ship the extension.

Alternatively, on Linux, with a driver that supports EXT_gpl (see below), run:

```sh
export WINEPREFIX=$HOME/.wine-test
winetricks d3dcompiler_47
export WINEDLLOVERRIDES=dxgi,d3d11=n
export ENABLE_VULKAN_RENDERDOC_CAPTURE=1
wine d3d11-compute.exe
```

Linux drivers that this can be triggered on are:
- Lavapipe from Mesa 22.3+
- Nvidia (520 or 525 series)
- RADV (from mesa-git when setting `RADV_PERFTEST=gpl`)

## Environment

* RenderDoc version: 653028fa0df9e115f81c54dba72bf816e577e5ac
* Operating System: Linux
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Huh, yeh I only thought about it in the context of graphics pipelines but I guess since the usage is defined on `VkPipelineShaderStageCreateInfo` it applies equally to compute pipelines as well. Easy enough to replicate the behaviour into that function, I'll update this today.

**Comment by baldurk** [comment]
That commit should handle this, it works for me on your test program.

**Comment by doitsujin** [comment]
thanks!
