### ISSUE TITLE
Histogram visualization is stale for different mipmap levels after changing custom shader

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2828]
## Description

The histogram visualization seems to re-use the values from the previous custom shader once after modifying the custom shader when changing mipmap levels.

Note that the histogram itself _does_ update when changing levels, just to the value for the previous custom shader. Furthermore, the incorrect set of values is only used once, becoming correct after switching away from the new mipmap level and back again. This only seems to happen if both the texture viewer and shader editor are visible at the same time. Also, the selected mipmap level _is_ immediately updated; it's only the other mipmap levels that exhibit this behavior.

## Steps to reproduce

1. Load a capture that contains a texture with multiple mipmap levels.
2. Select a texture with multiple mipmap levels.
3. Set channels to "custom".
4. Enter a name for the custom shader, and then click the "+". I used a GLSL shader.
5. Drag the "editing fragment shader" tab and dock it on the side of the screen so that both it and the texture viewer are visible at the same time (this is required; the issue does not happen if you need to switch tabs to see the texture viewer).
6. Enter the following as the shader:
    ```glsl
    #version 420 core

    layout (location = 0) in vec2 uv;

    layout (location = 0) out vec4 color_out;

    uint RD_SelectedMip();

    void main()
    {
    	color_out = vec4(0, .1 + .2 * RD_SelectedMip(), 0, 0);
    }
    ```
7. Click "refresh". The texture viewer should immediately update.
8. Enable the histogram in the texture viewer.
9. Scroll through all of the mipmaps. The histogram should (probably?) look correct for them all.
10. Change the shader to this:
     ```glsl
    #version 420 core
    
    layout (location = 0) in vec2 uv;
    
    layout (location = 0) out vec4 color_out;
    
    uint RD_SelectedMip();
    
    void main()
    {
    	color_out = vec4(.5, .15 + .2 * RD_SelectedMip(), .4, .3);
    }
    ```
11. Click "refresh". The texture viewer and histogram should immediately update.
12. Scroll through all of the mipmaps. Observe that the histogram is that of the original shader (a changing line and a line at 0), not that of the new shader (4 distinct lines).
13. Scroll through all of the mipmaps again. Observe that the histogram is now correct.

## Environment

* RenderDoc version: v1.24
* Operating System: Windows 10.0.19044.2486
* Graphics API: Vulkan (I have not tested other APIs, but it probably affects them, although the shader may need changes)

**Comment by baldurk** [comment]
Thanks for the report. This was an order-of-operations problem, it wasn't refreshing the rendered custom shader for a new mip level before fetching the histogram data. That commit should fix the issue.
