### ISSUE TITLE
qrenderdoc freezes after selecting draw call

### ISSUE THREAD

**Issue by clickingbuttons** [baldurk/renderdoc#2829]
## Description

qrenderdoc freezes after selecting a draw call

## Steps to reproduce

Run https://github.com/clickingbuttons/jeditrader/tree/no-db

Also, here's a capture: [freezes.rdc.txt](https://github.com/baldurk/renderdoc/files/10472922/freezes.rdc.txt)

## Environment
* RenderDoc version: QRenderDoc v1.23 (df7a3562be505eb9140ec4d5a24714bca322e475)
* Operating System: Linux 6.1.7-arch1-1 x86_64 GNU/Linux
* Graphics API: Vulkan 1.1
* GPU: Nvidia GeForce 1080 driver version 525.78.01

[RenderDoc_2023.01.21_14.28.22.log](https://github.com/baldurk/renderdoc/files/10472929/RenderDoc_2023.01.21_14.28.22.log)

I also tried the latest build on Github which has the same issue:
* QRenderDoc v1.25 (4e02449617a7284415d39e59da4454cdab0ed1cd)

It additionally logged this to stderr:
```
NVPERF|ERR|2023-Jan-21|14:50:20:781|InitializeNvPerf || NVPW_InitalizeHost failed
```

**Comment by baldurk** [comment]
Verified as an application error over discord.

**Comment by clickingbuttons** [comment]
Caused by https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdBindDescriptorSets-pDescriptorSets-00358
