### ISSUE TITLE
a error wrning when i lauch any application in renderdoc

### ISSUE THREAD

**Issue by 1064347558** [baldurk/renderdoc#2833]
## Description

Excuse me, I met a problem when i lauch an appllication in latest version of renderdoc 
but warning 'error connenting to debugger...'

i have ensured my phone's "ro.debuggable" = 1, but still can't fix the problem.
i searched in issue page and found the "Can't connect android device using version 1.0 " which include the same problem.
so i tried to use the nightly build version 2018_3_14, 2018_3_13, but they all get the same problem, i wonder how can i fix it and lauch the application successfully, thank you!

## Steps to reproduce

I use the phone whose android version is 7.1.2.
connect to the renderdoc and the remote server is running
i lauch some game such as kartrider2 and stumble guys, 
![image](https://user-images.githubusercontent.com/112362267/214598807-63b8f276-05ef-4def-a8e9-554fc81e33e8.png)
and get the warning
![image](https://user-images.githubusercontent.com/112362267/214599087-05e600ca-6ef1-441a-81f5-a2daf1dad0ea.png)

## Environment

* RenderDoc version: v1.42,   nightly build version:2018_3_14,2018_3_13
* Operating System: win 10 22H2
* Graphics API: opengles

my test phone's SOC is snapdragon 616, a littile bit old

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
