### ISSUE TITLE
Some textures sizes / DPI values do not allow for precise pixel selection

### ISSUE THREAD

**Issue by iOrange** [baldurk/renderdoc#2836]
## Description

Some textures sizes / DPI values do not allow for precise pixel selection
I'm on 4k monitor with 200% resolution scale (DPI scale factor 2.0)

## Steps to reproduce

Occurred to me during capture analysis, but can be easily reproed without it even:

- Create image of size 3440x1440 in any image editor (Paint works)
- Save to any format supported by RenderDoc
- Open image in RenderDoc
- Try to select pixel 1764 x 762 - no luck

## Environment

* RenderDoc version: 1.24 (any recent actually, even built from github tip)
* Operating System: Windows 10/11
* Graphics API: Doesn't matter

## More Details

As I already mentioned - my setup is 4k monitor with 200% resolution scale
The issue comes from `MipCoordFromBase` as it uses float to calc scaled pixel pos and fails in this case
"Fixed" it in my local build by early-out `if mip == 0`, but I guess needs proper fix ?

**Comment by baldurk** [comment]
This isn't DPI related, but yes the epsilon for rounding wasn't properly applied. I've fixed it now.
