### ISSUE TITLE
Fill discarded resources with some easy to spot pattern

### ISSUE THREAD

**Issue by Anteru** [baldurk/renderdoc#284]
Resource discarding is a great way to avoid clears, yet provide the driver with information that a resource is no longer needed. In D3D12, it's also useful for placed resources which can be initialized using discard.
However, if you capture with "Save all initials", it's impossible to tell if a resource has been discarded or not. Would be great to have a text overlay on textures (DISCARD) or so, and for buffers, some easy to spot pattern. 0xD15C or something like this. Applies to all APIs that have a way to discard resources.

**Comment by baldurk** [comment]
I've implemented these discard patterns for textures and buffers, it should support any format/dimension combination and the pattern varies for APIs where relevant, e.g. with DONT_CARE renderpass ops on vulkan:

![image](https://user-images.githubusercontent.com/661798/87331669-4121eb00-c532-11ea-8bed-ff9e015cfb00.png)

**Comment by Anteru** [comment]
Thanks, glad to see this!
