### ISSUE TITLE
Using vmaCreateBuffer will cause Development build renderdoc output invalid warining message.

### ISSUE THREAD

**Issue by leozzyzheng** [baldurk/renderdoc#2842]
## Description

I'm using [VulkanMemoryAllocator](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator) to help me manage the memory when using Vulkan and I'm also debugging some hangs when using renderdoc to capture my game, so I'm using the version compiled by myself.

Then I found the renderdoc will output some message like `Truncating memory size %llu to dedicated buffer size %llu for %s`, after debugging, it seems this warning is invalid when using `vmaCreateBuffer` to create buffer. Here is what I found:

1. [VMA call vkCreateBuffer](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L17011) with the exact size passed by user, let's see we are creating buffer with size 500.
2. [VMA check buffer memory requirements](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L17022), in my computer, it returns alignment with 256 and with size 512.
3. VMA use this memory requirement size 512 to allocate memory, the arugment will [pass buffer object](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L14598).
4. Renderdoc hook the vkAllocateMemory and check [memory size is same to buffer size](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/vulkan/wrappers/vk_resource_funcs.cpp#L362), then output the debug warining message.

Since Vma has already done the memory requirement check, so I think Serialise_vkAllocateMemory could check if the memory allocate size is already meet the requirement for the dedicated buffer creation and not to output warning message?

## Steps to reproduce

1. Using `vmaCreateBuffer` from  [VulkanMemoryAllocator](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator) to create buffer with size not align to memory requirements. For example, if the buffer memory requirements need alignment of 256, create the buffer with size 500, the you might get this message in output.

## Environment

* RenderDoc version: Build from tag v1.24
* Operating System: Window 10
* Graphics API: Vulkan 1.1.0

**Comment by baldurk** [comment]
Your report does not clearly outline what the actual bug is. You list a log message which is irrelevant and the log is intended for RenderDoc developers only, it is not user facing and you should not be reading it or doing anything with it.

Is this causing a crash? what other misbehaviour is the actual bug? Your steps to reproduce are also incomplete since you do not provide any information about the details of the buffer and its creation info, which may easily be relevant.

Please outline what the actual problem you observe is and complete steps to reproduce it.

**Comment by leozzyzheng** [comment]
It actually doesn't cause crash or misbehaviour, it only print a invalid log message when using development RenderDoc.
So I will close this issue since it won't affect any user.

The pure Vulkan step to reproduce is:
1. vkCreateBuffer, doesn't need any special create info, just use a unaligned size, for example 500, so the creation info could be this:
```
VkBufferCreateInfo bufferInfo = {};
bufferInfo.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
bufferInfo.size = 500;
bufferInfo.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
bufferInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
vkCreateBuffer(device, &bufferInfo, nullptr, buffer);
```
2. vkGetBufferMemoryRequirements to get the memory requirement size for this buffer, for example it may return 512.
```
VkMemoryRequirements memReq = {};
vkGetBufferMemoryRequirements(device, buffer, &memReq);
```
3. vkAllocateMemory to allocate memory bind to buffer later, but with struct `VkMemoryDedicatedAllocateInfoKHR` to pass buffer object:
```
VkMemoryDedicatedAllocateInfo dedicatedAllocInfo = {VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO};
dedicatedAllocInfo.buffer = buffer;

VkMemoryAllocateInfo allocInfo = { VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO };
allocInfo.memoryTypeIndex = FindMemoryTypeIndex(buffer, memReq);  // the type index is not important here
allocInfo.allocationSize= memReq.size;
allocInfo.pNext= &dedicatedAllocInfo;

VkDeviceMemory memory = VK_NULL_HANDLE;
vkAllocateMemory(device, &allocInfo, nullptr, &memory);
```

Then RenderDoc will get buffer from `VkMemoryDedicatedAllocateInfo` and get size from the buffer, in this case, it will get 500, and compare to memory size which is 512, then print the log message like `Truncating memory size 512 to dedicated buffer size 500 for 1234567`. But in fact, the memory size and buffer size is well handled by VMA.

It is the VMA logic to create buffer in my case, the original post has put on the source code link to reference to.
Hope it will give a help for other developers get this log message when using self built RenderDoc.

**Comment by baldurk** [comment]
Even if log messages are incorrect that is not a bug, and this log message is correct so there is certainly no problem here.

The log is for RenderDoc developers only and it is deliberately not visible to users since the messages are only intended to be interpreted by those familiar with the RenderDoc codebase, it is not relevant to anyone who is using RenderDoc.
