### ISSUE TITLE
Can't connect Quest 2 to RenderDoc

### ISSUE THREAD

**Issue by BaptisteDev09** [baldurk/renderdoc#2843]
## Description
When I try to connect to my Quest2 I get the error : Remote server not running or failed to start.
The command `adb shell pm list packages org.renderdoc.renderdoccmd` returns : 
```
package:org.renderdoc.renderdoccmd.arm32
package:org.renderdoc.renderdoccmd.arm64
```
So it seems that the installation has occured. 
I've set up the android sdk and jdk in the settings panel.
(I can't seem to find the logs either, but that might be because I am new to RenderDoc...)

## Steps to reproduce
- Install RenderDoc (v1.25) on Windows 10
- Connect Quest 2 by USB to pc 
- Select Quest 2 in the replay context drop down

## Environment

* RenderDoc version: 1.25
* Operating System: Windows 10
* Graphics API: OpenGLES3

**Comment by baldurk** [comment]
I wasn't able to reproduce this reliably, but sometimes when the server started it timed out connecting even with a 1.5 second timeout. I had to re-select it, but then everything worked fine.

I've increased the timeout substantially, which should help.

**Comment by BaptisteDev09** [comment]
Ok, for future references, I tried again today and it was not working until I put the Quest 2 on. Then everything worked out. I do not know why but hopefully this could help someone that have the same issue.
Thank you for your time @baldurk ,
Cheers.
