### ISSUE TITLE
support windows10 Qt libEGLd.dll 

### ISSUE THREAD

**Issue by car520120** [baldurk/renderdoc#2847]
## Description

build app for release is renderdoc is HOOK  GLES
build app for debug is renderdoc is  HOOK D3D11
It may be that qt will use libegld.dll in debug mode, resulting in failure to capture gles
what i want is gles
RENDERDOC_HOOK_EGL_ALIAS = "libEGLd.dll"

## Environment

* RenderDoc version: 1.21
* Operating System: windows10
* Graphics API: EGL_API D3D11

**Comment by baldurk** [comment]
I'm sorry I don't understand what you are asking. Can you please try to explain in more detail or with an example what feature you are requesting?

**Comment by car520120** [comment]
![image](https://user-images.githubusercontent.com/36702004/218399457-660ae6a7-c2ad-4f27-a723-d64c28216d12.png)
qt debug is use libEGLd.dll

**Comment by baldurk** [comment]
Qt is wrong here, libEGL is the standard filename and should not be changed.
