### ISSUE TITLE
[Feature Request] Buffer Device Address support in shader debugging

### ISSUE THREAD

**Issue by Cazadorro** [baldurk/renderdoc#2848]
## Description

Would like buffer device address support in Render doc, currently doesn't support it, get "This shader doesn't support debugging: Unsupported capability 'PhysicalStorageBufferAddresses'"

## Environment

* RenderDoc version: [XXX](https://github.com/baldurk/renderdoc/commit/d47e79ae079783935b8857d6a1730440eafb0b38) 1.25
* Operating System: Windows (still a problem on linux)
* Graphics API: Vulkan

**Comment by Zorro666** [comment]
PR #3217

**Comment by OptimisticMonkey** [comment]
Thank you for adding! - just ran into this and was looking
