### ISSUE TITLE
modifications to LD_LIBRARY_PATH break linking for some Linux programs

### ISSUE THREAD

**Issue by ExpandingMan** [baldurk/renderdoc#2849]
## Description

It seems that modifications to `LD_LIBRARY_PATH` are breaking the ability of some programs to find their libraries.  In my case, I am trying to run [Julia](https://julialang.org/downloads/).  This is a programming language with a run-time that links to a whole bunch of shared libraries.

## Steps to reproduce

1. Install the [Julia x86 linux binaries](https://julialang.org/downloads/) to `/opt/julia`.
2. Create the following script
```
#!/bin/bash
/opt/julia/bin/julia "$@" &> badthings.log
```
3. Run this script through the renderdoc GUI (no environment variables or command line arguments).
4. The following error occurs in `badthings.log`
```
WARNING: Error during initialization of module LinearAlgebra:
ErrorException("could not load library "libblastrampoline"
libblastrampoline.so: cannot open shared object file: No such file or directory")
fatal: error thrown and no exception handler available.
InitError(mod=:LinearAlgebra, error=ErrorException("could not load library "libblastrampoline"
libblastrampoline.so: cannot open shared object file: No such file or directory"))
ijl_errorf at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/rtutils.c:77
ijl_load_dynamic_library at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/dlload.c:277
jl_get_library_ at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/runtime_ccall.cpp:48 [inlined]
jl_get_library_ at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/runtime_ccall.cpp:30
ijl_load_and_lookup at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/runtime_ccall.cpp:61
jlplt_lbt_set_num_threads_60108.clone_1 at /opt/julia/lib/julia/sys.so (unknown line)
lbt_set_num_threads at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/LinearAlgebra/src/lbt.jl:184 [inlined]
set_num_threads at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/LinearAlgebra/src/blas.jl:125 [inlined]
__init__ at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/LinearAlgebra/src/LinearAlgebra.jl:592
jfptr___init___60093.clone_1 at /opt/julia/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/gf.c:2377 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/gf.c:2559
jl_apply at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/julia.h:1843 [inlined]
jl_module_run_initializer at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/toplevel.c:75
_finish_julia_init at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/init.c:765
julia_init at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/init.c:698
jl_repl_entrypoint at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/jlapi.c:713
main at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/cli/loader_exe.c:59
unknown function (ip: 0x7f2d6e43c28f)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 0x401098)
```

## Environment

- RenderDoc version: 1.25
- Operating system: Manjaro Linux (`6.1.9-1-MANJARO`, x86_64)
- Graphics API: any

## Additional Details
I of course realize that this issue will look extremely esoteric because of its reliance on a very specific binary (Julia).  I expect this can cause similar problems with other linux programs, but Julia's very specific linking process means I can't create an e.g. C or Python MWE (at least I don't know how).

@giordano helped me to confirm that this is likely a linking issue.  I'm grateful for his assistance and hope he won't mind me referencing him in this issue as the renderdoc devs may have questions that he can answer far better than me (:slightly_smiling_face: ).

**Comment by baldurk** [comment]
This is not related to LD_LIBRARY_PATH modifications at all. This program julia looks to use an obscure feature of libc where dlopen considers the rpath from the module containing the calling function in the paths of libraries searched.

I honestly don't think there is any feasible way for RenderDoc to support this. It must intercept dlopen, but at that point the caller is only visible to renderdoc's library. There's no alternate or non-standard version of dlopen that allows manually passing an address - which I can get on Android to solve a similar problem there. Any program that hooks dlopen will break this, I can see the same behaviour when running via apitrace.

As a workaround I'd suggest specifying the necessary directory for your libraries via manual LD_LIBRARY_PATH when running - if I set LD_LIBRARY_PATH to `/opt/julia/lib/julia` in the RenderDoc UI then the script runs correctly. Alternatively you might want to consider not relying on this feature, I don't know how portable it is within linux but certainly on platforms like windows the library search path is process-wide so if you ever want to have you program work on windows you'd need a different approach.

**Comment by ExpandingMan** [comment]
Thanks for looking into this.  It looks like I'll have to create a script to extract every directory Julia wants to link libraries from (Julia itself is just `/opt/julia/lib/julia` but dependencies use others) and generate a script that adds them before it starts.  If I do this I'll put up a repo so that other users of the language can use the same workaround.

**Comment by baldurk** [comment]
This will only affect the specific scenario of dynamic loading (not linking) where the library specified is a relative path and relies on the module's rpath to locate it. Anything which is actually linked will work as normal since RenderDoc doesn't affect that process, and anything which uses the normal standard search path logic or specifies absolute paths will also work as normal.

**Comment by ExpandingMan** [comment]
Yeah, sorry, I tend to use the term "linking" incorrectly.  Regardless, I think there's a workaround here.  Anyway, thanks again.
