### ISSUE TITLE
[Feature Request] D3D12 view instancing support

### ISSUE THREAD

**Issue by chromedays** [baldurk/renderdoc#2851]
## Description

D3D12's view instancing (https://microsoft.github.io/DirectX-Specs/d3d/ViewInstancing.html) doesn't seem to be supported in renderdoc. When you capture a draw call that uses pso with the view instancing feature enabled, the view switch in the mesh viewer is disabled, maybe it's only for vulkan's multiview feature? 
~~Also the mesh and the highlighted vertices in VS Out window aren't aligned well. It would be nice if we can see instanced views in the renderdoc.~~ I just found this bug isn't related to view instancing.
![image](https://user-images.githubusercontent.com/6375892/217921604-f5e4cee3-80e9-4d63-9617-65c6d329b9fb.png)
![image](https://user-images.githubusercontent.com/6375892/217922803-ec1fc62b-4daa-4b41-b95d-5790c9ff378e.png)

## Environment

* RenderDoc version: v1.22
* Operating System: Windows 10
* Graphics API: DirectX 12

**Comment by baldurk** [comment]
I have a feeling that this can't ever be supported. On vulkan multiview is explicitly banned together with stream-out, so the output under multiview is only possible via vertex shader patching (and not available for geometry/tessellation output which still depends on stream-out). D3D12's spec isn't very rigorous as usual and doesn't mention anything either way, which if it were allowed it would at minimum need to specify the output order, but at least on nvidia the driver crashes trying to create such a PSO. It's been crashing for ~2 years since this was first reported and I forcibly disabled view instancing so I think this is probably illegal.

I'm trying to double check to see if this is intended to work or not, but my expectation is that it isn't and so can't be supported on D3D12.

**Comment by chromedays** [comment]
It is true that the spec is not well documented and some parts could be outdated. The only fully written spec that I could ever find was https://microsoft.github.io/DirectX-Specs/d3d/ViewInstancing.html, which says the last update is 2017 :(
It's not much related to this feature request but, speaking of the vulkan multiview, it looks at least some GPUs support multiview with geometry/tessellation shaders?
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceMultiviewFeatures.html
![image](https://user-images.githubusercontent.com/6375892/218447236-ca2b70b2-d589-4098-8f20-ead3bed5c566.png)

Thank you for looking into it anyways. I'll open a new ticket for the bug that the highlighted vertices not being aligned with the mesh in VS Output window since it happens regardless of the view instancing.

**Comment by chromedays** [comment]
Thank you for looking into it anyways. I'll open a new ticket for the bug that the highlighted vertices not being aligned with the mesh in VS Output window since it happens regardless of the view instancing.

**Comment by baldurk** [comment]
Yes but it's multiple levels of interaction:

- Vertex outputs can be fetched (effectively) always with no feature requirements. Geometry and tessellation outputs require the us of stream-out.
- Multiview is supported regardless of what vertex stages are used.
- Multiview is not allowed to be used with stream-out at all.

So on vulkan you can use multiview with geometry/tessellation fine, and it will replay and display, but you will only get mesh output data from the vertex stage (which has no feature requirements as it's done with shader patching) and will only see an error on the geometry/tessellation output.

**Comment by baldurk** [comment]
I talked to some folks at MS, they weren't sure whether view instancing and stream out was supposed to work together but suspected it probably was, however they thought the output was most likely implementation defined so not possible to rely on making it of limited use. Unfortunately that means supporting this is not possible on D3D12.

**Comment by chromedays** [comment]
That's unfortunate. Thank you for clarifying it.
