### ISSUE TITLE
"Don't blink at me" for just "Info"/"Miscellaneous"

### ISSUE THREAD

**Issue by AntonioNoack** [baldurk/renderdoc#2854]
## Description

*This feature request is purely aesthetic.* (and low priority)

On my RTX 3070 in OpenGL, there are messages that are marked as Info/Miscellaneous. RenderDoc blinks with a stop symbol in the bottom bar until you click on them. Since they are just debug data, I'd recommend to not blink, and use a calmer symbol, maybe a green I like [here](https://pixabay.com/vectors/info-information-green-sign-symbol-31185/).
Also the name "issues" in the message at the bottom of RenderDoc is a bit harsh for just debug information.

The currently used symbol:
![image](https://user-images.githubusercontent.com/20659579/218258628-3c2e9a69-4667-4670-b456-c3c4a8dad954.png)

The warnings (a sample):
![image](https://user-images.githubusercontent.com/20659579/218258610-305f08aa-5769-485c-a5ef-af65384c1512.png)

## Environment

* RenderDoc version: 1.24
* Operating System: Windows 10
* Graphics API: OpenGL

**Comment by baldurk** [comment]
I will double check but I'm not sure there's enough consistency across how drivers and APIs report these messages that 'info' severity can be treated any differently to any other validation message.

If you don't want to see these messages, then not enabling API validation during capture or replay should mean they won't appear regardless of severity. When you do enable validation you'll get whatever the API validator reports - I know these messages are mostly garbage and shouldn't be enabled by default with validation but that's GL unfortunately.

**Comment by baldurk** [comment]
Thinking about this more, no I don't want to make any change here. These messages come categorised/filtered from an external source so I don't want to editorialise, and the downsides of notifying users for something that's not an issue don't outweigh the downsides of potentially hiding things which are an issue. Especially since this is something the user opted in for in the first place.

**Comment by AntonioNoack** [comment]
How about a configuration option? Maybe a list of Source/Severity/Category strings, which will not blink?

**Comment by baldurk** [comment]
I think such a configuration option would be needlessly complicated and extremely narrow in use. There is already an overall option - do not enable API validation and you will not get any messages. If you do enable API validation then you'll see all messages unfiltered and treated the same as they come from an external source.
