### ISSUE TITLE
HLSL "Step forwards Over(F10)" still broken only with the first line of hlsl with v1.25

### ISSUE THREAD

**Issue by Clapeysron** [baldurk/renderdoc#2855]
## Description
As #2786 mentioned, the specific performance is that when using "Step forwards Over(F10)" button, hlsl will not jump to the next line but jump into the function. This still exists only with the first line of hlsl on v1.25. Renderdoc v1.21 works fine.

## Steps to reproduce
Use unity 2021.3.4f1 with HDRP sample project and load renderdoc
Add #pragma enable_d3d11_debug_symbols to shader
Debug into the pixel and press "Step forwards Over(F10)" with the first line of hlsl

## Environment
* RenderDoc version: v1.25
* Operating System: Windows 10
* Graphics API: DX11

**Comment by baldurk** [comment]
If this is reproducible with a sample project can you please share a capture that demonstrates the problem? That way I can be sure I'm debugging your actual bug. I am not at all familiar with unity and I don't know what HDRP is.

**Comment by Clapeysron** [comment]
Sure, I have already sent you an email with the .rdc under that issue.

**Comment by baldurk** [comment]
That should fix the issue, the first instruction step wasn't fetching a callstack so stepping over didn't have a reference point to know what the current function was.
