### ISSUE TITLE
Launch Renderdoc causing system level error (intel graphic driver error)

### ISSUE THREAD

**Issue by StellarWarp** [baldurk/renderdoc#2856]
## Description

After an update about 7 mouth ago, every time after I open the renderdoc on my laptop the ScreenClipping don't work any more， more seriously File Explorer start the endless restart after a while. Latter found that renderdoc casued intel graphic driver error (igd10iumd64.dll), only solution is to disable the GPU0 （Iris(R) Xe Graphics）and then enable it again

```
<EventData>
  <Data Name="AppName">ScreenClippingHost.exe</Data> 
  <Data Name="AppVersion">622.32703.0.0</Data> 
  <Data Name="AppTimeStamp">637de5ad</Data> 
  <Data Name="ModuleName">igd10iumd64.dll</Data> 
  <Data Name="ModuleVersion">30.0.101.1003</Data> 
  <Data Name="ModuleTimeStamp">616858bb</Data> 
  <Data Name="ExceptionCode">c0000005</Data> 
  <Data Name="FaultingOffset">000000000001c20f</Data> 
  <Data Name="ProcessId">0x67c0</Data> 
  <Data Name="ProcessCreationTime">0x1d940400f251b5d</Data> 
  <Data Name="AppPath">C:\WINDOWS\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\ScreenClippingHost.exe</Data> 
  <Data Name="ModulePath">C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_556bf05bd4afaaf1\igd10iumd64.dll</Data> 
  <Data Name="IntegratorReportId">3d1029d8-0d8e-40e2-abe5-49fb7bcf23ea</Data> 
  <Data Name="PackageFullName">MicrosoftWindows.Client.CBS_1000.22638.1000.0_x64__cw5n1h2txyewy</Data> 
  <Data Name="PackageRelativeAppId">ScreenClipping</Data> 
  </EventData>
</Event>
```

## Steps to reproduce

1. On 11th Gen Intel(R) Core(TM) i5-11300H
2. Launch Renderdoc or load Renderdoc from Unity,
3. ScreenClipping crash when launch
4. Look for log in Event Viewer 

## Environment

* RenderDoc version: v1.25
* Operating System: Windows11
* Graphics API: DirectX11/12
* CPU: 11th Gen Intel(R) Core(TM) i5-11300H
* GPU0: Intel(R) Iris(R) Xe Graphics
* GPU Driver Version: 30.0.101.1003

**Comment by baldurk** [comment]
By definition this is a problem with the Intel driver since it is responsible for ensuring that problems in one process don't affect any other processes - especially system level ones. If only launching RenderDoc and doing nothing else causes the bug it's very unlikely that there's any bug in RenderDoc or this would be seen more widely. You would need to get in touch with Intel to investigate this any further.
