### ISSUE TITLE
Failed to open "capture.rdc" for replay. Network I/O operation failed.

### ISSUE THREAD

**Issue by josefalanga** [baldurk/renderdoc#2857]
## Description

I'm having the following error while trying to open a capture made on an Adroid device:

![renderdoc](https://user-images.githubusercontent.com/5981265/219137844-0a8ea038-2956-43e5-9dd2-619ad0ea9cbd.png)

It's the same if the capture is opened from the device, or saved locally and then opened.

It doesn't happen in other devices I own, only on this one (that happens to be needed to reproduce an issue with that GPU).

## Steps to reproduce

Looks like it happens with the common workflow of capturing and opening the capture afterwards.

[capture sample](https://github.com/baldurk/renderdoc/files/10746950/capture.zip)

## Environment

* RenderDoc version: 1.25
* Operating System: Windows 10, Ubuntu 22.04
* Graphics API: Vulkan
* The problematic device is: Android 10 armeabi-v7a, Samsung SM-M105M, GPU Mali-T830 MP1, Vulkan. I Tried with another device and works well.

**Comment by baldurk** [comment]
This capture contains invalid use of Vulkan. There is a renderpass being created with one color attachment where the `VkAttachmentReference` contains a value of `attachment = 3806161832` which is not a valid value. This causes an invalid index and then a crash while loading which leads to the disconnect.

I would recommend running your program with the validation layers (I'm not sure how/if that's possible on android but I assume so) to catch errors like this, as RenderDoc does not handle invalid API use.
