### ISSUE TITLE
Shader-exported depth not reflected in depth test overlay

### ISSUE THREAD

**Issue by LordOfDragons** [baldurk/renderdoc#2858]
## Description
Rendering captured during OcclusionQuery shows in the Texture view with DepthTest enabled all geometry always red (aka failing depth test) although it is clearly in front of other geometry. This happens always. Outside of OcclusionQuery the DepthTest shows green/red correctly but always read while an OcclusionQuery is running

## Steps to reproduce

- Use a program using OcclusionQuery.
- Capture the scene.
- Go to a geometry render which is in front of the used depth map with OcclusionQuery is running.
- Switch to Texture view.
- Switch to Depth Test mode.

The geometry is rendered all in red but the parts in front of the depth map should be green. Since the occlusion query does succeed it is RenderDoc showing the wrong result.

Capture can not be shared. But any OcclusionQuery should trigger the bug.

In my test "depth test" is enabled with function LEQUAL and depth writes are disabled.  Depth write is disabled. OpenGL 4.6 context. Bug happens on both ATI and nVidia systems on 2 different Linux systems (GenToo, Kubuntu). Using RenderDoc 1.24 .

**Comment by LordOfDragons** [comment]
![renderdoc_occquery_bug](https://user-images.githubusercontent.com/310073/219901477-1693c12c-81d9-43e7-8b37-5c8e52a5f3d4.png)
Made a screenshot. Both are the same captured geometry render but once with wireframe and once with depth test to show how the geometry (a light volume running along the hallway) is marked red if occlusion query is enabled.

**Comment by baldurk** [comment]
I'm not able to reproduce this. I added an occlusion query around some geometry that should pass and fail the depth test in different places and the results were the same.

If you don't want to share your capture here, you can email it to me privately at baldurk@baldurk.org. If that's also not possible could you modify a sample program to reproduce the problem in the way you describe, if you say it works with any use of occlusion queries at all?

**Comment by LordOfDragons** [comment]
I can reproduce it with the smaller example application but the exported capture is nearly 200MB files large.

**Comment by baldurk** [comment]
That's fine, I'm used to captures that are multiple GBs in size

**Comment by LordOfDragons** [comment]
I can 7zip it down to a bit more than 100MB but that's still to large. Doesn't fit through mail.

**Comment by baldurk** [comment]
You can use any file sharing site of your choosing to share files that are more than a couple of MB and don't fit as an email attachment. Google drive, dropbox, onedrive, whatever else.

**Comment by LordOfDragons** [comment]
I've created another capture this time from a different angle. I have the impression I see where RenderDoc might have a bug in displaying the DepthTest information. I can get green color for pixels over cleared background but nowhere else. I have the suspicion RenderDoc uses the position after vertex shader for depth display not after fragment shader (which write gl_FragDepth). I've bookmarked one of the tests with all red: https://drive.google.com/file/d/1d8bHArDOV780MAd6itz2yVloyF2zn3Ke/view?usp=sharing

**Comment by baldurk** [comment]
That would make sense, the overlay is implemented with shader replacement so any shader-modified depth values won't apply. It doesn't have anything to do with occlusion queries then?

I'll need to think if it's possible to solve this without shader patching (which is only really possible on Vulkan).

**Comment by LordOfDragons** [comment]
In that case, yes, it is not related to occlusion query but writing depth in the fragment shader. So it is a "limitation" not a "bug". Might help to note it somewhere in the docs or in the view itself that fragment depth writes are ignored.

**Comment by Zorro666** [comment]
This is now implemented. 
Sorry it took longer than expected, it required a refactor on all APIs to be able support the feature.

Thank you for the original report and reproduction capture that included an important scenario of shader exported depth with no colour output just depth output.
