### ISSUE TITLE
renderdoc deadlocks

### ISSUE THREAD

**Issue by zmike** [baldurk/renderdoc#2868]
## Description

When trying to capture a frame from a trace using zink, renderdoc hits an infinite loop during queue submission. Other traces seem to work fine, but this one doesn't.

## Steps to reproduce
* Grab https://gitlab.freedesktop.org/gfx-ci/tracie/traces-db/-/blob/master/valve/portal-2-v2.trace
* Build+install zink from mesa main
* set up environment (`export LIBGL_DRIVERS_PATH=/usr/local/lib64/dri ; export LD_LIBRARY_PATH=/usr/local/lib64` or whatever your library prefix is for mesa builds)
* also disable all GL support in renderdoc
* `MESA_LOADER_DRIVER_OVERRIDE=zink glretrace -b --loop ~/src/traces-db/valve/portal-2-v2.trace`

## Environment

Running renderdoc from git 52e9404961277d1bb1ed03a376b722c2b91e3762

**Comment by baldurk** [comment]
Fixed in that commit, from direct discussions it wasn't deadlocking but it was going very slow when capturing with a lot of memory mapped. Updated a codepath that did GPU readbacks instead of CPU-reads to also apply on integrated GPUs when necessary.
