### ISSUE TITLE
I cant get a capture it says OpenGLES not presenting

### ISSUE THREAD

**Issue by vadik317** [baldurk/renderdoc#2869]
## Description
im trying to injest as launching the app doesnt even detect openGL, but ehre it fails to present, it sould say active and i dont get the interface when i inject and start chrome, insted it starts downlaoding cmd.exe and tries toreach some webpage

## Steps to reproduce

I dont know how someone can reproduce the bug, i this my opengl is just not working

## Environment

* RenderDoc version: v1.17
* Operating System: windows 10
* Graphics API: OpenGLSE (not presenting)

![image](https://user-images.githubusercontent.com/111152105/221985643-8a1e9bbd-2aa2-4ab3-b7fc-b731806d1bf8.png)
![image](https://user-images.githubusercontent.com/111152105/221985897-e6e3841b-1b35-43e6-9a85-2bc03c4d3427.png)
my opengl version is 4.6, 4.6.0 NVIDIA 528.24

**Comment by baldurk** [comment]
Due to the very high rate of abuse I do not provide any support for capturing from chrome.

**Comment by vadik317** [comment]
Is there any other way to capute google maps data?
