### ISSUE TITLE
Compute shader debugger ld_raw instruction returns 0 for byteOffset >= size/4

### ISSUE THREAD

**Issue by calvindhsu** [baldurk/renderdoc#287]
Tested with v0.29 and 6/22 Nightly.

When debugging a compute shader, the ld_raw instruction appears to return 0 values for byte address offsets that are greater than the size of the buffer / 4.

I.e. in the attached capture, event 507 (3rd Dispatch call) on disassembly line 7, debugging with thread id.x = (0-5) returns values as expected as they pass in byteoffsets to ld_raw of (0 - 60) respectively.

However, for threadid.x >= 6, which use byteoffsets >= 72, start to return 0.

It turns out the length of the buffer is 288, which curiously is 4 * 72. 
I am speculating that the length check is incorrectly dividing by 4.

[LoadRawBuffer.zip](https://github.com/baldurk/renderdoc/files/328729/LoadRawBuffer.zip)

**Comment by baldurk** [comment]
Thank you for the very clear bug report and repro case! This was just a bit of missing code to handle byte addressing as opposed to element indexing, it should work now.

**Comment by calvindhsu** [comment]
Fixed verified in 6/24 Nightly, thanks!
