### ISSUE TITLE
Frame timing seems to be calculated incorrect

### ISSUE THREAD

**Issue by jcortell68** [baldurk/renderdoc#2870]
## Description
The event timing feature in the Event Browser seems to not be working correctly when it comes to calculating the overall frame time. See the attached screenshot. It reports a zero time for the entire frame, despite it also reporting the frame has a renderpass that takes 124us.

The screenshot includes some logging I've added to EventItemModel::CalculateTotalDuration(), which is what is ultimately producing the numbers in that tree column. I think it might prove helpful in showing what's going wrong. Specificaly, I wonder if the root action node shouldn't have ActionDescriptions for 6,14,15,16, instead of 6,17,15,16

## Steps to reproduce
I cannot share the rdc file, but I will describe how I created it, using our Android platform.

1. installed the GAPID apk that comes with AGI (spinning cube app)
2. capture a frame
3. press the Timing button in the Event Browser

## Environment

* RenderDoc version: 1.24
* Operating System: host=linux, target=Android-arm64
* Graphics API: Vulkan

![ss](https://user-images.githubusercontent.com/109228283/222008796-004ba389-c8f9-4ed0-a55b-0964e8d3e3d0.png)

**Comment by baldurk** [comment]
This only applied in the case of fake markers, because their EIDs are out of order so it wasn't properly recalculating the root after them. That commit should fix it.

**Comment by jcortell68** [comment]
Thanks. Confirmed fixed in the scenario described in the issue (GAPID), and in a separate internal one which first surfaced the problem.
