### ISSUE TITLE
Win11-OpenGLES (Active) at startup, then...

### ISSUE THREAD

**Issue by Ivan367al** [baldurk/renderdoc#2874]
## Description

After successful installation, it run without issues. OpenGLES marked as Active.
After running Google Earth Pro, I try to start a capture... after a little while, OpenGLES turns to (Not Presenting)
and nothing happens anymore.
The program keep running, but not working...

## Environment

* RenderDoc version: 1.25
* Operating System: Win 11 Home
* Graphics API: 
* Nvidia RTX 3080 ti mobile
Those are the settings to launch EarthPro
![RenderDoc v1 25 04_03_2023 15_36_21](https://user-images.githubusercontent.com/46423819/222915043-119d19cc-8418-4086-bc8a-2e4928a8b80b.png)

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.
