### ISSUE TITLE
 Allow stepping through the timeline, using the arrow keys

### ISSUE THREAD

**Issue by AbdullahAmrSobh** [baldurk/renderdoc#2876]
## Description

I think it would make a better use experience, if we can move back, and forth between events in the timeline, using the arrow keys,

## Environment

* RenderDoc version: v1.25
* Operating System: Win 10

**Comment by baldurk** [comment]
I don't think this is a good way to go. The Timeline Bar is not primarily meant for navigation and is not tailored for fine-grained event to event navigation. To have some keyboard shortcuts you would need some sense of a 'current event' cursor which doesn't exist, and handle how to move across marker regions and scrolling out of the visible region etc.

I would recommend you use the Event Browser. It is entirely oriented around navigating the frame, has all of those problems solved, and does have keyboard shortcuts for moving through either between actions or on an event-by-event basis.
