### ISSUE TITLE
Vulkan: Shading rate image view not tracked properly

### ISSUE THREAD

**Issue by doitsujin** [baldurk/renderdoc#2877]
## Description
When using a shading rate attachment with dynamic rendering, and the view is not otherwise used in a frame, it does not get tracked, shows up as an "Unknown resource" in the capture, and the shading rate is not applied on replay as a result.

On the Vulkan side of things, this looks as follows:
```c++
  VkRenderingFragmentShadingRateAttachmentInfoKHR shadingRate = { VK_STRUCTURE_TYPE_RENDERING_FRAGMENT_SHADING_RATE_ATTACHMENT_INFO_KHR };

  if (renderingInfo.shadingRate.view) {
    auto& view = static_cast<const GfxVulkanImageView&>(*renderingInfo.shadingRate.view);
    shadingRate.imageView = view.getHandle();
    shadingRate.imageLayout = view.getLayout();
    shadingRate.shadingRateAttachmentTexelSize = getVkExtent2D(m_device->getShadingRateTileSize());
  }

  VkRenderingInfo info = { VK_STRUCTURE_TYPE_RENDERING_INFO };
  if (shadingRate.imageView)
    shadingRate.pNext = std::exchange(info.pNext, &shadingRate);
  ...
```

For testing purposes I did the following change to RenderDoc code, which indeed made the view appear in the capture, but it also causes qrenderdoc to crash when selecting any of the related commands so it's clearly not the full solution to the problem.

```c++
@@ -7195,6 +7195,15 @@ void WrappedVulkan::vkCmdBeginRendering(VkCommandBuffer commandBuffer,
       if(att->resolveMode)
         record->MarkImageViewFrameReferenced(GetRecord(att->resolveImageView), ImageRange(), refType);
     }
+
+    VkRenderingFragmentShadingRateAttachmentInfoKHR *shadingRateAttachment =
+        (VkRenderingFragmentShadingRateAttachmentInfoKHR *)FindNextStruct(
+            pRenderingInfo, VK_STRUCTURE_TYPE_RENDERING_FRAGMENT_SHADING_RATE_ATTACHMENT_INFO_KHR);
+
+    if(shadingRateAttachment)
+      record->MarkImageViewFrameReferenced(GetRecord(shadingRateAttachment->imageView), ImageRange(), eFrameRef_Read);
   }
 }
```

## Steps to reproduce

Here's a small demo app which runs into this problem: [renderdoc-vrs.tar.gz](https://github.com/baldurk/renderdoc/files/10892498/renderdoc-vrs.tar.gz)
(cube demo from https://github.com/doitsujin/alseid/tree/vrs (`vrs` branch))

Run via
```sh
cd renderdoc-vrs
./02-cube
```

This was built on a reasonably up-to-date Arch Linux, I hope this works on other systems. I'm sorry I don't have a more trivial repro available right now, but it seems like the official Vulkan samples have nothing for the KHR extension yet.

## Environment

* RenderDoc version: ac302d7a48276dc05a64e0cbd4754b64f9464442
* Operating System: Arch Linux
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Thanks for the repro, it took a bit of fiddling but I was able to get it running on windows and tracked down the problem quite quickly. Your fix was almost complete - it was just missing an extra unwrap later when replaying that dynamic rendering.
