### ISSUE TITLE
Compute shader debugger ByteAddressBuffer load2, load3, load4 return the "x" component for all components

### ISSUE THREAD

**Issue by calvindhsu** [baldurk/renderdoc#288]
Tested on v0.29

When debugging compute shaders in DX11, the Load2, Load3, Load4 instructions always return the "x" component as all components.

I.e. if my buffer contains  (1, 2, 3, 4), then buffer.Load4(0) returns (1, 1, 1, 1).
However, the output buffer shows the correct values for a simple Load4, Store4 shader.

Using individual Load instructions is the work around.

**Comment by baldurk** [comment]
Again a very clear report, thank you :). This was similar to the other - byte addressing buffers can load from any component even if the view is technically only a 1 component format (R32_TYPELESS).

**Comment by calvindhsu** [comment]
Fixed verified in 6/24 Nightly, thanks!
