### ISSUE TITLE
Textures appear black/garbage in Android replay

### ISSUE THREAD

**Issue by snagy** [baldurk/renderdoc#2885]
## Description

Textures aren't recording/replaying (not 100% which) properly on Android GLES captures.  Most textures are black, and some are garbage.  This does not apply to rendertargets - those show up fine during replay, usually showing silhouettes of the geometry which would have a texture applied but instead just has black applied to it.

I took captures both with the Meta fork of RD as well as a stock version I compiled from this repo - on both captures, I've captured content from the Quest Browser and replayed them, only to see all my captured texture data is either black or garbage.

## Steps to reproduce

Here's a capture with a single texture that shows up as garbage for me:

[xr_sample.rdc.zip](https://github.com/baldurk/renderdoc/files/10997232/xr_sample.rdc.zip)

This capture was taken from a build I made off this repo yesterday, on MacOS.  I've previously had good results using MacOS builds.

This capture was taken as follows:
* attach to my Quest 2
* Launch com.oculus.browser from renderdoc
* navigate to https://immersive-web.github.io/webxr-samples/reduced-bind-rendering.html
* capture a frame
* exit browser
* replay the frame on the quest 2
* the texture looks grey and garbage, both in texture viewer and when rendered in replay

I have other captures taken using the Meta fork but this is taken with mainline and is pretty simple.

## Environment

* RenderDoc version: 1.26 built from 38afb7c8adfd63c78c64cbfa3d003df9e5a5000d
* Operating System: MacOS Ventura 13.2.1
* Graphics API: GLES

**Comment by baldurk** [comment]
Mac is not a supported platform.
