### ISSUE TITLE
Textures appear garbage/black in Android GLES capture replay

### ISSUE THREAD

**Issue by snagy** [baldurk/renderdoc#2888]
## Description

Textures aren't recording/replaying (not 100% which) properly on Android GLES captures. Most textures are black, and some are garbage. This does not apply to rendertargets - those show up fine during replay, usually showing silhouettes of the geometry which would have a texture applied but instead just has black applied to it.

I took captures both with the Meta fork of RD as well as stock v1.25 - on both captures, I've captured content from the Quest Browser and replayed them, only to see all my captured texture data is either black or garbage.

## Steps to reproduce

Here's a capture with a single texture that shows up as garbage for me:

[rd_125_badtex.rdc.zip](https://github.com/baldurk/renderdoc/files/11021383/rd_125_badtex.rdc.zip)

This capture was taken as follows:

* attach to my Quest 2
* Launch com.oculus.browser from renderdoc
* navigate to https://immersive-web.github.io/webxr-samples/reduced-bind-rendering.html
* capture a frame
* exit browser
* replay the frame on the quest 2 (preview screenshot looks good)
* the texture looks grey and garbage, both in texture viewer and when rendered in replay

I have other captures taken using the Meta fork but this is taken with standard RD.

## Environment

* RenderDoc version: 1.25
* Operating System: Windows 10
* Graphics API: GLES

**Comment by baldurk** [comment]
I can't investigate this at the moment as my quest 2 is out of action, I'm talking to oculus to try and get it working again which I'm hoping won't take long.

**Comment by baldurk** [comment]
It looks like the browser was creating a context that made it unshareable without special properties. That commit should fix it to drop the properties (which should be fine) and allow sharing again, for capturing resource contents properly.
