### ISSUE TITLE
Capturing Option in GUI disabled

### ISSUE THREAD

**Issue by immineal** [baldurk/renderdoc#2889]
## Description

When injecting/attaching RenderDoc to a process, the capturing buttons in the GUI are disabled

## Steps to reproduce

On my system, opening RenderDoc and launching Chrome with these settings ([Capture_Settings.zip](https://github.com/baldurk/renderdoc/files/11043345/Capture_Settings.zip); only as zip because GitHub doesn't support .cap)
and attaching to the process reproduces the problem (on my system; as described below)

![Screenshot_20230322_190502](https://user-images.githubusercontent.com/78079641/226997295-bbc90292-cbe3-4b5b-a04e-1ca74dfacfa0.png)

* RenderDoc version: v1.24
* Operating System: Linux-6.1.13-2-preempt-x86_64-with-glibc2.37 64 Bits
* Graphics API: Mesa Intel(R) UHD Graphics (TGL GT1) Intel 4.6 (Core Profile) Mesa 22.3.5

Thank you for providing this amazing program, and thanks in advance!

**Comment by baldurk** [comment]
Due to the very high rate of abuse I do not provide any support for capturing from chrome.

**Comment by xylactic** [comment]
> Due to the very high rate of abuse I do not provide any support for capturing from chrome.

Why? Chrome is a browser. Capturing Chrome doesn't automatically mean the person is committing copyright infringement. Importantly, many of us, myself included, are in fact debugging our own web-based graphics applications, and you're refusing to support a major usecase for your software? And in fact, limiting conversation on issues related to Chrome? That seems to go against the ethos of open source. 

You explicitly state, "Note: Capturing projects you created that use a third party engine like Unreal or Unity, or open source and free projects is completely fine and supported." Chrome is similar to Unreal or Unity: it is an engine, capable of many things, including graphics. If I wish to use your software to capture a project I created, or a FOSS project, that happens to be web-based, you refuse support no matter what. I don't understand.

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
