### ISSUE TITLE
Capturing the first frame results in invalid framebuffer with OpenGL 3.3 Core

### ISSUE THREAD

**Issue by ceeac** [baldurk/renderdoc#2890]
## Description

Capturing frame 0 of a program running with SDL2+OpenGL 3.3 causes the default framebuffer to have a width and height of 0 in RenderDoc. In the texture viewer this shows up as a 1x1 texture. I expected the framebuffer to have a size of 1920x1080.

## Steps to reproduce

- Download header-only GLAD gl loader: http://glad.sh/#api=gl%3Acore%3D3.3&extensions=&generator=c&options=HEADER_ONLY%2CMX
- Install SDL2
- Compile the following C program: 
```C

#define GLAD_GL_IMPLEMENTATION
#include "glad/gl.h"

#include "SDL.h"


int main()
{
    if (SDL_InitSubSystem(SDL_INIT_VIDEO) < 0) {
        return 1;
    }

    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);

    SDL_Window *window = SDL_CreateWindow("Test", 0, 0, 1920, 1080, SDL_WINDOW_OPENGL);
    if (window == NULL) {
        return 1;
    }

    SDL_GLContext sdlglContext = SDL_GL_CreateContext(window);
    SDL_GL_MakeCurrent(window, sdlglContext);

    GladGLContext gl;

    if (gladLoadGLContext(&gl, (GLADloadfunc)SDL_GL_GetProcAddress) == 0) {
        return 1;
    }

/* first frame */
    gl.ClearColor(0.1f, 0.25f, 0.5f, 1.f);
    gl.Clear(GL_COLOR_BUFFER_BIT);

    SDL_GL_SwapWindow(window);

    SDL_Delay(1000);

/* second frame */
    gl.ClearColor(1.f, 1.f, 1.f, 1.f);
    gl.Clear(GL_COLOR_BUFFER_BIT);

    SDL_GL_SwapWindow(window);

    SDL_Delay(1000);

    SDL_GL_DeleteContext(sdlglContext);
    SDL_DestroyWindow(window);

    SDL_QuitSubSystem(SDL_INIT_VIDEO);
}
```
 - Capture frame 0 and frame 1 in RenderDoc

## Environment

* RenderDoc version: Tested with c353f6f and v1.25
* Operating System: Ubuntu 22.04
* Graphics API: OpenGL 3.3 Core
* Nvidia GeForce GTX 1080
* Driver version 470.161.03

**Comment by baldurk** [comment]
This was an order of operations issue, updating the window size after saving it for frame 0 captures. Note however that fundamentally GL is still a terrible API especially around window & context management, and that there will be cases this will still be wrong on if the context/window changes (most likely to happen during frame 0 setup).
