### ISSUE TITLE
enable renderdoc capture cause steam game "Shadow of the Tomb Raider" rendering corruption on RADV driver

### ISSUE THREAD

**Issue by farosis** [baldurk/renderdoc#2891]
## Description

different version of renderdoc behavious diffenrently on this issue, version 1.25 simply doesn't show capture options. I have to use 1.18 to enable capture.

## Steps to reproduce
1. start a terminal on Ubuntu 22.04.
2. export ENABLE_VULKAN_RENDERDOC_CAPTURE=1
3. start steam in the same terminal. choose the game.
4. select the "Manage---> Properties--->Compatibility---> Force the use of a specific SteamPlay compatibility tool"
5. check the "Force the use of specific Steam Play compatibility tool" box and select the Proton version -> "7.0-6"
6. close the window and the game should Update automatically, if not manually click the updated bottom of the game 
7. once the game finishes update, start the game, in the launch menu go to options and  Unselect DirectX12
8. to start the benchmark: "Options->  Display and Graphics -> "Run Benchmark'/ or Press "R" 
9. you will notice the corruption.

## Environment

* RenderDoc version: 1.18
* Operating System: ubuntu22.04
* Graphics API: DX11 over Proton

I'm using 6900XT on this issue, amdvlk driver always render corrupted looks similar to how renderdoc enabled on RADV, but without renderdoc enabled RADV renders correctly, you can also use the vulkan version(default option on ubuntu without enable proton) of the game to see the correct rendering. also please make sure "DX12" unselect in the game panel, it crashes on both RADV and AMDVLK. if you are busy, please share you idea, I'd like to understand the issue in renderdoc

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing programs that are not your own is not endorsed or allowed for any reason, and I will provide absolutely no support for it.
