### ISSUE TITLE
RenderDoc running when Android Studio opened, jdwp handshake failed

### ISSUE THREAD

**Issue by CatDroid** [baldurk/renderdoc#2892]
## Description

Each time when I change code, I need to restart android studio and then close to use RenderDoc.
I think it's troublesome, and I try some ways to deal with it, but fail. 
A. 
[Troubleshooting](https://renderdoc.org/docs/how/how_android_capture.html#troubleshooting)
“Tools → Android → Enable ADB integration”.
This button was not exsiting after Android Studio 3.0, and I am using Android Studio 4.4 or higer.

B. 
I change the RendorDoc's code , e.g 
android.cpp  Android::GetJdwpPort : use another jdwp port--- but it's not working 
or 
RenderDoc_ForwardPortBase : use another local port --- but it's not working 

Finally,  it will log "handshake failed - received"
Connection::Connection @ jdwp_connection.cpp 
and then prompt "Error connection to debugger"  

Actually, I'm confused about what influence RenderDoc to commuticate to debugable app with jdwp. 

## Steps to reproduce

1. Start up Android Studio, but not do anything on it 
2. Start up RenderDoc
3. Start up debugable app on Android Device by RenderDoc.
4. debugable app prompt "Waiting for Debugger" and RenderDoc prompt  "Error connection to debugger"  

## Environment

* RenderDoc version: v1.22 (built from 95edf6a9)
* Operating System: Windows 10
* Graphics API: OpenGLES

**Comment by CatDroid** [comment]
I found this is an issue about Android Studio.
It seems that Android Studio will jdb all debugable app, so other tools ( like RenderDoc or even  JDB on command line.) can not jdwp with certain debugable app,

**Comment by baldurk** [comment]
Yes sorry, I was going to reply to this earlier but something else came up.

Unfortunately as you say this is a problem with Android Studio, not RenderDoc and not something that can be fixed on my side. On old Android devices (before Android 10) RenderDoc needs to use the debugger connection to inject itself into your application on the device, however Android Studio automatically connects to all debuggable apps before RenderDoc can, and takes the only connection.

The option you mentioned used to disable this behaviour, If the option has moved in Android Studio you'd need to look for where it has moved to (if it still exists), I do not use Android Studio myself so I can't answer that question. If you do find where the option has moved to you can let me know and I can update the documentation.

Note that with newer Android devices this should not be an issue as the debugger connection is not used.
