### ISSUE TITLE
Game crashes at startup (License)

### ISSUE THREAD

**Issue by Skel7890** [baldurk/renderdoc#2893]
@

## Steps to reproduce

 Run the file ACBSP.exe at the root of the licensed game with the launch parameter "-playoffline" through the program

## Environment

* RenderDoc version: (Latest) v1.26
* Operating System: Windows 10 Home Edition
* Graphics API: I do not know

<!-- More details here never hurt! For example your GPU, driver version, etc.

NVIDIA GeForce RTX 3060
Intel Core i5-9400 2.90 GHz
RAM 16 GB

https://user-images.githubusercontent.com/124431246/229536247-49363695-c986-42a7-9111-570afe9f130d.png

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing programs that are not your own is not endorsed or allowed for any reason, and I will provide absolutely no support for it.
