### ISSUE TITLE
Can we include Android x86/x86_64 build apk in nightly build?

### ISSUE THREAD

**Issue by zzyiwei** [baldurk/renderdoc#2897]
## Description

Hi, can we include Android x86/x86_64 build apk in nightly build? There're more and more x86 Android devices in the market:
* Android on Intel and AMD Chromebooks
* Cloud Android
* other Android emulators on x86 platforms.

Having prebuilt renderdoc work out-of-box on those platforms would make life much easier for platform and app developers when debugging against Vulkan drivers on x86 platforms. If nightly build is too frequent for including the x86 layer libs and core libs, weekly is fine as well ; )

Many thanks!

## Environment

* RenderDoc version: N/A
* Operating System:
   * Android on ChromeOS on Intel/AMD platforms
   * similar also applies to Cloud Android and Android emulators on x86 platforms
* Graphics API: Vulkan

**Comment by baldurk** [comment]
x86 is not supported on Android at all, so no builds will be provided. I don't even know if it compiles or runs successfully.

**Comment by zzyiwei** [comment]
@cnorthrop for the info as well. Local build to do the x86 build works, and I’ve used that so far to debug issues with Android apps on Intel Chromebooks.

@baldurk I’m confused about “x86 is not supported on Android at all” part. ARCVM (Android VM) on ChromeOS devices are with the x86_64 build if the host platform is Intel or AMD.

**Comment by baldurk** [comment]
I mean that x86 on Android is not a supported platform for RenderDoc, sorry that was ambiguous. I only support arm32 and arm64 platforms on Android - any other platforms like x86 or mips etc are not supported. I don't test them to make sure they compile or run, so they may work by coincidence but it could break with a future change or when used in a different way.
