### ISSUE TITLE
OpenGL on Linux: cloned context may use incompatible fbconfig

### ISSUE THREAD

**Issue by derhass** [baldurk/renderdoc#2898]
## Description

After upgrading to versionv1.26, capturing some OpenGL programs stopped working, the programs would abort with an GLX related error:

```
mh@ixtlilton:~/development/HelloCube$ renderdoccmd capture ./HelloCube
Launching './HelloCube'
Launched as ID 38922
initializing GLFW
mh@ixtlilton:~/development/HelloCube$ creating window and OpenGL context
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  170
  Current serial number in output stream:  170
```

Bisecting the issue ended up with 7d05d545d2928df3678bf5057e70a9869d4b8983:

```
7d05d545d2928df3678bf5057e70a9869d4b8983 is the first bad commit
commit 7d05d545d2928df3678bf5057e70a9869d4b8983
Author: Le Philousophe <lephilousophe@users.noreply.github.com>
Date:   Sat Jan 28 18:15:40 2023 +0100

    Create a clone context with the same profile as the shared one
    
    This matches behaviour of WGLPlatform

:040000 040000 741b52cab73fa04b5efa709564e7dc7d601bf100 51b011cf127f4b0086c704bc396ec7577d452304 M      renderdoc
```

After looking at the code and some experimenting, it turned out that on the `glXGetConfig(..., GLX_FBCONFIG_ID, ...)` call, the nvidia proprietary driver returned `GLX_BAD_ATTRIBUTE`. In my reading of the glX 1.4 spec (and the driver reports version 1.4), this query attribute is explicitly allowed at this point. 

However, as the Fbconfig ID was not queried, the rest of the code does just query all fbconfigs with no particular attributes,and used the first entry that is returned - which might not be compatible to the actual visual of the window, so making current the cloned context fails...

## Steps to reproduce

Trying to capture the GL output of for example my simple [HelloCube](https://github.com/derhass/HelloCube) (GLFW based) example is enough. I'm not sure why this bug isn't hit more often, though.

In my reading of the glX spec, this should be a an implementation bug. To check this, I made this quick&dirty test (not run through renderdoc):
```
/* compile:  gcc test.c -lX11 -lGL -otest, run: ./test */
#include <GL/glx.h>
#include <stdio.h>

int main(int argc, char **argv)
{
        int i;
        Display *dpy = XOpenDisplay("");
        printf("%s %s\n",glXGetClientString(dpy, GLX_VERSION),glXGetClientString(dpy, GLX_VENDOR));
        XVisualInfo tpl = {0};
        int cnt = 0;
        XVisualInfo* vi = XGetVisualInfo(dpy, VisualNoMask, &tpl,&cnt);
        printf("%d\n",cnt);

        for(i=0;i<cnt;i++) {
                int gl = 0;
                int res1 =glXGetConfig(dpy, vi+i, GLX_USE_GL, &gl);
                if (res1 == Success && gl) {
                        int id = -1;
                        int res2 =glXGetConfig(dpy, vi+i, GLX_FBCONFIG_ID, &id);
                        printf("vis: 0x%x res: %d fb: 0x%x\n",(unsigned)vi[i].visualid,res2,(unsigned)id);
                }
        }
        XFree(vi);
        XCloseDisplay(dpy);
        return 0;
}
```
and neither on my main machine with NVidia proprietary driver, nor on my laptop with mesa (Intel GPU), the `glXGetConfig(.. GLX_FBCONFIG_ID, ...)`  ever gave a useful result.

## Suggested Workaround 

So  I'm suggesting the following workaround to make he fbconfig selection more robust:
https://github.com/derhass/renderdoc/commit/d667cca328606b35eb1e252cebd9ea0838ee693e

This will try to find a matching fbconfig by checking the `GLX_VISUAL_ID` of all returned fbconfigs if it did not get the fbconfig ID before. With this workaround, renderdoc works for me again.

## Environment

* RenderDoc version: 1.26
* Operating System: Linux Debian 10.13, 
* Graphics API: OpenGL (via glX)
```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 525.105.17
```

**Comment by baldurk** [comment]
I'd agree, I don't see a reason why this attribute should fail to query but glx is a bit of a hellish API so there might be some obscure reason it breaks.

I think your fix is along the right lines so you could probably open a PR. I think it could break in some cases since visuals and fbconfigs aren't 1:1 AFAIK, but it's better than picking the first of the whole list and guessing (and I think even a different fbconfig with the same visual should be compatible enough for our purposes). In fact I don't think you even need to make that loop conditional on the visual query, as it should be safe to do always - if the fbconfig was queried we should have a list of one and a) the visual should match the first one b) even if it doesn't for some reason the loop falls back to picking the first in the list anyway.

One thing that's worth trying though - does it work if you use `GLX.glXQueryContext(share.dpy, share.ctx, GLX_FBCONFIG_ID, &fbcfgID);` to query the context for its fbconfig ID instead of the visual? that might be more reliable as a fallback.

**Comment by derhass** [comment]
> One thing that's worth trying though - does it work if you use `GLX.glXQueryContext(share.dpy, share.ctx, GLX_FBCONFIG_ID, &fbcfgID);` to query the context for its fbconfig ID instead of the visual? that might be more reliable as a fallback.

Yes, this works and is much simpler. I created PR #2899 for this.
