### ISSUE TITLE
Pixel History tex after is incorrect on Intel GPUs on OpenGL for multiple primitives touching a single fragment in a single draw call

### ISSUE THREAD

**Issue by w-pearson** [baldurk/renderdoc#2907]
## Description

This is a follow-up to #2894. Sorry for taking a while to report it properly.

If there are multiple primitives touching a single fragment in a single draw call, the output is completely incorrect (at least on my Intel GPU). This includes the "tex after" field for the whole draw, not just the primitives before then. (The Vulkan issue had the correct result for the last primitive, and in fact skips recalculating the tex after column for the last primitive.) The incorrect value is random garbage (and can change if you select pixel history for the same pixel multiple times). Usually all of them have the same value, but not always.

Separate drawcalls (i.e. `glDrawArrays(GL_TRIANGLES, 0, 3); glDrawArrays(GL_TRIANGLES, 3, 3); glDrawArrays(GL_TRIANGLES, 6, 3);`) work properly, as does the unmodified GL_Simple_Triangle demo. GL_Pixel_History causes renderdoc to hang on my machine (I'm not sure why and I haven't investigated it enough to be sure whether it's a RenderDoc problem or an Intel problem).

## Steps to reproduce

Patch the demos GL_Simple_Triangle demo using the patch I had on #2894.
1. Launch the modified demos in RenderDoc.
2. Start GL_Simple_Triangle.
3. Make a capture.
4. Close the demo.
5. In renderdoc, right-click at around (200, 200) (a location hit by all 3 triangles).
6. Select pixel history
7. Observe that while the "pixel out" column is correct for all three primitives, the "tex after" column is incorrect.

Here are several captures, which hopefully will be helpful: [captures.zip](https://github.com/baldurk/renderdoc/files/11226695/captures.zip). The captures do report several errors, which are all one of these:

```
0 API High Miscellaneous 1280 Error has been generated. GL error GL_INVALID_ENUM in IsEnabled: (ID: 3525876922) Generic error
7 API High Miscellaneous 1282 Error has been generated. GL error GL_INVALID_OPERATION in GetVertexAttribfv: (ID: 775370890) Generic error
```

I don't have easy access to another GPU currently so I don't have a good way of checking non-Intel devices. Hopefully this information is enough to do something; let me know if there's anything else I can supply.

<details><summary>Example screenshots</summary>

![image](https://user-images.githubusercontent.com/127789813/231885902-d06f8bbd-0996-4e46-ba90-8035f71b67a0.png)
![image](https://user-images.githubusercontent.com/127789813/231885910-eb250ccb-7337-4510-bd07-eb1f6c77943d.png)
![image](https://user-images.githubusercontent.com/127789813/231885893-e2cf7511-5b5c-4b63-ad75-c11709e79031.png)

</details>

## Environment

* RenderDoc version: Self-built 6ab754b4e47101447e4faff8f8a3f856f3450ede (official v1.26 is affected by #2894).
* Operating System: Windows 10.0.19042.2728
* Graphics API: OpenGL
* CPU: 12th Gen Intel(R) Core(TM) i7-1270P, 2200 Mhz, 12 Core(s), 16 Logical Processor(s)
* GPU: Intel(R) UHD Graphics, driver version 31.0.101.4255; this also happened with driver version 31.0.101.3790

**Comment by baldurk** [comment]
That commit should fix it. This is a driver bug, it's applying scissors to framebuffer blits internally unless every scissor is disabled, when it should at most only be applying the first scissor region.
