### ISSUE TITLE
Capture annotation saving issue

### ISSUE THREAD

**Issue by Goshido** [baldurk/renderdoc#2908]
## Description

According to [official documentation](https://renderdoc.org/docs/getting_started/tips_tricks.html) (_tip №10_) _RenderDoc_ should save annotation and other changes inside opened capture. Indeed it works when _PC_'s _GPU_ is used. So called `local` mode. But unfortunately it doesn't work when `remote` mobile _GPU_ is used . It's sad because I found the problem only after several hours working with capture and highly annotated it. All progress was lost.

## Steps to reproduce

1. Make _GLES 3.2_ capture on _Android_ smartphone.
1. Save capture on the _PC_ 
1. Open capture via _RenderDoc_ and select _Android_ device as renderer.
1. Annotate texture resource. Set custom name for example.
1. Trigger `File->Save Capture`

### Problem

The `.rdc` file with capture did not change. You can verify it via _Windows Explorer_. If you open this file again and look at annotated texture it will not have custom name.

### Expected

Capture annotations and other changes should be saved in `.rdc` file as explained in  [official documentation](https://renderdoc.org/docs/getting_started/tips_tricks.html) (_tip №10_).

## Environment

* RenderDoc version: _1.26_
* Operating System: _Windows 10_ and _Android 12_
* Graphics API: _GLES 3.2_

## Addition

I also tried to export capture _XML + ZIP_. It also did not work. Annotations were lost as well.

**Comment by baldurk** [comment]
That commit should fix the code to save annotations to the local file as intended, rather than saving them across the remote connection to the temporary file that was transferred.
