### ISSUE TITLE
LD_LIBRARY_PATH is set too "vaguely" for some captured processes if installed globally

### ISSUE THREAD

**Issue by gri573** [baldurk/renderdoc#2909]
## Description

I would like to capture Minecraft Java edition, as I am developing a shader pack for it.
However, when launching applications, qrenderdoc sets `LD_LIBRARY_PATH=/usr/bin:/usr/bin/../lib:/usr/lib` (in my case anyway, but the main issue is that it adds /usr/lib if installed globally). This can cause issues with some applications that have their own shared libraries (such as java runtime environments, which provide their own `libnet.so`), which are then potentially overridden by incompatible versions in `/usr/lib` or `usr/bin`, as described [here](https://bugs.archlinux.org/task/77183).
I would expect renderdoc to have the shared libraries it needs (or symlinks to them) in a subdirectory and only add that to `LD_LIBRARY_PATH`

I believe this may be a problem with the PKGBUILD configuration of renderdoc in the arch user repository rather than renderdoc itself, but this is still the best place I found to report it

## Steps to reproduce

 - Have a linux computer with renderdoc installed with its shared library files in /usr/bin, and a java runtime environment with dynamic libraries specified via RUNPATH rather than RPATH (so that LD_LIBRARY_PATH takes precedence over it)
 - have libnet.so in /usr/lib
 - attempt to start the jre through renderdoc
   - alternatively, start a minecraft launcher. These will have various symptoms depending on the exact one: the official launcher will start, crash, start again, crash again and stay closed after that. multimc-based launchers will start, but will fail to start the game, and will also report that they didn't find any java versions in their appropriate settings

## Environment

* RenderDoc version: v1.26
* Operating System: endeavourOS / arch linux
* Graphics API: the program doesn't get far enough to start initialising one, but it would be openGL

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing programs that are not your own is not endorsed or allowed for any reason, and I will provide absolutely no support for it.
