### ISSUE TITLE
Attaching to a remote process from Windows to Linux

### ISSUE THREAD

**Issue by edrickhong** [baldurk/renderdoc#291]
Hey, I am trying to attach render doc to my remote linux machine to try out the debugger. However, I have not done any sort of remote debugging before. Can you explain to me what I need to do to get remote debugging working? Thanks.

**Comment by baldurk** [comment]
This setup is a bit unfriendly and possibly buggy since it hasn't really been supported in the past.

It's something I'm actively looking at improving and smoothing out the workflow though, so there will be some proper documentation and instructions arriving soon.

**Comment by baldurk** [comment]
The workflow for this has been implemented in [v0.31](https://github.com/baldurk/renderdoc/releases/tag/v0.31) - see [the documentation](https://renderdoc.org/docs/how/how_network_capture_replay.html) or a [short video](https://youtu.be/6_Bg06oe22I) I recorded showing how it fits together.
