### ISSUE TITLE
GL_EXT_scalar_block_layout not properly supported by 'Go' feature to view buffer data

### ISSUE THREAD

**Issue by forenoonwatch** [baldurk/renderdoc#2918]
## Description

I have a GLSL shader with an SSBO declared to have scalar layout, and containing an array of structs:

```glsl
struct Instance {
	mat4x3 model;
	uint materialID;
};

layout (set = 1, binding = 0, scalar) readonly buffer InstanceData {
	Instance instances[];
};
```

When I click the Go button from the Pipeline State view in order to view the data in my buffer,  it will open the buffer but show some of my fields commented out with unexpected size/matrix stride. If I manually modify the format to be `#pack(scalar)`, uncomment these fields, and press apply, I am able to view my data correctly.

![image](https://user-images.githubusercontent.com/91013521/233743596-8fb683ce-3d42-461c-9564-9d70e1f193a9.png)
![image](https://user-images.githubusercontent.com/91013521/233743713-d4e0f0cc-d9c4-4316-a5d5-f47146141ca3.png)

## Steps to reproduce

1. Create an SSBO with the `scalar` layout decorator, containing a struct that would have a different size/layout when scalar than when std140 or std430. This is important to note because structs which would function normally in std430 do not get fields commented out, although they do not get declared with #pack(scalar)
2. Take a capture of a shader using this buffer, navigate to the pipeline state menu, and press Go on the buffer.

## Environment

* RenderDoc version: v1.26 (built from 4524cddc)
* Operating System: Windows 10 Pro 64 bit, OS build 19044.1826
* Graphics API: Vulkan 1.1
* GPU: NVIDIA GeForce GTX 760
* GPU Driver Version: 473.81.0.0

**Comment by baldurk** [comment]
This was specifically an issue where the matrix was the only thing requiring scalar layout, and everything else was otherwise non-scalar. The reverse engineering/detection I have to guess which layout is in use wasn't properly detecting that and then got confused generating the format when it detected the matrix stride difference.

That commit should fix this.

**Comment by itayronen** [comment]
Just updated to 1.27 and it a similar issue reproduces.
In my case on compute shader.
When I edit the auto-generated format, everything is fine, it's just the auto-generated still produces `#pack(std430)` instead of `#pack(scalar)`.

glsl:
```glsl
#version 460
#extension GL_EXT_scalar_block_layout : require

struct MeshletData {
	mat4 worldTransform;
	uint geometryIndex;
};

layout(scalar, set = 1, binding = 0) readonly buffer MeshletBuffer { MeshletData data[]; } meshletBuffer;
```

Auto generated format:
```glsl
#pack(std430)

// Unexpected size of struct 68
struct MeshletData
{
	float4x4 worldTransform;
	uint geometryIndex;
}
```

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
