### ISSUE TITLE
Vulkan pixel history fails to detect shader discards on Intel

### ISSUE THREAD

**Issue by w-pearson** [baldurk/renderdoc#2925]
## Description

Pixel history does not properly detect shader discards (presumably only on Intel drivers). For discards, it seems like shader out shows as all black, while tex after is unchanged. (Though, shader out might simply be undefined and in my case it just happens to be black).

## Steps to reproduce

This can be reproduced by running the `VK_Pixel_History` functional test.

```
$ ./renderdoccmd test functional -t VK_Pixel_History
...
>> Test VK_Pixel_History
    .. Running exe:'C:\Users\w.pearson\source\repos\renderdoc-contrib\util\test\demos_x64.exe' cmd:'VK_Pixel_History --log C:\Users\w.pearson\source\repos\renderdoc-contrib\util\test\tmp\demos.log' in dir:'' with env:'[]'
main.cpp:678 Log: Running 'VK_Pixel_History'
    .. Queuing capture of frame 5..6 with timeout of default
vk\vk_test.cpp:294 Log: Initialising Vulkan at VK1.3
vk\vk_test.cpp:750 Log: Running Vulkan test on Intel(R) UHD Graphics (version 1.3)
    >> Raw Process output
        vk\vk_test.cpp:294 Log: Initialising Vulkan at VK1.3
        vk\vk_test.cpp:750 Log: Running Vulkan test on Intel(R) UHD Graphics (version 1.3)
    << Raw Process output
    .. Loading capture
    .. Checking capture
    .. Testing pixel 190, 149
    ** Picked value at 190,149 in Swapchain Image 176 is as expected
    .. Testing pixel 190, 150
    ** Picked value at 190,150 in Swapchain Image 176 is as expected
    .. Testing pixel 200, 50
    ** Picked value at 200,50 in Swapchain Image 176 is as expected
    .. Testing pixel 150, 250
    !+ FAILURE in VK_Pixel_History: TestFailureException eventId 21, primitiveID 0: testing shader_discarded expected True, got False
    >> Callstack
        File "tests/Vulkan/VK_Pixel_History.py", line 397, in check_events
            actual))
        File "tests/Vulkan/VK_Pixel_History.py", line 122, in primary_test
            self.check_events(events, modifs, False)
        File "tests/Vulkan/VK_Pixel_History.py", line 37, in check_capture
            self.primary_test()
        File "rdtest/testcase.py", line 493, in run
            self.check_capture()
        File "rdtest/testcase.py", line 500, in invoketest
            self.run()
        File "rdtest/runner.py", line 349, in do
            instance.invoketest(debugMode)
        File "rdtest/runner.py", line 357, in run_tests
            do(False)
    << Callstack
    !- FAILURE
    $$ FAILED
<< Test VK_Pixel_History
...
```

The test passes if the `check_events` call on line 122 is commented out (i.e. everything else behaves correctly; it's only discards that are broken).

In RenderDoc itself, this can be seen just by using pixel history at x=150 and observing that e.g. EID 21 is not shown as a discard. (That's how I checked the stable version).

## Environment

* RenderDoc version: v1.26, self-built eb643dd76f92aed18f9837fe942d5491feb8f3e1. Demos from eb643dd76f92aed18f9837fe942d5491feb8f3e1.
* Operating System: Windows 10.0.19042.2728
* Graphics API: Vulkan
* CPU: 12th Gen Intel(R) Core(TM) i7-1270P, 2200 Mhz, 12 Core(s), 16 Logical Processor(s)
* GPU: Intel(R) UHD Graphics, driver version 31.0.101.4255

**Comment by baldurk** [comment]
This looks to be a different manifestation of a driver bug previously encountered. I've expanded the workaround that seems to work for me, but it may or may not work depending on what the driver bug is.

**Comment by w-pearson** [comment]
Thanks. That workaround seems to at least fix the broken test on my machine. If I find any other broken edge-cases I'll open a new issue.

**Comment by baldurk** [comment]
At this point I would suggest that you don't unless it repro's on a non-Intel GPU. Intel seems quite broken.

**Comment by w-pearson** [comment]
I was looking over this code again and I noticed that there seems to be a mistake:

https://github.com/baldurk/renderdoc/blob/1a2db41fa807dd0bdc4afe67f5d92590fef9dee7/renderdoc/driver/vulkan/vk_pixelhistory.cpp#L785-L788

Shouldn't the second line use `dst` instead of `src`?

```C++
atts[i].dstColorBlendFactor = atts[i].dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
```

I tested it out locally and it seems like both versions behave correctly on my machine. (I'm not sure if that makes sense or not.)

(As a minor side thing, `atts[i].colorWriteMask = VK_COLOR_COMPONENT_A_BIT` would probably also be clearer than using `0x8`, but that shouldn't matter either.)

**Comment by baldurk** [comment]
Yes it should have been dst, fixed now.
