### ISSUE TITLE
vkGetInstanceProcAddr for vkCreateDevice broken on some newer Vulkan loader revisions

### ISSUE THREAD

**Issue by tycho** [baldurk/renderdoc#2927]
## Description

This commit in the Vulkan loader broke `WrappedVulkan::vkCreateDevice()`, since it uses `vkGetInstanceProcAddr(VK_NULL_HANDLE, "vkCreateDevice")`:
https://github.com/KhronosGroup/Vulkan-Loader/commit/4be91725abb01e8004be966203b95a181c06e1a0

It was later "fixed" through a compatibility hack in https://github.com/KhronosGroup/Vulkan-Loader/commit/23d4caea0d450b94fd96fa380307d755379df5a2

It's unlikely that anyone will run into this bug in the wild since the compatibility fix was added within a matter of a few days. However, it sounds like requesting the `vkCreateDevice` function without an instance handle is against the spec, so this should probably be fixed anyway.

Proposed fix, with an added sanity check for `createFunc` being non-null to prevent a less graceful crash:

```diff
diff --git a/renderdoc/driver/vulkan/wrappers/vk_device_funcs.cpp b/renderdoc/driver/vulkan/wrappers/vk_device_funcs.cpp
index fc0d383ca..c3bd5c546 100644
--- a/renderdoc/driver/vulkan/wrappers/vk_device_funcs.cpp
+++ b/renderdoc/driver/vulkan/wrappers/vk_device_funcs.cpp
@@ -3902,7 +3902,13 @@ VkResult WrappedVulkan::vkCreateDevice(VkPhysicalDevice physicalDevice,
   // move chain on for next layer
   layerCreateInfo->u.pLayerInfo = layerCreateInfo->u.pLayerInfo->pNext;

-  PFN_vkCreateDevice createFunc = (PFN_vkCreateDevice)gipa(VK_NULL_HANDLE, "vkCreateDevice");
+  PFN_vkCreateDevice createFunc = (PFN_vkCreateDevice)gipa(m_Instance, "vkCreateDevice");
+
+  if(createFunc == NULL)
+  {
+    RDCERR("Couldn't get the address of vkCreateDevice. Incompatible loader?");
+    return VK_ERROR_INITIALIZATION_FAILED;
+  }

   // now search again through for the loader data callback (if it exists)
   layerCreateInfo = (VkLayerDeviceCreateInfo *)pCreateInfo->pNext;
```

## Steps to reproduce

* Attempt any Vulkan RenderDoc capture when using a `vulkan-1.dll` built from https://github.com/KhronosGroup/Vulkan-Loader/commit/4be91725abb01e8004be966203b95a181c06e1a0
* RenderDoc layer will cause the application to crash upon trying to call through the null `createFunc` pointer.

## Environment

* RenderDoc version: v1.26-65-geb643dd76 (eb643dd76f92aed18f9837fe942d5491feb8f3e1)
* Operating System: Windows 10 19044.2846
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Very strange that I had that there, it looks like that code goes back to the earliest layer interface changes just before public vulkan 1.0 release, I presume it was explicitly illegal back then too and this is just a copy-paste error though the spec has been tightened up around the behaviour of GIPA/GDPA since then.

Closed in b115a6750b - almost the same as your diff but with an unwrap of the instance.
