### ISSUE TITLE
Renderdoc does not open simple Vulkan capture properly

### ISSUE THREAD

**Issue by ruperson** [baldurk/renderdoc#2931]
## Description
A Simple Vulkan demo app created in Unity for Android was captured using Renderdoc v 1.26. When opening capture in Renderdoc v 1.26 the output image does not match saved thumbnail. Moreover, every time the same capture is opened, a different output image is produced.

## Steps to reproduce
Open the attached capture in Renderdoc v.1.26 several times and observe output image after vkQueuePresentKHR.
[UnitySample.zip](https://github.com/baldurk/renderdoc/files/11398887/UnitySample.zip)

## Environment
* RenderDoc version: 1.26
* Operating System: Windows 10 Pro
* Device: ARM-Mali-G76, 18.0.0 Android 10
* Graphics API: Vulkan

**Comment by andrew-archer80** [comment]
Confirm. The same problem observed.

**Comment by baldurk** [comment]
I believe that commit should fix the issue, at least it does on my similar ARM device though I don't have that exact GPU to test with. The next nightly build should work so let me know if it functions for you as a different device may not behave the same.

@andrew-archer80 please open a separate issue with a reproducible test case if you are encountering a bug, as there is no guarantee that the problem you are seeing is the same as someone else's.
