### ISSUE TITLE
Provide 32-bit linux builds

### ISSUE THREAD

**Issue by Miepee** [baldurk/renderdoc#2933]
## Description
There are currently still a bunch of games/programs built as 32-bit applications as opposed to 64-bit applications, which for some reason or another, cannot be built as 64-bit. I personally want to [contribute to one ](https://github.com/milesthenerd/AM2R-Server), but because it has a requirement on an older compiler/IDE (Game Maker Studio 1.4), only 32-bit builds can exist.
Since on Linux Renderdoc only supports capturing from an identical ABI, this makes it difficult for me to use Renderdoc on the program / my contributions. Since not only would I have to compile everything from source, but Renderdoc on 32-bit (x86) Linux is also completely unsupported.
Another potential use case could be for game developers to run their games under wine/proton to investigate steam deck compatibility bugs (I was involved in such a case, where in the end the bug was just fixed by pure trial and error).

I realize this isn't a huge priority, and there are probably good technical reasons as to why this was never done, but it would be very appreciated.
## Environment

* RenderDoc version: 1.26
* Operating System: Arch Linux
* Graphics API: OpenGL

**Comment by baldurk** [comment]
This is not something I want to support, no. Realistically the number of exclusively 32-bit programs that are actively maintained is small and only shrinking. It's not something I want to expand the support set to include.

You're can continue using RenderDoc on 32-bit linux as it's not deliberately blocked by any means, and you can contribute any fixes specific to that architecture (as long as they aren't likely to cause problems), but it will not be officially supported and so I will not provide any support for bugs exclusive to that ABI or provide official builds.
