### ISSUE TITLE
GL enum confusion - GL_ONE vs GL_LINES, GL_ZERO vs GL_NONE

### ISSUE THREAD

**Issue by hrydgard** [baldurk/renderdoc#2935]
## Description

A really simple one, and not critical in any way.

I'm looking at a glBlendFuncSeparate call and noticed that the arguments were displayed as GL_LINES and GL_NONE, which don't make much sense as blend factors.

![image](https://github.com/baldurk/renderdoc/assets/130929/f99f8598-3aed-4cc7-bcb2-401440abbee7)

Of course, this happens because GL_LINES = 1 and GL_ONE = 1 (which would be the expected value).
Similarly, GL_NONE = 0 and GL_ZERO = 0.

So, need to choose which enum to display from in a context dependent way.

## Steps to reproduce

Record an app that uses glBlendFuncSeparate with GL_ZERO and GL_ONE as parameters in RenderDoc, and look at the output. PPSSPP would be an example.

## Environment

* RenderDoc version: v1.26
* Operating System: Windows 10
* Graphics API: OpenGL

NV, but should hardly matter.

**Comment by baldurk** [comment]
This has been brought up before, but it is effectively an OpenGL bug and not worth fixing - the blend state is displayed correctly on the pipeline state view which is 95% of the time where people will be looking for this information.

**Comment by hrydgard** [comment]
Ok, that's fair enough!
