### ISSUE TITLE
[OpenGL 4.6] Updated image bindings (via glUniform1i) for SPIR-V shaders are not reflected in Pipeline State

### ISSUE THREAD

**Issue by JuanDiegoMontoya** [baldurk/renderdoc#2942]
## Description

I have a simple application that does the following things each frame:
1. Binds a compute program
2. Sets an image binding of the program with `glUniform1i` (the binding is set to 0)
3. Binds a 1x1 image to unit 0 with `glBindImageTexture`
4. Dispatches compute to set the image to a solid color (green)
5. Binds a graphics program
6. Draws a single triangle that maps the 1x1 texture color to all fragments

The result is a green triangle whether the shader was created with SPIR-V or textual GLSL. However, RenderDoc will not show the updated binding in the pipeline state tab if the shader was made with SPIR-V.

Here is an image of the bug in question, when using a SPIR-V shader:
![the bug](https://i.imgur.com/39elHZd.png)

With textual GLSL, RenderDoc displays the updated binding with no issue:
![the not-bug](https://i.imgur.com/7P2nLJM.png)

The image uniform is bound to 5 by default with an explicit binding in the shader `layout(binding = 5)`.

The correct image is drawn whether the shader was created with SPIR-V or textual GLSL.

## Steps to reproduce

1. Create a SPIR-V shader that uses images (`glShaderBinary(..., GL_SHADER_BINARY_FORMAT_SPIR_V, ...)` + `glSpecializeShader(...)`)
2. Use `glUniform1i` to change the binding of one or more images
3. Bind the image accordingly and invoke the shader
4. In RenderDoc, observe the pipeline state for the image bindings that were changed

zip containing captures with the bug (using a SPIR-V shader) and without (using a regular textual GLSL shader): [rdc.zip](https://github.com/baldurk/renderdoc/files/11540059/rdc.zip)

## Environment

* RenderDoc version: v1.26
* Operating System: Windows 10
* Graphics API: OpenGL
* GPU: RTX 3070
* Driver version: 531.79

**Comment by baldurk** [comment]
This behaviour is deliberately not supported and I don't think is always even specified as defined/legal in all cases. GLSL compiled to SPIR-V always supports proper explicitly specified bindings like any other modern API so there should be no need to attempt to modify them dynamically.
