### ISSUE TITLE
feature requests for zink compat

### ISSUE THREAD

**Issue by zmike** [baldurk/renderdoc#2943]
## Description
There's a few features zink uses that renderdoc doesn't support. I think they're all pretty trivial. Supporting them would reduce the delta between what users see when running zink standalone and trying to capture with renderdoc for issue reporting.

* EXT_provoking_vertex
* EXT_image_2d_view_of_3d
* EXT_attachment_feedback_loop_dynamic_state

## Environment

* RenderDoc version: git ae718049f68c796626a980ceba215363c99efbfa
* Operating System: linux
* Graphics API: vulkan

**Comment by baldurk** [comment]
These extensions have now been implemented in 4b87803, a6c1ba1 and 2887409.
