### ISSUE TITLE
Array out-of-bounds when `elemtype` is empty

### ISSUE THREAD

**Issue by mickbeaver** [baldurk/renderdoc#2947]
## Description

When loading the XML config, it is possible to have an empty string as the `elemtype` of an array. This causes us to index into the `types` array with an index of `-1`. On instrumented builds that detect memory problems, this can cause an error.

Example XML config snippet:
```
  <DXBC>
    <Debug>
      <!-- DXBC.Debug.SearchDirPaths

Paths to search for separated shader debug PDBs.

Default value: '[]' -->
      <SearchDirPaths type="Array" elemtype=""></SearchDirPaths>
    </Debug>
```

## Steps to reproduce

Run RenderDoc in such a way that it loads renderdoc.conf with the aforementioned zero-length array with empty string for the `elemtype`. You will find that you are using an array index of `-1` in `XML2Config(pugi::xml_node &obj)`.

I fixed this locally using the following code snippet:

```
    if(type == SDBasic::Array)
    {
#if 0
      type = types[basicTypeStrings.indexOf(obj.attribute("elemtype").as_string())];
#else
      // Empty arrays may not have an elemtype. Default to String.
      const int32_t basicTypeIndex = basicTypeStrings.indexOf(obj.attribute("elemtype").as_string());
      type = (basicTypeIndex != -1) ? types[basicTypeIndex] : SDBasic::String;
#endif

```

## Environment

* RenderDoc version: 1.17
* Operating System: Windows 10
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Thanks for reporting this, that commit should fix it. I also noticed the string-to-enum array was static but being filled each time, leading it to grow, so I also fixed that.

I'm hoping that you saying version 1.17 was a typo and you meant 1.27, if not I would strongly recommend you update as that version is 1.5 years out of date.
