### ISSUE TITLE
Renderdoc-layer crashes when using vkUpdateDescriptorSets to update multiple bindings

### ISSUE THREAD

**Issue by timon37** [baldurk/renderdoc#295]
From what I managed to conclude WrappedVulkan::vkUpdateDescriptorSets() assumes that a single VkWriteDescriptorSet will only touch a specific binding and it's array elements however the specification allows using one to update multiple consecutive bindings.

Quote from the vulkan-spec, section for vkUpdateDescriptorSets:
> If the dstBinding has fewer than descriptorCount array elements remaining starting from dstArrayElement, then the remainder will be used to update the subsequent binding - dstBinding+1 starting at array element zero. This behavior applies recursively, with the update affecting consecutive bindings as needed to update all descriptorCount descriptors. All consecutive bindings updated via a single VkWriteDescriptorSet structure must have identical descriptorType and stageFlags, and must all either use immutable samplers or must all not use immutable samplers.
[link to spec](https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#descriptorsets-updates-consecutive)

**Comment by baldurk** [comment]
Ah yes, I wasn't aware of this behaviour. This shouldn't be too hard to support.

**Comment by baldurk** [comment]
Based on a toy/simple example I wrote, I believe that should now work correctly. If you have any test cases that run into this please check it on the next nightly or build yourself, since I might have missed some edge case handling or similar. Otherwise I'll close this issue after the next stable release.

**Comment by timon37** [comment]
Sorry it took so long but I was busy and running into various other issues (both related and unrelated to renderdoc).

This one seems to be fixed now:)
