### ISSUE TITLE
how to replay a rdc file without extra API calls

### ISSUE THREAD

**Issue by waitlessJ** [baldurk/renderdoc#2953]
## Description

I want to replay a .rdc file without extrac API calls which my own APP do not have (except the necessary ones such as Device init/ Set pipelinestate).

I try to replay by click the Start Replay Loop in UI, Howerver, I found so many extra API calls has been called for the sake of UI's feature. I mean, extra buffers even shaders are created, which I do not want to. I try the in-applincation API, it do the same thing.

Besides, I notice that RenderDoc Create swapchain at the end of the capture rather than at the beginning , which my on application does, and the SwapChainDesc is a little different from mine. I look at the rdc file, and I do not find SwapChainDesc at all.

So I wonder how to replay a rdc file without extra API calls?
Should I dump SwapChainDesc to meet this end?

## Environment

* RenderDoc version: V1.25
* Operating System: Windows
* Graphics API: DX 11.1

**Comment by baldurk** [comment]
This is implicit to how RenderDoc works, there is no intention of replaying purely a 1:1 list of API calls. If you want a tool for that which only replays API calls with nothing else, [apitrace](https://github.com/apitrace/apitrace) is likely what you want to use.
