### ISSUE TITLE
glClearTex(Sub)?Image operations in GL do not consider half-float fill data formats.

### ISSUE THREAD

**Issue by graphitemaster** [baldurk/renderdoc#2956]
## Description

The `glClearTexImage` and `glClearTexSubImage` commands within RenderDoc do not handle `GL_HALF_FLOAT` as a data type format for the constant fill pixel value given by pointer to the commands. The handling code within RenderDoc thus only copies the least-significant byte of the fill value (treating it as a byte, rather than two bytes).

## Steps to reproduce

```c
u16 clear_data = 0xAABB;
glClearTexImage(texture, 0, GL_RED, GL_HALF_FLOAT, &clear_data);
```

Here we just write the constant pattern `0xAABB` as a half-float, i.e: `-0.0526` into `texture`. RenderDoc will only write and see `0xBB` for the underlying half-float texture.

The functions here:
<https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/gl/wrappers/gl_draw_funcs.cpp#L4590>
<https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/gl/wrappers/gl_draw_funcs.cpp#L4590>

Do not not handle `type` of `GL_HALF_FLOAT`, as a result `s` stays `1` and `memcpy` only copies the least-significant byte of the fill value.

It should be noted that `GL_UNSIGNED_SHORT` works, however `glClearTexImage` and `glClearTexSubImage` are defined to convert the data given by `fill` to the underlying texture format when the types aren't the same. This means there's no way to specify a half-float value as an unsigned short and clear the texture with it since that value will be converted to half-float instead.

## Environment

* RenderDoc version: Multiple
* Operating System: Windows 10, Windows 11, and ArchLinux
* Graphics API: OpenGL 4.5 and OpenGL 4.6 (Core Profile)

**Comment by baldurk** [comment]
That commit should add in the necessary handling, treating it similarly as a 2-byte value.
