### ISSUE TITLE
D3D11: "Error debugging pixel" during problematic shader

### ISSUE THREAD

**Issue by null77** [baldurk/renderdoc#296]
I'm trying to debug a problem with a simple shader program involving multisample stencil resolve in D3D11. It's not clear to me if this is an expected error or something that's not working right in renderdoc. I've attached the capture log.

[error_debugging_pixel.zip](https://github.com/baldurk/renderdoc/files/348357/error_debugging_pixel.zip)

To repro:
1. open the log, scroll down to the line starting with "gl::BlitFramebuffer"
2. expand this line, and navigate to the Draw(6) command
3. click on texture viewer, and click debug on any pixel
4. go to the pixel history view and right click, debug pixel (x,y) at event 116
5. a message box pops up with the error.

I tried looking at this very briefly and it appears to be that an 'initialBuf' is empty after a call to 'm_WrappedDevice->ReplayLog'. Not sure on how to diagnose this further, so help would be appreciated. I found this problem when implementing ES3 multisample depth-stencil resolve in ANGLE/D3D11.

**Comment by baldurk** [comment]
It looks like the reason the debugging failed was also connected to the problem you were debugging (maybe). There's a call to OMSetBlendState() that sets the sample mask to 0, which effectively means no samples will ever render (the default is typically 0xFFFFFFFF, although anything with the first N bits will work for Nx multisampling).

I've fixed a couple of bugs in renderdoc that obscured this - the pipeline state was showing a default blend factor and sample mask if there was no state bound, which is wrong, and the pixel history wasn't catching this which it does now:

![image](https://cloud.githubusercontent.com/assets/661798/16739722/c89b94c8-479b-11e6-9e89-cfab3b0c1fde.png)

**Comment by null77** [comment]
Awesome, thank you Baldur. I did indeed figure out the bug earlier today, and the additions you mention above will help me or others in a similar situation in the future. Feel free to close this out.
