### ISSUE TITLE
RenderDoc crashes when loading a Vulkan capture

### ISSUE THREAD

**Issue by Alihene222** [baldurk/renderdoc#2960]
## Description

After loading a capture of my Vulkan program, RenderDoc crashes with a segmentation fault. Running it through GDB produced the following output: https://pastebin.com/wWpxnkAd

## Steps to reproduce

- Run RenderDoc
- Run this program: 
[volcano.zip](https://github.com/baldurk/renderdoc/files/11772451/volcano.zip) (working directory is just `volcano`)
- Capture a frame
- Close the program

## Environment

* RenderDoc version: 1.27: https://github.com/baldurk/renderdoc/tree/367d55d88d332be1f1a40ff840166b583d483faa (built from source)
* Operating System: Ubuntu 22.04 LTS
* Graphics API: Vulkan 1.0
* GPU: Mesa Intel® HD Graphics 4000 (IVB GT2)
* CPU: Intel® Core™ i5-3340M CPU @ 2.70GHz × 4

**Comment by baldurk** [comment]
I'm able to capture this program fine, including opening the capture you sent (with some slight modifications for compatibility).

I notice you are running on an ivy bridge GPU, which does not properly support vulkan. Does this reproduce on a GPU that does support at least vulkan 1.0?

**Comment by Alihene222** [comment]
Unfortunately, I do not have access to any GPUs that have full Vulkan support.
As for Vulkan support on this current GPU, I think my `vulkaninfo` output may also be of use: 
[vulkaninfo.txt](https://github.com/baldurk/renderdoc/files/11773295/vulkaninfo.txt)
Also, I'm not sure if I set up renderdoc correctly from source. When I opened it for the first time after building from source, I got the `Warning: Vulkan capture is not configured` message. I clicked on it however it prompted me with `There is an unfixable problem with your vulkan layer configuration` and said that the problem was in `/usr/share/vulkan/implicit_layer.d/renderdoc_capture.json`. I went to that file and changed `layer.library_path` to the `librenderdoc.so` file that was produced from building from source, and after that it seemed to work. I'm not sure if this was the correct way to fix it.

**Comment by baldurk** [comment]
Unless this can be reproduced on a GPU with actual vulkan support I suspect this is a limitation of the GPU, and not a RenderDoc bug. If you are able to reproduce it on a proper GPU please open a new issue.

If you have a json in /usr/share that means you installed a distribution package. I do not provide any support for distribution packages here, and I do not recommend mixing and matching a source build with a distro build as it may break in unexpected ways. You should completely delete the distribution build and then run the source built version of RenderDoc.
