### ISSUE TITLE
RenderDoc causes Godot 4 to crash after calling vkCreateDevice

### ISSUE THREAD

**Issue by ctkerns** [baldurk/renderdoc#2961]
## Description

RenderDoc crashes when calling Godot method [RenderingServer.create_local_rendering_device()](https://docs.godotengine.org/en/stable/classes/class_renderingserver.html#class-renderingserver-method-create-local-rendering-device)  
The C++ source [here](https://github.com/godotengine/godot/blob/a83eb16fba5bb3da086b41cbd79e6f95b09eb8ee/servers/rendering_server.cpp#LL1481C39-L1481C39)   

Here is what Godot says when it crashes:  
USER ERROR: Condition "err" is true. Returning: RID()  
at: local_device_create (drivers/vulkan/vulkan_context.cpp:2576) [link](https://github.com/godotengine/godot/blob/a83eb16fba5bb3da086b41cbd79e6f95b09eb8ee/drivers/vulkan/vulkan_context.cpp#LL2543C43-L2543C43)  

So Vulkan is now returning an error when vkCreateDevice is called. When run without RenderDoc, there is no error. It would be informative to know which error this is, but Godot fails to log this for some reason.

I have also reported this issue in Godot:  
https://github.com/godotengine/godot/issues/76189  
Another developer noted that RenderDoc crashes in Godot 4 in general.

## Steps to reproduce

Download the following minimal Godot project:  
[RenderDoc.zip](https://github.com/baldurk/renderdoc/files/11776754/RenderDoc.zip)
Launch RenderDoc with Godot 4 executable path provided. Also provide path to the Godot project under working directory.  
It will crash shortly after launch.  

Error log:
[0rY8.zip](https://github.com/baldurk/renderdoc/files/11776742/0rY8.zip)

## Environment

* RenderDoc version: v1.26
* Operating System: Windows 10
* Graphics API: Vulkan

Intel UHD Graphics
Vulkan version 1.2.131

**Comment by baldurk** [comment]
I can't reproduce this. I downloaded https://github.com/godotengine/godot/releases/download/4.0.3-stable/Godot_v4.0.3-stable_win64.exe.zip and ran the Godot_v4.0.3-stable_win64.exe executable from RenderDoc, with the path to the project.godot and working directory set to the folder, and it launched and captured correctly for me.

If any of those steps are incorrect please let me know, but otherwise have you tried testing this on a different machine in case it's something system-specific?

**Comment by ctkerns** [comment]
I was able to borrow another device and got similar results.
[godot.log](https://github.com/baldurk/renderdoc/files/11779605/godot.log)
[qVf54.zip](https://github.com/baldurk/renderdoc/files/11779606/qVf54.zip)

Windows 11
Intel Iris Xe Graphics
Vulkan 1.3.224

Also, one of the Godot devs was able to reproduce this as well in the issue page I originally linked.

Double check you are launching Godot correctly by doing the following. Godot keeps an error log which should be in (User Directory)/Appdata/Roaming/Godot/app_user_data/RenderDoc/logs/. When correctly run, you should find a log there even if there was no crash because I printed some messages to the console. It should say "trying it\n did it". If that message is not there, then something went wrong.

When I set the working directory, I set it to the path of the folder that contains project.godot. I don't include project.godot in the path; if you do this, it will start Godot normally without running the project. I should have been more specific about that.

**Comment by baldurk** [comment]
OK I was able to reproduce it now. I don't know anything about Godot so I thought I had to pass the project file not the directory as the argument.

It looks like your application is creating multiple devices within a single instance. This is legal but something I do not support within RenderDoc and have no plans to support in future.
