### ISSUE TITLE
Unable to debug Android device (Vulkan 1.1.128) with only bufferDeviceAddress support

### ISSUE THREAD

**Issue by Alegruz** [baldurk/renderdoc#2963]
## Description

I am currently working on Android vulkan on Samsung S22 Ultra where Adreno 730 supports Vulkan 1.1.128. The device **supports the extension `VK_KHR_buffer_device_address` but with only `bufferDeviceAddress` set true**, and `bufferDeviceAddressCaptureReplay` and `bufferDeviceAddressMultiDevice` set to false. The application runs fine without RenderDoc, however **it crashes when create VkDevice giving `VK_ERROR_FEATURE_NOT_PRESENT`**. The same code runs fine with/without RenderDoc in Samsung S23 Ultra which supports Vulkan 1.3.

Is this an intentional choice? or is this simply a bug?

## Steps to reproduce

* Device that supports maximum Vulkan API version 1.1.128
* VK_KHR_buffer_device_address extension enabled
* `VkPhysicalDeviceBufferDeviceAddressFeaturesKHR`'s `bufferDeviceAddress` is true while others, `bufferDeviceAddressCaptureReplay` and `bufferDeviceAddressMultiDevice` are false

Samsung S22 Ultra is my actual reproducing device

1. Run RenderDoc
2. Set replay context to the android device
3. Launch application
4. vkCreateDevice fails with `VK_ERROR_FEATURE_NOT_PRESENT`

The code is straightforward (apologies for not posting the original code due to copyright issues)

```cpp
// create a linked list of features including VkPhysicalDeviceBufferDeviceAddressFeaturesKHR

// Make VkDeviceCreateInfo.pNext point to the linked list of features (starts with VkPhysicalDeviceFeatures2)

// include VK_KHR_buffer_device_address extension to `VkDeviceCreateInfo.ppEnabledExtensionNames`.

// vkCreateDevice <- returns VK_ERROR_FEATURE_NOT_PRESENT !!
```

## Environment

* RenderDoc version: 1.22
* Operating System: Android OS 13
* Graphics API: Vulkan 1.1.128
* GPU: Adreno 730
* GPU Driver Version: 512.615.0

**Comment by baldurk** [comment]
If you are unconditionally enabling an extension and a feature without querying to see if they are supported, then the error from vkCreateDevice is expected. You should always use `vkEnumerateDeviceExtensionProperties` first to check what extensions are available before enabling them.

If `bufferDeviceAddressCaptureReplay` is not available then buffer device address can't be supported and RenderDoc will remove the extension from the list of those available. Your application is responsible for checking that list before enabling anything.

**Comment by Alegruz** [comment]
The application only requires `bufferDeviceAddress`, and the extension is available from the enumeration. So I do not quite understood the part "If `bufferDeviceAddressCaptureReplay` is not available then buffer device address can't be supported". The feature is supported, but only `bufferDeviceAddress`. Do you mean that if the capture replay is not supported, then RenderDoc doesn't support the device?

**Comment by Alegruz** [comment]
> If you are unconditionally enabling an extension and a feature without querying to see if they are supported, then the error from vkCreateDevice is expected. You should always use `vkEnumerateDeviceExtensionProperties` first to check what extensions are available before enabling them.
> 
> If `bufferDeviceAddressCaptureReplay` is not available then buffer device address can't be supported and RenderDoc will remove the extension from the list of those available. Your application is responsible for checking that list before enabling anything.

@baldurk 
The application only requires bufferDeviceAddress, and the extension is available from the enumeration. So I do not quite understood the part "If bufferDeviceAddressCaptureReplay is not available then buffer device address can't be supported". The extension is supported, but only the bufferDeviceAddress feature is supported. Do you mean that if the capture replay is not supported, then RenderDoc doesn't support the device?

**Comment by baldurk** [comment]
Are you saying that when running under RenderDoc your application calls vkEnumerateDeviceExtensionProperties before vkCreateDevice and KHR_buffer_device_address is returned in the list of extensions? You didn't mention calling that function in your steps to reproduce so I wasn't sure. That should not be happening, but if it is then since this is Android that probably means the device is broken and is not properly calling into vulkan layers for functions as it should. That would mean RenderDoc could not remove support for the extension.

I would suggest that you double check that you are really calling vkEnumerateDeviceExtensionProperties every time correctly. If you are and KHR_buffer_device_address is reported even when running under RenderDoc, then as a workaround you could also manually check the bufferDeviceAddressCaptureReplay feature, and treat it as required. RenderDoc is a capture and replay debugger, and so without the capture and replay feature then buffer device address can't be supported.

**Comment by Alegruz** [comment]
> Are you saying that when running under RenderDoc your application calls vkEnumerateDeviceExtensionProperties before vkCreateDevice and KHR_buffer_device_address is returned in the list of extensions? You didn't mention calling that function in your steps to reproduce so I wasn't sure. That should not be happening, but if it is then since this is Android that probably means the device is broken and is not properly calling into vulkan layers for functions as it should. That would mean RenderDoc could not remove support for the extension.
> 
> I would suggest that you double check that you are really calling vkEnumerateDeviceExtensionProperties every time correctly. If you are and KHR_buffer_device_address is reported even when running under RenderDoc, then as a workaround you could also manually check the bufferDeviceAddressCaptureReplay feature, and treat it as required. RenderDoc is a capture and replay debugger, and so without the capture and replay feature then buffer device address can't be supported.

Okay this is what I've missed: I only checked that the extensions are available when launched without RenderDoc. Apparently, as you mentioned, when launched with RenderDoc, the extension is unavailable.

I would guess capturing on pre 2023 android devices is impossible with bufferDeviceAddress features ;(

Thank you for the help!
