### ISSUE TITLE
wglCreateContext cannot be hooked

### ISSUE THREAD

**Issue by POLO-huhu** [baldurk/renderdoc#2966]
## Description
I use this thought([https://github.com/baldurk/renderdoc/issues/2940](https://github.com/baldurk/renderdoc/issues/2940)), and copy renderdoc.dll into renderdoc1.dll and load two *.dll. I have deal some confliction like Instance ID because it is singleton pattern. On dx11, user define functions work well.

On WGL ,  it work not well. After debug, I find that WGL functions cannot be hooked like wglCreateContext function in renderdoc.dll. In reasonable, Hooked_GetProcAddress will return wglCreateContext _hooked function pointer, actually not.

## Steps to reproduce
Reproducing is complex. If you were interested in this, I will attach projection code.

## Environment

* RenderDoc version: v1.6
* Operating System: windows 10
* Graphics API: WGL

Thanks for your review.

**Comment by baldurk** [comment]
If you are making custom and unsupported modifications to the code and the RenderDoc application then of course you are welcome to experiment with this, but that is not a bug and it should not be reported as such.

Please only report bugs if you are using the application as normal and unmodified, in a supported way, and something goes wrong. If you are customising it for some other uses or making changes then you will need to investigate any problems yourself.

**Comment by POLO-huhu** [comment]
Thank you. BTW, renderdoc is wonderful.

**Comment by quadpixels** [comment]
I played around with this as well, [this](https://github.com/quadpixels/renderdoc/commit/bbbfe4c1c321ea34168f373dc152a179a0948f1d) is how I manage to get it working to some extent.

The keys to this issue are, in the replaying RenderDoc DLL file:
1) `wglCreateContextAttrib` has to be hooked before `CreateReplayDevice` is called
2) `gl*` functions need to be hooked before any GL functions are called
