### ISSUE TITLE
The global layer for Vulkan is not found when try to launch android app

### ISSUE THREAD

**Issue by iamunicorn1993** [baldurk/renderdoc#2969]
## Description

I was trying to launch my android app (Android 13) with RenderDoc. 

The RenderDoc was installed successfully on my android device, but when I choose my native activity (use Vulkan API) and clicked "launch", it crashed immediately and RenderDoc gave me an error
![d6a544f3-11e6-4bc5-98a7-3ac55b7745c7](https://github.com/baldurk/renderdoc/assets/131149289/903c3dc9-beae-47d6-ab75-b199bed29705)

The android logcat showed that the Vulkan just search the global layer at my own app path:
06-26 15:54:10.797 12041 14409 D vulkan  : searching for layers in '/data/app/~~H1VuAyZzCtSk0oyWURcgeA==/com.XXX.myApp.debug-nouCprVHOIstoe6uQe1rsQ==/lib/arm64'
06-26 15:54:10.797 12041 14409 D vulkan  : searching for layers in '/data/app/~~H1VuAyZzCtSk0oyWURcgeA==/com.XXX.myApp.debug-nouCprVHOIstoe6uQe1rsQ==/base.apk!/lib/arm64-v8a'
06-26 15:54:10.802 12041 14409 D vulkan  : added global layer 'VK_LAYER_KHRONOS_validation' from library '/data/app/~~H1VuAyZzCtSk0oyWURcgeA==/com.XXX.myApp.debug-nouCprVHOIstoe6uQe1rsQ==/base.apk!/lib/arm64-v8a/libVkLayer_khronos_validation.so'

My app crashed when call vkCreateInstance, and the error code is VK_ERROR_LAYER_NOT_PRESENT.
I guess it just couldn't find the dynamic library for VK_LAYER_RENDERDOC_Capture layer.

I also tried on a device with Android 11, then all goes well, I can successfully capture frame.
The logcat said:
06-26 15:43:53.912 11738 22323 D vulkan  : searching for layers in '/data/user/0/com.XXX.myApp.debug'
06-26 15:43:53.912 11738 22323 D vulkan  : searching for layers in '/data/app/~~2mmVLwWPoQBcdfdoYayQCA==/org.renderdoc.renderdoccmd.arm64-Y9ZOHl8qMmXmm25J5mz--Q==/lib/arm64'
06-26 15:43:53.912 11738 22323 D vulkan  : added global layer 'VK_LAYER_RENDERDOC_Capture' from library '/data/app/~~2mmVLwWPoQBcdfdoYayQCA==/org.renderdoc.renderdoccmd.arm64-Y9ZOHl8qMmXmm25J5mz--Q==/lib/arm64/libVkLayer_GLES_RenderDoc.so'
06-26 15:43:53.913 11738 22323 D vulkan  : searching for layers in '/data/app/~~2mmVLwWPoQBcdfdoYayQCA==/org.renderdoc.renderdoccmd.arm64-Y9ZOHl8qMmXmm25J5mz--Q==/base.apk!/lib/arm64-v8a'
06-26 15:43:53.913 11738 22323 D vulkan  : searching for layers in '/data/app/~~SO_B5QQBb0CaXpGKjzJH0g==/com.XXX.myApp.debug-gjtDo0ktPqY-TJDf4DtB5A==/lib/arm64'
06-26 15:43:53.913 11738 22323 D vulkan  : searching for layers in '/data/app/~~SO_B5QQBb0CaXpGKjzJH0g==/com.XXX.myApp.debug-gjtDo0ktPqY-TJDf4DtB5A==/base.apk!/lib/arm64-v8a'
06-26 15:43:53.916 11738 22323 D vulkan  : added global layer 'VK_LAYER_KHRONOS_validation' from library '/data/app/~~SO_B5QQBb0CaXpGKjzJH0g==/com.XXX.myApp.debug-gjtDo0ktPqY-TJDf4DtB5A==/base.apk!/lib/arm64-v8a/libVkLayer_khronos_validation.so'

So maybe the layer search path is wrong on Android 13 ?

## Steps to reproduce

1. Write a native activity app with Vulkan API
2. Install the app on an android device with Android 13
3. In RenderDoc, connect the target device and choose the target activity in "Executable Path"
4. Click "Launch" button

## Environment

* RenderDoc version: 1.22 or 1.27
* Operating System: Windows 10 (Client), Android 13 (Host)
* Graphics API: Vulkan (in Android NDK 21.3.6528147)

**Comment by Zorro666** [comment]
HI there,

Currently do not have access to an Android 13 device to investigate this issue.

Is it possible for you to try on a different Android 13 device in case it is a vendor and device specific issue.

Thank you in advance

**Comment by iamunicorn1993** [comment]
> HI there,
> 
> Currently do not have access to an Android 13 device to investigate this issue.
> 
> Is it possible for you to try on a different Android 13 device in case it is a vendor and device specific issue.
> 
> Thank you in advance

Sorry, but I have just one Android 13 device which is OnePlus 9 Pro now. *-*||

**Comment by unityyang** [comment]
I have the same problem, too. My device is just OnePlus 9 Pro with Android 13. 
Graphics api: OpenGL
RenderDoc version: 1.27

**Comment by Zorro666** [comment]
Hi there,

Locally RenderDoc capture and replay has been tested and verified with GLES and Vulkan API on these Android 13 devices: Samsung S20 & S21, OnePlus 8T. 

Perhaps your device requires some extra setup or a device-specific setting to allow support graphics debugging and RenderDoc capture & replay, or perhaps that particular device does not support graphics debugging.

Perhaps you would be able test using our test APKs to rule out an APK specific problem.
[jake-kart-vk.apk](https://renderdoc.org/jake-kart-vk.apk)
[jake-runner-gles3.apk](https://renderdoc.org/jake-runner-gles3.apk)

Thanks in advance

**Comment by unityyang** [comment]
> Hi there,
> 
> Locally RenderDoc capture and replay has been tested and verified with GLES and Vulkan API on these Android 13 devices: Samsung S20 & S21, OnePlus 8T.
> 
> Perhaps your device requires some extra setup or a device-specific setting to allow support graphics debugging and RenderDoc capture & replay, or perhaps that particular device does not support graphics debugging.
> 
> Perhaps you would be able test using our test APKs to rule out an APK specific problem. [jake-kart-vk.apk](https://renderdoc.org/jake-kart-vk.apk) [jake-runner-gles3.apk](https://renderdoc.org/jake-runner-gles3.apk)
> 
> Thanks in advance

Thank you very much. Bug it seems doesn't work on my OnePlus9 Pro.

**Comment by Zorro666** [comment]
Thank you for testing. Can I check one thing, did both APKs (GLES and Vulkan) fail to work for you on the OnePlus9 Pro?

**Comment by unityyang** [comment]
> Thank you for testing. Can I check one thing, did both APKs (GLES and Vulkan) fail to work for you on the OnePlus9 Pro?

Yes, I tested both APKs. Both failed. The vulkan game will render error with a magenta screen when launched by renderdoc.

**Comment by LeavesInAutumn** [comment]
> Hi there,
> 
> Locally RenderDoc capture and replay has been tested and verified with GLES and Vulkan API on these Android 13 devices: Samsung S20 & S21, OnePlus 8T.
> 
> Perhaps your device requires some extra setup or a device-specific setting to allow support graphics debugging and RenderDoc capture & replay, or perhaps that particular device does not support graphics debugging.
> 
> Perhaps you would be able test using our test APKs to rule out an APK specific problem. [jake-kart-vk.apk](https://renderdoc.org/jake-kart-vk.apk) [jake-runner-gles3.apk](https://renderdoc.org/jake-runner-gles3.apk)
> 
> Thanks in advance

Thanks! I've tested both APKs with RenderDoc 1.22 on three different physical devices :
1. OnePlus 9 LE2110 with OxygenOS 11.2.9.9.LE25AA (Android 11). Both APKs worked well, I can capture frames normally.
2. OnePlus 9 LE2110 with ColorOS 13.0 (Android 13). Both APKs failed, RenderDoc reported the same error as I issued
3. OnePlus Ace2 PHK110 with ColorOS 13.0 (Android 13). Both APKs failed, RenderDoc reported the same error as I issued

So I guess the ColorOS 13.0 has some modifications which cause this problem ?

**Comment by Zorro666** [comment]
Thank you for the thorough testing.
The results of the testing look to show a specific problem with ColorOS 13.0 (the test Vulkan APK showing magenta when running means Vulkan didn't load correctly). 

I do not know any details about that OS, perhaps it has non-standard options or settings that need to be set to enable Vulkan debugging (perhaps an internet search might turn up something).

I am going to close this issue as there does not appear to be anything to fix or change in RenderDoc.

If you get more information or details that demonstrate a problem with RenderDoc please get back in touch.

**Comment by SupinePandora43** [comment]
Happens to me too on `Redmi Note 9 Pro`

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
