### ISSUE TITLE
Incorrect dimension arguments of the ExecuteIndirect method shown in the event browser

### ISSUE THREAD

**Issue by tiruns** [baldurk/renderdoc#2970]
## Description

The dimension arguments are read from the `argBuf` resource, which is accessed via the [Map](https://github.com/baldurk/renderdoc/blob/c328c3fdf7fb3706e48a66572a6f926ba8bdae92/renderdoc/driver/d3d12/d3d12_command_list_wrap.cpp#L3640) method. However, (due to lack of synchronization?), it takes some time for the Map action to take effect, and before that the contents read from the pointer are all zeros. Therefore, the values of [dispatchDimension](https://github.com/baldurk/renderdoc/blob/c328c3fdf7fb3706e48a66572a6f926ba8bdae92/renderdoc/driver/d3d12/d3d12_command_list_wrap.cpp#L3794) can be all zeros, which lead to incorrect results in the event browser.

Some workarounds that might help:

- Sleep for several milliseconds before reading.
- Use [D3D12DebugManager::GetBufferData](https://github.com/baldurk/renderdoc/blob/c328c3fdf7fb3706e48a66572a6f926ba8bdae92/renderdoc/driver/d3d12/d3d12_debug.h#L139) instead of Map.
 
I didn't find any content related to thread synchronization on the documentation of `ID3D12Resource::Map`, but the synchronization operations in the `D3D12DebugManager::GetBufferData` do solve the problem.

## Steps to reproduce

I've sent you the capture file and a screenshot via email.

Diff of my modification:
```
@@ -3637,7 +3637,12 @@ void WrappedID3D12GraphicsCommandList::PatchExecuteIndirect(BakedCmdListInfo &in

   D3D12_RANGE range = {0, D3D12CommandData::m_IndirectSize};
   byte *mapPtr = NULL;
-  m_pDevice->CheckHRESULT(exec.argBuf->Map(0, &range, (void **)&mapPtr));
+  //m_pDevice->CheckHRESULT(exec.argBuf->Map(0, &range, (void **)&mapPtr));
+
+  bytebuf argBufBytes;
+  m_pDevice->GetDebugManager()->GetBufferData(exec.argBuf, range.Begin, range.End - range.Begin,
+                                              argBufBytes);
+  mapPtr = argBufBytes.data();

   if(m_pDevice->HasFatalError())
     return;
```

## Environment

* RenderDoc version: 1.27
* Operating System: Windows 11 (22H2)
* Graphics API: D3D12
* GPU: NVIDIA GeForce RTX 3080
* Driver Version: 536.23

**Comment by Zorro666** [comment]
Thank you for reporting the problem and suggesting a proposed fix.
I think there is a slightly different fix which you can try if that is helpful for you.

```
renderdoc/driver/d3d12/d3d12_command_queue_wrap.cpp
@@ -504,8 +504,8 @@ bool WrappedID3D12CommandQueue::Serialise_ExecuteCommandLists(SerialiserType &se

           for(size_t c = 1; c < info.crackedLists.size(); c++)
           {
-            // ensure all work on all queues has finished
-            m_pDevice->GPUSyncAllQueues();
+           // ensure all GPU work has finished
+           m_pDevice->GPUSync();

             if(m_pDevice->HasFatalError())
               return false;

```

**Comment by tiruns** [comment]
Thank you for your suggestion and I think it's just the solution that I want.
I'll close the issue since my problem is resolved.
