### ISSUE TITLE
Support for applications that use multiple VkDevices

### ISSUE THREAD

**Issue by ngladitz** [baldurk/renderdoc#2974]
## Description

I've got a multithreaded application which creates a VkDevice which I use to load images, run compute shaders and render to framebuffer attached images.

Now I also have a Qt6-UI which is set up to explicitly use the Vulkan rendering backend.
It also creates its own VkDevice (for the same physical device).

I thought about sharing the VkDevice with Qt but this seems difficult since I can synchronize access to the VkQueue when I use it on my own but I don't think I have control over how Qt synchronizes access to the VkQueue (and the device might only have one).

So now I instead export the memory from my framebuffer attached images and import them into memory objects that Qt can use for rendering with its own logical device.

Now I still would like to be able to debug my own code with RenderDoc but when Qt tries to create its VkDevice this fails with:
```
vkDebug: RDOC: 1: RenderDoc does not support multiple simultaneous logical devices.
```

So what I suppose I would like is support for multiple VkDevices.

At least for the same physical device (if that makes it at all easier).

I don't know if that would be easier to achieve but I'd also be quite happy if RenderDoc were to only capture the first device (ignoring the rest / allowing vkCreateDevice to succeed); or maybe the one matching a configurable index based on creation order.

## Environment

* RenderDoc version: v1.28 (5f88b303b56f70b50e92735d572544fe63058a9a)
* Operating System: Ubuntu 23.04
* Graphics API: Vulkan

**Comment by baldurk** [comment]
Hi, this is not something I plan to ever support in RenderDoc, the complexity of the necessary refactoring and rearchitecting is not justified by the benefit that it would bring to support. If you are using Qt for vulkan then it sounds like Qt itself needs to offer methods of synchronising with its internal use, that's the only feasible way Qt can expose some kind of shared vulkan use.

You may be able to create an entirely separate instance, in principle RenderDoc should support multiple instances, but this is very rarely tested as primarily component sharing of Vulkan happens within the same VkDevice.
