### ISSUE TITLE
descriptor set x binding x is not bound, when performing ImageFetch operation

### ISSUE THREAD

**Issue by gjaegy** [baldurk/renderdoc#2975]
## Description

I'm trying to debug a vertex shader (vulkan) that load some float4 from a float4 buffer. 

When debugging the shader, the value loaded from this buffer is (0.0, 0.0, 0.0, 1.0) which is not the value contained in the buffer.

Surprisingly, I can correctly display the content of the buffer in RenderDoc, and check the value at the given offset, it looks correct (and different from the Load()-ed value displayed by the debugger). 

A weird thing is that I get some errors in the warning and error windows:

<img width="674" alt="image" src="https://github.com/baldurk/renderdoc/assets/900305/5ad787da-5db7-4d25-a837-38b708567f71">

This error is likely incorrect because the rendering is correct, and the buffer content can be correctly displayed in RenderDoc.

There might be some link with the fact that we use a fully bindless approach.

## Steps to reproduce

I've sent a capture by email.

## Environment

* RenderDoc version: 1.27 or latest nightly (3/7)
* Operating System: Windows 11
* Graphics API: Vulkan

Tried with different NV GPUs, same problem occurs.

**Comment by Zorro666** [comment]
Hi there

Thank you for the report and capture.

Currently working to get a system setup (Windows+ nVidia GPU) to be able to load and debug the capture.

It might take a couple of weeks before can investigate this issue.

Thank you in advance

**Comment by gjaegy** [comment]
Hi Jake,

Thanks for your answer. I'm afraid I don't have any AMD GPU here, otherwise I could have recorded a new capture with that other GPU... 

Let me know if you need anything else.

**Comment by Zorro666** [comment]
Hi

Quick update to say have reproduced this locally now.

**Comment by Zorro666** [comment]
Hi there,

The issue was related to shader debugging with arrays of buffers.

The fix will be available in the [nightly builds](https://renderdoc.org/builds) dated after 20th July 2023.

Thanks

**Comment by gjaegy** [comment]
Thanks a lot Jake, really appreciated 👍

________________________________

**Comment by DragonJoker** [comment]
I can confirm that it now works with latest nightly build.
Thanks a lot !
