### ISSUE TITLE
"Capture Child Processes" does not automatically open child process's capture when the parent process outlives its child

### ISSUE THREAD

**Issue by w-pearson** [baldurk/renderdoc#2985]
## Description

If a capture is made in a child process, and then that child process closes, and then the parent process closes, the capture made by the child process is not automatically opened (and in fact, it seems to be lost entirely). It is only opened if the child process is double-clicked in RenderDoc itself before it closes.

This also occurs (at least on my machine) when both processes exit at the same time, but I'm not completely sure if that is deterministic.

The [documentation for the capture connection window](https://renderdoc.org/docs/window/capture_connection.html#child-processes) says:

> If a process exits, instead of just closing the connection window if there have been no captures, instead RenderDoc looks at the child processes - if there is only one child process, it assume that process must be of interest and immediately switches to tracking that process. If there are more than one child process open, the capture connection window will stay open to give you a chance to double click on those child processes to open a new connection window.

This is a slightly different case (a parent closing with still live children), but it seems like both should behave the same.

## Steps to reproduce

This can be most easily reproduced by hacking up the renderdoc demos to spawn a subprocess:

```patch
diff --git a/util/test/demos/main.cpp b/util/test/demos/main.cpp
index b0d494d23..7ac0b00d9 100644
--- a/util/test/demos/main.cpp
+++ b/util/test/demos/main.cpp
@@ -662,6 +662,24 @@ Usage: %s Test_Name [test_options]
     }
 
     NuklearShutdown();
+
+    CHAR filename[MAX_PATH];
+    GetModuleFileNameA(NULL, filename, MAX_PATH);
+
+    CHAR commandline[MAX_PATH * 2];
+    snprintf(commandline, sizeof(commandline), "%s %s", filename, testchoice.c_str());
+
+    STARTUPINFOA info = {sizeof(info)};
+    PROCESS_INFORMATION processInfo;
+    if(CreateProcessA(filename, commandline, NULL, NULL, TRUE, 0, NULL, NULL, &info, &processInfo))
+    {
+      WaitForSingleObject(processInfo.hProcess, INFINITE);
+      CloseHandle(processInfo.hProcess);
+      CloseHandle(processInfo.hThread);
+    }
+
+    Sleep(2000);    // To ensure child process exits much before the parent - may not be required
+    return 0;
   }
 
   if(testchoice.empty())
```
1. Open RenderDoc
2. Launch the demos without providing a command-line argument, so that the demo chooser window appears
3. Choose a demo (e.g. `VK_Simple_Triangle`)
4. Run that demo
5. Make a capture in the demo window that appears by pressing F12
6. Close the demo window
7. Observe that the capture connection tab in RenderDoc closes without opening the capture

Note that if the `WaitForSingleObject` call is removed, then the parent process does exit before the child process, and everything behaves correctly (and as documented). Additionally, if multiple captures are made, they are still lost (no capture connection tab for that subprocess appears to choose one of them).

## Environment

* RenderDoc version: v1.27 (both release and self-built)
* Operating System: Windows 10
* Graphics API: All (based on the Simple_Triangle demos)

**Comment by w-pearson** [comment]
My understanding of why this happens is that `LiveCapture::connectionClosed()` is responsible for [opening the child process](https://github.com/baldurk/renderdoc/blob/d4c9de7f8169940fc3ecafe853d5821e97ee9971/qrenderdoc/Windows/Dialogs/LiveCapture.cpp#L1218-L1228) and also [auto-opening the capture](https://github.com/baldurk/renderdoc/blob/d4c9de7f8169940fc3ecafe853d5821e97ee9971/qrenderdoc/Windows/Dialogs/LiveCapture.cpp#L1205-L1216), but `LiveCapture::childUpdate` [removes child processes on them closing](https://github.com/baldurk/renderdoc/blob/d4c9de7f8169940fc3ecafe853d5821e97ee9971/qrenderdoc/Windows/Dialogs/LiveCapture.cpp#L461-L493) without checking if they have any captures. However, I don't know if there's a good way of doing that, as `childUpdate` only knows the relevant PIDs and my impression is that you need to talk to the process to get its capture list (which isn't possible after it has closed).

**Comment by baldurk** [comment]
This is not a bug as it is working as intended for this behaviour. If you have a parent-child process tree you should navigate to the child process that's doing the captures in the UI using the process selection before making any captures, or at minimum before you close the child process, if you want to open them up directly through the UI.

**Comment by w-pearson** [comment]
> if you want to open them up directly through the UI

Is there another way to open them up? I don't know where the captures are getting saved if they don't show up in the UI, which is part of what makes this behavior so confusing to me; the app says the capture is saved, but I don't know where to find it.

(I also initially ran into this with a fullscreen app, which made it a lot harder to notice what was going on.)

**Comment by baldurk** [comment]
The directory where captures are saved temporarily is specified in the settings menu, by default it's `%TEMP%\RenderDoc`. You can also override this in your application using the [in-application API](https://renderdoc.org/docs/in_application_api.html). Note that if you're not going through the UI nothing will delete those captures since there is no 'owner' of them, so you will need to delete them yourself when you are done with them.

**Comment by w-pearson** [comment]
Thanks. It seems like the capture from the subprocess gets left in there, and isn't automatically cleaned up (which is good (if renderdoc still new to clean up that capture but didn't show it, that'd be really weird), although it did mean I had several leftover captures in that directory).

For a bit of extra context, I originally ran into this while trying to capture an unreal engine demo sent by a co-worker. For me, it wouldn't automatically load the capture upon closing the demo, but for my co-worker it would; for me, `UE52_FSR.exe` stayed open for a bit longer than its child `UE52_FSR-Win64-Test.exe`. I'm not sure if they exited at the same time for my co-worker or how it was behaving, unfortunately; I don't know too much about what their set up was.
