### ISSUE TITLE
GLES3.2/2.0 App debugging fails due to missing extensions

### ISSUE THREAD

**Issue by vaxerski** [baldurk/renderdoc#2988]
## Description

Hey, I am trying to profile my wayland compositor, Hyprland, running on GLES3.2 and wlroots. However, when I try to launch it (or any other wlroots-based compositor) it complains about `GL_EXT_unpack_subimage not supported`. Manually removing the check leads to a hard crash a bit later when allocating a swapchain.

## Steps to reproduce

 - Plug in [sway](https://github.com/swaywm/sway) or [Hyprland](https://github.com/hyprwm/Hyprland) into renderdoc
 - Hit launch
 - Yikes:
```
00:00:00.041 [wlr] [EGL] command: eglGetConfigAttrib, error: EGL_BAD_CONFIG (0x3005), message: "eglGetConfigAttrib"
00:00:00.041 [wlr] [EGL] command: eglGetConfigAttrib, error: EGL_BAD_CONFIG (0x3005), message: "eglGetConfigAttrib"
00:00:00.041 [wlr] [EGL] command: eglGetConfigAttrib, error: EGL_BAD_CONFIG (0x3005), message: "eglGetConfigAttrib"
00:00:00.041 [wlr] [EGL] command: eglGetConfigAttrib, error: EGL_BAD_CONFIG (0x3005), message: "eglGetConfigAttrib"
00:00:00.041 [wlr] [EGL] command: eglGetConfigAttrib, error: EGL_BAD_CONFIG (0x3005), message: "eglGetConfigAttrib"
00:00:00.041 [wlr] [EGL] command: eglGetConfigAttrib, error: EGL_BAD_CONFIG (0x3005), message: "eglGetConfigAttrib"
00:00:00.044 [wlr] [render/gles2/renderer.c:860] GL_EXT_unpack_subimage not supported
00:00:00.044 [wlr] [render/gles2/renderer.c:810] Failed to create GLES2 renderer
00:00:00.046 [wlr] [render/wlr_renderer.c:315] Could not initialize renderer
00:00:00.046 [sway/server.c:87] Failed to create renderer
```

## Environment

* RenderDoc version: 1.27
* Operating System: Arch Linux
* Graphics API: GLES2 / GLES3.2

AMD GPU if that helps.

**Comment by baldurk** [comment]
RenderDoc does not support Wayland, see #853 . Also note that an extension which isn't supported is not a bug, as applications are expected to check the supported extension list and either fallback or exit depending on whether they can handle the extension not being present. Adding a new extension would be a feature request, but in this case I presume the core issue is wayland support.
