### ISSUE TITLE
0/0 is 0 when debuging by source code in vulkan

### ISSUE THREAD

**Issue by King19931229** [baldurk/renderdoc#2993]
## Description

0/0 is 0 when debugging in vulkan compute shader, which is supposed to be NAN
## Steps to reproduce

If you write a code of shader that is c = a / b, where is a == 0 and b == 0 in glsl, by debugging in compute shader by the source code.
The result of c is 0, but it is supposed to be is NAN. The the actual result is also NAN that is different from the debugging.

![03](https://github.com/baldurk/renderdoc/assets/12392203/57eaca19-a4dd-49cb-b9c3-f235b6afc2c8)

## Environment

* RenderDoc version: v1.27
* Operating System: Win10
* Graphics API: Vulkan 1.3.243.0

**Comment by Zorro666** [comment]
Hi

This looks like unsigned integer division which according to the SPIRV spec is undefined when dividing by 0. I don't think NaN applies to integer division, it only applies to floating point arithmetic.

```
OpUDiv

Unsigned-integer division of Operand 1 divided by Operand 2.

Results are computed per component. Behaviour is undefined if Operand 2 is 0.
```
