### ISSUE TITLE
Do we have plan to support RISCV?

### ISSUE THREAD

**Issue by yuzibo** [baldurk/renderdoc#2999]
## Description

Do we have plan to support RISC-V for renderdoc?
I just noticed here and I think the project has great advantages to debug graphics issues.
As far as I know there many people focus on fixing graphics issues on real riscv64 hardware.
If possible please tell me and I can do something for here.

BTW, as a Debian riscv porter, there is a [good news](https://lists.debian.org/debian-riscv/2023/07/msg00053.html) to share with here.
And the renderdoc has not been packaged into Debian archive yet. I will do it.

## Environment

* RenderDoc version: v1.27
* Operating System: linux

**Comment by baldurk** [comment]
I'm not familiar with RISC-V but it looks like a hardware ISA? RenderDoc does not work directly with GPUs it works with graphics APIs. If there was a GPU that existed that used RISC-V and wanted to expose the ISA via RenderDoc's disassembly that could be supported if someone gave a pull request with the necessary implementation, but that's the only place a hardware ISA would be relevant.
