### ISSUE TITLE
texcoords are off on miplevels > 0

### ISSUE THREAD

**Issue by karyon** [baldurk/renderdoc#300]
an example: i open miplevel one of a 2048x2048 texture. the texcoords as shown in the `Hover` bar at the bottom range from (0, 1024) in the lower left corner to (1023, 2047) in the upper right corner. the x coordinate is correct, but i'd expect the y-coordinate to range from 0 to 1023 as well.

if i press the `Flip Y` button, the coordinates seem to be correct.

**Comment by baldurk** [comment]
Yes this was just a silly mistake, using the texture height to flip co-ordinates even for mips. Should be fixed now with this change.

**Comment by karyon** [comment]
the hover coordinate seems correct now, the right click coordinate not however :)

**Comment by baldurk** [comment]
My bad! I also noticed the normalised co-ordinates needed to be fixed for mips in both dimensions, not just vertically.

**Comment by karyon** [comment]
works as expected, thanks!
