### ISSUE TITLE
RENDERDOC_TextureType is zero

### ISSUE THREAD

**Issue by karyon** [baldurk/renderdoc#302]
I have a 2D RGBA32F texture bound as image. when using a custom shader that does `	color_out = vec4(float(RENDERDOC_TextureType == 0), 0.0, 0.0, 0.0);`, i get a red image. also, when reading from tex2D (which i think should be bound), i get no data, just zeroes.

(it's about the push buffer in the multiframesampling project)

i do get the warning `warning C7050: "RENDERDOC_TextureType" might be used before being initialized`, but assume that the define is set by renderdoc...? i have the definition set at the top of the shader. full shader code:

```
#version 420 core
uint RENDERDOC_SelectedMip; // selected mip in UI

uvec4 RENDERDOC_TexDim; // xyz == width, height, depth. w == # mips

uint RENDERDOC_TextureType; // 1 = 1D, 2 = 2D, 3 = 3D, 4 = Cube, 5 = 1DArray, 6 = 2DArray, 7 = CubeArray, 8 = Rect, 9 = Buffer, 10 = 2DMS

// Textures
// Unsigned int samplers
layout (binding = 1) uniform usampler1D texUInt1D;
layout (binding = 2) uniform usampler2D texUInt2D;
layout (binding = 3) uniform usampler3D texUInt3D;
// cube = 4
layout (binding = 5) uniform usampler1DArray texUInt1DArray;
layout (binding = 6) uniform usampler2DArray texUInt2DArray;
// cube array = 7
layout (binding = 8) uniform usampler2DRect texUInt2DRect;
layout (binding = 9) uniform usamplerBuffer texUIntBuffer;
layout (binding = 10) uniform usampler2DMS texUInt2DMS;

// Int samplers
layout (binding = 1) uniform isampler1D texSInt1D;
layout (binding = 2) uniform isampler2D texSInt2D;
layout (binding = 3) uniform isampler3D texSInt3D;
// cube = 4
layout (binding = 5) uniform isampler1DArray texSInt1DArray;
layout (binding = 6) uniform isampler2DArray texSInt2DArray;
// cube array = 7
layout (binding = 8) uniform isampler2DRect texSInt2DRect;
layout (binding = 9) uniform isamplerBuffer texSIntBuffer;
layout (binding = 10) uniform isampler2DMS texSInt2DMS;

// Floating point samplers
layout (binding = 1) uniform sampler1D tex1D;
layout (binding = 2) uniform sampler2D tex2D;
layout (binding = 3) uniform sampler3D tex3D;
layout (binding = 4) uniform samplerCube texCube;
layout (binding = 5) uniform sampler1DArray tex1DArray;
layout (binding = 6) uniform sampler2DArray tex2DArray;
layout (binding = 7) uniform samplerCubeArray texCubeArray;
layout (binding = 8) uniform sampler2DRect tex2DRect;
layout (binding = 9) uniform samplerBuffer texBuffer;
layout (binding = 10) uniform sampler2DMS tex2DMS;

layout (location = 0) out vec4 color_out;
void main()
{
    // all black
    color_out = texelFetch(tex2D, ivec2(gl_FragCoord.xy), int(RENDERDOC_SelectedMip));
    // all red
    color_out = vec4(float(RENDERDOC_TextureType == 0), 0.0, 0.0, 0.0);
}

**Comment by baldurk** [comment]
I wonder if that's possibly the inserted glsl snippets that are incorrect. Can you try prepending `uniform` to those parameters?

```
uniform uint RENDERDOC_SelectedMip;
uniform uvec4 RENDERDOC_TexDim;
uniform uint RENDERDOC_TextureType;
```

That wouldn't explain the texelFetch going wrong though, but one step at a time - I'll try and repro the missing texture samples.

**Comment by karyon** [comment]
that works. the texelfetch went wrong because RENDERDOC_SelectedMip was probably zero as well and that miplevel indeed contained no data.

with the shader above however (removing the second line in main of course), the following happens:
![2016-07-19 15_33_20-mfs-viewer_2016 07 18_16 38 05_frame336447 rdc - renderdoc unofficial release v](https://cloud.githubusercontent.com/assets/1891915/16951646/2904bbc0-4dc6-11e6-899e-4095367e061f.png)
maybe the "canvas" should be resized to fit the miplevel size?

**Comment by baldurk** [comment]
Good point indeed, at the moment it always renders to the size of the top-level mip, but it should have the same mip chain as the input texture and render to the corresponding mip level.

**Comment by baldurk** [comment]
I think both issues should now be sorted - let me know how it works for you in the next nightly.

**Comment by karyon** [comment]
works beautifully, thanks!

**Comment by baldurk** [comment]
Great! Keep these reports coming, they are awesome :).
