### ISSUE TITLE
Tesselation case Thumbnail is different with backbuffer

### ISSUE THREAD

**Issue by POLO-huhu** [baldurk/renderdoc#3027]
## Description
After applying https://github.com/baldurk/renderdoc/issues/3025 fix.
We capture a tesselation case and can get thumbnail by *.rdc file. We also use python replay it and save backbuffer texture. We find 
they are differences in middle two rows.

If we not apply 3025 fix, result is well.
case info: use https://github.com/g-truc/ogl-samples     gl-420-interface-matching. 

We find all ogl-samples' all **tesslation cases have this bug**.

Example:
![image](https://github.com/baldurk/renderdoc/assets/33439206/1f127020-5d3d-4d83-86a0-d438c2bb8eba)

## Steps to reproduce
1 capture gl-420-interface-matching app
2 convert to xml+zip
3 run python:
    #  draw is swapbuffer action
    controller.SetFrameEvent(draw.eventId, True)
    texsave = rd.TextureSave()
    # Select the first color output
    texsave.resourceId = draw.outputs[0]

    if texsave.resourceId == rd.ResourceId.Null():
        return

    print("Saving images at eventId = %d, resourceId = %d: %s" % (draw.eventId, int(texsave.resourceId), draw.GetName(controller.GetStructuredFile())))

    # Save different types of texture

    # Most formats can only display a single image per file, so we select the
    # first mip and first slice
    texsave.mip = 0
    texsave.slice.sliceIndex = 0

    texsave.alpha = rd.AlphaMapping.BlendToColor

    fileType = rd.FileType.PNG
           
    texsave.destType = fileType
    controller.SaveTexture(texsave, goldenName)
compare goldenName and Thumbnail, you will find difference in Example
## Environment
  RenderDoc version: newest
  Operating System: win
  Graphics API: OGL

**Comment by Zorro666** [comment]
I am closing this issue here - as it is relevant to the PR and works well as a comment on the PR or an extension/extra conditions on the origin case #3025

**Comment by POLO-huhu** [comment]
This problem will show after apply PR. Attention please, this problem is not same as 3025. It is only occur on tesselation case.

**Comment by Zorro666** [comment]
For completeness - this looks to be a difference in the Windows AMD GL driver compared to the Windows nVidia GL driver and the MESA GL driver.
