### ISSUE TITLE
Vulkan: device lost when not binding all locations of a vertex attribute that uses multiple locations

### ISSUE THREAD

**Issue by jeroenbakker-atmind** [baldurk/renderdoc#3033]
## Description

A graphics pipeline uses a vertex shader input that contains a mat4, and only the first location of its 4 locations are bound with a buffer. When a drawing command of such shader is selected in to update the pipeline view of render doc. It freezes for several seconds, and after that it shows a message that the connection to the device is lost.

After that no data can be retrieved anymore and the capture needs to be reopened.

## Steps to reproduce

The application is Blender, but it requires a custom build. So for now I will add a capture.
[202308-renderdoc-attribute-locations.zip](https://github.com/baldurk/renderdoc/files/12407978/202308-renderdoc-attribute-locations.zip)

In the capture navigate to:
`Frame #1 -> SPACE_VIEW3D -> Viewport -> Overlay -> *p_extra_ps -> vkCmdDraw(16, 1)`

The device lost error should appear.

## Environment

* RenderDoc version: 1.28
* Operating System: PopOS 22.04
* Graphics API: Vulkan

I tried on AMD Vega, AMD PRO 7800 and NVIDIA RTX 5000. They all gave me the same results. 

Some context what I am doing. I am the lead developer of the Vulkan backend for Blender. Blender has an abstraction layer and its OpenGL/Metal part is already production ready. We are now in the process of implementing the Vulkan backend. The backend is unfinished and known to be buggy, but it also provides some use-cases that are not often encountered when using renderdoc.

**Comment by baldurk** [comment]
This is an application bug as far as I can tell. As you've identified, only one location out of the matrix is bound, but the matrix itself is used in the shader and so all locations must be bound correctly.

RenderDoc does not handle invalid API use, and so you may encounter undefined behaviour when using RenderDoc the same as any driver may have undefined behaviour. Some drivers may work in cases where RenderDoc fails and vice-versa, but none of them are guaranteed to work in the case of invalid API use.

You should run your application with the vulkan validation layers without RenderDoc present and fix any issues they identify - if they don't catch this one yet you can open an issue on the validation layers repository to ask that this be checked for.

**Comment by jeroenbakker-atmind** [comment]
Thanks for the clarification.
