### ISSUE TITLE
SM-A5057F Crash!

### ISSUE THREAD

**Issue by xjqxzyr** [baldurk/renderdoc#3036]
SM-A5057F Crash
BackTrace like this:
## Description
Android  PID  24945: [23:05:07]        gl_driver.cpp(1366) - Log     - Activating new GL context: ARM / Mali-G72 / OpenGL ES 3.2 v1.r26p0-01eac0.###other-sha0123456789ABCDEF0###
Android  PID  24945: [15:05:15]                    libc(0) - Fatal   - Fatal signal 11 (SIGSEGV), code -6 (SI_TKILL) in tid 28142 (RenderThread 1), pid 24945 (MainThread-UE4)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - Build fingerprint: 'samsung/a50dd/a50:11/RP1A.200720.012/A505FDDS9CVA4:user/release-keys'
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - Revision: '6'
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - ABI: 'arm64'
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - Timestamp: 2023-08-23 15:05:13+0800
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - pid: 24945, tid: 28142, name: RenderThread 1  >>> com.xxgame <<<
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - uid: 10318
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - signal 11 (SIGSEGV), code -6 (SI_TKILL), fault addr --------
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - x0  0000007634f93620  x1  00000076326ac9c0  x2  0000000000000055  x3  0000000000000004
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - x4  0000000000000028  x5  0000000000000050  x6  651eff09736d746e  x7  7f7f7f7f7f7f7f7f
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - x8  65722f6b7275646c  x9  f8cb3cbc0c90339e  x10 0000000001830a68  x11 0000007600000000
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - x12 0000000001830a28  x13 0000000000000000  x14 0000000000000000  x15 ffffffffffffffff
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - x16 00000077c407a9b8  x17 00000077c406ef7c  x18 00000076b656199e  x19 00000076b654d338
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - x20 000000772aff93a8  x21 00000076b654da68  x22 000000772aff9380  x23 00000076b654887c
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - x24 000000772aff9430  x25 65722f6b7275646c  x26 000000000000000b  x27 0000000000000001
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - x28 0000000000000000  x29 00000075fb83ce10
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - lr  00000076b51b2658  sp  00000075fb83cdc0  pc  00000076b51b2664  pst 0000000060000000
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - backtrace:
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #00 pc 0000000000217664  /data/app/~~Q8v5C0FoXLotlcufS_vK5w==/org.renderdoc.renderdoccmd.arm64-XzVs3ZhaqVDyc6Je18WmPQ==/lib/arm64/libVkLayer_GLES_RenderDoc.so (BuildId: f9b35ae503e99e72162e5d252cb1be120ec3acc3)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #01 pc 00000000003ed348  /data/app/~~Q8v5C0FoXLotlcufS_vK5w==/org.renderdoc.renderdoccmd.arm64-XzVs3ZhaqVDyc6Je18WmPQ==/lib/arm64/libVkLayer_GLES_RenderDoc.so (BuildId: f9b35ae503e99e72162e5d252cb1be120ec3acc3)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #02 pc 00000000003fde60  /data/app/~~Q8v5C0FoXLotlcufS_vK5w==/org.renderdoc.renderdoccmd.arm64-XzVs3ZhaqVDyc6Je18WmPQ==/lib/arm64/libVkLayer_GLES_RenderDoc.so (BuildId: f9b35ae503e99e72162e5d252cb1be120ec3acc3)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #03 pc 000000000000e0ec  /system/lib64/libnativedisplay.so (android::EGLConsumer::bindTextureImageLocked(android::SurfaceTexture&)+256) (BuildId: 43f3bc60aa3f9e9691c1b350ca9c6367)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #04 pc 000000000000da30  /system/lib64/libnativedisplay.so (android::EGLConsumer::updateTexImage(android::SurfaceTexture&)+396) (BuildId: 43f3bc60aa3f9e9691c1b350ca9c6367)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #05 pc 000000000000c0d4  /system/lib64/libnativedisplay.so (android::SurfaceTexture::updateTexImage()+80) (BuildId: 43f3bc60aa3f9e9691c1b350ca9c6367)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #06 pc 00000000000ec668  /system/lib64/libandroid_runtime.so (android::SurfaceTexture_updateTexImage(_JNIEnv*, _jobject*)+112) (BuildId: d1c4f108b3aac7289eafd61a580206d6)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #07 pc 000000000023cbec  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+124) (BuildId: d7c97b78e8f3b621344f5fe1a10c5f58d1b13d14)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #08 pc 0000000000134564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #09 pc 00000000001a9a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #10 pc 0000000000321270  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #11 pc 000000000031759c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #12 pc 0000000000688928  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+576) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #13 pc 000000000012e914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #14 pc 000000000046c2b4  /system/framework/framework.jar (android.graphics.SurfaceTexture.updateTexImage)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #15 pc 000000000068654c  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1520) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #16 pc 000000000012e814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #17 pc 00000000005c2a98  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/oat/arm64/base.vdex (com.epicgames.ue4.MediaPlayer14$BitmapRenderer.copyFrameTexture+350)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #18 pc 0000000000688bc8  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+1248) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #19 pc 000000000012e914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #20 pc 00000000005c3974  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/oat/arm64/base.vdex (com.epicgames.ue4.MediaPlayer14$BitmapRenderer.updateFrameData+4)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #21 pc 000000000068654c  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1520) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #22 pc 000000000012e814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #23 pc 00000000005c46e2  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/oat/arm64/base.vdex (com.epicgames.ue4.MediaPlayer14.getVideoLastFrame+26)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #24 pc 000000000030eb98  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.13836355384225087550)+268) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #25 pc 0000000000674d30  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #26 pc 000000000013dff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #27 pc 0000000000134564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #28 pc 00000000001a9a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #29 pc 000000000055e5b8  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+468) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #30 pc 000000000055e758  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #31 pc 0000000000411ee0  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallBooleanMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+660) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #32 pc 00000000003820fc  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::__va_list, art::Primitive::Type, art::InvokeType)+1644) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #33 pc 000000000036f9c4  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallBooleanMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+72) (BuildId: ffbc4c31ca7e027e2ad21029e8b11b2e)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #34 pc 000000000f680418  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/lib/arm64/libUE4.so
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #35 pc 000000000f680354  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/lib/arm64/libUE4.so (FJavaAndroidMediaPlayer::GetVideoLastFrame(int)+44)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #36 pc 00000000156eddd8  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/lib/arm64/libUE4.so
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #37 pc 00000000156e84ac  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/lib/arm64/libUE4.so
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #38 pc 00000000156f2bc0  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/lib/arm64/libUE4.so
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #39 pc 000000000f11b088  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/lib/arm64/libUE4.so (FNamedTaskThread::ProcessTasksNamedThread(int, bool)+1560)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #40 pc 000000000f11a698  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/lib/arm64/libUE4.so (FNamedTaskThread::ProcessTasksUntilQuit(int)+244)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #41 pc 000000000fb73ea4  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/lib/arm64/libUE4.so (RenderingThreadMain(FEvent*)+264)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #42 pc 000000000fb87a20  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/lib/arm64/libUE4.so (FRenderingThread::Run()+24)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #43 pc 000000000f1ad008  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/lib/arm64/libUE4.so (FRunnableThreadPThread::Run()+164)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #44 pc 000000000f115b30  /data/app/~~sKOeCMiCHE9f73Nkx9CUSQ==/com.tencent.ig-d_-HAxFXz0GoXW_heTEwtw==/lib/arm64/libUE4.so (FRunnableThreadPThread::_ThreadProc(void*)+176)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #45 pc 00000000000eb7a8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 698b6aef520f034a9d40736d477f7a96)
Android  PID  28399: [15:05:15]                   DEBUG(0) - Fatal   - #46 pc 000000000008bc8c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 698b6aef520f034a9d40736d477f7a96)

## Steps to reproduce

Use the latest version to attach to the debuggable game process, then click on the frame capture interface that appears, and then a crash occurs

## Environment

* RenderDoc version: v1.28
* Operating System: Android
* Graphics API: OpenGles 3.2

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.

**Comment by xjqxzyr** [comment]
已经收到您的邮件，谢谢！
