### ISSUE TITLE
Capturing vulkan application that uses VK_EXT_debug_utils crashes on windows

### ISSUE THREAD

**Issue by jspanchu** [baldurk/renderdoc#3038]
## Description

This is only a minor annoyance. When vulkan apps use `VK_EXT_debug_utils` and the callback function uses C++ stream operator on `VkDebugUtilsMessengerCallbackDataEXT::pMessageIdName` for logging purpose, RenderDoc capture mysteriously fails because `operator<<` for `std::cout` cannot seem to handle `nullptr_t` in VS2022. Now this is not immediately obvious because all I saw was my window pop up and close without any capture. I had to launch my application through debugger and use the strongly discouraged "Inject into process" method on windows to find out why it crashed. The message it wanted to print was 

> 
> "While debugging through RenderDoc, debug output through validation layers is suppressed.
> To show debug output look at the 'DebugOutputMute' capture option in RenderDoc's API, but be aware of false positives from the validation layers."

and the `pMessageIdName = nullptr`.

## Steps to reproduce
Enable `VK_EXT_debug_utils` extension in a vulkan sample program. In the debug callback function, attempt to print` pCallbackData->pMessageIdName` using `std::cout` when message type is `VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT` and message severity is `VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT`. Ex:

```c++

static VkBool32 VKAPI_CALL
DebugUtilsCallback(VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity,
                   VkDebugUtilsMessageTypeFlagsEXT messageTypes,
                   const VkDebugUtilsMessengerCallbackDataEXT* pCallbackData,
                   void* pUserData) {
    if (messageTypes & VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT) {
        if (messageSeverity & VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT) {
            std::cout << "General|Info: " << pCallbackData->messageIdNumber << "|" << pCallbackData->pMessageIdName << ": " << pCallbackData->pMessage << std::endl;
        }
    }
    return VK_FALSE;
}
```

I've a workaround which is check if `pCallbackData->pMessageIdName` is non-null and only then print it. However, the spec suggests that `pCallbackData->pMessageIdName` is a null terminated string. Perhaps [this](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/vulkan/wrappers/vk_misc_funcs.cpp#L1869C12-L1869C27) should be assigned to `"\0"` instead of `NULL`?

## Environment

* RenderDoc version: 1.28
* Operating System: Windows 11
* Graphics API: Vulkan 1.2

**Comment by baldurk** [comment]
`pMessageIdName` is indeed allowed to be NULL in the callback. See `VUID-VkDebugUtilsMessengerCallbackDataEXT-pMessageIdName-parameter`:

> If `pMessageIdName` is not `NULL`, `pMessageIdName` must be a null-terminated UTF-8 string

And compare to `pMessage` which isn't allowed to be NULL in `VUID-VkDebugUtilsMessengerCallbackDataEXT-pMessage-parameter`:

> `pMessage` must be a null-terminated UTF-8 string

As a note, there is no reason to use inject into process to use a debugger with your program. You can launch your program as normal from RenderDoc and set the "debugger delay" option to say 30s to give you time to attach your debugger. This is strongly recommended as the way to go and not use injection which may easily break.

**Comment by jspanchu** [comment]
I see. I missed that information. Perhaps I should’ve read the spec properly. Thanks! Didn’t know about the debugger delay option. That’s convenient!
