### ISSUE TITLE
New ISA compiler support for AMD drivers greater than 22.7.1

### ISSUE THREAD

**Issue by dreamelon** [baldurk/renderdoc#3041]
## Description

GLSL disassembly is not supported on AMD drivers greater than 22.7.1 due to the retirement of VirtualContext.
Is there any plan to support the new ISA compiler? I heard the point is the size of the package.

## Environment

* RenderDoc version: 1.28
* Operating System: Windows11 22H2
* Graphics API: OpenGL

**Comment by baldurk** [comment]
Yes the size of the backend in this case is too much to ask for the feature. A RenderDoc install is roughly 150MB (which is already larger than I'd like ideally) and about 25MB of that is already AMD plugins. The new backend _just_ for GL ISA is 36MB.

Given that GL users are not very likely to be interested in ISA anyway, the feature is not significant enough to justify the increase in program size.
