### ISSUE TITLE
spurious error "544 ID3D12GraphicsCommandList::Reset: Reset fails because the command list was not closed." when running microsoft D3D12 examples

### ISSUE THREAD

**Issue by billgan1024** [baldurk/renderdoc#3042]
## Description
When running the official microsoft examples in Renderdoc (e.g. Microsoft's Fullscreen example, SM6 example) with enable API validation, I get an error saying "GraphicsCommandList::Reset: Reset fails because the command list was not closed." even though there is no error reported in the app's debug layer.

## Steps to reproduce:
Run [this example](https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12Fullscreen) in renderdoc with enable api validation.
There will be an error in renderdoc as shown here:
[fullscreen.zip](https://github.com/baldurk/renderdoc/files/12478480/fullscreen.zip)

## Environment

* RenderDoc version: 1.28
* Operating System: Windows 11 (build 22621.2134)
* Graphics API: Direct3D 12

GPU: Nvidia RTX 3090
Driver version: 537.13

**Comment by baldurk** [comment]
I am confused at this. You have filed a feature request but your description doesn't make any sense in that context.

If this is a feature request please clearly explain which feature you want and how you would use it. If this is a bug report please use the correct issue format and fill out the template provided.

**Comment by billgan1024** [comment]
It was a bug report; I've filled out the issue format with more info.

**Comment by baldurk** [comment]
Thank you, I believe that commit should resolve the issue. For me it was only happening on the first capture made, if you were seeing something different or the error isn't resolved please let me know.
