### ISSUE TITLE
Vulkan sparse binding for images assumes sparse residency

### ISSUE THREAD

**Issue by JustSid** [baldurk/renderdoc#3044]
## Description

Right now, RenderDoc will not correctly replay images that use sparse binding but not sparse residency. [vk_initstate.cpp:752](https://github.com/baldurk/renderdoc/blob/52801a99a6bba9fa274d87559e69f5860295afef/renderdoc/driver/vulkan/vk_initstate.cpp#L752) calls `vkGetImageSparseMemoryRequirements` asking for the number of requirements. However, the number reported will be 0, as the spec states:

> If the image was not created with VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT then pSparseMemoryRequirementCount will be set to zero and pSparseMemoryRequirements will not be written to.

I was hoping to contribute a patch to fix this, but it seems that there is actually more going wrong. Based on the buffer binding code, naively it seems like I could just get the mip tail from the table and then use `GetLiveHandle()` to get the memory for it. Trying this, I hit a new assertion that the resource doesn't actually exist. However, if I press on, I actually can see the image data in the replay. I'm wondering if there might be something in the capture that doesn't properly track the resource usage because it has the same mistake with regards to assuming sparse binding implies sparse residency? Sadly once I'm out of strings to grep for, I'm pretty much out of my depth.

I have attached my patch for what I've done to vk_initstate.cpp so far. I think it's on the right track, but I don't understand enough about the RenderDoc architecture to fully finish it. If you have some pointers for me, I'd be very happy to keep digging into this myself and provide a full patch.

[vk_initstate.patch](https://github.com/baldurk/renderdoc/files/12492098/vk_initstate.patch)

## Steps to reproduce

Make a Vulkan image with sparse binding, then bind a single or multiple opaque memory regions to it. Then capture that with RenderDoc and replay the capture.

## Environment

* RenderDoc version: 1.28
* Operating System: Windows 11
* Graphics API: Vulkan 1.3

**Comment by baldurk** [comment]
I believe that commit should fix the issue, at least it does for me following your steps to reproduce. If you're still having problems please share a specific application that's running into issues as with sparse textures it's quite an involved API with many different ways of doing things so it's hard to reconstruct a test case that adequately hits the same path as yours.
