### ISSUE TITLE
SPIR-V Shader debugger does not respect Specialization Constants

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#3046]
## Description

When running the SPIR-V shader debugger, the specialization constants appear to be either garbage uninitialized data, or wrongly offsetted.

## Steps to reproduce

1. Download this project: https://mega.nz/file/pnAXgBIS#mAV_i1Ncj7v_TvQWYaxdfTw2TPecwzyjgQa0w0prE4c
2. Open it in RenderDoc with the following parameters:
```
ExePath = C:\Projects\Godot\projects\AndroidTest2\godot.windows.editor.dev.x86_64.exe
WorkingDir = C:\Projects\Godot\projects\AndroidTest2
CmdLine Args = -e --generate-spirv-debug-info
```
3. Take a capture of the editor.
4. Go to EID 38 and you will see the following:
![RenderDoc](https://github.com/baldurk/renderdoc/assets/3395130/9d101d1b-b17d-4b2b-a3ea-bf5ec2b0e815)
5. Ask to debug a pixel touched by the cube (e.g. pixel 1000, 500) in the Render Opaque Subpass section (EID 38 in the picture).

You will see that the debugger thinks that e.g. `sc_disable_directional_lights` is true but going to Pipeline State -> FS -> Specialization Constants, it clearly says it's false.

A lot of other spec. constants are in disagreement:

![RenderDoc02](https://github.com/baldurk/renderdoc/assets/3395130/39d28f4e-2948-4cbe-9697-1585d712de5b)

## Environment

* RenderDoc version: 1.28
* Operating System: Windows 10 & Xubuntu 20.04
* Graphics API: Vulkan

**Comment by Zorro666** [comment]
I verified the specialisation constants values inside the shader using shader printf and compared them to the constants in the pipeline view. 
```
#extension GL_EXT_debug_printf : enable

debugPrintfEXT(
"sc_directional_soft_shadow_samples %d\nsc_soft_shadow_samples %d\nsc_use_light_soft_shadows %d\n sc_penumbra_shadow_samples %d\n sc_use_light_projector %d\nsc_projector_use_mipmaps %d\nsc_luminance_multiplier %f\nsc_disable_fog %d\nsc_disable_decals %d\nsc_decal_use_mipmaps %d\nsc_disable_reflection_probes %d\nsc_disable_directional_lights %d\nsc_disable_omni_lights %d\nsc_disable_spot_lights %d\nsc_use_directional_soft_shadows %d\nsc_directional_penumbra_shadow_samples %d\n", 
sc_soft_shadow_samples,
sc_directional_soft_shadow_samples,
sc_use_light_soft_shadows, 
sc_penumbra_shadow_samples, 
sc_use_light_projector,
sc_projector_use_mipmaps,
sc_luminance_multiplier,
sc_disable_fog,
sc_disable_decals,
sc_decal_use_mipmaps,
sc_disable_reflection_probes,
sc_disable_directional_lights,
sc_disable_omni_lights,
sc_disable_spot_lights,
sc_use_directional_soft_shadows,
sc_directional_penumbra_shadow_samples
);
```
The data matches ie.

From Shader Pipeline using shader printf
```
sc_directional_soft_shadow_samples 4
sc_soft_shadow_samples 4
sc_use_light_soft_shadows 0
sc_penumbra_shadow_samples 8
sc_use_light_projector 0
sc_projector_use_mipmaps 1
sc_luminance_multiplier 2.000000
sc_disable_fog 1
sc_disable_decals 1
sc_decal_use_mipmaps 1
sc_disable_reflection_probes 1
sc_disable_directional_lights 0
sc_disable_omni_lights 1
sc_disable_spot_lights 1
sc_use_directional_soft_shadows 0
sc_directional_penumbra_shadow_samples 8
```
From Specialisation Constants Viewer 
```
sc_directional_soft_shadow_samples   4   0 uint
sc_soft_shadow_samples               4   8 uint
sc_use_light_soft_shadows            false 16 bool
sc_penumbra_shadow_samples           8   24 uint
sc_use_light_projector               false 32 bool
sc_projector_use_mipmaps             true 40 bool
sc_luminance_multiplier              2.00 48 float
sc_disable_fog                       true 56 bool
sc_disable_decals                    true 64 bool
sc_decal_use_mipmaps                 true 72 bool
sc_disable_reflection_probes         true 80 bool
sc_disable_directional_lights        false 88 bool
sc_disable_omni_lights               true 96 bool
sc_disable_spot_lights               true 104 bool
sc_use_directional_soft_shadows      false 112 bool
sc_directional_penumbra_shadow_samples 8   120 uint
```

Tracked the bug back to the shader debugger processing of the `Op::LogicalNot` instruction when applying specialisation constants. Can't really show screenshots of it working but after the code change the shader debugger steps in a logical way into or not into the if conditionals in the shader source which use the `!` (logical not) operator i.e.
```
```

**Comment by Zorro666** [comment]
The fix will be in the nightly builds : https://renderdoc.org/builds#nightly : after 04/09/2023
