### ISSUE TITLE
Certain OpenGL uniform values not displayed

### ISSUE THREAD

**Issue by OndrejSpanel** [baldurk/renderdoc#3047]
## Description

In captures I make in a game I am creating the values of uniform called `hemisphereLights` is always displayed as all zeros, while the light itself is working properly, therefore the values are not zero.

![image](https://github.com/baldurk/renderdoc/assets/6927223/2fcf1d44-4d4e-41a1-ac1c-8d53139f4cc4) ![image](https://github.com/baldurk/renderdoc/assets/6927223/952c3425-a03c-4c31-b696-80010ee01cb3)

## Steps to reproduce

- Open the capture I have attached - [hemi-uniforms.zip](https://github.com/baldurk/renderdoc/files/12512038/hemi-uniforms.zip)
- Check fragment shader uniforms for EID 29, notice values of `hemisphereLights` all all zeros
  - This is not correct, as seen by the fact the polyhedron is lighted as expected
  - EID 22-24 seem to be setting the values to nonzero vectors

### Note

The uniform is declared as follows in the shader:

```glsl
	struct HemisphereLight {
		vec3 direction;
		vec3 skyColor;
		vec3 groundColor;
	};

	uniform HemisphereLight hemisphereLights[ 1 ];
```

I think the issue shows with uniforms declared as arrays of structures. Arrays of arrays or plain structures work fine.

## Environment

* RenderDoc version: 1.28
* Operating System: Windows 11 x64
* Graphics API: OpenGL 4,6

* LWJGL 3.2.3 build 13, GLFW 3.4.0 Win32 WGL EGL OSMesa VisualC DLL
* OpenGL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation, GeForce GT 1030/PCIe/SSE2

**Comment by Zorro666** [comment]
Thank you for reporting the issue with a clear reproduction project and steps.

Here is a screenshot of the uniforms after the code fix
![image](https://github.com/baldurk/renderdoc/assets/39392/4d3cde3d-6a9e-4091-a59d-b46689f72dfe)

The fix will be in the nightly builds https://renderdoc.org/builds#nightly after 05/09/2023.
