### ISSUE TITLE
Vulkan object tags support

### ISSUE THREAD

**Issue by SupinePandora43** [baldurk/renderdoc#3054]
## Description

The Vulkan API requires 18+13 objects for basic rendering and presentation. (Assuming there are 3 swapchain images)
This can be hard to manage, especially with large numbers of objects. Object labels help, but it could be better.

I expected RenderDoc to support `vkSetDebugUtilsObjectTagEXT` in `Resource List` in a similar way to `vkCmdBeginDebugUtilsLabelEXT` in `Event Browser`, but found that it doesn't, and it's not even shown in `Resource Initialisation Parameters`.
The closest I could find was #2338, but it's closed.

I'd like to be able to simply collapse all initialization- and presentation- related objects in the `Resource List' view.

`uint64_t tagName` can be used for sorting, `size_t tagSize` for UTF-8 length, and `const void* pTag` for UTF-8 string description.

## Environment

* RenderDoc version: 1.27
* Operating System: Linux 6.4.12-arch1-1 (64-bit)
* Graphics API: Vulkan 1.1 `VK_EXT_debug_utils`

**Comment by baldurk** [comment]
That is not what `vkSetDebugUtilsObjectTagEXT` is for, that function is for attaching arbitrary implementation-defined sets of debug data to objects, where the implementation defines the tag (with something like a GUID) not the application.

You can use `vkSetDebugUtilsObjectNameEXT` which does what you are asking for and allows you to name objects. It is documented just above `vkSetDebugUtilsObjectTagEXT` in the vulkan spec.
