### ISSUE TITLE
ERROR: Could not find Nsight Perf SDK library

### ISSUE THREAD

**Issue by tylerfan** [baldurk/renderdoc#3057]
## Description
As in the title, I was trying to use the Nvidia counter type. 
I have copied the two downloaded .so from nvidia to the given path in renderdoc. 

libnvperf_grfx_host.so.2023.3.0
libnvperf_grfx_host.so

reopened the renderdoc with a new capture, still could not find the nvidia performance counters. 

## Steps to reproduce

same as above.

## Environment

* RenderDoc version: 1.2.6
* Operating System: ubuntu22.04
* Graphics API: VULKAN

**Comment by tylerfan** [comment]
ok found the issue. the instruction told me to put the .so under ~/.renderdoc, but it should actually be put under where the rendoerdoc executable is with plugins/nv/xxx.so

**Comment by baldurk** [comment]
Either location should work correctly. Are you saying you copied the library to `~/.renderdoc/plugins/nv/libnvperf_grfx_host.so` and it didn't work? It's unclear what you mean as you say `~/.renderdoc` in one case and `plugins/nv/libnvperf_grfx_host.so` in another case, so I'm not sure if you were copying the file just to `~/.renderdoc`.

**Comment by tylerfan** [comment]
@baldurk i copied the file to ~/.renderdoc/plugins/nv which didn't work as my binary is in ~/Downloads/renderdoc.
the thing that made it work is i copied the .so to ~/Downloads/renderdoc/plugins/nv.

the init error message told me to copy to ~/.renderdoc/plugins/nv

**Comment by baldurk** [comment]
Just to check, do you have the `$HOME` environment variable properly set to the same path as `~` ?

Can you share a screenshot of the error message as well as showing the library in the location specified? This should definitely work so I'll let nvidia know that it's broken. I can't repro right now because the nvidia webpage for downloading the library is broken.

**Comment by tylerfan** [comment]
![Screenshot from 2023-09-14 10-08-26](https://github.com/baldurk/renderdoc/assets/104521469/6ad9bc8c-11dc-46d4-bea0-bc33f164355f)

**Comment by tylerfan** [comment]
also to note for clarity, this is after i re-opened renderdoc after copied those libraries.

**Comment by tylerfan** [comment]
echo $HOME gives 
/home/tyler

**Comment by baldurk** [comment]
Did you find out what was causing this problem? Or why did you close the issue? I'm still waiting to get a reply from nvidia.
