### ISSUE TITLE
Feature request: Automatically set light/dark theme based on system setting

### ISSUE THREAD

**Issue by Fell** [baldurk/renderdoc#3059]
## Background

Most people prefer a dark theme these days, but in some lighting situations a light theme might be better readable. In my specific case, I switch themes based on the weather and time of day. It would be nice if RenderDoc could be configured to automatically apply the light or dark theme based on the system settings, like many other applications.

I mainly use Windows 10, but I also switch themes on Linux (KDE Plasma).

## Requested Feature

A configuration option that allows to apply "Light" and "Dark" themes based on the current system setting. It should also listen to events and change the theme when needed.

As RenderDoc is already able to change themes at runtime (I could not find any issues, despite the warning message) I hope that implementing this feature is not too much of a hassle.

## Environment

* RenderDoc version: v1.28
* Operating System: Windows 10 x64 22H2 (19045.3448)
* Graphics API: OpenGL

I understand that this feature would have to be implemented seperately on each platform. I'm mainly asking for Windows, but I use the same workflow on Linux as well.

Thank you very much for your work. RenderDoc has been an incredibly useful tool to me for years and I most humbly ask for this improvement.

**Comment by baldurk** [comment]
I don't know that I agree that most people prefer dark themes, but that's irrelevant to the request :).

RenderDoc is not able to completely change themes at runtime. Most things do change, but not everything will update and it does require a program restart for everything to be correct. This is not something I plan to fix as it's too rare a need to justify the workload and extra bug surface required, and similarly changing themes regularly at runtime automatically is also not something I want to support for the same reasons.

The theme is auto-detected on first startup based on the system theme, but after that point you will have to manually change it. The only thing I can suggest is you create a UI extension with a menu item you can toggle to do the work of auto-detecting again and changing the style. As I say above this will require a UI restart to properly refresh but if you can live with the brokenness then you don't have to restart.
