### ISSUE TITLE
RenderDoc fails to open multiple Vulkan captures with out of device memory errors

### ISSUE THREAD

**Issue by Kelebek1** [baldurk/renderdoc#3062]
## Description

With RenderDoc I often want to compare 2 different frames at the same time, a good frame a bad frame, to see what inputs went wrong and where, in order to track down rendering issues. However in Vulkan, it's almost impossible to open 2 captures at the same time, as RenderDoc always throws this out of device memory error on opening the second capture:
![image](https://github.com/baldurk/renderdoc/assets/34639600/417c0cd4-3f88-4b31-80c6-f18793fce04e)

With 0 captures open:
![Untitled](https://github.com/baldurk/renderdoc/assets/34639600/27b34389-d409-4937-8117-ecb68191823d)
With 1 capture open:
![Untitled](https://github.com/baldurk/renderdoc/assets/34639600/13057818-0dc8-4ff5-8b11-6e47fe0a9049)

Once loaded, it seems to only take up ~1.5GB with plenty to spare, but then attempting to load any other capture and it will throw out of device memory.

Also, if I run my application and then try to load a RenderDoc capture while my app is open, RenderDoc will also throw this error. If I reverse the order and load the RenderDoc capture first, and then my application, both work perfectly fine with low GPU memory utilisation. It seems RenderDoc just doesn't like when another Vulkan application is running on the system, including itself.

## Steps to reproduce

Here are 2 small and simple captures which trigger the issue for me: https://cdn.discordapp.com/attachments/942442841408434186/1153640179513434112/deko_texture_example.7z

Open one of the captures, and then open the other so that a second RenderDoc instance opens. The second capture should throw an out of device memory error.

These were captured on an nVidia Titan X, using Vulkan 1.3. The build process is a bit of a pain, so I'm hoping you can open these. Let me know if not though.

## Environment

Windows 10, and all RenderDoc versions I've used experience this issue, currently on v1.29 https://github.com/baldurk/renderdoc/commit/815c88b932245826c30dba1a8309ee9ae3eadb78

**Comment by baldurk** [comment]
I'm not able to reproduce this. I can open both captures fine (though I did have to patch them to open on my 4090 as the memory types were not compatible with a titan X). I'm on the exact same driver 536.99 so I don't think it's a driver version thing.

Does this only happen with your program? Or can you repro this with e.g. vkcube or Sascha Willems' demos? Do you have a different machine or GPU you can test with?

Realistically I'm not sure why this would happen only for you unless it was an NV/driver issue, but it doesn't make a lot of sense to me either why it would report an out of memory error.

**Comment by Kelebek1** [comment]
I cannot reproduce this with vkcube or Sascha's demos, I can open multiple of those, so it may be my app only. We have an OpenGL backend and I can open multiple OpenGL captures without issue. We don't have a DirectX backend so I can't test that, but after capturing some other random DX apps, multiples there are also ok. So it seems like it is specific to my app, and is Vulkan-only.

I'll try to build RenderDoc from source and do a little debugging to see if I can get some information about the allocations.

EDIT: Ok, it's trying to allocate 0x8000000 bytes as a stream buffer in heap 2, which is my host visible/device local memory region and only 0xD600000 in size, so it can only fit a single allocation that size in it. Lack of rebar support is a killer. Bit of a shame I suppose, but I guess RenderDoc has to replicate the memory allocations in the exact heaps they came from? I'll close this as an issue with my application.

**Comment by baldurk** [comment]
Ahh, yes that make sense - also makes sense why I didn't reproduce it when I hacked the capture to remap the memory allocations.

In the general case RenderDoc needs to preserve the memory types for correctness, otherwise there could be a cascading effect with the resources bound not being available to bind to other memory types, availability for host writes, etc. Newer features like buffer device address put a nail in the coffin of the idea of remapping memory types. I do have a local hack that will reallocate memory for resources but it doesn't work in all cases and right now doubles the amount of memory used in a capture.

Presumably that also means that if you run two instances of your application it will break? Indeed the only thing I can suggest is what you will have already thought of - being more careful with how much PCI-E window memory you use.
