### ISSUE TITLE
Be able to view a capture even on different platform/GPU

### ISSUE THREAD

**Issue by arnaudcarre** [baldurk/renderdoc#3073]
## Description

RenderDoc doesn't allow to view a .rdc capture file if captured on another platform/GPU. For instance, a VK mobile .rdc capture file on Adreno 640 can't be inspected on a desktop PC with NVidia GPU. 
I perfectly get why the capture can't be "replayed" without the original hardware, but why can't I just "look" at the frame commands? ( drawcalls, etc).
A "view mode" only would be awesome to be able to do that for debug purpose.

## Environment

* RenderDoc version: 1.28
* Operating System: Windows 10
* Graphics API: any

**Comment by baldurk** [comment]
No I do not plan to add this functionality, as I think the value is quite small but it has a high implementation cost and complexity. If you want to view the contents of a capture without replaying it you can use the python API to examine the serialised structured data.
