### ISSUE TITLE
error: no member named 'type' in 'glslang::TSpirvTypeParameter'

### ISSUE THREAD

**Issue by Martinfx** [baldurk/renderdoc#3075]
## Description

Hi, I am porting this software to FreeBSD and I  have issue with _"error: no member named 'type' in 'glslang::TSpirvTypeParameter'"_

## Steps to reproduce
`
cmake -DCMAKE_BUILD_TYPE=Release -DQMAKE_QT5_COMMAND=qmake-qt5 -Bbuild -H.
gmake -C build -j6

`

## Environment

* FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
Target: x86_64-unknown-freebsd13.2
Thread model: posix
InstalledDir: /usr/bin

* Last commit : f36d8a3b2
* RenderDoc version: XXX
* Operating System: FreeBSD
* Graphics API: OpenGL/GLX

**Comment by baldurk** [comment]
FreeBSD is not a supported platform so this is not something I will provide any support with. If you're porting to an unsupported platform you will need to investigate any platform-specific problems yourself.

**Comment by jbeich** [comment]
FWIW, https://github.com/amshafer/renderdoc has WIP FreeBSD support.
