### ISSUE TITLE
Vulkan ReplayManager segfaulting on a single triangle draw capture

### ISSUE THREAD

**Issue by Firestar99** [baldurk/renderdoc#3086]
## Description

I'm building a hobby vulkan renderer that somehow segfaults RenderDoc in `ReplayManager` threads. Unfortunately I cannot get CLion to properly load the debug symbols (missing experience on my part) to provide anymore detail myself. 

I've attached a capture below where I tried to rip out as much as possible but it still segfaults. This capture does a single 3 vertices draw call to swapchain image and presents it, with no descriptors, uniforms, vertex attachments, buffers (I provide the vertices in the shader for now), other images than swapchain ones and has it's very basic shaders ported to glsl. Also shows no Validation Errors with standard validation. I unfortunately can't rip out the draw call itself due to a bug in vulkano, the framework I am using. 

## Steps to reproduce

1. load the capture [renderdoc_crash.zip](https://github.com/baldurk/renderdoc/files/12885080/renderdoc_crash.zip)
2. segfault <0.5s after loading bar disappears

My Repo in case it helps, but I'm using rust: 
https://gitlab.com/spacegamedev/space-rust/-/tree/debug_renderdoc?ref_type=heads
**branch debug_renderdoc**

## Environment

* RenderDoc version: 1.29, 1.27, de8981134ca372ce19d3e12f542a9f30c407f428 (latest master)
* Operating System: Ubuntu 23.04, [AMD Radeon Graphics (RADV REMBRANDT)](http://vulkan.gpuinfo.org/displayreport.php?id=21072)
* Graphics API: Vulkan

**Comment by Firestar99** [comment]
I can confirm it works just fine on Windows, tested on:
* [AMD 680M iGPU](http://vulkan.gpuinfo.org/displayreport.php?id=22166) 
Capture: [amd.zip](https://github.com/baldurk/renderdoc/files/12885472/amd.zip)
* [NVIDIA GeForce RTX 3070 Ti Laptop GPU](http://vulkan.gpuinfo.org/displayreport.php?id=23629) 
Capture: [nvidia.zip](https://github.com/baldurk/renderdoc/files/12885474/nvidia.zip)

**Comment by baldurk** [comment]
I can only reproduce this by loading on lavapipe from my distro, it crashes somewhere inside lavapipe's code. Contrary to your environment listing you are creating your vulkan device from lavapipe rather than the radv physical devices.

If I build lavapipe from latest mesa it works fine. Can you try using radv or else using a more up to date lavapipe? This seems like a driver bug from what I can tell.

**Comment by Firestar99** [comment]
> you are creating your vulkan device from lavapipe rather than the radv physical devices

Well that wasn't supposed to happen...

It seems like I preferred CPU implementations over iGPUs over dGPUs, but it should have been in reverse of course. Thanks for the help :sweat_smile:
