### ISSUE TITLE
Not support  Android-14

### ISSUE THREAD

**Issue by deargaoshan** [baldurk/renderdoc#3088]
## Description
install Renderdoc APK in Android-14，Pop-up window: Couldn't correctly verify installed APK version.
## Steps to reproduce
1- Connect to replay context
2- RenderDoc app shows on Android device
3- Launching app from RenderDoc
4- App launches on Android device
5- The Game application crash immediately after startup

## Environment
* RenderDoc version: 1.29
* Operating System: **Android 14**
* Graphics API:OpenGL ES 3.1

![image](https://github.com/baldurk/renderdoc/assets/79963375/de37aeda-120e-4f4f-8894-0592ea66706c)

**Comment by baldurk** [comment]
I guess this means something changed in Android 14 that broke backwards compatibility.

This may take a while to investigate as Android 14 only came out a matter of days ago so it will be a while before any devices are updated, and I'm not sure if any of my devices will get an update at all.

**Comment by deargaoshan** [comment]
![image](https://github.com/baldurk/renderdoc/assets/79963375/cc660936-6994-4839-a507-3dc18bb32f59)

**Comment by baldurk** [comment]
Posting a screenshot of a message box is not very helpful without context. Can you please explain in detail what you are meaning to say here and what is happening? You've already reported that Android 14 is not working in multiple ways (not detecting that the RenderDoc server is installed properly, and causing applications to crash) and I understand that but like I said above I can't reproduce this currently so I will need to wait until I can to investigate. Has something changed from the original report?

**Comment by baldurk** [comment]
I've had some clarification from google who have helped test RenderDoc on Android 14, and it appears that RenderDoc v1.29 should work correctly but there are some cosmetic/workflow issues that have been introduced. These should not prevent you from using RenderDoc as far as I understand:

- If you have a 64-bit only device, the message about being unable to verify installed APKs may appear. This message can be ignored as it is a false positive.
- There may also be a message on the device about the app being outdated. This is a false positive from Android.
- If you do not get a prompt when the RenderDoc APK is installed on your device to grant file management permissions, you will need to grant this permission manually. The way to do this will vary by device.

Can you please uninstall RenderDoc fully from your Android device, and then detail the exact steps you take from starting RenderDoc on your computer, what happens at each point, and what goes wrong - if anything after this?

**Comment by deargaoshan** [comment]
All three of what you say, I have been careful to check, and there is nothing wrong with it. Maybe it's because of the phone I used. Because this is the next generation of qualcomm chips, with android 14, there will be problems using renderdoc. Now the phenomenon is that when the app starts, it kills right away
