### ISSUE TITLE
renderdoc server crash on mobilephone when install

### ISSUE THREAD

**Issue by Sean-Tang** [baldurk/renderdoc#3089]
## Environment

* RenderDoc version: V1.29 win-x64
* Operating System: HarmonyOS 4.0
* Graphics API: Opengles

when install renderdoc server，failed for crash, can it be fixed and be available on harmonyOS? crash log:

10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: FATAL EXCEPTION: main
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: Process: org.renderdoc.renderdoccmd.arm64, PID: 9307
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.renderdoc.renderdoccmd.arm64/org.renderdoc.renderdoccmd.arm64.Loader}: android.content.res.Resources$NotFoundException: Drawable org.renderdoc.renderdoccmd.arm64:drawable/icon with resource ID #0x7f020000
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4765)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4983)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:123)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3059)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:117)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:205)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.os.Looper.loop(Looper.java:293)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.ActivityThread.loopProcess(ActivityThread.java:9934)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:9923)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at com.android.internal.os.WrapperInit.main(WrapperInit.java:94)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:392)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable org.renderdoc.renderdoccmd.arm64:drawable/icon with resource ID #0x7f020000
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: width and height must be > 0
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.graphics.Bitmap.createBitmap(Bitmap.java:1309)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.content.res.HwResourcesImpl.getOptimisedMask(HwResourcesImpl.java:659)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.content.res.HwResourcesImpl.processMask(HwResourcesImpl.java:621)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.content.res.HwResourcesImpl.initMask(HwResourcesImpl.java:613)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.content.res.HwResourcesImpl.handleAddIconBackground(HwResourcesImpl.java:862)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:1100)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.content.res.Resources.loadDrawable(Resources.java:1107)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.content.res.Resources.getDrawableForDensity(Resources.java:1097)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.content.res.Resources.getDrawable(Resources.java:1029)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.content.Context.getDrawable(Context.java:753)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:327)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:922)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at com.android.internal.policy.PhoneWindow.setDefaultIcon(PhoneWindow.java:1999)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.Activity.initWindowDecorActionBar(Activity.java:3722)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.Activity.setContentView(Activity.java:3757)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.NativeActivity.onCreate(NativeActivity.java:145)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at org.renderdoc.renderdoccmd.arm64.Loader.onCreate(Loader.java:17)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:8592)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:8565)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4733)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4983)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:123)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3059)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:117)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:205)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.os.Looper.loop(Looper.java:293)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.ActivityThread.loopProcess(ActivityThread.java:9934)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:9923)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at com.android.internal.os.WrapperInit.main(WrapperInit.java:94)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:392)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: Error reporting crash
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.os.BinderProxy.transactNative(Native Method)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.os.BinderProxy.transact(BinderProxy.java:607)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5648)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:193)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
10-17 19:10:20.989 10261 9307 9307 E AndroidRuntime: at java.lang.Thread.dispatchUncaughtException(Thread.java:2211)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
