### ISSUE TITLE
pixel context selects wrong pixel in opengl

### ISSUE THREAD

**Issue by karyon** [baldurk/renderdoc#309]
whenever i select a pixel in the texture viewer by right-clicking it, the pixel context pane has the pixel directly above it selected.

**Comment by baldurk** [comment]
I think that commit should do the trick :). I copied over code from vulkan and forgot to account for the different co-ordinate system, so the rendered highlight box was upside-down.

**Comment by karyon** [comment]
yeah, it works now.
