### ISSUE TITLE
Adobe AfterEffects crashes with RenderDoc enabled

### ISSUE THREAD

**Issue by mmdurrant** [baldurk/renderdoc#3090]
## Description

AfterFX spits out some Direct2D errors then crashes when launched from RenderDoc.  I attached the warning that appears. This only happens when launched from RenderDoc. My goal is troubleshooting a plugin I wrote that uses Vulkan. 

## Steps to reproduce
Launch After Effects using the RenderDoc Launch Application interface. 

## Environment

* RenderDoc version: 1.29
* Operating System: Windows 10 
* Graphics API: DirectX12/Vulkan

I'd like to provide more info but presently this is all I have.  If I can enable any RenderDoc logging/debugging/etc to provide more useful data, I will gladly do so. 
![image](https://github.com/baldurk/renderdoc/assets/5604598/83e47d10-12b6-4294-88c8-4f1587d0f4b1)

**Comment by baldurk** [comment]
RenderDoc does not support Direct2D - it uses undocumented private Microsoft-only APIs and so it is impossible to handle.

The only thing I can suggest is seeing if you can create a fallback path in your application that doesn't rely on Direct2D, at least as far as allows you to debug what you're interested in.

**Comment by mmdurrant** [comment]
I'm not trying to debug Direct2D, I'm trying to debug Vulkan shader code that runs in AE and this is the error I get. I thought I specified that when I created the issue.

**Comment by baldurk** [comment]
Your program uses Direct2D, which as stated above is an impossible library to support by third party tools due to it using undocumented private interfaces. If you have problems when using programs that don't use Direct2D and only Vulkan, please open a new issue with information about that.
