### ISSUE TITLE
incorrect access of VkPipelineRenderingCreateInfo

### ISSUE THREAD

**Issue by zmike** [baldurk/renderdoc#3093]
## Description

Renderdoc captures crash due to access of VkPipelineRenderingCreateInfo from GPL stages. Only the FRAGMENT_OUTPUT GPL stage can access this.

## Steps to reproduce
Probably happens when capturing anything using GPL?

this part of `renderdoc/driver/vulkan/vk_next_chains.cpp`
```c
      case VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO:
      {
       	const VkPipelineRenderingCreateInfo *in = (const VkPipelineRenderingCreateInfo *)nextInput;
        VkPipelineRenderingCreateInfo *out = (VkPipelineRenderingCreateInfo *)tempMem;

       	// append immediately so tempMem is incremented
       	AppendModifiedChainedStruct(tempMem, out, nextChainTail);

//EVERYTHING BELOW THIS PART IS ONLY VALID TO ACCESS FOR FRAGMENT_OUTPUT

        // allocate unwrapped array
        VkFormat *outFormats = (VkFormat *)tempMem;
       	tempMem += sizeof(VkFormat) * in->colorAttachmentCount;

        *out = *in;

        out->pColorAttachmentFormats = outFormats;
       	for(uint32_t i = 0; i < in->colorAttachmentCount; i++)
          outFormats[i] = in->pColorAttachmentFormats[i];

       	break;
      }
```

## Environment
3ca187d725d9cfc27145198106e70ce2e27701a9

* RenderDoc version: git
* Operating System: linux
* Graphics API: vulkan

**Comment by zmike** [comment]
Can be reproduced with any recent-ish build/release of Mesa when trying to capture zink with `MESA_LOADER_DRIVER_OVERRIDE=zink supertuxkart`

**Comment by baldurk** [comment]
That commit should fix the issue, doing a two-pass preprocessing step to first determine the struct validity before processing.
