### ISSUE TITLE
Segmentation fault replaying a Vulkan LLVMpipe capture

### ISSUE THREAD

**Issue by Kurapikov** [baldurk/renderdoc#3102]
## Description

I am developing an Linux application use bgfx, imgui and SDL2 framework. Rendering API is Vulkan. I captured a frame successfully. While I tried to replay the capture, there's a segment fault with renderdoc.

The phenomenon is similar to #2939 

## Steps to reproduce

Install Ubuntu in VMWare Workstation.
Capture a frame and open with qrenderdoc or renderdoc cmd.

## Environment

* RenderDoc version: 1.29 Linux
* Operating System: Ubuntu 23.04
* Graphics API: Vulkan LLVMpipe

### About VMWare and Ubuntu in VMWare
I recently noticed that my application uses LLVMPipe. That's because VMWare display driver doesn't have a real Vulkan implementation. I think that may caused the segment fault.

### bt Information provided by GDB
`
#0  0x00007ff355a003f2 in fill_sampler_stage (state=0x1801200, dyn_info=<optimized out>,  stage=stage@entry=MESA_SHADER_VERTEX, p_stage=MESA_SHADER_VERTEX, array_idx=array_idx@entry=0,  descriptor=0x266d420, binding=0x30418b0) at ../src/gallium/frontends/lavapipe/lvp_execute.c:1123 #1  0x00007ff355a01ed4 in handle_descriptor (state=state@entry=0x1801200, dyn_info=dyn_info@entry=0x7ff349ffcb50,  binding=binding@entry=0x30418b0, stage=stage@entry=MESA_SHADER_VERTEX,  p_stage=p_stage@entry=MESA_SHADER_VERTEX, array_idx=array_idx@entry=0, type=<optimized out>,  descriptor=0x266d420) at ../src/gallium/frontends/lavapipe/lvp_execute.c:1242 #2  0x00007ff355a02004 in handle_set_stage (state=state@entry=0x1801200, dyn_info=dyn_info@entry=0x7ff349ffcb50,  set=set@entry=0x266d240, stage=stage@entry=MESA_SHADER_VERTEX, p_stage=p_stage@entry=MESA_SHADER_VERTEX) at ../src/gallium/frontends/lavapipe/lvp_execute.c:1275 #3  0x00007ff355a02194 in handle_descriptor_sets (cmd=cmd@entry=0x6721570, state=state@entry=0x1801200) at ../src/gallium/frontends/lavapipe/lvp_execute.c:1357 #4  0x00007ff355a05b35 in lvp_execute_cmd_buffer (cmd_buffer=<optimized out>, state=state@entry=0x1801200) at ../src/gallium/frontends/lavapipe/lvp_execute.c:4049 #5  0x00007ff355a09a85 in lvp_execute_cmds (device=0x17ffec0, queue=queue@entry=0x1800ff8,  cmd_buffer=<optimized out>) at ../src/gallium/frontends/lavapipe/lvp_execute.c:4347 #6  0x00007ff3559fbcb6 in lvp_queue_submit (submit=<optimized out>, vk_queue=<optimized out>) at ../src/gallium/frontends/lavapipe/lvp_device.c:1521 #7  lvp_queue_submit (vk_queue=0x1800ff8, submit=0x4a35670) at ../src/gallium/frontends/lavapipe/lvp_device.c:1506 #8  0x00007ff3558d78f6 in vk_queue_submit_final (queue=queue@entry=0x1800ff8, submit=submit@entry=0x4a35670) at ../src/vulkan/runtime/vk_queue.c:377 #9  0x00007ff3558d7b78 in vk_queue_submit_thread_func (_data=_data@entry=0x1800ff8) at ../src/vulkan/runtime/vk_queue.c:490 #10 0x00007ff3558c996b in impl_thrd_routine (p=<optimized out>) at ../src/c11/impl/threads_posix.c:67 #11 0x00007ff35768f6ba in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444 #12 0x00007ff35771e0d0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
`

### The captured file
I cannot access the Linux box right now. If information above is not enough and the capture file helps, feel free to comment and I will upload as an attachment ASAP.

**Comment by Zorro666** [comment]
This does not appear to be a RenderDoc crash. The reported crash is in the llvmpipe driver code.
It might be a similar issue to this reported problem when running RenderDoc with llvmpipe : https://gitlab.freedesktop.org/mesa/mesa/-/issues/4694

Also worth mentioning RenderDoc relies on correct API usage and behaviour from the application being captured. 

It would be helpful to run your application with Vulkan validation layers enabled (without RenderDoc attached) to find and then fix any reported Vulkan validation errors.

**Comment by Kurapikov** [comment]
Hi Zorro, 

If it was a llvmpipe bug, the application should crash I guess? but the application works without any problem.

**Comment by Zorro666** [comment]
Hi

I think in this case, the llvmpipe bug is triggered by the RenderDoc replay code. 
The RenderDoc code is valid and correct API usage (and works fine on other Vulkan drivers).

Making the capture and replay on a different driver would be helpful to identify it was an llvmpipe bug.

If you can share a capture file then I can try and test that locally on a different driver (sometimes the captures are not portable between drivers though).
