### ISSUE TITLE
Support for VK_EXT_frame_boundary

### ISSUE THREAD

**Issue by theHamsta** [baldurk/renderdoc#3103]
## Description

At the moment, renderdoc only supports profiling or debugging graphics applications that use a swapchain (please correct me if I'm wrong in that regard). For Vulkan, vkQueuePresent serves as a marker for frame boundaries. In RenderDoc UI you can select how many frames you want to capture which will be delimited by vkQueuePresent. If your application doesn't use vkQueuePresent (e.g. because your application outputs the render result to disk, network or the GPU video encoder), you can not use all features of renderdoc.

`VK_LAYER_RENDERDOC_Capture` could implement `VK_EXT_frame_boundary` (https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_frame_boundary.html) to offer a swapchain-less application an alternative way to delimit frame and designate a final render result as if it would use `vkQueuePresent`

## Environment

* RenderDoc version: v1.29
* Operating System: Linux, Ubuntu 23.10
* Graphics API: Vulkan

**Comment by Zorro666** [comment]
Yeah, RenderDoc uses the present boundary to determine render frames and for capturing from the RenderDoc UI.

For applications which don't use or don't have a present boundary then the RenderDoc capture API is available for the application to manually start and stop the capture. [Documentation](https://renderdoc.org/docs/in_application_api.html) is on the website and has example code for using the API to generate a capture manually using the RenderDoc APIs `StartFrameCapture` and `EndFrameCapture`
