### ISSUE TITLE
How to parse Chunk Data?(NOT SDChunk)

### ISSUE THREAD

**Issue by waitlessJ** [baldurk/renderdoc#3109]
## Description

When Capture end, I know renderdoc will write captured data to rdc files with Chunk.
What if I do not want to add all the needed chunks to the rdc file?
It is kind of edit the rdc and it do works when I just remove some chunks by editing the xml files for small captures.
But I think for complicated captures , it's more strightforward by remove chunks I do not want when write to rdc file

Or is there a way to write the SDChunk Data to a new rdc file with some SDChunk remove/edit?

## Environment

* RenderDoc version: V.127
* Operating System: Windows/Linux
* Graphics API: D3D/OGL/VK

**Comment by baldurk** [comment]
I don't quite understand what you're asking but it sounds like you're making custom modifications to the RenderDoc source and capture process. Of course you are free to do so but this is not something I provide support for so you are on your own with any such investigations.

If you are just using an unmodified RenderDoc, please open a new issue and give more details and clarify what you are asking for in terms of using the program only and not referring to internal implementation details.
