### ISSUE TITLE
Request: support for inspect/replay vktrace files?

### ISSUE THREAD

**Issue by oscarbg** [baldurk/renderdoc#312]
Don't know if it's hard work or not and if interested to implement or not..
but seeing Khronos Siggraph video I saw a GUI for inspecting vktrace files is being implemented and thought if made sense to RenderDoc able to inspect this trace files captured from LunarG VUlkan SDK?

**Comment by baldurk** [comment]
RenderDoc already supports capturing Vulkan programs natively and in a much more efficient file format than vktrace, which traces every frame from the start of a program. Why do you actually want to be able to load vktrace files in RenderDoc?

Realistically this will never happen as the capture file formats are incompatible and it would be a lot of work to make the two tools interoperable. From what I can tell, there is no benefit to doing so either.

**Comment by edrickhong** [comment]
@baldurk I was thinking that this feature would be useful for those bugs that only persist for a couple of frames. Maybe a work flow where I can scrub through each frame in the trace viewer and launch renderdoc from there to inspect a specific frame. Maybe instead of supporting the vktrace format, an application can pass the necessary state information for a frame, input + output states + api calls.

**Comment by baldurk** [comment]
RenderDoc only supports capturing directly from rendering in vulkan applications, not any kind of constructed or artificially passed information.

If vktrace wants to integrate the [RenderDoc in-application API](https://renderdoc.org/docs/in_application_api.html) to capture a segment of rendering then that's up to that project, many projects have done something similar for custom triggered captures, but there's still nothing that will change on RenderDoc's side to support this.

**Comment by edrickhong** [comment]
@baldurk Thanks for the reply. I'll take this up to LunarG then. Just a quick question. When TriggerCapture() is called, the capture frame will be exported to an rdc file, correct?

**Comment by edrickhong** [comment]
Idk how exactly renderdoc works but I assume that the viewer app would have to ensure some initial input state first and renderdoc takes that, the api calls, and uses that to recreate the frame

**Comment by baldurk** [comment]
The linked documentation should explain exactly what each function does. `TriggerCapture()` is identical to the way F12 or PrintScreen work, by triggering a capture to be created on the next Present frame boundary. `StartFrameCapture()` and `EndFrameCapture()` will begin and end a capture immediately when called, without any delay, so can be useful either when rendering happens off-screen without being tied to a Present call or if you want extremely fine-grained control over what is included in the capture.

There is no requirement for any input state or data to be passed to RenderDoc. It works entirely transparently within the Vulkan API itself and can capture any subset of commands - by default it captures between two Present calls but that can be controlled via `StartFrameCapture()` and `EndFrameCapture()` as above.
