### ISSUE TITLE
Possible to build without swig?

### ISSUE THREAD

**Issue by mcclure** [baldurk/renderdoc#3123]
Would it be possible to get an ENABLE_SWIG CMake configuration option, so that building the SWIG bits of qrenderdoc could be disabled?

## Description

I am building a local copy of Renderdoc. To simplify the build, I am trying to include only those features I know I need. For example, I include `-DENABLE_PYRENDERDOC=0`, because I do not need Python scripting at this moment.

The build fails after a bit with

```
[ 96%] Performing configure step for 'custom_swig'
configure: error: in `/home/mcc/work/g/other/renderdoc/build/qrenderdoc/custom_swig-prefix/src/custom_swig':
configure: error: 
        Cannot find pcre-config script from PCRE (Perl Compatible Regular Expressions)
        library package. This dependency is needed for configure to complete,
        Either: [snip]
```

At one level this is unsurprising, because Dependencies.md says:

> For qrenderdoc you need Qt5 >= 5.6 along with the 'svg' and 'x11extras' packages. You also need `python3-dev` for the python integration, and `bison`, `autoconf`, `automake` and `libpcre3-dev` for building the custom SWIG tool for generating bindings.

But at another it is surprising because if pcre is only needed for a "SWIG tool for generating bindings", it's not clear to me why I need it. I will not be scripting with Python (or anything else) at this time. SWIG as far as I know is only used for connecting scripting languages to C programs.

Reading the CMakeLists by hand, it appears the SWIG stuff goes live if `ENABLE_QRENDERDOC OR ENABLE_PYRENDERDOC`, and there is a comment I am not sure I understand:

```
# we also need python3-config for swig, but it's only for the examples
# so it doesn't matter which one we find as long as we find something!
```

Is there some specific thing qrenderdoc needs SWIG for, above and beyond the generation of scripting interfaces? (Not asking for details here, just asking if it exists.)

## "Expected behavior"

I would have expected I could pass -DENABLE_SWIG and avoid the need for SWIG dependencies such as PCRE.

I do not *need* the ability to disable SWIG, and I can easily just install pcre as documented and continue. However, "build a RenderDoc with minimal dependencies" seems like a reasonable desire.

## Steps to reproduce

On a fairly fresh Ubuntu 23.10 machine, I install some of the required-as-stated dependencies (eg, qt5-qmake) for renderdoc but not all (eg, not pcre).  I run

```
mkdir build && cd build
QT_SELECT="default" QTTOOLDIR="/usr/lib/qt5/bin" QTLIBDIR="/usr/lib/x86_64-linux-gnu" cmake .. -DENABLE_PYRENDERDOC=0 -DENABLE_WAYLAND=1 -DENABLE_XLIB=0 -DENABLE_XCB=0 -DENABLE_GL=0 -DENABLE_GLES=0 -DENABLE_EGL=0
QT_SELECT="default" QTTOOLDIR="/usr/lib/qt5/bin" QTLIBDIR="/usr/lib/x86_64-linux-gnu" cmake --build .
```

Note: I understand ENABLE_WAYLAND=1 is not supported, but it is orthogonal to this particular issue.

## Environment

* RenderDoc version: git 74b0a8b1a73e4b
* Operating System: Ubuntu 23.10
* Graphics API: Vulkan

**Comment by baldurk** [comment]
No, swig isn't an optional dependency (at least as long as you're building the UI or python modules as you've found). It's needed for the python shell panel even if you're not using the separate python modules, and that's not a dependency that can trivially be snipped out and not one that I think is worth making optional.

In my view at least as far as open source projects goes RenderDoc's set of dependencies is not very demanding or time consuming to set up, and I try to keep it that way. I don't see sufficient value in reducing the required set of dependencies even further.

**Comment by mcclure** [comment]
Thank you for explaining.

**Comment by elmarco** [comment]
Hi @baldurk , bundling swig is a bit problematic for some distributions.

What's the modifications that require a forked version?

A newer version of swig would allow to get rid of deprecated libprce.

thanks

**Comment by baldurk** [comment]
I'm not really sure what you mean, the build process handles downloading swig and building it so there shouldn't be anything distributions need to do at all. The custom swig has a number of features for the python integration that don't exist upstream and probably never will.

In future please do not comment on closed issues, please open a new issue with whatever bug or feature request you are running into. If you have a general question these should be taken to a channel like discord or via email.
