### ISSUE TITLE
RenderDoc doesn't see Vulkan API on Windows 11 with AMD RX 6500 XT and nVidia GeForce GTX 1650

### ISSUE THREAD

**Issue by Andreyogld3d** [baldurk/renderdoc#3130]
## Description
I cannot create capture for any Vulkan App, because I have no active button "Capture ***", and static text "API: None"

## Steps to reproduce
1. Run RenderDoc
2. Open any Vulkan executable file(for Example https://github.com/SaschaWillems/Vulkan/tree/master/examples/multiview, vkcube.exe from Lunarg Vulkan SDK) File->Launch Application
3. Press Launch button

## Environment

* RenderDoc version: 1.29(1.30 73c604d2f0fd5e690406af5ef3703727315ddbf1)
* Operating System: Windows 11
* Graphics API: Vulkan

GPU 1 AMD RX 6500 XT  driver 31.0.22023.1014 - Monitor is attached to this Video Card
GPU 2 NVidia Geforce GTCX 1650 driver 31.0.15.4601

also I have GPU inside AMD Ryzen 5 5600 G
![image](https://github.com/baldurk/renderdoc/assets/8597425/325f415c-0815-4deb-9a66-4b271a38a2d8)

but Direct3D12, Vulkan API get only AMD RX 6500 XT and GPU 2 NVidia Geforce GTCX 1650

Additional info:
Direct3D12 capture is working.

Screenshot with bug:

![rdoc_vk_bug](https://github.com/baldurk/renderdoc/assets/8597425/9e41fea3-7259-4521-9fc1-33c33463863b)
Vulkan caps viewer: 

![image](https://github.com/baldurk/renderdoc/assets/8597425/ba9366f8-8a86-4bd3-ab4d-6ba40b36b1bb)
![image](https://github.com/baldurk/renderdoc/assets/8597425/c4cc92ca-0e67-448f-aefc-af5ffcbe8ddf)

I have a building version 1.30 73c604d2f0fd5e690406af5ef3703727315ddbf1 and possible debuging from Visual Studio it can help to fix bug
This [breakpoint ](https://github.com/baldurk/renderdoc/blob/bcb7dfd3aebe32c669b5122f00ba27dd12ea54ca/renderdoc/core/target_control.cpp#L865)is working for Direct3D12, but it doesn't work for Vulkan

**Comment by baldurk** [comment]
Do you have the RenderDoc vulkan layer registered correctly? Look at the launch application tab, if it has a large warning banner asking you to click it to set up the vulkan layer, it's not properly registered.

**Comment by Andreyogld3d** [comment]
>Do you have the RenderDoc vulkan layer registered correctly?

Yes, I use VVL suring developing Vulkan apps.

From Visual Studio Debug Output I see 
'qrenderdoc.exe' (Win32): Loaded 'C:\Library\VulkanSDK\Bin\VkLayer_khronos_validation.dll'. Symbols loaded.
So, seems VVL are loaded correctlty ?

> Look at the launch application tab, if it has a large warning banner asking you to click it to set up the vulkan layer, it's not properly registered.

I see no any error or warning,

**Comment by baldurk** [comment]
The validation layers have nothing to do with RenderDoc, that's not what I was asking, but if you don't see a warning then it should be fine.

Are you using vkconfig at all? vkconfig is known to cause many problems and incompatibilities, and should never be used at the same time as RenderDoc.

**Comment by Andreyogld3d** [comment]
I have removed overrided C:\Documents and Settings\....\AppData\Local \vk_config\override\vk_layer_settings.txt 
Now I can create capture! Thank you! Issue can be closed

**Comment by baldurk** [comment]
OK, glad you got it working. For future reference vkconfig should **never** be used at the same time as RenderDoc as vkconfig intends to take full control over the layer system which breaks RenderDoc's functionality.
