### ISSUE TITLE
[d3d] 'SV_InnerCoverage' was not handled properly 

### ISSUE THREAD

**Issue by SevenIsSeven** [baldurk/renderdoc#3137]
## Description
'SV_InnerCoverage' was not correctly displayed in the DXBC window of Pixel Shader

## Steps to reproduce
1. Load the attached capture [2023.11.13_03.49.33_frame0.rdc.zip](https://github.com/baldurk/renderdoc/files/13364616/2023.11.13_03.49.33_frame0.rdc.zip)
2. Click event 
24: Draw(3)
3. Check the 'Pipeline State' -> 'PS'
4. verify the DXBC Disassembly that 'oUnsupported' was shown instead of 'SV_InnerCoverage'

## Environment

* RenderDoc version: RenderDoc_1.29_64
* Operating System: Windows 11
* Graphics API: D3D

![sv-innerCoverage](https://github.com/baldurk/renderdoc/assets/150881358/c80467e4-7d02-4a9d-9545-8e1f8be779f5)

**Comment by baldurk** [comment]
That commit fixes the disassembly for this operand type.

**Comment by SevenIsSeven** [comment]
> That commit fixes the disassembly for this operand type.

thanks for the prompt fix~
