### ISSUE TITLE
Does not build - missing dependency.

### ISSUE THREAD

**Issue by Marqin** [baldurk/renderdoc#314]
After installing mentioned dependencies for Arch and nothing more I get:

```
/bin/sh: xxd: command not found
/bin/sh: xxd: command not found
```

After looking for that, I found that xxd is packaged with vim. So I think vim should be listed as renderdoc dependency.

**Comment by baldurk** [comment]
That's quite unexpected for xxd to come packaged with a text editor, I guess it's never been split out from the vim source. Vim isn't exactly the most heavy-weight of dependencies and at least it's not a runtime dependency ,ut it's a little annoying to need it just for that little utility.

Perhaps in future I should write something to do the job instead and pre-compile it before using it (xxd looks like it might have license issues, as it's dual MIT/GPL so I want to stay away from distributing it as-is).

Can you please check #274 to see if it's working for you now? As I mentioned I couldn't repro the warnings even with the specified compiler version.

**Comment by Marqin** [comment]
@baldurk it's super simple to implement. My c++ version took 42 lines of code - https://gist.github.com/Marqin/b73d9a95d80833bd89063b616d8b8b68

**Comment by Marqin** [comment]
I'll put this tommorow in proper repo with proper license and tests, so you can use it for renderdoc.

**Comment by Marqin** [comment]
I've changed it a little, to be exacly like xxd - now it makes new line after 12 characters and variable name is sanitized input filename.

**Comment by baldurk** [comment]
It looks good to me :+1:. This is pretty much what I had in mind, to be honest even minor things like formatting to 80 chars isn't really necessary as these are intermediate files it's generating, but it's a nice thing to account for.

**Comment by Marqin** [comment]
@baldurk https://github.com/Marqin/include-bin

**Comment by Marqin** [comment]
Also, if you don't want to use it, there is C program called `bin2c` that's on public domain. You can find it's forks in many places.

**Comment by Marqin** [comment]
Build and backported it to Arch package.
