### ISSUE TITLE
Incorrect handling of OpSwitch with 64-bit selectors

### ISSUE THREAD

**Issue by Hugobros3** [baldurk/renderdoc#3140]
## Description

 * RenderDoc's SPIR-V parser fails to correctly parse `OpSwitch` instructions that have a selector value whose type is a `OpTypeInt` with a width of 64.
 * This leads to the disassembler and debugger incorrectly handling shaders where such switches appear - the extra word per selector literal gets misinterpreted as a SSA reference. 
 * I am the developer of [shady](https://github.com/Hugobros3/shady), a research SPIR-V compiler that implements a higher baseline of capabilities. This issue came up while I was trying to diagnose some visual corruptions in one of my C++ shader samples.
 * The shader in question _might_ have problematic constructs in it, _but_ it does pass `spirv-val` _and_ I have debugged and inspected RD itself and it's crystal clear that the `PairLiteralIntegerIdRef` struct is not adequate for handling cases of such switches.

---

The following function contains this instruction: `OpSwitch %rshift_logical_149 %264 0 %265 1 %266 2 %267 3 %268` parses as

```c
void generated_store_Generic_f32(ulong _259, float _260) {
  ulong rshift_logical_149 = _259 >> 62;
  
  switch(rshift_logical_149) {
      Unreachable();
    case 0:
      Unreachable();
      Unreachable();
    case 0:
      ulong rshift_logical_150 = _259 >> 61;
      ulong and_151 = rshift_logical_150 & 1;
      bool eq_152 = and_151 == 1;
      ulong select_153 = Select(eq_152, 13835058055282163712, 0);
      ulong and_154 = _259 & 4611686018427387903;
      ulong or_155 = and_154 | select_153;
      generated_store_PrivatePhysical_varying_f32(or_155, _260);
      break;
    default:
      Unreachable();
  }

  return;
}
```

Note the incoherent layout and duplicated zero case. The actual source IR for that function is this:

```
@Generated fn generated_store_Generic_f32(varying u64 ptr~147, varying f32 value~148) {
    val varying u64 rshift_logical~149 = rshift_logical(ptr~147, 62);
    match(rshift_logical~149) {
        case 0:  {
            unreachable;
        }
        case 1:  {
            unreachable;
        }
        case 2:  {
            unreachable;
        }
        case 3:  {
            val varying u64 rshift_logical~150 = rshift_logical(ptr~147, 61);
            val varying u64 and~151 = and(rshift_logical~150, 1);
            val varying bool eq~152 = eq(and~151, 1);
            val varying u64 select~153 = select(eq~152, 13835058055282163712, 0);
            val varying u64 and~154 = and(ptr~147, 4611686018427387903);
            val varying u64 or~155 = or(and~154, select~153);
            call (generated_store_PrivatePhysical_varying_f32)(or~155, value~148);
            yield();
        }
        default:  {
            unreachable;
        }
    };
    return();
}
```
---

The SPIR-V spec says the following about `OpSwitch`:

> [...] Each literal is interpreted with
the type of Selector: The bit width of Selector’s type is the width of each literal’s type. If this width is not a
multiple of 32-bits and the OpTypeInt Signedness is set to 1, the literal values are interpreted as being
sign extended.

This means that you need the _type_ of the selector to parse `OpSwitch`. I tried writing a RD PR to fix this, but unfortunately it looks to be architectured in such a way that the instruction parser only gets a slice of the words, where it'd need the surrounding context knowledge to know the selector's type.

## Steps to reproduce

https://github.com/baldurk/renderdoc/files/13427757/rd_switch64_capture_fixed.zip

Using the linked capture, look at the disassembled shader (there's only one) or try to debug one of the pixels from the triangle.

![image](https://github.com/baldurk/renderdoc/assets/772170/69994885-6ecb-486b-a638-545a0e0d8811)

(NB: The visual corruption is what I was initially debugging. It might be a driver bug. The RD issue is unrelated!)

## Environment

* RenderDoc version: Git commit 0d9ea809dd436b631874f65d100eac95764ef349
* Operating System: Ubuntu 22.04 LTS
* Graphics API: Vulkan

It's irrelevant to the SPIR-V parsing issue, but the GPU is a 6900XT and the driver is Mesa RADV 23.1.9 built in Debug mode.

**Comment by baldurk** [comment]
I think the issue is still valid either way but the capture you have included as a repro case does not use OpSwitch, `generated_store_Generic_f32` looks like this for me in it:

```
void generated_store_Generic_f32(ulong _214, float _215) {
  ulong rshift_logical_120 = _214 >> 61;
  ulong and_121 = rshift_logical_120 & 1;
  bool eq_122 = and_121 == 1;
  ulong select_123 = Select(eq_122, 13835058055282163712, 0);
  ulong and_124 = _214 & 4611686018427387903;
  ulong or_125 = and_124 | select_123;
  generated_store_PrivatePhysical_varying_f32(or_125, _215);
  return;
}
```

It would be much easier to verify any fix if you could provide a capture that reproduces the problem.

**Comment by Hugobros3** [comment]
Sorry! I updated the capture after someone pointed out another problem, and forgot to disable the workaround I made in the meanwhile. [This](https://github.com/baldurk/renderdoc/files/13427757/rd_switch64_capture_fixed.zip) capture should exhibits the issue properly.

![image](https://github.com/baldurk/renderdoc/assets/772170/2b51e611-99eb-460a-b0b8-aa61de11b2f1)

**Comment by Zorro666** [comment]
Hi there

Thank you for reporting this issue. GLSL and HLSL don't appear to support switch statements with 64-bit selectors.
The support for 64-bit selectors has been added in 5bfb844643bd

I also explored the shader debugger with your capture.
When I ran the shader in the capture through "spirv-val" it gave this error

`error: line 6: Operand 1 of MemoryModel requires one of these capabilities: PhysicalStorageBufferAddresses`

If I edit the shader to add the missing capability then the shader debugger reports the shader can not be edited because is uses unsupported capability `PhysicalStorageBufferAddresses` (for reference that is Issue #2848)

**Comment by Zorro666** [comment]
BTW - the capture replays correctly in RenderDoc on Windows nVidia machine

![image](https://github.com/baldurk/renderdoc/assets/39392/6f9d5824-0fa6-4f13-b922-32554d29195f)

**Comment by Hugobros3** [comment]
Thanks! The visual corruption was my own fault (reading undefined values) and I was trying to diagnose it concurrently with reporting the Switch64 issue in RD. I believe the final capture I uploaded contained the fixes, but I have been tweaking it continuously and I may have regressed some other things accidentally, like declaring capabilities inconsistently. The fix looks good, thanks again!
