### ISSUE TITLE
Folder/timestamp for captures started from cmd

### ISSUE THREAD

**Issue by dimateos** [baldurk/renderdoc#3143]
## Description

I use `renderdoccmd` to start captures and `--capture-file` to specify the path to save the captures. I have been looking around and I dont see a simple way to add timestamps to avoid clashing. I digged as far as finding the fmt code for the suffix to see if there was a special case that did the replacement: https://github.com/baldurk/renderdoc/blob/0d9ea809dd436b631874f65d100eac95764ef349/renderdoc/core/core.cpp#L1378

Basically I want something like the filename **already used for temporal captures / unspecified capture names**:

- Sample tmp capture filename for an app named "viewer": `viewer_2023.11.20_12.25.28_frame165.rdc`

---

Right now I ended up cooking the path/filename in a .bat before calling renderdoc, but this is quite cumbersome... I can think of two simple ways to make it simpler:

- Respect folders: make `--capture-file` identify when the passed argument is a folder (e.g. ends in a folder separator) and use that folder to store the captures following the same pattern used in `%temp%/renderdoc` (`executablename-timestampt-frame.rdc`).

- Or use a new argument: `--capture-folder` users could specify a folder directly. Probably then, `--capture-file` would specify local paths inside this folder.

This would keep the timestamaps for sorting and avoid name clashing, plus being able to specify the folders for different debugging sessions etc would be very nice.

> I might have missed something more obvious? then sorry for openning the issue :(
> Thanks for your work!

## Environment
* RenderDoc version: v1.29
* Operating System: Win10 (21H2)
* Graphics API: OpenGL

**Comment by baldurk** [comment]
`renderdoccmd` is not supported at all and is not eligible for any feature requests. It is an internal undocumented and private program only for use by the tool itself, not by users directly.

If you would like to automate capturing then you can use the python API which is supported, but it doesn't provide the level of control you want. Temporary capture filenames are also an implementation detail and are not intended to be created directly in whatever final location you want. When you have a session in the UI they are managed by the UI until you save them manually so you would need to follow that process with a python script - enumerating the captures made and their timestamps and moving/rename them to the appropriate location.
