### ISSUE TITLE
Need support for Vulkan VK_NV_linear_color_attachment

### ISSUE THREAD

**Issue by alecazam** [baldurk/renderdoc#3144]
## Description

We have a game that relies on VK_NV_linear_color_attachment for screenshots.   The screenshot is rendered into that, and then encoded afterwards, since it has a linear instead of serpentine pattern to the pixels.  But when running the game under RenderDoc this extension seems to be suppressed.

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_NV_linear_color_attachment.html

This extension is a different list of linearTiling and optimalTiling settings in a 64-bit uint.   I guess Vulkan ran out of bits.   And Nvidia only supports linearTiling in isolation.  So can do MRT, but then all targets must be linear, or optimal tiling.   Nvidia hardware basically breaking the Vulkan spec.   AMD/Intel just support mixing linear and optimal tiling.  

## Steps to reproduce

The capture is from a shipping game, but probably wouldn't help here.  We are just told the extension is unsupported, so disable our screenshot button.

## Environment

* RenderDoc version: 1.29
* Operating System: Win 10
* Graphics API: Vulkan
* Gpu: Nvidia 3070
* Driver: 537.13.0.0 (0x86434000)

**Comment by baldurk** [comment]
I'm not quite clear on this, is this a feature request or a bug report? It seems like a feature request for VK_NV_linear_color_attachment and your description doesn't seem to detail any kind of bug but you've used the bug report template. I'm going to file this as a feature request for now but please let me know if I've misunderstood.

**Comment by alecazam** [comment]
Yes, that’s fine.  I wasn’t sure if it was a bug that this extension wasn’t appearing, or that RenderDoc is filtering the extension due to a missing feature.

**Comment by alecazam** [comment]
Also would be nice to know when an extension is suppressed by enabling RenderDoc_capture.   Wasn't expecting that to alter the extensions so drastically.   And it's always present on Win/Android, but the dll isn't.  So we can disable the extension only when RenderDoc is running the app on most of our platforms.

**Comment by baldurk** [comment]
I don't really understand what you mean by "it's always present". There's no need for a separate query for RenderDoc though, supported extensions are reported through the normal vulkan enumeration functions and an application can react to the available extensions without needing to special-case anything for RenderDoc, the same way as it does for different drivers.

**Comment by alecazam** [comment]
The issue is that the capture extension is always present for RenderDoc.  Maybe because I have RenderDoc installed.  But I’ve had to add tests for platforms that we know have a particular extension, since when we activate the capture extension many of the unsupported Nv extensions disappear from the list.  

Right now I search for the DLL and if present then I activate the capture extension, but only.  I’m using this to identify that the app was launched from RenderDoc.

**Comment by baldurk** [comment]
I don't know what you mean by a capture extension so I'm afraid I still don't understand. Do you mean `VK_EXT_debug_utils` the debug extension? That shouldn't have any relation to this.

When you launch your program from RenderDoc you'll run under RenderDoc's environment. It behaves as-if it were a driver with different capabilities so you don't need any special case code you can just run your normal logic to handle different drivers.

**Comment by alecazam** [comment]
This is what I have to do to disable renderDoc, but I'd like to leave the support enabled in our debug builds.  But since it modifies the extension list, that's not good.  So right now, I have to comment out the second line to test with RenderDoc.  On some platforms, I'm detecting the renderdoc dll but that doesn't work on all.  

```
       bool hasRenderDocExtension =  m_debugLayers.IsAvailable( "VK_LAYER_RENDERDOC_Capture" );

	// Since this disables many NV extensions (checkpoints and linear_color_attachment), then leave
	// this off unless this is manually ocmmented out.  Need a way to detect app is being run
	// from RenderDoc.  
	hasRenderDocExtension = false;
```

**Comment by baldurk** [comment]
Layers are not the same things as extensions but you seem to be using the terms interchangeably. You never have to interact with the RenderDoc layer, and indeed you never _should_ interact with the RenderDoc layer. If you are enabling it by hand then that is definitely wrong and there is nowhere in any documentation or instructions that tells you to do that.

I'm still not entirely sure what you're doing, but as I said above you do not need to make any modifications to your program to 'disable' RenderDoc. Run your program from RenderDoc when you want to use it and allow RenderDoc to work as normal, if you try to interfere with how it works then you may create problems for yourself as it sounds like you are doing or get unwanted behaviour.

**Comment by alecazam** [comment]
Thanks, we build up a list of the debug layers, then query them for extensions.  I can try just not adding in that into our array of debug layers, and see if that helps.
