### ISSUE TITLE
Mesh Viewer fails when vertex input state has per instance attributes before per vertex attributes

### ISSUE THREAD

**Issue by tksuoran** [baldurk/renderdoc#3145]
## Description

Mesh Viewer does not work when draw call has per instance attributes before per vertex attributes.

- The draw call renders correctly in the app
- The draw call renders correctly in RenderDoc capture except for Mesh Viewer
- Mesh viewer data table appears to show values from vertex buffer using vertex 0 repeatedly for all elements (indices)
- Mesh viewer preview shows nothing for VS input (assuming it shows same data as table above, which has same value for all vertex positions, this would be consistent with the table)
- Swapping the order of attributes so that per vertex attributes are before per instance attributes makes Mesh Viewer to work as well
- NSight Graphics has similar issue

## Steps to reproduce

- Capture will be shared privately shortly
- Event ID 20 has the issue (`vkCmdDrawIndexed(4920,2)`)
- Mesh Viewer preview is unexpectedly empty

## Environment

* RenderDoc version: v1.29
* Operating System: Windows 11
* Graphics API: Vulkan

**Comment by baldurk** [comment]
That commit should fix the issue, as tested on the capture you shared.
