### ISSUE TITLE
Ability to run custom texture shaders at visible pixel resolution instead of texture pixel resolution.

### ISSUE THREAD

**Issue by reduz** [baldurk/renderdoc#3150]
## Description

When using shader to debug textures, Renderdoc renders to a texture the same size of the texture you are debugging and then displays it on screen.

In some cases, the textures may be packing more pixels inside. As an example, trying to debug a compressed texture (that uses smaller blocks) by reading in the custom shader with the uncompression code that writes out bigger blocks.

In this mode, RenderDoc should simply create a render target the size of the visible texture in the UI and run the shader there, without 1:1 pixel match.

## Environment

* RenderDoc version: 1.29
* Operating System: Geforce 1650
* Graphics API: Vulkan

**Comment by baldurk** [comment]
This is not something I intend to support, the 1:1 processing of custom visualisation shaders is deliberate. If you have data e.g. packed in a gbuffer you could create multiple shaders for each aspect you wanted to display if each input texel generates more than four components worth of output, but it's not intended to support arbitrary reformatting or processing.
