### ISSUE TITLE
[Vulkan Shader Debugging] texelFetch R32_UINT/R16_UINT usampleBuffer always returns 0.

### ISSUE THREAD

**Issue by wumo** [baldurk/renderdoc#3152]
## Description

When debugging in vulkan, `texelFetch` a `R32_UINT`/`R16_UINT` `usampleBuffer` in compute shader will always return 0 while the actual value shown in buffer window isn't 0. If I change the resource from usampleBuffer to storage buffer, then the result seems correct. 

Actual buffer value:
![](https://github.com/baldurk/renderdoc/assets/7351935/a651d93c-2346-4da4-aaef-aa87ce7bf03d)

Debugging value:
![image](https://github.com/baldurk/renderdoc/assets/7351935/54ae903a-1fa1-4a21-8138-35cb700392ba)

Result:
![image](https://github.com/baldurk/renderdoc/assets/7351935/4f43754d-9cf9-4ee3-9e9d-7610b24150f5)

## Steps to reproduce

The compute shader is:
```glsl
#version 450
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform writeonly image3D ResultTex;
layout(set = 0, binding = 1) uniform usamplerBuffer IdxBuffer;
// layout(set = 0, binding = 1) buffer IdxBuffer {
//     uint Indices[];
// };

void main() {
    // uint Idx = Indices[int(gl_GlobalInvocationID.x)];
    uint Idx = texelFetch(IdxBuffer, int(gl_GlobalInvocationID.x)).x;
    imageStore(ResultTex, ivec3(gl_GlobalInvocationID.xyz), uvec4(Idx) / 64.0);
}
```
Capture file: [capture.zip](https://github.com/baldurk/renderdoc/files/13467257/capture.zip)

## Environment

* RenderDoc version: 1.29.0
* Operating System: Windows 10
* Graphics API: Vulkan 1.1.0
* Graphics Card: NVIDIA GeForce RTX 3080
* Graphics Driver: 537.52.0
*

**Comment by wumo** [comment]
For now, I'll have to use `buffer` instead of `samplerBuffer` to debug.

**Comment by baldurk** [comment]
That commit should fix the issue, return values from samples in int/uint weren't being properly processed according to their type.
