### ISSUE TITLE
Renderdoc buttons not showing on UE 5.2/5.3

### ISSUE THREAD

**Issue by isaaclepes** [baldurk/renderdoc#3157]
## Description
Renderdoc is enabled and installed
![image](https://github.com/baldurk/renderdoc/assets/54421422/10f0a809-6a8b-412b-892d-38e530a81a32)

However, the buttons are not showing in the editor.
![image](https://github.com/baldurk/renderdoc/assets/54421422/1e06c116-0462-4a2d-ba5e-fe501795fd1f)

## Steps to reproduce

Install UE 5.2+
Enable Renderdoc
Watch it fail to show the button.

## Environment

* RenderDoc version: 1.0
* Operating System: Windows 10
* Graphics API: DX12

AMD RX 480

**Comment by baldurk** [comment]
I am not responsible for Unreal Engine's RenderDoc integration. You need to report this bug wherever there is support for that button/plugin.

**Comment by isaaclepes** [comment]
OK, well you may wish to have them remove the links from the plugin to your github then.

**Comment by wumo** [comment]
@isaaclepes It is not the problem of renderdoc. It is the problem of UE5 adding additional configuration to enable the renderdoc button. Check the configuration of Plugin renderdoc and enable 'Auto attach on startup'. BTW, you can get what I said just by googling and the official UE doc will show you how todo it. 
[Using RenderDoc with Unreal Engine](https://docs.unrealengine.com/5.2/en-US/using-renderdoc-with-unreal-engine/)

**Comment by blueroseslol** [comment]
@isaaclepes 

Add config in DefaultEngine.ini
```ini
[/Script/RenderDocPlugin.RenderDocPluginSettings]
renderdoc.AutoAttach=True
```
RenderDoc icon can show!
