### ISSUE TITLE
APP have 0x20000000 Flags in CreateDeviceAndSwapChain function. When I capture, create device is well and generate rdc file, but replay is error.

### ISSUE THREAD

**Issue by POLO-huhu** [baldurk/renderdoc#3159]
## Description
APP have 0x20000000 Flags in CreateDeviceAndSwapChain( , Flags = 0x20000000, ..) function. When I capture, renderdoc create device is well, but replay is error. In d3d11_replay.cpp, D3D11_CreateReplayDevice function.

[WGF11FillRules_2023.11.28_06.13.56_frame0.rdc.zip](https://github.com/baldurk/renderdoc/files/13559390/WGF11FillRules_2023.11.28_06.13.56_frame0.rdc.zip)
please remove .zip postfix to use.

## Steps to reproduce
 1 run capture, Flags is 0x20000000,create device well. capture a rdc file.
 2 convert to xml. Show that "<uint name="Flags" typename="uint32_t" width="4">536870912</uint>",  536870912 is 0x20000000
3 open rdc file,  CreateDeviceAndSwapChain  is error in function D3D11_CreateReplayDevice 

## Environment
* RenderDoc version: v1.29
* Operating System: win10 profession
* Graphics API: D3D11 
* GPU: intel 
*

**Comment by baldurk** [comment]
0x20000000 is not [a valid flag to pass to device creation](https://learn.microsoft.com/en-us/windows/win32/api/d3d11/ne-d3d11-d3d11_create_device_flag), your application should not be passing it. If you use the API in invalid ways RenderDoc may not function correctly.
