### ISSUE TITLE
Attachments displayed as LOAD DONT CARE while loadOp is LOAD

### ISSUE THREAD

**Issue by Flone-dnb** [baldurk/renderdoc#3160]
## Description

I've split my rendering into 2 render passes, the first one does a depth prepass (only vertex shader is binded) and the second one does the actual color rendering. I'm using 2 render passes instead of 2 subpasses because I need to run compute shaders after the depth render pass. Now in the color render pass RenderDoc displays depth attachment texture as LOAD DONT CARE (all text is just white) but I specified LOAD to load the depth that was recorded during the depth render pass (although RenderDoc displays `C=Clear, D=Load` which is correct). My color attachment is also displayed as LOAD DONT CARE but it was set to CLEAR (although color of the LOAD DONT CARE text changes according to the color of the pixel and because I screenshot a cube I can clearly see a shaded cube made out of colorful LOAD DONT CARE text).

I only specify LOAD_OP_DONT_CARE on stencil (because I don't use it) and on resolve target attachments (because their contents will be overwritten anyway). If I disable multisampling (and thus resolve targets) RenderDoc displays attachments correctly.

Although RenderDoc has this weird behavior, the actual rendered image is displayed as expected (if you just run the app) I also tested this on different GPUs and different OSes. Validation layers also don't say anything. In addition I tried using NVIDIA Nsight and it displays everything as expected. I'm not trying to debug a rendering issue (because everything works correctly in the app) I just noticed RenderDoc behaving weird.

## Steps to reproduce

Attaching an archive with the RenderDoc capture of the issue: 
[capture.zip](https://github.com/baldurk/renderdoc/files/13562366/capture.zip)

1st render pass (depth only pass):
- multisampled depth attachment (loadOp = CLEAR)

2nd render pass (color pass):
- multisampled color attachment (loadOp = CLEAR)
- multisampled depth attachment (loadOp = LOAD)
- resolve color attachment (loadOp = DONT_CARE)

## Environment

* RenderDoc version: 1.30
* Operating System: Windows
* Graphics API: Vulkan 1.2

I also tested older versions of RenderDoc and version 1.17 was the last version of RenderDoc that displayed attachments correctly (even with multisampling enabled).

**Comment by baldurk** [comment]
That commit should fix it I think. I found this sneaky section of the vulkan spec I was unaware of:

> When an image view of a depth/stencil image is used as a depth/stencil framebuffer attachment, the aspectMask is ignored and both depth and stencil image subresources are used.

Which I thought I could use to mask off writes to one aspect of an image when filling out discard patterns.

I don't know why this broke between v1.17 and v1.18, none of that code changed around that time so it should have behaved identically. Either way that fix should be correct.

**Comment by Flone-dnb** [comment]
Yep, I just tried the latest nightly build and everything works correctly. Thanks!
