### ISSUE TITLE
crash when launching instagram on xiaomi8 

### ISSUE THREAD

**Issue by wtmilk** [baldurk/renderdoc#3161]
## Description
when launching application, instagram crash. crash stack is below 
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/dipper/dipper:9/PKQ[1.180729.001](tel:1.180729.001)/[9.8.22](tel:9.8.22):user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: [29891](tel:29891), tid: [29957](tel:29957), name: Lacrima_single_  >>> [com.instagram.android](http://com.instagram.android/) <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2a0
Cause: null pointer dereference
    x0  [0000000000000000](tel:0000000000000000)  x1  [0000000000000000](tel:0000000000000000)  x2  [0000000000000000](tel:0000000000000000)  x3  [0000007016960](tel:0000007016960)c00
    x4  [000000700](tel:000000700)c[503](tel:503)a60  x5  [000000007686](tel:000000007686)c3ea  x6  [0000000000000000](tel:0000000000000000)  x7  [0000000000000000](tel:0000000000000000)
    x8  f5d57ec[627](tel:627)a09e63  x9  [000000700](tel:000000700)e27ca58  x[10 0000000000000406](tel:10 0000000000000406)  x[11 0000007036507](tel:11 0000007036507)edc
    x[12 0000007036507](tel:12 0000007036507)f30  x[13 0000007036507](tel:13 0000007036507)f84  x[14 0000007036507](tel:14 0000007036507)fe4  x[15 0000000000000000](tel:15 0000000000000000)
    x[16 000000700](tel:16 000000700)e[238978](tel:238978)  x[17 00000070](tel:17 00000070)bb[143844](tel:143844)  x[18 000000000000001](tel:18 000000000000001)f  x[19 0000000000000000](tel:19 0000000000000000)
    x[20 00000070](tel:20 00000070)ba4af5d0  x[21 0000007016960](tel:21 0000007016960)c00  x[22 000000700](tel:22 000000700)c[5038](tel:5038)d0  x[23 000000007686](tel:23 000000007686)c3ea
    x[24 0000000000000000](tel:24 0000000000000000)  x[25 000000700](tel:25 000000700)c[505588](tel:505588)  x[26 0000007016960](tel:26 0000007016960)ca0  x[27 0000000000000000](tel:27 0000000000000000)
    x[28 0000000000000000](tel:28 0000000000000000)  x[29 000000700](tel:29 000000700)c[503600](tel:503600)
    sp  [000000700](tel:000000700)c[5035](tel:5035)b0  lr  [000000700](tel:000000700)d40cca8  pc  [000000700](tel:000000700)d26ae08

backtrace:
    #00 pc [000000000014](tel:000000000014)ee08  /data/app/[org.renderdoc.renderdoccmd](http://org.renderdoc.renderdoccmd/).arm64-gHPJLKqFjUmE3-RTg6EMKA==/lib/arm64/[libVkLayer_GLES_RenderDoc.so](http://libvklayer_gles_renderdoc.so/) (WrappedOpenGL::CheckImplicitThread()+36)
    #01 pc [00000000002](tel:00000000002)f0ca4  /data/app/[org.renderdoc.renderdoccmd](http://org.renderdoc.renderdoccmd/).arm64-gHPJLKqFjUmE3-RTg6EMKA==/lib/arm64/[libVkLayer_GLES_RenderDoc.so](http://libvklayer_gles_renderdoc.so/) (glGetError_renderdoc_hooked()+60)
    #02 pc [0000000000](tel:0000000000)bbbc90  /system/framework/arm64/[boot-framework.oat](http://boot-framework.oat/) (offset 0xa4b[000](tel:000)) ([android.content.res.AssetManager.getGlobalAssetCount](http://android.content.res.assetmanager.getglobalassetcount/) [DEDUPED]+[144](tel:144))
    #03 pc [000000000055](tel:000000000055)d04c  /system/lib64/[libart.so](http://libart.so/) (art_quick_invoke_static_stub+[604](tel:604))
    #04 pc [00000000000](tel:00000000000)d[0740](tel:0740)  /system/lib64/[libart.so](http://libart.so/) (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+[232](tel:232))
    #05 pc [0000000000280](tel:0000000000280)d90  /system/lib64/[libart.so](http://libart.so/) (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+[344](tel:344))
    #06 pc [000000000027](tel:000000000027)ada4  /system/lib64/[libart.so](http://libart.so/) (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+[968](tel:968))
    #07 pc [000000000052](tel:000000000052)db34  /system/lib64/[libart.so](http://libart.so/) (MterpInvokeStatic+[204](tel:204))
    #08 pc [000000000054](tel:000000000054)f[514](tel:514)  /system/lib64/[libart.so](http://libart.so/) (ExecuteMterpImpl[+14612](tel:+14612))
    #09 pc [00000000011](tel:00000000011)e6d64  /data/app/[com.instagram.android](http://com.instagram.android/)-S3gJRAVhwuEkQAmhsJuaTQ==/oat/arm64/[base.vdex](http://base.vdex/) ([X.0U7.DQd](http://x.0u7.dqd/)+[420](tel:420))
    #10 pc [0000000000254](tel:0000000000254)aa8  /system/lib64/[libart.so](http://libart.so/) (_ZN3art11interpreterL7ExecuteEPNS_6Th[readERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm](http://readerkns_20codeitemdataaccessorerns_11shadowframeens_6jvalueeb.llvm/).[223931584](tel:223931584)+[488](tel:488))
    #11 pc [000000000025](tel:000000000025)a59c  /system/lib64/[libart.so](http://libart.so/) (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+[216](tel:216))
    #12 pc [000000000027](tel:000000000027)ad88  /system/lib64/[libart.so](http://libart.so/) (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+[940](tel:940))
    #13 pc [000000000052](tel:000000000052)d5ac  /system/lib64/[libart.so](http://libart.so/) (MterpInvokeInterface[+1392](tel:+1392))
    #14 pc [000000000054](tel:000000000054)f[594](tel:594)  /system/lib64/[libart.so](http://libart.so/) (ExecuteMterpImpl[+14740](tel:+14740))
    #15 pc [000000000100](tel:000000000100)c[876](tel:876)  /data/app/[com.instagram.android](http://com.instagram.android/)-S3gJRAVhwuEkQAmhsJuaTQ==/oat/arm64/[base.vdex](http://base.vdex/) (X.0LN.A09+[598](tel:598))
    #16 pc [0000000000254](tel:0000000000254)aa8  /system/lib64/[libart.so](http://libart.so/) (_ZN3art11interpreterL7ExecuteEPNS_6Th[readERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm](http://readerkns_20codeitemdataaccessorerns_11shadowframeens_6jvalueeb.llvm/).[223931584](tel:223931584)+[488](tel:488))
    #17 pc [000000000025](tel:000000000025)a59c  /system/lib64/[libart.so](http://libart.so/) (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+[216](tel:216))
    #18 pc [000000000027](tel:000000000027)bea8  /system/lib64/[libart.so](http://libart.so/) (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+[720](tel:720))
    #19 pc [000000000052](tel:000000000052)de5c  /system/lib64/[libart.so](http://libart.so/) (MterpInvokeVirtualRange+[576](tel:576))
    #20 pc [000000000054](tel:000000000054)f[694](tel:694)  /system/lib64/[libart.so](http://libart.so/) (ExecuteMterpImpl[+14996](tel:+14996))
    #21 pc [000000000100](tel:000000000100)c29c  /data/app/[com.instagram.android](http://com.instagram.android/)-S3gJRAVhwuEkQAmhsJuaTQ==/oat/arm64/[base.vdex](http://base.vdex/) ([X.0LK.run](http://x.0lk.run/)+34)
    #22 pc [0000000000254](tel:0000000000254)aa8  /system/lib64/[libart.so](http://libart.so/) (_ZN3art11interpreterL7ExecuteEPNS_6Th[readERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm](http://readerkns_20codeitemdataaccessorerns_11shadowframeens_6jvalueeb.llvm/).[223931584](tel:223931584)+[488](tel:488))
    #23 pc [000000000025](tel:000000000025)a59c  /system/lib64/[libart.so](http://libart.so/) (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+[216](tel:216))
    #24 pc [000000000027](tel:000000000027)ad88  /system/lib64/[libart.so](http://libart.so/) (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+[940](tel:940))
    #25 pc [000000000052](tel:000000000052)d5ac  /system/lib64/[libart.so](http://libart.so/) (MterpInvokeInterface[+1392](tel:+1392))
    #26 pc [000000000054](tel:000000000054)f[594](tel:594)  /system/lib64/[libart.so](http://libart.so/) (ExecuteMterpImpl[+14740](tel:+14740))
    #27 pc [00000000001](tel:00000000001)b9ee4  /system/framework/[boot-core-oj.vdex](http://boot-core-oj.vdex/) ([java.util.concurrent.ThreadPoolExecutor.runWorker](http://java.util.concurrent.threadpoolexecutor.runworker/)+[162](tel:162))
    #28 pc [0000000000254](tel:0000000000254)aa8  /system/lib64/[libart.so](http://libart.so/) (_ZN3art11interpreterL7ExecuteEPNS_6Th[readERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm](http://readerkns_20codeitemdataaccessorerns_11shadowframeens_6jvalueeb.llvm/).[223931584](tel:223931584)+[488](tel:488))
    #29 pc [000000000025](tel:000000000025)a59c  /system/lib64/[libart.so](http://libart.so/) (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+[216](tel:216))
    #30 pc [000000000027](tel:000000000027)ad88  /system/lib64/[libart.so](http://libart.so/) (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+[940](tel:940))
    #31 pc [000000000052](tel:000000000052)c[630](tel:630)  /system/lib64/[libart.so](http://libart.so/) (MterpInvokeVirtual+[588](tel:588))
    #32 pc [000000000054](tel:000000000054)f[394](tel:394)  /system/lib64/[libart.so](http://libart.so/) (ExecuteMterpImpl[+14228](tel:+14228))
    #33 pc [00000000001](tel:00000000001)b8f80  /system/framework/[boot-core-oj.vdex](http://boot-core-oj.vdex/) ([java.util.concurrent.ThreadPoolExecutor](http://java.util.concurrent.threadpoolexecutor/)$[Worker.run](http://worker.run/)+4)
    #34 pc [0000000000254](tel:0000000000254)aa8  /system/lib64/[libart.so](http://libart.so/) (_ZN3art11interpreterL7ExecuteEPNS_6Th[readERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm](http://readerkns_20codeitemdataaccessorerns_11shadowframeens_6jvalueeb.llvm/).[223931584](tel:223931584)+[488](tel:488))
    #35 pc [000000000025](tel:000000000025)a59c  /system/lib64/[libart.so](http://libart.so/) (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+[216](tel:216))
    #36 pc [000000000027](tel:000000000027)ad88  /system/lib64/[libart.so](http://libart.so/) (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+[940](tel:940))
    #37 pc [000000000052](tel:000000000052)d5ac  /system/lib64/[libart.so](http://libart.so/) (MterpInvokeInterface[+1392](tel:+1392))
    #38 pc [000000000054](tel:000000000054)f[594](tel:594)  /system/lib64/[libart.so](http://libart.so/) (ExecuteMterpImpl[+14740](tel:+14740))
    #39 pc [000000000100](tel:000000000100)ed8e  /data/app/[com.instagram.android](http://com.instagram.android/)-S3gJRAVhwuEkQAmhsJuaTQ==/oat/arm64/[base.vdex](http://base.vdex/) ([X.0MR.run](http://x.0mr.run/)+46)
    #40 pc [0000000000254](tel:0000000000254)aa8  /system/lib64/[libart.so](http://libart.so/) (_ZN3art11interpreterL7ExecuteEPNS_6Th[readERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm](http://readerkns_20codeitemdataaccessorerns_11shadowframeens_6jvalueeb.llvm/).[223931584](tel:223931584)+[488](tel:488))
    #41 pc [000000000051](tel:000000000051)cee4  /system/lib64/[libart.so](http://libart.so/) (artQuickToInterpreterBridge[+1020](tel:+1020))
    #42 pc [0000000000565](tel:0000000000565)efc  /system/lib64/[libart.so](http://libart.so/) (art_quick_to_interpreter_bridge+92)
    #43 pc [000000000055](tel:000000000055)cd88  /system/lib64/[libart.so](http://libart.so/) (art_quick_invoke_stub+[584](tel:584))
    #44 pc [00000000000](tel:00000000000)d[0720](tel:0720)  /system/lib64/[libart.so](http://libart.so/) (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+[200](tel:200))
    #45 pc [000000000045](tel:000000000045)f5a8  /system/lib64/[libart.so](http://libart.so/) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+[104](tel:104))
    #46 pc [0000000000460664](tel:0000000000460664)  /system/lib64/[libart.so](http://libart.so/) (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+[424](tel:424))
    #47 pc [000000000048](tel:000000000048)eab4  /system/lib64/[libart.so](http://libart.so/) (art::Thread::CreateCallback(void*)[+1092](tel:+1092))
    #48 pc [0000000000081](tel:0000000000081)dac  /system/lib64/[libc.so](http://libc.so/) (__pthread_start(void*)+36)
    #49 pc [0000000000023788](tel:0000000000023788)  /system/lib64/[libc.so](http://libc.so/) (__start_thread+68)
## Environment

* RenderDoc version: v1.22
* Operating System: windows 11
* Graphics API: XXX

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing programs that are not your own is not endorsed or allowed for any reason, and I will provide absolutely no support for it.
