### ISSUE TITLE
"Load Last Settings" to remember more than one setting

### ISSUE THREAD

**Issue by tobiaskoppen** [baldurk/renderdoc#3168]
## Description

I frequently switch between two launch configurations (Android and Windows) and it would be great if the "Load Last Settings" button could facilitate this by remembering more than one setting. I know I can recall more settings by using "Save/Load Settings" but that is a bunch more clicks (usually the file dialog will not point to where my .cap files are).

Maybe the "Load Last Settings" button could drop down to reveal two or more of the most recently used settings?
## Environment

* RenderDoc version: v1.30
* Operating System: Windows 10
* Graphics API: OpenGL ES, Vulkan, DX11, DX12

**Comment by baldurk** [comment]
No the 'load last settings' is explicitly only for the _last_ settings, especially if they may be temporary or weren't explicitly saved. Overcomplicating that control is more complexity than it's worth and duplicates functionality already available.

As you say, you can save settings manually and load them. If you don't want to load them via the 'load settings' button you can use file -> recent capture settings, drag & drop the .cap file onto RenderDoc, or double click the .cap file if you have file associations configured.

**Comment by tobiaskoppen** [comment]
Fair enough! I hadn't noticed File -> Recent Capture Settings, that will do nicely.
