### ISSUE TITLE
Why thumbnail width be restricted on 2048?

### ISSUE THREAD

**Issue by POLO-huhu** [baldurk/renderdoc#3182]
## Description
I capture one frame for 4k APP. But I find that thumbnail width is 2048. I search source code find there is a limited maxSize is 2048. 
code:
 d3d11_device.cpp
bool WrappedID3D11Device::EndFrameCapture(DeviceOwnedWindow devWnd)
{
// omit
const uint32_t maxSize = 2048;
// omit
}
This limitation may be due to other reasons, please tech me the reason.
## Environment

* RenderDoc version:  v1.30
* Operating System: win10
* Graphics API: DX11

**Comment by baldurk** [comment]
I'm assuming this is a feature request for a larger thumbnail? Although that's not what you've said as you've been very unclear about what you're actually asking for.

This is not something I am going to change though as there is no value in doing so, the thumbnail is just a preview of the capture output and it is more than sufficient for that.

**Comment by POLO-huhu** [comment]
I get it. The thumbnail is just a preview of the capture output. It doesn't have to be the same size as the original. Thank you.
