### ISSUE TITLE
Solution to #3091: Renderdoc server crashes on HarmonyOS 4.0

### ISSUE THREAD

**Issue by laralex** [baldurk/renderdoc#3187]
## Description

I present **solution** to the issue #3091 which was closed without further investigation. The issue itself is well described in #3091. I have the same environment (HarmonyOS v4.0 mobile phone) and encounter the same issue. 

## Steps to reproduce

When you try to switch replay context Local to the phone's, it says "Running remote server command...". Then on the phone you see RenderDoc activity with black title bar and white screen (no green renderdoc logo), the phone doesn't prompt to give permissions to RenderDoc's modules. After a few seconds the app on the phone crashes and on PC you see "Remote server not running of failed to start".

Meanwhile if you run check Android LogCat (`adb logcat`) you can find an exception, that it can't load the RenderDoc icon, and thus fails to start the Android activity. 
```
FATAL EXCEPTION: main
Process: org.renderdoc.renderdoccmd.arm64, PID: 28295
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.renderdoc.renderdoccmd.arm64/org.renderdoc.renderdoccmd.arm64.Loader}: android.content.res.Resources$NotFoundException: Drawable org.renderdoc.renderdoccmd.arm64:drawable/icon with resource ID #0x7f020000
... <omited>
Caused by: android.content.res.Resources$NotFoundException: Drawable org.renderdoc.renderdoccmd.arm64:drawable/icon with resource ID #0x7f020000
Caused by: java.lang.IllegalArgumentException: width and height must be > 0
```
## Environment

* RenderDoc version: v1.29 or 1.30
* Operating System: Windows 10.0 x64 / HarmonyOS 4.0
* Graphics API: Not relevant

## Solution
Basically HarmonyOS somehow strangely handles Android APK files, in particular it can't find RenderDoc's icon, even though it is totally present in the APK file. To fix it, we need to prevent Android Activity from loading this icon. I do this by patching the RenderDoc's APK files.

Steps to solve (maybe you can do it easier or less hacky, but this is what I've come up with):
1. You need `apktool` https://apktool.org/ (the tool consists of a `.jar` file and a wrapper script)
1. You need Java SDK installed and `JAVA_HOME` environment variable defined to the root of Java SDK
1. Go to RenderDoc's installation folder with the executable file. In subfolder `plugins/android` there should be one or two `.apk` files. For example: 
    ```
    org.renderdoc.renderdoccmd.arm32.apk
    org.renderdoc.renderdoccmd.arm64.apk
    ```
1. To be safe, backup them (e.g. copy as `backup_org.renderdoc.renderdoccmd.arm32.apk`)
1. Create a keystore using tool from Java SDK.
    ```
    keytool -genkey -v -keystore Key_Name.keystore -alias Alias_Name -keyalg RSA -keysize 2048 -validity 10000 
    ```
1. It will start asking questions about password and country/company etc, you can answer anything to those questions, but remember the password
1. Do the following to **BOTH** APK files, replace `<apk_name>`  with the name of RenderDoc's apk and `<folder_name>` with folder name created by `apktool`
    1. (maybe optional, I didn't check) Install some file necessary for the tool.
        ```
        apktool.bat if <apk_name> 
        ```
    1. Unzip the apk into a nearby folder via apktool (**don't use plain unzip/winrar/7z**, it must be done via apktool, in order to recreate the apk later). 
        ```
        apktool.bat d <apk_name> 
        ```
    1. Go to the newly created folder corresponding to this apk
    1. Open `AndroidManifest.xml` in a text editor
    1. Remove mentioning of `drawable/icon.png` (or any other file which caused the exception in logcat)
    1. Recreate a new apk file from the modified folder. Make sure <apk_name> is the same as the original apk.
        ```
        apktool.bat b <folder_name> -o <apk_name>
        ```
    1. Sign the apk using tool from Java SDK
        ```
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore Key_Name.keystore <apk_name> Alias_Name
        ```
    1. Delete old RenderDoc applications from the mobile phone (via adb or Settings→Apps on the phone)
    1. Now when you try to switch context inside RenderDoc on computer, the new apk files should be installed, and you shouldn't receive such exception in adb logcat, and on mobile it should ask you to give permissions to the RenderDoc apks. 
    1. Maybe on computer it still shows the error "Remote server not running or failed to start". Try to switch context a few more times

**Comment by baldurk** [comment]
From your description it sounds like you have confirmed that this is an OS bug and it is a broken vendor customisation of Android, which is fairly common for vendor distributions of Android. I'm glad you found a workaround that works but that is not a solution at all and not feasible to ship with as it just removes the icon entirely.

**Comment by laralex** [comment]
I agree, but still better to provide the workaround for the community. I would appreciate if you could add a link/mention into the original issue  #3091
