### ISSUE TITLE
Shader dissassembly debug view shows wrong line text

### ISSUE THREAD

**Issue by imccown** [baldurk/renderdoc#319]
![renderdoc_shaderlinebug](https://cloud.githubusercontent.com/assets/8538777/17530320/e8a592c2-5e2b-11e6-8573-3339ac597d6a.png)
[ShaderLineBug.zip](https://github.com/baldurk/renderdoc/files/409737/ShaderLineBug.zip)

The file and line number shown in the dissassembly view are correct, but the text it shows for that line is sometimes wrong. The number of lines it is off by seems to increase the further down you get in the file.

The attachment includes the log file and the hlsl shader. This is from the D3D11 SDK sample BasicHLSL11 debugging a pixel on the main model in the scene. This program compiles the shaders at runtime so there should be no discrepancy between the debug data and the shader. It also happens with programs using precompiled shaders.

**Comment by baldurk** [comment]
I think this was limited only to the old debug format (MS changed it between d3dcompiler _43 and _46). The code was accidentally skipping blank lines, which caused the gradual incorrect line text.

**Comment by baldurk** [comment]
I believe this should now be fixed in [v0.31](https://github.com/baldurk/renderdoc/releases/tag/v0.31). If there's something remaining to do, please comment and I'll re-open.
