### ISSUE TITLE
The diagnostic log window is gone

### ISSUE THREAD

**Issue by csdjk** [baldurk/renderdoc#3204]
## Description

The diagnostic log window is gone

## Steps to reproduce

![image](https://github.com/baldurk/renderdoc/assets/33519787/a393cb2e-6441-499e-8fbe-49bb03f18524)

## Environment

* RenderDoc version: v1.29
* Operating System: windows11
* Graphics API: dx

**Comment by baldurk** [comment]
This is not a bug, the diagnostic log is only intended for RenderDoc developers and not for users.

**Comment by csdjk** [comment]
> This is not a bug, the diagnostic log is only intended for RenderDoc developers and not for users.

I want to develop a renderdoc plugin, if there is no diagnostic log, how to debug?

**Comment by quadpixels** [comment]
My quick solution: Build from source, add `RegisterShortcut("ALT+D", this, [this](QWidget *) { showDiagnosticLogView(); });` at the end of `MainWindow::MainWindow(ICaptureContext&)`, and then press `Alt+D` when the UI shows up

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
