### ISSUE TITLE
Unity editor crashes when loading renderdoc using vulkan api

### ISSUE THREAD

**Issue by shchen2017** [baldurk/renderdoc#3208]
## Description
Unity editor crashes when loading renderdoc using vulkan api.
I found that the following modifications caused，this caused vkCreateDevice hook failed.
![image](https://github.com/baldurk/renderdoc/assets/33756431/9473aa76-0d6d-4d71-96ac-86e893b2b6ee)

## Steps to reproduce
1. open unity2020
2. load renderdoc

## Environment
* RenderDoc version: 1.30
* Graphics API: vulkan

**Comment by Zorro666** [comment]
This is a Unity bug not a RenderDoc bug.
I am able to load renderdoc and capture Unity  2022.3.5f1 Vulkan Editor
![image](https://github.com/baldurk/renderdoc/assets/39392/9b489a03-5210-401c-97d8-f3ec5ea5a597)
