### ISSUE TITLE
RenderDoc always selecting wrong gpu in dual gpu PC

### ISSUE THREAD

**Issue by CaTaTo23** [baldurk/renderdoc#3220]
## Description

I have 2 GPUs in my PC, Radeon 6700xt and Nvidia 1070, when I launching anything with Vulkan through RenderDoc or that uses RenderDoc library it always launching on 1070, DRI_PRIME don't work and changing in game engine/app gpu priority affects nothing. Also 6700xt for me always come first in all Vulkan applications by default.

Tested in Godot, Unreal Engine, vkcube

## Steps to reproduce

Install 2 gpu in PC (Radeon and Nvidia)
Launch anything that uses Vulkan on Linux though RenderDoc

## Environment

* RenderDoc version: 1.30
* Operating System: Kubuntu 23.10
* Graphics API: Vulkan

**Comment by baldurk** [comment]
RenderDoc has nothing to do with GPU selection on vulkan programs. In Vulkan it's up to the captured application to select its physical device for use and RenderDoc doesn't play a part in that. On replay RenderDoc uses the closest GPU available to the one used during capture.

You need to look at the programs you are running and see how they select a physical device and whether you can choose that, this isn't a RenderDoc issue.

**Comment by CaTaTo23** [comment]
> RenderDoc has nothing to do with GPU selection on vulkan programs.

No, it definitely forces to run apps on 1070, here is proof of that

https://www.youtube.com/watch?v=XQZPLam9Mb4

also initial 27% of gpu utilization are from nvenc encoder
