### ISSUE TITLE
REnder doc Injection failed: timeout

### ISSUE THREAD

**Issue by Spahbed** [baldurk/renderdoc#3221]
## Description
TRying to run a game (development build) i produced from unity on my POCO m5, game loads on phoen but render doc timesout 10-15 seconds after 

## Steps to reproduce

Install an APK on a XIAMO m5 POCO and try inject render doc to the application

APK is rather large so not uploading here. Although just tested on a mini application and it takes liek a minute to timeout; app runs immediatley

## Environment

Windows 11; latest render doc 1.3

<img width="248" alt="Screenshot 2024-01-17 205032" src="https://github.com/baldurk/renderdoc/assets/36801304/6684dade-b64c-4c95-b2a2-b509bcb9e4ec">

**Comment by Henry-Suen** [comment]
I just happened to have the same issue hours ago. 
The key to my problem is the AndriodManifest.xml > android:debuggable="false"(should be true) even in development build.

I managed to capture frames of my program in the morning but an updated version later , a colleague overrode the debuggable flag, made me suffer the issue you are having.
And I changed the flag back and it works again.

It might sound dumb that there's a clear warning showing "Android application not set up for RenderDoc capture"
but the warning is glitchy itself. It'll show that whether it's true or not, so it became a "cry wolf" to users like me.
I still got that warning even when it's working.

**Comment by Zorro666** [comment]
Please can you check if you can capture and replay these APKs on your device [jake-kart-vk.apk](https://renderdoc.org/jake-kart-vk.apk), [jake-runner-gles3.apk](https://renderdoc.org/jake-runner-gles3.apk).

These APKs are known to work and help to identify if there is a device issue.

**Comment by Spahbed** [comment]
> I just happened to have the same issue hours ago. The key to my problem is the AndriodManifest.xml > android:debuggable="false"(should be true) even in development build.
> 
> I managed to capture frames of my program in the morning but an updated version later , a colleague overrode the debuggable flag, made me suffer the issue you are having. And I changed the flag back and it works again.
> 
> It might sound dumb that there's a clear warning showing "Android application not set up for RenderDoc capture" but the warning is glitchy itself. It'll show that whether it's true or not, so it became a "cry wolf" to users like me. I still got that warning even when it's working.

Where are you changing that setting

**Comment by Spahbed** [comment]
> Please can you check if you can capture and replay these APKs on your device [jake-kart-vk.apk](https://renderdoc.org/jake-kart-vk.apk), [jake-runner-gles3.apk](https://renderdoc.org/jake-runner-gles3.apk).
> 
> These APKs are known to work and help to identify if there is a device issue.

Can confirm it also gets the same error with both of these; timeout; app runs though

**Comment by Henry-Suen** [comment]
> > I just happened to have the same issue hours ago. The key to my problem is the AndriodManifest.xml > android:debuggable="false"(should be true) even in development build.
> > I managed to capture frames of my program in the morning but an updated version later , a colleague overrode the debuggable flag, made me suffer the issue you are having. And I changed the flag back and it works again.
> > It might sound dumb that there's a clear warning showing "Android application not set up for RenderDoc capture" but the warning is glitchy itself. It'll show that whether it's true or not, so it became a "cry wolf" to users like me. I still got that warning even when it's working.
> 
> Where are you changing that setting

Assets/Plugins/Android/AndroidManifest.xml

It appears that your issue is not related to this, since Zorro666 provided you with APKs that are possibly debuggable.

Try to uninstall the render doc apps on your phone and link the PC again?

**Comment by baldurk** [comment]
If those APKs also fail can you please check with the latest RenderDoc nightly build? It includes some workarounds for broken devices that don't work properly, and this may fix the problem you're seeing.

**Comment by Spahbed** [comment]
> > > I just happened to have the same issue hours ago. The key to my problem is the AndriodManifest.xml > android:debuggable="false"(should be true) even in development build.
> > > I managed to capture frames of my program in the morning but an updated version later , a colleague overrode the debuggable flag, made me suffer the issue you are having. And I changed the flag back and it works again.
> > > It might sound dumb that there's a clear warning showing "Android application not set up for RenderDoc capture" but the warning is glitchy itself. It'll show that whether it's true or not, so it became a "cry wolf" to users like me. I still got that warning even when it's working.
> > 
> > 
> > Where are you changing that setting
> 
> Assets/Plugins/Android/AndroidManifest.xml
> 
> It appears that your issue is not related to this, since Zorro666 provided you with APKs that are possibly debuggable.
> 
> Try to uninstall the render doc apps on your phone and link the PC again?

This worked. IT still isntalls two render docs, I dont know why; both different sizes

ISsue im having now is; ITs capturing stuff but doesnt display any duration for the events; that part was working when captured straight from Unity

Tested that on kart and my apk both dont show duration of anything
<img width="834" alt="Screenshot 2024-01-21 215513" src="https://github.com/baldurk/renderdoc/assets/36801304/0fd191c8-072c-4b94-b14f-c775527677fd">

<img width="939" alt="Screenshot 2024-01-21 215230" src="https://github.com/baldurk/renderdoc/assets/36801304/4b99e6b8-2f5b-42cc-83c6-0de3144d629e">

**Comment by Henry-Suen** [comment]
Try to click this button to refresh the duration.
![Snipaste_2024-01-22_09-17-32](https://github.com/baldurk/renderdoc/assets/45254361/526e38b1-c387-4164-ada4-fa9d60934aae)

**Comment by Spahbed** [comment]
> Try to click this button to refresh the duration. ![Snipaste_2024-01-22_09-17-32](https://private-user-images.githubusercontent.com/45254361/298429687-526e38b1-c387-4164-ada4-fa9d60934aae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4ODY3MjAsIm5iZiI6MTcwNTg4NjQyMCwicGF0aCI6Ii80NTI1NDM2MS8yOTg0Mjk2ODctNTI2ZTM4YjEtYzM4Ny00MTY0LWFkYTQtZmE5ZDYwOTM0YWFlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAxMjAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MDgzNzAyZWFlZmQ1YzhmNDgzNzUxNTNkYjI0ZWNkMmM1MjQ1NDEyMGZmYmFhNmRkYWQ2MjU5MmVkYjk1OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OHGGDKSbXeRNGS64y_ci7bxAM9MW9HdpeV4BCNfUD3A)

Yep tried that; just says 0 for everything
<img width="931" alt="Screenshot 2024-01-21 231439" src="https://github.com/baldurk/renderdoc/assets/36801304/511c5b13-51fe-41f1-9cab-df6342229974">

Also get this error showing up at the bottom, not sure if relevant

**Comment by baldurk** [comment]
@Spahbed I'm unclear if your issue is solved or not. Please do not start describing different unrelated bugs here in this issue as that will cause confusion and make it less likely for anything to be fixed. Once this bug is resolved if you have a different bug please open a new issue.

You didn't say if you did as asked previously and ran with the most recent nightly build. Is that how you are now able to capture? If so it is most likely that your device is broken and the workaround in the recent nightly build has avoided it.

@Henry-Suen Please do not try to get involved in bug diagnosis and suggest things for users to try when we are trying to investigate a bug. Trying to narrow down the cause of bugs especially on a platform as fundamentally broken and awful as Android is difficult enough with only RenderDoc developers so adding in additional confusion with other instructions and people who may not understand how RenderDoc works or what is wrong is very likely to cause problems.

**Comment by Henry-Suen** [comment]
> @Spahbed I'm unclear if your issue is solved or not. Please do not start describing different unrelated bugs here in this issue as that will cause confusion and make it less likely for anything to be fixed. Once this bug is resolved if you have a different bug please open a new issue.
> 
> You didn't say if you did as asked previously and ran with the most recent nightly build. Is that how you are now able to capture? If so it is most likely that your device is broken and the workaround in the recent nightly build has avoided it.
> 
> @Henry-Suen Please do not try to get involved in bug diagnosis and suggest things for users to try when we are trying to investigate a bug. Trying to narrow down the cause of bugs especially on a platform as fundamentally broken and awful as Android is difficult enough with only RenderDoc developers so adding in additional confusion with other instructions and people who may not understand how RenderDoc works or what is wrong is very likely to cause problems.

That's rude for commuty member who trys to help others.  If you read the the words properly,  he solved it by uninstalled the render doc apps and reinstalled them by linking again.  

You have my respect for your contributions and skills But i don't need your lecturing. 

 I can't believe you have patience with harassing issues but not with an enthusiast.

**Comment by Spahbed** [comment]
> oc works or what is wrong is very l

The timeout issue was fixed yes; Ill open another for the capture issue
