### ISSUE TITLE
UWP, Microsoft Store support

### ISSUE THREAD

**Issue by Doliman100** [baldurk/renderdoc#3229]
## Description

Since the original request, several tools have been released for debugging UWP apps, so this should be possible. Maybe it is worth consider the following request again? https://github.com/baldurk/renderdoc/issues/920
1. x64dbg accepts process id and thread id as command line arguments to work in pair with PLMDebug. Unfortunately, restarting the application also requires restarting the debugger.
https://github.com/x64dbg/x64dbg/issues/1698
2. WinDbg
https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-a-uwp-app-using-windbg
3. PIX can run UWP apps out of the box.
![image](https://github.com/baldurk/renderdoc/assets/5512376/9f10dc9f-cfec-47eb-9876-0d4af4be80f8)

The most convenient way is to be able to launch UWP applications directly from RenderDoc, just like in PIX. But any other way is ok, if it is easier to implement.
It would be useful to be able to view the callstack and use other features that PIX doesn't have.

## Environment

* RenderDoc version: v1.30
* Operating System: Windows 11
* Graphics API: D3D12

**Comment by baldurk** [comment]
No there are no plans to ever support UWP. As in the isssue you linked, my recommendation if you want to use RenderDoc is to make a proper build of your program so that you have a normal executable to run.
