### ISSUE TITLE
Capture not displaying any durations

### ISSUE THREAD

**Issue by Spahbed** [baldurk/renderdoc#3230]
## Description

My captures from android phone arenmt displaying any durations for the events; see picture below. It works if i capture directly from Unity on the same PC though, but not on mobile connection. Tested with my APK and the Kart APK here used to debug. HAve tried clickuing the timer button which just sets durations to 0 instead of a dash

## Steps to reproduce

I click capture now while the games playing
Capture is 230mb so is that possible to upload here or externally only?

## Environment

* RenderDoc version: 1.30
* Operating System: Windows 11
* Graphics API: ??

Phone is Xiaomi Poco M5

<img width="939" alt="Screenshot 2024-01-21 215230" src="https://github.com/baldurk/renderdoc/assets/36801304/f08b2d39-f20f-4b14-966a-31dd792c36db">
<img width="834" alt="Screenshot 2024-01-21 215513" src="https://github.com/baldurk/renderdoc/assets/36801304/df9bb6fe-0b32-4175-b7a4-4973684b4bc6">

**Comment by baldurk** [comment]
If you can share a capture that reproduces this I can check it, though I suspect that it's unlikely I will find the same problem as I'm able to take timestamps on a couple of mobile devices I tested. I believe 230MB is too large to attach to github so yes using a file sharing service like dropbox, google drive, onedrive, mega.nz, etc would be necessary.

If you only see 0 for the duration of every draw after timing then my guess is that your mobile device doesn't support or implement timestamps, which may make sense as generally speaking drawcall-based timestamps on mobile GPUs are not meaningful or possible anyway. Do you have any other mobile devices you can test with, ideally from a different manufacturer?

As something else to try, if you go to the performance counter viewer and enable the 'generic' set of counters, do you get any values back for any of those? You may only have 'GPU Duration' and 'Samples passed' depending on your mobile device's capabilities.

**Comment by cmannett85-arm** [comment]
Please can you post the GPU driver version?  You can easily find it by opening Chrome and going to `chrome://gpu`, then scroll down to `Driver Information` and paste the contents of the `GPU0` row.

**Comment by Spahbed** [comment]
> to try, if you go to the performance counter viewer and enable the 'generic' set of counters, do you get any values back for any of those? You may only have 'GPU Duration' and 'Samples passed' depending on your mobile device's capabilities.

https://file.io/eKUy5Dfaw2rM

Capture there

I have two other phones but I think i need a new cable as the app/pc cant see them, gonna get them tommorow

Performance counter sees; samples not durations
<img width="931" alt="Screenshot 2024-01-21 231439" src="https://github.com/baldurk/renderdoc/assets/36801304/00505032-a272-4595-b26c-b094cec2b5df">

GPu Driver info:
VENDOR= 0x8086, DEVICE=0x5917, SUBSYS=0x837f103c, REV=7, LUID={0,92495}, DRIVER_VENDOR=Intel, DRIVER_VERSION=31.0.101.2111 *ACTIVE*

**Comment by baldurk** [comment]
OK I don't think it's capture specific as I'm able to get timings fine for that capture. I suspect it is a hardware issue with your device but we can try to confirm that.

Can you share a screenshot showing the performance counter viewer, and also export the results to a csv and attach here?

Could you also go to Help -> Send Error Report **after** having gathered performance counters so I can examine the report?

I think Cam's suggestion above to check the driver on the device was to go to `chrome://gpu` on the device itself. The driver on your local machine is not relevant for this, as the important part is what the device is capable of. I can also see the driver in the capture though so I'm not sure if more information will be available that way.

**Comment by Spahbed** [comment]
> OK I don't think it's capture specific as I'm able to get timings fine for that capture. I suspect it is a hardware issue with your device but we can try to confirm that.
> 
> Can you share a screenshot showing the performance counter viewer, and also export the results to a csv and attach here?
> 
> Could you also go to Help -> Send Error Report **after** having gathered performance counters so I can examine the report?
> 
> I think Cam's suggestion above to check the driver on the device was to go to `chrome://gpu` on the device itself. The driver on your local machine is not relevant for this, as the important part is what the device is capable of. I can also see the driver in the capture though so I'm not sure if more information will be available that way.

That screenshot had the the performance page on it:
<img width="953" alt="Screenshot 2024-01-22 194237" src="https://github.com/baldurk/renderdoc/assets/36801304/dacec5c9-8a62-46da-a1fc-87cb8332d874">


Error log here: https://file.io/3RjyJc9puU54

IF you can get timings from that capture then its in issue on my pc/the software?

**Comment by baldurk** [comment]
It won't be anything to do with your PC, the problem lies on your mobile device.

Can you try running [this modified build](https://renderdoc.org/RenderDoc_timestamp_logging_64.zip) of RenderDoc and do the same steps again: Fetch the performance counters and then send an error report with a note that it's about this issue. You can just send the report, you don't need to extract any files or attach them here manually.

**Comment by Spahbed** [comment]
> It won't be anything to do with your PC, the problem lies on your mobile device.
> 
> Can you try running [this modified build](https://renderdoc.org/RenderDoc_timestamp_logging_64.zip) of RenderDoc and do the same steps again: Fetch the performance counters and then send an error report with a note that it's about this issue. You can just send the report, you don't need to extract any files or attach them here manually.

Tried. Same issue
<img width="957" alt="Screenshot 2024-01-22 222856" src="https://github.com/baldurk/renderdoc/assets/36801304/cc03f39e-3e05-43c0-8bcf-9d9044f56cd4">


Send error report too: https://renderdoc.org/bugreporter/report/OeEDPYIZOk4B5

**Comment by baldurk** [comment]
OK thanks, that does confirm that the device itself is just broken - it does not report a valid timestamp period so durations can't be calculated. There's no way to fix this and meaningfully interpret the results so 0 ends up being displayed.
