### ISSUE TITLE
Respect the XDG base directory specification’s environment variables

### ISSUE THREAD

**Issue by astralchan** [baldurk/renderdoc#3232]
## Description

Duplicate of [723](https://github.com/baldurk/renderdoc/issues/723)...

Currently, renderdoc [always makes](https://github.com/baldurk/renderdoc/blob/86585b685cfefa56e2aa757a698b0202bd3bd5dc/renderdoc/os/posix/linux/linux_stringio.cpp#L610) `~/.renderdoc`. The [XDG Base Directory Speficiation](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) lays out an environment for unix desktop apps. While there are several not implemented, not respecting `XDG_CONFIG_HOME`, especially if you just make a directory in the base home directory, tends to clutter a user's home directory.

A simple C implementation could look like:

```c
char *configPath = getenv("XDG_CONFIG_HOME");
if (configPath == NULL) {
    configPath = getenv("HOME");
    strcat(configPath, "/.config");
}
strcat(configPath, "/renderdoc");
```

## Environment

* RenderDoc version: 1.21
* Operating System: Void Linux
* Graphics API: OpenGL

**Comment by baldurk** [comment]
This has been discussed before and from previous conversations with other people who have asked for XDG support there is no compromise between what I'm willing to implement and what they want that is acceptable to both sides, so there is no plan to ever support XDG configs.

#723 was specifically about interop with the vulkan loader where the layer was required to go into the location that matches what the loader was looking for.

**Comment by astralchan** [comment]
> This has been discussed before and from previous conversations with other people who have asked for XDG support there is no compromise between what I'm willing to implement and what they want that is acceptable to both sides, so there is no plan to ever support XDG configs.
> 
> #723 was specifically about interop with the vulkan loader where the layer was required to go into the location that matches what the loader was looking for.

723 was about `XDG_DATA_HOME`

Even if `XDG_CONFIG_HOME` isn't read, redirecting the default location to `$HOME/.config/renderdoc` could be nice.

[1741](https://github.com/baldurk/renderdoc/pull/1741)
Linked relevant PR for additional context.
