### ISSUE TITLE
Capture duration not recorded

### ISSUE THREAD

**Issue by Spahbed** [baldurk/renderdoc#3234]
## Description

Reopening this thread because i just tested render doc an a different phone: Samsung galaxy s9+. And the very same issue; no capture durations being recorded
## Steps to reproduce

Run the apk like in the other thrread; through render doc; hit capture ingame

## Environment

* RenderDoc version: 1.30
* Operating System: Android 13
* Graphics API: ?? not sure Smasung galaxy s9+

See screenshot
<img width="953" alt="Screenshot 2024-01-24 170936" src="https://github.com/baldurk/renderdoc/assets/36801304/19cabbfa-fa7a-4bc4-95a7-7bda64f15314">

**Comment by baldurk** [comment]
This presumably just means that the second device you've tested with is broken in the same way as the first. Android is a platform where features and devices are broken so commonly that everything working correctly is a rarity. RenderDoc displays 0.0 for all durations like that when the timestamps are broken on the device.

**Comment by Spahbed** [comment]
I just tested the kart apk too and it fails too, although differently

It shows no memory error and no times; but when i click timer it freezes so just displays dashes

IF its android issues then how are you supposed to test/use render doc. I mean like 50% of people use android devices to play games so whats the other options

**Comment by Spahbed** [comment]
Also I dont understand as you said before that you were able to open my capture and read the durations?

**Comment by baldurk** [comment]
The devices I was testing with do not have broken timestamps so I'm able to obtain the event durations, although in general they don't produce useful information since per-drawcall timestamps are not meaningfully possible on mobile GPUs so it's not a big difference either way.

In general how to develop on Android when it is so broken is a good question, but not one I have the answer to. This bug is not a flaw that can be worked around, the information obtained cannot be interpreted meaningfully.

**Comment by Spahbed** [comment]
So what phone can I get that it will work on. I just want to GPU debug my game

**Comment by baldurk** [comment]
Event durations are not used at all for debugging, and as I say even on working mobile devices the information they produce is almost useless. If the lack of durations is the only problem you encounter on your phone then there is nothing stopping you from debugging your game.

**Comment by Spahbed** [comment]
> Event durations are not used at all for debugging, and as I say even on working mobile devices the information they produce is almost useless. If the lack of durations is the only problem you encounter on your phone then there is nothing stopping you from debugging your game.

I thought it was the main thing to look at?

OTherwise how doy ou know whats causign a bottleneck ie; I profiled it staright from unity and i can see my trees take a huge time duratioon up and the game lags when they coem in

I was told to test that and then change the shader to non transulecent/ opaque or somethigng to see difference

**Comment by baldurk** [comment]
It sounds like you're wanting to profile, which is not the same as debugging. RenderDoc is a debugger, not a profiler.

**Comment by Spahbed** [comment]
> It sounds like you're wanting to profile, which is not the same as debugging. RenderDoc is a debugger, not a profiler.

Potentially. I just need to see the event durations for items rendered. Render doc has the slot for it but not working on any of my phones. Is there anything else you recommend for profiling, not debugging as you call it?

**Comment by baldurk** [comment]
I'm not familiar with profiling tools on Android so I don't have anything specific to recommend.
