### ISSUE TITLE
Unrecognized file format

### ISSUE THREAD

**Issue by e2002e** [baldurk/renderdoc#3235]
## Description

Launching RenderDoc with an ELF as argument opens a popup box that says:
"Couldn't open file, file format is unrecognized. file magic number is 464c457f".

## Steps to reproduce

Under linux:
`qrenderdoc untitled`

## Environment

* RenderDoc version: 1.30
* Operating System: Debian 12
* Graphics API: OpenGL

Lattest nvidia drivers

**Comment by baldurk** [comment]
Passing an ELF file as a parameter to qrenderdoc is not supported. The error you get is exactly what it sounds - it tries to open the file and does not recognise the file format.

To capture a program launch the UI normally and then select the executable you want to launch from the launch executable panel. See [the documentation on getting started using RenderDoc](https://renderdoc.org/docs/getting_started/quick_start.html).
