### ISSUE TITLE
Incorrect constant buffer bytes needed

### ISSUE THREAD

**Issue by niello** [baldurk/renderdoc#324]
It seems that constant buffer info at least at the Vertex Shader stage shows incorrect 'needed' size. It counts each floatX variable to be 4 bytes, independently of X.

Buffers:

cbuffer Buffer0: register(b0)
{
	matrix	A;
	float3	B;
}

cbuffer Buffer2: register(b2)
{
	struct
	{
		float4 C;
		float4 D;
		float2 E;
	} Something;
}

cbuffer Buffer3: register(b3)
{
	float2 F;
}

RenderDoc output:

![bug](https://cloud.githubusercontent.com/assets/2044092/17650916/97a9f0a6-625a-11e6-839e-ce0936c3e0a0.png)

**Comment by baldurk** [comment]
Looks like this was a bug specifically with the case when reflection data is stripped from the shaders, and some default data is generated - it was missing a multiply by `sizeof(float)`.

**Comment by baldurk** [comment]
I believe this should now be fixed in [v0.31](https://github.com/baldurk/renderdoc/releases/tag/v0.31). If there's something remaining to do, please comment and I'll re-open.
