### ISSUE TITLE
Rightclick-copy doesn't work on stencil state

### ISSUE THREAD

**Issue by hrydgard** [baldurk/renderdoc#3240]
## Description

It would be nice to be able to copy out the full stencil state to text, so I don't have to type it all up into notepad or taking screenshots when doing my investigations.

Rightclicking and choosing the Copy item looks like it should work, but doesn't actually seem to copy anything.

![image](https://github.com/baldurk/renderdoc/assets/130929/63514916-0e11-4399-8c22-0e0f85b2e640)

## Steps to reproduce

Open any RenderDoc capture with stencil stuff. Go to the pipeline viewer, FS tab, and rightclick the stencil state and choose Copy. Nothing happens.

## Environment

Windows 10, RenderDoc v1.31

**Comment by baldurk** [comment]
As a side note, you may find it helpful to export the state to HTML for comparison/large scale copying.

**Comment by hrydgard** [comment]
Yeah, that's not a bad idea! Also, obviously, probably treat this as absolute minimum priority, since copy not working here isn't really blocking any real workflow. I was just surprised it didn't do anything.

**Comment by Zorro666** [comment]
Example outputs after the fix

D3D12 `Front Greater Keep Keep Replace FF FF 55`
D3D11 `Front Greater Keep Keep Replace`
GL `Front Greater Keep Keep Replace FF FF 55`
Vk `Front Always Keep Keep Replace FF FF 01`
