### ISSUE TITLE
CreateRootSignature internally refcount and return an existing object if compatible

### ISSUE THREAD

**Issue by galop1n** [baldurk/renderdoc#325]
Two calls to CreateRootSignature return the same pointer if the root signature match a previously created object already, by doing so, it breaks the internal wrapping registration.

Repro steps : Call CreateRootSignature twice with the same arguments

**Comment by galop1n** [comment]
Fixed in PL#326, following the ssame logic as in d3d11 with blendstates

**Comment by baldurk** [comment]
Should be sorted by the D3D12 stuff I pushed today. I also merged in a couple of your changes from #326 where still possible - thank you for that! The rest will come naturally I think.

I'm going to work on it more next week so hopefully it can get to a point where there's more supported than broken when testing on your code :).

**Comment by baldurk** [comment]
This should be resolved in v0.32. If something's still not right in the latest build then let me know and I'll re-open and investigate.
