### ISSUE TITLE
Segmentation fault when opening a frame capture

### ISSUE THREAD

**Issue by troibe** [baldurk/renderdoc#3254]
## Description

I'm trying to follow the getting started tutorial and using the `debugmarker` example from Sascha Willems.
Capturing a frame seems to work as expected (at least in the UI it looks like it does).
However when opening the captured frame I run into a segmentation fault.
The `debugmarker` program continues to run as expected.

## Steps to reproduce

- Run `debugmarker` example from within renderdoc
- Capture a frame and open it

## Environment

* RenderDoc version: v1.31, v1.30, Nightly 2024-02-15
* Operating System: Ubuntu 22.04
* Linux Graphics Information: RENOIR (renoir, LLVM 15.0.7, DRM 3.54, 6.5.0-17-generic)
* GPU: AMD Radeon RX Vega 7
* Graphics API: Vulkan

## Next steps

Is there maybe an existing capture for a RENOIR based sytem that I could try to open?
That way I can verify that either the issue is during capture or during opening.
Would posting my recorded capture be helpful for you?
If you have any further debugging advice please tell me.

**Comment by troibe** [comment]
I just used `VK_ICD_FILENAMES Set /my/path/vk_swiftshader_icd.json` and launched `VK_ICD_FILENAMES=/mypath/vk_swiftshader_icd.json ./qrenderdoc`.
I then went into `Settings > Replay > GPU Selection Override` and picked SwiftShader.
With SwiftShader as a driver capturing and opening the frame works as expected.

Using renderdoc with SwiftShader was my main goal anyways so the issue above isn't that critical for me.
I just assumed using my built-in GPU would be easier to start out with.
However, I'm happy to help debugging the issue on the RENOIR GPU.

**Comment by baldurk** [comment]
If changing drivers fixes the problem then that suggests it may be the driver crashing in the first place. Are you able to attach a debugger and see where it's crashing? If you can confirm that it's crashing in the driver then the issue should be reported there first.

**Comment by troibe** [comment]
We can close this.
I just built `qrenderdoc` from source and it worked now on my RENOIR GPU.
After that I went back and tried the pre-built binary, which worked as well.
My suspicion is that one of the dependencies required for the source build was also missing for the pre-built binary.
I'm not sure why this was not an issue when using SwiftShader as a driver.
