### ISSUE TITLE
Nothing is recorded when (Vulkan) application never presents frames

### ISSUE THREAD

**Issue by haasn** [baldurk/renderdoc#3255]
## Description

I am trying to debug my vulkan test suite by making a renderdoc capture, but since this test suite does not render any frames, renderdoc does not record anything.

## Steps to reproduce

1. Create a headless vulkan application that does not present frames, but still runs rendering commands, transfers textures, or otherwise.
2. Try to `renderdoccmd capture` it

An example is the [https://code.videolan.org/videolan/libplacebo](libplacebo) test suite.

## Environment

* RenderDoc version: renderdoccmd x64 v1.31 built from NO_GIT_COMMIT_HASH_DEFINED
* Operating System: openSuSE Tumbleweed @ Linux xor 6.6.11-1-default #1 SMP PREEMPT_DYNAMIC Thu Jan 11 08:01:39 UTC 2024 (05ae4ad) x86_64 x86_64 x86_64 GNU/Linux
* Graphics API: Vulkan

## Additional notes

I am aware of the renderdoc frame capture API, but this is too involved for my use case - I simply want to record the entire stream of commands in such a way that I can view it in e.g. `qrenderdoc`, without having to spend half an hour writing boilerplate code for loading the renderdoc DLL, initializing it, and wrapping a start/stop call around my entire application. Never mind that committing such debug code to `git master` would be very poor form, and thus this effort would have to be duplicated by *all* devs.

I expect renderdoc to be capable of recording the API calls from headless vulkan applications *out of the box*, without extensive modification of the application.

**Comment by baldurk** [comment]
Using the in-application API for this is the intended solution for programs where present boundaries do not provide a delineation of frames, and I do not intend to ever support a 'capture everything' mode.

Please also note that `renderdoccmd` is an internal program and not user facing and is not directly supported, you should launch your program from `qrenderdoc`.

**Comment by haasn** [comment]
> I do not intend to ever support a 'capture everything' mode.

Is there a specific reason for this? Would you accept a PR adding this functionality?

*Edit:* Also, what about, for example, a simple vulkan layer that merely hooks `vkCreateInstance / vkDestroyInstance` and places the appropriate renderdoc API call around each? I will try and write something like this for my own use, so I don't have to continuously re-invent the wheel just to use renderdoc in various projects.

**Comment by baldurk** [comment]
It is not how RenderDoc is intended to function as it's a frame-capture based debugger that is built around capturing the a given subset of work. I don't want to take on the support burden or encourage that kind of workflow of capturing an unbounded amount of work. If someone wants to they can use the in-application API to start and stop captures at arbitrary points, but I suspect it is unlikely to scale unless their program is quite small.

I would not accept any PR that tries to add that functionality, no.

Writing a layer like that I suspect you will run into challenges with layer ordering, and I'm not sure exactly when it will be valid to call the in-application API as it is only intended to be called by applications outside of those functions and not part way through their evaluation. If you wanted to try then you could of course, but you'd be on your own to fix any problems you encounter. In my experience integrating the in-application API has not been an issue for projects before, e.g. the vulkan CTS has the exact kind of integration needed for what you're describing.

**Comment by dorian-apanel-intel** [comment]
@haasn 
For small simple tests, you might want to try this change:

```
diff --git a/renderdoc/driver/vulkan/wrappers/vk_device_funcs.cpp b/renderdoc/driver/vulkan/wrappers/vk_device_funcs.cpp
index 9514d3aeb..b3cc40dbc 100644
--- a/renderdoc/driver/vulkan/wrappers/vk_device_funcs.cpp
+++ b/renderdoc/driver/vulkan/wrappers/vk_device_funcs.cpp
@@ -4490,6 +4490,12 @@ void WrappedVulkan::vkDestroyDevice(VkDevice device, const VkAllocationCallbacks
     m_MemoryFreeThread = 0;
   }
 
+  // Save capture if active
+  if(IsActiveCapturing(m_State))
+  {
+    RenderDoc::Inst().EndFrameCapture(DeviceOwnedWindow(LayerDisp(m_Instance), NULL));
+  }
+
   // flush out any pending commands/semaphores
   SubmitCmds();
   SubmitSemaphores();

```   
And just start test from Renderdoc with queueCapture frame 0.
Assuming your test does not call vkQueuePresent and calls `vkDestroyDevice` it will write everything to a capture.

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
