### ISSUE TITLE
SPIRV shader debugger: `OpDebugValue` does not update the value of an vector element.

### ISSUE THREAD

**Issue by csyonghe** [baldurk/renderdoc#3264]
## Description

When debugging SPIRV shader that uses `OpDebugValue` to update an element of a `OpDebugTypeVector` debug variable, the variable value does not change in the debug watch window.

## Steps to reproduce
[repro.zip](https://github.com/baldurk/renderdoc/files/14442738/repro.zip)
- Open the attached repro file in top-of-tree render doc.
- Select the `vkCmdDispatch` command from event browser.
- Goto "Pipeline State" tab, click "Debug" button to debug the compute shader.
- Step through line 75 of the shader source.
- Should expect `t.memberB` to have updated vector value, but it is not updated.

## Environment
* RenderDoc commit: [70b79d7](https://github.com/baldurk/renderdoc/commit/70b79d73e7437ff1bf9354f46d71c1860fcb8694)
* Operating System: Windows 11
* Graphics API: Vulkan 1.2/SPIRV 1.5

**Comment by Zorro666** [comment]
The construction of using `DebugValue` to index into a vector and using `OpAccessChain` through a pointer to a structure member to modify the y-component is not currently handled by the RenderDoc source level debugging.

Source
```
    t.memberB = float3(1, 2, 3);
    t.memberB.y = 4.0;
```

SPIRV `slang`
```
%167 = OpAccessChain %_ptr_Function_v3float %t %int_1
       OpStore %167 %168
%175 = OpAccessChain %_ptr_Function_float %167 %int_1
       OpStore %175 %float_4
```

For reference: SPIRV `glslang` construction which does work with RenderDoc source debugging
```
%86 = OpAccessChain %_ptr_Function_v3float %t %int_1
      OpStore %86 %84
%89 = OpAccessChain %_ptr_Function_float %t %int_1 %uint_1
      OpStore %89 %float_4
```

**Comment by csyonghe** [comment]
The difference with glslang and slang's own spirv backend (enabled with `-emit-spirv-directly` in `slangc`) is that Slang uses more SSA registers than explicit `OpVar`s and is relying on `OpDebugValue` to update a debug variable. Therefore we don't use `OpDebugDeclare` to link a debug variable with an actual variable as done in glslang, but rely more heavily on `OpDebugValue`.
