### ISSUE TITLE
Unreal Engine Android : Injection failed....

### ISSUE THREAD

**Issue by cppgod17** [baldurk/renderdoc#3273]
## Description
Hello, I'm trying to debug my Android game written in Unreal Engine, I built the project in development mode and disabled for distribution, but renderdoc writes that "Android application not set up for RenderDoc capture", it seems to me that I did everything to it worked, I would be very glad if you could help me

## Steps to reproduce
1. download apk file mail, i send apk link to yourr mail from cppgod17@gmail.com
2. connect phone to pc with enabled developer mode, and enabled usb debugging,
3. choose my device in the Render Doc
4. Launch the application, (its called like "my bundlename" + com.epicgames.ue4.SplashActivity (idk its normal or not)( its normally launched on my devices, but after few second i will see
![image](https://github.com/baldurk/renderdoc/assets/46503223/2f7d6fa0-444a-4507-80c6-1d9c074f299a)

## Environment

My Device Xiaomi 10T Pro

**Comment by cppgod17** [comment]
Also i can't attach to active process, because when i launch my game, render doc is not see it

**Comment by baldurk** [comment]
The apk you shared is not set up for RenderDoc capture as it is not debuggable. You said you saw the error message about this and it is exactly correct about the problem, so there is no RenderDoc bug here:

![image](https://github.com/baldurk/renderdoc/assets/661798/f17cef9c-0e0f-4bdc-a2b2-0e28d5d1259d)

The exact mechanism varies by engine and build process so I can't help you directly with that. If you did uncheck 'for distribution' then maybe there are other steps that need to be taken, but that is up to you and the engine that you're using this isn't something RenderDoc related.
