### ISSUE TITLE
Missing a donation link

### ISSUE THREAD

**Issue by jeremyabel** [baldurk/renderdoc#328]
This tool has really been invaluable for those times when I'm deep inside the Unreal 4 render engine trying to make it do stuff it was never designed for. I'd love to throw some beer money your way just for the sheer number of hours this tool has saved me, but I can't seem to find a donation link. Sounds like a bug to me!

**Comment by baldurk** [comment]
I appreciate the thought, but I wouldn't feel comfortable accepting donations. I am currently contracting on RenderDoc so I'm able to work on it full time, there's no need for anything else - I'm just glad the tool is useful to you.

If you want to do something - make sure you report any bugs you run into or request any features :smile:. Either here or directly contacting me over email. Bonus points for encouraging any others you know using the tool to do the same!
