### ISSUE TITLE
Smoothly capture several sequential frame

### ISSUE THREAD

**Issue by WinnieHo** [baldurk/renderdoc#3286]
## Description

When I use "capture 10 sequential frame(s)",  the game will be lag or forzen. Is there a way to smoothly operate the game when apply "capture 10 sequential frame(s)"?

## Environment

* RenderDoc version: 1.31
* Operating System: Windows 11
* Graphics API: OpenGL

**Comment by baldurk** [comment]
Capturing a frame is an expensive process, except in very small or trivial rendering examples. It will take many seconds to capture a frame so no there is no way to capture 10 frames without any interruption.
