### ISSUE TITLE
Renderdoc Support for embedded systems

### ISSUE THREAD

**Issue by P-S-Y-S-U** [baldurk/renderdoc#3289]
## Description

Hi, 

I'm trying to use renderdoccmd tool to capture frames of our armv7e applications but it fails to connect to the program during initialisation stage. The host system is a TV board. The TV has a Wayland Compositor system, So I'm trying to capture frames of Wayland server and client applications. 

All of these applications are using OpenGLES for rendering.

Renderdoc binaries built with the following configuration.

> ENABLE_EGL=ON
> ENABLE_GL=OFF
> ENABLE_GLES=ON
> ENABLE_PYRENDERDOC=OFF
> ENABLE_QRENDERDOC=OFF
> ENABLE_RENDERDOCCMD=ON
> ENABLE_VULKAN=OFF
> ENABLE_XCB=OFF
> ENABLE_XLIB=OFF
> QRENDERDOC_ENABLE_PYSIDE2=OFF
> ENABLE_UNSUPPORTED_EXPERIMENTAL_POSSIBLY_BROKEN_WAYLAND=ON
> CMAKE_BUILD_TYPE=Debug

Below is toolkit used to build the binaries.

```
export C="arm-starfishmllib32-linux-gnueabi-gcc  -march=armv7ve -mthumb -mfpu=neon -mfloat-abi=softfp -mcpu=cortex-a7 -mtune=cortex-a7 -funwind-tables -rdynamic --sysroot=$SYSROOT"

export CXX="arm-starfishmllib32-linux-gnueabi-g++  -march=armv7ve -mthumb -mfpu=neon -mfloat-abi=softfp -mcpu=cortex-a7 -mtune=cortex-a7 -funwind-tables -rdynamic --sysroot=$SYSROOT"

export CPP="arm-starfishmllib32-linux-gnueabi-gcc -E  -march=armv7ve -mthumb -mfpu=neon -mfloat-abi=softfp -mcpu=cortex-a7 -mtune=cortex-a7 -funwind-tables -rdynamic --sysroot=$SYSROOT"
```

I'm wondering whether renderdoc can be made work in this particular system, please let me know if it's possible. it would be really helpful for our developing environment.

## Steps to reproduce

When i tried launch for application for capture with following command
`./renderdoccmd capture --opt-hook-children systemctl start <app_name>`

It throws this error 

> Failed to create & inject: RenderDoc injection failed: Couldn't connect to target program. Check that it didn't crash or exit during early initialisation, e.g. due to an incorrectly configured working directory.

## Environment

* RenderDoc version: renderdoccmd x86 v1.32 built from 10d402358cb5eac9d35bc66216eb77eddc6e9098
* Operating System: linux
* Graphics API: OpenGLES 2

**Comment by baldurk** [comment]
RenderDoc does not support ARM linux nor does it support wayland as indicated by the name of the option you enabled.
