### ISSUE TITLE
Cannot capture frame with AMD properitary driver

### ISSUE THREAD

**Issue by GinShio** [baldurk/renderdoc#3298]
## Description

Hi,
Running the game *The Talos Principle 2* under Proton is okay. Either RADV or AMD proprietary driver.
When I run with Renderdoc, **RADV is okay**. But failed to start with AMD proprietary driver.

command follow as below (ref: [How to run](https://github.com/ValveSoftware/Proton/issues/7260)):
```shell
ENABLE_VULKAN_RENDERDOC_CAPTURE=1 %command%
```

Error Message as below:
```
DirectX 12 is not supported on your system. Try running without the -dx12 or -d3d12 command line argument.
```
![image](https://github.com/baldurk/renderdoc/assets/38715657/de5bb69f-c930-4917-8501-812f48c053d1)

If add environment variable `LD_PRELOAD=/usr/lib64/librenderdoc.so`, running game is okay, still cannot capture frame.

## Steps to reproduce

 1. Use AMD proprietary driver
 2. Setup the game *The Talos Principle 2* properties
   a. Set Launch options to `ENABLE_VULKAN_RENDERDOC_CAPTURE=1 %command%` in General
 3. Run the game *The Talos Principle 2*

## Environment

* RenderDoc Version: x64 v1.31
* Operating System: openSUSE Tumbleweed x86_64, Linux 6.8.7-1-default
* Graphics API: Vulkan
* API Version: 1.3.283
* Proton Version: 8.0-5
* GPU: AMD RX 6600XT (Navi23)
* Driver Info: AMD Proprietary Driver
* Driver ID: DRIVER_ID_AMD_PROPRIETARY

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing programs that are not your own is not endorsed or allowed for any reason, and I will provide absolutely no support for it.
