### ISSUE TITLE
Renderdoc can not capture frame while the hwui rendering type is skiavk

### ISSUE THREAD

**Issue by lqy731** [baldurk/renderdoc#3318]
## Description

When we switch hwui rendering type from skiagl to skiavk, we found that renderdoc can not capture frames for any apps as attached image "renderdoc_capture.png" shown.
we test filament demo based on vulkan backend is alright to use renderdoc,but any apps based on skiavk is not fine to use renderdoc.
Compared with the log between filament demo and app based on skiavk:
 Renderdoc can call hooked_vkQueuePresentKHR, but for app based on skiavk cannot hooked.
So we guess if skiavk rendering type has different api calling logic, and renderdoc are not adapted. As Android V required, hwui is forced to switch to skiavk, we need to debug issue based on renderdoc, please help to resolve these issue on skiavk, thank you for your support!

## Steps to reproduce

![renderdoc_capture](https://github.com/baldurk/renderdoc/assets/169657273/fec56cf4-6c0d-4a8a-8220-6933320dede8)
switch mobile phone system to hwui skiavk on Android U or above, connect with the device, and launch any app used skia, the button capture frame is disabled, and there is no hint on mobile phone device, the other cases (likely, app based on skiagl) will show some hint on the left-top corner.
## Environment

* RenderDoc version: renderdoc_1.25/renderdoc_1.21
* Operating System: Android U
* Graphics API: Skiavk
    GPU : both mtk and qcom chip set have this issue

**Comment by baldurk** [comment]
You are running an extremely old version of RenderDoc, which there is no reason to do. Does this happen on the latest version v1.32?

**Comment by lqy731** [comment]
![RenderDocv132](https://github.com/baldurk/renderdoc/assets/169657273/969f789d-c6c0-4b83-b7e7-f5c90d2260c4)
Yes，this still happen on the latest version v1.32

**Comment by cmannett85-arm** [comment]
Please provide a sample app that demonstrates the problem.

**Comment by lqy731** [comment]
[Uploading apkpart0.zip…]()
[Uploading apkpart1.zip…]()
[Uploading apkpart2.zip…]()
I've uploaded three parts of the sample app, because of the attached file size limitation.Please download both of them ,and unzip together.

**Comment by cmannett85-arm** [comment]
@lqy731 all those download links just point to this page.

**Comment by lqy731** [comment]
Hi Mannett，
Shall I send it by email to you ? This page may have some limitation.

**Comment by cmannett85-arm** [comment]
Sure, please send camden.mannett@arm.com.

**Comment by lqy731** [comment]
Already send email to you, please check,thanks.

**Comment by cmannett85-arm** [comment]
Thanks @lqy731, however I've only received `apkpart1.zip` and `apkpart2.zip` - I assume there is a third part still to come?

**Comment by lqy731** [comment]
Hi Mannett，
I've send you three seperate email,which is apkpart0.zip,apkpart1.zip and apkpart2.zip. Is apkpart0.zip missed? I've send it again just now.

**Comment by cmannett85-arm** [comment]
Interesting, I still haven't received `apkpart0.zip`.  There's nothing in my corporate quarantine either.

**Comment by cmannett85-arm** [comment]
How large is the combined compressed data?

**Comment by lqy731** [comment]
![email](https://github.com/baldurk/renderdoc/assets/169657273/a429ecf1-5c9f-4e05-a3b3-e21f32b8355d)
It's strange..
the combined compressed data is 61.8 MB.
But It just a sample apk 'taobao', could you download any app from app store?we test any apps downloaded from app store launched on skiavk both have this problem.

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing programs that are not your own is not endorsed or allowed for any reason, and I will provide absolutely no support for it.
