### ISSUE TITLE
Can we directly obtain the 3D world coordinates of the vertices?

### ISSUE THREAD

**Issue by limtexpe** [baldurk/renderdoc#3320]
## Description
Hi, I am a beginner and I am learning about this field. I think that obtaining the 3D world coordinates might make the analysis more comprehensive and convenient (for example, understanding the positional relationships between different objects). Is it necessary to have the 3D world coordinates? Can we calculate or obtain them? 

## Environment

* RenderDoc version: 1.32
* Operating System: Windows 10
* Graphics API: Direct3D 11

**Comment by baldurk** [comment]
This is something far better suited for you to determine in your application and your editor/data source/etc. It may be possible to determine this from RenderDoc if you know what details to look up but it is far better to do such analysis on the source data not what is sent to the graphics API.
