### ISSUE TITLE
Allow Vulkan capture when not presenting

### ISSUE THREAD

**Issue by friesofdoom** [baldurk/renderdoc#3321]
## Description
When doing "headless" rendering where the output is an encoded video stream, there is no window and no present call. It would be nice to still be able to do a capture in this case.

## Environment
* RenderDoc version: 1.32
* Operating System: Windows 10
* Graphics API: Vulkan

Possibly an option to capture on a queue submit, or to capture N queue submit calls immediately would suffice.

**Comment by baldurk** [comment]
You can use the [in-application API](https://renderdoc.org/docs/in_application_api.html) to control when captures start and stop, regardless of whether your application creates a window or presents to it.
