### ISSUE TITLE
Capturing frames with RenderDoc will slow down the rendering speed of the exe.

### ISSUE THREAD

**Issue by limtexpe** [baldurk/renderdoc#3328]
## Description
Hi, I am trying to capture an action using RenderDoc. I implemented this with the Python API: capturing starts when F11 is pressed, and it can be manually stopped at any time. However, I noticed that while running this program, the rendering speed of the exe becomes very slow, and the motion is no longer continuous (the frame rate drops significantly compared to normal operation).

Is there a way to solve this problem? Thank you!

## Steps to reproduce
```
import renderdoc as rd
import time
from pynput.keyboard import Key, Listener
import shutil
import os

f11_pressed = False


def on_press(key):
    global f11_pressed
    if key == Key.f11:
        f11_pressed = True
        return False


app = "D:\\workspace\\my.exe"
workingDir = "D:\\workspace"
cmdLine = ""
env = []
capturefile = ""
opts = rd.GetDefaultCaptureOptions()
waitForExit = False

result = rd.ExecuteAndInject(app, workingDir, cmdLine, env, capturefile, opts, waitForExit)
target = rd.CreateTargetControl('', result.ident, "test", True)

with Listener(on_press=on_press) as listener:
    listener.join()

if f11_pressed:
    while True:
        target.TriggerCapture(5)  

        msg = None
        start = time.clock()
        while msg is None or msg.type != rd.TargetControlMessageType.NewCapture:
            msg = target.ReceiveMessage(None) 
            if msg.type == rd.TargetControlMessageType.Disconnected:
                target = rd.CreateTargetControl('', result.ident, "test", True)
                break
            if time.clock() - start > 1:
                break
        cap_path = msg.newCapture.path
        if cap_path != '':
            destination_path = 'D:\\captures\\' + str(msg.newCapture.frameNumber) + '.rdc'
            shutil.copy2(cap_path, destination_path)
            os.remove(cap_path)

    target.Shutdown()
    target = None
```

## Environment

* RenderDoc version: 1.32
* Operating System: Windows 10
* Graphics API: D3D11

**Comment by baldurk** [comment]
I've mentioned to you multiple times before that this issue tracker is for RenderDoc bug reports and feature requests, not for programming assistance or help writing python scripts. You will need to debug your own scripts and any problems you encounter yourself.

In future please only report bugs that can be reproduced using the UI normally and do not involve running a custom python script.
