### ISSUE TITLE
A guide for when you don't know how to stop ignoring a symbol.

### ISSUE THREAD

**Issue by hxdnshx** [baldurk/renderdoc#3329]
## Description

When using the Callstack feature in RenderDoc, you need to click `Tools -> Resolve Symbols` to address missing symbols. During this process, a dialog box `Do you want to permanently ignore this file?` may appear. If you choose `Yes`, the corresponding pdb will be permanently ignored, even if you later found the required pdb.

To avoid this, you can refer to the following code:

https://github.com/baldurk/renderdoc/blob/666c248b3a0385f846dd4ec48205e1931c2519d5/renderdoc/os/win32/win32_callstack.cpp#L751-L752

In the `<User>\AppData\Roaming\renderdoc` directory, locate the `config.ini`, and delete the corresponding pdb entry. After restarting RenderDoc, it will again ask you during the Resolve Symbol process where you can find the corresponding pdb.

I hope there can be a GUI option to reset such configurations.

## Environment

* RenderDoc version: v1.32
* Operating System: Windows 10 x64
* Graphics API: OpenGL

**Comment by baldurk** [comment]
This was a little strangely phrased but I treated this as a request to have the list of ignored DLLs/PDBs exposed in the UI as you said at the end of your description.
