### ISSUE TITLE
In renderdoc 1.13, I use TextureSave to save R8G8, but it's not work! 

### ISSUE THREAD

**Issue by wsqat** [baldurk/renderdoc#3333]
## Description

In renderdoc 1.13, I use TextureSave to save R8G8, but it's not work! The saved picture is black.

## Steps to reproduce

In renderdoc 1.13

` texsave.alpha = rd.AlphaMapping.BlendToCheckerboard

texsave.mip = 0

texsave.slice.sliceIndex = 0

texsave.resourceId = sd.textures[0].resourceId

texsave.destType = rd.FileType.PNG

texsave.comp.blackPoint = 0.0

texsave.comp.whitePoint = 1.0

filename = "./capture/" + os.path.basename(sys.argv[1]).split('.')[0] + ""

controller.SaveTexture(texsave, filename + "_0.png")`
'
## Environment

* RenderDoc version: 1.13
* Operating System:  Windows 10 企业版
* Graphics API: no

**Comment by baldurk** [comment]
Please do not open multiple copies of the same issue, this amounts to spam and makes it harder to help with any problems people are having.
