### ISSUE TITLE
Please consider adding support for VK_KHR_dynamic_rendering_local_read

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#3341]
## Description

The VK_KHR_dynamic_rendering_local_read extension closes a big gap between VK_KHR_dynamic_rendering and VkRenderPass objects. For applications that use input attachments, this extension is an absolute necessity to enable them to move to dynamic rendering (which is already part of core Vulkan 1.3).

Please consider adding support for this extension. It's likely not too difficult to implement, but it does include an annoyance with color and input attachment index mapping. In particular, unlike the subpass mapping of color locations to render pass attachments, the mapping in this extension does not affect blend states etc matching dynamic rendering attachments.

## Environment

* RenderDoc version: v1.33
* Operating System: Linux
* Graphics API: Vulkan

**Comment by ShabbyX** [comment]
Some gotchas and findings:

- When reading from input attachments (in shader debugger), if input attachments are read from the descriptor set, then `VkRenderingInputAttachmentIndexInfoKHR` can largely be ignored. It may still need to be used to extract the format of the attachments correctly.

- Depth/stencil input attachments now don't need an input_attachment_index. Lack of that decoration + type (float vs int) implicitly defines depth and stencil input attachments.

- `VkRenderingAttachmentLocationInfoKHR` remaps the render pass attachments to "locations". The shader references locations (for example writing to locations 2 and 5), which needs care to map to attachments (which for example could be at index 1 and 0 respectively)

- `vkCmdClearAttachments`, blend state, etc still reference the attachment index, NOT the location. This is the only real deviation from subpasses.

- The mappings, if any, should be specified in the pipeline (if not shader object), and matching mappings should be specified either as command buffer inheritance info or via `vkCmdSet*` functions.

- In some cases, the mappings can be nullptr, meaning identity mapping.

- If VkRenderingAttachmentLocationInfoKHR maps an attachment to VK_ATTACHMENT_UNUSED, it must be disabled! The application doesn't have to explicitly mask writes to the attachment.

**Comment by jmoguill** [comment]
With this extension (and extensions in general) if there was an ability for Renderdoc to ignore unsupported extensions but still be usable for inspecting the rest of the API calls etc. (without crash) that would be a great feature (e.g. minimal support as a first step?)

**Comment by ShabbyX** [comment]
> With this extension (and extensions in general) if there was an ability for Renderdoc to ignore unsupported extensions but still be usable for inspecting the rest of the API calls etc. (without crash) that would be a great feature (e.g. minimal support as a first step?)

I talked about this with Baldur previously, he's not a fan of such a solution. It's understandable, particularly because the "without crash" part cannot really be guaranteed, and crashing is not a good feedback to the user about it.

I'm working in this right now by the way, so this particular extension should be supported soon. FWIW, adding support for new extensions is not that hard, if you hit any that's blocking you, you might want to just add it yourself.

**Comment by jmoguill** [comment]
> > With this extension (and extensions in general) if there was an ability for Renderdoc to ignore unsupported extensions but still be usable for inspecting the rest of the API calls etc. (without crash) that would be a great feature (e.g. minimal support as a first step?)
> 
> I talked about this with Baldur previously, he's not a fan of such a solution. It's understandable, particularly because the "without crash" part cannot really be guaranteed, and crashing is not a good feedback to the user about it.
> 
> I'm working in this right now by the way, so this particular extension should be supported soon. FWIW, adding support for new extensions is not that hard, if you hit any that's blocking you, you might want to just add it yourself.

Thanks @ShabbyX looking forward to it
