### ISSUE TITLE
DXGI_ERROR_INVALID_CALL in IDXGISwapChain::ResizeBuffers

### ISSUE THREAD

**Issue by mihnea-epic** [baldurk/renderdoc#3343]
## Description

Trying to capture multiple frames from the Unreal Engine editor fails because the editor creates a new window during the capturing process, and IDXGISwapChain::ResizeBuffers returns DXGI_ERROR_INVALID_CALL for that window. The resize calls work fine without renderdoc attached.

## Steps to reproduce

* Run the UE5 editor on any project with the following command line: -dx11 -attachrenderdoc -onethread (-onethread is not strictly necessary, but it rules out threading issues; the problem still happens without it).
* Set renderdoc.captureframecount 2 via the console or output window command input field. (This is what causes the editor to spawn and resize that small popup window).
Press the capture button in the top-right corner of the viewport.
Observe crash. The editor log will contain this information:

```
[2024.06.06-11.24.30:101][333]RenderDocPlugin: Capture frame and launch renderdoc!
RDOC 044064: [14:24:30]             core.cpp(2047) - Log     - Adding D3D11 frame capturer for 0x0000028F22EEACC8 / 0x0000000000080C2C
RDOC 044064: [14:24:30]     d3d11_device.cpp(1954) - Log     - Starting capture
RDOC 044064: [14:24:30]   resource_manager.h(1469) - Log     - Preparing up to 285 potentially dirty resources
RDOC 044064: [14:24:30]   resource_manager.h(1526) - Log     - Prepared 285 dirty resources, postponed 0, skipped 0
[2024.06.06-11.24.30:382][334]LogD3D11RHI: Error: SwapChain->ResizeBuffers(0, SizeX, SizeY, RenderTargetFormat, SwapChainFlags) failed with error DXGI_ERROR_INVALID_CALL
 at D:\UE5\Main\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Viewport.cpp:285
 (Size=8x8 Fullscreen=0 Format=DXGI_FORMAT_B8G8R8A8_UNORM(0x00000057)) -> (Size=105x56 Fullscreen=0 Format=DXGI_FORMAT_B8G8R8A8_UNORM(0x00000057))
```

The error does not happen when using DX12. The D3D debug layer doesn't complain about anything, with or without renderdoc attached.

## Environment

* RenderDoc version: 1.33
* Operating System: Windows 10 22H2
* Graphics API: D3D11

This problem has been reproduced for multiple UE5 releases, using multiple renderdoc and OS versions.

**Comment by baldurk** [comment]
That commit should fix the issue, allowing the resize to go through without any refcounting issues during capture.

**Comment by mihnea-epic** [comment]
That fixes the issue indeed, thanks for the quick turnaround!
