### ISSUE TITLE
Missing geometry only in Renderdoc 1.33

### ISSUE THREAD

**Issue by LiamTyler** [baldurk/renderdoc#3346]
## Description

Hi there! I have a small application. It simply draws a red + blue gradient to a render target in a compute shader, and then draws a green cube ontop of that using a mesh shader. The application seems to work fine, no validation errors or anything, whether I launch it through Renderdoc or not. When I take a capture and open it however, the cube is gone. I confirmed this does not happen with Renderdoc 1.31 or 1.32, only in 1.33 so far. Here are some comparison images between 1.32 and 1.33 for me:

<img width="951" alt="rd_1_32" src="https://github.com/baldurk/renderdoc/assets/10976902/bb753002-d0db-4857-8985-9c4aa1213dfd">
<img width="949" alt="rd_1_33" src="https://github.com/baldurk/renderdoc/assets/10976902/8d5e09e2-5adc-44da-8bbb-63e4c8f556ec">
<img width="1083" alt="rd_1_32_mesh_viewer" src="https://github.com/baldurk/renderdoc/assets/10976902/ed6b5c46-4d79-4b23-a036-7bd35896b6c1">
<img width="1082" alt="rd_1_33_mesh_viewer" src="https://github.com/baldurk/renderdoc/assets/10976902/0c1352ee-0ad1-46ae-a5e0-3cb78d297088">

## Steps to reproduce

Attached is a zip file of the application, and the assets needed to run it. You should just be able to unzip the folder, and double click the application to run it, and the cube should be immediately infront of the camera upon launch. I also included a capture using 1.32 and a capture using 1.33. When I open the 1.32 capture while using 1.33, it does work. But 1.33 with 1.33 does not.

## Environment

* RenderDoc version: 1.33
* Operating System: Windows 11 (22631.3593)
* Graphics API: Vulkan 1.3.280
* GPU: AMD Radeon 7900XT, Driver: 24.5.1 (latest, released 5/8/2024)

[Repro.zip](https://github.com/user-attachments/files/15743913/Repro.zip)

**Comment by vblanco20-1** [comment]
This is something ive been able to confirm on my end, on renderdoc 1.33 vkguide codebase even at chapter 4 is broken . Caused for some reason due to grabbing vertex data from a buffer device address. Its not just mesh shader but all mesh types, happening on both indirect and "normal" drawing, it also doesnt matter if the pass before is a compute gradient.

**Comment by LiamTyler** [comment]
Thanks vblanco! Good to know I'm not the only one seeing it. And I'm sure you recognized the compute gradient haha😄
