### ISSUE TITLE
Support for Vulkan Extension: VK_EXT_shader_object

### ISSUE THREAD

**Issue by parsaiej** [baldurk/renderdoc#3355]
## Description

I have a Vulkan application using the `VK_EXT_shader_object` extension. I noticed that when the Renderdoc Vulkan layer is implicitly loaded (i.e. when using the Launch Application option), the call to `vkCreateDevice` fails. It otherwise succeeds when I do not load that extension. I assume this is happening because Renderdoc currently does not support this extension, so I decided to make this request in case that assumption was correct. I am making heavy use of this extension and won't have time to re-organize things for traditional Vulkan pipeline objects.

## Environment

* RenderDoc version: v1.33
* Operating System: Windows 11 64-Bit
* Graphics API: Vulkan 1.3

**Comment by baldurk** [comment]
Note that your application should be checking for extensions being available before calling vkCreateDevice, although RenderDoc will also return VK_EXTENSION_NOT_PRESENT if you don't do that. This will let you detect what is happening and report appropriately.

Nintendo is currently contributing shader object support as the extension is primarily relevant/intended for their platform, so it should be supported in the near future.

**Comment by baldurk** [comment]
Implemented by Nintendo in #3364 - I believe they will be primarily maintaining it going forwards.
