### ISSUE TITLE
Input vertex attributes and input vertex data not shown when using SPIR-V shaders on OpenGL app

### ISSUE THREAD

**Issue by raaaliii** [baldurk/renderdoc#3375]
## Description
Previously when I had 1050ti and older NVidia drivers that problem didn't exist, now with rtx 4070 and newer drivers RenderDoc not showing vertex attributes and input geometry at all...

## Steps to reproduce
Added a capture in attachments, just look at any draw call
[Captures.zip](https://github.com/user-attachments/files/16116773/Captures.zip)

## Environment

* RenderDoc version: 1.33
* Operating System: Windows 10 64bit
* Graphics API: OpenGL 4.5 (All code written in DSA using C# OpenTK)
* NVidia Drivers 556.12
* GPU: GeForce RTX 4070

![spirv](https://github.com/baldurk/renderdoc/assets/127874853/ac80079c-b5e3-42cb-959f-300ce5e00c25)

**Comment by Zorro666** [comment]
This looks like a v.133 specific bug. If you open the attached capture in v1.32 then the vertex inputs are visible.

![image](https://github.com/baldurk/renderdoc/assets/39392/bf1d36d1-bf9e-465a-8ef4-c2959db2db34)

**Comment by Zorro666** [comment]
Thank you for chasing it down. The fix is pushed to v1.x and will be available in the next nightly build.
