### ISSUE TITLE
Add Warning Dialog when running Wayland

### ISSUE THREAD

**Issue by swapname** [baldurk/renderdoc#3380]
## Description

Pretty simple request. Just add a warning dialog when running with wayland. Because I just got gotcha'd by this so that would be very helpful for anyone else that might end up falling into this trap.

## Environment

    RenderDoc version: v1.33
    Operating System: Arch Linux, Kernel 6.9.7-arch1-1
    Graphics API: Vulkan
    Card: Radeon RX 7900 XT
    Window Manager: wayland/X11(depending on what I select on bootup)

**Comment by Zorro666** [comment]
RenderDoc does not support Wayland. When RenderDoc is launched on Wayland it implements a fallback to try and use X11. If the fallback does not succeed and Wayland gets used then RenderDoc shows an error dialog.

To work with RenderDoc the application needs to choose X11 in preference to Wayland.
