### ISSUE TITLE
Error device lost when using buffer device address

### ISSUE THREAD

**Issue by LiamTyler** [baldurk/renderdoc#3381]
## Description

Hi there. I noticed my application would hang when run inside of Renderdoc, but not otherwise. I narrowed it down to a change that started using BDA in a shader. To confirm this, I also tried running Khronos Group's [BDA example](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/buffer_device_address) in renderdoc, and get an error device lost there. I was running Renderdoc 1.32, but I downloaded the latest nightly (aa5538b2), and get the same results. Both of these applications work fine when not run inside of Renderdoc.

## Steps to reproduce
Clone the Vulkan Samples repo from the hyperlink above, build everything, and then run the BDA sample by using the repo's top level directory as the working directory, and "sample buffer_device_address" as the command line args.
![image](https://github.com/baldurk/renderdoc/assets/10976902/a26740ac-4b8e-4a15-9b5c-6c2004ce386b)

## Environment
I only have access to 1 computer right now, so I haven't been able to test on any other hardware than this:
RenderDoc version: 1.32 and Nightly aa5538b2
Operating System: Windows 11 (22631.3737)
Graphics API: Vulkan 1.3.283
GPU: AMD Radeon 7900XT, Driver: 24.6.1 (latest, released 6/20/2024)

**Comment by Zorro666** [comment]
It is working without problems on nVidia.
On AMD Windows driver it is triggering a device timeout in the Vulkan Sample and the RenderDoc BDA test project. This is happening on RenderDoc versions v1.33, v1.32, v1.31, v.130.
The Vulkan Sample and RenderDoc BDA test project used to work on AMD.
I think the AMD driver updates have caused this problem.
Will try to test on an older AMD driver.

**Comment by Zorro666** [comment]
Using the same hardware the BDA tests work fine on Linux using RADV driver.

**Comment by LiamTyler** [comment]
Thank you for testing all of that! I downgraded to AMD driver 24.5.1 and I can run the sample in renderdoc now. Sorry to give a false alarm for renderdoc here. I just submitted a bug report to AMD using their bug report tool, hopefully that gets look at soon. Thanks for all your help!

**Comment by Zorro666** [comment]
Thank you for confirming the driver downgrade fixed the problem. Have also asked AMD to investigate.
