### ISSUE TITLE
External image formats cannot be created

### ISSUE THREAD

**Issue by joemarshall** [baldurk/renderdoc#3383]
## Description

I'm using VK_ANDROID_external_memory_android_hardware_buffer to wrap an Android hardware buffer. Because of this, I need to create vkImages with format VK_FORMAT_UNDEFINED (and the android specific info in the pNext). This hits the check at: https://github.com/baldurk/renderdoc/blob/94212f148878fbe4c6d83a9221e3678da43d6bec/renderdoc/driver/vulkan/wrappers/vk_resource_funcs.cpp#L2341 which means the image creation fails and I can't debug anything.

It would be more useful if renderdoc just returned the created image in this case rather than returning an error to my app.

## Steps to reproduce

Create an image based on an Android hardware buffer which comes from video or camera as a YCbCr image.

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkAndroidHardwareBufferFormatPropertiesANDROID.html

```
        AHardwareBuffer_Desc hardwareBufferDesc;
        AHardwareBuffer_describe(buffer, &hardwareBufferDesc);

        imgData.width = hardwareBufferDesc.width;
        imgData.height = hardwareBufferDesc.height;

        VkAndroidHardwareBufferFormatPropertiesANDROID hardwareBufferFormatProperties{};
        hardwareBufferFormatProperties.sType = VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_FORMAT_PROPERTIES_ANDROID;

        VkAndroidHardwareBufferPropertiesANDROID hardwareBufferProperties{};
        hardwareBufferProperties.sType = VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_PROPERTIES_ANDROID;
        hardwareBufferProperties.pNext = &hardwareBufferFormatProperties;

        CHECK_VULKAN(vkGetAndroidHardwareBufferPropertiesANDROID(vulkanDevice, buffer, &hardwareBufferProperties));
        LOGV("Hardware buffer props: %p %x %ld vkformat:%d", buffer, hardwareBufferProperties.memoryTypeBits, hardwareBufferProperties.allocationSize, hardwareBufferFormatProperties.format);
        // Set ExternalFormatANDROID
        VkExternalFormatANDROID externalFormatAndroid{};
        externalFormatAndroid.sType = VK_STRUCTURE_TYPE_EXTERNAL_FORMAT_ANDROID;
        externalFormatAndroid.pNext = nullptr;
        externalFormatAndroid.externalFormat = hardwareBufferFormatProperties.externalFormat;

        // Set ExternalMemoryImageCreateInfo
        VkExternalMemoryImageCreateInfo externalMemoryImageCI{};
        externalMemoryImageCI.sType = VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO;
        externalMemoryImageCI.pNext = &externalFormatAndroid;
        externalMemoryImageCI.handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_ANDROID_HARDWARE_BUFFER_BIT_ANDROID;

        VkImageCreateInfo imageCI{};
        imageCI.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
        imageCI.pNext = &externalMemoryImageCI;
        imageCI.flags = 0;
        imageCI.imageType = VK_IMAGE_TYPE_2D;
        imageCI.format = hardwareBufferFormatProperties.format;
        imageCI.extent.width = hardwareBufferDesc.width;
        imageCI.extent.height = hardwareBufferDesc.height;
        imageCI.extent.depth = 1;
        imageCI.mipLevels = 1;
        imageCI.arrayLayers = 1;
        imageCI.samples = VK_SAMPLE_COUNT_1_BIT;
        imageCI.tiling = VK_IMAGE_TILING_OPTIMAL;
        imageCI.usage = VK_IMAGE_USAGE_SAMPLED_BIT;
        imageCI.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
        imageCI.queueFamilyIndexCount = 0;
        imageCI.pQueueFamilyIndices = nullptr;
        imageCI.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        CHECK_VULKAN(vkCreateImage(vulkanDevice, &imageCI, nullptr, &retImage));
```

## Environment

* RenderDoc version: 1.33
* Operating System: Android (running on Windows host)
* Graphics API: Vulkan

Running on oculus quest 3

**Comment by Zorro666** [comment]
Sorry to say this is not supported and can't be supported as you describe. 
Extending the support of this extension is outside of the scope of the project.
If the full extent of the extension were known when support was first added then the extension would not have been supported because of problems like you have found. Full support would require going outside of Vulkan and using Android APIs to obtain the information required to support the extension.
Rather than remove support for the extension it is supported in a slightly restricted way.

The application needs to create VkImage's with a supported Vulkan Image Format.
