### ISSUE TITLE
Dx12 Cannot show all of used sampler descriptors when using sm5.1 descriptor indexing

### ISSUE THREAD

**Issue by Rilliane** [baldurk/renderdoc#3387]
## Description

When I use descriptor indexing, I can't see any sampler in Pipeline State Window.My pixel shader uses two textures and both of them have a sampler which I use descriptor table to access. 
![image](https://github.com/user-attachments/assets/42e639d3-0d67-42f8-b406-6985d2fe8b26)
I can find the sampler I am using in Resource Inspector:
![image](https://github.com/user-attachments/assets/a2059a3b-a984-4197-a3cd-85679045832b)
I've test many apps. Some can show only one sampler (Actually using more than one) and some cannot show anything.
This is my shader:
``
Texture2D    gDiffuseMap[1000] : register(t0);
SamplerState bindlessSamplers[1000] : register(s0, space1);

......

float4 PS(VertexOut pin) : SV_Target
{

    float4 diffuseAlbedo = gDiffuseMap[0].Sample(bindlessSamplers[0], pin.TexC) * gDiffuseAlbedo;
    float4 diffuseAlbedo2 = gDiffuseMap[1].Sample(bindlessSamplers[1], pin.TexC) * gDiffuseAlbedo;
	
   ......

    // Common convention to take alpha from diffuse albedo.
    litColor.a = diffuseAlbedo.a*diffuseAlbedo2.a;

    return litColor;
}
``

## Steps to reproduce

1. Run the latest renderdoc
2. Launch an App in dx12 which uses sm5.1 descriptor indexing images and samplers
3. Get a capture and click a "DrawIndexInstanced()"command, open the pipeline state window, switch to "Pixel Shader"page

## Environment

* RenderDoc version: 1.33
* Operating System: Windows 10
* Graphics API: Dx12

**Comment by Rilliane** [comment]
This is my root signature:
![image](https://github.com/user-attachments/assets/9a420f3b-3d1e-4989-9efa-57dc7b1fb927)

**Comment by baldurk** [comment]
Shader feedback for samplers had not been implemented, and in v1.33 this meant arrays no longer showed up with at least element [0] as in prior versions. With that commit you should get proper feedback now for dynamic arrayed descriptor access.
