### ISSUE TITLE
Rendering commands replay cause GPU crash if the “Ref all Resources” option is checked

### ISSUE THREAD

**Issue by iiiwk** [baldurk/renderdoc#3388]
## Description

If "Ref all Resources" option is not checked, it's fine.

## Steps to reproduce

<img width="537" alt="RefAllResources" src="https://github.com/user-attachments/assets/aff62b13-5773-4f28-a02c-bce6eb1b6ee5">

<img width="251" alt="RefAllResources-DeviceLost" src="https://github.com/user-attachments/assets/8299e52c-b94f-49f7-bf5b-9b9234a1d611">

Captured file:
[GPUDeviceLostOnReplay.zip](https://github.com/user-attachments/files/16323915/GPUDeviceLostOnReplay.zip)
[NoCrashVersion.zip](https://github.com/user-attachments/files/16323942/NoCrashVersion.zip)

## Environment

* RenderDoc version: 1.33
* Operating System: Windows 10 22H2
* Graphics API: Vulkan
* GPU: Nvidia RTX 3060
* Nvidia Driver Version: 551.52

**Comment by Zorro666** [comment]
Sorry to say unable to reproduce the crash on two different nVidia system.
Both systems have newer drivers than used in the capture and this might explain why the crash is not reproducible.

In case, it hasn't been done it would be worth checking your application is free of Vulkan Validation Errors when running outside of RenderDoc. RenderDoc relies upon and requires correct API usage and accidental API mistakes can cause errors and crashes in RenderDoc (and drivers).

There should be no requirement to use "Ref All Resources", be good to know if you are seeing a problem in the working capture that was the rationale for using "Ref All Resources"

**Comment by iiiwk** [comment]
Thank you very much for your comments and suggestions! I tried installing the latest version of NVIDIA driver 560.70 and the crash doesn't happen anymore. There are no errors reported at the validation layer level, so I think this is indeed an underlying driver issue.
