### ISSUE TITLE
samplerCubeArrayShadow is not visible as a texture resource

### ISSUE THREAD

**Issue by dontweaks** [baldurk/renderdoc#3391]
## Description

I've got a cube map array shadow texture bound to unit 1.
![image](https://github.com/user-attachments/assets/c36bd512-199a-40d4-bf16-125ec60a4110)
`X::Bind(...)` is just `glBindTextureUnit(bindingPoint, glTexture);`, but I'm sure there's no problem with this.

```glsl
    layout(binding = 1) uniform samplerCubeArrayShadow u_pointShadowMap;
    layout(binding = 2) uniform sampler2DArrayShadow u_spotShadowMap;
```

I am 100% sure it's valid, because the shader uses this texture and it works.
The frame buffer's output of the depth pass looks good

![image](https://github.com/user-attachments/assets/a66f02c2-7b55-4c99-8ad2-a1665d1d9c95)

but on "color pass" I can only see `sampler2DArrayShadow` map:
![image](https://github.com/user-attachments/assets/f36892c3-154f-4e59-8cfb-a2b7cd87c98f)

As I said before, point light shadows work thus the `layout(binding = 1) uniform samplerCubeArrayShadow u_pointShadowMap;` is valid (as a resource and syntax), but not displayed by the render doc.

## Steps to reproduce

1. create opengl context and window
2. Create depth texture:

```cpp
static constexpr std::uint32_t TEXTURE_CUBE_FACE_COUNT = 6;
std::uint32_t pointLightsCount = 1;

GLuint glTexture;
glCreateTextures(GL_TEXTURE_CUBE_MAP_ARRAY, 1, &glTexture);
glTextureStorage3D(glTexture, 0, GL_DEPTH_COMPONENT32F, 1024, 1024, pointLightsCount  * TEXTURE_CUBE_FACE_COUNT);

glTextureParameteri(glTexture, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
glTextureParameteri(glTexture, GL_TEXTURE_MIN_FILTER, GL_NEAREST_MIPMAP_NEAREST);

glTextureParameteri(glTexture, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER);
glTextureParameteri(glTexture, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER);
glTextureParameteri(glTexture, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_BORDER);

glTextureParameteri(glTexture, GL_TEXTURE_COMPARE_MODE, GL_COMPARE_REF_TO_TEXTURE);
glTextureParameteri(glTexture, GL_TEXTURE_COMPARE_FUNC, GL_GREATER);
```
3. bind texture
```cpp
GLuint bindingPoint = 1;
glBindTextureUnit(bindingPoint, gltexture);
```
4. run render doc

## Environment

* RenderDoc version: v1.33
* Operating System: Windows 11
* Graphics API: OpenGL 4.5

**Comment by Zorro666** [comment]
This commit fixed the missing CubeArrayShadow binding in a local test project.
