### ISSUE TITLE
Uniform buffers with the std430 layout are not diplayed correctly

### ISSUE THREAD

**Issue by Trider12** [baldurk/renderdoc#3392]
## Description

Here I have a structure that I pass in a uniform buffer with the std430 layout:
```c
struct LightData
{
    float r, g, b, radius;
    float16_t x, y, z;
    float16_t intensity;
};

struct LightingData
{
    uint16_t dirLightCount;
    uint16_t pointLightCount;
    LightData lights[16];
};
```

According to the layout its size should be 388 bytes. However, in Renderdoc I see this:
![image](https://github.com/user-attachments/assets/e76d886d-f7c7-4e53-9940-b3a8aa818eda)

The auto generated format is:
```c
#pack(std430)

struct LightData
{
    float r;
    float g;
    float b;
    float radius;
    half x;
    half y;
    half z;
    half intensity;
}

[[size(528)]]
struct LightingData
{
    ushort dirLightCount;
    ushort pointLightCount;
    LightData lights[16];
}

struct LightsBlock_var
{
    LightingData lightData;
}
```

So, despite `#pack(std430)` the size is still explicitly calculated as if it were std140.

## Steps to reproduce

Pass a uniform buffer with the std430 layout. This requires the [VK_KHR_uniform_buffer_standard_layout](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_uniform_buffer_standard_layout.html) and  [GL_EXT_scalar_block_layout](https://github.com/KhronosGroup/GLSL/blob/main/extensions/ext/GL_EXT_scalar_block_layout.txt) extensions. The 16 bit types are not relevant here, because I have another structure that has the same problem without using them.

## Environment

* RenderDoc version: 1.33
* Operating System: Windows
* Graphics API: Vulkan

**Comment by baldurk** [comment]
That commit should solve the issue, it was calculating the stride of the parent struct too pessimistically since struct sizes are implicit even though manually looking here you can see what the implied size should realistically be based on other context.
