### ISSUE TITLE
Capture official Vulkan-Samples's frame, the swapchain image only shows UI with a black background

### ISSUE THREAD

**Issue by SakuragiHnmch** [baldurk/renderdoc#3407]
## Description
I was using renderdoc to capture the async_compute sample's frames, and found that the swapChain image only contains UI informations . At first, I guess that might be caused by the multi queues. But when I set the `async_enabled` to false, using single queue to do the compute work, this problem still remained.

And later I tested several other samples like msaa , render_passes , the same problem occurred.
## Steps to reproduce
When running the `render_passes`  sample, the scene shows as below:
![scene](https://github.com/user-attachments/assets/60842a50-7865-4b98-9279-97be8a7a2c35)

And when I capture the frame, the current swapchain image shows as below:
![capture](https://github.com/user-attachments/assets/533e5551-4c2c-4bb3-b7bf-0038f4c90090)

## Environment
* RenderDoc version: 1.34
* Operating System: Windows10
* Graphics API: Vulkan1.3.283

I have no idea about why this will happen. And I know there is In-application API of renderdoc for headless vulkan application, but it seems have nothing to do with my problem, the scene actually has presented to the screen.

Could you please offer some help and give some advice, thanks very much!

**Comment by SaschaWillems** [comment]
To avoid duplicate work, see https://github.com/KhronosGroup/Vulkan-Samples/issues/1128

I don't think this is a RenderDoc issue.
