### ISSUE TITLE
LWJGL Vulkan App Crash

### ISSUE THREAD

**Issue by RawFish2D** [baldurk/renderdoc#3408]
## Description
My Vulkan Java app always crashes when I'm launch it from RenderDoc. It doesn't crash if I launch it with IDE debugger or compiled into a jar. The crash reason seems to be inside LWJGL library during vkCmdPipelineBarrier2 function pointer check. When it's launched with RenderDoc that function pointer is always 0.
Here is the stacktrace:
```
java.lang.NullPointerException
        at org.lwjgl.system.Checks.check(Checks.java:188)
        at org.lwjgl.vulkan.VK13.nvkCmdPipelineBarrier2(VK13.java:1600)
        at org.lwjgl.vulkan.VK13.vkCmdPipelineBarrier2(VK13.java:1693)
        at ua.rawfish2d.vklib.utils.VkHelper.bufferMemoryBarrier2(VkHelper.java:530)
        at ua.rawfish2d.vklib.VkBuffer.vertexBufferBarrier(VkBuffer.java:172)
        at ua.rawfish2d.vklib.test.BulletScene.uploadBuffers(BulletScene.java:132)
        at ua.rawfish2d.vklib.test.VKLIB_TEST.createBulletScene(VKLIB_TEST.java:122)
        at ua.rawfish2d.vklib.test.VKLIB_TEST.<init>(VKLIB_TEST.java:96)
        at ua.rawfish2d.vklib.test.VKLIB_TEST.main(VKLIB_TEST.java:329)
```

## Steps to reproduce
1. Run Java application in "Launch Application" window from this repo (https://github.com/RawFish2D/VKLib/tree/30ae4d740f31cb086e0900ccb086631a4cb9104d)
2. Java application crashes.

## Environment

* RenderDoc version: 1.34
* Operating System: Windows 11 22H2 build 22621.2283
* Graphics API: Vulkan 1.3
* GPU: AMD Vega 8 (Ryzen 2200g APU)
* GPU Vulkan Api Version: 1.3.260
* AMD Adrenalin Edition Version: 24.7.1
* GPU Driver Version: 23.19.16-240618a-405470C-AMD-Software-Adrenalin-Edition
* GPU Vulkan Driver Version: 2.0.279

Also here is a video of this bug:
https://github.com/user-attachments/assets/666b09b4-384b-480d-ac56-6df56d5ca607

**Comment by baldurk** [comment]
Can you tell me how to run your program? I don't see any instructions on the repository of how to run - I tried to follow the commands in your video by running `java -jar VKLib.jar` but it gives me an error because the jar file doesn't exist.

The java version I'm using is `Java(TM) SE Runtime Environment (build 1.8.0_421-b09)` in case a specific version is needed.

**Comment by RawFish2D** [comment]
> Can you tell me how to run your program? I don't see any instructions on the repository of how to run - I tried to follow the commands in your video by running `java -jar VKLib.jar` but it gives me an error because the jar file doesn't exist.

I'm sorry, I updated repository with instructions on how to build and run it. I also added pre compiled jar binary with 
dependencies in case you don't want to build it yourself, but it might need to be rebuilt to run on OS other than Windows.
> The java version I'm using is `Java(TM) SE Runtime Environment (build 1.8.0_421-b09)` in case a specific version is needed.

I'm using GraalVM JDK 21 `Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)`

**Comment by baldurk** [comment]
OK I downloaded that version of GraalVM and I'm able to run the jar you provided, but it works correctly for me in v1.34 as it launches the program successfully and I'm able to create a capture. I tested on nvidia and AMD systems.

On nvidia the program doesn't render anything and the capture fails to load due to invalid API use - memory bindings are incorrect as insufficient memory is provided for a buffer. You should run your program with the validation layers as RenderDoc does not handle invalid API use and may break on misbehave in different ways if your program is not valid.

**Comment by RawFish2D** [comment]
Okay so I did more testing, and I don't have any validation layer errors, but my program still crashes inside RenderDoc. I also tested it in Nvidia Nsight Graphics and it works there. Also I found out something weird about LWJGL when it's launched inside RenderDoc. Device extensions like `VK_KHR_dynamic_rendering` and `VK_KHR_dynamic_rendering` work fine inside RenderDoc (`vkCmdBeginRenderingKHR` and `vkQueueSubmit2KHR` functions work fine), but if I'm using them as device features (`vkCmdBeginRendering` and `vkQueueSubmit2`, non KHR versions) LWJGL crashes because it can't find pointer to these functions, also I enabled these device features correctly and provided `VK_API_VERSION_1_3` when creating Vulkan instance, and I have no validation errors.

Inside RenderDoc, while calling vkQueueSubmit2 LWJGL crashes here https://github.com/LWJGL/lwjgl3/blob/813400f21ebfce5a9e1566cbf8ff96ca1d8f4921/modules/lwjgl/vulkan/src/generated/java/org/lwjgl/vulkan/VK13.java#L1822 because function pointer in `queue.getCapabilities().vkQueueSubmit2` is 0, even thought `vkGetInstanceProcAddr(vkInstance, "vkQueueSubmit2")` and `vkGetDeviceProcAddr(vkLogicalDevice, "vkQueueSubmit2")` always return valid pointer to this function, inside and outside of RenderDoc.

Right now I found workaround by using extensions instead of device features, or calling native function directly.

So I think it might be some sort of incompatibility between RenderDoc and LWJGL library, since it works outside of it, and it works without a problem inside other graphics debugger like Nvidia Nsight Graphics.
I don't know what RenderDoc does to a debugging program to be able to hook it's function calls to Vulkan API, but something causes LWJGL to not resolve function pointers correctly.

**Comment by baldurk** [comment]
Do you properly check that 1.3 is reported as available when running before trying to enable it or use such core functionality, or do you try to enable it regardless? What you're describing sounds like what might happen if RenderDoc the available version is only 1.2 and so you don't get any core 1.3 functions. Depending on your code this may cause a crash or NULL check if you don't properly conditionally call functions based on whether they are available.

If you are doing that and you've verified that 1.3 is available and enabled then it sounds like it might be a LWJGL bug - I can't reproduce it and what you're describing sounds like a mismanagement of feature enablement or function pointer fetching. Unless I can reproduce it or you can find evidence that it's a RenderDoc bug I don't have anything to go on.

**Comment by RawFish2D** [comment]
Right now my program doesn't check available Vulkan version, it only prints it as well as all other device properties and tries to enable specified version whatever it might be.
And I just checked, when launched inside RenderDoc `vkGetPhysicalDeviceProperties` reports `1.2.0` Vulkan API Version. Outside of it, it reports `1.3.260` which is also reported by GPU drivers.

**Comment by baldurk** [comment]
If you program is not checking for a version before using its functionality then your program is not written correctly. You must check for any functionality - whether that is a core version or extension - and enable it before using it, otherwise yes crashes and misbehaviour is definitely expected.

So following from what you just said: if only 1.2 is reported as available it is illegal to call 1.3 core functions like vkQueueSubmit or vkCmdBeginRendering or vkCmdPipelineBarrier2. Is your program calling those functions anyway even if it's illegal?

**Comment by RawFish2D** [comment]
Yes, right now my program always calls 1.3 functions because it doesn't check API version (it just prints it), even though they illegal to call like that, the problem is that when it's launched inside RenderDoc, LWJGL doesn't report Vulkan API Version correctly, and that's why it seems illegal to call 1.3 functions, but outside of RenderDoc LWJGL reports Vulkan API version correctly.

I also think it's possible that it might be LWJGL bug, but I'm not sure since works fine for me outside of RenderDoc.

**Comment by baldurk** [comment]
If your program is unconditionally calling functions without checking if they are valid then that is definitely the source of the bug. It is not a problem that a different API version is reported under RenderDoc and that is not incorrect - it may happen depending on device capabilities just the same as RenderDoc may change the reported functionality and properties in any other legal way. If your program is not correctly written and does not properly handle different capabilities then it will misbehave and potentially crash.
