### ISSUE TITLE
Export the incremental content of the texture images in the events browser before and after frames

### ISSUE THREAD

**Issue by benzhangdragonplus** [baldurk/renderdoc#3409]
## Description
Hello, developer! I have a requirement that I have been searching for in the API documentation for a long time and have made many attempts, but still cannot be implemented. Therefore, I speculate whether this feature is currently not supported.

My requirement is: I need to export the incremental content of texture between adjacent rendered frames in the Events Browser. Let me give you an example:

  Here are the textures of the two rendered frames I exported：
  
  
![image](https://github.com/user-attachments/assets/9587cfae-da68-4e00-8bbb-7d79ef122d2c)
![image](https://github.com/user-attachments/assets/fb779292-e44f-41ca-bb50-159716d86946)

﻿As can be seen, in the first and second frames, there is only an additional character (which I have framed), and I want to export this character image (only the character, the rest of the background is a transparent channel). 
Or maybe I couldn't find the corresponding Python API (I compiled renderdoc.pyc to use the API), could you please tell me where the relevant API is

looking forward to your reply

## Environment

* RenderDoc version: 1.34
* Operating System: Windows 10
* Graphics API: Vulkan

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing programs that are not your own [is not endorsed or allowed for any reason](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING.md#acceptable-use-of-renderdoc), and I will provide absolutely no support for it.
