### ISSUE TITLE
Latest update to Android's 'Play Protect' prevents RenderDocCmd app to install

### ISSUE THREAD

**Issue by mehlian** [baldurk/renderdoc#3413]
## Description

I downloaded the latest version of RenderDoc (1.34) and it turned out that the 'RenderDocCmd' application that is installed on the phone with Android 10 required to be updated with the newer version.

During the installation of this application, the message 'Google Play Protect' pops up about blocking 'Harmful app' (RenderDocCmd).

However, after selecting the option 'More details' and 'Install anyway', and entering the password in the form of 'pattern' to draw, nothing is installed on the device.

In the previous version of RenderDoc (1.33), the behavior was similar, but the application installed on the device and you could run 'remote server'.

After further investigation, it appears that after updating the Play Store, the 'Play Protect' feature is still blocking the app from installing even though we have allowed it.

## Steps to reproduce

1. Connect Android 10 device to PC (Windows 10 x64) via USB
2. Open RenderDoc v 1.34
3. Go to 'Tools > Manage Remote Servers'
4. Select Android 10 device on list and press 'Run Server'
5. When popup appears on device, select 'install anyway'
6. Installation fails and popup to install again will appear again

Same issue appears when changing from 'Local' to '\<device name\>' option in bottom left corner of RenderDoc window.

As workaround do this:
1. Open 'Play Store' app on device
2. Go to Account settings (tap on your avatar at top right corner) - you must be logged in
3. Select 'Play Protect' option
4. Go to 'Play Protect' settings (tap on cog icon at top right)
5. Turn off 'Scan apps with Play Protect'
6. Install RenderDocCmd app following previous steps.
7. Turn back on 'Scan apps with Play Protect'

Now everything should work as expected.

## Environment

* RenderDoc version: 1.34 (probably all versions are affected. Tested this with 1.33 too - it worked back then, now it does not)
* Operating System: Windows 10 x64 / Android 10 aarch64
* Graphics API: OpenGL ES 3.2

**Comment by baldurk** [comment]
I'm not able to reproduce this on my devices but I spoke to some people who did get the popup. They were able to get through it eventually by clicking 'install anyway' and repeating the process until the app was installed - it might require several attempts and manually granting some permissions that were unable to be granted automatically as a result of this. They could then successfully capture and replay.

When you do get these popups, after clicking 'install anyway' you say that installation fails and the popup appears again - does that repeat forever or if you try a few more times does it eventually install?

It might also be that the workaround you mention of turning off this 'play protect' might be necessary for RenderDoc if the 'play protect' breaks things on your device in such a way that it can't be recovered. Unfortunately Android is a truly terrible and broken platform so problems like this occur constantly and there's little that can be done from the developer side, beyond documenting this limitation or mentioning it in error messages if it can be detected.

**Comment by mehlian** [comment]
>When you do get these popups, after clicking 'install anyway' you say that installation fails and the popup appears again - does that repeat forever or if you try a few more times does it eventually install?

After many tries to install it just gives up.
You can see at 'Remote Host Manager' window that you can again try to 'Run Server', but result is the same.

I'll attach logcat file. It contains couple of tries to install app. Maybe it will provide some clues. Just search for renderdoc.

[logcat.txt](https://github.com/user-attachments/files/16674914/logcat.txt)

**Comment by solidpixel** [comment]
What device are you running on?

**Comment by mehlian** [comment]
Xiaomi Mi 10 Lite 5G
MIUI version 10.0.2.0 Global Stable (QJIEUXM)
Android version 10 QKQ1.191222.002

**Comment by baldurk** [comment]
Do you have a different device you can test with? Ideally from a different manufacturer, as Xiaomi devices have caused a lot of problems and incompatibilities in the past.

To clarify: you may have to install the app multiple times going through the popup each time, manually grant permissions afterwards, and then reconnect once the server is installed.

**Comment by mehlian** [comment]
I've tested RenderDocCmd installation on Samsung Galaxy A20e (One UI 1.1; Android 9) and app installed (and launched) on second try after 'Install anyway' option was selected. 

Play Protect was enabled, but I was logged off of the Play Store. You can find Play Protect feature in Android's settings (just search for it). RenderDocCmd app is listed as 'Harmful app' there with option to uninstall.

Weird thing is that RenderDocCmd is listed twice there as if 2 apps were installed.

**Comment by baldurk** [comment]
In that case it sounds like the issue of being unable to go successfully through the "install anyway" path is a Xiaomi-device specific problem. As mentioned these devices have had quite a few unique problems in the past. If you want to use them I'd recommend using the workaround of disabling playprotect that you have.

The two apps is normal and expected and will happen even if this error doesn't occur, at least for 64-bit devices because there is a different app for 32-bit and 64-bit.
