### ISSUE TITLE
Can't build renderdoc (-Werror=cast-user-defined)

### ISSUE THREAD

**Issue by zefir1990** [baldurk/renderdoc#3417]
## Description

Trying to build renderdoc on Linux. Got error "-Werror=cast-user-defined"

## Steps to reproduce

1. git clone git@github.com:baldurk/renderdoc.git
2. cd renderdoc
3. cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild -H.
4. make -C build
5. get error

## Environment

* RenderDoc version: source
* Operating System: Arch Linux x86_64
* Graphics API: Vulkan, OpenGL

`
[ 39%] Building CXX object renderdoc/driver/vulkan/CMakeFiles/rdoc_vulkan.dir/vk_common.cpp.o
In file included from /home/demensdeum_stream/Sources/renderdoc/renderdoc/core/resource_manager.h:38,
                 from /home/demensdeum_stream/Sources/renderdoc/renderdoc/driver/vulkan/vk_common.h:78,
                 from /home/demensdeum_stream/Sources/renderdoc/renderdoc/driver/vulkan/vk_common.cpp:25:
/home/demensdeum_stream/Sources/renderdoc/renderdoc/driver/vulkan/vk_common.cpp: In instantiation of ‘void DoSerialise(SerialiserType&, VkPackedVersion&) [with SerialiserType = Serialiser<SerialiserMode::Writing>]’:
/home/demensdeum_stream/Sources/renderdoc/renderdoc/driver/vulkan/vk_common.cpp:936:1:   required from here
   51 |   template void DoSerialise(Serialiser<SerialiserMode::Writing> &, type &); \
      |                                                                          ^
/home/demensdeum_stream/Sources/renderdoc/renderdoc/driver/vulkan/vk_common.cpp:934:49: error: casting ‘VkPackedVersion’ to ‘uint32_t&’ {aka ‘unsigned int&’} does not use ‘VkPackedVersion::operator uint32_t() const’ [-Werror=cast-user-defined]
  934 | BASIC_TYPE_SERIALISE_STRINGIFY(VkPackedVersion, (uint32_t &)el, SDBasic::UnsignedInteger, 4);
      |                                                 ^~~~~~~~~~~~~~
/home/demensdeum_stream/Sources/renderdoc/renderdoc/serialise/serialiser.h:1677:40: note: in definition of macro ‘BASIC_TYPE_SERIALISE_STRINGIFY’
 1677 |     ser.SerialiseValue(type, byteSize, member);                          \
      |                                        ^~~~~~
/home/demensdeum_stream/Sources/renderdoc/renderdoc/driver/vulkan/vk_common.cpp: In instantiation of ‘void DoSerialise(SerialiserType&, VkPackedVersion&) [with SerialiserType = Serialiser<SerialiserMode::Reading>]’:
/home/demensdeum_stream/Sources/renderdoc/renderdoc/driver/vulkan/vk_common.cpp:936:1:   required from here
   52 |   template void DoSerialise(Serialiser<SerialiserMode::Reading> &, type &);
      |                                                                          ^
/home/demensdeum_stream/Sources/renderdoc/renderdoc/driver/vulkan/vk_common.cpp:934:49: error: casting ‘VkPackedVersion’ to ‘uint32_t&’ {aka ‘unsigned int&’} does not use ‘VkPackedVersion::operator uint32_t() const’ [-Werror=cast-user-defined]
  934 | BASIC_TYPE_SERIALISE_STRINGIFY(VkPackedVersion, (uint32_t &)el, SDBasic::UnsignedInteger, 4);
      |                                                 ^~~~~~~~~~~~~~
/home/demensdeum_stream/Sources/renderdoc/renderdoc/serialise/serialiser.h:1677:40: note: in definition of macro ‘BASIC_TYPE_SERIALISE_STRINGIFY’
 1677 |     ser.SerialiseValue(type, byteSize, member); 
`

**Comment by baldurk** [comment]
You didn't specify which compiler you're using, but from googling it sounds like this warning is new in GCC 14 so I'm assuming you're using that. The commit should disable the warning.
