### ISSUE TITLE
std430 layout for uniform in Vulkan displays as std140

### ISSUE THREAD

**Issue by JesseRMeyer** [baldurk/renderdoc#3423]
## Description

Hi,

For a Vulkan 1.3 application, I have the following uniform buffer defined
`layout(std430, binding = 0) restrict readonly uniform UBO { ... }` and the `uniformBufferStandardLayout` feature enabled (although the latter may not be necessary anymore), but RenderDoc (build from hash 88be65d1) believes that the layout is `#pack(std140)`, both in terms of the padding rules it displays, as well as the "Uniform Buffer Custom Format" window.

I note in the SPIR-V RenderDoc shader disassembly, the `struct UBO : [[Block]]` makes no mention of the Block layout, the GLSL (SPIR-V Cross) display incorrectly states `layout(set = 0, binding = 0, std140) uniform UBO`, while SPIR-V Asm (spirv-dis) correctly states `layout(binding = 0, std430) restrict readonly uniform UBO {`.

If all three thought the layout specifier was 140, then I would have suspected an issue with my shader compiler `glslc`, but since at least one gets it right, that's no longer a smoking gun.  I've looked through other similar issues, so I think this is a feature that should be supported in RenderDoc.

## Steps to reproduce

Happy to share a repo, but the capture is rather large due to a significant amount of textures loaded.  Is there a way to tell RenderDoc to save some kind of sparse (no textures, for instance) capture?

## Environment

* RenderDoc version: 1.35
* Operating System: Win 10
* Graphics API: Vulkan 1.3

NV 3060, Vulkan beta driver 553.02

**Comment by baldurk** [comment]
Yes, some kind of repro case is definitely necessary to investigate this as without that I don't have enough information to go on as you haven't given any specific details. Sharing the SPIR-V file would be a good start, but it may not be enough on its own so sharing a capture would be best as you've said you are willing to share it.

There is no way to create a customised sparse capture since there is no way for RenderDoc to know which textures are important or not, or may lead to crashes/GPU hangs/misbehaviour/etc. The only way to make a smaller capture is to do that in your application - reduce the workload of your program when capturing e.g. with a test level.

It would also help if you explained why std140 layout is invalid for your UBO and why the displayed packing is wrong as a result of it being incorrectly identified - what in your UBO is impossible/invalid to describe with std140 layout? Presumably something with an array as there are few differences between std140 and std430?

You also mention spirv-dis displaying the packing as std430, but that is impossible as that is not something that spirv-dis displays. Do you mean that that's the SPIRV-Cross output?

**Comment by JesseRMeyer** [comment]
Here's the zipped SPIR-V shader.  I'll work on reducing the size of the capture.

[atmospheric_shadowing_v_d.zip](https://github.com/user-attachments/files/16829002/atmospheric_shadowing_v_d.zip)

This is less a "I want 430 to work" and more "I so happened to debug a uniform block layout specified with 430 and RenderDoc's UI didn't seem to recognize that".

I did mean SPIR-V asm (spirv-dis) but upon a closer look it seems to be storing a carbon copy of my shader's text before the actual code bytes start (part of debug info, I presume).

**Comment by JesseRMeyer** [comment]
Here is a capture.  To locate the problem, expand the `Render` column in the Event Browser, colored blue, then expand the Atmospheric Shadowing column,  then select the vkCmdDraw.  Switch to the `VS` Pipeline state, select the Uniform Buffer, press the -> Go button.  Show Padding.  The tooltip will specify std140 explicitly when mouse hovering over a padding row, and if the Column Formatter button `{}` is pressed, the Custom Format text indicates `#pack(std140)`.

https://drive.google.com/file/d/1wYp5XDs0HhwT50PWKvm_8VEE_6XcuUGU/view?usp=sharing

**Comment by baldurk** [comment]
Looking at the shader provided there doesn't look like there is any bug there. Your UBO definition is std140 compatible so it would produce identical SPIR-V whether you specified std140 or std430 (minus debug info duplicating your source). It is not possible in general to know whether you used std430, std140, or even scalar layout, so RenderDoc displays the most compatible definition that still works for the UBO as specified.

Unless it displays any wrong values, padding or offsets there's no wrong behaviour here. Is there an actual bug or incorrect behaviour anywhere here? Does it misbehave if you have a different UBO which requires std430 and is not std140 compatible? You said that you think this feature should be supported by RenderDoc but I'm not sure what is going wrong exactly.

**Comment by JesseRMeyer** [comment]
I see, if there's no way for RenderDoc to know the difference here then choosing the most compatible format is clearly reasonable.  As a user I expected the uniform specifier to be reflected in the debugger's UI as-is, because otherwise it's not obvious what is happening, so it's confusing.  There is no known miscalculation that I'm aware of.

**Comment by baldurk** [comment]
OK, thanks for clarifying that it is working correctly.

RenderDoc can tell the difference if you have a UBO layout which would be invalid for std140 - the most obvious example being `float a[4]` taking up 16-bytes. But effectively if you declare a feature but then never use it it's equivalent to the feature never being declared at all. For example if you had typedefs or #defines or other source-level-only concepts they would not show up in RenderDoc's reflection either.

std140/430 packing is a GLSL concept and does not translate into SPIR-V which specifies offsets and strides of data only. Other shading languages have other packing systems and all those do is say 'apply these rules when packing elements of this buffer'.

In theory you could have debug/reflection information that provided all of this information such as the source level packing scheme etc, but that doesn't exist today and I don't think there's enough value in there for that to be worth plumbing through compilers and tools etc.

**Comment by JesseRMeyer** [comment]
Thank you for your continued support!
