### ISSUE TITLE
Render Overlay Quad Overdraw is Broken when using Vulkan Multiview

### ISSUE THREAD

**Issue by mazvalente** [baldurk/renderdoc#3424]
## Description

When using the Quad OverDraw Overlays in RenderDoc on APKs that make use of Vulkan's Multiview, the displayed overlays are incorrect. Instead of displaying the results of the drawcalls being executed for the selected view, in each slice the overlay will contain the combined overlays for all of the views.

The expectation is that the overlay for each view/slice should be overlaying the draws happening in that particular view/slice, rather than the cumulative draws across all views/slices, since this obscures the image and can make debugging very difficult especially for objects that are not visible in every view.

## Steps to reproduce
(Sample capture [AvgFirst.zip](https://github.com/user-attachments/files/16881481/AvgFirst.zip) which showcases the bug on a Unity app in the Meta Quest 3 headset)

1) Capture a frame of an app using the multiview extension
2) Replay the app in RenderDoc
3) Select one of the two Quad OverDraw Overlays while in the primary view (slice 0) and notice that the overlay is not correct
4) Swap to another view (in my sample slice 1) and notice that the overlay is identical while the image has changed

Note that if you try any overlays other than Quad OverDraw (Pass) or Quad OverDraw (Draw) the overlay functions as expected, it is only these two overlays which have an issue.

## Environment

* RenderDoc version: 1.34
* Operating System: Android (Meta Quest, software version 68)
* Graphics API: Vulkan

## Sample images:
No Overlays
![baseline](https://github.com/user-attachments/assets/6170a122-43be-4671-bc79-aba1f95d4d11)
Quad Overdraw (Draw) Overlay in the first slice
![Quad Overdraw view1](https://github.com/user-attachments/assets/96e0a238-58b0-4fa6-80fd-9b7dfb639eab)
Quad Overdraw (Draw) Overlay in the second slice
![Quad Overdraw view2](https://github.com/user-attachments/assets/1595b0e5-8e8c-42e4-8791-a91273406709)

**Comment by baldurk** [comment]
You mentioned multiview but I think the important point here is that this is with MSAA - can you test this with multiview but with no MSAA?

The quad overdraw overlay does not work with MSAA on Vulkan - this should be documented and ideally signposted better somehow.

Note that quad overdraw does not make sense when MSAA is enabled so on other APIs what you get is the overlay with MSAA disabled, which produces unreliable results too. On vulkan it is not feasible to turn off MSAA for a single draw so the overlay is not functional.

**Comment by mazvalente** [comment]
Thank you for the feedback! Unfortunately it looks like the issue is not MSAA dependent, I created a new sample and removed any MSAA and I still get similar results, the only difference I'm seeing is that without MSAA the second view I have does not show a quad overdraw overlay at all. Captures are attached [Captures.zip](https://github.com/user-attachments/files/16898370/Captures.zip) (from a Quest 2 headset)

No overlay:
<img width="623" alt="sample_no_msaa_no_overlay" src="https://github.com/user-attachments/assets/72d97991-a22f-44a6-bd90-5ff2a848d132">
Quad Overlay (Pass):
<img width="611" alt="sample_no_msaa_quad_overlay_pass" src="https://github.com/user-attachments/assets/f1b83fdf-af06-426c-af60-b95013a32c24">

**Comment by baldurk** [comment]
OK thanks for testing that. It's definitely MSAA dependent and these are not similar results as these screenshots do now show the overlay in some form, whereas your previous screenshots showed no overlay at all.

**Comment by baldurk** [comment]
That commit should implement multiview support for the quad overdraw overlay. I've also added a change that indicates that it's not supported for MSAA on vulkan.
