### ISSUE TITLE
Vulkan HLSL with source edit issue

### ISSUE THREAD

**Issue by Goshido** [baldurk/renderdoc#3425]
## Description

I added [`VK_KHR_shader_non_semantic_info`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_shader_non_semantic_info.html) device extension and made capture from _RenderDoc_.

I do get _HLSL_ shader code. But if I try to modify shader source I get compilation error from _DXC_ under _RenderDoc_. For example

```cpp
#include "blit_program.inc"


[[vk::binding ( BIND_IMAGE, SET_BLIT )]] <-------------------------------------------
Texture2D<float32_t4>           g_image:        register ( t0 );

...

```

```txt
Running "D:/Development/VulkanSDK/1.3.290.0/Bin/dxc.exe" ...
C:/Users/Goshido/AppData/Local/Temp/shader_input:8:17: error: use of undeclared identifier 'BIND_IMAGE'
[[vk::binding ( BIND_IMAGE, SET_BLIT )]]
                ^
```

I started experimenting. I modified each `-I` parameter to compiler in _RenderDoc_ command window and provided absolute paths to every single include directory. Still got same error.

My next experiment: I intentionally made mistake in include file name like this

```cpp
#include "blit_program-oopsy.inc"

...

```

Compiler error did not change again. It looks like _RenderDoc_ removes `#include` from source files and fed them into `DXC`. Would you kindly help?

## Steps to reproduce

1. Take _Vulkan HLSL_ shader code which contains `#include`'s
1. Compile it with  `-Od` and `-fspv-debug=vulkan-with-source`
1. Use that _SPIR-V_ blob in _Vulkan 1.1_ application with extension [`VK_KHR_shader_non_semantic_info`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_shader_non_semantic_info.html) enabled
1. Capture application
1. Go to corresponding drawcall/dispatch and try to modify shader
1. Apply changes

**Problem:** _RenderDoc_ reports compilation error from _DXC_ backend.

**Expected:** Shader source compiled successfully and changes are visible in _RenderDoc_

## Environment

* RenderDoc version: _1.34_
* Operating System: _Windows 11 Pro (23H2, Build 22631.4112)_
* Graphics API: _Vulkan 1.1_
* GPU: _NVIDIA GeForce RTX 4080_, game ready driver _560.94_
* DXC: 
  - _RenderDoc_ uses binary from official _Vulkan SKD 1.3.290.0_, _v1.8.0.4650_(`49d1ae9a0`)
  - _SPIR-V_ blobs are compiled with _v1.8.2407.10013_ from commit `a2a220bc616ca28848ec0af77ad33a09f92fa43a`

## Additional information

Default compilation command after _Edit shader_ button press:

```txt
-T {hlsl_stage2}_6_0 -E {entry_point} -spirv -fspv-target-env={vulkan_ver}  -E PS -T ps_6_8 -HV 2021 -spirv 
-fvk-use-dx-layout -fspv-reduce-load-size -fspv-target-env=vulkan1.1 -enable-16bit-types -WX -I tools\editor\hlsl
-I tools\editor\include -I app\src\main\hlsl -I app\src\main\cpp\include\pbr -Od -fspv-debug=vulkan-with-source
-Fo tools\editor\editor-assets\shaders\blit.ps.spv -Qembed_debug
```

[Link to device report](https://vulkan.gpuinfo.org/displayreport.php?id=32689) on _Vulkan GPU info_ web-resource.

**Comment by baldurk** [comment]
I can't verify with 100% certainty as you didn't include a full reproducible test case but this looks like a DXC bug to me. From a bit of experimentation and checking the source, it looks like the SPIR-V backend doesn't include debug information for include files that only have definitions but no code. You should be able to see that the shader viewer/editor doesn't have source tabs for any such include files.

Without those files it is impossible for RenderDoc to recompile the edited shaders.

This setup:

```
// test.hlsl
#define OUT_COL float4(1, 0, 1, 1)
```

```
// source.hlsl
#include "test.hlsl"

float4 main() : SV_Target0 {
  return OUT_COL;
}
```

built with `dxc -spirv -fspv-debug=vulkan-with-source source.hlsl -T ps_6_0 -Fo test.spv` only includes the source of `source.hlsl` in the output, as verified with `spirv-dis`.

If I make a small change:

```
// test.hlsl
#define OUT_COL float4(1, 0, 1, 1)

void helper() { }
```

```
// source.hlsl
#include "test.hlsl"

float4 main() : SV_Target0 {
  helper();
  return OUT_COL;
}
```

Then the same build works correctly and includes the `test.hlsl` source. You could use this as a workaround until the compiler is fixed.

If you do see the source for those include files in RenderDoc when editing then it's a different bug, but in that case you need to provide a specific repro case as I followed your steps and only by partial luck managed to reproduce this, as if I had used a function in the first place I would not have been able to repro the bug.

**Comment by Goshido** [comment]
Thanks for investigation @baldurk !👍

I created an [issue in _DXC_ repo](https://github.com/microsoft/DirectXShaderCompiler/issues/6907).
