### ISSUE TITLE
The capture prompt from RenderDoc is persistently displayed in the upper left corner of the UE editor and cannot be removed.

### ISSUE THREAD

**Issue by ViperBling** [baldurk/renderdoc#3433]
## Description

![image](https://github.com/user-attachments/assets/ae556a0b-d3dd-4bf6-a5c4-e2d2cc9c6eb7)

This issue only occurs with the UE5.3.2 version engine; other versions of the UE engine do not have this problem. Reinstalling UE5.3.2 does not resolve it.

## Steps to reproduce

It appeared after I compiled a source version of RenderDoc and used Python to operate RenderDoc. The methods I have tried include: reinstalling RenderDoc; reinstalling the UE5.3.2 version engine.

## Environment

* RenderDoc version: v1.34
* Operating System: Window10 64bit
* Unreal Engine Version: 5.3.2

**Comment by hanbim520** [comment]
This should be submitted as an official question to the Unreal Engine

**Comment by baldurk** [comment]
Displaying the overlay is not a bug, it's the default and normal behaviour. Your application can hide it if it chooses but that's up to you.

Is there any actual bug here? If you want your application to hide the overlay you will need to do that or contact someone at Unreal to ask them how to do that.

**Comment by ViperBling** [comment]
> Displaying the overlay is not a bug, it's the default and normal behaviour. Your application can hide it if it chooses but that's up to you.
> 
> Is there any actual bug here? If you want your application to hide the overlay you will need to do that or contact someone at Unreal to ask them how to do that.

Sure, thank you for the assistance. I'll look into how to resolve it on the Unreal side.
