### ISSUE TITLE
Cannot capture contents in a wayland window

### ISSUE THREAD

**Issue by MetsukiMio** [baldurk/renderdoc#3438]
## Description

Renderdoc cannot capture contents in a wayland window

## Steps to reproduce
1. Open any glfw wayland applications (like Minecraft which uses system glfw) with env variable LD_PRELOAD=/usr/lib/librenderdoc.so
2. then the renderdoc hud will show that this is an unknown window, and it's unavailable to capture frames
![图片](https://github.com/user-attachments/assets/aba1df87-e065-4be9-ab4d-b7c96a48fe2c)

## Environment

* RenderDoc version: 1.34
* Operating System: ArchLinux x86_64 rolling
* Graphics API: OpenGL / glfw wayland

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing programs that are not your own [is not endorsed or allowed for any reason](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING.md#acceptable-use-of-renderdoc), and I will provide absolutely no support for it.

**Comment by NikitaWeW** [comment]
I have the same problem with almost the same enviroenment:
+ RenderDoc version: 1.36
+ Operating System: ArchLinux x86_64 rolling
+ Graphics API: OpenGL / glfw wayland

I can not capture [**my application**](https://github.com/NikitaWeW/lopengl) when launching it from the Launch Application panel:
![image](https://github.com/user-attachments/assets/08550a1a-585c-42c2-8ef1-c9c2c0d511ea)

It says Unknown window:
![image](https://github.com/user-attachments/assets/4a581da2-1871-4e36-8e13-711e29c8cd7b)

However, when I enable `Queue Capture with Frame 0 # Frames 1`, only the first frame is captured.

I will create a new issue if needed.

Thanks.

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
