### ISSUE TITLE
Cannot open rdc capture in renderdoc app

### ISSUE THREAD

**Issue by joye-ramone** [baldurk/renderdoc#3440]
## Description

Cannot open capture. Verified on different PC - same error. Log captured from game engine OGSR (sources available)

## Steps to reproduce

1. download https://drive.google.com/file/d/1aJFvJ7o2-CWmaJn2raxi28txhfSd9RfR/view?usp=sharing
2. open capture in render doc
3. error apper says: 

```
---------------------------

---------------------------
Failed to open '_frame745.rdc' for replay

Replaying the capture encountered invalid/corrupted data: Reading invalid array or byte buffer - 3203137261 larger than total stream size 16440384.
---------------------------
OK   
---------------------------
```

full log:
```
RDOC 002860: [15:37:48]          rdcfile.cpp( 250) - Log     - Opening RDCFile \renderdoc_captures\_frame745.rdc
RDOC 002860: [15:37:48]          rdcfile.cpp( 250) - Log     - Opening RDCFile \renderdoc_captures\_frame745.rdc
RDOC 002860: [15:37:48]             core.cpp(  61) - Log     - Not enabling API validation during replay
RDOC 002860: [15:37:48]             core.cpp(  66) - Log     - Using default GPU replay selection algorithm
RDOC 002860: [15:37:48]             core.cpp(  75) - Log     - Replay optimisation level: Balanced
RDOC 002860: [15:37:48]     d3d11_replay.cpp(4118) - Log     - Capture was created on nVidia / NVIDIA GeForce RTX 4070 Ti
RDOC 002860: [15:37:48]      dxgi_common.cpp(2085) - Log     - Selected nVidia / NVIDIA GeForce RTX 4070 Ti adapter for replay
RDOC 002860: [15:37:48]     d3d11_replay.cpp(4442) - Log     - Created device.
RDOC 002860: [15:37:48]     d3d11_replay.cpp( 143) - Log     - Running replay on nVidia / NVIDIA GeForce RTX 4070 Ti 32.0.15.6094
RDOC 002860: [15:37:48]     d3d11_replay.cpp( 216) - Log     - nVidia GPU detected - trying to initialise nVidia counters
RDOC 002860: [15:37:48]      nv_counters.cpp( 207) - Warning - NV GPU performance counters could not locate 'NvPmApi.Core.dll'
RDOC 002860: [15:37:48] nv_d3d11_counters.cpp(  71) - Warning - NvPerf library failed to initialize
RDOC 002860: [15:37:48] replay_controller.cpp(2170) - Log     - Created replay driver.
RDOC 002860: [15:37:50]         serialiser.h(1529) - Error   - Reading invalid array or byte buffer - 3203137261 larger than total stream size 16440384.
RDOC 002860: [15:37:50]     d3d11_device.cpp(1370) - Log     - Timer chunk initialisation - 1655.903 ms
RDOC 002860: [15:37:50] replay_controller.cpp(1934) - Log     - Shutting down replay renderer
```

## Environment

* RenderDoc version: 1.34 https://github.com/baldurk/renderdoc/commit/323726cde8d959f264595690ed00234993dbe5bd
* Operating System: Windows 11  [Version 10.0.22621.4169]
* Graphics API: DirectX 11

**Comment by baldurk** [comment]
Looking at this I can't tell only from the capture why it has been corrupted, but judging by the surroundings near the corruption this might be caused by a Map() buffer overrun or other memory trample. I would recommend running your program with a memory verifier or possibly using RenderDoc's "Verify buffer access" capture option.

If you've checked that you don't have any memory errors in your program then please share a reproducible test case, either here or in private, so I can investigate what's going wrong at capture time.

**Comment by baldurk** [comment]
This could also be caused by incorrect threading behaviour in your code, if you access the same context from multiple threads without enabling thread-protection in D3D11. Check that you do not have any incorrect threading use.

**Comment by joye-ramone** [comment]
> enabling thread-protection in D3D11

that make sense. we use multiple cmd_list from diff threads.
I will check that is enabling thread-protection and back

**Comment by joye-ramone** [comment]
no ... it is not related
it is related with DLSS changes in engine
but I still cannot find a root cause

**Comment by joye-ramone** [comment]
Ok, I found phase that broke render doc capture (though this till looks ok in game)
So I think we can close ticket for now
Sorry for the false alarm
