### ISSUE TITLE
Exception access violation when initializing Vulkan with RenderDoc layer in v1.31+

### ISSUE THREAD

**Issue by SWinxy** [baldurk/renderdoc#3441]
## Description

I'm running into a problem where initializing Vulkan with the layer `VK_LAYER_RENDERDOC_Capture` causes an exception access violation in `renderdoc.dll` when using version 1.31 or later. Initializing Vulkan without that layer or when using 1.30 initializes Vulkan successfully. Initializing Vulkan with other layers, like `VK_LAYER_LUNARG_api_dump` or `VK_LAYER_KHRONOS_validation` successfully initializes with their respective layers.

## Steps to reproduce

My project is written in Java using LWJGL's excellent Vulkan bindings. I've zipped up a [sample Java project](https://drive.google.com/file/d/1LsUmw-iScrZZTZE1ctsVK8JokGOE1SzH/view) which reproduces the crash for me, along with a sample crash log. The log points out the problematic frame, but is unable to give more information: `renderdoc.dll+0xe5d836`. This project is built on Java 22, though it should not matter what Java version it's using. My dependency manager is Maven, which is installed with IntelliJ IDEA CE (what I suggest be used to replicate).

The following Java code is all that is needed. It reads very similarly to C:

```java
try (MemoryStack stack = MemoryStack.stackPush()) {
	VkApplicationInfo pApplicationInfo = VkApplicationInfo
			.calloc(stack)
			.applicationVersion(VK_MAKE_VERSION(1, 3, 0))
			.pApplicationName(stack.UTF8("Scratch file"));

	VkInstanceCreateInfo pCreateInfo = VkInstanceCreateInfo
			.calloc(stack)
			.sType$Default()
			.pApplicationInfo(pApplicationInfo);

	// Enabling renderdoc capture causes the crash
	pCreateInfo.ppEnabledLayerNames(stack.pointers(stack.UTF8("VK_LAYER_RENDERDOC_Capture")));

	PointerBuffer pInstance = stack.mallocPointer(1);
	int result = vkCreateInstance(pCreateInfo, null, pInstance);
	if (result != VK_SUCCESS) {
		throw new RuntimeException(String.valueOf(result));
	}
	long instance = pInstance.get();
	System.out.println("Created instance " + instance);
}
```

## Environment

* RenderDoc versions: 1.31–1.34
* Operating System: Windows 11, Version 10.0.22631 Build 22631
* Graphics API: Vulkan 1.3.28

**Comment by baldurk** [comment]
Enabling the RenderDoc layer yourself manually is incorrect, you should never do this as it has never been documented or allowed. If this happens an error code is returned but possibly your code or some other layer on your system is not handling that properly and causing a crash.

**Comment by SWinxy** [comment]
I didn't know that the layer is not to be used, sorry! Linking to the DLL works.

**Comment by baldurk** [comment]
Linking to the DLL is also extremely incorrect. Please read the documentation and follow the instructions on how to use RenderDoc correctly, do not make up entirely wrong ways of doing things or else you are likely to cause yourself future problems and it will absolutely not be supported in any way.

**Comment by SWinxy** [comment]
I incorrectly wrote 'linking' instead of 'loading' in my reply. I'm loading it in my app at runtime if available, based on what I understand of [the API documentation](https://renderdoc.org/docs/in_application_api.html) and the example code. If this isn't the right way of using the API, that's on me; this is not a familiar area.
