### ISSUE TITLE
API: None with dlopen

### ISSUE THREAD

**Issue by Wambomango** [baldurk/renderdoc#3443]
## Description

Hello!

I want to use the API using dlopen to load librenderdoc.so to debug my OpenGL application.
I do the loading at the start of main, therefore I expect any gl calls to be hooked and captured.
I can find and attach my application using qrenderdoc, though it says "API: None" and nothing gets captured.
![image](https://github.com/user-attachments/assets/06b03967-978e-48b2-b7cb-59479374ac5b)

Thank you for your help!

## Steps to reproduce
test.cpp:
```
#include <renderdoc/renderdoc_app.h>
#include <dlfcn.h>

#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>
#include <glad/glad.h>

int main(int argc, char **argv)
{
    RENDERDOC_API_1_6_0 *rdoc_api;
    if (void *mod = dlopen("librenderdoc.so", RTLD_NOW))
    {
        pRENDERDOC_GetAPI RENDERDOC_GetAPI = (pRENDERDOC_GetAPI)dlsym(mod, "RENDERDOC_GetAPI");
        int ret = RENDERDOC_GetAPI(eRENDERDOC_API_Version_1_6_0, (void **)&rdoc_api);
    }

    glfwInit();
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 6);
    GLFWwindow *window = glfwCreateWindow(1, 1, "window", NULL, NULL);

    glfwMakeContextCurrent(window);
    gladLoadGLLoader((GLADloadproc)glfwGetProcAddress);

    glfwSetWindowSize(window, 640, 480);
    while (!glfwWindowShouldClose(window))
    {
        rdoc_api->StartFrameCapture(NULL, NULL);

        int width, height;
        glfwGetFramebufferSize(window, &width, &height);
        glViewport(0, 0, width, height);

        glClear(GL_COLOR_BUFFER_BIT);
        glfwSwapBuffers(window);
        glfwPollEvents();

        rdoc_api->EndFrameCapture(NULL, NULL);
    }

    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
```
Compiling and running the above code results in the described behaviour.

## Environment

I run the code within a vscode dev container with gpu passthrough.

* RenderDoc version: 1.34
* Operating System: Ubuntu 24.04
* Graphics API: OpenGL 4.6

**Comment by baldurk** [comment]
Your code is not correct, please read [the documentation](https://renderdoc.org/docs/in_application_api.html) and follow the instructions there - in particular when calling `dlopen` you should pass `RTLD_NOW | RTLD_NOLOAD` to ensure you only load the library when launched from RenderDoc. You should also protect to make sure you don't crash as currently when your program is not launched from RenderDoc the library will not be present and your program will crash when calling `rdoc_api` if it's `NULL`.

Otherwise this works correctly for me and I can't reproduce the problem. I compiled your test program and launched it from RenderDoc and I got a huge number of captures generated as you are capturing every frame.

**Comment by Wambomango** [comment]
Thank you for your reply!
I read the docs once more and it looks like I was making assumptions, my bad.
Though, can you help me understand one more thing I am really struggling to understand?


I did an experiment where I created a cmake target for renderdoc like this
```
add_library(renderdoc SHARED IMPORTED GLOBAL)
set_target_properties(renderdoc PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/lib/librenderdoc.so")
target_include_directories(renderdoc INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/include/")
install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/lib/librenderdoc.so" DESTINATION lib/${PROJECT_NAME})
```
and using it to build my application like this
```
add_executable(Test test.cpp)
target_link_libraries(Test glad glfw renderdoc -Wl,-rpath -Wl,\$ORIGIN -Wl,-z,origin)
```
When I started my application (not through the UI), the capture overlay was present and I could attach through the UI after the fact.


I was thinking, that I might be able to get the same behaviour by `dlopen("librenderdoc.so", RTLD_NOW)`, as this loads the library just the same (I assume?), installs the hooks (given I do it early enough before using the graphics API) and enables the remote access.

This does not work and with my limited knowledge I cannot figure out why. I have read this

> To begin using the API you need to fetch the RENDERDOC_GetAPI function. You should do this dynamically, it is not recommended to actually link against RenderDoc’s DLL as it’s intended to be injected or loaded at runtime.

in the docs which tells me not to do what I did in this initial experiment, but what is the actual mechanism behind it not working?

Thank you!

**Comment by baldurk** [comment]
You should never link against RenderDoc. I would personally not recommend using cmake for the RenderDoc API as that massively overcomplicates things - just copy the header into your project and include it where necessary.

If you are not launching your program from the UI you are not using RenderDoc correctly and misbehaviour is not surprising. Please read the documentation and be sure you use RenderDoc properly.
