### ISSUE TITLE
Vulkan: Debug overlay missing when swapchain has no color target usage set

### ISSUE THREAD

**Issue by TiemoJung** [baldurk/renderdoc#345]
Hi,

as the title says, when a swap chain is created whit images that are not enabled for use as a color target, then the debug overlay does not work (and probably spews a lot of validation errors).

**Comment by baldurk** [comment]
I presume you are doing something like I do - creating them with TRANSFER_DST only and doing all rendering off screen. I don't have a sample to hand that I could easily modify to do that, but if that's the case I think this commit should fix the problem.

Can you try it out and see? If not I'll look at it next week when I can construct a proper repro case.

**Comment by TiemoJung** [comment]
Seems to be working now, thanks!
