### ISSUE TITLE
Add Blacklist when [Capture Child Process] is ON

### ISSUE THREAD

**Issue by noobdawn** [baldurk/renderdoc#3454]
## Description

I have noticed that the [Capture Child Process] feature in RenderDoc can cause the target application to fail to launch under certain circumstances.

For example, when I try to capture steam.exe, it launches steamwebhelper.exe. When the [Capture Child Process] option is enabled, steamwebhelper.exe gets hooked, which then prevents steam.exe from launching.

I would like to suggest a blacklist mechanism where processes listed will not be hooked. I have already made modifications in my forked version, and it seems to work. If you don't have the time to add this feature, I would be happy to help.

![explorer_vaYYeTCHHZ](https://github.com/user-attachments/assets/78bc91f5-1c4e-487a-8cec-52d95108e014)

Please forgive me any unintentional rudeness. This is my first time attempting to submit modifications to someone else's project.

## Environment

* RenderDoc version: 1.36
* Operating System: Windows 10 19045.3693

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing programs that are not your own [is not endorsed or allowed for any reason](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING.md#acceptable-use-of-renderdoc), and I will provide absolutely no support for it.
