### ISSUE TITLE
d3d12 pipeline state deferred build problem

### ISSUE THREAD

**Issue by Mario-Cui** [baldurk/renderdoc#3455]
## Description

when  d3d12 create command list with pipeline state, but due to deferred  build,pipeline state not valid in this time, causing create command list fail 

## Steps to reproduce

Refer to the attached RDC file

## Environment

* RenderDoc version: 1.35
* Operating System: win10
* Graphics API: d3d12
[D3D12MeshletCull_frame357.zip](https://github.com/user-attachments/files/17430419/D3D12MeshletCull_frame357.zip)

**Comment by baldurk** [comment]
Thank you, yes this bug was reported after v1.35 release and fixed a little while ago. The latest nightly builds include the fix.
