### ISSUE TITLE
Can't Inject RenderDoc into chrome

### ISSUE THREAD

**Issue by yjerroud** [baldurk/renderdoc#3456]
## Description

Cant't inject RenderDoc into chrome, normally this works on windows 10 I don' t know if the issue is chrome or renderdoc related.

## Steps to reproduce

I Run chrome with the following command : cmd /C "set RENDERDOC_HOOK_EGL=0 && "C:\Program Files\Google\Chrome\Application\chrome.exe" --gpu-startup-dialog --disable_direct_composition=1 --disable-gpu-sandbox"
and before (or even after) clicking on the dialog box shown by Chrome when I try to inject renderDoc into chrome exe I get this message from renderdoc
![image](https://github.com/user-attachments/assets/4ae534c6-ae4e-4017-af3e-14da96596a9d)

## Environment

* RenderDoc version:  1.35 (built from 8a394019) (Qt Version 5.15.2)
* Operating System: Windows 11 Pro 23H2
* Graphics API: WebGL 2.0
* Chrome Version : 130.0.6723.59

**Comment by baldurk** [comment]
Due to the very high rate of abuse from people using RenderDoc to extract copyrighted data from google maps, I unfortunately do not provide any support for capturing from chrome. If you have a legitimate use case I apologise but this policy has become necessary.
