### ISSUE TITLE
Serialise_glClearNamedBufferDataEXT does not handle data=NULL case

### ISSUE THREAD

**Issue by jra101** [baldurk/renderdoc#347]
My OpenGL app has this line in the render loop:

`glClearBufferData(GL_SHADER_STORAGE_BUFFER, GL_R8UI, GL_RED, GL_UNSIGNED_BYTE, nullptr);`

When I try to capture this app with RenderDoc, my app crashes in WrappedOpenGL::Serialise_glClearNamedBufferDataEXT which unconditionally does this memcpy:

` memcpy(val, data, s);`

From http://docs.gl/gl4/glClearBufferData:

_If data is NULL, then the buffer's data store is filled with zeros._

So this function needs a check for data==NULL.

**Comment by baldurk** [comment]
Thank you for the clear report - I'll get a fix in for this shortly.

**Comment by baldurk** [comment]
I think that commit should do the trick - as you say, just need to check for NULL and the default values are already 0.

Let me know if this fixes it for you, it'll be in the next nightly build or you can build a copy locally.

**Comment by jra101** [comment]
Just tried capturing with the 2016-09-06 nightly build and my app no longer crashes when calling glClearBufferData. Thanks for the quick fix!
