### ISSUE TITLE
D3D11 Applications wont's Launch via RenderDoc

### ISSUE THREAD

**Issue by softinitializing** [baldurk/renderdoc#3471]
## Description of Bug

HI,
I am working on a DirextX11 renderer with SharpDX, the SwapChain is hosted in a WPF HwndHost,
Whenever i launch the exe from RenderDoc it wont open
I simply locate the exe and click launch.
So I tried to use some games i have, mainly Dark Souls 3 that uses DirectX 11 API and Elden Ring that uses DirectX 12 API
DS3 would open and immediately close while ER works fine and i can capture as intended .
I have tried some other D3D11 games as well as the [SharpDX DirectX11 Tutorials ](https://github.com/RobyDX/SharpDX_Demo)
but i would experience the same behavior as DS3
I also tried a D3D12 SharpDX sample and it worked without a problem .

## Steps to reproduce

Opening any DX11 application will cause the issue for me 
like here 
![Animation](https://github.com/user-attachments/assets/707b5cc7-b994-48dc-991a-484d3c0a5255)
the game opens , stays white for a few seconds then closes .

## Environment

RenderDoc version: 1.35
Operating System: Win11 ,Dell Laptop with intel 620 UHD and RTX3050
Graphics API: DirextX11

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing programs that are not your own [is not endorsed or allowed for any reason](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING.md#acceptable-use-of-renderdoc), and I will provide absolutely no support for it.
