### ISSUE TITLE
Display the numerical value of "no reesource" arguments

### ISSUE THREAD

**Issue by NogginBops** [baldurk/renderdoc#3479]
## Description of Feature

When debugging errors in OpenGL it would be useful to be able to see the numerical value of arguments passed that evaluate to "no resource" in renderdoc.
![image](https://github.com/user-attachments/assets/5817acb4-84c9-4157-9089-04b4a44d1dcc)

All I'm asking is for the ability to see what number is passed so it can be debugged why this value was passed or why it's not a valid resource.

## Environment

* RenderDoc version: v1.35
* Operating System: Windows 10
* Graphics API: OpenGL

**Comment by baldurk** [comment]
This should only happen if you explicitly unbound a program, or passed a handle which is completely invalid, so this display is as intended.

If you're passing an invalid handle that is not something RenderDoc is intended to be able to debug and you should make sure you fix your application to address any invalid API use using the API's built-in validation before using RenderDoc.

**Comment by NogginBops** [comment]
What I'm asking for is the ability to know what number was actually sent to the command.
This is information that renderdoc should have access to, I don't see why this isn't something that renderdoc could display.

Someone sent me a renderdoc capture that worked on their computer but doesn't work on my computer and being able to see numerical value of this argument would be really helpful for debugging why it works for them and not for me.
