### ISSUE TITLE
Using bufferDeviceAddress while not supporting bufferDeviceAddressCaptureReplay errors ungracefully

### ISSUE THREAD

**Issue by jmsaunde** [baldurk/renderdoc#3490]
## Description of Bug

GPUs not supporting bufferDeviceAddressCaptureReplay when required by RenderDoc (for example, through bufferDeviceAddress usage) result in vkCreateDevice returning VK_ERROR_FEATURE_NOT_PRESENT in the client application. This was confusing for me and I had to build RenderDoc locally and debug through the wrapper code to understand that it was requesting bufferDeviceAddressCaptureReplay and causing the device creation to fail.

I think what would be best is if RenderDoc had a popup indicating why it had failed (requesting bufferDeviceAddress brought in bufferDeviceAddressCaptureReplay, which was unsupported) with an explainer, since the code works fine outside of RenderDoc.

## Steps to reproduce

I am trying to make a capture of a Vulkan program using the bufferDeviceAddress feature. I'm using the onboard Radeon iGPU on my 7950x. It doesn't support bufferDeviceAddressCaptureReplay. The WrappedVulkan::vkCreateDevice code adds bufferDeviceAddressCaptureReplay to the enabled features list with a comment indicating it had been verified to exist, but I'm not seeing in the code where that verification would happen. I also don't see anything in the "Errors and Warnings" list, or where it might otherwise be logged.

I can verify that explicitly checking through vkGetPhysicalDeviceFeatures2 with a VkPhysicalDeviceVulkan12Features pNext does indicate bufferDeviceAddress isn't supported when running in RenderDoc. Unfortunately, my code was not set up checking all of these since it was prototyping work - but I don't think that will be a particularly uncommon use case.

My app wouldn't be the easiest to share the code for. If you want, I'm willing to spend some time isolating it in a single file repro case for you. Please say if you want this. It might still be difficult for you to repro without a similar setup, but I'm also willing to try out patches locally.

## Environment

I reproed this with both latest shipping version, then home-built off github head (97c7586758f7d87a43a7c79fd1fea19613bf7815).

* RenderDoc version: 1.35
* Operating System: Windows 10
* Graphics API: Vulkan 1.3

This machine also has a dGPU (a 4080, the 'primary' video out device). I am choosing the integrated one explicitly in code.

**Comment by baldurk** [comment]
Your program must enumeratte and check for features before enabling them, if it does not then VK_ERROR_FEATURE_NOT_PRESENT is the correct return value to receive. RenderDoc does not intend to support invalid applications so if your program is receiving that in response to enabling a feature which is explicitly reported as unsupported then that is expected and there is not a bug here. This would behave no differently if running on a driver which did not support BDA.
