### ISSUE TITLE
Usability: Remember expanded entries in API Inspector

### ISSUE THREAD

**Issue by djeedai** [baldurk/renderdoc#3495]
Thanks for RenderDoc. This is an amazing tool!

## Description of Feature

While debugging some GPU particle system, I often find myself having to compare data between various points in the pipeline. This is made difficult by the fact several pieces of UI do not remember which items are selected or expanded.

In particular, for this specific item: in the API Inspector, an indirect call like vkCmdDispatchIndirect() shows the buffer and offset of the indirect args. Those properties are initially collapsed when selecting the command in the Event Browser:

![image](https://github.com/user-attachments/assets/7aca61b3-b72d-4f51-adcc-7d4285483951)

When trying to compare those args between different Events, each time I have to select the event then expand it to see the values. This means I cannot quickly go back and forth with the UP/DOWN arrows between events in the Event Browser; instead each time I have to pause and use the mouse to expand the item in the API Inspector.

I appreciate this feels like a small thing, but this would be an amazing usability feature.

## Environment

* RenderDoc version: 1.35
* Operating System: Win11
* Graphics API: Vulkan (not relevant)

**Comment by baldurk** [comment]
If you're not seeing this behaviour then this is a bug - the UI already remembers these in most cases.

For example the exact situation you're talking about:

![already_remembered](https://github.com/user-attachments/assets/7843b50b-22de-4e79-ad0f-9b4d922b5891)

Can you please double check that you are not mistaken, and if so provide a reproducible test case and a video of what you're seeing?

**Comment by djeedai** [comment]
Yes, the UI remembers if you expand an event, then select another one and come back. 

However that assumes you first go over all events you want expanded and manually expand them. I have in my bug repro 99 indirect dispatch calls. For me to quickly compare their args, I need to go over those 99 events and expand them all. 

What this feature suggests is that for a similar event (here `vkCmdDispatchIndirect`) the UI understands and remembers a shared state to expand or collapse them all at once. That way I can expand the command on the first event, and then navigate through all events with the same expanded layout. 

I do appreciate it's a non-trivial request, more complex than the per-event state currently implemented. I don't have a good alternative in mind though unfortunately. 

Thanks!

**Comment by baldurk** [comment]
Oh right, I see what you mean. I would describe that as remembering, that is a kind of batch-applying or locking things between different events.

I don't think this is widely applicable or useful - I would suggest you look at writing a python extension to easily automate what you're doing rather than making it slightly less tedious to do by hand. If you're going through 99 indirect dispatch calls looking at the API inspector then perhaps there's some information that's missing which you should be able to get at better elsewhere.
