### ISSUE TITLE
[Feature] ARM64 Windows Platform Support for RenderDoc

### ISSUE THREAD

**Issue by robotchaoX** [baldurk/renderdoc#3497]
## Description of Feature

ARM64 Windows Platform Support for RenderDoc

I did some initial support for ARM64 Windows. Patches are here: https://github.com/robotchaoX/renderdoc/pull/1
Test some DX11/DX12/Vulkan testcases it could work.
Could this be accessible by mainline?

Update some third-party module:
- Qt 5.15.2
- Python 3.11.9
- dbghelp in Windows SDK 10.0.22621.0

## Environment

* RenderDoc version: v1.35+
* Operating System: Win11 24H2
* Graphics API: DX11/DX12/Vulkan
* Platform: ARM64 Windows (Qualcomm(R) Adreno(TM) 8cx Gen 3)

**Comment by baldurk** [comment]
No I have no plans to ever support ARM outside of Android.
