### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [baldurk/renderdoc#350]
[Extra null pointer checks are not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") in [macros like "`SAFE_DELETE`" and "`SAFE_DELETE_ARRAY`"](https://github.com/baldurk/renderdoc/blob/3693a17c73c85d10abbebe430318cf50dcc425f2/renderdoc/common/common.h#L36 "Update candidates: SAFE_DELETE …").

**Comment by baldurk** [comment]
Having seen your activity on other repositories I'm still not entirely clear if you're a troll, a partially-automated system, or what exactly.

The end result though is consistently noisy and unhelpful though. For that reason I'm closing this and I would politely ask you not to make other comments, or open any other issues.

**Comment by elfring** [comment]
Do you get an useful impression if you look at [a few additional information sources](https://lkml.org/ "Another example for free software development") once more?
