### ISSUE TITLE
Disassembly not recognizing gl_FragDepth and giving warning about a commented extension

### ISSUE THREAD

**Issue by paulvirtuel** [baldurk/renderdoc#3503]
## Description of Bug

I get the following errors after a capture when I look at the Disassembly window:
Disassembly Type: SPIR-V (RenderDoc)
----------------------------------------------------------
Disassembly to SPIR-V failed:

Shader failed to compile:

WARNING: source0.glsl:3: '#extension' : extension not supported: GL_EXT_texture_array
ERROR: source2.glsl:796: 'gl_DepthRange' : undeclared identifier 
ERROR: source2.glsl:796: 'near' : unknown swizzle selection 
ERROR: source2.glsl:796: 'near' : unknown swizzle selection 
ERROR: source2.glsl:796: 'near' : vector swizzle selection out of range 
ERROR: source2.glsl:796: '' : missing #endif 
ERROR: source2.glsl:796: '' : compilation terminated 
ERROR: 6 compilation errors.  No code generated.
----------------------------------------------------------

In my fragment shader, these are the lines that seem to be causing the warning/errors:
//Done in #extension GL_EXT_texture_array : enable
  ...
#if LOGARITHMIC_Z_BUFFER == 1
   ...
#else
   gl_FragDepth = lerp(gl_DepthRange.near, gl_DepthRange.far, 9.0/10.0);
#endif

## Steps to reproduce

In a fragment shader, at these lines:
//Done in #extension GL_EXT_texture_array : enable
#if LOGARITHMIC_Z_BUFFER == 1
   // commented lines
#else
   // any code using gl_DepthRange.near and gl_DepthRange.far
   gl_FragDepth = (gl_DepthRange.near + gl_DepthRange.far) / 2.0;
#endif

## Environment

* RenderDoc version: 1.35
* Operating System: Window 10
* Graphics API: OpenGL 4.6

**Comment by baldurk** [comment]
This looks to me like expected behaviour - you are using a GLSL construct which is not legal for compilation to SPIR-V, so the compilation fails and gives you the error message about what the problem is. It's not a bug to display a valid compile error.
