### ISSUE TITLE
Request for Windows ARM64 build..

### ISSUE THREAD

**Issue by oscarbg** [baldurk/renderdoc#3506]
## Description of Feature

Hi,
I would love a Renderdoc Windows ARM64 for my Windows ARM64 Vulkan testing..
it's little strange still not released as we have Elite X PC's with Windows ARM64 Qualcomm driver shipping for half a year and also we have a Vulkan SDK for Windows ARM64..

I'm running Windows ARM64 on a Parallels Windows VM on a M4 Mac Mini..
I downloaded current Renderdoc 1.36 Windows build..
using Vulkan SDK 1.3.296 for Windows ARM I compiled a simple Windows ARM64 executable vkgears demo from:
https://gitlab.freedesktop.org/mesa/demos/-/blob/main/src/vulkan/vkgears.c?ref_type=heads
or use included vkcube.exe

using lavapipe Win ARM64 Vulkan driver ( https://github.com/mmozeiko/build-mesa/releases/download/24.3.1/mesa-lavapipe-arm64-24.3.1.zip) these two sample work by setting:
set VK_ICD_FILENAMES=lvp_icd.aarch64.json
I made a batch script to launch qrenderdoc after setting VK_ICD_FILENAMES and trying to capture this samples fail with failing to inject renderdoc.dll:

![Captura de pantalla 2024-12-21 064111](https://github.com/user-attachments/assets/b0ee9376-6ddd-46f9-a89a-06968f78b222)

## Environment

* RenderDoc version: 1.36
* Operating System: Windows ARM64 24H2
* Graphics API: Vulkan with Lavapipe 24.3.1 Win ARM64 driver..

**Comment by baldurk** [comment]
No I have no plans to ever support ARM outside of Android.
