### ISSUE TITLE
Issue trying to capture a simple Vulkan ray query sample on NV..

### ISSUE THREAD

**Issue by oscarbg** [baldurk/renderdoc#3507]
## Description of Bug

Hi,
wanting to capture a simple Vulkan ray query sample on Nvidia as it should be supported..
sample is:
https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/ray_queries
and runs OK with:
```
cd Vulkan-Samples/build/linux/app/bin/Release/x86_64
./vulkan_samples sample ray_queries
```
EDIT:
for running like this, need to create some symlinks in Vulkan-Samples/build/linux/app/bin/Release/x86_64:
assets -> ../../../../../../assets
shaders -> ../../../../../../shaders/

## Steps to reproduce

try to capture:
![Captura desde 2024-12-24 04-35-06](https://github.com/user-attachments/assets/208fdea0-83d8-4794-aafa-e06183e64bc3)

get:

```
[info] Logger initialized
[info] Initializing Vulkan sample
[info] Vulkan debug utils enabled (VK_EXT_debug_utils)
[info] Extension VK_KHR_get_physical_device_properties2 found, enabling it
[info] Extension VK_EXT_debug_utils found, enabling it
[info] Extension VK_KHR_xcb_surface found, enabling it
[info] Enabled Validation Layers:
[info] Found GPU: NVIDIA GeForce RTX 4070
[info] Found GPU: AMD Radeon Graphics
[info] Found GPU: llvmpipe (LLVM 19.1.1, 256 bits)
[info] Selected GPU: NVIDIA GeForce RTX 4070
[info] Dedicated Allocation enabled
[info] Device supports the following requested extensions:
[info]   	VK_KHR_get_memory_requirements2
[info]   	VK_KHR_dedicated_allocation
[info]   	VK_KHR_swapchain
[info]   	VK_KHR_shader_float_controls
[info]   	VK_KHR_spirv_1_4
[info]   	VK_KHR_deferred_host_operations
[info]   	VK_KHR_buffer_device_address
[info]   	VK_KHR_acceleration_structure
[info]   	VK_EXT_descriptor_indexing
[info]   	VK_KHR_ray_query
[error] [framework/platform/platform.cpp:149] Error Message: Cannot create device : ERROR_FEATURE_NOT_PRESENT
[error] [framework/platform/platform.cpp:150] Failed when running application ray_queries
```

## Environment

* RenderDoc version: 1.36
* Operating System: ubuntu 24.10
* Graphics API: Vulkan

Nvidia RTX 4070
driver 550.40.82

thanks..

**Comment by oscarbg** [comment]
note sample uses:
```
[info] Dedicated Allocation enabled
[info] Device supports the following requested extensions:
[info]   	VK_KHR_get_memory_requirements2
[info]   	VK_KHR_dedicated_allocation
[info]   	VK_KHR_swapchain
[info]   	VK_KHR_shader_float_controls
[info]   	VK_KHR_spirv_1_4
[info]   	VK_KHR_deferred_host_operations
[info]   	VK_KHR_buffer_device_address
[info]   	VK_KHR_acceleration_structure
[info]   	VK_EXT_descriptor_indexing
[info]   	VK_KHR_ray_query
```

**Comment by baldurk** [comment]
I don't have an nvidia linux system but I can't reproduce this on windows, the sample captures correctly for me on a 4070 on driver 566.03.

I would suggest that you make sure that you are running the driver that you say you're running, perhaps temporarily disable any other ICDs you have. Also your driver version is a beta version, try updating to the latest stable version as it may have improved support. Lastly going only by the line numbers on your error messages you are also not running the latest Vulkan-Samples code so I would recommend that you update that too.

**Comment by oscarbg** [comment]
thanks for feedback..
ultimately was bad luck on my side..
using as you point old version of repo from 29 March 2023 it seems..
git log:
```
commit de7304fbacf442a6c93c8f6e551b09f328b7407c (HEAD -> main, origin/main, origin/HEAD)
Author: Marty Johnson <68354714+marty-johnson59@users.noreply.github.com>
Date:   Wed Mar 29 15:44:33 2023 -0700
    Update README.md
```

and it had a bug the ray_query sample also requested rayTracingPipeline feature:


`request(VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_PIPELINE_FEATURES_KHR, &VkPhysicalDeviceRayTracingPipelineFeaturesKHR::rayTracingPipeline);
`

fixed in commmit in feb'24: 
```
Remove RTP feature request from ray_queries
https://github.com/KhronosGroup/Vulkan-Samples/commit/5177ee62aa0af372114c21a82fc98710947f1ece
```

had done some more tests before and it was failing of course:
1)disabled other ICDS.. 
2)driver is correct:

```
vulkaninfo |grep driver
driverVersion     = 550.40.82.0 (2307527808)
driverInfo           = 550.40.82
```
3) stable driver 550.142
same error
