### ISSUE TITLE
Allow changing object names via the UI

### ISSUE THREAD

**Issue by yuriks** [baldurk/renderdoc#356]
It would be useful to be able to rename objects from their auto-generated names ("Texture 1234", etc.) via the UI. This would help to keep track of them across different draw calls without having to go so far as setting up names for them via the API.

(No rush. :)

**Comment by baldurk** [comment]
Got this in at last :smile: . The new resource inspector panel lets you rename any resource. It will be treated as unsaved changes so you'll be prompted to save the capture if you close it.

I'd still advise that it's better to set these up in code where possible, but this can be useful if e.g. you have pooled resources that it's hard to give a name to programmatically but you want to trace through the frame.

Let me know if you have any trouble, it will be available in the next v1.x nightly build.

**Comment by baldurk** [comment]
v1.0 has now released, including this feature as described above.
