### ISSUE TITLE
Vulkan multiple queues are not supported

### ISSUE THREAD

**Issue by ArtVandelae** [baldurk/renderdoc#373]
I'm having an issue with a crash when running a program though Renderdoc v0.30 or later if I create an image with the share mode set to VK_SHARING_MODE_CONCURRENT, specifying queue families 0 and 1 (universal and transfer on Nvidia) and make a vkCmdPipelineBarrier call to transition the layout with the following parameters:

```
vkImageMemoryBarrier.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
vkImageMemoryBarrier.pNext = nullptr;

vkImageMemoryBarrier.srcAccessMask = 0; // Initial creation
vkImageMemoryBarrier.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
vkImageMemoryBarrier.oldLayout  = VK_IMAGE_LAYOUT_UNDEFINED;
vkImageMemoryBarrier.newLayout  = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;

vkImageMemoryBarrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
vkImageMemoryBarrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;

vkImageMemoryBarrier.image = theImageHandle;

// Image region info follows ...
```

The program will crash with an unhandled exception somewhere in the Nvidia driver nvoglv64.dll which it enters from Renderdoc in the file vk_cmd_funcs.cpp in the function WrappedVulkan::vkCmdPipelineBarrier, line 1930.  

```
ObjDisp(commandBuffer)
    ->CmdPipelineBarrier(Unwrap(commandBuffer), srcStageMask, destStageMask, dependencyFlags,
                         memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, buf,
                         imageMemoryBarrierCount, im);
```

If it is run with the validation layers enabled, then it crashes in VkLayer_core_validation.dll which it enters at the same point.

Outside of Renderdoc the application runs cleanly without warnings or errors from the validation layers and Renderdoc v0.29 doesn't have this issue, just v0.30 and up including the current master branch.  Additionally, if I change the sharing mode of the image to be VK_SHARING_MODE_EXCLUSIVE and perform both the transfer and drawing on the universal queue instead of using the transfer queue then the crash no longer occurs.

Since the crash isn't actually happening within Renderdoc itself I unfortunately can't get an error log or crash dump to include with this report.

**Comment by baldurk** [comment]
At the moment RenderDoc's Vulkan back-end doesn't support multiple queues - it's something I haven't looked into yet to figure out how much there is to add to have proper support.

If you enumerate the available queues via vkGetPhysicalDeviceQueueFamilyProperties you should only get one queue family reported with only one queue in it. This started in v0.30 which possibly explains the crash, as it might be to do with me changing queue properties. Are you seeing multiple queues being enumerated, or are you hardcoding the fetching queues without checking which families are available? I haven't done anything to prevent that currently.

**Comment by ArtVandelae** [comment]
Ah, some of my test code was was hardcoded to use the transfer queue.  Reworking that to respect the enumerated queue counts fixed it.  Thanks for the help.

**Comment by baldurk** [comment]
Cool! I'll leave this issue open to track the lack of queue support.

**Comment by baldurk** [comment]
I've added support for multiple queues, the queues will be reported as-is from the driver, and then remapped on replay - so if the capture used a compute-only queue but is replayed on a device with only a single graphics/compute queue it will use that.

I've tested this as I can on existing programs that use multiple queues, but any further testing and feedback would be welcome.
