### ISSUE TITLE
Errors/Warnings refer to the wrong EID

### ISSUE THREAD

**Issue by Fulg** [baldurk/renderdoc#380]
In the **Errors and Warnings** panel, the listed EID is seemingly off by one. I just happened to have a capture that tried to sample a texture with NaNs as UVs.

In this specific instance the warning occurred while debugging a VS at EID 18202, but the log says the error is from EID 18201 (which is a call to `CSSetConstantBuffers` just before the call to `DrawIndexedInstanced()`.

I traced into `WrappedID3D11Device::AddDebugMessage` and the call to `m_pImmediateContext->GetEventID()` returned 18201, presumably it contains the _last_ executed EID on the context and not the one being debugged.

I'm using RD 0.31. Let me know if you need more information, I unfortunately cannot share the capture that reproduces this issue. :(

Cheers!

![wrong_eid](https://cloud.githubusercontent.com/assets/3320405/18967519/8221dfc4-8653-11e6-91f8-ea892fc8fae8.png)

**Comment by Fulg** [comment]
No longer an issue with the latest code and my original capture, thanks a bunch! Glad this also exposed UAV debugging issues, as those are already tricky enough to debug.

**Comment by baldurk** [comment]
Thanks for checking!

**Comment by Fulg** [comment]
This seems to have come back with RD 0.33, but in the other direction:

![image](https://cloud.githubusercontent.com/assets/3320405/23855701/18e44bc2-07cd-11e7-8f44-059ebbb0125b.png)

**Comment by baldurk** [comment]
Ah this is probably because of 029ffec6e64a0757d2d42a4dcaf83f2023356405. I'll double check, but it should be an easy fix.
