### ISSUE TITLE
Histogram visualization does not care about custom shaders, but the range selectors do

### ISSUE THREAD

**Issue by karyon** [baldurk/renderdoc#385]
I have an R32UI texture with values from 0 to 500,000. i use a custom shader which (among other stuff) divides that value by 500,000.

The histogram always shows the values from 0 to 500,000, whereas i need to put the range selector to (0.0 and) 1.0 so i can see something. If I do that, the histogram is basically empty since it shows the original values and there are almost no original values in the texture in the [0.0, 1.0] range.

**Comment by baldurk** [comment]
With that commit it should now behave as expected - please compile or check the next nightly build and let me know if you run into any issues with it.

**Comment by karyon** [comment]
it seems like there have been no nightlies for the past few days...

**Comment by baldurk** [comment]
Ah crap, that's a misconfiguration on my end. I've kicked a build just now and it's uploaded.

**Comment by karyon** [comment]
it works, thanks.
