### ISSUE TITLE
Histogram update delayed when changing mipmap levels

### ISSUE THREAD

**Issue by karyon** [baldurk/renderdoc#388]
To reproduce:
1. open some log with a texture that has mipmap levels (https://owncloud.hpi.de/index.php/s/TyUzlhe2vxT0wyE has one, "Push Buffer" in "ISM pushpull" event section)
2. select that texture
3. open histogram
4. scroll through miplevels
5. the histogram shows the values of the miplevel selected previously. selecting the currently selected miplevel again in the dropdown menu updates the histogram to the correct values. the first miplevel change after that does not update the histogram.

**Comment by baldurk** [comment]
This was a bug added with the fix to #385. Because I changed it to use the currently selected settings instead of passing through the settings each time from the UI, there was a 1 update lag as I updated the histogram before I applied the UI's settings to the output.

**Comment by karyon** [comment]
works as expected, thanks!

**Comment by baldurk** [comment]
Thanks!
