### ISSUE TITLE
Feature request: Texture viewer "Show data before draw"

### ISSUE THREAD

**Issue by sebbbi** [baldurk/renderdoc#389]
RenderDoc seems to be missing a handy feature: Texture viewer should have "Show data before draw" checkbox. It would show the contents of the RT/UAV just before the selected draw call. This would allow you to quickly compare before<->after state of output RTs/UAVs.

History view already kind of implements this, but it opens slowly and is more complicated to use. Single click checkbox to switch between before<->after would be a nice productivity booster.

**Comment by baldurk** [comment]
Maybe I'm misunderstanding, but what's wrong with just selecting the previous drawcall/event? That will show the same thing.

I get what you mean that it would be nice to have an explicit button to toggle back and forth, but I'm not sure if the extra UI is worth the marginal benefit over just going back and forth between two draws.

If you need a keyboard shortcut, you can create a bookmark on any event (in the event browser either the ![image](https://cloud.githubusercontent.com/assets/661798/19149129/9f171744-8bc0-11e6-9946-c9da9547ff7e.png) button or `Ctrl+B`) and then the number key shortcuts `Ctrl+1` through `Ctrl+9` will work globally even if you are focused in the texture viewer.

**Comment by sebbbi** [comment]
Yes, it would just be a convenience feature. Being able to switch between before<->after directly in the texture viewer (one click). I do similar comparisons between two images regularly in other debugging tools and also in Photoshop (repeatedly toggling one layer on/off).

Currently you need to either open the history view or the event browser. And in event browser you don't always have a flat list open, so pressing up/down in event browser doesn't always switch between before<->after. Sometimes up/down jumps between more draws.

Not a high priority issue by any means. Just a small usability improvement for a common use case of mine.

**Comment by baldurk** [comment]
Right, I see what you mean. One thing I could possibly do is add buttons to the event browser to jump to the previous and next drawcall regardless of where they appear in the marker hierarchy. Then you could set bookmarks or use those buttons directly, whatever works.

I'm not sure about having an explicit button to toggle this in the texture viewer. I'll have a think about it but I don't think it's above the value/cost cutoff (the cost here being mostly in avoiding a "kitchen sink" approach to adding features, buttons, etc).

**Comment by baldurk** [comment]
I've added previous/next draw buttons which are mapped to a global shortcut `ctrl-left` and `ctrl-right`. I think that's generally useful and can be nice for stepping through a frame with complex marker hierarchy. I think it's not worth the drawbacks to add a specific toggle for it into the texture viewer.

**Comment by baldurk** [comment]
The previous/next toggle is in v0.32 and I don't plan to add the toggle you were asking for originally, so unless there's a bug I'm going to close this down.
