### ISSUE TITLE
Feature request: Allow overriding F11, F12 keys

### ISSUE THREAD

**Issue by RCalocaO** [baldurk/renderdoc#391]
Some apps (ie UE4 Editor) have hardcoded keys like F11 to make the 3d viewport fullscreen, which makes it hard to capture the editor. Seems like it would be really easy in RD to add a dialog in the settings to switch which keys do the capture and switch viewports. Thanks!

**Comment by baldurk** [comment]
For this kind of thing I'd recommend using the [API available](https://renderdoc.org/docs/in_application_api.html) for applications to change the keys used. You could make them context sensitive, or trigger the capture directly from some button or menu item in your program.

For UE4 there's already [a plugin written](https://github.com/Temaran/UE4RenderDocPlugin) to do all that for you. It would be really nice if that were natively available in UE4, hint hint :wink:.

**Comment by baldurk** [comment]
Given the ease that you can override these commands yourself if you need to (half a dozen lines of code), I don't think it's worthwhile to add a UI to customise them in RenderDoc and pipe that into target processes. I'm going to close this.
