### ISSUE TITLE
StatisticsViewer::OnLogFileLoaded tries to fopen remote captures

### ISSUE THREAD

**Issue by michaelrgb** [baldurk/renderdoc#400]
After a capture is 100% loaded, if that capture is on a remote device then StatisticsViewer::OnLogFileLoaded still attempts to open the file as if it was on the Windows machine, and an exception is thrown:
 
        public void OnLogfileLoaded()
        {
            statisticsLog.Clear();
 
            long fileSize = (new FileInfo(m_Core.LogFileName)).Length; // Crashes if .rdc is on remote device
 
This only happens if you have the Statistics Viewer enabled in the GUI.

**Comment by baldurk** [comment]
I didn't check this explicitly on remote logs, but the direct access to the file is gone now, I rely on the underlying serialiser to get the file size.

I also spotted another call to `Path.GetFileName` that would likely fail on remote paths, so I replaced that. Can you let me know how you get on with those changes?

**Comment by michaelrgb** [comment]
Stats Viewer works fine now. Thanks!
