### ISSUE TITLE
Feature Request: Dark Theme

### ISSUE THREAD

**Issue by Aborres** [baldurk/renderdoc#405]
Are you planning/Could you add a dark theme? It is painful for some of us to use that white programs while programming at night.. 

Thank you for your amazing work

**Comment by baldurk** [comment]
The current UI respects Windows's settings for control colours - background, foreground, active/inactive control etc. You should be able to configure your Windows theme and the UI will update (after a restart at least) - I tested it with the various high contrast themes in windows including a white-on-black theme.

Aside from that though .NET winforms has pretty terrible theming support so there won't be any built-in dark theme.

The plan is though to replace the .NET UI with a Qt one some time next year, and Qt does have very good theming support. On the current partially complete Qt UI I experimented with someone's dark theme and it looked pretty good, although it would probably need some finer tuning:

![image](https://cloud.githubusercontent.com/assets/661798/19702411/d2385824-9aff-11e6-897b-6ff802ecdfc2.png)

**Comment by baldurk** [comment]
With the v1.0 release, RenderDoc now comes with a default theme which has light and dark variants.
