### ISSUE TITLE
Continual memory leak opening and re-opening a capture

### ISSUE THREAD

**Issue by baldurk** [baldurk/renderdoc#406]
Split off from #403, comment by @sibojia:

> Yes. Previously there was no problem on my laptop (Win 8.1), but now I'm working on a Win 10 desktop computer. When opening the same log file repeatedly, RAM grows from 300MB to 10GB, after that the OS warned low memory. 
> ![default](https://cloud.githubusercontent.com/assets/6429444/19717372/d329f902-9b92-11e6-9a78-1255adcc746a.PNG)
> The image above is the performance monitor of VS 2015 when running from source. I opened a log, closed it, and re-opened it many times. RAM usage dropped a little when closing, but kept growing each time opening.

**Comment by sibojia** [comment]
Please get my log file from  https://drive.google.com/open?id=0B0WLIgoZTt4HNzVoUmFIdDJQUEE . Thanks a lot!

**Comment by baldurk** [comment]
I think this should be fixed - thank you for sharing the log, the problem was due to a temporary SRV in a specific multisample state restore, which I might not have reproduced easily myself.

![image](https://cloud.githubusercontent.com/assets/661798/19811198/abc258ec-9d30-11e6-9232-272fcd5fea2b.png)

**Comment by sibojia** [comment]
I have tested on my logs and it worked well. Thanks for the fix!
