### ISSUE TITLE
There is no way to save textures as png without alpha

### ISSUE THREAD

**Issue by karyon** [baldurk/renderdoc#407]
When i tried to export an RGB10A2 texture that has all zeroes in the alpha channel, it exported a PNG that had the alpha channel set to zero everywhere. The alpha channel was not selected in the texture viewer. The alpha mapping option is greyed out for me no matter what format I select.

workaround for me was to save as jpg.

**Comment by baldurk** [comment]
I've added an option to TGA/PNG so you can still specify what will happen with the alpha channel - keep or discard it. It defaults to whether or not the alpha was visible on the texture viewer before-hand.

**Comment by karyon** [comment]
works as i'd expect it to work, thanks!
