### ISSUE TITLE
Windows 10 lockheed martin prepar3d Solved

### ISSUE THREAD

**Issue by dbrgames** [baldurk/renderdoc#408]
Prepar3d.exe Showing the process but then closes nothing happens. Os Windows 10.

**Comment by baldurk** [comment]
This isn't enough information to do anything with. On a cursory examination by googling the filename, this isn't a public/free/trial software that I can go and test myself. Can you give more detail about what steps you take, what exactly happens and what goes wrong? Please also include the log files from the replay and application side.

It's also possible the software has anti-hack/anti-theft protections which are triggering. RenderDoc isn't intended for capturing applications that you don't control so if that's the case then there's nothing I'll do from my side, as any developer on the project would not encounter those protections.

**Comment by dbrgames** [comment]
Hello Log with information

RENDERDOC:  [15:56:02]             core.cpp( 303) - Log     - RenderDoc v0.31 x64 (8213a992c90bb70ab3143635ad1e7c5f7f5d2a6f-official) loaded in replay application
RENDERDOC:  [15:56:02]             core.cpp( 303) - Log     - RenderDoc v0.31 x64 (8213a992c90bb70ab3143635ad1e7c5f7f5d2a6f-official) loaded in replay application
RENDERDOC:  [15:56:20]    win32_process.cpp( 460) - Log     - Injecting renderdoc into process 8948
RENDERDOC:  [15:56:22]    win32_process.cpp( 312) - Error   - Couldn't find module 'renderdoc.dll' among 5 modules
RENDERDOC:  [15:56:22]    win32_process.cpp( 656) - Error   - Can't locate renderdoc.dll in remote PID 8948
RENDERDOC:  [15:56:22]   target_control.cpp( 409) - Log     - Got remote handshake: Prepar3D () [8948]
RENDERDOC:  [15:56:31]    win32_network.cpp( 178) - Warning - recv: 10054

**Comment by baldurk** [comment]
Unfortunately there's still not enough information in that log. Do you have a corresponding log from the application? It should be in %TEMP%, and if the process is crashing then it will be left behind. If it's not crashing, then you can examine it before closing the process.

The error itself indicates that something went wrong during injecting the dll which might explain problems, but then the successful handshake and connection suggests that the dll did get loaded.

Without a repro or at least more specific information about what's going wrong I can't really suggest how to investigate further. You still haven't explained exactly what steps you're following or whether the program is crashing, closing itself down gracefully, or running without being able capture.

**Comment by dbrgames** [comment]
The steps I made were deactivated "windows defender" running "RenderDoc" in adminitrador mode. Capture Log CTRL + N "Execute Path" performed "Capture" button
Conecctando appeared and nothing happened. I went into the folder "% temp%" this empty
