### ISSUE TITLE
buffer vis of mat4 and float4x4 have different element count

### ISSUE THREAD

**Issue by zao** [baldurk/renderdoc#414]
I have a SSBO containing an array of a struct of two `mat4` in my GLSL, which is detected as such when looking at the buffer in RenderDoc 0.31.

The data table in the buffer visualizer only shows a single `vec4` of the data when the fields are declared in RenderDoc as `mat4`. If I change the deduced types to `float4x4`, a full 16-element matrix is shown.

I do unfortunately not have any logs or reproducing project with me at the moment as I only have remote access to the system, so sorry for the verbal-only report.

**Comment by zao** [comment]
The data shown in the `mat4` case seems to consume a `vec4` of data from the buffer. Note that in the first row `instData_worldIT` contains the second column of the actual `instData_world`.
![ofrx9vu](https://cloud.githubusercontent.com/assets/260218/19939727/6e92c83c-a12a-11e6-8a1b-604137d26045.png)
![boo4xrr](https://cloud.githubusercontent.com/assets/260218/19939733/728186c2-a12a-11e6-984b-a4bc82b369ea.png)

**Comment by baldurk** [comment]
Yeh it's a stupid mistake on my part - I had handled parsing of `mat` but only by treating it the same as `float so that the `mat4x4` or `mat4x3` variants would work. I didn't promote `mat4` into `mat4x4`.

**Comment by baldurk** [comment]
Fixed with that commit as I mentioned, square matrices should be handled as expected.

**Comment by zao** [comment]
That commit indeed fixes my problem, verified with nightly.
