### ISSUE TITLE
Bug in viewing non-pow2 volume texture slices

### ISSUE THREAD

**Issue by JarkkoPFC** [baldurk/renderdoc#415]
I have a volume texture of size 400x400x29. When I view slices of this texture one slice is viewed twice and one slice is entirely skipped (slice 14 & 15 are viewed as the same slice). The type of the texture is R8G8_UNORM.

**Comment by baldurk** [comment]
Hey, I think this has been fixed on latest code. I didn't track down which commit it would be, but I think probably in with the fixes to #359. Any recent nightly should do the trick - can you try and see if it works for you?

**Comment by JarkkoPFC** [comment]
Hi, and sorry the late reply. I finally got around to test the nightly build (2016.11.08_09.07.43) and the bug is indeed fixed!

Cheers, Jarkko

**Comment by baldurk** [comment]
Thanks for checking!
