### ISSUE TITLE
Obtaining screen coordinates from 3D object position

### ISSUE THREAD

**Issue by atroudi** [baldurk/renderdoc#422]
Hi,
I am trying to use renderdoc with FIFA game in order to extract player position, so I was looking into how to get the position of 3D objects. I found sv_position in the mesh output, as far as I understand those are coordinates in 3D space, but what I really need is to have the position of the player in the screen coordinates. So is there any transformation to use in order to get from 3D space (sv_position) to screen pixel coordinates?

Thank You!

**Comment by baldurk** [comment]
SV_Position is in clip space, so if you divide through by w you'll get the NDC and you can convert to pixel locations by applying the viewport transform.

This isn't really a RenderDoc question though, and reverse engineering games isn't something I explicitly support. You're generally on your own in that case.

**Comment by atroudi** [comment]
Thanks for the reply!

**Comment by avijit9** [comment]
Which version of renderdoc are you using?
