### ISSUE TITLE
QRenderDoc minor compile fix

### ISSUE THREAD

**Issue by timon37** [baldurk/renderdoc#430]
Hi, I just tried compiling QRenderDoc on linux (awesome that it's moving forward).

The fix for me is just changing the include "math.h" into "cmath"
Note I didn't check if this works on windows, or other linux systems (yet).

I've got qt 5.6.2, gcc 5.4.0, glibc-2.23.
I got these the errors below (sorry but file upload didn't work for me).

`g++ -c -pipe -std=c++11 -Wno-unused-parameter -Wno-reorder -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DRENDERDOC_PLATFORM_POSIX -DRENDERDOC_PLATFORM_LINUX -DRENDERDOC_WINDOWING_XLIB -DRENDERDOC_WINDOWING_XCB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../qrenderdoc -I. -I../renderdoc/api/replay -I../qrenderdoc -I../qrenderdoc/3rdparty/toolwindowmanager -I../qrenderdoc/3rdparty/flowlayout -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I.obj -I.obj -I/usr/lib64/qt5/mkspecs/linux-g++ -o .obj/RangeHistogram.o ../qrenderdoc/Widgets/RangeHistogram.cpp
../qrenderdoc/Widgets/RangeHistogram.cpp: In member function 'bool RangeHistogram::ValidRange() const':
../qrenderdoc/Widgets/RangeHistogram.cpp:65:6: error: '__builtin_isinf_sign' is not a member of 'std'
   if(std::isinf(m_WhitePoint) || std::isnan(m_WhitePoint) || std::isinf(m_BlackPoint) ||
      ^
../qrenderdoc/Widgets/RangeHistogram.cpp:65:6: note: suggested alternative:
<built-in>: note:   '__builtin_isinf_sign'
../qrenderdoc/Widgets/RangeHistogram.cpp:65:34: error: '__builtin_isnan' is not a member of 'std'
   if(std::isinf(m_WhitePoint) || std::isnan(m_WhitePoint) || std::isinf(m_BlackPoint) ||
                                  ^
../qrenderdoc/Widgets/RangeHistogram.cpp:65:34: note: suggested alternative:
<built-in>: note:   '__builtin_isnan'
../qrenderdoc/Widgets/RangeHistogram.cpp:65:62: error: '__builtin_isinf_sign' is not a member of 'std'
   if(std::isinf(m_WhitePoint) || std::isnan(m_WhitePoint) || std::isinf(m_BlackPoint) ||
                                                              ^
../qrenderdoc/Widgets/RangeHistogram.cpp:65:62: note: suggested alternative:
<built-in>: note:   '__builtin_isinf_sign'
../qrenderdoc/Widgets/RangeHistogram.cpp:66:6: error: '__builtin_isnan' is not a member of 'std'
      std::isnan(m_BlackPoint) || std::isinf(m_RangeMax) || std::isnan(m_RangeMax) ||
      ^
../qrenderdoc/Widgets/RangeHistogram.cpp:66:6: note: suggested alternative:
<built-in>: note:   '__builtin_isnan'
../qrenderdoc/Widgets/RangeHistogram.cpp:66:34: error: '__builtin_isinf_sign' is not a member of 'std'
      std::isnan(m_BlackPoint) || std::isinf(m_RangeMax) || std::isnan(m_RangeMax) ||
                                  ^
../qrenderdoc/Widgets/RangeHistogram.cpp:66:34: note: suggested alternative:
<built-in>: note:   '__builtin_isinf_sign'
../qrenderdoc/Widgets/RangeHistogram.cpp:66:60: error: '__builtin_isnan' is not a member of 'std'
      std::isnan(m_BlackPoint) || std::isinf(m_RangeMax) || std::isnan(m_RangeMax) ||
                                                            ^
../qrenderdoc/Widgets/RangeHistogram.cpp:66:60: note: suggested alternative:
<built-in>: note:   '__builtin_isnan'
../qrenderdoc/Widgets/RangeHistogram.cpp:67:6: error: '__builtin_isinf_sign' is not a member of 'std'
      std::isinf(m_RangeMin) || std::isnan(m_RangeMin) || std::isinf(m_RangeMax - m_RangeMin) ||
      ^
../qrenderdoc/Widgets/RangeHistogram.cpp:67:6: note: suggested alternative:
<built-in>: note:   '__builtin_isinf_sign'
../qrenderdoc/Widgets/RangeHistogram.cpp:67:32: error: '__builtin_isnan' is not a member of 'std'
      std::isinf(m_RangeMin) || std::isnan(m_RangeMin) || std::isinf(m_RangeMax - m_RangeMin) ||
                                ^
../qrenderdoc/Widgets/RangeHistogram.cpp:67:32: note: suggested alternative:
<built-in>: note:   '__builtin_isnan'
../qrenderdoc/Widgets/RangeHistogram.cpp:67:58: error: '__builtin_isinf_sign' is not a member of 'std'
      std::isinf(m_RangeMin) || std::isnan(m_RangeMin) || std::isinf(m_RangeMax - m_RangeMin) ||
                                                          ^
../qrenderdoc/Widgets/RangeHistogram.cpp:67:58: note: suggested alternative:
<built-in>: note:   '__builtin_isinf_sign'
../qrenderdoc/Widgets/RangeHistogram.cpp:68:6: error: '__builtin_isnan' is not a member of 'std'
      std::isnan(m_RangeMax - m_RangeMin) || std::isinf(m_WhitePoint - m_BlackPoint) ||
      ^
../qrenderdoc/Widgets/RangeHistogram.cpp:68:6: note: suggested alternative:
<built-in>: note:   '__builtin_isnan'
../qrenderdoc/Widgets/RangeHistogram.cpp:68:45: error: '__builtin_isinf_sign' is not a member of 'std'
      std::isnan(m_RangeMax - m_RangeMin) || std::isinf(m_WhitePoint - m_BlackPoint) ||
                                             ^
../qrenderdoc/Widgets/RangeHistogram.cpp:68:45: note: suggested alternative:
<built-in>: note:   '__builtin_isinf_sign'
../qrenderdoc/Widgets/RangeHistogram.cpp:69:6: error: '__builtin_isnan' is not a member of 'std'
      std::isnan(m_WhitePoint - m_BlackPoint))
      ^
../qrenderdoc/Widgets/RangeHistogram.cpp:69:6: note: suggested alternative:
<built-in>: note:   '__builtin_isnan'
make: *** [Makefile:1302: .obj/RangeHistogram.o] Error 1
19:42:12: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project qrenderdoc (kit: qt5)
When executing step "Make"
`

**Comment by baldurk** [comment]
Eurgh, isinf/isnan seems to be a complete mess on linux compilers :(. I changed it from isnan() to std::isnan() because on a different compiler/version they weren't available *except* in the std:: namespace.

I'll figure out something that will get it to compile.

**Comment by timon37** [comment]
huh ohh sorry for some reason the message got broken I just changed the header from math.h to cmath and then it compiles fine.

**Comment by baldurk** [comment]
It probably got picked up as an html tag. `<math.h>` should be fine though - I think likely I will implement my own `isinf`/`isnan` just to check bits, to sidestep the problem.

**Comment by baldurk** [comment]
I thought I had looked for this before actually and didn't find anything, but Qt has isinf/isnan implementations which just avoid the whole mess.

**Comment by baldurk** [comment]
This should be resolved in v0.32. If something's still not right in the latest build then let me know and I'll re-open and investigate.
