### ISSUE TITLE
RenderDoc causes application crash when using indexed geometry

### ISSUE THREAD

**Issue by disks86** [baldurk/renderdoc#432]
I'm trying to use indexed geometry in my project but the screen is black. I tried to run it through RenderDoc to figure out the issue but the application crashes immediately when running through renderdoc. The last issue I filed only effected the 32bit path so this maybe the same. I'm seeing the following messages from the validation layers that don't appear when running outside of RenderDoc.

[]: DebugReport(Error): SPIR-V module not valid: OpStore Pointer <id> '62's type does not match Object <id> '63's type. 0
[]: DebugReport(Warn): Additional bits in Dest accessMask 0x5000 [VK_ACCESS_TRANSFER_WRITE_BIT | VK_ACCESS_HOST_WRITE_BIT] are specified when layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL. 0
[]: DebugReport(Warn): Additional bits in Source accessMask 0x5000 [VK_ACCESS_TRANSFER_WRITE_BIT | VK_ACCESS_HOST_WRITE_B
[]: DebugReport(Warn): vkGetSwapchainInfoKHR(0xa3, VK_SWAP_CHAIN_INFO_TYPE_PERSISTENT_IMAGES_KHR) returned mismatching data 27
[]: DebugReport(Error): Invalid Semaphore Object 0xddaa660000000d6 5

source: https://github.com/disks86/VK9

using RenderDoc v0.29
CPU: Intel i7
GPU: NVIDIA GeForce GTX 760

**Comment by baldurk** [comment]
Can you try a recent nightly build? I wonder if this is fixed by 400c596894344066647f1cd5af9fc967013711ac. At the least you should update to the latest stable build, v0.29 is 6 months old by now.

**Comment by disks86** [comment]
I just tried the 11/22 nightly build. The messages are gone from the log but the application still crashes when run through RenderDoc. I did notice a new message however it's from a routine that shouldn't be called and doesn't show up when run stand-alone so I'm wondering if there is some memory corruption.

**Comment by baldurk** [comment]
If you mean a routine on your side, is it perhaps to do with the minimal D3D9 support added to RenderDoc since v0.31? It doesn't do much but render an overlay at the moment, but it will end up hooked in between the application and your D3D9.dll shim, and maybe it calls some functions that your test program doesn't.

**Comment by disks86** [comment]
Yes, the method being called is related to swap chains which aren't fully supported. I'll look into the level of effort for implementing the method but if it's hooking D3d9 and Vulkan what will the output look like?

**Comment by baldurk** [comment]
To be honest I don't know exactly, but I'd guess nothing good. Chances are it would be a toss-up which API actually gets captured.

I guess the best option would be rather than launching through renderdoc as normal, you load the dll manually after D3D9 has been initialised (so it isn't hooked). That way it should only hook Vulkan.

Or make a test harness where the application fetches the D3D9 functions from a VK9.dll instead of a 'fake' D3D9.dll, and use that while capturing.

**Comment by disks86** [comment]
I get (No API detected) if I start the sample application and then try to attach RenderDoc, presumably for the same reason it can't attach after the API has been initialized. Is there a way to turn off D3d9 support?

**Comment by baldurk** [comment]
Yes you can't attach to any API after it's been initialised. What I meant was you could manually load it at the right time by loading the dll _after_ D3D9 has been initialised but _before_ you call `vkCreateInstance`. That should do the trick, as long as D3D9 isn't initialised multiple times or something and renderdoc sticks around. Or equivalently just set the `ENABLE_VULKAN_RENDERDOC_CAPTURE=1` environment variable which will effectively do that for you.

The only way to turn of D3D9 support is to compile it out locally - either unload the d3d9 project, or `#if 0` the code in `d3d9_hooks.cpp`, or something like that.

**Comment by disks86** [comment]
The d3d9 instance is what starts the vulkan instance but I was able to work around this with the In-application API. I load the renderdoc.dll if it's available and grab a pointer to the API immediately after I setup my logging and I use "Attach to a Running Instance" from the UI.
