### ISSUE TITLE
Capturing and loading becomes much slower after many logs captured in a single program

### ISSUE THREAD

**Issue by sibojia** [baldurk/renderdoc#434]
I used the global hook to capture frames from GTA, and simulates F12 key every a few seconds in a separate program to trigger capturing. After capturing about 1k frames, the capture time for a frame grows from ~1s to ~5s. Also the time for loading these log files grows from ~5s to ~20s. 
Is there any information accumulating as time passes? If so is there any way not to capture these information? Thanks!

**Comment by baldurk** [comment]
Wow, a thousand frame captures is definitely more than is typical. If that's every 4-5 seconds that's over an hour of running, too.

I think probably there's no easy fix, but could you share one of the last logs - the ones that are slowest to load? I'll see if there's anything obvious I can do.

Also if you are actually sending a fake F12 keypress, it's probably easier just to trigger the capture programmatically through the connection RenderDoc has.

**Comment by sibojia** [comment]
Please download at https://drive.google.com/open?id=0B6qhYXtjS8EgNGpnQkVwcEY0Tzg

Yes typically I will run it for 24 hours :) Generated data are used for algorithm training.

**Comment by baldurk** [comment]
Can you try again with that commit? It should hopefully fix the slowdown over time without breaking anything :).

**Comment by sibojia** [comment]
Worked perfectly. Thanks!
