### ISSUE TITLE
0.31 integrated in UE4 will prevent Swarm from running

### ISSUE THREAD

**Issue by monops** [baldurk/renderdoc#435]
Hello,

Using 0.31 in UE4 4.12 through the the plugin (https://github.com/Temaran/UE4RenderDocPlugin) will prevent Swarm from running.
It crashes with this callstack:
>             UE4Editor-SwarmInterface-Win64-Debug.dll!NSwarm::FSwarmInterfaceImpl::InitSwarmInterfaceManaged(const wchar_t * SwarmInterfaceDLLPath) Line 560                C++
               UE4Editor-SwarmInterface-Win64-Debug.dll!NSwarm::FSwarmInterface::Initialize(const wchar_t * SwarmInterfacePath) Line 75     C++
               UE4Editor-UnrealEd-Win64-Debug.dll!FStaticLightingSystem::CreateLightmassProcessor() Line 1844       C++
               UE4Editor-UnrealEd-Win64-Debug.dll!FStaticLightingSystem::BeginLightmassProcess() Line 577 C++
               UE4Editor-UnrealEd-Win64-Debug.dll!FStaticLightingManager::CreateStaticLightingSystem(const FLightingBuildOptions & Options) Line 223            C++
               UE4Editor-UnrealEd-Win64-Debug.dll!UEditorEngine::BuildLighting(const FLightingBuildOptions & Options) Line 2310             C++
               UE4Editor-UnrealEd-Win64-Debug.dll!FEditorBuildUtils::EditorBuild(UWorld * InWorld, FName Id, const bool bAllowLightingDialog) Line 339   C++
               UE4Editor-LevelEditor-Win64-Debug.dll!FLevelEditorActionCallbacks::BuildLightingOnly_Execute() Line 568                C++
               UE4Editor-LevelEditor-Win64-Debug.dll!TBaseStaticDelegateInstance<TTypeWrapper<void> __cdecl(void)>::Execute() Line 953          C++
               UE4Editor-LevelEditor-Win64-Debug.dll!TBaseStaticDelegateInstance<void __cdecl(void)>::ExecuteIfSafe() Line 1021             C++
               UE4Editor-Slate-Win64-Debug.dll!TBaseDelegate<void>::ExecuteIfBound() Line 608       C++
               UE4Editor-Slate-Win64-Debug.dll!FUICommandList::ExecuteAction(const TSharedRef<FUICommandInfo const ,0> InUICommandInfo) Line 88      C++
               UE4Editor-Slate-Win64-Debug.dll!SMenuEntryBlock::OnClicked(bool bCheckBoxClicked) Line 1027          C++
               UE4Editor-Slate-Win64-Debug.dll!SMenuEntryBlock::OnMenuItemButtonClicked() Line 987        C++
               UE4Editor-Slate-Win64-Debug.dll!TMemberFunctionCaller<SMenuEntryBlock,FReply (__cdecl SMenuEntryBlock::*)(void) __ptr64>::operator()<>() Line 161   C++
               UE4Editor-Slate-Win64-Debug.dll!TTupleImpl<TIntegerSequence<unsigned int> >::ApplyAfter_ExplicitReturnType<FReply,TMemberFunctionCaller<SMenuEntryBlock,FReply (__cdecl SMenuEntryBlock::*)(void) __ptr64> >(TMemberFunctionCaller<SMenuEntryBlock,FReply (__cdecl SMenuEntryBlock::*)(void)> && Func) Line 128 C++
               UE4Editor-Slate-Win64-Debug.dll!TBaseSPMethodDelegateInstance<0,SMenuEntryBlock,0,FReply __cdecl(void)>::Execute() Line 321          C++
               UE4Editor-Slate-Win64-Debug.dll!TBaseDelegate<FReply>::Execute() Line 521  C++
               UE4Editor-Slate-Win64-Debug.dll!SButton::OnMouseButtonUp(const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) Line 275 C++
               UE4Editor-Slate-Win64-Debug.dll!SMenuEntryButton::OnMouseButtonUp(const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) Line 382       C++
               UE4Editor-Slate-Win64-Debug.dll!FSlateApplication::RoutePointerUpEvent::__l8::<lambda>(const FArrangedWidget & TargetWidget, const FPointerEvent & Event) Line 4618         C++
               UE4Editor-Slate-Win64-Debug.dll!FEventRouter::Route<FReply,FEventRouter::FToLeafmostPolicy,FPointerEvent,FReply <lambda>(const FArrangedWidget &, const FPointerEvent &) >(FSlateApplication * ThisApplication, FEventRouter::FToLeafmostPolicy RoutingPolicy, FPointerEvent EventCopy, const FSlateApplication::RoutePointerUpEvent::__l8::FReply <lambda>(const FArrangedWidget &, const FPointerEvent &) & Lambda) Line 215         C++
               UE4Editor-Slate-Win64-Debug.dll!FSlateApplication::RoutePointerUpEvent(FWidgetPath & WidgetsUnderPointer, FPointerEvent & PointerEvent) Line 4607               C++
               UE4Editor-Slate-Win64-Debug.dll!FSlateApplication::ProcessMouseButtonUpEvent(FPointerEvent & MouseEvent) Line 5061 C++
               UE4Editor-Slate-Win64-Debug.dll!FSlateApplication::OnMouseUp(const EMouseButtons::Type Button, const FVector2D CursorPos) Line 5041                C++
               UE4Editor-Core-Win64-Debug.dll!FWindowsApplication::ProcessDeferredMessage(const FDeferredWindowsMessage & DeferredMessage) Line 1510      C++
               UE4Editor-Core-Win64-Debug.dll!FWindowsApplication::DeferMessage(TSharedPtr<FWindowsWindow,0> & NativeWindow, HWND__ * InHWnd, unsigned int InMessage, unsigned __int64 InWParam, __int64 InLParam, int MouseX, int MouseY, unsigned int RawInputFlags) Line 1850      C++
               UE4Editor-Core-Win64-Debug.dll!FWindowsApplication::ProcessMessage(HWND__ * hwnd, unsigned int msg, unsigned __int64 wParam, __int64 lParam) Line 802             C++
               UE4Editor-Core-Win64-Debug.dll!FWindowsApplication::AppWndProc(HWND__ * hwnd, unsigned int msg, unsigned __int64 wParam, __int64 lParam) Line 

Using 0.30 will not give this error.

**Comment by baldurk** [comment]
Looking at the code on UE4's side, it seems like this initialises CLR and so it is quite possible that it runs into  [this bug](https://github.com/baldurk/renderdoc/issues/394).

Can you try the [latest nightly build](https://renderdoc.org/builds#nightly) and see if it works for you?

**Comment by monops** [comment]
Thanks for the answer! I'll wait for the next release, as I can't allocate more time in the upgrade now :(

Cheers!
Alex

**Comment by baldurk** [comment]
I forgot to comment on this when I released it, but v0.32 came out last week. If this isn't fixed there then let me know.

**Comment by monops** [comment]
Thanks very much! I'll let you know as soon as I can try another update :)
