### ISSUE TITLE
Crash on capture in IDXGISwapChain::Present()

### ISSUE THREAD

**Issue by mridgewell** [baldurk/renderdoc#437]
Hi,

Whenever I capture I get a bad_alloc exception. Here's the callstack:
```
KernelBase.dll!7693a6f2()	Unknown
[Frames below may be incorrect and/or missing, no symbols loaded for KernelBase.dll]	
[External Code]	
renderdoc.dll!WrappedID3D11Device::Serialise_InitialState(ResourceId resid, ID3D11DeviceChild * res) Line 1787	C++
renderdoc.dll!D3D11ResourceManager::Serialise_InitialState(ResourceId id, ID3D11DeviceChild * res) Line 110	C++
renderdoc.dll!ResourceManager<ID3D11DeviceChild *,ID3D11DeviceChild *,D3D11ResourceRecord>::InsertInitialContentsChunks(Serialiser * fileSerialiser) Line 1039	C++
renderdoc.dll!WrappedID3D11Device::EndFrameCapture(void * dev, void * wnd) Line 3011	C++
renderdoc.dll!RenderDoc::EndFrameCapture(void * dev, void * wnd) Line 502	C++
renderdoc.dll!WrappedID3D11Device::Present(WrappedIDXGISwapChain4 * swap, unsigned int SyncInterval, unsigned int Flags) Line 3366	C++
renderdoc.dll!WrappedIDXGISwapChain4::Present(unsigned int SyncInterval, unsigned int Flags) Line 491	C++
```

Am I doing something wrong or is this a bug?

**Comment by baldurk** [comment]
That function is responsible in large part for the peak CPU memory usage in RenderDoc, at the end of a capture when reading back all resource contents at the start of the frame (e.g. textures that weren't shadowed offline and render target contents).

From the last frame of the callstack, it looks like you're running in 32-bit mode? If that's the case my guess would be that you're genuinely just running out of memory. Which means that you're not doing something wrong, but it's not really a bug either.

There are no easy wins if that is the case - it's pretty much a matter of running with less memory usage (in this case particularly GPU memory, but obviously if you have a way of reducing your CPU memory footprint then that will help allow for more overhead). Or of course, running in 64-bit is preferred :smile:.

**Comment by mridgewell** [comment]
Thanks for the quick response! You're right - turns out my absurdly high shadowmap resolution was the culprit! I bumped it up as a test and forgot to reset it.

**Comment by baldurk** [comment]
Yep, that would do it :). Glad you got it sorted.
