### ISSUE TITLE
QRenderDoc ubuntu 'make install' problem

### ISSUE THREAD

**Issue by blakemt** [baldurk/renderdoc#438]
I have successfully built renderdoc and qrenderdoc from master, but come install time, I run into trouble. I built with `mkdir bld; cd bld; cmake ..; make -j7 -l7`, but `sudo make install` fails with the error below. Any help would be greatly appreciated.  Thanks.

```
[~/src/renderdoc/bld]$ sudo make install                                                                                                 *[master] 
[  1%] Built target include-bin
[ 20%] Built target rdoc
[ 43%] Built target rdoc_spirv
[ 56%] Built target rdoc_gl
[ 69%] Built target rdoc_vulkan
[ 97%] Built target renderdoc
[ 98%] Built target generate-json
[100%] Built target renderdoccmd
[100%] Generating QRenderDoc
Project ERROR: requires Qt 5.6
qrenderdoc/CMakeFiles/build-qrenderdoc.dir/build.make:61: recipe for target 'qrenderdoc/QRenderDoc' failed
make[2]: *** [qrenderdoc/QRenderDoc] Error 3
CMakeFiles/Makefile2:489: recipe for target 'qrenderdoc/CMakeFiles/build-qrenderdoc.dir/all' failed
make[1]: *** [qrenderdoc/CMakeFiles/build-qrenderdoc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
[~/src/renderdoc/bld]$                                                                                                                   *[master] 
```

**Comment by baldurk** [comment]
I don't think that you have successfully built actually. That error would show up at build time too.

It is fairly self explanatory though - you need at least Qt version 5.6 to build qrenderdoc. There are ppas you can add to install Qt into /opt for building.

**Comment by blakemt** [comment]
Ok, then I'm confused. I see the build process finish compiling librenderdoc.  Then there is a bunch of compiler output which uses files from my Qt 5.6 installation.  Sorry, I forgot to explicitly state that I installed Qt 5.6.2; I used the installer from Qt's website to install to $HOME/Qt.  At the end, it outputs `[100%] Built target build-qrenderdoc`.  Then `sudo make install` fails.  I'll give the ppa a shot.  I've attached the build output if you're curious.

[renderdoc-output.txt](https://github.com/baldurk/renderdoc/files/632455/renderdoc-output.txt)


```

**Comment by baldurk** [comment]
OK yeh that is building then. That's very weird. It's it possible that however you have configured Qt to pick the version in your home directory isn't propagating to the sudo command? I don't know how home folder installs work in Linux.

**Comment by blakemt** [comment]
There's something to that idea. I tried setting everything up and building the entire project as root (`sudo -s`), but I still had trouble.  I got around the need to sudo by setting `VULKAN_LAYER_FOLDER` to a folder I had write access to.  I'll copy those layer files over manually.  Thanks for your help.

**Comment by baldurk** [comment]
right, the layer file can also go under $HOME if needs be, but /etc was more sensible as a default place to install it.

It sounds like you've got it working, and if I understand right it's not something fixable on my side. But if I got the wrong end of the stick please correct me :).
