### ISSUE TITLE
Global Process Hook Not work

### ISSUE THREAD

**Issue by LemonAniLabs** [baldurk/renderdoc#441]
I'm using renderdoc to capture GTAV. Since my game is not on steam, I followed [this instruction](https://renderdoc.org/docs/window/capture_log_attach.html#global-process-hook) to do global process hooking.
I use capture button to launch GTAV, it will work fine.

But when I use global process hooking, and then launch GTAV ,there is nothing happend, and the diagnostic log shows that

> RDOC 028956: [20:39:12]             core.cpp( 308) - Log     - RenderDoc v0.33 x64 (NO_GIT_COMMIT_HASH_DEFINED) loaded in replay application

**Comment by baldurk** [comment]
Can you be more specific about what actually happens or what goes wrong?

After you've enabled the global process hook, when you run the program - does it crash? Does it run but without the overlay/injection happening? Does it exit unexpectedly without crashing? What operating system version are you running?

I'm also not clear on why you are using the global process hook - if you say that you're not running through steam so you can launch the capture directly and that works, why are you wanting to use the global hook?

**Comment by LemonAniLabs** [comment]
I have enabled the global process hook, and my system is Windows 10 x64, GPU ,Nvidia GTX 1070, GTAV run in D3DX11.

I just setting the executable path and click the enable global hook, and then launch GTAV, but no overlay display on gtav screen. And no error message no crash.

Also, I tested with the [Tutorial 1 ](https://code.msdn.microsoft.com/windowsdesktop/Direct3D-Tutorial-Win32-829979ef)in Direct3D Samples, it doesn't work too . It seems global hook can't hook any process?  I have no problem building RendorDoc. Thanks

**Comment by baldurk** [comment]
Do you have 'secure boot' enabled? According to [this article](https://msdn.microsoft.com/en-us/library/windows/desktop/dn280412(v=vs.85).aspx), secure boot disables the AppInit_DLLs registry key that uses for global hooking.

If the case then I'm not sure there's a possible fix - but as I asked before, if you are able to launch the program directly then why do you need the global hook?

**Comment by monajalal** [comment]
@LemonAniLabs I have the same problem as you. When I enable the "Global Process Hook" and then start the GTA nothing happens (no overlay shows even after pressing F12). I bought the game from RockStar Games. 
Can you please share how you fixed this issue?
![renderdocuinew](https://cloud.githubusercontent.com/assets/1892917/21534118/cb782e2e-cd27-11e6-9f5e-6ba2acda3d18.PNG)
![secure](https://cloud.githubusercontent.com/assets/1892917/21534119/cb7f0f5a-cd27-11e6-8606-3f65b7d51235.PNG)

**Comment by moradin** [comment]
Hey, I have a slightly different problem with very similar results. I have a game that I'm developing (not a game on steam) and when I try using the global process hook to inject RenderDoc (the reasons for this I would rather not discuss) the game starts fine but the overlay is not there. Tried checking the processes in File/attach to running instance and nothing shows up. The only log I found in the temp folder has only this:

> RDOC 006592: [11:58:20]             core.cpp( 308) - Log     - RenderDoc v0.33 x64 (NO_GIT_COMMIT_HASH_DEFINED) loaded in replay application
RDOC 006592: [11:59:12]    win32_network.cpp( 333) - Debug   - connect timed out
RDOC 006592: [11:59:12]    win32_network.cpp( 333) - Debug   - connect timed out
RDOC 006592: [11:59:13]    win32_network.cpp( 333) - Debug   - connect timed out
RDOC 006592: [11:59:13]    win32_network.cpp( 333) - Debug   - connect timed out
RDOC 006592: [11:59:13]    win32_network.cpp( 333) - Debug   - connect timed out
RDOC 006592: [11:59:13]    win32_network.cpp( 333) - Debug   - connect timed out
RDOC 006592: [11:59:14]    win32_network.cpp( 333) - Debug   - connect timed out
RDOC 006592: [11:59:14]    win32_network.cpp( 333) - Debug   - connect timed out

I built renderdoc from the latest sources and I'm happy to debug if you can provide some pointers where I should start.

**Comment by m-khurram-amin** [comment]
I am facing same issue with GTA V. Games starts fine with GlobalHook as  well as with Capture Launcher but there is no overlay and F12 or ScrenCapture do nothing. I am not running game directly (not from steam). I have build renderdoc myself and there was no error. I followed this guide https://bitbucket.orgd 6-playing-for-data/overview.

My OS is windows 10 with Nvidia GTX980M.

**Comment by moradin** [comment]
The first problem I had was that I was building renderdoc and building the UI didn't build the shim dll thus it was not added to the registry properly.
The second problem is unfortunately the secure boot. Is there any way to have the global hooks working without switching this off? I'm trying to use renderdoc at work and I can't switch off secure boot on this PC.

**Comment by baldurk** [comment]
@moradin Apparently secure boot disables the AppInit_Dlls registry key, which is up to MS and out of my control. I emailed you separately about your bug though, there should be a way to avoid using the global hook if you control the problem.

To others, I just tested and I can capture fine from GTA5 on steam using the global hook on RenderDoc v0.32. Make sure you're on the latest version and you don't have 'secure boot' enabled as covered above.

I don't want to have to be rude about this, but there have been a number of people asking for help with capturing GTA5 specifically and it's largely turned out to be user error. As I've mentioned before on other bugs I *do not* support capturing from 3rd party games. At this point it's taking time away from other work to diagnose user problems doing something I explicitly don't support, I have to draw a line and say that I will not help with people having trouble capturing GTA5.

Also it goes without saying, I cannot support some fork of RenderDoc that has unknown changes and is based on year-old code. If you are having trouble on that branch you'll need to ask the authors for help.

**Comment by shreyaj** [comment]
@monajalal How did you get renderdoc to capture the game? I am trying to use the playing for data fork to capture but I get Access violation writing location 0x0000000000000000 error and the game crashes on global hook. I am not using Scripthook and global hook works perfectly fine with laetst build of renderdoc. Could you please help me out? Thanks!

@moradin do you have any idea what might be wrong? Thanks!

**Comment by baldurk** [comment]
Hi @shreyaj. RenderDoc doesn't support or help with capturing applications that you don't own the copyright to, nor can it cover problems with unofficial forks that are quite outdated.

Please also avoid tagging individual users for help when they may not welcome such a direct approach, if you have any problems with a recent version of RenderDoc itself using it on programs that you own feel free to contact me directly or open a new issue.
