### ISSUE TITLE
DirectComposition D3D11 swap chains break capture

### ISSUE THREAD

**Issue by nta** [baldurk/renderdoc#446]
When trying to capture a process that uses D3D11 with a swap chain using DirectComposition (`IDXGIFactory2::CreateSwapChainForComposition`), the UI will stay on 'No API detected', and the log will show the following:

```
RDOC 019040: [18:00:09]             core.cpp(1053) - Error   - Invalid FrameCapturer combination: 0X0000000000000000 / 0X00000230D1AA9A90
RDOC 019040: [18:00:09]             core.cpp(1053) - Error   - Invalid FrameCapturer combination: 0X0000000000000000 / 0X00000230D1AA9A90
```

This seems to be because of [d3d11_device.cpp](https://github.com/baldurk/renderdoc/blob/5a243c4b4275076a06380699830e21c4d1eb8259/renderdoc/driver/d3d11/d3d11_device.cpp#L2646) using the `OutputWindow` in the swap chain description as key for this internal structure, where this type of swap chain _has_ no output window.

I encountered this while trying to debug CEF, which seems to [use](https://chromium.googlesource.com/angle/angle/+/chromium/2946/src/libANGLE/renderer/d3d/d3d11/win32/NativeWindow11Win32.cpp#66) this particular device creation mode ANGLE offers for the backing D3D device.

**Comment by baldurk** [comment]
This is probably a simple fix but I need to find a simpler example program I can test with, I'll see what I can do.

**Comment by baldurk** [comment]
I forgot to update this bug - I think this is fixed now, at least with the simple test program I found.

Let me know if it works for you. I'm just kicking a new nightly build now so there should be one available shortly.

**Comment by nta** [comment]
Yeah - this particular issue seems to be resolved now. I've not taken an in-depth look yet, but the DComp-based devices in Chrome appear to be detected now.
