### ISSUE TITLE
RENDERDOC_PLATFORM=win32

### ISSUE THREAD

**Issue by monajalal** [baldurk/renderdoc#462]
What should we select for a 64bit  Windows machine?  I only see Linux and Win32 options.

**Comment by baldurk** [comment]
I don't understand what your question is. The feature/platform macros are controlled internally, you don't (and shouldn't) change them manually. Also RENDERDOC_PLATFORM as a macro was removed/refactored a long time ago so it doesn't even exist.

If you need to capture 64-bit programs, build the x64 target. If you need to capture 32-bit programs, build the Win32 target. If you're building for linux then only 64-bit is supported, and that happens through cmake so there's no target to select at all.
