### ISSUE TITLE
renderdocui.exe doesn't run in Windows 10

### ISSUE THREAD

**Issue by monajalal** [baldurk/renderdoc#463]
so I built the renderdocui and renderdoc using Visual Studio 2015 under Windows 10 home edition and when I right click on renderdocui.exe and run it as administrator nothing happens. Any thought on what could be wrong or how to fix it?
![capture](https://cloud.githubusercontent.com/assets/1892917/21444077/98124d4c-c86f-11e6-91bb-97ef470089d4.PNG)

Here are my successful build reports as well
http://pastebin.com/DCMu5R6A
http://pastebin.com/HipdgDXm

**Comment by baldurk** [comment]
This could be a lot of things. You need to give more detail about what happens exactly than 'nothing happens'. Do you get a log file in %TEMP%\RenderDoc? Also I'm not sure why you're running it as administrator, but if you run it from the debugger then it will be equivalent and will give much more information (for example it is maybe hitting an exception while launching and immediately closing, or something like that).

Are you building from the latest source? I see in the path that you still have this 'playing-for-data' fork. If you're building from that code then I can't help you as it is many months out of date and there could be any number of bugs you are running into which are already fixed. Try to replicate the problem on the latest code here in this repository, and if it breaks then we can investigate.

If it doesn't break with the code here then you will need to report it with the repository for the fork you are actually building.
