### ISSUE TITLE
WeifenLuo.WinFormsUI.Docking.dll' could not be found

### ISSUE THREAD

**Issue by monajalal** [baldurk/renderdoc#466]
when trying to build renderdocui in x64 and debug configuration mode, I get this error. Can you please suggest fixes?
```
Severity	Code	Description	Project	File	Line	Category	Source	Suppression State	Tool
Error	CS0006	Metadata file 'C:\Users\mona\playing-for-data\renderdoc\renderdocui\3rdparty\WinFormsUI\bin\Debug\WeifenLuo.WinFormsUI.Docking.dll' could not be found	renderdocui	C:\Users\mona\playing-for-data\renderdoc\renderdocui\CSC	1	Build	Build	Active	Compiler
```
![124](https://cloud.githubusercontent.com/assets/1892917/21487047/e245c6b4-cb85-11e6-9b7e-775d37e0d626.PNG)
![jjj](https://cloud.githubusercontent.com/assets/1892917/21487048/e245df0a-cb85-11e6-88a8-1c3101cceebe.PNG)

![ekdjejf](https://cloud.githubusercontent.com/assets/1892917/21487076/90a4dc22-cb86-11e6-9396-6dbb1fefe7ff.PNG)

**Comment by baldurk** [comment]
I realise that you're looking for help to try and get things working, but as I've said several times now I won't help with problems when you're compiling a forked project with some unknown code changes and based on almost year-old code from the main branch.

The code compiles normally from a fresh checkout and any recent VS version, and this is verified by appveyor as well as myself and any others compiling the project. I can't promise the same for whatever fork you are using.

If you have problems compiling **this repository** with recent code then file an issue, but if you are still building the other fork then you have to report problems there.
