### ISSUE TITLE
Exporting from the Event Browser does not export "Durations" column

### ISSUE THREAD

**Issue by pranav0091** [baldurk/renderdoc#468]
The EventID, Name and Draw # columns are exported, but not the Duration column even if its active and has been timed (ie, not 0.00) 

Right now I use an AutoIt script to manually send [Right][Down][Ctrl+C] and copy out the info per row- but this is very unreliable/jittery. 

I'm not a programmer per-se, and not familiar with git at this point, or else I'd have attempted a proper-fix myself instead of bugging you with yet another issue. Awesome tool, btw :)

**Comment by pranav0091** [comment]
I have verified that this behaviour persists even in the latest x64 nightly build from Dec 26 - @d249faac

**Comment by baldurk** [comment]
Right, it seems like I only export the event ID, draw ID and name.

It's an easy change to add the durations if they're available.

**Comment by baldurk** [comment]
Durations should be exported with that commit - please check in the next nightly build.

**Comment by pranav0091** [comment]
Yes, the drawcalls-durations are now getting exported :) 

There is one remaining bug with the export though - 
![image](https://cloud.githubusercontent.com/assets/20370575/21677859/1057b970-d362-11e6-84c3-92f6ee4f838a.png)

gets exported as 

          | - Colour Pass #1 (1 Targets + Depth)                                  | 1      | 3.84
    62    |  \- ClearRenderTargetView(0.0000, 0.0000, 0.0000, 0.0000)             | 1      | 3.84
    63    |   - ClearDepthStencilView(0.0000, 00000000)                           | 2      | 13.376
    81    |   - DrawIndexed(30)                                                   | 3      | 87.84


observe how the very first row - "Colour Pass 1" is exported with a value of 3.84 when it should be the sum of the entire pass (= 286.048) as seen in the image above.

**Comment by pranav0091** [comment]
Thanks Baldur, confirming that the fix works. :) 

My bad, this somehow completely dropped off my radar.
