### ISSUE TITLE
Bound 2D shadow textures do not show up under the "Pipeline Output / Fragment Shader" tab

### ISSUE THREAD

**Issue by DominikWitczakAMD** [baldurk/renderdoc#470]
This problem happens, no matter what API commands are used to set up the binding. Since my engine can be configured to use core 4.3 API / DSA / multi_bind extensions, I've checked and the outcome is the same, no matter what API commands are used, so it's probably more of a general problem.

I can provide a repro app, if that would be of help.

**Comment by baldurk** [comment]
Yes a repro app would be quite helpful in this case, if you could provide one! It sounds like it's maybe just some code missing handling of OpenGL's silly funky types like shadow or rectangle textures.

**Comment by baldurk** [comment]
This wasn't related to shadow samplers, it was changing source on a shader object and recompiling not being supported. Should work now according to the repro you sent.

**Comment by DominikWitczakAMD** [comment]
Works like a charm, many thanks!
