### ISSUE TITLE
Feature: Label captures in the "Captures collected:" container

### ISSUE THREAD

**Issue by jeremyabel** [baldurk/renderdoc#476]
I think it'd be pretty useful to be able to label captures in the box that contains all the captures collected in the session. I use the Unreal plugin, so everything comes in as just "UE4Editor-Win64-Debug" with the date and time, and it'd be great to be able to label these with some text to differentiate them a bit more. Example use case would be labeling one "UE4Editor - New Render Feature: On" and another "UE4Editor - New Render Feature: Off"

**Comment by baldurk** [comment]
As luck would have it, this basically already existed in the .NET control. I just had to switch it on and hook it up.

Give it a shot on the next nightly and let me know if it's what you had in mind - the names aren't used for anything else they're just entirely local within that list of captures from a connection.

**Comment by baldurk** [comment]
This was included with [v0.33](https://github.com/baldurk/renderdoc/releases/tag/v0.33) so it should do what you're after. Let me know if there's some extra improvement you'd want to see over what's available there.
