### ISSUE TITLE
which executable should I use for renderdoc?

### ISSUE THREAD

**Issue by monajalal** [baldurk/renderdoc#479]
Can someone who has used GTAV executable for RenderDoc please explain the difference between PlayGTAV.exe and GTAVLauncher.exe? Should both work or should I go with a specific one?  Why?
Thanks!
https://www.reddit.com/r/GrandTheftAutoV_PC/comments/33xoyx/trying_to_get_scripthook_v_working_f4_key_doesnt/

**Comment by baldurk** [comment]
**To anyone who finds this response**: The response below is rude and hurtful and does not convey the attitude I want to have towards users reporting bugs. Please understand that it was made in frustration regarding a situation I do not support, after making it clear this was unsupported in many repeated similar bugs and emails from the same user. While not acceptable no matter the situation it was not intended as a general statement to all users, but specifically to this problem.

Note: the response itself is left unmodified as I think it's dishonest to try and hide what I wrote.

------

This bug tracker isn't for personal questions and help, it's for reporting issues with RenderDoc itself. Please don't open unrelated or irrelevant issues like this, as it only clutters the repository for everyone. You can't always ask for help as soon as anything goes the slightest bit wrong, you have to learn to investigate problems on your own.

Likewise as I've told you directly and mentioned in other issues, I don't officially support capturing other people's products. You are on your own for getting them to capture unless there's an actual RenderDoc bug being exhibited.

Also on top of all of that, you had capturing working just a few days ago. I don't know why you're now confused about which executable to launch.

**Comment by monajalal** [comment]
I came across the idea of mixing script hook V and renderdoc and had issues with PlayGTA5.exe. I assume I should go with GTAVLauncher.exe. I'll update when I come across some sensible results on my experiments.

**Comment by monajalal** [comment]
You should use GTAVLauncher.exe for RenderDoc.
