### ISSUE TITLE
Incorrect buffer padding in BufferViewer

### ISSUE THREAD

**Issue by rkevingibson** [baldurk/renderdoc#485]
Not sure if this is desired behaviour or not, but the buffer viewer incorrectly predicts buffer padding in SSBOs (possibly other buffers as well). I've observed this in OpenGL 4.5 with the std430 layout specifier.

The attached capture has a compute shader dispatched with two SSBOs attached: cells_buffer and particles_buffer. The particles buffer is an array of a particles struct which is 24 bytes large, but should be padded to 32 bytes since its largest member is a vec4. Adding a vec2 to the end of the format string makes it display correctly. 

Looking at the code now, it seems like the BufferViewer doesn't take the packing layout into consideration and just uses the raw stride for layout. 

Either having an option to take the packing into account, or doing it automatically, would be awesome.

[offset_bug.zip](https://github.com/baldurk/renderdoc/files/697177/offset_bug.zip)

**Comment by baldurk** [comment]
I had forgotten or not realised that the std430 packing rules still had padding in some cases and weren't tightly packed.

That commit should do the trick - it queries for the top level stride and then adds a padding element in automatically. It worked for me in that capture, let me know if you find cases where it falls down.

**Comment by rkevingibson** [comment]
Looks great to me! I'll keep an eye out if I see any issues, but I'd call this resolved.

Thanks for the quick work!
