### ISSUE TITLE
Bug: OpenGL: VS Output viewer doesn't show all instances correctly for instanced draw calls

### ISSUE THREAD

**Issue by jpaver** [baldurk/renderdoc#487]
Hey there, 

 I just wanted to file an issue I noticed in v0.32 of your wonderful tool, thanks btw it works amazingly well. 

When viewing Mesh Output / VS Output with instanced draw calls (using glDrawElementsInstancedBaseVertex in OpenGL), it appears only the first instance is drawn. See the attached image (suffix:_meshoutputviewer) which shows only the first instance in the batch is drawn, and the corresponding image (suffix: _textureviewer) for comparison.

Maybe a bit obvious, but I'm using gl_InstanceID to index a UBO in the VS.

![renderdoc_bug_draw81_in_meshoutputviewer](https://cloud.githubusercontent.com/assets/8569715/21878326/5b9b95da-d846-11e6-8ba4-59308a26c49c.png)
![renderdoc_bug_draw81_in_textureviewer](https://cloud.githubusercontent.com/assets/8569715/21878330/5fbb3602-d846-11e6-9543-13fff9f84c4a.png)

**Comment by baldurk** [comment]
Hi there, thanks for the report! I'm not able to reproduce this locally using a capture that calls `glDrawElementsInstancedBaseVertex` - I used the [`gl-400-texture-buffer-rgb`](https://github.com/g-truc/ogl-samples/blob/master/tests/gl-400-texture-buffer-rgb.cpp) sample from g-truc's [ogl-samples](https://github.com/g-truc/ogl-samples):

![image](https://cloud.githubusercontent.com/assets/661798/21887284/42514054-d8b7-11e6-9061-e8ad9ccc89a1.png)
![image](https://cloud.githubusercontent.com/assets/661798/21887289/46d4d942-d8b7-11e6-9601-ce1b80ef2923.png)

So I guess the problem must be more complex or depend on some other factors unique to your case.

Are you able to share the capture or your program with me so I can try to reproduce? If not, can you tell me whether the instance data is as expected - if you change the value in the mesh viewer toolbar from instance 0 to instance 1, does the data show up and the preview render in the right place? I'm wondering if the data for all instances after 0 is wrong, or if it's just the "show all instances" mode which doesn't work correctly.

**Comment by jpaver** [comment]
Thanks for the quick reply - I've sent a capture to you by e-mail.

**Comment by baldurk** [comment]
Resolved over email, it seems like some unknown change fixed this since v0.32.
