### ISSUE TITLE
How to remotely trigger a capture without using renderdocui?

### ISSUE THREAD

**Issue by sibojia** [baldurk/renderdoc#493]
I'm working on a GTA V plugin and I want to trigger a renderdoc capture in the game. The plugin is written in c# and injected into the game with a dll library. Is there a web API for capturing, or do I need to use renderdoc.dll to do the connection and capturing? Thanks!

**Comment by baldurk** [comment]
Doing it remotely without renderdocui might be a bit tricky, you'd need to connect over the socket and use the protocol to trigger a remote capture.

However if you have your plugin injected into the process then there's a simpler solution - you can use the [in-application API](https://renderdoc.org/docs/in_application_api.html) yourself to trigger a capture, the same as any other code in the process.

Someone on the Unity forums I remember did exactly this to be able to use the editor integration to capture parts of the scene that weren't rendered, so there's some sample code showing how to do this from C# using P/Invoke [in this forum thread](https://forum.unity3d.com/threads/how-do-i-get-the-dispatch-call-for-a-compute-shader-to-show-in-renderdoc.380082/#post-2487897)

**Comment by sibojia** [comment]
I successfully triggered a capture with the TriggerCapture API. It's so convenient. Thanks!
