### ISSUE TITLE
Channels are reversed when saving .exr or .hdr

### ISSUE THREAD

**Issue by mavrokefalos** [baldurk/renderdoc#495]
Hello,

After exporting a buffer as an hdr/exr image, I noticed that the color channels are saved in reverse order (resulting hdr/exr viewed with renderdoc and with other viewers). 

![exrtest](https://cloud.githubusercontent.com/assets/7605917/22253999/542e31b8-e24b-11e6-9a33-adba7c0be665.jpg)

**Comment by baldurk** [comment]
I believe this only happened when saving BGR-ordered formats. The above commit should fix it, it'll be in the next nightly build. Let me know if it works for you.

**Comment by baldurk** [comment]
This should be fixed with the above commit which is now in v0.33. If you're still having issues on that version saving images then comment here and I can look into it.

**Comment by mavrokefalos** [comment]
Hey, sorry for not replying earlier. Thanks for the fix!
