### ISSUE TITLE
Mismatch in row major compile settings between original and edited shaders

### ISSUE THREAD

**Issue by bejitt** [baldurk/renderdoc#499]
We have all our dx11 shaders compiled against fxc with /Zpr (aka D3D10_SHADER_PACK_MATRIX_ROW_MAJOR). When I edit one of our shaders in a capture, it looks like the recompile that renderdoc is doing doesn't enable row major matrices.

In our specific case, we have a constant buffer layout like so:
  float3x4 someMatrix;
  float4 someData;
  float4 someData2

After editing+saving the shader, the constant buffer data for those last two variables changes. In fact, the data in 'someMatrix' is transposed.

**Comment by baldurk** [comment]
I tested this and it seems like it works on the case I had (I didn't have a float3x4 matrix to test for sure, but the `PACK_MATRIX_ROW_MAJOR` flag got through and the output was identical.

Do you have debug information included in your shaders and unstripped? That's where the compile flags are stored, so if it's not included then there's no way for me to figure out what flags were used to originally compile.

You could work around it by adding a `#pragma pack_matrix(row_major)` into the source when editing, but including debug info (whether with the shader, or [separated](https://renderdoc.org/docs/getting_started/faq.html#unstripped-shader-info)) is what I'd recommend.

**Comment by bejitt** [comment]
As far as I know, it's taking the full shader output and passing it to the shader create methods. We're definitely seeing source information when editing, I'm not sure if/how I can check if those flags were stripped.

For reference, the DX11 shaders I'm dealing with were compiled with these arguments:
`fxc.exe /nologo /E "entry" /T "ps_5_0" /Zpr /Gec /Zi /Od /Fo "input" "output"`

In addition, we're using fxc with the 46 version of the compiler dll.

**Comment by baldurk** [comment]
Well, that turned out to be an embarrassingly silly typo in the end. The key was you had `/Od`. This caused the first 4 bits of the flag to change from 0x9 = `PACK_MATRIX_ROW_MAJOR | DEBUG` to 0xd = `PACK_MATRIX_ROW_MAJOR | DEBUG | SKIP_OPTIMIZATION`. My hex decoding then broke on the value and decoded the wrong flags. When it worked for me, I only had debug and row major packing flags, so it decoded correctly!

It should be fixed with that commit, it'll be in the next nightly build so let me know how you get on.

**Comment by baldurk** [comment]
I don't have your exact repro but I believe this was fixed with that commit, which is now in version v0.33. If you're still having trouble then let me know and I can investigate further.
