### ISSUE TITLE
D3D11: renderdoc does not replicate the behavior of unbinding UAV hazards

### ISSUE THREAD

**Issue by Pyromuffin** [baldurk/renderdoc#503]
If you bind a UAV on the CS pipe that was previously bound on the OM, then d3d11 complains and unbinds it from the OM.

D3D11 WARNING: ID3D11DeviceContext::CSSetUnorderedAccessViews: Resource being set to CS UnorderedAccessView slot 0 is already bound on output elsewhere. [ STATE_SETTING WARNING #2097354: DEVICE_CSSETUNORDEREDACCESSVIEWS_HAZARD]
D3D11 WARNING: ID3D11DeviceContext::CSSetUnorderedAccessViews: Forcing OM UnorderedAccessView slot 1 to NULL. [ STATE_SETTING WARNING #2097346: DEVICE_OMSETRENDERTARGETSANDUNORDEREDACCESSVIEWS_HAZARD]

In renderdoc this behavior isn't replicated in the OM pipeline state view, still showing the buffer bound. Curiously the texture viewer correctly shows the PS RW resource to be unbound.

**Comment by baldurk** [comment]
Hey, I believe I've fixed this behaviour with that commit, which will be included in the next nightly build. Can you check that it's working for you now on your repro case? It should be retroactive so a capture of it you made before will now display the right state.

**Comment by baldurk** [comment]
I found an additional problem with the first fix that could cause crashes by accidentally deleting RTVs or UAVs that were unbound, so you might want wait for the next nightly build - that's my bad.

I also found a fix for a very old bug. Thank you for reporting this as it set me on the trail to find that one :smile:.

**Comment by Pyromuffin** [comment]
indeed it crashes with the replay I have, I'll test it on tomorrow's build.

**Comment by Pyromuffin** [comment]
by the way, thank you for fixing this so quickly.

**Comment by baldurk** [comment]
I believe this should be fixed in the latest build v0.33. These hazard tracking rules have nasty edge cases and aren't well documented, so there may still be problems - let me know if you find in testing that something is still broken.
