### ISSUE TITLE
Vulkan: Update to Spec 39 and its new extensions

### ISSUE THREAD

**Issue by TiemoJung** [baldurk/renderdoc#504]
Hi,

spec rev 39 introduced a couple of extensions:
- VK_KHR_get_physical_device_properties2
  - adds new functions to query device properties
- VK_KHR_maintenance1
  - adds enums, functions and changes behavior of some functions
- VK_EXT_direct_mode_display
  - adds basic function for display control extensions
- VK_EXT_acquire_xlib_display
  - adds new functions to take over control of a display from xlib
- VK_EXT_display_surface_counter
  - adds functions to query display vblanc counter support
- VK_EXT_shader_subgroup_ballot
  - advertises support for SPV_KHR_shader_ballot
- VK_EXT_shader_subgroup_vote
  - advertises support for SPV_KHR_subgroup_vote
- VK_EXT_swapchain_colorspace
  - adds new enums to support multiple color spaces for swapchains
- VK_KHR_shader_draw_parameters
  - advertises support for SPV_KHR_shader_draw_parameters
- VK_NN_vi_surface
  - adds support for Nintendo display devices

would be nice to have support at least for VK_KHR_maintenance1

**Comment by baldurk** [comment]
I'm currently working on this as we speak. The code will probably be pushed to a secondary branch until I can test at least some of the extensions, as there are only a few examples around that use them. A lot of them though require little to no modification from RenderDoc's side.

The only one that I can't support is VK_NN_vi_surface. Unless someone from Nintendo wants to send me a devkit, then I will happily make RenderDoc work there! :smile:

**Comment by baldurk** [comment]
See [this branch](https://github.com/baldurk/renderdoc/tree/vk-1.0.39-exts).

**Comment by baldurk** [comment]
Merged into main branch now, I'm closing this as it's a fairly general request so difficult to directly verify. If you run into any bugs with any of the newer extensions, feel free to open a new issue.
