### ISSUE TITLE
uncalled ID3D11DeviceContext::UpdateSubresource() event is listed

### ISSUE THREAD

**Issue by lifeisforu** [baldurk/renderdoc#505]
I did not call UpdateSubresource(), but that API is listed in "API Calls" window.

Version : RenderDoc v0.32.

**Comment by baldurk** [comment]
Are you using any utility libraries or middleware? Perhaps that is calling UpdateSubresource().

You can enable callstacks in RenderDoc and then you might be able to see where the call is coming from, although if it comes from a dll without symbols it will only show where it last came from your code.

**Comment by lifeisforu** [comment]
I'm sorry. I tested it on Visual Studio Graphics Debugger, and I confirmed the event( UpdateSubresource() ) is valid. My mistake!

But I found other bug. ID3D11DeviceContext::Map()/Unmap() pair is not matched.

I checked the pair is matched on VS Graphics Debugger. 

Please check an attached image.

![map_unmap_renderdoc](https://cloud.githubusercontent.com/assets/11884712/22616141/01b671fa-eaea-11e6-8c2c-63d5d67cfdbf.png)

**Comment by baldurk** [comment]
Yes RenderDoc doesn't record the Map() call, since on its own it has no effect. I only record calls that actually have an effect on the capture itself, so e.g. I don't record functions that only return data to the user like READ maps, or Get functions.

**Comment by lifeisforu** [comment]
Yes I understood.

Have a nice day.
