### ISSUE TITLE
Renderdoc on gentoo won't work

### ISSUE THREAD

**Issue by newincpp** [baldurk/renderdoc#525]
I was trying RenderDoc for the first time today (because of the GUI news) and it seems that it won't work with gentoo:
`./qrenderdoc: error while loading shared libraries: librenderdoc.so: cannot open shared object file: No such file or directory`
`./renderdoccmd: error while loading shared libraries: librenderdoc.so: cannot open shared object file: No such file or directory`
Gentoo always been known to be a bit annoying with dynamic library so I used the usual trick to make it run:
`LD_LIBRARY_PATH=../lib:.: ./qrenderdoc`
 
But my problem comes when I try to capture an executable I get this:
`ERROR: ld.so: object 'librenderdoc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
I think this is linked but if anyone have any idea how to fix this ?

PS: if I `LD_PRELOAD=~/Downloads/renderdoc_0.32/lib/librenderdoc.so ./demo` there is no problem so it looks like the problem come from the instantiation from renderdoc. If anyone have an idea to workaround(/FIX?)

**Comment by baldurk** [comment]
That seems like very strange behaviour. I [set rpath during linking](https://github.com/baldurk/renderdoc/blob/master/qrenderdoc/qrenderdoc.pro#L83) to include ../lib so it should work without any need to mess with `LD_LIBRARY_PATH` at all.

I don't know exactly what the `LD_PRELOAD` error is about. When qrenderdoc launches a process it sets LD_PRELOAD to librenderdoc.so, and also appends both the dir containing qrenderdoc as well as ../lib, in absolute path form, to `LD_LIBRARY_PATH`.

Are you able to see what the environment is when launching the demo from qrenderdoc? I'm not sure if there's a nice built-in way to do that in linux, but you could [print envp right before execve](https://github.com/baldurk/renderdoc/blob/master/renderdoc/os/posix/posix_process.cpp#L362).

**Comment by baldurk** [comment]
I installed Gentoo today (as in, it took me all day to install it), but I can build and run qrenderdoc fine and I don't have any errors running programs either, although I didn't test extensively. Ditto running from the 0.33 release

Can you provide more information about what exactly you're building and running? Also I noticed just now that your LD_PRELOAD example lists renderdoc_0.32. Is that a typo? You should definitely run v0.33, whether you're running binaries or compiling from source.

**Comment by newincpp** [comment]
I was running 0.32 yes. I updated to 0.33 like you advised and everything is fixed I don't even have to use LD_LIBRARY_PATH or anything, thank you very much ! I'm very sorry (and a bit embarrassed) that you took a day just to install gentoo just for this issue  ｡(*^▽^*)ゞ
