### ISSUE TITLE
No way to restore Capture Executable window in QRenderDoc

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#530]
If you accidentally close the Capture Executable window... there's no (obvious?) way to reopen it!
This issue survives relaunching QRenderDoc.

I had to delete the config at ~/.local/share/qrenderdoc to get the tab again.

**Comment by baldurk** [comment]
Maybe I'm misunderstanding - can't you just go File -> capture log just like you've always been able to? It behaves exactly the same in the Qt UI.

Admittedly the menu item text is a bit out of sync, probably because it's been unchanged since forever, but it opens the panel fine for me.

**Comment by darksylinc** [comment]
I am an idiot. It's not intuitive but I'm also an idiot.
