### ISSUE TITLE
Crash loading Vulkan capture on Intel Mesa driver

### ISSUE THREAD

**Issue by oscarbg** [baldurk/renderdoc#531]
Using Renderdoc 0.33 
Ubuntu 16.10
Vulkan Runtime/SDK: 1.0.39
Intel HD530 using latest Mesa 17.1 dev form Padoka PPA

log:
Log     - QRenderDoc initialising.
Log     - Loading into /home/oscar/Descargas/VulkanSDK/1.0.37.0/examples/build/cube
Log     - Initialised capture layer in Vulkan instance.
Warning - shaderStorageImageMultisample = false, save/load from 2DMS textures will not be possible
../../../../src/compiler/spirv/spirv_to_nir.c:2707 WARNING: Unsupported SPIR-V capability: ImageMSArray
../../../../src/compiler/spirv/spirv_to_nir.c:2707 WARNING: Unsupported SPIR-V capability: ImageMSArray
../../../../src/compiler/spirv/spirv_to_nir.c:2707 WARNING: Unsupported SPIR-V capability: ImageMSArray
Log     - Got remote handshake: cube () [3973]
../../../../src/compiler/spirv/spirv_to_nir.c:2707 WARNING: Unsupported SPIR-V capability: ImageMSArray
../../../../src/compiler/spirv/spirv_to_nir.c:2707 WARNING: Unsupported SPIR-V capability: ImageMSArray
../../../../src/compiler/spirv/spirv_to_nir.c:2707 WARNING: Unsupported SPIR-V capability: ImageMSArray
Log     - Used API: Vulkan
Log     - Starting capture, frame 112
Log     - Finished capture, Frame 113
Log     - Compressed frame capture data from 784214 to 57375
Log     - Timer File writing - 1.177 ms
Log     - Written to disk: /tmp/RenderDoc/cube_2017.02.26_21.16.29_frame113.rdc
Log     - Got a new capture: 0 (time 1488143793) 12058 byte thumbnail
Log     - 'Leaking' unretrieved capture /tmp/RenderDoc/cube_2017.02.26_21.16.29_frame113.rdc
Log     - Creating replay device for /tmp/RenderDoc/cube_2017.02.26_21.16.29_frame113.rdc
Log     - Created device.
Log     - Created replay driver.
Log     - Captured log describes physical device 0:
Log     -    - Intel(R) HD Graphics 530 (Skylake GT2) (ver 0.0 patch 0x1) - 8086:1912
Log     - Replaying on physical device 0:
Log     -    - Intel(R) HD Graphics 530 (Skylake GT2) (ver 0.0 patch 0x1) - 8086:1912
Warning - shaderStorageImageMultisample = false, save/load from 2DMS textures will not be possible
Log     - Ext 0: VK_KHR_swapchain (68)
Log     - Ext 1: VK_KHR_sampler_mirror_clamp_to_edge (1)
Log     - Ext 2: VK_KHR_maintenance1 (1)
Log     - Ext 3: VK_KHR_shader_draw_parameters (1)
../../../../src/compiler/spirv/spirv_to_nir.c:2707 WARNING: Unsupported SPIR-V capability: ImageMSArray
../../../../src/compiler/spirv/spirv_to_nir.c:2707 WARNING: Unsupported SPIR-V capability: ImageMSArray
../../../../src/compiler/spirv/spirv_to_nir.c:2707 WARNING: Unsupported SPIR-V capability: ImageMSArray
../../../../src/compiler/spirv/spirv_to_nir.c:2707 WARNING: Unsupported SPIR-V capability: ImageMSArray
../../../../src/compiler/spirv/spirv_to_nir.c:2707 WARNING: Unsupported SPIR-V capability: ImageMSArray
../../../../src/compiler/spirv/spirv_to_nir.c:2707 WARNING: Unsupported SPIR-V capability: ImageMSArray
Warning - On replay, semaphore got a duplicate handle - maybe a bug, or it could be an indication of an implementation that doesn't use semaphores
Violación de segmento (`core' generado)

**Comment by baldurk** [comment]
It seems like some incompatibility with the intel mesa vulkan driver, whether it's my side or theirs is difficult to tell. I'll try to replicate this next week to see what is going on exactly, and whether those SPIR-V errors are important or unrelated.

**Comment by baldurk** [comment]
I've been looking at GL and Vulkan on mesa, and I was able to capture vulkan programs OK. I didn't try the SDK cube example but I did try some of Sascha Willems' demos.

I think this issue has been fixed by another change since the bug was opened, can you test again on a recent build?

**Comment by baldurk** [comment]
Closing this since from my testing vulkan is working on v0.34 (GL is not, but that appears to be a mesa-side issue - #515 ).

**Comment by oscarbg** [comment]
Yes it works!
