### ISSUE TITLE
Captured shader missing constant buffer info

### ISSUE THREAD

**Issue by hustruan** [baldurk/renderdoc#538]
![image](https://cloud.githubusercontent.com/assets/1239333/23830301/9e09c8e4-0742-11e7-8bb4-a984501b7c8a.png)

And the dxbc shader I saved is also missing constant buffer info

**Comment by baldurk** [comment]
Can you give more details? The screenshot you showed only shows the disassembly which lists a couple of constant buffers - what information is missing exactly?

**Comment by hustruan** [comment]
I capture a frame of a game, and save one shader bytecode, found that there is no constant buffer informations in dxbc.  I debug it,  in the constructor of the class DXBCFile, the code never reach the cbuffer path.

![image](https://cloud.githubusercontent.com/assets/1239333/23830950/8fbbf2ee-0751-11e7-9094-a470a6ddd75d.png)

**Comment by baldurk** [comment]
Do you mean the reflection information? That's is normally stripped out as it's usually only used for debugging, not for normal running. It's not a RenderDoc bug.

**Comment by hustruan** [comment]
Ok, it's the reflection information. you mean the reflection info is stripped out when the game is released.
I understand. Thank you!
