### ISSUE TITLE
Support for new Nvidia Perfworks GPU counters (similar to PIX)?

### ISSUE THREAD

**Issue by oscarbg** [baldurk/renderdoc#550]
Hi,
know Renderdoc recently gained support for GPU metrics..
today new PIX was released (https://blogs.msdn.microsoft.com/pix/2017/03/20/pix-1703-20-002/):
with "~300 newly available counters" & "partnered with NVIDIA to enable a rich set of hardware performance counters inside PIX"..
they seem to use new Perfworks SDK (seems avaiable under request):
https://developer.nvidia.com/perfworks
as this seems better for NV GPUs than existing support would like to know if interested on supporting it or not?
thanks..

**Comment by baldurk** [comment]
The SDK is not public and given NVIDIA's history, it's unclear if it will ever be public. Unless that happens it won't be something I will integrate into renderdoc.

The general question of profiling has been addressed in other issues like #450 and the situation is still the same - profiling is certainly something I'd like to support in future as time and resources permit, but right now it's not a priority. RenderDoc is a debugger not a profiler and there's still a lot of work to do on that front. Being a good profiler isn't just a matter of throwing in some counters, it needs careful thought and time.

**Comment by vinjn** [comment]
`perfworks` was never released to public, and `perfworks` is also deprecated now.
