### ISSUE TITLE
qrenderdoc unnecessarily requires multi-sampled image-load-store

### ISSUE THREAD

**Issue by janesma** [baldurk/renderdoc#552]
To Reproduce:

With debug build of mesa i965 vulkan driver, launch simple spinning cube app (cube from https://github.com/LunarG/VulkanTools/tree/master/demos) from qrenderdoc.
Trigger a capture.
qrenderdoc triggers an assert in mesa: Assertion `!(vk_info->usage & VK_IMAGE_USAGE_STORAGE_BIT)' failed.

Backtrace:
http://sprunge.us/JjIa

**Comment by baldurk** [comment]
It's hard for me to verify for sure since the systems I have easy access to support MSAA storage, but I think that commit should skip the extra storage MSAA texture that's only used for dummy purposes.

**Comment by baldurk** [comment]
v0.34 includes the above fix which should cover the cases concerned, so I'm closing this issue. Note that MSAA storage support will still be required if the target application uses MSAA textures.
