### ISSUE TITLE
pythonlibs.zip not found error, with pythonlibs.zip present

### ISSUE THREAD

**Issue by adjelouah** [baldurk/renderdoc#563]
I am trying to use the python shell in renderdoc but whenever I try to access any of renderdoc member I get the error message that the attribute of 'namespace#' object is read-only
for example: 
> attribute 'CurTextures' of 'namespace#' object is read-only

This is the case both in interactive and script mode. In script mode I have the following comment:
```
# !!! pythonlibs.zip not found! Check installation !!!
# !!! If building locally, ensure you have compiled python libraries: !!!
# !!! Download IronPython-2.7.4 package, run this command and rebuild renderdocui !!!
# cd renderdocui/3rdparty/ironpython/ && ./compilelibs.sh /path/to/IronPython-2.7.4
```
but the file pythonlibs.zip is present as well as all IronPython dll's

Regarding my configuration:
 - I have installed the latest version of renderdoc (v0.33) using the provided installer ( but I have the same problem with previous versions v0.32 for example)
 - OS is Windows 10

Any idea on what could be the problem?

Many thanks!

**Comment by baldurk** [comment]
The `pythonlibs.zip` error was unfortunately a false positive that showed up in 0.33. I [fixed it recently](https://github.com/baldurk/renderdoc/commit/bda6cf08701c48f8bf026a742bb4e15eec731e0b) but if you installed via the normal installer then you don't have to worry, it's configured correctly.

It sounds like you're trying to access `CurTextures` in the wrong object - `renderdoc` is a namespace defining types and structures, not an object with member attributes. The `pyrenderdoc` object corresponds to the `Core` object in C# and it contains attributes, so try accessing `pyrenderdoc.CurTextures`.

This is a change that happened between v0.30 and v0.31 last year. Before then the `Core` object was called `renderdoc`, but this meant that there was no way to access the namespace and its types.

**Comment by adjelouah** [comment]
Indeed everything works fine with the `pyrenderdoc` object. Same thing in script mode despite the error message.

Thanks for the quick answer! I am closing the issue.
