### ISSUE TITLE
d3d11_1 UAV in vertex shader not shown (both VS nor OM resources)

### ISSUE THREAD

**Issue by pixeljetstream** [baldurk/renderdoc#564]
Using version 0.33, a vertex shader that is using a UAV resource, disassembly shows "dcl_uav_typed_buffer (uint,uint,uint,uint) u0", does not list that as resource.
As consequence when the VS is used in a drawcall the bound UAV is listed under "Disabled Items" which is a bug as well.

**Comment by baldurk** [comment]
If I understand right, these are the same bug - the UAV was being listed under the OM stage, but I was only looking at the PS to see if it was used, so it got marked as unused/disabled.

With that change the OM UAVs should be listed as active if any stage uses them. If multiple stages use the same UAV then the latest shader 'wins' to describe the type/format, but I think in most cases if there are multiple stages using the same UAV they'll probably use the same definition.

It will be in the next nightly build, or you can compile locally. If there's something else to fix after the above commit then let me know and I'll look into it further.

**Comment by baldurk** [comment]
Closing this issue, as the fix for the bug is included in v0.34.
