### ISSUE TITLE
No mesh visible when rendering with a sparse indexbuffer

### ISSUE THREAD

**Issue by stelar7** [baldurk/renderdoc#580]
When rendering with a sparse indexbuffer, i end up with a different result IRL and in RenderDoc.

This is on the latest nightly commit 386c830b1de80d11572eb71505a76693b3cfb616

See here: https://puu.sh/vlhse/021f033f55.png
this here: https://puu.sh/vlhyM/744af21537.png
and here: https://puu.sh/vlhtK/f7207c47df.png

Sample application here: https://www.dropbox.com/s/ppuz7o6k51noeyz/engine-1.0-SNAPSHOT-jar-with-dependencies.jar?dl=0

**Comment by baldurk** [comment]
I think that commit should fix it, when resetting sparse bindings on buffers I wasn't aligning up from the buffer size to the aligned size requirement (in your case e.g. 12 bytes to 65536 bytes).

**Comment by stelar7** [comment]
Seems to work.
