### ISSUE TITLE
Capture Executable Tab Missing

### ISSUE THREAD

**Issue by nobledemon** [baldurk/renderdoc#599]
Once closed, how are we supposed to recover it? It seems missing from the window dropdown.

**Comment by baldurk** [comment]
It's opened via "File -> Capture..." or "File -> Inject...", but that's a fair point - it should be under the Window menu for consistency/discoverability.

**Comment by nobledemon** [comment]
It seems I pulled the trigger too fast, though we have had this issue several times, sometimes we closed the tab and we had no idea how to reopen it.  I should have looked more since other people had this issue too.

Aside the unexpected place, perhaps it could help if "Capture Executable" was labeled as "Capture Log" or "viceversa"

Thanks for the fast response, great application.
