### ISSUE TITLE
python shell not working

### ISSUE THREAD

**Issue by jackyko1991** [baldurk/renderdoc#611]
I want to use my own script using renderdoc python shell

when starting the shell tab, follow error appears

```
!!! pythonlibs.zip not found! Check installation !!!
!!! If building locally, ensure you have compiled python libraries: !!!
!!! Download IronPython-2.7.4 package, run this command and rebuild renderdocui !!!
cd renderdocui/3rdparty/ironpython/ && ./compilelibs.sh /path/to/IronPython-2.7.4
```

I am using windows 10 and build directly using the solution file. I cannot use the renderdoc class. Example is as following:

```
renderdoc.FrameInfo
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: attribute 'FrameInfo' of 'namespace#' object is read-only
```

any idea how to fix this?

**Comment by baldurk** [comment]
If you're building from source then that error message gives the command you need to run to build the python libraries - if you run that script and point it to a downloaded copy of IronPython-2.7.4 then it will package the libraries. Or you could copy the pythonlibs.zip from a nightly/stable build into the folder where your renderdocui.exe is.

The error you are encountering is expected -` renderdoc` is not an object, it's the namespace where the renderdoc types are available. The `pyrenderdoc` object is the access into the Core object. This is explained in the comment just above the pythonlibs message that you pasted:

> RenderDoc Python console, powered by IronPython 2.7.4.1000
> The 'pyrenderdoc' object is the Core class instance.
> The 'renderdoc' module is available, as the matching namespace in C#.

**Comment by jackyko1991** [comment]
I have fixed the pythonlibs.zip error. However whenever I call renderdoc.FrameInfo, same error still occur

**Comment by baldurk** [comment]
I'm not sure I understand what's still the problem. As I explained in the comment above, `renderdoc` is not an object, it's a namespace with types available. The error message indicates that there's no `FrameInfo` member - `pyrenderdoc` is an object and has a `FrameInfo` member among other things.

This is explained in the comment at the start of the script editor, as well as at the top of the shell:

> **The 'pyrenderdoc' object is the Core class instance.**
> **The 'renderdoc' module is available, as the matching namespace in C#.**

**Comment by zao** [comment]
@jackyko1991 If I may guess, are you trying to use the instructions from the Playing For Data project? That uses a very ancient fork of RenderDoc and if you intend to use it with current builds of actual RenderDoc, you probably have to adapt their/your source code to the current state of things.

@baldurk With some sleuthing I found Python API use like [this one in 2016-playing-for-data](https://bitbucket.org/visinf/projects-2016-playing-for-data/src/8b11a42db50184a773951af15e6b28e5c0602d9f/scripts/extract_from_game.py?at=master&fileviewer=file-view-default), thus the question to the OP above.

**Comment by baldurk** [comment]
Yeh I'm aware of playing-for-data but I didn't want to assume what @jackyko1991 was doing.

As you say though, anyone using that repo should use the renderdoc fork there where the scripts are compatible, and report any bugs there too, or rebase their changes onto latest HEAD.

**Comment by baldurk** [comment]
I'm going to close this seeing as it's not a renderdoc bug and the mistaken use has hopefully been clarified.

**Comment by JialeTao** [comment]
> I'm going to close this seeing as it's not a renderdoc bug and the mistaken use has hopefully been clarified.

Hello,I fixed it by replacing renderdoc with pyrenderdoc,and I'am also run the python script of the project playing-for-data,but it still errors like    TypeError: len() of unsized object      when using len(frameInfo)

**Comment by JialeTao** [comment]
> I'm going to close this seeing as it's not a renderdoc bug and the mistaken use has hopefully been clarified.

Can you help me with it?

**Comment by baldurk** [comment]
No support is provided for the playing-for-data fork, it is controlled by a third party and is many many years out of date. Please don't open issues about it or comment on old issues.
