### ISSUE TITLE
I can't see overlay when the renderdoc triggers the GTA5, and the renderdoc can't capture frames from the game. Any ideas?

### ISSUE THREAD

**Issue by tyzaizl** [baldurk/renderdoc#612]
RENDERDOC:  [20:48:12]    win32_process.cpp( 307) - Log     - Injecting renderdoc into process 7432
RENDERDOC:  [20:48:13]    win32_process.cpp( 180) - Debug   - Injecting call to RENDERDOC_SetLogFile
RENDERDOC:  [20:48:13]    win32_process.cpp( 180) - Debug   - Injecting call to RENDERDOC_SetCaptureOptions
RENDERDOC:  [20:48:13]    win32_process.cpp( 180) - Debug   - Injecting call to RENDERDOC_GetRemoteAccessIdent
'renderdocui.exe' (Win32): Loaded 'C:\Windows\System32\mswsock.dll'. Cannot find or open the PDB file.
'renderdocui.exe' (Win32): Loaded 'C:\Windows\System32\dnsapi.dll'. Cannot find or open the PDB file.
'renderdocui.exe' (Win32): Loaded 'C:\Windows\System32\FWPUCLNT.DLL'. Cannot find or open the PDB file.
'renderdocui.exe' (Win32): Loaded 'C:\Windows\System32\rasadhlp.dll'. Cannot find or open the PDB file.
The thread 0x3994 has exited with code 0 (0x0).
RENDERDOC:  [20:48:24]    win32_network.cpp( 323) - Debug   - connect before timeout
The thread 0x3b90 has exited with code 0 (0x0).
RENDERDOC:  [20:48:27]    remote_access.cpp( 389) - Log     - Got remote handshake: GTAVLauncher () [7432]
The thread 0x3388 has exited with code 0 (0x0).

**Comment by baldurk** [comment]
The log output format you've pasted shows that you're running an older version - at least 0.31 or maybe before. Can you try running the latest version to see if it's working there?

**Comment by tyzaizl** [comment]
I tried 0.33(a binary version), but it still does not work. There is no response when F12 pressed.

**Comment by baldurk** [comment]
How are you injecting renderdoc into the program? Are you using the global hook or launching the exe directly?

**Comment by tyzaizl** [comment]
I  pushed the capture button with global hook disabled to launch the GTA-V, and launched the GTA-5 directly with global hook enabled. Both were not working.

**Comment by baldurk** [comment]
I'm not sure what's wrong then, I just tried it and the global hook works for me. As mentioned [in the documentation](https://renderdoc.org/docs/window/capture_log_attach.html#global-process-hook) you will need to make sure you have 'secure boot' disabled in windows to allow it to run.

For various reasons I do not provide help or support with capturing third party programs. It can work but possibly your version has different copy protection to mine, or other DRM which might affect it.
