### ISSUE TITLE
OpenGL render states show as opposite of what they are

### ISSUE THREAD

**Issue by BartSiwek** [baldurk/renderdoc#617]
Noticed while using RenderDoc to debug an OpenGL 4.1 application.
The "Multisample", "Sample Shading", "Alpha to Coverage", "Alpha to One" are incorrectly reported.

I believe the following code in "renderdoc/renderdocui/Windows/PipelineState/GLPipelineStateViewer.cs", lines 1358-1362" is responsible. Notice setting the image to cross when the value is true, and to tick when it's false:
`multisampleEnable.Image = state.m_RS.m_State.MultisampleEnable ? cross : tick;`
`sampleShading.Image = state.m_RS.m_State.SampleShading ? cross : tick;`
`minSampleShadingRate.Text = Formatter.Format(state.m_RS.m_State.MinSampleShadingRate);`
`alphaToCoverage.Image = state.m_RS.m_State.SampleAlphaToCoverage ? cross : tick;`
`alphaToOne.Image = state.m_RS.m_State.SampleAlphaToOne ? cross : tick;`

**Comment by BartSiwek** [comment]
Also Scissor test state is not updated correctly. The variable `anyScissorEnable` is set to false, never updated and then used to display scissor state:
`scissorEnable.Image = anyScissorEnable  ? tick : cross;`

**Comment by baldurk** [comment]
Good catch! It looks like maybe just a copy-paste error or something. I believe the above commit should fix it.

**Comment by baldurk** [comment]
I snuck this in just before v0.34 so I'm going to close it down as it's fairly evident that it's fixed. If I missed a case or didn't fix it correctly, do let me know. Thanks again for catching this :smile: .
