### ISSUE TITLE
Constant Buffer Viewer not displaying Float Arrays properly

### ISSUE THREAD

**Issue by reltham** [baldurk/renderdoc#618]
Float Arrays are not packed in the actual CB, but the view panel is reading them as if they are packed. See the red box in the image.  When actually debugging the shader the Constants & Resources panel is displaying the correct values. See the green box in the image.

![renderdoc_bug](https://cloud.githubusercontent.com/assets/3689101/26181100/58ebfec6-3b22-11e7-9490-ae792884f558.jpg)

I am using Version v0.33 and my application is using DX11 API.  The shader is compiled as SM4.  The shader is working correctly, it's just the constant buffer viewer panel that is wrong (I assume it's also wrong for other Arrays that have padding in the actual CB).

**Comment by baldurk** [comment]
Thanks for the report! It looks like when extracting data in a structured manner (ie. not splitting everything into float4 registers explicitly) I was missing code to align each element in an array up to a float4 boundary.

I think that commit should fix it, let me know if you have any other issues.

**Comment by reltham** [comment]
I grabbed the nightly build (5/18 x64 Windows), and this is now working correctly.

Thanks!
