### ISSUE TITLE
Multiple StartFrameCapture/EndFrameCapture within the same frame overwrites temp .rdc 

### ISSUE THREAD

**Issue by remage** [baldurk/renderdoc#645]
When trying to capture multiple small parts of a frame into separate .rdc files (e.g. when generating lightprobes), RenderDoc::OpenWriteSerialiser() may generate the same temp filename for multiple captures (because the timestamp and frameNum stays the same).

**Comment by remage** [comment]
Workaround:
```
  static uint32_t s_CaptureNum = 0;
  m_CurrentLogFile = StringFormat::Fmt("%s_%u_frame%u.rdc", m_LogFile.c_str(), s_CaptureNum++, frameNum);
```

**Comment by baldurk** [comment]
This is an interesting problem :smile:. I don't want to add the capture sequence number into the default filename format really, but you're right that this case starts to alias filenames.

I think what I'll do is get `OpenWriteSerialiser` to check the list of captures in `m_Captures`, which include the previous captures generated. If it sees that it's about to overwrite a previous file, then it will takes steps to disambiguate as necessary (like `frame12345_2.rdc`, `frame12345_3.rdc`, etc).

**Comment by baldurk** [comment]
OK I implemented the check I described above, and did a quick test to make sure that multiple captures in the same frame don't trample each other anymore. Are you able to test that it works for your scenario and there's no edge-case I didn't handle?

**Comment by remage** [comment]
Sure, I can check tomorrow morning.

**Comment by remage** [comment]
There's a missing `altnum++`, causing an infinite while loop.
Fixing that, it works fine.

**Comment by baldurk** [comment]
Duh! That shows me for only testing with one duplicate frame capture :disappointed:.

Thanks for catching that! I'll fix it, but otherwise close this issue.
