### ISSUE TITLE
Copy/Paste broken on Linux

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#646]
In the C# version, selecting multiple rows of the UBO viewer and then doing Ctrl+C would copy all the selected rows (all columns). This was very handy.

In the Qt version (at least on Linux), doing Ctrl+C only copies the contents of the __last active cell_, regardless of how much is selected.

Additionally, clicking on the save button doesn't seem to be doing anything.
![savebutton](https://user-images.githubusercontent.com/3395130/27015232-a40f383e-4edf-11e7-8237-7b236d33f357.png)

**Comment by baldurk** [comment]
Are you running v0.34 or latest code? I only added copy-paste handling for the tree widgets [relatively recently](https://github.com/baldurk/renderdoc/commit/c95f7c4cead04074a466dbd830f39c02a3f1137b).

The save button though indeed seems like it's not hooked up, I can fix that easily enough.

**Comment by darksylinc** [comment]
On Linux I'm building from repo, but last time I pulled was on May 19th. I should try again then.

**Comment by darksylinc** [comment]
OK I just pulled latest and rebuilt, I can confirm your change works.

The only thing not working is the save button (TBH I rarely use it, I only noticed because I tried everything to try to get the data out of RenderDoc)

**Comment by baldurk** [comment]
I think that commit should sort the CSV export too now.

**Comment by baldurk** [comment]
Closing this as the clipboard functionality was implemented for the v0.90 release.
