### ISSUE TITLE
Crash in WrappedIDXGISwapChain4::GetFullscreenState

### ISSUE THREAD

**Issue by Pombal** [baldurk/renderdoc#652]
Hello!

I got a read access violation when ppTarget of GetFullscreenState is null. 
The function goes on to check if the call on the real device succeeded and then tries to dereference the null pointer.

**Comment by baldurk** [comment]
Oh right, that's my mistake. I didn't realise that the ppTarget was allowed to be NULL, I thought it would error inside the real device function if that was true.

**Comment by Pombal** [comment]
No worries, happy to help :)

**Comment by baldurk** [comment]
I believe that commit should fix it - can you make sure it's working for you with that? It'll be in the next nightly build if you're not compiling locally.

**Comment by Pombal** [comment]
Yep, it's working. Thanks!
