### ISSUE TITLE
Broken textures on linux

### ISSUE THREAD

**Issue by reduz** [baldurk/renderdoc#654]
Vendor: X.Org (0x1002)
    Device: AMD TONGA (DRM 3.1.0 / 4.4.0-78-generic, LLVM 3.8.0) (0x6939)
 Vendor: X.Org (0x1002)
    Device: AMD TONGA (DRM 3.1.0 / 4.4.0-78-generic, LLVM 3.8.0) (0x6939)

textures cant be visualized after frame capture under Ubuntu Linux/X11, all looks broken:

![image](https://user-images.githubusercontent.com/6265307/27114361-7e4eb21c-5099-11e7-9ae9-df5044c6e065.png)

**Comment by baldurk** [comment]
I'm not sure I can do much to directly debug this without being able to repro it. It works fine on my AMD ubuntu install, so something must be different between our setups whether software or hardware.

One thing that's quite suspicious is the titlebar indicates degraded performance - on GL that means it's missing some core extensions, but with a tonga card that shouldn't be the case - I'm on hawaii and it's fine (GCN2 vs your GCN3). Can you paste into a gist or pastebin with the full diagnostic log?

Also can you compile renderdoc locally? There's one or maybe two things I'd like you to try and change in the code to see if it helps.

**Comment by baldurk** [comment]
I'm closing this as without more information I can't solve it. If you can provide a repro or more specific information about your setup and GL configuration then add a comment here and I can re-open to investigate.
