### ISSUE TITLE
Error   - Can't capture x64 process with x86 renderdoc

### ISSUE THREAD

**Issue by vinjn** [baldurk/renderdoc#66]
This error happens when I am injecting `d:\Program Files\Microsoft DirectX SDK (June 2010)\Samples\C++\Direct3D11\Bin\x86\BasicHLSL11.exe`
It's a x86 application running on x86 cpu, renderdoc is also x86 version.

**Comment by hgm4** [comment]
This still happens on a 64-bit machine trying to inject into a 32-bit process.

**Comment by baldurk** [comment]
Are you able to build RenderDoc to step through the code and see what happens? In general this does work (32-bit processes are still fairly common and I capture them myself pretty often), so I'd like to know what is happening [in this code](https://github.com/baldurk/renderdoc/blob/master/renderdoc/os/win32/win32_process.cpp#L322-L343):

```cpp
#if !defined(WIN64)
	BOOL selfWow64 = FALSE;

	HANDLE hSelfProcess = GetCurrentProcess();

	success = IsWow64Process(hSelfProcess, &selfWow64);

	CloseHandle(hSelfProcess);

	if(!success)
	{
		RDCERR("Couldn't determine bitness of self");
		return 0;
	}

	if(selfWow64 && !isWow64)
	{
		RDCERR("Can't capture x64 process with x86 renderdoc");
		CloseHandle(hProcess);
		return 0;
	}
#else
```

**Comment by hgm4** [comment]
I see what happened. The OpenProcess call above fails because the process I was trying to attach to was running with admin privileges. Works fine when renderdoc is running with admin privileges (or vice versa of course).

Sorry for the false alarm.

--
George

**Comment by baldurk** [comment]
Ah good to hear. I will see if I can add some detection of that error case and give a more useful message :).
