### ISSUE TITLE
Feature request: Double-click in pixel history navigates to relevant event in event browser

### ISSUE THREAD

**Issue by jshofmann** [baldurk/renderdoc#661]
A nice convenience would be if you double-click on an event in the pixel history it displayed and selected that event in the Event Browser, opening the parent nodes if necessary. Thanks for all your work on this wonderful tool!

**Comment by baldurk** [comment]
What version are you running? For me on both the C# and Qt UI double clicking the pixel history events does exactly that. That's the intention, the help text even says so:

![image](https://user-images.githubusercontent.com/661798/27246282-729fb226-52e8-11e7-8cf9-06eca162916e.png)

**Comment by jshofmann** [comment]
I'm running 0.34, and it's weird - using a capture I took yesterday, it works as advertised, but in an earlier capture (long since deleted) double-clicking was doing nothing, prompting this request. Apparently I hit some sort of UI bug I can no longer reproduce? If I see it again I'll send the capture your way, otherwise this is a non-issue.
