### ISSUE TITLE
D3D11 Incorrect BlendState being reported

### ISSUE THREAD

**Issue by TarpHerder** [baldurk/renderdoc#665]
On RenderDoc 0.34 when looking at a D3D11 capture the blendstate is incorrectly shown as (Colour Source: DstAlpha, Colour Dest: InvDstAlpha) while the blend that is actually being performed is (Source Blend: D3D11_BLEND_SRC_ALPHA(5), Dest Blend: D3D11_BLEND_INV_SRC_ALPHA(6)). The resulting image shows the correctly blend image (partially blended according to src alpha, dst alpha is 1 which would result in opaque rendering). Not all blend args are reported incorrectly; One and Zero show up correctly for example.

As the actual blend being performed (and shown in RenderDoc) does not match the blend state description (as shown in RenderDoc) I expect this to be a bug in RenderDoc. I have verified that I am passing correct values to D3D and the debug layer does not report any issue while rendering or creating the BlendState object.

**Comment by baldurk** [comment]
Ah sorry about that. Someone else noticed this over the weekend but I forgot to commit the fix. It's down to the enums internally needing to be specified in two places - once for the C++ code and once for the C# code, and I'd only updated the enum in one place with some new entries, which through it off in C# land.

That commit should fix it I think, it'll be in the next nightly build if you don't compile from source yourself.

**Comment by TarpHerder** [comment]
No problem, I'll grab the next nightly and verify the fix (probably tomorrow or the day after). RenderDoc is great by the way! Still better than PIX! :P

**Comment by TarpHerder** [comment]
Verified that the behavior is now correct on the latest nightly build (x86 version tested).
