### ISSUE TITLE
how to trace game on steam

### ISSUE THREAD

**Issue by xiaofeng94** [baldurk/renderdoc#666]
I notice that a paper, _Playing for Data: Ground Truth from Computer Games_, makes use of renderdoc to capture data from commercial games. And I'd like to have a try.  But I find I cannot trace game downloaded at steam because games on steam should be launched by steam. 
Since steam is a large platform for games, support for tracing game on it will be a very nice feature.

Renderdoc used by me was built from Tag v0.34. It seems to be v0.35 on the title of main Window.
The game I tried is Life is strange, which is free for episode 1.

**Comment by baldurk** [comment]
Sorry, for some reason I didn't get an email about this issue.

The [global hook](https://renderdoc.org/docs/window/capture_log_attach.html#global-process-hook) feature can be used to capture programs that aren't launched directly from RenderDoc, but indirectly through another launcher.

However I want to be clear that I cannot and do not support capturing 3rd party programs that you do not control. It generally works but for obvious reasons I don't provide any help with problems you encounter unless they are clearly RenderDoc issues and can be reproduced outside of this scenario. If you need any help with this beyond what I've said here I can't help you.

**Comment by xiaofeng94** [comment]
thanks a lot. I think  global hook is what I needed!
