### ISSUE TITLE
Something broke between 0.32 and 0.34

### ISSUE THREAD

**Issue by nicebyte** [baldurk/renderdoc#668]
The latest available stable version won't capture frames properly for me. The capture will appear in the UI, but when I load it, I can't see any API calls, can't see any textures, etc. All I see in event browser is "frame start" and "SwapBuffers". I have tried both 64 and 32 bit versions. I've made sure that renderdocui, renderdoccmd and my test application are set to use the nvidia gpu in the nvidia control panel tool.

The issue doesn't happen with 0.32. I haven't checked 0.33 or the nightlies.

I have a dual-gpu setup on my laptop (intel integrated graphics + geforce 970m) so that might be the culprit...

**Comment by baldurk** [comment]
You didn't mention your OS or which API you're capturing, but this sounds a lot like #650 ? Can you try a recent nightly build or the workaround mentioned there?

**Comment by nicebyte** [comment]
Sorry about that - yes, it is win 10 and I am capturing OpenGL. This does look very similar to what I'm seeing. 

I tried the workaround, but it crashed my app after caprturing the first frame.

Then I tried the nightly build, and it worked fine. Thanks for your help!
