### ISSUE TITLE
WrappedVulkan::MakeRenderPassOpString() does not consider VK_ATTACHMENT_UNUSED

### ISSUE THREAD

**Issue by Themaister** [baldurk/renderdoc#670]
Tripping an assertion on
```
          opDesc = store ? ToStr::Get(atts[col0].storeOp) : ToStr::Get(atts[col0].loadOp);
```
where col0 == ATTACHMENT_UNUSED == -1u. It is the only color attachment in the subpass.

Commit: 08cbddf06398d69f72af3629f61d95efb48ceff1

I don't trip this on v0.34 stable.

**Comment by baldurk** [comment]
Should be fixed with that commit above, thanks!

**Comment by Themaister** [comment]
Thanks!
