### ISSUE TITLE
Build failures (Werror) due to gcc fallthrough warnings.

### ISSUE THREAD

**Issue by gicmo** [baldurk/renderdoc#671]
Newer gcc (I believe >= 7) will warn on switch fall-throughs (see -Wimplicit-fallthrough=X at [gcc's warning page](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html).

```sh
src/renderdoc/renderdoc/driver/shaders/spirv/spirv_disassemble.cpp: In function ‘void ParseSPIRV(uint32_t*, size_t, SPVModule&)’:
src/renderdoc/renderdoc/driver/shaders/spirv/spirv_disassemble.cpp:5567:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
         mathop = true;    // deliberate fallthrough
         ~~~~~~~^~~~~~
src/renderdoc/renderdoc/driver/shaders/spirv/spirv_disassemble.cpp:5569:7: note: here
       case spv::OpCompositeConstruct:
       ^~~~
```
Lots in `src/renderdoc/renderdoc/driver/gl/wrappers/gl_debug_funcs.cpp`. More in ` src/renderdoc/renderdoc/3rdparty/jpeg-compressor/jpgd.cpp` and a few other places.

I have a patch that added comments to shut gcc up for all of them. I will post it shorty. You want microcommits for each file so you can pick and choose?

**Comment by baldurk** [comment]
I'll need to see that patch to figure out whether this is a warning we'd want to keep or silence, I'm on the fence about it. It looks like a couple of places in gl_debug_funcs.cpp don't technically have a comment although it's very clear from the code that the fallthrough is deliberate.

I don't want to modify any 3rdparty libraries though for something like this since it gets painful to have deltas to upstream if I ever need to update, so this will need to be added to the list of warnings that are suppressed for that code.

**Comment by gicmo** [comment]
Patch as [gist](https://gist.github.com/gicmo/06424509ff86343ccd56e407978f911e). It is broken up and maybe some whatspace/punctuation changes (some leftovers from me experimenting what would make gcc happy).

For quick reference, from the gcc manual:
- -Wimplicit-fallthrough=0 disables the warning altogether.
-    -Wimplicit-fallthrough=1 matches `.*` regular expression, any comment is used as fallthrough comment.
-    -Wimplicit-fallthrough=2 case insensitively matches `.*falls?[ \t-]*thr(ough|u).*` regular expression.
-    -Wimplicit-fallthrough=3 case sensitively matches one of the following regular expressions:
```
        -fallthrough
        @fallthrough@
        lint -fallthrough[ \t]*
        [ \t.!]*(ELSE,? |INTENTIONAL(LY)? )?
        FALL(S | |-)?THR(OUGH|U)[ \t.!]*(-[^\n\r]*)?
        [ \t.!]*(Else,? |Intentional(ly)? )?
        Fall((s | |-)[Tt]|t)hr(ough|u)[ \t.!]*(-[^\n\r]*)?
        [ \t.!]*([Ee]lse,? |[Ii]ntentional(ly)? )?
        fall(s | |-)?thr(ough|u)[ \t.!]*(-[^\n\r]*)? 
```
-    -Wimplicit-fallthrough=4 case sensitively matches one of the following regular expressions:
```
        -fallthrough
        @fallthrough@
        lint -fallthrough[ \t]*
        [ \t]*FALLTHR(OUGH|U)[ \t]* 
```
-    -Wimplicit-fallthrough=5 doesn’t recognize any comments as fallthrough comments, only attributes disable the warning.

**Comment by baldurk** [comment]
OK that's not too bad. Like I say I'd have to revert those couple of changes to 3rdparty code and mute the warning with compile flags there.

I'd probably want to change the warning level to 2 though since it would be annoying to have the compiler be particularly picky about the exact phrasing of a comment that's clear enough if it says "fall through" in any manner.

The other problem is that this warning isn't going to be checked in CI right now. I might try to set up a gcc7 build to catch the warning.

**Comment by gicmo** [comment]
Let me split the patch into multiple so you can easily rebase interactively and pick and choose; unless of course you prefer to just do it yourself. In that case you can just take the template and do whatever you want with the patch and just pick the bits you want. :)

**Comment by baldurk** [comment]
It's fine I'll just apply the patch then rebase/revert the bits I don't want and add any CMake changes :).

**Comment by gicmo** [comment]
Apropos CMake. I packaged RenderDoc for Fedora (25, 26, rawhide) in my [copr](https://copr.fedorainfracloud.org/coprs/gicmo/devel/package/renderdoc/). I had to patch cmake bcause it is `qmake-qt5` not `qmake` on Fedora. Maybe that could be a proper CMake option?

**Comment by baldurk** [comment]
Yeh I can add an option for that.

**Comment by baldurk** [comment]
All right, should be the option you requested and a clean build against GCC7 from your commit at 31f67f4c192d8b3939c170e89adbb727e3321c99 and some warning setting changes at 094b9ebf35ad1124129c893b72b1f09ff039e97f. Unfortunately qmake doesn't support warning settings per file so I had to mute the warning across the whole qrenderdoc project.

**Comment by galpeter** [comment]
@baldurk I've did a clean build and now there are now such warnings (errors) for me.

**Comment by baldurk** [comment]
@galpeter where do you get a warning? and with which compiler version? I just built latest code with gcc-7.0.1 and I don't get any warnings.

**Comment by galpeter** [comment]
@baldurk Ahh... sorry I meant there are no such warnings. (GCC 7.1.1)

**Comment by baldurk** [comment]
Ah ok, good to hear :smile:. I'll wait for @gicmo to verify on their distro too, as well as the qmake option.

**Comment by gicmo** [comment]
Can confirm that a) the qmake options works fine, and b) builds warning free on F26 beta (with gcc 7.1.1). Thanks a lot!
