### ISSUE TITLE
Save capture dialog sometimes opens the capture

### ISSUE THREAD

**Issue by Arkane-Chris** [baldurk/renderdoc#674]
I tend to make a bunch of captures in a single run, save them and then view them side-by-side. At some point recently (or always?), RenderDoc started opening the capture after I saved it, but not _every_ time. This is a minor annoyance when I really only want to save them and not necessarily view them.

I think it's related to hitting Enter in the save dialog vs clicking the Save button. It looks like hitting Enter auto-opens the capture while Save doesn't.

**Comment by baldurk** [comment]
Yeh I think I'd noticed this before, the enter from the save dialog gets processed after it has closed by the capture window.

I'll double check my handlers, it's maybe checking key up instead of key pressed or something like that.

**Comment by baldurk** [comment]
That was exactly what it was :smile:. Should be fixed with that commit, in the next nightly build.

**Comment by baldurk** [comment]
Closing this down now as the fix should be in the v0.90 release.
