### ISSUE TITLE
Compiling renderdoc C1083/LNK1181

### ISSUE THREAD

**Issue by danielnjoo** [baldurk/renderdoc#675]
Hi!

Very new here, so this might be a super simple fix that is totally on my end, but any and all help would be appreciated.

I'm trying to compile renderdoc by following the instructions [here](https://bitbucket.org/visinf/projects-2016-playing-for-data), but compiling renderdoc is giving me the following errors:

![image](https://user-images.githubusercontent.com/16789604/27504289-bab249a4-583b-11e7-848b-a4d1b19c5fac.png)

(I also initially had a ton of C2220 errors which I got rid of by turning off the warning levels in all the projects)

And WRT to the first error, my project include directories looks like this:

![image](https://user-images.githubusercontent.com/16789604/27504300-e9d1d7f4-583b-11e7-871b-865a7cb71eb4.png)

wherein 'ImathInt64.h" is definitely contained, although I don't actually have a 'renderdoc.lib' at all?

Finally, trying to look ahead a little, [one other person](https://github.com/baldurk/renderdoc/issues/465) (that I know of so far) has made this work and ran into problems capturing images from a 64bit game on a 32bit version of renderdoc... should I just compile the 64bit version now? -- [I have tried asking said person for help but she says shes no longer working on it/available to help]

Any tips appreciated!! Many thanks=)

**Comment by baldurk** [comment]
You're not compiling this repository, you are compiling a [different repository](https://bitbucket.org/visinf/projects-2016-playing-for-data-renderdoc) which is a fork from years ago. It expressly has a disclaimer telling you **not** to file bugs here:

> ## Disclaimer (Before you begin capturing)
> This is our modification of an now outdated version of renderdoc. renderdoc evolves, but we do not integrate these changes into our version.
> * We added functions that are not available in plain renderdoc. Running our scripts against a version from the regular renderdoc repository will not work.
> * Bugs you find in our version should not be reported to the official renderdoc repository as they may have been fixed already. (except they also occur in the regular renderdoc version independent of using our code).
> * Do not ask for help in capturing commercial games on the renderdoc forums.
> * If you need features from more recent renderdoc releases, you will need to modify renderdoc on your own.

I also mentioned this in the bug you linked to.

**Comment by TURuibo** [comment]
I fixed the problem after I added the path of the include file to the property of the project in VS.
