### ISSUE TITLE
mscorlib recursive resoure lookup bug

### ISSUE THREAD

**Issue by xiaofeng94** [baldurk/renderdoc#676]
I use global hook to attach game to  renderdoc and encounter a problem shown in the picture. 

![renderodc](https://user-images.githubusercontent.com/9328733/27524255-f8739f28-5a65-11e7-88d9-26a0de2c8776.PNG)

I can run the game without renderdoc successfully.
the renderdoc is built from tag v0.34.
Is that a bug for renderdoc or just a problem on my game resources?

**Comment by baldurk** [comment]
As far as I can see this is an error from the game - even more so it looks like it's an error from a mod applied to the game. I don't know what the incompatibility with renderdoc is.

I can't help with problems injecting into 3rd party code you don't own or control. If you encounter problems with your own programs, then you can file a bug for that.

**Comment by xiaofeng94** [comment]
I see. thanks anyway!
