### ISSUE TITLE
Feature Request: Remember tree control states

### ISSUE THREAD

**Issue by jshofmann** [baldurk/renderdoc#678]
A nice UI enhancement would be if the tree views in the constant buffer / UBO displays and the API Calls display remembered which nodes were expanded and which nodes remained collapsed when navigating between events. Currently, when switching between two (or more) events, all nodes in all open cbuffer displays and the API calls display are collapsed when a new event is selected, making it more difficult to compare the data used by those events as you will need to re-open all nodes you had opened before. Thanks!

**Comment by baldurk** [comment]
That makes sense. To what extent should it maintain the setup? Would you expect it to only work for identical constant buffers, or should it try to handle constant buffers that have some similarities but aren't identical?

**Comment by jshofmann** [comment]
I'd like it best if the tree state was somehow bound to the tree control- i.e. when returning to a tree control you viewed before, regardless of the control's contents (e.g. cbuffer, API calls, event browser, etc), it retains the same expanded/collapsed state it had before. There's no need for comparing one control to another, each tree control has a state independent of any other controls. For my purposes, each tree's state does not need to be persistent if you load a previously saved log, but that might be a nice additional feature.

**Comment by baldurk** [comment]
I don't plan to persist these between opens of a capture, but the controls that make sense to save state during a capture load are now saved: API Inspector, Resource Inspector, CBuffer view

I'll try to keep an eye on this to see if the memory/processing impact is significant but from initial tests it seems reasonable.
