### ISSUE TITLE
Target Blend values displayed are not accurate

### ISSUE THREAD

**Issue by el3ment** [baldurk/renderdoc#687]
So this has been really difficult for me to track down, but I think there is something wrong with how you display Target Blends in the Output Merger. 

Here is a log that should help you debug it.  
https://drive.google.com/open?id=0B2E0bL_lIf09Um1yRFhadHVnbUk

Here are the steps to reproduce:

Open EID: 17731 (the first HUD draw command)
View the pipeline state
View the output merger in the pipeline state
Look at the `Colour Src` and `Color Dst` properties under Target Blends

You’ll see they are DstAlpha and InvDstAlpha, but these are not correct.

 If you add a breakpoint to the line that builds the data structure:
https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/d3d11/d3d11_replay.cpp#L1261

You’ll see what I mean. I came across this when I realized that Quantum Break doesn’t use DstAlpha ever, let alone during the HUD draw.

**Comment by baldurk** [comment]
Ah, I'm sorry about that causing you pain. This is a regression that was introduced in v0.34. Someone else ran into the same thing - see #665 - so it should be fixed if you open the capture in a recent nightly build. No need to recapture, it was just a mismatch of enums internally.

**Comment by el3ment** [comment]
No problem! The nightly build works. I should have searched for an existing issue before posting this one!

Thanks!
