### ISSUE TITLE
Buggy initialization in vk_initstate.cpp

### ISSUE THREAD

**Issue by bioglaze** [baldurk/renderdoc#688]
I ran static analysis and found the following strange initializations in vk_initstate.cpp:

Lines 812 and 952 (Apply_SparseInitialState):

  VkBufferCreateInfo bufInfo = {
      VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
      NULL,
      0,
      0,
      VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
  };

Note that VK_BUFFER_USAGE_TRANSFER_DST_BIT is used twice. Didn't create a pull request because I'm not 100 % sure how this should be fixed.

**Comment by baldurk** [comment]
Looks like this struct isn't used anymore, just the size component. When I added a built-in buffer for every memory allocation, this became redundant, so it can just be deleted.

**Comment by baldurk** [comment]
I just deleted those structs, so I'm going to close this. If there's anything I missed though let me know.
