### ISSUE TITLE
Sign release tags and tarballs

### ISSUE THREAD

**Issue by jljusten** [baldurk/renderdoc#690]
Would it be possible to sign release tar.gz files and provide the .asc signature files? You could still provide signature files for old tarballs, since you can add the .asc files under the github release area.

It also would be nice to sign future tags. Unfortunately this can't be done for old tags, since it must be done at tag creation tome. I think most distros use the tarball signature, so the signed tag is probably less important.

This page might be helpful:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by baldurk** [comment]
I think this should be doable. Normally I create the tags through the github web interface when I draft the release, but it's not a problem to make the tag locally.

Just to clarify, you'd ideally like the tag itself to be signed (with `git tag -s`) but the critical thing is to have the *source* tar.gz tarball at the point of each tag signed?

**Comment by jljusten** [comment]
On 2017-07-10 14:36:06, Baldur Karlsson wrote:
> Just to clarify, you'd ideally like the tag itself to be signed
> (with `git tag -s`) but the critical thing is to have the *source*
> tar.gz tarball at the point of each tag signed?

Correct. I'm not sure I'd say tarball signing is critical, but it is a
really good idea. :) I'm working on the debian packaging, and it
warned that we could verify the tarball if a signature was provided.
Debian bases the build on the tarball, so it only cares to verify that
signature.

It is possible that other packagers may prefer to git clone instead,
and in that case the signed tag would be useful. (I do not personally
know of someone that would use it.)

I think setting up GPG is the hard part, and after that is working,
`git tag -s` will 'just work'. Like you mention, you'd have to use the
git command line since the website can't sign tags.

https://help.github.com/articles/signing-tags-using-gpg/

**Comment by baldurk** [comment]
I've signed v0.33 and v0.34 tarballs using the same gpg key I used for signing the builds for the past few years. There doesn't seem much point in signing all the way back to the first releases but I can if you want. I've also made a note for future releases to sign the tag when I make it.

Can you check that the signature all verifies correctly against my public key, and close this issue when you do?

**Comment by jljusten** [comment]
I verified the v0.34 signature against the key with a fingerprint of 1B039DB9A4718A2D699DE031AC612C3120C34695.

Yeah, I agree about not bothering with the other releases.

Could you also sign https://github.com/baldurk/swig/archive/renderdoc-3.0.12.zip?

Thanks!

**Comment by baldurk** [comment]
where should the signature for that go? I'm not making releases for that swig fork.

**Comment by jljusten** [comment]
> where should the signature for that go?

I guess as an attachment to the release.
https://github.com/baldurk/swig/releases/tag/rel-3.0.12

**Comment by baldurk** [comment]
The [latest release v0.90](https://github.com/baldurk/renderdoc/releases/tag/v0.90) now has a signed tag, the .asc for the .tar.gz.

I've also switched the swig build to fetch from tag/release [`renderdoc-modified-1`](https://github.com/baldurk/swig/releases/tag/renderdoc-modified-1) on my swig fork, which is similarly signed.

Hopefully that's everything you need now.
