### ISSUE TITLE
GetSizedFormat breaks with type=GL_UNSIGNED_SHORT_5_6_5 (GLES)

### ISSUE THREAD

**Issue by michaelrgb** [baldurk/renderdoc#691]
glTexImage2D was called with: {internalformat,format}=GL_RGB, type=GL_UNSIGNED_SHORT_5_6_5
`GetSizedFormat` then converted internalformat to GL_RGB8 which was saved to the capture.

This sized type however is invalid with GL_UNSIGNED_SHORT_5_6_5, thereby breaking replay. See table 1 in https://khronos.org/registry/OpenGL-Refpages/es3/html/glTexImage2D.xhtml

Im not sure if this is correct, but seems reasonable as a fix:
```
GLenum GetSizedFormat(const GLHookSet &gl, GLenum target, GLenum internalFormat, GLenum type)
{
  switch(type)
  {
    // types can imply a sized format
    case eGL_UNSIGNED_SHORT_5_6_5: return eGL_RGB565;
    default: break;
  }
```

**Comment by baldurk** [comment]
That sounds like a reasonable approach. Like you say it's not valid to use any other internal format in that case, so a PR for that change would be fine. It would probably be a good idea while you're there to handle the other oddball formats like `GL_UNSIGNED_SHORT_4_4_4_4` to `GL_RGBA4` and `GL_UNSIGNED_SHORT_5_5_5_1` to `GL_RGB5_A1`.

**Comment by michaelrgb** [comment]
Done. Ive added cases for all the unsized internal formats from Table 1, which are those cases that you mentioned.

**Comment by baldurk** [comment]
Merged the PR so I'm closing this.
