### ISSUE TITLE
GLES extensions not equivalent to GL extensions

### ISSUE THREAD

**Issue by baldurk** [baldurk/renderdoc#701]
Attention @pantosj .

In [gl_common.h](https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/gl/gl_common.h#L361-L383) there are a few equivalencies defined so that certain GLES-specific extensions act like the GL/ARB extension is available.

I ran into a crash because the GL code was checking for `HasExt[ARB_viewport_array]` then trying to call `glGetFloati_v` to fetch the current viewport details. The device only provided `NV_viewport_array` though and so the function would only be available as `glGetFloati_vNV`. I think the same problem would happen with `OES_viewport_array` because it defines a `glGetFloati_vOES` version of the function.

What's the ideal solution here? I can see a few different possibilities but I don't know what is the correct fix.

**Comment by pantosj** [comment]
Hi @baldurk  ! First of all I apologize for the late reply. We have not encountered this problem since none of these extensions are supported on our phones. I think a possible solution would be to overwrite the affected function pointers with their `OES` or `NV` versions, for example in the `gl_emulated.cpp`, after adding them to `gl_hookset.h`. But I'm afraid that similar problems can arise with other extensions too. Previously it seemed that the non-suffixed functions always exist, but apparently this is not the case.

What are your possible solutions to this problem?

**Comment by baldurk** [comment]
My ideas may not be valid. I thought either one:

* Set up `glGetFloati_vNV` and `glGetFloati_vOES` as aliases of `glGetFloati_v`, like `glGetFloati_vEXT` is. This should still favour the non-extension version of the function, but if it's missing and one of the ext functions is present it will use it. I think this is similar to what you describe doing in `gl_emulated.cpp`. However this is only OK to do if these functions really are 100% interchangeable. This would need to also apply to the other functions.
* Remove the `EXT_COMP_CHECK(ARB_viewport_array, NV_viewport_array)` if they aren't equivalent. E.g. if those extensions don't provide the other parts of ARB_viewport_array that are used like indexed scissor.

It kind of depends on if these extensions really are exactly the same, so we can just use their functions if present, or if they're really a bit different in which case it needs special handling. It looks to me like ARB_viewport_array == NV_viewport_array just with different function suffixes, so the first option is probably OK here, but it makes me worry about the other `EXT_COMP_CHECK` checks too to know if the extension checks are really equivalent or not.

**Comment by pantosj** [comment]
In addition to PR #710 I also reviewed the `EXT_COMP_CHECK` and `HasExt[..]` checks and compared the affected extensions again. In many cases these are the same, or if there are differences, they are treated in the right place. I do not think that the compatibility problem could be solved better than currently.
