### ISSUE TITLE
Mesh Output GS/DS Output panel always empty

### ISSUE THREAD

**Issue by drone1** [baldurk/renderdoc#706]
I am building my HS and DS shaders with:

fxc /Zi /Tds5_1 /EDS DS.hlsl /Fh DS.h
fxc /Zi /Ths5_1 /EHS HS.hlsl /Fh HS.h

I see data in the VS Input and Output panels, but nothing under "GS/DS Output." I'm running v0.34 on Windows 10, with data exported from Unity v5.5.1f1.

Windows SDK v10.0A, it looks like.

Is there something else I need to do in order to utilize this panel? I have not been able to find a single thing about things / anyone else w/ this issue. 

Great app by the way -- a lifesaver really. Would love to be able to dig into my DS inputs/outputs as I'm trying to do something relatively complex.

Thank you!

**Comment by baldurk** [comment]
What API are you using? D3D11 or D3D12? They should both work but D3D12 will have been less tested.

You shouldn't have to do anything special but it's hard to tell from your description what's going wrong exactly. Can you share a capture that repros the problem?

**Comment by baldurk** [comment]
Without more information I can't investigate this bug any further, so I'm closing this issue now. If you have any more to add then please comment here.
