### ISSUE TITLE
Feature: Glsl formatting

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#709]
I have a question for a certain feature. Currently, for our glsl shaders, we've had to compress and strip out lots of text to make them compile quickly and reduce filesize (I'm looking at you OSX). Anyway... one of these optimizations was newline, tab and whitespace stripping.

The issue I'm having currently is that renderdoc displays the shader as it's fed to it, which means in a single line which becomes borderline unreadable. How feasible would it be to include a text formatter for the glsl we see in the renderdoc panel? It should do just basic things like indentation, etc. so nothing fancy, just to make the shader a bit more tractable.

**Comment by baldurk** [comment]
I'm not sure this is entirely within scope. Although it straddles a bit of a weird edge case since GL doesn't have a proper distinction between source code and object/binary code, I don't think directly having a formatter would be the right way to go. Generally to auto-format with indentation you need to have half of a parser - at least down to the statement level.

What might be more possible is doing something similar to the other APIs, where you can embed a marker in the 'object code' shader that indicates where the original source code is available, or somehow attach both versions.

The question would be if that's useful for you. I don't know how easily you can plumb that information through, or whether your glsl shaders are auto-generated and don't usefully correspond to a source shader in that way.

**Comment by redorav** [comment]
Yeah, I wouldn't be able to get these formatted shaders from anywhere as they're embedded in the data and they're autogenerated as well (when processing the assets for a build) so effectively they wouldn't be stored anywhere. The problem really is what you've said, source and binary are the same in opengl (at least from a developer's point of view) but the source itself needs a lot of massaging to ease the workload on the driver. If it's not possible or within scope I can accept that, it's a shame though as we are kind of forced to do this.

**Comment by zao** [comment]
@redorav As a personal hack, you could perhaps feed the shader text through a separate `clang-format` process to attempt to prettify it a bit, either when loading the replay or as a UI button. Something even less effort would be to have a dump functionality (if there isn't one already) and postproc it on disk.

On the shaders I've tested standalone, the code after formatting looks a bit strangely written, but seems to survive the trip. There's prior art to using it for GLSL in Atom beautify extensions.

**Comment by redorav** [comment]
@zao Thanks for the suggestions :) You mean like have a branch of renderdoc that does this formatting? I don't know enough about the code but it's a possibility. I was thinking if there wasn't something that didn't need dumping them then reloading in renderdoc.

**Comment by baldurk** [comment]
I've closed this issue with that commit - I don't think I'll add this as a first-class feature, but you can now accomplish what you're after using the new configurable shader processing tools.

With an initial shader like this:

![image](https://user-images.githubusercontent.com/661798/45221755-55e42680-b2aa-11e8-9bdc-1393f0d8be46.png)

You can configure a custom shader tool like so:

![image](https://user-images.githubusercontent.com/661798/45221770-62687f00-b2aa-11e8-9c19-78654cd0316e.png)

Then you can invoke it either as a "disassembler" on the shader view:

![image](https://user-images.githubusercontent.com/661798/45221792-79a76c80-b2aa-11e8-9ed0-d2f919f90e29.png)

Or when going to edit a shader you can select to "decompile" with clang-format for the same effect:

![image](https://user-images.githubusercontent.com/661798/45221846-a78cb100-b2aa-11e8-8a9f-92ef25c72d7e.png)

**Comment by redorav** [comment]
Hey @baldurk that is awesome! It's just what I needed. I had actually given up on this feature so it's a much appreciated surprise :+1:
