### ISSUE TITLE
SPIR-V: Renderdoc asserts on a 2d arrayed input parameter

### ISSUE THREAD

**Issue by DrChat** [baldurk/renderdoc#714]
In a geometry shader:
```
layout(location = 0) in vec4 in_interpolators[][16];
```

Asserts [here](https://github.com/baldurk/renderdoc/blob/c2b0c2d7d840c810f6400733a9e6ea68a79fd9ea/renderdoc/driver/shaders/spirv/spirv_disassemble.cpp#L3818). Just need to traverse down the baseType chain :)

**Comment by baldurk** [comment]
This shouldn't have taken so long, but is now fixed on the v1.x branch :smile:.

**Comment by baldurk** [comment]
Fix released in v1.0, closing this issue.
