### ISSUE TITLE
Handling of glxCreateContextAttribsARB doesn't work with Firefox and Mesa

### ISSUE THREAD

**Issue by jrmuizel** [baldurk/renderdoc#716]
librenderdoc.so exports glxCreateContextAttribsARB and Mesa does not.

Firefox looks up symbols using dlsym first which finds the librenderdoc glxCreateContextAttribsARB but when it tries to call glxCreateContextAttribsARB glxCreateContextAttribsARB_real is null because librenderdoc has not looked it up from Mesa using glxGetProcAddressARB

**Comment by baldurk** [comment]
I've just called straight to glXGetProcAddress to fetch the onward function pointer, which should be safe as unlike windows it doesn't need a trampoline context to fetch anything.

It's fixed on v0.x so the next v0.x nightly build should work, let me know if you have any issues - I only tested it on a small program I set up to fetch glxCreateContextAttribsARB with dlsym, not with firefox itself as I don't know how to test that way.

**Comment by baldurk** [comment]
v1.0 has now released, including this fix.
