### ISSUE TITLE
UBO: "Couldn't identify implicit object at binding"

### ISSUE THREAD

**Issue by asylum2010** [baldurk/renderdoc#724]
glBindBufferRange seems to misbehave, see screenshots.
1 - renderdoc code where it crashes
2- my code

![1](https://user-images.githubusercontent.com/937925/29519955-8f9a1a0e-867f-11e7-945d-383d9c0b82a8.png)
![2](https://user-images.githubusercontent.com/937925/29519956-8f9de008-867f-11e7-8a07-bf8a1c807bf1.png)

**Comment by baldurk** [comment]
Hey, since you have a working version of renderdoc compiled locally, can you step inside glBindBufferRange and see what's happening? This code at the start of it should set the implicit buffer record:

```cpp
void WrappedOpenGL::glBindBufferRange(GLenum target, GLuint index, GLuint buffer, GLintptr offset,
                                      GLsizeiptr size)
{
  ContextData &cd = GetCtxData();

  if(m_State >= WRITING)
  {
    size_t idx = BufferIdx(target);

    GLResourceRecord *r = NULL;

    if(buffer == 0)
      r = cd.m_BufferRecord[idx] = NULL;
    else
      r = cd.m_BufferRecord[idx] =
          GetResourceManager()->GetResourceRecord(BufferRes(GetCtx(), buffer));
```

and `cd.m_BufferRecord[idx]` is then the `GLResourceRecord *record` from your first screenshot there.

I tried setting up a simple repro example locally with code like this:

```cpp
  // create buffer up here...
  
  glBindBuffer(GL_UNIFORM_BUFFER, 0);
  glBindBufferRange(GL_UNIFORM_BUFFER, 0, buf, 0, sizeof(data));

  // set the right data
  glBufferSubData(GL_UNIFORM_BUFFER, 0, sizeof(data), data);
```

But renderdoc behaved correctly and didn't complain in the `glBufferSubData`, so I guess there must be other factors going on.

**Comment by baldurk** [comment]
That would explain the error as well as why I can't see it in my small repro. The question then is why it's not being registered as a buffer. Buffer resources are assumed to be shared between contexts, so a context switch _shouldn't_ affect this.

Are you able to tell from your side where that buffer is created to investigate there? It must come from either `glCreateBuffers` or `glGenBuffers`, which both register it in that map, and it's then not unregistered until `glDeleteBuffers` is called.

You can add a print to those functions, something like:

```cpp
    ResourceId id = GetResourceManager()->RegisterResource(res);
    RDCLOG("Added buffer %u as ID %llu", res.name, id); // added line
```

To make sure it's registered. Similarly print something in `glDeleteBuffers` like:

```cpp
      RDCLOG("Deleting buffer %u", res.name);
      GetResourceManager()->UnregisterResource(res);
```

**Comment by asylum2010** [comment]
I think this might be a bug in my implementation as both the buffer and the shader program it's associated to are "zombies" (I see their deletion in my log, but not their recreation). I will dig into this a little bit deeper. It's weird tho why glIsBuffer returns GL_TRUE...

**Comment by baldurk** [comment]
Fair enough - I'll close the issue here for now, but in case you find it's still something to do with RenderDoc then just let me know and I can re-open it and investigate.

I suspect glIsBuffer is probably picking up the 'zombie' and it might continue to return TRUE until a texture or something else is allocated for that GLuint. Especially since most drivers still have legacy paths and this kind of overlaps with the old GL behaviour that was deprecated, where you could make up your own names without using glGenBuffers at all.

**Comment by asylum2010** [comment]
Did you say that you assume that GL object names are shared across contexts? Because my log says that each context creates its own numbering:

// create context 1
* CORE: Created core profile context (1) on thread 18460
* CORE: Activated context (1) on thread 18460
* PIPELINE: Created push constant buffer 21
* FACTORY: Cached program 3 with hash '9442913755890896771' (1)

// create context 2
* CORE: Created core profile context (2) on thread 18460
* CORE: Activated context (2) on thread 18460
* PIPELINE: Created push constant buffer 21
* FACTORY: Cached program 3 with hash '9442913755890896771' (2)

// delete context 1
* CORE: Activated context (1) on thread 18460
* FACTORY: Deleted program 3 with hash '9442913755890896771' (1)
* PIPELINE: Deleted push constant buffer 21 (~PROG)
* CORE: Deleted context (1) on thread 18460

// create context 3
* CORE: Created core profile context (3) on thread 18460

// but use context 2
* CORE: Activated context (2) on thread 18460

// program 3 and buffer 21 in context 2 still exists, was never deleted!!!

**Comment by baldurk** [comment]
RenderDoc works under the assumption that all contexts are created to share with each other - ie. `shareContext` set to one of the previous contexts every time you call CreateContextAttribsARB, such that they're all in the same share group.

If you don't set that, then yes each context can create a 'buffer 21' which is different. RenderDoc only handles this case for resources that are *never* shared - like FBOs, program pipelines, etc.

In theory this could be fixable but realistically this isn't something I'll likely get around to for the foreseeable future. Especially as the common case for GL programs is either to only have a single context, or to completely share between all contexts. It's just a limitation of using RenderDoc - much like not supporting legacy GL functions.

**Comment by asylum2010** [comment]
Well the application I'm working on doesn't need context sharing, but creates a lot of GL contexts (being a "multi-document" application). Perhaps I can find out a workaround, but could you please point me to some resources which describe this context sharing thingy?

**Comment by baldurk** [comment]
Sure, I'm not sure if there's explicit documentation anywhere. Basically when you're calling `wglCreateContextAttribsARB` or `glXCreateContextAttribsARB` there's a 'share context' parameter that's either `NULL` by default or the handle to a previously created context. Any GL wrapper that handles context creation for you like glfw will also have a share context parameter.

If you create context A, then create context B sharing with A, then any buffers created in one will be visible (with the same name) in the other, and vice-versa. Same for textures, shaders, and various other objects. Not everything is shared but most objects are.

You can have as many contexts in a sharing group as you want - say you have A, B, C, D in a share group and you create E which shares with B - then it also shares with A, C and D. It's kind of a "friends-of-friends" system.

As far as I'm aware there isn't really any significant cost to sharing every context with every other context, although I'm not sure anyone has done any recent benchmarks.

**Comment by asylum2010** [comment]
Thanks, now renderdoc works fine :) (you don't wanna know what I've been through to achieve this with this monstrous app...)
