### ISSUE TITLE
show reasons why editing a shader fails.

### ISSUE THREAD

**Issue by krux02** [baldurk/renderdoc#726]
The UI doesn't tell me anything. It doesn't even thell me that shader patching failed, it just doesn't have any effect. When I open the console where I started qrenderdoc, I see this message:

```
Error   - Couldn't make separable program for shader via patching - functionality will be broken.
Error   - Couldn't make separable shader program for shader. Errors:

```

But it doesn't list any error that I could fix. So I would also like to know what I need so that live editing shaders does work.

**Comment by baldurk** [comment]
I can't really diagnose this without further information. I've checked the code but any errors should always be printed. My best guess is that the shader is failing to compile but your GL driver isn't returning any errors via `glGetShaderInfoLog`, which would explain a blank list of errors.

If that's the case then there might not be much I can do. Those messages in the log can just be ignored, they're knock-ons from the shader failing to compile. I can probably silence them if the shader failed to compile as they're really only intended for the case where the shader compiles but then can't be made into a separable program.

Can you give any more details about your case? What OS and driver are you using? Can you provide the shader or the capture?

**Comment by krux02** [comment]
My Operating system is Manjaro Linux and my driver from pacman is listed as:

    extra/linux44-nvidia 1:375.82-4 (linux44-extramodules) [Installiert]
        NVIDIA drivers for linux.

I think I found out the problem. When I change my shader to use a uniform/attribute that is unused up until then, my program doesn't know about the uniform location (-1), and therefore that uniform/attribute cannot have meaningful data attached to.

**Comment by baldurk** [comment]
Yes, the shader editing can't change the external interface (bound resources etc), since the shader is replaced as-is without binding anything new. In that case if I understand right there are no errors to display - the shader compiled and was replaced successfully, it's just that nothing was bound where you expected something?

If you don't think there's a bug then I can close this issue, otherwise I'd need more details on what else is going wrong.

**Comment by krux02** [comment]
Well I think it would be very nice, if there would be a reminder in the documentation that tells me that I should used fixed attribute and uniform locations, so that live editing can work reliable. The best would be, if there is live feedback, when a shader chage also attribue/uniform locations. But apart from the documentation, I can't say that there is anything broken in the software, just the feedback could be better.
