### ISSUE TITLE
Invalid vulkan usage hardening: Renderdoc crashes when a draw call references a shader that uses a descriptor set but isn't bound/specified.

### ISSUE THREAD

**Issue by Lssikkes** [baldurk/renderdoc#727]
In vk_debug.cpp:
	for (uint32_t i = 0; i < descSet; i++)
		descSetLayouts[i] = GetResourceManager()->GetCurrentHandle<VkDescriptorSetLayout>( creationInfo.m_PipelineLayout[pipeInfo.layout].descSetLayouts[i]);

In creationInfo.m_PipelineLayout[pipeInfo.layout].descSetLayouts[i], "i" can be out of bounds of the array due to no descriptor set being bound, crashing RenderDoc.

Attached minimal repro case renderdoc:
[EX-BASIC_2017.08.29_17.30.26_frame3006.zip](https://github.com/baldurk/renderdoc/files/1261666/EX-BASIC_2017.08.29_17.30.26_frame3006.zip)

**Comment by baldurk** [comment]
If I understand correctly then this probably isn't something I'll fix. Tolerating invalid API use is not a goal for RenderDoc on any API, and especially on explicit APIs like Vulkan it's going to cause things to blow up. However that's a problem for the validation layers to solve, handling and surviving invalid use like that will end up meaning I duplicate all the work that goes into the validation layers which is not worthwhile. If this isn't something the validation layers catch then you can file an issue there, they're usually good about adding reported missing checks quickly.

In some cases if it's trivial to add a check I don't mind, but in this case I think there would be a lot of knock-on problems so it's not something I can just silently ignore in one place with minimal impact.

If I've misunderstood and this is valid use but is crashing, let me know and I'll investigate.

**Comment by Lssikkes** [comment]
Alright, fair enough - I've changed this locally so that it just puts a dummy object in there, which fixes the issue for me.. For this sample I'm still working on all the bindings and making it completely validation proof, but wanted to check if the rest of the state was already as expected using renderdoc. I'll just keep this change locally then, thanks!
