### ISSUE TITLE
Inject abruptly stops

### ISSUE THREAD

**Issue by polkovnikov-ph** [baldurk/renderdoc#728]
When debugging Java (LWJGL 2) application, the following happens when `renderdoc` redirects back to "Inject into Process" screen.

```
RDOC 002284: [18:22:34]    win32_process.cpp( 518) - Log     - Injecting renderdoc into process 5988
RDOC 005988: [18:22:34]             core.cpp( 318) - Log     - RenderDoc v0.91 x64 Release (2d8b2cf818746b6a2add54e2fef449398816a40c) capturing application
RDOC 005988: [18:22:34]   win32_libentry.cpp(  67) - Log     - Loading into C:\Program Files\Java\jdk1.8.0_121\bin\java.exe
RDOC 002284: [18:22:35]   target_control.cpp( 412) - Log     - Got remote handshake: java () [5988]
RDOC 005988: [18:22:40]   gl_hooks_win32.cpp( 613) - Log     - dc 000000005A01107B. PFD: type 0, 32 color bits, 24 depth bits, 0 stencil bits. Win: 854x480
RDOC 005988: [18:22:40]        gl_common.cpp( 406) - Log     - Vendor checks for 0 (NVIDIA Corporation / GeForce GTX 950M/PCIe/SSE2 / 4.5.0 NVIDIA 378.92)
RDOC 005988: [18:22:40]        gl_common.cpp( 688) - Warning - FBOs are shared on this implementation
RDOC 005988: [18:22:40] gl_texture_funcs.cpp(1281) - Error   - Called texture function with invalid/unrecognised texture, or no texture bound to implicit slot
RDOC 005988: [18:22:40] gl_texture_funcs.cpp(1281) - Error   - Called texture function with invalid/unrecognised texture, or no texture bound to implicit slot
RDOC 005988: [18:22:40] gl_texture_funcs.cpp(1281) - Error   - Called texture function with invalid/unrecognised texture, or no texture bound to implicit slot
RDOC 005988: [18:22:40] gl_texture_funcs.cpp(1689) - Error   - Called texture function with invalid/unrecognised texture, or no texture bound to implicit slot
RDOC 005988: [18:22:40] gl_texture_funcs.cpp(2353) - Error   - Calling non-DSA texture function with no texture bound to active slot
RDOC 005988: [18:22:40] gl_texture_funcs.cpp(1281) - Error   - Called texture function with invalid/unrecognised texture, or no texture bound to implicit slot
RDOC 005988: [18:22:40] gl_texture_funcs.cpp(1281) - Error   - Called texture function with invalid/unrecognised texture, or no texture bound to implicit slot
RDOC 005988: [18:22:40] gl_texture_funcs.cpp(1281) - Error   - Called texture function with invalid/unrecognised texture, or no texture bound to implicit slot
RDOC 005988: [18:22:40] gl_texture_funcs.cpp(1281) - Error   - Called texture function with invalid/unrecognised texture, or no texture bound to implicit slot
RDOC 005988: [18:22:40] gl_texture_funcs.cpp(4692) - Error   - Called texture function with invalid/unrecognised texture, or no texture bound to implicit slot
RDOC 002284: [18:22:40]    win32_network.cpp( 178) - Warning - recv: 10054
```

Seems like 10054 (connection closed) is the only thing that might be related to the issue. If I understand correctly, it's telling that injected DLL suddenly disconnected from local server, and pretty much nothing else. What do I do?

**Comment by baldurk** [comment]
Can you clarify some things:

* Does the program crash? It looks like it, but you don't say exactly. By 'redirects back to the "Inject into Process" screen' do you mean that your program closes/crashes and so the connection window in renderdoc closes, and the next visible window is back to "Inject into Process"?
* If you're injecting are you injecting *before* the target program has used the target API?

My best guess is that you've injected into the program after the API is initialised, then a context creation is seen and renderdoc starts intercepting GL calls but without having seen all of the initialisation necessary to have the textures tracked. Some functions will handle it (as the errors indicate) but I'm sure others won't, and will just crash.

**Comment by polkovnikov-ph** [comment]
It doesn't crash. Java process keeps working with no problems.

I've set breakpoint into the first line of `main`, and inject while the process is paused in debugger. LWJGL (and OpenGL context) gets initialized much further.

**Comment by baldurk** [comment]
OK. In that case I'm not sure what's wrong, I'd need more information to investigate. The error message about the socket is most likely just be a symptom of something else - the connection is lost due to some other problem.

Can you re-attach by going to file -> attach to running instance and locating the running program there? Do you get the overlay in your program, and if so are you able to make captures and see them saved to disk (by default to `%TEMP%/RenderDoc/`)?

The GL error messages still indicate that something is quite wrong, and I don't know if RenderDoc can survive whatever is causing that.

Are you able to share the program with me to debug directly?

**Comment by polkovnikov-ph** [comment]
Yes, I understand that there's certainly not enough information.

There was no overlay, and at first I didn't even understand what are you talking about. Now that I restarted RenderDoc instance, application crashes, because `getFunctionAddress` for `glMatrixMode` returns `null`. When I do the same without attaching RenderDoc instance (either under debugger or not), it works. I restarted RenderDoc once again, and this time the issue persists.

The program is called Minecraft, and I'm afraid EULA doesn't allow me to share the jar file. Their website hosts jar file [here](https://launcher.mojang.com/mc/game/1.11.2/client/db5aa600f0b0bf508aaf579509b345c4e34087be/client.jar), and if you need more readable names, you can use semi-official decompiler from [here](http://www.modcoderpack.com/files/mcp937.zip).

But I don't think it's really related to its source code. I've created a blank project with LWJGL 2.9.4 with the following file:

import org.lwjgl.LWJGLException;
import org.lwjgl.opengl.Display;
import org.lwjgl.opengl.DisplayMode;
import java.lang.management.ManagementFactory;

```
public class Test {
    public Test() {
        try {
            Display.setDisplayMode(new DisplayMode(800, 600));
            Display.create();
            
            while(!Display.isCloseRequested()) {
                Display.update();
            }
            
            Display.destroy();
        } catch(LWJGLException e) {
            e.printStackTrace();
        }
    }
    
    public static void main(String[] args) {
        System.out.println(ManagementFactory.getRuntimeMXBean().getName());
        new Test();
    }
}
```

If I attach RenderDoc to it, I get the following overlay:
![image](https://user-images.githubusercontent.com/2983969/29887015-b9ed0202-8dc4-11e7-8faf-08588b439ec9.png)
