### ISSUE TITLE
Mesh Output doesn't appear to update with shader changes.

### ISSUE THREAD

**Issue by vk2gpu** [baldurk/renderdoc#729]
In QRenderDoc w/ D3D11 when editing a vertex shader the VS Out tab doesn't seem to update to reflect the edited shader. It seems to work fine in the texture view.

**Comment by baldurk** [comment]
I considered for a while doing some more complex caching mechanism, so I could keep the unmodified mesh output data for when you remove the shader edits, but in the end I decided just to clear the cache when anything changes. It's a much simpler/more robust change, and it will work in the future when state edits and buffer edits are supported without any modification.

I've merged it to both branches, so please check on the next nightly build (or compile yourself) and let me know if you run into any problems.

**Comment by baldurk** [comment]
v1.0 has now released, including this change.
