### ISSUE TITLE
The "VK_LAYER_RENDERDOC_Capture" affect the device extensions

### ISSUE THREAD

**Issue by leopard02** [baldurk/renderdoc#731]
When I enabled the layer of "VK_LAYER_RENDERDOC_Capture", I found that some device extensions disappeared.
## Disabled  "VK_LAYER_RENDERDOC_Capture":
	* VK_KHR_swapchain                                : extension revision 68
	* VK_KHR_descriptor_update_template               : extension revision  1
	* VK_KHR_dedicated_allocation                     : extension revision  1
	* VK_KHR_get_memory_requirements2                 : extension revision  1
	* VK_KHR_maintenance1                             : extension revision  1
	* VK_KHR_push_descriptor                          : extension revision  1
	* VK_KHR_sampler_mirror_clamp_to_edge             : extension revision  1
	* VK_KHR_shader_draw_parameters                   : extension revision  1
	* VK_KHR_external_memory                          : extension revision  1
	* VK_KHR_external_memory_fd                       : extension revision  1
	* VK_KHR_external_semaphore                       : extension revision  1
	* VK_KHR_external_semaphore_fd                    : extension revision  1
	* VK_KHR_external_fence                           : extension revision  1
	* VK_KHR_external_fence_fd                        : extension revision  1
	* VK_KHX_device_group                             : extension revision  1
	* VK_KHX_external_memory                          : extension revision  1
	* VK_KHX_external_memory_fd                       : extension revision  1
	* VK_KHX_external_semaphore                       : extension revision  1
	* VK_KHX_external_semaphore_fd                    : extension revision  1
	* VK_KHX_multiview                                : extension revision  1
	* VK_EXT_discard_rectangles                       : extension revision  1
	* VK_EXT_shader_subgroup_ballot                   : extension revision  1
	* VK_EXT_shader_subgroup_vote                     : extension revision  1
	* VK_EXT_display_control                          : extension revision  1
	* VK_NV_dedicated_allocation                      : extension revision  1
	* VK_NV_glsl_shader                               : extension revision  1
	* VK_NV_clip_space_w_scaling                      : extension revision  1
	* VK_NV_sample_mask_override_coverage             : extension revision  1
	* VK_NV_viewport_array2                           : extension revision  1
	* VK_NV_viewport_swizzle                          : extension revision  1
	* VK_NV_geometry_shader_passthrough               : extension revision  1
	* VK_NVX_device_generated_commands                : extension revision  1
	* VK_NVX_multiview_per_view_attributes            : extension revision  1

## Enabled  "VK_LAYER_RENDERDOC_Capture":
	* VK_EXT_display_control                          : extension revision  1
	* VK_EXT_shader_subgroup_ballot                   : extension revision  1
	* VK_EXT_shader_subgroup_vote                     : extension revision  1
	* VK_KHR_dedicated_allocation                     : extension revision  1
	* VK_KHR_external_memory                          : extension revision  1
	* VK_KHR_external_memory_fd                       : extension revision  1
	* VK_KHR_external_semaphore                       : extension revision  1
	* VK_KHR_external_semaphore_fd                    : extension revision  1
	* VK_KHR_get_memory_requirements2                 : extension revision  1
	* VK_KHR_maintenance1                             : extension revision  1
	* VK_KHR_sampler_mirror_clamp_to_edge             : extension revision  1
	* VK_KHR_shader_draw_parameters                   : extension revision  1
	* VK_KHR_swapchain                                : extension revision 68
	* VK_NV_dedicated_allocation                      : extension revision  1
	* VK_EXT_debug_marker                             : extension revision  4

**Comment by baldurk** [comment]
Yes, this is deliberate. RenderDoc removes extensions that it doesn't support from enumeration, since otherwise using those extensions would lead to crashes.
