### ISSUE TITLE
Pixel Context view: I don't understand the "Debug" button...

### ISSUE THREAD

**Issue by benblo** [baldurk/renderdoc#732]
So clicking "History" opens the Pixel History tab, fine. But what does "Debug" do? Most of the times it seems like it simply opens the very same Pixel History, but sometimes (?) I've seen it open the pixel shader debugger directly, which seems to be the same behavior as if I had used right click > "Debug Pixel" from a fragment in the history tab.
What's the intended behavior? If it's the later, which fragment would be selected?

**Comment by baldurk** [comment]
The debug button just launches pixel shading debug on the currently selected pixel for the current drawcall. If there are multiple levels of overdraw it will just pick any fragment. If the highlighted pixel isn't covered by the current draw, it then falls back and launches the pixel history.

It's just a kind of shortcut really for when you already have a draw selected and don't need to select a particular fragment - e.g. if it's a fullscreen pass or something - and you don't want to have to run the pixel history just to debug the draw you already have selected.

**Comment by benblo** [comment]
Aaah got it, it depends on the selected draw call, makes sense! Thanks.
