### ISSUE TITLE
Remote replay stopped working

### ISSUE THREAD

**Issue by pantosj** [baldurk/renderdoc#735]
Hi @baldurk 

After I rebased my work on the latest v1.x branch, I found that remote replay is not currently working. The remote server either crashes or freezes my machine after seizing a lot of memory. After some debugging, I think the problem is likely to be caused by commit 9b4ee72. Without it, the remote replay still works.

I didn't try it out with a GL application, but I think it behaves similarly than with GLES. With a simple GLES application a part of remote server's log is:

```
Log     - Timer chunk initialisation - 390.798 ms
Error   - Assertion failed: 'm_ReadFileHandle' 
Error   - Assertion failed: 'm_LiveIDs.find(id) != m_LiveIDs.end()' (id=ResID_7172719)
Error   - Assertion failed: '!m_RemoteServer || m_FromReplaySerialiser->GetSize() == 0' 
Error   - Assertion failed: 'm_ReadFileHandle' 
Error   - Assertion failed: 'm_ReadFileHandle' 
Error   - Assertion failed: 'm_ReadFileHandle' 
Error   - Can't get shader details without separable program
Error   - Assertion failed: 'm_ReadFileHandle' 
Error   - Assertion failed: '!m_RemoteServer || m_FromReplaySerialiser->GetSize() == 0' 
Error   - Can't get shader details without separable program
```

And the stack trace of the first assert is:

```
__GI_raise() at raise.c:54 0x7ffff59fb428	
Serialiser::ReadFromFile() at serialiser.cpp:1 140 0x7ffff77b3d7c	
Serialiser::ReadBytes() at serialiser.cpp:1 123 0x7ffff77b385d	
Serialiser::ReadInto<ResourceId>() at serialiser.h:605 0x7ffff737c5b8	
Serialiser::Serialise<ResourceId>() at serialiser.h:444 0x7ffff7372ce1	
ReplayProxy::GetLiveID() at replay_proxy.cpp:2 656 0x7ffff7761913	
ReplayProxy::SavePipelineState() at replay_proxy.cpp:2 522 0x7ffff77607b0	
ReplayProxy::Tick() at replay_proxy.cpp:2 239 0x7ffff775ec94	
ActiveRemoteClientThread() at remote_server.cpp:462 0x7ffff774c399	
Threading::sThreadInit() at posix_threading.cpp:118 0x7ffff78ced55	
start_thread() at pthread_create.c:333 0x7ffff55ac6ba	
clone() at clone.S:109 0x7ffff5acd3dd	
```

Do you have any idea what's wrong with it?

**Comment by baldurk** [comment]
I don't know off the top of my head. That commit seems like a reasonable guess as to a cause, but I don't see anything obvious.

Note this is explicitly the purpose of the v1.x branch though - so that I can do some larger refactors without having to worry about fixing bugs as I go along until everything has stabilised - much of this code will be deleted or significantly changed in the future.

If you're able to find the bug and fix it then a PR is welcome of course, but otherwise the idea of branching to v0.x and v1.x is to make the best trade-off between possibly unstable future development and stable day-to-day use.

**Comment by cnorthrop** [comment]
I think creating traces may be broken too.  I'm able to connect to the RenderDoc server and layer, but can't trigger any captures, for Vulkan on Android at least.  I'm trying to bisect now, but the build tool changes on v1.x make it a bit challenging.  Need to figure out a good/easy/fast way to track day to day stability.

**Comment by baldurk** [comment]
Try with 80ec87fdd2cfd45c7c60d46798fa7042ffaf258a that I just pushed. qrenderdoc needed an extra flag to properly export the symbol I started using to identify the replay program, which caused weird issues as qrenderdoc thought it was a capturing program.

**Comment by cnorthrop** [comment]
Thanks for the quick heads up, but that doesn't help.  I'll let you know if bisecting turns anything up.

**Comment by cnorthrop** [comment]
I think your suggestion is on the right track:
```
broken: 60a29a2 - Android compile fix for missing definition of NULL (11 days ago) <baldurk>
build error: 82a0e05 - Change how replay programs are identified, from filename to sym export (11 days ago) <baldurk>
build error: fbd1c40 - Add python typemap handling for rdctype::pair (11 days ago) <baldurk>
working: f51a412 - Add GL format unit tests and fix a couple of issues found (11 days ago) <baldurk>
```
So most likely something in 82a0e05 causing it.

**Comment by cnorthrop** [comment]
The new scheme for identifying debug markers expects to use dlsym, but that doesn't work with how Android is hooked up at the moment, where `GetExecutableFilename` is returning the package name.  Restoring the check for `curfile` being `org.renderdoc.renderdoccmd` gets things going again, but doesn't feel like the right solution.

**Comment by baldurk** [comment]
`GetExecutableFilename` isn't used for the dlsym call, it uses `RTLD_DEFAULT` to search if that symbol is available anywhere in any dynamic lib as well as the executable - and it should be exported in `librenderdoccmd.so` on android, right?
