### ISSUE TITLE
Vulkan: Dispatch command sets viewport for following commands to 0

### ISSUE THREAD

**Issue by TiemoJung** [baldurk/renderdoc#740]
Hi,

it seems that a vkDispatch command sets the viewport for all following graphics commands to 0 and so produces incorrect results.

**Comment by baldurk** [comment]
When binding a compute pipeline it was trampling over all the dynamic state, since the compute pipeline won't ever have dynamic state (at least currently - they're all graphics states). It should be fixed with that commit.

**Comment by TiemoJung** [comment]
Looks like it is now working correctly.
