### ISSUE TITLE
RenderDoc does not support instance extension 'VK_KHR_external_fence_capabilities'

### ISSUE THREAD

**Issue by H-EAL** [baldurk/renderdoc#742]
Hi,

RenderDoc version 0.91.
LunarG vulkan SDK 1.0.57.
VK_LAYER_RENDERDOC_Capture enabled and obviously VK_KHR_EXTERNAL_FENCE_CAPABILITIES also enabled.

Note that VK_KHR_EXTERNAL_SEMAPHORE_CAPABILITIES doesn't produce any issue.

Thanks!

**Comment by baldurk** [comment]
This is implemented now, although I didn't have any test case to actually run against it I believe it's almost identical to external semaphores - since I replay them as regular fences and not external, I can just ignore/pass-through the extra calls.

If you run into any troubles please let me know.
