### ISSUE TITLE
Vulkan implementation can only handle 7 output attachments when the limit should be 16.

### ISSUE THREAD

**Issue by gfxguymatt** [baldurk/renderdoc#743]
In vk_core.cpp vulkan::WrappedVulkan::AddDrawcall the assert below is incorrect:

      RDCASSERT(colAtt.size() < 8);

This seems to be in place due to the size limit of DrawcallDescription::outputs[8] but it should allow colAtt to be 8.

Aside from this the Vulkan spec indicates that when multiViewport is supported the minimum value of maxViewports is 16. Is there any reason that RenderDoc can't support this minimum value for v1.x?

**Comment by baldurk** [comment]
You're right that the assert should be changed to `<= 8`. Or better yet `<= ARRAY_COUNT(draw.outputs)` or something.

The `maxViewports` limit is something different though - the number of viewports isn't tied to the number of color attachments in a subpass, which is governed by the `maxColorAttachments` limit. This is 8 on all current hardware so I don't think there's any problem with the current hardcoded size.

**Comment by gfxguymatt** [comment]
Sorry, yes you are correct. The only issue is the assert comparison.

**Comment by baldurk** [comment]
Closing this directly as the assertion is fixed now, thanks for pointing it out. FYI it's harmless enough though since the rest of the code was fine, so you don't need to update to have 8 attachments work.
