### ISSUE TITLE
Vulkan: Replay order possibly wrong

### ISSUE THREAD

**Issue by TiemoJung** [baldurk/renderdoc#746]
Hi,

i encountered some strange behavior of renderdoc (0.x branch). It seems that sometimes render commands and their results are not matching, i encountered render commands that did basically nothing, and the result was the final result of the following render pass and vise versa.
Sometimes render commands that clearly result in geometry that should be drawn to the render target (vs output is the upside down version as we use the viewport inversion of khr maintenance1, and we only use vs and ps/fs) , is never rendered to it, even all those display modes for changes on the render target show nothing.
And then magically a render target has the required content and a render command that uses this is then correct. 
Also the clear before draw and clear before pass, result in not drawing anything and sometimes crash.

**Comment by baldurk** [comment]
This is definitely a bug, but I can't investigate it unless I have something to reproduce the problem. Can you send a capture that shows this behaviour, or share a sample application?

**Comment by TiemoJung** [comment]
Hi,

i did send you a e-mail with more information and a .rdc file

**Comment by TiemoJung** [comment]
Hi,

tested it with latest changes and video drivers and its working as expected now.
