### ISSUE TITLE
Shared library versioning

### ISSUE THREAD

**Issue by gicmo** [baldurk/renderdoc#750]
Hi,
I am trying to get the [rpm](https://copr.fedorainfracloud.org/coprs/gicmo/devel/package/renderdoc/) into the actual fedora repositories, but in fedora every shared library needs to be properly versioned (for proper ABI changes handling), see the section in the [packaging guidelines](https://fedoraproject.org/wiki/Packaging:Guidelines#Downstream_.so_name_versioning). Currently `librenderdoc.so` is unversioned though and thus poses a problem. It would be great to avoid downstream versioning and just properly version the library upstream.

**Comment by baldurk** [comment]
I wonder if versioning is necessary. The guidelines you linked state:

> In cases where upstream ships unversioned .so library **(so this is not needed for plugins, drivers, etc.)**.

Emphasis mine. `librenderdoc.so` isn't a normal library insomuch as no-one should ever link against it directly, but it's not exactly a plugin either. Where does the line get drawn about that?

In terms of ABI, the only guaranteed ABI for programs is the [in-application API](https://renderdoc.org/docs/in_application_api.html) which only exports a single symbol which will never change, as it does all versioning/etc in the parameters to `RENDERDOC_GetAPI`. The remaining exported symbols are all non-contractual as they're internal interfaces for the UI, so aren't part of any ABI promises. Even so again, no-one will link against renderdoc to get that API - it's only for use at runtime dynamically if the application wants to detect renderdoc or control it.

So can you clarify if versioning is actually needed?

**Comment by gicmo** [comment]
So I think we can leave it unversioned if we put it into a private place (since it is basically an internal library) a la <prefix>/renderdoc/librenderdoc.so (e.g. /usr/lib/renderdoc/librenderdoc.so). For compile-time discoverability we could ship a pkg-config file containing that path (like gio does with `giomodulepath`). Does that sound reasonable to you?

**Comment by baldurk** [comment]
I can add some options to allow a custom private subdir like `$LIBDIR/renderdoc/librenderdoc.so` - the path is only used/assumed in a couple of places so that would be minimal impact. I'm not sure what you mean compile-time discoverability though, what would that be for?

**Comment by gicmo** [comment]
> I can add some options to allow a custom private subdir like $LIBDIR/renderdoc/librenderdoc.so - the path is only used/assumed in a couple of places so that would be minimal impact.

Sounds great!

> I'm not sure what you mean compile-time discoverability though, what would that be for?

I was thinking of an application that wants to load the library "normally" via dlopen (not using RTLD_NOLOAD) and needs to know where it is located. The usual way we do this in GNOME is via pkg-config and variables (see [gio-2.0.pc.in](https://git.gnome.org/browse/glib/tree/gio-2.0.pc.in)). Maybe that is not needed for now though.

**Comment by baldurk** [comment]
I don't think that makes sense for any application to do, for similar reasons to why applications won't ever link directly to it. For vulkan hooking the library is loaded & injected via the loader - which has its own registration setup that works independent of where the library is located. For GL hooking `librenderdoc.so` must be in `LD_PRELOAD` - loading it by hand is too late and doesn't really do anything useful.

**Comment by gicmo** [comment]
Sounds all good to me, so we dont have to care about it. ;)

**Comment by baldurk** [comment]
OK, that's only on v1.x branch but I can probably backport it if it's working how you want. This should let you add `-DLIB_SUBFOLDER` in addition to the `-DLIB_SUFFIX` variable. I did a quick test targetting `/tmp/foo` and specifying a subfolder, and everything seemed to work OK locating the library.

**Comment by baldurk** [comment]
@gicmo does this cover everything you need now? I'd like to be sure I have everything distributions might need in place for v1.0.

**Comment by gicmo** [comment]
Renderdoc is included in [fedora](https://src.fedoraproject.org/rpms/renderdoc). So I think yeah all is fine and I think we can close this issue. Thanks.
