### ISSUE TITLE
Renderdoc not able to launch Vulkan application "Possibly the process crashed during early startup?"

### ISSUE THREAD

**Issue by Mercesa** [baldurk/renderdoc#753]
Hello, I am trying to run my Vulkan application with Renderdoc and it instantly throws an error.

The application works fine on its own, when injecting with renderdoc it can not detect which API it uses.

Renderdoc version: v0.91
LunarG SDK version: 1.0.57.0

> 
> RDOC 016412: [13:35:45]    win32_process.cpp( 852) - Error   - Can't locate renderdoc.dll in remote PID 4696
> RDOC 016412: [13:35:56]    win32_process.cpp( 458) - Log     - Running process E:\Github Projects\VulkanPBR\MercesaVulkanFramework\x64\Debug\MercesaVulkanFramework.exe
> RDOC 016412: [13:35:56]    win32_process.cpp( 518) - Log     - Injecting renderdoc into process 5536
> RDOC 016412: [13:35:56]    win32_process.cpp( 259) - Warning - CreateToolhelp32Snapshot(5536) -> 0x0000012b
> RDOC 016412: [13:35:56]    win32_process.cpp( 272) - Error   - Couldn't create toolhelp dump of modules in process 5536
> RDOC 016412: [13:35:56]    win32_process.cpp( 852) - Error   - Can't locate renderdoc.dll in remote PID 5536

**Comment by baldurk** [comment]
Can you give more information? The error listed there 0x12b is 299, according to the `CreateToolhelp32Snapshot` docs:

> If the specified process is a 64-bit process and the caller is a 32-bit process, this function fails and the last error code is ERROR_PARTIAL_COPY (299).

Which doesn't make much sense - can you verify that you're running the 64-bit build of RenderDoc?

If you are, I'll need something more to investigate, is [this](https://github.com/Mercesa/VulkanPBR/tree/master/MercesaVulkanFramework) the project you're building - if I compile the latest code from github will that be able to reproduce the problem?

**Comment by Mercesa** [comment]
My apologies, my standalone executable was missing the SDL2.dll, a bit strange it would give off an error as such. 

My application is now throwing an exception on the creation of the vulkan instance. "Error extension not present". This only happens when running the application through renderdoc, the standalone version of the executable is working fine.

edit: also wanted to note I am querying the extensions through the Vulkan enumerate

**Comment by baldurk** [comment]
Ah, perhaps the message should be rephrased to include missing dependencies as a possible culprit as well as early-startup crashes.

RenderDoc only supports certain vulkan extensions, not all. When enumerating _device_ extensions I'm able to filter out any non-supported extensions so they are not reported while renderdoc is active, but unfortunately due to how the loader works it's not possible to filter out instance extensions.

So instead it will fail the vkCreateInstance call with VK_ERROR_EXTENSION_NOT_PRESENT and print an error message - you can check the diagnostic log you pasted from before, it should have a message.

**Comment by Mercesa** [comment]
Ah I see, VK_KHR_get_surface_capabilities2 is not supported. Hopefully if I disable this extension it should work.

Edit: It works, thanks a lot for helping :)
