### ISSUE TITLE
Bug in floating point display

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#756]
I've got an issue with the way renderdoc handles floats in the inspector, in that the precision displayed is rounded with respect to its true hex value. This has given me a bit of a headache when debugging a seemingly good value that's actually wrong. As an example, I had two different values interpolated from the vertex shader, both of them displayed as 18.0000000000 by renderdoc. As you can see, I cranked up the decimals in the options.

Then inside the shader, I transformed that value into a uint by a simple cast. In some shaders I got 17 and in others 18 (disregard the fact that I could use nointerpolate to force them being passed without being manipulated by the interpolation)

After some head scratching, it turns out that the hex number for one of them was

`418FFFFF = 17.999998`

while the other was

`0x41900001 = 18.000002`

I used this website to get the float values. https://www.h-schmidt.net/FloatConverter/IEEE754.html

**Comment by baldurk** [comment]
Is this using the .NET UI (v0.x branch on windows) or Qt UI (v1.x branch, or anywhere non-windows) ?

From your description it sounds like this is in the buffer viewer, displaying mesh output values, is that correct?

The floating point settings just control the specified precision passed to either toolkit's float-to-string formatting functions. I don't know if either of them provide guarantees about rounding precision when you get to that many decimal places, but I can check to see if I'm doing anything wrong.

**Comment by redorav** [comment]
I'm using the 0.91 on the .NET UI but I can test the Qt UI if you have a beta version readily available somewhere. And yes, sorry I didn't mention it, but this happens everywhere where we inspect a float value, (I guess it's what you call buffer viewer), so hovering over the value doesn't fix it.

UPDATE: I wasn't clear, I'm looking at the value **after** interpolation in the pixel shader, not the mesh output value, because those haven't been interpolated yet.

**Comment by baldurk** [comment]
Right yeh, the float formatting *should* all go through the same code-path, but I wanted to be sure.

The [v1.x nightly builds](https://renderdoc.org/builds#nightly) on windows all use the Qt UI, as the .NET UI is already deleted on that branch :smile: . I don't mind checking and making small fixes to it like this though as the Qt UI is still beta.

**Comment by redorav** [comment]
Ok, I've got a capture readily available, let me test in the Qt UI and see if I get similar results.

**Comment by redorav** [comment]
It seems like the Qt UI version gives much better precision as I can see the **0x418FFFFE == 17.999996185305** value now. I think you can close this with this new information. Do we have an estimate on when the Qt UI will have an official version?

**Comment by baldurk** [comment]
Thanks for checking! I don't have any concrete date yet. It will happen when 1.0 releases but I don't know yet when that will be. I certainly hope it will be before the end of the year, but I'll need to wait until I have more of the features for 1.0 coming together before knowing more precisely.
