### ISSUE TITLE
DX11 DeviceContext QueryInterface missing ID3D11DeviceContext4

### ISSUE THREAD

**Issue by Tomek-Stolarczyk** [baldurk/renderdoc#758]
At this point I just need the interface, not making any calls yet so they don't need to be hooked.
https://msdn.microsoft.com/en-us/library/windows/desktop/mt492481(v=vs.85).aspx

**Comment by baldurk** [comment]
It doesn't look difficult to handle, but it's low priority to add right now - especially if you say you're not actually using the interface.

**Comment by baldurk** [comment]
Fixed at the same time as #864.
