### ISSUE TITLE
Option to capture multiple consecutive frames

### ISSUE THREAD

**Issue by hrydgard** [baldurk/renderdoc#760]
Sometimes there are dependencies between frames like various sorts of pingpong targets, feedback effects and whatnot. It would be useful to have the option to make F12 capture two or three consecutive frames with one keypress, to be able to easily investigate this kind of thing.

Also somewhat related to #442 - if this option would also apply to the "Queue capture of frame" feature, that one would be solved.

**Comment by baldurk** [comment]
Can you clarify exactly what you're wanting over [the existing functionality](https://renderdoc.org/docs/window/capture_connection.html#capture-connection-window)?

![image](https://user-images.githubusercontent.com/661798/31015269-1d60a3fc-a517-11e7-97e5-0cd0fd14a9f9.png)

That will capture 3 consecutive frames after 5 seconds, when you click the 'trigger capture' button. You can tweak the # frames or the delay (by default it's just 1 frame with no delay). Are you wanting something equivalent but to capture some number of frames after a specific number - so frames 500, 501, 502 or something?

**Comment by hrydgard** [comment]
Oh! Apologies, I never noticed that that UI appeared when running. Always just used F12 to capture. I tend to hunt for parameters before launch.... it would make some sense to show them on the Capture Executable tab, but that's up to you.
