### ISSUE TITLE
New install of RenderDoc 0.91 on Windows 10 fails to populate the 'Recently Used' menus

### ISSUE THREAD

**Issue by jshofmann** [baldurk/renderdoc#775]
On a new Windows 10 Professional workstation, I've installed RenderDoc 0.91, and now it fails to add items to the 'Recent Logs' and 'Recent Capture Settings' menus. I'm having no other problems with RenderDoc on this workstation, its D3D11 capture functionality is operating as expected. Those menus have worked reliably on all of my previous workstations, and all of my auxillary workstations here, in every previous version of RenderDoc, including the 0.91 install on my old main workstation. Those menus remain greyed out, regardless of how many times I run RenderDoc and open my .cap file. I expect there's some sort of permission problem here - where does RenderDoc store those settings, so I can examine the ownership and permissions of those places?

Possibly related, I got a strange message from the installer when I ran it - it thought that RenderDoc was already installed, and asked if I wanted to repair my installation instead. (c:\Program Files\RenderDoc did not exist when I ran the installer. What was it looking at?) I have a console SDK that uses a RenderDoc fork as its graphics debugger, I wonder if there is a conflict between those two installs? Thanks for your attention!

**Comment by baldurk** [comment]
Those recent file lists are stored with the other settings in `%APPDATA%\RenderDoc\UI.config`. It certainly sounds like you're hitting a permissions issue, although [the code should be checking for errors](https://github.com/baldurk/renderdoc/blob/v0.x/renderdocui/Code/PersistantConfig.cs#L333-L362) and showing a message box. It might be worth building from source to see if you get any more info on what's going wrong exactly.

It certainly could be a conflict, I obviously can't comment on what a fork might be doing, if it's using a different format for the settings or something like that. (Also, that's the first I've heard of it! Sounds cool, though very surprising :smile:).

**Comment by jshofmann** [comment]
Now that I know where the relevant file is, I deleted that file, ran RenderDoc again, and it recreated that file as expected - so it's not a permission problem. The file's owner and permissions are correct and what you'd expect them to be. Yet my Recent menus remain unpopulated....I guess the problem is upstream of the file creation code? I compared the newly-created UI.config to one from a machine where the Recent menus work as expected, and (unsurprisingly) the only differences are in the < RecentCaptureSettings > and < CheckUpdate_LastUpdate > elements.

Unfortunately, I do not have the time right now to run RenderDoc from source. I may have the time after we ship, but that's weeks away. Is there anything I can easily check that may affect the population of the < RecentCaptureSettings > element?

**Comment by baldurk** [comment]
I'm not sure what else to check without debugging with source. Make sure you're closing renderdoc properly - there are some points where the config files will be saved explicitly but otherwise it usually gets flushed to disk when the program is closed.

**Comment by baldurk** [comment]
Without more information I can't investigate this bug any further, so I'm closing this issue now. If you have any more to add then please comment here. Note that the v1.0 releases use a new UI with different configuration - on the same principles as before but slightly different storage.
