### ISSUE TITLE
"No API connection"

### ISSUE THREAD

**Issue by ioquatix** [baldurk/renderdoc#784]
I have a vulkan program which doesn't use the swap chain. It is used for hardware accelerated offline rendering. It sets up a context and renderer, and renders to a custom framebuffer, then exits.

When I try to run it using renderdoc, it runs fine, but it cannot capture any data.

How can I begin to debug this issue?

**Comment by baldurk** [comment]
This isn't a bug, per se. Without a swap chain renderdoc has no way to know when the frame starts and ends so it can't capture just based on a keypress.

You can use the [in-application API](https://renderdoc.org/docs/in_application_api.html) to control when the frame capture starts and stop based on your own criteria. There are a lot of off-line or headless rendering programs that use this API to capture.

**Comment by ioquatix** [comment]
Okay, awesome, thanks for the quick response.
