### ISSUE TITLE
qrenderdoc crashes when capturing OpenGL application 

### ISSUE THREAD

**Issue by samsartor** [baldurk/renderdoc#798]
I mentioned this as a comment on #778. The crash occurs rarely when the "Trigger Capture" or "Queue Capture" buttons are pressed, but PrtScrn and F12 usually segfault. The "Collect Callstacks" option does not change anything. Notably, the crash does not happen on all applications. For example `gl-320-texture-cube` seems to always work but `gl-320-program` often causes the crash when full-screen. I feel like larger application cause it more often, but I can't really back that up. 

I am running Arch Linux and using the Aur package (RenderDoc v0.91) and my laptop's onboard graphics:
```
00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Richland [Radeon HD 8450G] (prog-if 00 [VGA controller])
	Subsystem: Lenovo Richland [Radeon HD 8450G]
	Flags: bus master, fast devsel, latency 0, IRQ 35
	Memory at e0000000 (32-bit, prefetchable) [size=256M]
	I/O ports at 3000 [size=256]
	Memory at f0300000 (32-bit, non-prefetchable) [size=256K]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: radeon
	Kernel modules: radeon
```

The capture still works (saves the file), the application remains running, and I can capture with PrtScn/F12 again. All that happens is qrenderdoc crashes. I can restart qrenderdoc and then open the saved capture(s) with no issue.

Attached is an example of `gl-320-program` exploding. It did take a few tries, the last capture is the one that blew up.
[qrenderdoc_crash.tar.gz](https://github.com/baldurk/renderdoc/files/1458992/qrenderdoc_crash.tar.gz)

**Comment by samsartor** [comment]
A large PBR rendering demo I wrote never fails to crash. Maybe because it has lots of huge framebuffers and things that `gl-320-program` doesn't?

**Comment by baldurk** [comment]
I've tried to repro this on my system but I'm not having much luck.

Can you try a couple of things:

* Are you able to get the crash without fullscreening the program? For me `gl-320-program-uniform` is a fixed size small window, and I noticed some of your captures are coming back with large framebuffers. That might affect the issue.
* Can you share your rendering demo that always crashes? That might be a more reliable repro.
* Lastly, can you build renderdoc from source on the `v0.x` branch and get a more useful callstack to try and see what's going wrong?

My current working theory is there's some kind of timing issue or race condition and I'm not getting the crash just by luck.

**Comment by baldurk** [comment]
Without more information I can't investigate this bug any further, so I'm closing this issue. If you have any more to add then please comment here. As an addendum to the above, if you do build from source to investigate you should build on the new `v1.x` branch.
