### ISSUE TITLE
crash executing talos renderdoc capture

### ISSUE THREAD

**Issue by airlied** [baldurk/renderdoc#806]
Just captured and tried to replay with timings a trace from talos on vulkan on radv.

#0  0x00007fffc17d10cb in radv_AllocateCommandBuffers (_device=0x7fffb42c73b0, pAllocateInfo=0x7fffc3229aa0, pCommandBuffers=0x7fffc3229ad8) at radv_cmd_buffer.c:2136
#1  0x00007fffc1fd43f5 in vkAllocateCommandBuffers () at /lib64/libvulkan.so.1
#2  0x00007ffff6b94f2f in WrappedVulkan::Serialise_vkBeginCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*, VkCommandBufferBeginInfo const*) (this=0x7fffb4006f10, ser=..., commandBuffer=0x0, pBeginInfo=0x0) at /home/airlied/devel/vulkan/renderdoc/renderdoc/driver/vulkan/wrappers/vk_cmd_funcs.cpp:609
#3  0x00007ffff69b3ef2 in WrappedVulkan::ProcessChunk(ReadSerialiser&, VulkanChunk) (this=0x7fffb4006f10, ser=..., chunk=VulkanChunk::vkBeginCommandBuffer)
    at /home/airlied/devel/vulkan/renderdoc/renderdoc/driver/vulkan/vk_core.cpp:1908

the command pool is NULL inside allocateinfo.

The code in 
renderdoc/driver/vulkan/wrappers/vk_cmd_funcs.cpp
WrappedVulkan::Serialise_vkBeginCommandBuffer:603

appears to assign an unwrapped pool, but then line 608 unwraps it again.

Removing the first unwrap seems to fix things for me.

**Comment by baldurk** [comment]
Your suggested fix to remove the first unwrap is spot on, committed now.
