### ISSUE TITLE
Incorrect alignment checks, issue with error message

### ISSUE THREAD

**Issue by meup** [baldurk/renderdoc#821]
Two things:  

In vk_resource_funcs.cpp, line 1003 & 892, it checks:
    if ((memoryOffset & mrq.alignment) != 0)
when it should probably check:
    if((memoryOffset & (mrq.alignment-1)) != 0)

Also, the error message at line 1005 is printing out 5 numbers, but only 4 are provided (Type is omitted).

**Comment by baldurk** [comment]
Thanks for catching this. I think I'd meant to do `%` to check that it's an even multiple, although since alignment is guaranteed to be power-of-two it's equivalent either way.

Should be fixed with that commit!
