### ISSUE TITLE
Pixel history/debugging chooses the wrong pixel when 'Flip Y' is enabled 

### ISSUE THREAD

**Issue by corngood** [baldurk/renderdoc#839]
On latest v1.x, using d3d11.  When you have Y flipping enabled in texture viewer, and show the history of a pixel, it will show the history of the pixel that would be in the same position if flipping was disabled.

**Comment by baldurk** [comment]
Fixed on v1.x.

**Comment by baldurk** [comment]
v1.0 has now released, including this fix.
