### ISSUE TITLE
Cannot capture on platforms with more than one ICD.

### ISSUE THREAD

**Issue by Themaister** [baldurk/renderdoc#840]
I have a setup now on my Linux box where I have two Vulkan ICDs:
0: AMD's official open source
1: RADV

when I try to capture an application which picks device 1 (RADV), renderdoc does not detect that Vulkan is in fact running. I can make a capture, but when I load that capture, it crashes (probably because it picks device 0).

**Comment by Themaister** [comment]
nvm ... seems to work actually.

**Comment by baldurk** [comment]
FYI this situation is probably always going to be a toss-up. RenderDoc uses the PCI vendor and device ID to match physical devices between capture and replay, so when they're identical it has no way of knowing which one is which. It should fall back on using the same order as the capture (ie. first maps to first, second maps to second) but if that order changes, you're out of luck.
