### ISSUE TITLE
Crash on glClearNamedFramebufferfi

### ISSUE THREAD

**Issue by sagaceilo** [baldurk/renderdoc#842]
Hello,
I've mentioned like over one year ago a bug in OpenGL Khronos XML doc [(here)](https://www.opengl.org/discussion_boards/showthread.php/197656-glClearNamedFramebufferfi-documentation-mismatches-and-errors?p=1279595#post1279595) and that was fixed [(here)](https://www.khronos.org/bugzilla/show_bug.cgi?id=1394). It seems that RenderDoc is still using old function signature with missing [like here](https://github.com/baldurk/renderdoc/blob/e25af7685ba72aa50df86fd464f63c1eb9a6c10c/renderdoc/driver/gl/gl_driver.h#L2367) drawbuffer arguments.

**Issue**: bcoz of that, there is 100% crash when using RenderDoc and this function on app side -> stack corruption on arguments. 
**Solution**: Update newest OpenGL headers (http://glad.dav1d.de/ already uses fixed XML file to generate headers) and reimplement some of RenderDoc function [like this one](https://github.com/baldurk/renderdoc/blob/b471f95c6a8fac45e32d1c22fa2589e5bb983921/renderdoc/driver/gl/wrappers/gl_draw_funcs.cpp#L3422) . I can do a PullRequest when I go back home :)

Thanks !

**Comment by baldurk** [comment]
I've fixed this on the v1.x branch. At this point I don't want to cherry-pick this fix back to v0.x but it shouldn't be long before v1.0 releases.

**Comment by baldurk** [comment]
v1.0 has now released, so I believe this should be now fixed.

**Comment by sagaceilo** [comment]
Sweet :) Thanks !
