### ISSUE TITLE
VS Input triangle view is incorrect when adjacency information is present

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#85]
In the VS Input view of the mesh, the active vertex and triangle it belongs to are selected in Red color. It looks like the triangle selection doesn't work properly with the `TriangleList_Adj` mode. The selection is done in the same way as with `TriangleList`, even though it should skip every odd number when adjacency indices are given:

http://msdn.microsoft.com/en-us/library/windows/desktop/bb509609%28v=vs.85%29.aspx

Optimally, we'd want 3 adjacent triangles to be selected as well (just with a different color, to say, green).

**Comment by baldurk** [comment]
I believe this is all fixed now - if there are remaining issues either re-open or make a new issue with what's currently broken in v0.23 and above.
