### ISSUE TITLE
Program renders differently if launched with RenderDoc

### ISSUE THREAD

**Issue by Erkaman** [baldurk/renderdoc#852]
If I launch my program from the window explorer, it looks like this:

![hair1](https://user-images.githubusercontent.com/602313/35472624-6eaa3f5c-0327-11e8-97e5-e2dacec8b6bf.png)

but if I launch it from renderdoc, it looks like:

![hair2](https://user-images.githubusercontent.com/602313/35472625-71d50e50-0327-11e8-8d94-c1d448ce8037.png)

I have the same issue both on the latest stable release, and the latest nightly build(of 280fe9ad)

The program can be downloaded here:
https://www.dropbox.com/s/5qc3nspvxwxwg2f/hairrender2.zip?dl=0

# How to build and Launch

I use CMake, to generate a VS2017 solution. I tell cmake to put the solution in a folder named build/.  I then launch the program by running the project named "hair_renderer" in the solution. The only dependencies of the program are GLFW and GLAD, but they are both included in the download.

When launching the program from renderdoc, you must make sure that the hair meshes and shaders can be found. Personally, I make sure of this by setting working directory to `build/`.

# project structure

main function is in `src/main.cpp`. The files `*.frag` and `*.vert` are shaders. `preamble.hpp` is a preamble that appended in the beginning of every shader. 

The program renders [opacity shadow maps](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.18.693&rep=rep1&type=pdf)  from the hair mesh(these are stored in an array texture), and then uses these opacity shadow maps to draw the hair mesh with volumetric self-shadows. Finally, some tone mapping is done at the end.

# Other Info:

Graphics Card:  Radeon RX Vega 64
Driver Version: 17.12.2
OS: Windows 10

EDIT: if I tried it on GTX960, it worked perfectly in RenderDoc.

**Comment by baldurk** [comment]
I still can't quite explain why it displays wrongly when running your application under renderdoc, but I did find one thing that was causing the replay to go badly: in your code you leave the depth buffer bound to the framebuffer when doing the offscreen pass to a texture array, but the depth buffer has the size of the window not the texture array. Un-setting the depth buffer fixed the replay for me.

As to the in-application artifact, it seems to go away if I comment out the draw that renders my overlay (but leave all other state setting) which is suspicious. I'll investigate further and see if I can narrow it down and/or report it to AMD.

**Comment by baldurk** [comment]
FYI I've had an update from AMD looking at this - they believe the remaining issue, with the different behaviour while the app is running with renderdoc's overlay, might be a driver bug. It's not confirmed yet but it looks that way and they're going to investigate further.

Are you happy if I close this now, since the capture/replay is accurate?

**Comment by Erkaman** [comment]
alright, you can close it down then.
