### ISSUE TITLE
Probably incorrect VS Output visualisation (Vulkan + viewport negative height)

### ISSUE THREAD

**Issue by kennyalive** [baldurk/renderdoc#856]
We use viewport's negative height extension when specifying VkViewport to match D3D output because of different NDC y-axis orientation. RenderDoc in VS Output window mirrors mesh vertically as expected comparing to D3D capture. But in addition it also mirrors mesh horizontally which looks like a bug for me.

One explanation I have why this happens is how default 'Aspect Ratio' control value might be computed. If it is computed directly like width/height then we get negative aspect ratio value for negative viewport height and this will probably mirror things horizontally. I tried to change 'Aspect Ratio' to non-default value and set it to 1 (we have square viewport). After this change the mesh was mirrored horizontally in the expect position. That's why I assume that computed default aspect ratio is -1.

Default aspect ratio (wrong output):
![rd1](https://user-images.githubusercontent.com/4964024/35735032-812c9656-0823-11e8-8fab-b43e4fbf3906.png)

Set manually (expected output):
![rd2](https://user-images.githubusercontent.com/4964024/35735044-87d2392a-0823-11e8-91a0-75d332f5df10.png)

**Comment by baldurk** [comment]
Yes you're exactly right, [the v0.91 code just does simple width/height](https://github.com/baldurk/renderdoc/blob/v0.x/renderdocui/Windows/BufferViewer.cs#L3135).

In v1.x I do slightly better, checking for positive width & height, but that's still not right. I think I can safely just take `abs()` on width and height. Thanks!

**Comment by baldurk** [comment]
I've fixed this on both v0.x and v1.x, so the next nightly build should behave correctly.

**Comment by kennyalive** [comment]
Thank you! I'll test the build on Monday.

**Comment by kennyalive** [comment]
It works as expected. Thank you.
