### ISSUE TITLE
GTA V crashes on F12 capture from renderdoc & capture file corrupted

### ISSUE THREAD

**Issue by shreyaj** [baldurk/renderdoc#858]
I am using renderdoc v0.91 64 bit version to capture GTA V. I used "Attach to process" and successfully saw the over lay on the game but when I press F12, the game stops responding and eventually "exits unexpectedly". A capture file is saved but when I try to open it, I get an error saying that the file is either corrupted or of wrong format. I tried the answers I could find regarding this issue and none of them fixed it for me. Below are two diagnostic logs, one for opening the corrupted capture file and the other for attach to process.

OPEN CAPTURE FILE DIAGNOSTIC LOG:

RDOC 001468: [21:56:02]             core.cpp( 318) - Log     - RenderDoc v0.91 x64 Release (2d8b2cf818746b6a2add54e2fef449398816a40c) loaded in replay application
RDOC 001868: [21:56:02]             core.cpp( 318) - Log     - RenderDoc v0.91 x64 Release (2d8b2cf818746b6a2add54e2fef449398816a40c) loaded in replay application
RDOC 001468: [21:56:04]     entry_points.cpp( 619) - Warning - adbExePath not set, attempting to call 'adb' in working env
RDOC 001468: [21:56:04]     entry_points.cpp( 591) - Log     - COMMAND: adb devices
RDOC 001468: [21:56:04]    win32_process.cpp( 458) - Log     - Running process adb
RDOC 001468: [21:56:04]    win32_process.cpp( 475) - Warning - Process adb could not be loaded.
RDOC 001468: [21:56:04]    win32_process.cpp( 916) - Warning - Couldn't launch process 'adb'
RDOC 001468: [21:56:43]    win32_process.cpp( 518) - Log     - Injecting renderdoc into process 12276
RDOC 012276: [21:56:43]             core.cpp( 318) - Log     - RenderDoc v0.91 x64 Release (2d8b2cf818746b6a2add54e2fef449398816a40c) capturing application
RDOC 012276: [21:56:45]   win32_libentry.cpp(  67) - Log     - Loading into D:\research\steamapps\common\Grand Theft Auto V\GTA5.exe
RDOC 012276: [21:56:45]     dxgi_wrapped.cpp( 742) - Warning - Querying IDXGIAdapter for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:45]     dxgi_wrapped.cpp( 178) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:45]      d3d11_hooks.cpp( 275) - Log     - Created wrapped D3D11 device.
RDOC 012276: [21:56:45]     dxgi_wrapped.cpp( 742) - Warning - Querying IDXGIAdapter for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:45]     dxgi_wrapped.cpp( 178) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:45]      d3d11_hooks.cpp( 275) - Log     - Created wrapped D3D11 device.
RDOC 012276: [21:56:45]     dxgi_wrapped.cpp( 742) - Warning - Querying IDXGIAdapter for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:45]     dxgi_wrapped.cpp( 178) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:46]     dxgi_wrapped.cpp( 742) - Warning - Querying IDXGIAdapter for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:46]     dxgi_wrapped.cpp( 178) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:58:32]     d3d11_device.cpp(2761) - Log     - Starting capture, frame 2491
RDOC 012276: [21:58:33]     d3d11_device.cpp(2797) - Log     - Finished capture, Frame 2492
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1486
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1489
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1492
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1498
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1501
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1510
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1522
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6120
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6123
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6126
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6129
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6159
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6162
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6165
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6168
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6688
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6691
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6694
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6697
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6727
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6739
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6817
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6828
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6839
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 23574
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 42951
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 001468: [22:05:53]       serialiser.cpp( 899) - Error   - Unrecognised section type 'f1'
RDOC 001468: [22:05:53]             core.cpp( 819) - Error   - Couldn't open 'D:\research\captures\12276_2018.02.04_21.56.43_frame2492.rdc'
RDOC 001468: [22:05:53]       serialiser.cpp( 899) - Error   - Unrecognised section type 'f1'
RDOC 001468: [22:05:53]             core.cpp( 819) - Error   - Couldn't open 'D:\research\captures\12276_2018.02.04_21.56.43_frame2492.rdc'

ATTACH TO PROCESS DIAGNOSTIC LOG:

RDOC 001468: [21:56:02]             core.cpp( 318) - Log     - RenderDoc v0.91 x64 Release (2d8b2cf818746b6a2add54e2fef449398816a40c) loaded in replay application
RDOC 001868: [21:56:02]             core.cpp( 318) - Log     - RenderDoc v0.91 x64 Release (2d8b2cf818746b6a2add54e2fef449398816a40c) loaded in replay application
RDOC 001468: [21:56:04]     entry_points.cpp( 619) - Warning - adbExePath not set, attempting to call 'adb' in working env
RDOC 001468: [21:56:04]     entry_points.cpp( 591) - Log     - COMMAND: adb devices
RDOC 001468: [21:56:04]    win32_process.cpp( 458) - Log     - Running process adb
RDOC 001468: [21:56:04]    win32_process.cpp( 475) - Warning - Process adb could not be loaded.
RDOC 001468: [21:56:04]    win32_process.cpp( 916) - Warning - Couldn't launch process 'adb'
RDOC 001468: [21:56:43]    win32_process.cpp( 518) - Log     - Injecting renderdoc into process 12276
RDOC 012276: [21:56:43]             core.cpp( 318) - Log     - RenderDoc v0.91 x64 Release (2d8b2cf818746b6a2add54e2fef449398816a40c) capturing application
RDOC 012276: [21:56:45]   win32_libentry.cpp(  67) - Log     - Loading into D:\research\steamapps\common\Grand Theft Auto V\GTA5.exe
RDOC 012276: [21:56:45]     dxgi_wrapped.cpp( 742) - Warning - Querying IDXGIAdapter for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:45]     dxgi_wrapped.cpp( 178) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:45]      d3d11_hooks.cpp( 275) - Log     - Created wrapped D3D11 device.
RDOC 012276: [21:56:45]     dxgi_wrapped.cpp( 742) - Warning - Querying IDXGIAdapter for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:45]     dxgi_wrapped.cpp( 178) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:45]      d3d11_hooks.cpp( 275) - Log     - Created wrapped D3D11 device.
RDOC 012276: [21:56:45]     dxgi_wrapped.cpp( 742) - Warning - Querying IDXGIAdapter for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:45]     dxgi_wrapped.cpp( 178) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:46]     dxgi_wrapped.cpp( 742) - Warning - Querying IDXGIAdapter for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:56:46]     dxgi_wrapped.cpp( 178) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 012276: [21:58:32]     d3d11_device.cpp(2761) - Log     - Starting capture, frame 2491
RDOC 012276: [21:58:33]     d3d11_device.cpp(2797) - Log     - Finished capture, Frame 2492
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1486
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1489
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1492
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1498
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1501
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1510
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 1522
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6120
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6123
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6126
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6129
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6159
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6162
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6165
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6168
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6688
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6691
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6694
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6697
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6727
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6739
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6817
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6828
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 6839
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 23574
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 012276: [21:58:33]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 42951
RDOC 012276: [21:58:33]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
 
Any help would be greatly appreciated. Thank you!

**Comment by baldurk** [comment]
I'm afraid I don't provide any help or assistance for capturing programs you don't own or have any rights to.
