### ISSUE TITLE
Shader edit can use the wrong source to compile shader if the original shader file has includes.

### ISSUE THREAD

**Issue by wdegroot** [baldurk/renderdoc#861]
RenderDoc can use the wrong shader source to compile an edited shader if the original shader has includes.

The bug orginates from this [line.](https://github.com/baldurk/renderdoc/blob/v0.x/renderdocui/Windows/PipelineState/D3D11PipelineStateViewer.cs#L2425) 
`shaderDetails.DebugInfo.files` is a list of all the shader files (both the shader file itself and includes). The list seems to be sorted alphabetically(?). The edited shader won't compile if the first file doesn't contain your shader entry point, you will get a HLSL error that the shader entry point can't be found. I've only tested this on D3D11 but judging from the [D3D12 implemention ](https://github.com/baldurk/renderdoc/blob/v0.x/renderdocui/Windows/PipelineState/D3D12PipelineStateViewer.cs#L2052) it contains the same bug.

**Comment by baldurk** [comment]
Thanks for reporting this.

I think this might be something that's addressed on the v1.x branch. Can you check out the latest v1.x nightly build and see if it's working for you there?

**Comment by wdegroot** [comment]
It's indeed fixed on the v1.x branch. Thanks! 👍
