### ISSUE TITLE
RenderDoc 1.0 minor UI issue: Texture tabs are too wide

### ISSUE THREAD

**Issue by hrydgard** [baldurk/renderdoc#866]
In the Inputs/Outputs view in Texture Viewer, the tabs are so wide that the little tab row scrolls on every click, which is mildly uncomfortable. The strings "Inputs" and "Outputs" are just a fraction of the width of the tabs.

Windows 10.

![tabs_too_wide](https://user-images.githubusercontent.com/130929/35934596-528c06a0-0c3e-11e8-800f-8b3210bd15a9.PNG)

**Comment by baldurk** [comment]
Yeh this is one of the little Qt things I want to polish and fix. The minimum tab size was needed for the main tabs to stop things like a tab just called "VS" from being tiny. I need to figure out how to differentiate the two cases. If it's possible what I'd like to do is set the minimum tab width based on the size of the other tabs in the group.

**Comment by baldurk** [comment]
Turns out that trying to do smarter sizing is impossible or extremely hard, so I compromised by reducing the minimum tab width to something that's a better balance.

**Comment by baldurk** [comment]
I think in the shipped v1.0 this is now at a reasonable balance.
