### ISSUE TITLE
Application looks different when launched with RenderDoc

### ISSUE THREAD

**Issue by matt77hias** [baldurk/renderdoc#869]
As mentioned in a previous [issue #864](https://github.com/baldurk/renderdoc/issues/864), I changed my DXGI and D3D11 interfaces to lower versions. I tested this with an old version (the latest release compatible with RenderDoc), which worked fine when launched from inside RenderDoc.

I now refactored the current version and tried multiple combinations of DXGI and D3D11 dependencies. In each case, RenderDoc is capable of launching the executable, but the observed behavior is not the same as when launching the executable independent from RenderDoc (command line or from within Visual Studio)? Concretely, I notice a white background instead of my 3D content. My 2D content, however, is rendered correctly (_note that my 2D content will drawn directly to the back buffer, whereas my 3D content will be first drawn to an intermediate rtv_). The cause of this problem is likely to be related to my own code instead of RenderDoc. Though I do not understand how the observed behavior of the application could differ, since RenderDoc will basically hook d3d11.dll?

My dependencies and interfaces are now pretty much the bare minimum:

|      include    |    library     |                                  interfaces                                      |
|---------------|-------------|------------------------------------------------------------|
| `d3d11.h`      | `d3d11.lib` | `ID3D11Device`, `ID3D11DeviceContext`                       |
| `DXGI1_2.h`   | `dxgi.lib`    | `IDXGIAdapter`, `IDXGIOutput1`, `IDXGISwapChain`      |

```
RDOC 006968: [19:09:48]             core.cpp( 318) - Log     - RenderDoc v0.91 x64 Release (2d8b2cf818746b6a2add54e2fef449398816a40c) loaded in replay application
RDOC 021984: [19:09:48]             core.cpp( 318) - Log     - RenderDoc v0.91 x64 Release (2d8b2cf818746b6a2add54e2fef449398816a40c) loaded in replay application
RDOC 006968: [19:09:50]     entry_points.cpp( 619) - Warning - adbExePath not set, attempting to call 'adb' in working env
RDOC 006968: [19:09:50]     entry_points.cpp( 591) - Log     - COMMAND: adb devices
RDOC 006968: [19:09:50]    win32_process.cpp( 458) - Log     - Running process adb
RDOC 006968: [19:09:50]    win32_process.cpp( 475) - Warning - Process adb could not be loaded.
RDOC 006968: [19:09:50]    win32_process.cpp( 916) - Warning - Couldn't launch process 'adb'
RDOC 006968: [19:10:04]    win32_process.cpp( 458) - Log     - Running process D:\Users\Matthias\Documents\Visual Studio 2017\Projects\MAGE\MAGE\FPS\bin\x64\Release\FPS.exe
RDOC 006968: [19:10:06]    win32_process.cpp( 518) - Log     - Injecting renderdoc into process 18544
RDOC 006968: [19:10:09]    win32_process.cpp( 259) - Warning - CreateToolhelp32Snapshot(18544) -> 0x00000018
RDOC 018544: [19:10:07]             core.cpp( 318) - Log     - RenderDoc v0.91 x64 Release (2d8b2cf818746b6a2add54e2fef449398816a40c) capturing application
RDOC 018544: [19:10:09]   win32_libentry.cpp(  67) - Log     - Loading into D:\Users\Matthias\Documents\Visual Studio 2017\Projects\MAGE\MAGE\FPS\bin\x64\Release\FPS.exe
RDOC 006968: [19:10:09]   target_control.cpp( 412) - Log     - Got remote handshake: FPS () [18544]
RDOC 018544: [19:10:14]     dxgi_wrapped.cpp( 742) - Warning - Querying IDXGIAdapter for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 018544: [19:10:14]     dxgi_wrapped.cpp( 178) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RDOC 006968: [19:10:15]   target_control.cpp( 645) - Log     - Used API: D3D11
RDOC 018544: [19:10:25]     d3d11_device.cpp(2761) - Log     - Starting capture, frame 7771
RDOC 018544: [19:10:25]     d3d11_device.cpp(2797) - Log     - Finished capture, Frame 7772
RDOC 018544: [19:10:25]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 64
RDOC 018544: [19:10:25]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 018544: [19:10:25]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 73
RDOC 018544: [19:10:25]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 018544: [19:10:25]     d3d11_device.cpp(1785) - Warning - Not serialising texture 2D initial state. ID 76
RDOC 018544: [19:10:25]     d3d11_device.cpp(1790) - Warning - Detected Write before Read of this target - assuming initial contents are unneeded.
Capture again with Save All Initials if this is wrong
RDOC 018544: [19:10:25]       serialiser.cpp(1490) - Log     - Compressed frame capture data from 125380750 to 94340854
RDOC 018544: [19:10:25]       serialiser.cpp(1327) - Log     - Timer File writing - 199.905 ms
RDOC 018544: [19:10:25]             core.cpp(1057) - Log     - Written to disk: C:\Users\Matthias\AppData\Local\Temp\RenderDoc\FPS_2018.02.10_19.10.04_frame7772.rdc
RDOC 006968: [19:10:25]   target_control.cpp( 612) - Log     - Got a new capture: 0 (time 1518286225) 24197 byte thumbnail
RDOC 006968: [19:10:27]    win32_network.cpp( 178) - Warning - recv: 10054
RDOC 006968: [19:10:27] replay_controller.cpp(1568) - Log     - Creating replay device for C:\Users\Matthias\AppData\Local\Temp\RenderDoc\FPS_2018.02.10_19.10.04_frame7772.rdc
RDOC 006968: [19:10:27]      d3d11_hooks.cpp( 275) - Log     - Created wrapped D3D11 device.
RDOC 006968: [19:10:27]     amd_counters.cpp( 121) - Warning - AMD GPU performance counters could not be initialized successfully. Are you missing the DLLs?
RDOC 006968: [19:10:27]     d3d11_replay.cpp(2119) - Log     - Created device.
RDOC 006968: [19:10:27] replay_controller.cpp(1587) - Log     - Created replay driver.
RDOC 006968: [19:10:27]     d3d11_device.cpp(1168) - Log     - Timer chunk initialisation - 212.490 ms
RDOC 006968: [19:15:33]      d3d11_debug.cpp(2051) - Warning - Attempting to read off the end of the buffer (0 162848). Will be clamped (144224)
RDOC 006968: [19:16:17]      d3d11_debug.cpp(2051) - Warning - Attempting to read off the end of the buffer (0 162848). Will be clamped (144224)
```

**Comment by baldurk** [comment]
It's not so much 3D/2D but with how constants are managed - imgui's constants are getting through OK but yours are being replaced with `0xcccccccc` everywhere:

![image](https://user-images.githubusercontent.com/661798/36100873-98dd257a-0fff-11e8-99b0-daf5c41346d3.png)

What's happening is that in `constant_buffer.tpp` (and `structured_buffer.tpp`) you have a `BufferLock` class you used for scoped `Map()` / `Unmap()` access to a buffer's data, which you then `memcpy` into. The problem is you declare the `BufferLock` like this:

```cpp
// Map the buffer.
D3D11_MAPPED_SUBRESOURCE mapped_buffer;
BufferLock(device_context, m_buffer.Get(),
		   D3D11_MAP_WRITE_DISCARD, &mapped_buffer);

memcpy(mapped_buffer.pData, &data, sizeof(DataT));
```

Which leads to it getting constructed then destructed in the same line, and in particular that means the destructor calls `Unmap()` before you've called `memcpy`. It seems like when you're running normally you get away with writing into the mapped pointer even after calling `Unmap()`, but this is undefined behaviour and could potentially break or crash on a different driver or under different circumstances.

If I declare a local variable like `BufferLock scopedlock(device_context, m_buffer.Get(), D3D11_MAP_WRITE_DISCARD, &mapped_buffer);` which will live until the end of the function after the `memcpy`, then it all works OK.

**Comment by matt77hias** [comment]
@baldurk A very big thank you for your time and effort to look into this issue (which turned out to be completely independent of RenderDoc). The `BufferLock` is indeed destroyed before the transfer of data for `ConstantBuffer` and `StructuredBuffer`. Adding a local variable name, results in the same correct behavior with and without RenderDoc and with and without NVidia Nsight (for which I faced the same problem), the renderings are shown, and all the RTVs, DSVs, UAVs and SRVs are present and populated correctly. Thank you very much!

**Comment by baldurk** [comment]
No problem! It would have been a lot harder to track down for anyone not familiar with RenderDoc's internals :smile:.
