### ISSUE TITLE
[renderdoc v0.91] Fail to launch FIFA2018 for capturing a log 

### ISSUE THREAD

**Issue by TURuibo** [baldurk/renderdoc#873]
When I use renderdoc v0.91 to capture a log of FIFA 2018, I can launch the game but cannot see the overlay and the tab for capturing frames. And diagnostic log shows no errors.
What might be the reasons for this? 

RDOC 006412: [07:13:50]    win32_process.cpp( 458) - Log     - Running process C:\Program Files (x86)\Origin Games\FIFA 18\FIFA18.exe
RDOC 006412: [07:13:50]    win32_process.cpp( 518) - Log     - Injecting renderdoc into process 9424
RDOC 009424: [07:13:51]             core.cpp( 318) - Log     - RenderDoc v0.91 x64 Release (2d8b2cf818746b6a2add54e2fef449398816a40c) capturing application
RDOC 009424: [07:13:52]   win32_libentry.cpp(  67) - Log     - Loading into C:\Program Files (x86)\Origin Games\FIFA 18\FIFA18.exe
RDOC 006412: [07:13:52]   target_control.cpp( 412) - Log     - Got remote handshake: FIFA18 () [9424]
RDOC 006412: [07:13:52]    win32_network.cpp( 178) - Warning - recv: 10054

**Comment by TURuibo** [comment]
when I used the old version, it shows:
RENDERDOC:  [07:26:27]             core.cpp( 242) - Log     - RenderDoc v0.27 x64 (NO_GIT_COMMIT_HASH_DEFINED) loaded in replay application
RENDERDOC:  [07:26:43]    win32_process.cpp( 307) - Log     - Injecting renderdoc into process 9168
RENDERDOC:  [07:26:43]    remote_access.cpp( 389) - Log     - Got remote handshake: FIFA18 () [9168]
RENDERDOC:  [07:26:44]    win32_network.cpp( 169) - Warning - recv: 10054
RENDERDOC:  [07:26:47]    win32_network.cpp( 344) - Warning - Failed to connect to localhost:38920
RENDERDOC:  [07:26:50]    win32_network.cpp( 344) - Warning - Failed to connect to localhost:38920

**Comment by baldurk** [comment]
Capturing third party copyrighted games is **not** supported in RenderDoc. Aside from the legal issues, there can be many reasons why hooking does not work on a game with copy-protection and other DRM.
