### ISSUE TITLE
Vulkan capture not working when Vulkan loader is statically linked

### ISSUE THREAD

**Issue by null77** [baldurk/renderdoc#874]
Currently in WrappedVulkan::vkCreateInstance we have this code:

```  // enumerate what instance extensions are available
  void *module = Process::LoadModule(VulkanLibraryName);
  PFN_vkEnumerateInstanceExtensionProperties enumInstExts =
      (PFN_vkEnumerateInstanceExtensionProperties)Process::GetFunctionAddress(
          module, "vkEnumerateInstanceExtensionProperties");

  uint32_t numSupportedExts = 0;
  enumInstExts(NULL, &numSupportedExts, NULL);

  std::vector<VkExtensionProperties> supportedExts(numSupportedExts);
  enumInstExts(NULL, &numSupportedExts, &supportedExts[0]);
```

When I load ANGLE's tests for capture, RenderDoc explodes when it tries to call  `enumInstExts` which is null. `module` is also null from the call to `Process::LoadModule`, because ANGLE never loads `vulkan-1.dll`. It links in the Vulkan loader statically, which calls right into the driver (as far as I can see, not entirely sure how it works).

Is it possible to change RenderDoc (or barring that, ANGLE) such that we can use Vulkan capture?

**Comment by baldurk** [comment]
At the moment renderdoc only uses this list to try and enable debug report when available. It could easily just add an `if(module)` in the appropriate place and leave the supportedExts list empty, that would work for now.

But I think I should be able to use the `pfnNextGetInstanceProcAddr` used to fetch the `vkCreateInstance` function pointer, since that's what I do after creating the instance. I just wasn't entirely sure at the time whether that was valid *before* calling `vkCreateInstance`.

**Comment by null77** [comment]
Thanks.. checking for nullptr got a bit farther - this time into `Vulkan_CreateReplayDevice`, where the module check fails again. I did have it working before at one point, not sure if something changed.

**Comment by baldurk** [comment]
That call happens at replay time - that suggests you don't have `vulkan-1.dll` at all on your system? RenderDoc won't work in this situation, I'm not going to statically link the vulkan loader so the runtime must be installed - plus any compatible vulkan driver should install it as part of its package.

**Comment by null77** [comment]
That's correct, vulkan-1.dll is not being loaded. I'm building the loader myself and statically linking. It might be present in the system somewhere (I do have the SDK installed, and it's in there) but not in the default search paths when I'm running RenderDoc.

**Comment by baldurk** [comment]
The SDK runs the vulkan runtime installer, and puts it in the system directory (`C:\Windows\System32`). Something sounds wrong if you're not able to load it at all. Does the SDK's cube sample run? It's linked to  `vulkan-1.dll` instead of `LoadLibrary`ing it, but the effect is the same.

**Comment by null77** [comment]
It does not run. I can try reinstalling my graphics drivers - I've just been running ANGLE (OpenGL ES on Vulkan) so haven't been using the more common use cases of loading entry points.

**Comment by baldurk** [comment]
It definitely sounds like your setup is in a strange state. When the SDK is installed it should be in a good state, so it sounds like something corrupted it since then.

**Comment by null77** [comment]
Is the SDK required or is the driver install sufficient?

**Comment by baldurk** [comment]
The driver should also install the vulkan runtime, yes.

**Comment by null77** [comment]
Driver reinstalled, works like a charm. Must have been a problem with my messed-up setup. Thanks!
