### ISSUE TITLE
Vulkan: Event Browser has two typos for clear commands

### ISSUE THREAD

**Issue by null77** [baldurk/renderdoc#876]
in `WrappedVulkan::Serialise_vkCmdClearDepthStencilImage`, we see:

```
        DrawcallDescription draw;
        draw.name = StringFormat::Fmt("vkCmdClearColorImage(%f, %u)", DepthStencil.depth,
                                      DepthStencil.stencil);
```

Seems like the string should say `vkCmdClearDepthStencilImage`.

Also, in `WrappedVulkan::Serialise_vkCmdClearColorImage`, we see:

```
        DrawcallDescription draw;
        draw.name = StringFormat::Fmt("vkCmdClearColorImage(%f, %f, %f, %f)", Color.float32[0],
                                      Color.float32[0], Color.float32[0], Color.float32[0]);
```

Seems like the format string should reference `Color.float32[0..3]` instead of just `[0]`.

**Comment by baldurk** [comment]
Good catch, thanks! I'm closing this directly as your changes were exactly what I applied.

**Comment by null77** [comment]
Thanks for the fix!
