### ISSUE TITLE
[GL] VS Output doesn't take InstanceID into account

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#882]
Revision: d9c7a4d41657695b502b00d7239184c1eb988254
System: Linux/Xorg
Context: OpenGL version 4.5 (Core Profile) Mesa 17.3.4, Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)

I'm looking at `glDrawElementsInstanced` draw call with 576 instances in the "Mesh Output" tab. The "VS Output" data as well as the "Preview" don't update when I change the instance ID at the top. "VS Input" does change.

![renderdoc-instance](https://user-images.githubusercontent.com/107301/36557730-10e76088-17d7-11e8-83b5-4e293b203764.png)

Might be related to #487
We use a ton of instancing in WebRender, so not being able to investigate a particular one has a strong negative effect on us.

**Comment by baldurk** [comment]
The drawcalls weren't being marked as instanced, so the vertex output data was only being fetched for one instance. Should be fixed with that commit, thanks for the report!

**Comment by baldurk** [comment]
This fix is included in the v1.0 release.
