### ISSUE TITLE
Wrong byte offset when inspecting index buffer used with "StartIndexLocation" (d3d11)

### ISSUE THREAD

**Issue by rocketz** [baldurk/renderdoc#884]
If you inspect an index buffer used by a drawcall that uses "StartIndexLocation" that value is directly used as "byte offset" in the inspector. That value is a offset-index and should be scaled with the size of the format of the index buffer.

**Comment by baldurk** [comment]
Thanks for reporting this. I believe this is fixed on the v1.x branch - can you check with a v1.x nightly build?

I can make a fix separately on the v0.x branch since this is just a missing multiply/scale as you say.

**Comment by rocketz** [comment]
I can confirm it works on v1.x!

(Looks good btw :)

**Comment by baldurk** [comment]
Thanks :smile:. I'll close this once I have a fix on v0.x.
