### ISSUE TITLE
Support the IDXGraphicsAnalysis for programmatic capture

### ISSUE THREAD

**Issue by stonelance** [baldurk/renderdoc#897]
VSGD and the new PIX For Windows support the IDXGraphicsAnalysis API for programmatic capture.  It would be nice if RenderDoc supported it as well so that we can use the same code and don't need to also include the RenderDoc in-application API to get RenderDoc support

**Comment by baldurk** [comment]
I think this should be feasible to support. The API doesn't provide any disambiguation about which device is capturing but as long as there's only one active D3D device that shouldn't be too much of a problem.

**Comment by baldurk** [comment]
This should be implemented now, but I found the interface behaved kind of unpredictably. PIX seems to begin/end as documented, but VSGD would begin when you called `BeginCapture` and then end at the next present, if if you didn't call `EndCapture` until a few frames later. I've implemented the documented behaviour.

It also seems like this interface is only available in windows 8 and above - I assume you're fine with that restriction.
