### ISSUE TITLE
VK_KHR_push_descriptor is not supported.

### ISSUE THREAD

**Issue by disks86** [baldurk/renderdoc#905]
I'm sure there are other extensions higher on your list but support for VK_KHR_push_descriptor would be much appreciated. My current application uses push descriptors so I currently can't debug with render doc.

**Comment by baldurk** [comment]
This should now be supported, I tested it against Sascha Willems' push descriptor sample and it worked there.

Please let me know if you run into any issues as there could still be bugs (the sample is quite a simplistic use, other uses might break).
