### ISSUE TITLE
32-bit qrenderdoc build failure ("SWIG wrapped code invalid in 32 bit architecture, regenerate code using -DSWIGWORDSIZE32")

### ISSUE THREAD

**Issue by akien-mga** [baldurk/renderdoc#906]
Building renderdoc 1.0 on both Mageia 6 i586 (GCC 5.5.0) and Mageia 7 i586 (GCC 7.3.0) (Linux), I get the following build error:
```
[100%] Building CXX object qrenderdoc/Code/pyrenderdoc/CMakeFiles/_qrenderdoc.dir/__/__/renderdoc_python.cxx.o
cd /home/iurt/rpmbuild/BUILD/renderdoc-1.0/build/qrenderdoc/Code/pyrenderdoc && /usr/bin/c++   -DDISTRIBUTION_CONTACT=\"https://madb.mageia.org/package/show/name/renderdoc\" -DDISTRIBUTION_NAME=\"Mageia\" -DDISTRIBUTION_VERSION=\"1.0-1.mga6\" -DGIT_COMMIT_HASH=\"5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c\" -DRENDERDOC_PLATFORM_LINUX -DRENDERDOC_STABLE_BUILD=1 -DRENDERDOC_SUPPORT_GL -DRENDERDOC_SUPPORT_VULKAN -DRENDERDOC_WINDOWING_XCB -DRENDERDOC_WINDOWING_XLIB -D_qrenderdoc_EXPORTS -I/home/iurt/rpmbuild/BUILD/renderdoc-1.0/qrenderdoc -I/home/iurt/rpmbuild/BUILD/renderdoc-1.0/renderdoc/api/replay -I/usr/include/python3.5m  -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fomit-frame-pointer -march=i586 -mtune=generic -fasynchronous-unwind-tables -std=c++11 -fstrict-aliasing -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-unused-result -Wno-type-limits -Wno-missing-field-initializers -Wno-unknown-pragmas -Wno-reorder -Wno-unused-but-set-variable -Wno-maybe-uninitialized -Werror -Wno-unknown-warning-option -Wno-unused-private-field -DNDEBUG -fPIC   -std=gnu++14 -o CMakeFiles/_qrenderdoc.dir/__/__/renderdoc_python.cxx.o -c /home/iurt/rpmbuild/BUILD/renderdoc-1.0/build/qrenderdoc/renderdoc_python.cxx
/home/iurt/rpmbuild/BUILD/renderdoc-1.0/build/qrenderdoc/renderdoc_python.cxx:4252:3: error: #error "SWIG wrapped code invalid in 32 bit architecture, regenerate code using -DSWIGWORDSIZE32"
 # error "SWIG wrapped code invalid in 32 bit architecture, regenerate code using -DSWIGWORDSIZE32"
   ^
```

Full build log: 
[build.0.20180309093408.log.txt](https://github.com/baldurk/renderdoc/files/1796318/build.0.20180309093408.log.txt)

**Comment by baldurk** [comment]
This is in theory an easy fix, I just assume linux is 64-bit in `qrenderdoc/CMakeLists.txt`:

```
if(NOT APPLE)
    set(SWIG_FLAGS "-DSWIGWORDSIZE64")
endif()
```

But I can't test any fix because I don't have any 32-bit linux install to verify that the code actually works.

I'm not sure if 32-bit linux is even used - at least on any desktop platform with sufficient graphics hardware to make use of renderdoc. Does it actually make sense to support 32-bit linux? Even 32-bit windows is almost gone, I only really support it because many people still default to building 32-bit applications.

**Comment by akien-mga** [comment]
32-bit Linux is still used, at least checking the download stats for Godot Engine 3.0 (which requires OpenGL 3.3 support), ~10% of the Linux downloads are for the 32-bit build.

I agree that it's likely not the main platform renderdoc users will use, but at the same time it doesn't make much sense (yet) to drop 32-bit support in an application if it can build on 32-bit out of the box. Most Linux distros won't package 64-bit only applications, as they thrive (again, for now) to provide the same level of support for 32-bit and 64-bit users.

I'll work on a patch, if all that's needed is a bits check, it shouldn't be too hard to implement.

**Comment by baldurk** [comment]
Fair enough, if there are systems out there then like you say there's no reason to drop it. I'm just surprised that there is such a high proportion of users, since going by steam survey numbers that's 10x higher than *windows* even.

I'd appreciate a patch, thanks!

**Comment by akien-mga** [comment]
> I'm just surprised that there is such a high proportion of users, since going by steam survey numbers that's 10x higher than windows even.

Yeah I find it surprising too. But it's similar for our Windows builds, 15% of Windows users download the 32-bit build for Godot Engine. I guess both Windows and Linux users might download 32-bit builds by habit more than by necessity (which is a terrible idea on Linux, as it's much easier to run a proper 64-bit build than a 32-bit one...).

So yeah, it's a bit of a chicken and egg problem.. Do people use 32-bit because we provide it, or do we provide it because they want to use it? :D
