### ISSUE TITLE
Vulkan 1.1 support

### ISSUE THREAD

**Issue by oscarbg** [baldurk/renderdoc#909]
Hi,
just going to install Vulkan SDK 1.1 and VK1.1 drivers..
any info on what to expect to work and not using new Vulkan 1.1 APIs on Renderdoc 1.0?
thanks..

**Comment by baldurk** [comment]
Vulkan 1.1 will be supported, yes. Some of the extensions that were promoted to core are already supported, others aren't, so it depends on what you're trying to do.
