### ISSUE TITLE
Ctrl + left/right keys change event when editing shaders

### ISSUE THREAD

**Issue by bejitt** [baldurk/renderdoc#911]
I habitually use ctrl+left/right to move quickly between words in text editors, including while editing shaders in RenderDoc pre-1.0. It seems that in 1.0, ctrl+left/right will actually change to the next/previous draw call.

At the same time, ctrl+up/down do the typical text editing "move view up/down a line", which is correct.

**Comment by rlabrecque** [comment]
How do you want to solve this @baldurk ? The key problem ends up being that ctrl+left/right are already bound. Do you want to change them completely or make this context specific (😕)?

**Comment by baldurk** [comment]
Yes, I'll suppress the shortcut when in a text editing control.

**Comment by baldurk** [comment]
As mentioned in the previous comment, I've suppressed the global shortcuts while the focus is on a text editing type control.
