### ISSUE TITLE
Report build error. (with Release of VS2017)

### ISSUE THREAD

**Issue by Jinten** [baldurk/renderdoc#915]
## Description
Hello, I will create a new issue for the first time. :)
I'm sorry that my English is not very good. it may be difficult to read... X(

Report build error. (Windows10 , VS2017, Release build)
The following files and code, the warning is handled as an error.
・iomapper.cpp (CP932)
・gl_program_iterate.cpp(865) not used Name array variable.
・bitstream.h (CP932)
・CaseConvert.h (CP932)

How to fix it locally.
・overrite save CP932 with UTF-8 BOM.
・remove not used "Name" array variable code.

I'm sorry if I made a mistake report...
I support the development! :)

## Repro steps
when trying to build with Release of VS2017.

## Environment
RenderDoc build v1.0
VS2017 (platform tool set v141)
Windows10

**Comment by baldurk** [comment]
I think this should now be fixed.

I also reported bugs to the other projects, for the CP932 problems in their files. In all cases it's easy to change back to just ASCII.
