### ISSUE TITLE
Crash in DXBCFile::DXBCFile expanding resource arrays

### ISSUE THREAD

**Issue by Ghost-yc** [baldurk/renderdoc#919]
when use renderdoc perf my application renderdoc crash in dxbc_inspect.cpp line 692 after captured , I think is vector iterator is invalid. 
attach callstack and code :
![image](https://user-images.githubusercontent.com/8528210/37392412-0b682db8-27a9-11e8-8e7e-9329f70f05ee.png)
![image](https://user-images.githubusercontent.com/8528210/37392446-2a33296e-27a9-11e8-9428-85a38415f522.png)
![image](https://user-images.githubusercontent.com/8528210/37392455-31c373e6-27a9-11e8-9910-8e46f7a1fe35.png)

**Comment by baldurk** [comment]
Thanks for reporting this. I'll need to be able to reproduce it to debug it directly. Are you able to share the capture with me, or even just the individual shader if you can extract it?

**Comment by Ghost-yc** [comment]
here is crash shader 
[dumpshader.zip](https://github.com/baldurk/renderdoc/files/1813784/dumpshader.zip)

**Comment by baldurk** [comment]
Thanks for uploading that. Unfortunately the shader seems to be truncated - the header says it should be 1046528 bytes long, but the zipped file is only 4098 bytes.

**Comment by Ghost-yc** [comment]
the crash shader zipped  file is dump memory from ByteCode and ByteCodeLength params of DXBCFile::DXBCFile function, here's uploaded full rdc file link. 
https://github.com/Ghost-yc/storefile/raw/master/crashshader.7z

**Comment by baldurk** [comment]
Thank you very much! I think if you were getting the shader from a minidump, it did not have all the data - minidumps only save a small amount of active memory.

With the capture you shared, I was able to find the problem and fix it. I also found a different problem where a resource name such as `<SceneMap>` would not be rendered correctly as the code incorrectly treated it as HTML tags.
