### ISSUE TITLE
Applications using MediaFoundation.MediaEngine crashes when started from RenderDoc

### ISSUE THREAD

**Issue by xenux** [baldurk/renderdoc#922]
## Description

Applications using the MediaFoundation.MediaEngine crashes when started with RenderDoc which make it impossible to analyse/debug. No error is displayed the application just suddenly crashes.
It seems that the issues happens as soon as we set the MediaEngine source video.

## Repro steps

You can easily reproduce the problem using the SharpDX video sample here:

https://github.com/sharpdx/SharpDX-Samples/tree/master/Desktop/MediaFoundation/MediaEngineAppVideo

Application runs fine when started out of RenderDoc but crashes as soon as the Source is set when started from RenderDoc.

## Environment

* RenderDoc build: v1.0, built from 5ef2d0bb
* Operating System:  Windows 10 Pro
* API: D3D11 lvl 11
* SharpDX version: 3.0.2 (but probably doesn't matter)
* CPU: Interl Xeon CPU E5-1620 64bits
* GPU: NVidia GeForce GTX 1070  
* GPU driver: 3.13.1.24
* Video File format: mp4 / 4:2:0 YUV
* video file codec: H264 MPEG-4 AVC / MPEG AAC audio

**Comment by baldurk** [comment]
I've looked at this and it looks like a **_huge_** pile of work to support properly. There's a whole bunch of special D3D11 interfaces for video decoding that aren't hooked, and I presume one of them is not being wrapped which leads to a crash eventually. On top of that it uses the video DXGI formats which aren't currently supported.

Are you looking to actually investigate and debug the video-related rendering, or would it be enough if it just didn't crash (but didn't capture/replay properly) and you could debug other non-video-related rendering?

**Comment by xenux** [comment]
Hi, thank you for taking the time to investigate.

I actually currently don't need (want) to investigate or debug video-related rendering. The problem is that my application contains a lot of video rendering and disabling all the video playbacks and recompiling the application every time I want to debug not-video related rendering is very time consuming. 

It would help me a lot if the application could play without crashing and I could still debug not-video related component of my application.

Also as a temporary workaround I would also be interested to know if there is a way to know from the application side if it has been launched from renderdoc or not. If there is a way to know, I could automatically disable all video playback in the engine when I detect that the application has been started from renderdoc to prevent the crash.

Thanks.

**Comment by baldurk** [comment]
OK I can look at how complex it would be to at least do a pass-through wrapper that will at least let you work.

In the meantime, the easiest way to detect renderdoc is just to look and see if `renderdoc.dll` is loaded, using `GetModuleHandle` or similar - if the dll is loaded, you can assume that you're running through renderdoc.

**Comment by baldurk** [comment]
As mentioned in that commit, I now have pass-through wrapping of the D3D11 video interfaces which should fix the crashes using MediaFoundation that's built on top of it. I added a [test program](https://github.com/baldurk/renderdoc/blob/v1.x/util/test/demos/d3d11/d3d11_video_textures.cpp) that uses MediaFoundation in the same way as SharpDX does and it works, as well as the SharpDX sample itself.

I haven't yet implemented display of video/YUV textures but that will follow shortly and on D3D11 is not fatal - they will just show up as black.

**Comment by evodabas** [comment]
Just wanted to chime in and say this fix is awesome! 😍 We've been never been able to use RenderDoc with our volumetric video plugin and I was just thinking about writing up a feature request for it today... only to find it's already done!
