### ISSUE TITLE
ShaderResource::resType is incorrect for combinedImageSampler defined in Vulkan GLSL

### ISSUE THREAD

**Issue by guwangfeng** [baldurk/renderdoc#923]
When I  built a tool upon renderdoc replay functionality, I found renderdoc returns incorrect  ShaderResource::resType. For example, I defined a sampler3D variable in Vulkan GLSL shader source:

layout(set = 0, binding = 0) uniform sampler3D samp;

But I got ShaderResource::resType = Texture2D.

After debugging, it caused by that in spv::MakeReflection, the variable "res", whose type is ShaderResource, comes from the variable "type", whose type is SpvDataType*. type.texdim is Dim2D, while type.baseType.texdim is Dim3D. So I think there is a bug here to get correct resType for CombinedImageSampler? That is, type.baseType, rather than type.type should be used?

**Comment by baldurk** [comment]
Closed this in exactly the way you described, using the image that makes up the sampled image, instead of the sampled image itself (which didn't have the right properties).
