### ISSUE TITLE
Crash opening some Vulkan frame dumps (1.0, sample framedump included)

### ISSUE THREAD

**Issue by hrydgard** [baldurk/renderdoc#925]
## Description

When loading some frame dumps of my emulator PPSSPP, RenderDoc crashes immediately.

## Repro steps

Load the following dump in RenderDoc: http://www.ppsspp.org/unofficial/godofwar.rdc

## Environment

* RenderDoc build: 1.0
* Operating System: Windows 10
* API: Vulkan
* Geforce driver: 391.01

**Comment by baldurk** [comment]
The capture you posted was captured on a GTX 770, and the closest hardware I have is a GTX 970 which is unfortunately not compatible (running on a similar driver, 391.35, I get different memory requirements on load which break it.

Are you able to capture on different hardware? Or else could you email me so we can see if I can find some other way to repro the problem?

**Comment by hrydgard** [comment]
I'll try to get a capture on Geforce 940MX shortly.

**Comment by hrydgard** [comment]
Caught one on the 940MX that crashes.

http://ppsspp.org/unofficial/godofwar_940mx.rdc
