### ISSUE TITLE
Crash when debugging a Vulkan application

### ISSUE THREAD

**Issue by DethRaid** [baldurk/renderdoc#928]
## Description

The Nova Renderer, the renderer I'm developing, crashes when run through RenderDoc. It does not crash when run without RenderDoc.

Based on the debugging I've done, the crash seems to happen when I call `vkUpdateDescriptorSet` on the second frame. There's a possibility that this happens after there's meshes loaded and that there's just no meshes loaded the first frame, but I haven't dug that far (yet)

With validation enabled in the RenderDoc setting (default in my settings file) the crash comes from `VkLayer_core_validation.dll+0x188fb4`, without the validation enabled the crash is at `renderdoc.dll+0x6eaaa0`

## Repro steps

1. Download the Nova Renderer from https://github.com/NovaMods/nova-renderer/tree/vulkan. Be sure to download the `vulkan` branch
2. Ensure you have your environment set up. You need CMake in your path. If you want to use Visual Studio you should run all command line commands from the Visual Studio Developer Command Prompt. If you prefer to use GCC you should install MinGW w64 and set your `PATH` to point to the directory where `gcc` is. You'll also want Java 8+, with `JAVA_HOME` set properly, and you'll need to run Minecraft 1.10 at least once (NOT 1.10.2 or anything)
3. Run `./gradlew setup` from your favorite command line. This will take a while, as it downloads the Mod Coder Pack and decompiles the Minecraft jar that you downloaded when you ran Minecraft 1.10. It will also clone all the dependencies of Nova from GitHub
4. Run `./gradlew build buildDll` to compile Nova. This will take some time since it compiles `shaderc` and `glfw` and all my other dependencies
5. To run Nova normally, run `./gradlew reRunNova`. This will launch Nova. You should see a window with a black area inside of it. The console will log things about updating descriptor sets for GUI objects
6. To observe the bug, run Nova though RenderDoc. I've provided a file with my RenderDoc settings in the root of the Nova Renderer repo. You'll need to change the executable path and working directory for your machine - executable path should point to your `java.exe`, while the working directory should point to the `jars` folder inside your clone of the Nova Renderer repo. Launch Nova through RenderDoc and wait a bit. It'll load some resources, including the textures from Minecraft (this takes most of the time), then crash

Nova logs a few things. You'll find the application logs in the `jars/logs` folder in your local Nova clone. `all.log` is the log of info-level events and above from my C++ code, `debug.log` is debug and trace log events from my C++ code, `latest.log` is all the logging from Minecraft and the Java part of Nova, and `myeasylogging.log` is the log from `easylogging++` loading my logging configuration file. There's also a crash log, which exists in the `jars` directory. Look for `hs_error_pid${pid}.log` where ${pid} is the process ID of Nova when you ran it from RenderDoc. This is the JVM crash log, but it gives the location of the crash. 

## Environment

* RenderDoc build: v1.0
* Windows 10 64 bit
* Vulkan 1.0
* LunarG Vulkan Loader 1.1.70
* Nvidia GTX 1080
* Nvidia driver 391.24
* Java 1.8.0_121
* gcc.exe (x86_64-posix-seh-rev1, Built by MinGW-W64 project) 7.2.0
* Intel i7-6700

**Comment by DethRaid** [comment]
I'm done some more debugging and learned some more thing.

I've been traveling this week, and I took my Solus Linux laptop with an Intel integrate GPU with me. The validation layers started yelling at me about having an invalid buffer ID when I specified the buffer to bind to my descriptor sets. Turns out I was accidentally deleting my buffer because it was wrapped in a class that deleted the buffer in the destructor, and I was using a temporary object to initialize my variable.

My program crashed when not run through RenderDoc, and the crash log said there was a sedfault in the validation layer. I'm going to leave this issue open because it happens in RenderDoc when the validation layer is turned off, but I'm also going to open an issue against the validation layer

**Comment by DethRaid** [comment]
To summarize: The issue is that RenderDoc crashes when I call `vkUpdateDescriptorSet` where the `VkBuffer buffer` parameter of the `VkDescriptorBufferInfo* pbufferInfo` of the `VkWriteDescriptorSet` parameter to `vkUpdateDescriptorSet` is not a valid `VkBuffer` id

**Comment by baldurk** [comment]
Thanks for the investigation. This is then not something I'd expect RenderDoc to handle. For obvious reasons I don't want to duplicate all of the work that the validation layers do inside RenderDoc to detect & handle invalid API use, so generally RenderDoc has the same kind of validity expectations as a driver. 

Instead the tool is useful when the code is technically valid but not doing what you want anyway :smile:.
