### ISSUE TITLE
VK_KHR_descriptor_update_template not supported

### ISSUE THREAD

**Issue by doitsujin** [baldurk/renderdoc#934]
## Description

See title. `VK_KHR_descriptor_update_template` is now [required](https://github.com/doitsujin/dxvk/commit/94aa650f3e250b79b449bb2f8b058e4ce7e11983) by DXVK and it's part of the 1.1 core specification, so it would be nice to have support for it in RenderDoc as well.

## Environment

* RenderDoc build: v1.0
* Operating System: Arch Linux
* API: Vulkan

**Comment by baldurk** [comment]
This should now be supported - I wasn't set up to test DXVK but I did find another program that used update templates and the capture/replay worked correctly there.

Please let me know if you run into any problems with the latest code.
