### ISSUE TITLE
Don't see android device listed.

### ISSUE THREAD

**Issue by 2015winter** [baldurk/renderdoc#936]
## Description

I don't see android device listed with replay context displaying only local, and adb has connected the android ip, please give an instruction to connect the android device, thanks.

## Repro steps

I have only connected the android ip by adb, and I don't know the renderdoc app how to scan the android device mechanism.
## Environment

* RenderDoc build:v1.0
* Operating System:  Windows 10，Android OS 8.0
* API: OpenGL ES 2.0.

**Comment by baldurk** [comment]
Can you print the output of running `adb devices -l` on your machine? That's the command renderdoc uses to list the available android devices.

**Comment by 2015winter** [comment]
C:\Program Files\RenderDoc\plugins\android>adb devices -l
List of devices attached
10.1.8.107:5555        device product:angler model:Nexus_6P device:angler transport_id:3

**Comment by baldurk** [comment]
Sorry for the delayed response. I don't understand this output, we look for something along the lines of:

```
List of devices attached
HT74T0200775           device product:marlin model:Pixel_XL device:marlin
```

And then construct a device string using that first identifier, which isn't expected to be an IP with a port.

@cnorthrop @michaelrgb can you shed any light on this? This seems to be some new adb output and I don't know if we just need to update our parsing or if there's something very different going on here.

**Comment by cnorthrop** [comment]
We don't support ADB over TCPIP yet.  Are you able to connect your devices directly with USB?

**Comment by 2015winter** [comment]
Well, my device is indeed connected by adb over tcpip in this case, and  I try to connect my device directly with USB again, and the message is:
C:\Program Files\RenderDoc\plugins\android>adb devices -l
List of devices attached
ENU7N15B12012203       device product:angler model:Nexus_6P device:angler transport_id:1

**Comment by baldurk** [comment]
OK I'm not sure I understand what adb over tcpip entails exactly, but the output of `adb devices` looks more as I'd expect - with the USB connection does renderdoc work? What happens now?

**Comment by 2015winter** [comment]
The drop-down of Replay Context has only the "Local" option when I start up, with I have try waiting a few seconds, but not get other option.

**Comment by baldurk** [comment]
Can you try `adb devices` without the `-l`? That's what the code is actually running now that I look, maybe the format there is different. It should output just `ENU7N15B12012203 device`.

**Comment by 2015winter** [comment]
yeah, now i try `adb devices` without the `-l`, and as you say, it has output just `ENU7N15B12012203 device`, and the connect is correct now. thanks for your hep.
