### ISSUE TITLE
Request for support for Intel Metrics Framework SDK..

### ISSUE THREAD

**Issue by oscarbg** [baldurk/renderdoc#938]
Hi,
now seeing preliminary NV Perfkit integration (sad new perfworks SDK is not released openly at least)
I thought I had asked that before but I can't seemd to find it so as seems now Intel iGPU are the only ones missing some counters integration asking for integration..
seems freely downloadable from:
https://software.intel.com/en-us/form/intel-platform-analysis-library-request
and selecting Intel Metrics..

**Comment by baldurk** [comment]
As I try to reinforce, RenderDoc is still primarily designed as a debugger, not a profiler. The integration of IHV counter libraries has come from others so this is not something I will address myself directly. It may be something that someone else contributes.

On another note, I've noticed that you request a lot of widely disparate features, and I'd like to understand which of these are critical for what you're working on. Requesting features is of course welcome, but having a lot of feature requests does add a burden on myself and anyone else looking to contribute. It also makes it harder to prioritise against features that others are directly wanting.

**Comment by oscarbg** [comment]
Hi,
really I'm no profesional need for this feature, just for some testing purposes I would like to avoid having to install Intel GPA that's all..
so feel free to not give any priority..
just leave me to point out (in case someone wants to implement) that an integration into UE4 has been made supporting DX11 and DX12 counters altough not merged in master:
can be found on https://wiki.unrealengine.com/GitHub_Sharing_Hub:
see "Intel Hardware Metrics for DX11/12"
pull: "Intel hardware metrics for DX11 and DX12 via stat command "
https://github.com/EpicGames/UnrealEngine/pull/2544/commits/50f3d2df8c233eb036e2857fd230ef80e614536f

**Comment by oscarbg** [comment]
News!
"We just open sourced our GPU metrics discovery API (used by GPA/Vtune) :) Soon Intel metrics in @RenderDoc too !"
https://twitter.com/acohade1/status/986985251959377920

**Comment by baldurk** [comment]
Intel merged their metrics API in with #1112.
