### ISSUE TITLE
Can't debug UE4 android app

### ISSUE THREAD

**Issue by monops** [baldurk/renderdoc#941]
Hello :)

I'm having some issues with debugging a UE4 android app. Here are my info:
The tick "For Distribution" is not flagged
I see my device in "adb devices"

The output to `adb shell cmd package resolve-activity -c android.intent.category.LAUNCHER com.MYCOMPANY.MYAPP` 
is:
```
priority=0 preferredOrder=0 match=0x108000 specificIndex=-1 isDefault=false
ActivityInfo:
  name=com.epicgames.ue4.GameActivity
  packageName=com.MYCOMPANY.MYAPP
  labelRes=0x7f060054 nonLocalizedLabel=null icon=0x0 banner=0x0
  enabled=true exported=true directBootAware=false
  taskAffinity=com.MYCOMPANY.MYAPP targetActivity=null persistableMode=PERSIST_ROOT_ONLY
  launchMode=2 flags=0x3 theme=0x7f080009
  screenOrientation=0 configChanges=0x4b0 softInputMode=0x0
  lockTaskLaunchMode=LOCK_TASK_LAUNCH_MODE_DEFAULT
  resizeMode=RESIZE_MODE_UNRESIZEABLE
  requestedVrComponent=com.google.vr.vrcore/com.google.vr.vrcore.common.VrCoreListenerService
  ApplicationInfo:
    packageName=com.MYCOMPANY.MYAPP
    labelRes=0x7f060054 nonLocalizedLabel=null icon=0x7f02002f banner=0x0
    processName=com.MYCOMPANY.MYAPP
    taskAffinity=com.MYCOMPANY.MYAPP
    uid=10134 flags=0x3 privateFlags=0x0 theme=0x0
    requiresSmallestWidthDp=0 compatibleWidthLimitDp=0 largestWidthLimitDp=0
    sourceDir=/data/app/com.MYCOMPANY.MYAPP-1/base.apk
    seinfo=default
    dataDir=/data/user/0/com.MYCOMPANY.MYAPP
    deviceProtectedDataDir=/data/user_de/0/com.MYCOMPANY.MYAPP
    credentialProtectedDataDir=/data/user/0/com.MYCOMPANY.MYAPP
    enabled=true minSdkVersion=24 targetSdkVersion=24 versionCode=1
    supportsRtl=false
    fullBackupContent=true
```

And the output gives me this error: `Couldn't make JDWP connection`
I'm including the whole log (it's not horribly long :) )
My device runs android 7.1 and I'm using UE4.16.
I'm using RenderDoc 1.0

Hope you can help me :)

[RenderDoc_2018.04.04_09.40.33.log](https://github.com/baldurk/renderdoc/files/1874943/RenderDoc_2018.04.04_09.40.33.log)

**Comment by baldurk** [comment]
I think this might be an issue that I've seen before. Can you run `adb shell ps -A` manually on a command line, and see what output you get? My guess is that it will print an error message, because some android devices seemingly have a `ps` that doesn't support the argument.

If that's the case, can you try again using a recent RenderDoc nightly build, as I put in a fix a little while ago that tries multiple ways of invoking `ps` to try and get something that works.

**Comment by monops** [comment]
Thanks!
I tried the latest nightly build and I could connect the app to RenderDoc.
I still can't do any capture though: when clicking the "Trigger after delay" button (with 0 or more seconds) it does nothing.
I'm adding the log, maybe it helps :)

[RenderDoc_2018.04.04_15.17.26.log](https://github.com/baldurk/renderdoc/files/1876268/RenderDoc_2018.04.04_15.17.26.log)

**Comment by trs-jimmy-lee** [comment]
Hi I think I know what this problem is. Android window selection is not implemented yet at the moment, so if your first "window" created is not the UE4's render context, then renderdoc won't have an active context to capture from.

On our internal fork, I have added RenderDoc::Inst().SetActiveWindow in vrapi_SubmitFrame (for gearvr) to force select the active window. If you do this in either the hook for eglSwapBuffers or manually inside UE4 before the call to eglSwapBuffers inside AndroidEGL::SwapBuffers then you should be able to do a capture for normal AndroidEGL.

**Comment by monops** [comment]
I don't have much experience with the renderdoc source code :(
I tried to add RenderDoc::Inst().SetActiveWindow in eglSwapBuffers in the file gl_hooks_egl.cpp, but that is excluded from the build.

Do you know where I should add it?

**Comment by baldurk** [comment]
I'm not clear on exactly the problem but I think @trs-jimmy-lee is referring to the change in #945 here.

**Comment by rokups** [comment]
Seems like i am hit with the same issue. Not using UE4. My device indeed does not support `ps -A`. I tried nightly but it also fails to debug the process. Renderdoc throws "Error connecting to debugger" like a second before phone shows "Waiting for debugger" popup. Setting debugger delay to anything does not have any effect.

**Comment by baldurk** [comment]
@rokups Can you post the diagnostic log from help -> view diagnostic log? That should provide more info about what's going wrong exactly.

**Comment by rokups** [comment]
[RenderDoc_2018.04.06_18.05.05.log](https://github.com/baldurk/renderdoc/files/1884547/RenderDoc_2018.04.06_18.05.05.log)

**Comment by baldurk** [comment]
It seems like this is a different issue to me, @monops is able to connect with the latest nightly but you're not able to make a debug connection at all - the debug connection is being refused.

Can you open a separate github issue for discussion as it doesn't look like something I've seen before? Also I'd be interested to know the output of `adb shell ps` and `adb jdwp` (you'll have to manually kill that second one after it's printed the output, as it seems like it never exits by default).

**Comment by monops** [comment]
Sorry for going silent: I'll be back with more info as soon as I've completed a task that's very important :)
At the moment I can use "Gapid" for this particular task, but I'd prefer to use RenderDoc, so I'll be back with more info.

**Comment by baldurk** [comment]
No worries! To keep you in the loop, @trs-jimmy-lee opened a new PR #947 that should hopefully be merged into the next nightly build, which might address your problem.

**Comment by baldurk** [comment]
I'm going to close this issue as I think the Android issues you were running into have been fixed on the latest v1.x branch. If when you next test you find that it's still not working then either comment back here or open a new issue with the details of the problem you're having.
