### ISSUE TITLE
Right-click to choose a triangle in the Mesh Output tab resets to instance 0

### ISSUE THREAD

**Issue by loosche** [baldurk/renderdoc#944]
## Description

When I try to select a triangle in an instanced mesh in the Mesh Output tab mesh viewer it changes my instance and vertex selection back to 0.

## Repro steps

1. Load a capture that has an instanced draw call (DrawIndexedInstanced) that draws multiple instances
2. Open the draw call in the Mesh Output Tab
3. Change to instance # n (can be any non-zero instance) using the "Instance" spin box at the top of the window (next to "Row Offset")
4. Select the mesh viewport 
5. Rotate around to find a triangle you like
6. Right Click on that triangle in the mesh viewport

Expected: A triangle from instance #n will be highlighted and show up in the VS Input buffer
Actual: The viewport resets the rotation and returns to showing instance #0 with the first vertex selected in the VS Input Buffer

## Environment

* RenderDoc build: Version v1.0 (built from 5ef2d0bb)
* Operating System: e.g. Windows 10
* API: D3D11

NVidia 1080 GTX
Driver Version 388.31

**Comment by baldurk** [comment]
This was the code misfiring which is intended to select the right instance on the output pane. I've fixed it now so it won't interfere on the input pane, thanks!
