### ISSUE TITLE
Problems with GL texture unpack state not being applied

### ISSUE THREAD

**Issue by cgmb** [baldurk/renderdoc#952]
## Description

I was debugging a texture that wasn't displaying correctly in my program, but was quite confused when the scene appeared to be correct in the RenderDoc Texture Viewer. It looked right in both the texture inputs and backbuffer output.

## Repro steps

* Load a texture using incorrect values for `GL_UNPACK_ROW_LENGTH` and `GL_UNPACK_ALIGNMENT`
* Inspect the texture with the RenderDoc Texture Viewer

If you would like an example program, I can send you one.

## Environment

* RenderDoc build: b88d6eaf86cf1c2456c204b800b8f4a497a4f83b
* Operating System: Ubuntu 16.04
* API: OpenGL
* GPU: Intel Iris Pro (Haswell)

**Comment by baldurk** [comment]
If you are able to share an example program then yes please do, since this is GL there are dozens of ways you can upload texture data and not all of them may exhibit the bug, so narrowing it down will be quicker if you can share a repro.

**Comment by baldurk** [comment]
Thanks for sharing the repro - this was a misreading of some spec text on my part (mentally substituted bits for bytes), when it essentially says that any formats that don't have components which are byte-multiples are treated as tightly packed. That meant I wasn't applying the alignment to a 3-component RGB texture, which is why the bug you were looking at was hidden.

**Comment by cgmb** [comment]
Thank you very much for the fix. I was reminded to report this bug because I was watching a couple of teaching assistants preparing a tutorial class on textures in OpenGL for the "Intro to Computer Graphics" course. Part of that was teaching students to use RenderDoc to debug their program when things weren't working as they expected.

Back when I was taking that course, the way you debugged your program was by dropping `glGetError` statements everywhere, double-checking every new API call against the documentation, and begging the TA to look over your code. The development of tools like ApiTrace and RenderDoc has had a small but noticeable impact on how the practical side of computer graphics is taught, and the change has been entirely for the better.
