### ISSUE TITLE
VKPipe::BindingElement::viewFormat is incorrect for uniform texel buffer and storage texel buffer.

### ISSUE THREAD

**Issue by guwangfeng** [baldurk/renderdoc#957]
Hi,

VKPipe::BindingElement::viewFormat for uniform texel buffer and storage texel buffer is always ResourceFormatType::Undefined. I found that in SavePipelineState, viewFormat is only set when 

            if(layoutBind.descriptorType == VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE ||
               layoutBind.descriptorType == VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER ||
               layoutBind.descriptorType == VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT ||
               layoutBind.descriptorType == VK_DESCRIPTOR_TYPE_STORAGE_IMAGE)
    {
         ...
         viewFormat = ...
         ...
    }

So seems we need to set viewFormat to correct value for uniform texel buffer and storage texel buffer too?

**Comment by baldurk** [comment]
Thanks for pointing this out, indeed the format of the texel buffer view should have been passed through. With that commit it should be available and displayed in the pipeline state viewer.
