### ISSUE TITLE
Renderdoc UE4 integration: fails to find renderdoc.dll on command-line cooked builds and fails the build when renderdoc is not installed.

### ISSUE THREAD

**Issue by pbronowski** [baldurk/renderdoc#961]
## Repro steps

- Do NOT install renderdoc app/bins (.msi file), or have it available locally.

- Enable RenderDoc in your Unreal .uproject settings

- Run a UAT commandline build like (ex: replace with your config params)...

!_UnrealRoot!Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project=!_ProjectFile! -noP4 -platform=!_BuildTarget! -clientconfig=!_BuildConfiguration! -serverconfig=!_BuildConfiguration! -cook -maps=AllMaps -nocompile -stage -pak -archive -archivedirectory=!_AppLayoutRoot!

- Engine\Plugins\Developer\RenderDocPlugin\Binaries\Win64\UE4Editor-RenderDocPlugin.dll will fail to find renderdoc.dll and fail the build.

Relevant code...

Source\RenderDocPlugin\Private\RenderDocPluginLoader.cpp:       FString PathToRenderDocDLL = FPaths::Combine(*RenderdocPath, *FString("renderdoc.dll"));
Source\RenderDocPlugin\Private\RenderDocPluginLoader.cpp:               UE_LOG(RenderDocPlugin, Warning, TEXT("unable to obtain 'RENDERDOC_GetAPI' function from 'renderdoc.dll'. You are likely using an incompatible version of RenderDoc."), *PathToRenderDocDLL);
Source\RenderDocPlugin\Private\RenderDocPluginLoader.cpp:       // Look for a renderdoc.dll somewhere in the system:
Source\RenderDocPlugin\Private\RenderDocPluginLoader.cpp:       UE_LOG(RenderDocPlugin, Log, TEXT("locating RenderDoc library (renderdoc.dll)..."));
Source\RenderDocPlugin\Private\RenderDocPluginLoader.cpp:       FString PathToRenderDocDLL = FPaths::Combine(*CVarRenderDocBinaryPath.GetValueOnAnyThread(), *FString("renderdoc.dll"));

## Environment

* RenderDoc build: v1.0
* Operating System: Windows 10
* API: D3D11, D3D12

**Comment by baldurk** [comment]
I'm not sure I understand, if you're saying you don't have RenderDoc installed at all then isn't this a UE4 bug?

**Comment by pbronowski** [comment]
Depends. Who owns the RenderDoc UE4 plugin code? Unreal or RenderDoc? - thanks

**Comment by baldurk** [comment]
Either Epic or else [Temaran/UE4RenderDocPlugin](https://github.com/Temaran/UE4RenderDocPlugin) - I'm not sure how it works since it was integrated into the main engine upstream.

All I do is provide the API that's used to control renderdoc within a process, anything else is up to whoever writes that integration, this repository is only for the tool itself.
