### ISSUE TITLE
Problems with JDWP connection

### ISSUE THREAD

**Issue by FelixK15** [baldurk/renderdoc#962]
## Description

I've tried connecting render doc to an Android Device (specifically, Samsung Galaxy Tab S3). Android 7.0 is installed on that device.

The renderdoc apk was installed correctly and starts up properly when selecting the device as a replay context.

However, after I select the apk that I want to debug in the 'Executable Path' box and hit 'Launch', it would say that it couldn't connect to the debugger ('debuggable' is set to true in the AndroidManifest).
There's no other application running that makes use of the adb other than RenderDoc.

To see what was causing this, I opened the Diagnostic Log File using the 'Help->View Diagnostic Log File' option.

When I was searching for potential errors, this line struck my interest:

>RDOC 000320: [15:31:38]             jdwp.cpp( 399) - Error   - Couldn't make JDWP connection
RDOC 000320: [15:31:38]          android.cpp( 217) - Error   - Failed to inject using JDWP

Could you maybe tell me what would cause this error? 

Something to note:
I tried the same procedure with an Samsung Galaxy S8 device and everything worked fine so this seems to be an Android or device specific setting.

If you need more informations, please don't hesitate to contact me.

The content of the whole log file:

>RDOC 000320: [15:31:10]             core.cpp( 298) - Log     - RenderDoc v1.0 64-bit Release (5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c) loaded in replay application
RDOC 010120: [15:31:10]             core.cpp( 298) - Log     - RenderDoc v1.0 64-bit Release (5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c) loaded in replay application
QTRD 000320: [15:31:10]       qrenderdoc.cpp(  87) - Log     - QRenderDoc initialising.
RDOC 007420: [15:31:10]             core.cpp( 298) - Log     - RenderDoc v1.0 64-bit Release (5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c) loaded in replay application
QTRD 000320: [15:31:12] ToolWindowManager.cpp( 817) - Warning - invalid splitter encountered
RDOC 000320: [15:31:12]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e forward tcp:39970 localabstract:renderdoc_39920'
RDOC 000320: [15:31:12]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e forward tcp:38970 localabstract:renderdoc_38920'
RDOC 000320: [15:31:12]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell getprop ro.product.manufacturer'
RDOC 000320: [15:31:13]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell getprop ro.product.model'
RDOC 000320: [15:31:13]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell setprop debug.vulkan.layers :'
RDOC 000320: [15:31:16]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell setprop debug.vulkan.layers :'
RDOC 000320: [15:31:20]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e forward tcp:39970 localabstract:renderdoc_39920'
RDOC 000320: [15:31:20]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e forward tcp:38970 localabstract:renderdoc_38920'
RDOC 000320: [15:31:26]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell pm list packages -3'
RDOC 000320: [15:31:27]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e forward tcp:39970 localabstract:renderdoc_39920'
RDOC 000320: [15:31:27]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e forward tcp:38970 localabstract:renderdoc_38920'
RDOC 000320: [15:31:28]    android_patch.cpp( 497) - Log     - Checking that APK is debuggable
RDOC 000320: [15:31:28]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell dumpsys package com.flaregames.monsterio'
RDOC 000320: [15:31:28]    android_patch.cpp( 460) - Log     - Checking for root access on 6ec8ea1eb10f312e
RDOC 000320: [15:31:28]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e root'
RDOC 000320: [15:31:28]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell whoami'
RDOC 000320: [15:31:28]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell test -e /system/xbin/su && echo found'
RDOC 000320: [15:31:32]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell cmd package resolve-activity -c android.intent.category.LAUNCHER com.flaregames.monsterio'
RDOC 000320: [15:31:32]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e forward --remove tcp:39021'
RDOC 000320: [15:31:32]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell am force-stop com.flaregames.monsterio'
RDOC 000320: [15:31:33]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell setprop debug.vulkan.layers VK_LAYER_RENDERDOC_Capture'
RDOC 000320: [15:31:33]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell mkdir -p /sdcard/Android/data/com.flaregames.monsterio'
RDOC 000320: [15:31:33]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell setprop debug.rdoc.RENDERDOC_CAPTUREOPTS ababaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabcbaa'
RDOC 000320: [15:31:34]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell pm path com.flaregames.monsterio'
RDOC 000320: [15:31:34]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell ls /data/app/com.flaregames.monsterio-1//lib/*/libVkLayer_GLES_RenderDoc.so'
RDOC 000320: [15:31:34]          android.cpp( 173) - Log     - No library found in /data/app/com.flaregames.monsterio-1//lib/*/libVkLayer_GLES_RenderDoc.so for com.flaregames.monsterio - assuming injection is required.
RDOC 000320: [15:31:34]          android.cpp( 185) - Log     - Setting up to launch the application as a debugger to inject.
RDOC 000320: [15:31:34]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell am start -S -D com.flaregames.monsterio/com.keenflare.monsterio.MonsterioActivity'
RDOC 000320: [15:31:35]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e forward tcp:39970 localabstract:renderdoc_39920'
RDOC 000320: [15:31:35]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e forward tcp:38970 localabstract:renderdoc_38920'
RDOC 000320: [15:31:35]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell ps -A | grep com.flaregames.monsterio'
RDOC 000320: [15:31:36]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell ps -A | grep com.flaregames.monsterio'
RDOC 000320: [15:31:36]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell ps -A | grep com.flaregames.monsterio'
RDOC 000320: [15:31:36]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell ps -A | grep com.flaregames.monsterio'
RDOC 000320: [15:31:37]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e shell ps -A | grep com.flaregames.monsterio'
RDOC 000320: [15:31:37]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e forward tcp:39970 localabstract:renderdoc_39920'
RDOC 000320: [15:31:37]    android_tools.cpp( 283) - Log     - COMMAND: C:\Users\fklinge\AppData\Local\Android\Sdk\platform-tools\adb.exe '-s 6ec8ea1eb10f312e forward tcp:38970 localabstract:renderdoc_38920'
RDOC 000320: [15:31:38]             jdwp.cpp( 399) - Error   - Couldn't make JDWP connection
RDOC 000320: [15:31:38]          android.cpp( 217) - Error   - Failed to inject using JDWP

## Environment

* RenderDoc build: v1.0 (build from 5ef2d0bb)
* Operating System: Windows 7 64-Bit
* API: OpenGL ES 3.0
* Device: Samsung Galaxy Tab S3

**Comment by baldurk** [comment]
This looks like the bug that's been reported a couple of times where some android devices don't support `ps -A`, so renderdoc can't determine the PID of the apk and can't set up the JDWP connection from there.

Can you try a recent nightly build? This has been fixed and I now have a fallback that tries just plain `ps` as well.

**Comment by FelixK15** [comment]
Yup, that fixed it. Thanks a lot!
