### ISSUE TITLE
Tooltips for constant buffer values in shader debugger

### ISSUE THREAD

**Issue by PfhorSlayer** [baldurk/renderdoc#963]
It would be awesome if, in addition to the tooltips that already appear for the register values when you hover the mouse over them while debugging a shader, you could have a similar tooltip for constant buffer values referenced in shader instructions. As it is right now, you're forced to scroll to the correct value in the Constants & Resources panel.

Thanks!

**Comment by baldurk** [comment]
This should be the case now with the HLSL debugging improvements I merged in.
