### ISSUE TITLE
Shader register tooltip misalignment with large signed integer values

### ISSUE THREAD

**Issue by PfhorSlayer** [baldurk/renderdoc#964]
## Description

The signed integer display in the tooltip when hovering over a register value in the shader debugger is misaligned when displaying values that are negative and more than nine digits as a signed integer.

![image](https://user-images.githubusercontent.com/5573131/39070133-03396264-4497-11e8-9bc5-fff955a2e8e9.png)

## Repro steps

Hover over a register in the shader debugger that has a value that is negative and more than nine digits when represented as a signed integer.

## Environment

Version 1.0, built from 5ef2d0bb
Windows 10
D3D11

**Comment by baldurk** [comment]
Thanks for the report! Indeed I just made the simple fix of padding to one extra character to account for the sign character.
