### ISSUE TITLE
OpenGL Constant Buffers not bound to correct slot in RenderDoc 1.0 UI

### ISSUE THREAD

**Issue by JensRestemeier** [baldurk/renderdoc#965]
## Description

Constant buffers seem to be bound to the wrong slots in the pipeline view. The actual replay works fine, but the UI complains about the size of the bound buffers.

Broken view in 1.0:
![renderdoc_10](https://user-images.githubusercontent.com/2105225/39083835-530dd7da-4563-11e8-93ac-f12091523efa.PNG)

Working view in 0.92:
![renderdoc_092](https://user-images.githubusercontent.com/2105225/39083842-5fde3eaa-4563-11e8-9ad5-e20d2c215010.PNG)

I can provide captures if required.

## Repro steps

I guess you would need to capture an OpenGL project that uses constant buffers, but I don't know any. My project was just ported to Windows 10 to debug it with RenderDoc, so has plenty of other issues.

The bug shows in the official 1.0 release and the nightly build, it works fine in 0.92.

## Environment

* RenderDoc build: v1.0, RenderDoc_2018_04_20_10960259_64 nightly build and v0.92
* Operating System: Windows 10
* API: OpenGL

GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: AMD Radeon R9 200 Series
GL_VERSION: 3.3.13506 Core Profile Context 23.20.15017.3010
GL_SHADING_LANGUAGE_VERSION: 4.50

**Comment by baldurk** [comment]
With OpenGL's horrible binding model especially there are _tons_ of variables that could affect how this bug manifests, so a repro capture would be very helpful to track down the actual problem.

I did make a fix yesterday which would cause the re-sorting of binding points to go wrong if the application was dynamically setting uniforms. Could you try with the latest nightly build as well (the one you mentioned was from a month ago or so) and see if you see any difference?

**Comment by JensRestemeier** [comment]
Sorry, I updated the reference to the nightly build to the exact version I tried.
Here are the captures I made:
[RenderDoc_092.zip](https://github.com/baldurk/renderdoc/files/1934492/RenderDoc_092.zip)
[RenderDoc_10.zip](https://github.com/baldurk/renderdoc/files/1934493/RenderDoc_10.zip)

**Comment by baldurk** [comment]
Thanks!

**Comment by baldurk** [comment]
This should be fixed now, it was a problem with the dynamic re-sorting of bindings that I have to do on OpenGL only, to try and get sensible results out of the GL binding model. I only started doing that in 1.0 though.
