### ISSUE TITLE
Support latest d3d12 functions and interfaces

### ISSUE THREAD

**Issue by msiglreith** [baldurk/renderdoc#966]
Would be great if RenderDoc supports the most recent d3d12 interfaces (e.g ID3D12Device3).
RenderDoc seems to fail hooking up the the corresponding wrappers in case of usage of such interfaces on the latest master.

**Comment by baldurk** [comment]
That support should exist now, although I didn't have much in the way of sample code to test against so it may have bugs. Let me know if you find any problems.
