### ISSUE TITLE
Framebuffer drawcall usage is not present for vulkan secondary command buffers

### ISSUE THREAD

**Issue by aejsmith** [baldurk/renderdoc#975]
Currently, if you look at the "usage in frame" list (in the resource inspector, or by right clicking it in the texture viewer) of a render target or depth/stencil texture, it will not show events where the texture is part of the current framebuffer on Vulkan.

This makes it more difficult to see where a texture is rendered to - I can sometimes find this from barrier events which do get listed, but there aren't always barriers near every place where a texture is rendered to. It'd be very useful if usage as render target was shown in the list as it is for other uses.

**Comment by baldurk** [comment]
There [is code to do this](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/vulkan/vk_core.cpp#L3127-L3164):

![image](https://user-images.githubusercontent.com/661798/39520233-c7af9212-4e01-11e8-9040-abeff8b6f7ac.png)

So something must be going wrong in your case. Could you share a repro capture with me?

**Comment by aejsmith** [comment]
Interesting! That's never appeared for me. I think it should repro on the capture I sent you by email a few weeks ago.

**Comment by baldurk** [comment]
Oh, I think the problem is that your draws happen inside secondary command buffers. At draw record time I don't know what the current renderpass/framebuffer is so I can't record the usage information.

This will probably require some sort of patch-up pass at `vkCmdExecuteCommands` time.

**Comment by aejsmith** [comment]
Can you get them from the inheritance info passed to BeginCommandBuffer on the secondary if they were provided? We always set them at least. Wouldn't help when they haven't been set though.

**Comment by baldurk** [comment]
It's a fair point; at least you are guaranteed to get the renderpass, but as you point out the framebuffer is optional in the inheritance info which scuppers the idea if it's not specified.

It would be possible to implement a path that takes advantage of the data if present, but I don't think there'd be a significant load performance win vs. post-patching the draws at the time the command buffer is executed, so I'd rather not write two codepaths when adding only one will cover a superset of cases.

**Comment by baldurk** [comment]
This post-patching method worked for me on the capture you sent me before, let me know if you notice any other issues.

**Comment by aejsmith** [comment]
Yep, that works, thanks!
