### ISSUE TITLE
SPIR-V 1.3 support

### ISSUE THREAD

**Issue by LDeakin** [baldurk/renderdoc#976]
## Description
Currently SPIR-V 1.3 shaders are not handled as the version of glslang in this repository is not recent. This causes a number of problems such as resource use not being detected.
https://github.com/baldurk/renderdoc/blob/e96f290772b2dcb516bd738f6b588cec61726456/renderdoc/driver/shaders/spirv/spirv_disassemble.cpp#L4581-L4585
Everything works as expected if I comment out this check for my use...
I guess you may want to update the glslang dependency instead and properly support 1.3?

## Repro steps
I've attached captures which use SPIR-V 1.0/1.3 shaders. [rdoc_spirv_1_3.zip](https://github.com/baldurk/renderdoc/files/1976601/rdoc_spirv_1_3.zip) (30 KB)
The output of the dispatch (EID 10) is not detected in `spirv_1_3.rdc`.

## Environment
* RenderDoc build: commit e96f29077 (latest v1.x)
* API: Vulkan

P.S. Thanks for developing RenderDoc 👍

**Comment by baldurk** [comment]
Thanks for pointing this out, I actually forgot that Vulkan 1.1 now allows SPIR-V 1.3. I wonder if I should expose the allowed SPIR-V versions based on the vulkan capture version, or just support up to 1.3 unconditionally even if the user is using Vulkan 1.0.

One question - you mention updating glslang, was there something else that was broken with SPIR-V 1.3? It's not a bad idea to update it honestly (I'll need to check it as I know the dependencies have grown more complex), but the code you linked to is my internal SPIR-V processing/reflection so it wouldn't be affected by glslang.

**Comment by LDeakin** [comment]
There wasn't anything else broken that I noticed. I think you can get away with not updating glslang.

**Comment by baldurk** [comment]
That commit updated glslang anyway (and I was using glslang's copy of the SPIR-V headers), and at the same time I accepted up to 1.3.

Looking at the spec it seems like the disassembly might be a bit broken but the reflection should be fine with 1.3.
