### ISSUE TITLE
OpenGL texture uniform slot name is wrong

### ISSUE THREAD

**Issue by fteppe** [baldurk/renderdoc#980]
## Description

Hello,
I have a bug when I look at my textures in my fragment shader stage I have a weird issue where the textures are the good one, but the name next to the slot is not the name of the uniform it is bound to.

## Repro steps

![image](https://user-images.githubusercontent.com/16321628/39756214-f85ea878-52c8-11e8-9d3c-efcda3479885.png)
So these are the slots as you can see them in RenderDoc, the uniforms exist in the shader, but the textures are mixed up. It should be :
color
depth
fragpos
...

The order displayed is the order I bound the textures in.
So the shader works find and the depth texture is bound to depth and the color is bound to color. But for some reason, in renderDoc it is not displayed properly.

These are the steps I followed, so the slot correponds to the binding order, but the names are wrong:
![image](https://user-images.githubusercontent.com/16321628/39756617-8bd127d8-52ca-11e8-9c27-f0d8a934fc89.png)

because they are the same as in my map in my code which is the following order:
![image](https://user-images.githubusercontent.com/16321628/39756586-773b2c24-52ca-11e8-8833-2f200a9ae44f.png)

The textures are also outputs of a framebuffer in a previous pass. And other objects don't have the same issue. It isn't a big issue but because of it for a while I thought the textures were wrong even though I tested by displaying them in my application and they are right.

## Environment

* RenderDoc build:  v1.0
* Operating System:  Windows 10
* API:  OpenGL,
 I use an intel HD 620 driver 21.20.16.4627

**Comment by baldurk** [comment]
Hi, can you test with the most recent nightly build? there have been a few fixes for this issue since v1.0 was released and it might be that it works now for you.

If it's still not working on the latest nightly, I'd either need some repro details like the application to capture or a .rdc file that exhibits the problem, or else I'd need you to run debugging builds to help narrow down what the problem is.

**Comment by fteppe** [comment]
It seems to be fixed on the nightly build, thanks a lot.
