### ISSUE TITLE
Shader edit not working for Vulkan SPIR-V

### ISSUE THREAD

**Issue by BNieuwenhuizen** [baldurk/renderdoc#985]
In the process of debugging some game I'd like to edit the vertex cshader of a Vulkan program to see if I can simplify the issue or find a clue as to the nature of the issue.

So if I go to the Pipeline State tab for the draw and go to VS, and press "Edit" I get a new tab with title "EditedShaderVS - Edit (generated.glsl)" and a bunch of SPIR-V disassembly from what looks like spirv-dis.

However, if I press Refresh I get:

    Shader failed to compile:

    ERROR: #version: Desktop shaders for Vulkan SPIR-V require version 140 or higher
    ERROR: 0:1: 'extraneous semicolon' : not supported for this version or the enabled extensions 
    ERROR: 2 compilation errors.  No code generated.

Looks like it expects GLSL.

My renderdoc version is 

commit e40ca6f59dc1d07cd5da230c0f1170473b496e90 (HEAD -> makepkg, origin/v1.x)
Author: baldurk <baldurk@baldurk.org>
Date:   Fri May 11 13:08:32 2018 +0100

    Support installing android APKs from local ABI-specific build folders

**Comment by BNieuwenhuizen** [comment]
After some talking with baldurk, looks like it works if you install spirv-cross.

So I suppose the main issue here is that there is no indication in the GUI that you can fix this by doing that.

**Comment by baldurk** [comment]
Forgot to close this when the improved shader editing/tools integration was committed. It's now more clear than it was that the default renderdoc disassembly is *not* compilable GLSL, and it also tracks the language inputs/outputs of tools to determine what compilers to use of those available.
