### ISSUE TITLE
Launch Android app with arguments

### ISSUE THREAD

**Issue by justuswang** [baldurk/renderdoc#987]
## Description

Is "Command-line Arguments" supported when launching an Android application from RenderDoc GUI "Launch Application" tab?

I have tried to specify command-line arguments for an APK to launch but seems those arguments do not take any effect.

e.g. I want to launch vkreplay to replay a trace file and analyze it in RenderDoc, how can I do it?

The adb command I was using to launch the vkreplay APK is:

`adb shell am start -a android.intent.action.MAIN -c android-intent.category.LAUNCH -n com.example.vkreplay/android.app.NativeActivity --es args '"-o /sdcard/test.vktrace"'
`

The command-line arguments are "-o /sdcard/test.vktrace" for application "com.example.vkreplay".

## Environment

* RenderDoc build:  v1.0
* Operating System: Windows 10 (host), Android 8.1 (target)
* API: Vulkan

**Comment by baldurk** [comment]
This seems like it would be straightforward to implement, but I don't know if there is something subtly broken or complicated with arguments on Android - tagging @cnorthrop or @michaelrgb to clarify if this is feasible.

**Comment by cnorthrop** [comment]
It is straightforward, just needs to be hooked up.  Only complication is that you must extract the strings through JNI to use in C++.

The args are passed as a string to the activity manager using an intent argument:
https://developer.android.com/studio/command-line/adb#IntentSpec

Here's a pointer to how vkreplay parses arguments, which I believe RenderDoc could refer to directly:
https://github.com/LunarG/VulkanTools/blob/master/vktrace/vktrace_replay/vkreplay_main.cpp#L624

**Comment by baldurk** [comment]
I'm a little unsure what you mean - we already have code in `renderdoccmd_android.cpp` for fetching arguments, but here we're talking about launching the apk itself so it would be up to the apk to parse/extract the args right?

Anyway, to clarify if the contents of the command line entry are (if not empty) appended to the adb command like: `--es args '"%s"'` would that do the trick? Are both quotes necessary, and how much escaping needs to happen?

**Comment by cnorthrop** [comment]
Ah, yes, RenderDoc doesn't need to parse them, just needs to pass them through.

I think the ugly bit would be determining the name of the string being passed in.  I don't believe it is standardized, although we've used `args` in a few projects.  I think users would need to provide everything after the --es argument through the UI and RenderDoc would provide it verbatim, i.e.:
`args '"-o /sdcard/test.vktrace"'`

I don't think the single quotes are required, double quotes should work.  But if you use the above approach, it is up to the user.

**Comment by cnorthrop** [comment]
And there are actually a number of flags that could be passed in, not just strings.  So you might expand the UI a bit and call it "Intent Arguments", then the user can specify any number of them.  vkreplay would then specify the following to RenderDoc:
`--es args '"-o /sdcard/test.vktrace"'`

**Comment by baldurk** [comment]
Oh I see, so the `args` part is app-specific not just part of the parameter setup? That's annoying.

Asking the user to manually specify the name and quote the parameter isn't terrible, but isn't ideal either - it's not very clear what they're specifying and if someone doesn't specify it correctly then they could break the launching process entirely.

Appending the full text and allowing arbitrary parameters is even more of a leaky abstraction. It's not a security risk exactly but it's definitely giving users the ability to shoot themselves in the foot.

**Comment by justuswang** [comment]
"Intent Arguments" sounds better to me which may work for more applications other than vkreplay.  vkreplay only uses `--es` but other applications may use `--ei` for integer value, `--ez` for boolean value, etc.

**Comment by baldurk** [comment]
Testing with `adb` it seems like it's almost impossible to pass bad arguments and actually break something. From my limited experiments at least any incorrect/invalid/unrecognised arguments just silently fail, which is pretty awful behaviour though not unusual for Android.

As long as this is something Android users are expected to understand then it's probably fine to rename "Command-line Arguments" to "Intent Arguments" when an android host is selected and pass it through unmodified to the `adb` command.

**Comment by baldurk** [comment]
The above commit should do as described earlier, pass the 'intent arguments' directly through to adb.

I won't close this just yet until you've tested it - I have nothing that I'm aware of which uses these arguments so I can't test if it's working. When you get a chance, can you see if it now works as expected?

**Comment by justuswang** [comment]
Unfortunately this does not work for vkreplay.  I have found following adb command in the log:

`adb shell am start -S -D com.example.vkreplay/android.app.NativeActivity --es args '"-v full -o /sdcard/test.vktrace"'`

which is not able to have "--es args" work.

I have tried with following command and it works:

`adb shell am start -S -n com.example.vkreplay/android.app.NativeActivity --es args '"-v full -o /sdcard/test.vktrace"'`

Maybe "-n" is needed to create an explicit intent to make it work? e.g.

`adb shell am start -S -D -n com.example.vkreplay/android.app.NativeActivity --es args '"-v full -o /sdcard/test.vktrace"'`

**Comment by baldurk** [comment]
Ping @cnorthrop again. The docs don't really say what `-n` does, it talks about a component and then gives an example of an activity, which we are able to specify without `-n` present anyway...

Also is this something that will break on some versions of android, or on some devices on the same version of android? Since many adb commands seem to vary inconsistently.

**Comment by cnorthrop** [comment]
Okay, took a look at this finally.

The documentation (inelegantly) says -n (specifying the [component name](https://developer.android.com/guide/components/fundamentals#Components)) is required for explicit intents, which is what we are passing.

Looking at Android source, the extra arguments are not added if the intent isn't explicitly specified.

That's true for:
Android-M: [--es](https://android.googlesource.com/platform/frameworks/base/+/marshmallow-release/cmds/am/src/com/android/commands/am/Am.java#479), [-n](https://android.googlesource.com/platform/frameworks/base/+/marshmallow-release/cmds/am/src/com/android/commands/am/Am.java#614)
Android-N: [--es](https://android.googlesource.com/platform/frameworks/base/+/nougat-release/core/java/android/content/Intent.java#5431), [-n](https://android.googlesource.com/platform/frameworks/base/+/nougat-release/core/java/android/content/Intent.java#5601)
Android-O: [--es](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/core/java/android/content/Intent.java#6250), [-n](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/core/java/android/content/Intent.java#6420)

And will be true for Android-P.  It is also covered by CTS, so all vendors should support it.

So yes, we should be specifying -n if the arguments are provided.

**Comment by baldurk** [comment]
OK, I've added `-n` in that commit - let me know how that works now.

**Comment by justuswang** [comment]
It works well on my Android!
