### ISSUE TITLE
Windows 10 GUI shifts up and down a few times a second after error in capture

### ISSUE THREAD

**Issue by loosche** [baldurk/renderdoc#988]
## Description

After I take a capture that has an error in it I get a warning icon at the bottom of the GUI (Red circle with a white line inside). This area grows and shrinks in size along with the rest of the GUI until I click on it. 

This may be due to the fact that I'm running on a 4k monitor in Win10 with 150% scaling enabled.

## Repro steps

1. Open the GUI
2. Choose an executable to launch
3. Launch the executable
4. Take a capture using the Print Screen key (one that you know will have an error in it)
5. Once the capture is complete the icon shows up at the bottom of the GUI indicating there was an error with the capture
6. The bottom end of the GUI moves up and down until the users double clicks on the icon (which opens the Errors and Warning window)

## Environment

RenderDoc v1.0 (built from 5ef2d0bb)
Windows 10 Enterprise
API: D3D11
4k Monitor
150% scaling via Windows Display Settings
GPU: NVidia GeForce GTX 1080 (Driver 388.31)

**Comment by baldurk** [comment]
Yep, this is because the flicking on/off icon wasn't set up for DPI properly - it has been fixed since in 8de1bcce90df1c559aca3ff535f18aa719a3e72b. If you run with any recent nightly build it should work fine.
