### ISSUE TITLE
QRenderDoc GUI won't show - possible anti-virus interference

### ISSUE THREAD

**Issue by jeweg** [baldurk/renderdoc#994]
## Description

I never get to see a window when starting qrenderdoc.exe. A process runs, and when I try "bring to front" with SysInternals ProcessExplorer I get "no visible windows". 

Also, when I use renderdoccmd.exe to launch and capture a simple Qml + OpenGL app, it gets stuck at "launching" but then I likewise never see anything, my app isn't even started.
I've used RenderDoc before, but on this machine (Alienware 17 R4) I cannot ever get it to do anything.

## Environment

* RenderDoc build: 1.0
* Operating System: Windows 10
* API: OpenGL
* Alienware 17 R4 w/ Nvidia GTX 1080

**Comment by baldurk** [comment]
Can you post the RenderDoc log file? It will be found in `%TEMP%/RenderDoc` and might show some errors.

Does this happen if you run a nightly build? It would also be helpful if you can clone and build renderdoc locally to see if a debugger shows any problems.

**Comment by jeweg** [comment]
The log contains just "RDOC 015580: [09:09:45]             core.cpp( 298) - Log     - RenderDoc v1.0 64-bit Release (5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c) loaded in replay application". The process is running, but no window (no virtual desktop shenenigans going on either). 
However...

* The current nightly (RenderDoc_2018_05_24_7fe45cee_64) works fine
* Compiling master head from source: works fine in Develop and Release
* Compiling the 1.0 tag: works fine as well

So armed with these successes, I reinstalled the 1.0 release, but.. still the same, no GUI.
Ah well.. seeing as the other options above work and noone else seems to have that problem we may as well leave it at that.
Thanks!

**Comment by baldurk** [comment]
Yes unfortunately I have no idea what could be causing this, especially over a restart :disappointed:.

If you're willing to try one more thing, can you attach to the installed 1.0 build with visual studio and see what the callstack is, how far it's gotten in initialisation? You can get the symbols if you add https://renderdoc.org/symbols as a [symbol server](https://github.com/baldurk/renderdoc/wiki/Symbol-Server).

Also out of curiosity just to diagnose - what if you run the installed qrenderdoc.exe as administrator, since the main difference between the installed version and all of your builds is that it's running from Program Files.

**Comment by jeweg** [comment]
Attaching to the running process w/ VS2015 gives me an error "failed to attach: timeout while attaching". VS2017 attaches, but break all doesn't do anything. I don't know how common that problem is, I haven't used debugger attaching much before.

Starting the installed .exe in VS and breaking into the debugger does work, however. I've tried a couple of times to break it at different points in time and always get this (pointed it to the 1.0-tagged sources):
![image](https://user-images.githubusercontent.com/1565943/40540572-e70c994c-6018-11e8-9e12-ae5d22599585.png)

Running qrenderdoc.exe as admin doesn't make any difference, by the way.

**Comment by baldurk** [comment]
Interesting - has the renderdoccmd process launched successfully in that code snippet where you are? It looks like `CreateProcess` is blocking forever - it would be very useful to see exactly what the callstack under that `[External Code]` is.

This might also explain why you had trouble running renderdoccmd directly. Do you have any anti-virus active? Could you temporarily disable it?

**Comment by jeweg** [comment]
Ah, there's a problem: yes, renderdoccmd.exe has started, but process explorer shows is as Suspended.

Yes, this is a company laptop with McAfee installed and unfortunately it's so locked down, I cannot disable it or add any exceptions. I don't see any messages or Windows events about it suspending a process, but it wouldn't surprise me if that was the cause of the problem. I don't see how it works in all the other ways I started it, but there's quite some code that is only compiled into official renderdoc builds, could that be the difference?

**Comment by baldurk** [comment]
Yes the crash handler for example is only compiled into official stable builds (for obvious reasons). That's the biggest difference, but it also means breakpad and an exception handler is enabled which might trigger something. It could be something completely random that happens to flag up in the anti-virus, those programs are not generally known for being very accurate.

It's not proof that the virus scanner is causing problems but at this point it does seem to be the most likely suspect - especially if you've found renderdoc working for you on other machines. I'm not familiar with McAfee to know if there's a way to get any more info from it to know either way, but unless you beleive it could be some other problem I don't think I can do much but close this issue.

**Comment by jeweg** [comment]
Go ahead and close it, and thanks for taking the time anyway. Not the first time McAfee looks like the culprit for weird things, and I'll it to my case against it. Maybe they'll at least allow adding exceptions to its rules one day, one can only hope :)
