### ISSUE TITLE
Cannot launch DX12 app when root signature is specified in the shader

### ISSUE THREAD

**Issue by SakibSaikia** [baldurk/renderdoc#997]
## Description
After making some changes to my DX12 sample project, I noticed that I could no longer launch it via Renderdoc to get a capture. 

![image](https://user-images.githubusercontent.com/8186559/40592116-34d05f8e-61d0-11e8-82fe-e8e36803575b.png)

It simply says "not presenting" and then exits the app. However, I don't have any issues when the app is launched outside of renderdoc.

I went through my commits to see when this started happening, and noticed that one of my changes [3b6ed63] in which I moved the root signature specification inside the shader caused this to break. 

I might be doing something wrong, but I just wanted to make sure whether this is supported by renderdoc.

The project is here : https://github.com/SakibSaikia/D3D12SampleFramework

I am using VS 2017 to build. Working directory is the 'Src' folder.

## Repro steps
1. Set working directory to the 'Src' folder
2. Launch the app via renderdoc
3. Notice that it says 'not presenting'

## Environment

* RenderDoc build: v1.0
* Operating System: Windows 10
* API: D3D12

**Comment by baldurk** [comment]
It seems there's an undocumented ability to set `pRootSignature` to `NULL` when creating a pipeline as long as one of the shaders contains an embedded RS blob - updated the code to handle that.

**Comment by SakibSaikia** [comment]
Awesome, thanks! I'll check it out once the latest nightly picks it up.
